export type Pair=[string,string];
export type DialogueLine=["P"|"V",string,string];
export type Scenario={emoji:string;title:string;english:string;context:Pair;dialogue:DialogueLine[];prompts:Pair[];resources:Pair[]};

export const scenarios:Scenario[]=[
  {emoji:"👋",title:"Saludos",english:"Greetings",context:["Llegás a la casa de una amistad.","You arrive at an Argentine friend’s home."],dialogue:[
    ["P","Che, ¡pasá! ¿Todo bien?","Hey, come in! All good?"],["V","Todo bien, ¿vos?","All good, and you?"],["P","Re bien. Dejé unas birras y gaseosa en la mesa.","Really good. I left some beers and soda on the table."],["V","Dale, gracias. Qué lindo el departamento.","Sure, thanks. What a nice apartment."],["P","Gracias, che. ¿Querés comer algo?","Thanks, mate. Do you want something to eat?"],["V","Sí, obvio. Tengo un poco de hambre.","Yes, of course. I’m a little hungry."],["P","Hay pizza. Está buenísima.","There’s pizza. It’s awesome."],["V","Buenísimo. La pizza me gusta mucho.","Awesome. I like pizza a lot."],["P","¿Es tu primera vez en este barrio?","Is this your first time in this neighbourhood?"],["V","Sí. No conozco mucho, pero me gusta.","Yes. I don’t know it well, but I like it."],["P","Después podemos caminar un poco.","Later we can walk around a little."],["V","Dale, me encanta la idea.","Sure, I love the idea."],["P","Joya. Primero comemos y después salimos.","Perfect. First we eat and then we go out."],["V","De una. Gracias por invitarme.","Definitely. Thanks for inviting me."]],prompts:[["Che, llegaste. ¿Todo tranqui?","Hey, you made it. Everything chill?"],["¿Querés una birra o una gaseosa?","Do you want a beer or soda?"],["¿Te gusta el departamento?","Do you like the apartment?"],["¿Es tu primera vez en el barrio?","Is this your first time in the neighbourhood?"],["¿Comés pizza?","Do you eat pizza?"],["¿Querés salir a caminar después?","Do you want to go for a walk later?"]],resources:[["Todo bien.","All good."],["Sí, tranqui.","Yeah, chill."],["Quiero…","I want…"],["Está re lindo.","It’s really nice."],["Tengo hambre.","I’m hungry."],["No conozco mucho.","I don’t know it well."],["Dale, obvio.","Sure, of course."],["Gracias por invitarme.","Thanks for inviting me."]]},
  {emoji:"🏪",title:"Kiosco",english:"Kiosk",context:["Entrás a un kiosco de barrio.","You enter a neighbourhood kiosk."],dialogue:[
    ["P","Hola, che. ¿Qué querés?","Hi, mate. What do you want?"],["V","Dame un alfajor y una gaseosa, por favor.","Give me an alfajor and a soda, please."],["P","Dale. ¿Coca o naranja?","Sure. Coke or orange?"],["V","Coca, por favor.","Coke, please."],["P","Son cuatro mil pesos.","It’s four thousand pesos."],["V","Dale. ¿Puedo pagar con tarjeta?","Okay. Can I pay by card?"],["P","Sí, de una.","Yes, absolutely."],["V","Joya. Nada más, gracias.","Perfect. Nothing else, thanks."],["P","Pará, ¿querés bolsa?","Wait, do you want a bag?"],["V","No, gracias. Lo llevo en la mochila.","No, thanks. I’ll carry it in my backpack."],["P","Listo. Acá tenés el ticket.","All set. Here is your receipt."],["V","Gracias. ¿A qué hora cerrás?","Thanks. What time do you close?"],["P","Hoy cierro a las diez.","Today I close at ten."],["V","Buenísimo. Nos vemos.","Great. See you."]],prompts:[["Buenas, ¿qué te doy?","Hi, what can I get you?"],["¿Querés algo para tomar?","Do you want something to drink?"],["Son tres mil. ¿Efectivo o tarjeta?","It’s three thousand. Cash or card?"],["¿Querés bolsa?","Do you want a bag?"],["¿Algo más?","Anything else?"],["¿Necesitás el ticket?","Do you need the receipt?"]],resources:[["Dame…","Give me…"],["Quiero…","I want…"],["un alfajor","an alfajor"],["una gaseosa","a soda"],["agua","water"],["con tarjeta","by card"],["en efectivo","in cash"],["Nada más.","Nothing else."],["No necesito bolsa.","I don’t need a bag."],["¿A qué hora cerrás?","What time do you close?"]]},
  {emoji:"☕",title:"Café porteño",english:"Buenos Aires café",context:["Pedís algo en un café clásico.","You order at a classic café."],dialogue:[
    ["P","Buenas. ¿Qué vas a tomar?","Hi. What are you going to drink?"],["V","Para mí, un café con leche.","For me, a coffee with milk."],["P","Dale. ¿Grande o chico?","Okay. Large or small?"],["V","Grande, por favor. Y dos medialunas.","Large, please. And two croissants."],["P","Joya. ¿Azúcar?","Perfect. Sugar?"],["V","Sí, un poco de azúcar.","Yes, a little sugar."],["P","Acá tenés. ¿Todo bien?","Here you go. Everything okay?"],["V","Sí, buenísimo. La cuenta, por favor.","Yes, awesome. The bill, please."],["P","¿Pagás ahora o después?","Are you paying now or later?"],["V","Ahora, por favor.","Now, please."],["P","Son ocho mil quinientos.","It’s eight thousand five hundred."],["V","¿Puedo pagar con el celular?","Can I pay with my phone?"],["P","Sí, acercalo acá.","Yes, hold it near here."],["V","Listo. Muchas gracias.","Done. Thank you very much."]],prompts:[["Hola, ¿qué querés tomar?","Hi, what do you want to drink?"],["¿Café con leche o café negro?","Coffee with milk or black coffee?"],["¿Grande o chico?","Large or small?"],["¿Querés medialunas también?","Do you want croissants too?"],["¿Algo más para la mesa?","Anything else for the table?"],["¿Pagás ahora o después?","Are you paying now or later?"]],resources:[["Para mí…","For me…"],["Quiero…","I want…"],["café con leche","coffee with milk"],["una medialuna","a croissant"],["grande","large"],["chico","small"],["sin azúcar","without sugar"],["La cuenta, por favor.","The bill, please."],["Pago ahora.","I’ll pay now."],["Dale.","Sure."]]},
  {emoji:"🥩",title:"Asado",english:"Argentine BBQ",context:["Te invitan a un asado.","You are invited to an Argentine barbecue."],dialogue:[
    ["P","Che, ¿comés carne?","Hey, do you eat meat?"],["V","Sí, como carne. Quiero un poco.","Yes, I eat meat. I want a little."],["P","Dale. ¿Chori también?","Sure. Chorizo sandwich too?"],["V","Sí, de una. Y ensalada, por favor.","Yes, definitely. And salad, please."],["P","Ojo, la salsa es picante.","Heads up, the sauce is spicy."],["V","Tranqui, me gusta picante.","No worries, I like spicy food."],["P","¿Querés birra?","Do you want beer?"],["V","Sí, gracias. Está re rico el morfi.","Yes, thanks. The food is really delicious."],["P","¿Probaste la provoleta?","Did you try the grilled provolone?"],["V","No. ¿Qué es?","No. What is it?"],["P","Es queso caliente. Probá un poco.","It’s hot cheese. Try a little."],["V","Mmm, está buenísima.","Mmm, it’s awesome."],["P","Después hay helado de postre.","There’s ice cream for dessert later."],["V","Genial. Pero primero quiero más carne.","Great. But first I want more meat."]],prompts:[["¿Querés chori o carne?","Do you want chorizo sandwich or meat?"],["¿Comés ensalada?","Do you eat salad?"],["Ojo, esto es picante.","Careful, this is spicy."],["¿Probaste la provoleta?","Did you try the grilled provolone?"],["¿Querés tomar algo?","Do you want something to drink?"],["¿Querés postre?","Do you want dessert?"]],resources:[["Quiero…","I want…"],["un poco de…","a little…"],["carne","meat"],["chori","chorizo sandwich"],["ensalada","salad"],["Quiero probar.","I want to try."],["No pasa nada.","No worries."],["Está re rico.","It’s really tasty."],["¿Qué es?","What is it?"],["Más, por favor.","More, please."]]},
  {emoji:"🧉",title:"Mate",english:"Sharing mate",context:["Probás mate con alguien.","You try mate with someone."],dialogue:[
    ["P","Che, ¿tomás mate?","Hey, do you drink mate?"],["V","Sí, un poco. Quiero probar.","Yes, a little. I want to try."],["P","Dale. ¿Amargo o dulce?","Sure. Bitter or sweet?"],["V","Dulce, por favor.","Sweet, please."],["P","Tomá, está acá.","Here, take it."],["V","Gracias. Mmm, es diferente.","Thanks. Mmm, it’s different."],["P","¿Te gusta?","Do you like it?"],["V","Sí, me gusta. Pero el café me gusta también.","Yes, I like it. But I like coffee too."],["P","No muevas la bombilla, ¿sí?","Don’t move the metal straw, okay?"],["V","Ah, bueno. No sabía.","Oh, okay. I didn’t know."],["P","Cuando terminás, me lo pasás.","When you finish, pass it back to me."],["V","Dale. ¿Siempre toman del mismo mate?","Sure. Do you always drink from the same mate?"],["P","Sí, compartir es parte del ritual.","Yes, sharing is part of the ritual."],["V","Qué copado. Dame otro después.","How cool. Give me another one later."]],prompts:[["¿Querés mate?","Do you want mate?"],["¿Amargo o dulce?","Bitter or sweet?"],["Tomá, probá un poco.","Here, try a little."],["No muevas la bombilla.","Don’t move the metal straw."],["¿Te gusta?","Do you like it?"],["¿Mate o café?","Mate or coffee?"]],resources:[["Sí, quiero.","Yes, I want it."],["No, gracias.","No, thanks."],["amargo","bitter"],["dulce","sweet"],["Quiero probar.","I want to try."],["Me gusta.","I like it."],["Es diferente.","It’s different."],["No sabía.","I didn’t know."],["Te lo paso.","I’ll pass it to you."],["Otro, por favor.","Another one, please."]]},
  {emoji:"🍺",title:"Bar",english:"At a bar",context:["Tomás algo en un bar.","You have a drink at a bar."],dialogue:[
    ["P","Este bar está re copado, ¿no?","This bar is really cool, right?"],["V","Sí, posta. Me gusta mucho.","Yes, for real. I like it a lot."],["P","¿Qué querés tomar?","What do you want to drink?"],["V","Una birra, por favor.","A beer, please."],["P","Dale. ¿Querés papas también?","Sure. Do you want fries too?"],["V","Sí, de una.","Yes, definitely."],["P","Podemos volver otro día.","We can come back another day."],["V","Buenísimo, me sirve.","Awesome, works for me."],["P","¿Preferís sentarte adentro o afuera?","Do you prefer to sit inside or outside?"],["V","Afuera. Hay menos ruido.","Outside. There is less noise."],["P","Dale. Yo pido en la barra.","Okay. I’ll order at the bar."],["V","Perfecto. Yo busco una mesa.","Perfect. I’ll find a table."],["P","Después pedimos otra ronda.","Later we’ll order another round."],["V","Capaz. Primero tomo esta.","Maybe. First I’ll drink this one."]],prompts:[["Che, ¿te gusta este lugar?","Hey, do you like this place?"],["¿Birra, vino o gaseosa?","Beer, wine, or soda?"],["¿Adentro o afuera?","Inside or outside?"],["¿Querés pedir algo para comer?","Do you want to order something to eat?"],["¿Pedimos otra ronda?","Shall we order another round?"],["¿Volvemos la semana que viene?","Shall we come back next week?"]],resources:[["Me gusta.","I like it."],["Está re copado.","It’s really cool."],["Quiero…","I want…"],["una birra","a beer"],["una gaseosa","a soda"],["papas","fries"],["Afuera, por favor.","Outside, please."],["De una.","Definitely."],["Capaz.","Maybe."],["Me sirve.","Works for me."]]},
  {emoji:"🚌",title:"Bondi y subte",english:"Bus & subway",context:["Te movés por Buenos Aires.","You get around Buenos Aires."],dialogue:[
    ["P","Che, ¿a dónde vas?","Hey, where are you going?"],["V","Voy a Palermo.","I’m going to Palermo."],["P","Podés tomar el subte.","You can take the subway."],["V","¿El subte queda acá?","Is the subway here?"],["P","Sí, a dos cuadras. Bajás en Plaza Italia.","Yes, two blocks away. Get off at Plaza Italia."],["V","¿Está lejos?","Is it far?"],["P","No, llegás al toque.","No, you get there quickly."],["V","Joya, gracias.","Perfect, thanks."],["P","Necesitás la tarjeta SUBE.","You need a SUBE card."],["V","Tengo una. ¿Dónde cargo plata?","I have one. Where do I add money?"],["P","En el kiosco de la esquina.","At the kiosk on the corner."],["V","Buenísimo. ¿Y después qué línea tomo?","Great. And then which line do I take?"],["P","La línea D, dirección Congreso de Tucumán.","Line D, towards Congreso de Tucumán."],["V","Perfecto. Ahora entiendo.","Perfect. Now I understand."]],prompts:[["¿A dónde querés ir?","Where do you want to go?"],["¿Preferís bondi o subte?","Do you prefer bus or subway?"],["¿Tenés tarjeta SUBE?","Do you have a SUBE card?"],["Bajás en la próxima parada.","You get off at the next stop."],["¿Sabés qué línea tomar?","Do you know which line to take?"],["¿Todo claro?","All clear?"]],resources:[["Voy a…","I’m going to…"],["Quiero ir a…","I want to go to…"],["bondi","bus"],["subte","subway"],["tarjeta SUBE","SUBE travel card"],["¿Está lejos?","Is it far?"],["¿Dónde bajo?","Where do I get off?"],["¿Qué línea tomo?","Which line do I take?"],["Otra vez, por favor.","Again, please."],["Joya, gracias.","Perfect, thanks."]]},
  {emoji:"📅",title:"Hacer planes",english:"Making plans",context:["Organizás una salida.","You organise an outing."],dialogue:[
    ["P","Che, ¿querés salir el sábado?","Hey, do you want to go out Saturday?"],["V","Dale, de una.","Sure, definitely."],["P","¿Tipo nueve te sirve?","Does around nine work for you?"],["V","Sí, nueve me sirve.","Yes, nine works for me."],["P","Podemos ir a un restaurante.","We can go to a restaurant."],["V","Buenísimo. ¿Dónde?","Awesome. Where?"],["P","En Palermo. Nos vemos allá.","In Palermo. See you there."],["V","Joya, nos vemos.","Perfect, see you."],["P","¿Querés comida argentina o italiana?","Do you want Argentine or Italian food?"],["V","Argentina. Quiero probar empanadas.","Argentine. I want to try empanadas."],["P","Conozco un lugar cerca de Plaza Serrano.","I know a place near Plaza Serrano."],["V","Dale. ¿Reservamos una mesa?","Okay. Shall we book a table?"],["P","Sí, yo llamo hoy.","Yes, I’ll call today."],["V","Perfecto. Mandame la dirección.","Perfect. Send me the address."]],prompts:[["¿Estás libre el viernes?","Are you free Friday?"],["¿A qué hora te sirve?","What time works for you?"],["¿Bar o restaurante?","Bar or restaurant?"],["¿Qué comida preferís?","What food do you prefer?"],["¿Reservamos una mesa?","Shall we book a table?"],["¿Nos vemos allá?","Shall we meet there?"]],resources:[["Sí, estoy libre.","Yes, I’m free."],["Capaz.","Maybe."],["No puedo.","I can’t."],["Me sirve.","Works for me."],["tipo ocho","around eight"],["bar","bar"],["restaurante","restaurant"],["Prefiero…","I prefer…"],["Mandame la dirección.","Send me the address."],["Nos vemos.","See you."]]},
  {emoji:"🎉",title:"Previa y juntada",english:"Pre-party & hangout",context:["Te invitan a una juntada.","You are invited to a hangout."],dialogue:[
    ["P","Che, hoy hay juntada en casa.","Hey, there’s a hangout at my place today."],["V","Qué copado. ¿A qué hora?","How cool. What time?"],["P","Caé tipo nueve. Tranqui.","Come around nine. Chill."],["V","Dale. ¿Llevo algo?","Okay. Should I bring something?"],["P","Sí, una birra o una gaseosa.","Yes, a beer or soda."],["V","De una. ¿Hay mucha gente?","Definitely. Are there many people?"],["P","Sí, una banda.","Yes, tons."],["V","Buenísimo. Nos vemos ahí.","Awesome. See you there."],["P","Si querés, vení con alguien.","If you want, come with someone."],["V","Dale. Capaz viene mi amiga Sara.","Okay. Maybe my friend Sara will come."],["P","Joya. Después vamos a otro lugar.","Perfect. Later we’re going somewhere else."],["V","¿Lejos de tu casa?","Far from your house?"],["P","No, queda a cinco cuadras.","No, it’s five blocks away."],["V","Buenísimo. Entonces llevo algo para tomar.","Great. Then I’ll bring something to drink."]],prompts:[["¿Querés venir a la juntada?","Do you want to come to the hangout?"],["Caé tipo ocho, ¿dale?","Come around eight, okay?"],["¿Podés traer algo para tomar?","Can you bring something to drink?"],["¿Querés venir con alguien?","Do you want to come with someone?"],["Después hay previa.","There are pre-drinks afterwards."],["¿Queda lejos?","Is it far?"]],resources:[["Quiero ir.","I want to go."],["Dale.","Sure."],["¿A qué hora?","What time?"],["Llevo…","I’ll bring…"],["una birra","a beer"],["algo para comer","something to eat"],["Capaz viene…","Maybe … will come."],["¿Queda lejos?","Is it far?"],["Tranqui.","Chill."],["De una.","Definitely."]]},
  {emoji:"🛍️",title:"Feria y compras",english:"Market & shopping",context:["Comprás algo en una feria.","You buy something at a market."],dialogue:[
    ["P","Hola, che. ¿Buscás algo?","Hi, mate. Are you looking for something?"],["V","Sí, busco una remera.","Yes, I’m looking for a T-shirt."],["P","Esta está re copada.","This one is really cool."],["V","Sí, me gusta. ¿Cuánto sale?","Yes, I like it. How much is it?"],["P","Veinte mil pesos.","Twenty thousand pesos."],["V","Es un poco caro.","It’s a little expensive."],["P","Te la dejo a dieciocho.","I’ll leave it at eighteen for you."],["V","Joya, me la llevo.","Perfect, I’ll take it."],["P","¿Qué talle necesitás?","What size do you need?"],["V","Mediano. ¿Me la puedo probar?","Medium. Can I try it on?"],["P","Sí, el probador está allá.","Yes, the fitting room is over there."],["V","Me queda bien, pero prefiero otro color.","It fits me well, but I prefer another colour."],["P","También tengo azul y negro.","I also have blue and black."],["V","Entonces me llevo la negra.","Then I’ll take the black one."]],prompts:[["¿Qué buscás?","What are you looking for?"],["¿Qué talle necesitás?","What size do you need?"],["¿Te gusta esta remera?","Do you like this T-shirt?"],["Sale quince mil pesos.","It costs fifteen thousand pesos."],["¿Te la querés probar?","Do you want to try it on?"],["¿Te la llevás?","Will you take it?"]],resources:[["Busco…","I’m looking for…"],["una remera","a T-shirt"],["talle mediano","medium size"],["Me gusta.","I like it."],["¿Cuánto sale?","How much is it?"],["Es re caro.","It’s really expensive."],["¿Me la puedo probar?","Can I try it on?"],["Prefiero otro color.","I prefer another colour."],["Me la llevo.","I’ll take it."],["No, gracias.","No, thanks."]]},
  {emoji:"⚽",title:"Fútbol",english:"Football",context:["Mirás un partido con amistades.","You watch a match with friends."],dialogue:[
    ["P","Che, ¿te gusta el fútbol?","Hey, do you like football?"],["V","Sí, un poco.","Yes, a little."],["P","Hoy juega Argentina.","Argentina plays today."],["V","Buenísimo. ¿Argentina gana?","Awesome. Will Argentina win?"],["P","Obvio. Va a ser un golazo.","Of course. It’s going to be an amazing goal."],["V","Mal, qué partido.","Totally, what a match."],["P","¡Gol! ¡Vamos!","Goal! Let’s go!"],["V","¡Vamos Argentina!","Let’s go Argentina!"],["P","¿Viste quién hizo el gol?","Did you see who scored?"],["V","No. Todo pasó muy rápido.","No. Everything happened very fast."],["P","Fue el número diez.","It was number ten."],["V","Qué jugador. Es muy bueno.","What a player. He’s very good."],["P","Faltan veinte minutos todavía.","There are still twenty minutes left."],["V","Estoy nervioso. Necesitamos otro gol.","I’m nervous. We need another goal."]],prompts:[["¿Te gusta el fútbol?","Do you like football?"],["Hoy juega Argentina.","Argentina plays today."],["¿Quién gana?","Who wins?"],["¡Gol! ¿Qué decís?","Goal! What do you say?"],["¿Quién hizo el gol?","Who scored the goal?"],["¿Estás nervioso?","Are you nervous?"]],resources:[["Sí, me gusta.","Yes, I like it."],["Un poco.","A little."],["No sé.","I don’t know."],["Obvio.","Of course."],["Capaz.","Maybe."],["¡Vamos!","Let’s go!"],["Golazo.","Amazing goal."],["Qué partido.","What a match."],["Estoy nervioso.","I’m nervous."],["Necesitamos otro gol.","We need another goal."]]},
  {emoji:"💼",title:"Laburo",english:"Work",context:["Charlás con alguien del trabajo.","You chat with a coworker."],dialogue:[
    ["P","Che, ¿cómo está el laburo?","Hey, how’s work?"],["V","Bien, pero tengo una banda de trabajo.","Good, but I have tons of work."],["P","Qué bajón. ¿Laburás desde casa?","That sucks. Do you work from home?"],["V","Sí, hoy laburo desde casa.","Yes, today I work from home."],["P","¿Tomamos un café?","Shall we have coffee?"],["V","Dale, necesito un café.","Sure, I need a coffee."],["P","Mañana está más tranqui.","Tomorrow is more chill."],["V","Buenísimo, gracias.","Awesome, thanks."],["P","¿Tenés una reunión ahora?","Do you have a meeting now?"],["V","Sí, a las tres con mi jefe.","Yes, at three with my boss."],["P","¿Necesitás ayuda con algo?","Do you need help with anything?"],["V","Sí, con este informe, por favor.","Yes, with this report, please."],["P","Dale. Lo miramos después del café.","Sure. We’ll look at it after coffee."],["V","Joya. Me salvás.","Perfect. You’re saving me."]],prompts:[["¿Mucho laburo hoy?","Lots of work today?"],["¿Laburás desde casa?","Do you work from home?"],["¿Tenés una reunión?","Do you have a meeting?"],["¿Querés un café?","Do you want a coffee?"],["¿Necesitás ayuda?","Do you need help?"],["¿Mañana estás libre?","Are you free tomorrow?"]],resources:[["Tengo…","I have…"],["una banda de trabajo","tons of work"],["Estoy tranqui.","I’m chill."],["Laburo desde casa.","I work from home."],["Tengo una reunión.","I have a meeting."],["Necesito ayuda.","I need help."],["Quiero café.","I want coffee."],["Qué bajón.","That sucks."],["Dale.","Sure."],["Mañana…","Tomorrow…"]]},
  {emoji:"❤️",title:"Cita",english:"Casual date",context:["Tomás un café o algo con alguien.","You have coffee or drinks with someone."],dialogue:[
    ["P","Este lugar es re lindo.","This place is really nice."],["V","Sí, tiene buena onda.","Yes, it has a good vibe."],["P","¿Qué querés tomar?","What do you want to drink?"],["V","Un café, por favor.","A coffee, please."],["P","¿Qué hacés los fines de semana?","What do you do on weekends?"],["V","Me gusta caminar y tomar café.","I like walking and drinking coffee."],["P","Posta, a mí también.","Really, me too."],["V","Podemos venir otra vez.","We can come again."],["P","¿Vivís cerca de acá?","Do you live near here?"],["V","No, vivo en otro barrio.","No, I live in another neighbourhood."],["P","¿Cómo viniste?","How did you get here?"],["V","En subte. Fue fácil.","By subway. It was easy."],["P","La próxima podemos ir a cenar.","Next time we can go for dinner."],["V","Sí, me encantaría.","Yes, I’d love to."]],prompts:[["¿Te gusta este café?","Do you like this café?"],["¿Café o birra?","Coffee or beer?"],["¿Qué hacés el fin de semana?","What do you do on the weekend?"],["¿Vivís cerca?","Do you live nearby?"],["¿Cómo viniste?","How did you get here?"],["¿Nos vemos otra vez?","Shall we see each other again?"]],resources:[["Está re lindo.","It’s really nice."],["Tiene buena onda.","It has a good vibe."],["Prefiero…","I prefer…"],["Me gusta…","I like…"],["Vivo en…","I live in…"],["Vine en subte.","I came by subway."],["La próxima…","Next time…"],["De una.","Definitely."],["Sí, me encantaría.","Yes, I’d love to."],["Capaz.","Maybe."]]},
  {emoji:"🚕",title:"Taxi / Uber",english:"Taxi / Uber",context:["Viajás en auto con un conductor.","You ride in a car with a driver."],dialogue:[
    ["P","Buenas. ¿A dónde vas?","Hi. Where are you going?"],["V","Voy a Palermo, por favor.","I’m going to Palermo, please."],["P","Dale. Hay un quilombo de tráfico.","Okay. There’s a traffic mess."],["V","Qué bajón. Tengo un poco de apuro.","That sucks. I’m in a bit of a hurry."],["P","Tranqui, vamos por otra calle.","No worries, we’ll take another street."],["V","Joya, gracias.","Perfect, thanks."],["P","¿Te bajo acá?","Should I let you out here?"],["V","Sí, acá está bien.","Yes, here is fine."],["P","¿Es este edificio?","Is it this building?"],["V","No, es el próximo, a la derecha.","No, it’s the next one, on the right."],["P","Perfecto. Llegamos en cinco minutos.","Perfect. We’ll arrive in five minutes."],["V","Buenísimo. ¿Puedo pagar con tarjeta?","Great. Can I pay by card?"],["P","Sí, no hay problema.","Yes, no problem."],["V","Listo. Muchas gracias por la ayuda.","Done. Thank you very much for the help."]],prompts:[["¿A dónde querés ir?","Where do you want to go?"],["Hay mucho tráfico hoy.","There’s a lot of traffic today."],["¿Tenés apuro?","Are you in a hurry?"],["¿Es este edificio?","Is it this building?"],["¿Te bajo acá?","Should I let you out here?"],["¿Efectivo o tarjeta?","Cash or card?"]],resources:[["Voy a…","I’m going to…"],["Tengo apuro.","I’m in a hurry."],["Tranqui.","No worries."],["Dale.","Okay."],["por otra calle","by another street"],["el próximo edificio","the next building"],["a la derecha","on the right"],["acá está bien","here is fine"],["con tarjeta","by card"],["Gracias.","Thanks."]]},
  {emoji:"🗺️",title:"Pedir ayuda",english:"Asking for help",context:["Pedís direcciones en la calle.","You ask for directions on the street."],dialogue:[
    ["P","Che, ¿necesitás ayuda?","Hey, do you need help?"],["V","Sí, busco el subte.","Yes, I’m looking for the subway."],["P","Queda allá, a dos cuadras.","It’s over there, two blocks away."],["V","¿Voy a la derecha?","Do I go right?"],["P","Sí, derecha y después izquierda.","Yes, right and then left."],["V","¿Está lejos?","Is it far?"],["P","No, llegás al toque.","No, you’ll get there quickly."],["V","Joya, muchas gracias.","Perfect, thank you very much."],["P","Ojo: la entrada está detrás del banco.","Heads up: the entrance is behind the bank."],["V","Perdón, ¿detrás del banco?","Sorry, behind the bank?"],["P","Sí. Cruzás la calle y la vas a ver.","Yes. Cross the street and you’ll see it."],["V","¿Hay un cartel grande?","Is there a big sign?"],["P","Sí, azul y blanco.","Yes, blue and white."],["V","Perfecto. Ahora sí entiendo.","Perfect. Now I understand."]],prompts:[["¿Qué buscás?","What are you looking for?"],["Queda a dos cuadras.","It’s two blocks away."],["Vas a la derecha.","You go right."],["La entrada está detrás del banco.","The entrance is behind the bank."],["¿Hay un cartel?","Is there a sign?"],["¿Entendés?","Do you understand?"]],resources:[["Busco…","I’m looking for…"],["¿Dónde queda…?","Where is …?"],["subte","subway"],["acá","here"],["allá","over there"],["a dos cuadras","two blocks away"],["a la derecha","to the right"],["detrás de…","behind…"],["¿Otra vez?","Again?"],["Más lento, por favor.","Slower, please."],["Ahora entiendo.","Now I understand."]]},
];

export const helpGroups:{title:Pair;items:Pair[]}[]=[
  {title:["QUIERO","I WANT"],items:[["Quiero…","I want…"],["No quiero…","I don’t want…"]]},
  {title:["ME GUSTA","I LIKE"],items:[["Me gusta…","I like…"],["No me gusta…","I don’t like…"],["Prefiero…","I prefer…"]]},
  {title:["REACCIONÁ","REACT"],items:[["Dale.","Okay."],["De una.","Absolutely."],["Joya.","Perfect."],["Buenísimo.","Awesome."],["No sé.","I don’t know."],["Capaz.","Maybe."]]},
  {title:["SEGUÍ","KEEP GOING"],items:[["porque…","because…"],["pero…","but…"],["y…","and…"],["también…","also…"],["un poco","a little"],["mucho","a lot"]]},
  {title:["PEDÍ AYUDA","ASK FOR HELP"],items:[["¿Otra vez?","Again?"],["Más lento, por favor.","Slower, please."],["No entiendo.","I don’t understand."],["¿Qué significa…?","What does … mean?"],["¿Cómo se dice…?","How do you say …?"]]},
];

export const slang:Array<{term:string;meaning:string;closest:string;use:string;example:Pair;note?:string}>=[
  {term:"che",meaning:"hey / mate / dude",closest:"mate / hey",use:"Para llamar la atención de alguien de manera casual · Casual way to get someone’s attention.",example:["Che, ¿todo bien?","Hey, all good?"]},
  {term:"dale",meaning:"okay / sure / come on",closest:"sure / okay",use:"Acuerdo o aliento muy frecuente · Very common agreement or encouragement.",example:["Dale, vamos.","Sure, let’s go."]},
  {term:"posta",meaning:"really / for real",closest:"for real",use:"Para enfatizar que algo es verdad · Used to emphasise something is true.",example:["Posta, está re rico.","For real, it’s really tasty."]},
  {term:"re",meaning:"really / very / super",closest:"really / so",use:"Intensificador delante de un adjetivo · Intensifier before an adjective.",example:["Es re copado.","It’s really cool."]},
  {term:"copado",meaning:"cool / great",closest:"cool / awesome",use:"Para un plan, lugar o persona agradable · For a nice plan, place or person.",example:["El bar es copado.","The bar is cool."]},
  {term:"quilombo",meaning:"mess / chaos",closest:"a total mess",use:"Informal; puede sonar fuerte según el tono · Informal; can be strong depending on tone.",example:["Hay un quilombo de tráfico.","Traffic is a total mess."]},
  {term:"laburo / laburar",meaning:"work / to work",closest:"work / work at a job",use:"Palabra cotidiana e informal para trabajo · Casual word for work.",example:["Tengo mucho laburo.","I have lots of work."]},
  {term:"guita",meaning:"money / cash",closest:"cash",use:"Palabra muy informal para dinero · Very informal word for money.",example:["No tengo mucha guita.","I don’t have much cash."]},
  {term:"birra",meaning:"beer",closest:"beer",use:"Palabra cotidiana e informal · Casual, everyday word.",example:["Quiero una birra.","I want a beer."]},
  {term:"morfi",meaning:"food",closest:"food / grub",use:"Palabra muy informal para comida · Very informal food word.",example:["El morfi está rico.","The food is tasty."]},
  {term:"bondi",meaning:"bus",closest:"bus",use:"Palabra cotidiana de Buenos Aires · Buenos Aires everyday word.",example:["Tomo el bondi.","I take the bus."]},
  {term:"subte",meaning:"subway",closest:"subway",use:"Metro subterráneo de Buenos Aires · Buenos Aires underground metro.",example:["Voy en subte.","I go by subway."]},
  {term:"tranqui",meaning:"chill / no worries",closest:"no worries",use:"Respuesta relajada para tranquilizar · Relaxed reassurance.",example:["Tranqui, no pasa nada.","No worries, it’s fine."]},
  {term:"de una",meaning:"absolutely / definitely",closest:"definitely",use:"Un sí fuerte y entusiasta · Strong, enthusiastic yes.",example:["¿Venís? De una.","Are you coming? Definitely."]},
  {term:"ni en pedo",meaning:"no way",closest:"no freaking way",use:"Expresión fuerte e informal · Strong and informal expression.",example:["Ni en pedo voy tarde.","No freaking way I’m going late."],note:"Usala con amistades y prestá atención al tono · Use it with friends and pay attention to tone."},
  {term:"bancá / bancame",meaning:"wait / give me a second",closest:"hold on",use:"Pedido informal para esperar · Informal request to wait.",example:["Bancame un minuto.","Give me a minute."]},
  {term:"joya",meaning:"great / perfect",closest:"perfect",use:"Aprobación amistosa · Friendly approval.",example:["Joya, nos vemos.","Perfect, see you."]},
  {term:"bárbaro / buenísimo",meaning:"great / awesome",closest:"great / awesome",use:"Reacción positiva y cálida · Warm positive reaction.",example:["Buenísimo, gracias.","Awesome, thanks."]},
  {term:"mal",meaning:"totally / exactly",closest:"totally",use:"Se usa solo para estar muy de acuerdo · Often used alone to strongly agree.",example:["Mal, tenés razón.","Totally, you’re right."]},
  {term:"una banda",meaning:"a lot / tons",closest:"a ton",use:"Para una cantidad muy grande · For a very large amount.",example:["Hay una banda de gente.","There are tons of people."]},
  {term:"qué bajón",meaning:"that sucks / what a bummer",closest:"that sucks",use:"Para una noticia decepcionante · For disappointing news.",example:["Qué bajón el tráfico.","Traffic sucks."]},
  {term:"qué paja / me da paja",meaning:"what a pain / can’t be bothered",closest:"I can’t be bothered",use:"Informal y más fuerte; mejor con amistades · Informal and stronger; best with friends.",example:["Me da paja salir.","I can’t be bothered to go out."],note:"Muy informal · Very informal."},
  {term:"estar al pedo",meaning:"to have nothing to do",closest:"to be bored with nothing on",use:"Informal y puede sonar directo · Informal and can sound blunt.",example:["Estoy al pedo hoy.","I have nothing to do today."],note:"Muy informal · Very informal."},
  {term:"al toque",meaning:"right away / quickly",closest:"in a sec",use:"Para algo que sucede muy pronto · For something very soon.",example:["Llego al toque.","I’ll arrive in a sec."]},
  {term:"ya fue",meaning:"forget it / whatever",closest:"forget it",use:"Para abandonar una idea o seguir igual · Casual decision to drop an idea.",example:["Ya fue, vamos igual.","Forget it, let’s go anyway."]},
  {term:"ojo",meaning:"careful / heads up",closest:"heads up",use:"Advertencia amistosa · Friendly warning.",example:["Ojo, está caliente.","Heads up, it’s hot."]},
  {term:"zarpado / groso",meaning:"insane / awesome",closest:"wild / awesome",use:"Puede ser positivo o intenso según el contexto · Positive or intense depending on context.",example:["Ese lugar es zarpado.","That place is amazing."]},
  {term:"joda / juntada / previa",meaning:"party / hangout / pre-drinks",closest:"hangout / pregame",use:"Palabras muy frecuentes de la vida social · Common social-life words.",example:["Hay previa antes de la joda.","There are pre-drinks before the party."]},
  {term:"capaz",meaning:"maybe",closest:"maybe",use:"Forma suave y muy común de decir quizás · Soft, common way to say maybe.",example:["Capaz voy mañana.","Maybe I’ll go tomorrow."]},
  {term:"viste / tipo / onda",meaning:"you know / like / vibe",closest:"you know / like / vibe",use:"Muletillas; usalas con moderación · Conversation fillers; use lightly.",example:["Es tipo un bar, viste.","It’s like a bar, you know."]},
  {term:"no da",meaning:"not cool / not appropriate",closest:"that’s not cool",use:"Juicio informal sobre una situación · Informal judgement about a situation.",example:["Llegar tarde no da.","Being late isn’t cool."]},
  {term:"boludo",meaning:"dude / idiot",closest:"dude",use:"Depende totalmente del tono y la confianza · Very tone-dependent and informal.",example:["Boludo, qué lindo día.","Dude, what a nice day."],note:"Solo con mucha confianza; evitá usarla con desconocidos · Only with close friends; avoid with strangers."},
];
