"use client";

import {useState} from "react";
import Link from "next/link";
import type {Lesson} from "../lesson-catalog";
import AudioDeck from "../listening-studio/AudioDeck";
import {contrastTrials,finalCriteria,mouthClips,noticeTrials,phraseModels,route,targets,wordModels} from "./data";
import {initialMouthAttempt,updateMouthAttempt,type MouthAction,type MouthAttempt} from "./state";
import "./mouth-lab.css";

const stages=["Escuchá","Colocá y repetí","Contrastá","Frases","Reutilizá","Banco opcional"];
type Contact="lips"|"ridge"|"back";
export default function MouthLab({lesson}:{lesson:Lesson}){
 const [stage,setStage]=useState(0),[notice,setNotice]=useState(0),[word,setWord]=useState(0),[trialIndex,setTrialIndex]=useState(0),[phrase,setPhrase]=useState(0);
 const [attempts,setAttempts]=useState<Record<string,MouthAttempt>>({});
 const [contact,setContact]=useState<Contact|null>(null),[oralHelp,setOralHelp]=useState(false),[observations,setObservations]=useState([false,false,false]),[epoch,setEpoch]=useState(0);
 const trial=stage===0?noticeTrials[notice]:contrastTrials[trialIndex];
 const clipId=stage===1?wordModels[word]:stage===3?phraseModels[phrase]:trial.clipId;
 const clip=mouthClips[clipId];
 const context=stage===1?`word-${clipId}`:stage===3?`phrase-${clipId}`:trial.id;
 const attempt=attempts[context]||initialMouthAttempt();
 const target=targets.find(t=>t.id===clip.target)||targets[0];
 const act=(action:MouthAction)=>setAttempts(current=>({...current,[context]:updateMouthAttempt(current[context]||initialMouthAttempt(),action,trial.options.length)}));
 const correct=attempt.checked&&attempt.choice===trial.answer;
 const earnedText=((stage===0||stage===2)&&correct)||(stage===1&&attempt.heard);
 const showAnswer=!attempt.textHidden&&(attempt.revealed||earnedText);
 const heardContrast=contrastTrials.filter(t=>{const a=attempts[t.id];return a?.heard&&a.checked&&!a.assisted&&a.choice===t.answer;}).length;
 const oralModels=wordModels.every(id=>attempts[`word-${id}`]?.heard&&attempts[`word-${id}`]?.observed);
 const oralPhrases=phraseModels.every(id=>attempts[`phrase-${id}`]?.heard&&attempts[`phrase-${id}`]?.observed);
 const noticed=noticeTrials.every(t=>{const a=attempts[t.id];return a?.heard&&a.checked&&!a.assisted&&a.choice===t.answer;});
 const complete=heardContrast===8&&noticed&&oralModels&&oralPhrases&&observations.every(Boolean);
 const reset=()=>{setStage(0);setNotice(0);setWord(0);setTrialIndex(0);setPhrase(0);setAttempts({});setContact(null);setOralHelp(false);setObservations([false,false,false]);setEpoch(e=>e+1);};
 const audio=<div className="ml-listener"><AudioDeck key={`${epoch}-${stage}-${context}-${attempt.reload}`} src={clip.src} title={stage===1?`Palabra ${word+1}`:stage===3?`Frase ${phrase+1}`:stage===0?`Modelo ${notice+1}`:`Contraste ${trialIndex+1}`} channel="ESCUCHÁ · COMPARÁ · REPETÍ" showWaveform={false} playingMessage={showAnswer?"Escuchá y compará con el texto visible.":"Escuchá el modelo completo antes de responder."} onComplete={()=>act({type:"ended"})}/><div className="ml-actions"><button type="button" disabled={!attempt.ended||attempt.heard} onClick={()=>act({type:"confirm"})}>{attempt.heard?"Escucha confirmada":"Sí, lo escuché"}</button><button type="button" onClick={()=>act({type:"reload"})}>Recargar este audio</button></div><p className="ml-small">{attempt.heard?"Confirmación del alumno o del profe; no es una evaluación de la voz.":attempt.ended?"La reproducción terminó. ¿Se oyó? Confirmalo solo si escuchaste el modelo.":"Escuchá hasta el final y confirmá que se oyó. Si falla, recargá este audio o usá el texto de apoyo."}</p></div>;
 const support=<><button type="button" onClick={()=>act({type:showAnswer?"hide":earnedText?"show":"support"})}>{showAnswer?"Ocultar texto":earnedText?"Mostrar texto":"Texto de apoyo"}</button>{attempt.assisted&&<p className="ml-support">Se usó texto de apoyo: práctica acompañada. No cuenta como contraste auditivo sin texto.</p>}</>;
 const observation=<fieldset className="ml-observation"><legend>Después de escuchar al alumno · marca del profe</legend><label><input type="checkbox" disabled={!attempt.heard&&!attempt.assisted} checked={attempt.observed} onChange={event=>act({type:"observe",value:event.target.checked})}/><span>{stage===1?"Escuché tres intentos de esta palabra y di una indicación concreta.":"Escuché la frase repetida y una versión con una palabra cambiada."}</span></label><p>La app no evalúa la pronunciación ni graba la voz. Con texto se puede practicar; el registro auditivo requiere escuchar y confirmar el modelo.</p></fieldset>;

 return <main className="ml-lab">
  <header className="ml-header"><Link href="/">← Biblioteca</Link><span>FONÉTICA · PRO</span><button type="button" onClick={reset}>Reiniciar lección</button></header>
  <div className="ml-intro"><div><p className="ml-kicker">La punta de la lengua cambia el sentido</p><h1>{lesson.title}</h1><p>Escuchá una R, encontrá el contacto y usala para que otra persona te entienda.</p><p className="ml-small">A1 guiado · alcance A1–C1: un solo banco, sin variantes por nivel · ≈ 45 min + extensión</p></div><img src={lesson.image} width="1600" height="900" alt=""/></div>
  <details className="ml-guide"><summary>Guía del profe · ruta central y apoyos</summary><p>Meta: distinguir R simple y múltiple en palabras conocidas y sostener el contraste en un intercambio breve. Para A1, modelá los turnos y aceptá frases cortas. En niveles superiores, retirás el apoyo; no hay cinco clases distintas.</p><ol>{route.map(line=><li key={line}>{line}</li>)}</ol><p>Estimación con escucha, tres intentos, turnos y devolución; no es tiempo observado en clase. Cerrá tras el intercambio oral. Las seis estaciones y cuatro propuestas originales son extensión opcional.</p><p>Modelo general de R simple/múltiple del español; instrucciones con voseo. Voz sintética Microsoft es-AR-TomasNeural, configurada para Argentina a −10%. Esa configuración no equivale a una variedad verificada de oído. El profe debe revisar los clips antes de la clase.</p><p>No se intenta borrar el acento. Si aparece tensión o molestia, descansá. Una R aún inestable requiere práctica guiada, no más fuerza. No hace falta explicar anatomía para cumplir la meta A1.</p><p>La app no puede comprobar el volumen físico: exige reproducción terminada y confirmación de que se oyó. Es un registro declarado, no prueba automática de audición ni dominio. El texto de apoyo permite una adaptación, pero nunca otorga crédito auditivo sin texto.</p><p>Podés saltar o volver a cualquier estación. Los datos duran esta visita; reiniciar o recargar la página borra respuestas, ayudas y observaciones. No se guarda ni graba la voz.</p></details>
  <nav className="ml-stages" aria-label="Recorrido de Mouth Lab">{stages.map((label,i)=><button type="button" key={label} aria-current={stage===i?"step":undefined} onClick={()=>setStage(i)}>{label}</button>)}</nav>

  {(stage===0||stage===2)&&<section className="ml-work" aria-labelledby="ml-listen-title"><p className="ml-kicker">{stage===0?`01 · Modelo ${notice+1} de 2`:`03 · Contraste ${trialIndex+1} de 8`}</p><h2 id="ml-listen-title">{stage===0?"¿Un toque o varios contactos?":"¿Qué palabra escuchaste?"}</h2><p>{stage===0?"Escuchá la R en el centro de la palabra. Después elegí qué notás.":"Escuchá antes de elegir. Las dos palabras son posibles; el sonido decide."}</p>{audio}<div className="ml-options" role="group" aria-label="Tu elección">{trial.options.map((option,index)=><button type="button" key={option} aria-pressed={attempt.choice===index} disabled={!attempt.heard&&!attempt.assisted} onClick={()=>act({type:"choose",choice:index})}>{option}</button>)}</div><div className="ml-actions"><button type="button" className="ml-primary" disabled={attempt.choice===null||(!attempt.heard&&!attempt.assisted)} onClick={()=>act({type:"check"})}>Comprobar</button><button type="button" onClick={()=>act({type:"retry"})}>Intentar de nuevo</button>{support}</div><div className="ml-feedback" role="status" aria-live="polite">{attempt.checked&&!correct&&<p>Volvé a escuchar. {trial.hint}</p>}{correct&&<p>{attempt.assisted?"Práctica con texto: compará y repetí.":"Coincide con el audio. Repetí y compará con el profe."}</p>}{showAnswer&&<><p className="ml-word">Sonó: {clip.text}</p><p>{trial.why}</p></>}</div><div className="ml-actions"><button type="button" disabled={stage===0?notice===0:trialIndex===0} onClick={()=>stage===0?setNotice(n=>n-1):setTrialIndex(n=>n-1)}>{stage===0?"Anterior modelo":"Anterior contraste"}</button><button type="button" disabled={stage===0?notice===1:trialIndex===7} onClick={()=>stage===0?setNotice(n=>n+1):setTrialIndex(n=>n+1)}>{stage===0?"Siguiente modelo":"Siguiente contraste"}</button></div>{stage===2&&<p>{heardContrast} de 8 contrastes sin texto, con respuesta coincidente y escucha confirmada. No es una nota de pronunciación.</p>}<button type="button" className="ml-primary" onClick={()=>setStage(stage===0?1:3)}>{stage===0?"Pasar a la colocación":"Pasar a las frases"}</button></section>}

  {stage===1&&<section className="ml-work" aria-labelledby="ml-mouth-title"><p className="ml-kicker">02 · Articulá y repetí</p><h2 id="ml-mouth-title">¿Dónde hace contacto la punta?</h2><p>Señalá el lugar; probalo sin tensión. Después escuchá una palabra y hacé tres intentos.</p><div className="ml-mouth-area"><figure><svg viewBox="0 0 440 260" role="img" aria-label="Perfil esquemático de la boca: labios a la izquierda, dientes superiores delante del reborde alveolar; lengua debajo del paladar" data-contact={contact||"none"}><path className="ml-palate" d="M65 95 Q135 35 280 63 Q348 77 361 154"/><path className="ml-jaw" d="M62 179 Q177 227 302 202 L354 173"/><path className="ml-teeth" d="M86 85 L87 123 L104 123 L107 77"/><path className="ml-tongue" d="M330 181 Q267 117 171 154 Q133 155 119 112 Q107 143 134 177 Q222 205 330 181Z"/><circle cx="62" cy="142" r="15" className={contact==="lips"?"ml-point chosen":"ml-point"}/><circle cx="122" cy="86" r="15" className={contact==="ridge"?"ml-point chosen":"ml-point"}/><circle cx="343" cy="137" r="15" className={contact==="back"?"ml-point chosen":"ml-point"}/><text x="30" y="218">Labios</text><text x="114" y="31">Detrás de los dientes</text><text x="302" y="236">Zona posterior</text></svg><figcaption>Esquema simplificado, no una animación ni un análisis de tu boca.</figcaption></figure><div className="ml-contact"><div role="group" aria-label="Lugar de contacto">{([["lips","Labios"],["ridge","Detrás de los dientes superiores"],["back","Zona posterior"]] as const).map(([id,label])=><button type="button" key={id} aria-pressed={contact===id} onClick={()=>setContact(id)}>{label}</button>)}</div><div role="status" className="ml-feedback">{contact==="lips"?<p>Los labios no hacen este contacto. Buscá con la punta de la lengua detrás de los dientes de arriba.</p>:contact==="back"?<p>La parte posterior no es el objetivo de este modelo. Acercá la punta de la lengua a la zona anterior.</p>:contact==="ridge"?<p><b>Punta de la lengua → reborde detrás de los dientes superiores.</b> Ese lugar sirve para los dos recorridos; cambia el contacto.</p>:<p>Elegí dónde apoyarías brevemente la punta de la lengua.</p>}</div></div></div><div className="ml-actions">{wordModels.map((id,i)=><button type="button" key={id} aria-pressed={word===i} onClick={()=>setWord(i)}>Palabra {i+1}</button>)}</div>{audio}{support}{showAnswer&&<div className="ml-articulation"><p className="ml-word">Sonó: {clip.text}</p><h3>{target.label}</h3><p>{target.cue}</p><p className="ml-motion">{target.motion}</p><p>{clipId==="rojo"?"Al principio de rojo se practica la R múltiple, aunque se escriba una sola r.":"Escuchá → repetí tres veces → compará una sola cosa con el profe."}</p></div>}{observation}<button type="button" className="ml-primary" onClick={()=>setStage(2)}>Pasar a los contrastes</button></section>}

  {stage===3&&<section className="ml-work" aria-labelledby="ml-phrase-title"><p className="ml-kicker">04 · De la palabra a la frase</p><h2 id="ml-phrase-title">Escuchá, imitá y cambiá un detalle</h2><div className="ml-actions">{phraseModels.map((id,i)=><button type="button" key={id} aria-pressed={phrase===i} onClick={()=>setPhrase(i)}>Frase {i+1}</button>)}</div>{audio}{support}{showAnswer&&<p className="ml-word">{clip.text}</p>}<div className="ml-transfer"><h3>Ahora, sin mirar el modelo</h3><p>Repetí la frase. Cambiá un detalle: de quién es el perro, qué juguete es caro o qué color querés. Tu compañero dice qué entendió. Si hace falta, abrí el texto, ensayá y volvé a ocultarlo.</p><p>Carro significa aquí vehículo de juguete; el profe puede explicar que también se usa auto o coche en otros contextos y regiones.</p></div>{observation}<button type="button" className="ml-primary" onClick={()=>setStage(4)}>Pasar al intercambio oral</button></section>}

  {stage===4&&<section className="ml-work" aria-labelledby="ml-final-title"><p className="ml-kicker">05 · Cierre oral · cambiar de roles</p><h2 id="ml-final-title">Quiero ese juguete</h2><p>Una persona vende; la otra quiere un regalo y tiene diez monedas. Mirá los objetos y elegí uno en silencio. Tu compañero debe identificarlo por lo que decís.</p><div className="ml-toys" aria-label="Objetos de la tienda"><div><b>Carro rojo</b><span>12 monedas</span></div><div><b>Carro azul</b><span>8 monedas</span></div><div><b>Perro de juguete</b><span>6 monedas</span></div></div><ol className="ml-turns"><li>Pedí el juguete sin señalarlo. El vendedor repite lo que entendió y dice el precio.</li><li>Comentá el precio o corregí una confusión. Usá tres palabras del laboratorio: carro, caro, rojo, pero o perro.</li><li>Si es demasiado caro, elegí otro o pedí otro precio. Confirmá la compra y cambiá de rol.</li><li>Sin leer el modelo, repetí dos frases del intercambio después de una indicación del profe. Tu compañero dice si ahora entiende mejor.</li></ol><button type="button" onClick={()=>setOralHelp(v=>!v)}>{oralHelp?"Ocultar ayuda oral":"Ayuda oral"}</button>{oralHelp&&<p className="ml-support">Quiero el… · ¿El carro o el perro? · El rojo. · Es caro, pero… · ¿Cuánto cuesta el otro? · Quiero ese, por favor.</p>}<fieldset className="ml-observation"><legend>Observación del profe, después del intercambio real</legend>{finalCriteria.map((criterion,i)=><label key={criterion}><input type="checkbox" checked={observations[i]} onChange={event=>setObservations(current=>current.map((v,n)=>n===i?event.target.checked:v))}/><span>{criterion}</span></label>)}<p>Marcas del profe, sin evaluación automática de la pronunciación.</p></fieldset><div className="ml-feedback" role="status">{complete?<p>Recorrido central registrado: escucha declarada, contrastes revisados y producción observada por el profe. No equivale a dominio de la pronunciación.</p>:<p>Falta evidencia de escucha o práctica: {heardContrast}/8 contrastes sin texto; {noticed?"2":"menos de 2"}/2 modelos distinguidos; {wordModels.filter(id=>attempts[`word-${id}`]?.heard&&attempts[`word-${id}`]?.observed).length}/5 palabras y {phraseModels.filter(id=>attempts[`phrase-${id}`]?.heard&&attempts[`phrase-${id}`]?.observed).length}/3 frases con escucha y observación. Podés cerrar una sesión adaptada sin marcarla como recorrido auditivo completo.</p>}</div><p>Para seguir: elegí una sola palabra difícil; probala dentro de una frase mañana y pedí a alguien que diga qué entendió.</p></section>}

  {stage===5&&<section className="ml-work" aria-labelledby="ml-bank-title"><p className="ml-kicker">Extensión · no necesaria para cerrar el recorrido</p><h2 id="ml-bank-title">Las seis estaciones originales</h2><p>Banco de consulta guiada A1–C1. No son niveles separados ni modelos grabados adicionales. El profe elige el objetivo y aporta los modelos; las consignas originales se conservan.</p><details><summary>Objetivos, entrada e idea original</summary><ul>{lesson.goals.map(goal=><li key={goal}>{goal}</li>)}</ul><p>{lesson.warmup}</p><p>{lesson.explanation}</p></details>{lesson.practice.map((line,i)=><details key={line}><summary>Estación {i+1} · {line.split(" · ")[0]}</summary><p>{line}</p></details>)}<h3>Cuatro propuestas orales originales</h3>{lesson.speaking.map((line,i)=><details key={line}><summary>Propuesta {i+1} · {line.split(" · ")[0]}</summary><p>{line}</p></details>)}<details><summary>Rutina para continuar</summary><p>{lesson.homework}</p></details><p className="ml-small">Al usar el mapa de consonantes original, el profe distingue posición orientativa de realización: b y d pueden variar según el contexto. No se practica aquí todo el sistema consonántico.</p></section>}
 </main>;
}
