export const adjectiveEnglish:Record<string,string>={
'¿Cómo es tu mesa de trabajo?':'What is your work table like?',
'¿Qué prefieres: una sala grande o pequeña?':'Which do you prefer: a large or a small room?',
'Dos salas para trabajar':'Two rooms for work',
'La empresa tiene dos salas nuevas. La sala pequeña es tranquila y tiene una mesa redonda. La sala grande tiene ventanas grandes y sillas cómodas. Las paredes son blancas. Los libros interesantes están en una estantería. Clara prefiere la sala pequeña: trabaja sola y necesita silencio. Su compañero prefiere la sala grande para las reuniones.':'The company has two new rooms. The small room is quiet and has a round table. The large room has large windows and comfortable chairs. The walls are white. The interesting books are on a bookshelf. Clara prefers the small room: she works alone and needs silence. Her colleague prefers the large room for meetings.',
'¿Por qué Clara prefiere la sala pequeña?':'Why does Clara prefer the small room?',
'Porque trabaja sola y necesita silencio.':'Because she works alone and needs silence.',
'Relaciona la elección con silencio y trabajo individual':'Connect her choice with silence and working alone.',
'¿Cómo son las sillas de la sala grande?':'What are the chairs in the large room like?',
'Cómodas.':'Comfortable.',
'Identifica la cualidad de las sillas':'Identify the quality of the chairs.',
'Compara «sala pequeña» y «paredes blancas». ¿Qué información muestra el adjetivo?':'Compare “sala pequeña” and “paredes blancas”. What information does the adjective show?',
'El género femenino y el número del nombre: singular o plural.':'The noun’s feminine gender and its number: singular or plural.',
'¿Por qué vemos «libros interesantes» y no «libros interesantos»?':'Why do we see “libros interesantes” and not “libros interesantos”?',
'Interesante conserva la forma de género y cambia a plural con -s.':'Interesante keeps the same form for gender and adds -s for the plural.',
'Una visita a la sala':'A visit to the room',
'Hola, Clara. Estoy en la sala grande. Las mesas son nuevas, pero las sillas son viejas. Las ventanas están abiertas y la sala es tranquila ahora. Tengo dos libros interesantes para ti. ¿Prefieres una mesa redonda o una mesa cuadrada para tu espacio? Las dos son pequeñas y cómodas.':'Hi, Clara. I am in the large room. The tables are new, but the chairs are old. The windows are open and the room is quiet now. I have two interesting books for you. Do you prefer a round or a square table for your space? Both are small and comfortable.',
'¿Qué decisión pide a Clara?':'What decision does the speaker ask Clara to make?',
'Elegir una mesa redonda o cuadrada.':'Choose a round or a square table.',
'Identifica las dos opciones y su destinataria':'Identify the two options and who is being asked.',
'¿Qué objetos son viejos?':'Which objects are old?',
'Las sillas.':'The chairs.',
'Distingue sillas de mesas':'Distinguish chairs from tables.',
'Elige mobiliario para tu espacio: mesa redonda o cuadrada, sillas claras u oscuras. Explica tres preferencias.':'Choose furniture for your space: a round or square table, light or dark chairs. Explain three preferences.',
'El profesor ofrece un objeto de otro tamaño. ¿Lo aceptas?':'Your teacher offers an object of a different size. Do you accept it?',
'Prefiero una mesa… porque…':'I prefer a… table because…',
'Describe cuatro objetos visibles por la cámara. Tu profesor intenta identificar cada uno.':'Describe four objects visible on camera. Your teacher tries to identify each one.',
'Describe un segundo objeto parecido y añade una diferencia.':'Describe a second, similar object and add one difference.',
'El libro azul… / Las cajas pequeñas…':'The blue book… / The small boxes…',
'Compara dos salas reales que conoces. Recomienda una para estudiar y otra para conversar.':'Compare two real rooms you know. Recommend one for studying and one for talking.',
'¿Qué característica es más importante para ti?':'Which feature matters most to you?',
'Esta sala es…; la otra es…':'This room is…; the other one is…',
'Escribe un mensaje para describir la sala que recomiendas a una compañera. Da tres detalles útiles.':'Write a message describing the room you recommend to a colleague. Give three useful details.',
'Te recomiendo la sala pequeña. Tiene una mesa redonda y dos sillas cómodas. Las paredes son blancas y las ventanas son grandes. Es una sala tranquila para estudiar español por la tarde.':'I recommend the small room. It has a round table and two comfortable chairs. The walls are white and the windows are large. It is a quiet room for studying Spanish in the afternoon.',
'Relaciona cada adjetivo con su sustantivo':'Connect each adjective to its noun.',
'Revisa género y número':'Check gender and number.',
'Incluye una recomendación comprensible':'Include a clear recommendation.',
'Describe dos sillas con un adjetivo en -o.':'Describe two chairs using an adjective whose base form ends in -o.',
'Son dos sillas cómodas.':'They are two comfortable chairs.',
'Sustantivo + descripción':'Noun + description',
'SUSTANTIVO + ADJETIVO · una casa + bonita · un café + tranquilo':'NOUN + ADJECTIVE · a pretty house · a quiet café',
'El sustantivo nombra; el adjetivo describe. En la forma más neutra y frecuente del español, el adjetivo aparece después del sustantivo.':'The noun names; the adjective describes. In the most neutral and common Spanish pattern, the adjective comes after the noun.',
'un libro interesante':'an interesting book',
'una calle tranquila':'a quiet street',
'un día difícil':'a difficult day',
'una persona amable':'a kind person',
'En inglés el adjetivo suele ir antes. En español, para empezar, usa sustantivo + adjetivo.':'In English, the adjective normally comes first. To start in Spanish, use noun + adjective.',
'Adjetivos en -o':'Adjectives ending in -o',
'-O / -A · -OS / -AS · nuevo · nueva · nuevos · nuevas':'-O / -A · -OS / -AS · four forms of nuevo (new)',
'Los adjetivos que terminan en -o suelen cambiar a -a para el femenino y agregan -s para el plural.':'Adjectives ending in -o normally change to -a for the feminine and add -s for the plural.',
'el barrio nuevo':'the new neighbourhood',
'la casa nueva':'the new house',
'los barrios nuevos':'the new neighbourhoods',
'las casas nuevas':'the new houses',
'Si el grupo tiene nombres masculinos y femeninos, el plural tradicional es masculino: Ana y Leo son argentinos.':'For a group with masculine and feminine nouns, the traditional plural is masculine: Ana and Leo are Argentinian (argentinos).',
'Una forma para dos géneros':'One form for two genders',
'-E → misma forma · consonante → misma forma · + S / ES para plural':'-E → same form · consonant → same form · add S / ES for the plural',
'Grande, interesante, fácil o azul no cambian por masculino/femenino. Sí cambian por número.':'Grande (large), interesante (interesting), fácil (easy) and azul (blue) do not change for masculine or feminine. They do change for number.',
'un hotel grande':'a large hotel',
'una casa grande':'a large house',
'dos hoteles grandes':'two large hotels',
'unas calles azules':'some blue streets',
'Nacionalidades en consonante sí pueden cambiar: español / española; francés / francesa.':'Nationality adjectives ending in a consonant can change for gender: español / española (Spanish); francés / francesa (French).',
'Una casa ___':'A ___ house (casa is feminine).',
'Casa es femenina singular.':'Casa is feminine singular.',
'Dos barrios ___':'Two ___ neighbourhoods (barrios is masculine).',
'Barrios es masculino plural.':'Barrios is masculine plural.',
'Una película ___':'An ___ film (película is feminine).',
'Interesante conserva la misma forma para ambos géneros.':'Interesante keeps the same form for both genders.',
'Un estudiante ___':'A ___ student (masculine in this sentence).',
'Estudiante es masculino singular en este contexto.':'Estudiante is masculine singular in this context.',
'Cambia a plural: una oficina tranquila y grande.':'Change to the plural: a quiet, large office.',
'Unas oficinas tranquilas y grandes.':'Some quiet, large offices.',
'Concuerdan sustantivo y adjetivos.':'The noun and adjectives agree.',
'Se aceptan otras formulaciones que conservan el significado y la estructura objetivo.':'Accept other wording that keeps the meaning and target structure.',
'Describe dos objetos reales con adjetivos distintos.':'Describe two real objects using different adjectives.',
'Mi mesa es pequeña. Mis sillas son cómodas.':'My table is small. My chairs are comfortable.',
'Las cualidades concuerdan con el objeto descrito.':'The adjectives agree with the object being described.',
'Describir lo que ves.':'Describe what you see.',
'Comprender mensajes sobre esta situación y responder con una intervención oral y un texto breve.':'Understand messages about this situation and respond in speech and a short text.',
};
