import {author,row as r} from './schema.mjs';
export default author('A1',{
 name:'Una frase, dos intenciones',demand:'Frases conocidas, dos opciones y gestos para acompañar la voz.',objective:'Reconocé una pregunta, una reacción y una confirmación; probalas con tu voz.',warmup:'Saludá con «Hola». Ahora saludá como si vieras a un amigo después de mucho tiempo.',teacher:'Modelá con gestos. Primero escuchá la elección del alumno; después revelá el texto. Los contornos son ejemplos de ensayo, no reglas para todas las personas.',avoid:'No exijas una melodía idéntica ni corrijas todo el acento. Buscá una intención reconocible.',extension:'Cambiá quién escucha: un amigo, una persona desconocida o alguien que no oyó bien.'},[
 r('Escuchá sin leer. ¿La persona pregunta o confirma?','Vamos mañana.',['Pregunta si el plan está bien','Confirma el plan'],0,'La subida del final puede invitar a confirmar. Con las mismas palabras, una caída puede cerrar el plan.','Decí «Vamos mañana» para preguntar y para confirmar. Tu profe señala cuál escucha.','Compará con tu propia voz. No enseñes que todas las preguntas suben.','question'),
 r('Escuchá esta reacción. ¿Qué parece sentir la persona?','Qué bueno, gracias.',['Alegría y sorpresa','Una pregunta sobre el lugar'],0,'El movimiento amplio de la voz ayuda a oír una reacción. También importa la situación.','Decí «Qué bueno» al recibir una buena noticia. Después decilo con calma.','Podés mostrar una noticia con un dibujo. Aceptá alegría o sorpresa como lecturas cercanas.','surprise'),
 r('Dos tomas, las mismas palabras. ¿Cuál cierra el plan con más claridad?','Nos vemos mañana.',['Toma A','Toma B'],1,'La toma con una caída definida termina el plan. La otra deja el final más abierto.','Repetí las dos tomas y elegí una para despedirte de un amigo.','Hacé un gesto hacia abajo en el cierre, sin pedir que copie cada nota.','firm','question'),
 r('Una amiga te ayuda. ¿Cómo parece sonar este agradecimiento?','Muchas gracias, Ana.',['Un agradecimiento tranquilo','Una pregunta para confirmar'],0,'La caída suave permite cerrar el agradecimiento. Para saber si es sincero también necesitamos el contexto.','Agradecé por un café. Cambiá el nombre y probá un tono más cálido.','No equipares un rango de voz con sinceridad garantizada.','warm'),
 r('Escuchá el modelo. Después decí la frase como una pregunta real.','Estás bien, Ana.',null,null,'Las palabras pueden funcionar como confirmación o pregunta. En este ensayo, el final sube.','Preguntá «Estás bien» a tu profe. Escuchá su respuesta y repetí con otra intención.','Una pregunta por el bienestar también puede caer en otras variedades. Mostrá una posibilidad.','question'),
 r('Te invitan a salir. ¿Qué toma suena más decidida a aceptar?','Sí, vamos ahora.',['Toma A','Toma B'],0,'La caída más definida favorece una aceptación decidida. La suspensión puede dejar espacio para dudar.','Aceptá una invitación con decisión. Después respondé como si todavía pensaras.','Pedí al alumno que explique con un gesto, no con terminología.','firm','doubt'),
 r('Escuchá y ensayá una reacción con dos voces distintas.','Qué lindo lugar.',null,null,'Un arco amplio puede destacar la reacción; una caída suave puede sonar más tranquila.','Decí la frase al ver una foto: primero con sorpresa, después con calma.','El objetivo es cambiar la entrega, no subir el volumen ni gritar.','surprise'),
 r('Estás en un café. Escuchá un pedido y prepará el tuyo.','Un café, por favor.',null,null,'La voz ayuda a acompañar «por favor». La cortesía depende también de las palabras y de la situación.','Pedí un café a tu profe. Recibí la bebida y decí «Gracias» con una intención clara.','Hacé de camarero. Devolvé solo una observación sobre cómo llegó el pedido.','warm'),
 r('Opcional: ¿esta voz termina o parece esperar algo más?','Sí, está bien.',['Parece dejar algo abierto','Cierra con mucha decisión'],0,'Un final suspendido puede invitar a continuar. Preguntá qué más podría decir la persona.','Decí «Sí, está bien» y agregá «pero…» solo en la segunda vuelta.','La continuación es una hipótesis, no una palabra que esté en el audio.','suspended'),
 r('Opcional: escuchá antes de leer. ¿Qué interpretación encaja mejor?','Venís mañana.',['Confirma una fecha','Pide confirmar una fecha'],1,'La subida final puede volver estas palabras una pregunta de confirmación.','Preguntá por mañana y luego confirmá la respuesta con una caída.','Aceptá la explicación con ejemplos o gestos.','question'),
],{prompt:'Tres frases para conocer a alguien en un café.',steps:['Prepará un saludo, una pregunta corta y un agradecimiento. Elegí qué querés transmitir en cada uno.','Decilas sin leer. El profe responde según la intención que escucha.','Recibí una sugerencia y repetí dos frases cambiando una intención.'],support:'Hola. / ¿Cómo estás? / Qué bueno. / Gracias.',criteria:['Se distingue una pregunta de una confirmación en este intercambio.','La reacción expresa una intención reconocible con apoyo del contexto.','Puede repetir una frase cambiando su entrega sin perder las palabras.']});
