export type Question = {
  prompt: string;
  options: string[];
  answer: number;
  feedback: string;
};

export type Country = {
  id: string;
  name: string;
  flag: string;
  locale: string;
  voiceHints: string[];
  color: string;
  x: number;
  y: number;
  city: string;
  title: string;
  topic: string;
  speaker: string;
  speed: number;
  pitch: number;
  script: string;
  glossary: { word: string; meaning: string }[];
  questions: Question[];
};

export const countries: Country[] = [
  {
    id: "argentina",
    name: "Argentina",
    flag: "🇦🇷",
    locale: "es-AR",
    voiceHints: ["argentina", "es-ar", "diego", "elena"],
    color: "#63c7ff",
    x: 48,
    y: 83,
    city: "Buenos Aires",
    title: "Un plan simple que salvó el día",
    topic: "Transporte, amistad y merienda",
    speaker: "Voz rioplatense · ritmo tranquilo",
    speed: 0.94,
    pitch: 0.98,
    script: "Che, te cuento lo que me pasó ayer. Salí del trabajo a las seis y quería tomar el colectivo para encontrarme con Lucía. Cuando llegué a la parada, vi que había un montón de gente. Al final, el colectivo tardó casi cuarenta minutos. Lucía me mandó un mensaje y me dijo que no había problema. Nos encontramos en un café de Almagro, pedimos dos medialunas y compartimos un café con leche. Yo estaba cansado, pero la charla me cambió el ánimo. Volví a casa cerca de las diez y pensé: a veces un plan simple te salva el día, ¿viste?",
    glossary: [
      { word: "colectivo", meaning: "autobús" },
      { word: "un montón de", meaning: "mucho / mucha" },
      { word: "¿viste?", meaning: "expresión para conectar con la otra persona" },
    ],
    questions: [
      { prompt: "¿A qué hora salió del trabajo?", options: ["A las cinco", "A las seis", "A las siete"], answer: 1, feedback: "Salió del trabajo a las seis." },
      { prompt: "¿Qué transporte quería tomar?", options: ["El colectivo", "El subte", "Un taxi"], answer: 0, feedback: "Quería tomar el colectivo." },
      { prompt: "¿Con quién iba a encontrarse?", options: ["Con su hermana", "Con Lucía", "Con un compañero"], answer: 1, feedback: "Iba a encontrarse con Lucía." },
      { prompt: "¿Cómo estaba la parada?", options: ["Vacía", "Cerrada", "Llena de gente"], answer: 2, feedback: "Había un montón de gente." },
      { prompt: "¿Cuánto tardó el colectivo?", options: ["Casi veinte minutos", "Casi cuarenta minutos", "Una hora"], answer: 1, feedback: "El colectivo tardó casi cuarenta minutos." },
      { prompt: "¿Dónde se encontraron?", options: ["En un café de Almagro", "En una plaza", "En la oficina"], answer: 0, feedback: "Se encontraron en un café de Almagro." },
      { prompt: "¿Qué pidieron?", options: ["Empanadas y mate", "Dos medialunas y café con leche", "Tostadas y té"], answer: 1, feedback: "Pidieron dos medialunas y compartieron un café con leche." },
      { prompt: "¿Cómo estaba la persona antes de la charla?", options: ["Cansada", "Enojada", "Nerviosa"], answer: 0, feedback: "Estaba cansada." },
      { prompt: "¿Qué efecto tuvo la charla?", options: ["Le dio sueño", "Le cambió el ánimo", "Le hizo perder el colectivo"], answer: 1, feedback: "La charla le cambió el ánimo." },
      { prompt: "¿Cuál es la idea final del audio?", options: ["Los planes caros son mejores", "Es mejor quedarse en casa", "Un plan simple puede mejorar el día"], answer: 2, feedback: "La conclusión es que un plan simple puede salvarte el día." },
    ],
  },
  {
    id: "mexico",
    name: "México",
    flag: "🇲🇽",
    locale: "es-MX",
    voiceHints: ["mexico", "méxico", "es-mx", "jorge", "dalia"],
    color: "#ffcf5a",
    x: 16,
    y: 15,
    city: "Ciudad de México",
    title: "Una mañana en Coyoacán",
    topic: "Mercado, comida y una decisión inesperada",
    speaker: "Voz mexicana · ritmo conversacional",
    speed: 0.93,
    pitch: 1,
    script: "El sábado fui con mi prima al mercado de Coyoacán. Queríamos comprar fruta, pero terminamos pasando toda la mañana ahí. Primero probamos un jugo de mango que estaba buenísimo. Después vimos un puesto de artesanías y mi prima encontró una taza pintada a mano para su mamá. Yo no pensaba comprar nada, pero vi una libreta con una portada azul y me encantó. Antes de volver, comimos dos tacos cada uno. Había mucha gente y hacía calor, así que buscamos una mesa a la sombra. Llegamos a casa cansados, pero muy contentos con nuestras compras.",
    glossary: [
      { word: "puesto", meaning: "pequeño espacio de venta en un mercado" },
      { word: "artesanías", meaning: "objetos hechos a mano" },
      { word: "a la sombra", meaning: "en un lugar protegido del sol" },
    ],
    questions: [
      { prompt: "¿Cuándo fueron al mercado?", options: ["El viernes", "El sábado", "El domingo"], answer: 1, feedback: "Fueron el sábado." },
      { prompt: "¿Con quién fue la persona?", options: ["Con su prima", "Con su mamá", "Con una amiga"], answer: 0, feedback: "Fue con su prima." },
      { prompt: "¿Qué querían comprar al principio?", options: ["Ropa", "Fruta", "Libros"], answer: 1, feedback: "Al principio querían comprar fruta." },
      { prompt: "¿Qué bebida probaron?", options: ["Agua de limón", "Café frío", "Jugo de mango"], answer: 2, feedback: "Probaron un jugo de mango." },
      { prompt: "¿Para quién era la taza?", options: ["Para la mamá de la prima", "Para la persona que habla", "Para una amiga"], answer: 0, feedback: "La taza era para la mamá de su prima." },
      { prompt: "¿Qué compró la persona que habla?", options: ["Una libreta azul", "Una taza roja", "Una camisa"], answer: 0, feedback: "Compró una libreta con una portada azul." },
      { prompt: "¿Cuántos tacos comió cada uno?", options: ["Uno", "Dos", "Tres"], answer: 1, feedback: "Comieron dos tacos cada uno." },
      { prompt: "¿Qué tiempo hacía?", options: ["Hacía frío", "Llovía", "Hacía calor"], answer: 2, feedback: "Hacía calor." },
      { prompt: "¿Dónde buscaron una mesa?", options: ["Cerca de la puerta", "A la sombra", "En la calle"], answer: 1, feedback: "Buscaron una mesa a la sombra." },
      { prompt: "¿Cómo llegaron a casa?", options: ["Cansados y contentos", "Enojados", "Con hambre"], answer: 0, feedback: "Llegaron cansados, pero muy contentos." },
    ],
  },
  {
    id: "colombia",
    name: "Colombia",
    flag: "🇨🇴",
    locale: "es-CO",
    voiceHints: ["colombia", "es-co", "salome", "gonzalo"],
    color: "#ff7f8d",
    x: 31,
    y: 40,
    city: "Medellín",
    title: "La mochila que se quedó en el café",
    topic: "Un olvido, una llamada y una buena sorpresa",
    speaker: "Voz colombiana · ritmo amable",
    speed: 0.94,
    pitch: 1.02,
    script: "Esta mañana salí temprano para una reunión en el centro. Como tenía tiempo, entré a un café y pedí un tinto. Revisé unos mensajes, pagué y me fui caminando. Diez minutos después, sentí que me faltaba algo: había dejado la mochila junto a la silla. Qué pena. Llamé al café y una chica me dijo: tranquilo, acá la tenemos. Volví rápidamente y la encontré en la caja. Dentro estaban mi computadora y todos mis documentos. Le agradecí varias veces a la chica y compré dos panes de queso para compartir con ella. Por suerte, todo terminó bien.",
    glossary: [
      { word: "tinto", meaning: "café negro en Colombia" },
      { word: "qué pena", meaning: "expresión de vergüenza o disculpa" },
      { word: "acá la tenemos", meaning: "la mochila está aquí y está segura" },
    ],
    questions: [
      { prompt: "¿Por qué salió temprano?", options: ["Tenía una reunión", "Quería hacer ejercicio", "Iba de viaje"], answer: 0, feedback: "Salió temprano porque tenía una reunión." },
      { prompt: "¿Qué pidió en el café?", options: ["Un jugo", "Un tinto", "Un chocolate"], answer: 1, feedback: "Pidió un tinto, es decir, un café negro." },
      { prompt: "¿Qué hizo antes de irse?", options: ["Leyó un libro", "Llamó a su familia", "Revisó mensajes y pagó"], answer: 2, feedback: "Revisó unos mensajes y pagó." },
      { prompt: "¿Cuándo notó que faltaba algo?", options: ["Diez minutos después", "Una hora después", "Al llegar a casa"], answer: 0, feedback: "Lo notó diez minutos después." },
      { prompt: "¿Dónde había dejado la mochila?", options: ["En la calle", "Junto a la silla", "En el autobús"], answer: 1, feedback: "La había dejado junto a la silla." },
      { prompt: "¿Qué hizo cuando recordó la mochila?", options: ["Volvió sin llamar", "Llamó al café", "Llamó a la policía"], answer: 1, feedback: "Primero llamó al café." },
      { prompt: "¿Dónde estaba la mochila cuando volvió?", options: ["En la caja", "En la mesa", "En la cocina"], answer: 0, feedback: "La mochila estaba en la caja." },
      { prompt: "¿Qué había dentro?", options: ["Ropa y comida", "Una cámara", "La computadora y documentos"], answer: 2, feedback: "Estaban su computadora y todos sus documentos." },
      { prompt: "¿Qué compró para agradecer?", options: ["Dos panes de queso", "Una torta", "Dos cafés"], answer: 0, feedback: "Compró dos panes de queso." },
      { prompt: "¿Cómo terminó la historia?", options: ["Perdió la reunión", "Terminó bien", "La mochila estaba vacía"], answer: 1, feedback: "Por suerte, todo terminó bien." },
    ],
  },
  {
    id: "peru",
    name: "Perú",
    flag: "🇵🇪",
    locale: "es-PE",
    voiceHints: ["peru", "perú", "es-pe", "alex", "rosa"],
    color: "#ff6868",
    x: 31,
    y: 54,
    city: "Lima",
    title: "El almuerzo que cambió de lugar",
    topic: "Familia, comida y un cambio de planes",
    speaker: "Voz peruana · ritmo claro",
    speed: 0.93,
    pitch: 1,
    script: "El domingo íbamos a almorzar en la casa de mi tía, pero temprano se cortó el agua en su edificio. Ella nos llamó un poco preocupada y propuso dejar el encuentro para otra semana. Mi hermano tuvo otra idea: llevar toda la comida a un parque cerca de su casa. Cada persona llevó algo. Mi tía preparó causa de pollo, mi mamá llevó limonada y yo compré frutas. Al principio pensamos que iba a ser incómodo, pero encontramos una mesa grande bajo unos árboles. Comimos, conversamos y hasta jugamos a las cartas. El cambio de planes resultó mejor de lo esperado.",
    glossary: [
      { word: "se cortó el agua", meaning: "el edificio quedó temporalmente sin agua" },
      { word: "causa de pollo", meaning: "plato peruano preparado con papa y pollo" },
      { word: "resultó", meaning: "al final fue" },
    ],
    questions: [
      { prompt: "¿Qué día iban a almorzar juntos?", options: ["El sábado", "El domingo", "El lunes"], answer: 1, feedback: "Iban a almorzar juntos el domingo." },
      { prompt: "¿Dónde era el plan original?", options: ["En la casa de la tía", "En un restaurante", "En la playa"], answer: 0, feedback: "El plan original era almorzar en la casa de la tía." },
      { prompt: "¿Qué problema hubo en el edificio?", options: ["No había electricidad", "Se rompió el ascensor", "Se cortó el agua"], answer: 2, feedback: "Se cortó el agua en el edificio." },
      { prompt: "¿Qué propuso primero la tía?", options: ["Cambiar el menú", "Dejar el encuentro para otra semana", "Ir a un hotel"], answer: 1, feedback: "Propuso dejar el encuentro para otra semana." },
      { prompt: "¿Quién tuvo la idea de ir al parque?", options: ["El hermano", "La mamá", "La tía"], answer: 0, feedback: "El hermano tuvo la idea." },
      { prompt: "¿Qué preparó la tía?", options: ["Arroz con pollo", "Causa de pollo", "Una ensalada"], answer: 1, feedback: "La tía preparó causa de pollo." },
      { prompt: "¿Qué llevó la mamá?", options: ["Limonada", "Frutas", "Café"], answer: 0, feedback: "La mamá llevó limonada." },
      { prompt: "¿Dónde encontraron una mesa?", options: ["Junto a la calle", "Bajo unos árboles", "Dentro de un café"], answer: 1, feedback: "Encontraron una mesa grande bajo unos árboles." },
      { prompt: "¿Qué hicieron además de comer y conversar?", options: ["Cantaron", "Jugaron a las cartas", "Fueron de compras"], answer: 1, feedback: "También jugaron a las cartas." },
      { prompt: "¿Cómo resultó el cambio de planes?", options: ["Mejor de lo esperado", "Muy incómodo", "Demasiado caro"], answer: 0, feedback: "Resultó mejor de lo esperado." },
    ],
  },
  {
    id: "chile",
    name: "Chile",
    flag: "🇨🇱",
    locale: "es-CL",
    voiceHints: ["chile", "es-cl", "catalina", "lorenzo"],
    color: "#6f96ff",
    x: 39,
    y: 75,
    city: "Santiago",
    title: "Una chaqueta para cuatro estaciones",
    topic: "Clima, trabajo y vida cotidiana",
    speaker: "Voz chilena · ritmo natural",
    speed: 0.92,
    pitch: 0.99,
    script: "Ayer salí de mi casa con sol y sin chaqueta porque la mañana estaba bastante agradable. Tenía que hacer una presentación en la oficina y no quería llegar con muchas cosas. A la hora del almuerzo, el cielo cambió completamente y empezó a correr un viento helado. Una compañera me dijo: te avisaron que hoy iba a cambiar el tiempo, po. Yo no había mirado el pronóstico. Cuando salimos del trabajo, además empezó a lloviznar. Por suerte, mi compañero Matías tenía una chaqueta extra en el auto y me la prestó. Desde ahora voy a revisar el tiempo antes de salir.",
    glossary: [
      { word: "po", meaning: "partícula chilena que refuerza lo que se dice" },
      { word: "pronóstico", meaning: "información sobre el tiempo" },
      { word: "lloviznar", meaning: "llover de manera muy suave" },
    ],
    questions: [
      { prompt: "¿Cómo estaba la mañana?", options: ["Agradable y con sol", "Muy fría", "Con lluvia fuerte"], answer: 0, feedback: "La mañana estaba agradable y había sol." },
      { prompt: "¿Por qué no llevó chaqueta?", options: ["La perdió", "No quería llevar muchas cosas", "No tenía ninguna"], answer: 1, feedback: "No quería llegar a la oficina con muchas cosas." },
      { prompt: "¿Qué tenía que hacer en la oficina?", options: ["Una entrevista", "Una presentación", "Una celebración"], answer: 1, feedback: "Tenía que hacer una presentación." },
      { prompt: "¿Cuándo cambió el cielo?", options: ["A la hora del almuerzo", "A primera hora", "Por la noche"], answer: 0, feedback: "El cielo cambió a la hora del almuerzo." },
      { prompt: "¿Qué empezó a correr?", options: ["Un viento helado", "Aire caliente", "Una tormenta de arena"], answer: 0, feedback: "Empezó a correr un viento helado." },
      { prompt: "¿Qué no había mirado la persona?", options: ["El calendario", "El pronóstico", "Su correo"], answer: 1, feedback: "No había mirado el pronóstico." },
      { prompt: "¿Qué pasó al salir del trabajo?", options: ["Nevó", "Salió el sol", "Empezó a lloviznar"], answer: 2, feedback: "Empezó a lloviznar." },
      { prompt: "¿Quién tenía una chaqueta extra?", options: ["Una compañera", "Matías", "El jefe"], answer: 1, feedback: "Matías tenía una chaqueta extra." },
      { prompt: "¿Dónde estaba la chaqueta?", options: ["En el auto", "En la oficina", "En una tienda"], answer: 0, feedback: "La chaqueta estaba en el auto." },
      { prompt: "¿Qué va a hacer desde ahora?", options: ["Llevar dos chaquetas", "Trabajar desde casa", "Revisar el tiempo antes de salir"], answer: 2, feedback: "Va a revisar el tiempo antes de salir." },
    ],
  },
  {
    id: "uruguay",
    name: "Uruguay",
    flag: "🇺🇾",
    locale: "es-UY",
    voiceHints: ["uruguay", "es-uy", "mateo", "valentina"],
    color: "#6fe8d8",
    x: 53,
    y: 81,
    city: "Montevideo",
    title: "La caminata que empezó con un mate",
    topic: "Rambla, perros y una conversación tranquila",
    speaker: "Voz uruguaya · ritmo relajado",
    speed: 0.94,
    pitch: 0.98,
    script: "El sábado de tarde estaba en casa sin saber qué hacer. Mi vecino Martín me escribió y me preguntó si quería caminar por la rambla. Preparé el mate, agarré una campera liviana y bajé. Martín llegó con su perro, un animal enorme pero muy tranquilo. Caminamos cerca de una hora mientras hablábamos del trabajo y de nuestros planes para el verano. Después nos sentamos frente al río y compartimos unas galletas. El perro se quedó dormido a nuestros pies. No hicimos nada extraordinario, pero volví a casa con la cabeza mucho más despejada. A veces salir un rato es suficiente.",
    glossary: [
      { word: "rambla", meaning: "paseo junto al agua en Montevideo" },
      { word: "campera", meaning: "chaqueta" },
      { word: "con la cabeza despejada", meaning: "más tranquilo y con menos preocupaciones" },
    ],
    questions: [
      { prompt: "¿Cuándo ocurre la historia?", options: ["El sábado de tarde", "El domingo de mañana", "El viernes de noche"], answer: 0, feedback: "Ocurre el sábado de tarde." },
      { prompt: "¿Quién propuso la caminata?", options: ["La persona que habla", "Martín", "Un compañero de trabajo"], answer: 1, feedback: "El vecino Martín propuso caminar." },
      { prompt: "¿Dónde iban a caminar?", options: ["Por el centro", "Por un parque", "Por la rambla"], answer: 2, feedback: "Iban a caminar por la rambla." },
      { prompt: "¿Qué preparó antes de bajar?", options: ["El mate", "Un café", "La cena"], answer: 0, feedback: "Preparó el mate." },
      { prompt: "¿Con quién llegó Martín?", options: ["Con su hermano", "Con su perro", "Con una amiga"], answer: 1, feedback: "Martín llegó con su perro." },
      { prompt: "¿Cómo era el perro?", options: ["Pequeño y nervioso", "Enorme y tranquilo", "Viejo y ruidoso"], answer: 1, feedback: "Era enorme, pero muy tranquilo." },
      { prompt: "¿Cuánto caminaron?", options: ["Media hora", "Cerca de una hora", "Dos horas"], answer: 1, feedback: "Caminaron cerca de una hora." },
      { prompt: "¿De qué hablaron?", options: ["De trabajo y planes de verano", "De política", "De fútbol solamente"], answer: 0, feedback: "Hablaron del trabajo y de sus planes para el verano." },
      { prompt: "¿Qué compartieron frente al río?", options: ["Unas galletas", "Un sándwich", "Fruta"], answer: 0, feedback: "Compartieron unas galletas." },
      { prompt: "¿Cómo volvió a casa?", options: ["Más preocupado", "Con la cabeza despejada", "Muy apurado"], answer: 1, feedback: "Volvió con la cabeza mucho más despejada." },
    ],
  },
  {
    id: "republica-dominicana",
    name: "República Dominicana",
    flag: "🇩🇴",
    locale: "es-DO",
    voiceHints: ["dominican", "dominicana", "es-do", "ramona"],
    color: "#ff8fcf",
    x: 40,
    y: 25,
    city: "Santo Domingo",
    title: "La fiesta que casi empezó sin música",
    topic: "Familia, tecnología y una solución rápida",
    speaker: "Voz dominicana · ritmo vivo",
    speed: 0.91,
    pitch: 1.03,
    script: "El viernes celebramos el cumpleaños de mi abuela en el patio de su casa. Toda la familia llevó comida y mi primo Andrés era responsable de la música. Cuando llegaron los invitados, él conectó su teléfono al parlante, pero no sonó nada. Probó otro cable, apagó el teléfono y volvió a encenderlo. Nada. Mi abuela se empezó a reír y dijo que podíamos cantar nosotros. En ese momento, una vecina apareció con un parlante pequeño que funcionaba perfectamente. Pusimos merengue, movimos las mesas y empezamos a bailar. Al final, el problema se convirtió en la mejor parte de la historia.",
    glossary: [
      { word: "parlante", meaning: "altavoz" },
      { word: "merengue", meaning: "música y baile tradicional del Caribe" },
      { word: "se convirtió en", meaning: "terminó siendo" },
    ],
    questions: [
      { prompt: "¿Qué celebraba la familia?", options: ["Una boda", "El cumpleaños de la abuela", "Un aniversario"], answer: 1, feedback: "Celebraban el cumpleaños de la abuela." },
      { prompt: "¿Dónde fue la celebración?", options: ["En un salón", "En una playa", "En el patio de la casa"], answer: 2, feedback: "Fue en el patio de la casa de la abuela." },
      { prompt: "¿Quién era responsable de la música?", options: ["Andrés", "La vecina", "La abuela"], answer: 0, feedback: "El primo Andrés era responsable de la música." },
      { prompt: "¿Qué aparato no funcionaba?", options: ["El televisor", "El parlante", "La computadora"], answer: 1, feedback: "El parlante no reproducía sonido." },
      { prompt: "¿Qué hizo Andrés con el teléfono?", options: ["Lo guardó", "Lo apagó y volvió a encender", "Lo cambió por otro"], answer: 1, feedback: "Apagó el teléfono y volvió a encenderlo." },
      { prompt: "¿Cómo reaccionó la abuela?", options: ["Se enojó", "Se fue", "Se empezó a reír"], answer: 2, feedback: "La abuela se empezó a reír." },
      { prompt: "¿Qué solución propuso la abuela?", options: ["Cantar ellos mismos", "Cancelar la fiesta", "Escuchar la radio"], answer: 0, feedback: "Dijo que podían cantar ellos mismos." },
      { prompt: "¿Quién trajo otro parlante?", options: ["Un invitado", "Una vecina", "Andrés"], answer: 1, feedback: "Una vecina apareció con otro parlante." },
      { prompt: "¿Qué música pusieron?", options: ["Merengue", "Rock", "Tango"], answer: 0, feedback: "Pusieron merengue." },
      { prompt: "¿Qué pasó con el problema al final?", options: ["Arruinó la fiesta", "Nadie lo recordó", "Se convirtió en una buena historia"], answer: 2, feedback: "El problema se convirtió en la mejor parte de la historia." },
    ],
  },
  {
    id: "costa-rica",
    name: "Costa Rica",
    flag: "🇨🇷",
    locale: "es-CR",
    voiceHints: ["costa rica", "es-cr", "juan", "maría"],
    color: "#77e47d",
    x: 27,
    y: 33,
    city: "San José",
    title: "Una visita con lluvia y perezosos",
    topic: "Naturaleza, paciencia y un viaje corto",
    speaker: "Voz costarricense · ritmo sereno",
    speed: 0.93,
    pitch: 1.01,
    script: "El mes pasado fui con dos amigos a un refugio de animales cerca de San José. Salimos temprano porque la visita empezaba a las nueve. En el camino comenzó a llover muy fuerte y el tránsito avanzaba lentísimo. Pensamos que íbamos a perder la entrada, pero llamamos al refugio y nos dijeron: tranquilos, pura vida, los esperamos. Llegamos veinte minutos tarde. Una guía nos explicó cómo cuidan a los perezosos y por qué no debemos tocarlos. También vimos monos y varias aves de colores. La lluvia siguió toda la mañana, pero a nadie le importó. Fue una visita corta y muy especial.",
    glossary: [
      { word: "refugio de animales", meaning: "lugar que protege y cuida animales" },
      { word: "pura vida", meaning: "expresión costarricense de saludo, calma o aprobación" },
      { word: "perezoso", meaning: "animal que se mueve muy lentamente" },
    ],
    questions: [
      { prompt: "¿Adónde fueron?", options: ["A un refugio de animales", "A un museo", "A una finca de café"], answer: 0, feedback: "Fueron a un refugio de animales." },
      { prompt: "¿Cuántos amigos acompañaron a la persona?", options: ["Uno", "Dos", "Tres"], answer: 1, feedback: "Fue con dos amigos." },
      { prompt: "¿A qué hora empezaba la visita?", options: ["A las ocho", "A las nueve", "A las diez"], answer: 1, feedback: "La visita empezaba a las nueve." },
      { prompt: "¿Qué pasó durante el camino?", options: ["Se perdieron", "Empezó a llover fuerte", "El auto se rompió"], answer: 1, feedback: "Comenzó a llover muy fuerte." },
      { prompt: "¿Cómo avanzaba el tránsito?", options: ["Muy rápido", "Normal", "Muy lentamente"], answer: 2, feedback: "El tránsito avanzaba lentísimo." },
      { prompt: "¿Qué hicieron antes de llegar?", options: ["Llamaron al refugio", "Compraron otra entrada", "Volvieron a casa"], answer: 0, feedback: "Llamaron al refugio." },
      { prompt: "¿Cuánto tarde llegaron?", options: ["Diez minutos", "Veinte minutos", "Cuarenta minutos"], answer: 1, feedback: "Llegaron veinte minutos tarde." },
      { prompt: "¿Qué explicó la guía?", options: ["Cómo alimentar monos", "Cómo cuidan a los perezosos", "Cómo plantar árboles"], answer: 1, feedback: "Explicó cómo cuidan a los perezosos." },
      { prompt: "¿Por qué no deben tocar a los perezosos?", options: ["La guía explicó que no se debe", "Porque estaban dormidos", "Porque no había tiempo"], answer: 0, feedback: "La guía explicó por qué no debemos tocarlos." },
      { prompt: "¿Cómo fue la visita?", options: ["Larga y aburrida", "Corta y especial", "Cara y difícil"], answer: 1, feedback: "Fue una visita corta y muy especial." },
    ],
  },
  {
    id: "cuba",
    name: "Cuba",
    flag: "🇨🇺",
    locale: "es-CU",
    voiceHints: ["cuba", "es-cu", "caribbean"],
    color: "#ff8b58",
    x: 32,
    y: 21,
    city: "La Habana",
    title: "La foto que apareció veinte años después",
    topic: "Familia, memoria y una caja antigua",
    speaker: "Voz cubana · ritmo cálido",
    speed: 0.91,
    pitch: 1.02,
    script: "El fin de semana ayudé a mi padre a ordenar un armario en casa de mi abuela. Había cajas con libros, ropa y objetos que nadie usaba desde hacía años. Dentro de una caja pequeña encontramos una cámara antigua. Mi padre pensó que estaba vacía, pero todavía tenía un rollo de fotos. Lo llevamos a una tienda para ver si podían revelarlo. Dos días después nos llamaron. Entre las fotos había una imagen de toda la familia en una playa, hace más de veinte años. Mi abuela no recordaba ese día, pero reconoció su vestido inmediatamente. Ahora la foto está en la sala.",
    glossary: [
      { word: "armario", meaning: "mueble para guardar ropa u objetos" },
      { word: "rollo de fotos", meaning: "película usada por cámaras antiguas" },
      { word: "revelar", meaning: "hacer visibles las fotos de un rollo" },
    ],
    questions: [
      { prompt: "¿A quién ayudó la persona?", options: ["A su padre", "A su hermano", "A una amiga"], answer: 0, feedback: "Ayudó a su padre." },
      { prompt: "¿Dónde estaban ordenando?", options: ["En una tienda", "En casa de la abuela", "En una oficina"], answer: 1, feedback: "Ordenaban un armario en casa de la abuela." },
      { prompt: "¿Qué había en las cajas?", options: ["Solo documentos", "Comida", "Libros, ropa y objetos"], answer: 2, feedback: "Había libros, ropa y objetos antiguos." },
      { prompt: "¿Qué encontraron en una caja pequeña?", options: ["Una cámara antigua", "Una radio", "Un reloj"], answer: 0, feedback: "Encontraron una cámara antigua." },
      { prompt: "¿Qué tenía todavía la cámara?", options: ["Una foto digital", "Un rollo de fotos", "Una batería nueva"], answer: 1, feedback: "Todavía tenía un rollo de fotos." },
      { prompt: "¿Adónde llevaron el rollo?", options: ["A una tienda", "A la escuela", "A un museo"], answer: 0, feedback: "Lo llevaron a una tienda." },
      { prompt: "¿Cuándo los llamaron?", options: ["Ese mismo día", "Dos días después", "Una semana después"], answer: 1, feedback: "Los llamaron dos días después." },
      { prompt: "¿Dónde estaba la familia en la foto?", options: ["En una fiesta", "En una playa", "En un parque"], answer: 1, feedback: "La familia estaba en una playa." },
      { prompt: "¿Qué reconoció la abuela?", options: ["Su vestido", "La cámara", "Una casa"], answer: 0, feedback: "Reconoció su vestido inmediatamente." },
      { prompt: "¿Dónde está ahora la foto?", options: ["En una caja", "En la tienda", "En la sala"], answer: 2, feedback: "Ahora la foto está en la sala." },
    ],
  },
  {
    id: "bolivia",
    name: "Bolivia",
    flag: "🇧🇴",
    locale: "es-BO",
    voiceHints: ["bolivia", "es-bo"],
    color: "#e8d85c",
    x: 42,
    y: 61,
    city: "La Paz",
    title: "El regalo que subió en teleférico",
    topic: "Ciudad, altura y una entrega importante",
    speaker: "Voz boliviana · ritmo pausado",
    speed: 0.92,
    pitch: 0.99,
    script: "El martes era el cumpleaños de mi hermana y yo tenía que llevarle un regalo a su trabajo. Salí con tiempo, pero una avenida estaba cerrada y los autobuses casi no avanzaban. Como su oficina quedaba lejos, decidí usar el teleférico. Desde arriba vi toda la ciudad y las montañas estaban clarísimas. El viaje fue más rápido de lo que esperaba, aunque tuve que cambiar de línea una vez. Llegué cinco minutos antes de que mi hermana saliera a almorzar. Cuando abrió la bolsa y vio el suéter que había elegido, sonrió y me abrazó. Después comimos juntos en un restaurante pequeño cerca de su oficina.",
    glossary: [
      { word: "teleférico", meaning: "transporte con cabinas que viajan por cables" },
      { word: "cambiar de línea", meaning: "pasar de una ruta de transporte a otra" },
      { word: "suéter", meaning: "prenda de abrigo para la parte superior del cuerpo" },
    ],
    questions: [
      { prompt: "¿Qué día era el cumpleaños?", options: ["El lunes", "El martes", "El jueves"], answer: 1, feedback: "El cumpleaños era el martes." },
      { prompt: "¿Para quién era el regalo?", options: ["Para su hermana", "Para su madre", "Para una compañera"], answer: 0, feedback: "El regalo era para su hermana." },
      { prompt: "¿Dónde tenía que llevar el regalo?", options: ["A una casa", "Al trabajo de su hermana", "A una tienda"], answer: 1, feedback: "Tenía que llevarlo al trabajo de su hermana." },
      { prompt: "¿Por qué los autobuses no avanzaban?", options: ["Había nieve", "Una avenida estaba cerrada", "No tenían pasajeros"], answer: 1, feedback: "Una avenida estaba cerrada." },
      { prompt: "¿Qué transporte decidió usar?", options: ["El teleférico", "Un taxi", "Una bicicleta"], answer: 0, feedback: "Decidió usar el teleférico." },
      { prompt: "¿Qué vio desde arriba?", options: ["El mar", "La ciudad y las montañas", "Un estadio"], answer: 1, feedback: "Vio toda la ciudad y las montañas." },
      { prompt: "¿Cuántas veces cambió de línea?", options: ["Ninguna", "Una vez", "Dos veces"], answer: 1, feedback: "Tuvo que cambiar de línea una vez." },
      { prompt: "¿Cuándo llegó?", options: ["Cinco minutos antes", "Media hora tarde", "Después del almuerzo"], answer: 0, feedback: "Llegó cinco minutos antes." },
      { prompt: "¿Qué había dentro de la bolsa?", options: ["Un libro", "Un suéter", "Unos zapatos"], answer: 1, feedback: "Dentro de la bolsa había un suéter." },
      { prompt: "¿Qué hicieron después?", options: ["Volvieron en autobús", "Comieron juntos", "Fueron de compras"], answer: 1, feedback: "Después comieron juntos cerca de la oficina." },
    ],
  },
];
