import {author,row as r} from '../schema.mjs';
export default author('B1',{
 name:'El foco de la conversación',demand:'Actitudes cotidianas, énfasis y reparación de malentendidos.',objective:'Explica qué intención escuchas y ajusta el énfasis para reparar un malentendido.',warmup:'Di «Yo lo pedí ayer». ¿Qué palabra destacarías para corregir quién lo pidió?',teacher:'Pide una explicación con evidencias auditivas y contexto. Separa volumen, altura y duración con ejemplos de tu propia voz.',avoid:'No sobrecorrijas vacilaciones normales ni trates una interpretación plausible como un error absoluto.',extension:'El interlocutor interpreta mal una frase: el alumno debe reformularla y volver a entregarla.'},[
 r('Una persona confirma una tarea. ¿Qué actitud favorece este cierre?','Ya le mandé el mensaje.',['Cierre decidido de la tarea','Pregunta abierta sobre el destinatario'],0,'La caída definida puede cerrar el asunto. No sabemos si la tarea ocurrió de verdad: oímos una entrega firme.','Responde a alguien que insiste en preguntarte. Luego responde a alguien que solo quiere información.','Pide explicar la diferencia sin convertir firmeza en mala educación.','firm'),
 r('Escucha una reacción ante un cambio de planes. ¿Cuál es una lectura posible?','Bueno, podemos intentarlo.',['Hay una aceptación con reservas','Hay una felicitación eufórica'],0,'El final sostenido deja espacio para condiciones. «Podemos» también evita una promesa absoluta.','Acepta una propuesta con una reserva y luego acéptala con entusiasmo.','Pide distinguir la pista de palabras de la entrega del audio.','suspended'),
 r('Dos tomas de una pregunta de confirmación. ¿Cuál pide más claramente una respuesta?','Lo vas a resolver hoy.',['Toma A','Toma B'],1,'La subida final abre la confirmación; la caída puede sonar como expectativa ya establecida.','Di la frase como pregunta genuina y como recordatorio de un compromiso.','Agrega el contexto antes de decidir si el recordatorio resulta amable.','question','firm'),
 r('Escucha el movimiento de la voz. ¿Qué hace dentro de la frase?','Yo lo pedí ayer.',['Da relieve a una parte del mensaje','Mantiene la misma altura de principio a fin'],0,'El relieve central destaca una parte del mensaje. El foco en una palabra concreta debe compararse en contexto con el modelo del profe.','Corrige primero quién hizo el pedido y después cuándo lo hizo, sin agregar palabras.','Modela el foco léxico con el alumno: el contorno sintético no certifica una lectura única de foco.','contrast'),
 r('Escucha y practica una respuesta que tranquiliza.','Todavía tenemos tiempo.',null,null,'Una caída suave puede ayudar a tranquilizar. Un descenso brusco en otra situación podría cerrar la discusión.','Tu profe está preocupado por llegar tarde. Responde y justifica con una frase breve.','Pide al interlocutor que diga si se sintió acompañado y por qué.','reassurance'),
 r('Alguien piensa que estás enojado. ¿Qué toma favorece una respuesta más acompañada?','No pasa nada, lo hablamos.',['Toma A','Toma B'],0,'La toma de rango más amplio y descenso suave puede favorecer una lectura tranquilizadora. La otra deja mayor distancia.','Usa cada versión en una escena. Explica qué lectura sería posible en cada una.','Si oye otra actitud, pide evidencia y compara tu propia entrega.','reassurance','distance'),
 r('Escucha el desacuerdo y ensaya dos énfasis.','No dije que fuera imposible.',null,null,'Destacar «dije» o «imposible» puede orientar dos correcciones distintas. La frase por sí sola no fija el foco.','Primero corrige lo que alguien cree que dijiste. Después enfatiza que todavía hay una posibilidad.','Repite sin mostrar texto al principio. Abre apoyo solo para ubicar palabras difíciles.','contrast'),
 r('Escucha una respuesta y prepara una reparación en contexto.','Me parece que no me entendiste.',null,null,'La misma frase puede abrir una aclaración o sonar como reproche. La voz y lo que viene después cambian el efecto.','Tu profe confunde tu plan de viaje. Aclara con esta frase, explica el dato y comprueba que quedó claro.','Haz un malentendido realista y devuelve la intención que percibiste.','warm'),
 r('Opcional: ¿qué lectura favorece esta reacción en una charla cotidiana?','Ah, eso cambia las cosas.',['Reacción ante un dato inesperado','Cierre de una despedida'],0,'El arco amplio destaca una novedad. No basta para saber si la novedad es buena o mala.','Recibe un dato favorable y otro problemático usando la misma frase.','Trabaja ambas lecturas en lugar de reducir sorpresa a alegría.','surprise'),
 r('Opcional: te ofrecen una solución. ¿Qué hace esta respuesta?','Sí, podría funcionar así.',['Deja la solución en evaluación','La rechaza de manera explícita'],0,'Una suspensión puede dejar abierta la evaluación; no expresa un rechazo literal.','Pide una condición antes de aceptar. Luego usa la misma frase para dar un acuerdo seguro.','Observa cómo el alumno enlaza la actitud con el turno siguiente.','doubt'),
],{prompt:'Repara un malentendido sin cambiar la idea.',steps:['Tu profe interpreta mal quién hizo un pedido o para cuándo era. Prepara una respuesta de tres frases con un foco claro.','Responde sin leer y pregunta qué corrección entendió. Después usa una entrega más cálida.','Recibe una devolución y repite una frase destacando una palabra diferente. Explica el nuevo efecto.'],support:'Yo lo pedí… / No dije que… / Lo que quería decir era…',criteria:['El énfasis permite reconocer qué dato se está corrigiendo.','La actitud de la respuesta encaja con la relación entre interlocutores.','Explica un cambio de foco y lo prueba en una segunda entrega.']});
