import {author,row as r} from '../schema.mjs';
export default author('B2',{
 name:'Lo que se insinúa',demand:'Contexto más rico, dos lecturas plausibles y justificación de la entrega.',objective:'Compará escepticismo, insistencia y tranquilidad; justificá qué entrega conviene a cada situación.',warmup:'Decí «Eso está resuelto» para tranquilizar y después para cerrar una discusión.',teacher:'Pedí evidencias de altura, duración y cierre sin imponer una interpretación única. Contrastá audio sintético y una entrega situada del profe.',avoid:'No uses la entonación como prueba de sinceridad, enfado o engaño. Puede haber lecturas diferentes con el mismo contorno.',extension:'Cambiá la relación de poder: colega, jefe o cliente; reformulá el efecto interpersonal.'},[
 r('Un colega propone una solución rápida. ¿Qué lectura favorece esta entrega?','Eso podría funcionar, supongo.',['Aceptación con cierta reserva','Celebración sin ninguna reserva'],0,'La suspensión y «supongo» favorecen una lectura cautelosa. La duda no implica rechazo.','Respondé a una idea arriesgada y después a una idea que ya probaste. Conservá el texto.','Pedí dos evidencias distintas y una lectura alternativa.','doubt'),
 r('Un amigo teme que el problema continúe. ¿Qué interpretación encaja mejor?','Está resuelto, podés quedarte tranquilo.',['Busca tranquilizarlo','Busca cerrar el tema con impaciencia'],0,'El descenso acompañado puede apoyar una intención tranquilizadora. Las palabras dan una pista adicional.','Tranquilizá a tu amigo. Después decí la misma frase para poner fin a preguntas repetidas.','La segunda entrega puede ser firme sin ser hostil.','reassurance'),
 r('La reunión se alarga. ¿Qué toma encaja mejor con cerrar el tema de manera firme?','Entonces seguimos con el próximo punto.',['Toma A','Toma B'],0,'La caída definida cierra el turno y orienta al siguiente punto; una suspensión puede invitar a esperar una objeción.','Cerrá la discusión con firmeza y luego dejá espacio para una última intervención.','Preguntá qué cambio del final modifica el derecho a responder.','firm','suspended'),
 r('Una promesa llega después de varios retrasos. ¿Qué lectura admite este modelo?','Esta vez va a estar listo.',['Afirmación con relieve enfático','Presentación neutral sin relieve marcado'],0,'El arco de relieve puede dar fuerza a la promesa. Si viene del cliente, la misma entrega podría sonar insistente.','Decilo como promesa y como advertencia. Justificá con el contexto quién habla.','No identifiques una emoción sin saber el papel del hablante.','contrast'),
 r('Escuchá y ensayá un desacuerdo que conserva el vínculo.','Entiendo tu punto, pero no lo veo igual.',null,null,'La primera parte puede reconocer al otro; la segunda introduce contraste. La transición de voz ayuda a organizarlo.','Discrepá con un amigo sobre un plan. Después usá más firmeza con alguien que insiste.','Modelá un cambio local de tono en «pero», no solo un cambio global de altura.','warm'),
 r('Un cliente necesita una garantía. ¿Qué toma puede sonar más acompañada en este contexto?','Lo revisamos juntos antes de enviarlo.',['Toma A','Toma B'],1,'El descenso suave puede ofrecer acompañamiento; un cierre más seco puede sonar procedural. Ambas entregas pueden ser válidas.','Elegí una entrega para un cliente nervioso y otra para un equipo con prisa. Explicá el costo de cada elección.','Aceptá preferencias justificadas; no conviertas las tomas en un examen de emociones universales.','reassurance','firm'),
 r('Escuchá y cambiá la interpretación mediante énfasis y cierre.','No es exactamente lo que habíamos acordado.',null,null,'El relieve puede señalar una discrepancia concreta. Un rango estrecho también puede transmitir distancia, según la escena.','Decí la frase como invitación a revisar y como objeción insistente. Cambiá la palabra destacada.','El alumno explica qué quiere que el otro haga después.','contrast'),
 r('Escuchá una propuesta y negociá su entrega.','Podemos resolverlo si ajustamos el plazo.',null,null,'La condición ofrece un camino. La voz puede hacerlo sonar tranquilizador o como límite no negociable.','Negociá un retraso con tu profe: ofrecé solución, insistí en la condición y cerrá sin atacar al otro.','Devolvé cómo llegó el límite y pedí una versión más flexible.','reassurance'),
 r('Opcional: ¿qué lectura resulta plausible después de una promesa dudosa?','Sí, claro, sería ideal.',['Aceptación todavía distante','Aceptación cálida y sin reservas'],0,'Un rango estrecho puede favorecer distancia, pero la ironía requiere contexto y otras pistas.','Ensayá una lectura sincera y una escéptica. Decí qué contexto necesita cada una.','No presentes el modelo como ironía verificada.','distance'),
 r('Opcional: escuchá el cierre. ¿Qué respuesta deja disponible?','Podemos seguir, si les parece.',['Invita a confirmar el avance','Anuncia una decisión sin pedir conformidad'],0,'La subida final puede pedir conformidad. La cortesía también está en «si les parece».','Pedí conformidad y luego anunciá el avance como decisión ya tomada.','Diferenciá efecto prosódico y fórmula de cortesía.','question'),
],{prompt:'Dos entregas para una negociación difícil.',steps:['Elegí «Podemos resolverlo si ajustamos el plazo» u otra frase propia. Prepará una entrega que tranquilice y otra que insista en el límite.','Decí ambas sin leer dentro de dos mini diálogos. Tu profe explica qué disposición a negociar percibió.','Justificá altura, énfasis y cierre elegidos; incorporá una devolución y hacé una tercera entrega.'],support:'Contexto → intención → palabra destacada → final de la voz → respuesta esperada.',criteria:['Las dos entregas crean un contraste perceptible y adecuado al contexto.','Justifica la elección con evidencias de voz y consecuencias para el interlocutor.','Ajusta la entrega después de una devolución sin perder la idea central.']});
