import {author,row as r} from '../schema.mjs';
export default author('C1',{
 name:'La relación también se escucha',demand:'Postura, atenuación, ironía contextual y cambios locales de tono.',objective:'Reformulá una entrega para cambiar su efecto interpersonal y defendé una lectura contextual.',warmup:'Decí «No era mi intención» como aclaración y como defensa. ¿Qué respuesta esperás provocar?',teacher:'Pedí hipótesis alternativas y una evidencia auditiva para cada una. Usá tu voz para enriquecer matices que los modelos sintéticos solo esquematizan.',avoid:'No penalices una lectura alternativa bien fundamentada ni igualés rango estrecho con ironía de manera automática.',extension:'Insertá un comentario entre paréntesis en el mismo mensaje y distinguí su tono del argumento principal.'},[
 r('Tras una crítica, escuchá la respuesta. ¿Qué postura favorece el contexto?','No era mi intención cuestionar tu trabajo.',['Aclaración que busca bajar la tensión','Defensa que marca distancia y cierra la discusión'],0,'La caída acompañada puede sostener una aclaración. Un cierre brusco podría sonar defensivo con el mismo texto.','Ensayá una aclaración reparadora y una defensa distante; explicá qué respuesta buscás.','Preguntá qué parte de la frase debería suavizarse y cuál conservar su firmeza.','reassurance'),
 r('Un colega anuncia otra solución milagrosa. ¿Qué lectura es plausible, sin darla por segura?','Bueno, parece que esta vez sí encontraron la solución.',['Reserva o distancia frente al anuncio','Reconocimiento cálido y sin reservas'],0,'Un rango estrecho puede acompañar distancia. La posible ironía depende de la historia de fracasos y de otras pistas.','Decí la frase como reconocimiento sincero y como distancia irónica leve. Aportá el contexto necesario.','Contrastá una lectura literal; no enseñes que la voz diagnostica ironía.','distance'),
 r('Querés disentir sin cerrar el diálogo. ¿Qué toma deja mayor espacio para responder?','Quizás convendría revisar ese supuesto.',['Toma A','Toma B'],1,'La suspensión puede dejar la propuesta abierta. Un cierre firme puede convertirla en recomendación más directiva.','Usá cada toma al hablar con un colega y con alguien a cargo del proyecto.','Pedí justificar también cuándo convendría la versión firme.','suspended','firm'),
 r('En una discusión, escuchá esta concesión. ¿Qué función puede cumplir?','En ese punto te doy la razón.',['Concede un punto sin conceder necesariamente todo','Retira explícitamente todas las objeciones'],0,'El relieve puede delimitar el alcance de la concesión. No afirma que el hablante abandone otras objeciones.','Destacá «ese punto» y luego «te doy la razón». Explicá cómo cambia el alcance que querés sugerir.','El modelo no fija por sí solo el foco: pedí al alumno ubicarlo con una nueva entrega.','contrast'),
 r('Escuchá el mensaje y separá el comentario lateral de la idea principal.','El plan, por lo que entiendo, sigue en marcha.',null,null,'El inciso puede usar un rango distinto y pausas para marcar una cautela. No es necesario cortar todas sus palabras.','Decí la frase con el inciso más bajo y después integrado en el tono principal. Compará el efecto de cautela.','Modelá tú mismo el inciso: el audio es un punto de partida sintético, no una muestra certificada de ese cambio local.','neutral'),
 r('Una persona acaba de admitir un error. ¿Qué toma favorece una reparación acompañada?','Podemos revisarlo sin convertirlo en un problema mayor.',['Toma A','Toma B'],0,'La caída suave y más amplia puede acompañar la reparación. El rango estrecho puede resultar más distante en esta escena.','Reformulá solo la entrega para ofrecer ayuda y luego para marcar un límite institucional.','Pedí al interlocutor describir el efecto, evitando etiquetas de personalidad.','reassurance','distance'),
 r('Escuchá y ensayá una discrepancia delicada.','No sé si ese es el mejor momento para plantearlo.',null,null,'La cautela puede venir de «no sé si» y de una suspensión. Un cierre enfático puede fortalecer la objeción.','Decilo para cuidar a un colega y luego para frenar una intervención. Conservá las palabras.','Observá si el cambio altera la invitación a responder.','doubt'),
 r('Escuchá una aclaración y cambiá el efecto interpersonal del mensaje.','Lo que propongo es revisar el criterio, no el esfuerzo del equipo.',null,null,'El contraste delimita qué se cuestiona. Una entrega reparadora puede evitar que suene como descalificación.','Tu profe escucha una crítica personal donde intentabas revisar un criterio. Aclará y comprobá qué entiende ahora.','Hacé la primera interpretación de buena fe; el alumno debe reparar, no imponerse.','contrast'),
 r('Opcional: ¿qué postura deja abierta este final?','No digo que sea imposible, solo que habría que pensarlo.', ['Cautela ante una decisión','Cierre tajante que evita seguir considerando la decisión'],0,'La suspensión acompaña una reserva y deja disponible una elaboración. No equivale a una negativa total.','Fortalecé la objeción sin cambiar el texto; después volvé a atenuarla.','Pedí describir el cambio con altura, cierre y duración.','suspended'),
 r('Opcional: un proyecto se retrasó tres veces. ¿Qué lectura podría favorecer esta entrega?','Qué oportuno que aparezca la solución justo ahora.', ['Distancia irónica posible en este contexto','Agradecimiento cálido por una solución esperada'],0,'El contexto hace plausible una lectura irónica. El rango de voz aislado no la demuestra y admite una lectura literal.','Construí dos contextos que permitan interpretar la frase literalmente o con ironía leve.','Si la lectura no se distingue, modelá otra entrega sin atribuir fracaso al alumno.','distance'),
],{prompt:'Reencuadrá una crítica para cuidar el vínculo.',steps:['Prepará un mensaje de tres frases sobre un criterio que necesita revisión. Incluí una concesión, una cautela o un inciso breve.','Entregalo como objeción firme y luego como invitación a colaborar, manteniendo la idea principal. Tu profe responde según el efecto que percibe.','Explicá qué modificaste en foco, tono del inciso y cierre. Recibí una devolución y ensayá una versión equilibrada.'],support:'En ese punto… / Lo que propongo es… / Por lo que entiendo… / Quizás convendría…',criteria:['Mantiene la postura mientras modifica el efecto interpersonal.','Distingue el tono de un inciso o de una concesión del argumento principal.','Defiende una lectura contextual y acepta otras interpretaciones justificadas.']});
