import {author,row as r} from '../schema.mjs';
export default author('C2',{
 name:'Una voz, varias lecturas',demand:'Control retórico, ambigüedad deliberada y capas de significado pragmático.',objective:'Entrega un mismo contenido de varias maneras y explica cómo cambia lo que el interlocutor puede inferir.',warmup:'Di «Eso dice mucho» como elogio, reserva y comentario deliberadamente ambiguo. ¿Qué contexto resuelve cada lectura?',teacher:'Trabaja decisiones de entrega y consecuencias discursivas. Admite ambigüedad deliberada y compara inferencias, sin fingir que una voz sintética reproduce todas las capas pragmáticas.',avoid:'No conviertas C2 en hablar más rápido. No impongas una sola lectura a una ironía o ambigüedad bien construida.',extension:'Pide mantener una ambigüedad en el primer turno y resolverla únicamente con el tono del segundo.'},[
 r('Tras un informe que el equipo esperaba, escucha la frase. ¿Qué puede favorecer esta entrega?','Eso dice bastante sobre nuestras prioridades.', ['Cierre retórico que invita a inferir una valoración','Reflexión suspendida que deja abierta la valoración'],0,'Un arco amplio con cierre definido puede dar peso a la valoración. El contexto decide si es aprobación o crítica.','Entrega el mismo texto como elogio y como reproche contenido, sin agregar adjetivos.','Pide precisar qué inferencia busca activar cada entrega.','rhetorical'),
 r('Una promesa llega después de varios incumplimientos. ¿Qué conclusión es defendible?','Naturalmente, ahora sí podemos confiar en el procedimiento.', ['La distancia irónica es una lectura posible','Confianza literal con calidez y cierre tranquilizador'],0,'Un rango estrecho en esta historia puede favorecer distancia irónica, pero no demuestra predicciones ni intenciones internas.','Actúa una confianza literal y una confianza puesta en duda. Explica qué pista adicional necesita el oyente.','Si el contraste sintético resulta insuficiente, modela ambos en vivo y compara.','distance'),
 r('Quieres cerrar una intervención sin impedir una réplica. ¿Qué toma mantiene más abierta esa réplica?','Y esa es la cuestión que nos queda por resolver.', ['Toma A','Toma B'],0,'El final suspendido puede dejar la palabra disponible; el cierre descendente da más peso a una conclusión.','Usa una versión para abrir debate y otra para cerrar una exposición. Justifica el efecto retórico.','Acepta que el turno también depende de mirada, pausa y normas de la conversación.','suspended','rhetorical'),
 r('Después de una respuesta ambigua, escucha esta concesión. ¿Qué inferencia sigue abierta?','No podría decir que me sorprende.',['Puede sugerir expectativa previa sin valorar todavía el hecho','Acogida cálida de una noticia que da ganas de celebrar'],0,'La reserva deja implícita una expectativa previa. La voz puede matizar distancia, delicadeza o reproche; el texto no fija una emoción.','Dilo con delicadeza ante un error y con distancia ante una maniobra previsible.','Pide explicar qué inferencia permanece y cuál cambia.','distance'),
 r('Escucha y ensaya una ambigüedad que luego puedas resolver.','Si eso es lo que querían, lo consiguieron.',null,null,'El texto admite felicitación o reproche. La entrega, el foco y la pausa pueden orientar la lectura sin explicitarla.','Haz una primera entrega ambigua y una segunda que la resuelva como reconocimiento. Después resuélvela como reproche.','No pidas caricatura ni sarcasmo exagerado: evalúa si el interlocutor percibe el cambio.','neutral'),
 r('Un equipo necesita una invitación que no suene a ultimátum. ¿Qué toma favorece esa apertura?','Todavía podemos elegir cómo terminar esta historia.',['Toma A','Toma B'],1,'El descenso suave puede favorecer apertura acompañada. El arco retórico más cerrado puede dar fuerza de conclusión.','Usa ambos como invitación, y después uno como advertencia. Explica qué contexto transforma su efecto.','No confundas una entrega persuasiva con manipulación: trabaja la respuesta que habilita.','reassurance','rhetorical'),
 r('Escucha y altera el relieve de una misma valoración.','Lo significativo no es el resultado, sino cómo llegamos a él.',null,null,'El contraste puede redistribuir importancia entre resultado y proceso. Una pausa y un cambio local de rango pueden organizar esa jerarquía.','Entrega el mensaje como análisis, como defensa y como crítica velada. Elige un foco distinto en cada versión.','Pide describir dónde comienza el segundo miembro y qué información presupone.','contrast'),
 r('Escucha una propuesta y prepara tres efectos pragmáticos.','Podríamos dejarlo aquí, si todos estamos de acuerdo.',null,null,'La frase puede ofrecer consenso, cerrar por cansancio o invitar a una objeción pendiente. Ninguna lectura se prueba solo con el contorno.','Tu profe representa una reunión tensa. Cierra con delicadeza, repite con autoridad y abre después un espacio real de desacuerdo.','Devuelve qué derecho a responder oyó en cada entrega.','suspended'),
 r('Opcional: ¿qué admite este comentario después de un desenlace inesperado?','Al final, todo quedó exactamente donde debía quedar.',['Una valoración cuya orientación requiere contexto','Inicio suspendido de una reflexión todavía abierta'],0,'El arco retórico da relieve al desenlace; puede servir a resignación, satisfacción o distancia según la escena.','Propón tres contextos y elige una entrega distinta para cada uno.','Evalúa control expresivo e inferencia, no una emoción obligatoria.','rhetorical'),
 r('Opcional: escucha el cierre de este comentario. ¿Qué efecto favorece?','Hay maneras de decirlo y maneras de hacerlo.', ['Deja disponible una implicación que el oyente debe completar','Cierra la valoración con una caída concluyente'],0,'La suspensión puede mantener una implicación abierta. La insinuación concreta depende del intercambio previo.','Deja la implicación abierta y luego ciérrala con una entrega más definida, sin agregar palabras.','Pide al oyente verbalizar dos inferencias posibles y explicar cuál descartó.','suspended'),
],{prompt:'El mismo mensaje, tres interpretaciones pragmáticas.',steps:['Prepara un texto breve de dos o tres frases sobre una decisión. Elige tres efectos: invitación sincera, distancia delicada y cierre persuasivo; puedes proponer otros.','Entrega el mismo texto tres veces sin leer, en contextos explícitos. Tu profe dice qué pudo inferir y qué quedó ambiguo.','Defiende tus decisiones de foco, rango, pausa y cierre. Recibe una objeción y rehaz una versión para resolver o conservar la ambigüedad deliberadamente.'],support:'Contenido constante → contexto → postura → inferencia buscada → entrega → interpretación observada.',criteria:['Mantiene el contenido y crea tres efectos pragmáticos distinguibles en contexto.','Explica las capas de interpretación y controla una ambigüedad de forma deliberada.','Ajusta la entrega con precisión después de contrastar su intención con la lectura del oyente.']});
