import {author,row as r} from '../schema.mjs';
export default author('C2',{
 name:'Una voz, varias lecturas',demand:'Control retórico, ambigüedad deliberada y capas de significado pragmático.',objective:'Entregá un mismo contenido de varias maneras y explicá cómo cambia lo que el interlocutor puede inferir.',warmup:'Decí «Eso dice mucho» como elogio, reserva y comentario deliberadamente ambiguo. ¿Qué contexto resuelve cada lectura?',teacher:'Trabajá decisiones de entrega y consecuencias discursivas. Admití ambigüedad deliberada y compará inferencias, sin fingir que una voz sintética reproduce todas las capas pragmáticas.',avoid:'No conviertas C2 en hablar más rápido. No impongas una sola lectura a una ironía o ambigüedad bien construida.',extension:'Pedí mantener una ambigüedad en el primer turno y resolverla únicamente con el tono del segundo.'},[
 r('Tras un informe que el equipo esperaba, escuchá la frase. ¿Qué puede favorecer esta entrega?','Eso dice bastante sobre nuestras prioridades.', ['Cierre retórico que invita a inferir una valoración','Reflexión suspendida que deja abierta la valoración'],0,'Un arco amplio con cierre definido puede dar peso a la valoración. El contexto decide si es aprobación o crítica.','Entregá el mismo texto como elogio y como reproche contenido, sin agregar adjetivos.','Pedí precisar qué inferencia busca activar cada entrega.','rhetorical'),
 r('Una promesa llega después de varios incumplimientos. ¿Qué conclusión es defendible?','Naturalmente, ahora sí podemos confiar en el procedimiento.', ['La distancia irónica es una lectura posible','Confianza literal con calidez y cierre tranquilizador'],0,'Un rango estrecho en esta historia puede favorecer distancia irónica, pero no demuestra predicciones ni intenciones internas.','Actuá una confianza literal y una confianza puesta en duda. Explicá qué pista adicional necesita el oyente.','Si el contraste sintético resulta insuficiente, modelá ambos en vivo y compará.','distance'),
 r('Querés cerrar una intervención sin impedir una réplica. ¿Qué toma mantiene más abierta esa réplica?','Y esa es la cuestión que nos queda por resolver.', ['Toma A','Toma B'],0,'El final suspendido puede dejar la palabra disponible; el cierre descendente da más peso a una conclusión.','Usá una versión para abrir debate y otra para cerrar una exposición. Justificá el efecto retórico.','Aceptá que el turno también depende de mirada, pausa y normas de la conversación.','suspended','rhetorical'),
 r('Después de una respuesta ambigua, escuchá esta concesión. ¿Qué inferencia sigue abierta?','No podría decir que me sorprende.',['Puede sugerir expectativa previa sin valorar todavía el hecho','Acogida cálida de una noticia que da ganas de celebrar'],0,'La reserva deja implícita una expectativa previa. La voz puede matizar distancia, delicadeza o reproche; el texto no fija una emoción.','Decilo con delicadeza ante un error y con distancia ante una maniobra previsible.','Pedí explicar qué inferencia permanece y cuál cambia.','distance'),
 r('Escuchá y ensayá una ambigüedad que luego puedas resolver.','Si eso es lo que querían, lo consiguieron.',null,null,'El texto admite felicitación o reproche. La entrega, el foco y la pausa pueden orientar la lectura sin explicitarla.','Hacé una primera entrega ambigua y una segunda que la resuelva como reconocimiento. Después resolvela como reproche.','No pidas caricatura ni sarcasmo exagerado: evaluá si el interlocutor percibe el cambio.','neutral'),
 r('Un equipo necesita una invitación que no suene a ultimátum. ¿Qué toma favorece esa apertura?','Todavía podemos elegir cómo terminar esta historia.',['Toma A','Toma B'],1,'El descenso suave puede favorecer apertura acompañada. El arco retórico más cerrado puede dar fuerza de conclusión.','Usá ambos como invitación, y después uno como advertencia. Explicá qué contexto transforma su efecto.','No confundas una entrega persuasiva con manipulación: trabajá la respuesta que habilita.','reassurance','rhetorical'),
 r('Escuchá y alterá el relieve de una misma valoración.','Lo significativo no es el resultado, sino cómo llegamos a él.',null,null,'El contraste puede redistribuir importancia entre resultado y proceso. Una pausa y un cambio local de rango pueden organizar esa jerarquía.','Entregá el mensaje como análisis, como defensa y como crítica velada. Elegí un foco distinto en cada versión.','Pedí describir dónde comienza el segundo miembro y qué información presupone.','contrast'),
 r('Escuchá una propuesta y prepará tres efectos pragmáticos.','Podríamos dejarlo aquí, si todos estamos de acuerdo.',null,null,'La frase puede ofrecer consenso, cerrar por cansancio o invitar a una objeción pendiente. Ninguna lectura se prueba solo con el contorno.','Tu profe representa una reunión tensa. Cerrá con delicadeza, repetí con autoridad y abrí después un espacio real de desacuerdo.','Devolvé qué derecho a responder oyó en cada entrega.','suspended'),
 r('Opcional: ¿qué admite este comentario después de un desenlace inesperado?','Al final, todo quedó exactamente donde debía quedar.',['Una valoración cuya orientación requiere contexto','Inicio suspendido de una reflexión todavía abierta'],0,'El arco retórico da relieve al desenlace; puede servir a resignación, satisfacción o distancia según la escena.','Proponé tres contextos y elegí una entrega distinta para cada uno.','Evaluá control expresivo e inferencia, no una emoción obligatoria.','rhetorical'),
 r('Opcional: escuchá el cierre de este comentario. ¿Qué efecto favorece?','Hay maneras de decirlo y maneras de hacerlo.', ['Deja disponible una implicación que el oyente debe completar','Cierra la valoración con una caída concluyente'],0,'La suspensión puede mantener una implicación abierta. La insinuación concreta depende del intercambio previo.','Dejá la implicación abierta y luego cerrala con una entrega más definida, sin agregar palabras.','Pedí al oyente verbalizar dos inferencias posibles y explicar cuál descartó.','suspended'),
],{prompt:'El mismo mensaje, tres interpretaciones pragmáticas.',steps:['Prepará un texto breve de dos o tres frases sobre una decisión. Elegí tres efectos: invitación sincera, distancia delicada y cierre persuasivo; podés proponer otros.','Entregá el mismo texto tres veces sin leer, en contextos explícitos. Tu profe dice qué pudo inferir y qué quedó ambiguo.','Defendé tus decisiones de foco, rango, pausa y cierre. Recibí una objeción y rehacé una versión para resolver o conservar la ambigüedad deliberadamente.'],support:'Contenido constante → contexto → postura → inferencia buscada → entrega → interpretación observada.',criteria:['Mantiene el contenido y crea tres efectos pragmáticos distinguibles en contexto.','Explica las capas de interpretación y controla una ambigüedad de forma deliberada.','Ajusta la entrega con precisión después de contrastar su intención con la lectura del oyente.']});
