import {author} from './schema.mjs';
export default author('A1',{
 name:'Primer flujo',demand:'Palabras conocidas, frases cortas y mucho apoyo.',objective:'Une palabras conocidas sin perder sus vocales.',warmup:'Di tu nombre y dónde vives. ¿Haces una pausa después de cada palabra?',teacher:'Modela una frase breve, deja tiempo para repetir y pide un cambio personal. Explica con gestos, sin terminología técnica.',avoid:'No corrijas todo el acento ni pidas hablar rápido. Una pausa para pensar es normal.',extension:'Usa los dos desafíos opcionales si el alumno ya puede repetir y cambiar las frases centrales.'},[
 {prompt:'Escucha sin leer. ¿La persona habla de una amiga o de una casa?',text:'Tengo una amiga.',options:['Una casa','Una amiga'],answer:1,explanation:'Sonó «Tengo una amiga». Las tres palabras pueden fluir sin tres paradas.',transfer:'Repite la frase. Cambia amiga por amigo y dila completa.',teacher:'Primero una respuesta oral. Después elige y repite sin empujar el aire.'},
 {prompt:'¿La persona quiere una bebida o quiere estudiar?',text:'Quiero un café.',options:['Una bebida','Estudiar'],answer:0,explanation:'Sonó «Quiero un café». Mantén claras las vocales aunque las palabras estén cerca.',transfer:'Pide otra bebida. Tu profe repite lo que entendió.',teacher:'Si cuesta, ofrece dos dibujos y repite el audio. No muestres el texto al primer intento.'},
 {prompt:'Escucha dos ideas. Abre las palabras y marca dónde terminarías la primera.',text:'Soy Ana. Vivo en Lima.',tokens:['Soy','Ana.','Vivo','en','Lima.'],target:[1],explanation:'Una división útil es «Soy Ana | Vivo en Lima». Cada parte dice algo completo. No hace falta separar «vivo» de «en».',transfer:'Di tu nombre y tu ciudad, con una pausa entre las dos ideas.',teacher:'Acepta otras pausas si el mensaje sigue claro. El modelo sugerido no es una regla universal.'},
 {prompt:'Escucha. Une «es» con «una» para decirlas sin una parada en el medio.',text:'Es una casa.',tokens:['Es','una','casa.'],target:[0],explanation:'La s final puede enlazarse con la u: «es‿una». Las palabras escritas siguen siendo dos; no borramos letras.',transfer:'Di «Es un café» y señala algo que podría ser un café.',teacher:'Haz un gesto continuo entre es y una. No exijas una s idéntica entre variedades.'},
 {prompt:'¿Qué va a hacer? Escucha y ordena las piezas después.',text:'Voy a estudiar.',tokens:['estudiar.','Voy','a'],target:[1,2,0],explanation:'El orden del modelo es «Voy a estudiar». Las palabras forman una intención.',transfer:'Cambia estudiar por trabajar. Di la frase de una vez, a velocidad cómoda.',teacher:'Reproduce otra vez antes de corregir el orden. Separa dificultad de vocabulario y de escucha.'},
 {prompt:'Escucha A y B. ¿Cuál suena menos cortada?',text:'Vivo en Argentina.',options:['A','B'],answer:0,explanation:'A es la frase continua. B es un contraste didáctico con cortes entre palabras; no es un acento regional.',transfer:'Repite A. Ahora di dónde vives tú, sin correr.',teacher:'Pide que el alumno muestre los cortes con la mano. La continuidad importa más que la velocidad.'},
 {prompt:'Escucha la pregunta. Repítela y cambia el nombre.',text:'¿Dónde está Ana?',explanation:'«Dónde está» puede decirse sin una pausa entre las dos palabras. La pregunta completa tiene una intención.',transfer:'Pregunta por otra persona. El profe responde «Está acá» y tú repites la respuesta.',teacher:'Primero eco, después cambio de nombre y finalmente intercambio sin leer.'},
 {prompt:'Escucha una presentación breve. Prepara la tuya sin copiar todos los datos.',text:'Me llamo Leo. Vivo en Perú. Quiero un café.',explanation:'Tres ideas cortas: nombre, lugar y pedido. Las pausas entre ideas ayudan a entender.',transfer:'Di tu nombre, tu país y algo que quieres. Tu compañero repite dos datos.',teacher:'Dale 30 segundos para pensar. Si necesita lectura, usa el apoyo y registra práctica acompañada.'},
 {prompt:'Desafío opcional: ¿habla de estudiar o de trabajar?',text:'Voy a trabajar.',options:['Estudiar','Trabajar'],answer:1,explanation:'La secuencia «voy a» prepara la acción trabajar.',transfer:'Di una cosa que vas a hacer hoy.',teacher:'Usa esta escucha solamente si el recorrido central ya resulta cómodo.'},
 {prompt:'Desafío opcional: separa el saludo de la pregunta.',text:'Buenos días. ¿Cómo estás?',tokens:['Buenos','días.','¿Cómo','estás?'],target:[1],explanation:'Saludo y pregunta pueden formar dos grupos. Dentro de cada uno, evita paradas innecesarias.',transfer:'Saluda a tu profe y pregúntale cómo está.',teacher:'No conviertas el saludo en una prueba de gramática; escucha el flujo.'}
],{prompt:'Conoce a alguien en un café.',steps:['Prepara dos o tres frases: tu nombre, dónde vives y qué quieres tomar. Tienes un minuto.','Dilas sin leer. La otra persona repite lo que entendió y te hace una pregunta corta.','Escucha una sola sugerencia del profe y repite tu presentación. Cambia un dato para cerrar.'],support:'Me llamo… / Vivo en… / Quiero un… / ¿Y tú?',criteria:['Las frases no se cortan después de cada palabra.','Las vocales permiten reconocer las palabras conocidas.','El interlocutor entiende al menos dos datos personales.']});
