import {author} from './schema.mjs';
export default author('A1',{
 name:'Primer flujo',demand:'Palabras conocidas, frases cortas y mucho apoyo.',objective:'Uní palabras conocidas sin perder sus vocales.',warmup:'Decí tu nombre y dónde vivís. ¿Hacés una pausa después de cada palabra?',teacher:'Modelá una frase breve, dejá tiempo para repetir y pedí un cambio personal. Explicá con gestos, sin terminología técnica.',avoid:'No corrijas todo el acento ni pidas hablar rápido. Una pausa para pensar es normal.',extension:'Usá los dos desafíos opcionales si el alumno ya puede repetir y cambiar las frases centrales.'},[
 {prompt:'Escuchá sin leer. ¿La persona habla de una amiga o de una casa?',text:'Tengo una amiga.',options:['Una casa','Una amiga'],answer:1,explanation:'Sonó «Tengo una amiga». Las tres palabras pueden fluir sin tres paradas.',transfer:'Repetí la frase. Cambiá amiga por amigo y decila completa.',teacher:'Primero una respuesta oral. Después elegí y repetí sin empujar el aire.'},
 {prompt:'¿La persona quiere una bebida o quiere estudiar?',text:'Quiero un café.',options:['Una bebida','Estudiar'],answer:0,explanation:'Sonó «Quiero un café». Mantené claras las vocales aunque las palabras estén cerca.',transfer:'Pedí otra bebida. Tu profe repite lo que entendió.',teacher:'Si cuesta, ofrecé dos dibujos y repetí el audio. No muestres el texto al primer intento.'},
 {prompt:'Escuchá dos ideas. Abrí las palabras y marcá dónde terminarías la primera.',text:'Soy Ana. Vivo en Lima.',tokens:['Soy','Ana.','Vivo','en','Lima.'],target:[1],explanation:'Una división útil es «Soy Ana | Vivo en Lima». Cada parte dice algo completo. No hace falta separar «vivo» de «en».',transfer:'Decí tu nombre y tu ciudad, con una pausa entre las dos ideas.',teacher:'Aceptá otras pausas si el mensaje sigue claro. El modelo sugerido no es una regla universal.'},
 {prompt:'Escuchá. Uní «es» con «una» para decirlas sin una parada en el medio.',text:'Es una casa.',tokens:['Es','una','casa.'],target:[0],explanation:'La s final puede enlazarse con la u: «es‿una». Las palabras escritas siguen siendo dos; no borramos letras.',transfer:'Decí «Es un café» y señalá algo que podría ser un café.',teacher:'Hacé un gesto continuo entre es y una. No exijas una s idéntica entre variedades.'},
 {prompt:'¿Qué va a hacer? Escuchá y ordená las piezas después.',text:'Voy a estudiar.',tokens:['estudiar.','Voy','a'],target:[1,2,0],explanation:'El orden del modelo es «Voy a estudiar». Las palabras forman una intención.',transfer:'Cambiá estudiar por trabajar. Decí la frase de una vez, a velocidad cómoda.',teacher:'Reproducí otra vez antes de corregir el orden. Separá dificultad de vocabulario y de escucha.'},
 {prompt:'Escuchá A y B. ¿Cuál suena menos cortada?',text:'Vivo en Argentina.',options:['A','B'],answer:0,explanation:'A es la frase continua. B es un contraste didáctico con cortes entre palabras; no es un acento regional.',transfer:'Repetí A. Ahora decí dónde vivís vos, sin correr.',teacher:'Pedí que el alumno muestre los cortes con la mano. La continuidad importa más que la velocidad.'},
 {prompt:'Escuchá la pregunta. Repetila y cambiá el nombre.',text:'¿Dónde está Ana?',explanation:'«Dónde está» puede decirse sin una pausa entre las dos palabras. La pregunta completa tiene una intención.',transfer:'Preguntá por otra persona. El profe responde «Está acá» y vos repetís la respuesta.',teacher:'Primero eco, después cambio de nombre y finalmente intercambio sin leer.'},
 {prompt:'Escuchá una presentación breve. Prepará la tuya sin copiar todos los datos.',text:'Me llamo Leo. Vivo en Perú. Quiero un café.',explanation:'Tres ideas cortas: nombre, lugar y pedido. Las pausas entre ideas ayudan a entender.',transfer:'Decí tu nombre, tu país y algo que querés. Tu compañero repite dos datos.',teacher:'Dale 30 segundos para pensar. Si necesita lectura, usá el apoyo y registrá práctica acompañada.'},
 {prompt:'Desafío opcional: ¿habla de estudiar o de trabajar?',text:'Voy a trabajar.',options:['Estudiar','Trabajar'],answer:1,explanation:'La secuencia «voy a» prepara la acción trabajar.',transfer:'Decí una cosa que vas a hacer hoy.',teacher:'Usá esta escucha solamente si el recorrido central ya resulta cómodo.'},
 {prompt:'Desafío opcional: separá el saludo de la pregunta.',text:'Buenos días. ¿Cómo estás?',tokens:['Buenos','días.','¿Cómo','estás?'],target:[1],explanation:'Saludo y pregunta pueden formar dos grupos. Dentro de cada uno, evitá paradas innecesarias.',transfer:'Saludá a tu profe y preguntale cómo está.',teacher:'No conviertas el saludo en una prueba de gramática; escuchá el flujo.'}
],{prompt:'Conocé a alguien en un café.',steps:['Prepará dos o tres frases: tu nombre, dónde vivís y qué querés tomar. Tenés un minuto.','Decilas sin leer. La otra persona repite lo que entendió y te hace una pregunta corta.','Escuchá una sola sugerencia del profe y repetí tu presentación. Cambiá un dato para cerrar.'],support:'Me llamo… / Vivo en… / Quiero un… / ¿Y vos?',criteria:['Las frases no se cortan después de cada palabra.','Las vocales permiten reconocer las palabras conocidas.','El interlocutor entiende al menos dos datos personales.']});
