export type SyntaxMode = "connector" | "clause" | "timeline" | "decision" | "contrast" | "referent";

export type SyntaxPattern = {
  key: string;
  label: string;
  intention: string;
  formula: string;
  example: string;
  preview: { left: string; connector: string; right: string };
  explanation: string;
};

export type SyntaxDecision = {
  intention: string;
  prompt: string;
  left: string;
  right: string;
  options: string[];
  correct: number;
  feedback: string;
};

export type SyntaxRepair = {
  prompt: string;
  original: string;
  options: string[];
  correct: number;
  feedback: string;
};

export type SyntaxLabData = {
  slug: string;
  level: "A1" | "A2" | "B1";
  category: "Gramática";
  mode: SyntaxMode;
  module: string;
  pcic: string;
  title: string;
  displayTitle: string;
  subtitle: string;
  goal: string;
  accent: string;
  accent2: string;
  productiveTargets: string[];
  boundaries: string;
  timeline: { label: string; minutes: number }[];
  activation: {
    instruction: string;
    cards: { first: string; second: string; intention: string }[];
  };
  patterns: SyntaxPattern[];
  decisions: SyntaxDecision[];
  questionAnswerCycle: { question: string; answer: string; cue: string }[];
  repairs: SyntaxRepair[];
  retrieval: { intention: string; prompt: string; challenge: string }[];
  production: { title: string; prompt: string; checklist: string[] }[];
  conversationMinutes: number;
  conversation: { question: string; starter: string; followUp: string }[];
  finalTask: string;
};

export const conectaLaFrase: SyntaxLabData = {
  slug: "conecta-la-frase",
  level: "A1",
  category: "Gramática",
  mode: "connector",
  module: "MÓDULO 14 · A1",
  pcic: "PCIC 14 · coordinación A1",
  title: "Conecta la frase",
  displayTitle: "Conecta\nla frase",
  subtitle: "Sumar, negar, elegir, contrastar y repartir ideas sin hablar como una lista",
  goal: "Unir ideas cotidianas con el conector que expresa la relación correcta y usarlas al hablar de la vida real.",
  accent: "#ff7a5c",
  accent2: "#ffd166",
  productiveTargets: ["y", "ni", "o", "pero", "uno… otro"],
  boundaries: "La clase trabaja las formas básicas de coordinación documentadas para A1. Las alternancias ortográficas de nivel posterior quedan fuera del objetivo productivo.",
  timeline: [
    { label: "Activación", minutes: 5 },
    { label: "Descubrimiento", minutes: 7 },
    { label: "Conecta", minutes: 8 },
    { label: "Repara", minutes: 7 },
    { label: "Hazlo verdadero", minutes: 8 },
    { label: "Cadena oral", minutes: 5 },
    { label: "Conversación", minutes: 5 },
  ],
  activation: {
    instruction: "Leé cada par sin mostrar conectores. El alumno decide si las ideas se suman, se niegan juntas, ofrecen una elección, contrastan o reparten acciones.",
    cards: [
      { first: "Trabajo por la mañana", second: "estudio por la tarde", intention: "SUMAR" },
      { first: "No tomo café", second: "no tomo té", intention: "NEGAR DOS COSAS" },
      { first: "Podemos cocinar", second: "podemos pedir comida", intention: "ELEGIR" },
      { first: "La casa es pequeña", second: "es muy luminosa", intention: "CONTRASTAR" },
      { first: "Un amigo prepara la cena", second: "otro pone la mesa", intention: "REPARTIR" },
    ],
  },
  patterns: [
    {
      key: "y",
      label: "Y",
      intention: "SUMAR",
      formula: "IDEA + Y + IDEA",
      example: "Trabajo en casa y estudio español.",
      preview: { left: "Trabajo en casa", connector: "y", right: "estudio español." },
      explanation: "Y añade una idea compatible: las dos informaciones son verdaderas al mismo tiempo.",
    },
    {
      key: "ni",
      label: "NI",
      intention: "NEGAR DOS ELEMENTOS",
      formula: "NO + VERBO + A + NI + B",
      example: "No como carne ni pescado.",
      preview: { left: "No como carne", connector: "ni", right: "pescado." },
      explanation: "Ni suma un segundo elemento dentro de una negación; no presenta una alternativa.",
    },
    {
      key: "o",
      label: "O",
      intention: "ELEGIR",
      formula: "OPCIÓN A + O + OPCIÓN B",
      example: "¿Cocinamos o pedimos comida?",
      preview: { left: "¿Cocinamos", connector: "o", right: "pedimos comida?" },
      explanation: "O abre una elección entre posibilidades reales para el hablante.",
    },
    {
      key: "pero",
      label: "PERO",
      intention: "CONTRASTAR",
      formula: "IDEA + PERO + CONTRASTE",
      example: "Es pequeño, pero es cómodo.",
      preview: { left: "Es pequeño", connector: "pero", right: "es cómodo." },
      explanation: "Pero avisa que la segunda idea contrasta con la expectativa creada por la primera.",
    },
    {
      key: "uno-otro",
      label: "UNO… OTRO",
      intention: "REPARTIR",
      formula: "UNO + ACCIÓN A; OTRO + ACCIÓN B",
      example: "Uno cocina y otro lava los platos.",
      preview: { left: "Uno cocina", connector: "y", right: "otro lava los platos." },
      explanation: "Uno… otro distribuye acciones o características entre dos participantes.",
    },
  ],
  decisions: [
    {
      intention: "SUMAR",
      prompt: "Querés contar dos actividades de tu rutina.",
      left: "Trabajo por la mañana",
      right: "estudio por la tarde.",
      options: ["y", "o", "pero"],
      correct: 0,
      feedback: "Las dos actividades forman parte de la misma rutina; y permite sumar ambas informaciones.",
    },
    {
      intention: "NEGAR DOS COSAS",
      prompt: "Decís dos bebidas que no tomás.",
      left: "No tomo café",
      right: "té.",
      options: ["y", "ni", "pero"],
      correct: 1,
      feedback: "La negación ya aparece con no; ni incorpora el segundo elemento dentro de esa misma negación.",
    },
    {
      intention: "ELEGIR",
      prompt: "Ofrecés dos planes posibles para esta noche.",
      left: "Podemos ver una película",
      right: "salir a caminar.",
      options: ["y", "o", "ni"],
      correct: 1,
      feedback: "Se presentan dos planes como alternativas; o invita a elegir uno de los dos.",
    },
    {
      intention: "CONTRASTAR",
      prompt: "El precio es alto, aunque tu valoración es positiva.",
      left: "El restaurante es caro",
      right: "la comida es excelente.",
      options: ["y", "pero", "o"],
      correct: 1,
      feedback: "La segunda valoración rompe la expectativa negativa del precio; por eso funciona pero.",
    },
    {
      intention: "REPARTIR",
      prompt: "Dos compañeros hacen tareas diferentes.",
      left: "Uno escribe el mensaje",
      right: "otro busca la dirección.",
      options: ["y", "pero", "ni"],
      correct: 0,
      feedback: "Uno… otro ya reparte las tareas; y conecta las dos acciones que forman el plan común.",
    },
    {
      intention: "SUMAR",
      prompt: "Describís una clase con dos cualidades compatibles.",
      left: "La clase es práctica",
      right: "divertida.",
      options: ["pero", "y", "o"],
      correct: 1,
      feedback: "Práctica y divertida son dos cualidades compatibles que se añaden a la misma descripción.",
    },
    {
      intention: "NEGAR DOS ACCIONES",
      prompt: "Contás lo que nunca hacés antes de dormir.",
      left: "No trabajo",
      right: "miro el teléfono en la cama.",
      options: ["ni", "o", "pero"],
      correct: 0,
      feedback: "No inicia la negación y ni añade la segunda acción también negada, sin repetir no.",
    },
    {
      intention: "ELEGIR",
      prompt: "Preguntás qué medio de transporte prefiere una persona.",
      left: "¿Vas en autobús",
      right: "en metro?",
      options: ["y", "pero", "o"],
      correct: 2,
      feedback: "La pregunta ofrece dos medios posibles; o marca con claridad la elección esperada.",
    },
    {
      intention: "CONTRASTAR",
      prompt: "Tenés ganas de salir, aunque hoy no podés.",
      left: "Quiero ir a la fiesta",
      right: "tengo que trabajar.",
      options: ["y", "pero", "ni"],
      correct: 1,
      feedback: "Tener que trabajar choca con el deseo de ir; pero hace visible ese contraste.",
    },
    {
      intention: "REPARTIR",
      prompt: "Comparás dos hermanos con gustos diferentes.",
      left: "A uno le gusta el fútbol",
      right: "al otro le gusta el tenis.",
      options: ["y", "o", "ni"],
      correct: 0,
      feedback: "Uno… otro distribuye los gustos y y reúne los dos datos en una sola comparación.",
    },
  ],
  questionAnswerCycle: [],
  repairs: [
    {
      prompt: "Queremos sumar dos gustos, no presentar una elección.",
      original: "Me gusta el cine o la música.",
      options: ["Me gusta el cine y la música.", "No me gusta el cine ni la música.", "Me gusta el cine, pero la música."],
      correct: 0,
      feedback: "Si los dos gustos son verdaderos, y suma; o cambiaría el mensaje y abriría una alternativa.",
    },
    {
      prompt: "Queremos negar las dos actividades.",
      original: "No corro y nado.",
      options: ["No corro ni nado.", "Corro o nado.", "No corro, pero nado."],
      correct: 0,
      feedback: "Ni mantiene las dos acciones dentro de la negación; las otras versiones cambian el significado.",
    },
    {
      prompt: "Queremos mostrar un contraste positivo.",
      original: "El piso es pequeño y tiene mucho espacio.",
      options: ["El piso es pequeño, pero tiene mucho espacio.", "El piso es pequeño o tiene mucho espacio.", "El piso ni es pequeño ni tiene espacio."],
      correct: 0,
      feedback: "Pero comunica la sorpresa: a pesar de ser pequeño, el piso ofrece mucho espacio.",
    },
    {
      prompt: "Queremos pedir una decisión.",
      original: "¿Tomamos café y té?",
      options: ["¿Tomamos café o té?", "No tomamos café ni té.", "Tomamos café, pero té."],
      correct: 0,
      feedback: "O convierte las dos bebidas en alternativas y permite que la otra persona elija.",
    },
    {
      prompt: "Queremos repartir dos objetos entre dos personas.",
      original: "Uno lleva las dos maletas y otro.",
      options: ["Uno lleva una maleta y otro lleva la otra.", "Uno no lleva ni otro.", "Uno lleva una maleta, pero otro."],
      correct: 0,
      feedback: "La estructura completa necesita una acción clara para cada participante: uno… y otro…",
    },
  ],
  retrieval: [
    { intention: "SUMAR", prompt: "Sin banco de respuestas: decí dos cosas que hacés todos los días.", challenge: "Unilas con y y agregá cuándo." },
    { intention: "NEGAR", prompt: "Sin opciones: decí dos alimentos o bebidas que no consumís.", challenge: "Usá no… ni… sin repetir no." },
    { intention: "ELEGIR", prompt: "Ofrecele al profesor dos planes reales para el fin de semana.", challenge: "Formulá una pregunta con o y pedí una decisión." },
    { intention: "CONTRASTAR", prompt: "Describí algo que tiene una desventaja y una ventaja.", challenge: "Usá pero para que el contraste sea claro." },
    { intention: "REPARTIR", prompt: "Imaginá dos personas preparando una comida.", challenge: "Distribuí las tareas con uno… otro." },
  ],
  production: [
    {
      title: "Cadena de rutina",
      prompt: "Contá tu rutina en cuatro ideas conectadas, sin convertirla en una lista de frases aisladas.",
      checklist: ["al menos dos usos de y", "una negación con ni", "un contraste con pero"],
    },
    {
      title: "Dos decisiones",
      prompt: "Proponé dos elecciones reales de esta semana y respondé qué preferís en cada caso.",
      checklist: ["pregunta con o", "respuesta completa", "una razón sencilla"],
    },
    {
      title: "Trabajo en equipo",
      prompt: "Repartí cuatro tareas entre dos personas y explicá el plan en voz alta.",
      checklist: ["uno… otro", "acciones diferentes", "una conexión final con y o pero"],
    },
  ],
  conversationMinutes: 5,
  conversation: [
    { question: "¿Qué dos cosas hacés siempre por la mañana?", starter: "Por la mañana… y…", followUp: "¿Qué no hacés nunca a esa hora?" },
    { question: "¿Preferís vivir en una ciudad grande o en un lugar tranquilo?", starter: "Prefiero…", followUp: "¿Qué ventaja y qué desventaja tiene tu opción?" },
    { question: "¿Qué comida te gusta, pero no comés con frecuencia?", starter: "Me gusta…, pero…", followUp: "¿Por qué no la comés con frecuencia?" },
    { question: "¿Qué dos cosas no pueden faltar en una buena clase?", starter: "No puede faltar ni… ni…", followUp: "¿Y qué cosa no es necesaria?" },
    { question: "Cuando viajás con otra persona, ¿cómo reparten las tareas?", starter: "Uno… y otro…", followUp: "¿Qué tarea preferís hacer vos?" },
    { question: "¿Trabajás mejor por la mañana o por la noche?", starter: "Trabajo mejor…", followUp: "¿Tu horario ideal es práctico o difícil de mantener?" },
    { question: "¿Qué te gusta de tu ciudad y qué querés cambiar?", starter: "Me gusta…, pero…", followUp: "¿Qué otra cosa positiva podés sumar?" },
    { question: "¿Qué elegís: más tiempo libre o más dinero?", starter: "Elijo…", followUp: "¿La otra opción también tiene una ventaja?" },
  ],
  finalTask: "Mi vida en 8 conexiones: hablá durante 2–3 minutos y usá y, ni, o, pero y uno… otro al menos una vez; después respondé repreguntas reales.",
};

export const ideasDentroDeIdeas: SyntaxLabData = {
  slug: "ideas-dentro-de-ideas",
  level: "A1",
  category: "Gramática",
  mode: "clause",
  module: "MÓDULO 15 · A1",
  pcic: "PCIC 15 · subordinación A1",
  title: "Ideas dentro de ideas",
  displayTitle: "Ideas dentro\nde ideas",
  subtitle: "Una idea principal abre un espacio para una actividad, una opinión, una identificación, una razón o un objetivo",
  goal: "Construir mensajes A1 con una idea principal y otra dependiente para hablar de gustos, deseos, opiniones, personas, razones y objetivos.",
  accent: "#55c8ff",
  accent2: "#b9f36b",
  productiveTargets: [
    "ser + infinitivo",
    "gustar + infinitivo",
    "querer + infinitivo",
    "creer que + oración",
    "nombre + que + presente",
    "porque",
    "para + infinitivo",
  ],
  boundaries: "La clase se limita a arquitecturas A1: infinitivo, presente de indicativo, que con antecedente expreso, porque y para + infinitivo. No convierte estructuras de niveles posteriores en objetivos productivos.",
  timeline: [
    { label: "Activación", minutes: 4 },
    { label: "Mapa", minutes: 8 },
    { label: "Encaja", minutes: 8 },
    { label: "Por qué / porque", minutes: 5 },
    { label: "Repara", minutes: 6 },
    { label: "Personaliza", minutes: 6 },
    { label: "Repetí con menos apoyo", minutes: 3 },
    { label: "Conversación", minutes: 5 },
  ],
  activation: {
    instruction: "Compará la frase mínima con la versión ampliada. El alumno dice qué información nueva aparece: actividad, opinión, identificación, razón u objetivo.",
    cards: [
      { first: "Es útil.", second: "Hablar español es útil.", intention: "ACTIVIDAD" },
      { first: "Tengo una opinión.", second: "Creo que la ciudad es segura.", intention: "OPINIÓN" },
      { first: "Conozco a la persona.", second: "Conozco a la persona que trabaja aquí.", intention: "IDENTIFICAR" },
      { first: "Estudio español.", second: "Estudio español porque vivo en Madrid.", intention: "RAZÓN" },
      { first: "Voy al mercado.", second: "Voy al mercado para comprar fruta.", intention: "OBJETIVO" },
    ],
  },
  patterns: [
    {
      key: "actividad",
      label: "ACTIVIDAD",
      intention: "VALORAR UNA ACTIVIDAD",
      formula: "INFINITIVO + ES + ADJETIVO",
      example: "Caminar es saludable.",
      preview: { left: "Caminar", connector: "es", right: "saludable." },
      explanation: "El infinitivo nombra la actividad completa y funciona como el tema de la valoración.",
    },
    {
      key: "gusto",
      label: "GUSTO",
      intention: "DECIR QUÉ ACTIVIDAD GUSTA",
      formula: "ME GUSTA + INFINITIVO",
      example: "Me gusta cocinar.",
      preview: { left: "Me gusta", connector: "+", right: "cocinar." },
      explanation: "Después de gusta usamos el infinitivo para nombrar la actividad, sin añadir otro sujeto.",
    },
    {
      key: "deseo",
      label: "DESEO",
      intention: "DECIR QUÉ QUERÉS HACER",
      formula: "QUIERO + INFINITIVO",
      example: "Quiero conocer México.",
      preview: { left: "Quiero", connector: "+", right: "conocer México." },
      explanation: "Querer abre un espacio para la acción deseada; la acción aparece en infinitivo.",
    },
    {
      key: "opinion",
      label: "OPINIÓN",
      intention: "EXPRESAR UNA OPINIÓN AFIRMATIVA",
      formula: "CREO QUE + ORACIÓN",
      example: "Creo que este barrio es tranquilo.",
      preview: { left: "Creo", connector: "que", right: "este barrio es tranquilo." },
      explanation: "Que introduce una idea completa que el hablante presenta como su opinión básica.",
    },
    {
      key: "identificacion",
      label: "IDENTIFICACIÓN",
      intention: "IDENTIFICAR UNA PERSONA O COSA",
      formula: "NOMBRE + QUE + PRESENTE",
      example: "La profesora que vive aquí habla italiano.",
      preview: { left: "La profesora", connector: "que", right: "vive aquí habla italiano." },
      explanation: "Aquí que no introduce una opinión: identifica de qué persona o cosa hablamos.",
    },
    {
      key: "razon",
      label: "RAZÓN",
      intention: "RESPONDER POR QUÉ",
      formula: "IDEA + PORQUE + RAZÓN",
      example: "Estudio español porque viajo mucho.",
      preview: { left: "Estudio español", connector: "porque", right: "viajo mucho." },
      explanation: "Porque introduce la respuesta o explicación; por qué aparece en la pregunta.",
    },
    {
      key: "objetivo",
      label: "OBJETIVO",
      intention: "DECIR PARA QUÉ",
      formula: "IDEA + PARA + INFINITIVO",
      example: "Voy al mercado para comprar fruta.",
      preview: { left: "Voy al mercado", connector: "para", right: "comprar fruta." },
      explanation: "Para + infinitivo expresa el objetivo inmediato de una acción.",
    },
  ],
  decisions: [
    {
      intention: "VALORAR UNA ACTIVIDAD",
      prompt: "Querés valorar la actividad de practicar cada día.",
      left: "Practicar cada día",
      right: "importante.",
      options: ["es", "que", "porque"],
      correct: 0,
      feedback: "Practicar nombra la actividad completa y es la conecta con la valoración importante.",
    },
    {
      intention: "GUSTO",
      prompt: "Decís una actividad que disfrutás.",
      left: "Me gusta",
      right: "música.",
      options: ["escuchar", "escucho", "que escuchar"],
      correct: 0,
      feedback: "Después de me gusta, el infinitivo escuchar nombra la actividad sin conjugar otro verbo.",
    },
    {
      intention: "DESEO",
      prompt: "Expresás un plan personal.",
      left: "Quiero",
      right: "Argentina.",
      options: ["visito", "visitar", "que visitar"],
      correct: 1,
      feedback: "Quiero abre el deseo y visitar aparece en infinitivo porque el sujeto de las dos acciones es el mismo.",
    },
    {
      intention: "OPINIÓN",
      prompt: "Das una opinión afirmativa sobre el curso.",
      left: "Creo",
      right: "el curso es útil.",
      options: ["que", "porque", "para"],
      correct: 0,
      feedback: "Creo que introduce una idea completa presentada como opinión: el curso es útil.",
    },
    {
      intention: "IDENTIFICAR",
      prompt: "Precisás de qué café hablás.",
      left: "El café",
      right: "está en la esquina es barato.",
      options: ["porque", "que", "para"],
      correct: 1,
      feedback: "Que identifica el café mediante una característica; el antecedente expreso es el café.",
    },
    {
      intention: "RAZÓN",
      prompt: "Explicás tu motivo para estudiar.",
      left: "Estudio español",
      right: "mi pareja es argentina.",
      options: ["por qué", "porque", "para"],
      correct: 1,
      feedback: "La frase responde a una pregunta sobre el motivo; porque introduce esa razón.",
    },
    {
      intention: "OBJETIVO",
      prompt: "Explicás el objetivo de ir al gimnasio.",
      left: "Voy al gimnasio",
      right: "más energía.",
      options: ["para tener", "porque tengo", "que tener"],
      correct: 0,
      feedback: "Para tener presenta el objetivo de ir; después de para usamos el infinitivo tener.",
    },
    {
      intention: "ACTIVIDAD",
      prompt: "Valorás una actividad cotidiana.",
      left: "Dormir bien",
      right: "necesario.",
      options: ["que", "es", "para"],
      correct: 1,
      feedback: "Dormir bien es el tema de la valoración y es lo conecta con necesario.",
    },
    {
      intention: "GUSTO",
      prompt: "Completás una preferencia real.",
      left: "A Marta le gusta",
      right: "con amigos.",
      options: ["sale", "salir", "que salir"],
      correct: 1,
      feedback: "El infinitivo salir nombra la actividad que le gusta a Marta, sin conjugar una segunda acción.",
    },
    {
      intention: "OPINIÓN",
      prompt: "Expresás una impresión básica del barrio.",
      left: "Creo",
      right: "hay buenos restaurantes.",
      options: ["para", "que", "porque"],
      correct: 1,
      feedback: "Creo que abre la opinión y la idea dependiente mantiene su verbo conjugado: hay.",
    },
    {
      intention: "IDENTIFICAR",
      prompt: "Identificás a una persona por su trabajo.",
      left: "La mujer",
      right: "trabaja en recepción habla francés.",
      options: ["porque", "para", "que"],
      correct: 2,
      feedback: "Que conecta mujer con la característica que permite identificarla: trabaja en recepción.",
    },
    {
      intention: "OBJETIVO",
      prompt: "Decís para qué usás una aplicación.",
      left: "Uso esta aplicación",
      right: "vocabulario.",
      options: ["porque practico", "para practicar", "que practico"],
      correct: 1,
      feedback: "Para practicar explica la finalidad de usar la aplicación y conserva practicar en infinitivo.",
    },
  ],
  questionAnswerCycle: [
    { question: "¿Por qué estudiás español?", answer: "Estudio español porque quiero viajar.", cue: "estudiar / viajar" },
    { question: "¿Por qué vivís en esta ciudad?", answer: "Vivo aquí porque trabajo cerca.", cue: "vivir / trabajar" },
    { question: "¿Por qué aprendés vocabulario nuevo?", answer: "Aprendo palabras porque quiero hablar mejor.", cue: "aprender / hablar" },
    { question: "¿Por qué cocinás en casa?", answer: "Cocino en casa porque es más barato.", cue: "cocinar / barato" },
  ],
  repairs: [
    {
      prompt: "Después de para necesitamos una acción en infinitivo.",
      original: "Voy al mercado para compro fruta.",
      options: ["Voy al mercado para comprar fruta.", "Voy al mercado porque comprar fruta.", "Voy al mercado que compro fruta."],
      correct: 0,
      feedback: "Comprar aparece en infinitivo porque expresa el objetivo de ir al mercado.",
    },
    {
      prompt: "La respuesta necesita porque, no la forma de pregunta por qué.",
      original: "Estudio español por qué vivo aquí.",
      options: ["Estudio español porque vivo aquí.", "¿Estudio español porque vivo aquí?", "Estudio español para vivo aquí."],
      correct: 0,
      feedback: "Porque introduce la razón dentro de la respuesta; por qué se reserva para preguntar por el motivo.",
    },
    {
      prompt: "Creer necesita que antes de una idea con verbo conjugado.",
      original: "Creo este barrio es tranquilo.",
      options: ["Creo que este barrio es tranquilo.", "Creo para este barrio es tranquilo.", "Creo porque este barrio tranquilo."],
      correct: 0,
      feedback: "Que abre la idea completa que funciona como contenido de la opinión expresada con creo.",
    },
    {
      prompt: "El infinitivo ya nombra la actividad; no necesita un segundo sujeto.",
      original: "Me gusta yo cocinar.",
      options: ["Me gusta cocinar.", "Me gusta que cocinar.", "Yo me gusta cocino."],
      correct: 0,
      feedback: "Me gusta cocinar presenta una sola persona y una actividad; el infinitivo evita una estructura innecesaria.",
    },
    {
      prompt: "El relativo necesita un antecedente claro antes de que.",
      original: "Que trabaja aquí habla francés.",
      options: ["La mujer que trabaja aquí habla francés.", "Creo que trabaja aquí habla francés.", "Porque trabaja aquí habla francés."],
      correct: 0,
      feedback: "La mujer es el antecedente expreso; que añade la información que permite identificarla.",
    },
  ],
  retrieval: [
    { intention: "ACTIVIDAD", prompt: "Sin banco de respuestas: valorá una actividad de tu vida con infinitivo + ser.", challenge: "Repetí la frase una segunda vez sin mirar la fórmula." },
    { intention: "GUSTO Y DESEO", prompt: "Decí algo que te gusta hacer y algo que querés hacer este mes.", challenge: "Usá dos infinitivos distintos y después repetí con menos apoyo." },
    { intention: "OPINIÓN", prompt: "Dá una opinión sencilla sobre tu ciudad con creo que.", challenge: "Cambiá la opinión para hablar de tu trabajo o estudio." },
    { intention: "IDENTIFICACIÓN", prompt: "Identificá una persona o cosa real con nombre + que + presente.", challenge: "Comprobá que el antecedente aparece antes de que." },
    { intention: "RAZÓN Y OBJETIVO", prompt: "Contá una acción, su razón con porque y su objetivo con para + infinitivo.", challenge: "Repetí la respuesta con más fluidez y sin leer." },
  ],
  production: [
    {
      title: "Lo que hago",
      prompt: "Explicá dos actividades que te gustan y una que querés empezar.",
      checklist: ["gustar + infinitivo", "querer + infinitivo", "una razón con porque"],
    },
    {
      title: "Lo que pienso",
      prompt: "Dá una opinión sobre tu ciudad y otra sobre aprender idiomas.",
      checklist: ["dos usos afirmativos de creo que", "una valoración con infinitivo + ser", "sin leer una respuesta preparada"],
    },
    {
      title: "Personas y objetivos",
      prompt: "Identificá a una persona real y explicá un objetivo actual.",
      checklist: ["antecedente + que + presente", "para + infinitivo", "una repregunta del profesor"],
    },
  ],
  conversationMinutes: 5,
  conversation: [
    { question: "¿Qué actividad te gusta hacer cuando tenés tiempo libre?", starter: "Me gusta…", followUp: "¿Por qué te gusta esa actividad?" },
    { question: "¿Qué querés hacer durante los próximos meses?", starter: "Quiero…", followUp: "¿Para qué querés hacerlo?" },
    { question: "¿Qué actividad es importante para estar bien?", starter: "… es importante porque…", followUp: "¿La hacés con frecuencia?" },
    { question: "¿Qué pensás de la ciudad donde vivís?", starter: "Creo que…", followUp: "¿Qué lugar que conocés representa bien esa opinión?" },
    { question: "¿Quién es una persona que te ayuda mucho?", starter: "… es una persona que…", followUp: "¿Por qué es importante para vos?" },
    { question: "¿Para qué estudiás español ahora?", starter: "Estudio español para…", followUp: "¿Y por qué elegiste español?" },
    { question: "¿Qué objeto que usás todos los días es indispensable?", starter: "El/La… que uso…", followUp: "¿Para qué lo usás exactamente?" },
    { question: "¿Qué creés que hace buena una clase?", starter: "Creo que una buena clase…", followUp: "¿Por qué esa característica es importante?" },
  ],
  finalTask: "Mi mapa A1: conversá durante 3–5 minutos sobre algo que te gusta hacer, algo que querés hacer, una opinión, una persona o cosa con que, una razón con porque y un objetivo con para + infinitivo.",
};

export const antesDespuesCuando: SyntaxLabData = {
  slug: "antes-despues-cuando",
  level: "A2",
  category: "Gramática",
  mode: "timeline",
  module: "MÓDULO 15.3.1 · A2",
  pcic: "PCIC 15.3.1 · temporales A2",
  title: "Antes, después, cuando",
  displayTitle: "Antes, después,\ncuando",
  subtitle: "Organizá rutinas y procesos como una secuencia clara, no como frases sueltas",
  goal: "Narrar secuencias habituales o factuales con antes de, después de y cuando, y explicarlas con naturalidad.",
  accent: "#55d6be",
  accent2: "#ffd166",
  productiveTargets: ["antes de + infinitivo", "después de + infinitivo", "cuando + presente de indicativo"],
  boundaries: "Trabajamos acciones del mismo sujeto y hechos habituales en presente. La referencia temporal futura y otras combinaciones quedan fuera de esta clase A2.",
  timeline: [
    { label: "Activación", minutes: 5 },
    { label: "Descubrimiento", minutes: 7 },
    { label: "Línea guiada", minutes: 8 },
    { label: "Contraste", minutes: 7 },
    { label: "Recuperación", minutes: 6 },
    { label: "Repetición", minutes: 5 },
    { label: "Conversación", minutes: 7 },
  ],
  activation: {
    instruction: "Ordená las acciones primero. Después explicá qué ocurre antes, qué ocurre después y qué pasa habitualmente en ese momento.",
    cards: [
      { first: "suena la alarma", second: "me levanto", intention: "ORDENAR" },
      { first: "desayuno", second: "salgo de casa", intention: "RUTINA" },
      { first: "llego al trabajo", second: "reviso los mensajes", intention: "MOMENTO" },
      { first: "compro el billete", second: "subo al tren", intention: "VIAJE" },
      { first: "termino de cocinar", second: "pongo la mesa", intention: "PROCESO" },
    ],
  },
  patterns: [
    { key: "antes-de", label: "ANTES DE", intention: "ACCIÓN PREVIA", formula: "ANTES DE + INFINITIVO", example: "Antes de salir, desayuno.", preview: { left: "desayuno", connector: "antes de", right: "salir" }, explanation: "Después de antes de, la acción aparece en infinitivo y se presenta como anterior a la acción principal." },
    { key: "despues-de", label: "DESPUÉS DE", intention: "ACCIÓN POSTERIOR", formula: "DESPUÉS DE + INFINITIVO", example: "Después de comer, camino un poco.", preview: { left: "como", connector: "después de", right: "caminar" }, explanation: "Después de sitúa una acción terminada como punto anterior; la acción que sigue a de va en infinitivo." },
    { key: "cuando-presente", label: "CUANDO", intention: "HÁBITO O HECHO", formula: "CUANDO + PRESENTE, PRESENTE", example: "Cuando llego, reviso el correo.", preview: { left: "llego", connector: "cuando", right: "reviso el correo" }, explanation: "Cuando conecta dos hechos habituales o factuales; en esta clase ambos se expresan en presente de indicativo." },
  ],
  decisions: [
    { intention: "ACCIÓN PREVIA", prompt: "Primero te duchás y luego te vestís.", left: "Me ducho", right: "vestirme.", options: ["antes de", "cuando", "después de"], correct: 0, feedback: "La ducha ocurre primero; antes de marca esa relación y vestirme conserva la forma de infinitivo." },
    { intention: "ACCIÓN POSTERIOR", prompt: "Primero cenás y luego lavás los platos.", left: "Lavo los platos", right: "cenar.", options: ["cuando", "antes de", "después de"], correct: 2, feedback: "Lavar ocurre tras la cena; después de expresa esa cronología y exige el infinitivo cenar." },
    { intention: "HÁBITO", prompt: "Las dos acciones forman parte de tu rutina al llegar.", left: "Llego a casa", right: "me saco los zapatos.", options: ["después de", "cuando", "antes de"], correct: 1, feedback: "Cuando presenta el momento habitual; llego y me saco aparecen conjugados en presente." },
    { intention: "PREPARACIÓN", prompt: "Preparás la mochila y luego salís.", left: "Preparo la mochila", right: "salir.", options: ["antes de", "después de", "cuando"], correct: 0, feedback: "Preparar la mochila es la acción previa; salir queda en infinitivo después de la preposición de." },
    { intention: "VIAJE", prompt: "Bajás del tren y enseguida buscás la salida.", left: "Busco la salida", right: "bajar del tren.", options: ["antes de", "cuando", "después de"], correct: 2, feedback: "Buscar la salida sucede más tarde; después de bajar organiza las dos acciones sin conjugación adicional." },
    { intention: "HECHO REPETIDO", prompt: "Siempre hacés esto al empezar una reunión.", left: "Empieza la reunión", right: "apago el teléfono.", options: ["cuando", "antes de", "después de"], correct: 0, feedback: "Cuando une dos hechos que se repiten; ambos verbos aparecen en presente de indicativo." },
    { intention: "COCINA", prompt: "Primero cortás las verduras y luego las cocinás.", left: "Corto las verduras", right: "cocinarlas.", options: ["después de", "antes de", "cuando"], correct: 1, feedback: "Cortar ocurre antes; el pronombre se une correctamente al infinitivo cocinarlas tras antes de." },
    { intention: "FIN DE JORNADA", prompt: "Terminás de trabajar y luego llamás a una amiga.", left: "Llamo a una amiga", right: "terminar de trabajar.", options: ["después de", "cuando", "antes de"], correct: 0, feedback: "La llamada es posterior; después de terminar expresa el orden y mantiene terminar en infinitivo." },
    { intention: "RUTINA", prompt: "Esto sucede cada vez que viajás en autobús.", left: "Viajo en autobús", right: "escucho música.", options: ["antes de", "después de", "cuando"], correct: 2, feedback: "Cuando introduce una situación habitual y permite conjugar las dos acciones en presente." },
    { intention: "ORGANIZACIÓN", prompt: "Revisás la dirección y después pedís el taxi.", left: "Reviso la dirección", right: "pedir el taxi.", options: ["antes de", "cuando", "después de"], correct: 0, feedback: "La revisión precede al pedido; antes de pedir mantiene clara la secuencia y usa infinitivo." },
  ],
  questionAnswerCycle: [],
  repairs: [
    { prompt: "Después de antes de necesitamos infinitivo.", original: "Antes de salgo, preparo la mochila.", options: ["Antes de salir, preparo la mochila.", "Cuando salir, preparo la mochila.", "Después de salgo, preparo la mochila."], correct: 0, feedback: "Salir va en infinitivo porque aparece inmediatamente después de antes de." },
    { prompt: "Después de después de también necesitamos infinitivo.", original: "Después de termino, llamo a Ana.", options: ["Después de terminar, llamo a Ana.", "Después de termino, llamo a Ana.", "Antes de terminar, llamo a Ana."], correct: 0, feedback: "Terminar conserva el infinitivo; conjugarlo aquí rompe la estructura seleccionada." },
    { prompt: "Cuando habitual necesita un verbo conjugado.", original: "Cuando llegar a casa, preparo la cena.", options: ["Cuando llego a casa, preparo la cena.", "Antes de llego a casa, preparo la cena.", "Después de llegar a casa, preparo la cena."], correct: 0, feedback: "Con cuando habitual usamos llego en presente; la opción elegida conserva el significado original." },
    { prompt: "La cronología debe coincidir con la situación.", original: "Antes de desayunar, me despierto.", options: ["Después de despertarme, desayuno.", "Antes de despertarme, desayuno.", "Cuando desayunar, me despierto."], correct: 0, feedback: "Primero ocurre despertarse y después desayunar; la forma reparada expresa ese orden real." },
  ],
  retrieval: [
    { intention: "MAÑANA", prompt: "Sin conectores visibles: enlazá levantarte, ducharte, desayunar y salir.", challenge: "Usá las tres estructuras y repetí la secuencia sin mirar." },
    { intention: "TRABAJO", prompt: "Explicá tres acciones habituales desde que llegás al trabajo.", challenge: "Incluí cuando + presente y una estructura con infinitivo." },
    { intention: "VIAJE", prompt: "Reconstruí un viaje con comprar, esperar, subir y llegar.", challenge: "Cambiá el orden de una frase sin cambiar la cronología." },
    { intention: "COCINA", prompt: "Describí un proceso sencillo con cuatro acciones.", challenge: "Comprobá que tras de no aparece un verbo conjugado." },
    { intention: "FIN DE SEMANA", prompt: "Contá una rutina real sin banco de respuestas.", challenge: "Repetila con menos pausas y al menos tres enlaces temporales." },
  ],
  production: [
    { title: "Un día laboral", prompt: "Narrá desde que te levantás hasta que empezás a trabajar.", checklist: ["6 acciones", "las tres estructuras", "orden cronológico claro"] },
    { title: "Un proceso útil", prompt: "Enseñale al profesor cómo preparás algo o cómo llegás a un lugar.", checklist: ["instrucciones personales", "una reparación si cambia el orden", "sin leer"] },
    { title: "Cambio de contexto", prompt: "Repetí la secuencia para un día de viaje o un fin de semana.", checklist: ["menos apoyo", "conectores variados", "una repregunta natural"] },
  ],
  conversationMinutes: 7,
  conversation: [
    { question: "¿Qué hacés antes de salir de casa?", starter: "Antes de salir…", followUp: "¿Qué cambia cuando tenés prisa?" },
    { question: "¿Qué hacés después de terminar de trabajar o estudiar?", starter: "Después de terminar…", followUp: "¿Lo hacés todos los días?" },
    { question: "¿Qué pasa cuando llegás tarde a un lugar?", starter: "Cuando llego tarde…", followUp: "¿Qué hacés primero en esa situación?" },
    { question: "¿Cómo preparás una comida sencilla?", starter: "Antes de cocinar…", followUp: "¿Qué hacés después de preparar los ingredientes?" },
    { question: "¿Cómo es tu rutina antes de dormir?", starter: "Antes de dormir…", followUp: "¿Qué parte te gustaría cambiar?" },
    { question: "¿Qué hacés cuando viajás en transporte público?", starter: "Cuando viajo…", followUp: "¿Qué hacés antes de subir?" },
    { question: "¿Cómo cambia tu mañana durante el fin de semana?", starter: "Cuando es fin de semana…", followUp: "¿Qué hacés después de levantarte?" },
  ],
  finalTask: "Mi secuencia real de 6 acciones: explicá una rutina o proceso con antes de, después de y cuando; el profesor cambia un detalle y repregunta para sostener la conversación.",
};

export const siPasaEsto: SyntaxLabData = {
  slug: "si-pasa-esto",
  level: "A2",
  category: "Gramática",
  mode: "decision",
  module: "MÓDULO 15.3.6 · A2",
  pcic: "PCIC 15.3.6 · condicionales A2",
  title: "Si pasa esto…",
  displayTitle: "Si pasa\nesto…",
  subtitle: "Tomá decisiones reales, anticipá consecuencias y negociá un plan que pueda cambiar",
  goal: "Expresar condiciones reales o posibles y consecuencias prácticas en decisiones cotidianas.",
  accent: "#ff8f70",
  accent2: "#7bdff2",
  productiveTargets: ["si + presente de indicativo", "consecuencia práctica en presente", "si / sí"],
  boundaries: "La clase se limita a condiciones reales o posibles en presente y consecuencias prácticas. Las hipótesis irreales y combinaciones avanzadas pertenecen a niveles posteriores.",
  timeline: [
    { label: "Decisiones rápidas", minutes: 5 },
    { label: "Descubrimiento", minutes: 7 },
    { label: "Si / sí", minutes: 6 },
    { label: "Cadena guiada", minutes: 8 },
    { label: "Problemas", minutes: 7 },
    { label: "Recuperación", minutes: 5 },
    { label: "Negociación", minutes: 7 },
  ],
  activation: {
    instruction: "Elegí una opción y explicá qué consecuencia práctica aparece. La decisión viene primero; la fórmula se descubre después.",
    cards: [
      { first: "llueve", second: "llevamos paraguas", intention: "TIEMPO" },
      { first: "el tren llega tarde", second: "avisamos", intention: "TRANSPORTE" },
      { first: "no hay entradas", second: "cambiamos el plan", intention: "OCIO" },
      { first: "tenemos tiempo", second: "caminamos", intention: "HORARIO" },
      { first: "el precio es alto", second: "comparamos", intention: "DINERO" },
    ],
  },
  patterns: [
    { key: "condicion-primero", label: "SI PRIMERO", intention: "CONDICIÓN → RESULTADO", formula: "SI + PRESENTE, PRESENTE", example: "Si llueve, llevamos paraguas.", preview: { left: "si llueve", connector: "→", right: "llevamos paraguas" }, explanation: "Si abre una condición real o posible; la consecuencia presenta una acción práctica en presente." },
    { key: "resultado-primero", label: "RESULTADO PRIMERO", intention: "RESULTADO ← CONDICIÓN", formula: "PRESENTE + SI + PRESENTE", example: "Llevamos paraguas si llueve.", preview: { left: "llevamos paraguas", connector: "si", right: "llueve" }, explanation: "El orden puede cambiar sin alterar la relación: la condición sigue usando presente de indicativo." },
    { key: "si-si", label: "SI / SÍ", intention: "CONDICIÓN O AFIRMACIÓN", formula: "SI = CONDICIÓN · SÍ = RESPUESTA", example: "Sí, voy si tengo tiempo.", preview: { left: "sí, voy", connector: "si", right: "tengo tiempo" }, explanation: "Si, sin tilde, introduce la condición. Sí, con tilde, confirma o responde afirmativamente." },
  ],
  decisions: [
    { intention: "TIEMPO", prompt: "Puede llover durante el paseo.", left: "Si llueve", right: "llevamos paraguas.", options: ["→", "porque", "aunque"], correct: 0, feedback: "La lluvia funciona como condición posible y llevar paraguas es una consecuencia práctica." },
    { intention: "TRANSPORTE", prompt: "El tren puede retrasarse.", left: "Si el tren llega tarde", right: "avisamos por mensaje.", options: ["→", "antes de", "para"], correct: 0, feedback: "La llegada tardía activa una decisión concreta; ambos verbos se mantienen en presente." },
    { intention: "HORARIO", prompt: "El tiempo disponible decide el transporte.", left: "Caminamos", right: "tenemos cuarenta minutos.", options: ["sí", "si", "porque sí"], correct: 1, feedback: "Si sin tilde introduce la condición; el resultado puede aparecer antes sin cambiar la relación." },
    { intention: "AFIRMACIÓN", prompt: "Confirmás el plan y añadís una condición.", left: "Sí, vamos al parque", right: "hace buen tiempo.", options: ["si", "sí", "cuando de"], correct: 0, feedback: "El primer sí confirma; el segundo si, sin tilde, abre la condición hace buen tiempo." },
    { intention: "DINERO", prompt: "El precio determina la decisión.", left: "Si cuesta menos de veinte euros", right: "lo compramos.", options: ["→", "antes", "por qué"], correct: 0, feedback: "El precio posible funciona como condición y comprar es la consecuencia práctica acordada." },
    { intention: "RESERVA", prompt: "La disponibilidad cambia el restaurante.", left: "Buscamos otro lugar", right: "no hay mesa.", options: ["sí", "si", "para"], correct: 1, feedback: "Si conecta la falta de mesa con la decisión de buscar otra opción; no expresa afirmación." },
    { intention: "SALUD", prompt: "Una sensación real cambia el plan.", left: "Si estás cansado", right: "descansamos un rato.", options: ["→", "después de", "porque"], correct: 0, feedback: "Estar cansado se presenta como condición posible y descansar como respuesta inmediata." },
    { intention: "PLAN SOCIAL", prompt: "La disponibilidad de Ana define el horario.", left: "Cenamos a las nueve", right: "Ana termina tarde.", options: ["sí", "si", "antes de"], correct: 1, feedback: "Si sin tilde introduce la condición que determina el horario acordado para la cena." },
    { intention: "TECNOLOGÍA", prompt: "La batería puede terminarse.", left: "Si no hay batería", right: "usamos el mapa de papel.", options: ["→", "cuando de", "para que"], correct: 0, feedback: "La falta de batería es una posibilidad real y usar el mapa es la solución práctica." },
    { intention: "ELECCIÓN", prompt: "Confirmás una opción bajo una condición.", left: "Sí, pedimos pizza", right: "todos quieren.", options: ["si", "sí", "por qué"], correct: 0, feedback: "Sí confirma la elección; si introduce la condición real todos quieren sin llevar tilde." },
  ],
  questionAnswerCycle: [
    { question: "¿Vamos al parque?", answer: "Sí, si no llueve.", cue: "confirmar / tiempo" },
    { question: "¿Tomamos el tren?", answer: "Sí, si llega a tiempo.", cue: "confirmar / transporte" },
    { question: "¿Compramos las entradas?", answer: "Sí, si quedan asientos.", cue: "confirmar / disponibilidad" },
    { question: "¿Cenamos afuera?", answer: "Sí, si encontramos una mesa.", cue: "confirmar / reserva" },
  ],
  repairs: [
    { prompt: "Distinguí si / sí por su función.", original: "Si, vamos sí hay tiempo.", options: ["Sí, vamos si hay tiempo.", "Si, vamos sí hay tiempo.", "Sí, vamos sí hay tiempo."], correct: 0, feedback: "Sí confirma la respuesta; si sin tilde introduce la condición que debe cumplirse." },
    { prompt: "La condición A2 usa presente de indicativo.", original: "Si tengo tiempo, llamo después.", options: ["Si tengo tiempo, llamo después.", "Si tiempo, llamo después.", "Sí tengo tiempo si llamo después."], correct: 0, feedback: "Tengo expresa una condición real en presente y llamo presenta su consecuencia práctica." },
    { prompt: "La consecuencia debe responder al problema.", original: "Si el autobús no llega, esperamos el autobús para siempre.", options: ["Si el autobús no llega, tomamos el metro.", "Sí el autobús no llega, tomamos el metro.", "Tomamos el metro sí el autobús."], correct: 0, feedback: "Tomar el metro resuelve el problema y si, sin tilde, conserva la relación condicional." },
    { prompt: "El orden puede variar, pero ambas ideas necesitan verbo.", original: "Nos quedamos en casa si lluvia.", options: ["Nos quedamos en casa si llueve.", "Si lluvia, nos quedamos.", "Sí llueve, nos quedamos en casa."], correct: 0, feedback: "Llueve completa la condición en presente; la posición final de la cláusula es perfectamente posible." },
  ],
  retrieval: [
    { intention: "TIEMPO", prompt: "Sin banco de respuestas: proponé dos planes según el tiempo.", challenge: "Variá el orden de una condición sin cambiar su sentido." },
    { intention: "TRANSPORTE", prompt: "Resolvé un retraso y una cancelación con dos condiciones reales.", challenge: "Usá dos consecuencias prácticas diferentes." },
    { intention: "DINERO", prompt: "Decidí qué hacés si un precio es alto o bajo.", challenge: "Incluí una confirmación con sí y una condición con si." },
    { intention: "PLAN SOCIAL", prompt: "Negociá hora, lugar y comida usando palabras clave solamente.", challenge: "Respondé a un cambio sin leer ninguna fórmula." },
    { intention: "DISPONIBILIDAD", prompt: "Creá una cadena de tres decisiones conectadas.", challenge: "Repetí la cadena con menos pausas y otro orden." },
  ],
  production: [
    { title: "Plan A / Plan B", prompt: "Prepará un plan y dos alternativas para una salida.", checklist: ["3 condiciones reales", "consecuencias útiles", "si / sí correctos"] },
    { title: "Resolver juntos", prompt: "Respondé a problemas de tiempo, transporte y dinero.", checklist: ["decidir antes de explicar", "variar el orden", "pedir acuerdo"] },
    { title: "Cadena viva", prompt: "Cada respuesta cambia el escenario siguiente.", checklist: ["sin frases preparadas", "6 condiciones en total", "negociación real"] },
  ],
  conversationMinutes: 7,
  conversation: [
    { question: "¿Qué hacemos si llueve durante el paseo?", starter: "Si llueve…", followUp: "¿Y si deja de llover temprano?" },
    { question: "¿Qué hacemos si el tren llega tarde?", starter: "Si llega tarde…", followUp: "¿Aceptás ese plan o proponés otro?" },
    { question: "¿Compramos las entradas si son caras?", starter: "Sí/No, si…", followUp: "¿Cuál es el precio máximo?" },
    { question: "¿Qué hacemos si no hay mesa en el restaurante?", starter: "Si no hay mesa…", followUp: "¿Qué opción preferís y por qué?" },
    { question: "¿Cambiamos la hora si alguien termina tarde?", starter: "Sí, cambiamos… si…", followUp: "¿Qué hora funciona para todos?" },
    { question: "¿Qué hacemos si el teléfono no tiene batería?", starter: "Si no tiene batería…", followUp: "¿Qué necesitamos preparar antes?" },
    { question: "¿Cómo organizamos el fin de semana si cada persona quiere algo distinto?", starter: "Si una persona quiere…", followUp: "¿Qué condición te parece más importante?" },
  ],
  finalTask: "Una negociación con 6 condiciones: acordá con el profesor un plan real que cambia según el tiempo, transporte, presupuesto y disponibilidad; reaccioná espontáneamente a cada cambio.",
};

export const peroHayUnMatiz: SyntaxLabData = {
  slug: "pero-hay-un-matiz",
  level: "B1",
  category: "Gramática",
  mode: "contrast",
  module: "MÓDULO 14.1 / 14.3 · B1",
  pcic: "PCIC 14.1 y 14.3 · coordinación B1",
  title: "Pero hay un matiz",
  displayTitle: "Pero hay\nun matiz",
  subtitle: "Pasá del contraste básico al contrapunto natural y defendé una opinión sin encadenar siempre pero",
  goal: "Organizar posiciones, objeciones y alternativas negativas con ni… ni, sin embargo y aunque adversativo.",
  accent: "#ff8066",
  accent2: "#ffd166",
  productiveTargets: ["ni… ni", "sin embargo", "aunque adversativo"],
  boundaries: "Partimos de pero, ya conocido, para organizar el discurso B1. Aunque se trabaja como contrapunto equivalente a pero; el sistema completo de subordinación concesiva queda para otra ruta.",
  timeline: [
    { label: "Activación", minutes: 5 },
    { label: "Subir el nivel", minutes: 6 },
    { label: "Mezclador guiado", minutes: 8 },
    { label: "Forma y posición", minutes: 6 },
    { label: "Trampa de sentido", minutes: 6 },
    { label: "Reformulación", minutes: 6 },
    { label: "Panel de opinión", minutes: 8 },
  ],
  activation: {
    instruction: "Escuchá cada par y decidí si suma información, niega las dos opciones o introduce un contrapunto. Todavía no elijas el conector.",
    cards: [
      { first: "El sueldo es bueno", second: "el horario es difícil", intention: "CONTRAPESO" },
      { first: "No quiero conducir", second: "quiero volar", intention: "DOBLE NEGACIÓN" },
      { first: "La idea parece simple", second: "exige mucha coordinación", intention: "OBJECIÓN" },
      { first: "La ciudad es intensa", second: "ofrece muchas oportunidades", intention: "MATIZ" },
      { first: "No llamó Ana", second: "llamó Marcos", intention: "DOS ALTERNATIVAS NEGADAS" },
    ],
  },
  patterns: [
    {
      key: "ni-ni", label: "NI… NI", intention: "NEGAR DOS ALTERNATIVAS", formula: "NI + OPCIÓN A + NI + OPCIÓN B",
      example: "Ni el precio ni la distancia son el problema.",
      preview: { left: "el precio", connector: "ni… ni", right: "la distancia son el problema" },
      explanation: "Ni… ni coloca dos elementos bajo la misma negación. La estructura evita repetir no y presenta las alternativas con el mismo peso.",
    },
    {
      key: "sin-embargo", label: "SIN EMBARGO", intention: "CONTRAPESO EXPLÍCITO", formula: "IDEA. SIN EMBARGO, CONTRAPESO",
      example: "El plan es caro. Sin embargo, ahorra mucho tiempo.",
      preview: { left: "El plan es caro.", connector: "Sin embargo,", right: "ahorra mucho tiempo." },
      explanation: "Sin embargo separa y organiza dos afirmaciones completas. El punto o punto y coma y la coma posterior hacen visible el cambio de dirección.",
    },
    {
      key: "aunque-adversativo", label: "AUNQUE", intention: "MATIZ BREVE", formula: "IDEA, AUNQUE + MATIZ",
      example: "La propuesta es útil, aunque cara.",
      preview: { left: "La propuesta es útil", connector: "aunque", right: "cara." },
      explanation: "En este uso adversativo, aunque introduce un matiz breve equivalente a pero. No abre aquí una condición que deba superarse.",
    },
  ],
  decisions: [
    { intention: "DOBLE NEGACIÓN", prompt: "Descartás por igual dos explicaciones.", left: "El problema es", right: "el tiempo.", options: ["sin embargo", "ni el dinero ni", "aunque"], correct: 1, feedback: "Ni… ni coloca dinero y tiempo dentro de la misma negación y evita presentar una de las causas como principal." },
    { intention: "CONTRAPESO FORMAL", prompt: "La segunda afirmación corrige una impresión demasiado negativa.", left: "El curso exige mucho trabajo.", right: "los resultados llegan pronto.", options: ["Ni", "Sin embargo,", "Y"], correct: 1, feedback: "Sin embargo organiza dos afirmaciones completas y anuncia que la segunda limita la valoración inicial." },
    { intention: "MATIZ BREVE", prompt: "La cualidad final limita la valoración sin abrir otro argumento.", left: "Es una solución eficaz", right: "provisional.", options: ["aunque", "ni", "sin embargo"], correct: 0, feedback: "Aunque adversativo introduce un matiz breve, cercano a pero, dentro de la misma unidad informativa." },
    { intention: "DOBLE NEGACIÓN", prompt: "La persona rechaza las dos opciones de transporte.", left: "Quiere viajar", right: "en avión.", options: ["aunque", "ni en tren ni", "sin embargo"], correct: 1, feedback: "Ni en tren ni en avión presenta dos alternativas igualmente negadas y conserva una estructura paralela." },
    { intention: "OBJECIÓN", prompt: "El segundo dato obliga a revisar la primera conclusión.", left: "La zona queda lejos.", right: "está muy bien conectada.", options: ["Sin embargo,", "Ni", "Porque"], correct: 0, feedback: "Sin embargo convierte la buena conexión en un contrapeso explícito frente a la distancia inicial." },
    { intention: "REGISTRO", prompt: "Buscás una versión editorial más organizada que una cadena con pero.", left: "La medida es popular.", right: "no resuelve el problema central.", options: ["O", "Sin embargo,", "Ni"], correct: 1, feedback: "Sin embargo permite ordenar el contraargumento y resulta más adecuado para un comentario editorial B1." },
    { intention: "MATIZ", prompt: "Añadís una reserva corta sobre una experiencia positiva.", left: "La reunión fue productiva", right: "demasiado larga.", options: ["aunque", "ni", "por eso"], correct: 0, feedback: "Aunque adversativo añade una reserva breve sin convertirla en una explicación ni en una consecuencia." },
    { intention: "CONTRASTE DE OPINIÓN", prompt: "Respondés a alguien con un beneficio que cambia el balance.", left: "Trabajar desde casa puede aislar.", right: "ofrece más autonomía.", options: ["Sin embargo,", "Ni… ni", "También"], correct: 0, feedback: "Sin embargo introduce el beneficio como contrapeso y ayuda a responder directamente a la objeción anterior." },
    { intention: "TRAMPA DE SENTIDO", prompt: "Elegí el uso adversativo, no una lectura concesiva con situación futura.", left: "La película es interesante", right: "un poco lenta.", options: ["aunque", "aunque mañana llueva", "ni"], correct: 0, feedback: "Interesante, aunque lenta contiene un matiz adversativo; la opción con lluvia abre una relación concesiva diferente." },
    { intention: "NEGACIÓN PARALELA", prompt: "Negás que dos personas sean responsables.", left: "Fue", right: "Lucía.", options: ["sin embargo", "ni Pablo ni", "aunque"], correct: 1, feedback: "Ni Pablo ni Lucía presenta dos posibles responsables bajo una sola negación y mantiene el paralelismo." },
  ],
  questionAnswerCycle: [],
  repairs: [
    { prompt: "Repará la posición y la puntuación del conector.", original: "El proyecto es útil sin embargo necesita cambios.", options: ["El proyecto es útil. Sin embargo, necesita cambios.", "El proyecto es útil, sin embargo necesita cambios.", "Sin embargo el proyecto es útil necesita cambios."], correct: 0, feedback: "Dos afirmaciones completas se separan y sin embargo lleva coma posterior para marcar el giro discursivo." },
    { prompt: "Construí una doble negación paralela.", original: "No me convence el precio y tampoco la duración.", options: ["No me convencen ni el precio ni la duración.", "Ni me convence el precio sin embargo la duración.", "Aunque el precio ni la duración me convencen."], correct: 0, feedback: "Ni… ni coordina los dos elementos negados con la misma función y evita una segunda negación añadida." },
    { prompt: "Conservá un matiz adversativo breve.", original: "La habitación es cómoda, aunque no reserve si mañana hay ruido.", options: ["La habitación es cómoda, aunque pequeña.", "Aunque mañana haya ruido, la habitación es cómoda.", "La habitación ni es cómoda ni pequeña."], correct: 0, feedback: "Cómoda, aunque pequeña contrapone dos rasgos; la alternativa temporal pertenece a otra relación de significado." },
    { prompt: "Evitá tratar todos los conectores como intercambiables.", original: "Ni el barrio es caro ni tiene buen transporte.", options: ["El barrio es caro. Sin embargo, tiene buen transporte.", "El barrio es caro ni tiene buen transporte.", "Aunque el barrio ni es caro, tiene transporte."], correct: 0, feedback: "La intención es contraponer una desventaja y una ventaja, no negar las dos; sin embargo expresa ese balance." },
  ],
  retrieval: [
    { intention: "REFORMULAR", prompt: "Sin etiquetas: convertí tres cadenas con pero usando dos alternativas distintas.", challenge: "Explicá qué cambia en la organización y no solo reemplaces palabras." },
    { intention: "DOBLE NEGACIÓN", prompt: "Negá dos causas, dos opciones y dos responsables sin banco de conectores.", challenge: "Mantené la estructura paralela y una entonación natural." },
    { intention: "CONTRAPESO", prompt: "Recibís una opinión tajante: respondé con un dato que cambie el balance.", challenge: "Usá sin embargo y después reformulá con pero para comparar." },
    { intention: "MATIZ", prompt: "Describí tres cosas positivas con una reserva breve.", challenge: "Usá aunque adversativo sin abrir una situación hipotética." },
    { intention: "TERCER DATO", prompt: "Sumá una tercera información que obligue a rehacer tu frase inicial.", challenge: "Elegí de nuevo la relación, la posición y la puntuación." },
  ],
  production: [
    { title: "Trabajo y vida", prompt: "Defendé una forma de trabajo y respondé a dos objeciones.", checklist: ["dos contrapesos", "una doble negación", "respuesta al profesor"] },
    { title: "Ciudad ideal", prompt: "Evaluá vivir en una ciudad grande o pequeña sin dar una respuesta absoluta.", checklist: ["ventaja y límite", "sin embargo", "aunque adversativo"] },
    { title: "Tecnología cotidiana", prompt: "Tomá postura sobre una herramienta y reformulala cuando aparece un tercer dato.", checklist: ["postura clara", "reformulación", "conectores no intercambiables"] },
  ],
  conversationMinutes: 8,
  conversation: [
    { question: "¿Trabajar desde casa mejora realmente la vida?", starter: "Mejora algunas cosas. Sin embargo…", followUp: "¿Qué objeción cambiaría tu postura?" },
    { question: "¿Una ciudad cara puede seguir siendo una buena elección?", starter: "Es cara, aunque…", followUp: "¿Qué dos problemas no aceptarías nunca?" },
    { question: "¿Las redes sociales conectan o aíslan?", starter: "Conectan a mucha gente. Sin embargo…", followUp: "¿Podés responder a la opinión contraria?" },
    { question: "¿Preferís estabilidad o libertad profesional?", starter: "Valoro la estabilidad, aunque…", followUp: "¿Qué no querés perder en ninguna opción?" },
    { question: "¿La educación online puede reemplazar la presencial?", starter: "Tiene ventajas. Sin embargo…", followUp: "¿Qué matiz añadirías después de escucharme?" },
    { question: "¿Qué plan popular no te convence completamente?", starter: "Es popular, aunque…", followUp: "¿Qué dos argumentos no te parecen suficientes?" },
  ],
  finalTask: "Panel de opinión B1: defendé una postura sobre tres temas familiares, respondé a objeciones con dos contrapesos y usá una construcción ni… ni de forma natural.",
};

export const laPersonaQueTengoEnMente: SyntaxLabData = {
  slug: "la-persona-que-tengo-en-mente",
  level: "B1",
  category: "Gramática",
  mode: "referent",
  module: "MÓDULO 15.2 · B1",
  pcic: "PCIC 15.2 · relativas B1",
  title: "La persona que tengo en mente",
  displayTitle: "La persona que\ntengo en mente",
  subtitle: "Identificá personas, lugares y cosas con precisión, repará ambigüedades y conectá la información",
  goal: "Usar un antecedente expreso y una cláusula relativa para identificar un único referente y aclararlo cuando haya confusión.",
  accent: "#62d0c2",
  accent2: "#ffd166",
  productiveTargets: ["antecedente expreso + que", "persona + quien", "indicativo conocido"],
  boundaries: "El núcleo productivo es antecedente expreso + que con tiempos de indicativo ya conocidos. Quien aparece solo en contextos claros de persona; quedan fuera los relativos libres y las combinaciones preposicionales complejas.",
  timeline: [
    { label: "Calentamiento", minutes: 5 },
    { label: "Descubrimiento", minutes: 7 },
    { label: "Buscador guiado", minutes: 8 },
    { label: "Reparar ambigüedad", minutes: 7 },
    { label: "Reciclar tiempos", minutes: 6 },
    { label: "Información parcial", minutes: 5 },
    { label: "Búsqueda real", minutes: 7 },
  ],
  activation: {
    instruction: "Dos tarjetas comparten rasgos. Añadí un dato que permita identificar solo una sin repetir oraciones separadas.",
    cards: [
      { first: "una compañera trabaja conmigo", second: "vive cerca del centro", intention: "PERSONA" },
      { first: "un café está junto al río", second: "abre hasta tarde", intention: "LUGAR" },
      { first: "una mochila es azul", second: "compré la mochila en Lima", intention: "COSA" },
      { first: "un profesor me ayudó", second: "el profesor hablaba despacio", intention: "PASADO" },
      { first: "una amiga viajará conmigo", second: "conozco a la amiga desde 2020", intention: "FUTURO" },
    ],
  },
  patterns: [
    {
      key: "que-persona", label: "PERSONA + QUE", intention: "IDENTIFICAR PERSONA", formula: "PERSONA + QUE + INFORMACIÓN",
      example: "Busco a la compañera que vive cerca del centro.",
      preview: { left: "la compañera", connector: "que", right: "vive cerca del centro" },
      explanation: "Que conecta el antecedente persona con el dato que permite distinguirlo de otras personas posibles.",
    },
    {
      key: "que-cosa-lugar", label: "COSA / LUGAR + QUE", intention: "IDENTIFICAR REFERENTE", formula: "ANTECEDENTE + QUE + INFORMACIÓN",
      example: "Elegí el café que abre hasta tarde.",
      preview: { left: "el café", connector: "que", right: "abre hasta tarde" },
      explanation: "Que también identifica cosas y lugares. El antecedente debe aparecer para que el oyente sepa qué se está filtrando.",
    },
    {
      key: "quien-persona", label: "QUIEN · PERSONA", intention: "RETOMAR UNA PERSONA", formula: "PERSONA IDENTIFICADA, QUIEN + DATO",
      example: "Hablé con Lucía, quien coordinó el proyecto.",
      preview: { left: "Lucía", connector: "quien", right: "coordinó el proyecto" },
      explanation: "Quien solo puede retomar personas. En esta clase se usa cuando la persona ya está identificada y se añade un dato claro sobre ella.",
    },
  ],
  decisions: [
    { intention: "PERSONA", prompt: "Hay dos compañeras; solo una vive cerca del centro.", left: "Busco a la compañera", right: "vive cerca del centro.", options: ["que", "quien", "donde"], correct: 0, feedback: "Que introduce el dato restrictivo que selecciona una compañera concreta entre varias candidatas." },
    { intention: "LUGAR", prompt: "Elegís entre varios cafés según su horario.", left: "Prefiero el café", right: "abre hasta medianoche.", options: ["quien", "que", "cuando"], correct: 1, feedback: "El antecedente es un lugar y que conecta el horario que permite identificar exactamente ese café." },
    { intention: "COSA", prompt: "Hay varias mochilas y solo una fue comprada en Lima.", left: "La mochila", right: "compré en Lima es azul.", options: ["que", "quien", "porque"], correct: 0, feedback: "Que enlaza mochila con una acción pasada ya conocida y distingue esa mochila de las demás." },
    { intention: "PERSONA YA IDENTIFICADA", prompt: "Lucía ya está identificada y añadís qué función cumplió.", left: "Hablé con Lucía", right: "coordinó el proyecto.", options: ["que", "quien", "donde"], correct: 1, feedback: "Quien retoma a una persona ya identificada y añade un dato sobre ella sin crear un nuevo candidato." },
    { intention: "ANTECEDENTE", prompt: "La información debe quedar unida al nombre correcto.", left: "Necesito el documento", right: "enviaste ayer.", options: ["quien", "que", "aunque"], correct: 1, feedback: "Documento es el antecedente expreso y que introduce la acción pasada que permite reconocerlo." },
    { intention: "TIEMPO RECICLADO", prompt: "Identificás a alguien mediante un hábito anterior.", left: "Es el vecino", right: "siempre saludaba desde el balcón.", options: ["que", "quien", "si"], correct: 0, feedback: "Que mantiene el foco en la arquitectura relativa; saludaba recicla un tiempo pasado ya conocido." },
    { intention: "FUTURO CONOCIDO", prompt: "Entre varias personas, una acompañará al grupo.", left: "La guía", right: "viajará con nosotros habla portugués.", options: ["quien", "que", "sin embargo"], correct: 1, feedback: "Que selecciona a la guía mediante una acción futura conocida sin convertir la actividad en una clase de conjugación." },
    { intention: "REFERENTE ÚNICO", prompt: "Solo una película recibió esa recomendación.", left: "Vi la película", right: "me recomendaste.", options: ["que", "quien", "donde"], correct: 0, feedback: "Que relaciona película con la recomendación y permite al interlocutor recuperar un único referente." },
    { intention: "QUIEN", prompt: "Añadís información sobre Mario, no lo distinguís de otros Marios.", left: "Mario", right: "dirigió el taller, llegará mañana.", options: ["que", "quien", "cuando"], correct: 1, feedback: "Quien es posible porque Mario ya identifica a la persona; el dato intermedio aporta información adicional." },
    { intention: "TRAMPA DE AMBIGÜEDAD", prompt: "¿Qué enlace conserva un antecedente expreso y claro?", left: "Quiero visitar el pueblo", right: "aparece en la foto.", options: ["quien", "que", "lo que"], correct: 1, feedback: "Que conecta pueblo con el dato identificador; el antecedente expreso evita una referencia libre o imprecisa." },
  ],
  questionAnswerCycle: [],
  repairs: [
    { prompt: "Repará la ambigüedad: dos personas podrían vivir en Valencia.", original: "Busco a la amiga de Marta que vive en Valencia.", options: ["Busco a la amiga de Marta; la amiga vive en Valencia.", "Marta vive en Valencia; busco a su amiga.", "Busco a la que vive en Valencia."], correct: 1, feedback: "Nombrar primero a Marta y luego retomar a su amiga deja claro quién vive en Valencia y evita dos lecturas." },
    { prompt: "Añadí el antecedente que falta.", original: "Que está junto a la estación abre temprano.", options: ["El café que está junto a la estación abre temprano.", "Quien está junto a la estación abre temprano.", "El café donde que está junto a la estación abre temprano."], correct: 0, feedback: "El café funciona como antecedente expreso y permite interpretar qué elemento identifica la cláusula relativa." },
    { prompt: "Elegí un dato que identifique solo una candidata.", original: "Busco a la persona que trabaja.", options: ["Busco a la persona que trabaja en recepción por la noche.", "Busco a la persona que es una persona.", "Busco a quien trabaja."], correct: 0, feedback: "El lugar y el horario vuelven específica la descripción; decir solo trabaja deja demasiadas candidatas." },
    { prompt: "Quien necesita un referente humano ya claro en este uso.", original: "El teléfono, quien compré ayer, no funciona.", options: ["El teléfono que compré ayer no funciona.", "El teléfono, quien compré ayer, no funciona.", "Quien teléfono compré ayer no funciona."], correct: 0, feedback: "Teléfono no es una persona; que enlaza correctamente la cosa con la acción que permite identificarla." },
  ],
  retrieval: [
    { intention: "PERSONAS", prompt: "Sin marco: distinguí a una persona entre tres candidatos parecidos.", challenge: "Usá dos datos y comprobá que solo queda una opción posible." },
    { intention: "LUGARES", prompt: "Describí un lugar real sin decir su nombre.", challenge: "El profesor propone un candidato incorrecto y vos aclarás la referencia." },
    { intention: "COSAS", prompt: "Con información incompleta, identificá tres objetos de tu entorno.", challenge: "Cambiá un dato si la descripción selecciona más de un objeto." },
    { intention: "TIEMPOS", prompt: "Recuperá una persona que conociste y un lugar que visitarás.", challenge: "Usá tiempos conocidos sin explicar cómo se conjugan." },
    { intention: "QUIEN", prompt: "Sin apoyo: nombrá a una persona concreta y añadí un dato sobre ella.", challenge: "Después reformulá con que y explicá qué información identifica." },
  ],
  production: [
    { title: "Directorio humano", prompt: "Presentá tres personas de tu vida sin usar oraciones desconectadas.", checklist: ["antecedentes claros", "datos identificadores", "una aclaración"] },
    { title: "Filtro de viaje", prompt: "Describí dos lugares y dos cosas necesarias para un viaje.", checklist: ["que productivo", "presente y pasado", "referente único"] },
    { title: "Candidato equivocado", prompt: "El profesor adivina mal y vos reparás cada descripción.", checklist: ["más precisión", "sin marco escrito", "preguntas de seguimiento"] },
  ],
  conversationMinutes: 7,
  conversation: [
    { question: "¿Quién es una persona que influyó en tu forma de trabajar o estudiar?", starter: "Es una persona que…", followUp: "¿Qué dato permite distinguirla de otras personas?" },
    { question: "¿Cuál es el lugar que más recordás de un viaje?", starter: "Es un lugar que…", followUp: "Creo que hablás de otro lugar: ¿podés aclararlo?" },
    { question: "¿Qué objeto que usás todos los días te resulta indispensable?", starter: "El objeto que…", followUp: "¿Qué lo diferencia de otros objetos parecidos?" },
    { question: "¿Quién es alguien que conociste recientemente?", starter: "Conocí a una persona que…", followUp: "¿Qué estaba haciendo cuando se conocieron?" },
    { question: "¿Qué lugar que todavía no visitaste te interesa?", starter: "Me interesa un lugar que…", followUp: "¿Qué harás allí si finalmente viajás?" },
    { question: "¿Qué profesional que admirás recomendarías?", starter: "Recomendaría a… quien…", followUp: "No estoy seguro de quién hablás: añadí otro dato." },
  ],
  finalTask: "Encontrá a la persona, el lugar y la cosa: describí seis referentes reales o plausibles; el profesor ofrece candidatos equivocados y vos tenés que aclarar cada uno.",
};
