export type Pair={es:string;en:string};
export type UsaPlace={name:string;state:string;tag:string;context:Pair;questions:Pair[];words:Pair[]};
export type UsaRegion={code:string;number:string;name:string;nameEn:string;color:string;zone:"este"|"centro"|"oeste"|"no-contiguo";hook:Pair;fact:Pair;mission:Pair;places:UsaPlace[]};

const p=(es:string,en:string):Pair=>({es,en});
const place=(name:string,state:string,tag:string,context:Pair,questions:Pair[],words:Pair[]):UsaPlace=>({name,state,tag,context,questions,words});

export const regions:UsaRegion[]=[
  {code:"NE",number:"01",name:"Nueva Inglaterra",nameEn:"New England",color:"#f15b4a",zone:"este",
    hook:p("Ciudades universitarias, costa, pueblos y memoria","University cities, coastlines, towns and memory"),
    fact:p("Esta zona reúne seis estados pequeños, pero cambia mucho entre las ciudades costeras, las montañas y los pueblos rurales.","This zone brings together six small states, but it changes greatly between coastal cities, mountains and rural towns."),
    mission:p("Compará quién puede vivir, trabajar y viajar en lugares con mucha historia.","Compare who can live, work and travel in places with a lot of history."),
    places:[
      place("Boston","MASSACHUSETTS","UNIVERSIDADES + VIVIENDA",p("Universidades, hospitales, barrios históricos y transporte público atraen a personas de todo el mundo, pero vivir cerca del centro puede ser muy caro.","Universities, hospitals, historic neighbourhoods and public transport attract people from around the world, but living near the centre can be very expensive."),[p("¿Pagarías más para vivir cerca del centro y no usar auto?","Would you pay more to live near the centre and not use a car?"),p("¿Cómo cambia una ciudad cuando llegan estudiantes de muchos países?","How does a city change when students arrive from many countries?"),p("Tenés una tarde: ¿buscás historia, comida o vida de barrio? ¿Por qué?","You have one afternoon: do you look for history, food or neighbourhood life? Why?")],[p("el alquiler","rent"),p("el barrio","neighbourhood"),p("la universidad","university"),p("moverse","to get around"),p("caro","expensive"),p("internacional","international")]),
      place("Salem","MASSACHUSETTS","MEMORIA + TURISMO",p("La ciudad recibe visitantes por los juicios de 1692 y debe decidir cómo contar una historia trágica sin convertirla solamente en espectáculo.","The city receives visitors because of the 1692 trials and must decide how to tell a tragic story without turning it only into entertainment."),[p("¿Una ciudad puede usar una tragedia histórica para atraer turistas?","Can a city use a historic tragedy to attract tourists?"),p("¿Qué necesita un museo para contar una historia difícil con respeto?","What does a museum need to tell a difficult story respectfully?"),p("¿Visitaste un lugar que cambió tu opinión sobre el pasado?","Have you visited a place that changed your view of the past?")],[p("la memoria","memory"),p("el juicio","trial"),p("la víctima","victim"),p("contar","to tell"),p("respetuoso","respectful"),p("el espectáculo","show / spectacle")]),
      place("Parque Nacional Acadia","MAINE","NATURALEZA + LÍMITES",p("Acadia mezcla montañas de granito, bosques y costa atlántica. Algunas áreas muy populares usan reservas para controlar el acceso.","Acadia combines granite mountains, forests and Atlantic coastline. Some very popular areas use reservations to control access."),[p("¿Aceptarías reservar una hora exacta para entrar a un paisaje natural?","Would you accept booking an exact time to enter a natural landscape?"),p("¿Qué se pierde cuando un lugar tranquilo se vuelve famoso en redes?","What is lost when a quiet place becomes famous on social media?"),p("¿Es mejor recibir menos visitantes o cobrar más para proteger el parque?","Is it better to receive fewer visitors or charge more to protect the park?")],[p("la reserva","reservation"),p("el acceso","access"),p("la costa","coast"),p("proteger","to protect"),p("masivo","mass / crowded"),p("el sendero","trail")]),
      place("Pueblos de Vermont","VERMONT","VIDA RURAL + CAMBIO",p("Los pueblos pequeños protegen paisajes, granjas y negocios locales mientras reciben nuevos residentes y trabajadores remotos.","Small towns protect landscapes, farms and local businesses while receiving new residents and remote workers."),[p("¿Un pueblo sin centros comerciales puede tener mejor calidad de vida?","Can a town without shopping malls have a better quality of life?"),p("¿Los trabajadores remotos ayudan a un pueblo o suben demasiado los precios?","Do remote workers help a town or raise prices too much?"),p("¿Qué negocio local es importante conservar en tu zona?","What local business is important to preserve in your area?")],[p("el pueblo","small town"),p("la granja","farm"),p("local","local"),p("mudarse","to move house"),p("conservar","to preserve"),p("la calidad de vida","quality of life")])
    ]},
  {code:"MA",number:"02",name:"Atlántico Medio",nameEn:"Mid-Atlantic",color:"#f2a93b",zone:"este",
    hook:p("Megaciudades, puertos, industria y bahías","Megacities, ports, industry and bays"),
    fact:p("Nueva York, Pensilvania, Nueva Jersey y la zona de la capital concentran enormes contrastes entre poder, industria, barrios y naturaleza costera.","New York, Pennsylvania, New Jersey and the capital area contain huge contrasts between power, industry, neighbourhoods and coastal nature."),
    mission:p("Decidí cómo una región densa puede crecer sin borrar su historia ni su ambiente.","Decide how a dense region can grow without erasing its history or environment."),
    places:[
      place("Nueva York por barrios","NEW YORK","IDENTIDAD + ESPACIO",p("Cinco distritos comparten una ciudad, pero cada barrio tiene ritmos, precios, idiomas y comunidades diferentes.","Five boroughs share one city, but each neighbourhood has different rhythms, prices, languages and communities."),[p("¿Qué hace que un barrio tenga identidad propia?","What gives a neighbourhood its own identity?"),p("¿Una ciudad mejora cuando todo está abierto las veinticuatro horas?","Does a city improve when everything is open twenty-four hours a day?"),p("¿Qué perdería Nueva York si solamente viviera gente con mucho dinero?","What would New York lose if only wealthy people lived there?")],[p("el distrito","borough"),p("la comunidad","community"),p("el ritmo","pace"),p("accesible","affordable / accessible"),p("mezclarse","to mix"),p("perder","to lose")]),
      place("Filadelfia","PENNSYLVANIA","HISTORIA + PRESENTE",p("La ciudad conecta símbolos de la independencia con barrios actuales, arte público y fuertes diferencias económicas.","The city connects symbols of independence with present-day neighbourhoods, public art and strong economic differences."),[p("¿Los monumentos históricos ayudan a entender los problemas actuales?","Do historic monuments help us understand present-day problems?"),p("¿Quién debe decidir qué personas aparecen en el espacio público?","Who should decide which people appear in public spaces?"),p("¿Qué historia de tu ciudad merece una ruta a pie?","What story from your city deserves a walking route?")],[p("la independencia","independence"),p("el monumento","monument"),p("el espacio público","public space"),p("representar","to represent"),p("el pasado","the past"),p("la desigualdad","inequality")]),
      place("Pittsburgh","PENNSYLVANIA","INDUSTRIA + REINVENCIÓN",p("Después de perder gran parte de su industria pesada, Pittsburgh desarrolló nuevos sectores sin olvidar su identidad obrera.","After losing much of its heavy industry, Pittsburgh developed new sectors without forgetting its working-class identity."),[p("¿Una ciudad debe conservar fábricas viejas aunque ya no produzcan?","Should a city preserve old factories even if they no longer produce anything?"),p("¿Qué necesita una persona para cambiar de profesión cuando desaparece su trabajo?","What does a person need to change careers when their job disappears?"),p("¿Tu ciudad vive del pasado o está creando algo nuevo?","Does your city live from the past or is it creating something new?")],[p("la fábrica","factory"),p("obrero/a","working-class / worker"),p("reinventarse","to reinvent oneself"),p("desaparecer","to disappear"),p("la capacitación","training"),p("el sector","sector")]),
      place("Bahía de Chesapeake","MARYLAND · VIRGINIA","AGUA + ECONOMÍA",p("La bahía sostiene pesca, puertos, ciudades y ecosistemas. Las decisiones de lugares lejanos también afectan la calidad del agua.","The bay supports fishing, ports, cities and ecosystems. Decisions in distant places also affect water quality."),[p("¿Quién debe pagar cuando una actividad económica contamina el agua?","Who should pay when an economic activity pollutes the water?"),p("¿Proteger empleos justifica permitir más contaminación por un tiempo?","Does protecting jobs justify allowing more pollution for a while?"),p("¿Qué río, lago o mar influye en la vida de tu región?","What river, lake or sea influences life in your region?")],[p("la bahía","bay"),p("la pesca","fishing"),p("contaminar","to pollute"),p("el ecosistema","ecosystem"),p("la costa","coast"),p("depender de","to depend on")])
    ]},
  {code:"GL",number:"03",name:"Grandes Lagos",nameEn:"Great Lakes",color:"#3eb6c6",zone:"centro",
    hook:p("Agua dulce, industria, migración y ciudades que cambian","Fresh water, industry, migration and changing cities"),
    fact:p("La región creció con fábricas, puertos y trenes; hoy combina grandes ciudades, agua dulce y procesos intensos de renovación.","The region grew with factories, ports and railways; today it combines major cities, fresh water and intense renewal."),
    mission:p("Pensá cómo renovar una ciudad sin expulsar a quienes sostuvieron su historia.","Think about how to renew a city without pushing out the people who sustained its history."),
    places:[
      place("Chicago","ILLINOIS","TRANSPORTE + BARRIOS",p("El tren elevado conecta un centro denso con barrios muy diferentes, pero la distancia física no siempre elimina la separación social.","The elevated train connects a dense centre with very different neighbourhoods, but physical distance does not always remove social separation."),[p("¿Un buen transporte público puede hacer una ciudad más justa?","Can good public transport make a city fairer?"),p("¿Qué parte de una ciudad conocés mal aunque esté cerca?","What part of a city do you know poorly even though it is nearby?"),p("¿Cómo evitás que un barrio renovado expulse a sus vecinos?","How do you prevent a renovated neighbourhood from pushing out its residents?")],[p("el tren elevado","elevated train"),p("conectar","to connect"),p("la separación","separation"),p("renovar","to renew"),p("expulsar","to push out"),p("justo","fair")]),
      place("Detroit","MICHIGAN","AUTOS + SEGUNDA VIDA",p("Detroit fue símbolo mundial del automóvil. Después de una fuerte pérdida de población, muchos proyectos reutilizaron terrenos y edificios vacíos.","Detroit was a global symbol of the car industry. After a major population loss, many projects reused empty land and buildings."),[p("¿Qué uso nuevo le darías a una fábrica abandonada?","What new use would you give an abandoned factory?"),p("¿Una ciudad con menos habitantes puede ofrecer una vida mejor?","Can a city with fewer inhabitants offer a better life?"),p("¿Qué producto representa a tu ciudad como los autos representan a Detroit?","What product represents your city like cars represent Detroit?")],[p("abandonado","abandoned"),p("reutilizar","to reuse"),p("la industria","industry"),p("la población","population"),p("el terreno","land / lot"),p("recuperarse","to recover")]),
      place("Isla Mackinac","MICHIGAN","SIN AUTOS + TURISMO",p("En la isla, los autos privados están prohibidos y las personas se mueven a pie, en bicicleta o en carruajes.","On the island, private cars are banned and people move around on foot, by bicycle or by carriage."),[p("¿Tu ciudad podría tener un barrio completamente sin autos?","Could your city have a completely car-free neighbourhood?"),p("¿Qué gana y qué pierde un lugar cuando depende del turismo de verano?","What does a place gain and lose when it depends on summer tourism?"),p("¿Aceptarías caminar más si las calles fueran más tranquilas?","Would you accept walking more if the streets were quieter?")],[p("prohibir","to ban"),p("el carruaje","carriage"),p("peatonal","pedestrian"),p("depender de","to depend on"),p("la temporada","season"),p("tranquilo","quiet")]),
      place("Búfalo","NEW YORK","INVIERNO + FRONTERA",p("Búfalo mira a Canadá, vive inviernos intensos y transforma antiguos espacios industriales junto al lago Erie.","Buffalo faces Canada, experiences intense winters and transforms former industrial spaces beside Lake Erie."),[p("¿El clima difícil puede crear una comunidad más unida?","Can difficult weather create a closer community?"),p("¿Qué cambia cuando otro país está a pocos minutos de tu casa?","What changes when another country is only minutes from your home?"),p("¿Cómo convertirías un puerto viejo en un lugar para todos?","How would you turn an old port into a place for everyone?")],[p("la frontera","border"),p("la nevada","snowfall"),p("el puerto","port"),p("transformar","to transform"),p("cercano","nearby"),p("unido","close-knit")])
    ]},
  {code:"AP",number:"04",name:"Apalaches",nameEn:"Appalachia",color:"#6db45a",zone:"este",
    hook:p("Montañas, trabajo, música y comunidades pequeñas","Mountains, work, music and small communities"),
    fact:p("Los Apalaches cruzan muchos estados y no son una sola cultura. La región combina naturaleza, ciudades creativas y comunidades marcadas por cambios económicos.","The Appalachians cross many states and are not a single culture. The region combines nature, creative cities and communities shaped by economic change."),
    mission:p("Evitá los estereotipos y compará qué significa desarrollar una región de montaña.","Avoid stereotypes and compare what developing a mountain region means."),
    places:[
      place("New River Gorge","WEST VIRGINIA","TURISMO + TRANSICIÓN",p("Una zona relacionada con carbón y ferrocarril también atrae visitantes por el río, el puente y los deportes de aventura.","An area connected to coal and railways also attracts visitors because of the river, bridge and adventure sports."),[p("¿El turismo puede reemplazar empleos industriales estables?","Can tourism replace stable industrial jobs?"),p("¿Qué entrenamiento necesita una comunidad cuando cambia su economía?","What training does a community need when its economy changes?"),p("¿Un parque nacional mejora automáticamente la vida local?","Does a national park automatically improve local life?")],[p("el carbón","coal"),p("la transición","transition"),p("el puente","bridge"),p("capacitar","to train"),p("estable","stable"),p("la aventura","adventure")]),
      place("Great Smoky Mountains","TENNESSEE · NORTH CAROLINA","PARQUE + MULTITUDES",p("Es un parque de acceso gratuito con rutas escénicas, bosques y una enorme cantidad de visitantes.","It is a free-access park with scenic roads, forests and a huge number of visitors."),[p("¿Un parque muy visitado debería limitar la entrada algunos días?","Should a heavily visited park limit entry on some days?"),p("¿El acceso gratuito siempre es la opción más justa?","Is free access always the fairest option?"),p("¿Qué comportamiento de los turistas daña un lugar natural?","What tourist behaviour damages a natural place?")],[p("la multitud","crowd"),p("limitar","to limit"),p("gratuito","free of charge"),p("el bosque","forest"),p("dañar","to damage"),p("el acceso","access")]),
      place("Asheville y Blue Ridge","NORTH CAROLINA","CREATIVIDAD + PRECIOS",p("La ciudad atrae artistas, cervecerías y visitantes por su entorno de montaña, pero el éxito también presiona los precios de vivienda.","The city attracts artists, breweries and visitors because of its mountain setting, but success also puts pressure on housing prices."),[p("¿Una ciudad creativa deja de ser auténtica cuando se vuelve muy popular?","Does a creative city stop being authentic when it becomes very popular?"),p("¿Cómo puede el turismo ayudar a artistas locales y no solamente a grandes empresas?","How can tourism help local artists and not only large companies?"),p("¿Qué señal muestra que una ciudad creció demasiado rápido?","What sign shows that a city grew too quickly?")],[p("creativo","creative"),p("auténtico","authentic"),p("la vivienda","housing"),p("atraer","to attract"),p("la empresa","company"),p("crecer","to grow")]),
      place("Este de Kentucky","KENTUCKY","DISTANCIA + SERVICIOS",p("En comunidades de montaña, la distancia puede complicar el acceso a salud, educación y empleo, pero también fortalece redes locales.","In mountain communities, distance can complicate access to health, education and jobs, but it can also strengthen local networks."),[p("¿Qué servicio público es más urgente en una zona rural?","Which public service is most urgent in a rural area?"),p("¿La educación online reduce realmente la desventaja de vivir lejos?","Does online education really reduce the disadvantage of living far away?"),p("¿Qué ventaja de una comunidad pequeña no existe en una gran ciudad?","What advantage of a small community does not exist in a large city?")],[p("rural","rural"),p("la distancia","distance"),p("el servicio público","public service"),p("la red local","local network"),p("la desventaja","disadvantage"),p("el acceso","access")])
    ]},
  {code:"DS",number:"05",name:"Sur Profundo",nameEn:"Deep South",color:"#b56bd8",zone:"este",
    hook:p("Música, memoria, hospitalidad y heridas históricas","Music, memory, hospitality and historical wounds"),
    fact:p("La región produjo formas culturales influyentes y también conserva espacios centrales para hablar de esclavitud, segregación y derechos civiles.","The region produced influential cultural forms and also preserves key places for discussing slavery, segregation and civil rights."),
    mission:p("Relacioná cultura y memoria sin convertir una región compleja en un estereotipo.","Connect culture and memory without turning a complex region into a stereotype."),
    places:[
      place("Nueva Orleans","LOUISIANA","MÚSICA + RESILIENCIA",p("La ciudad mezcla tradiciones afroamericanas, criollas y caribeñas, y vive con el riesgo constante de huracanes e inundaciones.","The city combines African American, Creole and Caribbean traditions, and lives with the constant risk of hurricanes and flooding."),[p("¿La música puede ayudar a una ciudad a recuperarse después de un desastre?","Can music help a city recover after a disaster?"),p("¿Quién debería recibir más ayuda para reconstruir después de una inundación?","Who should receive more help to rebuild after a flood?"),p("¿Cómo se protege una cultura cuando llegan millones de turistas?","How do you protect a culture when millions of tourists arrive?")],[p("la inundación","flood"),p("recuperarse","to recover"),p("la tradición","tradition"),p("reconstruir","to rebuild"),p("proteger","to protect"),p("la mezcla","mix")]),
      place("Delta del Mississippi","MISSISSIPPI","BLUES + TERRITORIO",p("El blues nació de experiencias afroamericanas en una región agrícola donde la música, el trabajo y la historia están profundamente conectados.","The blues grew from African American experiences in an agricultural region where music, work and history are deeply connected."),[p("¿Se puede entender una música sin conocer la historia que la produjo?","Can you understand a type of music without knowing the history that produced it?"),p("¿Cómo puede una ruta musical beneficiar a comunidades pequeñas?","How can a music route benefit small communities?"),p("¿Qué género musical cuenta mejor la historia de tu país?","What music genre best tells the story of your country?")],[p("el origen","origin"),p("agrícola","agricultural"),p("el blues","blues"),p("la experiencia","experience"),p("beneficiar","to benefit"),p("la ruta musical","music route")]),
      place("Montgomery","ALABAMA","DERECHOS + MEMORIA",p("La ciudad reúne lugares relacionados con el movimiento por los derechos civiles y con la historia de la esclavitud y la segregación.","The city brings together places connected to the civil rights movement and the history of slavery and segregation."),[p("¿Visitar un lugar histórico produce más empatía que leer sobre él?","Does visiting a historic place create more empathy than reading about it?"),p("¿Qué responsabilidad tiene una ciudad frente a una injusticia de su pasado?","What responsibility does a city have regarding an injustice in its past?"),p("¿Qué cambio social importante empezó con una acción pequeña?","What important social change began with a small action?")],[p("los derechos civiles","civil rights"),p("la injusticia","injustice"),p("la segregación","segregation"),p("la empatía","empathy"),p("la responsabilidad","responsibility"),p("el cambio social","social change")]),
      place("Savannah","GEORGIA","BELLEZA + HISTORIA",p("Plazas arboladas y arquitectura histórica atraen visitantes, pero la imagen romántica de la ciudad puede esconder historias incómodas.","Tree-filled squares and historic architecture attract visitors, but the city's romantic image can hide uncomfortable histories."),[p("¿Una ciudad bella tiene la obligación de mostrar también su lado difícil?","Does a beautiful city have an obligation to show its difficult side too?"),p("¿Qué edificios antiguos vale la pena conservar y cuáles no?","Which old buildings are worth preserving and which are not?"),p("¿Cómo cambia tu experiencia cuando un guía cuenta una historia inesperada?","How does your experience change when a guide tells an unexpected story?")],[p("la plaza","square"),p("la arquitectura","architecture"),p("ocultar","to hide"),p("incómodo","uncomfortable"),p("conservar","to preserve"),p("el guía","guide")])
    ]},
  {code:"FL",number:"06",name:"Florida y Caribe",nameEn:"Florida & Caribbean Coast",color:"#1fb9a5",zone:"este",
    hook:p("Migración, humedales, fantasía y riesgo climático","Migration, wetlands, fantasy and climate risk"),
    fact:p("Florida conecta Estados Unidos con el Caribe y América Latina, mientras equilibra crecimiento urbano, turismo y ecosistemas frágiles.","Florida connects the United States with the Caribbean and Latin America while balancing urban growth, tourism and fragile ecosystems."),
    mission:p("Elegí qué debe proteger una región cuando su economía y su ambiente están bajo presión.","Choose what a region should protect when its economy and environment are under pressure."),
    places:[
      place("Miami","FLORIDA","ESPAÑOL + IDENTIDAD",p("En muchos espacios de Miami, el español forma parte de la vida cotidiana, los negocios y la identidad de la ciudad.","In many Miami spaces, Spanish is part of everyday life, business and the city's identity."),[p("¿Una ciudad bilingüe necesita ofrecer todos sus servicios en dos idiomas?","Does a bilingual city need to offer all its services in two languages?"),p("¿Hablar otra lengua cambia la forma en que una persona vive la ciudad?","Does speaking another language change how a person experiences the city?"),p("¿Qué parte de una cultura migrante se transforma con la segunda generación?","What part of a migrant culture changes with the second generation?")],[p("bilingüe","bilingual"),p("el servicio","service"),p("la migración","migration"),p("la generación","generation"),p("la identidad","identity"),p("cotidiano","everyday")]),
      place("Everglades","FLORIDA","HUMEDAL + CRECIMIENTO",p("El agua conecta todo el ecosistema de los Everglades; el crecimiento urbano y la agricultura cambian cómo circula.","Water connects the entire Everglades ecosystem; urban growth and agriculture change how it flows."),[p("¿Hasta dónde debe crecer una ciudad cerca de un ecosistema frágil?","How far should a city grow near a fragile ecosystem?"),p("¿Qué actividad debería tener prioridad cuando falta agua?","Which activity should have priority when water is scarce?"),p("¿Por qué cuesta proteger un lugar que muchas personas no visitan?","Why is it difficult to protect a place that many people do not visit?")],[p("el humedal","wetland"),p("el agua dulce","fresh water"),p("frágil","fragile"),p("circular","to flow"),p("la prioridad","priority"),p("la agricultura","agriculture")]),
      place("Orlando","FLORIDA","FANTASÍA + TRABAJO",p("Los parques temáticos venden experiencias perfectas, pero detrás funcionan como ciudades con miles de trabajadores, hoteles y sistemas de transporte.","Theme parks sell perfect experiences, but behind the scenes they operate like cities with thousands of workers, hotels and transport systems."),[p("¿Qué trabajo invisible hace posible una experiencia turística perfecta?","What invisible work makes a perfect tourist experience possible?"),p("¿Una ciudad debería depender tanto de una sola industria?","Should a city depend so heavily on one industry?"),p("¿Preferís una atracción muy organizada o una aventura imprevisible?","Do you prefer a highly organized attraction or an unpredictable adventure?")],[p("el parque temático","theme park"),p("el trabajador","worker"),p("invisible","invisible"),p("depender de","to depend on"),p("la atracción","attraction"),p("imprevisible","unpredictable")]),
      place("Cayos de Florida","FLORIDA","ISLAS + ADAPTACIÓN",p("Una carretera une islas bajas y comunidades que viven del mar, el turismo y la preparación frente a tormentas.","A highway connects low islands and communities that depend on the sea, tourism and storm preparation."),[p("¿Seguirías viviendo en un lugar hermoso con riesgo frecuente de huracanes?","Would you continue living in a beautiful place with frequent hurricane risk?"),p("¿Quién debe pagar para proteger casas privadas frente al aumento del mar?","Who should pay to protect private homes from rising seas?"),p("¿Qué objeto llevarías si tuvieras que evacuar rápido?","What object would you take if you had to evacuate quickly?")],[p("la isla","island"),p("evacuar","to evacuate"),p("la tormenta","storm"),p("el nivel del mar","sea level"),p("el riesgo","risk"),p("prepararse","to prepare")])
    ]},
  {code:"TX",number:"07",name:"Texas y la Frontera",nameEn:"Texas & the Borderlands",color:"#e45f45",zone:"centro",
    hook:p("Energía, ciudades gigantes y vidas entre dos países","Energy, giant cities and lives between two countries"),
    fact:p("Texas contiene grandes áreas urbanas, industrias energéticas, territorios rurales y comunidades fronterizas con conexiones cotidianas con México.","Texas contains major urban areas, energy industries, rural territories and border communities with everyday connections to Mexico."),
    mission:p("Compará crecimiento, identidad y cooperación en una región que no entra en una sola imagen.","Compare growth, identity and cooperation in a region that cannot fit into one image."),
    places:[
      place("Houston","TEXAS","ENERGÍA + ESPACIO",p("Houston relaciona petróleo, medicina, puertos y exploración espacial; su economía mira al subsuelo y al espacio al mismo tiempo.","Houston connects oil, medicine, ports and space exploration; its economy looks underground and into space at the same time."),[p("¿Una ciudad petrolera puede liderar la transición a energías limpias?","Can an oil city lead the transition to clean energy?"),p("¿Qué inversión produce más beneficio: explorar el espacio o mejorar la Tierra?","Which investment creates more benefit: exploring space or improving Earth?"),p("¿Qué industria define hoy a tu ciudad?","Which industry defines your city today?")],[p("el petróleo","oil"),p("la energía limpia","clean energy"),p("el puerto","port"),p("la inversión","investment"),p("explorar","to explore"),p("la industria","industry")]),
      place("El Paso y Ciudad Juárez","TEXAS · CHIHUAHUA","FRONTERA + VIDA DIARIA",p("Dos ciudades de países diferentes forman una región urbana conectada por familias, trabajo, comercio e historia.","Two cities in different countries form an urban region connected by families, work, trade and history."),[p("¿Una frontera puede separar gobiernos pero unir la vida cotidiana?","Can a border separate governments but connect everyday life?"),p("¿Qué debería ser más rápido en una ciudad fronteriza: controlar o conectar?","What should be faster in a border city: controlling or connecting?"),p("¿Cómo cambia una familia cuando vive entre dos países?","How does a family change when it lives between two countries?")],[p("la frontera","border"),p("cruzar","to cross"),p("el comercio","trade"),p("cotidiano","everyday"),p("separar","to separate"),p("conectar","to connect")]),
      place("Austin","TEXAS","TECNOLOGÍA + CRECIMIENTO",p("La música, la universidad y la tecnología hicieron crecer la ciudad rápidamente, con más empleos y también más presión sobre vivienda y transporte.","Music, the university and technology made the city grow quickly, with more jobs and also more pressure on housing and transport."),[p("¿Cómo conserva una ciudad su personalidad cuando llegan grandes empresas?","How does a city preserve its personality when large companies arrive?"),p("¿Más empleos compensan alquileres mucho más altos?","Do more jobs make up for much higher rents?"),p("¿Qué tradición local no debería desaparecer por el crecimiento?","What local tradition should not disappear because of growth?")],[p("la empresa tecnológica","tech company"),p("el alquiler","rent"),p("compensar","to make up for"),p("la tradición","tradition"),p("la personalidad","personality"),p("la presión","pressure")]),
      place("San Antonio","TEXAS","CAPAS DE HISTORIA",p("La ciudad combina misiones españolas, cultura mexicana y tejana, bases militares y un centro turístico junto al río.","The city combines Spanish missions, Mexican and Tejano culture, military bases and a tourist centre beside the river."),[p("¿Quién cuenta la historia cuando un mismo lugar significa cosas diferentes?","Who tells the story when the same place means different things?"),p("¿Una zona turística puede seguir siendo un espacio para residentes?","Can a tourist area remain a space for residents?"),p("¿Qué mezcla cultural se nota en la comida de tu región?","What cultural mix can be seen in your region's food?")],[p("la misión","mission"),p("tejano/a","Tejano"),p("la capa","layer"),p("el residente","resident"),p("la mezcla","mix"),p("significar","to mean")])
    ]},
  {code:"PL",number:"08",name:"Grandes Llanuras",nameEn:"Great Plains",color:"#d6a72f",zone:"centro",
    hook:p("Distancias, agricultura, tormentas y naciones tribales","Distances, farming, storms and Tribal Nations"),
    fact:p("Las llanuras parecen abiertas y vacías desde lejos, pero contienen ciudades, agricultura intensiva, territorios indígenas y comunidades muy conectadas al clima.","The plains may look open and empty from far away, but they contain cities, intensive agriculture, Indigenous lands and communities closely tied to the weather."),
    mission:p("Descubrí quién vive en los espacios que muchas personas llaman equivocadamente vacíos.","Discover who lives in spaces that many people incorrectly call empty."),
    places:[
      place("Kansas City","MISSOURI · KANSAS","FRONTERA URBANA + COMIDA",p("La región urbana cruza una frontera estatal y construyó una fuerte identidad alrededor del jazz, los deportes y el barbecue.","The urban region crosses a state border and built a strong identity around jazz, sports and barbecue."),[p("¿Una ciudad puede tener una identidad fuerte gracias a una comida?","Can a city have a strong identity because of one food?"),p("¿Qué problemas aparecen cuando una ciudad pertenece a dos estados?","What problems appear when a city belongs to two states?"),p("¿Qué competencia amistosa existe entre ciudades cercanas a vos?","What friendly rivalry exists between cities near you?")],[p("la frontera estatal","state border"),p("el barbecue","barbecue"),p("la rivalidad","rivalry"),p("pertenecer","to belong"),p("la identidad","identity"),p("cruzar","to cross")]),
      place("Sandhills de Nebraska","NEBRASKA","PAISAJE + POBLACIÓN",p("Dunas cubiertas de pasto sostienen ganadería y pequeños pueblos en una zona de muy baja densidad.","Grass-covered dunes support ranching and small towns in a very low-density area."),[p("¿Qué necesita un joven para elegir quedarse en un pueblo pequeño?","What does a young person need to choose to stay in a small town?"),p("¿Es un problema que una región tenga muy pocos habitantes?","Is it a problem for a region to have very few inhabitants?"),p("¿Qué servicio puede funcionar de forma móvil en lugares muy distantes?","What service can work in a mobile way in very distant places?")],[p("la duna","dune"),p("la ganadería","ranching"),p("la densidad","density"),p("quedarse","to stay"),p("distante","distant"),p("móvil","mobile")]),
      place("Badlands y Black Hills","SOUTH DAKOTA","PAISAJE + SOBERANÍA",p("Los paisajes atraen turismo, pero la región también tiene una profunda importancia cultural e histórica para pueblos lakota.","The landscapes attract tourism, but the region also has deep cultural and historical importance for Lakota peoples."),[p("¿Cómo puede un visitante respetar un lugar que también es sagrado?","How can a visitor respect a place that is also sacred?"),p("¿Quién debería decidir los nombres oficiales de montañas y lugares?","Who should decide the official names of mountains and places?"),p("¿Un paisaje puede pertenecer legalmente a alguien y culturalmente a otra comunidad?","Can a landscape legally belong to someone and culturally to another community?")],[p("sagrado","sacred"),p("la soberanía","sovereignty"),p("el paisaje","landscape"),p("pertenecer","to belong"),p("nombrar","to name"),p("respetar","to respect")]),
      place("Oklahoma y Tulsa","OKLAHOMA","NACIONES + CAPAS URBANAS",p("Oklahoma contiene muchas naciones tribales soberanas; Tulsa también confronta la historia de Greenwood y su destrucción en 1921.","Oklahoma contains many sovereign Tribal Nations; Tulsa also confronts the history of Greenwood and its destruction in 1921."),[p("¿Qué significa que una nación exista dentro de otro país?","What does it mean for a nation to exist within another country?"),p("¿Cómo puede una ciudad reparar una injusticia ocurrida hace generaciones?","How can a city repair an injustice that happened generations ago?"),p("¿Qué historia local importante no aprendiste en la escuela?","What important local history did you not learn at school?")],[p("la nación tribal","Tribal Nation"),p("soberano/a","sovereign"),p("reparar","to repair"),p("la injusticia","injustice"),p("la generación","generation"),p("confrontar","to confront")])
    ]},
  {code:"SW",number:"09",name:"Suroeste",nameEn:"Southwest",color:"#ef7d32",zone:"oeste",
    hook:p("Desierto, agua, pueblos indígenas y ciudades de calor","Desert, water, Indigenous peoples and cities of heat"),
    fact:p("El Suroeste obliga a pensar en agua, calor y territorio. Sus paisajes famosos también son hogares y espacios culturales vivos.","The Southwest forces people to think about water, heat and land. Its famous landscapes are also homes and living cultural spaces."),
    mission:p("Proponé formas de vivir y visitar el desierto sin tratarlo como un espacio vacío.","Suggest ways to live in and visit the desert without treating it as an empty space."),
    places:[
      place("Phoenix","ARIZONA","CALOR + CIUDAD",p("Una gran metrópolis crece en el desierto con aire acondicionado, autopistas y una demanda enorme de agua.","A major metropolis grows in the desert with air conditioning, highways and enormous demand for water."),[p("¿Cómo debería cambiar una ciudad cuando hace demasiado calor para caminar?","How should a city change when it is too hot to walk?"),p("¿Es responsable seguir construyendo casas con piscinas en el desierto?","Is it responsible to keep building homes with pools in the desert?"),p("¿Qué espacio público necesitás durante una ola de calor?","What public space do you need during a heatwave?")],[p("la ola de calor","heatwave"),p("la sombra","shade"),p("la demanda","demand"),p("el desierto","desert"),p("responsable","responsible"),p("enfriar","to cool")]),
      place("Santa Fe","NEW MEXICO","ARQUITECTURA + IDENTIDAD",p("La ciudad protege una imagen arquitectónica de adobe mientras mezcla historias indígenas, hispanas y angloamericanas.","The city protects an adobe architectural image while combining Indigenous, Hispanic and Anglo-American histories."),[p("¿Una ciudad debe controlar el estilo de los edificios nuevos?","Should a city control the style of new buildings?"),p("¿Qué diferencia hay entre conservar una cultura y vender su imagen?","What is the difference between preserving a culture and selling its image?"),p("¿Qué material representa mejor la arquitectura de tu región?","What material best represents your region's architecture?")],[p("el adobe","adobe"),p("el estilo","style"),p("conservar","to preserve"),p("la imagen","image"),p("mezclar","to combine"),p("el edificio","building")]),
      place("Gran Cañón","ARIZONA","MARAVILLA + ACCESO",p("Millones de personas ven el cañón desde pocos miradores, mientras el río, los senderos y la historia humana revelan un territorio mucho más complejo.","Millions of people see the canyon from a few viewpoints, while the river, trails and human history reveal a much more complex territory."),[p("¿Ver un paisaje cinco minutos es realmente conocerlo?","Is seeing a landscape for five minutes really knowing it?"),p("¿Cómo se reparte el acceso cuando demasiadas personas quieren visitar el mismo lugar?","How should access be shared when too many people want to visit the same place?"),p("¿Qué maravilla natural te decepcionaría si estuviera llena de gente?","What natural wonder would disappoint you if it were full of people?")],[p("el mirador","viewpoint"),p("el sendero","trail"),p("repartir","to distribute"),p("la maravilla","wonder"),p("complejo","complex"),p("conocer","to know / experience")]),
      place("Nación Navajo","ARIZONA · NEW MEXICO · UTAH","SOBERANÍA + LENGUA",p("La Nación Navajo —Diné Bikéyah— tiene gobierno propio y un territorio que cruza tres estados; la lengua y la comunidad siguen siendo centrales.","The Navajo Nation —Diné Bikéyah— has its own government and a territory that crosses three states; language and community remain central."),[p("¿Qué poder necesita un gobierno local para proteger su comunidad?","What power does a local government need to protect its community?"),p("¿Cómo puede una lengua minoritaria seguir viva entre los jóvenes?","How can a minority language stay alive among young people?"),p("¿Qué debe aprender un turista antes de entrar en territorio indígena?","What should a tourist learn before entering Indigenous land?")],[p("el territorio","territory"),p("el gobierno propio","self-government"),p("la lengua","language"),p("seguir vivo","to stay alive"),p("indígena","Indigenous"),p("la comunidad","community")])
    ]},
  {code:"MW",number:"10",name:"Montañas Rocosas",nameEn:"Mountain West",color:"#5e9b77",zone:"oeste",
    hook:p("Altura, parques, crecimiento y tierras públicas","Altitude, parks, growth and public lands"),
    fact:p("Las ciudades crecen junto a grandes áreas naturales y tierras públicas, creando conflictos sobre vivienda, animales, agua y acceso.","Cities grow beside large natural areas and public lands, creating conflicts over housing, wildlife, water and access."),
    mission:p("Equilibrá libertad, conservación y crecimiento en territorios enormes.","Balance freedom, conservation and growth across enormous territories."),
    places:[
      place("Denver","COLORADO","CRECIMIENTO + MONTAÑA",p("La ciudad atrae empleos y personas que buscan vida al aire libre, pero la expansión aumenta el tránsito y el costo de vivienda.","The city attracts jobs and people seeking an outdoor life, but expansion increases traffic and housing costs."),[p("¿Una ciudad puede vender naturaleza sin dañar el paisaje que vende?","Can a city sell nature without damaging the landscape it sells?"),p("¿Qué es más urgente en una ciudad que crece: casas o transporte?","What is more urgent in a growing city: housing or transport?"),p("¿Vivir cerca de montañas cambia la rutina de una persona?","Does living near mountains change a person's routine?")],[p("la expansión","expansion"),p("al aire libre","outdoors"),p("la vivienda","housing"),p("el tránsito","traffic"),p("urgente","urgent"),p("el paisaje","landscape")]),
      place("Yellowstone","WYOMING · MONTANA · IDAHO","FAUNA + MULTITUDES",p("El parque protege ecosistemas y animales salvajes mientras recibe visitantes que a veces se acercan demasiado.","The park protects ecosystems and wild animals while receiving visitors who sometimes get too close."),[p("¿Por qué algunas personas ignoran reglas claras frente a animales salvajes?","Why do some people ignore clear rules around wild animals?"),p("¿Un parque debe cerrar zonas para dar más espacio a la fauna?","Should a park close areas to give wildlife more space?"),p("¿Qué experiencia natural vale la pena vivir sin sacar fotos?","What natural experience is worth having without taking photos?")],[p("la fauna","wildlife"),p("salvaje","wild"),p("acercarse","to approach"),p("cerrar","to close"),p("la regla","rule"),p("el ecosistema","ecosystem")]),
      place("Salt Lake City","UTAH","CIUDAD + ENTORNO",p("Una ciudad en crecimiento está rodeada de montañas, desierto y un gran lago cuyo nivel afecta ambiente, salud y economía.","A growing city is surrounded by mountains, desert and a great lake whose level affects the environment, health and economy."),[p("¿La ciudad debe limitar su crecimiento si el agua no alcanza?","Should the city limit its growth if there is not enough water?"),p("¿Qué problema ambiental cercano casi no se ve en la vida diaria?","What nearby environmental problem is barely visible in daily life?"),p("¿Preferís una ciudad compacta o una casa grande lejos del centro?","Do you prefer a compact city or a large house far from the centre?")],[p("el nivel del lago","lake level"),p("alcanzar","to be enough"),p("compacto","compact"),p("rodeado","surrounded"),p("la salud","health"),p("limitar","to limit")]),
      place("Pueblos de Montana","MONTANA","TIERRA + DISTANCIA",p("Pueblos pequeños conviven con ranchos, turismo, inviernos largos y grandes extensiones de tierra pública.","Small towns coexist with ranches, tourism, long winters and large areas of public land."),[p("¿Quién debería decidir el uso de una tierra que pertenece al público?","Who should decide how publicly owned land is used?"),p("¿Qué servicio es difícil mantener cuando las personas viven muy lejos?","What service is difficult to maintain when people live far apart?"),p("¿La tranquilidad compensa tener menos oportunidades de trabajo?","Does tranquillity make up for having fewer job opportunities?")],[p("la tierra pública","public land"),p("el rancho","ranch"),p("la extensión","expanse"),p("mantener","to maintain"),p("la oportunidad","opportunity"),p("compensar","to make up for")])
    ]},
  {code:"CA",number:"11",name:"California",nameEn:"California",color:"#ffbe3f",zone:"oeste",
    hook:p("Imagen global, agricultura, tecnología y vivienda","Global image, farming, technology and housing"),
    fact:p("California conecta industrias culturales y tecnológicas con agricultura intensiva, parques famosos y una crisis profunda de vivienda.","California connects cultural and technology industries with intensive agriculture, famous parks and a deep housing crisis."),
    mission:p("Mirá detrás de la imagen perfecta y discutí quién puede participar del éxito.","Look behind the perfect image and discuss who can take part in success."),
    places:[
      place("Los Ángeles","CALIFORNIA","SUEÑO + DISTANCIA",p("La ciudad produce imágenes globales, pero su enorme extensión hace que el auto, el tiempo y la ubicación definan muchas oportunidades.","The city produces global images, but its enormous size means the car, time and location define many opportunities."),[p("¿Cuánto tiempo diario aceptarías perder para vivir en una casa mejor?","How much time each day would you accept losing to live in a better home?"),p("¿El cine muestra una ciudad real o crea una ciudad imaginaria?","Does cinema show a real city or create an imaginary one?"),p("¿Qué cambiaría si Los Ángeles tuviera transporte público excelente?","What would change if Los Angeles had excellent public transport?")],[p("la distancia","distance"),p("el tránsito","traffic"),p("la oportunidad","opportunity"),p("la imagen","image"),p("la industria cultural","cultural industry"),p("perder tiempo","to lose time")]),
      place("Silicon Valley","CALIFORNIA","INNOVACIÓN + COSTO",p("Empresas que cambian el mundo comparten región con precios de vivienda que excluyen a muchos trabajadores esenciales.","Companies that change the world share a region with housing prices that exclude many essential workers."),[p("¿Una empresa exitosa tiene responsabilidad por los problemas que crea cerca?","Does a successful company have responsibility for the problems it creates nearby?"),p("¿Qué innovación cotidiana no necesitábamos realmente?","What everyday innovation did we not really need?"),p("¿Quién merece vivir cerca de su trabajo en una zona muy cara?","Who deserves to live near their job in a very expensive area?")],[p("la innovación","innovation"),p("excluir","to exclude"),p("el trabajador esencial","essential worker"),p("la responsabilidad","responsibility"),p("el éxito","success"),p("merecer","to deserve")]),
      place("Valle Central","CALIFORNIA","ALIMENTOS + TRABAJO",p("Una región agrícola produce alimentos para millones, con trabajo exigente, grandes sistemas de riego y comunidades migrantes.","An agricultural region produces food for millions, with demanding work, large irrigation systems and migrant communities."),[p("¿Por qué conocemos tan poco a las personas que producen nuestra comida?","Why do we know so little about the people who produce our food?"),p("¿Los alimentos deberían costar más si eso mejora las condiciones de trabajo?","Should food cost more if that improves working conditions?"),p("¿Qué cultivo depende demasiado del agua en tu país?","Which crop depends too heavily on water in your country?")],[p("el cultivo","crop"),p("el riego","irrigation"),p("la cosecha","harvest"),p("exigente","demanding"),p("las condiciones","conditions"),p("producir","to produce")]),
      place("Yosemite","CALIFORNIA","BELLEZA + RESERVAS",p("El valle concentra vistas famosas y multitudes; gestionar el acceso busca proteger tanto el paisaje como la experiencia.","The valley concentrates famous views and crowds; managing access aims to protect both the landscape and the experience."),[p("¿Preferís reservar con meses de anticipación o arriesgarte a no entrar?","Do you prefer booking months in advance or risking not getting in?"),p("¿Un lugar natural sigue siendo libre si necesita reservas?","Is a natural place still free if it requires reservations?"),p("¿Qué harías para que visitantes nuevos entiendan las reglas del parque?","What would you do so new visitors understand park rules?")],[p("con anticipación","in advance"),p("arriesgarse","to risk"),p("gestionar","to manage"),p("la multitud","crowd"),p("la experiencia","experience"),p("la reserva","reservation")])
    ]},
  {code:"PA",number:"12",name:"Pacífico, Alaska y Hawai",nameEn:"Pacific, Alaska & Hawaiʻi",color:"#4c7fd8",zone:"no-contiguo",
    hook:p("Tecnología, océano, distancia y culturas insulares","Technology, ocean, distance and island cultures"),
    fact:p("Esta ruta une el Noroeste continental con Alaska y Hawai: territorios muy distintos conectados por océano, migración, clima y grandes distancias.","This route connects the continental Northwest with Alaska and Hawaiʻi: very different territories connected by ocean, migration, climate and great distances."),
    mission:p("Compará cómo la distancia cambia precios, identidad, movilidad y relación con la naturaleza.","Compare how distance changes prices, identity, mobility and relationships with nature."),
    places:[
      place("Seattle","WASHINGTON","TECNOLOGÍA + CIUDAD",p("Grandes empresas, un puerto internacional y paisajes naturales conviven con altos precios de vivienda y cambios rápidos de barrio.","Major companies, an international port and natural landscapes coexist with high housing prices and rapid neighbourhood change."),[p("¿Las grandes empresas deben financiar más vivienda y transporte local?","Should large companies fund more local housing and transport?"),p("¿Qué gana una ciudad cuando atrae trabajadores de todo el mundo?","What does a city gain when it attracts workers from around the world?"),p("¿La naturaleza cercana mejora la vida si casi no tenés tiempo para disfrutarla?","Does nearby nature improve life if you barely have time to enjoy it?")],[p("el puerto","port"),p("financiar","to fund"),p("atraer","to attract"),p("la vivienda","housing"),p("cercano","nearby"),p("disfrutar","to enjoy")]),
      place("Portland","OREGON","DISEÑO URBANO + CAMBIO",p("La ciudad es conocida por bicicletas, barrios caminables y cultura independiente, pero también debate seguridad, vivienda y crecimiento.","The city is known for bicycles, walkable neighbourhoods and independent culture, but it also debates safety, housing and growth."),[p("¿Qué hace que una ciudad sea realmente cómoda para andar en bicicleta?","What makes a city truly comfortable for cycling?"),p("¿Cómo cambia un barrio cuando su imagen se vuelve una marca?","How does a neighbourhood change when its image becomes a brand?"),p("¿Qué problema urbano no se resuelve solamente con buen diseño?","What urban problem cannot be solved only through good design?")],[p("caminable","walkable"),p("la bicicleta","bicycle"),p("la marca","brand"),p("el diseño urbano","urban design"),p("la seguridad","safety"),p("resolver","to solve")]),
      place("Alaska remota","ALASKA","DISTANCIA + COSTO",p("Muchas comunidades no están conectadas por carretera y dependen de aviones, barcos y cadenas de suministro largas.","Many communities are not connected by road and depend on planes, boats and long supply chains."),[p("¿Qué producto básico debería recibir ayuda pública en un lugar remoto?","Which basic product should receive public support in a remote place?"),p("¿Aceptarías precios muy altos a cambio de vivir cerca de naturaleza enorme?","Would you accept very high prices in exchange for living near vast nature?"),p("¿Cómo cambia una emergencia cuando el hospital está a horas de distancia?","How does an emergency change when the hospital is hours away?")],[p("remoto","remote"),p("el suministro","supply"),p("la carretera","road"),p("la emergencia","emergency"),p("depender de","to depend on"),p("la ayuda pública","public support")]),
      place("Hawaiʻi","HAWAIʻI","TURISMO + CULTURA LOCAL",p("Las islas reciben visitantes de todo el mundo mientras comunidades locales protegen lengua, tierra, agua e identidad hawaiana.","The islands receive visitors from around the world while local communities protect Hawaiian language, land, water and identity."),[p("¿Cuándo el turismo deja de ayudar y empieza a ocupar demasiado espacio?","When does tourism stop helping and start taking up too much space?"),p("¿Qué debe hacer un visitante para respetar una cultura insular viva?","What should a visitor do to respect a living island culture?"),p("¿Las personas locales deberían tener prioridad para comprar vivienda?","Should local people have priority when buying housing?")],[p("la isla","island"),p("la lengua hawaiana","Hawaiian language"),p("la prioridad","priority"),p("la tierra","land"),p("ocupar","to take up"),p("respetar","to respect")])
    ]}
];

export const regionZones={este:p("ESTE","EAST"),centro:p("CENTRO","CENTRAL"),oeste:p("OESTE","WEST"),"no-contiguo":p("ALASKA + HAWÁI","ALASKA + HAWAIʻI")};
export const stances=[p("Para mí, la prioridad es…","For me, the priority is…"),p("Una ventaja clara es…","One clear advantage is…"),p("El problema principal es…","The main problem is…")];
export const connectors=[p("porque…","because…"),p("sin embargo…","however…"),p("por eso…","that is why…"),p("por ejemplo…","for example…"),p("en cambio…","whereas…"),p("depende de…","it depends on…")];
export const depthMoves=[p("Dá un ejemplo personal.","Give a personal example."),p("Comparalo con tu país.","Compare it with your country."),p("Buscá una desventaja.","Find a disadvantage."),p("Proponé una solución simple.","Suggest a simple solution."),p("Hacé una pregunta al otro.","Ask the other person a question."),p("Cambiá de postura por un minuto.","Change sides for one minute.")];
