import type { Module } from "../../types";

export const a1w01: Module = {
  id: "a1-01",
  level: "a1",
  week: 1,
  kind: "core",
  title: "¡Hola! Me llamo…",
  subtitle: "Saludar, presentarte y preguntar el nombre, de tú o de usted.",
  stop: { place: "Ciudad de México", country: "México" },
  minutes: 60,
  newObjectives: [
    "a1.gram.pronombres-sujeto",
    "a1.gram.ser-singular",
    "a1.voc.saludos",
    "a1.pron.cinco-vocales",
    "a1.fun.presentarse",
    "a1.lis.saludos-nombres",
    "a1.spk.presentacion-20s",
  ],
  reviewObjectives: [],
  prerequisites: [],
  goal: {
    canDo: "Al final de esta semana puedes saludar, presentarte y preguntar el nombre a otra persona, de tú o de usted.",
    canDoEn: "By the end of this week, you can greet people, introduce yourself and ask someone's name, informally or formally.",
    steps: [
      "Descubre cómo se saluda según la hora y la situación.",
      "Aprende **yo, tú, usted, él, ella** y las formas `soy`, `eres`, `es`.",
      "Entrena las cinco vocales del español.",
      "Escucha tres encuentros en Ciudad de México.",
      "Graba tu presentación de 20 segundos para usarla en clase.",
    ],
  },
  theory: {
    intro: "En español, el saludo cambia con la hora del día y con la relación entre las personas. Esta semana aprendes las fórmulas básicas y la diferencia entre **tú** y **usted**.",
    parts: [
      {
        heading: "Saludar según la hora",
        body: [
          "Para saludar a cualquier persona, en cualquier momento, puedes decir **Hola**. Si quieres ser más completo o más formal, usa el saludo de la hora: **Buenos días** por la mañana, **Buenas tardes** desde la hora de comer hasta que oscurece y **Buenas noches** por la noche.",
          "Es muy normal combinar: **Hola, buenos días**. Después del saludo, se pregunta por la persona: **¿Qué tal?** o **¿Cómo estás?**",
          "Para despedirte: **Adiós**, **Hasta luego** (te vas, pero vas a volver), **Hasta mañana** y, entre amigos, **Chao** (en Argentina y Uruguay se escribe **chau**).",
        ],
        support: [
          "_Buenos días_ = good morning; _buenas tardes_ = good afternoon (from lunchtime until it gets dark); _buenas noches_ = good evening AND good night. Spanish uses the same phrase to say hello and goodbye at night.",
          "_Día_ is masculine (buen**os** días) but _tarde_ and _noche_ are feminine (buen**as** tardes, buen**as** noches).",
        ],
        examples: [
          { es: "Hola, buenos días.", en: "Hi, good morning." },
          { es: "Buenas tardes, ¿qué tal?", en: "Good afternoon, how are you?" },
          { es: "Buenas noches. Hasta mañana.", en: "Good night. See you tomorrow." },
          { es: "Hasta luego, Marta.", en: "See you later, Marta." },
        ],
        mistakes: [
          { wrong: "Buenos tardes.", right: "Buenas tardes.", why: "_Tarde_ es femenino: buen**as** tardes." },
          { wrong: "Buenas días.", right: "Buenos días.", why: "_Día_ es masculino aunque termina en -a." },
        ],
        tip: "En Argentina y Uruguay también se oye **Buen día** por la mañana.",
      },
      {
        heading: "¿Quién? Yo, tú, usted, él, ella",
        body: [
          "Los pronombres sujeto dicen quién hace la acción: **yo** (la persona que habla), **tú** (la persona con quien hablas, en confianza), **usted** (la persona con quien hablas, con respeto o distancia), **él** y **ella** (otra persona).",
          "En español el verbo ya dice la persona. Por eso, normalmente no decimos el pronombre: **Soy Ana** es más natural que _Yo soy Ana_. Usamos el pronombre para contrastar o insistir: **Yo soy Ana y ella es Lucía.**",
          "**Tú o usted.** Con amigos, familia, niños y gente joven, usa **tú**. Con una persona mayor que no conoces, en una oficina o con un cliente, usa **usted**. Atención: _usted_ habla con la persona de enfrente, pero el verbo va como con _él_ o _ella_: **usted es**.",
          "En Argentina, Uruguay, Paraguay y gran parte de Centroamérica se usa **vos** en lugar de _tú_: **vos sos**. Esta semana solo necesitas reconocerlo.",
        ],
        support: [
          "Spanish verbs show who is acting, so subject pronouns are usually dropped: _Soy Ana_ (I'm Ana). Use _yo, tú, él_… only for contrast or emphasis.",
          "_Tú_ is informal 'you'; _usted_ is polite 'you'. _Usted_ takes the same verb form as _él/ella_ (he/she).",
        ],
        table: {
          caption: "Las personas de esta semana",
          head: ["Persona", "Pronombre", "Ser", "Llamarse"],
          rows: [
            ["la persona que habla", "yo", "soy", "me llamo"],
            ["con quien hablas (confianza)", "tú", "eres", "te llamas"],
            ["con quien hablas (respeto)", "usted", "es", "se llama"],
            ["otra persona", "él / ella", "es", "se llama"],
            ["variación (Río de la Plata, Centroamérica)", "vos", "sos", "te llamás"],
          ],
        },
        examples: [
          { es: "Soy Tomás. ¿Y tú?", en: "I'm Tomás. And you?" },
          { es: "Yo soy Valeria y ella es Sofía.", en: "I'm Valeria and she's Sofía." },
          { es: "¿Usted es la señora Ortiz?", en: "Are you Mrs Ortiz? (formal)" },
        ],
        mistakes: [
          { wrong: "Usted eres el profesor.", right: "Usted es el profesor.", why: "Con _usted_ el verbo va como con él o ella: **es**." },
        ],
      },
      {
        heading: "Me llamo… / Soy…",
        body: [
          "Hay tres maneras frecuentes de decir tu nombre: **Me llamo Marta**, **Soy Marta** y, un poco más formal, **Mi nombre es Marta**.",
          "_Llamarse_ siempre lleva un pequeño pronombre delante: **me** llamo, **te** llamas, **se** llama. Para preguntar: **¿Cómo te llamas?** (tú) y **¿Cómo se llama?** o **¿Cómo se llama usted?** (usted).",
          "Cuando alguien se presenta, responde **Mucho gusto** o **Encantado** (si eres hombre) / **Encantada** (si eres mujer). La otra persona puede contestar **Igualmente**.",
        ],
        support: [
          "_Me llamo_ literally means 'I call myself'. Never drop _me_: say _me llamo_, not _yo llamo_.",
          "_Encantado / encantada_ agrees with the person who speaks, not with the person you meet.",
        ],
        examples: [
          { es: "—¿Cómo te llamas? —Me llamo Diego.", en: "What's your name? — My name is Diego." },
          { es: "—Mucho gusto. —Igualmente.", en: "Nice to meet you. — Likewise." },
          { es: "Encantada, soy Laura.", en: "Nice to meet you, I'm Laura. (a woman speaking)" },
        ],
        mistakes: [
          { wrong: "Yo llamo Javier.", right: "Me llamo Javier.", why: "_Llamarse_ necesita **me**: me llamo." },
          { wrong: "¿Cómo tú te llamas?", right: "¿Cómo te llamas?", why: "Después de _cómo_ va directamente el verbo; el pronombre sobra." },
        ],
      },
    ],
  },
  grammar: {
    intro: "Practica las formas de **ser** y **llamarse** con tú, usted, él y ella.",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "Soy, eres, es",
        prompt: "Elige la forma correcta.",
        items: [
          { q: "Hola, ___ Carlos.", options: ["soy", "eres", "es"], answer: 0, why: "Hablas de ti: **yo soy**." },
          { q: "¿Tú ___ Ana?", options: ["soy", "eres", "es"], answer: 1, why: "Con **tú**: eres." },
          { q: "Ella ___ Sofía, mi compañera.", options: ["soy", "eres", "es"], answer: 2, why: "Con **ella**: es." },
          { q: "Buenos días. ¿Usted ___ el profesor García?", options: ["soy", "eres", "es"], answer: 2, why: "**Usted** usa la forma de él/ella: es." },
        ],
      },
      {
        id: "g2",
        type: "choice",
        title: "Me, te, se",
        prompt: "¿Qué pronombre necesita _llamarse_?",
        items: [
          { q: "¿Cómo ___ llamas?", options: ["me", "te", "se"], answer: 1, why: "Pregunta con tú: **te** llamas." },
          { q: "Perdón, ¿cómo ___ llama usted?", options: ["me", "te", "se"], answer: 2, why: "Con usted: **se** llama." },
          { q: "Hola, ___ llamo Inés.", options: ["me", "te", "se"], answer: 0, why: "Hablas de ti: **me** llamo." },
          { q: "Él ___ llama Mateo.", options: ["me", "te", "se"], answer: 2, why: "Con él: **se** llama." },
        ],
      },
      {
        id: "g3",
        type: "gap",
        title: "Pequeñas conversaciones",
        prompt: "Completa con una forma de **ser** o **llamarse**.",
        items: [
          { q: "—Hola, ¿cómo te ___? —Me ___ Lucía. ¿Y tú?", answers: [["llamas"], ["llamo"]], why: "Tú → te llam**as**; yo → me llam**o**." },
          { q: "—___ Diego. Mucho gusto. —Igualmente.", answers: [["Soy", "Me llamo"]], why: "Dos formas correctas: **Soy** Diego / **Me llamo** Diego." },
          { q: "—Buenos días. ¿Usted ___ la señora Ruiz? —Sí, ___ yo.", answers: [["es"], ["soy"]], why: "Usted **es**; yo **soy**." },
          { q: "Él ___ Mateo y ella ___ Carla.", answers: [["es"], ["es"]], why: "Él y ella comparten la forma **es**." },
        ],
      },
      {
        id: "g4",
        type: "classify",
        title: "¿Tú o usted?",
        prompt: "¿Cómo hablas con estas personas? Clasifícalas.",
        categories: ["tú (confianza)", "usted (respeto)"],
        items: [
          { text: "Un compañero de clase de 20 años", cat: 0 },
          { text: "Tu nueva jefa en la primera reunión", cat: 1, why: "Relación profesional nueva: usted, hasta que ella te proponga el tú." },
          { text: "Un niño en el parque", cat: 0 },
          { text: "Una señora mayor en el banco", cat: 1 },
          { text: "Tu amiga Paula", cat: 0 },
          { text: "El médico, la primera vez que lo ves", cat: 1 },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Aprende estas fórmulas como bloques completos: así salen solas en una conversación.",
    groups: [
      {
        title: "Saludar",
        items: [
          { es: "Hola.", en: "Hi / Hello." },
          { es: "Buenos días.", en: "Good morning." },
          { es: "Buenas tardes.", en: "Good afternoon." },
          { es: "Buenas noches.", en: "Good evening / Good night." },
          { es: "¿Qué tal?", en: "How's it going?" },
          { es: "¿Cómo estás?", en: "How are you? (tú)" },
          { es: "¿Cómo está usted?", en: "How are you? (usted)" },
          { es: "Bien, gracias. ¿Y tú?", en: "Fine, thanks. And you?" },
        ],
      },
      {
        title: "Presentarse",
        items: [
          { es: "Me llamo…", en: "My name is…" },
          { es: "Soy…", en: "I'm…" },
          { es: "¿Cómo te llamas?", en: "What's your name? (tú)" },
          { es: "¿Cómo se llama usted?", en: "What's your name? (usted)" },
          { es: "Mucho gusto.", en: "Nice to meet you." },
          { es: "Encantado. / Encantada.", en: "Pleased to meet you. (man / woman speaking)" },
          { es: "Igualmente.", en: "Likewise." },
        ],
      },
      {
        title: "Despedirse",
        items: [
          { es: "Adiós.", en: "Goodbye." },
          { es: "Hasta luego.", en: "See you later." },
          { es: "Hasta mañana.", en: "See you tomorrow." },
          { es: "Nos vemos.", en: "See you." },
          { es: "Chao.", en: "Bye. (informal; _chau_ in Argentina and Uruguay)" },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "La fórmula justa",
        prompt: "Une cada situación con lo que dices.",
        pairs: [
          { left: "8:00, entras en la panadería", right: "Buenos días." },
          { left: "16:00, llegas a la oficina", right: "Buenas tardes." },
          { left: "22:00, llegas a una cena", right: "Buenas noches." },
          { left: "Te presentan a una persona", right: "Mucho gusto." },
          { left: "Te vas y vuelves mañana", right: "Hasta mañana." },
        ],
        why: "La hora decide el saludo; _mucho gusto_ es para conocer a alguien y _hasta mañana_ para despedirse.",
      },
      {
        id: "v2",
        type: "context",
        title: "¿Qué respondes?",
        prompt: "Elige la respuesta natural.",
        items: [
          { context: "Una persona nueva te dice: «Mucho gusto».", q: "Tú respondes:", options: ["Igualmente.", "De nada.", "Buenas noches."], answer: 0, why: "_Igualmente_ devuelve el «mucho gusto». _De nada_ responde a _gracias_." },
          { context: "Tu vecino te pregunta: «¿Qué tal?»", q: "Tú respondes:", options: ["Bien, gracias. ¿Y tú?", "Me llamo Ana.", "Adiós."], answer: 0, why: "_¿Qué tal?_ pregunta cómo estás." },
          { context: "Eres una mujer y te presentan a Pablo.", q: "Tú dices:", options: ["Encantada.", "Encantado.", "Igualmente."], answer: 0, why: "Hablas tú, que eres mujer: encantad**a**." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "Cinco vocales, cinco sonidos",
    explanation: [
      "El español tiene solo **cinco sonidos vocálicos**: a, e, i, o, u. Son cortos, claros y estables: suenan igual al principio, en el medio y al final de la palabra, con acento o sin acento.",
      "La gran diferencia con el inglés es que en español **las vocales no se reducen**. En _chocolate_ se oyen las cuatro vocales completas: cho-co-la-te. No hay una vocal débil tipo «uh».",
      "Tampoco se alargan ni se deslizan: la **o** de _hola_ no termina en «u» y la **e** de _mesa_ no termina en «i».",
    ],
    support: [
      "a ≈ the 'a' in _father_, but short · e ≈ the 'e' in _met_ · i ≈ the 'ee' in _see_, short · o ≈ the 'o' in _or_, without a glide · u ≈ the 'oo' in _food_, short.",
      "Keep every vowel full, even in unstressed syllables: _ca-sa_, not 'cass-uh'.",
    ],
    table: {
      head: ["Vocal", "Palabras", "Frase"],
      rows: [
        ["a", "casa, mamá, Ana", "Hola, Ana."],
        ["e", "mesa, leche, Elena", "Me llamo Elena."],
        ["i", "sí, libro, Inés", "Sí, soy Inés."],
        ["o", "hola, ocho, Olga", "Hola, Olga."],
        ["u", "uno, tú, Úrsula", "¿Y tú, Úrsula?"],
      ],
    },
    perceive: {
      id: "p1",
      type: "listen",
      title: "¿Qué palabra oyes?",
      prompt: "Escucha y elige. Solo cambia una vocal.",
      items: [
        { q: "¿Qué palabra oyes?", audio: "peso", options: ["paso", "peso", "piso", "puso"], answer: 1 },
        { q: "¿Qué palabra oyes?", audio: "misa", options: ["masa", "mesa", "misa", "musa"], answer: 2 },
        { q: "¿Qué palabra oyes?", audio: "toco", options: ["taco", "toco", "tico"], answer: 1 },
        { q: "¿Qué palabra oyes?", audio: "luna", options: ["lana", "luna", "lona"], answer: 1 },
        { q: "¿Qué palabra oyes?", audio: "dedo", options: ["dado", "dedo", "dudo"], answer: 1 },
        { q: "¿Qué palabra oyes?", audio: "mora", options: ["mira", "mora", "mera"], answer: 1 },
      ],
    },
    produce: [
      { text: "Ana, Elena, Inés, Olga, Úrsula.", tip: "Cinco nombres, cinco vocales. Cada vocal, corta y clara." },
      { text: "Hola, me llamo Ana.", tip: "La **o** de _hola_ no termina en «u»: ho-la." },
      { text: "Mucho gusto, Elena.", tip: "Mu-cho gus-to: la **u** es corta, como en _tú_." },
      { text: "Encantada, soy Inés.", tip: "En-can-ta-da: las tres **a** suenan igual, sin reducirse." },
      { text: "¿Y tú, cómo te llamas?", tip: "Cuatro vocales distintas en una pregunta muy útil." },
    ],
    spelling: "Cada vocal se escribe siempre con la misma letra. La **h** no suena: _hola_ empieza con el sonido **o**.",
  },
  listening: {
    title: "Tres encuentros en Ciudad de México",
    context: "Valeria y Tomás estudian en una escuela de idiomas de la colonia Roma. Escucha tres momentos del mismo día: en el café por la mañana, en la oficina por la tarde y en la puerta de la escuela por la noche.",
    speakers: [
      { id: "valeria", name: "Valeria", voice: "es-MX-f", role: "estudiante" },
      { id: "tomas", name: "Tomás", voice: "es-MX-m", role: "estudiante" },
      { id: "ortiz", name: "Laura Ortiz", voice: "es-CO-f", role: "directora" },
      { id: "martin", name: "Martín", voice: "es-AR-m", role: "viajero" },
    ],
    script: [
      { speaker: "valeria", text: "¡Hola! Buenos días. ¿Cómo te llamas?" },
      { speaker: "tomas", text: "Hola. Me llamo Tomás. ¿Y tú?" },
      { speaker: "valeria", text: "Yo soy Valeria. Mucho gusto, Tomás." },
      { speaker: "tomas", text: "Igualmente." },
      { speaker: "ortiz", text: "Buenas tardes. Soy Laura Ortiz, la directora." },
      { speaker: "tomas", text: "Buenas tardes, señora Ortiz. Soy Tomás Ruiz. Encantado." },
      { speaker: "ortiz", text: "Encantada. ¿Cómo está usted?" },
      { speaker: "tomas", text: "Muy bien, gracias." },
      { speaker: "martin", text: "Buenas noches. ¿Vos sos Valeria?" },
      { speaker: "valeria", text: "Sí, soy yo. ¿Y tú cómo te llamas?" },
      { speaker: "martin", text: "Me llamo Martín. Soy de Argentina." },
      { speaker: "valeria", text: "¡Hola, Martín! Hasta mañana, Tomás." },
      { speaker: "tomas", text: "¡Hasta mañana!" },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: no busques palabras. Solo decide cómo es cada encuentro.",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha todo una vez y responde.",
          items: [
            { q: "Encuentro 1, en el café: ¿cómo hablan?", options: ["De tú, informal", "De usted, formal"], answer: 0, why: "Dicen _¿Cómo te llamas?_ y _¿Y tú?_" },
            { q: "Encuentro 2, en la oficina: ¿cómo hablan?", options: ["De tú, informal", "De usted, formal"], answer: 1, why: "Dicen _señora Ortiz_ y _¿Cómo está usted?_" },
            { q: "Encuentro 3: ¿qué momento del día es?", options: ["la mañana", "la tarde", "la noche"], answer: 2, why: "Martín saluda con _Buenas noches_." },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: ahora sí, atención a los nombres y a los datos.",
        exercise: {
          id: "l2",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "¿Cómo se llama el chico del café?", options: ["Ramón", "Tomás", "Martín"], answer: 1 },
            { q: "¿Quién es Laura Ortiz?", options: ["una estudiante", "la directora", "una viajera"], answer: 1 },
            { q: "¿De dónde es Martín?", options: ["de México", "de Colombia", "de Argentina"], answer: 2 },
            { q: "¿Qué dice Tomás al final?", options: ["Hasta luego.", "Hasta mañana.", "Adiós."], answer: 1 },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en cómo cada persona trata a la otra.",
        exercise: {
          id: "l3",
          type: "classify",
          prompt: "¿Estas frases usan tú, usted o vos?",
          categories: ["tú", "usted", "vos"],
          items: [
            { text: "¿Cómo te llamas?", cat: 0 },
            { text: "¿Y tú?", cat: 0 },
            { text: "¿Cómo está usted?", cat: 1 },
            { text: "Buenas tardes, señora Ortiz.", cat: 1, why: "_Señora_ + apellido marca respeto: es un contexto de usted." },
            { text: "¿Vos sos Valeria?", cat: 2, why: "Martín es argentino: _vos sos_ = _tú eres_." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Intercambio de idiomas · CDMX",
    genre: "Chat de grupo",
    frame: "Primeros mensajes en el grupo de un intercambio de idiomas en un café de Coyoacán.",
    text: [
      "**Daniela** (18:02): ¡Hola, hola! Soy Daniela, la organizadora. Bienvenidos al grupo 🙂",
      "**Kenji** (18:15): Buenas tardes. Me llamo Kenji. Soy de Japón. ¡Mucho gusto!",
      "**Camille** (18:40): Hola, ¿qué tal? Yo soy Camille. ¡Encantada, Kenji!",
      "**Luis** (21:30): Buenas noches a todos. Mi nombre es Luis. Hasta mañana en el café 👋",
    ],
    glossary: [
      { es: "la organizadora", en: "the organiser (woman)" },
      { es: "bienvenidos", en: "welcome (to a group)" },
      { es: "a todos", en: "everyone" },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee los mensajes y responde.",
        items: [
          { q: "¿Quién organiza el intercambio?", options: ["Daniela", "Camille", "Luis"], answer: 0 },
          { q: "¿Quién escribe por la noche?", options: ["Kenji", "Camille", "Luis"], answer: 2, why: "Escribe a las 21:30 y saluda con _buenas noches_." },
          { q: "Camille escribe «Encantada». Entonces Camille…", options: ["es una mujer.", "es un hombre.", "no sabemos."], answer: 0, why: "Encantad**a**: habla una mujer." },
          { q: "¿Quién responde directamente a Kenji?", options: ["Daniela", "Camille", "Luis"], answer: 1 },
        ],
      },
      {
        id: "r2",
        type: "classify",
        prompt: "¿Qué hace cada persona en su mensaje? Clasifica las frases del chat.",
        categories: ["Saluda", "Se presenta", "Se despide"],
        items: [
          { text: "¡Hola, hola!", cat: 0, why: "Daniela abre su mensaje con un saludo." },
          { text: "Me llamo Kenji.", cat: 1, why: "_Me llamo_ + nombre: Kenji se presenta." },
          { text: "Buenas tardes.", cat: 0, why: "Kenji saluda según la hora: son las 18:15." },
          { text: "Yo soy Camille.", cat: 1, why: "_Soy_ + nombre: otra forma de presentarse." },
          { text: "Mi nombre es Luis.", cat: 1, why: "La forma más formal de decir tu nombre." },
          { text: "Hasta mañana en el café.", cat: 2, why: "_Hasta mañana_ es una despedida: se ven al día siguiente." },
        ],
      },
    ],
    noticing: {
      prompt: "Toca cada frase para ver qué hay detrás.",
      items: [
        { quote: "Soy Daniela", note: "Ser + nombre. No hace falta decir _yo_." },
        { quote: "Yo soy Camille", note: "Aquí _yo_ aparece porque Camille se presenta después de otra persona: contraste." },
        { quote: "Mi nombre es Luis", note: "Tercera forma de presentarse, un poco más formal." },
        { quote: "Buenas noches a todos", note: "Saludo para un grupo: _a todos_." },
      ],
    },
  },
  practice: {
    intro: "Combina todo lo de la semana. Cada ejercicio usa una mecánica distinta.",
    exercises: [
      {
        id: "x1",
        type: "order",
        title: "Construye la frase",
        prompt: "Toca las palabras en orden.",
        items: [
          { words: ["Hola,", "me", "llamo", "Pedro."], en: "Hi, my name is Pedro." },
          { words: ["¿Cómo", "se", "llama", "usted?"], alt: ["¿Usted cómo se llama?"], en: "What's your name? (formal)" },
          { words: ["Mucho", "gusto,", "yo", "soy", "Elena."], en: "Nice to meet you, I'm Elena." },
        ],
      },
      {
        id: "x2",
        type: "error",
        title: "Detective de errores",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "Buenos tardes, me llamo Rosa.", answers: ["Buenas tardes, me llamo Rosa."], why: "_Tarde_ es femenino: buen**as** tardes." },
          { sentence: "¿Cómo te llama?", answers: ["¿Cómo te llamas?"], why: "Con _tú_ el verbo termina en **-s**: te llama**s**." },
          { sentence: "Tú es Marta, ¿no?", answers: ["Tú eres Marta, ¿no?"], why: "Con _tú_: **eres**." },
          { sentence: "Laura dice: «Mucho gusto, Pablo. Encantado».", answers: ["Laura dice: «Mucho gusto, Pablo. Encantada»."], why: "Habla Laura, una mujer: encantad**a**." },
        ],
      },
      {
        id: "x3",
        type: "context",
        title: "¿Qué dices aquí?",
        prompt: "Lee la situación y elige la frase adecuada.",
        items: [
          { context: "Son las nueve de la mañana. Entras en una oficina.", q: "Dices:", options: ["Buenos días.", "Buenas noches.", "Hasta luego."], answer: 0 },
          { context: "Tu profesor te presenta a la señora Gómez, una persona mayor.", q: "Dices:", options: ["Mucho gusto, señora. ¿Cómo está usted?", "¡Hola! ¿Cómo estás?", "Chao."], answer: 0, why: "Persona mayor y presentación formal: usted." },
          { context: "Te vas de una fiesta a las once de la noche.", q: "Dices:", options: ["Buenas noches, hasta mañana.", "Buenos días.", "Mucho gusto."], answer: 0 },
        ],
      },
      {
        id: "x4",
        type: "transform",
        title: "De tú a usted",
        prompt: "Transforma la pregunta para hablar con usted.",
        items: [
          { source: "¿Cómo te llamas?", answers: ["¿Cómo se llama usted?", "¿Cómo se llama?", "¿Usted cómo se llama?"], why: "Te llamas → **se llama** (usted)." },
          { source: "¿Cómo estás?", answers: ["¿Cómo está usted?", "¿Cómo está?"], why: "Estás → **está** (usted)." },
          { source: "¿Tú eres Carlos?", answers: ["¿Usted es Carlos?", "¿Es usted Carlos?"], why: "Eres → **es** (usted)." },
        ],
      },
      {
        id: "x5",
        type: "open",
        title: "Escribe tú",
        prompt: "Escribe frases cortas con tus datos. Después compara con el modelo.",
        items: [
          {
            prompt: "Un compañero nuevo te escribe: «¡Hola! Soy Pablo. ¿Cómo te llamas?». Contesta en dos frases.",
            model: "¡Hola, Pablo! Me llamo Sam. Mucho gusto.",
            checklist: ["Saludas a Pablo", "Dices tu nombre con _me llamo_ o _soy_", "Terminas con _mucho gusto_ o _encantado/encantada_"],
          },
          {
            prompt: "Son las nueve de la mañana. Escribe a tu nueva profesora, de usted: saluda, di tu nombre y pregunta el suyo.",
            model: "Buenos días. Soy Sam, su nuevo estudiante. ¿Cómo se llama usted?",
            checklist: ["Usas _buenos días_", "Te presentas", "Preguntas con _¿Cómo se llama usted?_ y no con _te llamas_"],
          },
          {
            prompt: "Es de noche. Despídete del grupo del intercambio y di cuándo los ves.",
            model: "Buenas noches a todos. ¡Hasta mañana!",
            checklist: ["Usas _buenas noches_", "Usas una despedida como _hasta mañana_ o _hasta luego_"],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe tu primer mensaje para el grupo del intercambio de idiomas.",
    context: "Acabas de entrar en el grupo de la lectura. Son las cinco de la tarde.",
    steps: ["Saluda según la hora.", "Di tu nombre con _me llamo_ o _soy_.", "Añade una fórmula de cortesía para los demás.", "Despídete."],
    useLanguage: ["Buenas tardes", "Me llamo… / Soy…", "Mucho gusto", "Encantado / Encantada", "Hasta luego"],
    model: ["¡Buenas tardes a todos! Me llamo Sam. Soy estudiante. Mucho gusto, Daniela. ¡Hasta luego!"],
    checklist: [
      "Empiezas con un saludo adecuado a la hora.",
      "Usas _me llamo_ o _soy_ (nunca _yo llamo_).",
      "Si usas _encantado/encantada_, concuerda contigo.",
      "Terminas con una despedida.",
    ],
    words: [12, 40],
  },
  speaking: {
    intro: "Habla en voz alta, grábate y escúchate. Repite cada tarea hasta que salga sin leer.",
    tasks: [
      {
        title: "Tu presentación de 20 segundos",
        prompt: "Imagina que entras en una clase nueva. Saluda, di tu nombre, añade una fórmula de cortesía y despídete.",
        prep: ["Saludo + hora", "Me llamo… / Soy…", "Mucho gusto", "Hasta luego"],
        seconds: 20,
        model: "¡Hola! Buenos días. Me llamo Ana. Mucho gusto a todos. ¡Hasta luego!",
        selfCheck: ["Hablo sin leer.", "Las vocales suenan cortas y claras.", "Uso el saludo correcto para la hora."],
      },
      {
        title: "Dos versiones: tú y usted",
        prompt: "Saluda y pregunta el nombre a (a) un compañero joven en un café y (b) una señora mayor en una oficina. Grábate las dos versiones.",
        prep: ["(a) Hola, ¿qué tal? ¿Cómo te llamas?", "(b) Buenos días, señora. ¿Cómo se llama usted?"],
        seconds: 30,
        model: "Hola, ¿qué tal? ¿Cómo te llamas? … Buenos días, señora. ¿Cómo se llama usted?",
        selfCheck: ["Cambio _te llamas_ por _se llama_ con usted.", "Con la señora uso un saludo completo."],
      },
      {
        title: "Responde rápido",
        prompt: "Lee cada pregunta, tapa la pantalla y responde en voz alta en menos de tres segundos: «¿Cómo te llamas?», «¿Qué tal?», «Mucho gusto», «Hasta mañana».",
        seconds: 20,
        selfCheck: ["Respondo con frases completas.", "Uso _igualmente_ después de _mucho gusto_."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo, usa el español desde el primer segundo.",
    cards: [
      { move: "Saluda", task: "Entra en la clase con el saludo correcto según la hora y pregunta cómo está tu profesor o profesora.", phrases: ["Buenas tardes, ¿cómo estás?", "Buenos días, ¿cómo está usted?"] },
      { move: "Preséntate", task: "Di tu presentación de 20 segundos sin leer." },
      { move: "Pregunta", task: "Pregunta si prefiere que le hables de tú o de usted.", phrases: ["¿Tú o usted?", "¿Puedo hablarte de tú?"] },
      { move: "Despídete", task: "Al final, despídete con una fórmula que no usaste al llegar.", phrases: ["Hasta luego", "Hasta la próxima semana", "Nos vemos"] },
    ],
    bring: "Escucha tu grabación de 20 segundos justo antes de la clase.",
  },
  quiz: {
    items: [
      { type: "choice", q: "Son las tres de la tarde y saludas a tu vecino.", options: ["Buenos días.", "Buenas tardes.", "Buenas noches."], answer: 1, why: "Las 15:00 son la tarde." },
      { type: "listen", q: "¿Quién habla?", audio: "Encantada, soy Elena.", options: ["Una mujer que se llama Elena", "Un hombre que se llama Elena", "Una mujer que se llama Alana"], answer: 0, why: "_Encantada_ → habla una mujer." },
      { type: "gap", q: "—¿Cómo ___ llamas? —Me ___ Pablo.", answers: [["te"], ["llamo"]] },
      { type: "gap", q: "Usted ___ el señor Díaz, ¿verdad?", answers: [["es"]], why: "Usted → **es**." },
      { type: "transform", source: "Tú eres la profesora nueva, ¿verdad?", instruction: "Hazla formal (usted).", answers: ["Usted es la profesora nueva, ¿verdad?", "Es usted la profesora nueva, ¿verdad?", "Es la profesora nueva, ¿verdad?"], why: "Eres → **es** con usted." },
      { type: "order", words: ["Mucho", "gusto,", "me", "llamo", "Inés."] },
      { type: "error", sentence: "Buenos noches, señora.", answers: ["Buenas noches, señora."], why: "_Noche_ es femenino: buen**as** noches." },
      { type: "error", sentence: "Yo llamo Rafael.", answers: ["Me llamo Rafael.", "Yo me llamo Rafael."], why: "_Llamarse_ necesita **me**." },
      { type: "open", prompt: "Escribe cómo saludas y te presentas a una profesora nueva a las diez de la mañana.", model: "Buenos días. Me llamo… Mucho gusto.", checklist: ["Buenos días", "Me llamo / Soy", "Mucho gusto"] },
    ],
  },
  complete: {
    canNow: [
      "Saludar y despedirte según la hora del día.",
      "Presentarte con _me llamo_, _soy_ y _mi nombre es_.",
      "Preguntar el nombre de tú y de usted.",
      "Pronunciar las cinco vocales sin reducirlas.",
    ],
    review: ["Las formas soy / eres / es.", "Encantado o encantada según quien habla.", "Buen**as** tardes y buen**as** noches."],
  },
  related: [
    { path: "/la-central-de-las-identidades", label: "La Central de las Identidades · pronombres" },
    { path: "/clase/201", label: "Cinco vocales, cinco sonidos" },
  ],
};
