import type { Module } from "../../types";

export const a1w02: Module = {
  id: "a1-02",
  level: "a1",
  week: 2,
  kind: "core",
  title: "¿De dónde eres?",
  subtitle: "Decir de dónde eres, qué idiomas hablas y dar tu número de teléfono.",
  stop: { place: "Guadalajara", country: "México" },
  minutes: 70,
  newObjectives: [
    "a1.gram.ser-plural",
    "a1.gram.negacion-no",
    "a1.gram.nacionalidades-genero",
    "a1.voc.paises-idiomas",
    "a1.voc.numeros-0-20",
    "a1.pron.silabas",
    "a1.fun.origen",
    "a1.lis.numeros-datos",
  ],
  reviewObjectives: ["a1.gram.pronombres-sujeto", "a1.gram.ser-singular", "a1.fun.presentarse"],
  prerequisites: ["a1-01"],
  goal: {
    canDo: "Al final de esta semana puedes decir de dónde eres, tu nacionalidad y qué idiomas hablas, preguntar lo mismo a otras personas y dar o anotar un número de teléfono.",
    canDoEn: "By the end of this week, you can say where you're from, your nationality and which languages you speak, ask other people the same, and give or note down a phone number.",
    steps: [
      "Completa el verbo **ser**: `somos`, `sois`, `son`, y descubre dónde se usa _vosotros_ y dónde _ustedes_.",
      "Aprende a decir que no: **no** + verbo.",
      "Forma nacionalidades en masculino, femenino y plural.",
      "Cuenta del 0 al 20 y practica números de teléfono.",
      "Divide palabras en sílabas y pronúncialas con el mismo peso.",
      "Escucha a estudiantes nuevos en una escuela de Guadalajara y anota sus datos.",
      "Graba una presentación con tu origen y tus idiomas.",
    ],
  },
  theory: {
    intro: "La semana pasada aprendiste a decir quién eres. Ahora das un paso más: **de dónde eres**, **qué idiomas hablas** y **cómo te contactan**. Para eso necesitas el verbo _ser_ completo, la palabra _no_, las nacionalidades y los números del 0 al 20.",
    parts: [
      {
        heading: "Ser: todas las personas",
        body: [
          "Ya conoces `soy`, `eres` y `es`. Hoy añades el plural: **nosotros/nosotras somos**, **vosotros/vosotras sois**, **ustedes son** y **ellos/ellas son**.",
          "**Nosotros** incluye a la persona que habla y a otras personas: _Camila y yo_ = nosotros. Si el grupo es solo de mujeres, se dice **nosotras**. Si hay hombres y mujeres, se usa la forma masculina: _nosotros_.",
          "**Vosotros o ustedes.** Para hablar a un grupo, en España se usa **vosotros sois** con amigos y familia, y **ustedes son** en situaciones formales. En toda América Latina solo se usa **ustedes son**, para amigos y para desconocidos. Las dos formas son correctas: elige una según tu variedad y reconoce la otra.",
          "Igual que _usted es_, **ustedes son** habla con las personas de enfrente, pero el verbo va como con _ellos_: **son**.",
        ],
        support: [
          "_Nosotros_ = we, _vosotros_ = you all (informal, only in Spain), _ustedes_ = you all (formal in Spain; formal AND informal in Latin America), _ellos/ellas_ = they.",
          "The feminine forms _nosotras, vosotras, ellas_ are only for all-female groups. A mixed group uses the masculine form, even if there's only one man.",
          "If you learn Latin American Spanish, you never need to produce _vosotros_ — but you will hear it in films and series from Spain.",
        ],
        table: {
          caption: "El verbo ser, completo",
          head: ["Persona", "Pronombre", "Ser", "Ejemplo"],
          rows: [
            ["yo", "yo", "soy", "Soy de Chile."],
            ["tú (confianza)", "tú", "eres", "¿Eres de aquí?"],
            ["vos (Río de la Plata, Centroamérica)", "vos", "sos", "¿Sos argentina?"],
            ["usted (respeto)", "usted", "es", "¿Usted es de Lima?"],
            ["otra persona", "él / ella", "es", "Ella es cubana."],
            ["yo + otras personas", "nosotros / nosotras", "somos", "Somos de Perú."],
            ["un grupo, en confianza (España)", "vosotros / vosotras", "sois", "¿Sois de Madrid?"],
            ["un grupo (América; formal en España)", "ustedes", "son", "¿Ustedes son de Guadalajara?"],
            ["otras personas", "ellos / ellas", "son", "Ellos son colombianos."],
          ],
        },
        examples: [
          { es: "Camila y yo somos de Colombia.", en: "Camila and I are from Colombia." },
          { es: "—¿Ustedes son los estudiantes nuevos? —Sí, somos nosotros.", en: "Are you the new students? — Yes, that's us." },
          { es: "¿Vosotros sois de Sevilla?", en: "Are you (all) from Seville? (Spain, informal)" },
          { es: "Ana y Lucía son mexicanas.", en: "Ana and Lucía are Mexican." },
        ],
        mistakes: [
          { wrong: "Nosotros son de Perú.", right: "Nosotros somos de Perú.", why: "Con _nosotros_ el verbo es **somos**." },
          { wrong: "Ustedes sois de México.", right: "Ustedes son de México.", why: "_Ustedes_ usa la forma de _ellos_: **son**. _Sois_ es solo para _vosotros_." },
          { wrong: "Marta y yo son amigas.", right: "Marta y yo somos amigas.", why: "_Marta y yo_ = nosotras → **somos**." },
        ],
        tip: "Truco para el plural: **so-** aparece en _somos_, _sois_ y _son_. Solo tienes que cambiar el final: -mos (nosotros), -is (vosotros), -n (ellos, ustedes).",
      },
      {
        heading: "Decir que no: no + verbo",
        body: [
          "Para negar en español, pon **no delante del verbo**: _Soy de México_ → **No soy** de México. No hay verbos auxiliares como _do_ o _does_ en inglés: solo **no**.",
          "Si hay pronombre sujeto, el orden es: sujeto + **no** + verbo: **Ella no es** cubana. Con _llamarse_, el **no** va antes de _me, te, se_: **No me llamo** Luis.",
          "Para responder a una pregunta, es muy normal decir **no** dos veces: el primero responde, el segundo niega el verbo. —¿Eres española? —**No, no soy** española. Soy chilena.",
        ],
        support: [
          "Spanish negation is simple: put _no_ right before the verb. No 'do not', no 'am not' — just _no soy_, _no es_, _no somos_.",
          "_No, no soy de aquí_ is not a mistake: the first _no_ means 'no' (the answer), the second means 'not'.",
          "With _me llamo_, _no_ goes before the little word _me_: _No me llamo Ana_, never _Me no llamo_.",
        ],
        examples: [
          { es: "No soy de Guadalajara, soy de Monterrey.", en: "I'm not from Guadalajara, I'm from Monterrey." },
          { es: "—¿Son ustedes argentinos? —No, no somos argentinos. Somos uruguayos.", en: "Are you Argentinian? — No, we're not Argentinian. We're Uruguayan." },
          { es: "Él no se llama Mario, se llama Darío.", en: "His name isn't Mario, it's Darío." },
        ],
        mistakes: [
          { wrong: "Soy no de Madrid.", right: "No soy de Madrid.", why: "**No** va siempre delante del verbo." },
          { wrong: "Me no llamo Pedro.", right: "No me llamo Pedro.", why: "Con _llamarse_, **no** va antes de _me_." },
          { wrong: "Ella es no cubana.", right: "Ella no es cubana.", why: "Sujeto + **no** + verbo." },
        ],
      },
      {
        heading: "Nacionalidades: masculino, femenino y plural",
        body: [
          "Las nacionalidades son adjetivos: cambian según la persona. Hay tres modelos principales.",
          "**1. Terminan en -o:** cambia la -o por -a. _mexicano → mexicana_, _colombiano → colombiana_.",
          "**2. Terminan en consonante:** añade -a. _español → española_, _alemán → alemana_, _francés → francesa_. Atención: la tilde desaparece en el femenino (_inglés → inglesa_), porque la palabra tiene una sílaba más.",
          "**3. Terminan en -e o en -a:** son iguales para hombres y mujeres. _estadounidense, canadiense, belga_.",
          "El plural: después de vocal, añade **-s** (_mexicanos, canadienses_); después de consonante, **-es** (_españoles, alemanes_). Para un grupo mixto, usa el masculino plural: _Ana y Pedro son peruanos_.",
          "En español, las nacionalidades y los idiomas se escriben con **minúscula**: _Soy francesa. Hablo francés._ Los países, con mayúscula: _Francia_.",
        ],
        support: [
          "Nationalities agree with the person: _Pedro es mexicano_, _Ana es mexicana_, _Pedro y Ana son mexicanos_.",
          "Unlike English, nationalities and languages are NOT capitalised in Spanish: _soy inglés_, _hablo español_. Countries are: _Inglaterra, España_.",
          "The name of the language is usually the masculine singular nationality: _el francés, el alemán, el inglés_.",
        ],
        table: {
          caption: "Tres modelos de nacionalidad",
          head: ["País", "Él", "Ella", "Ellos / ellas"],
          rows: [
            ["México", "mexicano", "mexicana", "mexicanos / mexicanas"],
            ["España", "español", "española", "españoles / españolas"],
            ["Francia", "francés", "francesa", "franceses / francesas"],
            ["Alemania", "alemán", "alemana", "alemanes / alemanas"],
            ["Canadá", "canadiense", "canadiense", "canadienses"],
            ["Estados Unidos", "estadounidense", "estadounidense", "estadounidenses"],
          ],
        },
        examples: [
          { es: "Lukas es alemán y Hanna es alemana.", en: "Lukas is German and Hanna is German." },
          { es: "Somos inglesas, de Londres.", en: "We're English (women), from London." },
          { es: "Kofi y Ama son ghaneses.", en: "Kofi and Ama are Ghanaian." },
        ],
        mistakes: [
          { wrong: "Ella es francésa.", right: "Ella es francesa.", why: "En el femenino la tilde desaparece: fran-**ce**-sa ya es una palabra llana." },
          { wrong: "Soy Mexicano.", right: "Soy mexicano.", why: "Las nacionalidades van con minúscula en español." },
          { wrong: "Juan y Carla son colombianas.", right: "Juan y Carla son colombianos.", why: "Grupo mixto → masculino plural." },
        ],
      },
      {
        heading: "¿De dónde eres? ¿Qué idiomas hablas?",
        body: [
          "Para preguntar el origen: **¿De dónde eres?** (tú), **¿De dónde es usted?**, **¿De dónde son?** (ustedes). Para responder tienes dos opciones: **ser de + lugar** (_Soy de Guadalajara_, _Soy de México_) o **ser + nacionalidad** (_Soy mexicana_). Muchas personas combinan las dos: _Soy mexicana, de Guadalajara_.",
          "Para los idiomas usa el verbo **hablar**: **hablo** (yo), **hablas** (tú), **habla** (él, ella, usted). Pregunta: **¿Qué idiomas hablas?** Respuesta: _Hablo español e inglés._ Si hablas un poco: _Hablo un poco de español._",
          "Un detalle: _y_ se convierte en **e** delante de una palabra que empieza con el sonido _i_: español **e** inglés, Francia **e** Italia.",
          "Los habitantes de Guadalajara se llaman **tapatíos** (_tapatío, tapatía_). En México vas a oír: _Soy tapatía_ = soy de Guadalajara.",
        ],
        support: [
          "_¿De dónde eres?_ literally 'From where are you?'. The preposition _de_ goes first: never _¿Dónde eres de?_.",
          "_Hablo, hablas, habla_ are forms of _hablar_ (to speak). In week 4 you'll learn the whole pattern; for now learn them as fixed chunks.",
        ],
        examples: [
          { es: "—¿De dónde eres? —Soy de Lima. Soy peruano.", en: "Where are you from? — I'm from Lima. I'm Peruvian." },
          { es: "—¿De dónde es usted? —Soy de Toronto, soy canadiense.", en: "Where are you from? (formal) — I'm from Toronto, I'm Canadian." },
          { es: "—¿Qué idiomas hablas? —Hablo inglés, francés y un poco de español.", en: "What languages do you speak? — I speak English, French and a little Spanish." },
        ],
        mistakes: [
          { wrong: "¿Dónde eres de?", right: "¿De dónde eres?", why: "En español la preposición va al principio de la pregunta: **De** dónde." },
          { wrong: "Soy de mexicana.", right: "Soy mexicana. / Soy de México.", why: "_De_ va con un lugar (_de México_); la nacionalidad va sin _de_." },
          { wrong: "Hablo español y inglés.", right: "Hablo español e inglés.", why: "Delante del sonido _i_, **y** cambia a **e** para no repetir el sonido." },
        ],
        tip: "Una respuesta completa y natural tiene tres piezas: lugar + nacionalidad + idiomas. _Soy de Oporto, soy portugués y hablo portugués e inglés._",
      },
      {
        heading: "Los números del 0 al 20",
        body: [
          "Del 0 al 15 cada número tiene su propia palabra. Memoriza especialmente **once, doce, trece, catorce, quince**: no se parecen a _uno, dos, tres_ de forma regular.",
          "Del 16 al 19 se dice «diez y seis», pero se escribe en **una sola palabra**: **dieciséis, diecisiete, dieciocho, diecinueve**. _Dieciséis_ lleva tilde.",
          "Para dar un número de teléfono, puedes decir las cifras una por una (_tres, tres, uno, cinco…_) o en parejas (_treinta y tres…_). Esta semana usa cifras sueltas o parejas hasta el 20. En España es frecuente agrupar de dos en dos; en México, muchos dicen el número cifra por cifra o en grupos.",
          "Pregunta útil: **¿Cuál es tu número de teléfono?** (tú) / **¿Cuál es su número de teléfono?** (usted). Respuesta: _Es el…_ o directamente las cifras.",
        ],
        support: [
          "11–15 are irregular: _once, doce, trece, catorce, quince_. 16–19 are 'ten and six' written as one word: _dieci-séis_.",
          "_Cero_ is zero. In phone numbers you'll hear each digit clearly: _cero, cero, cinco…_",
        ],
        table: {
          caption: "Del 0 al 20",
          head: ["0–6", "7–13", "14–20"],
          rows: [
            ["0 cero", "7 siete", "14 catorce"],
            ["1 uno", "8 ocho", "15 quince"],
            ["2 dos", "9 nueve", "16 dieciséis"],
            ["3 tres", "10 diez", "17 diecisiete"],
            ["4 cuatro", "11 once", "18 dieciocho"],
            ["5 cinco", "12 doce", "19 diecinueve"],
            ["6 seis", "13 trece", "20 veinte"],
          ],
        },
        examples: [
          { es: "Mi número es el seis, uno, dos, cero, ocho, siete, cinco, cuatro, nueve.", en: "My number is 612 087 549." },
          { es: "Salón doce, por favor.", en: "Room twelve, please." },
        ],
        mistakes: [
          { wrong: "diez y seis", right: "dieciséis", why: "Del 16 al 19 se escribe en una sola palabra: **dieci**séis." },
          { wrong: "cuatroce", right: "catorce", why: "El 14 es irregular: **catorce**." },
        ],
      },
    ],
  },
  grammar: {
    intro: "Practica el verbo _ser_ completo, la negación y las nacionalidades.",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "Somos, sois, son",
        prompt: "Elige la forma correcta de **ser**.",
        items: [
          { q: "Andrés y yo ___ de Medellín.", options: ["somos", "son", "sois"], answer: 0, why: "_Andrés y yo_ = nosotros → **somos**." },
          { q: "Buenos días. ¿Ustedes ___ los estudiantes de Colombia?", options: ["sois", "son", "somos"], answer: 1, why: "_Ustedes_ usa la forma de _ellos_: **son**." },
          { q: "En Madrid, a dos amigos: «¿Vosotros ___ de aquí?»", options: ["son", "sois", "es"], answer: 1, why: "_Vosotros_ (España, confianza) → **sois**." },
          { q: "Kenji y Yuki ___ japoneses.", options: ["es", "son", "somos"], answer: 1, why: "_Kenji y Yuki_ = ellos → **son**." },
          { q: "Mi amiga Laura ___ de Bogotá.", options: ["son", "eres", "es"], answer: 2, why: "Repaso: una persona (ella) → **es**." },
        ],
      },
      {
        id: "g2",
        type: "gap",
        title: "No, no soy…",
        prompt: "Completa la respuesta negativa con **no** y la forma correcta de _ser_.",
        items: [
          { q: "—¿Eres argentina? —No, ___ ___ argentina. Soy uruguaya.", answers: [["no"], ["soy"]], why: "Respuesta: **No**, + **no soy**. El segundo _no_ va delante del verbo." },
          { q: "—¿Ustedes son de Guadalajara? —No, ___ ___ de Guadalajara. Somos de Puebla.", answers: [["no"], ["somos"]], why: "Contestas por el grupo: **no somos**." },
          { q: "—¿Él es Tomás? —No, ___ ___ Tomás. Es Mateo.", answers: [["no"], ["es"]], why: "Él → **no es**." },
          { q: "—¿Usted es la profesora? —No, yo ___ ___ la profesora. Soy estudiante.", answers: [["no"], ["soy"]], why: "Con sujeto: _yo_ + **no** + **soy**." },
          { q: "—¿Te llamas Marisol? —No, ___ ___ ___ Marisol. Me llamo Maribel.", answers: [["no"], ["me"], ["llamo"]], why: "Con _llamarse_: **no me llamo**." },
        ],
      },
      {
        id: "g3",
        type: "transform",
        title: "Él, ella, ellos",
        prompt: "Cambia la nacionalidad según la instrucción.",
        items: [
          { source: "Diego es peruano.", instruction: "Habla de Lucía.", answers: ["Lucía es peruana."], why: "Modelo -o → **-a**: peruana." },
          { source: "Pierre es francés.", instruction: "Habla de Amélie.", answers: ["Amélie es francesa."], why: "Consonante → **+a**, y la tilde desaparece: francesa." },
          { source: "Hans es alemán.", instruction: "Habla de Hans y Greta.", answers: ["Hans y Greta son alemanes."], why: "Plural después de consonante: **-es**; grupo mixto → masculino. Alemán pierde la tilde: alemanes." },
          { source: "Emily es canadiense.", instruction: "Habla de Emily y Jack.", answers: ["Emily y Jack son canadienses."], why: "_Canadiense_ es igual para él y ella; en plural, solo **-s**." },
          { source: "Soy español.", instruction: "Habla de ti y de tu amigo Pablo (nosotros).", answers: ["Somos españoles.", "Nosotros somos españoles.", "Pablo y yo somos españoles."], why: "Nosotros → **somos**; español → **españoles**." },
        ],
      },
      {
        id: "g4",
        type: "classify",
        title: "¿Dónde lo oyes?",
        prompt: "¿Esta pregunta a un grupo de amigos se oye en España, en América Latina o en los dos lugares?",
        categories: ["solo en España", "en América Latina (y en España, formal)"],
        items: [
          { text: "¿Vosotros sois de aquí?", cat: 0, why: "_Vosotros sois_: forma de confianza de España." },
          { text: "¿Ustedes son de aquí?", cat: 1, why: "_Ustedes son_ es la forma de toda América; en España es formal." },
          { text: "¿Sois hermanas?", cat: 0, why: "_Sois_ siempre corresponde a _vosotros/vosotras_." },
          { text: "¿Son colombianos?", cat: 1, why: "_Son_ puede ser _ustedes_ o _ellos_." },
          { text: "¿De dónde sois?", cat: 0 },
          { text: "¿De dónde son ustedes?", cat: 1 },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Aprende cada país con su nacionalidad, y los números en bloques. Di siempre la frase completa en voz alta.",
    groups: [
      {
        title: "Países y nacionalidades (él / ella)",
        items: [
          { es: "México · mexicano, mexicana", en: "Mexico · Mexican" },
          { es: "Colombia · colombiano, colombiana", en: "Colombia · Colombian" },
          { es: "Argentina · argentino, argentina", en: "Argentina · Argentinian" },
          { es: "Perú · peruano, peruana", en: "Peru · Peruvian" },
          { es: "Chile · chileno, chilena", en: "Chile · Chilean" },
          { es: "Cuba · cubano, cubana", en: "Cuba · Cuban" },
          { es: "España · español, española", en: "Spain · Spanish" },
          { es: "Estados Unidos · estadounidense", en: "United States · American (same for both)" },
          { es: "Canadá · canadiense", en: "Canada · Canadian (same for both)" },
          { es: "Brasil · brasileño, brasileña", en: "Brazil · Brazilian" },
          { es: "Francia · francés, francesa", en: "France · French" },
          { es: "Alemania · alemán, alemana", en: "Germany · German" },
          { es: "Inglaterra · inglés, inglesa", en: "England · English" },
          { es: "Japón · japonés, japonesa", en: "Japan · Japanese" },
        ],
      },
      {
        title: "Idiomas y origen",
        items: [
          { es: "¿De dónde eres? / ¿De dónde es usted?", en: "Where are you from? (tú / usted)" },
          { es: "Soy de Guadalajara.", en: "I'm from Guadalajara." },
          { es: "No soy de aquí.", en: "I'm not from here." },
          { es: "¿Qué idiomas hablas?", en: "What languages do you speak?" },
          { es: "Hablo español e inglés.", en: "I speak Spanish and English." },
          { es: "Hablo un poco de francés.", en: "I speak a little French." },
          { es: "el portugués, el alemán, el chino, el japonés", en: "Portuguese, German, Chinese, Japanese (languages are masculine)" },
        ],
      },
      {
        title: "Números y datos",
        items: [
          { es: "cero, uno, dos, tres, cuatro, cinco", en: "0, 1, 2, 3, 4, 5" },
          { es: "seis, siete, ocho, nueve, diez", en: "6, 7, 8, 9, 10" },
          { es: "once, doce, trece, catorce, quince", en: "11, 12, 13, 14, 15" },
          { es: "dieciséis, diecisiete, dieciocho, diecinueve, veinte", en: "16, 17, 18, 19, 20" },
          { es: "¿Cuál es tu número de teléfono?", en: "What's your phone number? (tú)" },
          { es: "¿Puedes repetir, por favor?", en: "Can you repeat, please?" },
          { es: "el celular (América) / el móvil (España)", en: "mobile phone" },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "País y nacionalidad",
        prompt: "Une cada frase con la nacionalidad correcta.",
        pairs: [
          { left: "Gabriela es de Santiago de Chile. Es…", right: "chilena" },
          { left: "Thiago es de São Paulo. Es…", right: "brasileño" },
          { left: "Akira es de Tokio. Es…", right: "japonés" },
          { left: "Charlotte es de Londres. Es…", right: "inglesa" },
          { left: "Yaima es de La Habana. Es…", right: "cubana" },
          { left: "Liam es de Chicago. Es…", right: "estadounidense" },
        ],
        why: "La nacionalidad concuerda con la persona: Gabriela → chilen**a**, Thiago → brasileñ**o**. _Estadounidense_ es igual para los dos.",
      },
      {
        id: "v2",
        type: "choice",
        title: "Cuentas rápidas",
        prompt: "Calcula y elige el número en palabras.",
        items: [
          { q: "siete + seis =", options: ["trece", "tres", "dieciséis"], answer: 0, why: "7 + 6 = 13: **trece**." },
          { q: "veinte − seis =", options: ["catorce", "cuatro", "cuarenta"], answer: 0, why: "20 − 6 = 14: **catorce**, no _cuatroce_." },
          { q: "nueve + nueve =", options: ["diecinueve", "dieciocho", "diecisiete"], answer: 1, why: "9 + 9 = 18: **dieciocho**." },
          { q: "dos + diez =", options: ["doce", "dos", "diez y dos"], answer: 0, why: "12 tiene su propia palabra: **doce**." },
          { q: "once + cuatro =", options: ["catorce", "quince", "cinco"], answer: 1, why: "11 + 4 = 15: **quince**." },
        ],
      },
      {
        id: "v3",
        type: "gap",
        title: "Idiomas",
        prompt: "Completa con el idioma (en minúscula).",
        bank: ["portugués", "francés", "alemán", "japonés", "español"],
        items: [
          { q: "Thiago es brasileño. Habla ___.", answers: [["portugués"]], why: "En Brasil se habla **portugués**, no español." },
          { q: "Amélie es de París. Habla ___.", answers: [["francés"]], why: "Idioma = nacionalidad en masculino: **francés**." },
          { q: "Akira es japonés. Habla ___ e inglés.", answers: [["japonés"]], why: "**Japonés**: el idioma va en minúscula." },
          { q: "Hans es de Berlín. Habla ___.", answers: [["alemán"]], why: "Alemania → **alemán**." },
          { q: "Camila es colombiana. Habla ___.", answers: [["español"]], why: "En Colombia se habla **español**." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "La sílaba española: todas pesan igual",
    explanation: [
      "El español es una lengua de **ritmo silábico**: cada sílaba dura más o menos lo mismo. Por eso _Guadalajara_ suena como una fila regular: **gua-da-la-ja-ra**, cinco golpes iguales.",
      "La sílaba más típica del español es **consonante + vocal**: _ca-sa_, _Mé-xi-co_, _pe-ru-a-no_. Cuando hay una consonante entre dos vocales, va con la vocal de después: _co-lom-bia-no_, no _col-omb-ia-no_.",
      "Cuando hay dos consonantes juntas, normalmente se separan: _Ar-gen-ti-na_, _es-pa-ñol_. Pero algunas parejas no se separan nunca: **ch, ll, rr** y las combinaciones con **l** o **r** como _bl, br, pl, pr, tr, gr_: _Bra-sil_, _in-glés_, _ca-tor-ce_.",
      "Las vocales **i** y **u** forman una sola sílaba con otra vocal cuando no llevan acento fuerte: Co-lom-**bia**, **die**-ci-séis, **Gua**-da-la-ja-ra, ca-na-**dien**-se. Esto se llama _diptongo_.",
      "Variación: en el Caribe, en Andalucía y en otras zonas la **s** al final de sílaba se aspira o casi desaparece: _los dos_ suena «loh doh». En el centro de México, en el habla rápida, algunas vocales sin acento se oyen muy cortas. Pero la regla de base es la misma: sílabas claras y regulares.",
    ],
    support: [
      "English is stress-timed: some syllables are long and others are swallowed. Spanish is syllable-timed: tap each syllable with your finger and give it the same time.",
      "Practise by clapping: _me-xi-ca-na_ = 4 claps, _es-ta-dou-ni-den-se_ = 6 claps.",
    ],
    table: {
      head: ["Palabra", "Sílabas", "Número"],
      rows: [
        ["Perú", "Pe-rú", "2"],
        ["chileno", "chi-le-no", "3"],
        ["Argentina", "Ar-gen-ti-na", "4"],
        ["Guadalajara", "Gua-da-la-ja-ra", "5"],
        ["estadounidense", "es-ta-dou-ni-den-se", "6"],
      ],
    },
    perceive: {
      id: "p1",
      type: "listen",
      title: "Cuenta las sílabas",
      prompt: "Escucha cada palabra y toca los golpes con el dedo. ¿Cuántas sílabas oyes?",
      items: [
        { q: "¿Cuántas sílabas tiene?", audio: "Colombia", options: ["2", "3", "4"], answer: 1, why: "Co-lom-bia: **ia** es una sola sílaba." },
        { q: "¿Cuántas sílabas tiene?", audio: "mexicana", options: ["3", "4", "5"], answer: 1, why: "me-xi-ca-na." },
        { q: "¿Cuántas sílabas tiene?", audio: "dieciséis", options: ["3", "4", "5"], answer: 0, why: "die-ci-séis: **ie** y **ei** son una sílaba cada una." },
        { q: "¿Cuántas sílabas tiene?", audio: "español", options: ["2", "3", "4"], answer: 1, why: "es-pa-ñol." },
        { q: "¿Cuántas sílabas tiene?", audio: "Guadalajara", options: ["4", "5", "6"], answer: 1, why: "Gua-da-la-ja-ra." },
        { q: "¿Cuántas sílabas tiene?", audio: "inglesa", options: ["2", "3", "4"], answer: 1, why: "in-gle-sa: **gl** no se separa." },
      ],
    },
    produce: [
      { text: "Gua-da-la-ja-ra. Guadalajara.", tip: "Primero sílaba por sílaba, con el mismo tiempo para cada una. Después, la palabra entera sin perder ninguna vocal.", voice: "es-MX-f" },
      { text: "Somos colombianos, de Medellín.", tip: "So-mos-co-lom-bia-nos: seis golpes regulares. La **s** final de _somos_ se une a la **c**: no hagas pausa.", voice: "es-CO-m" },
      { text: "No soy española, soy argentina.", tip: "El **no** va pegado al verbo: _no-soy_ suena como una sola unidad.", voice: "es-AR-f" },
      { text: "Mi número es el seis, quince, doce, dieciocho, cero.", tip: "_Die-ci-o-cho_: cuatro sílabas claras. No digas «dieciocho» como «dichocho».", voice: "es-ES-m" },
      { text: "Hablo inglés, francés y un poco de español.", tip: "_In-glés_, _fran-cés_: la **gl** y la **fr** van juntas. Mantén el ritmo regular hasta el final." },
    ],
    spelling: "Para dividir por escrito, una consonante entre vocales va con la vocal siguiente (_ca-na-dien-se_). **Ch**, **ll** y **rr** son una sola letra a efectos de sílaba: _chi-le-no_, _a-ma-ri-llo_, _pe-rro_.",
  },
  listening: {
    title: "Primer día en una escuela de Guadalajara",
    context: "Es lunes por la mañana en una escuela de español del centro de Guadalajara. Lupita, la recepcionista, recibe a los estudiantes nuevos y apunta sus datos. Escucha la conversación completa.",
    speakers: [
      { id: "lupita", name: "Lupita", voice: "es-MX-f", role: "recepcionista" },
      { id: "camila", name: "Camila", voice: "es-CO-f", role: "estudiante" },
      { id: "andres", name: "Andrés", voice: "es-CO-m", role: "estudiante" },
      { id: "javier", name: "Javier", voice: "es-ES-m", role: "estudiante" },
    ],
    script: [
      { speaker: "lupita", text: "¡Buenos días! Bienvenidos. ¿Ustedes son los estudiantes nuevos?" },
      { speaker: "camila", text: "Sí, somos nosotros. Yo soy Camila y él es Andrés." },
      { speaker: "lupita", text: "Mucho gusto. Yo soy Lupita. ¿De dónde son?" },
      { speaker: "andres", text: "Somos colombianos, de Medellín." },
      { speaker: "lupita", text: "¡Qué bien! ¿Y hablan inglés?" },
      { speaker: "camila", text: "Yo sí, hablo inglés. Andrés no habla inglés. Él habla un poco de francés." },
      { speaker: "lupita", text: "Muy bien. Andrés, ¿cuál es tu número de celular?" },
      { speaker: "andres", text: "Es el tres, uno, cinco, dos, cero, siete, uno, cuatro, nueve, seis." },
      { speaker: "lupita", text: "Tres, uno, cinco, dos, cero, siete, uno, cuatro, nueve, seis. Perfecto." },
      { speaker: "javier", text: "¡Hola, buenos días! Perdón. Soy Javier. ¿Vosotros sois estudiantes también?" },
      { speaker: "camila", text: "Sí, somos estudiantes. ¿Tú eres de Madrid?" },
      { speaker: "javier", text: "No, no soy de Madrid. Soy de Sevilla. Soy español, de Andalucía." },
      { speaker: "lupita", text: "Javier, tu número es el seis, dieciocho, quince, doce, once, ¿verdad?" },
      { speaker: "javier", text: "Sí, eso es." },
      { speaker: "lupita", text: "Perfecto. Las clases son en el salón catorce. ¡Bienvenidos a Guadalajara!" },
      { speaker: "andres", text: "¿El salón cuatro?" },
      { speaker: "lupita", text: "No, no es el cuatro. Es el catorce: uno, cuatro." },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: no anotes nada. Solo descubre quiénes son y de dónde son.",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha una vez y responde.",
          items: [
            { q: "¿Cuántos estudiantes nuevos hablan con Lupita?", options: ["dos", "tres", "cuatro"], answer: 1, why: "Camila, Andrés y Javier: **tres**." },
            { q: "¿De dónde son Camila y Andrés?", options: ["de México", "de Colombia", "de España"], answer: 1, why: "Andrés dice: _Somos colombianos, de Medellín_." },
            { q: "¿De qué país es Javier?", options: ["de España", "de Argentina", "de Colombia"], answer: 0, why: "Javier dice: _Soy español, de Andalucía_." },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: ahora anota los datos con atención, como Lupita.",
        exercise: {
          id: "l2",
          type: "choice",
          prompt: "Elige el dato correcto.",
          items: [
            { q: "El celular de Andrés es…", options: ["315 207 1496", "315 217 1496", "351 207 1496"], answer: 0, why: "_Tres, uno, cinco, dos, cero, siete, uno, cuatro, nueve, seis_." },
            { q: "El número de Javier es…", options: ["6 18 15 12 11", "6 18 15 2 11", "6 8 15 12 11"], answer: 0, why: "_Seis, dieciocho, quince, doce, once_." },
            { q: "¿De qué ciudad es Javier?", options: ["Madrid", "Sevilla", "Medellín"], answer: 1, why: "_No, no soy de Madrid. Soy de Sevilla._" },
            { q: "¿Quién habla inglés?", options: ["Camila", "Andrés", "Camila y Andrés"], answer: 0, why: "_Yo sí, hablo inglés. Andrés no habla inglés._" },
            { q: "¿En qué salón son las clases?", options: ["en el 4", "en el 14", "en el 15"], answer: 1, why: "Lupita repite: _Es el catorce: uno, cuatro_." },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en cómo hablan al grupo y en las frases negativas.",
        exercise: {
          id: "l3",
          type: "classify",
          prompt: "¿Qué persona del verbo usa cada frase?",
          categories: ["nosotros (somos)", "ustedes (son, hablan)", "vosotros (sois)"],
          items: [
            { text: "¿Ustedes son los estudiantes nuevos?", cat: 1, why: "Lupita es mexicana: para un grupo usa **ustedes**." },
            { text: "Somos colombianos, de Medellín.", cat: 0 },
            { text: "¿Y hablan inglés?", cat: 1, why: "_Hablan_ va con _ustedes_, aunque Lupita no dice el pronombre." },
            { text: "¿Vosotros sois estudiantes también?", cat: 2, why: "Javier es de España: para un grupo de amigos usa **vosotros sois**." },
            { text: "Sí, somos estudiantes.", cat: 0 },
            { text: "¿De dónde son?", cat: 1 },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Intercambio de idiomas · Guadalajara",
    genre: "Tablón de perfiles",
    frame: "Perfiles en la página web de un intercambio de idiomas que se reúne en un café de la colonia Americana, en Guadalajara.",
    text: [
      "**¡Hola! Somos el intercambio «Lenguas Tapatías».** Jueves, 19:00, café La Jacaranda. Mesas de español, inglés, francés y alemán. Perfiles de esta semana:",
      "**Mariana** · Soy tapatía: soy de aquí, de Guadalajara. Hablo español e inglés. No soy profesora, soy estudiante de diseño. Mesa 3.",
      "**Kofi y Ama** · Somos ghaneses, de Kumasi. No somos de la capital. Hablamos inglés, twi y un poco de español. Mesa 7.",
      "**Lukas** · Soy alemán, de Berlín. Hablo alemán, inglés y un poco de español. ¿Mi español? ¡No es perfecto! Mesa 12.",
      "**Yaima** · Soy cubana, de La Habana. Mi novio, Pierre, es francés, de Lyon. Él no habla muy bien español. Habla francés e inglés. Somos de la mesa 15.",
      "Para reservar, escribe al WhatsApp del intercambio. ¡Bienvenidos!",
    ],
    glossary: [
      { es: "el tablón", en: "noticeboard" },
      { es: "la mesa", en: "table" },
      { es: "la capital", en: "the capital city" },
      { es: "mi novio", en: "my boyfriend" },
      { es: "reservar", en: "to book" },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee los perfiles y responde.",
        items: [
          { q: "¿Quién es de Guadalajara?", options: ["Mariana", "Yaima", "Lukas"], answer: 0, why: "_Tapatía_ = de Guadalajara." },
          { q: "¿Qué idiomas hablan Kofi y Ama?", options: ["inglés, twi y un poco de español", "solo inglés", "francés y twi"], answer: 0 },
          { q: "¿En qué mesa está Lukas?", options: ["en la 2", "en la 12", "en la 15"], answer: 1 },
          { q: "¿De dónde es Pierre?", options: ["de La Habana", "de Lyon", "de Berlín"], answer: 1, why: "Yaima dice: _Pierre es francés, de Lyon_." },
        ],
      },
      {
        id: "r2",
        type: "classify",
        prompt: "¿Verdadero o falso según el texto?",
        categories: ["verdadero", "falso"],
        items: [
          { text: "Mariana es profesora.", cat: 1, why: "Ella dice: _No soy profesora, soy estudiante_." },
          { text: "Kofi y Ama no son de la capital de Ghana.", cat: 0 },
          { text: "Lukas habla muy bien español.", cat: 1, why: "Él dice: _¡No es perfecto!_" },
          { text: "Yaima y Pierre son de la misma nacionalidad.", cat: 1, why: "Yaima es cubana y Pierre es francés." },
          { text: "El intercambio es los jueves por la tarde.", cat: 0, why: "Jueves, 19:00." },
        ],
      },
    ],
    noticing: {
      prompt: "Mira cómo funcionan estas frases del texto.",
      items: [
        { quote: "Somos ghaneses", note: "Nosotros → **somos**. _Ghanés_ + -es = _ghaneses_: la tilde desaparece en plural." },
        { quote: "No somos de la capital", note: "Negación: **no** delante del verbo." },
        { quote: "Hablo español e inglés", note: "**E** en lugar de _y_ delante de _inglés_ (sonido _i_)." },
        { quote: "Soy tapatía", note: "Gentilicio de Guadalajara. Concuerda como cualquier nacionalidad: _tapatío_, _tapatía_." },
        { quote: "Pierre es francés", note: "Nacionalidad en minúscula y en masculino porque Pierre es un hombre." },
      ],
    },
  },
  practice: {
    intro: "Ahora todo junto: ser, negación, nacionalidades, idiomas y números.",
    exercises: [
      {
        id: "x1",
        type: "order",
        title: "Frases completas",
        prompt: "Ordena las palabras.",
        items: [
          { words: ["No", "soy", "de", "aquí,", "soy", "de", "Lima."], en: "I'm not from here, I'm from Lima." },
          { words: ["¿De", "dónde", "son", "ustedes?"], alt: ["¿Ustedes de dónde son?"], en: "Where are you (all) from?" },
          { words: ["Ellas", "no", "son", "españolas."], en: "They (women) aren't Spanish." },
          { words: ["Hablo", "inglés", "y", "un", "poco", "de", "español."], en: "I speak English and a little Spanish." },
        ],
      },
      {
        id: "x2",
        type: "error",
        title: "Detective de errores",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "Nosotras somos argentinos.", answers: ["Nosotras somos argentinas."], why: "_Nosotras_ = solo mujeres → argentin**as**." },
          { sentence: "Yo soy de chilena.", answers: ["Yo soy chilena.", "Soy chilena.", "Yo soy de Chile.", "Soy de Chile."], why: "La nacionalidad va sin _de_. _De_ va con el país: _de Chile_." },
          { sentence: "Ellos sois de Cuba.", answers: ["Ellos son de Cuba."], why: "_Ellos_ → **son**. _Sois_ es para _vosotros_." },
          { sentence: "Hablo japonés y inglés.", answers: ["Hablo japonés e inglés."], why: "Delante de una palabra que empieza con el sonido _i_, **y** cambia a **e**." },
          { sentence: "Me no llamo Sara, me llamo Clara.", answers: ["No me llamo Sara, me llamo Clara."], why: "**No** va antes de _me_: _no me llamo_." },
        ],
      },
      {
        id: "x3",
        type: "context",
        title: "¿Qué dices?",
        prompt: "Lee la situación y elige la frase más natural.",
        items: [
          { context: "En Ciudad de México, quieres saber el origen de dos chicas jóvenes de tu clase.", q: "Preguntas:", options: ["¿De dónde son?", "¿De dónde sois?", "¿Dónde son de?"], answer: 0, why: "En México, para un grupo se usa _ustedes_: **son**. _Sois_ es de España." },
          { context: "Una señora mayor en una oficina de Guadalajara. Quieres saber de dónde es.", q: "Preguntas:", options: ["¿De dónde es usted?", "¿De dónde eres?", "¿De dónde son?"], answer: 0, why: "Persona mayor, situación formal: **usted es**." },
          { context: "Un chico pregunta: «¿Eres de Estados Unidos?». Eres de Canadá.", q: "Respondes:", options: ["No, no soy estadounidense. Soy canadiense.", "Sí, soy canadiense.", "No, soy no de Estados Unidos."], answer: 0, why: "Respuesta negativa: **No, no soy…** + la información correcta." },
          { context: "No entiendes un número de teléfono.", q: "Dices:", options: ["¿Puedes repetir, por favor?", "No soy de aquí.", "Mucho gusto."], answer: 0 },
        ],
      },
      {
        id: "x4",
        type: "transform",
        title: "De uno a varios",
        prompt: "Pasa la frase al plural.",
        items: [
          { source: "Soy colombiana.", instruction: "nosotras", answers: ["Somos colombianas.", "Nosotras somos colombianas."], why: "Soy → **somos**; colombiana → **colombianas**." },
          { source: "¿Eres inglés?", instruction: "ustedes", answers: ["¿Son ingleses?", "¿Ustedes son ingleses?", "¿Son ustedes ingleses?"], why: "Eres → **son** (ustedes); inglés → **ingleses**, sin tilde." },
          { source: "Ella no es japonesa.", instruction: "ellas", answers: ["Ellas no son japonesas."], why: "Es → **son**; japonesa → **japonesas**. El _no_ no cambia de lugar." },
          { source: "¿Tú eres de Valencia?", instruction: "vosotros (España)", answers: ["¿Vosotros sois de Valencia?", "¿Sois de Valencia?"], why: "Tú eres → **vosotros sois**." },
        ],
      },
      {
        id: "x5",
        type: "gap",
        title: "Un formulario",
        prompt: "Completa la conversación en la recepción del hostal.",
        bank: ["De dónde", "eres", "no", "soy", "Hablo", "dieciséis"],
        items: [
          { q: "—Hola, ¿___ son ustedes? —Somos de Chile.", answers: [["De dónde", "de dónde"]], why: "Preguntas el origen: **¿De dónde…?**" },
          { q: "—Y tú, ¿también ___ chilena? —No, yo ___ soy chilena, ___ peruana.", answers: [["eres"], ["no"], ["soy"]], hint: "tú + ser / negación / yo + ser", why: "Tú **eres**; negación **no** + verbo; yo **soy**." },
          { q: "—¿Qué idiomas hablan? —___ español y quechua. Mi amiga habla español e inglés.", answers: [["Hablo", "hablo"]], why: "Hablas de ti: **hablo**." },
          { q: "—¿Número de habitación? —La ___, por favor: uno, seis.", answers: [["dieciséis", "16"]], why: "Uno, seis = **dieciséis**, en una sola palabra y con tilde." },
        ],
      },
      {
        id: "x6",
        type: "open",
        title: "Escribe tú",
        prompt: "Escribe frases cortas con el lenguaje de la semana.",
        items: [
          {
            prompt: "Lupita te escribe por WhatsApp: «¡Hola! Soy Lupita, de la escuela. ¿De dónde eres? ¿Qué idiomas hablas? ¿Cuál es tu número de celular?». Contesta en 2 o 3 frases.",
            model: "¡Hola, Lupita! Soy de Dublín, soy irlandesa. Hablo inglés y un poco de español. Mi número es el ocho, siete, dos, cero, cinco, uno, uno, nueve, seis.",
            checklist: ["Soy de + ciudad / país y la nacionalidad sin «de»", "Hablo… (e delante de inglés)", "El número en palabras, bien escrito"],
          },
          {
            prompt: "Presenta a dos personas que conoces (reales o inventadas) de otro país. Escribe 3 frases: quiénes son, de dónde son y una frase con **no**.",
            model: "Ellos son Kenji y Aiko. Son japoneses, de Osaka. No son de Tokio y no hablan español.",
            checklist: ["Son + nacionalidad en plural", "Una frase con no delante del verbo", "Nacionalidades en minúscula"],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe tu perfil para el tablón del intercambio de idiomas de Guadalajara.",
    context: "Los perfiles de la lectura son tu modelo. Los organizadores necesitan saber de dónde eres, qué idiomas hablas y un dato de contacto.",
    steps: [
      "Saluda y di tu nombre.",
      "Di de dónde eres: ciudad, país y nacionalidad.",
      "Di qué idiomas hablas (y si hablas un poco de alguno).",
      "Añade una frase con **no** (por ejemplo, de dónde no eres o qué no hablas).",
      "Termina con un número de mesa o de teléfono, en palabras.",
    ],
    useLanguage: ["Soy de… / Soy + nacionalidad", "Hablo… e inglés / y…", "un poco de…", "No soy… / No hablo…", "Somos… (si escribes con otra persona)", "números del 0 al 20"],
    model: [
      "¡Hola! Me llamo Sam. Soy estadounidense, de Denver. Hablo inglés y un poco de español. No hablo francés. Mi amiga Jun y yo somos estudiantes. Ella es china, de Shanghái. Somos de la mesa once. ¡Hasta el jueves!",
    ],
    checklist: [
      "La nacionalidad concuerda contigo (masculino o femenino) y va en minúscula.",
      "Usas _de_ con el lugar, no con la nacionalidad.",
      "Hay al menos una frase con **no** delante del verbo.",
      "Si escribes _y_ delante de _inglés_ o _italiano_, cámbiala por **e**.",
      "El número está escrito en palabras y bien escrito (_dieciséis_, _catorce_…).",
    ],
    words: [25, 60],
  },
  speaking: {
    intro: "Habla sin leer. Prepara con las notas, tapa la pantalla y grábate. Después escucha y revisa la lista.",
    tasks: [
      {
        title: "¿De dónde eres?",
        prompt: "Preséntate como en la semana 1 y añade tu origen, tu nacionalidad y tus idiomas. Incluye una frase con **no**.",
        prep: ["Hola, me llamo… / Soy…", "Soy de [ciudad], [país]. Soy [nacionalidad].", "Hablo… y un poco de…", "No soy de… / No hablo…"],
        seconds: 30,
        model: "Hola, buenas tardes. Me llamo Hannah. Soy de Toronto, soy canadiense. Hablo inglés, francés y un poco de español. No hablo portugués. ¡Mucho gusto!",
        selfCheck: ["Digo la nacionalidad en masculino o femenino correctamente.", "El _no_ va delante del verbo.", "Las sílabas suenan regulares, sin comerme vocales."],
      },
      {
        title: "Tu número, claro y lento",
        prompt: "Imagina que hablas con Lupita en la recepción. Di tu número de teléfono (real o inventado) dos veces: primero cifra por cifra, después en grupos hasta el 20.",
        prep: ["Mi número es el…", "cifra por cifra: tres, tres, uno…", "en grupos: seis, quince, doce…", "¿Lo repito?"],
        seconds: 25,
        model: "Mi número es el seis, cuatro, cero, uno, uno, ocho, dos, nueve, siete. Otra vez, en grupos: seis, cuatro, cero… once… ocho, dos… nueve, siete. ¿Lo repito?",
        selfCheck: ["Digo _catorce_, _quince_, _dieciséis_ sin dudar.", "Hago una pequeña pausa entre los grupos."],
      },
      {
        title: "Presenta a otras personas",
        prompt: "Piensa en dos amigos o familiares de otros países (reales o inventados). Preséntalos: quiénes son, de dónde son, qué hablan. Usa _son_ y _somos_.",
        prep: ["Ellos son… y …", "Son de… Son [nacionalidad en plural].", "Hablan…", "Yo no soy de…, soy de…"],
        seconds: 30,
        model: "Ellas son Ana y Rocío. Son españolas, de Valencia. Hablan español y valenciano. Yo no soy española, soy irlandesa. Somos amigas.",
        selfCheck: ["El plural de la nacionalidad es correcto.", "Uso **son** para ellos/ellas y **somos** para nosotros."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo, intercambia datos reales con tu profesor o profesora.",
    cards: [
      { move: "Cuéntale", task: "Di tu presentación con origen e idiomas, sin leer.", phrases: ["Soy de…, soy…", "Hablo… e inglés", "No soy de…"] },
      { move: "Pregúntale", task: "Pregunta de dónde es y qué idiomas habla. Elige tú o usted y mantenlo.", phrases: ["¿De dónde eres? / ¿De dónde es usted?", "¿Qué idiomas hablas?"] },
      { move: "Dicta", task: "Dicta un número de teléfono inventado. Tu profesor lo escribe. Después comprueba si es correcto.", phrases: ["Es el…", "¿Puedes repetir, por favor?", "Sí, eso es. / No, es el catorce."] },
      { move: "Corrige", task: "Tu profesor dice tres frases falsas sobre ti (_Eres francés, ¿verdad?_). Corrige cada una con **no**.", phrases: ["No, no soy…, soy…", "No, no hablo…"] },
    ],
    bring: "Ten preparado un número de teléfono inventado de nueve o diez cifras para dictarlo.",
  },
  quiz: {
    items: [
      { type: "choice", q: "Tu amiga y tú están en Guadalajara. Una persona pregunta de dónde son. Respondes:", options: ["Somos de Irlanda.", "Son de Irlanda.", "Sois de Irlanda."], answer: 0, why: "Hablas por ti y tu amiga: nosotros → **somos**." },
      { type: "choice", q: "¿Cuál es la forma femenina de _alemán_?", options: ["alemana", "alemán", "alemána"], answer: 0, why: "Consonante + **a**, y sin tilde: alemana." },
      { type: "listen", q: "Escucha el número de la habitación de Sofía. ¿Cuál es?", audio: "La habitación de Sofía es la diecisiete.", options: ["17", "7", "16"], answer: 0, why: "_Diecisiete_ = 17." },
      { type: "listen", q: "¿De dónde es la persona que habla?", audio: "Hola, soy Valentina. No soy chilena, soy uruguaya, de Montevideo.", options: ["de Uruguay", "de Chile", "de Paraguay"], answer: 0, why: "_No soy chilena, soy uruguaya_." },
      { type: "gap", q: "—¿Vosotras ___ de Barcelona? —No, ___ de Bilbao.", answers: [["sois"], ["somos"]], why: "Vosotras → **sois**; la respuesta es por el grupo: **somos**." },
      { type: "gap", q: "Lucas y Marie ___ franceses. ___ hablan español.", answers: [["son"], ["No", "no"]], hint: "ser / negación", why: "Ellos **son**; negación: **No** hablan español." },
      { type: "transform", source: "Tomás es portugués.", instruction: "Habla de Ana y Sara.", answers: ["Ana y Sara son portuguesas."], why: "Es → **son**; portugués → **portuguesas** (femenino plural, sin tilde)." },
      { type: "order", words: ["Ustedes", "no", "son", "de", "aquí,", "¿verdad?"], why: "Sujeto + **no** + verbo." },
      { type: "error", sentence: "Ellas son inglésas.", answers: ["Ellas son inglesas."], why: "_Inglesas_ no lleva tilde: in-gle-sas es palabra llana." },
      { type: "error", sentence: "Tú eres no mexicana, ¿verdad?", answers: ["Tú no eres mexicana, ¿verdad?", "No eres mexicana, ¿verdad?"], why: "**No** va delante del verbo: _no eres_." },
      { type: "error", sentence: "Usted son de Cuba, ¿verdad?", answers: ["Usted es de Cuba, ¿verdad?", "¿Usted es de Cuba, verdad?"], why: "_Usted_ (una persona) va con **es**; _son_ es para _ustedes_." },
      { type: "open", prompt: "Escribe tres frases sobre ti: de dónde eres, qué idiomas hablas y una cosa que **no** eres.", model: "Soy de Manchester, soy inglés. Hablo inglés y un poco de español. No soy estudiante.", checklist: ["Soy de + lugar", "Nacionalidad bien concordada", "Hablo…", "No + verbo"] },
    ],
  },
  complete: {
    canNow: [
      "Usar el verbo **ser** con todas las personas, y reconocer _vosotros_ y _ustedes_.",
      "Negar una frase con **no** delante del verbo.",
      "Decir nacionalidades en masculino, femenino y plural.",
      "Preguntar y decir de dónde eres y qué idiomas hablas.",
      "Decir y entender números del 0 al 20, también en un teléfono.",
      "Dividir palabras en sílabas y pronunciarlas con ritmo regular.",
    ],
    review: [
      "Somos / sois / son.",
      "No + verbo (y _no me llamo_).",
      "Francés → francesa, inglés → ingleses: la tilde desaparece.",
      "Once, doce, trece, catorce, quince, dieciséis.",
      "Y → **e** delante de _i_: español e inglés.",
    ],
  },
  related: [
    { path: "/la-central-de-las-identidades", label: "La Central de las Identidades · pronombres" },
    { path: "/clase/202", label: "El ritmo de las palabras" },
  ],
};
