import type { Module } from "../../types";

export const a1w07: Module = {
  id: "a1-07",
  level: "a1",
  week: 7,
  kind: "core",
  title: "¿Qué comes?",
  subtitle: "Hablar de comidas, bebidas y hábitos con los verbos en -er e -ir y los adverbios de frecuencia.",
  stop: { place: "Puebla", country: "México" },
  minutes: 75,
  newObjectives: [
    "a1.gram.presente-er-ir",
    "a1.gram.frecuencia",
    "a1.voc.comidas-bebidas",
    "a1.pron.b-v",
    "a1.fun.habitos",
    "a1.lis.entrevista-habitos",
  ],
  reviewObjectives: ["a1.gram.tener", "a1.gram.posesivos", "a1.gram.concordancia-adjetivo", "a1.gram.presente-ar"],
  prerequisites: ["a1-06"],
  goal: {
    canDo: "Al final de esta semana puedes describir qué comes y bebes normalmente, decir con qué frecuencia lo haces y preguntar por los hábitos de otra persona.",
    canDoEn: "By the end of this week, you can describe what you usually eat and drink, say how often you do things and ask about other people's habits.",
    steps: [
      "Aprende el presente de los verbos regulares en **-er** e **-ir**: como, bebo, vivo, escribo.",
      "Di con qué frecuencia haces algo: **siempre, a veces, nunca**… y la doble negación.",
      "Aprende comidas y bebidas, con sus variantes: **jugo / zumo**, **frijoles / porotos**.",
      "Descubre por qué la **b** y la **v** suenan igual.",
      "Escucha una encuesta de hábitos en el centro de Puebla.",
      "Cuenta tus hábitos en voz alta y por escrito.",
    ],
  },
  theory: {
    intro: "Ya conjugas los verbos en **-ar** (semana 4). Esta semana completas el sistema regular del presente con los verbos en **-er** e **-ir**, y aprendes a decir con qué frecuencia haces las cosas: la base para hablar de tus hábitos.",
    parts: [
      {
        heading: "Verbos en -er e -ir: casi iguales",
        body: [
          "El sistema es el mismo que en -ar: quitas **-er** o **-ir** y añades la terminación. La vocal típica ahora es la **e**: com**o**, com**es**, com**e**, com**en**.",
          "Los verbos en **-er** y en **-ir** solo son diferentes en **nosotros** y **vosotros**: com**emos** / viv**imos**, com**éis** / viv**ís**. En todas las demás personas son iguales: com**e** / viv**e**.",
          "Verbos frecuentes en -er: **comer, beber, leer, aprender, vender, comprender, correr**. En -ir: **vivir, escribir, compartir, abrir, recibir, subir**.",
          "Con **vos** la terminación lleva tilde: **vos comés**, **vos vivís**. En América, **beber** se usa, pero para las bebidas es muy frecuente **tomar** (verbo en -ar): _¿Qué tomas?_",
        ],
        support: [
          "-er and -ir verbs share the same endings except for _nosotros_ (-emos / -imos) and _vosotros_ (-éis / -ís).",
          "Compare with -ar verbs: the 'a' endings (-as, -a, -an) become 'e' endings (-es, -e, -en). _Habla_ → _come_, _vive_.",
        ],
        table: {
          caption: "Tres modelos del presente regular",
          head: ["Persona", "tomar (-ar)", "comer (-er)", "vivir (-ir)"],
          rows: [
            ["yo", "tomo", "como", "vivo"],
            ["tú / vos", "tomas / tomás", "comes / comés", "vives / vivís"],
            ["usted, él, ella", "toma", "come", "vive"],
            ["nosotros, nosotras", "tomamos", "comemos", "vivimos"],
            ["vosotros, vosotras", "tomáis", "coméis", "vivís"],
            ["ustedes, ellos, ellas", "toman", "comen", "viven"],
          ],
        },
        examples: [
          { es: "Mis padres viven en Puebla y comen en casa todos los días.", en: "My parents live in Puebla and eat at home every day." },
          { es: "Nosotros compartimos una pizza y bebemos agua.", en: "We share a pizza and drink water." },
          { es: "¿Lees en el desayuno?", en: "Do you read at breakfast?" },
        ],
        mistakes: [
          { wrong: "Nosotros vivemos en Puebla.", right: "Nosotros vivimos en Puebla.", why: "En nosotros, los verbos en -ir terminan en **-imos**." },
          { wrong: "Ella comé pan.", right: "Ella come pan.", why: "La forma de ella no lleva tilde: **come**. La tilde es para _vos comés_." },
          { wrong: "Ellos escriban mensajes.", right: "Ellos escriben mensajes.", why: "Verbo en -ir: la terminación es **-en**, no _-an_." },
        ],
      },
      {
        heading: "¿Con qué frecuencia?",
        body: [
          "Para decir cuántas veces haces algo, usa una escala: **siempre** → **casi siempre** → **normalmente** → **a menudo / muchas veces** → **a veces** → **casi nunca** → **nunca**.",
          "También puedes ser exacto: **todos los días**, **todas las mañanas**, **una vez a la semana**, **dos veces al mes**. Fíjate en la concordancia: tod**os** los días, tod**as** las mañanas.",
          "La mayoría de estas expresiones van delante del verbo o al final de la frase: **Siempre desayuno café** / **Desayuno café siempre**. **Todos los días** y **una vez a la semana** suelen ir al final o al principio: **Como fruta todos los días.**",
          "**Nunca** tiene una regla especial. Delante del verbo va solo: **Nunca bebo café.** Detrás del verbo necesita **no** delante: **No bebo nunca café.** Es la doble negación: en español es correcta y obligatoria.",
        ],
        support: [
          "_Nunca_ before the verb = no extra _no_. _Nunca_ after the verb = you need _no_ before the verb: _No como nunca carne_. Two negatives are correct in Spanish.",
          "Never say _Nunca no como_: when _nunca_ comes first, it does the negative job alone.",
        ],
        table: {
          caption: "La escala de frecuencia",
          head: ["Frecuencia", "Expresión", "Ejemplo"],
          rows: [
            ["100 %", "siempre / todos los días", "Siempre desayuno en casa."],
            ["≈ 80 %", "casi siempre / normalmente", "Normalmente ceno con mi familia."],
            ["≈ 60 %", "a menudo / muchas veces", "Como tortillas a menudo."],
            ["≈ 30 %", "a veces / de vez en cuando", "A veces bebo refresco."],
            ["≈ 5 %", "casi nunca", "Casi nunca como carne."],
            ["0 %", "nunca / no… nunca", "Nunca cocino. · No cocino nunca."],
          ],
        },
        examples: [
          { es: "Leo el periódico una vez a la semana.", en: "I read the newspaper once a week." },
          { es: "Mi hermana no bebe nunca leche.", en: "My sister never drinks milk." },
          { es: "—¿Con qué frecuencia comes pescado? —Dos veces al mes.", en: "How often do you eat fish? — Twice a month." },
        ],
        mistakes: [
          { wrong: "Nunca no como carne.", right: "Nunca como carne. / No como nunca carne.", why: "Si _nunca_ va delante, no necesita _no_." },
          { wrong: "Como nunca carne.", right: "No como nunca carne.", why: "Si _nunca_ va detrás del verbo, el verbo necesita **no** delante." },
          { wrong: "Todas los días desayuno fruta.", right: "Todos los días desayuno fruta.", why: "_Días_ es masculino: **todos** los días." },
        ],
        tip: "Una respuesta corta también es natural: —¿Bebes café? —**Nunca.** / —**A veces.** No hace falta repetir el verbo.",
      },
      {
        heading: "Las comidas del día y sus nombres",
        body: [
          "En casi todo el mundo hispanohablante hay tres comidas principales: el **desayuno** (por la mañana), la **comida** o el **almuerzo** (al mediodía o por la tarde) y la **cena** (por la noche). Los verbos son regulares en -ar: **desayunar**, **cenar**.",
          "Los nombres cambian según el país. En muchos países de América, **el almuerzo** es la comida del mediodía. En España se dice más **la comida**. En México, **la comida** es la comida fuerte de la tarde y **el almuerzo** puede ser un desayuno tarde, a media mañana.",
          "Muchos alimentos tienen variantes regionales: **jugo** (América) / **zumo** (España); **papa** (América, Canarias) / **patata** (España); **frijoles** (México, Centroamérica) / **porotos** (Cono Sur) / **caraotas** (Venezuela). Atención: una **torta** en México es un sándwich; en otros países, un pastel dulce.",
        ],
        support: [
          "Meal names vary: _almuerzo_ is lunch in much of Latin America, a late breakfast in Mexico and a mid-morning snack in parts of Spain. _La comida_ is both 'food' and 'the main midday/afternoon meal'.",
          "You don't need to learn every variant: use one, recognise the others.",
        ],
        examples: [
          { es: "Desayuno café con leche y pan dulce.", en: "I have coffee with milk and sweet bread for breakfast." },
          { es: "En mi casa cenamos tortillas con frijoles.", en: "At home we have tortillas with beans for dinner." },
          { es: "Un jugo de naranja, por favor. (En España: un zumo de naranja.)", en: "An orange juice, please." },
        ],
        mistakes: [
          { wrong: "Desayuno en la cena.", right: "Ceno… / Desayuno…", why: "_Desayunar_ y _cenar_ ya incluyen el momento: **desayuno café**, **ceno sopa**." },
        ],
      },
    ],
  },
  grammar: {
    intro: "Primero las formas, luego la frecuencia y, al final, las dos cosas juntas.",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "Las terminaciones",
        prompt: "Elige la forma correcta.",
        items: [
          { q: "Mi hermana y yo ___ en el centro de Puebla.", options: ["vivimos", "vivemos", "viven"], answer: 0, why: "Nosotras + verbo en -ir → **vivimos**." },
          { q: "¿Tú ___ café o té por la mañana?", options: ["bebes", "bebas", "bebe"], answer: 0, why: "Tú + verbo en -er → **bebes**." },
          { q: "Mis abuelos ___ cartas a mano.", options: ["escribían", "escriben", "escribin"], answer: 1, why: "Ellos + -ir → **escriben** (igual que -er)." },
          { q: "Vosotros ___ mucho español en clase.", options: ["aprendéis", "aprendís", "aprenden"], answer: 0, why: "Vosotros + -er → **-éis**: aprend**éis**." },
          { q: "—¿Vos ___ carne? —No, soy vegetariano.", options: ["comés", "comes", "comís"], answer: 0, why: "Vos + -er → **comés**, con tilde." },
        ],
      },
      {
        id: "g2",
        type: "gap",
        title: "En casa de los Hernández",
        prompt: "Completa con el verbo en presente.",
        items: [
          { q: "La señora Hernández ___ (vender) chalupas en el mercado.", answers: [["vende"]], why: "Ella + -er → vend**e**." },
          { q: "Sus hijos ___ (abrir) la tienda los sábados.", answers: [["abren"]], why: "Ellos + -ir → abr**en**." },
          { q: "Nosotros ___ (compartir) la cena con los vecinos.", answers: [["compartimos"]], why: "Nosotros + -ir → compart**imos**." },
          { q: "Yo ___ (leer) recetas en internet.", answers: [["leo"]], why: "Yo → le**o**." },
          { q: "¿Ustedes ___ (recibir) muchas visitas en Navidad?", answers: [["reciben"]], why: "Ustedes + -ir → recib**en**." },
          { q: "Mi padre ___ (cocinar) y mi madre ___ (lavar) los platos.", answers: [["cocina"], ["lava"]], why: "Repaso de -ar: cocin**a**, lav**a**. Fíjate: en -ar la vocal es **a**, en -er/-ir es **e**." },
        ],
      },
      {
        id: "g3",
        type: "transform",
        title: "Nunca, de dos maneras",
        prompt: "Escribe la frase con **nunca** detrás del verbo (doble negación).",
        items: [
          { source: "Nunca bebo refresco.", answers: ["No bebo nunca refresco.", "No bebo refresco nunca."], why: "_Nunca_ detrás del verbo → **no** delante del verbo." },
          { source: "Mi hijo nunca come verduras.", answers: ["Mi hijo no come nunca verduras.", "Mi hijo no come verduras nunca."], why: "**No** + verbo + **nunca**." },
          { source: "Nunca cenamos tarde.", answers: ["No cenamos nunca tarde.", "No cenamos tarde nunca."], why: "La doble negación es correcta y obligatoria en esta posición." },
        ],
      },
      {
        id: "g4",
        type: "order",
        title: "¿Dónde va la frecuencia?",
        prompt: "Ordena las palabras.",
        items: [
          { words: ["Casi", "siempre", "desayuno", "fruta."], alt: ["Desayuno fruta casi siempre."], en: "I almost always have fruit for breakfast.", why: "_Casi siempre_ va normalmente delante del verbo." },
          { words: ["Mis", "amigos", "no", "cocinan", "nunca."], en: "My friends never cook.", why: "_Nunca_ al final → **no** delante del verbo." },
          { words: ["Comemos", "mole", "dos", "veces", "al", "año."], alt: ["Dos veces al año comemos mole."], en: "We eat mole twice a year.", why: "Las expresiones exactas (_dos veces al año_) van al final o al principio." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Aprende la comida en combinaciones reales —**café con leche**, **pan con queso**— y no en listas sueltas.",
    groups: [
      {
        title: "Las comidas del día",
        items: [
          { es: "el desayuno · desayunar", en: "breakfast · to have breakfast" },
          { es: "la comida / el almuerzo", en: "lunch, the main midday meal (varies by country)" },
          { es: "la merienda", en: "afternoon snack" },
          { es: "la cena · cenar", en: "dinner · to have dinner" },
          { es: "comer en casa / fuera", en: "to eat at home / out" },
        ],
      },
      {
        title: "Para comer",
        items: [
          { es: "pan con mantequilla", en: "bread and butter" },
          { es: "huevos con jamón", en: "eggs with ham" },
          { es: "fruta: plátano, naranja, manzana", en: "fruit: banana, orange, apple" },
          { es: "verduras y ensalada", en: "vegetables and salad" },
          { es: "arroz con pollo", en: "rice with chicken" },
          { es: "carne / pescado", en: "meat / fish" },
          { es: "tortillas de maíz", en: "corn tortillas" },
          { es: "frijoles (porotos en el Cono Sur)", en: "beans" },
          { es: "papas (patatas en España)", en: "potatoes" },
          { es: "queso", en: "cheese" },
          { es: "sopa", en: "soup" },
          { es: "un pan dulce / un pastel", en: "a sweet bun / a cake" },
        ],
      },
      {
        title: "Para beber",
        items: [
          { es: "un vaso de agua", en: "a glass of water" },
          { es: "un café con leche / un café solo", en: "a white coffee / a black coffee" },
          { es: "una taza de té", en: "a cup of tea" },
          { es: "un jugo de naranja (zumo en España)", en: "an orange juice" },
          { es: "un refresco", en: "a soft drink" },
          { es: "una cerveza / una copa de vino", en: "a beer / a glass of wine" },
        ],
      },
      {
        title: "Hablar de hábitos",
        items: [
          { es: "¿Qué desayunas normalmente?", en: "What do you usually have for breakfast?" },
          { es: "¿Con qué frecuencia comes fuera?", en: "How often do you eat out?" },
          { es: "Soy vegetariano / vegetariana.", en: "I'm vegetarian." },
          { es: "una vez a la semana", en: "once a week" },
          { es: "de vez en cuando", en: "from time to time" },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "Misma comida, otra palabra",
        prompt: "Une la palabra de México con la variante de otro país.",
        pairs: [
          { left: "jugo (México)", right: "zumo (España)" },
          { left: "frijoles (México)", right: "porotos (Argentina, Chile)" },
          { left: "papas (México)", right: "patatas (España)" },
          { left: "torta (México)", right: "sándwich o bocadillo (otros países)" },
          { left: "pastel (México)", right: "tarta (España)" },
        ],
        why: "Son la misma comida con nombres distintos. Elige una forma para hablar y reconoce las demás.",
      },
      {
        id: "v2",
        type: "gap",
        title: "Combinaciones naturales",
        prompt: "Completa con una palabra del banco.",
        bank: ["vaso", "taza", "leche", "pollo", "naranja"],
        items: [
          { q: "Por la mañana tomo un café con ___.", answers: [["leche"]], why: "_Café con leche_: combinación fija y muy frecuente." },
          { q: "Con la comida bebo un ___ de agua.", answers: [["vaso"]], why: "El agua se bebe en un **vaso**." },
          { q: "Por la tarde tomo una ___ de té.", answers: [["taza"]], why: "Té y café caliente: **una taza**." },
          { q: "Los domingos comemos arroz con ___.", answers: [["pollo"]], why: "_Arroz con pollo_: plato típico en muchos países." },
          { q: "Un jugo de ___, por favor.", answers: [["naranja"]], why: "El jugo más común: **de naranja**." },
        ],
      },
      {
        id: "v3",
        type: "classify",
        title: "¿Para comer o para beber?",
        prompt: "Clasifica cada palabra.",
        categories: ["se come", "se bebe"],
        items: [
          { text: "una copa de vino", cat: 1 },
          { text: "chilaquiles", cat: 0, why: "Plato mexicano de tortillas fritas con salsa." },
          { text: "un refresco", cat: 1 },
          { text: "una sopa", cat: 0, why: "Aunque es líquida, en español la sopa **se come**, con cuchara." },
          { text: "un café de olla", cat: 1, why: "Café mexicano preparado con canela." },
          { text: "una cemita", cat: 0, why: "El sándwich típico de Puebla." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "B y V: un solo sonido",
    explanation: [
      "En español moderno, la **b** y la **v** se pronuncian exactamente igual. _Vino_ y _bino_ sonarían idénticos: la diferencia es solo de ortografía. No pronuncies la **v** con los dientes sobre el labio, como en inglés.",
      "Ese único sonido tiene dos variantes según la posición. Después de una pausa y después de **m** o **n**, los labios se cierran del todo: es una **[b] fuerte**, como en _**V**ino, por favor_, _u**n v**aso_, _ta**mb**ién_.",
      "En las demás posiciones —sobre todo entre vocales— los labios casi se tocan, pero no se cierran: es una **[β] suave**, como en _la **v**erdura_, _be**b**o_, _Cu**b**a_. El aire pasa entre los labios.",
      "Lo importante: la variante depende de la **posición**, no de la letra. La misma palabra cambia: _**v**aso_ (fuerte, al principio) → _el **v**aso_ (suave).",
    ],
    support: [
      "B and V are the same sound in Spanish. Never use the English lip-teeth V.",
      "After a pause and after m/n: lips fully closed [b]. Elsewhere, especially between vowels: lips almost closed [β], a soft sound.",
    ],
    table: {
      head: ["Posición", "Sonido", "Ejemplos"],
      rows: [
        ["después de pausa", "[b] fuerte", "¡Vino! · Bebo agua."],
        ["después de m, n", "[b] fuerte", "un vaso, con verduras, también, hambre"],
        ["entre vocales", "[β] suave", "la verdura, Cuba, pavo, una vez"],
        ["después de otras consonantes", "[β] suave", "el vaso, los sábados"],
      ],
    },
    perceive: {
      id: "p1",
      type: "classify",
      title: "¿Fuerte o suave?",
      prompt: "Escucha. Cada frase tiene una sola **b** o **v**. ¿Los labios se cierran del todo (fuerte) o casi se tocan (suave)?",
      categories: ["[b] fuerte", "[β] suave"],
      items: [
        { text: "Vino tinto, por favor.", audio: "Vino tinto, por favor.", voice: "es-MX-m", cat: 0, why: "Al principio, después de pausa: **fuerte**." },
        { text: "un vaso de agua", audio: "un vaso de agua", voice: "es-CO-f", cat: 0, why: "Después de **n**: fuerte (se pronuncia «umbaso»)." },
        { text: "con verduras", audio: "Arroz con verduras.", voice: "es-ES-f", cat: 0, why: "Después de **n**: fuerte." },
        { text: "la verdura", audio: "la verdura", voice: "es-MX-f", cat: 1, why: "Entre vocales (la_**v**erdura): suave." },
        { text: "una vez a la semana", audio: "una vez a la semana", voice: "es-AR-m", cat: 1, why: "Entre vocales: suave." },
        { text: "café de Cuba", audio: "café de Cuba", voice: "es-CU-m", cat: 1, why: "Cu**b**a: entre vocales, suave." },
        { text: "Tengo hambre.", audio: "Tengo hambre.", voice: "es-PE-f", cat: 0, why: "Después de **m**: fuerte." },
        { text: "los sábados", audio: "los sábados", voice: "es-CL-f", cat: 1, why: "Entre vocales (sá-**b**a-dos): suave." },
      ],
    },
    produce: [
      { text: "Bebo vino.", tip: "La primera **b** es fuerte (después de pausa); las otras dos, entre vocales, son suaves: no cierres los labios del todo." },
      { text: "Un vaso de vino blanco, por favor.", tip: "_Un vaso_ → «umbaso»: la **n** se convierte casi en **m** y la **v** es fuerte. _De vino_: suave." },
      { text: "También bebo jugo de vez en cuando.", tip: "_Tam**b**ién_: fuerte después de **m**. _De **v**ez_: suave, entre vocales." },
      { text: "Nunca cenamos verduras los sábados.", tip: "_Cenamos **v**erduras_: después de **s**, suave. Ninguna **v** con los dientes." },
      { text: "En Puebla bebemos café de olla.", tip: "_En **P**uebla_ es otra letra; en _be**b**emos_, la segunda **b** es suave." },
    ],
    spelling: "Como suenan igual, la **b** y la **v** se aprenden con la palabra escrita. Dos pistas: después de **m** siempre se escribe **b** (_también, hambre_) y después de **n** siempre **v** (_invitar, enviar_). Las terminaciones **-aba** del pasado y las palabras con **bl, br** llevan **b**.",
  },
  listening: {
    title: "Encuesta en el zócalo de Puebla",
    context: "Andrea es estudiante de periodismo y trabaja para la radio de la universidad. En el zócalo de Puebla hace una encuesta breve: «¿Cómo comen los poblanos?». Escucha a las tres personas que responden.",
    speakers: [
      { id: "andrea", name: "Andrea", voice: "es-MX-f", role: "periodista de la radio" },
      { id: "julio", name: "Don Julio", voice: "es-MX-m", role: "jubilado de Puebla" },
      { id: "valentina", name: "Valentina", voice: "es-CL-f", role: "estudiante chilena" },
      { id: "ruben", name: "Rubén", voice: "es-VE-m", role: "cocinero venezolano" },
    ],
    script: [
      { speaker: "andrea", text: "Buenas tardes, señor. Soy Andrea, de Radio Universidad. Es una encuesta sobre los hábitos de comida en Puebla. ¿Tiene un minuto?" },
      { speaker: "julio", text: "Sí, claro, señorita. Soy Julio." },
      { speaker: "andrea", text: "Don Julio, ¿qué desayuna usted normalmente?" },
      { speaker: "julio", text: "Siempre desayuno café de olla y pan dulce. Y los domingos, chilaquiles con mi esposa." },
      { speaker: "andrea", text: "¿Y come mole poblano a menudo?" },
      { speaker: "julio", text: "¡Claro! Pero no todos los días: una o dos veces al mes, en las fiestas de la familia." },
      { speaker: "andrea", text: "Gracias, don Julio. Y tú, ¿cómo te llamas?" },
      { speaker: "valentina", text: "Valentina. Soy chilena, pero vivo en Puebla: estudio arquitectura aquí." },
      { speaker: "andrea", text: "¿Comes en casa o en la universidad?" },
      { speaker: "valentina", text: "Normalmente como en la cafetería de la universidad. Casi nunca cocino: no tengo tiempo." },
      { speaker: "andrea", text: "¿Y qué bebes?" },
      { speaker: "valentina", text: "Agua, todo el día. A veces un jugo. Y no tomo nunca café. ¡Es raro para una estudiante!" },
      { speaker: "ruben", text: "Yo soy Rubén. Soy venezolano y soy cocinero en un restaurante de la calle Cinco de Mayo. Como en el restaurante todos los días, con mis compañeros." },
      { speaker: "andrea", text: "¿Y qué cenas, Rubén?" },
      { speaker: "ruben", text: "Casi siempre una arepa con queso, como en Venezuela. Y no como carne: soy vegetariano. Como frijoles, huevos y verduras." },
      { speaker: "andrea", text: "¡Muchas gracias a los tres! Y a ustedes, en la radio: ¿qué comen hoy?" },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: la idea general.",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha todo una vez y responde.",
          items: [
            { q: "¿Cuántas personas responden a la encuesta?", options: ["dos", "tres", "cuatro"], answer: 1, why: "Don Julio, Valentina y Rubén. Andrea hace las preguntas." },
            { q: "¿De qué trata la encuesta?", options: ["de los hábitos de comida", "de los precios de los restaurantes", "de las fiestas de Puebla"], answer: 0 },
            { q: "¿Con quién habla Andrea de usted?", options: ["con don Julio", "con Valentina", "con Rubén"], answer: 0, why: "_¿Qué desayuna usted?_ Don Julio es un señor mayor; con los jóvenes usa tú." },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: qué come y bebe cada persona, y con qué frecuencia.",
        exercise: {
          id: "l2",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "¿Qué desayuna don Julio todos los días?", options: ["chilaquiles", "café de olla y pan dulce", "una arepa con queso"], answer: 1, why: "Los chilaquiles son solo **los domingos**." },
            { q: "¿Con qué frecuencia come mole don Julio?", options: ["todos los días", "una o dos veces al mes", "una vez al año"], answer: 1 },
            { q: "¿Dónde come Valentina normalmente?", options: ["en casa", "en la cafetería de la universidad", "en un restaurante"], answer: 1 },
            { q: "¿Qué no bebe nunca Valentina?", options: ["agua", "jugo", "café"], answer: 2, why: "_No tomo nunca café._" },
            { q: "¿Por qué Rubén no come carne?", options: ["Es vegetariano.", "No tiene tiempo.", "Es muy cara."], answer: 0 },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en las expresiones de frecuencia.",
        exercise: {
          id: "l3",
          type: "classify",
          prompt: "Clasifica cada expresión que oyes según la frecuencia.",
          categories: ["mucho (casi todos los días)", "a veces", "nunca o casi nunca"],
          items: [
            { text: "Siempre desayuno café de olla.", cat: 0 },
            { text: "una o dos veces al mes", cat: 1 },
            { text: "Normalmente como en la cafetería.", cat: 0 },
            { text: "Casi nunca cocino.", cat: 2 },
            { text: "A veces un jugo.", cat: 1 },
            { text: "No tomo nunca café.", cat: 2, why: "Doble negación: **no** + verbo + **nunca**." },
            { text: "Como en el restaurante todos los días.", cat: 0 },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Una semana en la mesa de los Hernández",
    genre: "Entrada de blog",
    frame: "Lena es alemana y vive con una familia en Puebla durante su intercambio. En su blog escribe sobre la comida de su nueva casa.",
    text: [
      "Vivo con la familia Hernández desde hace un mes y mi vida es completamente diferente… sobre todo en la mesa. Aquí van mis observaciones.",
      "**El desayuno.** En Alemania desayuno pan con queso. Aquí, la señora Hernández —Lupe— prepara huevos con salsa verde, frijoles y tortillas calientes casi todos los días. Su marido, don Arturo, nunca desayuna sin un café de olla.",
      "**La comida.** La comida fuerte es por la tarde, no al mediodía. Comemos todos juntos: sopa, arroz y un plato principal. Los domingos visitamos a la abuela, que vive en Cholula, y ella siempre cocina mole poblano. ¡Es una salsa con más de veinte ingredientes, incluido chocolate!",
      "**La cena.** Por la noche la cena es ligera: un pan dulce, una fruta o un vaso de leche. Mis hermanos anfitriones, Diego y Paola, a veces comen tacos en la calle con sus amigos.",
      "**Mi problema.** La comida es deliciosa, pero un poco picante para mí. Lupe siempre pregunta: «¿Pica?». Y yo siempre respondo: «No, no, ¡es deliciosa!». No es verdad, pero aprendo rápido 🌶️.",
    ],
    glossary: [
      { es: "desde hace un mes", en: "for a month (and still now)" },
      { es: "caliente", en: "hot (temperature)" },
      { es: "ligero, ligera", en: "light (meal)" },
      { es: "picante / ¿pica?", en: "spicy / is it spicy?" },
      { es: "anfitrión, anfitriona", en: "host" },
      { es: "incluido", en: "including" },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee el blog y responde.",
        items: [
          { q: "¿Qué desayuna Lena en Alemania?", options: ["huevos con salsa", "pan con queso", "café de olla"], answer: 1 },
          { q: "¿Cuándo es la comida fuerte en Puebla, según Lena?", options: ["por la mañana", "al mediodía", "por la tarde"], answer: 2 },
          { q: "¿Quién cocina mole los domingos?", options: ["Lupe", "la abuela", "don Arturo"], answer: 1, why: "_Los domingos visitamos a la abuela… y ella siempre cocina mole poblano._" },
          { q: "¿Qué problema tiene Lena con la comida?", options: ["Es un poco picante para ella.", "No es deliciosa.", "Es muy cara."], answer: 0 },
        ],
      },
      {
        id: "r2",
        type: "classify",
        prompt: "¿Verdadero o falso según el texto?",
        categories: ["Verdadero", "Falso"],
        items: [
          { text: "Don Arturo desayuna café de olla todos los días.", cat: 0, why: "_Nunca desayuna sin un café de olla_ = siempre lo toma." },
          { text: "La cena de los Hernández es grande.", cat: 1, why: "_Por la noche la cena es ligera._" },
          { text: "Diego y Paola son los hermanos de Lena.", cat: 1, why: "Son sus **hermanos anfitriones**: los hijos de la familia que la recibe." },
          { text: "El mole tiene chocolate.", cat: 0 },
          { text: "Lena dice siempre la verdad sobre el picante.", cat: 1, why: "_No es verdad, pero aprendo rápido._" },
        ],
      },
    ],
    noticing: {
      prompt: "Toca cada fragmento: la gramática de esta semana y de la anterior.",
      items: [
        { quote: "Vivo con la familia Hernández", note: "Verbo en -ir, yo: viv**o**. Igual que en -ar y -er." },
        { quote: "nunca desayuna sin un café de olla", note: "_Nunca_ delante del verbo: sin _no_. _Desayunar_ es un verbo regular en -ar." },
        { quote: "tortillas calientes", note: "Concordancia: _caliente_ termina en -e, solo añade **-s** en plural." },
        { quote: "Su marido, don Arturo", note: "_Su_ = de ella (de Lupe). _Marido_ es la palabra frecuente en España; en México se dice más _esposo_, pero Lena es europea." },
        { quote: "a veces comen tacos en la calle con sus amigos", note: "Frecuencia (_a veces_) + verbo en -er, ellos: com**en**. _Sus_ amigos: varios amigos." },
      ],
    },
  },
  practice: {
    intro: "Combina verbos, frecuencia y comida. Recicla también tener, los posesivos y los verbos en -ar.",
    exercises: [
      {
        id: "x1",
        type: "error",
        title: "Errores en la mesa",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "Nosotros escribemos la lista de la compra.", answers: ["Nosotros escribimos la lista de la compra.", "Escribimos la lista de la compra."], why: "Verbo en -ir: nosotros → escrib**imos**." },
          { sentence: "Mi hijo nunca no bebe leche.", answers: ["Mi hijo nunca bebe leche.", "Mi hijo no bebe nunca leche.", "Mi hijo no bebe leche nunca."], why: "Con _nunca_ delante del verbo, sobra el _no_." },
          { sentence: "Valentina come nunca carne.", answers: ["Valentina no come nunca carne.", "Valentina nunca come carne.", "Valentina no come carne nunca."], why: "_Nunca_ detrás del verbo exige **no** delante." },
          { sentence: "Las tortillas de mi abuela son muy ricos.", answers: ["Las tortillas de mi abuela son muy ricas."], why: "Concordancia con _tortillas_ (femenino plural): ric**as**." },
          { sentence: "Mis amigos y yo comen tacos los viernes.", answers: ["Mis amigos y yo comemos tacos los viernes."], why: "_Mis amigos y yo_ = nosotros → com**emos**." },
        ],
      },
      {
        id: "x2",
        type: "transform",
        title: "Habla de otra persona",
        prompt: "Cambia la frase a la persona indicada.",
        items: [
          { source: "Desayuno fruta y bebo un café. (mi madre)", answers: ["Mi madre desayuna fruta y bebe un café."], why: "Desayun**a** (-ar) y beb**e** (-er): la vocal cambia según el grupo del verbo." },
          { source: "Vivo en Puebla y tengo un restaurante. (nosotros)", answers: ["Vivimos en Puebla y tenemos un restaurante.", "Nosotros vivimos en Puebla y tenemos un restaurante."], why: "Viv**imos** (-ir) y **tenemos**." },
          { source: "¿Lees el menú en español? (vosotros)", answers: ["¿Leéis el menú en español?", "¿Vosotros leéis el menú en español?"], why: "Vosotros + -er → le**éis**." },
          { source: "Mi hermano come fuera a menudo. (mis hermanos)", answers: ["Mis hermanos comen fuera a menudo."], why: "Ellos → com**en**; el posesivo pasa a **mis**." },
        ],
      },
      {
        id: "x3",
        type: "context",
        title: "Preguntas de una encuesta",
        prompt: "Elige la pregunta o la respuesta adecuada.",
        items: [
          { context: "Quieres saber cuántas veces come fuera tu compañero.", q: "Preguntas:", options: ["¿Con qué frecuencia comes fuera?", "¿Dónde comes fuera?", "¿Qué comes fuera?"], answer: 0, why: "Para la frecuencia: **¿Con qué frecuencia…?**" },
          { context: "Te preguntan: «¿Bebes refresco?». Lo bebes el sábado y el domingo.", q: "Respondes:", options: ["Sí, dos veces a la semana.", "Sí, todos los días.", "No, nunca."], answer: 0, why: "Sábado y domingo = **dos veces a la semana**." },
          { context: "Hablas con una señora mayor en una encuesta.", q: "Preguntas:", options: ["¿Qué desayuna usted normalmente?", "¿Qué desayunas normalmente?", "¿Qué desayunáis normalmente?"], answer: 0, why: "Persona mayor desconocida: **usted** + desayun**a**." },
          { context: "Tu amigo pregunta: «¿Comes carne?». Eres vegetariana.", q: "Respondes:", options: ["No, nunca. Soy vegetariana.", "No, siempre. Soy vegetariana.", "Sí, a veces. Soy vegetariana."], answer: 0, why: "Vegetariana → **nunca** come carne." },
        ],
      },
      {
        id: "x4",
        type: "gap",
        title: "Mi familia a la mesa",
        prompt: "Completa con la forma correcta del verbo (-ar, -er o -ir) o con el posesivo.",
        items: [
          { q: "En ___ casa (de nosotros) siempre ___ (cenar) juntos.", answers: [["nuestra"], ["cenamos"]], why: "**Nuestra** casa; cen**amos** (-ar)." },
          { q: "Mi padre ___ (tener) sesenta años y todavía ___ (correr) por la mañana.", answers: [["tiene"], ["corre"]], why: "**Tiene** (irregular); corr**e** (-er)." },
          { q: "Mis primas ___ (vivir) en Cholula y ___ (vender) pan.", answers: [["viven"], ["venden"]], why: "Ellas → viv**en**, vend**en**." },
          { q: "¿Tú ___ (compartir) piso con ___ hermano?", answers: [["compartes"], ["tu"]], why: "Tú → compart**es**; posesivo **tu** sin tilde." },
        ],
      },
      {
        id: "x5",
        type: "open",
        title: "Responde la encuesta",
        prompt: "Andrea envía la encuesta de la radio por escrito. Responde a cada pregunta con dos o tres frases.",
        items: [
          {
            prompt: "«¿Qué desayunas normalmente y dónde?»",
            model: "Normalmente desayuno en casa: un café con leche y pan con mantequilla. Los domingos desayuno huevos con mi familia.",
            checklist: ["Uso una expresión de frecuencia.", "Uso verbos en -ar o -er bien conjugados (desayuno, como, bebo).", "Uso combinaciones como _café con leche_."],
          },
          {
            prompt: "«¿Hay algo que no comes o no bebes nunca? ¿Por qué?»",
            model: "No bebo nunca refresco: no es sano. Y casi nunca como carne, pero como pescado una vez a la semana.",
            checklist: ["Uso _nunca_ bien: delante sin _no_, o detrás con _no_.", "Uso _casi nunca_ o _a veces_.", "Uso _pero_ para un contraste."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe un mensaje a tu futura familia anfitriona en Puebla y explica tus hábitos de comida.",
    context: "Vas a vivir un mes con una familia en Puebla. La madre, Lupe, pregunta por mensaje: «¿Qué comes normalmente? ¿Hay algo que no comes?».",
    steps: [
      "Saluda a Lupe y a su familia.",
      "Explica qué desayunas, comes y cenas normalmente, con expresiones de frecuencia.",
      "Di una cosa que no comes o no bebes nunca (con doble negación).",
      "Añade una cosa de tu familia: qué comen en tu casa.",
      "Termina con una pregunta sobre sus hábitos y una despedida.",
    ],
    useLanguage: [
      "Normalmente desayuno… / Casi siempre como…",
      "No como nunca… / Nunca bebo…",
      "a veces, una vez a la semana, de vez en cuando",
      "En mi casa (nosotros) comemos…",
      "¿Y ustedes qué…?",
    ],
    model: [
      "¡Hola, Lupe! Gracias por su mensaje. Normalmente desayuno un café con leche y pan con queso. Como en el trabajo, casi siempre ensalada y pollo, y por la noche ceno algo ligero: sopa o fruta. No bebo nunca refresco, pero bebo agua todo el día. En mi casa, en Canadá, comemos pescado una vez a la semana. ¿Y ustedes qué desayunan? ¡Un abrazo y hasta pronto!",
    ],
    checklist: [
      "Uso al menos cuatro verbos en -er o -ir bien conjugados.",
      "Uso tres expresiones de frecuencia distintas.",
      "Uso _nunca_ correctamente (delante sin _no_, o detrás con _no_).",
      "Hablo de usted con Lupe de forma constante (o de tú, pero siempre igual).",
      "Termino con una pregunta sobre sus hábitos.",
    ],
    words: [50, 90],
  },
  speaking: {
    intro: "Habla de tus hábitos reales. Si algo no es verdad, también vale: lo importante es que la gramática salga sola.",
    tasks: [
      {
        title: "Mis hábitos de comida",
        prompt: "Explica en 45 segundos qué comes y bebes en un día normal: desayuno, comida y cena. Usa al menos cuatro expresiones de frecuencia.",
        prep: ["Normalmente desayuno…", "Casi siempre como en…", "A veces / de vez en cuando…", "No bebo nunca…"],
        seconds: 45,
        model: "Normalmente desayuno un café solo y una tostada. Casi siempre como en casa, con mi pareja: arroz, verduras y a veces pescado. Ceno algo ligero: una fruta o un yogur. Bebo agua todo el día y de vez en cuando una cerveza con mis amigos. Pero no bebo nunca refresco.",
        selfCheck: ["Uso cuatro expresiones de frecuencia.", "Las **b** y **v** entre vocales suenan suaves.", "_Nunca_ está en la posición correcta."],
      },
      {
        title: "La entrevista de Andrea",
        prompt: "Ahora eres periodista. Graba cinco preguntas para una encuesta sobre hábitos. Después responde tú mismo a cada una.",
        prep: ["¿Qué desayunas normalmente?", "¿Dónde comes?", "¿Con qué frecuencia comes fuera?", "¿Bebes café?", "¿Comes carne / pescado?"],
        seconds: 60,
        model: "¿Qué desayunas normalmente? — Normalmente desayuno fruta y un jugo. ¿Dónde comes? — Como en la oficina. ¿Con qué frecuencia comes fuera? — Una vez a la semana. ¿Bebes café? — Sí, siempre. ¿Comes carne? — Casi nunca.",
        selfCheck: ["Las preguntas sí/no suben al final.", "Las respuestas tienen frecuencia.", "Uso tú en las preguntas de forma constante."],
      },
      {
        title: "Mi familia a la mesa",
        prompt: "Describe en 30 segundos los hábitos de tu familia: quién cocina, qué comen juntos y una costumbre especial.",
        prep: ["En mi casa, mi… cocina…", "Nosotros comemos… los domingos", "Mi abuela / mi padre siempre…"],
        seconds: 30,
        model: "En mi casa, mi padre cocina casi siempre. Los domingos comemos todos juntos en casa de mis abuelos: mi abuela siempre prepara sopa y nosotros bebemos limonada. Mi hermano no come nunca verduras.",
        selfCheck: ["Uso posesivos (mi, nuestra, sus).", "Uso nosotros: comemos, bebemos, vivimos."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo, convierte tus hábitos en conversación.",
    cards: [
      {
        move: "Encuesta",
        task: "Haz a tu profesor o profesora cinco preguntas sobre sus hábitos de comida y apunta las respuestas con la frecuencia.",
        phrases: ["¿Con qué frecuencia…?", "¿Qué desayunas normalmente?", "¿Comes fuera a menudo?"],
      },
      {
        move: "Cuenta",
        task: "Explica un plato típico de tu país o de tu familia: cuándo lo comen y quién lo cocina.",
        phrases: ["En mi país comemos… en Navidad.", "Mi abuela siempre cocina…"],
      },
      {
        move: "Compara",
        task: "Compara tus hábitos con los de tu profesor o profesora: una cosa igual y una diferente.",
        phrases: ["Yo también desayuno…", "Tú bebes café todos los días, pero yo no bebo nunca café."],
      },
      {
        move: "Reacciona",
        task: "Cuando tu profesor o profesora cuente un hábito, reacciona con una expresión antes de hacer otra pregunta.",
        phrases: ["¿En serio?", "¡Qué interesante!", "¿Todos los días?"],
      },
    ],
    bring: "Una foto de tu desayuno o de un plato típico de tu país.",
  },
  quiz: {
    items: [
      { type: "choice", q: "Mi pareja y yo ___ en un piso pequeño.", options: ["vivimos", "viven", "vivemos"], answer: 0, why: "Nosotros + -ir → **vivimos**." },
      { type: "choice", q: "¿Qué frase con «nunca» es correcta?", options: ["Nunca desayuno en la calle.", "Nunca no desayuno en la calle.", "Desayuno nunca en la calle."], answer: 0, why: "_Nunca_ delante del verbo, sin _no_." },
      { type: "listen", q: "¿Con qué frecuencia come pescado la persona?", audio: "Como pescado una vez a la semana.", voice: "es-PE-m", options: ["todos los días", "una vez a la semana", "nunca"], answer: 1 },
      { type: "listen", q: "¿Qué bebida pide la persona?", audio: "Un zumo de naranja, por favor.", voice: "es-ES-f", options: ["un jugo de naranja", "un refresco", "un café con leche"], answer: 0, why: "_Zumo_ (España) = **jugo** (América)." },
      { type: "gap", q: "Los estudiantes ___ (leer) y ___ (escribir) en la biblioteca.", answers: [["leen"], ["escriben"]], why: "Ellos → le**en**, escrib**en**." },
      { type: "gap", q: "¿Tus padres ___ (beber) café de olla todas ___ mañanas?", answers: [["beben"], ["las"]], why: "Ellos → beb**en**; _todas las mañanas_." },
      { type: "transform", source: "Nunca cocinamos los lunes.", instruction: "Pon «nunca» detrás del verbo.", answers: ["No cocinamos nunca los lunes.", "No cocinamos los lunes nunca."], why: "**No** + verbo + **nunca**." },
      { type: "transform", source: "Ella aprende recetas y comparte la comida.", instruction: "Cambia a «vosotras».", answers: ["Vosotras aprendéis recetas y compartís la comida.", "Aprendéis recetas y compartís la comida."], why: "Aprend**éis** (-er) y compart**ís** (-ir): solo aquí se diferencian." },
      { type: "order", words: ["De", "vez", "en", "cuando", "cenamos", "en", "un", "restaurante."], alt: ["Cenamos en un restaurante de vez en cuando."], en: "From time to time we have dinner at a restaurant." },
      { type: "error", sentence: "Mi abuelo vive en Puebla y tiene una panadería, pero nunca no abre los domingos.", answers: ["Mi abuelo vive en Puebla y tiene una panadería, pero nunca abre los domingos.", "Mi abuelo vive en Puebla y tiene una panadería, pero no abre nunca los domingos."], why: "_Nunca_ delante del verbo no necesita _no_." },
      { type: "error", sentence: "Tú comés pan todos los días, ¿no?", answers: ["Tú comes pan todos los días, ¿no?", "Vos comés pan todos los días, ¿no?"], why: "Con **tú** la forma es _comes_, sin tilde; _comés_ es la forma de **vos**." },
      {
        type: "open",
        prompt: "Escribe tres frases sobre tus hábitos de comida: una con «siempre», una con «a veces» y una con «nunca».",
        model: "Siempre desayuno pan con mantequilla. A veces como fuera con mis compañeros. No bebo nunca leche.",
        checklist: ["Tres frecuencias distintas.", "Verbos en -er/-ir bien conjugados.", "_Nunca_ en la posición correcta."],
      },
    ],
  },
  complete: {
    canNow: [
      "Conjugar los verbos regulares en -er e -ir en presente.",
      "Decir con qué frecuencia haces algo, incluida la doble negación con nunca.",
      "Hablar de desayuno, comida y cena, y reconocer variantes como jugo/zumo o frijoles/porotos.",
      "Pronunciar la b y la v igual, con la variante fuerte o suave según la posición.",
      "Preguntar por los hábitos de otra persona y contar los tuyos.",
    ],
    review: [
      "-er/-ir solo cambian en nosotros y vosotros: comemos/vivimos, coméis/vivís.",
      "Nunca + verbo, o no + verbo + nunca. Nunca _nunca no_.",
      "Todos los días, todas las mañanas.",
      "La b y la v suenan igual: no uses la v inglesa.",
    ],
  },
  related: [
    { path: "/sistema-verbal/presente-de-indicativo", label: "Presente de indicativo" },
    { path: "/el-atelier-de-la-concordancia", label: "El Atelier de la Concordancia · adjetivos" },
  ],
};
