import type { Module } from "../../types";

export const a1w10: Module = {
  id: "a1-10",
  level: "a1",
  week: 10,
  kind: "checkpoint",
  title: "Checkpoint 2: personas, lugares y rutinas",
  subtitle: "Reúne las semanas 6 a 9: describe a tu familia, tu barrio y tu semana, y entiende mensajes de voz.",
  stop: { place: "Lago de Atitlán", country: "Guatemala" },
  minutes: 95,
  newObjectives: ["a1.rev.checkpoint-2", "a1.lis.mensaje-voz"],
  reviewObjectives: [
    "a1.gram.tener",
    "a1.gram.posesivos",
    "a1.gram.concordancia-adjetivo",
    "a1.voc.familia",
    "a1.voc.descripcion-personas",
    "a1.pron.c-z-s",
    "a1.fun.describir-personas",
    "a1.gram.presente-er-ir",
    "a1.gram.frecuencia",
    "a1.voc.comidas-bebidas",
    "a1.pron.b-v",
    "a1.fun.habitos",
    "a1.gram.estar-ubicacion",
    "a1.gram.hay-esta",
    "a1.gram.preposiciones-lugar",
    "a1.voc.ciudad",
    "a1.pron.r-rr",
    "a1.fun.direcciones",
    "a1.gram.reflexivos",
    "a1.gram.hora",
    "a1.voc.rutina-dias",
    "a1.pron.j-g",
    "a1.fun.rutina-horarios",
  ],
  prerequisites: ["a1-09"],
  goal: {
    canDo: "Al final de este checkpoint puedes describir a tu familia, tu barrio y tu semana en un texto y en voz alta, y sacar el lugar, la hora y el plan de un mensaje de voz.",
    canDoEn: "By the end of this checkpoint, you can describe your family, your neighbourhood and your week in writing and aloud, and pick out the place, time and plan from a voice message.",
    steps: [
      "Repasa los contrastes clave: **ser, estar, tener y hay**; posesivos y concordancia.",
      "Repasa el presente (-ar, -er, -ir y reflexivos) con frecuencia y horas.",
      "Aprende una estrategia para escuchar mensajes de voz.",
      "Escucha tres mensajes de amigos en el Lago de Atitlán y lee la publicación de una familia de Panajachel.",
      "Escribe y graba tu presentación completa: familia, barrio y semana.",
    ],
  },
  theory: {
    intro: "Este checkpoint no trae gramática nueva: une las piezas de las semanas 6 a 9. Lee cada resumen, mira los errores típicos y comprueba si ya los evitas. Lo único nuevo es una estrategia para escuchar mensajes de voz.",
    parts: [
      {
        heading: "Ser, estar, tener y hay: cuatro verbos, cuatro trabajos",
        body: [
          "Para describir personas y lugares necesitas cuatro verbos, y cada uno tiene su trabajo. **Ser** dice qué o cómo es alguien o algo: identidad, origen, profesión, carácter, físico (**Mi hermana es alta y muy simpática**).",
          "**Estar** dice dónde está alguien o algo (**Mi casa está cerca del lago**). **Tener** dice qué tiene una persona: familia, edad, cosas, rasgos (**Tengo dos hermanos**, **Mi abuelo tiene ochenta años**, **Tiene el pelo corto**). **Hay** dice qué existe en un lugar, con información nueva (**En mi barrio hay un mercado**).",
          "La pregunta que te ayuda a elegir: ¿**cómo es**? → ser; ¿**dónde está**? → estar; ¿**qué tiene** / **cuántos años tiene**? → tener; ¿**qué hay** allí? → hay.",
        ],
        support: [
          "English uses 'to be' for age (_she is 30_) but Spanish uses _tener_: _tiene treinta años_ (she has thirty years).",
          "English 'is' can be _es_ (what/how it is) or _está_ (where it is). And 'there is' is always _hay_.",
        ],
        table: {
          caption: "¿Qué verbo?",
          head: ["Pregunta", "Verbo", "Ejemplo"],
          rows: [
            ["¿Cómo es? ¿Quién es? ¿De dónde es?", "ser", "Mi padre es profesor. Es de Sololá."],
            ["¿Dónde está?", "estar", "Su tienda está al lado del muelle."],
            ["¿Qué tiene? ¿Cuántos años tiene?", "tener", "Tiene cuarenta y dos años y tiene los ojos verdes."],
            ["¿Qué hay en…?", "hay", "En el pueblo hay dos iglesias."],
          ],
        },
        examples: [
          { es: "Mi prima es morena, tiene el pelo largo y está en Panajachel.", en: "My cousin is dark-haired, has long hair and is in Panajachel." },
          { es: "En mi calle hay una panadería. Está enfrente de mi casa.", en: "There's a bakery on my street. It's opposite my house." },
          { es: "—¿Cuántos años tiene tu hijo? —Tiene seis.", en: "How old is your son? — He's six." },
        ],
        mistakes: [
          { wrong: "Mi abuela es ochenta años.", right: "Mi abuela tiene ochenta años.", why: "La edad se dice con **tener**." },
          { wrong: "El lago es cerca de mi hotel.", right: "El lago está cerca de mi hotel.", why: "Ubicación = **estar**." },
          { wrong: "Hay mi hermano en la cocina.", right: "Mi hermano está en la cocina.", why: "_Mi hermano_ es una persona concreta: **está**. _Hay_ solo con información nueva (_un, una, dos_…)." },
          { wrong: "Mi madre está muy simpática y alta.", right: "Mi madre es muy simpática y alta.", why: "Carácter y físico de una persona = **ser**." },
        ],
        tip: "Cuando describas a alguien, usa los tres: **es** (cómo es), **tiene** (qué tiene) y **está** (dónde está ahora). Suena completo y natural.",
      },
      {
        heading: "Mi, tu, su… y la concordancia",
        body: [
          "Los posesivos **mi, tu, su** concuerdan en número con la cosa poseída, no con la persona: **mi hermano**, **mis hermanos**. **Nuestro** y **vuestro** concuerdan también en género: **nuestra casa**, **nuestros padres**.",
          "**Su** tiene muchos dueños posibles: de él, de ella, de usted, de ellos, de ellas, de ustedes. Si no está claro, aclara con **de** + persona: **la casa de él**, **la casa de Ana**.",
          "Los adjetivos concuerdan en género y número con el sustantivo: **un tío alto**, **una tía alta**, **unos primos altos**. Los que terminan en **-e** o en consonante no cambian en femenino: **una hermana inteligente**, **una amiga joven** (pero **jóvenes** en plural). Recuerda también las nacionalidades: **español → española**.",
        ],
        support: [
          "_Su_ can mean his, her, its, your (usted), their or your (ustedes). Context usually makes it clear; if not, say _de él / de ella_.",
          "Adjectives come after the noun and match it: _mi hermana pequeña_, _mis abuelos simpáticos_.",
        ],
        table: {
          caption: "Posesivos",
          head: ["Dueño", "una cosa", "varias cosas"],
          rows: [
            ["yo", "mi primo", "mis primos"],
            ["tú / vos", "tu madre", "tus padres"],
            ["usted, él, ella", "su casa", "sus casas"],
            ["nosotros, nosotras", "nuestro pueblo / nuestra calle", "nuestros hijos / nuestras hijas"],
            ["vosotros, vosotras (España)", "vuestro barrio / vuestra familia", "vuestros tíos / vuestras tías"],
            ["ustedes, ellos, ellas", "su abuelo", "sus abuelos"],
          ],
        },
        examples: [
          { es: "Nuestra familia es grande: tenemos doce primos.", en: "Our family is big: we have twelve cousins." },
          { es: "Mis hermanas son altas y simpáticas.", en: "My sisters are tall and friendly." },
          { es: "Diego vive con su madre. La casa de ella está cerca del lago.", en: "Diego lives with his mother. Her house is near the lake." },
        ],
        mistakes: [
          { wrong: "Mis hermano se llama Jorge.", right: "Mi hermano se llama Jorge.", why: "Un hermano → **mi** (singular)." },
          { wrong: "Nuestro casa está en Panajachel.", right: "Nuestra casa está en Panajachel.", why: "_Casa_ es femenino: **nuestra**." },
          { wrong: "Mis abuelas son muy simpáticos.", right: "Mis abuelas son muy simpáticas.", why: "El adjetivo concuerda con _abuelas_: femenino plural." },
        ],
      },
      {
        heading: "El presente de tu semana: -ar, -er, -ir y reflexivos",
        body: [
          "Todo tu día cabe en el presente. Los verbos en **-ar** llevan **-a-** en las terminaciones (_trabajo, trabajas, trabaja_…); los verbos en **-er** e **-ir** llevan **-e-** (_como, comes, come; vivo, vives, vive_), y solo se separan en nosotros y vosotros: **comemos / vivimos**, **coméis / vivís**.",
          "Los verbos reflexivos son iguales, pero con **me, te, se, nos, os, se** delante: **me levanto**, **nos acostamos**. Recuerda los bloques con cambio de vocal: **me despierto**, **me acuesto**.",
          "Para hablar de hábitos, añade la frecuencia: **siempre**, **casi siempre**, **normalmente**, **a veces**, **casi nunca**, **nunca**. Con _nunca_ hay dos posiciones: **Nunca como carne** o **No como carne nunca**. Y para situar la acción: **a las ocho**, **los lunes**, **por la mañana**.",
        ],
        support: [
          "-er and -ir verbs share all endings except _nosotros_ and _vosotros_: _comemos_ but _vivimos_.",
          "If _nunca_ comes after the verb, you need _no_ before it: _No bebo café nunca_. This 'double negative' is correct in Spanish.",
        ],
        table: {
          caption: "Tres verbos regulares y un reflexivo",
          head: ["Persona", "-ar: desayunar", "-er: beber", "-ir: escribir", "reflexivo: ducharse"],
          rows: [
            ["yo", "desayuno", "bebo", "escribo", "me ducho"],
            ["tú", "desayunas", "bebes", "escribes", "te duchas"],
            ["vos", "desayunás", "bebés", "escribís", "te duchás"],
            ["usted, él, ella", "desayuna", "bebe", "escribe", "se ducha"],
            ["nosotros/as", "desayunamos", "bebemos", "escribimos", "nos duchamos"],
            ["vosotros/as", "desayunáis", "bebéis", "escribís", "os ducháis"],
            ["ustedes, ellos, ellas", "desayunan", "beben", "escriben", "se duchan"],
          ],
        },
        examples: [
          { es: "Los domingos nos levantamos tarde y desayunamos en el jardín.", en: "On Sundays we get up late and have breakfast in the garden." },
          { es: "Mi hermano nunca bebe café, pero siempre bebe atol.", en: "My brother never drinks coffee, but he always drinks atol (a warm corn drink)." },
          { es: "¿Vives cerca del trabajo? ¿A qué hora regresas a casa?", en: "Do you live near work? What time do you get back home?" },
        ],
        mistakes: [
          { wrong: "Nosotros vivemos en Sololá.", right: "Nosotros vivimos en Sololá.", why: "_Vivir_ es de **-ir**: nosotros viv**imos** (no _-emos_)." },
          { wrong: "Nunca no desayuno.", right: "Nunca desayuno.", why: "_Nunca_ delante del verbo no lleva _no_." },
          { wrong: "Mi padre levanta a las cinco.", right: "Mi padre se levanta a las cinco.", why: "_Levantarse_ necesita **se** con él." },
        ],
        tip: "La hora de una acción va con **a**: _a las ocho_; la hora en este momento, con **es / son**: _son las ocho_.",
      },
      {
        heading: "Escuchar un mensaje de voz",
        body: [
          "Un mensaje de voz casi siempre tiene la misma forma: **saludo** (_¡Hola! Soy Mateo_), **motivo** (_te llamo por lo del sábado_), **datos** (lugar, hora, quién) y **despedida** (_¡Nos vemos!_, _Un beso_). Si conoces esta forma, sabes dónde están las informaciones importantes: en el centro.",
          "Antes de escuchar, prepara tres preguntas: **¿Dónde?**, **¿A qué hora?** y **¿Qué plan?** Mientras escuchas, no intentes entender todo: anota solo números, horas, nombres de lugares y las preposiciones que los acompañan (_enfrente de, detrás de_…).",
          "Escucha dos veces. La primera, para saber quién habla y para qué. La segunda, para completar tus notas. Atención a los cambios de plan: palabras como **pero**, **no** o **mejor** anuncian que algo cambia.",
        ],
        support: [
          "Voice messages are fast and informal, but they follow a pattern: greeting → reason → details → goodbye. Focus your attention on the details in the middle.",
          "Write only key words while listening: a number, a place, a time. You can build the full sentences afterwards.",
        ],
        examples: [
          { es: "¡Hola, soy Camila! Te escribo por lo del sábado…", en: "Hi, it's Camila! I'm writing about Saturday…" },
          { es: "…la lancha sale a las ocho y media del muelle…", en: "…the boat leaves the pier at half past eight…" },
          { es: "…pero mejor a la una, detrás de la iglesia. ¡Nos vemos!", en: "…but better at one, behind the church. See you!" },
        ],
        mistakes: [
          { wrong: "(Escuchas e intentas traducir cada palabra.)", right: "(Escuchas y anotas solo: lugar, hora, plan.)", why: "Traducir todo te hace perder los datos importantes. Busca solo las respuestas a tus tres preguntas." },
        ],
        tip: "Si el mensaje dice dos horas, la última que oyes después de **pero** o **mejor** suele ser la buena.",
      },
    ],
  },
  grammar: {
    intro: "Ejercicios mixtos de las semanas 6 a 9. Si fallas uno, vuelve al resumen de la teoría correspondiente.",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "¿Es, está, tiene o hay?",
        prompt: "Elige el verbo que completa la frase.",
        items: [
          { q: "Mi tía Rosa ___ cincuenta años.", options: ["tiene", "es", "está"], answer: 0, why: "Edad → **tener**." },
          { q: "Su restaurante ___ al lado del muelle.", options: ["está", "es", "hay"], answer: 0, why: "Ubicación de algo concreto → **está**." },
          { q: "En el pueblo ___ un mercado los martes.", options: ["hay", "está", "tiene"], answer: 0, why: "Algo nuevo en un lugar → **hay**." },
          { q: "Mi sobrino ___ muy alegre y un poco tímido.", options: ["es", "está", "tiene"], answer: 0, why: "Carácter → **ser**." },
          { q: "Mis primos ___ el pelo rizado.", options: ["tienen", "son", "están"], answer: 0, why: "Rasgo físico con _el pelo_ → **tener**." },
          { q: "—¿Dónde ___ tus padres? —En San Pedro.", options: ["están", "son", "hay"], answer: 0, why: "Personas concretas + _dónde_ → **están**." },
        ],
      },
      {
        id: "g2",
        type: "gap",
        title: "Posesivos y adjetivos",
        prompt: "Completa con el posesivo o con la forma correcta del adjetivo.",
        items: [
          { q: "___ abuelos viven en Sololá. (de mí)", answers: [["Mis", "mis"]], why: "Varios abuelos → **mis**." },
          { q: "Nosotros tenemos una hija. ___ hija se llama Itzel. (de nosotros)", answers: [["Nuestra", "nuestra"]], why: "_Hija_: femenino singular → **nuestra**." },
          { q: "Mis hermanas son muy ___ (trabajador).", answers: [["trabajadoras"]], why: "Femenino plural: trabajador**as**." },
          { q: "Tu madre es ___ (joven) y tus tíos también son ___ (joven).", answers: [["joven"], ["jóvenes"]], why: "_Joven_ no cambia en femenino; en plural, **jóvenes** (con tilde)." },
          { q: "Andrés y ___ novia viven cerca del lago. (de Andrés)", answers: [["su"]], why: "La novia de él → **su**." },
        ],
      },
      {
        id: "g3",
        type: "gap",
        title: "La semana de Mateo",
        prompt: "Completa con el verbo en presente. Atención a los reflexivos.",
        items: [
          { q: "De lunes a viernes, Mateo ___ (despertarse) a las cinco y media.", answers: [["se despierta"]], why: "Él → **se despierta** (e → ie, como _me despierto_)." },
          { q: "Normalmente ___ (beber) café y ___ (comer) pan dulce.", answers: [["bebe"], ["come"]], why: "-er con él: **bebe**, **come**." },
          { q: "Su mujer y él ___ (vivir) en Panajachel, cerca del mercado.", answers: [["viven"]], why: "Ellos → **viven**." },
          { q: "Los sábados sus hijos y él ___ (levantarse) tarde.", answers: [["se levantan"]], why: "Ellos → **se levantan**." },
          { q: "Mateo no ___ (trabajar) nunca los domingos.", answers: [["trabaja"]], why: "_No_ + verbo + _nunca_: doble negación correcta." },
        ],
      },
      {
        id: "g4",
        type: "transform",
        title: "Del yo al ella",
        prompt: "Reescribe cada frase hablando de tu hermana. Cambia el verbo, el pronombre y el posesivo.",
        items: [
          { source: "Me levanto a las siete y desayuno con mi hijo.", answers: ["Se levanta a las siete y desayuna con su hijo.", "Mi hermana se levanta a las siete y desayuna con su hijo.", "Ella se levanta a las siete y desayuna con su hijo."], why: "me levanto → **se levanta**; desayuno → **desayuna**; mi hijo → **su** hijo." },
          { source: "Vivo en Guatemala y tengo dos perros.", answers: ["Vive en Guatemala y tiene dos perros.", "Mi hermana vive en Guatemala y tiene dos perros.", "Ella vive en Guatemala y tiene dos perros."], why: "vivo → **vive**; tengo → **tiene**." },
          { source: "Mi oficina está enfrente del parque y nunca como allí.", answers: ["Su oficina está enfrente del parque y nunca come allí.", "La oficina de mi hermana está enfrente del parque y nunca come allí."], why: "mi → **su**; como → **come**." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "No hay palabras nuevas: estas son las más útiles de las semanas 6 a 9, agrupadas para describir una vida entera.",
    groups: [
      {
        title: "La familia",
        items: [
          { es: "los padres: el padre y la madre", en: "parents: father and mother" },
          { es: "los hermanos: el hermano mayor / la hermana menor", en: "siblings: older brother / younger sister" },
          { es: "los abuelos, los nietos", en: "grandparents, grandchildren" },
          { es: "los tíos, los primos, los sobrinos", en: "uncles and aunts, cousins, nephews and nieces" },
          { es: "el esposo, la esposa / el marido, la mujer", en: "husband, wife" },
          { es: "los hijos: un hijo y una hija", en: "children: a son and a daughter" },
        ],
      },
      {
        title: "Cómo es",
        items: [
          { es: "es alto / bajo / delgado", en: "he's tall / short / slim" },
          { es: "tiene el pelo largo, corto, rizado", en: "has long, short, curly hair" },
          { es: "tiene los ojos verdes / oscuros", en: "has green / dark eyes" },
          { es: "es simpático, alegre, tímido, trabajador", en: "is friendly, cheerful, shy, hard-working" },
          { es: "es joven / mayor", en: "is young / older" },
        ],
      },
      {
        title: "Comer y beber",
        items: [
          { es: "desayunar, comer / almorzar, cenar", en: "have breakfast, lunch, dinner" },
          { es: "los frijoles, las tortillas, los huevos", en: "beans, tortillas, eggs" },
          { es: "el jugo (América) / el zumo (España)", en: "juice" },
          { es: "el pescado del lago", en: "fish from the lake" },
          { es: "beber agua, café, atol", en: "drink water, coffee, atol" },
        ],
      },
      {
        title: "Lugares",
        items: [
          { es: "el muelle y la lancha", en: "the pier and the boat (on Lake Atitlán, boats connect the villages)" },
          { es: "el mercado, la iglesia, la plaza", en: "the market, the church, the square" },
          { es: "la parada, el banco, la farmacia", en: "the stop, the bank, the pharmacy" },
          { es: "cerca de, al lado de, enfrente de, detrás de", en: "near, next to, opposite, behind" },
        ],
      },
      {
        title: "Mi semana",
        items: [
          { es: "me despierto, me levanto, me ducho", en: "I wake up, get up, shower" },
          { es: "empiezo a trabajar / termino de trabajar", en: "I start / finish work" },
          { es: "me acuesto", en: "I go to bed" },
          { es: "de lunes a viernes, los fines de semana", en: "Monday to Friday, at weekends" },
          { es: "siempre, normalmente, a veces, nunca", en: "always, usually, sometimes, never" },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "¿Quién es?",
        prompt: "Une cada definición con el familiar.",
        pairs: [
          { left: "La madre de mi madre", right: "mi abuela" },
          { left: "El hijo de mi tía", right: "mi primo" },
          { left: "La hija de mi hermano", right: "mi sobrina" },
          { left: "El hermano de mi padre", right: "mi tío" },
          { left: "Los hijos de mis hijos", right: "mis nietos" },
        ],
        why: "Las relaciones familiares se construyen con **de**: _la madre de mi madre_ = mi abuela.",
      },
      {
        id: "v2",
        type: "classify",
        title: "¿Con qué verbo?",
        prompt: "¿Qué verbo completa mejor cada expresión: **ser** o **tener**?",
        categories: ["ser…", "tener…"],
        items: [
          { text: "… muy trabajadora", cat: 0, why: "Carácter → **es** trabajadora." },
          { text: "… los ojos verdes", cat: 1, why: "Rasgo con artículo → **tiene** los ojos verdes." },
          { text: "… treinta y cinco años", cat: 1, why: "Edad → **tener**." },
          { text: "… de Quetzaltenango", cat: 0, why: "Origen → **ser** de." },
          { text: "… el pelo rizado", cat: 1, why: "**tiene** el pelo rizado." },
          { text: "… alto y delgado", cat: 0, why: "Físico con adjetivo → **es** alto." },
        ],
      },
      {
        id: "v3",
        type: "context",
        title: "Variantes del mundo hispano",
        prompt: "Elige la palabra que usarías en cada lugar.",
        items: [
          { context: "Estás en un desayuno en Madrid y pides una bebida de naranja.", q: "Pides:", options: ["un zumo de naranja", "un jugo de naranja", "un atol de naranja"], answer: 0, why: "En España se dice **zumo**; en América, _jugo_." },
          { context: "Preguntas por una calle en Panajachel. La tienda está dos bloques más allá.", q: "Te dicen:", options: ["Está a dos cuadras.", "Está a dos manzanas.", "Está a dos lanchas."], answer: 0, why: "En Guatemala y casi toda América: **cuadra**. En España, _calle_ o _manzana_." },
          { context: "En Antigua Guatemala tu familia anfitriona te dice cuándo es la comida del mediodía.", q: "Te dicen:", options: ["Almorzamos a la una.", "Merendamos a la una.", "Cenamos a la una."], answer: 0, why: "En gran parte de América, la comida del mediodía es el **almuerzo**." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "Repaso: c/z/s, b/v, r/rr y la jota",
    explanation: [
      "En estas cuatro semanas has trabajado cuatro puntos difíciles. **C, Z y S**: en casi toda América y en partes de Andalucía y Canarias, _casa_ y _caza_ suenan igual (**seseo**); en el centro y el norte de España, _ce, ci, za, zo, zu_ suenan como la _th_ de _think_ (**distinción**). Las dos son correctas.",
      "**B y V** son el mismo sonido en todo el mundo hispano: _vaca_ y _baca_ se pronuncian igual. Al principio de frase o después de _m, n_ los labios se cierran (_un vaso_); entre vocales se tocan apenas (_la vaca, el lobo_).",
      "**R y RR**: un toque (_pero, caro_) o varios (_perro, carro, Roma, Enrique_). **J y G**: _jueves, gente_ con jota; _gato, guitarra_ con g suave. En Guatemala la jota es suave, casi una _h_ aspirada.",
      "Esta semana juntas los cuatro sonidos en frases reales sobre familia, lugares y rutina. Ve despacio primero y luego a velocidad normal.",
    ],
    support: [
      "Seseo (Latin America) = c/z sound like s. Distinción (central/northern Spain) = c/z sound like English 'th'. Choose one and be consistent.",
      "b and v: same sound. Never bite your lip for v.",
      "r = one tap; rr = trill. j = breathy sound at the back of the mouth, never English 'j'.",
    ],
    table: {
      head: ["Punto", "Escucha la diferencia", "Ejemplo en frase"],
      rows: [
        ["c, z / s", "casa – caza (iguales con seseo)", "Mi tío Ignacio cocina en la plaza."],
        ["b / v", "vaca – baca (siempre iguales)", "Mi abuela vive en Sololá y bebe atol."],
        ["r / rr", "pero – perro", "Mi primo Rodrigo tiene un perro."],
        ["j / g", "gente – gato", "Los jueves mi hija juega con su gato."],
      ],
    },
    perceive: {
      id: "p1",
      type: "listen",
      title: "Cuatro sonidos, un oído",
      prompt: "Escucha y responde. Cada pregunta repasa un punto distinto.",
      items: [
        { q: "Oyes una palabra de una persona de Madrid. ¿Cuál es?", audio: "caza", voice: "es-ES-m", options: ["caza", "casa"], answer: 0, why: "Con distinción, la **z** suena como _th_: es **caza** (_hunting_)." },
        { q: "Oyes dos palabras. ¿Suenan igual o diferente?", audio: "vaca, baca", voice: "es-MX-f", options: ["Suenan igual.", "Suenan diferente."], answer: 0, why: "**B y V** son el mismo sonido: _vaca_ y _baca_ son idénticas al oído." },
        { q: "¿Qué palabra oyes?", audio: "carro", voice: "es-MX-m", options: ["caro", "carro"], answer: 1, why: "Varios toques: **carro**." },
        { q: "¿Qué palabra oyes en esta frase?", audio: "Mi primo tiene un perro.", voice: "es-CO-f", options: ["pero", "perro"], answer: 1, why: "La rr vibra: **perro**." },
        { q: "¿Cómo empieza esta palabra?", audio: "gente", voice: "es-ES-f", options: ["con sonido de jota", "con g suave, como en gato"], answer: 0, why: "**ge, gi** suenan como jota." },
        { q: "¿Cómo empieza esta palabra?", audio: "guitarra", voice: "es-AR-m", options: ["con sonido de jota", "con g suave, como en gato"], answer: 1, why: "**gui** = g suave; la u no suena." },
        { q: "Oyes a una persona de Guatemala. ¿Cómo es su jota en «hijo»?", audio: "Mi hijo trabaja en Panajachel.", voice: "es-MX-m", options: ["suave, casi como una h", "como la j inglesa de «job»"], answer: 0, why: "En Guatemala y gran parte de América la jota es suave y aspirada; nunca es la _j_ inglesa." },
      ],
    },
    produce: [
      { text: "Mi abuela vive en Sololá y bebe atol todas las mañanas.", tip: "Ninguna **v** se muerde: _vive, bebe_ suenan igual. Entre vocales, labios relajados." },
      { text: "Mi tío Ignacio cocina pescado en la plaza a las doce.", tip: "Elige seseo (_Ignasio, cosina, plasa, dose_) o distinción con _th_. Sé constante en toda la frase." },
      { text: "Rodrigo, mi primo, corre con su perro alrededor del lago.", tip: "Fuerte: _Rodrigo, corre, perro_ y la primera r de _alrededor_ (después de l). Simple: _primo_ y la r final de _alrededor_." },
      { text: "Los jueves mi hija juega con la gente en el jardín.", tip: "Cinco jotas: _jueves, hija, juega, gente, jardín_. Suaves o fuertes, pero nunca la _j_ inglesa.", voice: "es-MX-f" },
      { text: "Me levanto a las seis y media, me ducho y desayuno jugo de naranja.", tip: "Todo junto: **v** suave entre vocales en _levanto_; **s** en _seis_; jota en _jugo_ y _naranja_; y una r simple en _naranja_." },
    ],
    spelling: "Cuatro reglas para escribir: **z** delante de a, o, u y **c** delante de e, i (_zapato, cine_); **b** o **v** se aprenden con la palabra (_vivir, beber_); **rr** solo entre vocales; **j** siempre con a, o, u (_jamón, joven, jugo_) y **g** o **j** delante de e, i (_gente, jefe_).",
  },
  listening: {
    title: "Tres mensajes desde el lago",
    context: "Es viernes por la noche. Estás en Panajachel, en el Lago de Atitlán, y mañana vas a pasar el día con tres amigos. Tu teléfono tiene tres mensajes de voz. Escucha y descubre el plan: dónde, a qué hora y con quién.",
    speakers: [
      { id: "mateo", name: "Mateo", voice: "es-MX-m", role: "amigo guatemalteco de Panajachel" },
      { id: "camila", name: "Camila", voice: "es-CL-f", role: "amiga chilena, trabaja en un hostal" },
      { id: "diego", name: "Diego", voice: "es-AR-m", role: "amigo argentino de viaje con su familia" },
    ],
    script: [
      { speaker: "mateo", text: "¡Hola! Soy Mateo. Te escribo por lo del sábado. El plan es desayunar en San Juan La Laguna, al otro lado del lago." },
      { speaker: "mateo", text: "La lancha sale del muelle de Panajachel a las ocho y media. El muelle está al final de la calle Santander, enfrente de un restaurante grande." },
      { speaker: "mateo", text: "Mi prima Lucía también desayuna con nosotros. Es alta, tiene el pelo largo y siempre lleva un sombrero rojo. ¡Hasta mañana!" },
      { speaker: "camila", text: "Hola, hola, soy Camila. Un problema: el sábado trabajo en el hostal hasta las nueve, así que no desayuno con ustedes." },
      { speaker: "camila", text: "Tomo la lancha de las diez y llego a San Juan a las diez y media, más o menos." },
      { speaker: "camila", text: "Para comer, en San Juan hay un comedor muy bueno, detrás de la iglesia. ¿Comemos allí a la una? ¡Un beso!" },
      { speaker: "diego", text: "Che, ¿qué tal? Soy Diego. Estoy en Santiago Atitlán con mi papá y mi hermano menor." },
      { speaker: "diego", text: "Nosotros llegamos a San Juan a las doce. Pero ojo: mi hermano no come carne nunca, es vegetariano." },
      { speaker: "diego", text: "¿Vos sabés si el comedor tiene comida vegetariana? Mi papá dice que hay frijoles, tortillas y pescado… ¡pero el pescado no es vegetariano! Bueno, nos vemos mañana." },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: ¿para qué escribe cada persona?",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha los tres mensajes una vez y responde.",
          items: [
            { q: "¿Qué propone Mateo?", options: ["desayunar en San Juan La Laguna", "comer en Santiago Atitlán", "cenar en Panajachel"], answer: 0, why: "_El plan es desayunar en San Juan La Laguna._" },
            { q: "¿Por qué escribe Camila?", options: ["porque trabaja y llega más tarde", "porque está enferma", "porque no le gusta el lago"], answer: 0, why: "_El sábado trabajo en el hostal hasta las nueve._" },
            { q: "¿Qué pregunta Diego?", options: ["si hay comida vegetariana en el comedor", "dónde está el muelle", "qué hora es"], answer: 0, why: "_¿Vos sabés si el comedor tiene comida vegetariana?_" },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: completa tus notas con el lugar y la hora.",
        exercise: {
          id: "l2",
          type: "gap",
          prompt: "Escribe la información que oyes (las horas, en palabras o en números).",
          items: [
            { q: "La lancha de Mateo sale a las ___.", answers: [["ocho y media", "8:30", "8.30"]], why: "_Sale del muelle de Panajachel a las ocho y media._" },
            { q: "El muelle está enfrente de un ___ grande.", answers: [["restaurante"]], why: "_Enfrente de un restaurante grande._" },
            { q: "Camila llega a San Juan a las ___, más o menos.", answers: [["diez y media", "10:30", "10.30"]], why: "_Tomo la lancha de las diez y llego a las diez y media._" },
            { q: "El comedor está detrás de la ___.", answers: [["iglesia"]], why: "_Hay un comedor muy bueno, detrás de la iglesia._" },
            { q: "Camila propone comer a la ___.", answers: [["una", "1", "1:00"]], why: "_¿Comemos allí a la una?_" },
            { q: "Diego llega a San Juan con su papá y su hermano a las ___.", answers: [["doce", "12", "12:00"]], why: "_Nosotros llegamos a San Juan a las doce._" },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en qué verbo usa cada frase para describir.",
        exercise: {
          id: "l3",
          type: "classify",
          prompt: "¿Para qué sirve el verbo en cada frase?",
          categories: ["ser: cómo es", "estar: dónde está", "tener: qué tiene", "hay: qué existe"],
          items: [
            { text: "Es alta.", cat: 0, why: "Físico de Lucía → **ser**." },
            { text: "El muelle está al final de la calle Santander.", cat: 1, why: "Ubicación → **estar**." },
            { text: "Tiene el pelo largo.", cat: 2, why: "Rasgo físico con artículo → **tener**." },
            { text: "En San Juan hay un comedor muy bueno.", cat: 3, why: "Información nueva → **hay**." },
            { text: "Estoy en Santiago Atitlán.", cat: 1, why: "Ubicación de Diego → **estar**." },
            { text: "Mi hermano es vegetariano.", cat: 0, why: "Cómo es una persona → **ser**." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Somos la familia del Café Tzununá",
    genre: "Publicación en redes sociales de un negocio familiar",
    frame: "La familia Mendoza tiene un café pequeño en Panajachel. Rosa, la hija mayor, presenta a su familia en la página del café.",
    text: [
      "¡Hola a todos! Soy Rosa y esta es mi familia. Somos cinco y todos trabajamos en el Café Tzununá. El café está en la calle Santander, a dos cuadras del muelle, entre una farmacia y una tienda de artesanías.",
      "Mi papá, don Julio, tiene sesenta años. Es bajo, tiene bigote y es muy alegre. Él se levanta a las cinco, abre el café a las seis y siempre prepara el café de Atitlán. Mi mamá, doña Elena, es la cocinera: cocina los mejores frijoles del pueblo. Ella se acuesta temprano, a las nueve: se levanta antes que nadie.",
      "Mis hermanos son gemelos: Kevin y Brayan tienen veinte años. Son altos, delgados y un poco tímidos. Estudian en Sololá de lunes a viernes, pero los sábados y los domingos trabajan aquí con nosotros. Y nuestra abuela, doña Tomasa, tiene ochenta y dos años y vive con nosotros. Ella habla kaqchikel y español, y casi todas las tardes teje en la terraza.",
      "Abrimos de martes a domingo, de seis de la mañana a cuatro de la tarde. Los lunes nunca abrimos: es nuestro día de familia. Hay desayunos típicos, jugos naturales y pan de banano. ¡Los esperamos!",
    ],
    glossary: [
      { es: "el bigote", en: "moustache" },
      { es: "los mejores frijoles", en: "the best beans" },
      { es: "la cocinera", en: "the cook (woman)" },
      { es: "antes que nadie", en: "before anyone else" },
      { es: "los gemelos", en: "twins" },
      { es: "el kaqchikel", en: "a Mayan language spoken around Lake Atitlán" },
      { es: "teje", en: "she weaves (from _tejer_)" },
      { es: "¡Los esperamos!", en: "We're waiting for you! / Come and see us!" },
    ],
    tasks: [
      {
        id: "r1",
        type: "match",
        title: "Cada persona, su descripción",
        prompt: "Une cada miembro de la familia con la información del texto.",
        pairs: [
          { left: "don Julio", right: "Es bajo, tiene bigote y abre el café a las seis." },
          { left: "doña Elena", right: "Es la cocinera y se acuesta a las nueve." },
          { left: "Kevin y Brayan", right: "Son gemelos y estudian en Sololá." },
          { left: "doña Tomasa", right: "Tiene ochenta y dos años y habla kaqchikel." },
        ],
        why: "Cada descripción combina **ser** (cómo es), **tener** (edad, rasgos) y una acción de la rutina.",
      },
      {
        id: "r2",
        type: "choice",
        prompt: "Lee otra vez y responde.",
        items: [
          { q: "¿Dónde está el café?", options: ["entre una farmacia y una tienda de artesanías", "enfrente del muelle", "al lado de la iglesia"], answer: 0, why: "_Está… a dos cuadras del muelle, entre una farmacia y una tienda de artesanías._" },
          { q: "¿Qué hacen los hermanos de Rosa los fines de semana?", options: ["Trabajan en el café.", "Estudian en Sololá.", "Descansan en casa."], answer: 0, why: "_Los sábados y los domingos trabajan aquí con nosotros._" },
          { q: "Quieres desayunar en el café un lunes a las ocho. ¿Es posible?", options: ["No, los lunes nunca abren.", "Sí, abren a las seis.", "Sí, pero solo hasta las nueve."], answer: 0, why: "_Los lunes nunca abrimos: es nuestro día de familia._" },
          { q: "¿Quién se levanta antes que nadie?", options: ["doña Elena", "don Julio", "doña Tomasa"], answer: 0, why: "Doña Elena _se acuesta temprano, a las nueve: se levanta antes que nadie_." },
        ],
      },
    ],
    noticing: {
      prompt: "Toca cada frase y mira qué repasa.",
      items: [
        { quote: "Es bajo, tiene bigote y es muy alegre", note: "La descripción completa: **ser** + físico, **tener** + rasgo, **ser** + carácter." },
        { quote: "entre una farmacia y una tienda de artesanías", note: "**Entre… y…** sin _de_. Y antes: _a dos cuadras **del** muelle_ (de + el)." },
        { quote: "Ella se acuesta temprano, a las nueve", note: "Reflexivo con cambio vocálico (**se acuesta**) + hora con **a las**." },
        { quote: "Los lunes nunca abrimos", note: "**Los** lunes = hábito. **Nunca** delante del verbo, sin _no_." },
        { quote: "nuestra abuela", note: "Posesivo de nosotros que concuerda con _abuela_: **nuestra**." },
      ],
    },
  },
  practice: {
    intro: "Práctica integrada: cada ejercicio mezcla puntos de semanas distintas.",
    exercises: [
      {
        id: "x1",
        type: "gap",
        title: "La familia de Itzel",
        prompt: "Completa el texto con las palabras del banco. Cada palabra se usa una vez.",
        bank: ["es", "está", "tiene", "hay", "sus", "se", "nunca", "del"],
        items: [
          { q: "Itzel ___ de San Pedro La Laguna y ___ veintiocho años.", answers: [["es"], ["tiene"]], why: "Origen → **es** de; edad → **tiene**." },
          { q: "Vive con ___ padres en una casa que ___ cerca ___ lago.", answers: [["sus"], ["está"], ["del"]], why: "Varios padres → **sus**; ubicación → **está**; de + el lago → **del**." },
          { q: "En su calle ___ una panadería muy buena.", answers: [["hay"]], why: "Algo nuevo → **hay**." },
          { q: "Ella ___ levanta a las seis y ___ desayuna sin café.", answers: [["se"], ["nunca"]], why: "Reflexivo → **se** levanta; _nunca_ delante del verbo, sin _no_." },
        ],
      },
      {
        id: "x2",
        type: "error",
        title: "Detective de errores: semanas 6 a 9",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "Mi hermana mayor es veinticinco años.", answers: ["Mi hermana mayor tiene veinticinco años."], why: "Semana 6: la edad va con **tener**." },
          { sentence: "Mis tíos son muy simpáticas.", answers: ["Mis tíos son muy simpáticos.", "Mis tías son muy simpáticas."], why: "Semana 6: concordancia. _Tíos_ es masculino plural → simpátic**os**." },
          { sentence: "A veces nosotros comemos y bebimos en el mercado.", answers: ["A veces nosotros comemos y bebemos en el mercado.", "A veces comemos y bebemos en el mercado."], why: "Semana 7: presente de _beber_ con nosotros → **bebemos**." },
          { sentence: "La parada del bus es enfrente del hospital.", answers: ["La parada del bus está enfrente del hospital."], why: "Semana 8: ubicación = **estar**." },
          { sentence: "Los sábados me levanto en las nueve.", answers: ["Los sábados me levanto a las nueve."], why: "Semana 9: hora de una acción → **a las**." },
          { sentence: "¿Hay tu oficina cerca de aquí?", answers: ["¿Está tu oficina cerca de aquí?", "¿Tu oficina está cerca de aquí?"], why: "Semana 8: _tu oficina_ es concreta → **está**." },
        ],
      },
      {
        id: "x3",
        type: "order",
        title: "Frases completas",
        prompt: "Toca las palabras en orden.",
        items: [
          { words: ["Nuestra", "casa", "está", "detrás", "de", "la", "iglesia."], en: "Our house is behind the church.", why: "Posesivo + sustantivo + **está** + _detrás de_." },
          { words: ["Mi", "abuelo", "nunca", "se", "acuesta", "tarde."], alt: ["Mi abuelo no se acuesta nunca tarde.", "Nunca se acuesta tarde mi abuelo."], en: "My grandfather never goes to bed late.", why: "**Nunca** + pronombre reflexivo + verbo." },
          { words: ["¿A", "qué", "hora", "desayunan", "tus", "hijos?"], en: "What time do your children have breakfast?", why: "Pregunta de horario con **a qué hora** + verbo + sujeto." },
        ],
      },
      {
        id: "x4",
        type: "context",
        title: "Situaciones reales",
        prompt: "Elige la respuesta más natural.",
        items: [
          { context: "En Panajachel, una turista te pregunta: «¿Hay un banco por aquí?». Hay uno en la esquina.", q: "Respondes:", options: ["Sí, hay uno en la esquina, al lado de la farmacia.", "Sí, el banco hay en la esquina.", "Sí, es en la esquina."], answer: 0, why: "Respuesta con **hay uno** + lugar." },
          { context: "Un amigo te muestra una foto y pregunta: «¿Quién es la chica del sombrero?».", q: "Respondes:", options: ["Es mi prima Lucía. Tiene veinte años y vive en Sololá.", "Está mi prima Lucía. Es veinte años.", "Hay mi prima Lucía."], answer: 0, why: "Identidad → **es**; edad → **tiene**; residencia → **vive**." },
          { context: "Tu profesora te pregunta: «¿Qué haces los domingos por la mañana?».", q: "Respondes:", options: ["Normalmente me levanto tarde y desayuno con mi familia.", "Normalmente levanto tarde y desayuno con mi familia.", "Normalmente me levanto tarde y me desayuno en mi familia."], answer: 0, why: "**Me levanto** (reflexivo), **desayuno** (no reflexivo), **con** mi familia." },
        ],
      },
      {
        id: "x5",
        type: "transform",
        title: "De tú a usted",
        prompt: "Haz las preguntas a una persona mayor que no conoces (usted).",
        items: [
          { source: "¿Dónde vives?", answers: ["¿Dónde vive usted?", "¿Dónde vive?", "¿Usted dónde vive?"], why: "-ir con usted → **vive**." },
          { source: "¿A qué hora te levantas?", answers: ["¿A qué hora se levanta usted?", "¿A qué hora se levanta?", "¿Usted a qué hora se levanta?"], why: "Reflexivo con usted → **se** levanta." },
          { source: "¿Cuántos hermanos tienes?", answers: ["¿Cuántos hermanos tiene usted?", "¿Cuántos hermanos tiene?", "¿Usted cuántos hermanos tiene?"], why: "_Tener_ con usted → **tiene**." },
          { source: "¿Tu casa está cerca del lago?", answers: ["¿Su casa está cerca del lago?", "¿Su casa está cerca del lago, señora?", "¿Su casa está cerca del lago, señor?"], why: "Posesivo de usted → **su**." },
        ],
      },
      {
        id: "x6",
        type: "open",
        title: "Responde a los mensajes",
        prompt: "Contesta a los mensajes de voz de Mateo, Camila y Diego.",
        items: [
          {
            prompt: "Escribe tu respuesta para el grupo: confirma a qué hora estás en el muelle, di dónde comes y añade un detalle sobre ti (qué comes normalmente o a qué hora te levantas).",
            model: "¡Hola a todos! Perfecto: estoy en el muelle a las ocho y cuarto. Normalmente me levanto a las siete, así que no hay problema. Comemos a la una en el comedor detrás de la iglesia. Diego, yo no como carne nunca: siempre como frijoles y tortillas. ¡Hasta mañana!",
            checklist: ["Digo una hora con **a las**.", "Uso **está** o **estoy** para la ubicación.", "Incluyo un hábito con frecuencia.", "Uso un verbo reflexivo."],
          },
          {
            prompt: "Lucía, la prima de Mateo, no te conoce. Escríbele tres frases para que te reconozca en el muelle: cómo eres, qué tienes (pelo, ojos, ropa) y dónde estás a las ocho y cuarto.",
            model: "¡Hola, Lucía! Soy bajo y un poco delgado. Tengo el pelo corto y los ojos oscuros, y siempre llevo una mochila verde. A las ocho y cuarto estoy enfrente del restaurante grande, al lado de la lancha.",
            checklist: ["Uso **soy** para el físico y **tengo** para el pelo o los ojos.", "Los adjetivos concuerdan conmigo.", "Digo dónde **estoy** con una preposición de lugar."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe tu presentación completa para un intercambio de idiomas: tu familia, tu barrio y tu semana.",
    context: "Un grupo de intercambio en Panajachel pide a cada participante un texto para conocerse antes del primer encuentro.",
    steps: [
      "Preséntate en una o dos frases (nombre, origen, edad o trabajo).",
      "Describe a dos personas de tu familia: cómo son, qué tienen, dónde viven.",
      "Describe tu barrio: qué hay y dónde están dos lugares importantes para ti.",
      "Cuenta tu semana: una rutina de lunes a viernes con horas y algo diferente el fin de semana.",
      "Añade un hábito de comida con frecuencia y despídete.",
    ],
    useLanguage: [
      "es + adjetivo / tiene + años, el pelo…",
      "mi, mis, su, nuestro/a",
      "En mi barrio hay… / … está al lado de…",
      "me levanto, me acuesto + a las…",
      "siempre, normalmente, a veces, nunca",
    ],
    model: [
      "¡Hola! Me llamo Daniel, soy de Toronto y tengo treinta y un años. Soy enfermero.",
      "Vivo con mi pareja, Ana. Ella es colombiana, es muy alegre y tiene el pelo rizado. Mis padres viven en Montreal; mi madre es alta y un poco tímida.",
      "Nuestro apartamento está en un barrio tranquilo. Hay un parque muy grande y un mercado. Mi café favorito está enfrente del parque.",
      "De lunes a viernes me levanto a las seis y empiezo a trabajar a las siete. Como en el hospital y me acuesto a las diez y media. Los sábados me levanto tarde y siempre desayuno con Ana en el mercado. Nunca bebo café por la noche. ¡Hasta pronto!",
    ],
    checklist: [
      "Uso **ser**, **estar**, **tener** y **hay**, cada uno en su trabajo.",
      "Los adjetivos concuerdan con la persona (_alta, tímidos_…).",
      "Los posesivos son correctos (_mi / mis, nuestro / nuestra_).",
      "Hay al menos tres verbos reflexivos o de rutina con hora.",
      "Uso dos expresiones de frecuencia.",
      "El texto tiene entre 80 y 130 palabras.",
    ],
    words: [80, 130],
  },
  speaking: {
    intro: "Tres tareas que juntan todo el bloque. Grábalas seguidas, como si fuera un examen oral, y después evalúate con la lista.",
    tasks: [
      {
        title: "Una foto de mi familia",
        prompt: "Elige una foto real de tu familia o de tus amigos. Presenta a tres personas: quién es, cómo es, cuántos años tiene y dónde vive o está ahora.",
        prep: ["Esta es mi… / Este es mi…", "Es + carácter / físico", "Tiene… años / el pelo… / los ojos…", "Vive en… / Ahora está en…"],
        seconds: 60,
        model: "En esta foto estamos en casa de mis abuelos. Esta es mi hermana Laura: es alta, tiene el pelo corto y es muy divertida. Tiene veintiséis años y vive en Valencia. Este es mi abuelo Pedro: tiene ochenta años, es bajo y muy tranquilo. Y esta es mi sobrina Sofía: tiene tres años y ahora está en la escuela.",
        selfCheck: ["Uso **es**, **tiene** y **está/vive** para cada persona.", "Los adjetivos concuerdan.", "Pronuncio bien la **z** o la **c** según mi variante (seseo o distinción)."],
      },
      {
        title: "Mi barrio en un mapa",
        prompt: "Describe tu barrio y explica cómo llegar de tu casa a tu lugar favorito (un café, un parque, una tienda).",
        prep: ["En mi barrio hay…", "… está al lado de / enfrente de / detrás de…", "Caminas… cuadras / calles", "Giras a la derecha / a la izquierda"],
        seconds: 45,
        model: "Mi barrio es pequeño y tranquilo. Hay una plaza, dos panaderías y un parque. Mi lugar favorito es una librería. Desde mi casa, caminas dos calles, giras a la izquierda y la librería está al lado de una farmacia, enfrente de la plaza.",
        selfCheck: ["Uso **hay** para lo nuevo y **está** para lo concreto.", "Digo **del** y **al** cuando corresponde.", "La **rr** de _barrio_ suena fuerte; la r de _derecha_ es simple."],
      },
      {
        title: "Mi semana",
        prompt: "Cuenta tu semana normal: un día de trabajo o estudio con horas y un día del fin de semana. Termina con un hábito de comida.",
        prep: ["De lunes a viernes me levanto a las…", "Primero… después… por último…", "Los sábados / los domingos…", "Siempre / nunca + comida"],
        seconds: 60,
        model: "De lunes a viernes me despierto a las seis y media. Primero me ducho, después desayuno y a las ocho empiezo a trabajar. Como a la una y termino a las cinco. Por la noche ceno, veo una serie y me acuesto a las once. Los domingos me levanto tarde y como con mis padres. Nunca bebo café después de las cinco.",
        selfCheck: ["Digo al menos cuatro horas con **a las**.", "Uso tres conectores.", "Mi **j** (_jueves, jugo_) no es la _j_ inglesa."],
      },
      {
        title: "Responde a un mensaje de voz",
        prompt: "Escucha otra vez el mensaje de Camila y grábale una respuesta: confirma la hora y el lugar de la comida y di una cosa que nunca o siempre comes.",
        prep: ["¡Hola, Camila! Soy…", "Perfecto: a la una en el comedor detrás de la iglesia.", "Yo siempre / nunca como…", "¡Un beso!"],
        seconds: 30,
        model: "¡Hola, Camila! Soy Alex. Perfecto: comemos a la una en el comedor, detrás de la iglesia. Yo nunca como carne, pero siempre como frijoles. ¡Nos vemos mañana!",
        selfCheck: ["Repito el lugar y la hora exactos.", "Mi mensaje tiene saludo, datos y despedida."],
      },
    ],
  },
  useInClass: {
    intro: "Tu próxima clase en vivo es tu examen oral del bloque: lleva tus grabaciones y demuestra lo que sabes.",
    cards: [
      { move: "Presenta", task: "Muestra una foto de tu familia y presenta a dos personas sin leer. Tu profesor o profesora te hace una pregunta sobre cada una.", phrases: ["Esta es mi…", "Es… y tiene…", "Vive en…"] },
      { move: "Compara", task: "Compara tu semana con la de tu profesor o profesora: busca dos diferencias de horario y un hábito en común.", phrases: ["Yo me levanto a las…, ¿y tú?", "Los dos… / Yo también…", "Yo nunca…, pero tú…"] },
      { move: "Guía", task: "Tu profesor o profesora es turista en tu barrio. Recomiéndale un lugar y explícale dónde está y cómo llegar.", phrases: ["Hay un/una… muy bueno/a", "Está enfrente de…", "Caminas… y giras…"] },
      { move: "Responde", task: "Pide a tu profesor o profesora que te diga un mensaje de voz improvisado con un plan. Repite el lugar, la hora y el plan para confirmar.", phrases: ["Entonces, ¿a las… en…?", "¿Puede repetir la hora, por favor?", "Perfecto, nos vemos…"] },
    ],
    bring: "Lleva una foto de tu familia, una captura del mapa de tu barrio y tu texto escrito de esta semana.",
  },
  quiz: {
    items: [
      { type: "choice", q: "¿Qué frase describe correctamente a la tía de Rosa?", options: ["Es baja y tiene cuarenta años.", "Está baja y es cuarenta años.", "Tiene baja y está cuarenta años."], answer: 0, why: "Físico → **ser**; edad → **tener**." },
      { type: "choice", q: "Elige la frase correcta sobre el muelle de Santiago.", options: ["El muelle está detrás del mercado.", "El muelle es detrás del mercado.", "Hay el muelle detrás del mercado."], answer: 0, why: "Algo concreto + ubicación → **está**; de + el → **del**." },
      { type: "listen", q: "Escucha el mensaje. ¿Dónde y cuándo es la cita?", audio: "Hola, soy Inés. Mañana no hay mercado. Mejor nos vemos en la plaza, enfrente de la iglesia, a las cuatro y media. ¡Chao!", voice: "es-PE-f", options: ["en la plaza, a las cuatro y media", "en el mercado, a las cuatro y media", "en la iglesia, a las cuatro"], answer: 0, why: "Después de **mejor** viene el plan bueno: _en la plaza, enfrente de la iglesia, a las cuatro y media_." },
      { type: "listen", q: "Escucha el mensaje de voz. ¿Qué tienes que llevar a la cena?", audio: "¡Hola! Soy Martín. La cena es el viernes a las ocho en casa de mi hermana. Ella vive al lado del banco. Yo llevo la comida y vos llevás el jugo, ¿dale?", voice: "es-UY-m", options: ["el jugo", "la comida", "el pan"], answer: 0, why: "_Yo llevo la comida y vos llevás el jugo_: **llevás** es la forma de vos de _llevar_." },
      { type: "gap", q: "___ (nosotros) abuelos viven en el campo y ___ casa es muy grande.", answers: [["Nuestros", "nuestros"], ["su"]], why: "_Abuelos_ masculino plural → **nuestros**; la casa de ellos → **su**." },
      { type: "gap", q: "Los viernes mis compañeros y yo ___ (comer) en un restaurante cerca ___ trabajo.", answers: [["comemos"], ["del"]], why: "Nosotros → **comemos**; cerca de + el trabajo → **del**." },
      { type: "gap", q: "—¿Qué hora es? —___ la una y diez. Mi clase es ___ la una y media.", answers: [["Es"], ["a"]], why: "Hora ahora → **es** la una; hora de un evento → **a** la una y media." },
      { type: "transform", source: "Mi hermano se acuesta a las once y nunca desayuna.", instruction: "Cambia a yo.", answers: ["Me acuesto a las once y nunca desayuno.", "Yo me acuesto a las once y nunca desayuno."], why: "se acuesta → **me acuesto**; desayuna → **desayuno**." },
      { type: "transform", source: "Hay un supermercado al lado de mi casa. (el supermercado Paiz)", instruction: "Sitúa el supermercado concreto.", answers: ["El supermercado Paiz está al lado de mi casa."], why: "Nombre concreto → **está**." },
      { type: "order", words: ["Mis", "primas", "son", "altas", "y", "tienen", "los", "ojos", "verdes."], en: "My cousins are tall and have green eyes.", why: "**son** + adjetivo concordado; **tienen** + los ojos." },
      { type: "error", sentence: "Mi sobrina es tres años y vive con sus padres.", answers: ["Mi sobrina tiene tres años y vive con sus padres."], why: "La edad se dice con **tener**: _tiene tres años_." },
      { type: "error", sentence: "Nosotros escribemos correos todos los días.", answers: ["Nosotros escribimos correos todos los días.", "Escribimos correos todos los días."], why: "_Escribir_ es de **-ir**: escrib**imos**." },
      { type: "error", sentence: "El lunes y el martes, a las siete, mi madre se levanta y se ducha, pero el miércoles levanta a las ocho.", answers: ["El lunes y el martes, a las siete, mi madre se levanta y se ducha, pero el miércoles se levanta a las ocho."], why: "Falta el reflexivo: **se** levanta." },
      { type: "choice", q: "En Madrid, ¿cómo suena normalmente la z de «plaza»?", options: ["como la th inglesa de «think»", "como una s", "como una j"], answer: 0, why: "En el centro y norte de España hay **distinción**: _z_ = _th_. En América, seseo: suena como _s_." },
      { type: "open", prompt: "Escribe cuatro frases: una persona de tu familia (cómo es y qué edad tiene), dónde está tu casa, a qué hora te levantas y un hábito de comida.", model: "Mi madre es muy trabajadora y tiene cincuenta y ocho años. Mi casa está cerca del centro, al lado de una panadería. Me levanto a las siete menos cuarto. Siempre bebo jugo de naranja en el desayuno.", checklist: ["ser + tener para la persona", "estar + preposición para la casa", "a las + hora", "una expresión de frecuencia"] },
    ],
  },
  complete: {
    canNow: [
      "Describir a mi familia con ser, tener, posesivos y adjetivos que concuerdan.",
      "Describir mi barrio con hay y está, y explicar cómo llegar a un lugar.",
      "Contar mi semana con verbos regulares, reflexivos, horas, días y frecuencia.",
      "Sacar el lugar, la hora y el plan de un mensaje de voz.",
      "Controlar cuatro sonidos difíciles: c/z/s, b/v, r/rr y la jota.",
    ],
    review: [
      "Edad con tener: tiene veinte años.",
      "Ubicación con estar; información nueva con hay.",
      "Posesivos: mi / mis, nuestro / nuestra, su = de él, de ella, de usted…",
      "Reflexivos: me levanto, se acuesta; hora: a las…",
      "Nunca + verbo, o no + verbo + nunca.",
    ],
  },
  related: [
    { path: "/la-casa-de-las-pertenencias", label: "La Casa de las Pertenencias · posesivos" },
    { path: "/el-atelier-de-la-concordancia", label: "El Atelier de la Concordancia · adjetivos" },
    { path: "/la-torre-de-las-coordenadas", label: "La Torre de las Coordenadas · preposiciones de lugar" },
  ],
};
