import type { Module } from "../../types";

export const a1w11: Module = {
  id: "a1-11",
  level: "a1",
  week: 11,
  kind: "core",
  title: "¿Quieres venir?",
  subtitle: "Querer, poder y preferir: proponer un plan, aceptarlo o decir que no puedes.",
  stop: { place: "San Salvador", country: "El Salvador" },
  minutes: 75,
  newObjectives: [
    "a1.gram.diptongacion",
    "a1.gram.querer-poder-inf",
    "a1.voc.tiempo-libre",
    "a1.pron.n-ll-y",
    "a1.fun.proponer",
    "a1.lis.planes-amigos",
  ],
  reviewObjectives: ["a1.gram.reflexivos", "a1.gram.hora", "a1.fun.rutina-horarios", "a1.gram.estar-ubicacion"],
  prerequisites: ["a1-10"],
  goal: {
    canDo: "Al final de esta semana puedes proponer un plan para el fin de semana, aceptarlo o decir con amabilidad que no puedes, y proponer otra cosa.",
    canDoEn: "By the end of this week, you can suggest a weekend plan, accept one, or politely say you can't and suggest something else.",
    steps: [
      "Descubre por qué `quiero`, `puedo`, `juego` y `pido` cambian la vocal.",
      "Aprende a usar **querer**, **poder** y **preferir** + infinitivo.",
      "Reconoce el **vos** de Centroamérica: `vos querés`, `vos podés`.",
      "Aprende actividades de tiempo libre y fórmulas para proponer y responder.",
      "Entrena la **ñ** y escucha cómo suenan **ll** e **y** en distintos países.",
      "Escucha a tres amigos que organizan su fin de semana en San Salvador.",
      "Graba un mensaje de voz con una propuesta para tu clase.",
    ],
  },
  theory: {
    intro: "Esta semana estás en San Salvador. Tus amigos te escriben: «¿Querés subir al volcán el sábado?». Para responder necesitas verbos muy frecuentes que cambian una vocal: **querer**, **poder**, **preferir**, **jugar**…",
    parts: [
      {
        heading: "Verbos que cambian la vocal: e → ie, o → ue, u → ue, e → i",
        body: [
          "Algunos verbos cambian la última vocal de la raíz cuando esa sílaba es **fuerte** (tónica). _Querer_ → **quie**ro; _poder_ → **pue**do; _jugar_ → **jue**go; _pedir_ → **pi**do. Las terminaciones son las de siempre (-o, -es, -e, -emos…).",
          "¿Por qué solo en algunas personas? Porque en **nosotros** y **vosotros** el acento se va a la terminación: que-**re**-mos, po-**de**-mos. La raíz ya no es fuerte y no cambia. Por eso se habla del modelo «zapato» o «bota»: si dibujas la tabla y marcas las formas que cambian, parece una bota.",
          "Hay cuatro grupos. **e → ie**: querer, preferir, empezar, entender, pensar, cerrar. **o → ue**: poder, volver, dormir, almorzar, costar, encontrar. **u → ue**: solo _jugar_. **e → i** (solo verbos en -ir): pedir, repetir, servir.",
          "El diccionario no te avisa. Por eso es buena idea aprender estos verbos con una marca: _querer (ie)_, _poder (ue)_, _pedir (i)_.",
        ],
        support: [
          "Some verbs change their stem vowel when it is stressed: _querer_ → _quiero_ (I want), _poder_ → _puedo_ (I can). The endings stay regular.",
          "_Nosotros_ and _vosotros_ never change, because the stress moves to the ending: _queremos, podéis_. This is often called the 'boot' or 'shoe' pattern.",
          "Write new verbs in your notebook with the change in brackets: _dormir (ue)_, _pedir (i)_.",
        ],
        table: {
          caption: "El modelo «bota»: las formas que cambian están en negrita",
          head: ["", "querer (e → ie)", "poder (o → ue)", "jugar (u → ue)", "pedir (e → i)"],
          rows: [
            ["yo", "**quiero**", "**puedo**", "**juego**", "**pido**"],
            ["tú", "**quieres**", "**puedes**", "**juegas**", "**pides**"],
            ["él / ella / usted", "**quiere**", "**puede**", "**juega**", "**pide**"],
            ["nosotros / nosotras", "queremos", "podemos", "jugamos", "pedimos"],
            ["vosotros / vosotras", "queréis", "podéis", "jugáis", "pedís"],
            ["ellos / ellas / ustedes", "**quieren**", "**pueden**", "**juegan**", "**piden**"],
          ],
        },
        examples: [
          { es: "Los domingos duermo hasta las diez.", en: "On Sundays I sleep until ten." },
          { es: "La clase empieza a las seis y media.", en: "The class starts at six thirty." },
          { es: "¿A qué hora vuelves a casa?", en: "What time do you go back home?" },
          { es: "Nosotros almorzamos a la una.", en: "We have lunch at one." },
        ],
        mistakes: [
          { wrong: "Yo podo nadar.", right: "Yo puedo nadar.", why: "_Poder_ cambia **o → ue** en la sílaba fuerte: p**ue**do." },
          { wrong: "Nosotros queiremos salir.", right: "Nosotros queremos salir.", why: "Con _nosotros_ la raíz no es fuerte, así que no cambia: **queremos**." },
          { wrong: "Yo jugo al fútbol.", right: "Yo juego al fútbol.", why: "_Jugar_ cambia **u → ue**: j**ue**go, j**ue**gas, j**ue**ga." },
        ],
        tip: "Truco rápido: si la forma de **nosotros** es regular y la de **yo** cambia, estás ante un verbo «bota». Practica siempre en voz alta: qu**ie**ro, qu**ie**res, qu**ie**re, queremos.",
      },
      {
        heading: "Querer, poder y preferir + infinitivo",
        body: [
          "Con **querer** dices lo que deseas, con **poder** lo que es posible para ti y con **preferir** lo que eliges entre dos opciones. Los tres pueden ir con un **infinitivo**: el segundo verbo no se conjuga.",
          "La estructura es simple: verbo conjugado + infinitivo. **Quiero ver** una película. **¿Puedes jugar** el sábado? **Prefiero nadar** en la piscina. No hay ninguna palabra entre los dos verbos: ni _a_, ni _de_, ni _que_.",
          "Si el infinitivo es reflexivo (levantarse, acostarse, ducharse), el pronombre va **pegado al final** del infinitivo o **delante del primer verbo**: _Quiero levantar**me** tarde_ = _**Me** quiero levantar tarde_. Las dos formas son correctas.",
          "Para decir que no puedes, añade un motivo: _No puedo, **es que** trabajo el sábado_. **Es que** introduce una explicación y suena más amable.",
        ],
        support: [
          "_Querer_ = to want, _poder_ = can / to be able to, _preferir_ = to prefer. After them, use the infinitive: _quiero ir_ (I want to go). Never add 'a' or conjugate the second verb.",
          "With reflexive verbs, the pronoun can go at the end of the infinitive or before the first verb: _Prefiero acostarme temprano_ = _Me prefiero acostar temprano_ (the first one is more common with _preferir_).",
        ],
        examples: [
          { es: "¿Quieres ir al cine esta noche?", en: "Do you want to go to the cinema tonight?" },
          { es: "No puedo salir, es que estudio para un examen.", en: "I can't go out, I'm studying for an exam, you see." },
          { es: "Prefiero correr por la mañana.", en: "I prefer running in the morning." },
          { es: "El sábado quiero levantarme a las nueve.", en: "On Saturday I want to get up at nine." },
          { es: "Me quiero acostar temprano hoy.", en: "I want to go to bed early today." },
        ],
        mistakes: [
          { wrong: "Quiero voy al concierto.", right: "Quiero ir al concierto.", why: "Después de _querer_ el segundo verbo va en **infinitivo**: _ir_." },
          { wrong: "¿Puedes a jugar el domingo?", right: "¿Puedes jugar el domingo?", why: "Entre _poder_ y el infinitivo no hay preposición." },
          { wrong: "Quiero levantar tarde el domingo.", right: "Quiero levantarme tarde el domingo.", why: "_Levantarse_ es reflexivo: el pronombre **me** no desaparece." },
        ],
      },
      {
        heading: "Vos querés, vos podés: el voseo en Centroamérica",
        body: [
          "En El Salvador, Honduras, Nicaragua, Guatemala y Costa Rica, mucha gente usa **vos** con amigos y familia, igual que en Argentina y Uruguay. En este curso aprendes **tú** como forma principal, pero vas a oír _vos_ en la calle y en los mensajes.",
          "La buena noticia: con **vos** estos verbos **no cambian la vocal**. La forma se parece al infinitivo y lleva tilde al final: querer → **vos querés**, poder → **vos podés**, jugar → **vos jugás**, preferir → **vos preferís**, pedir → **vos pedís**.",
          "Con verbos regulares pasa lo mismo: **vos trabajás**, **vos comés**, **vos vivís**. Con reflexivos, el pronombre es **te**: _¿A qué hora te levantás?_",
          "Tú y vos significan lo mismo. En San Salvador también se oye **usted** entre amigos y en familia: es una forma de cariño y respeto, no de distancia.",
        ],
        support: [
          "_Vos_ is an informal 'you', used across Central America and the River Plate. Its present forms are stressed on the ending and keep the infinitive vowel: _querés, podés, jugás_ — no stem change.",
          "You don't need to produce _vos_ yet. Just recognise it: _¿Vos querés venir?_ = _¿Tú quieres venir?_",
        ],
        table: {
          caption: "Tú y vos en presente",
          head: ["Verbo", "tú", "vos"],
          rows: [
            ["querer", "quieres", "querés"],
            ["poder", "puedes", "podés"],
            ["preferir", "prefieres", "preferís"],
            ["jugar", "juegas", "jugás"],
            ["levantarse", "te levantas", "te levantás"],
          ],
        },
        examples: [
          { es: "¿Vos querés subir al volcán el sábado?", en: "Do you want to climb the volcano on Saturday? (vos)" },
          { es: "¿Podés a las ocho?", en: "Can you make it at eight? (vos)" },
          { es: "¿Y vos qué preferís, cine o fútbol?", en: "And what do you prefer, cinema or football? (vos)" },
        ],
        mistakes: [
          { wrong: "¿Vos quierés ir?", right: "¿Vos querés ir?", why: "Con _vos_ el acento cae en la terminación, así que la raíz no cambia: **querés**." },
        ],
        tip: "Si oyes una forma con tilde al final y sin cambio de vocal (_podés, jugás_), es casi seguro **vos**.",
      },
      {
        heading: "Proponer, aceptar y decir que no",
        body: [
          "Para **proponer** algo a una persona, usa una pregunta con _querer_ o _poder_: **¿Quieres jugar al fútbol?** **¿Puedes el sábado?** Para proponer algo que hacemos juntos, usa **¿Por qué no…?** + verbo con _nosotros_: **¿Por qué no comemos pupusas?**",
          "Para **aceptar**: **¡Sí, claro!**, **¡Buena idea!**, **¡Perfecto!** Cada región tiene su palabra rápida: **¡Va, pues!** en El Salvador y Honduras, **¡Dale!** en Centroamérica y el Río de la Plata, **¡Vale!** en España, **¡Sale!** o **¡Va!** en México.",
          "Para **decir que no** con amabilidad, hay tres pasos: lamentarlo (**Lo siento**), explicar (**es que…**) y proponer otra cosa (**¿Y el domingo?**, **Prefiero…**). Un _no_ sin explicación suena brusco en español.",
          "Para cerrar el plan, confirma el día, la hora y el lugar: _Entonces, el sábado a las ocho. ¿Dónde **está** el parque?_",
        ],
        support: [
          "To suggest: _¿Quieres + infinitive?_ (Do you want to…?), _¿Por qué no + nosotros form?_ (Why don't we…?).",
          "To say no politely: _Lo siento, no puedo. Es que…_ + reason + an alternative. A bare 'no' sounds rude in Spanish.",
          "Regional 'OK!': _¡Va, pues!_ (El Salvador, Honduras), _¡Dale!_ (Central America, Argentina, Uruguay), _¡Vale!_ (Spain), _¡Sale!_ (Mexico).",
        ],
        table: {
          caption: "Fórmulas para quedar con amigos",
          head: ["Proponer", "Aceptar", "Decir que no y proponer otra cosa"],
          rows: [
            ["¿Quieres ir al cine?", "¡Sí, claro!", "Lo siento, no puedo."],
            ["¿Puedes el sábado?", "¡Buena idea!", "Es que trabajo hasta las cinco."],
            ["¿Por qué no jugamos al fútbol?", "¡Perfecto! ¿A qué hora?", "¿Y el domingo?"],
            ["¿Vos querés venir? (voseo)", "¡Va, pues! / ¡Dale!", "Prefiero ver una película."],
          ],
        },
        examples: [
          { es: "—¿Quieres jugar al básquetbol el sábado? —¡Sí, claro! ¿A qué hora?", en: "—Do you want to play basketball on Saturday? —Sure! What time?" },
          { es: "—¿Por qué no comemos pupusas? —¡Va, pues!", en: "—Why don't we eat pupusas? —OK, let's do it! (El Salvador)" },
          { es: "—¿Puedes a las seis? —Lo siento, es que trabajo. ¿Y a las ocho?", en: "—Can you make it at six? —Sorry, I'm working. How about eight?" },
        ],
        mistakes: [
          { wrong: "¿Por qué no comer pupusas?", right: "¿Por qué no comemos pupusas?", why: "Con _¿Por qué no…?_ el verbo se conjuga en **nosotros**: comemos." },
          { wrong: "—¿Quieres venir? —No.", right: "—¿Quieres venir? —Lo siento, no puedo. Es que estudio.", why: "Un _no_ solo suena brusco. Añade _lo siento_ y un motivo con _es que_." },
        ],
      },
    ],
  },
  grammar: {
    intro: "Primero las formas, después las frases completas. Di cada respuesta en voz alta.",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "¿Cambia o no cambia?",
        prompt: "Elige la forma correcta del verbo.",
        items: [
          { q: "Yo no ___ jugar el sábado, trabajo todo el día.", options: ["puedo", "podo", "pudo"], answer: 0, why: "_Poder_ cambia **o → ue** con _yo_: p**ue**do." },
          { q: "Nosotros ___ ver una película de acción.", options: ["queremos", "quieremos", "quiermos"], answer: 0, why: "Con _nosotros_ la raíz no es fuerte: **queremos**, sin cambio." },
          { q: "Mis hermanos ___ al fútbol los domingos.", options: ["juegan", "jugan", "jueguen"], answer: 0, why: "_Ellos_ es una forma «bota»: j**ue**gan." },
          { q: "En el restaurante, Ana siempre ___ pupusas de queso.", options: ["pide", "pede", "piede"], answer: 0, why: "_Pedir_ cambia **e → i**, no e → ie: p**i**de." },
          { q: "¿A qué hora ___ la película?", options: ["empieza", "empeza", "empiezan"], answer: 0, why: "_Empezar_ es **e → ie** y el sujeto es _la película_ (singular): emp**ie**za." },
          { q: "¿Vosotros ___ ir a la playa o a la montaña?", options: ["preferís", "prefierís", "prefieren"], answer: 0, why: "_Vosotros_ no cambia: **preferís**. Esta forma se usa en España." },
        ],
      },
      {
        id: "g2",
        type: "gap",
        title: "Una semana en San Salvador",
        prompt: "Escribe la forma correcta del verbo entre paréntesis.",
        items: [
          { q: "Los sábados yo ___ (dormir) hasta las nueve.", answers: [["duermo"]], why: "_Dormir_ (ue): d**ue**rmo." },
          { q: "¿Tú ___ (entender) el menú de la pupusería?", answers: [["entiendes"]], why: "_Entender_ (ie): ent**ie**ndes." },
          { q: "Carlos ___ (volver) a casa a las once de la noche.", answers: [["vuelve"]], why: "_Volver_ (ue): v**ue**lve." },
          { q: "Nosotras ___ (almorzar) juntas el domingo.", answers: [["almorzamos"]], why: "Con _nosotras_ no hay cambio: **almorzamos**." },
          { q: "El museo ___ (cerrar) a las cinco.", answers: [["cierra"]], why: "_Cerrar_ (ie): c**ie**rra." },
          { q: "¿Ustedes ___ (poder) venir a las tres?", answers: [["pueden"]], why: "_Ustedes_ va como _ellos_: p**ue**den." },
        ],
      },
      {
        id: "g3",
        type: "classify",
        title: "Cuatro familias",
        prompt: "¿Qué cambio tiene cada verbo en la forma de yo?",
        categories: ["e → ie", "o → ue", "u → ue", "e → i"],
        items: [
          { text: "preferir", cat: 0, why: "Yo pref**ie**ro." },
          { text: "pensar", cat: 0, why: "Yo p**ie**nso." },
          { text: "encontrar", cat: 1, why: "Yo enc**ue**ntro." },
          { text: "costar", cat: 1, why: "Cuesta, c**ue**stan: se usa sobre todo en tercera persona." },
          { text: "dormir", cat: 1, why: "Yo d**ue**rmo." },
          { text: "jugar", cat: 2, why: "_Jugar_ es el único verbo u → ue: j**ue**go." },
          { text: "repetir", cat: 3, why: "Yo rep**i**to. Solo verbos en -ir hacen e → i." },
          { text: "servir", cat: 3, why: "Yo s**i**rvo, la comida se s**i**rve." },
        ],
      },
      {
        id: "g4",
        type: "transform",
        title: "Deseo, posibilidad, preferencia",
        prompt: "Reescribe la frase con el verbo indicado + infinitivo.",
        items: [
          { source: "Juego al tenis. (querer)", answers: ["Quiero jugar al tenis.", "Yo quiero jugar al tenis."], why: "_Querer_ se conjuga (quiero) y _jugar_ queda en infinitivo." },
          { source: "¿Vienes a la fiesta? (poder)", answers: ["¿Puedes venir a la fiesta?", "¿Tú puedes venir a la fiesta?"], why: "_Poder_ toma la persona (puedes) y _venir_ va en infinitivo." },
          { source: "Me acuesto temprano. (preferir)", answers: ["Prefiero acostarme temprano.", "Me prefiero acostar temprano.", "Yo prefiero acostarme temprano."], why: "El pronombre _me_ va al final del infinitivo o delante de _prefiero_." },
          { source: "Mis amigos nadan en el lago. (querer)", answers: ["Mis amigos quieren nadar en el lago."], why: "_Ellos_: qu**ie**ren + nadar." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Aprende cada actividad con su verbo: no _fútbol_, sino **jugar al fútbol**; no _cine_, sino **ir al cine**. Así puedes usarla enseguida con _quiero_ o _puedo_.",
    groups: [
      {
        title: "Deporte y movimiento",
        items: [
          { es: "jugar al fútbol", en: "to play football (in Latin America also _jugar fútbol_)" },
          { es: "jugar al básquetbol", en: "to play basketball (_baloncesto_ in Spain)" },
          { es: "nadar en la piscina", en: "to swim in the pool (_alberca_ in Mexico)" },
          { es: "correr en el parque", en: "to run in the park" },
          { es: "andar en bicicleta", en: "to ride a bike (_montar en bici_ in Spain)" },
          { es: "subir al volcán", en: "to climb the volcano" },
          { es: "hacer una caminata", en: "to go hiking (Central America; _hacer senderismo_ in Spain)" },
        ],
      },
      {
        title: "Cultura y descanso",
        items: [
          { es: "ir al cine", en: "to go to the cinema" },
          { es: "ver una película", en: "to watch a film" },
          { es: "ver una serie en casa", en: "to watch a series at home" },
          { es: "ir a un concierto", en: "to go to a concert" },
          { es: "visitar un museo", en: "to visit a museum" },
          { es: "leer un libro", en: "to read a book" },
          { es: "escuchar música", en: "to listen to music" },
          { es: "descansar", en: "to rest" },
        ],
      },
      {
        title: "Con amigos",
        items: [
          { es: "salir con amigos", en: "to go out with friends" },
          { es: "tomar un café", en: "to have a coffee" },
          { es: "comer pupusas", en: "to eat pupusas (El Salvador's favourite dish)" },
          { es: "bailar salsa", en: "to dance salsa" },
          { es: "ir a la playa", en: "to go to the beach" },
          { es: "cocinar juntos", en: "to cook together" },
        ],
      },
      {
        title: "Para quedar",
        items: [
          { es: "el fin de semana / el finde", en: "the weekend / the weekend (informal)" },
          { es: "¿Quieres venir?", en: "Do you want to come?" },
          { es: "¿Puedes el sábado?", en: "Can you make it on Saturday?" },
          { es: "¿A qué hora nos vemos?", en: "What time shall we meet?" },
          { es: "¿Dónde nos vemos?", en: "Where shall we meet?" },
          { es: "Lo siento, no puedo.", en: "Sorry, I can't." },
          { es: "Es que…", en: "The thing is… (to give a reason)" },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "¿Dónde?",
        prompt: "Une cada actividad con el lugar donde normalmente se hace.",
        pairs: [
          { left: "nadar", right: "en la piscina" },
          { left: "ver una película de estreno", right: "en el cine" },
          { left: "jugar al fútbol", right: "en la cancha" },
          { left: "visitar una exposición", right: "en el museo" },
          { left: "tomar un café", right: "en una cafetería" },
          { left: "hacer una caminata", right: "en la montaña" },
        ],
        why: "Aprender la actividad con su lugar te ayuda a proponer planes completos: _¿Quieres nadar en la piscina?_",
      },
      {
        id: "v2",
        type: "gap",
        title: "El verbo justo",
        prompt: "Completa con el verbo del banco. Cada verbo se usa una vez.",
        bank: ["jugar", "andar", "ver", "tomar", "subir", "bailar"],
        items: [
          { q: "¿Quieres ___ un café después de clase?", answers: [["tomar"]], why: "En América se dice **tomar** un café (en España también _tomar_ o _tomarse_)." },
          { q: "Los domingos prefiero ___ en bicicleta por la ciudad.", answers: [["andar"]], why: "**Andar** en bicicleta (América); en España, _montar en bici_." },
          { q: "¿Por qué no vamos a ___ salsa el viernes? Es muy divertido.", answers: [["bailar"]], why: "**Bailar** salsa, cumbia, bachata…" },
          { q: "No puedo ___ al básquetbol hoy, es que trabajo hasta las nueve.", answers: [["jugar"]], why: "Con deportes se usa **jugar al** + deporte." },
          { q: "Esta noche quiero ___ una serie en casa.", answers: [["ver"]], why: "Las series y las películas se **ven**." },
          { q: "¿Puedes ___ al volcán a las ocho de la mañana?", answers: [["subir"]], why: "A una montaña o a un volcán se **sube**." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "Ñ, LL e Y",
    explanation: [
      "La **ñ** es una letra propia del español. Para pronunciarla, apoya la parte central de la lengua contra el paladar duro y deja salir el aire por la nariz. Se parece a la _ny_ de _canyon_, pero es **un solo sonido**: _ma-ña-na_, no _man-ya-na_.",
      "La **n** y la **ñ** distinguen palabras: _cana_ (pelo blanco) y _caña_ (planta), _pena_ y _peña_, _mono_ y _moño_. Si no las separas, cambias el significado.",
      "**LL** e **Y**: en casi todo el mundo hispano suenan igual (este fenómeno se llama **yeísmo**). _Calle_ y _cayó_, _pollo_ y _poyo_ tienen el mismo sonido, parecido a la _y_ de _yes_ pero un poco más fuerte.",
      "Variación real: en Buenos Aires y Montevideo, **ll** e **y** suenan como la _sh_ de _show_ o la _s_ de _vision_: _yo me shamo_. En el habla relajada de El Salvador y Honduras, la **ll** entre vocales puede sonar muy suave o casi desaparecer: _ga(y)ina_, _sía_ por _silla_. Todas estas pronunciaciones son correctas en su región.",
    ],
    support: [
      "ñ ≈ 'ny' in _canyon_, but as one single sound. Practise: _año, señor, España, mañana_.",
      "ll and y sound the same for most speakers ('yeísmo'), close to English 'y' in _yes_ but with more friction. In Argentina and Uruguay they sound like 'sh'. In Central America they can be very soft between vowels.",
      "At the end of a word, **y** is a vowel sound: _hoy, muy, soy_ sound like 'oi', 'mui', 'soi'.",
    ],
    table: {
      head: ["Sonido", "Palabras", "Frase"],
      rows: [
        ["ñ", "año, señor, mañana, montaña", "Mañana subo a la montaña."],
        ["n / ñ", "cana / caña, pena / peña", "La caña es verde."],
        ["ll = y", "calle, playa, lluvia, yo", "Yo me llamo Yolanda."],
        ["y final = vocal", "hoy, muy, soy, rey", "Hoy estoy muy bien."],
      ],
    },
    perceive: {
      id: "p1",
      type: "listen",
      title: "¿N o Ñ?",
      prompt: "Escucha y elige la palabra que oyes. Solo cambia n por ñ.",
      items: [
        { q: "¿Qué palabra oyes?", audio: "caña", options: ["cana", "caña"], answer: 1, why: "**Caña**: la lengua toca el paladar y el sonido es más largo y nasal." },
        { q: "¿Qué palabra oyes?", audio: "mono", options: ["mono", "moño"], answer: 0, why: "**Mono**: n simple, la punta de la lengua toca detrás de los dientes." },
        { q: "¿Qué palabra oyes?", audio: "soñar", options: ["sonar", "soñar"], answer: 1, why: "**Soñar** = to dream; _sonar_ = to ring / to sound." },
        { q: "¿Qué palabra oyes?", audio: "pena", options: ["pena", "peña"], answer: 0, why: "**Pena** (tristeza): n simple." },
        { q: "¿Qué palabra oyes?", audio: "uña", options: ["una", "uña"], answer: 1, why: "**Uña** = fingernail; _una_ = one / a." },
        { q: "¿Qué palabra oyes?", audio: "Una niña pequeña.", options: ["Una nina pequena.", "Una niña pequeña."], answer: 1, why: "Las dos palabras tienen **ñ**: ni-**ña**, pe-que-**ña**." },
      ],
    },
    produce: [
      { text: "año, señor, mañana, montaña", tip: "Un solo sonido: ma-**ña**-na. No digas _man-ya-na_ con dos sonidos.", voice: "es-MX-f" },
      { text: "Mañana subo a la montaña con la señora Muñoz.", tip: "Cuatro ñ en una frase. Ve despacio y mantén la lengua contra el paladar.", voice: "es-MX-f" },
      { text: "Yo me llamo Yolanda y vivo en la calle Llano.", tip: "Pronuncia **ll** e **y** igual, como la mayoría de hispanohablantes. Después escucha la versión rioplatense: _sho me shamo_.", voice: "es-AR-f" },
      { text: "¿Quieres ir a la playa el domingo? Hoy no puedo.", tip: "_Playa_: y entre vocales. _Hoy_: y final, suena como vocal (oi).", voice: "es-CO-m" },
      { text: "Los niños juegan en la calle hasta las seis.", tip: "Combina ñ (niños), ll (calle) y el cambio u → ue (juegan).", voice: "es-MX-m" },
    ],
    spelling: "La **ñ** siempre se escribe con tilde (virgulilla): si no tienes teclado español, no la cambies por _n_ ni por _ny_. **Ll** e **y** suenan igual para muchas personas, así que hay que aprender la ortografía palabra por palabra: _calle_, _playa_. Al final de palabra, el sonido _i_ se escribe **y**: _hoy, muy, soy_.",
  },
  listening: {
    title: "Un plan para el sábado",
    context: "Karla es salvadoreña. Andrés es colombiano y Lucía es argentina; los dos viven en San Salvador por trabajo. Están en un café de la Colonia Escalón y organizan el fin de semana. Escucha qué quiere hacer cada uno y qué deciden.",
    speakers: [
      { id: "karla", name: "Karla", voice: "es-MX-f", role: "salvadoreña, organiza el plan" },
      { id: "andres", name: "Andrés", voice: "es-CO-m", role: "colombiano" },
      { id: "lucia", name: "Lucía", voice: "es-AR-f", role: "argentina" },
    ],
    script: [
      { speaker: "karla", text: "Bueno, ¿qué quieren hacer el sábado? Yo quiero subir al volcán, al Boquerón." },
      { speaker: "andres", text: "¿Al volcán? ¿A qué hora?" },
      { speaker: "karla", text: "Temprano. ¿Pueden a las seis de la mañana?" },
      { speaker: "andres", text: "¿A las seis? No, no, no. Los sábados me levanto a las nueve. Prefiero jugar al fútbol en el parque." },
      { speaker: "lucia", text: "Yo no juego al fútbol, pero quiero ver la película nueva de Pixar. ¿Vos querés ir al cine, Karla?" },
      { speaker: "karla", text: "El cine, el domingo sí. El sábado prefiero salir de la ciudad." },
      { speaker: "andres", text: "¿Y por qué no subimos al volcán a las ocho? Así duermo un poco más." },
      { speaker: "karla", text: "¡Va, pues! A las ocho. Lucía, ¿vos podés?" },
      { speaker: "lucia", text: "Lo siento, a la mañana no puedo. Es que trabajo hasta las doce." },
      { speaker: "karla", text: "Entonces almorzamos juntos después. ¿Querés comer pupusas?" },
      { speaker: "lucia", text: "¡Dale! ¿Dónde está la pupusería?" },
      { speaker: "karla", text: "Está aquí, en la Colonia Escalón, al lado del parque. ¿Nos vemos a la una?" },
      { speaker: "lucia", text: "Perfecto, a la una. ¿Y el cine el domingo?" },
      { speaker: "andres", text: "¡Buena idea! Yo prefiero la función de las cuatro." },
      { speaker: "karla", text: "Bueno: sábado, volcán a las ocho y pupusas a la una. Domingo, cine a las cuatro." },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: no busques detalles. ¿De qué hablan y cuántos planes hacen?",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha una vez y responde.",
          items: [
            { q: "¿Qué organizan los tres amigos?", options: ["el fin de semana", "un viaje a Colombia", "una fiesta de cumpleaños"], answer: 0, why: "Karla pregunta _¿Qué quieren hacer el sábado?_ y al final repite el plan del sábado y del domingo." },
            { q: "Al final, ¿cuántas actividades deciden?", options: ["una", "dos", "tres"], answer: 2, why: "Volcán, pupusas y cine: tres actividades." },
            { q: "¿Cómo es la conversación?", options: ["Hay problemas, pero encuentran una solución.", "Nadie está de acuerdo y no hay plan.", "Todos quieren lo mismo desde el principio."], answer: 0, why: "Andrés y Lucía dicen que no a algunas cosas, pero proponen otras opciones y cierran un plan." },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: atención a las horas, los motivos y los lugares.",
        exercise: {
          id: "l2",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "¿Por qué Andrés no quiere salir a las seis?", options: ["Porque los sábados se levanta a las nueve.", "Porque trabaja el sábado.", "Porque prefiere ir al cine."], answer: 0, why: "Dice: _Los sábados me levanto a las nueve._" },
            { q: "¿A qué hora suben al volcán?", options: ["a las seis", "a las ocho", "a las nueve"], answer: 1, why: "Andrés propone _¿Por qué no subimos al volcán a las ocho?_ y Karla acepta." },
            { q: "¿Por qué Lucía no puede ir al volcán?", options: ["Trabaja hasta las doce.", "Prefiere dormir.", "Prefiere jugar al fútbol."], answer: 0, why: "_Es que trabajo hasta las doce._" },
            { q: "¿Dónde está la pupusería?", options: ["al lado del parque", "enfrente del cine", "cerca del volcán"], answer: 0, why: "_Está aquí, en la Colonia Escalón, al lado del parque._" },
            { q: "¿Qué función de cine prefiere Andrés?", options: ["la de las cuatro", "la de la una", "la de las ocho"], answer: 0, why: "_Yo prefiero la función de las cuatro._" },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en qué hace cada frase en la conversación.",
        exercise: {
          id: "l3",
          type: "classify",
          prompt: "¿Esta frase propone, acepta o dice que no?",
          categories: ["propone", "acepta", "dice que no"],
          items: [
            { text: "¿Pueden a las seis de la mañana?", cat: 0 },
            { text: "¿Y por qué no subimos al volcán a las ocho?", cat: 0, why: "_¿Por qué no…?_ + nosotros: una propuesta para el grupo." },
            { text: "¡Va, pues! A las ocho.", cat: 1, why: "_¡Va, pues!_ es un «sí» muy salvadoreño." },
            { text: "¡Dale!", cat: 1, why: "Lucía es argentina: _¡Dale!_ = de acuerdo." },
            { text: "Lo siento, a la mañana no puedo.", cat: 2, why: "Fíjate: Lucía dice _a la mañana_ (Argentina); en El Salvador se dice _en la mañana_." },
            { text: "¿A las seis? No, no, no.", cat: 2 },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Agenda del finde · San Salvador",
    genre: "Publicación en redes sociales con comentarios",
    frame: "Una cuenta cultural de San Salvador publica los planes del fin de semana. Debajo, sus seguidores comentan.",
    text: [
      "🌋 **Sábado, 7:00.** Caminata al volcán de San Salvador. Salida desde la Plaza Salvador del Mundo. Puedes llevar agua y gorra. Precio: $5.",
      "⚽ **Sábado, 16:00.** Torneo de fútbol en el Parque Cuscatlán. Equipos de cinco personas: hombres y mujeres pueden jugar juntos.",
      "🎬 **Domingo, 18:00.** Cine en la calle en el Centro Histórico: una película salvadoreña con subtítulos en inglés. La entrada es gratis.",
      "🎶 **Domingo, 20:00.** Concierto de cumbia en la Plaza Libertad. ¿No bailas bien? No importa: la primera hora hay clase para todos.",
      "**@meli.sv:** @josue503 ¿Querés jugar en el torneo? Necesitamos un equipo de cinco 😅",
      "**@josue503:** @meli.sv El sábado no puedo, es que trabajo hasta las cinco. ¿Por qué no vemos la película del domingo?",
      "**@ana_viaja:** Yo soy de Madrid y estoy aquí dos semanas. Prefiero el concierto, pero puedo ir a los dos: ¡la película empieza a las seis y el concierto a las ocho!",
    ],
    glossary: [
      { es: "la salida", en: "departure point / start" },
      { es: "la gorra", en: "cap" },
      { es: "gratis", en: "free (no cost)" },
      { es: "no importa", en: "it doesn't matter" },
      { es: "$5", en: "five dollars: El Salvador uses the US dollar" },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee la agenda y responde.",
        items: [
          { q: "¿Qué actividad cuesta dinero?", options: ["la caminata al volcán", "el cine en la calle", "el concierto de cumbia"], answer: 0, why: "Solo la caminata tiene precio: $5. El cine es _gratis_." },
          { q: "¿Qué actividad es buena para una persona que no sabe bailar?", options: ["el concierto, porque hay clase la primera hora", "el torneo de fútbol", "ninguna"], answer: 0, why: "_La primera hora hay clase para todos._" },
          { q: "¿Por qué Josué no puede jugar en el torneo?", options: ["Trabaja hasta las cinco.", "No tiene equipo.", "Prefiere el concierto."], answer: 0, why: "_Es que trabajo hasta las cinco_, y el torneo empieza a las cuatro." },
          { q: "¿Qué propone Josué?", options: ["ver la película del domingo", "subir al volcán", "bailar cumbia"], answer: 0 },
          { q: "¿Por qué Ana puede ir a la película y al concierto?", options: ["Porque son a horas distintas.", "Porque son el mismo día y a la misma hora.", "Porque no trabaja."], answer: 0, why: "La película empieza a las seis y el concierto a las ocho." },
        ],
      },
      {
        id: "r2",
        type: "classify",
        prompt: "¿Quién escribe cada idea: Meli, Josué o Ana?",
        categories: ["Meli", "Josué", "Ana"],
        items: [
          { text: "Busca personas para un equipo.", cat: 0 },
          { text: "Explica por qué no puede el sábado.", cat: 1 },
          { text: "Está de visita en El Salvador.", cat: 2, why: "_Estoy aquí dos semanas_: es de Madrid." },
          { text: "Propone otra actividad.", cat: 1, why: "_¿Por qué no vemos la película del domingo?_" },
        ],
      },
    ],
    noticing: {
      prompt: "Toca cada frase para ver qué hay detrás.",
      items: [
        { quote: "¿Querés jugar en el torneo?", note: "Voseo salvadoreño: _querés_ = _quieres_. Sin cambio de vocal y con tilde al final." },
        { quote: "es que trabajo hasta las cinco", note: "_Es que_ introduce el motivo de un _no_. Así suena amable." },
        { quote: "¿Por qué no vemos la película del domingo?", note: "Propuesta para el grupo: _¿Por qué no…?_ + verbo en nosotros." },
        { quote: "Prefiero el concierto, pero puedo ir a los dos", note: "_Preferir_ con un sustantivo y _poder_ con un infinitivo." },
        { quote: "la película empieza a las seis", note: "_Empezar_ (e → ie): emp**ie**za. Y la hora con _a las_." },
      ],
    },
  },
  practice: {
    intro: "Ahora todo junto: verbos que cambian, infinitivos, rutinas y planes.",
    exercises: [
      {
        id: "x1",
        type: "context",
        title: "¿Qué respondes?",
        prompt: "Lee el mensaje y elige la respuesta más natural.",
        items: [
          { context: "Tu amiga Paola: «¿Quieres correr en el parque mañana a las seis?» Tú trabajas hasta las siete.", q: "Respondes:", options: ["Lo siento, no puedo. Es que trabajo hasta las siete. ¿Y a las ocho?", "No.", "Sí, puedo correr a las seis."], answer: 0, why: "Dices que no, explicas con _es que_ y propones otra hora." },
          { context: "Tu compañero hondureño: «¿Vos podés jugar al básquetbol el sábado?» Tú estás libre.", q: "Respondes:", options: ["¡Va, pues! ¿A qué hora nos vemos?", "Lo siento, es que no.", "Vos podés."], answer: 0, why: "Aceptas y preguntas por la hora para cerrar el plan." },
          { context: "Quieres proponer al grupo comer juntos el domingo.", q: "Escribes:", options: ["¿Por qué no comemos juntos el domingo?", "¿Por qué no comer juntos el domingo?", "¿Por qué no comen juntos el domingo?"], answer: 0, why: "Propuesta para el grupo: _¿Por qué no…?_ + **nosotros**." },
          { context: "Un amigo te propone ir al cine, pero tú prefieres ir a un concierto.", q: "Dices:", options: ["Mmm, prefiero ir al concierto. ¿Puedes el viernes?", "Prefiero voy al concierto.", "Prefiero a ir al concierto."], answer: 0, why: "_Preferir_ + infinitivo, sin preposición." },
        ],
      },
      {
        id: "x2",
        type: "order",
        title: "Frases completas",
        prompt: "Ordena las palabras.",
        items: [
          { words: ["¿Quieres", "andar", "en", "bicicleta", "el", "domingo?"], alt: ["¿El domingo quieres andar en bicicleta?"], en: "Do you want to ride a bike on Sunday?" },
          { words: ["Los", "sábados", "prefiero", "levantarme", "tarde."], alt: ["Prefiero levantarme tarde los sábados."], en: "On Saturdays I prefer to get up late." },
          { words: ["No", "puedo,", "es", "que", "tengo", "clase."], en: "I can't, I have class, you see." },
          { words: ["¿Por", "qué", "no", "jugamos", "al", "fútbol?"], en: "Why don't we play football?" },
        ],
      },
      {
        id: "x3",
        type: "error",
        title: "Detective de errores",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "Mi hermana no pode venir al concierto.", answers: ["Mi hermana no puede venir al concierto."], why: "_Poder_ cambia o → ue con _ella_: p**ue**de." },
          { sentence: "¿Quieres a tomar un café?", answers: ["¿Quieres tomar un café?"], why: "Entre _querer_ y el infinitivo no va _a_." },
          { sentence: "Nosotros jugamos al fútbol y después volvemos a casa a la seis.", answers: ["Nosotros jugamos al fútbol y después volvemos a casa a las seis.", "Jugamos al fútbol y después volvemos a casa a las seis."], why: "La hora va con **las** (excepto la una): _a las seis_." },
          { sentence: "Ellos prefieren duchar por la noche.", answers: ["Ellos prefieren ducharse por la noche.", "Ellos se prefieren duchar por la noche.", "Prefieren ducharse por la noche."], why: "_Ducharse_ es reflexivo: el pronombre (**se**) no desaparece con el infinitivo." },
          { sentence: "El concierto empeza a las nueve.", answers: ["El concierto empieza a las nueve."], why: "_Empezar_ cambia e → ie: emp**ie**za." },
        ],
      },
      {
        id: "x4",
        type: "gap",
        title: "Un chat para quedar",
        prompt: "Completa el chat entre Diego y Sofía con una forma de querer, poder, preferir o estar.",
        items: [
          { q: "Diego: ¿___ ir al Museo de Arte el sábado?", answers: [["Quieres", "Puedes"]], why: "Para proponer: _¿Quieres…?_ o _¿Puedes…?_ + infinitivo." },
          { q: "Sofía: El sábado no ___, es que me levanto a las cinco para trabajar.", answers: [["puedo"]], why: "_Yo_ + poder: p**ue**do." },
          { q: "Sofía: ___ ir el domingo. ¿A qué hora abre?", answers: [["Prefiero", "Quiero", "Puedo"]], why: "Varias opciones correctas: _prefiero / quiero / puedo_ + ir." },
          { q: "Diego: Abre a las diez. ¿Dónde ___ tu casa? Paso por ti.", answers: [["está"]], why: "Ubicación de algo conocido: **estar**." },
          { q: "Sofía: ___ al lado del supermercado, en la calle Arce. ¡Hasta el domingo!", answers: [["Está"]], why: "_La casa_ → **está**." },
        ],
      },
      {
        id: "x5",
        type: "transform",
        title: "De tú a vos",
        prompt: "Escribe la pregunta como la diría un amigo salvadoreño (con vos).",
        items: [
          { source: "¿Tú quieres venir?", answers: ["¿Vos querés venir?", "¿Querés venir?"], why: "Con vos: **querés**, sin cambio de vocal y con tilde." },
          { source: "¿Puedes el domingo?", answers: ["¿Podés el domingo?", "¿Vos podés el domingo?"], why: "Con vos: **podés**." },
          { source: "¿A qué hora te levantas?", answers: ["¿A qué hora te levantás?", "¿A qué hora te levantás vos?", "¿Vos a qué hora te levantás?"], why: "Reflexivo con vos: **te levantás**." },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe un chat de dos mensajes: tu propuesta para el fin de semana y tu respuesta a la propuesta de un amigo.",
    context: "Estás en San Salvador. Mensaje 1: propones un plan a una amiga. Mensaje 2: tu amigo Josué te propone jugar al fútbol el sábado a las cuatro, pero tú no puedes a esa hora.",
    steps: [
      "Mensaje 1: saluda y propone una actividad con _¿Quieres…?_ o _¿Por qué no…?_",
      "Di el día, la hora y el lugar (_está al lado de…_).",
      "Mensaje 2: responde a Josué con _Lo siento_ y un motivo con _es que_.",
      "Propón otra hora u otro día, o di qué prefieres hacer.",
    ],
    useLanguage: ["¿Quieres + infinitivo?", "¿Por qué no + nosotros?", "Lo siento, no puedo. Es que…", "Prefiero + infinitivo", "a las + hora", "está al lado de / cerca de"],
    model: [
      "**Para Marta:** ¡Hola, Marta! ¿Quieres ver la película salvadoreña el domingo? Es en el Centro Histórico, a las seis. El cine está cerca de la catedral. ¿Puedes?",
      "**Para Josué:** Hola, Josué. Lo siento, a las cuatro no puedo. Es que el sábado almuerzo con mi familia y vuelvo a casa a las cinco. ¿Por qué no jugamos el domingo por la mañana? Prefiero jugar temprano.",
    ],
    checklist: [
      "Uso _querer_, _poder_ o _preferir_ + infinitivo sin preposición.",
      "Los verbos «bota» cambian bien la vocal (_puedo, quiero, almuerzo, vuelvo_).",
      "Mi _no_ tiene un motivo con _es que_.",
      "Escribo la hora con _a las_ y el lugar con _está_.",
      "Propongo una alternativa.",
    ],
    words: [40, 80],
  },
  speaking: {
    intro: "Graba cada tarea. Escucha la grabación y revisa las formas que cambian: quiero, puedo, prefiero.",
    tasks: [
      {
        title: "Mensaje de voz: tu plan del sábado",
        prompt: "Deja un mensaje de voz a un amigo: saluda, propone dos actividades para el sábado (una por la mañana y otra por la tarde), di la hora y dónde está el lugar, y pregunta si puede.",
        prep: ["Hola, ¿qué tal?", "¿Quieres… por la mañana?", "Y por la tarde, ¿por qué no…?", "Es a las… / Está al lado de…", "¿Puedes? ¡Hasta luego!"],
        seconds: 45,
        model: "¡Hola, Andrés! ¿Qué tal? Oye, ¿quieres subir al volcán el sábado por la mañana? Salimos a las ocho de la plaza. Y por la tarde, ¿por qué no comemos pupusas? La pupusería está al lado del parque. ¿Puedes? ¡Hasta luego!",
        selfCheck: ["Digo dos actividades con su verbo (subir al volcán, comer pupusas).", "Digo la hora con _a las_.", "Pronuncio _quieres_ y _puedes_ con el diptongo claro."],
      },
      {
        title: "Decir que no con amabilidad",
        prompt: "Lee estas tres propuestas y responde a cada una en voz alta: di que no puedes, explica por qué y propón otra cosa. (1) «¿Quieres correr a las seis de la mañana?» (2) «¿Puedes venir a mi fiesta el viernes?» (3) «¿Por qué no jugamos al tenis hoy?»",
        prep: ["Lo siento, no puedo.", "Es que + rutina u horario (me levanto…, trabajo…, tengo clase…)", "¿Y…? / Prefiero…"],
        seconds: 40,
        model: "(1) Lo siento, a las seis no puedo, es que me levanto a las siete y media. ¿Y a las ocho? (2) ¡Qué pena! El viernes no puedo, es que trabajo hasta las diez. (3) Hoy no puedo, prefiero descansar. ¿Por qué no jugamos el sábado?",
        selfCheck: ["Cada _no_ tiene un motivo.", "Uso un verbo reflexivo de mi rutina con el pronombre correcto.", "Propongo una alternativa en al menos dos respuestas."],
      },
      {
        title: "La bota en voz alta",
        prompt: "Conjuga en voz alta, sin leer, querer, poder y jugar en todas las personas. Después di una frase verdadera con cada verbo sobre tu semana.",
        seconds: 30,
        model: "Quiero, quieres, quiere, queremos, queréis, quieren. Puedo, puedes, puede, podemos, podéis, pueden. Juego, juegas, juega, jugamos, jugáis, juegan. Este sábado quiero descansar. No puedo salir el viernes. Juego al tenis los martes.",
        selfCheck: ["Nosotros y vosotros no cambian.", "Mis tres frases son verdaderas y tienen hora o día."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo vas a organizar un plan real (o imaginario) con tu profesor o profesora.",
    cards: [
      { move: "Propón", task: "Propón a tu profesor o profesora dos planes para un sábado en San Salvador (o en tu ciudad). Usa una pregunta con _querer_ y otra con _¿Por qué no…?_", phrases: ["¿Quieres… el sábado?", "¿Por qué no… por la tarde?", "Es a las… / Está al lado de…"] },
      { move: "Rechaza", task: "Cuando tu profesor o profesora te proponga algo, di que no una vez con un motivo real de tu rutina y propón otra hora.", phrases: ["Lo siento, no puedo.", "Es que los sábados me levanto…", "¿Y a las…?"] },
      { move: "Negocia", task: "Pónganse de acuerdo en un plan final: día, hora y lugar. Repite el plan al final para confirmarlo.", phrases: ["Prefiero…", "Entonces: el domingo a las…", "¡Perfecto! / ¡Va, pues!"] },
      { move: "Pregunta", task: "Pregunta qué palabra usa tu profesor o profesora para decir «OK» a un plan (vale, dale, va, sale…) y si usa vos o tú con sus amigos.", phrases: ["¿Cómo dices «OK»?", "¿Usas vos o tú?"] },
    ],
    bring: "Lleva tu agenda de esta semana: vas a necesitar horas y días reales.",
  },
  quiz: {
    items: [
      { type: "choice", q: "¿Qué forma es correcta para «nosotros» + dormir?", options: ["dormimos", "duermimos", "duermemos"], answer: 0, why: "Con _nosotros_ no hay cambio de vocal: **dormimos**." },
      { type: "listen", q: "¿Qué dice la persona?", audio: "Lo siento, el viernes no puedo. Es que vuelvo tarde del trabajo.", voice: "es-MX-m", options: ["Acepta el plan del viernes.", "Dice que no y explica por qué.", "Propone otro día."], answer: 1, why: "_Lo siento, no puedo_ + motivo con _es que_. No propone otro día." },
      { type: "gap", q: "¿A qué hora ___ (servir) el desayuno en el hotel?", answers: [["sirven", "sirve"]], why: "_Servir_ (e → i): s**i**rven (ellos, impersonal) o s**i**rve." },
      { type: "gap", q: "Mi hijo ___ (jugar) al béisbol y yo ___ (preferir) nadar.", answers: [["juega"], ["prefiero"]], why: "J**ue**ga (u → ue) y pref**ie**ro (e → ie)." },
      { type: "transform", source: "Me ducho después de correr.", instruction: "Empieza con «Quiero…».", answers: ["Quiero ducharme después de correr.", "Me quiero duchar después de correr."], why: "Reflexivo + infinitivo: _quiero duchar**me**_ o _**me** quiero duchar_." },
      { type: "transform", source: "¿Juegas al fútbol con nosotros?", instruction: "Convierte la pregunta en una propuesta con «¿Por qué no…?» (nosotros).", answers: ["¿Por qué no jugamos al fútbol?", "¿Por qué no jugamos al fútbol juntos?"], why: "_¿Por qué no_ + jugamos (nosotros, sin cambio de vocal)." },
      { type: "order", words: ["¿Ustedes", "pueden", "venir", "a", "las", "siete?"], alt: ["¿Pueden ustedes venir a las siete?", "¿Pueden venir ustedes a las siete?"], why: "Poder conjugado + infinitivo + hora con _a las_." },
      { type: "error", sentence: "Yo quero ver una serie esta noche.", answers: ["Yo quiero ver una serie esta noche.", "Quiero ver una serie esta noche."], why: "_Querer_ cambia e → ie: qu**ie**ro." },
      { type: "error", sentence: "¿Podemos a cocinar juntos el domingo?", answers: ["¿Podemos cocinar juntos el domingo?"], why: "Después de _poder_ va el infinitivo directamente, sin _a_." },
      { type: "choice", q: "Un amigo de Tegucigalpa te dice «¿Vos querés ir al concierto?». ¿Qué significa?", options: ["¿Tú quieres ir al concierto?", "¿Ustedes quieren ir al concierto?", "¿Él quiere ir al concierto?"], answer: 0, why: "_Vos querés_ es la forma de voseo de _tú quieres_." },
      { type: "listen", q: "¿Qué palabra oyes?", audio: "Mañana es mi cumpleaños.", voice: "es-CO-f", options: ["Manana es mi cumpleanos.", "Mañana es mi cumpleaños."], answer: 1, why: "Ma-**ña**-na y cum-ple-**a**-ños: las dos tienen ñ." },
      { type: "open", prompt: "Tu amiga te propone «¿Quieres hacer una caminata el domingo a las siete?». Responde: di que no a esa hora (con un motivo de tu rutina) y propone otra hora y un lugar para verse.", model: "Lo siento, a las siete no puedo. Es que los domingos me levanto a las nueve. ¿Por qué no salimos a las diez? Nos vemos en la plaza, está al lado de mi casa.", checklist: ["Lo siento / no puedo", "es que + rutina con verbo reflexivo", "otra hora con a las", "un lugar con está"] },
    ],
  },
  complete: {
    canNow: [
      "Conjugar verbos con cambio vocálico (quiero, puedo, juego, pido) y saber por qué nosotros no cambia.",
      "Decir qué quiero, qué puedo y qué prefiero hacer con un infinitivo.",
      "Proponer un plan, aceptarlo o decir que no con un motivo y una alternativa.",
      "Reconocer el voseo centroamericano: vos querés, vos podés.",
      "Pronunciar la ñ y saber cómo suenan ll e y en distintos países.",
    ],
    review: [
      "El modelo «bota»: nosotros y vosotros no cambian.",
      "Verbo + infinitivo, sin a: quiero ir, puedo jugar.",
      "Reflexivos con infinitivo: quiero levantarme / me quiero levantar.",
      "Lo siento, no puedo. Es que…",
    ],
  },
  related: [
    { path: "/sistema-verbal/presente-de-indicativo", label: "Sistema verbal · presente de indicativo" },
    { path: "/clase/38", label: "Spanish Mouth Lab · consonantes" },
  ],
};
