import type { Module } from "../../types";

export const a1w17: Module = {
  id: "a1-17",
  level: "a1",
  week: 17,
  kind: "core",
  title: "Mi casa",
  subtitle: "Describir una vivienda con ser, estar y hay, y decir cómo están las personas y las cosas.",
  stop: { place: "Ciudad de Panamá", country: "Panamá" },
  minutes: 75,
  newObjectives: [
    "a1.gram.ser-estar-hay",
    "a1.gram.estar-estados",
    "a1.voc.casa",
    "a1.pron.sinalefa",
    "a1.fun.describir-vivienda",
    "a1.read.anuncio-piso",
  ],
  reviewObjectives: ["a1.gram.ir-a-inf", "a1.gram.marcadores-futuro", "a1.fun.planes-fin-semana", "a1.gram.cuantificadores"],
  prerequisites: ["a1-16"],
  goal: {
    canDo: "Al final de esta semana puedes describir tu casa o el apartamento que buscas: qué hay, dónde está, cómo es y cómo está.",
    canDoEn: "By the end of this week, you can describe your home or the flat you are looking for: what there is, where it is, what it is like and what state it is in.",
    steps: [
      "Aprende a elegir entre **hay**, **estar** y **ser** para hablar de una vivienda.",
      "Usa **estar** + adjetivo para decir cómo estás tú y cómo está tu casa hoy.",
      "Nombra habitaciones, muebles y pisos (primer piso, tercer piso…).",
      "Une las vocales entre palabras: la_amiga, mi_hijo.",
      "Visita un apartamento en Ciudad de Panamá y lee tres anuncios de alquiler.",
      "Describe tu casa en voz alta durante un minuto.",
    ],
  },
  theory: {
    intro: "Para describir una casa en español necesitas tres verbos: **hay**, **estar** y **ser**. No son intercambiables: cada uno responde a una pregunta distinta. Esta semana aprendes a elegir bien, y a usar **estar** para los estados: cansado, contento, sucio, abierto…",
    parts: [
      {
        heading: "Hay, estar y ser: tres preguntas, tres verbos",
        body: [
          "**Hay** responde a la pregunta _¿qué hay?_: presenta algo por primera vez, dice que existe. **Hay dos dormitorios. Hay un balcón. No hay ascensor.** Después de _hay_ va un número, **un / una / unos / unas** o un sustantivo sin artículo. Nunca _el_ o _la_.",
          "**Estar** responde a _¿dónde está?_: dice el lugar de algo que ya conocemos. Por eso lleva **el, la, mi, tu…** delante: **El apartamento está en el centro. La cocina está al lado de la sala. Mi cuarto está en el segundo piso.**",
          "**Ser** responde a _¿cómo es?_: describe las características que forman parte de la cosa. **El apartamento es grande. Es moderno. Es de alquiler.** También sirve para identificar: **Esta es la cocina.**",
          "Una descripción natural usa los tres verbos juntos: **Mi casa está en un barrio tranquilo. Es pequeña, pero es muy bonita. Hay una sala, una cocina y dos cuartos.**",
        ],
        support: [
          "_Hay_ = there is / there are. It introduces new things and never changes for plural: _hay un baño, hay dos baños_.",
          "_Estar_ = location of something already known (with _el, la, mi_…). _Ser_ = what something is like (size, style, age, colour) and identification.",
          "Quick test: am I mentioning it for the first time? → **hay**. Do we already know it and I'm saying where? → **está**. Am I describing what it's like? → **es**.",
        ],
        table: {
          caption: "¿Qué verbo necesito?",
          head: ["Pregunta", "Verbo", "Ejemplo"],
          rows: [
            ["¿Qué hay?", "hay (existencia)", "Hay una terraza con plantas."],
            ["¿Dónde está?", "estar (ubicación)", "La terraza está en el último piso."],
            ["¿Cómo es?", "ser (característica)", "La terraza es grande y luminosa."],
            ["¿Cómo está hoy?", "estar (estado)", "La terraza está un poco sucia."],
          ],
        },
        examples: [
          { es: "En mi edificio hay un gimnasio.", en: "In my building there's a gym." },
          { es: "El gimnasio está en la planta baja.", en: "The gym is on the ground floor." },
          { es: "Es pequeño, pero es nuevo.", en: "It's small, but it's new." },
        ],
        mistakes: [
          { wrong: "Hay la cocina a la derecha.", right: "La cocina está a la derecha.", why: "_La cocina_ ya es conocida (lleva _la_): para su lugar usamos **está**, no _hay_." },
          { wrong: "El apartamento es en el centro.", right: "El apartamento está en el centro.", why: "La ubicación va con **estar**." },
          { wrong: "Está un baño en el pasillo.", right: "Hay un baño en el pasillo.", why: "_Un baño_ es información nueva: usamos **hay**." },
        ],
        tip: "Mira el artículo: **un / una** o un número → casi siempre _hay_; **el / la / mi** + lugar → casi siempre _está_.",
      },
      {
        heading: "Estar + adjetivo: cómo estás tú, cómo está la casa",
        body: [
          "Con **estar** + adjetivo decimos el **estado** de una persona o de una cosa en un momento concreto: **Estoy cansada. Estamos contentos. La cocina está sucia. La farmacia está cerrada.**",
          "Con **ser** + adjetivo decimos cómo es algo normalmente: su característica. Compara: **La cocina es pequeña** (siempre, es su tamaño) y **La cocina está sucia** (hoy; mañana puede estar limpia).",
          "El adjetivo concuerda con la persona o la cosa en género y número: **La ventana está abierta. Los cuartos están ordenados. Ana y Luz están cansadas.**",
          "Adjetivos de estado muy útiles. Para personas: **cansado, contento, nervioso, enfermo, aburrido, ocupado**. Para cosas y lugares: **limpio, sucio, ordenado, desordenado, abierto, cerrado, roto, libre**.",
        ],
        support: [
          "_Estar_ + adjective describes a temporary state or condition: how someone feels, or how something is right now (dirty, open, broken).",
          "_Ser_ + adjective describes what something is like in general. _La casa es bonita_ (it's a pretty house) vs _la casa está bonita_ (it looks nice today, e.g. after decorating).",
          "The adjective agrees: _cansado_ (man), _cansada_ (woman), _cansados_ (group with at least one man), _cansadas_ (only women).",
        ],
        table: {
          caption: "El verbo estar",
          head: ["Persona", "Estar", "Ejemplo"],
          rows: [
            ["yo", "estoy", "Estoy muy cansado."],
            ["tú / vos", "estás", "¿Estás contenta con tu casa?"],
            ["usted, él, ella", "está", "La puerta está abierta."],
            ["nosotros, nosotras", "estamos", "Estamos ocupados hoy."],
            ["vosotros, vosotras (España)", "estáis", "¿Estáis cansados?"],
            ["ustedes, ellos, ellas", "están", "Las sillas están rotas."],
          ],
        },
        examples: [
          { es: "Hoy estoy contenta: mi nuevo apartamento está listo.", en: "Today I'm happy: my new flat is ready." },
          { es: "¿Por qué está abierta la ventana?", en: "Why is the window open?" },
          { es: "Los platos están sucios.", en: "The dishes are dirty." },
        ],
        mistakes: [
          { wrong: "La ventana es abierta.", right: "La ventana está abierta.", why: "_Abierta_ es un estado (ahora): va con **estar**." },
          { wrong: "Las sillas están sucios.", right: "Las sillas están sucias.", why: "_Sillas_ es femenino plural: suci**as**." },
          { wrong: "Soy cansado hoy.", right: "Estoy cansado hoy.", why: "Cómo te sientes hoy es un estado: **estoy**." },
        ],
        tip: "Si puedes añadir **hoy** o **ahora** y la frase tiene sentido, probablemente necesitas **estar**: _Hoy la casa está desordenada._",
      },
      {
        heading: "Las partes de la casa y los pisos",
        body: [
          "Las palabras de la casa cambian según el país. Una vivienda en un edificio es un **piso** en España, un **apartamento** en Panamá, Colombia, Venezuela o el Caribe y un **departamento** en México, Argentina, Chile o Perú. El cuarto para dormir es el **dormitorio**, la **habitación** o el **cuarto**; en México, también la **recámara**. La sala de estar es el **salón** en España y la **sala** en América.",
          "Para el número del piso usamos ordinales: **primero, segundo, tercero, cuarto, quinto, sexto, séptimo, octavo, noveno, décimo**. Delante de un sustantivo masculino, _primero_ y _tercero_ pierden la **-o**: **el primer piso, el tercer piso**. Con un sustantivo femenino concuerdan: **la primera planta, la tercera puerta**.",
          "Atención: en España, el nivel de la calle es la **planta baja** y el **primer piso** está encima. En muchos países de América, el **primer piso** es el de la calle. Cuando no estés seguro, pregunta: **¿Es el piso de la calle?**",
        ],
        support: [
          "Ordinals agree like adjectives: _primero / primera_. Before a masculine noun: _primer piso, tercer piso_ (not _primero piso_).",
          "In Spain people often drop the noun: _Vivo en el tercero_ = I live on the third floor.",
        ],
        table: {
          caption: "Los ordinales del 1 al 10",
          head: ["Número", "Masculino", "Femenino", "Ejemplo"],
          rows: [
            ["1.º / 1.ª", "primero (primer)", "primera", "el primer piso"],
            ["2.º / 2.ª", "segundo", "segunda", "la segunda puerta"],
            ["3.º / 3.ª", "tercero (tercer)", "tercera", "el tercer piso"],
            ["4.º / 4.ª", "cuarto", "cuarta", "el cuarto piso"],
            ["5.º – 7.º", "quinto, sexto, séptimo", "quinta, sexta, séptima", "el séptimo piso"],
            ["8.º – 10.º", "octavo, noveno, décimo", "octava, novena, décima", "el décimo piso"],
          ],
        },
        examples: [
          { es: "Vivo en el tercer piso, puerta B.", en: "I live on the third floor, door B." },
          { es: "En mi apartamento hay dos recámaras y una sala pequeña.", en: "In my flat there are two bedrooms and a small living room. (Mexico)" },
        ],
        mistakes: [
          { wrong: "Vivo en el tercero piso.", right: "Vivo en el tercer piso.", why: "Delante de un sustantivo masculino: **tercer**, sin -o." },
          { wrong: "Está en la primer planta.", right: "Está en la primera planta.", why: "_Planta_ es femenino: **primera**. Solo el masculino pierde la -o." },
        ],
      },
      {
        heading: "Describir una vivienda paso a paso",
        body: [
          "Para describir tu casa (o la casa que buscas) sigue un orden sencillo: **qué es** y **dónde está** → **cómo es** → **qué hay** → **tu opinión** → **un plan**.",
          "Para tu opinión, recicla los cuantificadores: **tiene bastante luz**, **hay demasiado ruido**, **es un poco caro**, **no hay nada de espacio**. Para el plan, usa **ir a** + infinitivo: **El sábado voy a comprar una mesa nueva.**",
          "Con **tener** dices lo mismo que con _hay_, pero desde la casa: **El apartamento tiene dos baños** = **En el apartamento hay dos baños.**",
          "Si buscas vivienda, estas frases te sirven: **Busco un apartamento con dos dormitorios. ¿Está amueblado? ¿Tiene ascensor? ¿Cuánto cuesta al mes?**",
        ],
        support: [
          "A good description moves from outside to inside: type and location, general description, rooms, your opinion, and a plan.",
          "_Tener_ and _hay_ can express the same idea: _the flat has two bathrooms_ / _there are two bathrooms in the flat_.",
        ],
        examples: [
          { es: "Vivo en un apartamento pequeño. Está en el centro, cerca del metro.", en: "I live in a small flat. It's in the centre, near the metro." },
          { es: "Es viejo, pero tiene mucha luz. Hay una sala, una cocina y un dormitorio.", en: "It's old, but it gets a lot of light. There's a living room, a kitchen and a bedroom." },
          { es: "Hay demasiado ruido por la noche. Este verano voy a buscar otro.", en: "There's too much noise at night. This summer I'm going to look for another one." },
        ],
        tip: "Prepara tu descripción una vez y úsala muchas veces: en clase, en un intercambio o cuando buscas alojamiento.",
      },
    ],
  },
  grammar: {
    intro: "Primero eliges el verbo; después haces concordar el adjetivo.",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "¿Hay, está o es?",
        prompt: "Elige el verbo correcto para cada frase.",
        items: [
          { q: "En mi calle ___ una panadería muy buena.", options: ["hay", "está", "es"], answer: 0, why: "_Una panadería_ es información nueva: **hay**." },
          { q: "La panadería ___ al lado del banco.", options: ["hay", "está", "es"], answer: 1, why: "_La panadería_ ya es conocida y decimos dónde: **está**." },
          { q: "Mi dormitorio ___ pequeño, pero muy cómodo.", options: ["hay", "está", "es"], answer: 2, why: "Tamaño = característica: **es**." },
          { q: "¿___ ascensor en tu edificio?", options: ["Hay", "Está", "Es"], answer: 0, why: "Preguntamos si existe: **¿Hay ascensor?**, sin artículo." },
          { q: "¿Dónde ___ el baño, por favor?", options: ["hay", "está", "es"], answer: 1, why: "_¿Dónde?_ + cosa conocida (_el baño_): **está**." },
          { q: "Este ___ mi cuarto. Pasa, pasa.", options: ["hay", "está", "es"], answer: 2, why: "Identificamos una cosa: **Este es** mi cuarto." },
        ],
      },
      {
        id: "g2",
        type: "gap",
        title: "Estados de hoy",
        prompt: "Completa con **estar** y el adjetivo bien concordado. Usa las palabras del banco.",
        bank: ["cansado", "sucio", "abierto", "contento", "roto"],
        items: [
          { q: "Mis hermanas ___ muy ___: hoy trabajan doce horas.", answers: [["están"], ["cansadas"]], why: "Ellas → **están**; femenino plural → cansad**as**." },
          { q: "Después de la cena, los platos ___ ___.", answers: [["están"], ["sucios"]], why: "_Los platos_ → **están** suci**os** (masculino plural)." },
          { q: "¿La farmacia ___ ___ el domingo?", answers: [["está"], ["abierta"]], why: "_La farmacia_ → **está** abiert**a**." },
          { q: "Yo ___ muy ___ con mi nuevo apartamento.", answers: [["estoy"], ["contento", "contenta"]], why: "Yo → **estoy**. El adjetivo concuerda contigo: content**o** o content**a**." },
          { q: "El aire acondicionado ___ ___ y hace mucho calor.", answers: [["está"], ["roto"]], why: "_El aire acondicionado_ (masculino singular) → **está** rot**o**." },
        ],
      },
      {
        id: "g3",
        type: "classify",
        title: "¿Cómo es o cómo está?",
        prompt: "¿Qué describe cada frase: una característica (ser) o un estado de ahora (estar)?",
        categories: ["característica → ser", "estado ahora → estar"],
        items: [
          { text: "La cocina ___ moderna.", cat: 0, why: "El estilo de la cocina no cambia de un día a otro: **es** moderna." },
          { text: "La cocina ___ desordenada después de la fiesta.", cat: 1, why: "_Después de la fiesta_: un estado temporal → **está**." },
          { text: "El edificio ___ muy alto.", cat: 0, why: "La altura es una característica: **es** alto." },
          { text: "Hoy Marcos ___ nervioso: tiene una entrevista.", cat: 1, why: "_Hoy_ + emoción = estado: **está** nervioso." },
          { text: "La puerta del balcón ___ cerrada.", cat: 1, why: "Abierta o cerrada son estados: **está**." },
          { text: "Mi barrio ___ tranquilo y bonito.", cat: 0, why: "Describimos cómo es el barrio en general: **es**." },
        ],
      },
      {
        id: "g4",
        type: "transform",
        title: "De nuevo a conocido",
        prompt: "La primera frase presenta algo con **hay**. Ahora ya lo conocemos: escribe dónde **está**.",
        items: [
          { source: "Hay un sofá en la sala.", instruction: "Empieza con «El sofá…».", answers: ["El sofá está en la sala."], why: "Algo ya conocido (_el sofá_) + lugar → **está**." },
          { source: "Hay una lavadora en la terraza.", instruction: "Empieza con «La lavadora…».", answers: ["La lavadora está en la terraza."], why: "_La lavadora_ ya es conocida: **está** en la terraza." },
          { source: "Hay dos baños en el pasillo.", instruction: "Empieza con «Los baños…».", answers: ["Los baños están en el pasillo.", "Los dos baños están en el pasillo."], why: "Plural: _los baños_ → **están**." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Aprende las palabras dentro de frases y fíjate en las variantes de cada país.",
    groups: [
      {
        title: "Las habitaciones",
        items: [
          { es: "Vemos la tele en **la sala** (América) / **el salón** (España).", en: "We watch TV in the living room." },
          { es: "Cocino en **la cocina** todos los días.", en: "I cook in the kitchen every day." },
          { es: "Comemos en **el comedor** los domingos.", en: "We eat in the dining room on Sundays." },
          { es: "**El dormitorio** / **la habitación** / **el cuarto** / **la recámara** (México)", en: "the bedroom" },
          { es: "**El baño** está al final del pasillo.", en: "The bathroom is at the end of the corridor." },
          { es: "**El pasillo** es largo y estrecho.", en: "The corridor is long and narrow." },
          { es: "Desayuno en **el balcón**.", en: "I have breakfast on the balcony." },
          { es: "En **la terraza** hay plantas.", en: "There are plants on the terrace / roof terrace." },
        ],
      },
      {
        title: "Muebles y aparatos",
        items: [
          { es: "**el sofá** de la sala", en: "the living-room sofa" },
          { es: "**una cama** doble", en: "a double bed" },
          { es: "**el armario** (España) / **el clóset** (América)", en: "the wardrobe / closet" },
          { es: "**una mesa** y cuatro **sillas**", en: "a table and four chairs" },
          { es: "**una estantería** (España) / **un librero** (México)", en: "a bookcase" },
          { es: "**la nevera** / **la refrigeradora** (Panamá, Perú) / **la heladera** (Río de la Plata)", en: "the fridge" },
          { es: "**la lavadora** está en la cocina", en: "the washing machine is in the kitchen" },
          { es: "**el aire acondicionado**", en: "the air conditioning" },
        ],
      },
      {
        title: "El edificio",
        items: [
          { es: "**un apartamento** (Panamá, Colombia) / **un piso** (España) / **un departamento** (México, Argentina)", en: "a flat / apartment" },
          { es: "**la planta baja**", en: "the ground floor" },
          { es: "Vivo en **el primer piso**.", en: "I live on the first floor." },
          { es: "**el ascensor** (España) / **el elevador** (México, Panamá)", en: "the lift / elevator" },
          { es: "subir **las escaleras**", en: "to go up the stairs" },
          { es: "**el último piso**", en: "the top floor" },
        ],
      },
      {
        title: "Describir una vivienda",
        items: [
          { es: "Es muy **luminoso**: tiene mucha luz.", en: "It's very bright: it gets a lot of light." },
          { es: "Es un barrio **tranquilo**.", en: "It's a quiet neighbourhood." },
          { es: "La calle es muy **ruidosa**.", en: "The street is very noisy." },
          { es: "**Está amueblado**: hay cama, mesa y sofá.", en: "It's furnished: there's a bed, a table and a sofa." },
          { es: "Es muy **céntrico**: está cerca de todo.", en: "It's very central: it's close to everything." },
          { es: "**Se alquila** apartamento.", en: "Flat for rent." },
          { es: "Tiene **vista al mar**.", en: "It has a sea view." },
          { es: "¿Cuánto cuesta **el alquiler** al mes?", en: "How much is the rent per month?" },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "Cada cosa en su sitio",
        prompt: "Une cada mueble o aparato con la habitación donde normalmente está.",
        pairs: [
          { left: "la cama", right: "el dormitorio" },
          { left: "la nevera", right: "la cocina" },
          { left: "el sofá", right: "la sala" },
          { left: "la ducha", right: "el baño" },
          { left: "la mesa grande y las sillas", right: "el comedor" },
        ],
        why: "Cada mueble tiene su habitación típica: así puedes decir _La cama está en el dormitorio_, _Hay una nevera en la cocina_…",
      },
      {
        id: "v2",
        type: "context",
        title: "La palabra del lugar",
        prompt: "Lee la situación y elige la palabra más natural en ese país.",
        items: [
          { context: "Estás en Madrid y buscas casa.", q: "Le escribes a una agencia:", options: ["Busco un piso con dos habitaciones.", "Busco una recámara con elevador.", "Busco una heladera con sala."], answer: 0, why: "En España se dice **piso** y **habitación**. _Recámara_ y _elevador_ son de México." },
          { context: "Una amiga de Ciudad de México te enseña su casa.", q: "Ella dice:", options: ["Esta es mi heladera.", "Este es mi salón de clases.", "Esta es mi recámara."], answer: 2, why: "En México el dormitorio es la **recámara**. _Heladera_ es la nevera en Argentina y Uruguay." },
          { context: "En un edificio de Panamá. El apartamento está en el piso 3.", q: "El agente dice:", options: ["Está en el tercero piso.", "Está en el tercer piso.", "Está en el tres piso."], answer: 1, why: "Ordinal masculino delante del sustantivo: **tercer** piso." },
          { context: "Tu casa tiene muchas ventanas y mucho sol.", q: "Dices:", options: ["Es muy ruidosa.", "Está muy amueblada.", "Es muy luminosa."], answer: 2, why: "Mucha luz = **luminosa**. _Ruidosa_ es con mucho ruido." },
        ],
      },
      {
        id: "v3",
        type: "gap",
        title: "Ordinales",
        prompt: "Escribe el ordinal correcto en letras.",
        items: [
          { q: "Vivo en el ___ piso (1) y no necesito el ascensor.", answers: [["primer"]], why: "Delante de _piso_ (masculino): **primer**." },
          { q: "Mi oficina está en la ___ planta (2).", answers: [["segunda"]], why: "_Planta_ es femenino: **segunda**." },
          { q: "Es la ___ puerta (3) a la izquierda.", answers: [["tercera"]], why: "_Puerta_ es femenino: **tercera** (aquí no se pierde la -a)." },
          { q: "El gimnasio está en el ___ piso (8).", answers: [["octavo"]], why: "8.º = **octavo**." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "Ritmo y sinalefa: la_amiga, mi_hijo",
    explanation: [
      "La semana pasada uniste consonante + vocal (los_amigos). Esta semana unimos **vocal + vocal**. Cuando una palabra termina en vocal y la siguiente empieza por vocal, las dos vocales van en la **misma sílaba**. Se llama **sinalefa**: _la amiga_ no suena «la · a-mi-ga», sino **la_a-mi-ga**, con tres golpes.",
      "La **h** no suena, así que también hay sinalefa en **mi_hijo**, **la_habitación**, **su_hermano**: las vocales se tocan.",
      "Si las dos vocales son iguales, casi se funden en una sola, un poco más larga: **está_abierta**, **la_amiga**. Si son distintas, pasas de una a otra sin parar: **mi_apartamento**, **todo_está**.",
      "Por eso el español suena tan continuo: dentro de una frase no hay pausas entre palabras, y cada sílaba dura más o menos lo mismo. Si separas cada palabra, tu español suena lento y cortado.",
      "En el habla caribeña, también en Panamá, la **-s** final se aspira o desaparece muchas veces (_los amigos_ → «loh amigo»). Por eso allí aparecen todavía más vocales juntas. No necesitas imitarlo, pero es bueno reconocerlo.",
    ],
    support: [
      "Sinalefa = linking a final vowel to the next initial vowel in one syllable. _La amiga_ has 3 beats, not 4. The letter h is silent, so _mi hijo_ links too.",
      "Same vowels merge into one slightly longer vowel; different vowels glide into each other. Don't insert a pause or a glottal stop between the words.",
    ],
    table: {
      caption: "Cuenta los golpes",
      head: ["Frase", "Palabra por palabra", "Con sinalefa"],
      rows: [
        ["la amiga", "la · a · mi · ga (4)", "la_a · mi · ga (3)"],
        ["mi hijo", "mi · hi · jo (3)", "mi_hi · jo (2)"],
        ["está abierta", "es · tá · a · bier · ta (5)", "es · tá_a · bier · ta (4)"],
        ["todo está limpio", "to · do · es · tá · lim · pio (6)", "to · do_es · tá · lim · pio (5)"],
      ],
    },
    perceive: {
      id: "p1",
      type: "listen",
      title: "¿Cuántos golpes oyes?",
      prompt: "Escucha la frase a velocidad normal. ¿Cuántas sílabas suenan?",
      items: [
        { q: "¿Cuántas sílabas oyes?", audio: "su hermano", options: ["3: su_her · ma · no", "4: su · her · ma · no"], answer: 0, why: "La h no suena: **su_her**-ma-no, con sinalefa." },
        { q: "¿Cuántas sílabas oyes?", audio: "una casa amarilla", options: ["8: u · na · ca · sa · a · ma · ri · lla", "7: u · na · ca · sa_a · ma · ri · lla"], answer: 1, why: "_casa_ + _amarilla_: dos **a** juntas se funden." },
        { q: "¿Cuántas sílabas oyes?", audio: "mi apartamento", options: ["5: mia · par · ta · men · to", "6: mi · a · par · ta · men · to"], answer: 0, why: "La **i** y la **a** van en la misma sílaba: **mia**-par-ta-men-to." },
        { q: "¿Cuántas sílabas oyes?", audio: "la ventana está abierta", options: ["9: la · ven · ta · na · es · tá · a · bier · ta", "7: la · ven · ta · na_es · tá_a · bier · ta"], answer: 1, why: "Dos sinalefas: **na_es** y **tá_a**." },
        { q: "¿Cuántas sílabas oyes?", audio: "Esta es la entrada.", options: ["5: es · ta_es · la_en · tra · da", "7: es · ta · es · la · en · tra · da"], answer: 0, why: "**ta_es** y **la_en**: el ritmo se hace continuo." },
        { q: "¿Cuántas sílabas oyes?", audio: "Todo está ordenado.", options: ["8: to · do · es · tá · or · de · na · do", "6: to · do_es · tá_or · de · na · do"], answer: 1, why: "**do_es** y **tá_or**: vocal final + vocal inicial, siempre unidas." },
      ],
    },
    produce: [
      { text: "Mi hijo está en la habitación.", tip: "Tres uniones: **mi_hi**jo, está_en, **la_ha**bitación. Sin pausas.", voice: "es-MX-f" },
      { text: "La cocina está abierta y ordenada.", tip: "cocina_es-tá_a-bier-ta_y_or-de-na-da: una sola línea de voz.", voice: "es-CO-m" },
      { text: "Esta es la entrada; a la izquierda está el baño.", tip: "**ta_es**, **la_en**, **a_la**, **la_iz**: practica despacio y después a velocidad normal.", voice: "es-ES-f" },
      { text: "Todo está limpio, pero estoy un poco cansada.", tip: "do_es, pe-ro_es-toy, un po-co can-sa-da: cuenta los golpes con la mano.", voice: "es-VE-m" },
    ],
    spelling: "La sinalefa no se escribe: el espacio entre palabras sigue ahí, pero no se oye. La **h** inicial tampoco suena, así que no impide la unión: _la_habitación_.",
  },
  listening: {
    title: "Un apartamento en San Francisco",
    context: "Sofía, una argentina que va a trabajar en Ciudad de Panamá, visita un apartamento de alquiler en el barrio de San Francisco con su amigo Jordi, de Barcelona. Rubén, el agente, les enseña el apartamento.",
    speakers: [
      { id: "ruben", name: "Rubén", voice: "es-VE-m", role: "agente inmobiliario" },
      { id: "sofia", name: "Sofía", voice: "es-AR-f", role: "busca apartamento" },
      { id: "jordi", name: "Jordi", voice: "es-ES-m", role: "amigo de Sofía" },
    ],
    script: [
      { speaker: "ruben", text: "Buenas tardes, bienvenidos. El apartamento está en el octavo piso, pero tranquilos: hay elevador." },
      { speaker: "sofia", text: "¡Menos mal! Estoy un poco cansada. ¿Es muy grande?" },
      { speaker: "ruben", text: "Es bastante grande. Hay una sala, una cocina, dos recámaras… perdón, dos dormitorios, y dos baños." },
      { speaker: "jordi", text: "¡Qué salón tan luminoso! Bueno, aquí decís «sala», ¿no? Tiene mucha luz." },
      { speaker: "ruben", text: "Sí, y desde el balcón hay vista al mar." },
      { speaker: "sofia", text: "La cocina es pequeña, pero está muy limpia. ¿Está amueblado?" },
      { speaker: "ruben", text: "Sí. Hay sofá, camas, una mesa y una refrigeradora nueva. Pero la lavadora está rota. El dueño va a comprar una nueva la semana que viene." },
      { speaker: "jordi", text: "Hay un poco de ruido, ¿no? Hay demasiados coches en la avenida." },
      { speaker: "ruben", text: "Sí, hay muchos carros de día, pero con las ventanas cerradas no hay casi nada de ruido." },
      { speaker: "sofia", text: "¿Y cuánto cuesta el alquiler al mes?" },
      { speaker: "ruben", text: "Novecientos dólares al mes, con agua incluida." },
      { speaker: "sofia", text: "Mmm, es un poco caro para mí." },
      { speaker: "jordi", text: "Sofía, el sábado vamos a ver otro en el Casco Viejo, ¿te acuerdas?" },
      { speaker: "sofia", text: "Sí, me acuerdo, pero este me gusta mucho. Rubén, ¿puedo volver mañana por la mañana?" },
      { speaker: "ruben", text: "Claro que sí. Mañana a las diez estoy aquí." },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: la idea general. No te preocupes por todos los detalles.",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha una vez y responde.",
          items: [
            { q: "¿Qué hacen Sofía y Jordi?", options: ["Visitan un apartamento para alquilar.", "Compran muebles para su casa.", "Limpian el apartamento de Rubén."], answer: 0, why: "Rubén les enseña el apartamento y Sofía pregunta por el alquiler." },
            { q: "¿Qué piensa Sofía al final?", options: ["No le gusta nada.", "Es perfecto y barato.", "Le gusta, pero es un poco caro."], answer: 2, why: "Dice _es un poco caro para mí_, pero también _este me gusta mucho_." },
            { q: "¿Qué va a hacer Sofía?", options: ["Comprar el apartamento hoy.", "Volver a ver el apartamento mañana.", "Vivir con Rubén."], answer: 1, why: "Pregunta: _¿puedo volver mañana por la mañana?_" },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: datos concretos del apartamento.",
        exercise: {
          id: "l2",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "¿En qué piso está el apartamento?", options: ["en el tercer piso", "en el octavo piso", "en el último piso"], answer: 1, why: "Rubén dice: _está en el octavo piso_." },
            { q: "¿Cuántos dormitorios hay?", options: ["uno", "dos", "tres"], answer: 1, why: "_Dos recámaras… perdón, dos dormitorios_." },
            { q: "¿Qué está roto?", options: ["la refrigeradora", "el elevador", "la lavadora"], answer: 2, why: "_La lavadora está rota_; la refrigeradora es nueva." },
            { q: "¿Cuánto cuesta al mes?", options: ["700 dólares", "900 dólares", "1900 dólares"], answer: 1, why: "_Novecientos dólares al mes_." },
            { q: "¿Cuándo van a ver otro apartamento?", options: ["el sábado", "mañana a las diez", "la semana que viene"], answer: 0, why: "Jordi: _el sábado vamos a ver otro en el Casco Viejo_." },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en los verbos ser, estar y hay.",
        exercise: {
          id: "l3",
          type: "classify",
          prompt: "¿Para qué usa cada frase el verbo?",
          categories: ["hay: qué existe", "estar: dónde está", "ser: cómo es", "estar: cómo está ahora"],
          items: [
            { text: "Hay una sala, una cocina…", cat: 0, why: "Presenta las habitaciones por primera vez: **hay**." },
            { text: "El apartamento está en el octavo piso.", cat: 1, why: "Ubicación de algo conocido: **está**." },
            { text: "Es bastante grande.", cat: 2, why: "Tamaño: característica → **es**." },
            { text: "La cocina está muy limpia.", cat: 3, why: "Limpia es un estado: **está**." },
            { text: "La lavadora está rota.", cat: 3, why: "_Rota_ es un estado (se puede arreglar): **está**." },
            { text: "La cocina es pequeña.", cat: 2, why: "Tamaño de la cocina: **es**." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Se alquila · Ciudad de Panamá",
    genre: "Anuncios de vivienda",
    frame: "Tres anuncios en una web de alquileres de Ciudad de Panamá. Los precios están en dólares, la moneda que se usa en Panamá junto con el balboa.",
    text: [
      "**A · Apartamento en El Cangrejo · 650 dólares/mes.** Apartamento de un dormitorio y un baño, amueblado. Está en el segundo piso de un edificio pequeño; no hay elevador. Es muy céntrico: hay supermercados, restaurantes y una estación de metro cerca. Ideal para una persona.",
      "**B · Apartamento familiar en Costa del Este · 1400 dólares/mes.** Tres dormitorios, dos baños, cocina grande y lavandería. Está en el piso 15 y tiene vista al mar. El edificio tiene piscina y seguridad 24 horas. No está amueblado. No se aceptan mascotas.",
      "**C · Habitación en casa compartida, Casco Viejo · 400 dólares/mes, todo incluido.** La habitación es pequeña, pero tiene balcón y aire acondicionado. El baño y la cocina son compartidos. La casa es antigua y muy bonita, y la terraza tiene vista a la ciudad. Hay bastante ruido los fines de semana. Se aceptan mascotas.",
    ],
    glossary: [
      { es: "la lavandería", en: "laundry room" },
      { es: "la seguridad 24 horas", en: "24-hour security" },
      { es: "las mascotas", en: "pets" },
      { es: "compartido/a", en: "shared" },
      { es: "todo incluido", en: "bills included" },
    ],
    tasks: [
      {
        id: "r1",
        type: "context",
        title: "¿Qué anuncio es para quién?",
        prompt: "Lee lo que necesita cada persona y elige el mejor anuncio.",
        items: [
          { context: "Marta y Pedro tienen dos hijos. Necesitan espacio y no tienen muebles.", q: "¿Qué anuncio es para ellos?", options: ["A", "B", "C"], answer: 1, why: "B tiene **tres dormitorios** y _no está amueblado_: perfecto si no necesitas muebles." },
          { context: "Kevin es estudiante, tiene un perro y solo puede pagar 450 dólares.", q: "¿Qué anuncio es para él?", options: ["A", "B", "C"], answer: 2, why: "C cuesta 400 dólares y **se aceptan mascotas**. En B no se aceptan." },
          { context: "Lucía trabaja en el centro, va en metro y vive sola. No quiere comprar muebles.", q: "¿Qué anuncio es para ella?", options: ["A", "B", "C"], answer: 0, why: "A es **céntrico**, hay metro cerca y **está amueblado**." },
          { context: "Don Alberto tiene 80 años y no puede subir escaleras.", q: "¿Qué anuncio NO es bueno para él?", options: ["A", "B", "C"], answer: 0, why: "A está en un segundo piso y **no hay elevador**." },
        ],
      },
      {
        id: "r2",
        type: "choice",
        title: "Datos del texto",
        prompt: "Responde según los anuncios.",
        items: [
          { q: "¿Qué apartamento tiene vista al mar?", options: ["el de El Cangrejo", "el de Costa del Este", "la casa del Casco Viejo"], answer: 1, why: "B: _está en el piso 15 y tiene vista al mar_. La casa C tiene vista a la ciudad." },
          { q: "En la casa del Casco Viejo, ¿qué es compartido?", options: ["el balcón", "el baño y la cocina", "el aire acondicionado"], answer: 1, why: "_El baño y la cocina son compartidos_; el balcón es de la habitación." },
          { q: "¿Qué problema tiene la habitación C?", options: ["Es muy cara.", "Hay bastante ruido los fines de semana.", "No tiene ventanas."], answer: 1, why: "El anuncio dice: _Hay bastante ruido los fines de semana_." },
        ],
      },
    ],
    noticing: {
      prompt: "Fíjate en cómo los anuncios usan los tres verbos.",
      items: [
        { quote: "Está en el segundo piso", note: "Ubicación con **estar** y ordinal: _segundo piso_." },
        { quote: "no hay elevador", note: "Negación de existencia: **no hay** + sustantivo sin artículo." },
        { quote: "Es muy céntrico", note: "**Ser** para una característica del lugar." },
        { quote: "No está amueblado", note: "_Amueblado_ es un estado (puede cambiar): **estar**." },
        { quote: "La habitación es pequeña, pero tiene balcón", note: "**Pero** une una desventaja y una ventaja. _Tiene_ = _hay_ desde el punto de vista de la habitación." },
        { quote: "Hay bastante ruido", note: "Un cuantificador de la semana 14: **bastante** + sustantivo." },
      ],
    },
  },
  practice: {
    intro: "Mezcla los verbos de la semana con planes (ir a) y cantidades (bastante, demasiado, un poco de).",
    exercises: [
      {
        id: "x1",
        type: "order",
        title: "Frases de anuncio",
        prompt: "Ordena las palabras.",
        items: [
          { words: ["El", "apartamento", "está", "en", "el", "quinto", "piso."], en: "The flat is on the fifth floor." },
          { words: ["En", "la", "cocina", "hay", "una", "nevera", "nueva."], alt: ["Hay una nevera nueva en la cocina."], en: "In the kitchen there's a new fridge." },
          { words: ["Mi", "cuarto", "es", "pequeño,", "pero", "tiene", "mucha", "luz."], en: "My room is small, but it gets a lot of light." },
        ],
      },
      {
        id: "x2",
        type: "error",
        title: "Detective de errores",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "Hay el baño al lado de la cocina.", answers: ["El baño está al lado de la cocina.", "Hay un baño al lado de la cocina."], why: "Con _el baño_ usamos **está**. Si es información nueva: **Hay un baño**." },
          { sentence: "La puerta es cerrada, no podemos entrar.", answers: ["La puerta está cerrada, no podemos entrar."], why: "_Cerrada_ es un estado: **está** cerrada." },
          { sentence: "Mis compañeros de casa están muy contentas.", answers: ["Mis compañeros de casa están muy contentos.", "Mis compañeras de casa están muy contentas."], why: "_Compañeros_ es masculino plural: content**os** (o, si son mujeres, _compañeras… contentas_)." },
          { sentence: "Vivo en el primero piso.", answers: ["Vivo en el primer piso."], why: "Delante de un sustantivo masculino: **primer**." },
        ],
      },
      {
        id: "x3",
        type: "gap",
        title: "Pros y contras",
        prompt: "Completa con un cuantificador del banco. Úsalos todos.",
        bank: ["demasiado", "bastante", "un poco de", "nada de", "poca"],
        items: [
          { q: "La sala es grande y tiene ___ luz. ¡Me encanta!", answers: [["bastante"]], why: "**Bastante** luz = suficiente, una ventaja." },
          { q: "La calle es muy ruidosa: hay ___ ruido para dormir.", answers: [["demasiado"]], why: "**Demasiado** = más de lo necesario, un problema." },
          { q: "El cuarto es oscuro, tiene ___ luz.", answers: [["poca"]], why: "_Luz_ es femenino: **poca** luz." },
          { q: "No hay ___ espacio en el armario: está lleno.", answers: [["nada de"]], why: "**No hay nada de** + sustantivo: cero." },
          { q: "En la terraza hay ___ sol por la tarde, no mucho.", answers: [["un poco de"]], why: "**Un poco de** = una cantidad pequeña, pero positiva." },
        ],
      },
      {
        id: "x4",
        type: "transform",
        title: "Planes para la casa nueva",
        prompt: "Transforma la frase en un plan con **ir a** + infinitivo y el marcador entre paréntesis.",
        items: [
          { source: "Pinto el dormitorio. (el sábado)", answers: ["El sábado voy a pintar el dormitorio.", "Voy a pintar el dormitorio el sábado."], why: "Yo → **voy a** + infinitivo: voy a pintar." },
          { source: "Compramos una mesa para el comedor. (la semana que viene)", answers: ["La semana que viene vamos a comprar una mesa para el comedor.", "Vamos a comprar una mesa para el comedor la semana que viene."], why: "Nosotros → **vamos a** comprar." },
          { source: "Mi hermana limpia la terraza. (mañana)", answers: ["Mañana mi hermana va a limpiar la terraza.", "Mi hermana va a limpiar la terraza mañana."], why: "Ella → **va a** limpiar." },
        ],
      },
      {
        id: "x5",
        type: "open",
        title: "Tu casa en cuatro frases",
        prompt: "Escribe cuatro frases sobre tu casa.",
        items: [
          {
            prompt: "Una frase con **está**, una con **es**, una con **hay** y una con **estar** + estado de hoy.",
            model: "Mi casa está cerca del parque. Es vieja, pero es bonita. Hay dos dormitorios y un balcón. Hoy la cocina está un poco desordenada.",
            checklist: ["Uso **está** para el lugar.", "Uso **es** para cómo es.", "Uso **hay** + un/una o número.", "El adjetivo de estado concuerda."],
          },
          {
            prompt: "Tu amiga Rosa busca apartamento en tu ciudad y te escribe: «¿Cómo es tu barrio? ¿Hay apartamentos baratos?». Respóndele en tres frases: qué hay en tu barrio, cómo es y una opinión con un cuantificador (bastante, demasiado, poco…).",
            model: "¡Hola, Rosa! Mi barrio es tranquilo y está cerca del centro. Hay un mercado, dos parques y bastantes apartamentos de alquiler. El problema: hay poco transporte por la noche.",
            checklist: ["Uso **hay** para lo que existe en el barrio.", "Uso **es** o **está** correctamente.", "Uso un cuantificador que concuerda (bastantes apartamentos, poco transporte)."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe un mensaje a un amigo o una amiga para describir tu casa nueva (o la casa de tus sueños).",
    context: "Tu amiga Daniela, de Bogotá, te escribe: «¿Qué tal la casa nueva? ¡Cuéntame cómo es!».",
    steps: [
      "Saluda y di dónde está la casa.",
      "Di cómo es: tamaño, estilo, luz.",
      "Explica qué hay: habitaciones y muebles importantes.",
      "Di cómo está hoy (limpia, desordenada…) y cómo estás tú.",
      "Termina con un plan para el fin de semana con **ir a**.",
    ],
    useLanguage: ["Está en…", "Es grande / pequeña / luminosa…", "Hay… / Tiene…", "en el primer / segundo / tercer piso", "Estoy cansado/a, contento/a…", "Este fin de semana voy a…"],
    model: [
      "¡Hola, Daniela! La casa nueva está en un barrio tranquilo, cerca del mar. Es un apartamento pequeño, pero es muy luminoso. Está en el cuarto piso y hay elevador.",
      "Hay una sala, una cocina, un dormitorio y un baño. También hay un balcón con plantas. Hoy la sala está un poco desordenada y yo estoy cansada, pero muy contenta. Este fin de semana voy a comprar una estantería. ¡Besos!",
    ],
    checklist: [
      "Uso **está** para la ubicación y **es** para las características.",
      "Uso **hay** con un/una o un número, sin el/la.",
      "Los adjetivos concuerdan (la sala está desordenad**a**).",
      "Uso al menos un ordinal (primer, segundo, tercer piso…).",
      "Termino con un plan con **ir a** + infinitivo.",
    ],
    words: [50, 80],
  },
  speaking: {
    intro: "Habla con frases cortas y une las vocales entre palabras. Grábate y escucha si suena continuo.",
    tasks: [
      {
        title: "Tour por tu casa",
        prompt: "Imagina que haces una videollamada y enseñas tu casa a un amigo. Empieza en la puerta y termina en tu habitación.",
        prep: ["Mi casa / mi apartamento está en…", "Es… y …", "Esta es la sala. Aquí hay…", "La cocina está al lado de…", "Y este es mi cuarto: es pequeño, pero…"],
        seconds: 60,
        model: "Hola, bienvenido a mi apartamento. Está en el tercer piso. Esta es la sala: es pequeña, pero tiene mucha luz. Aquí hay un sofá y una mesa. La cocina está al lado de la sala. Hoy está un poco desordenada, ¡perdón! Al final del pasillo está el baño. Y este es mi cuarto: hay una cama, un armario y una ventana grande.",
        selfCheck: ["Uso hay, está y es sin mezclarlos.", "Uso al menos un ordinal.", "Uno las vocales: _esta_es_, _la_entrada_."],
      },
      {
        title: "¿Cómo estás? ¿Cómo está todo?",
        prompt: "Es domingo por la noche. Un compañero de casa te llama desde el aeropuerto y pregunta cómo estás y cómo está la casa. Responde con cinco estados.",
        prep: ["Yo estoy…", "La cocina está…", "Las plantas están…", "La puerta del balcón está…", "El aire acondicionado está…"],
        seconds: 30,
        model: "Hola, Pablo. Yo estoy bien, un poco cansado. La casa está bastante limpia. Las plantas están perfectas. La puerta del balcón está cerrada, tranquilo. Pero el aire acondicionado está roto otra vez…",
        selfCheck: ["Uso **estar**, no _ser_, para los estados.", "El adjetivo concuerda con cada cosa."],
      },
      {
        title: "Llamas a la agencia",
        prompt: "Has visto el anuncio A (El Cangrejo). Llama a la agencia, preséntate de usted y haz cuatro preguntas sobre el apartamento.",
        prep: ["Buenos días, llamo por el apartamento de…", "¿Está amueblado?", "¿Hay elevador?", "¿Cuánto cuesta al mes?", "¿Puedo verlo… el sábado?"],
        seconds: 45,
        model: "Buenos días. Me llamo Alex y llamo por el apartamento de El Cangrejo. ¿Está amueblado? ¿En qué piso está? ¿Hay elevador? ¿Y cuánto cuesta al mes? El sábado por la mañana estoy libre. Muchas gracias.",
        selfCheck: ["Trato a la agente de usted.", "Hago cuatro preguntas con entonación de pregunta.", "Uso al menos un marcador de futuro."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase, la casa es el tema de conversación. Prepara tu tour con antelación.",
    cards: [
      { move: "Describe", task: "Haz el tour de tu casa en un minuto, sin leer. Tu profesor o profesora va a dibujar el plano mientras hablas.", phrases: ["Mi casa está en…", "Al lado de la cocina está…", "En mi cuarto hay…"] },
      { move: "Pregunta", task: "Pregunta por la casa de tu profesor o profesora: cinco preguntas con hay, está y es.", phrases: ["¿Cómo es tu casa?", "¿Hay balcón?", "¿En qué piso está?", "¿Cómo está tu barrio hoy?"] },
      { move: "Compara", task: "Elige entre dos de los anuncios de la semana y explica por qué con un cuantificador.", phrases: ["El A tiene bastante luz, pero…", "En el C hay demasiado ruido.", "Para mí, el B es perfecto: tiene…"] },
      { move: "Planea", task: "Cuenta un cambio que vas a hacer en tu casa y cuándo.", phrases: ["El fin de semana que viene voy a…", "Dentro de un mes vamos a…"] },
    ],
    bring: "Una foto o un dibujo simple de tu casa, con el nombre de cada habitación.",
  },
  quiz: {
    items: [
      { type: "choice", q: "Estás en la puerta de un edificio y preguntas: «¿___ un supermercado por aquí?»", options: ["Hay", "Está", "Es"], answer: 0, why: "Preguntas si existe, con _un_: **¿Hay un supermercado?**" },
      { type: "choice", q: "«Mi abuela ___ enferma y no puede venir hoy.»", options: ["es", "está", "hay"], answer: 1, why: "_Enferma_ hoy = estado → **está**." },
      { type: "listen", q: "¿Dónde está el apartamento?", audio: "El apartamento está en el sexto piso, al lado del elevador.", voice: "es-CO-f", options: ["en el sexto piso", "en el séptimo piso", "en la planta baja"], answer: 0, why: "_Sexto piso_ = 6.º." },
      { type: "listen", q: "¿Cómo está la cocina?", audio: "La cocina es muy bonita, pero hoy está sucia.", voice: "es-MX-m", options: ["Está limpia.", "Es fea.", "Está sucia."], answer: 2, why: "_Es bonita_ (característica), _pero hoy está sucia_ (estado)." },
      { type: "gap", q: "En el edificio ___ un gimnasio. El gimnasio ___ en la planta baja y ___ pequeño.", answers: [["hay"], ["está"], ["es"]], why: "Nuevo → **hay**; lugar → **está**; característica → **es**." },
      { type: "gap", q: "Hace calor y las ventanas de la sala están ___ (abierto).", answers: [["abiertas"]], why: "_Las ventanas_: femenino plural → abiert**as**." },
      { type: "transform", source: "En el comedor hay una mesa redonda.", instruction: "La mesa ya es conocida. Escribe dónde está, empezando con «La mesa redonda…».", answers: ["La mesa redonda está en el comedor."], why: "Cosa conocida + lugar → **está**." },
      { type: "order", words: ["Este", "verano", "vamos", "a", "pintar", "la", "terraza."], alt: ["Vamos a pintar la terraza este verano."], en: "This summer we're going to paint the terrace." },
      { type: "error", sentence: "Mi oficina es en el décimo piso.", answers: ["Mi oficina está en el décimo piso."], why: "La ubicación va con **estar**." },
      { type: "error", sentence: "En mi barrio están dos parques muy grandes.", answers: ["En mi barrio hay dos parques muy grandes."], why: "Presentamos algo nuevo con número: **hay**." },
      { type: "error", sentence: "Hoy los niños son muy cansados.", answers: ["Hoy los niños están muy cansados."], why: "Un estado de hoy: **están** cansados." },
      { type: "open", prompt: "Describe en tres o cuatro frases el apartamento o la casa que buscas: dónde, cómo, qué hay y cuánto quieres pagar.", model: "Busco un apartamento en el centro, cerca del metro. Quiero un apartamento luminoso y tranquilo. Necesito dos dormitorios y una cocina grande. No puedo pagar más de 700 dólares al mes.", checklist: ["Uso **está** o _en el centro_ para el lugar.", "Uso adjetivos con concordancia.", "Uso **hay** o _con_ + sustantivo para las habitaciones."] },
    ],
  },
  complete: {
    canNow: [
      "Elegir entre **hay**, **está** y **es** para describir una vivienda.",
      "Decir cómo estás y cómo están las cosas con **estar** + adjetivo.",
      "Nombrar habitaciones, muebles y pisos, con variantes de varios países.",
      "Unir vocales entre palabras (sinalefa) para hablar con un ritmo continuo.",
      "Elegir un anuncio de vivienda según tus necesidades.",
    ],
    review: [
      "Hay + un/una/número; el/la + está.",
      "Es pequeña (siempre) / está sucia (hoy).",
      "Primer y tercer delante de un sustantivo masculino.",
      "Ir a + infinitivo para tus planes en casa.",
    ],
  },
  related: [
    { path: "/la-torre-de-las-coordenadas", label: "La Torre de las Coordenadas · preposiciones de lugar" },
    { path: "/el-mercado-de-las-cantidades", label: "El Mercado de las Cantidades · cuantificadores" },
  ],
};
