export type Pair={es:string;en:string};

export type SwissCanton={
  code:string;
  number:string;
  name:string;
  localName:string;
  capital:string;
  region:"norte"|"centro"|"oeste"|"sur"|"este";
  languages:string;
  color:string;
  hook:Pair;
  fact:Pair;
  mission:Pair;
  words:Pair[];
  questions:Pair[];
};

const p=(es:string,en:string):Pair=>({es,en});
const words=(...items:[string,string][])=>items.map(([es,en])=>p(es,en));
const q=(...items:[string,string][])=>items.map(([es,en])=>p(es,en));

export const cantons:SwissCanton[]=[
  {code:"ZH",number:"01",name:"Zúrich",localName:"Zürich",capital:"Zúrich",region:"norte",languages:"alemán",color:"#e24a43",hook:p("La ciudad que trabaja rápido y descansa junto al lago.","The city that works fast and unwinds by the lake."),fact:p("Zúrich es un gran centro financiero, pero sus playas públicas y el lago también forman parte de la vida cotidiana.","Zurich is a major financial centre, but its public swimming areas and lake are also part of everyday life."),mission:p("Diseñá una ciudad exitosa que todavía deje tiempo y espacio para vivir.","Design a successful city that still leaves time and space for living."),words:words(["el alquiler","rent"],["el barrio","neighbourhood"],["el equilibrio","balance"],["el transporte público","public transport"],["la orilla","waterfront"],["el ruido","noise"]),questions:q(
    ["Si trabajaras en Zúrich, ¿pagarías más para vivir cerca del lago o preferirías viajar desde otra ciudad? ¿Por qué?","If you worked in Zurich, would you pay more to live near the lake or commute from another city? Why?"],
    ["¿Qué debería ofrecer un barrio caro para que el precio parezca justo?","What should an expensive neighbourhood offer to make the price feel fair?"],
    ["¿Una ciudad dedicada a los negocios puede tener una vida tranquila? Explicá tu respuesta.","Can a business-focused city have a calm way of life? Explain your answer."],
    ["Los domingos muchas tiendas cierran. ¿Te ayudaría a descansar o te resultaría incómodo?","Many shops close on Sundays. Would that help you rest or be inconvenient?"],
    ["¿Cómo usarías la orilla del lago para mejorar la vida de personas que no tienen mucho dinero?","How would you use the lakefront to improve life for people without much money?"],
    ["¿Preferís una ciudad muy puntual y organizada o una más flexible y espontánea? Comparalas.","Do you prefer a very punctual, organised city or a more flexible, spontaneous one? Compare them."]
  )},
  {code:"BE",number:"02",name:"Berna",localName:"Bern / Berne",capital:"Berna",region:"oeste",languages:"alemán y francés",color:"#d52d47",hook:p("Una capital que no necesita ser la ciudad más grande.","A capital that does not need to be the largest city."),fact:p("Berna es la ciudad federal de Suiza. Su centro medieval tiene kilómetros de arcadas y el río Aar rodea gran parte del casco antiguo.","Bern is Switzerland’s federal city. Its medieval centre has kilometres of arcades, and the Aare River curves around much of the old town."),mission:p("Decidí qué necesita una buena capital para representar a todo un país.","Decide what a good capital needs in order to represent a whole country."),words:words(["la capital","capital city"],["representar","to represent"],["las arcadas","arcades"],["la corriente","current"],["conservar","to preserve"],["el ritmo","pace"]),questions:q(
    ["¿Una capital debe ser la ciudad más grande del país? ¿Qué gana Berna al no serlo?","Should a capital be the country’s largest city? What does Bern gain by not being so?"],
    ["Las arcadas permiten caminar incluso con lluvia. ¿Qué detalle pequeño hace más cómoda tu ciudad?","The arcades make it possible to walk even in the rain. What small detail makes your city more comfortable?"],
    ["Mucha gente nada en el río Aar, que tiene una corriente fuerte. ¿Qué actividad local probarías solo con una persona experta?","Many people swim in the Aare, which has a strong current. What local activity would you try only with an expert?"],
    ["¿Cómo puede una capital representar regiones que hablan idiomas y tienen costumbres diferentes?","How can a capital represent regions that speak different languages and have different customs?"],
    ["¿Qué parte de una ciudad histórica debe conservarse y qué parte puede cambiar?","Which part of a historic city should be preserved, and which part can change?"],
    ["Berna parece más tranquila que otras capitales. ¿Un ritmo lento puede ser una forma de eficiencia?","Bern feels calmer than other capitals. Can a slower pace be a form of efficiency?" ]
  )},
  {code:"LU",number:"03",name:"Lucerna",localName:"Luzern",capital:"Lucerna",region:"centro",languages:"alemán",color:"#ef6c3b",hook:p("La postal perfecta… y la vida detrás de la postal.","The perfect postcard… and the life behind it."),fact:p("Lucerna combina el lago de los Cuatro Cantones, montañas cercanas y el famoso Puente de la Capilla en pleno centro.","Lucerne combines Lake Lucerne, nearby mountains and the famous Chapel Bridge in the city centre."),mission:p("Buscá un equilibrio entre una ciudad hermosa para visitar y cómoda para habitar.","Find a balance between a city that is beautiful to visit and comfortable to live in."),words:words(["la postal","postcard image"],["el visitante","visitor"],["el vecino","resident"],["la temporada","season"],["el patrimonio","heritage"],["el acceso","access"]),questions:q(
    ["¿Cómo cambia una ciudad cuando muchas personas la visitan solo para sacar la misma foto?","How does a city change when many people visit only to take the same photo?"],
    ["Si vivieras junto al lago, ¿qué rutina diaria crearías allí?","If you lived by the lake, what daily routine would you create there?"],
    ["¿Debería haber horarios especiales para los grandes grupos turísticos en el centro?","Should there be special times for large tour groups in the city centre?"],
    ["El Puente de la Capilla fue reconstruido después de un incendio. ¿Reconstruir algo antiguo conserva su historia?","The Chapel Bridge was rebuilt after a fire. Does rebuilding something old preserve its history?"],
    ["¿Elegirías vivir entre un lago y montañas aunque hubiera más lluvia y turistas?","Would you choose to live between a lake and mountains even if there were more rain and tourists?"],
    ["Inventá una experiencia en Lucerna que no dependa de comprar nada.","Invent an experience in Lucerne that does not require buying anything."]
  )},
  {code:"UR",number:"04",name:"Uri",localName:"Uri",capital:"Altdorf",region:"centro",languages:"alemán",color:"#f0a43a",hook:p("Un valle pequeño en una ruta enorme.","A small valley on a huge route."),fact:p("El paso y los túneles del Gotardo conectan el norte y el sur de Europa a través de esta región alpina.","The Gotthard Pass and tunnels connect northern and southern Europe through this Alpine region."),mission:p("Pensá cómo una comunidad pequeña puede recibir los beneficios del tránsito sin cargar con todos sus problemas.","Think about how a small community can gain from transit without carrying all its problems."),words:words(["el túnel","tunnel"],["el tránsito","traffic"],["el valle","valley"],["la comunidad","community"],["la energía","energy"],["la ruta","route"]),questions:q(
    ["Miles de personas atraviesan Uri rumbo a otro lugar. ¿Cómo lograrías que algunas se detengan y conozcan el cantón?","Thousands of people cross Uri on their way elsewhere. How would you encourage some of them to stop and discover the canton?"],
    ["¿Qué debería recibir una comunidad pequeña cuando una ruta internacional pasa por su territorio?","What should a small community receive when an international route crosses its land?"],
    ["¿Preferís un viaje rápido por un túnel o uno lento por un paso de montaña? ¿Qué cambia en la experiencia?","Do you prefer a fast trip through a tunnel or a slow one over a mountain pass? What changes in the experience?"],
    ["¿Cómo puede un cantón pequeño hacer escuchar su voz en decisiones nacionales?","How can a small canton make its voice heard in national decisions?"],
    ["¿Qué trabajo nuevo podría ayudar a los jóvenes a quedarse en un valle alpino?","What new job could help young people stay in an Alpine valley?"],
    ["Si una leyenda forma parte de la identidad local, ¿importa que sea completamente verdadera?","If a legend is part of local identity, does it matter whether it is completely true?" ]
  )},
  {code:"SZ",number:"05",name:"Schwyz",localName:"Schwyz",capital:"Schwyz",region:"centro",languages:"alemán",color:"#f4bb3c",hook:p("El nombre que terminó nombrando a todo el país.","The name that ended up naming the whole country."),fact:p("El nombre internacional de Suiza está relacionado con Schwyz, uno de los cantones fundadores de la antigua Confederación.","Switzerland’s international name is linked to Schwyz, one of the founding cantons of the old Confederation."),mission:p("Explorá qué pasa cuando un lugar histórico también se vuelve atractivo para nuevos habitantes.","Explore what happens when a historic place also becomes attractive to new residents."),words:words(["los impuestos","taxes"],["el origen","origin"],["la autonomía","autonomy"],["mudarse","to move"],["pertenecer","to belong"],["la vivienda","housing"]),questions:q(
    ["¿Cómo se sentirá vivir en un lugar cuyo nombre representa a todo el país?","How might it feel to live in a place whose name represents the whole country?"],
    ["Si llegan muchas personas por los impuestos bajos, ¿qué responsabilidades deberían asumir con la comunidad?","If many people arrive because of low taxes, what responsibilities should they take on in the community?"],
    ["¿Una persona pertenece a un lugar cuando nace allí, cuando vive allí o cuando participa?","Does a person belong to a place when they are born there, live there or take part in the community?"],
    ["¿Cómo evitarías que las nuevas viviendas ocupen todos los espacios naturales junto al lago?","How would you prevent new housing from taking over all the natural spaces by the lake?"],
    ["¿Qué tradición local mostrarías primero a una persona que acaba de mudarse?","Which local tradition would you first show someone who has just moved there?"],
    ["¿Cuándo la autonomía ayuda a una región y cuándo puede separarla demasiado de las demás?","When does autonomy help a region, and when can it separate it too much from others?" ]
  )},
  {code:"OW",number:"06",name:"Obwalden",localName:"Obwalden",capital:"Sarnen",region:"centro",languages:"alemán",color:"#b9b634",hook:p("Pueblos pequeños bajo montañas enormes.","Small towns beneath enormous mountains."),fact:p("Engelberg, rodeado de montañas y conocido por el Titlis, pertenece a Obwalden aunque está separado del resto del cantón.","Engelberg, surrounded by mountains and known for Titlis, belongs to Obwalden even though it is separated from the rest of the canton."),mission:p("Imaginá un turismo de montaña que funcione todo el año y cuide a quienes viven allí.","Imagine year-round mountain tourism that looks after the people who live there."),words:words(["la nieve","snow"],["la temporada alta","high season"],["el teleférico","cable car"],["el alojamiento","accommodation"],["el servicio","service"],["todo el año","all year round"]),questions:q(
    ["Si hubiera menos nieve en el futuro, ¿qué nuevas actividades ofrecerías en Engelberg?","If there were less snow in the future, what new activities would you offer in Engelberg?"],
    ["¿Cómo puede un pueblo turístico seguir siendo un hogar y no convertirse solamente en un hotel grande?","How can a tourist town remain a home instead of becoming only a large hotel?"],
    ["¿Pagarías más por un teleférico si ese dinero protegiera la montaña?","Would you pay more for a cable car if the money protected the mountain?"],
    ["¿Qué servicios son esenciales para vivir todo el año en un pueblo pequeño?","Which services are essential for living in a small town all year round?"],
    ["¿Cómo resolverías la falta de alojamiento para trabajadores de temporada?","How would you solve the lack of accommodation for seasonal workers?"],
    ["¿Una comunidad tranquila debe aceptar grandes eventos si generan trabajo? ¿Con qué límites?","Should a quiet community accept major events if they create jobs? With what limits?" ]
  )},
  {code:"NW",number:"07",name:"Nidwalden",localName:"Nidwalden",capital:"Stans",region:"centro",languages:"alemán",color:"#80aa3d",hook:p("Alta tecnología entre el lago y las montañas.","High technology between the lake and the mountains."),fact:p("En Stans se encuentra Pilatus Aircraft, una empresa aeronáutica conocida internacionalmente.","Stans is home to Pilatus Aircraft, an internationally known aviation company."),mission:p("Uní innovación, formación y paisaje sin obligar a elegir solo una cosa.","Bring innovation, training and landscape together without forcing a choice."),words:words(["la industria","industry"],["el aprendiz","apprentice"],["la formación","training"],["la innovación","innovation"],["el paisaje","landscape"],["el empleo","job"]),questions:q(
    ["¿Qué ventajas tiene una empresa tecnológica importante cuando está en un cantón pequeño?","What advantages does a major technology company have when it is based in a small canton?"],
    ["¿Preferirías aprender una profesión trabajando en una empresa o estudiarla primero en una universidad?","Would you prefer to learn a profession by working in a company or studying it first at university?"],
    ["¿Cómo puede una fábrica convivir con un paisaje que la gente quiere proteger?","How can a factory coexist with a landscape that people want to protect?"],
    ["¿Qué podría hacer Nidwalden para atraer talento sin perder su identidad local?","What could Nidwalden do to attract talent without losing its local identity?"],
    ["¿Aceptarías más ruido de aviones si la industria creara buenos empleos? ¿Hasta qué punto?","Would you accept more aircraft noise if the industry created good jobs? To what extent?"],
    ["Diseñá un día ideal que combine trabajo, lago y montaña.","Design an ideal day that combines work, lake and mountain." ]
  )},
  {code:"GL",number:"08",name:"Glaris",localName:"Glarus",capital:"Glaris",region:"este",languages:"alemán",color:"#43a267",hook:p("Una democracia que todavía sale a la plaza.","A democracy that still goes out into the square."),fact:p("En Glaris, la Landsgemeinde reúne a ciudadanos al aire libre para votar levantando la mano.","In Glarus, the Landsgemeinde gathers citizens outdoors to vote by raising their hands."),mission:p("Compará la fuerza de decidir juntos con la necesidad de votar libremente.","Compare the power of deciding together with the need to vote freely."),words:words(["votar","to vote"],["levantar la mano","to raise one’s hand"],["la plaza","square"],["la fábrica","factory"],["el riesgo natural","natural hazard"],["quedarse","to stay"]),questions:q(
    ["¿Te gustaría votar en una plaza frente a tus vecinos? ¿Qué ventaja y qué dificultad tendría?","Would you like to vote in a square in front of your neighbours? What advantage and difficulty would it have?"],
    ["¿Una decisión pública cambia cuando podemos ver quién vota cada opción?","Does a public decision change when we can see who votes for each option?"],
    ["Glaris tiene una historia industrial. ¿Cómo puede una vieja fábrica encontrar una nueva función?","Glarus has an industrial history. How can an old factory find a new purpose?"],
    ["¿Qué proyecto convencería a una persona joven de quedarse en un valle pequeño?","What project would convince a young person to stay in a small valley?"],
    ["¿Construirías una casa con una vista increíble si hubiera riesgo de avalanchas o derrumbes?","Would you build a house with an incredible view if there were a risk of avalanches or landslides?"],
    ["¿Qué tema de tu ciudad debería decidirse en una reunión abierta?","Which issue in your city should be decided in an open meeting?" ]
  )},
  {code:"ZG",number:"09",name:"Zug",localName:"Zug",capital:"Zug",region:"centro",languages:"alemán",color:"#2f9f91",hook:p("Un cantón pequeño con empresas de todo el mundo.","A small canton with companies from around the world."),fact:p("Zug es conocido por sus impuestos competitivos y por el ecosistema tecnológico llamado Crypto Valley.","Zug is known for competitive taxes and for the technology ecosystem called Crypto Valley."),mission:p("Decidí cómo compartir el éxito económico con toda la comunidad.","Decide how economic success can be shared with the whole community."),words:words(["la empresa","company"],["el costo de vida","cost of living"],["la tecnología","technology"],["la vivienda accesible","affordable housing"],["el beneficio","benefit"],["la identidad local","local identity"]),questions:q(
    ["Cuando llegan muchas empresas internacionales, ¿cómo debería beneficiarse la población local?","When many international companies arrive, how should local residents benefit?"],
    ["¿El éxito de una ciudad se mide por sus empresas o por la vida cotidiana de sus habitantes?","Is a city’s success measured by its companies or by its residents’ everyday lives?"],
    ["¿Qué solución propondrías si los buenos empleos hacen subir demasiado el precio de la vivienda?","What solution would you propose if good jobs made housing prices rise too much?"],
    ["¿Qué trámite del gobierno te gustaría poder hacer en dos minutos desde el teléfono?","Which government task would you like to complete in two minutes from your phone?"],
    ["¿Trabajar en un equipo con varios idiomas mejora las ideas o complica la comunicación?","Does working in a multilingual team improve ideas or complicate communication?"],
    ["¿Cómo puede Zug mantener una identidad local cuando muchas personas llegan por poco tiempo?","How can Zug keep a local identity when many people arrive for only a short time?" ]
  )},
  {code:"FR",number:"10",name:"Friburgo",localName:"Fribourg / Freiburg",capital:"Friburgo",region:"oeste",languages:"francés y alemán",color:"#2495ad",hook:p("Dos idiomas que se encuentran todos los días.","Two languages meeting every day."),fact:p("Friburgo es un cantón oficialmente bilingüe; la ciudad y su universidad conectan zonas francófonas y germanófonas.","Fribourg is an officially bilingual canton; the city and its university connect French- and German-speaking areas."),mission:p("Creá una comunidad bilingüe donde nadie tenga miedo de equivocarse.","Create a bilingual community where nobody is afraid of making mistakes."),words:words(["bilingüe","bilingual"],["el cartel","sign"],["cambiar de idioma","to switch languages"],["equivocarse","to make a mistake"],["el puente","bridge"],["la convivencia","living together"]),questions:q(
    ["Si vivieras en Friburgo, ¿en qué situaciones usarías francés y en cuáles alemán?","If you lived in Fribourg, in which situations would you use French and in which German?"],
    ["¿Una escuela bilingüe debe separar los idiomas o mezclarlos durante el día?","Should a bilingual school separate the languages or mix them throughout the day?"],
    ["¿Qué ayuda más a aprender un idioma: una regla, una amistad o una necesidad real?","What helps most when learning a language: a rule, a friendship or a real need?"],
    ["¿Cómo debería reaccionar una persona cuando alguien comete un error en su idioma?","How should someone react when another person makes a mistake in their language?"],
    ["La ciudad tiene muchos puentes. ¿Qué tipo de puente cultural necesita tu comunidad?","The city has many bridges. What kind of cultural bridge does your community need?"],
    ["Inventá un evento donde personas de dos idiomas tengan que colaborar de verdad.","Invent an event where speakers of two languages genuinely have to collaborate." ]
  )},
  {code:"SO",number:"11",name:"Soleura",localName:"Solothurn",capital:"Soleura",region:"norte",languages:"alemán",color:"#497bc0",hook:p("Una ciudad barroca obsesionada con el número once.","A Baroque city fascinated by the number eleven."),fact:p("Soleura está asociada al número 11: hay once iglesias y capillas históricas, y la catedral juega con ese número en su diseño.","Solothurn is associated with the number 11: there are eleven historic churches and chapels, and the cathedral plays with that number in its design."),mission:p("Convertí una curiosidad local en una experiencia que una a la gente.","Turn a local curiosity into an experience that brings people together."),words:words(["la curiosidad","curiosity"],["el número","number"],["el casco antiguo","old town"],["la fiesta","festival"],["el río","river"],["la coincidencia","coincidence"]),questions:q(
    ["¿Qué número, objeto o costumbre podría representar tu ciudad? ¿Por qué?","Which number, object or custom could represent your city? Why?"],
    ["Inventá una ruta de once paradas que una persona recordaría durante años.","Invent an eleven-stop route that someone would remember for years."],
    ["¿Las curiosidades históricas ayudan a conocer un lugar o lo convierten en un producto?","Do historical curiosities help us know a place, or do they turn it into a product?"],
    ["¿Qué actividad organizarías junto al río para reunir a distintas generaciones?","What activity would you organise by the river to bring different generations together?"],
    ["¿Preferís vivir en una ciudad pequeña con mucha historia o en una ciudad moderna con más opciones?","Would you rather live in a small city with lots of history or a modern city with more options?"],
    ["¿Una coincidencia repetida puede transformarse en parte de la identidad de un lugar?","Can a repeated coincidence become part of a place’s identity?" ]
  )},
  {code:"BS",number:"12",name:"Basilea-Ciudad",localName:"Basel-Stadt",capital:"Basilea",region:"norte",languages:"alemán",color:"#675fbd",hook:p("Arte, ciencia y un río que funciona como plaza.","Art, science and a river that works like a public square."),fact:p("Basilea reúne industrias farmacéuticas, museos de nivel internacional y un puerto sobre el Rin, cerca de Francia y Alemania.","Basel brings together pharmaceutical industries, internationally known museums and a Rhine port near France and Germany."),mission:p("Imaginá una ciudad industrial, cultural y abierta que no expulse a sus habitantes.","Imagine an industrial, cultural and open city that does not push out its residents."),words:words(["la frontera","border"],["la industria farmacéutica","pharmaceutical industry"],["el puerto","port"],["nadar","to swim"],["la exposición","exhibition"],["la calidad de vida","quality of life"]),questions:q(
    ["En Basilea podés cruzar dos fronteras en poco tiempo. ¿Cómo cambiaría eso tu rutina y tu identidad?","In Basel you can cross two borders quickly. How would that change your routine and identity?"],
    ["¿Qué responsabilidad tiene una gran empresa farmacéutica con la ciudad donde trabaja?","What responsibility does a large pharmaceutical company have towards the city where it operates?"],
    ["En verano, mucha gente nada en el Rin. ¿Qué espacio de tu ciudad funciona como punto de encuentro?","In summer, many people swim in the Rhine. Which space in your city works as a meeting point?"],
    ["¿El arte debería estar dentro de museos o aparecer también en fábricas, calles y estaciones?","Should art be inside museums, or should it also appear in factories, streets and stations?"],
    ["¿Qué ventajas y problemas trae un puerto a una ciudad que no está junto al mar?","What advantages and problems does a port bring to a city that is not by the sea?"],
    ["¿Cómo evitarías que una ciudad con empleos excelentes se vuelva imposible de pagar?","How would you prevent a city with excellent jobs from becoming unaffordable?" ]
  )},
  {code:"BL",number:"13",name:"Basilea-Campiña",localName:"Basel-Landschaft",capital:"Liestal",region:"norte",languages:"alemán",color:"#8258a7",hook:p("La vida entre la gran ciudad, los pueblos y las colinas.","Life between the big city, towns and hills."),fact:p("Basilea-Campiña rodea parte de la ciudad de Basilea y combina zonas residenciales, industria, pueblos y paisajes rurales.","Basel-Landschaft surrounds part of Basel and combines residential areas, industry, towns and rural landscapes."),mission:p("Diseñá una región donde viajar a la ciudad no signifique perder la vida del pueblo.","Design a region where commuting to the city does not mean losing village life."),words:words(["las afueras","outskirts"],["desplazarse","to commute"],["la zona rural","rural area"],["construir","to build"],["el castillo","castle"],["los servicios","services"]),questions:q(
    ["¿Qué ganás y qué perdés cuando vivís fuera de la ciudad pero trabajás en ella?","What do you gain and lose when you live outside the city but work in it?"],
    ["¿Es mejor construir edificios más altos o usar más terreno para nuevas viviendas?","Is it better to build taller buildings or use more land for new housing?"],
    ["¿Qué servicio urbano debería existir también en todos los pueblos?","Which urban service should also exist in every town?"],
    ["¿Cómo convertirías un castillo o edificio antiguo en un lugar útil para la comunidad?","How would you turn a castle or old building into a useful place for the community?"],
    ["¿Puede una región tener identidad propia aunque dependa mucho de una ciudad vecina?","Can a region have its own identity even if it depends heavily on a neighbouring city?"],
    ["Diseñá un fin de semana sin auto que conecte ciudad, pueblo y naturaleza.","Design a car-free weekend connecting city, town and nature." ]
  )},
  {code:"SH",number:"14",name:"Schaffhausen",localName:"Schaffhausen",capital:"Schaffhausen",region:"norte",languages:"alemán",color:"#9d5094",hook:p("Una frontera, viñedos y la fuerza del Rin.","A border, vineyards and the power of the Rhine."),fact:p("Las cataratas del Rin, cerca de Schaffhausen, son las más grandes de Europa por volumen de agua.","The Rhine Falls near Schaffhausen are Europe’s largest waterfalls by water volume."),mission:p("Usá una maravilla natural para generar energía, turismo y respeto al mismo tiempo.","Use a natural wonder to create energy, tourism and respect at the same time."),words:words(["la catarata","waterfall"],["la frontera","border"],["la energía hidráulica","hydropower"],["el viñedo","vineyard"],["la multitud","crowd"],["proteger","to protect"]),questions:q(
    ["¿Qué debería sentir una persona al visitar las cataratas: aventura, calma o respeto? ¿Por qué?","What should a person feel when visiting the falls: adventure, calm or respect? Why?"],
    ["¿Cómo controlarías la cantidad de visitantes sin cerrar el lugar?","How would you manage visitor numbers without closing the place?"],
    ["¿Producir energía con un río siempre es una opción ecológica? ¿Qué habría que revisar?","Is producing energy from a river always an ecological option? What would need to be checked?"],
    ["¿Vivir junto a una frontera ofrece más oportunidades o crea más complicaciones?","Does living by a border offer more opportunities or create more complications?"],
    ["¿Qué producto local puede contar mejor la historia de una región: el vino, la comida o una artesanía?","Which local product can best tell a region’s story: wine, food or a craft?"],
    ["Si tuvieras una tarde libre en Schaffhausen, ¿elegirías la catarata, el casco antiguo o los viñedos? Armá el plan.","If you had a free afternoon in Schaffhausen, would you choose the falls, the old town or the vineyards? Make a plan." ]
  )},
  {code:"AR",number:"15",name:"Appenzell Rodas Exteriores",localName:"Appenzell Ausserrhoden",capital:"Herisau",region:"este",languages:"alemán",color:"#c14f78",hook:p("Colinas, talleres y nuevas ideas en pueblos antiguos.","Hills, workshops and new ideas in old towns."),fact:p("La región es conocida por sus paisajes de colinas, una larga historia textil y pueblos con casas pintadas.","The region is known for its rolling hills, long textile history and villages with painted houses."),mission:p("Dale una segunda vida a una tradición sin convertirla en una decoración vacía.","Give a tradition a second life without turning it into empty decoration."),words:words(["el tejido","fabric"],["el taller","workshop"],["la tradición","tradition"],["la salud","health"],["el sendero","trail"],["el recién llegado","newcomer"]),questions:q(
    ["¿Cómo transformarías una antigua tradición textil en un proyecto moderno?","How would you turn an old textile tradition into a modern project?"],
    ["¿Qué hace que un pueblo bonito sea también interesante para una persona joven?","What makes a beautiful village interesting for a young person as well?"],
    ["¿La tranquilidad mejora siempre la salud o a veces puede sentirse como aislamiento?","Does tranquillity always improve health, or can it sometimes feel like isolation?"],
    ["¿Cómo recibirías a nuevos habitantes sin pedirles que abandonen su propia cultura?","How would you welcome new residents without asking them to leave their own culture behind?"],
    ["¿Qué ruta a pie diseñarías para mostrar algo más que paisajes?","What walking route would you design to show more than scenery?"],
    ["¿Un pueblo necesita transporte frecuente aunque pocos pasajeros lo usen? ¿Por qué?","Does a village need frequent transport even if few passengers use it? Why?" ]
  )},
  {code:"AI",number:"16",name:"Appenzell Rodas Interiores",localName:"Appenzell Innerrhoden",capital:"Appenzell",region:"este",languages:"alemán",color:"#d85b64",hook:p("El cantón más pequeño decide a cielo abierto.","The smallest canton makes decisions in the open air."),fact:p("Appenzell Rodas Interiores es el cantón menos poblado y conserva la votación abierta de la Landsgemeinde.","Appenzell Innerrhoden is the least populated canton and keeps the open-air Landsgemeinde vote."),mission:p("Explorá cómo una comunidad muy cercana puede cambiar sin perder confianza.","Explore how a very close community can change without losing trust."),words:words(["la confianza","trust"],["la privacidad","privacy"],["la votación","vote"],["la granja","farm"],["el cambio","change"],["la costumbre","custom"]),questions:q(
    ["¿Es más fácil confiar en los demás cuando casi todo el mundo se conoce? ¿Y tener privacidad?","Is it easier to trust others when almost everyone knows each other? And to have privacy?"],
    ["¿Votar levantando la mano fortalece la comunidad o puede dar presión?","Does voting by raising your hand strengthen the community, or can it create pressure?"],
    ["Las mujeres obtuvieron el voto cantonal aquí en 1991. ¿Por qué algunas tradiciones tardan tanto en cambiar?","Women gained the cantonal vote here in 1991. Why do some traditions take so long to change?"],
    ["¿Cómo puede una granja tradicional producir alimentos y también proteger el paisaje?","How can a traditional farm produce food and also protect the landscape?"],
    ["¿Qué costumbre conservarías incluso si ya no fuera práctica? Explicá su valor.","Which custom would you keep even if it were no longer practical? Explain its value."],
    ["¿Cómo mostrarías este cantón a visitantes sin convertir la vida local en un espectáculo?","How would you show this canton to visitors without turning local life into a show?" ]
  )},
  {code:"SG",number:"17",name:"San Galo",localName:"St. Gallen",capital:"San Galo",region:"este",languages:"alemán",color:"#df7547",hook:p("Libros antiguos, bordados y negocios modernos.","Old books, embroidery and modern business."),fact:p("La abadía y su biblioteca son Patrimonio Mundial, mientras la región también es famosa por sus textiles y su universidad.","The abbey and its library are a World Heritage Site, while the region is also known for textiles and its university."),mission:p("Conectá conocimiento antiguo y trabajo futuro en una misma ciudad.","Connect old knowledge and future work in one city."),words:words(["la biblioteca","library"],["el bordado","embroidery"],["el conocimiento","knowledge"],["el patrimonio","heritage"],["la universidad","university"],["el oficio","craft"]),questions:q(
    ["Si pudieras guardar un objeto actual en una biblioteca durante mil años, ¿qué elegirías?","If you could keep one current object in a library for a thousand years, what would you choose?"],
    ["¿Cómo puede un oficio como el bordado seguir siendo valioso en la época de las máquinas?","How can a craft like embroidery remain valuable in the age of machines?"],
    ["¿Qué debería compartir una universidad con la ciudad que la rodea?","What should a university share with the city around it?"],
    ["¿Un edificio histórico debe sentirse silencioso y serio o vivo y participativo?","Should a historic building feel quiet and serious, or lively and participatory?"],
    ["¿Qué nuevo trabajo podría unir diseño, historia y tecnología?","What new job could combine design, history and technology?"],
    ["San Galo está cerca de varias fronteras. ¿Qué aprendemos cuando nuestra región no mira solo hacia la capital?","St. Gallen is near several borders. What do we learn when our region does not look only towards the capital?" ]
  )},
  {code:"GR",number:"18",name:"Grisones",localName:"Graubünden / Grigioni / Grischun",capital:"Coira",region:"este",languages:"alemán, romanche e italiano",color:"#dd8e31",hook:p("Tres idiomas, 150 valles y más de una Suiza.","Three languages, 150 valleys and more than one Switzerland."),fact:p("Grisones es el cantón más grande y el único con tres idiomas oficiales: alemán, romanche e italiano.","Graubünden is the largest canton and the only one with three official languages: German, Romansh and Italian."),mission:p("Mantené conectados valles muy diferentes sin borrar sus voces.","Keep very different valleys connected without erasing their voices."),words:words(["el valle","valley"],["el romanche","Romansh"],["la segunda residencia","second home"],["el tren","train"],["el parque nacional","national park"],["la distancia","distance"]),questions:q(
    ["¿Qué debería hacer una escuela cuando hay tres idiomas oficiales en la misma región?","What should a school do when there are three official languages in the same region?"],
    ["¿Cómo puede sobrevivir un idioma con pocos hablantes sin quedar encerrado en el pasado?","How can a language with few speakers survive without being trapped in the past?"],
    ["¿Es justo que haya muchas segundas residencias vacías mientras falta vivienda para la población local?","Is it fair to have many empty second homes while local people lack housing?"],
    ["¿El tren lento por la montaña es transporte o también parte del viaje?","Is the slow mountain train transport, or is it also part of the journey?"],
    ["¿Qué regla pondrías para visitar un parque nacional sin dañarlo?","What rule would you set for visiting a national park without damaging it?"],
    ["Compará un pueblo remoto con St. Moritz: ¿en cuál sería más fácil sentirse libre y en cuál sentirse acompañado?","Compare a remote village with St. Moritz: where would it be easier to feel free, and where to feel connected?" ]
  )},
  {code:"AG",number:"19",name:"Argovia",localName:"Aargau",capital:"Aarau",region:"norte",languages:"alemán",color:"#b69d31",hook:p("Castillos, ríos y la pregunta de dónde viene la energía.","Castles, rivers and the question of where energy comes from."),fact:p("Argovia concentra varias instalaciones energéticas importantes y tiene numerosos castillos a lo largo de sus ríos y colinas.","Aargau contains several major energy facilities and many castles along its rivers and hills."),mission:p("Tomá una decisión energética pensando en seguridad, costo y futuro.","Make an energy decision while considering safety, cost and the future."),words:words(["la central eléctrica","power station"],["la seguridad","safety"],["el suministro","supply"],["el castillo","castle"],["las aguas termales","thermal baths"],["la reputación","reputation"]),questions:q(
    ["¿Qué información necesitarías antes de vivir cerca de una central eléctrica?","What information would you need before living near a power station?"],
    ["Si cerrara una fuente de energía, ¿qué alternativa elegirías y por qué?","If an energy source closed, what alternative would you choose and why?"],
    ["Argovia está entre Zúrich y Basilea. ¿Es una ventaja estar entre dos lugares más famosos?","Aargau lies between Zurich and Basel. Is it an advantage to be between two more famous places?"],
    ["¿Cómo usarías un castillo para que la historia interese a personas jóvenes?","How would you use a castle to make history interesting to young people?"],
    ["¿Las aguas termales deberían ser un servicio de salud, un lujo turístico o las dos cosas?","Should thermal baths be a health service, a tourist luxury or both?"],
    ["¿Cómo cambiarías la reputación de una región que muchas personas solo atraviesan?","How would you change the reputation of a region that many people only pass through?" ]
  )},
  {code:"TG",number:"20",name:"Turgovia",localName:"Thurgau",capital:"Frauenfeld",region:"norte",languages:"alemán",color:"#73a541",hook:p("Manzanas, bicicletas y un lago compartido.","Apples, bicycles and a shared lake."),fact:p("Turgovia es conocida por sus manzanas y se extiende junto al lago de Constanza, frente a Alemania.","Thurgau is known for its apples and stretches along Lake Constance opposite Germany."),mission:p("Convertí la agricultura y el lago en una experiencia cotidiana, no solo turística.","Turn farming and the lake into an everyday experience, not only a tourist one."),words:words(["la cosecha","harvest"],["el manzano","apple tree"],["la bicicleta","bicycle"],["la orilla pública","public shore"],["el trabajador temporal","seasonal worker"],["compartir","to share"]),questions:q(
    ["¿Qué producto simple de tu región podría convertirse en una experiencia interesante para visitantes?","What simple product from your region could become an interesting visitor experience?"],
    ["¿Deberíamos comprar alimentos locales aunque cuesten un poco más?","Should we buy local food even if it costs a little more?"],
    ["Diseñá una ruta en bicicleta que combine comida, paisaje y una conversación con alguien local.","Design a cycling route combining food, scenery and a conversation with a local person."],
    ["¿Quién debería tener prioridad en la orilla de un lago: casas privadas, naturaleza o acceso público?","Who should have priority on a lake shore: private homes, nature or public access?"],
    ["¿Qué condiciones deberían recibir las personas que llegan solo durante la cosecha?","What conditions should people who arrive only for the harvest receive?"],
    ["Si un lago pertenece a varios países, ¿cómo deberían compartir sus reglas y cuidados?","If a lake belongs to several countries, how should they share its rules and care?" ]
  )},
  {code:"TI",number:"21",name:"Tesino",localName:"Ticino",capital:"Bellinzona",region:"sur",languages:"italiano",color:"#e0533e",hook:p("Una Suiza italiana al otro lado del Gotardo.","An Italian-speaking Switzerland beyond the Gotthard."),fact:p("Tesino es el único cantón donde el italiano es la única lengua oficial; combina lagos, ciudades y valles alpinos al sur del Gotardo.","Ticino is the only canton where Italian is the sole official language; it combines lakes, cities and Alpine valleys south of the Gotthard."),mission:p("Imaginá una región fronteriza conectada sin perder su forma propia de vivir.","Imagine a connected border region without losing its own way of life."),words:words(["el cruce fronterizo","border crossing"],["el calor","heat"],["el trabajador fronterizo","cross-border worker"],["el pueblo de piedra","stone village"],["la conexión","connection"],["el estilo de vida","way of life"]),questions:q(
    ["¿Cómo cambia la identidad de una región cuando comparte idioma con el país vecino?","How does a region’s identity change when it shares a language with the neighbouring country?"],
    ["Muchas personas cruzan desde Italia para trabajar. ¿Qué beneficios y tensiones puede crear eso?","Many people cross from Italy to work. What benefits and tensions can that create?"],
    ["¿Preferirías vivir en Lugano junto al lago o en un pequeño pueblo de piedra? Compará la vida diaria.","Would you rather live in Lugano by the lake or in a small stone village? Compare daily life."],
    ["Con veranos cada vez más calurosos, ¿cómo adaptarías las calles y las casas?","With increasingly hot summers, how would you adapt streets and homes?"],
    ["¿Un túnel que acorta el viaje también acerca culturalmente a dos regiones?","Does a tunnel that shortens a journey also bring two regions culturally closer?"],
    ["Creá una actividad en Tesino que muestre que el lugar es más que sol, lago y vacaciones.","Create an activity in Ticino that shows the place is more than sun, lake and holidays." ]
  )},
  {code:"VD",number:"22",name:"Vaud",localName:"Vaud",capital:"Lausana",region:"oeste",languages:"francés",color:"#df3857",hook:p("Viñedos en terrazas mirando un lago enorme.","Terraced vineyards overlooking an enormous lake."),fact:p("Vaud reúne Lausana, sede del Comité Olímpico Internacional, los viñedos de Lavaux y un fuerte polo universitario y tecnológico.","Vaud brings together Lausanne, home of the International Olympic Committee, the Lavaux vineyards and a major university and technology hub."),mission:p("Conectá deporte, ciencia y paisaje en una vida urbana posible para todos.","Connect sport, science and landscape in an urban life that works for everyone."),words:words(["el viñedo","vineyard"],["la pendiente","slope"],["la investigación","research"],["el deporte","sport"],["la orilla","waterfront"],["el precio de la vivienda","housing cost"]),questions:q(
    ["Si una ciudad es la capital olímpica, ¿cómo debería notarse en la vida de una persona común?","If a city is the Olympic capital, how should that be visible in an ordinary person’s life?"],
    ["¿Qué invento universitario te gustaría probar primero en una ciudad real?","Which university invention would you like to test first in a real city?"],
    ["Los viñedos de Lavaux ocupan pendientes junto al lago. ¿Cómo se protege un paisaje que también produce trabajo?","The Lavaux vineyards occupy slopes by the lake. How do you protect a landscape that also provides jobs?"],
    ["¿Qué debería ser gratuito en la orilla de un lago: el acceso, el transporte o las actividades?","What should be free at a lakeside: access, transport or activities?"],
    ["Lausana tiene muchas pendientes. ¿Qué transporte inventarías para personas con movilidad reducida?","Lausanne has many slopes. What transport would you invent for people with reduced mobility?"],
    ["¿Una ciudad con estudiantes internacionales cambia para mejor? ¿Qué necesita para integrarlos?","Does a city with international students change for the better? What does it need to include them?" ]
  )},
  {code:"VS",number:"23",name:"Valais",localName:"Valais / Wallis",capital:"Sion",region:"sur",languages:"francés y alemán",color:"#e86a37",hook:p("Glaciares, viñedos y agua que mueve el país.","Glaciers, vineyards and water that powers the country."),fact:p("Valais combina algunos de los picos y glaciares más conocidos de los Alpes con grandes represas, viñedos y zonas francófonas y germanófonas.","Valais combines some of the Alps’ best-known peaks and glaciers with major dams, vineyards and French- and German-speaking areas."),mission:p("Diseñá un futuro de montaña con menos nieve pero con comunidades fuertes.","Design a mountain future with less snow but strong communities."),words:words(["el glaciar","glacier"],["la represa","dam"],["derretirse","to melt"],["la estación de esquí","ski resort"],["el agua","water"],["adaptarse","to adapt"]),questions:q(
    ["Si un glaciar que conocés desapareciera, ¿cambiaría tu relación con ese lugar?","If a glacier you knew disappeared, would your relationship with that place change?"],
    ["¿Quién debería decidir cómo se usa el agua de montaña: la región, el país o todos juntos?","Who should decide how mountain water is used: the region, the country or everyone together?"],
    ["¿Qué actividad podría reemplazar parte del esquí si hubiera menos nieve?","What activity could replace some skiing if there were less snow?"],
    ["¿Una gran represa es parte del paisaje o una interrupción del paisaje? Defendé tu mirada.","Is a large dam part of the landscape or a disruption of it? Defend your view."],
    ["¿Cómo puede una región bilingüe evitar que sus dos partes vivan separadas?","How can a bilingual region prevent its two parts from living separately?"],
    ["Armá un menú del Valais que cuente una historia sobre montaña, clima y trabajo.","Create a Valais menu that tells a story about mountains, climate and work." ]
  )},
  {code:"NE",number:"24",name:"Neuchâtel",localName:"Neuchâtel",capital:"Neuchâtel",region:"oeste",languages:"francés",color:"#a454a4",hook:p("Precisión relojera frente a un lago tranquilo.","Watchmaking precision beside a calm lake."),fact:p("Neuchâtel forma parte de una región histórica de relojería y microtecnología, con ciudades industriales junto al lago y en las montañas del Jura.","Neuchâtel is part of a historic watchmaking and microtechnology region, with industrial towns by the lake and in the Jura mountains."),mission:p("Protegé el saber artesanal mientras llegan nuevas máquinas.","Protect craft knowledge as new machines arrive."),words:words(["el reloj","watch"],["la precisión","precision"],["la pieza","part"],["el artesano","craftsperson"],["automatizar","to automate"],["el conocimiento","knowledge"]),questions:q(
    ["¿Por qué alguien compra un reloj artesanal si el teléfono da la hora perfectamente?","Why does someone buy a handmade watch if a phone tells the time perfectly?"],
    ["¿Qué tarea nunca automatizarías, aunque una máquina pudiera hacerla?","Which task would you never automate, even if a machine could do it?"],
    ["¿Cómo se transmite un conocimiento que depende de las manos y de muchos años de práctica?","How do you pass on knowledge that depends on hands and many years of practice?"],
    ["Si una industria importante tiene una crisis, ¿cómo puede prepararse una ciudad?","If an important industry faces a crisis, how can a city prepare?"],
    ["¿El tiempo se siente diferente en una ciudad dedicada a medirlo? Inventá una respuesta.","Does time feel different in a city devoted to measuring it? Invent an answer."],
    ["¿Qué espacio público crearías junto al lago para unir a trabajadores, estudiantes y familias?","What public space would you create by the lake to bring workers, students and families together?" ]
  )},
  {code:"GE",number:"25",name:"Ginebra",localName:"Genève",capital:"Ginebra",region:"oeste",languages:"francés",color:"#2e83a6",hook:p("El mundo negocia junto al lago.","The world negotiates beside the lake."),fact:p("Ginebra reúne organizaciones internacionales, misiones diplomáticas y trabajadores que viven a ambos lados de la frontera con Francia.","Geneva brings together international organisations, diplomatic missions and workers living on both sides of the French border."),mission:p("Convertí una ciudad global en un lugar accesible para quienes la hacen funcionar cada día.","Turn a global city into an accessible place for the people who keep it running every day."),words:words(["la diplomacia","diplomacy"],["negociar","to negotiate"],["la organización internacional","international organisation"],["la desigualdad","inequality"],["el alquiler","rent"],["el trabajador fronterizo","cross-border worker"]),questions:q(
    ["¿Qué problema cotidiano debería discutirse en una gran reunión internacional?","Which everyday problem should be discussed at a major international meeting?"],
    ["Para negociar bien, ¿es más importante hablar mucho, escuchar o saber ceder?","To negotiate well, is it more important to talk a lot, listen or know when to compromise?"],
    ["¿Cómo puede una ciudad muy rica evitar que sus trabajadores esenciales tengan que vivir demasiado lejos?","How can a very wealthy city prevent essential workers from having to live too far away?"],
    ["¿Vivir en Francia y trabajar en Ginebra crea una vida de dos países o una sola región?","Does living in France and working in Geneva create a two-country life or a single region?"],
    ["¿Qué parte de la orilla del lago reservarías para actividades totalmente públicas?","Which part of the lakeshore would you reserve for completely public activities?"],
    ["Inventá una misión de paz pequeña pero real para dos grupos de tu comunidad.","Invent a small but real peace mission for two groups in your community." ]
  )},
  {code:"JU",number:"26",name:"Jura",localName:"Jura",capital:"Delémont",region:"oeste",languages:"francés",color:"#5974aa",hook:p("El cantón más joven cuenta una historia de identidad.","The youngest canton tells a story of identity."),fact:p("Jura se convirtió en cantón en 1979, el miembro más joven de la Confederación Suiza.","Jura became a canton in 1979, making it the youngest member of the Swiss Confederation."),mission:p("Imaginá cómo una región joven puede crear oportunidades sin perder su memoria.","Imagine how a young region can create opportunities without losing its memory."),words:words(["la identidad","identity"],["la frontera","border"],["el cantón joven","young canton"],["el transporte rural","rural transport"],["la energía eólica","wind power"],["irse / quedarse","to leave / stay"]),questions:q(
    ["¿Qué necesita una región para sentir que tiene una identidad propia?","What does a region need to feel it has an identity of its own?"],
    ["Jura es el cantón más joven. ¿Una nueva frontera resuelve un problema o crea preguntas nuevas?","Jura is the youngest canton. Does a new border solve a problem or create new questions?"],
    ["¿Qué oportunidad convencería a una persona joven de quedarse en una zona rural?","What opportunity would convince a young person to stay in a rural area?"],
    ["¿Cómo debería funcionar el transporte público cuando los pueblos están lejos y hay pocos pasajeros?","How should public transport work when villages are far apart and there are few passengers?"],
    ["¿Aceptarías molinos de viento visibles si produjeran energía limpia para la región?","Would you accept visible wind turbines if they produced clean energy for the region?"],
    ["Diseñá una celebración para un cantón joven: ¿qué recordaría del pasado y qué mostraría del futuro?","Design a celebration for a young canton: what would it remember from the past and show about the future?" ]
  )}
];

export const starters:Pair[]=[
  p("Para mí, lo más importante es…","For me, the most important thing is…"),
  p("Yo elegiría… porque…","I would choose… because…"),
  p("Una ventaja sería…","One advantage would be…"),
  p("El problema principal es que…","The main problem is that…"),
  p("Depende de…","It depends on…"),
  p("En mi ciudad, la situación es diferente porque…","In my city, the situation is different because…")
];

export const connectors:Pair[]=[
  p("porque","because"),p("además","also / furthermore"),p("sin embargo","however"),
  p("por ejemplo","for example"),p("por eso","that is why"),p("aunque","although")
];

export const depthMoves:Pair[]=[
  p("Dá una razón concreta.","Give a specific reason."),
  p("Agregá un ejemplo personal.","Add a personal example."),
  p("Compará con tu país o ciudad.","Compare it with your country or city."),
  p("Mencioná una ventaja y una dificultad.","Mention one advantage and one difficulty."),
  p("Cambiá una condición: ¿qué pasaría entonces?","Change one condition: what would happen then?"),
  p("Hacé una pregunta de vuelta.","Ask a follow-up question.")
];

export const regionNames:Record<SwissCanton["region"],Pair>={
  norte:p("Norte y Rin","North & Rhine"),centro:p("Suiza Central","Central Switzerland"),
  oeste:p("Oeste y Romandía","West & Romandy"),sur:p("Sur alpino","Alpine South"),este:p("Este y Alpes","East & Alps")
};
