import type {CEFRLevel} from './types';
export function decisionChallenge(level:CEFRLevel,first:string,second:string){
 if(level==='B2')return `Compara «${first}» y «${second}»: ¿qué coste aceptarías para asegurar el beneficio principal? Propón una condición concreta.`;
 if(level==='C1')return `¿Qué prioridades sociales contrapone «${first}» a «${second}»? Explica qué persona podría rechazar el criterio que estás usando y responde a su objeción.`;
 return `¿Qué deja fuera presentar «${first}» y «${second}» como alternativas excluyentes? Reformula el problema, delimita tu posición y reconoce qué incertidumbre impide cerrar el juicio.`;
}
export const reactionChallenges:Record<string,Record<string,string>>={
 B2:{'VIDA COTIDIANA':'Compara resolverlo ahora con esperar ayuda: ¿qué coste o molestia aceptarías y por qué?','SOCIAL':'Formula una respuesta directa y otra cortés. ¿Cuál protege mejor tu límite sin dañar la relación?','TRABAJO':'Negocia un plazo, un recurso o una responsabilidad concreta. Explica qué puedes conceder.','VIAJE':'Compara el coste económico con el tiempo perdido; propón un plan alternativo viable.','DECISIÓN':'Define un beneficio y un riesgo de tu elección. ¿Qué información te haría revisarla?'},
 C1:{'VIDA COTIDIANA':'Distingue el problema práctico de la interpretación que haces de quien lo causó. ¿Qué evidencia falta?','SOCIAL':'Interpreta la intención de la otra persona sin darla por probada. Responde conservando la relación y tu autonomía.','TRABAJO':'Detecta una expectativa implícita de disponibilidad o lealtad y conviértela en un acuerdo explícito.','VIAJE':'Contrasta tu expectativa como visitante con la perspectiva de quien presta el servicio. Reformula la petición.','DECISIÓN':'¿Qué supuesto sobre éxito o bienestar sostiene tu elección? Explora una excepción que pondría a prueba ese supuesto.'},
 C2:{'VIDA COTIDIANA':'Reformula el incidente sin insinuar una culpa que no puedes demostrar; explica qué matiz retiras y cuál mantienes.','SOCIAL':'Expresa el mismo límite con franqueza y con una insinuación cortés. Compara los riesgos interpretativos de ambas versiones.','TRABAJO':'Cuestiona el marco de responsabilidad del encargo y formula una reserva precisa que no pueda confundirse con una negativa total.','VIAJE':'Distingue un derecho, una expectativa comercial y una preferencia personal. Negocia sin presentar las tres como equivalentes.','DECISIÓN':'Detecta qué alternativa queda invisibilizada por el dilema. Defiéndela y explicita qué evidencia invalidaría tu argumento.'},
};
