import type {Pair} from './data';
export const auroraConsequences:readonly (readonly Pair[])[]=[
 [['Otra misión llega antes.','Another mission arrives first.'],['Hay energía, pero los organismos se alejan.','There is energy, but the organisms move away.'],['La nueva zona es segura, pero cuesta tiempo.','The new area is safe, but it takes time.']],
 [['La respuesta es confusa. El público cree que es un saludo.','The reply is unclear. The public thinks it is a greeting.'],['Otro equipo encuentra un error y confirma parte de los datos.','Another team finds an error and confirms some data.'],['El sonido desaparece. Ya no puedes responder.','The sound disappears. You can no longer reply.']],
 [['Los animales regresan. La marca deja la misión.','The animals return. The brand leaves the mission.'],['La marca acepta menos luz, pero quiere las imágenes.','The brand accepts less light, but wants the images.'],['Los animales cambian su ruta.','The animals change their route.']],
 [['El equipo obedece, pero no comparte ideas.','The team obeys, but does not share ideas.'],['Dos reglas cambian después de hablar.','Two rules change after discussion.'],['Los equipos responden de forma diferente al mismo riesgo.','The teams respond differently to the same risk.']],
 [['La muestra ayuda a la ciencia, pero deja una marca permanente.','The sample helps science, but leaves a permanent mark.'],['La muestra pequeña no permite una conclusión clara.','The small sample does not allow a clear conclusion.'],['La misión termina. Otras misiones usan tus reglas.','The mission ends. Other missions use your rules.']],
];
export const ministryEvidence:readonly (readonly Pair[])[]=[
 [['El titular dice: Inés abandona la empresa.','The headline says: Inés leaves the company.'],['La empresa dice: Inés decidió empezar otra etapa.','The company says: Inés decided to start a new chapter.'],['Un chat dice: Inés ya no tenía acceso al dinero.','A chat says: Inés no longer had access to the money.'],['Inés había abierto una empresa y negoció su salida.','Inés had started a company and negotiated her departure.']],
 [['El titular dice: el actor sale por una humillación.','The headline says: the actor leaves because of humiliation.'],['La regidora dice: la salida estaba en el guion.','The stage manager says: the exit was in the script.'],['El actor escribe: la presentadora se pasó.','The actor writes: the presenter went too far.'],['El guion tenía una broma. La presentadora añadió un detalle privado.','The script had a joke. The presenter added a private detail.']],
 [['El titular dice: una boda de pesadilla.','The headline says: a nightmare wedding.'],['La jefa dice: todos recibieron comida segura.','The manager says: everyone received safe food.'],['El chef dice: falló el refrigerador.','The chef says: the refrigerator failed.'],['El informe confirma dos platos distintos y setenta minutos de retraso.','The report confirms two changed dishes and a seventy-minute delay.']],
 [['El titular dice: la universidad cancela la conferencia.','The headline says: the university cancels the lecture.'],['La universidad dice: buscamos una fecha segura.','The university says: we are seeking a safe date.'],['Un correo dice: nos preocupan los titulares.','An email says: we are concerned about the headlines.'],['El invitado cambió el título y no aceptó preguntas.','The guest changed the title and did not accept questions.']],
 [['El titular dice: la directora critica al público.','The headline says: the director criticizes the audience.'],['El productor dice: ella señaló a los patrocinadores.','The producer says: she pointed at the sponsors.'],['Un chat dice: no aclares demasiado.','A chat says: do not explain too much.'],['La pregunta era sobre el público; el gesto era hacia los patrocinadores.','The question was about the audience; the gesture was toward the sponsors.']],
];
export const agencyConsequences:readonly (readonly Pair[])[]=[
 [['Sigues en el estudio. Conservas los ingresos y necesitas negociar límites de horario.','You stay at the studio. You keep your income and need to negotiate schedule limits.'],['Reduces el estudio. Ganas noches libres, pero tus ingresos bajan.','You reduce the studio. You gain free evenings but your income falls.']],
 [['Te quedas con el cine. Conservas la comunidad y debes abrir espacio para cambios.','You keep the cinema. You preserve the community and must make room for change.'],['Viajas. Tu carrera crece y la relación necesita acuerdos a distancia.','You travel. Your career grows and the relationship needs long-distance agreements.']],
 [['Sigues viajando. Mantienes proyectos internacionales, pero tus visitas siguen siendo breves.','You keep traveling. You retain international projects but visits remain brief.'],['Eliges una base. Crean una rutina contigo, pero pierdes algunos proyectos.','You choose a base. People build a routine with you but you lose some projects.']],
 [['Empiezas otro proyecto. Recuperas retos, pero vuelve la presión de tiempo.','You start another project. Challenges return, but so does time pressure.'],['Descansas. Conservas tiempo libre y necesitas construir una identidad fuera del trabajo.','You rest. You preserve free time and need to build an identity outside work.']],
 [['Sigues ayudando. El cine permanece abierto y tu oportunidad profesional debe esperar.','You keep helping. The cinema stays open and your professional opportunity must wait.'],['Aceptas el trabajo. Tu familia busca ayuda y tú recuperas tu carrera.','You accept the job. Your family seeks help and you regain your career.']],
 [['Sigues en el puesto estable. Conservas el piano y debes buscar otra vía para crear.','You stay in the stable job. You keep piano time and must find another outlet for creativity.'],['Cambias a la cooperativa. Ganas autonomía, pero tus ingresos varían.','You move to the cooperative. You gain autonomy but your income varies.']],
];
export const liveConsequences:readonly (readonly Pair[])[]=[
 [['Ganas tiempo, pero el presentador necesita nuevas instrucciones.','You gain time, but the presenter needs new instructions.'],['La invitada puede entrar a tiempo, pero la conexión puede fallar.','The guest can join on time, but the connection may fail.']],
 [['Compartir es barato, pero las personas tienen que esperar su turno.','Sharing is cheap, but people must wait their turn.'],['Hay otro micrófono, pero el teléfono puede tener retraso.','There is another microphone, but the phone may have a delay.']],
 [['El público participa, pero sus preguntas pueden ser inesperadas.','The audience participates, but its questions may be unexpected.'],['La entrevista ocupa el tiempo, pero la invitada puede cansarse.','The interview fills the time, but the guest may get tired.']],
 [['La marca gana tiempo, pero solo aparece una vez.','The brand gets more time, but appears only once.'],['La marca aparece otra vez, pero hay que cortar otro segmento.','The brand appears again, but another segment must be cut.']],
];
