import type {Pair,Scene} from './data';
export function oralBlocks(kind:string,stage:number,scene:Scene,option:Pair):readonly Pair[]{
 if(kind==='gala')return stage===0?[['Hola.','Hello.'],['Yo me llamo','My name is'],['Alex.','Alex.']]:stage===2?[['Hola.','Hello.'],['¿Cómo te llamas?','What is your name?'],['¿De dónde eres?','Where are you from?']]:stage===3?[['Yo creo que','I think that'],['la invitación es para','the invitation is for'],[scene.name[0].split(' · ')[0]+'.',scene.name[1].split(' · ')[0]+'.']]:stage===4?[['Yo quiero','I want'],['sentarme con','to sit with'],[scene.name[0].split(' · ')[0]+'.',scene.name[1].split(' · ')[0]+'.']]:stage===5?[['Perdón,','Sorry,'],['¿puedes repetir?','can you repeat?'],['Gracias. Hasta luego.','Thank you. See you later.']]:scene.words;
 if(kind==='cinema')return stage===3?[['Hola.','Hello.'],['¿Quieres ir','Do you want to go'],['al cine conmigo?','to the cinema with me?']]:stage===4?[['Nosotros','We'],['nos vemos','meet'],['en la entrada.','at the entrance.']]:stage===5?[['Tenemos un problema.','We have a problem.'],['Nosotros podemos','We can'],['cambiar el plan.','change the plan.']]:scene.words;
 if(kind==='theatre')return stage===2?[['Primero','First'],['termina el ensayo.','rehearsal ends.'],['Después','Then'],['Vera lleva la máscara.','Vera takes the mask.']]:stage===4?[['¿Dónde','Where'],['está','is'],['la máscara?','the mask?']]:scene.words;
 if(kind==='live')return stage===0?[['Yo','I'],['trabajo en','work in'],['producción.','production.']]:stage===3?[['Hola.','Hello.'],['Nosotros tenemos','We have'],['un cambio.','a change.'],['¿Puedes hablar?','Can you talk?']]:stage===4||stage===5?[['Yo quiero','I want'],['conservar la entrevista','to keep the interview'],['y cortar el video.','and cut the video.']]:scene.words;
 if(kind==='context')return stage===4?[['Yo','I'],['no quiero','do not want'],['una captura pública.','a public screenshot.'],['¿Puedes borrarla?','Can you delete it?']]:scene.words;
 if(kind==='deal')return stage===0?[['Nosotros','We'],['ofrecemos','offer'],['un lugar tranquilo','a quiet place'],['para trabajar.','to work.']]:stage===2?[['Yo','I'],['quiero','want'],['menos porcentaje.','a smaller share.'],['¿Podemos hablar?','Can we talk?']]:stage===4?[['Yo','I'],['quiero proteger','want to protect'],['los datos y los precios.','data and prices.']]:stage===5?[['Yo','I'],['elijo','choose'],[option[0].toLowerCase()+'.',option[1].toLowerCase()+'.']]:scene.words;
 if(kind==='agency')return stage===2?[['¿Qué','What'],['quieres?','do you want?'],['¿Qué necesitas?','What do you need?']]:stage===3?[['Para mí,','For me,'],['el tiempo y la familia','time and family'],['son importantes.','are important.']]:scene.words;
 return scene.words;
}
