import type {CEFRLevel} from '../conversation-families/types';
import type {Pair,Scene} from './data';
// Each entry follows a native activity, rather than applying one conversation prompt to every screen.
export const actions:Record<string,readonly Pair[]>={
 gala:[['Saluda y di tu nombre.','Say hello and your name.'],['Di tu país, idioma y un gusto.','Say your country, language and one thing you like.'],['Pregunta un dato al invitado.','Ask the guest one question.'],['Busca al dueño de la invitación.','Find the owner of the invitation.'],['Elige dos invitados para tu mesa.','Choose two guests for your table.'],['Pide repetir y despídete.','Ask for repetition and say goodbye.'],['Presenta a un invitado.','Introduce a guest.']],
 cinema:[['Elige una película.','Choose a film.'],['Di qué película prefieres.','Say which film you prefer.'],['Acuerda un día y una hora.','Agree on a day and time.'],['Invita a una persona al cine.','Invite a person to the cinema.'],['Acuerda un lugar de encuentro.','Agree on a meeting place.'],['Cambia el plan después del problema.','Change the plan after the problem.'],['Confirma el plan completo.','Confirm the complete plan.']],
 theatre:[['Di quién está en el teatro.','Say who is in the theater.'],['Escucha y di dónde está cada persona.','Listen and say where each person is.'],['Pon los hechos en orden.','Put the events in order.'],['Compara una declaración y una pista.','Compare a statement and a clue.'],['Pregunta dónde está la máscara.','Ask where the mask is.'],['Elige a una persona y comprueba la prueba.','Choose a person and check the evidence.'],['Cuenta qué pasa con la máscara.','Tell what happens to the mask.']],
 live:[['Elige tu trabajo en el programa.','Choose your job on the show.'],['Elige qué problema resolver primero.','Choose which problem to solve first.'],['Elige soluciones sin gastar más de seis puntos.','Choose solutions without spending more than six points.'],['Llama y comunica un cambio.','Call and communicate a change.'],['Protege dos partes del programa y corta otra.','Protect two parts of the show and cut another.'],['Resuelve la pérdida de cinco minutos.','Solve the loss of five minutes.'],['Explica el programa final.','Explain the final show.']],
 context:[['Lee el mensaje.','Read the message.'],['Elige qué significa el mensaje.','Choose what the message means.'],['Abre el contexto y comprueba tu idea.','Open the context and check your idea.'],['Pregunta sin acusar.','Ask without accusing.'],['Decide qué hacer con la captura pública.','Decide what to do with the public screenshot.'],['Escucha el mensaje completo.','Listen to the complete message.'],['Explica cómo evitar el malentendido.','Explain how to avoid the misunderstanding.']],
 deal:[['Presenta un proyecto.','Present a project.'],['Compara las tres ofertas.','Compare the three offers.'],['Pide un cambio en la oferta.','Ask for a change in the offer.'],['Abre y explica la condición oculta.','Open and explain the hidden condition.'],['Elige dos cosas que quieres proteger.','Choose two things you want to protect.'],['Acepta, pide cambios o sal de la negociación.','Accept, ask for changes or leave the negotiation.'],['Explica tu acuerdo y un coste.','Explain your agreement and one cost.']],
 calls:[['Contesta el teléfono.','Answer the phone.'],['Pregunta, escucha una pista y da un consejo.','Ask, listen to a clue and give advice.'],['Explica qué llamada resolviste.','Explain which call you resolved.']],
 aurora:[['Elige qué quieres proteger.','Choose what you want to protect.'],['Decide cómo conseguir energía.','Decide how to obtain energy.'],['Decide qué hacer con el sonido.','Decide what to do with the sound.'],['Decide cuánta luz usar.','Decide how much light to use.'],['Acuerda reglas con el nuevo equipo.','Agree on rules with the new team.'],['Responde a la orden de la Tierra.','Respond to Earth’s order.'],['Compara tus cinco decisiones.','Compare your five decisions.']],
 agency:[['Elige una puerta.','Choose a door.'],['Abre la decisión, la consecuencia y el coste.','Open the decision, consequence and cost.'],['Pregunta a la persona por su vida.','Ask the person about their life.'],['Elige dos prioridades.','Choose two priorities.'],['Cambia la decisión y observa el resultado.','Change the decision and observe the result.'],['Explica qué vida prefieres.','Explain which life you prefer.']],
 ministry:[['Di qué sabes y qué no sabes.','Say what you know and do not know.'],['Abre las pruebas y revisa tu idea.','Open the evidence and revise your idea.'],['Elige una interpretación del micrófono abierto.','Choose an interpretation of the open microphone.'],['Cuenta el hecho con otro tono.','Tell the event in another tone.']],
};
export function lessonTask(kind:string,stage:number,scene:Scene,level:CEFRLevel){
 const action=actions[kind][stage];
 const prompts:Record<CEFRLevel,Pair>={
 A0:[`${action[0]} Usa los bloques y lee una frase completa.`,`${action[1]} Use the blocks and read one complete sentence.`],
 A1:[`${action[0]} Di dos frases en presente y haz una pregunta sencilla.`,`${action[1]} Say two present-tense sentences and ask a simple question.`],
 A2:[`${action[0]} Explica qué pasó primero y qué vas a hacer después.`,`${action[1]} Explain what happened first and what you are going to do next.`],
 B1:[`${action[0]} Relaciona tu decisión con «${scene.fact[0]}». Da una razón y responde a un problema del profesor.`,`${action[1]} Connect your decision to “${scene.fact[1]}”. Give a reason and respond to a problem from your teacher.`],
 B2:[`${action[0]} Compara dos alternativas para «${scene.name[0]}», concede una ventaja a la opción descartada y negocia una condición.`,`${action[1]} Compare two alternatives for “${scene.name[1]}”, concede an advantage to the rejected option and negotiate a condition.`],
 C1:[`${action[0]} Replantea el caso de «${scene.name[0]}» desde la otra persona. Explica qué habría cambiado con otra decisión y revisa un supuesto.`,`${action[1]} Reframe “${scene.name[1]}” from the other person’s perspective. Explain what would have changed with another decision and revise an assumption.`],
 C2:[`${action[0]} En «${scene.name[0]}», distingue lo dicho, lo sugerido y lo omitido. Defiende dos lecturas incompatibles y reformula tu conclusión para otro interlocutor sin alterar los hechos.`,`${action[1]} In “${scene.name[1]}”, distinguish what is said, implied and omitted. Defend two incompatible readings and reformulate your conclusion for another audience without altering the facts.`],
 };
 const support:Record<CEFRLevel,Pair>={A0:['Yo = I · tú = you · él = he · ella = she · nosotros/nosotras = we. Los verbos de los bloques ya están preparados.','Choose the person first. The verbs in the blocks are already prepared; you do not need to conjugate them.'],A1:['Yo quiero… Tú puedes… ¿Y tú?','I want… You can… And you?'],A2:['Primero pasó… Después voy a…','First … happened. Next I am going to…'],B1:['Elegí… porque… Si eso pasa, podemos…','I chose… because… If that happens, we can…'],B2:['Reconozco que…, aunque… Aceptaría…, siempre que…','I acknowledge that…, although… I would accept…, provided that…'],C1:['De haber sabido…, habría… Mi supuesto inicial era…','Had I known…, I would have… My initial assumption was…'],C2:['La formulación presupone… No se sigue de ello que… Ante otro interlocutor lo expresaría…','The wording presupposes… It does not follow that… For another audience I would express it…']};
 const expected:Record<CEFRLevel,Pair>={A0:['Una frase completa con apoyo; el profesor lee y pulsa.','One complete supported sentence; the teacher reads and clicks.'],A1:['Dos frases y una pregunta; presente, trato cercano.','Two sentences and one question; present tense, informal address.'],A2:['Una secuencia breve; pasado y plan próximo, trato cotidiano.','A short sequence; past and near-future plan, everyday register.'],B1:['30–45 segundos: decisión, razón y respuesta a una dificultad.','30–45 seconds: decision, reason and response to a difficulty.'],B2:['45–60 segundos: comparación, concesión y condición negociada.','45–60 seconds: comparison, concession and negotiated condition.'],C1:['60–90 segundos: hipótesis contrafactual, perspectiva ajena y revisión.','60–90 seconds: counterfactual, another perspective and revision.'],C2:['90 segundos: inferencia precisa, reserva y cambio de registro con los mismos hechos.','90 seconds: precise inference, qualification and register shift preserving the same facts.']};
 return {prompt:prompts[level],support:support[level],expected:expected[level]};
}
