"use client";
import {ConversationFamily} from '../conversation-families/ConversationFamily';
import type {CEFRLevel} from '../conversation-families/types';
import {nativeBank,nativeLabel,nativeInstruction,NativeSpeakingSupport} from '../conversation-narratives/native-adapter';
import {narratives,narrativeLevels} from '../conversation-narratives/data';
import {useState} from "react";
import Link from "next/link";
import "./style.css";

type CallStatus="PENDIENTE"|"RESUELTO"|"NO RESUELTO"|"OTRA OPINIÓN";
const authored_calls=[
 {time:"22:10",minutes:"3 min",name:"ALBA",initials:"AL",hint:"«No encuentro algo que necesito mañana.»",urgency:"BAJA",clues:["Es un anillo antiguo que pertenecía a su abuelo.","Lo llevaba esta tarde en una cafetería donde trabajó dos horas.","Una compañera lo vio sobre la mesa justo antes de que Alba tomara un taxi."],mission:"Averigua dónde puede estar. Compara tres acciones y recomienda qué debería hacer primero.",teacher:"Eres Alba. Al principio solo di que perdiste algo importante. Revela cada dato únicamente cuando el alumno formule una pregunta útil.",follow:["¿Por qué empezarías por ahí?","¿Y si la cafetería ya estuviera cerrada?","¿Te ha pasado algo parecido?"]},
 {time:"22:37",minutes:"4 min",name:"NICO",initials:"NI",hint:"«Tengo que cancelar, pero no sé cómo decirlo.»",urgency:"MEDIA",clues:["Había prometido pasar el fin de semana con dos amigos.","Su nuevo jefe le pidió trabajar el sábado, pero no es obligatorio.","Ya canceló otro plan con esas mismas personas el mes pasado."],mission:"Ayúdalo a decidir si cancela. Después, prepara con él una forma honesta de hablar con sus amigos.",teacher:"Eres Nico. Te preocupa quedar mal con tu jefe. No aceptes el primer consejo sin preguntar qué consecuencias podría tener.",follow:["¿Qué opción daña menos la relación?","¿Debería contar toda la verdad?","¿Qué harías tú en su lugar?"]},
 {time:"23:05",minutes:"4 min",name:"JULIA",initials:"JU",hint:"«Mi amiga dice que exagero.»",urgency:"MEDIA",clues:["Su amiga publicó seis fotos de una cena privada.","Julia había pedido que una foto concreta no se publicara.","La amiga eliminó esa foto, pero no entiende por qué Julia sigue molesta."],mission:"Escucha las dos perspectivas. Explica qué parte del problema ya se resolvió y cuál todavía necesita una conversación.",teacher:"Eres Julia. Si el alumno aconseja olvidar el tema, responde: «La foto ya no está, pero no confío igual». Pide una solución concreta.",follow:["¿Importa más la intención o el resultado?","¿Qué debería decir Julia?","¿En qué punto no estás de acuerdo con ella?"]},
 {time:"23:42",minutes:"4 min",name:"OMAR",initials:"OM",hint:"«Organicé el viaje perfecto… desde el aeropuerto equivocado.»",urgency:"ALTA",clues:["Reservó un coche en un aeropuerto situado a noventa kilómetros.","Puede cambiar la reserva, pero cuesta casi el doble.","Su familia lo espera para una cena; si toma transporte público llegará dos horas tarde."],mission:"Haz preguntas sobre tiempo, precio y prioridades. Compara las opciones y ayúdalo a explicar el retraso.",teacher:"Eres Omar. Quieres llegar a tiempo, pero no gastar demasiado. Cuestiona una recomendación que ignore una de esas prioridades.",follow:["¿Qué información falta para decidir?","¿Cuándo vale la pena pagar más?","¿Cómo se lo explicarías a la familia?"]},
 {time:"00:16",minutes:"4 min",name:"VALENTINA",initials:"VA",hint:"«Recibí una invitación que no esperaba.»",urgency:"BAJA",clues:["Es la boda de una expareja con la que terminó hace tres años.","La invitación incluye acompañante y una nota muy amable.","Su pareja actual piensa que ir podría ser interesante; Valentina no está segura."],mission:"Descubre qué le incomoda de verdad. Recomienda ir, rechazar o pedir más información y justifica tu consejo.",teacher:"Eres Valentina. No estás triste por la expareja; temes que la situación sea incómoda. Obliga al alumno a distinguir esas dos cosas.",follow:["¿Qué cambiaría tu consejo?","¿Cómo rechazarías la invitación?","¿Irías con la pareja actual?"]},
 {time:"00:58",minutes:"5 min",name:"MARTÍN",initials:"MA",hint:"«Quizá quiero cambiar de vida. Quizá solo estoy cansado.»",urgency:"MEDIA",clues:["Tiene un empleo estable que ya no le interesa.","Su prima propone abrir juntos una pequeña panadería y tiene experiencia.","Martín tiene ahorros para seis meses, pero nunca dirigió un negocio."],mission:"Separa cansancio y deseo real de cambio. Propón una prueba antes de decidir y anticipa dos posibles consecuencias.",teacher:"Eres Martín. Te entusiasma la idea, pero rechazas dejar el trabajo mañana. Pide un consejo gradual y luego señala un riesgo.",follow:["¿Qué probarías durante un mes?","¿Qué podría salir bien o mal?","¿Qué experiencia tuya influye en tu consejo?"]},
 {time:"01:46",minutes:"8 min",name:"SOFÍA",initials:"SO",hint:"«Tengo veinte minutos para responder a una propuesta.»",urgency:"ALTA",clues:["Le ofrecen seis meses de trabajo en otro país, algo que siempre quiso.","Su empresa actual acepta darle una pausa sin sueldo y conservar su puesto.","Su pareja quiere acompañarla, pero recibió una oportunidad distinta en otra ciudad."],mission:"Construye con Sofía tres planes posibles. Defiende uno, escucha su objeción y cambia o mantén tu recomendación con razones.",teacher:"Eres Sofía. Primero temes perder la relación. Después revela que tu pareja también quiere viajar, pero a otra ciudad. No aceptes una solución que decida por ambos.",follow:["¿Qué tendría que negociar la pareja?","¿Qué opción conserva más posibilidades?","¿Qué riesgo aceptarías tú?","Resume tu consejo en tres frases claras."]},
] as const;
const authored_supports={"PREGUNTAR MÁS":["¿Qué pasó exactamente?","¿Desde cuándo?","¿Qué hiciste después?","¿Qué opción tienes ahora?"],"DAR CONSEJO":["Yo creo que…","Podrías…","Si estuviera en tu lugar…","Lo mejor sería… porque…"],"REACCIONAR":["Qué situación tan rara.","Entiendo por qué te preocupa.","No estoy del todo seguro/a.","Depende de lo que quieras proteger."]} as const;
const authored_finalQuestions=[
 ["¿A quién llamas normalmente cuando tienes un problema?","¿Qué hace que confíes en esa persona?"],["¿Eres bueno/a dando consejos?","¿Te resulta más fácil aconsejar que decidir por ti?"],["¿Qué consejo te dieron alguna vez y no escuchaste?","¿Cambiarías algo ahora?"],["¿Te resulta fácil decirle a alguien que está equivocado?","¿Cómo evitas que se sienta atacado?"],["¿Qué tipo de problemas prefieres resolver sin ayuda?","¿Cuándo sí pedirías otra opinión?"],["¿Alguna vez ayudaste a un desconocido?","¿Qué pasó después?"],["¿Qué haces cuando no sabes qué decisión tomar?","¿Esperas, preguntas o actúas?"],["¿Crees que la gente escucha realmente los consejos que pide?","¿Por qué los pide entonces? · ¿Siempre ocurre así?"],
] as const;

function SieteLlamadasNative({level}:{level:CEFRLevel}){
 const calls=nativeBank('calls',level,'calls',authored_calls);
 const supports=nativeBank('calls',level,'supports',authored_supports);
 const finalQuestions=nativeBank('calls',level,'finalQuestions',authored_finalQuestions);

 const [active,setActive]=useState(0),[revealed,setRevealed]=useState<Record<number,number>>({}),[statuses,setStatuses]=useState<Record<number,CallStatus>>({}),[teacherOpen,setTeacherOpen]=useState(false),[follow,setFollow]=useState(0),[support,setSupport]=useState<keyof typeof supports|null>(null),[finalMode,setFinalMode]=useState(false),[finalOpen,setFinalOpen]=useState<number|null>(null);
 const current=calls[active],facts=revealed[active]??0,status=statuses[active]??"PENDIENTE",solved=Object.values(statuses).filter(value=>value==="RESUELTO").length;
 const chooseCall=(index:number)=>{setActive(index);setTeacherOpen(false);setFollow(0);setFinalMode(false);window.scrollTo({top:0,behavior:"auto"})};
 const reveal=()=>setRevealed(old=>({...old,[active]:Math.min(3,(old[active]??0)+1)}));
 const mark=(next:CallStatus)=>setStatuses(old=>({...old,[active]:next}));
 return <main className="calls-app">
  <nav className="calls-nav"><Link href="/"><img src="/brand/mascot/portrait.webp" alt=""/><span><b>{nativeLabel(level,"SPANISHCUE")}</b><small>{nativeLabel(level,"B1 · CONVERSACIÓN")}</small></span></Link><div><i/> {nativeLabel(level," TURNO NOCTURNO · ")}{current.time}</div><Link href="/">{nativeLabel(level,"BIBLIOTECA")}</Link></nav>
  <aside className="phone-wall">{calls.map((call,index)=><button key={call.name} className={`${active===index&&!finalMode?"active":""} ${statuses[index]?"handled":""}`} onClick={()=>chooseCall(index)}><span>{call.initials}</span><div><b>{call.name}</b><small>{call.time} · {call.minutes}</small></div><i>{statuses[index]==="RESUELTO"?"✓":index+1}</i></button>)}<button className={finalMode?"final active":"final"} onClick={()=>{setFinalMode(true);window.scrollTo({top:0,behavior:"auto"})}}><span>{nativeLabel(level,"SC")}</span><div><b>{nativeLabel(level,"AHORA TÚ")}</b><small>{nativeLabel(level,"10 min · conversación libre")}</small></div><i>8</i></button></aside>
  {!finalMode&&<><section className="calls-hero"><div className="calls-image"/><div className="calls-shade"/><article><span>{nativeLabel(level,"LLAMADA ")}{active+1}/7 · {current.minutes} {nativeLabel(level," · URGENCIA ")}{current.urgency}</span><h1>{active===0?nativeLabel(level,"La noche acaba de empezar."):nativeLabel(level,`Son las ${current.time}.`)}</h1><blockquote>{current.hint}</blockquote><p>{nativeInstruction('calls',level,(finalMode?2:1),"Contesta y habla antes de abrir información. Tu primera misión es descubrir qué ocurrió mediante preguntas naturales.",active)}</p><div className="answer-line"><span>{nativeLabel(level,"● EN LÍNEA · ")}{current.name}</span><h2>{nativeLabel(level,"¿Qué preguntarías primero?")}</h2><p>{nativeInstruction('calls',level,(finalMode?2:1),"El profesor responde en personaje. Una pregunta útil permite revelar el siguiente dato.",active)}</p></div></article></section>
  <section className="call-desk"><header><div><span>{nativeLabel(level,"EXPEDIENTE ")}{String(active+1).padStart(2,"0")} {nativeLabel(level," · INFORMACIÓN PROGRESIVA")}</span><h1>{nativeLabel(level,"No aconsejes todavía.")}</h1><p>{nativeInstruction('calls',level,(finalMode?2:1),"Pregunta, escucha y reacciona. Abre solo un dato después de cada respuesta.",active)}</p></div><aside><b>{solved}/7</b><span>{nativeLabel(level,"resueltas")}</span></aside></header>
   <div className="call-grid"><article className="caller-card"><div className="caller-head"><span>{current.initials}</span><div><small>{nativeLabel(level,"PERSONA EN LÍNEA")}</small><h2>{current.name}</h2></div><i>{nativeLabel(level,status)}</i></div><blockquote>{current.hint}</blockquote><div className="clue-stack">{current.clues.map((clue,index)=><section key={clue} className={facts>index?"open":""}><span>{facts>index?nativeLabel(level,`DATO ${index+1}`):nativeLabel(level,"INFORMACIÓN OCULTA")}</span><p>{facts>index?clue:nativeLabel(level,"Haz una pregunta concreta para desbloquearla.")}</p></section>)}</div><button className="reveal-call" onClick={reveal} disabled={facts===3}>{facts===3?nativeLabel(level,"TODA LA INFORMACIÓN ABIERTA"):nativeLabel(level,"REVELAR SIGUIENTE DATO")}</button></article>
   <aside className="operator-panel"><span>{nativeLabel(level,"TU MISIÓN")}</span><h2>{current.mission}</h2><div className="live-follow"><small>{nativeLabel(level,"REPREGUNTA DEL PROFESOR · ")}{follow+1}/{current.follow.length}</small><p>{current.follow[follow]}</p><button onClick={()=>setFollow(value=>(value+1)%current.follow.length)}>{nativeLabel(level,"OTRA REPREGUNTA →")}</button></div><button className="teacher-toggle" onClick={()=>setTeacherOpen(!teacherOpen)}>{teacherOpen?nativeLabel(level,"OCULTAR INDICACIÓN"):nativeLabel(level,"SOLO PROFESOR · ABRIR")}</button>{teacherOpen&&<div className="teacher-cue"><b>{nativeLabel(level,"ROLEPLAY")}</b><p>{current.teacher}</p></div>}<div className="status-row"><small>{nativeLabel(level,"MARCAR RESULTADO")}</small>{(["RESUELTO","NO RESUELTO","OTRA OPINIÓN"] as CallStatus[]).map(item=><button key={nativeLabel(level,item)} className={status===item?"active":""} onClick={()=>mark(item)}>{nativeLabel(level,item)}</button>)}</div></aside></div>
   <footer><button disabled={active===0} onClick={()=>chooseCall(active-1)}>{nativeLabel(level,"← LLAMADA ANTERIOR")}</button><span>{current.time}<i style={{width:`${((active+1)/7)*100}%`}}/></span>{active<6?<button onClick={()=>chooseCall(active+1)}>{nativeLabel(level,"SIGUIENTE LLAMADA →")}</button>:<button onClick={()=>{setFinalMode(true);window.scrollTo({top:0,behavior:"auto"})}}>{nativeLabel(level,"APAGAR LA CENTRAL →")}</button>}</footer>
  </section></>}
  {finalMode&&<section className="calls-final"><div className="city-off"/><header><span>{nativeLabel(level,"02:30 · LA CENTRAL SE APAGA · 10 MIN")}</span><h1>{nativeLabel(level,"Ahora te toca a ti.")}</h1><p>{nativeInstruction('calls',level,(finalMode?2:1),"Ya no hay llamadas que resolver. Elige una pregunta, habla desde tu experiencia y abre la repregunta solamente después de desarrollar la primera respuesta.",active)}</p></header><div className="final-call-grid">{finalQuestions.map(([question,deeper],index)=><button key={question} className={finalOpen===index?"open":""} onClick={()=>setFinalOpen(finalOpen===index?null:index)}><span>0{index+1}</span><h2>{question}</h2>{finalOpen===index&&<p>{deeper} {nativeLabel(level," · ¿Y el profesor?")}</p>}</button>)}</div><aside className="last-message"><img src="/brand/mascot/standing.webp" alt="Mascota oficial de SPANISHCUE"/><div><small>{nativeLabel(level,"ÚLTIMO MENSAJE")}</small><h2>{nativeLabel(level,"Cuenta un problema sin pedir consejo todavía.")}</h2><p>{nativeInstruction('calls',level,(finalMode?2:1),"El profesor debe hacerte tres preguntas antes de opinar. Después comparen las dos posibles soluciones.",active)}</p></div></aside></section>}
  <button className="calls-support-trigger" onClick={()=>setSupport(support?null:"PREGUNTAR MÁS")}>{support?nativeLabel(level,"CERRAR AYUDA"):nativeLabel(level,"AYUDA B1")}</button>{support&&<aside className="calls-support"><nav>{(Object.keys(supports) as (keyof typeof supports)[]).map(key=><button key={nativeLabel(level,key)} className={support===key?"active":""} onClick={()=>setSupport(key)}>{nativeLabel(level,key)}</button>)}</nav><div>{supports[support].map(item=><span key={nativeLabel(level,item)}>{nativeLabel(level,item)}</span>)}</div></aside>}
 <NativeSpeakingSupport key={`${level}-${(finalMode?2:1)}-${active}`} kind="calls" level={level} stage={(finalMode?2:1)} index={active}/></main>;
}

export default function SieteLlamadas(){
 const lesson=narratives.calls;
 return <ConversationFamily id={lesson.id} title={lesson.title} levels={narrativeLevels} defaultLevel="B1">{level=><SieteLlamadasNative key={level} level={level}/>}</ConversationFamily>;
}
