export type ChoiceCategory="VIDA"|"VIAJES"|"TRABAJO"|"PERSONAS"|"DINERO"|"TECNOLOGÍA"|"DECISIONES";

/** Tipo de conflicto que introduce una condición. Sirve para variar de verdad los dilemas y para validarlos. */
export type ConditionKind=
  |"DINERO"|"TIEMPO"|"DISTANCIA"|"CLIMA"|"COMODIDAD"|"RIESGO"|"PRIVACIDAD"|"COMPAÑÍA"|"TRABAJO"|"FAMILIA"
  |"RESPONSABILIDAD"|"SALUD"|"REPUTACIÓN"|"TECNOLOGÍA"|"OPORTUNIDAD"|"REGLAS"|"CANSANCIO"|"COMPROMISO"
  |"LIBERTAD"|"SORPRESA"|"CONFIANZA"|"DISPONIBILIDAD"|"PRIORIDADES";

/**
 * Una condición complica una de las dos opciones (`against`: 0 = opción A, 1 = opción B).
 * La condición 2 se suma a la condición 1: nunca la reemplaza ni la contradice.
 */
export type Condition={text:string;against:0|1;kind:ConditionKind};

/**
 * Un dilema completo. La etapa de elecciones rápidas usa `options` y `follow`;
 * la etapa de dilema usa además las dos condiciones y sus consignas:
 * decisión inicial → condición 1 → nueva decisión → condición 2 → decisión final con las dos a la vista.
 */
export type Choice={
  category:ChoiceCategory;
  options:[string,string];
  depth:1|2|3;
  /** Consigna después de la decisión inicial. */
  follow:string;
  condition1:Condition;
  /** Consigna para hablar después de la condición 1, antes de volver a elegir. */
  afterCondition1:string;
  condition2:Condition;
  /** Consigna final: tiene que obligar a comparar las dos condiciones juntas. */
  finalPrompt:string;
};

export const choiceBank:Choice[]=[
  {category:"VIDA",options:["VIVIR SOLO","COMPARTIR CASA"],depth:1,follow:"¿Qué es lo mejor y lo más difícil de tu opción?",
    condition1:{text:"En la casa compartida, tu habitación da al living y se escucha todo.",against:1,kind:"PRIVACIDAD"},
    afterCondition1:"¿Cuánto silencio necesitas para sentirte en casa?",
    condition2:{text:"Si vives solo, todas las tareas de la casa quedan para ti.",against:0,kind:"RESPONSABILIDAD"},
    finalPrompt:"Ruido en la casa compartida o todas las tareas para ti: ¿con cuál de esas dos rutinas podrías convivir todos los días?"},
  {category:"VIDA",options:["CIUDAD GRANDE","PUEBLO PEQUEÑO"],depth:1,follow:"¿Qué ritmo de vida funciona mejor para ti?",
    condition1:{text:"En el pueblo hay un solo lugar para hacer tu actividad favorita, y cierra los fines de semana.",against:1,kind:"DISPONIBILIDAD"},
    afterCondition1:"¿Qué actividad de tu semana sería imposible abandonar?",
    condition2:{text:"En la ciudad, llegar a la casa de tus amigos lleva una hora y media.",against:0,kind:"DISTANCIA"},
    finalPrompt:"Compara las dos pérdidas: tu actividad favorita en el pueblo o ver seguido a tus amigos en la ciudad. ¿Cuál te costaría menos y por qué?"},
  {category:"VIDA",options:["CERCA DEL TRABAJO","LEJOS, PERO MEJOR CASA"],depth:2,follow:"¿Qué vale más para ti: tiempo o espacio?",
    condition1:{text:"Desde la casa lejana tardas noventa minutos por día en ir y volver.",against:1,kind:"TIEMPO"},
    afterCondition1:"¿En qué usarías esos noventa minutos si vivieras cerca?",
    condition2:{text:"El departamento cerca del trabajo no tiene balcón y entra poca luz natural.",against:0,kind:"COMODIDAD"},
    finalPrompt:"Noventa minutos de viaje o una casa oscura: ¿cuál de los dos sacrificios notarías más en un martes normal?"},
  {category:"VIDA",options:["MADRUGAR","ACOSTARTE TARDE"],depth:1,follow:"¿En qué momento del día tienes más energía?",
    condition1:{text:"Las personas con quienes vives se levantan a las seis y la cocina está al lado de tu cuarto.",against:1,kind:"FAMILIA"},
    afterCondition1:"¿Cómo organizarías tus horarios para descansar igual?",
    condition2:{text:"Tus amigos solamente pueden verse de noche, después de las diez.",against:0,kind:"COMPAÑÍA"},
    finalPrompt:"Si madrugas, pierdes las noches con tus amigos; si te acuestas tarde, duermes con ruido. ¿Qué factor termina decidiendo por ti?"},
  {category:"VIDA",options:["RUTINA FIJA","IMPROVISAR"],depth:1,follow:"¿Cuándo te ayuda tu estilo y cuándo te complica?",
    condition1:{text:"Un amigo te invita a último momento a un recital que te encanta, el miércoles a la noche.",against:0,kind:"SORPRESA"},
    afterCondition1:"¿Qué harías con esa invitación y qué dejarías de hacer esa noche?",
    condition2:{text:"Esa misma semana tienes una entrega importante que depende de organizar bien cada día.",against:1,kind:"TRABAJO"},
    finalPrompt:"El recital sorpresa y la entrega importante caen en la misma semana. ¿Qué estilo te sirve más y qué riesgo asumes con él?"},
  {category:"VIDA",options:["ADOPTAR UN PERRO","SEGUIR SIN MASCOTA"],depth:2,follow:"¿Qué cambia en una casa cuando vive un animal?",
    condition1:{text:"Con un perro, cada escapada de fin de semana necesita que alguien lo cuide.",against:0,kind:"LIBERTAD"},
    afterCondition1:"¿Qué parte de tu libertad podrías negociar y cuál no?",
    condition2:{text:"Trabajas desde casa y pasas muchas horas sin hablar con nadie.",against:1,kind:"COMPAÑÍA"},
    finalPrompt:"Menos escapadas improvisadas o más horas solo en casa: ¿qué te pesa más a largo plazo?"},
  {category:"VIDA",options:["COCINAR EN CASA","COMER AFUERA"],depth:1,follow:"¿Qué plato te sale bien o qué lugar recomendarías?",
    condition1:{text:"Llegas a casa a las nueve de la noche, sin energía y con la cocina sin limpiar.",against:0,kind:"CANSANCIO"},
    afterCondition1:"¿Qué haces realmente una noche así?",
    condition2:{text:"El único lugar abierto cerca de tu casa vende solo comida frita.",against:1,kind:"SALUD"},
    finalPrompt:"Cocinar sin energía o comer frito otra vez: ¿qué prefieres sacrificar esta noche y qué harías mañana para compensarlo?"},

  {category:"VIAJES",options:["VIAJAR SOLO","VIAJAR ACOMPAÑADO"],depth:1,follow:"¿Qué cambia en un viaje cuando vas con alguien?",
    condition1:{text:"La única persona que puede acompañarte quiere un viaje muy distinto al tuyo.",against:1,kind:"PRIORIDADES"},
    afterCondition1:"¿Qué parte del viaje negociarías y qué parte no?",
    condition2:{text:"El destino es una zona de montaña donde se recomienda no hacer caminatas solo.",against:0,kind:"RIESGO"},
    finalPrompt:"Con alguien que quiere otro viaje o solo en un lugar donde conviene ir acompañado: ¿qué problema es más fácil de resolver?"},
  {category:"VIAJES",options:["PLAYA","MONTAÑA"],depth:1,follow:"¿Qué plan harías allí el primer día?",
    condition1:{text:"En la playa solo quedan habitaciones a cuarenta minutos del mar.",against:0,kind:"DISTANCIA"},
    afterCondition1:"¿Qué importa más en esas vacaciones: el paisaje o lo fácil que es llegar a él?",
    condition2:{text:"El único alojamiento libre en la montaña está al final de un sendero de dos horas, con mochila.",against:1,kind:"CANSANCIO"},
    finalPrompt:"Cuarenta minutos hasta el mar o dos horas caminando con mochila: ¿qué desventaja aceptarías para esas vacaciones?"},
  {category:"VIAJES",options:["VOLVER A TU LUGAR FAVORITO","CONOCER UNO NUEVO"],depth:2,follow:"¿Qué te da cada tipo de viaje?",
    condition1:{text:"Tu lugar favorito ahora cuesta el doble.",against:0,kind:"DINERO"},
    afterCondition1:"¿Cuánto vale para ti volver a un lugar que ya sabes que te gusta?",
    condition2:{text:"El lugar nuevo está en temporada de lluvias.",against:1,kind:"CLIMA"},
    finalPrompt:"Las dos opciones tienen una desventaja. ¿Cuál eliges y qué problema estás más dispuesto a aceptar?"},
  {category:"VIAJES",options:["VIAJAR LENTO","VISITAR MUCHOS LUGARES"],depth:2,follow:"¿Qué quieres recordar al volver?",
    condition1:{text:"Probablemente nunca vuelvas a esa región.",against:0,kind:"OPORTUNIDAD"},
    afterCondition1:"¿Qué te daría más pena no haber visto?",
    condition2:{text:"Visitar muchos lugares significa dormir en una cama distinta cada noche.",against:1,kind:"CANSANCIO"},
    finalPrompt:"Ver poco de una región a la que no vas a volver o cambiar de cama todas las noches: ¿cuál descartas y por qué?"},
  {category:"VIAJES",options:["HOTEL","CASA DE UNA FAMILIA LOCAL"],depth:2,follow:"¿Qué esperas de un buen alojamiento?",
    condition1:{text:"En la casa de familia compartes el baño y la cena es a una hora fija.",against:1,kind:"PRIVACIDAD"},
    afterCondition1:"¿Qué pesa más en un viaje: tu independencia o ver cómo vive la gente del lugar?",
    condition2:{text:"La familia te invita a una fiesta del pueblo que no aparece en ninguna guía, y desde el hotel no te vas a enterar.",against:0,kind:"OPORTUNIDAD"},
    finalPrompt:"Baño compartido y horarios fijos, pero una fiesta que no vas a ver en otro lado: ¿qué te hace inclinar la balanza?"},
  {category:"VIAJES",options:["TREN NOCTURNO","AVIÓN TEMPRANO"],depth:2,follow:"¿Qué disfrutas más: el camino o llegar rápido?",
    condition1:{text:"El avión sale a las seis y tienes que estar en el aeropuerto a las cuatro.",against:1,kind:"TIEMPO"},
    afterCondition1:"¿Cómo te imaginas el primer día del viaje en cada caso?",
    condition2:{text:"En el tren ya no quedan camas: solo asientos, y el viaje dura once horas.",against:0,kind:"COMODIDAD"},
    finalPrompt:"Levantarte a las cuatro o pasar once horas en un asiento: ¿cómo llegarías mejor al destino? Justifícalo con las dos condiciones."},
  {category:"VIAJES",options:["VIAJE ORGANIZADO","ARMARLO TÚ"],depth:2,follow:"Cuenta un viaje en que tu forma de organizar salió muy bien o muy mal.",
    condition1:{text:"El viaje organizado tiene horarios fijos todos los días, incluso para comer.",against:0,kind:"LIBERTAD"},
    afterCondition1:"¿Qué parte de un viaje necesitas decidir tú?",
    condition2:{text:"En ese país casi nadie habla tu idioma ni inglés, y los micros cambian de horario sin avisar.",against:1,kind:"RIESGO"},
    finalPrompt:"Horarios fijos para todo o resolver por tu cuenta un transporte imprevisible: ¿con cuál de los dos problemas viajarías más tranquilo?"},

  {category:"TRABAJO",options:["TRABAJO REMOTO","OFICINA"],depth:1,follow:"¿Qué opción mejora tu día normal?",
    condition1:{text:"La oficina queda a una hora de tu casa.",against:1,kind:"DISTANCIA"},
    afterCondition1:"¿Qué harías con esas dos horas diarias si no tuvieras que viajar?",
    condition2:{text:"El equipo toma las decisiones importantes en charlas informales en la oficina, y quien trabaja remoto se entera tarde.",against:0,kind:"OPORTUNIDAD"},
    finalPrompt:"Dos horas de viaje por día o quedarte afuera de las conversaciones importantes: ¿qué condición te importa más?"},
  {category:"TRABAJO",options:["JEFE EXIGENTE QUE ENSEÑA MUCHO","JEFE RELAJADO QUE ENSEÑA POCO"],depth:2,follow:"¿Qué necesitas de la persona que dirige tu trabajo?",
    condition1:{text:"El jefe exigente escribe mensajes fuera de horario y espera respuesta rápida.",against:0,kind:"DISPONIBILIDAD"},
    afterCondition1:"¿Qué vale más para ti en esta etapa: aprender rápido o desconectarte al salir?",
    condition2:{text:"Con el jefe relajado, nadie en la empresa ve tus resultados.",against:1,kind:"REPUTACIÓN"},
    finalPrompt:"Mensajes fuera de horario o un trabajo que nadie ve: ¿con cuál de los dos jefes aguantarías un año completo?"},
  {category:"TRABAJO",options:["TRABAJO INTERESANTE","TRABAJO ESTABLE"],depth:2,follow:"¿Qué necesitarías saber antes de decidir?",
    condition1:{text:"El proyecto interesante tiene contrato por un año, sin garantía de renovación.",against:0,kind:"RIESGO"},
    afterCondition1:"¿Qué plan B tendrías si ese contrato termina en un año?",
    condition2:{text:"El trabajo estable es igual al que haces hoy, y ya te aburre.",against:1,kind:"PRIORIDADES"},
    finalPrompt:"Un año incierto o seguir aburriéndote con seguridad: defiende tu decisión mencionando las dos condiciones."},
  {category:"TRABAJO",options:["4 DÍAS MÁS LARGOS","5 DÍAS MÁS CORTOS"],depth:2,follow:"¿Cómo organizarías tu semana?",
    condition1:{text:"Con jornadas de diez horas, no llegas a cenar con tu familia de lunes a jueves.",against:0,kind:"FAMILIA"},
    afterCondition1:"¿Qué momentos de la semana no negociarías?",
    condition2:{text:"Con el viernes libre podrías hacer un curso que siempre quisiste y que se dicta solo ese día.",against:1,kind:"OPORTUNIDAD"},
    finalPrompt:"Cenas familiares o el curso de los viernes: ¿qué tendría que cambiar para que eligieras la otra semana?"},
  {category:"TRABAJO",options:["MÁS SUELDO","MÁS TIEMPO LIBRE"],depth:1,follow:"¿Cuánto tiempo cambiarías por más dinero?",
    condition1:{text:"El aumento incluye trabajar dos sábados por mes.",against:0,kind:"TIEMPO"},
    afterCondition1:"¿Qué te perderías esos sábados?",
    condition2:{text:"Este año tu familia necesita tu ayuda para arreglar el techo de su casa.",against:1,kind:"RESPONSABILIDAD"},
    finalPrompt:"Dos sábados de trabajo por mes o no poder ayudar con el techo: ¿qué responsabilidad pones primero?"},
  {category:"TRABAJO",options:["TRABAJAR EN EQUIPO","TRABAJAR SOLO"],depth:1,follow:"¿En qué tipo de tarea rindes más?",
    condition1:{text:"En el equipo hay una persona que suele presentar como propio el trabajo de los demás.",against:0,kind:"CONFIANZA"},
    afterCondition1:"¿Qué necesitas para confiar en un equipo?",
    condition2:{text:"Si trabajas solo, cualquier error del proyecto es completamente tu responsabilidad.",against:1,kind:"RESPONSABILIDAD"},
    finalPrompt:"Compartir el mérito con alguien poco confiable o cargar solo con cada error: ¿qué riesgo aceptas y cómo lo manejarías?"},
  {category:"TRABAJO",options:["ASCENSO CON PERSONAS A CARGO","QUEDARTE EN TU PUESTO"],depth:2,follow:"¿Qué te atrae y qué te da miedo de dirigir a otras personas?",
    condition1:{text:"Tus futuros colaboradores son los compañeros con quienes almuerzas todos los días.",against:0,kind:"COMPAÑÍA"},
    afterCondition1:"¿Qué cambiaría en tu relación con ellos?",
    condition2:{text:"Si rechazas el ascenso, la próxima oportunidad puede tardar varios años.",against:1,kind:"OPORTUNIDAD"},
    finalPrompt:"Dirigir a tus compañeros de almuerzo o esperar años otra oportunidad: ¿qué opción te parece más razonable ahora y qué pierdes con ella?"},

  {category:"PERSONAS",options:["POCOS AMIGOS MUY CERCANOS","MUCHOS CONOCIDOS"],depth:1,follow:"¿Qué esperas de una amistad?",
    condition1:{text:"Dos de tus amigos más cercanos se mudan a otro país este año.",against:0,kind:"DISTANCIA"},
    afterCondition1:"¿Qué le pasa a un grupo pequeño cuando alguien se va?",
    condition2:{text:"Tienes un problema personal serio y necesitas hablar con alguien de total confianza.",against:1,kind:"CONFIANZA"},
    finalPrompt:"Un grupo pequeño que se achica o un grupo grande donde no sabes a quién contarle algo serio: ¿qué eliges con toda esta información?"},
  {category:"PERSONAS",options:["AMIGO DIVERTIDO","AMIGO CONFIABLE"],depth:1,follow:"Tienes que organizar una fiesta grande: ¿a quién le pides ayuda y por qué?",
    condition1:{text:"El amigo divertido ya se olvidó dos veces de reservar el lugar de una fiesta.",against:0,kind:"COMPROMISO"},
    afterCondition1:"¿Qué tareas le darías a cada uno?",
    condition2:{text:"El amigo confiable casi no conoce a tus invitados y en grupo se pone muy serio.",against:1,kind:"COMPAÑÍA"},
    finalPrompt:"Una fiesta que puede salir mal o una fiesta segura pero apagada: ¿qué problema aceptas más fácilmente?"},
  {category:"PERSONAS",options:["DECIR LO QUE PIENSAS","EVITAR EL CONFLICTO"],depth:2,follow:"¿Dónde pones el límite?",
    condition1:{text:"La otra persona está pasando un momento difícil.",against:0,kind:"CONFIANZA"},
    afterCondition1:"¿Qué dirías y qué te callarías en este momento?",
    condition2:{text:"El mismo problema ya pasó cuatro veces este mes y afecta tu trabajo.",against:1,kind:"TRABAJO"},
    finalPrompt:"La persona está mal, pero el problema se repite y te perjudica: convence a otra persona de que tu manera de actuar es la correcta."},
  {category:"PERSONAS",options:["PEDIR CONSEJO","DECIDIR SOLO"],depth:1,follow:"¿A quién escucharías y por qué?",
    condition1:{text:"La única persona que conoce bien el tema no sabe guardar secretos.",against:0,kind:"PRIVACIDAD"},
    afterCondition1:"¿Qué información compartirías y cuál no?",
    condition2:{text:"Tienes que decidir antes del viernes y sabes muy poco del tema.",against:1,kind:"TIEMPO"},
    finalPrompt:"Arriesgar tu privacidad o decidir rápido sobre algo que no conoces: ¿qué pesa más ahora?"},
  {category:"PERSONAS",options:["PERDONAR RÁPIDO","TOMARTE TIEMPO"],depth:2,follow:"¿Qué tendría que hacer la otra persona?",
    condition1:{text:"La persona no pidió disculpas de verdad: solo dijo «bueno, perdón».",against:0,kind:"CONFIANZA"},
    afterCondition1:"¿Qué esperas de una disculpa real?",
    condition2:{text:"Mañana tienen que viajar juntos al casamiento de un amigo en común.",against:1,kind:"COMPROMISO"},
    finalPrompt:"Una disculpa floja y un viaje juntos mañana: ¿qué haces y qué parte del problema dejas para después?"},
  {category:"PERSONAS",options:["FIESTA CON GENTE NUEVA","CENA CON AMIGOS DE SIEMPRE"],depth:1,follow:"¿En qué situación social te sientes más tú?",
    condition1:{text:"En la fiesta va a estar alguien que trabaja en lo que siempre quisiste hacer.",against:1,kind:"OPORTUNIDAD"},
    afterCondition1:"¿Cuánto vale esa oportunidad frente a una noche tranquila?",
    condition2:{text:"Tuviste una semana agotadora y la fiesta termina a las cuatro de la mañana.",against:0,kind:"CANSANCIO"},
    finalPrompt:"Una oportunidad profesional con muy poca energía o descanso con tu gente: ¿qué factor terminó siendo decisivo?"},
  {category:"PERSONAS",options:["AYUDAR A UN AMIGO CON SU MUDANZA","IR AL PLAN QUE YA TENÍAS"],depth:2,follow:"¿Cuándo te cuesta decir que no?",
    condition1:{text:"Ese amigo te ayudó con tu propia mudanza el año pasado.",against:1,kind:"COMPROMISO"},
    afterCondition1:"¿Qué le debes a alguien que te ayudó antes?",
    condition2:{text:"Tu plan es el último día de un taller que no se repite hasta el año que viene.",against:0,kind:"PRIORIDADES"},
    finalPrompt:"Una deuda de amistad o algo importante para ti que no se repite: ¿qué sacrificio prefieres hacer y cómo se lo explicarías a tu amigo?"},

  {category:"DINERO",options:["AHORRAR","DISFRUTAR AHORA"],depth:1,follow:"¿Qué equilibrio intentas mantener?",
    condition1:{text:"Tus amigos organizan un viaje de reencuentro que solo va a pasar este año.",against:0,kind:"SORPRESA"},
    afterCondition1:"¿Qué recuerdos valen el gasto para ti?",
    condition2:{text:"Tu computadora de trabajo está por romperse y la necesitas para ganar dinero.",against:1,kind:"TECNOLOGÍA"},
    finalPrompt:"El viaje que no se repite o la computadora que sostiene tu trabajo: ¿qué prioridad pones primero y qué harías con la otra?"},
  {category:"DINERO",options:["GASTAR EN EXPERIENCIAS","GASTAR EN COSAS"],depth:1,follow:"¿Qué compra o experiencia recuerdas especialmente?",
    condition1:{text:"La experiencia que quieres es un recital en otra ciudad: dura una sola noche.",against:0,kind:"TIEMPO"},
    afterCondition1:"¿Qué te queda después de una experiencia que dura una noche?",
    condition2:{text:"Tu casa es chica y ya no tienes dónde guardar nada más.",against:1,kind:"COMODIDAD"},
    finalPrompt:"Algo que dura una noche o algo que no entra en tu casa: compara las dos opciones y di cuál te deja algo más valioso."},
  {category:"DINERO",options:["CASA PEQUEÑA PROPIA","CASA GRANDE ALQUILADA"],depth:2,follow:"¿Qué significa seguridad para ti?",
    condition1:{text:"La casa propia está a dos horas de tu familia y tus amigos.",against:0,kind:"DISTANCIA"},
    afterCondition1:"¿Qué pesa más ahora: tener algo propio o vivir cerca de tu gente?",
    condition2:{text:"El contrato de alquiler no permite mascotas ni hacer cambios en la casa.",against:1,kind:"REGLAS"},
    finalPrompt:"Lejos de tu gente o con reglas que no elegiste: ¿cuál de los dos problemas prefieres tener?"},
  {category:"DINERO",options:["ALGO CARO Y DURADERO","ALGO BARATO Y CAMBIARLO SEGUIDO"],depth:2,follow:"¿Con qué productos piensas así?",
    condition1:{text:"Comprar lo caro te deja sin dinero para el resto del mes.",against:0,kind:"DINERO"},
    afterCondition1:"¿Cuánto te importa llegar justo a fin de mes si el producto dura años?",
    condition2:{text:"Lo barato se rompió tres veces este año y cada vez perdiste una tarde buscando otro.",against:1,kind:"TIEMPO"},
    finalPrompt:"Un mes ajustado o perder tardes reemplazando cosas: defiende tu opción con un ejemplo real."},
  {category:"DINERO",options:["PAGAR TODO A MEDIAS","CADA UNO PAGA LO QUE USA"],depth:2,follow:"¿Qué sistema te parece más justo para compartir una casa?",
    condition1:{text:"Una de las dos personas gana tres veces más que la otra.",against:0,kind:"DINERO"},
    afterCondition1:"¿Qué sería justo cuando los ingresos son tan distintos?",
    condition2:{text:"Anotar quién usa qué genera discusiones todas las semanas.",against:1,kind:"COMODIDAD"},
    finalPrompt:"Una división desigual o discusiones semanales por las cuentas: ¿qué sistema defenderías frente a la otra persona?"},
  {category:"DINERO",options:["PRESTAR DINERO A UN AMIGO","DECIR QUE NO"],depth:2,follow:"¿Qué cambia cuando mezclas amistad y dinero?",
    condition1:{text:"Ya le prestaste una vez y tardó un año en devolverlo.",against:0,kind:"CONFIANZA"},
    afterCondition1:"¿Qué condiciones le pondrías antes de decidir?",
    condition2:{text:"Necesita ese dinero para no perder el departamento donde vive con su hijo.",against:1,kind:"FAMILIA"},
    finalPrompt:"Una deuda vieja que tardó en volver y una urgencia real: ¿qué harías exactamente y qué riesgo aceptas?"},

  {category:"TECNOLOGÍA",options:["MENSAJES","LLAMADAS"],depth:1,follow:"Tienes que aclarar un malentendido con un amigo: ¿cómo lo haces y por qué?",
    condition1:{text:"Estás en el tren y todos a tu alrededor pueden escuchar.",against:1,kind:"PRIVACIDAD"},
    afterCondition1:"¿Qué parte de la conversación podrías resolver por escrito?",
    condition2:{text:"Tu amigo ya malinterpretó dos mensajes tuyos esta semana.",against:0,kind:"CONFIANZA"},
    finalPrompt:"Una llamada con gente escuchando o un mensaje que puede entenderse mal otra vez: ¿qué eliges y qué harías para reducir ese riesgo?"},
  {category:"TECNOLOGÍA",options:["REDES SOCIALES","NINGUNA RED"],depth:2,follow:"¿Qué ganarías y qué perderías?",
    condition1:{text:"Una foto tuya vieja y vergonzosa empezó a circular entre tus contactos.",against:0,kind:"REPUTACIÓN"},
    afterCondition1:"¿Cuánto control quieres tener sobre tu imagen?",
    condition2:{text:"En tu trabajo, los clientes nuevos te encuentran por tus publicaciones.",against:1,kind:"TRABAJO"},
    finalPrompt:"Exponerte a que circule otra foto así o perder clientes nuevos: ¿qué factor pesa más para ti?"},
  {category:"TECNOLOGÍA",options:["COMPRAR ONLINE","COMPRAR EN TIENDA"],depth:1,follow:"Necesitas un regalo para el cumpleaños de mañana: ¿cómo lo consigues?",
    condition1:{text:"El envío llega mañana a la noche, justo antes del cumpleaños, si no se atrasa.",against:0,kind:"RIESGO"},
    afterCondition1:"¿Cuánto riesgo aceptas con un regalo importante?",
    condition2:{text:"La única tienda que lo tiene queda del otro lado de la ciudad y cierra a las siete.",against:1,kind:"DISTANCIA"},
    finalPrompt:"Un envío que puede llegar tarde o cruzar la ciudad antes de las siete: ¿qué eliges con esta nueva información?"},
  {category:"TECNOLOGÍA",options:["IA PARA AYUDARTE","HACERLO TODO TÚ"],depth:2,follow:"¿Qué tarea nunca delegarías?",
    condition1:{text:"La herramienta guarda todo lo que escribes, incluidos datos de tu trabajo.",against:0,kind:"PRIVACIDAD"},
    afterCondition1:"¿Qué información nunca le darías a una herramienta así?",
    condition2:{text:"Este mes tienes el doble de tareas y el mismo horario.",against:1,kind:"TRABAJO"},
    finalPrompt:"Tus datos guardados o el doble de trabajo en el mismo horario: ¿cuál de las dos desventajas puedes controlar mejor?"},
  {category:"TECNOLOGÍA",options:["INTERNET SIEMPRE","UN DÍA DESCONECTADO POR SEMANA"],depth:2,follow:"¿Cómo sería ese día sin internet?",
    condition1:{text:"Tu familia vive lejos y solo puede hablar contigo por videollamada.",against:1,kind:"FAMILIA"},
    afterCondition1:"¿Qué conexiones son imprescindibles para ti y cuáles no?",
    condition2:{text:"Últimamente duermes mal porque miras el celular hasta la madrugada.",against:0,kind:"SALUD"},
    finalPrompt:"Estar disponible para tu familia o cortar con el celular que no te deja dormir: ¿qué sacrificio harías y cómo lo organizarías?"},
  {category:"TECNOLOGÍA",options:["AUTO","TRANSPORTE PÚBLICO"],depth:1,follow:"Compara precio, tiempo y comodidad.",
    condition1:{text:"En tu barrio casi no hay estacionamiento y las multas son altas.",against:0,kind:"REGLAS"},
    afterCondition1:"¿Cómo cambiaría tu día con esa regla?",
    condition2:{text:"Después de las nueve de la noche, el autobús pasa cada cuarenta minutos.",against:1,kind:"DISPONIBILIDAD"},
    finalPrompt:"Buscar estacionamiento todos los días o esperar cuarenta minutos de noche: ¿cuál de las dos rutinas soportarías mejor?"},
  {category:"TECNOLOGÍA",options:["SERIE EN CASA","PELÍCULA EN EL CINE"],depth:1,follow:"¿Qué hace especial una noche de película?",
    condition1:{text:"Un amigo que ves poco te propone ir al cine juntos esta noche.",against:0,kind:"COMPAÑÍA"},
    afterCondition1:"¿Qué vale más esta noche: descansar o ver a alguien que ves poco?",
    condition2:{text:"En el cine la película está doblada, y a ti te gusta en versión original.",against:1,kind:"PRIORIDADES"},
    finalPrompt:"Decirle que no a tu amigo o ver una película doblada: ¿cómo le explicarías tu decisión a esa persona?"},

  {category:"DECISIONES",options:["UN AÑO LIBRE AHORA","JUBILARTE CINCO AÑOS ANTES"],depth:3,follow:"¿En qué etapa de la vida vale más el tiempo?",
    condition1:{text:"Tu empresa no te guarda el puesto durante ese año.",against:0,kind:"TRABAJO"},
    afterCondition1:"¿Qué riesgo profesional aceptarías por un año así?",
    condition2:{text:"Tu plan para ese año necesita estar en forma: cruzar un país en bicicleta.",against:1,kind:"SALUD"},
    finalPrompt:"Perder tu puesto o dejar para dentro de treinta años un plan que necesita energía: ¿cuál de las dos condiciones te importa más?"},
  {category:"DECISIONES",options:["TRABAJO ESPECTACULAR EN OTRO PAÍS","TRABAJO NORMAL CERCA DE TU GENTE"],depth:3,follow:"¿Qué hace que un lugar se sienta como hogar?",
    condition1:{text:"El contrato es por tres años y no permite volver antes.",against:0,kind:"COMPROMISO"},
    afterCondition1:"¿Qué te perderías en tres años lejos?",
    condition2:{text:"En tu ciudad, el trabajo normal no tiene ninguna posibilidad de crecer.",against:1,kind:"OPORTUNIDAD"},
    finalPrompt:"Tres años sin poder volver o un trabajo sin futuro cerca de tu gente: ¿qué tendría que pasar para que eligieras la otra opción?"},
  {category:"DECISIONES",options:["SABER QUÉ VA A PASAR","VIVIR CON SORPRESA"],depth:3,follow:"¿La seguridad haría tu vida más tranquila o más aburrida? ¿Por qué?",
    condition1:{text:"Saber el futuro incluye conocer también las malas noticias, con fecha exacta.",against:0,kind:"RIESGO"},
    afterCondition1:"¿Qué noticia preferirías no saber antes de tiempo?",
    condition2:{text:"Este mes tienes que decidir si aceptas un trabajo en otra ciudad.",against:1,kind:"PRIORIDADES"},
    finalPrompt:"Conocer también lo malo o decidir algo enorme sin saber cómo sale: explica qué ganas y qué pierdes con tu elección final."},
  {category:"DECISIONES",options:["HABLAR TODOS LOS IDIOMAS","PODER VIVIR EN CUALQUIER PAÍS"],depth:2,follow:"¿Cómo usarías esa posibilidad?",
    condition1:{text:"Con todos los idiomas, cada país te pide visa y papeles como a cualquier persona.",against:0,kind:"REGLAS"},
    afterCondition1:"¿Qué harías primero con cada poder?",
    condition2:{text:"Puedes vivir en cualquier país, pero no aprendes ningún idioma nuevo.",against:1,kind:"COMPAÑÍA"},
    finalPrompt:"Entenderlo todo sin poder quedarte o quedarte donde quieras sin entender a nadie: ¿qué poder eliges y cómo lo usarías el primer mes?"},
  {category:"DECISIONES",options:["SER EXCELENTE EN UNA COSA","SER BUENO EN MUCHAS"],depth:3,follow:"¿Qué opción abre más puertas?",
    condition1:{text:"Lo que harías de forma excelente puede cambiar mucho con la automatización en diez años.",against:0,kind:"TECNOLOGÍA"},
    afterCondition1:"¿Qué habilidad crees que va a seguir valiendo dentro de diez años?",
    condition2:{text:"Las empresas que te interesan contratan especialistas, no perfiles generales.",against:1,kind:"TRABAJO"},
    finalPrompt:"Una especialidad que puede cambiar o un perfil amplio que esas empresas no buscan: ¿cómo prepararías tu futuro?"},
  {category:"DECISIONES",options:["MUCHO ÉXITO PÚBLICO","VIDA PRIVADA TRANQUILA"],depth:3,follow:"¿Qué parte de tu vida protegerías?",
    condition1:{text:"Desconocidos opinan en internet sobre cada decisión tuya.",against:0,kind:"REPUTACIÓN"},
    afterCondition1:"¿Cuánta crítica pública aguantarías y por qué?",
    condition2:{text:"Con el éxito podrías sostener un proyecto de tu barrio que hoy no tiene apoyo.",against:1,kind:"RESPONSABILIDAD"},
    finalPrompt:"Críticas constantes o un proyecto de tu barrio sin apoyo: ¿qué te parece más importante y qué renunciarías a tener?"},
  {category:"DECISIONES",options:["SER RECORDADO POR TU TRABAJO","SER RECORDADO POR CÓMO TRATASTE A LA GENTE"],depth:3,follow:"¿Qué legado te parece más importante?",
    condition1:{text:"Tu trabajo puede mejorar la vida de miles de personas.",against:1,kind:"OPORTUNIDAD"},
    afterCondition1:"¿Qué harías con esa posibilidad?",
    condition2:{text:"Ese trabajo exige viajar casi todo el año, lejos de tu gente.",against:0,kind:"FAMILIA"},
    finalPrompt:"Miles de personas beneficiadas o estar presente para los tuyos: ¿qué sacrificio harías y cómo te gustaría que te recuerden?"},
];

export const choiceCategories=[
  {value:"TODO",label:"TODO"},
  {value:"VIDA",label:"VIDA"},
  {value:"VIAJES",label:"VIAJES"},
  {value:"TRABAJO",label:"TRABAJO"},
  {value:"PERSONAS",label:"PERSONAS"},
  {value:"DINERO",label:"DINERO"},
  {value:"TECNOLOGÍA",label:"TECNOLOGÍA / VIDA MODERNA"},
  {value:"DECISIONES",label:"DECISIONES MÁS INTERESANTES"},
] as const;
