import test from 'node:test';import assert from 'node:assert/strict';import {JSDOM,VirtualConsole} from 'jsdom';import {build} from 'esbuild';import{createRequire}from'node:module';
const require=createRequire(import.meta.url);
const compiled=await build({entryPoints:['app/bosque-de-los-hongos-gigantes/BosqueHongos.tsx'],bundle:true,platform:'node',format:'cjs',write:false,loader:{'.css':'empty'},jsx:'automatic',external:['react','react-dom/client'],plugins:[{name:'local-link-fixture',setup(b){b.onResolve({filter:/^next\/link$/},()=>({path:'link',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'import React from "react";export default function Link({children,...props}){return React.createElement("a",props,children)}',loader:'js'}));}}]});
const m={exports:{}};new Function('require','module','exports',compiled.outputFiles[0].text)(require,m,m.exports);
const React=require('react'),{act}=React,{createRoot}=require('react-dom/client');
async function mount(query='A1',reduced=true){
 const dom=new JSDOM('<div id="root"></div>',{url:`https://test.invalid/?level=${query}`,pretendToBeVisual:true,virtualConsole:new VirtualConsole()});
 for(const k of ['window','document','HTMLElement','localStorage','location','history','KeyboardEvent','Event'])globalThis[k]=dom.window[k];
 window.matchMedia=()=>({matches:reduced,addEventListener(){},removeEventListener(){}});
 HTMLElement.prototype.getClientRects=function(){return[{width:100,height:30}];};
 globalThis.IS_REACT_ACT_ENVIRONMENT=true;const root=createRoot(document.getElementById('root'));
 await act(async()=>root.render(React.createElement(m.exports.default)));
 return{dom,root,async stop(){await act(()=>root.unmount());dom.window.close();}};
}
const button=(text)=>Array.from(document.querySelectorAll('button')).find(b=>b.textContent.includes(text));
async function click(b){assert.ok(b);await act(()=>{b.focus();b.click();});}
test('prompt replacement retains dialog focus and traps Tab from outside',async()=>{const t=await mount();try{await click(button('Entrar en el bosque'));await click(button('Sobre ti'));await click(button('Otra de esta categoría'));assert.ok(document.querySelector('[role="dialog"]').contains(document.activeElement),'focus remains inside replaced card');button('SPANISH')?.focus();document.querySelector('a').focus();await act(()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Tab',bubbles:true,cancelable:true})));assert.ok(document.querySelector('[role="dialog"]').contains(document.activeElement));}finally{await t.stop();}});
test('Escape closes the class guide',async()=>{const t=await mount();try{await click(document.querySelector('[aria-label="Ayuda y controles"]'));assert.ok(document.querySelector('.bh-help'));await act(()=>document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true})));assert.equal(document.querySelector('.bh-help'),null);}finally{await t.stop();}});
test('query levels, fallback prompts and direct vocabulary work for all six levels',async()=>{for(const level of ['A1','A2','B1','B2','C1','C2','invalid']){const t=await mount(level);try{const active=level==='invalid'?'A1':level;assert.equal(document.querySelector('[aria-pressed="true"]').textContent,active);await click(button('Entrar en el bosque'));assert.equal(document.querySelectorAll('.bh-map-view .bh-category-grid button').length,12);await click(button('Elige'));const title=document.querySelector('.bh-prompt h2').textContent;assert.ok(title);assert.equal(Boolean(document.querySelector('.conversation-glosses')),['A1','A2','B1','B2'].includes(active));await click(document.querySelector('.bh-choices button'));if(active==='B1'){assert.ok(document.querySelector('.bh-scene'),'the landmark sets the scene');assert.match(document.querySelector('.bh-answer-cue').textContent,/experiencia local/);assert.match(document.querySelector('.bh-open').textContent,/sin saber exactamente qué era/);}else{assert.equal(document.querySelector('.bh-scene'),null);assert.match(document.querySelector('.bh-answer-cue').textContent,/explica por qué|Explica tus prioridades/);}await click(button('Repregunta'));assert.ok(document.querySelector('.bh-followup'));await click(button('Marcar como hablada'));assert.match(document.querySelector('.bh-session-bar').textContent,/1 preguntas habladas/);await click(Array.from(document.querySelectorAll('.bh-levels button')).find(b=>b.textContent===active));assert.match(document.querySelector('.bh-session-bar').textContent,/1 preguntas habladas/);}finally{await t.stop();}}});

test('changing level in a conversation clears choices and follow-ups and uses only the new bank',async()=>{const t=await mount();try{await click(button('Entrar en el bosque'));await click(button('Elige'));await click(document.querySelector('.bh-choices button'));await click(button('Repregunta'));assert.ok(document.querySelector('.bh-answer-cue'));await click(Array.from(document.querySelectorAll('.bh-levels button')).find(b=>b.textContent==='C2'));assert.match(document.querySelector('.bh-prompt-label').textContent,/C2/);assert.equal(document.querySelector('.bh-answer-cue'),null);assert.equal(document.querySelector('.bh-followup'),null);assert.equal(document.querySelector('.conversation-glosses'),null);assert.ok(document.querySelector('[role="dialog"]').contains(document.activeElement));assert.match(document.querySelector('.bh-session-bar').textContent,/0 preguntas habladas/);}finally{await t.stop();}});
test('a real WebGL creation failure opens the complete fallback without losing the selected level',async()=>{const t=await mount('B1',false);try{await click(button('Entrar en el bosque'));await act(async()=>{await new Promise(resolve=>setTimeout(resolve,50));});assert.equal(document.querySelectorAll('.bh-map-view .bh-category-grid button').length,12);await click(button('Sobre ti'));assert.match(document.querySelector('.bh-prompt-label').textContent,/B1/);assert.ok(document.querySelector('.conversation-glosses'));}finally{await t.stop();}});

test('B1 stations open once, then the landmark draws from its category deck; the summit opens the expedition final',async()=>{const t=await mount('B1');try{await click(button('Entrar en el bosque'));
 await click(button('Sobre ti'));assert.match(document.querySelector('.bh-prompt h2').textContent,/lugar nuevo/);assert.ok(document.querySelector('.bh-open-skip'),'open question waits for the choice');await click(button('Pasar a la conversación abierta'));assert.match(document.querySelector('.bh-open').textContent,/Cuenta un lugar/);await click(button('Marcar como hablada'));
 await click(button('Sobre ti'));assert.equal(document.querySelector('.bh-scene'),null,'second visit uses the deck');assert.doesNotMatch(document.querySelector('.bh-prompt h2').textContent,/lugar nuevo/);await click(button('Marcar como hablada'));
 for(const zone of ['Vida real','Elige','Opina','Supón','Reacciona','Compara','Recuerda','Imagina']){await click(button(zone));assert.ok(document.querySelector('.bh-scene'),zone);await click(button('Marcar como hablada'));}
 await click(button('Gran final'));assert.match(document.querySelector('.bh-prompt-label').textContent,/1 \/ 3/);assert.match(document.querySelector('.bh-prompt h2').textContent,/hasta las nubes/);assert.ok(document.querySelector('.bh-open'),'summit has no choice: the open question shows directly');
}finally{await t.stop();}});
test('A2 keeps the category banks in the same world',async()=>{const t=await mount('A2');try{await click(button('Entrar en el bosque'));await click(button('Sobre ti'));assert.equal(document.querySelector('.bh-scene'),null);assert.match(document.querySelector('.bh-prompt-label').textContent,/A2/);}finally{await t.stop();}});
