import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {createRequire} from 'node:module';
import {JSDOM} from 'jsdom';
import React,{act} from 'react';
import {createRoot} from 'react-dom/client';
await build({entryPoints:['app/grammar-classroom/GrammarPage.tsx'],bundle:true,platform:'node',format:'cjs',jsx:'automatic',external:['react','react-dom','next/link','next/navigation'],loader:{'.css':'empty'},outfile:'node_modules/.cache/observatory-page.cjs'});
const require=createRequire(import.meta.url);
const Page=require('../node_modules/.cache/observatory-page.cjs').default;
async function mount(){const dom=new JSDOM('<div id="root"></div>',{url:'https://spanishcue.test'});Object.assign(globalThis,{window:dom.window,self:dom.window,document:dom.window.document,HTMLElement:dom.window.HTMLElement,IS_REACT_ACT_ENVIRONMENT:true});dom.window.HTMLElement.prototype.scrollIntoView=function(){};dom.window.HTMLMediaElement.prototype.pause=function(){};const root=createRoot(document.getElementById('root'));await act(async()=>root.render(React.createElement(Page,{id:43})));return {click:async s=>{const el=document.querySelector(s);assert.ok(el,s);await act(async()=>el.click());},close:async()=>{await act(async()=>root.unmount());dom.window.close();}};}
test('demonstratives follow the speaker and agree with the selected object',async()=>{const v=await mount();try{assert.ok(document.querySelector('[data-observatory]'));await v.click('[data-object="notebook"]');assert.match(document.querySelector('[data-scene-answer]').textContent,/esta libreta/);await v.click('[data-swap-speaker]');assert.match(document.querySelector('[data-scene-answer]').textContent,/esa libreta/);await v.click('[data-object="boxes"]');assert.match(document.querySelector('[data-scene-answer]').textContent,/aquellas cajas/);}finally{await v.close();}});
test('eight bilingual stages retain real audio and choice feedback',async()=>{const v=await mount();try{assert.equal(document.querySelectorAll('[data-stage]').length,8);await v.click('[data-stage="practice"]');await v.click('input[value="1"]');await v.click('[data-check="0"]');assert.match(document.body.textContent,/Try again/);await v.click('input[value="0"]');await v.click('[data-check="0"]');assert.match(document.body.textContent,/Correct/);await v.click('[data-stage="listening"]');assert.equal(document.querySelector('audio').getAttribute('src'),'/audio/grammar-classroom/43.mp3');assert.match(document.body.textContent,/Listen/);await v.click('[data-stage="closing"]');assert.equal(document.querySelector('[data-next]'),null);}finally{await v.close();}});
