import type {Pair, UKArea} from './data';
import {placesByCode, type UKPlace} from './places';

const p=(es:string,en:string):Pair=>({es,en});
const pairList=(rows:[string,string][]):Pair[]=>rows.map(([es,en])=>p(es,en));

// Eight concrete, present-tense questions per territory: places, location, likes and choices.
const questions:Record<string,[string,string][]>={
 TLC:[['¿Newcastle es una ciudad grande o pequeña?','Is Newcastle a big or small city?'],['¿Te gustan los puentes?','Do you like bridges?'],['¿Quieres visitar la catedral de Durham?','Do you want to visit Durham Cathedral?'],['¿Quieres caminar junto al río?','Do you want to walk by the river?'],['¿Prefieres la playa o la ciudad?','Do you prefer the beach or the city?'],['¿Qué hay en la costa: playas o montañas?','What is on the coast: beaches or mountains?'],['¿Te gusta caminar junto a un muro antiguo?','Do you like walking beside an old wall?'],['¿Qué llevas para un día frío?','What do you take on a cold day?']],
 TLD:[['¿Quieres visitar Manchester o Liverpool?','Do you want to visit Manchester or Liverpool?'],['¿Te gusta la música en vivo?','Do you like live music?'],['¿Liverpool tiene un puerto?','Does Liverpool have a harbour?'],['¿Prefieres la ciudad o el campo?','Do you prefer the city or the countryside?'],['¿Te gustan los lagos?','Do you like lakes?'],['¿Qué llevas para caminar?','What do you take for a walk?'],['¿Blackpool está junto al mar?','Is Blackpool by the sea?'],['¿Quieres viajar en tren o en autobús?','Do you want to travel by train or bus?']],
 TLE:[['¿York es una ciudad antigua?','Is York an old city?'],['¿Qué ves en York: un muro o una playa?','What do you see in York: a wall or a beach?'],['¿Te gustan los mercados de Leeds?','Do you like the markets in Leeds?'],['¿Qué quieres comprar en un mercado?','What do you want to buy at a market?'],['¿Quieres caminar por las colinas?','Do you want to walk in the hills?'],['¿Qué llevas en la mochila?','What do you carry in your backpack?'],['¿Whitby está junto al mar?','Is Whitby by the sea?'],['¿Prefieres visitar un puerto o una ciudad?','Do you prefer visiting a harbour or a city?']],
 TLF:[['¿Conoces a Robin Hood?','Do you know Robin Hood?'],['¿Quieres visitar Nottingham?','Do you want to visit Nottingham?'],['¿Te gustan los parques grandes?','Do you like big parks?'],['¿Prefieres caminar o tomar el tren?','Do you prefer walking or taking the train?'],['¿En Leicester hay tiendas?','Are there shops in Leicester?'],['¿Qué quieres comprar?','What do you want to buy?'],['¿Quieres ver la catedral de Lincoln?','Do you want to see Lincoln Cathedral?'],['¿La catedral es grande o pequeña?','Is the cathedral big or small?']],
 TLG:[['¿En Birmingham hay canales?','Are there canals in Birmingham?'],['¿Te gusta caminar junto al agua?','Do you like walking by the water?'],['¿Quieres visitar Coventry?','Do you want to visit Coventry?'],['¿Viajas en tren o en autobús?','Do you travel by train or by bus?'],['¿Te gusta el teatro?','Do you like theatre?'],['¿Quieres visitar Stratford?','Do you want to visit Stratford?'],['¿Quieres caminar por el centro?','Do you want to walk around the centre?'],['¿Prefieres un canal o un parque?','Do you prefer a canal or a park?']],
 TLH:[['¿Te gusta andar en bicicleta?','Do you like cycling?'],['¿Quieres visitar Cambridge?','Do you want to visit Cambridge?'],['¿Hay un río en Cambridge?','Is there a river in Cambridge?'],['¿Prefieres un pueblo o una ciudad?','Do you prefer a town or a city?'],['¿Quieres visitar Norwich?','Do you want to visit Norwich?'],['¿Te gustan los barcos?','Do you like boats?'],['¿Quieres pasear por los Broads?','Do you want to visit the Broads?'],['¿Qué llevas para un día en barco?','What do you take for a day on a boat?']],
 TLI:[['¿Quieres visitar Londres?','Do you want to visit London?'],['¿Te gusta viajar en metro?','Do you like taking the Underground?'],['¿Quieres caminar junto al Támesis?','Do you want to walk beside the Thames?'],['¿Prefieres un mercado o un museo?','Do you prefer a market or a museum?'],['¿Quieres comprar un regalo en Camden?','Do you want to buy a gift in Camden?'],['¿Qué quieres comprar?','What do you want to buy?'],['¿Quieres visitar Greenwich?','Do you want to visit Greenwich?'],['¿Te gusta caminar junto al río?','Do you like walking by the river?']],
 TLJ:[['¿Brighton está junto al mar?','Is Brighton by the sea?'],['¿Te gusta la playa?','Do you like the beach?'],['¿Quieres visitar la isla de Wight?','Do you want to visit the Isle of Wight?'],['¿Prefieres el ferry o el tren?','Do you prefer the ferry or the train?'],['¿En Oxford hay una universidad?','Is there a university in Oxford?'],['¿Te gustan las cafeterías?','Do you like cafés?'],['¿Quieres caminar por los South Downs?','Do you want to walk in the South Downs?'],['¿Qué llevas para caminar?','What do you take for a walk?']],
 TLK:[['¿Quieres visitar Bristol?','Do you want to visit Bristol?'],['¿Te gustan los barcos?','Do you like boats?'],['¿Bath es una ciudad antigua?','Is Bath an old city?'],['¿Prefieres Bath o Bristol?','Do you prefer Bath or Bristol?'],['¿Cornwall está junto al mar?','Is Cornwall by the sea?'],['¿Te gusta nadar?','Do you like swimming?'],['¿Quieres caminar por Dartmoor?','Do you want to walk in Dartmoor?'],['¿Qué llevas cuando llueve?','What do you take when it rains?']],
 TLL:[['¿Cardiff es una ciudad grande?','Is Cardiff a big city?'],['¿Quieres visitar Cardiff?','Do you want to visit Cardiff?'],['¿En Gales hay montañas?','Are there mountains in Wales?'],['¿Te gusta caminar en la montaña?','Do you like walking in the mountains?'],['¿Prefieres la costa o la montaña?','Do you prefer the coast or the mountains?'],['¿Dónde está el mar en el mapa?','Where is the sea on the map?'],['¿Ves palabras en galés?','Do you see words in Welsh?'],['¿Qué llevas para un día de playa?','What do you take for a beach day?']],
 TLM:[['¿Prefieres Edimburgo o Glasgow?','Do you prefer Edinburgh or Glasgow?'],['¿Te gustan los festivales?','Do you like festivals?'],['¿Hay un río en Glasgow?','Is there a river in Glasgow?'],['¿Quieres visitar un museo?','Do you want to visit a museum?'],['¿En Escocia hay montañas?','Are there mountains in Scotland?'],['¿Qué llevas cuando hace frío?','What do you take when it is cold?'],['¿Quieres visitar una isla?','Do you want to visit an island?'],['¿Te gusta viajar en ferry?','Do you like travelling by ferry?']],
 TLN:[['¿Quieres visitar Belfast?','Do you want to visit Belfast?'],['¿Dónde está el puerto?','Where is the harbour?'],['¿Derry tiene un puente?','Does Derry have a bridge?'],['¿Te gusta caminar por una ciudad antigua?','Do you like walking through an old city?'],['¿Quieres ver la Calzada del Gigante?','Do you want to see the Giant’s Causeway?'],['¿Prefieres la costa o la montaña?','Do you prefer the coast or the mountains?'],['¿Te gusta caminar por los Mournes?','Do you like walking in the Mournes?'],['¿Qué llevas para un día junto al mar?','What do you take for a day by the sea?']],
};

// Each stop retains its geographic identity and name, with a short A1 context and task.
type PlaceCopy=[string,string,string,string];
const stops:Record<string,PlaceCopy[]>={
 TLC:[['Newcastle está junto al río Tyne.','Newcastle is by the River Tyne.','¿Quieres caminar junto al río?','Do you want to walk by the river?'],['Durham tiene una catedral y un río.','Durham has a cathedral and a river.','¿Qué quieres visitar primero?','What do you want to visit first?'],['Aquí hay playas y castillos.','There are beaches and castles here.','¿Prefieres una playa o un castillo?','Do you prefer a beach or a castle?'],['Este muro antiguo está en el norte de Inglaterra.','This old wall is in northern England.','¿Quieres caminar junto al muro?','Do you want to walk beside the wall?']],
 TLD:[['Manchester tiene canales y música.','Manchester has canals and music.','¿Te gusta la música en vivo?','Do you like live music?'],['Liverpool está junto al río Mersey.','Liverpool is by the River Mersey.','¿Quieres ver el río o el puerto?','Do you want to see the river or the harbour?'],['Aquí hay lagos y montañas.','There are lakes and mountains here.','¿Prefieres un lago o una montaña?','Do you prefer a lake or a mountain?'],['Blackpool es una ciudad junto al mar.','Blackpool is a seaside town.','¿Te gusta caminar junto al mar?','Do you like walking by the sea?']],
 TLE:[['Leeds tiene tiendas y mercados.','Leeds has shops and markets.','¿Qué compras en un mercado?','What do you buy at a market?'],['Sheffield tiene parques y colinas.','Sheffield has parks and hills.','¿Te gusta caminar por el parque?','Do you like walking in the park?'],['York tiene calles y muros antiguos.','York has old streets and walls.','¿Quieres caminar por el centro?','Do you want to walk around the centre?'],['Whitby es un pueblo junto al mar.','Whitby is a seaside town.','¿Quieres comer junto al puerto?','Do you want to eat by the harbour?']],
 TLF:[['Nottingham es la ciudad de Robin Hood.','Nottingham is Robin Hood’s city.','¿Conoces a Robin Hood?','Do you know Robin Hood?'],['Leicester tiene mercados y tiendas.','Leicester has markets and shops.','¿Qué quieres comprar?','What do you want to buy?'],['Aquí hay colinas y senderos.','There are hills and walking paths here.','¿Quieres caminar por el parque?','Do you want to walk in the park?'],['Lincoln tiene una catedral grande.','Lincoln has a large cathedral.','¿Quieres entrar en la catedral?','Do you want to enter the cathedral?']],
 TLG:[['Birmingham tiene muchos canales.','Birmingham has many canals.','¿Quieres caminar junto al canal?','Do you want to walk along the canal?'],['Coventry tiene una catedral.','Coventry has a cathedral.','¿Dónde está la catedral?','Where is the cathedral?'],['Aquí hay ciudades y talleres.','There are cities and workshops here.','¿Prefieres visitar un taller o un mercado?','Do you prefer visiting a workshop or a market?'],['Stratford tiene teatros.','Stratford has theatres.','¿Te gusta ir al teatro?','Do you like going to the theatre?']],
 TLH:[['Cambridge tiene un río y bicicletas.','Cambridge has a river and bicycles.','¿Quieres andar en bicicleta?','Do you want to ride a bicycle?'],['Norwich tiene calles y mercados.','Norwich has streets and markets.','¿Quieres visitar un mercado?','Do you want to visit a market?'],['Aquí hay ríos y barcos.','There are rivers and boats here.','¿Te gusta viajar en barco?','Do you like travelling by boat?'],['Aquí hay pueblos y costa.','There are towns and a coastline here.','¿Prefieres un pueblo o la playa?','Do you prefer a town or the beach?']],
 TLI:[['Brixton tiene un mercado.','Brixton has a market.','¿Quieres visitar el mercado?','Do you want to visit the market?'],['Aquí hay un río y un observatorio.','There is a river and an observatory here.','¿Quieres ver el río?','Do you want to see the river?'],['Camden tiene un mercado.','Camden has a market.','¿Qué quieres comprar en el mercado?','What do you want to buy at the market?'],['Canary Wharf tiene edificios altos.','Canary Wharf has tall buildings.','¿Te gustan los edificios altos?','Do you like tall buildings?']],
 TLJ:[['Brighton está junto al mar.','Brighton is by the sea.','¿Quieres ir a la playa?','Do you want to go to the beach?'],['Oxford tiene una universidad.','Oxford has a university.','¿Te gustan las ciudades universitarias?','Do you like university cities?'],['Aquí hay una ciudad antigua y costa.','There is an old city and a coastline here.','¿Prefieres la ciudad o la playa?','Do you prefer the city or the beach?'],['Esta isla está cerca de la costa.','This island is near the coast.','¿Quieres viajar en ferry?','Do you want to travel by ferry?']],
 TLK:[['Bristol tiene un puerto y barcos.','Bristol has a harbour and boats.','¿Quieres visitar el puerto?','Do you want to visit the harbour?'],['Bath tiene edificios antiguos.','Bath has old buildings.','¿Te gusta caminar por Bath?','Do you like walking through Bath?'],['Aquí hay playas y un puerto.','There are beaches and a harbour here.','¿Prefieres nadar o caminar?','Do you prefer swimming or walking?'],['Dartmoor tiene colinas y ponis.','Dartmoor has hills and ponies.','¿Quieres ver los ponis?','Do you want to see the ponies?']],
 TLL:[['Cardiff es la capital de Gales.','Cardiff is the capital of Wales.','¿Quieres visitar Cardiff?','Do you want to visit Cardiff?'],['Eryri tiene montañas y pueblos.','Eryri has mountains and villages.','¿Te gusta caminar por la montaña?','Do you like walking in the mountains?'],['Aquí hay playas y acantilados.','There are beaches and cliffs here.','¿Prefieres una playa o un pueblo?','Do you prefer a beach or a village?'],['Aquí hay pueblos y trenes.','There are villages and trains here.','¿Quieres viajar en tren?','Do you want to travel by train?']],
 TLM:[['Edimburgo tiene un castillo y festivales.','Edinburgh has a castle and festivals.','¿Quieres visitar el castillo?','Do you want to visit the castle?'],['Glasgow está junto al río Clyde.','Glasgow is by the River Clyde.','¿Quieres visitar un museo?','Do you want to visit a museum?'],['Aquí hay montañas y bosques.','There are mountains and forests here.','¿Prefieres el bosque o la ciudad?','Do you prefer the forest or the city?'],['Estas islas tienen playas y ferris.','These islands have beaches and ferries.','¿Quieres visitar una isla?','Do you want to visit an island?']],
 TLN:[['Belfast tiene un puerto.','Belfast has a harbour.','¿Quieres caminar junto al puerto?','Do you want to walk by the harbour?'],['Derry tiene un puente y muros antiguos.','Derry has a bridge and old walls.','¿Quieres cruzar el puente?','Do you want to cross the bridge?'],['Aquí hay costa y piedras grandes.','There is a coastline and big rocks here.','¿Quieres ver la Calzada del Gigante?','Do you want to see the Giant’s Causeway?'],['Aquí hay montañas y agua.','There are mountains and water here.','¿Prefieres la montaña o el mar?','Do you prefer the mountains or the sea?']],
};

const notes:Record<string,[string,string,string,string]>={
 TLC:['Ríos, ciudades y playas.','Rivers, cities and beaches.','Newcastle y Durham están en el noreste de Inglaterra.','Newcastle and Durham are in north-eastern England.'],
 TLD:['Música, ciudades y lagos.','Music, cities and lakes.','Manchester y Liverpool están cerca del Lake District.','Manchester and Liverpool are near the Lake District.'],
 TLE:['Ciudades, mercados y colinas.','Cities, markets and hills.','York y Leeds están en el norte de Inglaterra.','York and Leeds are in northern England.'],
 TLF:['Ciudades, historias y parques.','Cities, stories and parks.','Nottingham y Leicester están cerca de grandes parques.','Nottingham and Leicester are near large parks.'],
 TLG:['Canales, ciudades y teatro.','Canals, cities and theatre.','Birmingham y Coventry están en el centro de Inglaterra.','Birmingham and Coventry are in central England.'],
 TLH:['Bicicletas, barcos y pueblos.','Bicycles, boats and towns.','Cambridge y Norwich están en el este de Inglaterra.','Cambridge and Norwich are in eastern England.'],
 TLI:['Un río, mercados y museos.','A river, markets and museums.','Londres está junto al río Támesis.','London is by the River Thames.'],
 TLJ:['Playas, ferris y ciudades.','Beaches, ferries and cities.','Brighton y Oxford están en el sur de Inglaterra.','Brighton and Oxford are in southern England.'],
 TLK:['Puertos, playas y colinas.','Harbours, beaches and hills.','Bristol, Bath y Cornwall están en el suroeste.','Bristol, Bath and Cornwall are in the south-west.'],
 TLL:['Una capital, montañas y playas.','A capital, mountains and beaches.','Cardiff es la capital de Gales.','Cardiff is the capital of Wales.'],
 TLM:['Ciudades, montañas e islas.','Cities, mountains and islands.','Edimburgo y Glasgow son ciudades de Escocia.','Edinburgh and Glasgow are cities in Scotland.'],
 TLN:['Ciudades, costa y montañas.','Cities, a coast and mountains.','Belfast y Derry están en Irlanda del Norte.','Belfast and Derry are in Northern Ireland.'],
};
const basicWords=pairList([['la ciudad','city'],['el río','river'],['el mar','sea'],['el mapa','map']]);
const localWords:Record<string,[string,string][]>={
 TLC:[['el puente','bridge'],['la catedral','cathedral'],['la playa','beach'],['el castillo','castle']],
 TLD:[['la música','music'],['el puerto','harbour'],['el lago','lake'],['el tren','train']],
 TLE:[['el mercado','market'],['la tienda','shop'],['el muro','wall'],['la colina','hill']],
 TLF:[['el parque','park'],['la historia','story'],['la tienda','shop'],['la catedral','cathedral']],
 TLG:[['el canal','canal'],['el teatro','theatre'],['el taller','workshop'],['el autobús','bus']],
 TLH:[['la bicicleta','bicycle'],['el barco','boat'],['el pueblo','town'],['el mercado','market']],
 TLI:[['el metro','Underground'],['el mercado','market'],['el regalo','gift'],['el edificio','building']],
 TLJ:[['la playa','beach'],['la isla','island'],['el ferry','ferry'],['la universidad','university']],
 TLK:[['el puerto','harbour'],['el barco','boat'],['la playa','beach'],['el poni','pony']],
 TLL:[['la capital','capital'],['la montaña','mountain'],['la playa','beach'],['el tren','train']],
 TLM:[['el castillo','castle'],['el festival','festival'],['la montaña','mountain'],['la isla','island']],
 TLN:[['el puerto','harbour'],['el puente','bridge'],['la costa','coast'],['la montaña','mountain']],
};
export const a1Support={
 starters:pairList([['Quiero visitar…','I want to visit…'],['Veo…','I see…'],['Prefiero…','I prefer…'],['Me gusta…','I like…']]),
 connectors:pairList([['y…','and…'],['también…','also…'],['porque…','because…']]),
 depthMoves:pairList([['Decí el nombre de un lugar.','Name one place.'],['Elegí una de dos opciones.','Choose one of two options.'],['Decí qué ves en el mapa.','Say what you see on the map.'],['Preguntá: ¿dónde está?','Ask: where is it?']]),
 stances:{elegiria:p('Me gusta este lugar.','I like this place.'),depende:p('Quiero ir.','I want to go.'),otra:p('Prefiero otro lugar.','I prefer another place.')},
};
export function a1QuestionsFor(area:UKArea):Pair[]{
 const rows=questions[area.code];if(!rows)throw new Error(`Missing A1 questions for ${area.code}`);return pairList(rows);
}
export function a1PlacesFor(area:UKArea):UKPlace[]{
 const originals=placesByCode[area.code],rows=stops[area.code];
 if(!originals||!rows||rows.length!==originals.length)throw new Error(`Missing A1 stops for ${area.code}`);
 return originals.map((place,index)=>{const [es,en,qes,qen]=rows[index];return {...place,context:p(es,en),prompt:p(qes,qen)}});
}
export function a1AreaFor(area:UKArea):UKArea{
 const note=notes[area.code];if(!note)throw new Error(`Missing A1 context for ${area.code}`);
 return {...area,hook:p(note[0],note[1]),fact:p(note[2],note[3]),mission:p('Elegí un lugar y decí qué te gusta.','Choose a place and say what you like.'),words:[...basicWords,...pairList(localWords[area.code])]};
}
