import type {Pair} from "./data";

export type UKPlace={name:string;type:string;context:Pair;prompt:Pair};
const p=(es:string,en:string):Pair=>({es,en});
const place=(name:string,type:string,es:string,en:string,qes:string,qen:string):UKPlace=>({name,type,context:p(es,en),prompt:p(qes,qen)});

export const placesByCode:Record<string,UKPlace[]>={
  TLC:[
    place("Newcastle upon Tyne","ciudad ribereña","Newcastle creció junto al Tyne y frente a Gateshead. Sus puentes, universidades y antiguos espacios industriales muestran una ciudad del noreste que sigue cambiando.","Newcastle grew beside the Tyne and opposite Gateshead. Its bridges, universities and former industrial spaces reveal a North East city that keeps changing.","¿Qué uso cotidiano le darías a una antigua zona industrial junto al río?","What everyday use would you give a former industrial waterfront?"),
    place("Durham","ciudad histórica","Durham se organiza alrededor del río Wear, su catedral, su castillo y una gran población universitaria. Es compacta, empinada y mucho más pequeña que Newcastle.","Durham is organised around the River Wear, its cathedral, castle and large student population. It is compact, hilly and much smaller than Newcastle.","¿Preferís estudiar en una ciudad pequeña donde todo está cerca o en una gran ciudad con más opciones?","Would you rather study in a small city where everything is close or a major city with more options?"),
    place("Costa de Northumberland","costa y pueblos","Entre largas playas aparecen pueblos, castillos y Holy Island, a la que se llega por una calzada que la marea cubre dos veces al día.","Long beaches are interrupted by villages, castles and Holy Island, reached by a causeway covered by the tide twice a day.","¿Te gustaría vivir en un lugar donde la marea decide a qué hora podés entrar o salir?","Would you like to live where the tide decides when you can enter or leave?"),
    place("Muro de Adriano","paisaje histórico","La antigua frontera romana cruza el norte de Inglaterra. En el noreste, su recorrido conecta arqueología, granjas, pueblos y senderos modernos.","The former Roman frontier crosses northern England. In the North East, its route connects archaeology, farms, villages and modern trails.","¿Una ruta histórica se entiende mejor caminando, con un museo o con una reconstrucción digital?","Is a historic route best understood by walking, through a museum or with a digital reconstruction?")
  ],
  TLD:[
    place("Manchester","ciudad posindustrial","Canales, almacenes y fábricas textiles conviven con universidades, música, medios y nuevos barrios. La ciudad se expandió mucho más allá de su centro.","Canals, warehouses and textile mills sit alongside universities, music, media and new neighbourhoods. The city has spread far beyond its centre.","¿Qué edificio industrial conservarías aunque ya no tenga su función original?","Which industrial building would you preserve even after it lost its original function?"),
    place("Liverpool","ciudad portuaria","El río Mersey y el puerto conectaron Liverpool con el mundo. Esa historia explica parte de su arquitectura, música, migración y fuerte identidad local.","The River Mersey and port connected Liverpool to the world. That history helps explain its architecture, music, migration and strong local identity.","¿Qué elemento muestra mejor que una ciudad siempre estuvo conectada con otros países?","Which feature best shows that a city has always been connected to other countries?"),
    place("Lake District","parque nacional","Los lagos y montañas de Cumbria atraen caminantes, pero las rutas estrechas, el estacionamiento y la vivienda para residentes generan presión.","Cumbria's lakes and mountains attract walkers, but narrow roads, parking and resident housing face pressure.","¿Qué cambiarías para que una visita al Lake District no empiece y termine con un auto?","What would you change so a Lake District visit does not begin and end with a car?"),
    place("Blackpool","balneario","Blackpool creció con el ferrocarril y las vacaciones obreras junto al mar. Su torre, sus luces y su paseo marítimo muestran una cultura popular muy británica.","Blackpool grew with railways and working-class seaside holidays. Its tower, illuminations and seafront reflect a distinctive strand of British popular culture.","¿Qué parte de un balneario antiguo conservarías para que no se vuelva genérico?","Which part of an old seaside resort would you preserve so it does not become generic?")
  ],
  TLE:[
    place("Leeds","centro regional","Leeds combina finanzas, comercio, universidades y antiguos edificios textiles. Es un centro importante para West Yorkshire y una base para viajar por la región.","Leeds combines finance, retail, universities and former textile buildings. It is a major West Yorkshire centre and a base for travel around the region.","¿Qué servicio hace que una ciudad funcione como capital informal de una región?","Which service makes a city work as an informal regional capital?"),
    place("Sheffield","ciudad y colinas","Sheffield se desarrolló con el acero, pero gran parte de su territorio es verde y llega hasta el Peak District. Industria y naturaleza aparecen muy cerca.","Sheffield developed through steel, yet much of its area is green and reaches into the Peak District. Industry and nature sit close together.","¿Te sorprendería más una fábrica en un paisaje verde o un gran parque dentro de una ciudad industrial?","Would a factory in a green landscape or a major park in an industrial city surprise you more?"),
    place("York","ciudad ferroviaria e histórica","York conserva murallas y calles medievales, pero también fue un gran centro ferroviario. Su tamaño permite recorrer capas muy distintas a pie.","York keeps its walls and medieval streets, but was also a major railway centre. Its size allows very different layers to be explored on foot.","¿Qué historia mostrarías primero: la ciudad medieval o la ciudad del ferrocarril?","Which story would you show first: the medieval city or the railway city?"),
    place("Whitby y North York Moors","costa y páramo","Whitby mira al mar del Norte bajo las ruinas de su abadía; detrás aparecen pueblos, páramos de brezo y un ferrocarril histórico.","Whitby faces the North Sea beneath its abbey ruins; behind it lie villages, heather moors and a heritage railway.","¿Qué transporte elegirías para llegar a la costa: tren histórico, bus o caminata larga?","Which transport would you choose to reach the coast: heritage train, bus or a long walk?")
  ],
  TLF:[
    place("Nottingham","ciudad de leyenda e industria","Además de Robin Hood, Nottingham tiene una historia de encaje, bicicletas, fábricas y cuevas bajo la ciudad. Su Lace Market cambió de función muchas veces.","Beyond Robin Hood, Nottingham has histories of lace, bicycles, factories and caves below the city. Its Lace Market has changed function many times.","¿Qué historia menos famosa usarías para presentar Nottingham?","Which less famous story would you use to introduce Nottingham?"),
    place("Leicester","ciudad multicultural","Leicester combina un centro industrial histórico con comunidades formadas por migraciones de distintas épocas. La Golden Mile es conocida por sus negocios y vida cultural del sur de Asia.","Leicester combines a historic industrial centre with communities shaped by migration at different times. The Golden Mile is known for South Asian businesses and cultural life.","¿Cómo puede una calle comercial contar la historia de varias generaciones?","How can a shopping street tell the story of several generations?"),
    place("Peak District","parque nacional","El primer parque nacional de Inglaterra ocupa sobre todo Derbyshire y queda cerca de Manchester, Sheffield, Derby y Nottingham. Esa cercanía permite excursiones de un día.","England's first national park lies mostly in Derbyshire and close to Manchester, Sheffield, Derby and Nottingham. That proximity makes day trips possible.","¿La naturaleza cercana a grandes ciudades necesita más transporte público o más límites de visitantes?","Does nature close to major cities need more public transport or stronger visitor limits?"),
    place("Lincoln","ciudad y llanura","Lincoln se levanta sobre una colina alrededor de su catedral y castillo, mientras gran parte del condado se extiende en tierras agrícolas mucho más planas.","Lincoln rises on a hill around its cathedral and castle, while much of the county stretches across much flatter farmland.","¿Qué cambia en una ciudad cuando un edificio domina el horizonte durante siglos?","What changes in a city when one building dominates the skyline for centuries?")
  ],
  TLG:[
    place("Birmingham","metrópolis de canales","Birmingham creció a través de talleres, fábricas, mercados y canales. Hoy sus barrios muestran muchas comunidades y una economía mucho más diversa.","Birmingham grew through workshops, factories, markets and canals. Today its neighbourhoods show many communities and a far more diverse economy.","¿Recorrerías Birmingham por sus canales, sus mercados o su arquitectura industrial?","Would you explore Birmingham through its canals, markets or industrial architecture?"),
    place("Coventry","ciudad reconstruida","La catedral medieval fue destruida durante la Segunda Guerra Mundial y sus ruinas quedaron junto a una nueva catedral. La ciudad convirtió esa herida en un símbolo visible.","The medieval cathedral was destroyed during the Second World War and its ruins remain beside a new cathedral. The city turned that wound into a visible symbol.","¿Es mejor dejar una ruina visible o reconstruir exactamente lo que existía antes?","Is it better to leave a ruin visible or rebuild exactly what existed before?"),
    place("Black Country","paisaje industrial","Dudley, Wolverhampton, Sandwell y Walsall forman un territorio de minas, hierro, vidrio y talleres. Sus canales y chimeneas explican el nombre y la historia local.","Dudley, Wolverhampton, Sandwell and Walsall form a territory of mines, iron, glass and workshops. Its canals and chimneys explain the name and local history.","¿Qué puede enseñar un museo industrial que no muestra un museo de arte?","What can an industrial museum teach that an art museum cannot?"),
    place("Stratford-upon-Avon","ciudad teatral","La ciudad de Shakespeare vive junto al río Avon y recibe visitantes por teatros, casas históricas y excursiones. También necesita funcionar para sus residentes.","Shakespeare's town sits beside the River Avon and attracts visitors through theatres, historic houses and day trips. It also needs to work for residents.","¿Cómo evitarías que una ciudad famosa por una persona cuente siempre la misma historia?","How would you stop a town famous for one person from always telling the same story?")
  ],
  TLH:[
    place("Cambridge","ciudad universitaria","Los colleges, bicicletas y espacios de investigación conviven con barrios donde el costo de la vivienda es un problema real. La universidad no es toda la ciudad.","Colleges, bicycles and research spaces coexist with neighbourhoods where housing costs are a real problem. The university is not the whole city.","¿Qué parte de Cambridge mostrarías para ir más allá de la universidad?","Which part of Cambridge would you show to go beyond the university?"),
    place("Norwich","ciudad regional","Norwich tiene una catedral, un mercado histórico y una escena cultural propia. Su distancia de Londres ayuda a que funcione como centro de Norfolk.","Norwich has a cathedral, historic market and its own cultural scene. Its distance from London helps it act as Norfolk's regional centre.","¿Es una ventaja vivir en una ciudad que no depende tanto de una capital cercana?","Is it an advantage to live in a city that depends less on a nearby capital?"),
    place("Norfolk Broads","humedales navegables","Ríos y lagos poco profundos forman un paisaje de barcos, juncos y pueblos. El agua sirve para recreación, biodiversidad y drenaje.","Rivers and shallow lakes form a landscape of boats, reeds and villages. Water supports recreation, biodiversity and drainage.","¿Qué reglas pondrías para compartir un humedal entre barcos, fauna y residentes?","Which rules would you set to share a wetland among boats, wildlife and residents?"),
    place("Costa de Suffolk y Essex","costa cambiante","Puertos, marismas, playas de piedras y pueblos miran al mar del Norte. En algunos sectores, la erosión obliga a decidir qué se puede proteger.","Ports, salt marshes, shingle beaches and villages face the North Sea. In some areas, erosion forces decisions about what can be protected.","Si no es posible salvar toda una costa, ¿cómo se decide qué proteger primero?","If an entire coast cannot be saved, how should people decide what to protect first?")
  ],
  TLI:[
    place("Brixton","barrio del sur","Brixton tiene mercados, música, conexiones caribeñas y una historia de cambio social. Su popularidad también trajo alquileres más altos.","Brixton has markets, music, Caribbean connections and a history of social change. Its popularity has also brought higher rents.","¿Cómo puede un mercado seguir sirviendo a residentes cuando el barrio se vuelve más caro?","How can a market continue serving residents when the neighbourhood becomes more expensive?"),
    place("Greenwich","barrio junto al Támesis","Greenwich combina parque, observatorio, historia marítima y una ribera conectada por barco, tren y DLR. Está en Londres, pero se siente lejos del West End.","Greenwich combines parkland, observatory, maritime history and a riverside linked by boat, rail and DLR. It is in London but feels far from the West End.","¿Qué medio usarías para llegar a Greenwich y qué cambiaría en la experiencia?","How would you travel to Greenwich, and how would that change the experience?"),
    place("Camden","mercado y canales","Camden mezcla mercado, música, turismo y vida residencial alrededor del Regent's Canal. Los fines de semana, la cantidad de visitantes cambia completamente el barrio.","Camden mixes market, music, tourism and residential life around Regent's Canal. At weekends, visitor numbers completely change the neighbourhood.","¿Qué horario elegirías para conocer un barrio popular sin verlo en su momento más lleno?","What time would you choose to see a popular neighbourhood away from its busiest moment?"),
    place("Canary Wharf","antiguos docks","Torres de oficinas ocupan parte de los antiguos Docklands. El agua, los muelles restaurados y nuevas viviendas recuerdan que el este de Londres tuvo otra economía.","Office towers occupy part of the former Docklands. Water, restored docks and new housing recall a different economy in East London.","¿Un distrito de oficinas puede convertirse en un barrio completo? ¿Qué le falta?","Can an office district become a complete neighbourhood? What does it lack?")
  ],
  TLJ:[
    place("Brighton y Hove","ciudad costera","La ciudad creció como destino de mar y hoy combina playa, vida nocturna, comunidad LGBTQ+, universidades y conexiones rápidas con Londres.","The city grew as a seaside destination and now combines beach, nightlife, an LGBTQ+ community, universities and fast links to London.","¿Qué necesita una ciudad costera para tener vida propia también en invierno?","What does a seaside city need to have a life of its own in winter?"),
    place("Oxford","ciudad universitaria","La universidad se reparte en colleges por toda la ciudad. Visitantes, estudiantes, bicicletas, buses y residentes comparten calles históricas con poco espacio.","The university is spread among colleges across the city. Visitors, students, bicycles, buses and residents share historic streets with little space.","¿A quién darías prioridad en el centro de Oxford: peatones, bicicletas, buses o autos?","Who would you prioritise in central Oxford: pedestrians, bicycles, buses or cars?"),
    place("Canterbury y costa de Kent","ciudad y puerta marítima","Canterbury se desarrolló como centro religioso y universitario; más al este, Dover mira hacia Francia desde sus acantilados y su puerto de ferris.","Canterbury developed as a religious and university centre; further east, Dover faces France from its cliffs and ferry port.","¿Qué cambia en una región cuando otro país se ve o se siente muy cerca?","What changes in a region when another country can be seen or felt very close?"),
    place("Isla de Wight","isla del canal","La isla está separada de Hampshire por el Solent. Los ferris conectan sus pueblos, playas y acantilados con Southampton, Portsmouth y Lymington.","The island is separated from Hampshire by the Solent. Ferries link its towns, beaches and cliffs with Southampton, Portsmouth and Lymington.","¿Qué servicio no podría faltar para que una isla cercana al continente funcione bien todo el año?","Which service is essential for an island close to the mainland to function well all year?")
  ],
  TLK:[
    place("Bristol","ciudad portuaria y creativa","El puerto interior cambió de zona comercial a espacio cultural y residencial. La ciudad también es conocida por música, arte urbano y una fuerte vida independiente.","The floating harbour shifted from commercial zone to cultural and residential space. The city is also known for music, street art and a strong independent scene.","¿Qué hace que una ciudad parezca creativa sin convertir la creatividad en publicidad?","What makes a city feel creative without turning creativity into advertising?"),
    place("Bath","ciudad termal","Baños romanos y arquitectura georgiana atraen visitantes a una ciudad compacta. Su belleza también puede aumentar el costo de vivir en el centro.","Roman baths and Georgian architecture attract visitors to a compact city. Its beauty can also increase the cost of living in the centre.","¿Cómo se equilibra la protección de una ciudad hermosa con las necesidades de vivienda?","How can protecting a beautiful city be balanced with housing needs?"),
    place("Cornwall y St Ives","costa atlántica","St Ives reúne playas, puerto y galerías; Cornwall mantiene una identidad propia, una lengua recuperada y comunidades donde el turismo cambia mucho cada temporada.","St Ives brings together beaches, harbour and galleries; Cornwall maintains its own identity, a revived language and communities where tourism changes each season.","¿Qué medida ayudaría más a una comunidad costera: vivienda, empleo anual o mejor transporte?","Which measure would help a coastal community most: housing, year-round work or better transport?"),
    place("Dartmoor","páramo de Devon","Granito, turberas, ponis y cambios rápidos de clima forman un paisaje abierto con pueblos en sus bordes. No es un parque urbano ni un paisaje completamente vacío.","Granite, peat bogs, ponies and fast-changing weather form an open landscape with villages around its edges. It is neither an urban park nor an empty landscape.","¿Qué llevarías para pasar un día seguro en un paisaje abierto con clima cambiante?","What would you take for a safe day in an open landscape with changeable weather?")
  ],
  TLL:[
    place("Cardiff · Caerdydd","capital","La capital creció alrededor del carbón y los docks; hoy Cardiff Bay, el centro cívico y los barrios multiculturales cuentan etapas distintas de la ciudad.","The capital grew around coal and docks; today Cardiff Bay, the civic centre and multicultural neighbourhoods tell different stages of the city's story.","¿Qué zona mostrarías para explicar que Cardiff es más que sus edificios oficiales?","Which area would you show to explain that Cardiff is more than its official buildings?"),
    place("Eryri · Snowdonia","parque nacional","Eryri reúne montañas, costa, pueblos de habla galesa y Yr Wyddfa, la cumbre más alta de Gales. La presión de autos y visitantes es un tema local.","Eryri brings together mountains, coast, Welsh-speaking communities and Yr Wyddfa, the highest summit in Wales. Pressure from cars and visitors is a local issue.","¿Reservarías espacios de estacionamiento, mejorarías buses o limitarías visitas en días muy llenos?","Would you book parking spaces, improve buses or limit visits on very busy days?"),
    place("Costa de Pembrokeshire","parque costero","Acantilados, playas, islas y pueblos forman el único parque nacional costero del Reino Unido. El sendero permite recorrerlo lentamente.","Cliffs, beaches, islands and villages form the UK's only coastal national park. Its trail allows people to explore slowly.","¿Qué se comprende mejor caminando varios días que visitando en auto durante unas horas?","What can be understood better by walking for several days than visiting by car for a few hours?"),
    place("Valles del sur de Gales","paisaje posindustrial","Comunidades de Rhondda, Cynon, Taff y otros valles crecieron con el carbón. Ferrocarriles, antiguas minas y nuevas rutas verdes muestran otra etapa.","Communities in the Rhondda, Cynon, Taff and other valleys grew with coal. Railways, former mines and new green routes reveal another stage.","¿Qué futuro puede unir memoria industrial, naturaleza y trabajo local?","What future could unite industrial memory, nature and local employment?")
  ],
  TLM:[
    place("Edimburgo · Edinburgh","capital","La Old Town y la New Town ocupan colinas distintas. El parlamento, las universidades y los festivales hacen que la ciudad cambie de ritmo durante el año.","The Old Town and New Town occupy different hills. Parliament, universities and festivals make the city's rhythm change through the year.","¿Preferirías conocer Edimburgo durante un festival lleno de gente o en un mes tranquilo?","Would you rather discover Edinburgh during a crowded festival or in a quiet month?"),
    place("Glasgow y el Clyde","ciudad ribereña","Los astilleros del Clyde marcaron Glasgow. Museos, viviendas, un campus y espacios de eventos ocupan hoy partes de la ribera.","The Clyde shipyards shaped Glasgow. Museums, housing, a campus and event spaces now occupy parts of the riverfront.","¿Qué mezcla de usos hace que una ribera renovada tenga vida todos los días?","Which mix of uses makes a renewed waterfront lively every day?"),
    place("Cairngorms y Highlands","montañas y comunidades","Los Highlands no son una sola postal: incluyen montañas, bosques, granjas, pueblos, rutas largas y servicios alejados entre sí. Cairngorms es el parque nacional más grande del Reino Unido.","The Highlands are not a single postcard: they include mountains, forests, farms, towns, long roads and distant services. Cairngorms is the UK's largest national park.","¿Qué servicio público es más difícil de mantener cuando las personas viven muy separadas?","Which public service is hardest to maintain when people live far apart?"),
    place("Skye y las Hébridas","islas del oeste","Puentes y ferris conectan islas con historias, paisajes y comunidades distintas. En lugares populares como Skye, el turismo puede concentrarse en pocas rutas.","Bridges and ferries connect islands with different histories, landscapes and communities. In popular places such as Skye, tourism can concentrate along a few routes.","¿Cómo invitarías a explorar una isla sin mandar a todos al mismo lugar?","How would you invite people to explore an island without sending everyone to the same place?")
  ],
  TLN:[
    place("Belfast","ciudad portuaria","Belfast creció con lino, ingeniería y construcción naval. Titanic Quarter, el centro y los barrios de murales muestran memorias y transformaciones diferentes.","Belfast grew through linen, engineering and shipbuilding. Titanic Quarter, the centre and mural neighbourhoods reveal different memories and transformations.","¿Qué historia de Belfast contarías junto al puerto además de la del Titanic?","Which Belfast story would you tell beside the harbour beyond the Titanic?"),
    place("Derry~Londonderry","ciudad amurallada","Las murallas rodean el centro histórico junto al río Foyle. El Peace Bridge conecta ambas orillas y el nombre de la ciudad refleja identidades distintas.","Walls surround the historic centre beside the River Foyle. The Peace Bridge links both banks and the city's name reflects different identities.","¿Un puente nuevo puede cambiar de verdad la relación entre dos partes de una ciudad?","Can a new bridge truly change the relationship between two parts of a city?"),
    place("Causeway Coast y Rathlin","costa e isla","La ruta costera conecta Belfast con Derry~Londonderry y pasa por acantilados, pueblos, castillos y la Calzada del Gigante. Rathlin se alcanza en ferry desde Ballycastle.","The coastal route links Belfast with Derry~Londonderry through cliffs, villages, castles and the Giant's Causeway. Rathlin is reached by ferry from Ballycastle.","¿Qué parada elegirías para pasar más tiempo en lugar de recorrer toda la costa rápido?","Which stop would you choose for a longer stay instead of rushing along the whole coast?"),
    place("Mourne Mountains y Strangford","montañas y agua","En County Down, los Mournes descienden hacia el mar; cerca, Strangford Lough crea un gran paisaje de agua, islas y mareas.","In County Down, the Mournes sweep down towards the sea; nearby, Strangford Lough creates a broad landscape of water, islands and tides.","¿Preferirías una caminata con vista al mar o un día lento junto al lough?","Would you rather take a mountain walk with sea views or spend a slow day beside the lough?")
  ]
};
