import type {Pair} from "./data";

export type IrishPlace={name:string;type:string;context:Pair;prompt:Pair};
const p=(name:string,type:string,es:string,en:string,promptEs:string,promptEn:string):IrishPlace=>({name,type,context:{es,en},prompt:{es:promptEs,en:promptEn}});

export const placesByCode:Record<string,IrishPlace[]>={
  CW:[
    p("Carlow Town","ciudad","El río Barrow y el castillo recuerdan que la ciudad creció alrededor de un cruce estratégico.","The River Barrow and the castle show that the town grew around a strategic crossing.","¿Cómo aprovecharías el río para mejorar la vida cotidiana del centro?","How would you use the river to improve daily life downtown?"),
    p("Altamont Gardens","jardín","Un jardín histórico combina diseño formal, bosque y vistas hacia las Blackstairs.","A historic garden combines formal design, woodland and views towards the Blackstairs.","¿Preferís un jardín muy cuidado o uno que parezca más salvaje?","Do you prefer a highly designed garden or one that feels wilder?"),
    p("Borris","pueblo","El pueblo conserva arquitectura de granito y una relación fuerte con el valle del Barrow.","The village retains granite architecture and a strong relationship with the Barrow valley.","¿Qué edificio antiguo convertirías en un nuevo espacio comunitario?","Which old building would you turn into a new community space?"),
    p("Blackstairs Mountains","montaña","La cadena marca el límite con Wexford y ofrece senderos menos concurridos que otros destinos irlandeses.","The range marks the Wexford border and offers trails quieter than other Irish destinations.","¿La falta de multitudes compensa tener menos servicios?","Does the lack of crowds make up for fewer services?")
  ],
  CN:[
    p("Cavan Burren Park","geoparque","Bosque, tumbas megalíticas y formaciones glaciares aparecen juntos en un paisaje muy compacto.","Woodland, megalithic tombs and glacial formations appear together in a compact landscape.","¿Qué capa explorarías primero: arqueología, geología o bosque?","Which layer would you explore first: archaeology, geology or woodland?"),
    p("Lough Oughter","lago","Islas, humedales y las ruinas de Clough Oughter Castle forman un paisaje dominado por el agua.","Islands, wetlands and the ruins of Clough Oughter Castle form a water-dominated landscape.","¿Llegar a un castillo en bote mejora la experiencia o la vuelve demasiado turística?","Does reaching a castle by boat improve the experience or make it too touristy?"),
    p("Cavan Town","ciudad","Es el centro de servicios del condado y una base para explorar su red de lagos.","It is the county's service centre and a base for exploring its network of lakes.","¿Qué necesitaría una ciudad pequeña para retener a estudiantes y jóvenes profesionales?","What would a small town need to retain students and young professionals?"),
    p("Shannon Pot","nacimiento","Una poza kárstica en las montañas de Cuilcagh es reconocida como el nacimiento del Shannon.","A karst pool in the Cuilcagh Mountains is recognised as the source of the Shannon.","¿Por qué visitar el comienzo de un río puede cambiar cómo entendemos todo su recorrido?","Why can visiting a river's beginning change how we understand its whole course?")
  ],
  CE:[
    p("Cliffs of Moher","acantilado","Una pared atlántica de ocho kilómetros atrae multitudes y exige decisiones constantes de seguridad y conservación.","An eight-kilometre Atlantic wall attracts crowds and requires constant safety and conservation decisions.","¿Debería cobrarse más en horas pico y menos cuando hay poca gente?","Should peak hours cost more and quiet hours less?"),
    p("The Burren","paisaje kárstico","La roca caliza expuesta parece austera, pero sostiene una combinación extraordinaria de plantas.","Exposed limestone looks austere but supports an extraordinary mixture of plants.","¿Un paisaje necesita ser verde para parecerte vivo?","Does a landscape need to be green to feel alive to you?"),
    p("Doolin","pueblo musical","El pequeño pueblo es conocido por sesiones tradicionales y como puerta hacia costa e islas.","The small village is known for traditional sessions and as a gateway to the coast and islands.","¿Escucharías música en un pub lleno o buscarías una sesión más pequeña?","Would you hear music in a packed pub or look for a smaller session?"),
    p("Loop Head","península","El cabo ofrece faro, aves marinas y una costa dramática con mucha menos presión turística.","The headland offers a lighthouse, seabirds and dramatic coast with far less tourism pressure.","¿Promocionarías este lugar como alternativa a Moher o lo protegerías del mismo éxito?","Would you promote this as an alternative to Moher or protect it from the same success?")
  ],
  CO:[
    p("English Market","mercado","El mercado cubierto del centro conecta alimentos locales, vida cotidiana e historia urbana.","The city-centre covered market connects local food, daily life and urban history.","¿Qué tres productos usarías para presentar Cork a un visitante?","Which three products would you use to introduce Cork to a visitor?"),
    p("Cobh","ciudad portuaria","Las fachadas sobre el puerto contrastan con historias de emigración, navegación y despedidas.","Harbour-front facades contrast with stories of emigration, sailing and farewells.","¿Cómo contarías una historia migratoria sin volverla solamente triste?","How would you tell a migration story without making it only sad?"),
    p("Kinsale","puerto gastronómico","Calles compactas, puerto y restaurantes convirtieron a Kinsale en un destino muy buscado.","Compact streets, a harbour and restaurants made Kinsale a highly sought-after destination.","¿La fama gastronómica beneficia a todos los residentes?","Does food fame benefit all residents?"),
    p("Mizen Head","cabo atlántico","Puentes y senderos conducen a una antigua estación de señales frente al Atlántico abierto.","Bridges and paths lead to a former signal station facing the open Atlantic.","¿Viajarías hasta un punto remoto si el clima pudiera ocultar la vista?","Would you travel to a remote point if weather might hide the view?")
  ],
  DL:[
    p("Slieve League","acantilado","Los acantilados marinos figuran entre los más altos de Europa y se recorren en un paisaje expuesto.","The sea cliffs rank among Europe's highest and are explored in exposed terrain.","¿Preferís un mirador accesible o un sendero que exija esfuerzo?","Do you prefer an accessible viewpoint or a trail that demands effort?"),
    p("Glenveagh National Park","parque nacional","Montañas, lagos y un castillo histórico ocupan un gran valle protegido.","Mountains, lakes and a historic castle fill a broad protected valley.","¿Qué limitarías primero para proteger el parque: autos, alojamiento o eventos?","What would you limit first to protect the park: cars, accommodation or events?"),
    p("Fanad Head","faro","El faro mira hacia Lough Swilly desde una costa remota de gran fuerza visual.","The lighthouse faces Lough Swilly from a remote, visually powerful coast.","¿Dormir cerca de un faro te parecería romántico o inquietante?","Would sleeping near a lighthouse feel romantic or unsettling?"),
    p("Gaoth Dobhair","gaeltacht","En esta comunidad de Donegal el irlandés, la música y la vida local no son elementos decorativos.","In this Donegal community Irish, music and local life are not decorative elements.","¿Cómo aprenderías algunas palabras de irlandés sin convertir la lengua en souvenir?","How would you learn some Irish without turning the language into a souvenir?")
  ],
  DU:[
    p("Trinity College","universidad","El campus histórico permanece activo en pleno centro y recibe enormes flujos de visitantes.","The historic campus remains active downtown and receives enormous visitor flows.","¿Cómo separarías mejor la vida universitaria del circuito turístico?","How would you better separate university life from the tourist circuit?"),
    p("Howth","península urbana","Un viaje corto en tren conecta el centro con puerto, acantilados y barrios residenciales.","A short train ride connects downtown with harbour, cliffs and residential areas.","¿Pagarías más alquiler por poder caminar junto al mar todos los días?","Would you pay higher rent to walk by the sea every day?"),
    p("Phoenix Park","parque urbano","Uno de los parques urbanos cerrados más grandes de Europa mezcla ciervos, deporte, instituciones y tránsito.","One of Europe's largest enclosed urban parks mixes deer, sport, institutions and traffic.","¿Qué uso debería tener prioridad cuando tantas funciones compiten?","Which use should take priority when so many functions compete?"),
    p("Docklands","distrito urbano","Antiguos muelles se transformaron en una zona de oficinas, vivienda y arquitectura contemporánea.","Former docks became a district of offices, housing and contemporary architecture.","¿Cómo evitarías que la renovación cree un barrio sin memoria local?","How would you stop regeneration from creating a district without local memory?")
  ],
  GY:[
    p("Latin Quarter","centro cultural","Calles peatonales, pubs y artistas concentran la energía social de Galway City.","Pedestrian streets, pubs and performers concentrate Galway City's social energy.","¿Cuándo un centro animado pasa de vibrante a saturado?","When does a lively centre go from vibrant to overcrowded?"),
    p("Connemara National Park","parque nacional","Turberas, montañas y ponis muestran una geografía atlántica de grandes espacios abiertos.","Bogs, mountains and ponies reveal an Atlantic geography of broad open spaces.","¿Caminarías bajo lluvia si fuera parte esencial de la experiencia?","Would you walk in the rain if it were an essential part of the experience?"),
    p("Aran Islands","islas","Las islas mantienen comunidades, lengua irlandesa y una arquitectura adaptada a piedra y viento.","The islands sustain communities, Irish language and architecture adapted to stone and wind.","¿Qué servicio es imprescindible para que una isla siga siendo una comunidad real?","Which service is essential for an island to remain a real community?"),
    p("Clifden","pueblo atlántico","El centro de Connemara funciona como base para rutas costeras y comunidades dispersas.","Connemara's centre works as a base for coastal routes and dispersed communities.","¿Preferís usar un solo pueblo como base o cambiar de alojamiento cada noche?","Do you prefer one base town or changing accommodation every night?")
  ],
  KE:[
    p("Irish National Stud","patrimonio ecuestre","Caballos de cría, jardines y museo explican por qué la cultura ecuestre pesa tanto en Kildare.","Stud horses, gardens and a museum explain why equestrian culture matters so much in Kildare.","¿Cómo harías interesante el lugar para alguien que no sabe nada de caballos?","How would you make the place interesting to someone who knows nothing about horses?"),
    p("The Curragh","llanura","La gran planicie abierta sostiene carreras, entrenamiento militar y un paisaje poco común.","The broad open plain supports racing, military training and an unusual landscape.","¿Qué uso debería tener prioridad en una llanura compartida?","Which use should take priority on a shared plain?"),
    p("Naas","ciudad conectada","La ciudad creció con rapidez por su cercanía y conexiones con Dublín.","The town grew rapidly because of its proximity and links to Dublin.","¿Qué servicio local evitaría que Naas fuera solamente una ciudad dormitorio?","Which local service would stop Naas being merely a commuter town?"),
    p("Grand Canal","canal","El canal ofrece una franja lenta de agua, senderos y pueblos dentro de un condado muy conectado.","The canal offers a slow strip of water, paths and towns inside a highly connected county.","¿Usarías el canal para llegar al trabajo si la ruta fuera segura?","Would you use the canal to commute if the route were safe?")
  ],
  KK:[
    p("Kilkenny Castle","castillo urbano","El castillo abre hacia un gran parque público en el corazón de la ciudad.","The castle opens onto a large public park in the heart of the city.","¿Te atrae más entrar al castillo o usar libremente su parque?","Are you more drawn to entering the castle or freely using its park?"),
    p("Medieval Mile","ruta histórica","La ruta conecta edificios, callejones e historias dentro de un centro todavía habitado.","The route connects buildings, lanes and stories within a still-inhabited centre.","¿Qué actividad evitaría que una ruta histórica se sienta como una lista?","What activity would stop a historic route feeling like a checklist?"),
    p("Thomastown","pueblo creativo","Talleres y escuelas de artesanía vinculan técnicas tradicionales con diseño contemporáneo.","Workshops and craft schools connect traditional techniques with contemporary design.","¿Qué oficio tradicional te gustaría aprender durante un fin de semana?","Which traditional craft would you like to learn over a weekend?"),
    p("Castlecomer Discovery Park","paisaje recuperado","Una antigua zona minera se reutilizó para bosque, educación y actividades al aire libre.","A former mining area was reused for woodland, education and outdoor activities.","¿Debería conservarse una parte industrial visible para no borrar la memoria?","Should some industrial remains stay visible so memory is not erased?")
  ],
  KY:[
    p("Killarney National Park","parque nacional","Lagos, bosques y montañas reciben una enorme cantidad de visitantes junto a la ciudad.","Lakes, woods and mountains receive huge visitor numbers beside the town.","¿Qué transporte debería reemplazar autos en los puntos más concurridos?","What transport should replace cars at the busiest sites?"),
    p("Dingle Peninsula","península","La ruta combina costa, montaña, arqueología y comunidades de lengua irlandesa.","The route combines coast, mountain, archaeology and Irish-speaking communities.","¿Recorrer rápido muchos miradores o quedarse en un solo pueblo?","See many viewpoints quickly or stay in one village?"),
    p("Skellig Michael","isla patrimonial","Un monasterio ocupa una isla rocosa de acceso limitado y condiciones marítimas difíciles.","A monastery occupies a rocky island with limited access and difficult sea conditions.","¿Aceptarías que el viaje se cancele para proteger seguridad y patrimonio?","Would you accept a cancelled trip to protect safety and heritage?"),
    p("Tralee","ciudad","La capital del condado ofrece cultura y servicios lejos del circuito más obvio de Killarney.","The county town offers culture and services outside Killarney's more obvious circuit.","¿Cómo convencerías a visitantes de pasar una noche en Tralee?","How would you convince visitors to spend a night in Tralee?")
  ],
  LS:[
    p("Rock of Dunamase","ruina panorámica","Las ruinas dominan una colina con vistas amplias sobre la llanura de Laois.","The ruins dominate a hill with broad views across the Laois plain.","¿Preferís una ruina libre y abierta o un sitio con centro de visitantes?","Do you prefer an open ruin or a site with a visitor centre?"),
    p("Slieve Bloom Mountains","sierra","Senderos y bosques ofrecen una montaña de escala íntima y poco concurrida.","Trails and woods offer intimate, uncrowded mountain country.","¿La promocionarías como alternativa secreta o evitarías esa etiqueta?","Would you promote it as a secret alternative or avoid that label?"),
    p("Portlaoise","ciudad central","Su posición y conexiones convierten la ciudad en cruce nacional y centro de servicios.","Its position and links make the town a national crossroads and service centre.","¿Qué espacio público podría transformar una ciudad conocida por sus conexiones?","What public space could transform a town known for its connections?"),
    p("Emo Court","finca histórica","Casa, jardines y parque cuentan una historia de diseño, propiedad y cambio social.","House, gardens and park tell a story of design, ownership and social change.","¿Qué perspectiva falta normalmente en las visitas a grandes mansiones?","Which perspective is usually missing from visits to grand houses?")
  ],
  LM:[
    p("Carrick-on-Shannon","ciudad fluvial","La navegación y los fines de semana sociales animan esta pequeña ciudad sobre el Shannon.","Boating and social weekends animate this small Shannon town.","¿Cómo equilibrarías fiesta de fin de semana y tranquilidad residente?","How would you balance weekend partying and residents' peace?"),
    p("Glencar Waterfall","cascada","La cascada cae en un valle boscoso asociado con la poesía de Yeats.","The waterfall drops into a wooded valley associated with Yeats's poetry.","¿Leer un poema antes de verla mejora o limita tu experiencia?","Does reading a poem before seeing it improve or limit your experience?"),
    p("Lough Allen","lago","El lago al pie de Sliabh an Iarainn conecta agua, viento y comunidades pequeñas.","The lake beneath Sliabh an Iarainn connects water, wind and small communities.","¿Qué actividad permitirías para generar empleo sin romper el silencio?","What activity would you allow to create jobs without breaking the quiet?"),
    p("Dromahair","pueblo","El pueblo junto al río Bonet guarda capas monásticas y rurales fuera de grandes circuitos.","The village by the River Bonet holds monastic and rural layers beyond major circuits.","¿Qué hace que valga la pena detenerse en un pueblo diminuto?","What makes a tiny village worth stopping in?")
  ],
  LI:[
    p("King John's Castle","castillo fluvial","La fortaleza ocupa King's Island y explica el valor estratégico del Shannon.","The fortress occupies King's Island and explains the Shannon's strategic value.","¿Qué historia contarías desde la mirada de quienes vivían fuera del castillo?","Which story would you tell from the viewpoint of people outside the castle?"),
    p("Milk Market","mercado","Productores, comida y eventos convierten el mercado cubierto en un punto de encuentro.","Producers, food and events turn the covered market into a meeting point.","¿Qué producto local usarías para iniciar una conversación?","Which local product would you use to start a conversation?"),
    p("Adare","pueblo patrimonial","Casas con techo de paja y grandes propiedades atraen turismo en un espacio muy pequeño.","Thatched cottages and large estates attract tourism into a very small space.","¿Cómo evitarías que un pueblo bonito se convierta en escenario?","How would you stop a pretty village becoming a stage set?"),
    p("Lough Gur","paisaje arqueológico","El lago reúne círculos de piedra, restos prehistóricos y granjas actuales.","The lake brings together stone circles, prehistoric remains and present-day farms.","¿Qué actividad te ayudaría a imaginar miles de años de ocupación?","What activity would help you imagine thousands of years of settlement?")
  ],
  LD:[
    p("Corlea Trackway","arqueología","Un tramo de camino de madera construido hace más de dos mil años sobrevivió dentro de la turbera.","A timber roadway built more than two thousand years ago survived inside the bog.","¿Qué pregunta le harías a quien decidió construirlo?","What would you ask the person who decided to build it?"),
    p("Lough Ree","lago","El gran lago del Shannon toca varios condados y combina navegación, islas y hábitats.","This large Shannon lake touches several counties and combines boating, islands and habitats.","¿Quién debería decidir su futuro si varios condados lo comparten?","Who should decide its future if several counties share it?"),
    p("Ardagh","pueblo planificado","El pueblo fue rediseñado en el siglo XIX con una composición cuidada y escala pequeña.","The village was redesigned in the nineteenth century with a careful composition and small scale.","¿Planificar belleza desde arriba puede crear comunidad real?","Can top-down planning of beauty create real community?"),
    p("Longford Town","ciudad","La ciudad funciona como centro comercial y de servicios de un condado rural.","The town serves as the commercial and service centre of a rural county.","¿Qué negocio nuevo tendría sentido aquí y no en Dublín?","What new business would make sense here but not in Dublin?")
  ],
  LH:[
    p("Carlingford Lough","fiordo fronterizo","Montaña y agua enmarcan un fiordo que también marca parte de la frontera.","Mountain and water frame a lough that also marks part of the border.","¿El paisaje hace que una frontera se sienta más fuerte o menos importante?","Does landscape make a border feel stronger or less important?"),
    p("Dundalk","ciudad fronteriza","La ciudad industrial y universitaria vive entre Dublín y Belfast.","The industrial and university town lives between Dublin and Belfast.","¿Estar entre dos capitales es ventaja o riesgo de quedar a la sombra?","Is being between two capitals an advantage or a risk of being overshadowed?"),
    p("Drogheda","ciudad del Boyne","El río, murallas y cercanía a sitios prehistóricos crean capas muy distintas.","The river, walls and proximity to prehistoric sites create very different layers.","¿Qué capa usarías para cambiar la imagen externa de Drogheda?","Which layer would you use to change Drogheda's outside image?"),
    p("Monasterboice","sitio monástico","Torres redondas y cruces altas aparecen en un antiguo asentamiento abierto.","Round towers and high crosses stand in an open early monastic settlement.","¿Preferís ver las cruces al aire libre o protegidas en un museo?","Would you rather see the crosses outdoors or protected in a museum?")
  ],
  MO:[
    p("Croagh Patrick","montaña sagrada","La montaña sobre Clew Bay combina peregrinación religiosa y desafío físico.","The mountain above Clew Bay combines religious pilgrimage and physical challenge.","¿Deberían separarse rutas para peregrinos y deportistas?","Should there be separate routes for pilgrims and athletes?"),
    p("Achill Island","isla conectada","Un puente une la isla al continente, pero el clima y la distancia conservan una fuerte identidad insular.","A bridge joins the island to the mainland, but weather and distance preserve a strong island identity.","¿Una isla conectada por puente sigue sintiéndose isla?","Does an island connected by bridge still feel like an island?"),
    p("Westport","ciudad planificada","Calles diseñadas, río y cercanía a montaña sostienen una economía turística muy visible.","Designed streets, a river and mountain access support a highly visible tourism economy.","¿Qué detalle urbano hace que una ciudad turística siga siendo cómoda para residentes?","Which urban detail keeps a tourist town comfortable for residents?"),
    p("Céide Fields","paisaje neolítico","Muros de campos de hace miles de años permanecieron ocultos bajo una extensa turbera.","Field walls thousands of years old remained hidden beneath a vast bog.","¿Cómo mostrarías algo que en gran parte sigue debajo del suelo?","How would you show something that largely remains underground?")
  ],
  MH:[
    p("Brú na Bóinne","paisaje UNESCO","Newgrange, Knowth y Dowth forman un paisaje ritual neolítico alrededor del Boyne.","Newgrange, Knowth and Dowth form a Neolithic ritual landscape around the Boyne.","¿El misterio aumenta cuando no sabemos exactamente para qué se construyó?","Does mystery grow when we do not know exactly why something was built?"),
    p("Hill of Tara","colina ceremonial","La antigua sede simbólica del poder se lee más en el terreno que en edificios conservados.","The ancient symbolic seat of power is read more in the land than in surviving buildings.","¿Necesitás ver edificios para sentir la importancia histórica de un lugar?","Do you need buildings to feel a place's historical importance?"),
    p("Trim Castle","castillo normando","La gran fortaleza junto al Boyne conserva un volumen capaz de dominar toda la ciudad.","The great fortress beside the Boyne retains a mass that dominates the whole town.","¿Qué uso contemporáneo sería compatible con una fortaleza así?","Which contemporary use would suit a fortress like this?"),
    p("Boyne Valley","valle histórico","El río conecta arqueología, batallas, agricultura y ciudades modernas.","The river connects archaeology, battles, farming and modern towns.","¿Organizarías la región por períodos históricos o siguiendo el río?","Would you organise the region by historical periods or by following the river?")
  ],
  MN:[
    p("Monaghan Town","ciudad","Plazas, mercado y edificios cívicos estructuran un centro compacto de zona fronteriza.","Squares, market and civic buildings structure a compact border-region centre.","¿Qué evento podría hacer que la plaza central se use todo el año?","What event could keep the central square active year-round?"),
    p("Castle Leslie","finca","Una gran propiedad histórica funciona hoy como hotel y espacio ecuestre.","A large historic estate now operates as a hotel and equestrian venue.","¿Abrirías más la finca a usos gratuitos de la comunidad?","Would you open more of the estate to free community use?"),
    p("Carrickmacross","pueblo artesanal","La tradición local de encaje conecta trabajo doméstico, diseño y memoria femenina.","The local lace tradition connects domestic work, design and women's history.","¿Cómo harías que una artesanía antigua atraiga a gente joven?","How would you make an old craft appeal to young people?"),
    p("Rossmore Forest Park","bosque urbano","Senderos y lagos quedan inmediatamente junto a Monaghan Town.","Trails and lakes sit immediately beside Monaghan Town.","¿Qué actividad cotidiana trasladarías de la ciudad al bosque?","Which everyday activity would you move from town into the forest?")
  ],
  OY:[
    p("Clonmacnoise","sitio monástico","Las ruinas ocupan un cruce histórico de río y rutas terrestres en el centro de la isla.","The ruins occupy a historic river and land-route crossing at the island's centre.","¿Qué pesa más aquí: religión, educación o geografía?","What matters more here: religion, learning or geography?"),
    p("Birr Castle","ciencia e historia","La finca reúne jardines y una historia científica ligada a un enorme telescopio del siglo XIX.","The estate combines gardens with scientific history linked to a huge nineteenth-century telescope.","¿Por qué la ciencia cambia nuestra idea de una casa histórica?","Why does science change our idea of a historic house?"),
    p("Lough Boora","turbera recuperada","Antiguos terrenos de extracción se transformaron con lagos, esculturas y rutas.","Former extraction land was transformed with lakes, sculpture and routes.","¿Dejarías una zona sin restaurar para recordar su pasado industrial?","Would you leave one area unrestored to remember its industrial past?"),
    p("Tullamore","ciudad","Canal, destilería y servicios regionales sostienen una ciudad central en transformación.","Canal, distillery and regional services support a changing central town.","¿Qué identidad podría complementar al whiskey sin competir con él?","Which identity could complement whiskey without competing with it?")
  ],
  RN:[
    p("Rathcroghan","paisaje real antiguo","Montículos, campos y relatos forman un complejo ceremonial más amplio que un solo monumento.","Mounds, fields and stories form a ceremonial complex broader than one monument.","¿Qué relato usarías para que un campo parezca un antiguo centro de poder?","Which story would make a field feel like an ancient centre of power?"),
    p("Lough Key Forest Park","parque forestal","Bosque, lago e islas mezclan conservación con actividades familiares.","Woodland, lake and islands mix conservation with family activities.","¿Cuánta aventura es compatible con un bosque tranquilo?","How much adventure is compatible with a quiet forest?"),
    p("Boyle Abbey","abadía","La ruina cisterciense conserva formas arquitectónicas claras dentro de una pequeña ciudad.","The Cistercian ruin preserves clear architectural forms within a small town.","¿Reconstruirías una parte para mostrar cómo funcionaba?","Would you reconstruct one part to show how it worked?"),
    p("Roscommon Castle","castillo","Las ruinas abiertas se integran con un parque público y la vida cotidiana local.","The open ruins blend into a public park and local daily life.","¿Preferís un castillo gratuito dentro de un parque o una visita muy producida?","Do you prefer a free castle in a park or a highly produced visit?")
  ],
  SO:[
    p("Benbulben","montaña","La silueta tabular domina el norte del condado y aparece en relatos, arte y rutas.","The table-shaped profile dominates northern Sligo and appears in stories, art and routes.","¿Una montaña puede convertirse en logotipo sin perder significado?","Can a mountain become a logo without losing meaning?"),
    p("Strandhill","pueblo de surf","Olas, dunas y cafés crearon una comunidad costera muy vinculada al surf.","Waves, dunes and cafés created a coastal community closely tied to surfing.","¿Qué limitarías primero si el surf atrae demasiada gente?","What would you limit first if surfing attracts too many people?"),
    p("Carrowmore","cementerio megalítico","Decenas de monumentos convierten un paisaje ordinario en un archivo prehistórico.","Dozens of monuments turn an ordinary landscape into a prehistoric archive.","¿Un mapa ayuda a comprender mejor muchos monumentos dispersos?","Does a map help people understand many dispersed monuments?"),
    p("Lough Gill","lago literario","Bosques, islas y asociaciones con Yeats hacen que naturaleza y literatura se superpongan.","Woods, islands and Yeats associations make nature and literature overlap.","¿Harías primero un paseo o leerías primero el poema?","Would you walk first or read the poem first?")
  ],
  TY:[
    p("Rock of Cashel","complejo medieval","Iglesias y torre se levantan sobre una roca que domina la llanura.","Churches and tower rise on a rock dominating the plain.","¿La ubicación impresiona más que los edificios?","Does the location impress more than the buildings?"),
    p("Cahir Castle","fortaleza fluvial","La fortaleza conserva su relación defensiva con una isla rocosa del río Suir.","The fortress retains its defensive relationship with a rocky island in the River Suir.","¿Qué decisión defensiva explicarías primero a un alumno?","Which defensive decision would you explain first to a learner?"),
    p("Glen of Aherlow","valle","Un valle agrícola queda entre las Galtee Mountains y Slievenamuck.","A farming valley lies between the Galtee Mountains and Slievenamuck.","¿Preferís caminar por el valle o mirar el valle desde arriba?","Would you rather walk in the valley or look down on it from above?"),
    p("Lough Derg","lago compartido","El gran lago del Shannon conecta Tipperary con Clare y Galway.","The large Shannon lake connects Tipperary with Clare and Galway.","¿Crearías una sola marca común para los tres condados?","Would you create one shared identity for all three counties?")
  ],
  WD:[
    p("Viking Triangle","barrio histórico","Museos y restos urbanos concentran más de mil años de historia en pocas calles.","Museums and urban remains concentrate more than a thousand years of history in a few streets.","¿Qué elemento vikingo convertirías en una actividad conversacional?","Which Viking element would you turn into a speaking activity?"),
    p("Copper Coast","geoparque costero","Acantilados, calas y huellas mineras cuentan la formación de una costa atlántica.","Cliffs, coves and mining traces tell the formation of an Atlantic coast.","¿Qué debe explicarse mejor: geología o historia minera?","What needs better explanation: geology or mining history?"),
    p("Waterford Greenway","vía verde","Una antigua línea ferroviaria conecta ciudad, pueblos, viaductos y costa en 46 kilómetros.","A former railway links city, villages, viaducts and coast across 46 kilometres.","¿Harías todo el recorrido o elegirías un tramo corto con más paradas?","Would you do the full route or a shorter section with more stops?"),
    p("Ardmore","pueblo costero","Playa, torre redonda y arte contemporáneo conviven en un pequeño asentamiento marítimo.","Beach, round tower and contemporary art coexist in a small seaside settlement.","¿Qué capa usarías para presentar Ardmore: playa, historia o arte?","Which layer would you use to present Ardmore: beach, history or art?")
  ],
  WH:[
    p("Athlone Castle","cruce del Shannon","La fortaleza explica por qué controlar el puente del Shannon significaba controlar movimientos.","The fortress explains why controlling the Shannon bridge meant controlling movement.","¿Qué cruce moderno tiene una importancia parecida en tu región?","Which modern crossing has similar importance in your region?"),
    p("Mullingar","ciudad","Mercado, música y servicios sostienen una identidad distinta de la ciudad fluvial de Athlone.","Market, music and services support an identity distinct from river-town Athlone.","¿Qué símbolo nuevo elegirías para Mullingar?","Which new symbol would you choose for Mullingar?"),
    p("Belvedere House","finca histórica","La casa y su gran jardín esconden una historia familiar marcada por poder y control.","The house and its great garden hide a family story shaped by power and control.","¿Las visitas a mansiones deberían hablar más de conflictos privados?","Should visits to mansions speak more about private conflicts?"),
    p("Hill of Uisneach","centro simbólico","La colina ocupa un lugar central en mitología, reunión y geografía antigua.","The hill occupies a central place in mythology, gathering and ancient geography.","¿Un centro simbólico necesita coincidir con el centro exacto del mapa?","Must a symbolic centre match the exact centre of a map?")
  ],
  WX:[
    p("Hook Lighthouse","faro histórico","El faro medieval sigue operativo en una península expuesta al encuentro de aguas.","The medieval lighthouse remains operational on a peninsula exposed to meeting waters.","¿Te atrae más que sea antiguo o que todavía funcione?","Are you more drawn to its age or to the fact it still works?"),
    p("Wexford Town","ciudad portuaria","Calles estrechas, muelles y festivales mantienen una identidad marítima y cultural.","Narrow streets, quays and festivals preserve a maritime and cultural identity.","¿Qué festival inventarías para conectar la ciudad con su puerto?","What festival would you invent to connect the town with its harbour?"),
    p("Curracloe Beach","playa y dunas","Una playa extensa y sistema de dunas combinan recreación, cine y hábitat frágil.","A long beach and dune system combine recreation, cinema and fragile habitat.","¿Cerrarías partes de las dunas durante ciertas temporadas?","Would you close parts of the dunes in certain seasons?"),
    p("Irish National Heritage Park","parque histórico","Reconstrucciones recorren miles de años de asentamiento en un paisaje boscoso.","Reconstructions cover thousands of years of settlement in a wooded landscape.","¿Reconstruir ayuda a aprender o crea una falsa sensación de certeza?","Does reconstruction aid learning or create false certainty?")
  ],
  WW:[
    p("Glendalough","valle monástico","Lagos glaciares y ruinas monásticas atraen grandes flujos a un valle estrecho.","Glacial lakes and monastic ruins draw heavy visitor flows into a narrow valley.","¿Reservarías horario para entrar en los días más concurridos?","Would you require time slots on the busiest days?"),
    p("Wicklow Mountains","parque nacional","Un gran paisaje de montaña y turbera comienza casi junto al área metropolitana.","A large mountain and bog landscape begins almost beside the metropolitan area.","¿La naturaleza cercana a una capital necesita reglas especiales?","Does nature near a capital need special rules?"),
    p("Powerscourt","jardín y finca","Jardines formales y una gran cascada construyen una imagen clásica del jardín de Irlanda.","Formal gardens and a great waterfall build a classic image of the Garden of Ireland.","¿Qué parte parece más natural y cuál más controlada?","Which part feels more natural and which more controlled?"),
    p("Bray Head","costa urbana","Un sendero elevado conecta paisaje marino con una ciudad suburbana y ferroviaria.","A high trail links seascape with a suburban railway town.","¿Caminar cerca de casa cuenta como aventura?","Does walking close to home count as adventure?")
  ]
};
