// Noche Abierta · B1 · Conversación · Modo Play — the lesson content.
//
// Everything a learner reads lives here, as plain data. The game engine
// (activities.mjs) knows nothing about this night: it turns each activity
// into beats according to its `type`. A new Modo Play world only needs a file
// like this one and a map.
//
// Tonight: Vale turns thirty. There is a "previa" at her flat and a party on a
// rooftop, but nobody has a fixed plan. The cast is the same everywhere: Vale,
// her flatmate Leo, and the friends Nico, Lu (Lucía), Martín and Sergio.
//
// Register: voseo rioplatense, everyday adult language, nothing that blocks a
// learner who did not grow up in Buenos Aires.

export const ARRIVAL = {
  kicker: "SÁBADO · 20:40",
  title: "Noche abierta",
  premise: "Bajás del colectivo en un barrio que no conocés bien. Hoy Vale cumple treinta: hay una previa en su casa y una fiesta en una terraza, pero nadie tiene un plan fijo. Caminá, entrá donde quieras y resolvé lo que vaya pasando.",
  warmup: [
    "¿Cómo festejás tu cumpleaños? ¿Organizás vos o dejás que te sorprendan?",
    "¿Preferís planear la noche o improvisar? Contá un ejemplo reciente.",
    "¿Cuál fue la última salida que terminó muy distinta de lo que pensabas?",
  ],
  teacher: "Dos o tres minutos de charla libre. No corrijas todavía: anotá qué tiempos verbales usa para contar.",
};

// How each activity type is presented. `mechanic` is the short name of the
// game shown on the card; `more` labels the way to another situation there.
export const MECHANICS = {
  mensajes: { mechanic: "Mensajes", more: "Otros mensajes" },
  observar: { mechanic: "Mirar y deducir", more: "Otra situación" },
  decisiones: { mechanic: "Decisiones", more: "Otra situación en la mesa" },
  conversacion: { mechanic: "Charla", more: "Hablar con otra persona" },
  social: { mechanic: "Resolver un problema", more: "Otro problema" },
  condiciones: { mechanic: "Si pasa esto…", more: "Otro problema en la calle" },
  museo: { mechanic: "Contar el pasado", more: "Ver otra pieza" },
  comparar: { mechanic: "Comparar y decidir", more: "Otro viaje" },
  describir: { mechanic: "Explicar sin la palabra", more: "Buscar otra cosa" },
  acuerdo: { mechanic: "Ponerse de acuerdo", more: "Otra discusión" },
};

// Each place is a different small game. `hub` places hold several people or
// objects you walk up to; the others play their situations one after another.
export const LOCATIONS = [
  {
    id: "cafe",
    name: "Café Martina",
    short: "Café",
    type: "mensajes",
    focus: "Entender mensajes ambiguos y responder",
    help: {
      starters: ["Me parece que quiere decir…", "No queda claro si…", "Capaz que…", "Le contestaría que…"],
      chunks: ["llegar tarde", "avisar con tiempo", "cambiar de plan", "quedar en un lugar", "mientras tanto"],
      vocab: ["el audio", "el visto", "la ubicación", "el grupo"],
    },
    activities: [
      {
        id: "cafe-alla",
        title: "¿Dónde es «allá»?",
        situation: "Quedaste con Nico en el café hace veinte minutos. Ya pediste un cortado y miraste la puerta veinte veces.",
        thread: [
          { from: "Nico", time: "hace 8 min", text: "Perdón perdón, se me complicó todo" },
          { from: "Nico", time: "hace 7 min", text: "Llego en un rato o nos vemos directamente allá, como quieras" },
        ],
        ask: "¿Qué entendiste? Hay por lo menos dos cosas que el mensaje no dice. ¿Cuáles son?",
        next: { from: "Nico", time: "ahora", text: "¿Ya estás viniendo? Los chicos ya subieron" },
        ask2: "«Subieron»: Nico no está pensando en el café. ¿Dónde está? ¿Qué pasó con el plan?",
        reply: "Grabale un audio a Nico de treinta segundos: dónde estás, cómo te sentís y qué hacés ahora.",
        role: "Sos Nico: apurado, con frases cortas. Solo al final confesás que «allá» era la terraza de la fiesta.",
        teacher: ["¿Te molesta más que lleguen tarde o que no avisen?", "¿Cuánto esperás a alguien antes de irte?"],
      },
      {
        id: "cafe-equivocado",
        title: "Un mensaje que era para otro",
        situation: "Estás en la barra y te llega un mensaje de Lu. Lo leés dos veces: claramente no era para vos.",
        thread: [
          { from: "Lu", time: "hace 3 min", text: "Martín, ¿le compraste algo a Vale? Yo ya no sé qué regalarle y ella cree que nadie se acordó" },
        ],
        ask: "¿Qué hacés con este mensaje: le avisás a Lu, se lo reenviás a Martín o hacés como si nada? ¿Por qué?",
        next: { from: "Vale", time: "ahora", text: "¿Vos sabés si los chicos están organizando algo? Están todos rarísimos" },
        ask2: "Ahora Vale te pregunta a vos. ¿Qué le contestás sin mentirle y sin arruinar la sorpresa?",
        reply: "Escribile a Lu para contarle que el mensaje te llegó a vos y qué le dijiste a Vale.",
        role: "Primero sos Vale: sospechás y hacés preguntas cada vez más concretas. Después sos Lu: te da vergüenza el error.",
        teacher: ["¿Sos bueno guardando secretos?", "¿Te mandaste alguna vez un mensaje al chat equivocado?"],
      },
      {
        id: "cafe-grupo",
        title: "El grupo no se pone de acuerdo",
        situation: "Estás por pagar y el celular no para. En el grupo «Sábado» cada uno quiere otra cosa.",
        thread: [
          { from: "Lu", time: "hace 4 min", text: "¿Y si en vez de la terraza vamos al bar de la esquina? Hay música en vivo" },
          { from: "Martín", time: "hace 3 min", text: "Yo ya pagué la entrada de la terraza, eh" },
          { from: "Sergio", time: "hace 3 min", text: "Me da igual, pero que sea cerca. Mañana trabajo temprano" },
        ],
        ask: "Resumí qué quiere cada uno y qué problema tiene cada propuesta.",
        next: { from: "Vale", time: "ahora", text: "Chicos… la terraza es mi cumple. ¿En serio?" },
        ask2: "Con el mensaje de Vale cambia todo. ¿Qué escribís en el grupo para calmar las cosas?",
        reply: "Mandá un mensaje al grupo con un plan concreto: hora, lugar y por qué le conviene a todos.",
        role: "Hacé de cualquiera del grupo y defendé tu idea hasta que te den una buena razón.",
        teacher: ["¿Quién suele organizar en tu grupo de amigos?", "¿Te molesta cuando cambian un plan a último momento?"],
      },
    ],
  },
  {
    id: "departamento",
    name: "Departamento de Vale",
    short: "Depto. de Vale",
    type: "observar",
    focus: "Observar detalles y hacer hipótesis",
    help: {
      starters: ["Por lo que veo, …", "Seguramente…", "Me imagino que…", "Debe de ser…", "Capaz que…"],
      chunks: ["estar invitado", "no hacer ruido", "sacarse los zapatos", "llegar temprano", "la previa"],
      vocab: ["la heladera", "el sillón", "el portero eléctrico", "los vecinos", "el repasador"],
    },
    activities: [
      {
        id: "depto-un-minuto",
        title: "Un minuto solo en la casa",
        situation: "Vale te abre, te dice «ponete cómodo» y baja corriendo a buscar hielo. Tenés un minuto para mirar. Tocá cada lugar.",
        items: [
          { id: "entrada", label: "La entrada", detail: "Ocho pares de zapatos alineados junto a la puerta. Nadie adentro tiene zapatos puestos." },
          { id: "heladera", label: "La heladera", detail: "Un papel con letra grande: «Vecinos: silencio desde las 00:00. Gracias»." },
          { id: "calendario", label: "El calendario", detail: "En el día de hoy alguien escribió: «Leo: examen 8 h»." },
          { id: "mesa", label: "La mesa", detail: "Algo tapado con un repasador. Asoman dos velas: un 3 y un 0." },
          { id: "sillon", label: "El sillón", detail: "Una montaña de abrigos y un libro de viajes sin envolver. Todavía tiene el precio." },
        ],
        ask: "Con lo que viste, ¿qué está pasando en esta casa? ¿Quién vive acá y qué va a pasar esta noche?",
        reveal: "Vale vuelve con el hielo y te dice en voz baja: «Leo, mi compañero de departamento, no sabe que hoy vienen veinte personas. Y mañana rinde un examen».",
        ask2: "Leo llega en diez minutos. Organizá con Vale qué le dicen y qué cambian de la previa para que todos estén bien.",
        role: "Sos Vale: nerviosa, querés que todo salga perfecto y das órdenes rápidas.",
        teacher: ["¿Qué se hace en tu cultura al llegar a una casa ajena?", "¿Qué reglas debería tener una casa compartida?"],
      },
      {
        id: "depto-timbre",
        title: "Alguien toca el timbre",
        situation: "Vale está en la ducha. Suena el portero eléctrico: «Hola, soy Tomi, vengo con Sergio». Vale nunca habló de ningún Tomi. Mirá antes de abrir.",
        items: [
          { id: "portero", label: "El portero", detail: "Se escuchan dos voces y risas. Parecen de buen humor." },
          { id: "celular", label: "El celular de Vale", detail: "Un mensaje de Sergio, sin responder: «¿Puedo llevar a un amigo?»." },
          { id: "lista", label: "La lista", detail: "En la heladera hay una lista de invitados. Sergio sí está. Tomi, no." },
          { id: "ventana", label: "La ventana", detail: "Abajo, en la vereda, uno de los dos tiene una torta en la mano." },
        ],
        ask: "¿Quién puede ser Tomi y por qué viene con una torta? Armá una hipótesis con las pistas.",
        reveal: "Desde la ducha, Vale grita: «¡¿Tomi?! ¡Es el vecino de abajo, el que siempre se queja del ruido!».",
        ask2: "Ya les abriste y están subiendo. ¿Qué les decís cuando toquen la puerta?",
        role: "Sos Tomi: simpático, un poco atrevido y convencido de que estás invitado. La torta es para hacer las paces.",
        teacher: ["¿Está bien llevar a alguien sin avisar? ¿Depende de qué?", "¿Cómo te llevás con tus vecinos?"],
      },
    ],
  },
  {
    id: "restaurante",
    name: "Restaurante El Toldo",
    short: "Restaurante",
    type: "decisiones",
    focus: "Decidir y explicar las consecuencias",
    help: {
      starters: ["Propongo que…", "A mí me parece más justo…", "Estoy de acuerdo, pero…", "¿Y si…?", "Lo que no me cierra es…"],
      chunks: ["dividir la cuenta", "cada uno lo suyo", "pedir para compartir", "dejar propina", "salir caro"],
      vocab: ["la cuenta", "el mozo", "la entrada", "el plato principal", "la propina"],
    },
    activities: [
      {
        id: "resto-cuenta",
        title: "Llegó la cuenta",
        situation: "Son cinco en la mesa. Lu pidió solamente una gaseosa porque ya había cenado. Martín propone dividir todo en partes iguales: «Así es más fácil».",
        prompt: "¿Cómo pagan?",
        options: [
          {
            id: "iguales",
            label: "Dividen todo en partes iguales.",
            result: "Todos aceptan menos Lu: paga lo mismo que los demás por una gaseosa. No dice nada, pero deja de hablar.",
            ask: "Lu está molesta y no lo dice. ¿Le hablás o preferís no decir nada? ¿Qué le decís?",
          },
          {
            id: "cada-uno",
            label: "Cada uno paga lo suyo.",
            result: "El mozo trae la cuenta separada, pero las dos entradas y el vino eran para compartir. Nadie se acuerda de quién comió qué.",
            ask: "Repartí las cosas compartidas entre los cuatro que cenaron. Explicá tu criterio en voz alta.",
          },
          {
            id: "otra",
            label: "Proponés otra solución.",
            result: "Proponés que los que cenaron dividan la comida y que cada uno pague su bebida. Lu sonríe. Martín dice que «es mucha matemática para un sábado».",
            ask: "Martín no quiere hacer cuentas. Convencelo en treinta segundos.",
          },
        ],
        close: "En general, ¿qué solución te parece más justa? ¿Cambia algo si es una cena de cumpleaños?",
        role: "Sos Martín: querés dividir en partes iguales porque «siempre se hizo así». Cedés solo ante un buen argumento.",
        teacher: ["¿Cómo se divide la cuenta en tu país?", "¿Qué hacés si alguien pidió mucho más que vos?"],
      },
      {
        id: "resto-plato",
        title: "El plato equivocado",
        situation: "Lu es vegetariana y pidió ravioles de verdura. Llegan los ravioles… con salsa de carne. El mozo ya se fue y la cocina está llena de pedidos.",
        prompt: "¿Qué hacen?",
        options: [
          {
            id: "devolver",
            label: "Llaman al mozo y lo devuelven.",
            result: "El mozo pide disculpas y se lleva el plato. Hacerlo de nuevo tarda veinticinco minutos y los demás ya están comiendo.",
            ask: "¿Qué hacen mientras Lu espera: comen o la esperan? Pónganse de acuerdo.",
          },
          {
            id: "compartir",
            label: "Le ofrecés compartir tu plato.",
            result: "Lu acepta la mitad de tu ensalada. Cuando llega la cuenta, los ravioles con carne están cobrados igual.",
            ask: "Hablá con el mozo: explicá qué pasó y pedile que no cobre ese plato.",
          },
          {
            id: "nada",
            label: "Lu dice que no importa y aparta la carne.",
            result: "Lu come lo que puede, pero casi no prueba nada. A la media hora dice que tiene hambre y quiere ir a comer a otro lado.",
            ask: "¿Fue un error no reclamar? ¿Por qué a veces no reclamamos aunque tengamos razón?",
          },
        ],
        close: "¿Reclamás cuando algo sale mal en un restaurante? Contá una vez que lo hiciste, o una vez que no te animaste.",
        role: "Sos el mozo: amable, pero con diez mesas a la vez. Al principio decís que «el plato salió bien».",
        teacher: ["¿Qué es peor: un mal plato o un mal servicio?", "¿Dejás propina si algo salió mal?"],
      },
      {
        id: "resto-al-lado",
        title: "La mesa de al lado",
        situation: "En la mesa de al lado festejan un cumpleaños: cantan, gritan y golpean la mesa. En la de ustedes nadie se escucha.",
        prompt: "¿Cómo lo resuelven?",
        options: [
          {
            id: "mozo",
            label: "Le piden al mozo que hable con ellos.",
            result: "El mozo dice que no puede hacer nada: «Es un cumpleaños, es un ratito». Media hora después, siguen igual.",
            ask: "El «ratito» ya lleva media hora. ¿Insistís, se cambian de mesa o se van? Explicá por qué.",
          },
          {
            id: "hablar",
            label: "Vas vos a hablar con ellos.",
            result: "La cumpleañera se disculpa y bajan un poco el volumen. Al rato te mandan una porción de torta y te invitan a acercarte.",
            ask: "Te acercás un minuto a su mesa. Presentate y contales qué hacen ustedes esta noche.",
          },
          {
            id: "sumarse",
            label: "Se suman al festejo.",
            result: "Cantan el feliz cumpleaños con ellos y juntan las mesas. Pero Martín, que tenía algo importante para contarles, ya no puede hablar.",
            ask: "Martín te dice al oído: «Necesitaba contarles algo». ¿Cómo lo ayudás a encontrar el momento?",
          },
        ],
        close: "¿Qué importa más en una salida: el lugar, la comida o poder charlar tranquilos?",
        role: "Hacé de la cumpleañera de la mesa de al lado: simpática y con ganas de que todos festejen.",
        teacher: ["¿Te molesta el ruido en los restaurantes?", "¿Festejaste alguna vez un cumpleaños en un restaurante?"],
      },
    ],
  },
  {
    id: "plaza",
    name: "Plaza de la Fuente",
    short: "Plaza",
    type: "conversacion",
    hub: true,
    hubPrompt: "En la plaza hay gente con ganas de charlar. Elegí con quién hablar.",
    focus: "Conversar con gente distinta, sin respuestas para elegir",
    help: {
      starters: ["Depende de…", "Yo, en tu lugar, …", "A mí me pasó algo parecido: …", "Lo que haría es…", "¿Y vos qué pensás?"],
      chunks: ["dejar plantado a alguien", "tener ganas de…", "animarse a…", "estar de festejo", "conocer gente"],
      vocab: ["el banco", "la fuente", "el colectivo", "la vereda"],
    },
    activities: [
      {
        id: "pablo",
        title: "Pablo",
        who: "Espera a un amigo que no llega",
        says: "Hace cuarenta y cinco minutos que lo espero. No contesta los mensajes. Ya no sé si irme o esperar un poco más.",
        ask: "Tu amigo llega cuarenta y cinco minutos tarde y no contesta. ¿En qué momento dejás de esperarlo? ¿Te vas sin avisar?",
        followUps: [
          "Al final el amigo de Pablo aparece como si nada. ¿Qué le dirías vos?",
          "¿Hay alguien en tu vida que siempre llega tarde? ¿Cómo lo manejás?",
        ],
        role: "Sos Pablo: paciente al principio, cada vez más ofendido.",
      },
      {
        id: "ines",
        title: "Inés",
        who: "Se mudó al barrio hace una semana",
        says: "Me mudé hace una semana y todavía no conozco a nadie. Salí a dar una vuelta para no quedarme sola en casa.",
        ask: "Inés no conoce a nadie en el barrio. ¿Qué le recomendás para hacer amigos en un lugar nuevo?",
        followUps: [
          "¿Qué fue lo más difícil la última vez que empezaste algo de cero: una casa, un trabajo, una ciudad?",
          "¿Qué tiene que tener un barrio para que te sientas en casa?",
        ],
        role: "Sos Inés: tímida, pero agradecés cualquier consejo y hacés preguntas concretas.",
      },
      {
        id: "pareja",
        title: "Ana y Diego",
        who: "Una pareja que no se pone de acuerdo",
        says: "Ana: «Yo quiero ir a bailar». Diego: «Y yo quiero comer algo tranquilo». Los dos te miran: «¿Vos qué harías?».",
        ask: "Ana y Diego quieren que decidas vos. ¿Aceptás ser el árbitro? ¿Qué les proponés?",
        followUps: [
          "Diego te dice por lo bajo: «En realidad estoy cansado, pero no se lo quiero decir». ¿Qué le aconsejás?",
          "Entre amigos o en pareja, ¿quién suele decidir los planes? ¿Está bien así?",
        ],
        role: "Hacé de Ana y de Diego: cada uno intenta que le des la razón.",
      },
      {
        id: "ramiro",
        title: "Ramiro",
        who: "Perdió el último colectivo",
        says: "Se me fue el último colectivo por un minuto. Vivo lejos, el taxi es carísimo y tengo el celular casi sin batería.",
        ask: "Ramiro puede pagar un taxi caro, esperar el primer colectivo a las cinco o pedirle a alguien que lo aloje. ¿Qué elegirías vos y por qué?",
        followUps: [
          "¿Alguna vez te quedaste sin forma de volver a casa de noche? ¿Cómo volviste?",
          "¿Le ofrecerías tu sillón a alguien que conociste hace diez minutos?",
        ],
        role: "Sos Ramiro: cansado, con humor negro, y rechazás la primera idea que te den.",
      },
      {
        id: "marta",
        title: "Marta",
        who: "Hoy tiene algo para festejar",
        says: "¡Hoy me jubilé! Cuarenta años en la misma oficina. Mis compañeros ya se fueron a dormir, pero yo no tengo ganas de volver a casa.",
        ask: "Marta trabajó cuarenta años en el mismo lugar. ¿Te gustaría una vida así o preferís cambiar de trabajo varias veces?",
        followUps: [
          "Marta te pregunta: «¿Y vos qué vas a hacer cuando no tengas que trabajar más?». Contestale.",
          "¿Cuál fue lo último que festejaste? ¿Cómo lo celebraste?",
        ],
        role: "Sos Marta: feliz, conversadora, y te encanta dar consejos de vida.",
      },
      {
        id: "kenji",
        title: "Kenji",
        who: "Un turista un poco perdido",
        says: "Perdón, hablo poco español. Quiero un lugar «auténtico», sin turistas. Pero todos me mandan al mismo restaurante.",
        ask: "Kenji quiere conocer el barrio de verdad. ¿Adónde lo mandás? Explicáselo despacio y con palabras simples.",
        followUps: [
          "¿Qué es «auténtico» para vos cuando viajás? ¿Existe de verdad?",
          "¿Qué lugar de tu ciudad no le recomendarías nunca a un turista? ¿Por qué?",
        ],
        role: "Sos Kenji: entendés la mitad, repetís palabras para confirmar y pedís que te lo expliquen otra vez.",
      },
      {
        id: "sofia",
        title: "Sofía",
        who: "Sentada sola con un café",
        says: "Me cancelaron una cita a último momento, pero igual salí. ¿Te venís a un bar de jazz acá a la vuelta? Dicen que es buenísimo.",
        ask: "Sofía te conoce hace veinte minutos y te invita a seguir la noche en otro lugar. ¿Qué tendría que pasar para que aceptes?",
        followUps: [
          "¿Salís a veces sin compañía: al cine, a comer, de viaje? ¿Por qué sí o por qué no?",
          "¿Qué te cuesta más: decir que sí a un plan improvisado o decir que no sin quedar mal?",
        ],
        role: "Sos Sofía: segura, divertida y directa. Si te dicen que no, no insistís.",
      },
    ],
  },
  {
    id: "bar",
    name: "Bar La Persiana",
    short: "Bar",
    type: "social",
    hub: true,
    hubPrompt: "En el bar pasan varias cosas a la vez. Acercate a una situación y resolvela.",
    focus: "Convencer, negociar y decir que no con respeto",
    help: {
      starters: ["Mirá, te entiendo, pero…", "¿Qué te parece si…?", "No es por nada, pero…", "Te propongo algo: …", "Prefiero no…, gracias."],
      chunks: ["bajar la voz", "colarse en la fila", "quedar mal", "llegar a un acuerdo", "no es para tanto"],
      vocab: ["la barra", "la fila", "la billetera", "la ronda", "el baño"],
    },
    activities: [
      {
        id: "fuerte",
        title: "El que habla a los gritos",
        who: "Un hombre en la barra",
        situation: "Un hombre en la barra habla por teléfono a los gritos. Es la tercera llamada y tu amiga no escucha nada de lo que le contás.",
        task: "Pedile que hable más bajo. Amable, pero claro.",
        pushback: "«¿Y a vos qué te importa? Es un bar, no una biblioteca».",
        task2: "No subas el tono. Respondele y llegá a un acuerdo con él.",
        role: "Sos el hombre del teléfono: al principio te ofendés, pero cedés si te hablan con respeto.",
      },
      {
        id: "quedarse",
        title: "Leo se quiere ir",
        who: "Leo y el grupo",
        situation: "Leo, el compañero de departamento de Vale, quiere irse ya: mañana rinde un examen a las ocho. El grupo le dice que se quede «una más».",
        task: "Ayudá a Leo a irse sin que el grupo se ofenda.",
        pushback: "El grupo insiste: «¡Siempre te vas temprano! Una sola más y te acompañamos al taxi».",
        task2: "Proponé algo que funcione para Leo y para el grupo.",
        role: "Sos el grupo: insistís con humor, pero aceptás una buena razón.",
      },
      {
        id: "billetera",
        title: "La billetera olvidada",
        who: "Martín",
        situation: "Llega la cuenta de la ronda. Martín busca la billetera y pone cara de pánico: se la olvidó en casa. Es la segunda vez este mes.",
        task: "Decile a Martín que esta vez pagás vos, pero que te molesta que se repita.",
        pushback: "Martín se pone a la defensiva: «Fue un error, che. ¿Me estás diciendo que lo hago a propósito?».",
        task2: "Bajá la tensión sin echarte atrás: decile cómo te sentís y qué esperás para la próxima.",
        role: "Sos Martín: te da vergüenza y por eso te defendés.",
      },
      {
        id: "fila",
        title: "Se colaron en la fila",
        who: "Dos chicas en la barra",
        situation: "Hace veinte minutos que esperás para pedir. Dos chicas llegan y se ponen delante tuyo como si nada.",
        task: "Explicales el problema sin pelear.",
        pushback: "Una de ellas sonríe: «Ay, perdón, un amigo nos estaba guardando el lugar». No hay ningún amigo.",
        task2: "No les creés del todo. Decidí si las dejás pasar y decíselo con respeto.",
        role: "Sos una de las chicas: simpática, un poco caradura. Si te hablan bien, terminás pidiendo disculpas.",
      },
      {
        id: "caro",
        title: "Un plan carísimo",
        who: "Vale y el grupo",
        situation: "Vale propone terminar la noche en un bar de cócteles muy caro. Todos dicen que sí. Vos no querés gastar tanto.",
        task: "Decíselo al grupo sin arruinar el plan.",
        pushback: "Vale insiste: «Dale, es mi cumple, un día es un día. Yo invito la primera».",
        task2: "Contestale a Vale: aceptás, ponés un límite o proponés otra cosa. Que suene amable.",
        role: "Sos Vale: entusiasmada, un poco insistente, pero no querés que nadie la pase mal.",
      },
      {
        id: "cancelo",
        title: "Canceló otra vez",
        who: "Una llamada de Nico",
        situation: "Nico te escribe: «Perdón, al final no voy a poder ir». Es la tercera vez que cancela a último momento, y este plan lo habían armado juntos.",
        task: "Llamalo y decile cómo te sentís sin atacarlo.",
        pushback: "Nico hace un silencio y dice: «Es que estoy pasando un momento complicado y no tenía ganas de contarlo».",
        task2: "La situación cambió. ¿Qué le decís ahora? ¿Le proponés algo?",
        role: "Sos Nico: al principio das excusas; cuando te preguntan con cariño, contás la verdad.",
      },
      {
        id: "invitacion",
        title: "Vino de traje",
        who: "Sergio, en la puerta",
        situation: "Sergio llega al bar de traje y con un regalo envuelto en papel dorado. Pensó que era una cena formal. Todos están en zapatillas.",
        task: "Explicale el malentendido a Sergio y ayudalo a sentirse cómodo.",
        pushback: "Sergio, colorado: «Me dijeron “algo tranqui por el cumple”. ¿Cómo iba a saber?».",
        task2: "Contale un malentendido parecido que te haya pasado a vos, para que se ría.",
        role: "Sos Sergio: avergonzado, te reís de vos mismo si te ayudan.",
      },
    ],
  },
  {
    id: "auto",
    name: "El auto con el capó abierto",
    short: "Auto roto",
    type: "condiciones",
    focus: "Hacer planes con «si» cuando la situación cambia",
    help: {
      starters: ["Si no conseguimos…, …", "Si llueve, …", "Si querés, puedo…", "Si fuera mi auto, …"],
      chunks: ["no arranca", "llamar a una grúa", "pedir un taxi", "quedarse sin batería", "dar una mano"],
      vocab: ["el capó", "las balizas", "la grúa", "el taller", "la estación de servicio"],
    },
    grammar: {
      title: "Condiciones con «si»",
      rows: [
        { form: "si + presente → presente", example: "Si no arranca, llamamos a una grúa." },
        { form: "si + presente → futuro", example: "Si llueve, vamos a esperar adentro." },
        { form: "si + presente → imperativo", example: "Si ves un taxi libre, paralo." },
        { form: "si + imperfecto de subjuntivo → condicional", example: "Si tuviera auto, te llevaría. (algo imaginario)" },
      ],
    },
    activities: [
      {
        id: "auto-aeropuerto",
        title: "El auto que no arranca",
        situation: "La calle está casi vacía. Carla tiene el capó abierto y sale un poco de humo. Su vuelo sale muy temprano y en pocas horas tiene que estar en el aeropuerto.",
        ask: "Si no consiguen un mecánico esta noche, ¿qué pueden hacer? Pensá por lo menos dos planes.",
        conditions: [
          { text: "Empieza a llover fuerte.", ask: "Si sigue lloviendo así, ¿cuál de tus planes deja de funcionar?" },
          { text: "El celular de Carla tiene 4 % de batería.", ask: "Si se queda sin batería, ¿cómo se comunican? ¿Qué hacen primero?" },
          { text: "Un hombre frena con su auto y ofrece llevarla. Nadie lo conoce.", ask: "Si fueras Carla, ¿aceptarías? ¿Qué condiciones pondrías?" },
          { text: "El taller de la esquina cierra en diez minutos.", ask: "Si corrés hasta el taller, ¿qué le decís al mecánico para convencerlo?" },
        ],
        close: "Contá cómo terminó la noche de Carla. Usá por lo menos dos frases con «si».",
        role: "Sos Carla: nerviosa y apurada; cambiás de idea rápido y hacés muchas preguntas.",
      },
      {
        id: "auto-nafta",
        title: "Sin nafta",
        situation: "Un señor empuja su auto hasta la vereda. Se quedó sin nafta a tres cuadras de la estación de servicio. Se llama Julio y está tranquilo. Demasiado tranquilo.",
        ask: "Si lo ayudás, ¿qué hacen? Si no podés ayudarlo, ¿qué le recomendás?",
        conditions: [
          { text: "La estación de servicio cierra en veinte minutos.", ask: "Si no llegan antes de que cierre, ¿qué otra opción tienen?" },
          { text: "Julio tiene un bidón vacío en el baúl, pero le duele la espalda.", ask: "Si vas vos a buscar nafta, ¿qué le pedís a Julio mientras tanto?" },
          { text: "Julio te cuenta que va a la fiesta de Vale. Es su papá.", ask: "Si llegan tarde, ¿qué le dicen a Vale? ¿Le avisás ahora o la sorprendés?" },
        ],
        close: "Si te pasara a vos mañana a la noche, ¿a quién llamarías y qué harías?",
        role: "Sos Julio: charlatán, tranquilo, te encanta contar anécdotas en el peor momento.",
      },
    ],
  },
  {
    id: "museo",
    name: "Museo del Pasado",
    short: "Museo",
    type: "museo",
    hub: true,
    hubPrompt: "Hoy el museo abre de noche. Cada pieza guarda una historia que nadie terminó de contar. Elegí una.",
    focus: "Narrar en pasado: contexto, hechos y lo que había pasado antes",
    help: {
      starters: ["Esa noche…", "Mientras…, de repente…", "Antes de eso, ya…", "Seguramente…", "Al día siguiente…"],
      chunks: ["de repente", "mientras tanto", "al día siguiente", "nunca más", "hacía años que…"],
      vocab: ["la vitrina", "la pieza", "el cartel", "la valija", "el andén"],
    },
    grammar: {
      title: "Para contar el pasado",
      rows: [
        { form: "Imperfecto: el contexto", example: "Era de noche, llovía y la estación estaba vacía." },
        { form: "Pretérito: lo que pasó", example: "De repente, alguien abrió la valija." },
        { form: "Pluscuamperfecto: lo de antes", example: "Cuando llegó la carta, ella ya se había ido." },
      ],
    },
    activities: [
      {
        id: "foto",
        title: "La foto de la playa",
        object: "Foto en blanco y negro",
        year: "1998",
        plaque: "Encontrada en una valija abandonada en una estación de tren. Cinco personas en una playa. Una se tapa la cara con un sombrero.",
        ask: "¿Qué estaba pasando cuando sacaron esta foto? ¿Quién es la persona del sombrero?",
        detail: "Atrás de la foto, alguien escribió en lápiz: «El último verano antes de todo».",
        ask2: "¿Qué pasó después de ese verano? Contá la historia.",
        role: "Sos el guardia de noche del museo: sabés algo más de cada pieza y lo contás de a poco, solo si te hacen buenas preguntas.",
      },
      {
        id: "telefono",
        title: "El teléfono público",
        object: "Teléfono público",
        year: "1975–2004",
        plaque: "Estuvo en una esquina de este barrio. Según los vecinos, una noche sonó durante una hora y nadie atendió.",
        ask: "¿Quién llamaba y por qué nadie atendió? Imaginá la escena.",
        detail: "A la mañana siguiente, una mujer atendió por fin. Escuchó una sola frase y se fue llorando.",
        ask2: "¿Qué frase escuchó? ¿Qué hizo después?",
        role: "Sos el guardia de noche del museo: sabés algo más de cada pieza y lo contás de a poco, solo si te hacen buenas preguntas.",
      },
      {
        id: "boleto",
        title: "Un tren que nunca salió",
        object: "Boleto de tren",
        year: "1987",
        plaque: "Buenos Aires – Mendoza, 14 de julio, 23:40. Ese tren nunca salió de la estación.",
        ask: "¿Por qué no salió el tren? Contá qué pudo haber pasado ese día.",
        detail: "El boleto tiene un nombre escrito a mano y una mancha de café.",
        ask2: "¿Quién era el pasajero y qué hizo esa noche en vez de viajar?",
        role: "Sos el guardia de noche del museo: sabés algo más de cada pieza y lo contás de a poco, solo si te hacen buenas preguntas.",
      },
      {
        id: "carta",
        title: "La carta detrás del mueble",
        object: "Carta sin abrir",
        year: "1979",
        plaque: "Una mujer la encontró veinte años después de que fue escrita, detrás de un mueble, el día que se mudaba.",
        ask: "Imaginá qué había pasado antes: ¿quién la escribió, para quién y por qué nunca llegó?",
        detail: "La mujer la abrió. La carta decía: «Si me esperás, vuelvo en marzo».",
        ask2: "¿Qué hizo la mujer cuando la leyó, veinte años tarde?",
        role: "Sos el guardia de noche del museo: sabés algo más de cada pieza y lo contás de a poco, solo si te hacen buenas preguntas.",
      },
      {
        id: "valija",
        title: "La valija que nadie buscó",
        object: "Valija de cuero",
        year: "1963",
        plaque: "Llegó a la oficina de objetos perdidos del puerto. Nadie la reclamó nunca.",
        ask: "¿Por qué el dueño no volvió a buscarla? ¿Qué le había pasado?",
        detail: "Adentro había un vestido de novia, un mapa de Italia y un pasaje de barco sin usar.",
        ask2: "Con esos tres objetos, contá la historia completa.",
        role: "Sos el guardia de noche del museo: sabés algo más de cada pieza y lo contás de a poco, solo si te hacen buenas preguntas.",
      },
      {
        id: "televisor",
        title: "La noche de la Luna",
        object: "Televisor",
        year: "1969",
        plaque: "En este televisor, medio barrio vio a los astronautas llegar a la Luna. La familia de la casa recuerda esa noche por otro motivo.",
        ask: "¿Cómo era esa noche en la casa? ¿Quiénes estaban y qué hacían?",
        detail: "Mientras todos miraban la Luna, el hijo mayor se fue de la casa sin avisar.",
        ask2: "¿Adónde fue y por qué eligió justo ese momento?",
        role: "Sos el guardia de noche del museo: sabés algo más de cada pieza y lo contás de a poco, solo si te hacen buenas preguntas.",
      },
      {
        id: "bicicleta",
        title: "La bicicleta del cartero",
        object: "Bicicleta roja",
        year: "1952–1982",
        plaque: "Un cartero la usó treinta años en este barrio. El último día de trabajo no volvió al correo.",
        ask: "¿Cómo era un día normal del cartero? ¿Qué pasó el último día?",
        detail: "Esa tarde, el cartero entregó su última carta. Estaba dirigida a él.",
        ask2: "¿Qué decía la carta y qué hizo él después?",
        role: "Sos el guardia de noche del museo: sabés algo más de cada pieza y lo contás de a poco, solo si te hacen buenas preguntas.",
      },
      {
        id: "habitacion",
        title: "La habitación de 1985",
        object: "Habitación reconstruida",
        year: "1985",
        plaque: "Así estaba el cuarto de una estudiante: una máquina de escribir, una planta, el póster de un recital. La cama, sin deshacer.",
        ask: "¿Cómo era la vida de esta estudiante? Describí un día normal suyo.",
        detail: "En la máquina de escribir quedó una hoja con una sola línea: «Hoy decidí irme».",
        ask2: "¿Qué decidió y adónde se fue? ¿Volvió alguna vez?",
        role: "Sos el guardia de noche del museo: sabés algo más de cada pieza y lo contás de a poco, solo si te hacen buenas preguntas.",
      },
      {
        id: "caja",
        title: "La caja de música",
        object: "Caja de música rota",
        year: "¿?",
        plaque: "Apareció una mañana en la puerta del museo con una nota: «Esto tiene que estar acá». Nadie sabe quién la dejó.",
        ask: "¿Quién la dejó y por qué en un museo? Inventá su historia.",
        detail: "Cuando la arreglaron, la canción que tocaba era la misma que suena todas las noches en el bar de enfrente.",
        ask2: "¿Qué relación hay entre la caja y el bar? Contá qué había pasado antes.",
        role: "Sos el guardia de noche del museo: sabés algo más de cada pieza y lo contás de a poco, solo si te hacen buenas preguntas.",
      },
    ],
  },
  {
    id: "taxi",
    name: "Taxi en la avenida",
    short: "Taxi",
    type: "comparar",
    focus: "Comparar opciones con datos y elegir",
    help: {
      starters: ["Es más rápido, pero…", "Tarda menos que…", "Sale tan caro como…", "Prefiero… aunque…", "Lo mejor sería…"],
      chunks: ["dar la vuelta", "tomar otro camino", "estar cortado", "salir más barato", "llegar a tiempo"],
      vocab: ["el semáforo", "el desvío", "la tarifa", "el taxímetro", "el conductor"],
    },
    activities: [
      {
        id: "taxi-cortado",
        title: "Calle cortada",
        situation: "Vas en taxi a la terraza de Vale. A dos cuadras, la policía corta la calle por un recital al aire libre. El conductor te mira por el espejo: «¿Qué hacemos?».",
        prompt: "Compará las tres opciones: tiempo, plata y comodidad. Después elegí una.",
        options: [
          {
            id: "caminar",
            label: "Bajar y caminar",
            facts: ["10 min", "Pagás lo que marca", "Hay que cruzar el recital"],
            result: "Te bajás y cruzás el recital. Hay gente bailando y… Nico en primera fila. Te ve y te hace señas para que te quedes.",
            ask: "Nico quiere que te quedes en el recital y Vale te espera. ¿Qué hacés? Explicáselo a uno de los dos.",
          },
          {
            id: "rodear",
            label: "Rodear por el puerto",
            facts: ["18 min", "El doble", "Llegás seco y cómodo"],
            result: "El conductor toma el camino del puerto. Llegás cómodo, pero pagás el doble y te perdés el brindis.",
            ask: "Vale te pregunta por qué llegaste tarde. Contale el viaje y convencela de que no fue tu culpa.",
          },
          {
            id: "esperar",
            label: "Esperar a que abran",
            facts: ["¿30 min?", "Sube despacio", "Nadie sabe cuándo termina"],
            result: "Esperan. El conductor apaga el motor, pone la radio y empieza a contarte su vida: durante veinte años fue músico.",
            ask: "Hacele preguntas al conductor sobre su vida de músico. ¿Por qué dejó de tocar?",
          },
        ],
        close: "¿Qué te importa más cuando viajás de noche: llegar rápido, gastar poco o sentirte seguro?",
        role: "Sos el conductor: charlatán, seguro de que conocés la ciudad mejor que nadie.",
      },
      {
        id: "taxi-mayor",
        title: "La otra calle Mayor",
        situation: "Le dijiste «a la calle Mayor». Diez minutos después te das cuenta de que el taxi va a la Plaza Mayor, al otro lado de la ciudad.",
        prompt: "Compará rápido: el taxímetro sigue corriendo.",
        options: [
          {
            id: "seguir",
            label: "Seguir hasta la plaza",
            facts: ["15 min", "Caro", "Después, 20 min a pie"],
            result: "Llegás a la Plaza Mayor. Está llena de gente: hay un mercado nocturno que no conocías.",
            ask: "Mandale un audio a Vale: dónde terminaste, qué ves y qué vas a hacer.",
          },
          {
            id: "volver",
            label: "Pedir que dé la vuelta",
            facts: ["12 min", "Más caro todavía", "La avenida está trabada"],
            result: "El conductor da la vuelta, pero dice que el error fue tuyo y que vas a pagar todo el recorrido.",
            ask: "Negociá el precio: explicá qué dijiste exactamente y qué entendió él.",
          },
          {
            id: "bajar",
            label: "Bajar y pedir otro auto",
            facts: ["¿?", "Este viaje más otro", "Empieza a lloviznar"],
            result: "Te bajás en una esquina que no conocés. La aplicación no encuentra autos y la llovizna se vuelve lluvia.",
            ask: "Entrás a un kiosco. Explicá adónde querés ir y pedí ayuda.",
          },
        ],
        close: "¿De quién fue el error? ¿Qué podés hacer para que no te vuelva a pasar?",
        role: "Sos el conductor: decís que «Mayor hay una sola» y no aceptás el error fácilmente.",
      },
    ],
  },
  {
    id: "tienda",
    name: "Almacén 24 horas",
    short: "Almacén 24 h",
    type: "describir",
    focus: "Explicar algo cuando no sabés la palabra",
    help: {
      starters: ["Es una cosa que sirve para…", "Es parecido a…, pero…", "Se usa cuando…", "Es de plástico / de metal…", "No sé cómo se dice, pero…"],
      chunks: ["sirve para", "se parece a", "más o menos así de grande", "se enchufa", "se lleva en la mano"],
      vocab: ["el estante", "la caja", "el empleado", "el vuelto", "la góndola"],
    },
    activities: [
      {
        id: "tienda-enchufe",
        title: "El enchufe que no entra",
        situation: "Tu cargador es de otro país y no entra en ningún toma de la pared. Te queda 3 % de batería. Necesitás algo, pero no sabés cómo se llama.",
        need: "un adaptador de enchufe",
        banned: ["adaptador", "enchufe", "cargador"],
        task: "Explicale al empleado qué necesitás sin decir las palabras prohibidas.",
        wrong: "El empleado vuelve con un alargue de cuatro tomas: «¿Esto?».",
        task2: "No es eso. Explicale la diferencia y qué tiene que tener lo que buscás.",
        close: "¿Te pasó alguna vez no saber cómo se dice algo en otro idioma? ¿Cómo te las arreglaste?",
        role: "Sos el empleado: aburrido en el turno noche, entendés todo al revés a propósito.",
      },
      {
        id: "tienda-hielo",
        title: "Algo para el hielo",
        situation: "Vale te pidió hielo para la previa, pero las bolsas se rompen y el hielo se derrite en el camino. Necesitás algo para llevarlo.",
        need: "una conservadora, una heladerita portátil",
        banned: ["conservadora", "heladera", "frío"],
        task: "Describí lo que buscás: la forma, el tamaño, el material y para qué sirve.",
        wrong: "El empleado te ofrece un balde de plástico y un diario viejo: «Con esto se arreglan todos».",
        task2: "¿Te sirve? Decidí si lo aceptás y explicale cómo lo vas a usar.",
        close: "¿Qué cosa de tu casa no sabrías nombrar en español? Describila para que alguien la adivine.",
        role: "Sos el empleado: das tu opinión sobre todo y tenés soluciones caseras para cualquier cosa.",
      },
      {
        id: "tienda-regalo",
        title: "Un regalo de último momento",
        situation: "Es el cumpleaños de Vale y no tenés regalo. En el almacén hay un estante con cosas raras: velas, juegos de cartas, un destapador con forma de pez.",
        need: "algo para Vale, que ama viajar y el café",
        banned: ["regalo", "viaje", "café"],
        task: "Describí a Vale sin decir esas palabras, para que el empleado te recomiende algo.",
        wrong: "El empleado te muestra, orgulloso, el destapador con forma de pez: «Este se lleva muchísimo».",
        task2: "Convencelo de que no es para Vale… o convencete vos de que sí.",
        close: "¿Qué es lo más raro que te regalaron? ¿Qué dijiste cuando lo abriste?",
        role: "Sos el empleado: el destapador con forma de pez es tu orgullo y lo defendés.",
      },
    ],
  },
  {
    id: "terraza",
    name: "La terraza de las luces",
    short: "Terraza",
    type: "acuerdo",
    focus: "Negociar en grupo hasta llegar a un acuerdo",
    help: {
      starters: ["Entiendo que…, pero…", "Lo que propongo es…", "Así, por lo menos…", "¿Les parece si…?", "Si nos separamos, …"],
      chunks: ["ponerse de acuerdo", "ceder un poco", "la mayoría", "dejar para otro día", "a mí me da igual"],
      vocab: ["el boliche", "el último colectivo", "la madrugada", "la despedida"],
    },
    activities: [
      {
        id: "terraza-cierre",
        title: "¿Cómo sigue la noche?",
        situation: "En la terraza, cada uno quiere terminar la noche de otra manera.",
        people: [
          { name: "Vale", wants: "Quedarse en la terraza", reason: "Es su cumpleaños y organizó todo." },
          { name: "Nico", wants: "Ir a bailar", reason: "Hace meses que no sale." },
          { name: "Lu", wants: "Volver a casa", reason: "Mañana trabaja temprano." },
          { name: "Martín", wants: "Ir a comer algo", reason: "Casi no cenó." },
        ],
        ask: "Armá un plan para el grupo. Tiene que funcionar por lo menos para tres de los cuatro.",
        change: "Lu dice que se queda una hora más si alguien la acompaña después a tomar un taxi.",
        ask2: "Con esta condición nueva, ¿cambia tu plan? Presentalo otra vez y convencé al que quedó afuera.",
        role: "Hacé de cualquiera de los cuatro. Cambiá de opinión solo con buenos argumentos.",
      },
      {
        id: "terraza-foto",
        title: "La foto del grupo",
        situation: "Todos posan con la ciudad de fondo y la foto sale perfecta. Vale quiere subirla ya mismo, pero Sergio no quiere aparecer.",
        people: [
          { name: "Vale", wants: "Subirla ahora", reason: "Es su cumpleaños y salieron todos lindos." },
          { name: "Sergio", wants: "No aparecer", reason: "Hoy le dijo a su jefa que estaba enfermo." },
          { name: "Nico", wants: "Sacar otra sin Sergio", reason: "No le parece para tanto." },
        ],
        ask: "¿Qué hacen con la foto? Proponé una solución que respete a todos.",
        change: "Vale descubre que la jefa de Sergio la sigue en las redes.",
        ask2: "¿Esto cambia algo? ¿Hay que pedir permiso siempre antes de subir una foto donde salen otros?",
        role: "Sos Sergio: nervioso, no querés contar toda la verdad.",
      },
    ],
  },
];

// One city-wide change after several places. `affects` names places whose
// earlier decisions the event asks the learner to revisit.
export const CITY_EVENTS = [
  {
    id: "lluvia",
    title: "Se larga a llover",
    text: "Empieza a llover fuerte. La plaza y la terraza se vacían, y no pasa ningún taxi libre.",
    affects: ["plaza", "terraza", "taxi", "auto"],
    prompts: [
      "Mirá los lugares donde estuviste. ¿Cuáles siguen siendo una buena opción con lluvia y cuáles no?",
      "Proponé un plan nuevo para el grupo y explicá qué cambia respecto del anterior.",
      "Un amigo llega empapado y no sabe nada. Contale qué pasó esta noche hasta ahora.",
    ],
    teacher: "A mitad del plan, cambiá un dato: «el bar cierra a la una».",
  },
  {
    id: "transporte",
    title: "Se corta el transporte",
    text: "Una falla corta el subte y el último colectivo pasa lleno, sin parar. Lu tiene que volver a su casa.",
    affects: ["taxi", "terraza", "bar"],
    prompts: [
      "¿Qué opciones tiene Lu para volver? Compará por lo menos dos.",
      "Pensá en una decisión que tomaste antes esta noche. ¿La cambiarías ahora? ¿Por qué?",
      "Proponé cómo se organiza el grupo para que nadie vuelva solo.",
    ],
    teacher: "Hacé de Lu: estás cansada y un poco preocupada. Rechazá la primera propuesta.",
  },
  {
    id: "celular",
    title: "Nico perdió el celular",
    text: "Nico no encuentra su celular. Estuvo en los mismos lugares que vos esta noche.",
    affects: [],
    prompts: [
      "Reconstruí el recorrido: ¿dónde estuvieron y qué pasó en cada lugar?",
      "¿Dónde puede estar? Hacé hipótesis: «capaz que lo dejó en…», «seguro que…», «no creo que…».",
      "Proponé un plan para buscarlo sin arruinar el resto de la noche.",
    ],
    teacher: "El celular aparece en el último lugar que nombre el alumno… con un mensaje nuevo que cambia el plan.",
  },
];

export const FINAL = {
  title: "Resumen de la noche",
  prompts: [
    "¿Adónde fuiste y en qué orden?",
    "¿Qué pasó en el lugar que más recordás?",
    "¿Qué decisión cambiaste cuando la ciudad cambió?",
    "Describí a una persona que conociste esta noche.",
    "¿Qué harías distinto la próxima vez?",
  ],
  hypothetical: "Si la noche empezara de nuevo, ¿qué cambiarías?",
  help: {
    starters: ["Primero fui a…", "Después…", "Al final…", "Lo que más me sorprendió fue…", "Si pudiera volver, …"],
    chunks: ["al principio", "de repente", "por eso", "al final", "la próxima vez"],
  },
  criteria: [
    { id: "conectores", label: "Relato conectado", detail: "Ordena los hechos con conectores (primero, después, entonces, al final)." },
    { id: "razones", label: "Razones", detail: "Explica por qué tomó sus decisiones." },
    { id: "repreguntas", label: "Repreguntas", detail: "Responde a preguntas nuevas sin guion." },
    { id: "claridad", label: "Comprensible", detail: "Se le entiende sin esfuerzo, aunque tenga errores." },
  ],
};

// Moves the teacher can make anywhere, on top of each situation's own role.
export const TEACHER_MOVES = [
  { id: "contradecir", label: "Llevar la contraria", line: "«Yo no lo haría así. ¿Por qué te parece la mejor opción?»" },
  { id: "repreguntar", label: "Repreguntar", line: "«¿Y si pasara lo contrario? ¿Qué harías?»" },
  { id: "cambiar-dato", label: "Cambiar un dato", line: "Cambiá la hora, el lugar o una persona y pedí que adapte el plan." },
];

export const ROUTE_PLAN = [
  { id: "llegada", title: "Llegada", minutes: 4, note: "Bajar del colectivo, activar el tema y elegir el primer lugar." },
  { id: "exploracion", title: "Explorar el barrio", minutes: 24, note: "Cuatro o cinco lugares de 4 a 6 minutos. No hace falta visitar todo." },
  { id: "evento", title: "Algo cambia", minutes: 8, note: "Un imprevisto en toda la ciudad obliga a revisar el plan." },
  { id: "cierre", title: "Resumen de la noche", minutes: 9, note: "Relato oral del recorrido e hipótesis final." },
];
