export type VerbalMood = "Indicativo" | "Subjuntivo" | "Imperativo";
export type TemporalPlane = "Presente" | "Pasado" | "Futuro" | "Condicional" | "Sin oposición temporal";
export type ProductiveStatus = "Productivo" | "Receptivo" | "Histórico / restringido";

export type VerbalExample = { es: string; en?: string };
export type VerbalUse = { title: string; titleEn?: string; explanation: string; explanationEn?: string; example: VerbalExample };
export type VerbalChoice = { prompt: string; options: string[]; answer: number; why: string; whyEn?: string };
export type VerbalConversation = { question: string; starter: string; followUp: string; english?: string };

export type VerbalLesson = {
  id: number;
  slug: string;
  title: string;
  shortTitle: string;
  level: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
  levels?: string[];
  mood: VerbalMood;
  tense: string;
  plane: TemporalPlane;
  status: ProductiveStatus;
  compound: boolean;
  bilingual: boolean;
  curriculumOrder: number;
  requires: number[];
  accent: string;
  question: string;
  questionEn?: string;
  core: string;
  coreEn?: string;
  formula: string;
  formation: string[];
  formationEn?: string[];
  uses: VerbalUse[];
  examples: VerbalExample[];
  contrast: { left: string; right: string; why: string; whyEn?: string }[];
  practice: VerbalChoice[];
  transform: { prompt: string; answer: string; why: string }[];
  conversation: VerbalConversation[];
  regional: string[];
  grammaticalTense: string;
  temporalPlane: TemporalPlane;
  productiveStatus: ProductiveStatus;
  route: string;
  duration: "≈ 45 min";
  regionalVariants: string[];
  isCompound: boolean;
  isHistoricalOrRestricted: boolean;
};

type VerbalLessonSource = Omit<VerbalLesson,
  "grammaticalTense" | "temporalPlane" | "productiveStatus" | "route" |
  "duration" | "regionalVariants" | "isCompound" | "isHistoricalOrRestricted"
>;

export type VerbalLessonSummary = Pick<VerbalLesson,
  "id" | "slug" | "title" | "shortTitle" | "level" | "levels" | "mood" |
  "tense" | "plane" | "status" | "compound" | "accent" | "question"
>;

const conversations = (items: Array<[string,string,string,string?]>): VerbalConversation[] =>
  items.map(([question,starter,followUp,english])=>({question,starter,followUp,english}));

const verbalLessonSources: VerbalLessonSource[] = [
  {
    id:140,slug:"presente-de-indicativo",title:"Presente de indicativo",shortTitle:"Presente",level:"A1",mood:"Indicativo",tense:"Presente",plane:"Presente",status:"Productivo",compound:false,bilingual:true,curriculumOrder:850,requires:[48],accent:"#20b7a6",
    question:"¿Qué ocurre ahora, habitualmente o en general?",questionEn:"What happens now, habitually or in general?",
    core:"El presente presenta acciones actuales, hábitos, estados y hechos generales. También puede señalar un futuro programado.",coreEn:"The present describes current actions, habits, states and general facts. It can also point to a scheduled future.",formula:"RAÍZ + -O / -ÁS(-AS) / -A(-E) / -AMOS(-EMOS/-IMOS) / -AN(-EN)",
    formation:["Quitá -ar, -er o -ir del infinitivo.","Agregá la terminación de la persona.","Aprendé los irregulares por familias: cambio de raíz, primera persona y formas propias."],formationEn:["Remove -ar, -er or -ir from the infinitive.","Add the ending that matches the person.","Learn irregular verbs in families: stem change, first-person change and unique forms."],
    uses:[
      {title:"Rutina",titleEn:"Routine",explanation:"Acción habitual.",explanationEn:"A habitual action.",example:{es:"Trabajo de lunes a viernes.",en:"I work Monday to Friday."}},
      {title:"Ahora",titleEn:"Now",explanation:"Estado o acción vigente.",explanationEn:"A current state or action.",example:{es:"Estoy en casa.",en:"I am at home."}},
      {title:"Hecho general",titleEn:"General fact",explanation:"Información válida en general.",explanationEn:"Information that is generally true.",example:{es:"El agua hierve a cien grados.",en:"Water boils at one hundred degrees."}},
      {title:"Futuro programado",titleEn:"Scheduled future",explanation:"El contexto temporal proyecta el presente.",explanationEn:"The time expression projects the present into the future.",example:{es:"Mañana salgo a las ocho.",en:"I leave at eight tomorrow."}},
    ],
    examples:[{es:"Yo hablo español.",en:"I speak Spanish."},{es:"Vos comés temprano.",en:"You eat early."},{es:"¿Dónde vivís?",en:"Where do you live?"},{es:"Ella tiene dos trabajos.",en:"She has two jobs."},{es:"Hoy no puedo.",en:"I can't today."},{es:"El tren llega mañana.",en:"The train arrives tomorrow."}],
    contrast:[{left:"Trabajo todos los días.",right:"Estoy trabajando ahora.",why:"El presente expresa la rutina; estar + gerundio enfoca el desarrollo actual.",whyEn:"The present describes the routine; estar + gerundio focuses on the action in progress."},{left:"Mañana trabajo.",right:"Mañana voy a trabajar.",why:"Ambas miran al futuro: la primera suena programada; la segunda destaca plan o intención.",whyEn:"Both refer to the future: the first sounds scheduled; the second highlights a plan or intention."}],
    practice:[{prompt:"Todos los días Ana ___ a las siete.",options:["sale","salió","saldrá"],answer:0,why:"Todos los días señala una rutina.",whyEn:"Todos los días signals a routine."},{prompt:"Yo no ___ la respuesta.",options:["sé","sabo","sabré ayer"],answer:0,why:"Saber tiene la primera persona irregular sé.",whyEn:"The first-person form of saber is the irregular sé."},{prompt:"¿Dónde ___ vos?",options:["vivís","vives tú","vivió"],answer:0,why:"Con vos, vivir forma vivís.",whyEn:"With vos, vivir becomes vivís."},{prompt:"Mañana el vuelo ___ a las nueve.",options:["sale","salía","saliera"],answer:0,why:"El presente puede expresar un horario futuro.",whyEn:"The present can describe a future timetable."},{prompt:"Nosotros ___ café por la mañana.",options:["tomamos","toman","tomemos"],answer:0,why:"Nosotros concuerda con tomamos.",whyEn:"Nosotros agrees with tomamos."}],
    transform:[{prompt:"Convertí en negativa: Trabajo aquí.",answer:"No trabajo aquí.",why:"No se coloca delante del verbo conjugado."},{prompt:"Convertí en pregunta: Vivís en Madrid.",answer:"¿Vivís en Madrid?",why:"La entonación y los signos forman la pregunta total."},{prompt:"Cambiá el sujeto: Yo tengo tiempo → nosotros.",answer:"Nosotros tenemos tiempo.",why:"El verbo concuerda con el nuevo sujeto."}],
    conversation:conversations([["¿Dónde vivís y con quién?","Vivo en… con…","¿Qué te gusta de ese lugar?","Where do you live and who do you live with?"],["¿Qué hacés normalmente por la mañana?","Normalmente…","¿A qué hora empezás?","What do you normally do in the morning?"],["¿Dónde trabajás o estudiás?","Trabajo / estudio en…","¿Qué hacés allí?","Where do you work or study?"],["¿Qué comida preparás o comprás con frecuencia?","Con frecuencia…","¿Cuándo la comés?","What food do you often make or buy?"],["¿Qué actividad te gusta mucho?","Me gusta…","¿Con quién la hacés?","What activity do you really like?"],["¿Qué no hacés nunca durante la semana?","Nunca…","¿Por qué no?","What do you never do during the week?"],["¿Cómo es un día normal para vos?","Primero…, después…","¿Qué parte preferís?","What is a normal day like for you?"],["¿Qué hacés mañana?","Mañana…","¿Es un plan fijo?","What are you doing tomorrow?"]]),
    regional:["Tú hablás no es estándar: tú hablas; vos hablás.","Vosotros se usa principalmente en España; ustedes, en toda América.","El presente con valor futuro es común en todas las variedades."],
  },
  {
    id:141,slug:"preterito-perfecto-compuesto-indicativo",title:"Pretérito perfecto compuesto de indicativo",shortTitle:"Perfecto compuesto",level:"A2",mood:"Indicativo",tense:"Pretérito perfecto compuesto",plane:"Pasado",status:"Productivo",compound:true,bilingual:true,curriculumOrder:1410,requires:[140],accent:"#4388f5",
    question:"¿Qué pasado sigue conectado con el presente?",questionEn:"Which past event is still connected to the present?",core:"Presenta una experiencia o acción anterior desde un marco que el hablante siente vigente.",coreEn:"It presents an earlier experience or action from a time frame the speaker still sees as current.",formula:"PRESENTE DE HABER + PARTICIPIO · HE / HAS / HA / HEMOS / HAN + -ADO/-IDO",
    formation:["Conjugá haber en presente.","Formá el participio: -ado o -ido.","El participio no cambia con la persona ni con el género."],formationEn:["Conjugate haber in the present.","Build the participle with -ado or -ido.","The participle does not change for person or gender."],
    uses:[{title:"Marco todavía abierto",titleEn:"Still-open time frame",explanation:"Hoy, esta semana o este año incluyen el presente.",explanationEn:"Today, this week or this year include the present.",example:{es:"Hoy he hablado con Ana.",en:"I have spoken to Ana today."}},{title:"Experiencia",titleEn:"Life experience",explanation:"Importa la experiencia, no una fecha cerrada.",explanationEn:"The experience matters, not a finished date.",example:{es:"He visitado México tres veces.",en:"I have visited Mexico three times."}},{title:"Resultado actual",titleEn:"Present result",explanation:"La acción pasada deja una consecuencia visible.",explanationEn:"The past action leaves a visible result.",example:{es:"He perdido las llaves.",en:"I've lost my keys."}},{title:"Noticia reciente",titleEn:"Recent news",explanation:"Acerca el hecho al momento de hablar.",explanationEn:"It brings the event close to the speaking moment.",example:{es:"El equipo ha ganado.",en:"The team has won."}}],
    examples:[{es:"Esta semana he trabajado mucho.",en:"I have worked a lot this week."},{es:"¿Alguna vez has viajado solo?",en:"Have you ever travelled alone?"},{es:"Todavía no hemos comido.",en:"We haven't eaten yet."},{es:"Ya han llegado.",en:"They have already arrived."},{es:"Nunca he visto esa película.",en:"I have never seen that film."},{es:"Hoy me he levantado tarde.",en:"I got up late today."}],
    contrast:[{left:"Hoy he hablado con Ana.",right:"Ayer hablé con Ana.",why:"Hoy puede sentirse abierto; ayer está cerrado.",whyEn:"Today may be felt as open; yesterday is finished."},{left:"He vivido en Chile.",right:"Viví en Chile en 2022.",why:"Experiencia sin fecha cerrada frente a periodo terminado.",whyEn:"An experience without a finished date contrasts with a completed period."}],
    practice:[{prompt:"Esta semana ___ tres clases.",options:["he dado","di ayer","daba"],answer:0,why:"Esta semana incluye el presente.",whyEn:"This week still includes the present moment."},{prompt:"Nunca ___ sushi.",options:["he probado","probaba ayer","probaré antes"],answer:0,why:"Nunca + experiencia vital favorece el perfecto.",whyEn:"Nunca with life experience favours the present perfect."},{prompt:"Hoy nosotros ___ tarde.",options:["hemos llegado","han llegado","llegábamos"],answer:0,why:"Hemos concuerda con nosotros.",whyEn:"Hemos agrees with nosotros."},{prompt:"El participio correcto de hacer es…",options:["hecho","hacido","hago"],answer:0,why:"Hecho es irregular.",whyEn:"Hecho is the irregular past participle."},{prompt:"Ayer a las cinco…",options:["terminé","he terminado esta semana","terminaba siempre"],answer:0,why:"Ayer a las cinco cierra el marco.",whyEn:"Yesterday at five creates a finished time frame."}],
    transform:[{prompt:"Conectá con hoy: Esta mañana perdí el pasaporte.",answer:"Esta mañana he perdido el pasaporte.",why:"El hablante conserva la mañana como marco actual."},{prompt:"Negá: Hemos terminado.",answer:"No hemos terminado.",why:"No precede al auxiliar."},{prompt:"Preguntá por experiencia: viajar a Brasil.",answer:"¿Alguna vez has viajado a Brasil?",why:"Alguna vez abre una experiencia sin fecha cerrada."}],
    conversation:conversations([["¿Qué has hecho hoy?","Hoy he…","¿Qué te falta hacer?","What have you done today?"],["¿Qué lugar interesante has visitado?","He visitado…","¿Cuándo fuiste?","What interesting place have you visited?"],["¿Qué película has visto recientemente?","Recientemente he visto…","¿La recomendarías?","What film have you seen recently?"],["¿Qué has aprendido este año?","Este año he aprendido…","¿Cómo lo aprendiste?","What have you learnt this year?"],["¿Alguna vez has vivido solo?","Sí, he… / No, nunca he…","¿Cómo fue o cómo sería?","Have you ever lived alone?"],["¿Qué cosa importante has perdido alguna vez?","He perdido…","¿La recuperaste?","What important thing have you ever lost?"],["¿Qué ha cambiado en tu vida últimamente?","Últimamente ha cambiado…","¿Es positivo?","What has changed in your life lately?"],["¿Qué no has hecho todavía esta semana?","Todavía no he…","¿Cuándo lo vas a hacer?","What haven't you done yet this week?"]]),
    regional:["En gran parte de España es frecuente con hoy/esta semana.","En muchas zonas de América se prefiere el indefinido: Hoy hablé con Ana.","La elección regional no cambia la formación del tiempo."],
  },
  {
    id:142,slug:"preterito-perfecto-simple-indicativo",title:"Pretérito perfecto simple de indicativo",shortTitle:"Indefinido",level:"A2",mood:"Indicativo",tense:"Pretérito perfecto simple",plane:"Pasado",status:"Productivo",compound:false,bilingual:true,curriculumOrder:1420,requires:[140],accent:"#f26b4b",
    question:"¿Qué ocurrió y quedó cerrado?",questionEn:"What happened and is now complete?",core:"Presenta una acción o secuencia pasada como completa dentro de un marco cerrado.",coreEn:"It presents a past action or sequence as complete within a finished time frame.",formula:"RAÍZ + -É/-ASTE/-Ó/-AMOS/-ARON · -Í/-ISTE/-IÓ/-IMOS/-IERON",
    formation:["Usá las terminaciones del indefinido.","Agrupá los irregulares fuertes: tuve, pude, puse, dije, fui.","No uses tilde en las formas irregulares fuertes."],formationEn:["Use the preterite endings.","Group strong irregulars: tuve, pude, puse, dije, fui.","Strong irregular forms do not take a written accent."],
    uses:[{title:"Acción terminada",titleEn:"Completed action",explanation:"El límite está cerrado.",explanationEn:"The event has a closed boundary.",example:{es:"Ayer trabajé ocho horas.",en:"I worked for eight hours yesterday."}},{title:"Secuencia",titleEn:"Sequence",explanation:"Hace avanzar una narración.",explanationEn:"It moves a story forward.",example:{es:"Entró, saludó y se sentó.",en:"She came in, said hello and sat down."}},{title:"Cambio puntual",titleEn:"Sudden change",explanation:"Marca la entrada en un estado.",explanationEn:"It marks entry into a state.",example:{es:"De repente entendí todo.",en:"Suddenly I understood everything."}},{title:"Periodo cerrado",titleEn:"Finished period",explanation:"La duración completa ya terminó.",explanationEn:"The full period is over.",example:{es:"Viví dos años en Lima.",en:"I lived in Lima for two years."}}],
    examples:[{es:"Anoche cené con Laura.",en:"I had dinner with Laura last night."},{es:"El sábado fuimos al museo.",en:"We went to the museum on Saturday."},{es:"¿Cuándo llegaste?",en:"When did you arrive?"},{es:"No pude dormir.",en:"I couldn't sleep."},{es:"Primero llamó y después salió.",en:"First he called and then he left."},{es:"La reunión terminó a las seis.",en:"The meeting ended at six."}],
    contrast:[{left:"Vivía en Madrid.",right:"Viví en Madrid dos años.",why:"El imperfecto abre la escena; el indefinido presenta el periodo completo.",whyEn:"The imperfect opens the scene; the preterite presents the complete period."},{left:"Hoy he hablado con él.",right:"Ayer hablé con él.",why:"El perfecto conecta con un marco vigente; el indefinido cierra el marco.",whyEn:"The present perfect connects with a current frame; the preterite closes it."}],
    practice:[{prompt:"Ayer Ana ___ temprano.",options:["llegó","llegaba siempre","ha llegado mañana"],answer:0,why:"Ayer presenta un marco cerrado.",whyEn:"Yesterday creates a finished time frame."},{prompt:"Primero ___ la puerta y después entré.",options:["abrí","abría cada día","he abierto mañana"],answer:0,why:"La secuencia pide una acción completa.",whyEn:"The sequence calls for a completed action."},{prompt:"El indefinido de tener es…",options:["tuve","tení","tenía"],answer:0,why:"Tener usa la raíz irregular tuv-.",whyEn:"Tener uses the irregular stem tuv-."},{prompt:"Nosotros ___ a Chile en 2024.",options:["viajamos","viajábamos ahora","hemos viajar"],answer:0,why:"Viajamos puede ser presente o indefinido; 2024 fija la lectura pasada.",whyEn:"Viajamos can be present or preterite; 2024 fixes the past reading."},{prompt:"De repente lo ___.",options:["comprendí","comprendía siempre","comprenderé ayer"],answer:0,why:"De repente introduce un cambio puntual.",whyEn:"De repente introduces a sudden change."}],
    transform:[{prompt:"Cerrá el marco: Vivo en Lima → 2023–2025.",answer:"Viví en Lima de 2023 a 2025.",why:"El periodo terminado favorece el indefinido."},{prompt:"Armá una secuencia con llegar, abrir y sentarse.",answer:"Llegó, abrió la puerta y se sentó.",why:"Cada evento hace avanzar la historia."},{prompt:"Preguntá por el momento: conocer a tu mejor amigo.",answer:"¿Cuándo conociste a tu mejor amigo?",why:"Cuándo busca el punto concreto."}],
    conversation:conversations([["¿Qué hiciste ayer después de trabajar o estudiar?","Ayer…","¿Y después qué pasó?","What did you do yesterday after work or study?"],["¿Cuál fue tu último viaje?","Mi último viaje fue…","¿Qué lugar visitaste?","What was your last trip?"],["¿Cuándo conociste a una persona importante?","La conocí…","¿Cómo se conocieron?","When did you meet an important person?"],["¿Qué comiste anoche?","Anoche comí…","¿Dónde cenaste?","What did you eat last night?"],["¿Qué compra hiciste recientemente?","Compré…","¿Valió la pena?","What did you buy recently?"],["¿Qué pasó el último fin de semana?","El fin de semana…","Contame tres acciones en orden.","What happened last weekend?"],["¿Cuándo aprendiste algo difícil?","Aprendí… cuando…","¿Quién te ayudó?","When did you learn something difficult?"],["¿Qué decisión importante tomaste el año pasado?","El año pasado decidí…","¿Qué cambió después?","What important decision did you make last year?"]]),
    regional:["Indefinido y pretérito perfecto simple son dos nombres del mismo tiempo.","En América puede usarse donde España prefiere el perfecto compuesto.","Vos usa las mismas formas de indefinido que tú en el estándar general: hablaste, comiste."],
  },
  {
    id:143,slug:"preterito-imperfecto-indicativo",title:"Pretérito imperfecto de indicativo",shortTitle:"Imperfecto",level:"A2",mood:"Indicativo",tense:"Pretérito imperfecto",plane:"Pasado",status:"Productivo",compound:false,bilingual:true,curriculumOrder:1430,requires:[142],accent:"#9a72df",
    question:"¿Cómo era la escena o qué ocurría habitualmente?",questionEn:"What was the scene like or what used to happen?",core:"Muestra una situación pasada desde dentro: describe, crea contexto, expresa hábitos o acciones en desarrollo.",coreEn:"It views a past situation from inside: description, background, habits or an action in progress.",formula:"-AR → -ABA · -ER/-IR → -ÍA · IR: IBA · SER: ERA · VER: VEÍA",
    formation:["Para -ar, agregá -aba y sus terminaciones.","Para -er/-ir, agregá -ía y sus terminaciones.","Recordá solo tres irregulares: iba, era y veía."],formationEn:["For -ar verbs, add -aba and its endings.","For -er/-ir verbs, add -ía and its endings.","Remember only three irregulars: iba, era and veía."],
    uses:[{title:"Descripción",titleEn:"Description",explanation:"Construye el fondo de una historia.",explanationEn:"It builds the background of a story.",example:{es:"La calle estaba vacía.",en:"The street was empty."}},{title:"Hábito pasado",titleEn:"Past habit",explanation:"Acción repetida en una etapa.",explanationEn:"A repeated action during a past period.",example:{es:"De chico jugaba afuera.",en:"As a child, I used to play outside."}},{title:"Acción en desarrollo",titleEn:"Action in progress",explanation:"Muestra una acción sin cerrar sus límites.",explanationEn:"It shows an action without closing its boundaries.",example:{es:"Cocinaba cuando llamaste.",en:"I was cooking when you called."}},{title:"Edad, hora y estado",titleEn:"Age, time and state",explanation:"Presenta circunstancias del pasado.",explanationEn:"It presents past circumstances.",example:{es:"Eran las nueve y tenía sueño.",en:"It was nine and I was tired."}}],
    examples:[{es:"Antes vivía cerca del mar.",en:"I used to live near the sea."},{es:"Todos los veranos viajábamos.",en:"We travelled every summer."},{es:"Mientras dormía, sonó el teléfono.",en:"While I was sleeping, the phone rang."},{es:"La casa era pequeña.",en:"The house was small."},{es:"No sabía la respuesta.",en:"I didn't know the answer."},{es:"A los diez años tocaba el piano.",en:"At ten, I played the piano."}],
    contrast:[{left:"Llovía y hacía frío.",right:"Empezó a llover.",why:"El imperfecto describe el fondo; el indefinido introduce el evento.",whyEn:"The imperfect describes the background; the preterite introduces the event."},{left:"Vivía en Roma.",right:"Viví en Roma tres años.",why:"Escena abierta frente a periodo presentado como completo.",whyEn:"An open scene contrasts with a period presented as complete."}],
    practice:[{prompt:"Cuando era niño, ___ al fútbol.",options:["jugaba","jugué una vez","he jugado mañana"],answer:0,why:"Describe un hábito de una etapa.",whyEn:"It describes a habit during a past stage."},{prompt:"___ las diez y todos dormían.",options:["Eran","Fueron","Han sido"],answer:0,why:"La hora de fondo usa imperfecto.",whyEn:"Background time is expressed with the imperfect."},{prompt:"Mientras yo cocinaba, Ana ___.",options:["llamó","llamaba una vez cerrada","ha llamar"],answer:0,why:"La llamada interrumpe la acción en desarrollo.",whyEn:"The phone call interrupts the ongoing action."},{prompt:"El imperfecto de ir es…",options:["iba","fui","iría"],answer:0,why:"Ir tiene la forma irregular iba.",whyEn:"Ir has the irregular imperfect form iba."},{prompt:"Antes no ___ café.",options:["tomaba","tomé ayer","tomaré"],answer:0,why:"Antes crea un hábito o estado pasado.",whyEn:"Antes introduces a past habit or state."}],
    transform:[{prompt:"Abrí la escena: La casa fue pequeña.",answer:"La casa era pequeña.",why:"La descripción sin límite usa imperfecto."},{prompt:"Combiná: yo dormir / sonar el teléfono.",answer:"Dormía cuando sonó el teléfono.",why:"Imperfecto para el proceso e indefinido para la interrupción."},{prompt:"Contá un hábito: ir al parque todos los domingos.",answer:"Todos los domingos iba al parque.",why:"La repetición en una etapa usa imperfecto."}],
    conversation:conversations([["¿Cómo era la casa donde creciste?","La casa era…","¿Qué habitación te gustaba más?","What was the house where you grew up like?"],["¿Qué hacías después de la escuela?","Después de la escuela…","¿Con quién lo hacías?","What did you do after school?"],["¿Cómo era tu barrio antes?","Mi barrio era / tenía…","¿Qué cambió?","What was your neighbourhood like before?"],["¿Qué comida no te gustaba de niño?","De niño no me gustaba…","¿Te gusta ahora?","What food didn't you like as a child?"],["¿Qué música escuchabas hace cinco años?","Escuchaba…","¿Por qué te gustaba?","What music did you listen to five years ago?"],["¿Cómo era un día normal en tu escuela?","Primero…, después…","¿Qué parte era mejor?","What was a normal school day like?"],["¿Qué estabas haciendo cuando recibiste una noticia importante?","Estaba… cuando…","¿Cómo reaccionaste?","What were you doing when you received important news?"],["¿Qué costumbre tenías y ya no tenés?","Antes…","¿Por qué cambió?","What habit did you have that you no longer have?"]]),
    regional:["Las formas del imperfecto son estables en todas las variedades.","Used to y would pueden traducir hábitos en inglés, pero no cubren todos los usos.","Vos no cambia las formas del imperfecto: vos hablabas, comías, vivías."],
  },
  {
    id:144,slug:"futuro-simple-indicativo",title:"Futuro simple de indicativo",shortTitle:"Futuro simple",level:"A2",mood:"Indicativo",tense:"Futuro simple",plane:"Futuro",status:"Productivo",compound:false,bilingual:true,curriculumOrder:1440,requires:[140],accent:"#f2b63f",
    question:"¿Qué ocurrirá o qué suponemos que ocurre?",questionEn:"What will happen, or what do we suppose is happening?",core:"Proyecta una acción y también permite formular predicciones, promesas o conjeturas.",coreEn:"It projects an action and can also express predictions, promises or guesses.",formula:"INFINITIVO + -É / -ÁS / -Á / -EMOS / -ÁN",
    formation:["Conservá el infinitivo completo.","Agregá las mismas terminaciones a -ar, -er e -ir.","Aprendé raíces irregulares: tendr-, podr-, dir-, har-, saldr-."],formationEn:["Keep the full infinitive.","Add the same endings to -ar, -er and -ir verbs.","Learn irregular stems: tendr-, podr-, dir-, har-, saldr-."],
    uses:[{title:"Predicción",titleEn:"Prediction",explanation:"Anticipa un resultado.",explanationEn:"It anticipates an outcome.",example:{es:"Mañana lloverá.",en:"It will rain tomorrow."}},{title:"Promesa",titleEn:"Promise",explanation:"Compromete al hablante.",explanationEn:"It commits the speaker.",example:{es:"Te llamaré esta noche.",en:"I'll call you tonight."}},{title:"Conjetura",titleEn:"Guess",explanation:"Calcula algo sobre el presente.",explanationEn:"It makes a guess about the present.",example:{es:"¿Dónde estará Ana?",en:"I wonder where Ana is."}},{title:"Resultado previsto",titleEn:"Expected result",explanation:"Presenta una consecuencia futura.",explanationEn:"It presents a future consequence.",example:{es:"Con práctica, mejorarás.",en:"With practice, you'll improve."}}],
    examples:[{es:"El año próximo viajaré más.",en:"Next year I will travel more."},{es:"No te olvidaré.",en:"I won't forget you."},{es:"¿Qué harás mañana?",en:"What will you do tomorrow?"},{es:"Serán las cinco.",en:"It must be about five."},{es:"Tendremos tiempo.",en:"We will have time."},{es:"Algún día vivirán aquí.",en:"One day they will live here."}],
    contrast:[{left:"Mañana voy a estudiar.",right:"Algún día estudiaré japonés.",why:"Ir a destaca plan o intención; el futuro simple funciona muy bien para predicción o proyección.",whyEn:"Ir a highlights a plan or intention; the simple future works well for prediction or projection."},{left:"Ana está en casa.",right:"Ana estará en casa.",why:"La segunda puede ser una conjetura sobre el presente.",whyEn:"The second sentence can be a guess about the present."}],
    practice:[{prompt:"Algún día ___ una casa.",options:["compraré","compraba","haya comprado"],answer:0,why:"La proyección futura usa compraré.",whyEn:"The future projection uses compraré."},{prompt:"La raíz futura de tener es…",options:["tendr-","ten-","tuv-"],answer:0,why:"Tener forma tendré.",whyEn:"Tener uses the future stem tendr-."},{prompt:"No sé dónde está; ___ trabajando.",options:["estará","estuvo ayer","estuviera"],answer:0,why:"El futuro expresa conjetura presente.",whyEn:"The future form expresses a guess about the present."},{prompt:"Nosotros ___ la verdad.",options:["diremos","deciremos","dijimos mañana"],answer:0,why:"Decir usa la raíz dir-.",whyEn:"Decir uses the irregular future stem dir-."},{prompt:"Te prometo que ___.",options:["volveré","volvía","haya vuelto"],answer:0,why:"La promesa admite futuro simple.",whyEn:"A promise naturally allows the simple future."}],
    transform:[{prompt:"Convertí el plan en predicción: Va a llover.",answer:"Lloverá.",why:"El futuro presenta la predicción directamente."},{prompt:"Expresá conjetura: Probablemente Ana está en casa.",answer:"Ana estará en casa.",why:"El futuro puede calcular una situación presente."},{prompt:"Negá la promesa: Volveré tarde.",answer:"No volveré tarde.",why:"No precede al verbo en futuro."}],
    conversation:conversations([["¿Cómo será tu vida dentro de cinco años?","Dentro de cinco años…","¿Qué podría cambiar ese plan?","What will your life be like in five years?"],["¿Qué tecnología cambiará más nuestra vida?","Creo que… cambiará…","¿Qué problema traerá?","Which technology will change our lives the most?"],["¿Cómo será tu ciudad en el futuro?","Mi ciudad será…","¿Qué seguirá igual?","What will your city be like in the future?"],["¿Qué harás el próximo fin de semana?","El próximo fin de semana…","¿Es plan o predicción?","What will you do next weekend?"],["¿Qué aprenderás durante el próximo año?","Aprenderé…","¿Cómo lo harás?","What will you learn next year?"],["¿Qué profesión desaparecerá o cambiará?","Creo que…","¿Por qué?","Which job will disappear or change?"],["¿Dónde estará una persona de tu familia ahora?","Estará…","¿Qué te hace pensar eso?","Where might a family member be right now?"],["¿Qué promesa podés hacer para esta semana?","Esta semana…","¿Cómo vas a cumplirla?","What promise can you make for this week?"]]),
    regional:["En conversación, ir a + infinitivo suele competir con el futuro simple.","El futuro de conjetura es frecuente en muchas variedades.","Las terminaciones son iguales con tú y vos: hablarás."],
  },
  {
    id:145,slug:"imperativo",title:"Imperativo afirmativo y negativo",shortTitle:"Imperativo",level:"A2",mood:"Imperativo",tense:"Sin serie temporal",plane:"Sin oposición temporal",status:"Productivo",compound:false,bilingual:true,curriculumOrder:1450,requires:[140],accent:"#ec4f6b",
    question:"¿Cómo dirigimos una acción?",questionEn:"How do we direct someone to act?",core:"El imperativo sirve para pedir, invitar, aconsejar, indicar, advertir u ordenar. No tiene una serie de tiempos propia.",coreEn:"The imperative is used to request, invite, advise, instruct, warn or order. It does not have its own tense series.",formula:"AFIRMATIVO: VEN / VENÍ / VENGA · NEGATIVO: NO + PRESENTE DE SUBJUNTIVO",
    formation:["Elegí la persona y la variedad: tú, vos, usted, ustedes o vosotros.","Para negativas, usá presente de subjuntivo.","En afirmativo, uní los pronombres: decime; en negativo, ponelos antes: no me digas."],formationEn:["Choose the person and variety: tú, vos, usted, ustedes or vosotros.","Use the present subjunctive for negative commands.","Attach pronouns to affirmative commands; place them before negative commands."],
    uses:[{title:"Pedido",titleEn:"Request",explanation:"Dirige la acción con cortesía contextual.",explanationEn:"It directs the action with contextual politeness.",example:{es:"Pasame la sal, por favor.",en:"Pass me the salt, please."}},{title:"Instrucción",titleEn:"Instruction",explanation:"Organiza pasos.",explanationEn:"It organises steps.",example:{es:"Abrí el archivo y elegí una opción.",en:"Open the file and choose an option."}},{title:"Consejo",titleEn:"Advice",explanation:"Propone una acción útil.",explanationEn:"It suggests a useful action.",example:{es:"Descansá un poco.",en:"Get some rest."}},{title:"Prohibición",titleEn:"Prohibition",explanation:"Evita o frena una acción.",explanationEn:"It prevents or stops an action.",example:{es:"No toques eso.",en:"Don't touch that."}}],
    examples:[{es:"Vení conmigo.",en:"Come with me."},{es:"Ven conmigo.",en:"Come with me."},{es:"No vengas tarde.",en:"Don't come late."},{es:"Dígame su nombre.",en:"Tell me your name."},{es:"Siéntense, por favor.",en:"Please sit down."},{es:"Contámelo después.",en:"Tell me about it later."}],
    contrast:[{left:"Decime la verdad.",right:"No me digas eso.",why:"Afirmativo: pronombre unido; negativo: pronombre delante.",whyEn:"Affirmative: attached pronoun; negative: pronoun before the verb."},{left:"Vení. / Ven.",right:"Venga.",why:"Vos/tú son cercanos; usted construye distancia o cortesía.",whyEn:"Vos and tú are familiar; usted adds distance or politeness."}],
    practice:[{prompt:"Mandato negativo con tú: ___ tarde.",options:["No llegues","No llega","No llegar"],answer:0,why:"La negativa usa presente de subjuntivo.",whyEn:"The negative command uses the present subjunctive."},{prompt:"Imperativo afirmativo con vos de hablar…",options:["hablá","hable","hablas"],answer:0,why:"El voseo afirmativo lleva acento final.",whyEn:"The affirmative vos command has final stress."},{prompt:"Pronombres en afirmativo…",options:["Decímelo","Me lo decí","No decímelo"],answer:0,why:"Se unen al final del imperativo afirmativo.",whyEn:"Pronouns attach to the end of an affirmative command."},{prompt:"Pedido formal a usted…",options:["Pase, por favor","Pasá, por favor","Pasas"],answer:0,why:"Pase corresponde a usted.",whyEn:"Pase is the usted form."},{prompt:"Negativa con ustedes…",options:["No entren","No entran","No entrar"],answer:0,why:"No entren usa subjuntivo con ustedes.",whyEn:"No entren uses the subjunctive form for ustedes."}],
    transform:[{prompt:"Hacé negativa: Abrí la puerta.",answer:"No abras la puerta.",why:"La negativa cambia a presente de subjuntivo."},{prompt:"Agregá los pronombres: Contá + me + lo.",answer:"Contámelo.",why:"En afirmativo se posponen y se unen."},{prompt:"Pasá de vos a usted: Esperá aquí.",answer:"Espere aquí.",why:"Usted usa la forma de subjuntivo."}],
    conversation:conversations([["Dale tres instrucciones al profesor para preparar un mate o té.","Primero…, después…","¿Qué no debe hacer?","Give the teacher three instructions to make mate or tea."],["¿Qué consejo le darías a alguien que visita tu ciudad?","Visitá / Visita…","¿Qué debería evitar?","What advice would you give someone visiting your city?"],["Pedile al profesor que haga tres cosas sencillas.","Por favor…","Ahora hacé los pedidos más formales.","Ask the teacher to do three simple things."],["¿Qué reglas hay en tu casa?","No… / Por favor…","¿Cuál es la más importante?","What rules are there in your home?"],["Explicá cómo llegar a un lugar cercano.","Seguí…, doblá…","¿Qué referencia visual ayuda?","Explain how to get to a nearby place."],["¿Qué le dirías a una persona que está muy estresada?","Descansá…","¿Qué no debería hacer?","What would you say to someone who is very stressed?"],["Creá cinco instrucciones para una clase online.","Abrí…, escribí…","¿Cuáles necesitan por favor?","Create five instructions for an online class."],["Invitá al profesor a hacer un plan y negociá la hora.","Vení / Venga…","¿Qué alternativa ofrecés?","Invite the teacher to do something and negotiate the time."]]),
    regional:["Vos: hablá, comé, viví; tú: habla, come, vive.","Vosotros: hablad; ustedes: hablen.","Las negativas usan subjuntivo en todas las variedades: no hables, no hablés, no hablen."],
  },
  {
    id:146,slug:"condicional-simple-indicativo",title:"Condicional simple de indicativo",shortTitle:"Condicional simple",level:"B1",mood:"Indicativo",tense:"Condicional simple",plane:"Condicional",status:"Productivo",compound:false,bilingual:false,curriculumOrder:1810,requires:[144],accent:"#cf7d2f",
    question:"¿Qué ocurriría bajo una condición o desde una perspectiva pasada?",core:"Presenta una consecuencia hipotética, un futuro visto desde el pasado, una conjetura pasada o una petición atenuada.",formula:"INFINITIVO + -ÍA / -ÍAS / -ÍA / -ÍAMOS / -ÍAN",
    formation:["Conservá el infinitivo y agregá las terminaciones.","Usá las mismas raíces irregulares del futuro: tendr-, podr-, har-.","No lo conviertas en un cuarto modo: pertenece al indicativo."],
    uses:[{title:"Consecuencia hipotética",explanation:"Depende de una condición.",example:{es:"Si tuviera tiempo, viajaría."}},{title:"Futuro desde el pasado",explanation:"Proyecta desde un punto pasado.",example:{es:"Dijo que llegaría tarde."}},{title:"Petición atenuada",explanation:"Reduce la imposición.",example:{es:"¿Podrías ayudarme?"}},{title:"Conjetura pasada",explanation:"Calcula una situación anterior.",example:{es:"Serían las diez cuando salió."}}],
    examples:[{es:"Me gustaría vivir cerca del mar."},{es:"Yo no haría eso."},{es:"Prometió que volvería."},{es:"¿Qué cambiarías?"},{es:"Tendríamos más tiempo."},{es:"En tu lugar, hablaría con ella."}],
    contrast:[{left:"Viajaré el año próximo.",right:"Dijo que viajaría al año siguiente.",why:"Futuro desde ahora frente a futuro desde un pasado."},{left:"Si tengo tiempo, voy.",right:"Si tuviera tiempo, iría.",why:"Condición posible frente a hipótesis más distante."}],
    practice:[{prompt:"Si pudiera elegir, ___ cerca del mar.",options:["viviría","viviré ayer","viva"],answer:0,why:"La consecuencia hipotética usa condicional."},{prompt:"Dijo que ___ después.",options:["llamaría","llamará desde ayer","llamara siempre"],answer:0,why:"Es futuro desde el pasado."},{prompt:"La raíz de poder es…",options:["podr-","poder-","pud-"],answer:0,why:"Forma podría."},{prompt:"Petición atenuada…",options:["¿Podrías cerrar la puerta?","Cerraste la puerta.","Cierres la puerta."],answer:0,why:"El condicional reduce la imposición."},{prompt:"Serían las ocho expresa…",options:["conjetura pasada","orden","hecho presente seguro"],answer:0,why:"Calcula aproximadamente una hora pasada."}],
    transform:[{prompt:"Pasá al futuro desde el pasado: Dice que vendrá → dijo.",answer:"Dijo que vendría.",why:"La referencia cambia al pasado."},{prompt:"Atenuá: Ayudame.",answer:"¿Podrías ayudarme?",why:"El condicional convierte la orden en pedido."},{prompt:"Completá la hipótesis: Si tuviera un mes libre…",answer:"Si tuviera un mes libre, viajaría.",why:"La consecuencia va en condicional simple."}],
    conversation:conversations([["¿Qué harías con un mes completamente libre?","Yo…","¿Qué sería lo primero?"],["¿Dónde vivirías si pudieras elegir cualquier lugar?","Viviría…","¿Qué perderías al mudarte?"],["¿Qué cambiarías de tu ciudad?","Cambiaría…","¿Quién debería hacerlo?"],["¿Qué trabajo nunca aceptarías?","Nunca trabajaría…","¿Ni siquiera por mucho dinero?"],["¿Qué le recomendarías a tu yo de hace cinco años?","Le diría…","¿Lo habría escuchado?"],["¿Cómo sería tu casa ideal?","Tendría…","¿Qué detalle es imprescindible?"],["¿Qué compra cara valdría la pena para vos?","Compraría…","¿En qué condiciones?"],["¿Qué pregunta cortés harías en un hotel?","¿Podría / Podrías…?","Hacela más directa y compará el tono."]]),
    regional:["Condicional simple es la clasificación académica actual dentro del indicativo.","Debería, podría y querría atenúan pedidos en todo el mundo hispánico.","En el habla informal, algunas variedades alternan con imperfecto: Yo que vos, no iba."],
  },
  {
    id:147,slug:"preterito-pluscuamperfecto-indicativo",title:"Pretérito pluscuamperfecto de indicativo",shortTitle:"Pluscuamperfecto",level:"B1",mood:"Indicativo",tense:"Pretérito pluscuamperfecto",plane:"Pasado",status:"Productivo",compound:true,bilingual:false,curriculumOrder:1820,requires:[143],accent:"#586ec9",
    question:"¿Qué ya había ocurrido antes de otro momento pasado?",core:"Ordena dos planos del pasado y marca cuál ocurrió primero.",formula:"IMPERFECTO DE HABER + PARTICIPIO · HABÍA / HABÍAS / HABÍAMOS / HABÍAN + PARTICIPIO",
    formation:["Conjugá haber en imperfecto.","Agregá el participio invariable.","Buscá el segundo punto pasado que funciona como referencia."],
    uses:[{title:"Anterioridad pasada",explanation:"Una acción termina antes de otra pasada.",example:{es:"Cuando llegué, Ana ya había salido."}},{title:"Explicación",explanation:"Aporta la causa anterior.",example:{es:"Estaba cansado porque no había dormido."}},{title:"Experiencia hasta entonces",explanation:"Mira lo vivido antes de un punto pasado.",example:{es:"Nunca había visto el mar."}},{title:"Descubrimiento",explanation:"Revela un antecedente.",example:{es:"Descubrí que habían cambiado la reserva."}}],
    examples:[{es:"Ya había comido cuando llamaste."},{es:"No habíamos reservado."},{es:"¿Habías estado allí antes?"},{es:"Habían cerrado la puerta."},{es:"Hasta ese día nunca lo había pensado."},{es:"Me explicó que había perdido el tren."}],
    contrast:[{left:"Llegué y salió.",right:"Cuando llegué, ya había salido.",why:"En la segunda, la salida es anterior a mi llegada."},{left:"He perdido las llaves.",right:"Había perdido las llaves antes de salir.",why:"Referencia actual frente a referencia pasada."}],
    practice:[{prompt:"Cuando llegamos, la película ya ___.",options:["había empezado","empezará","haya empezado"],answer:0,why:"Empezó antes de nuestra llegada."},{prompt:"Nosotros no ___ mesa.",options:["habíamos reservado","hemos reservar","reservaríamos antes"],answer:0,why:"Habíamos + participio."},{prompt:"El participio con haber…",options:["queda invariable","concuerda siempre","va antes del auxiliar"],answer:0,why:"Decimos habían llegado, no habían llegados."},{prompt:"Estaba enfermo porque no ___.",options:["había descansado","descansará","descanse"],answer:0,why:"La causa es anterior al estado pasado."},{prompt:"¿___ ese lugar antes del viaje?",options:["Habías visitado","Has visitar","Visitaras"],answer:0,why:"Antes del viaje crea una referencia pasada."}],
    transform:[{prompt:"Marcá anterioridad: Ana salió. Después llegué.",answer:"Cuando llegué, Ana ya había salido.",why:"El pluscuamperfecto identifica el primer evento."},{prompt:"Explicá la causa: Estaba cansado / no dormir.",answer:"Estaba cansado porque no había dormido.",why:"La falta de sueño es anterior."},{prompt:"Negá: Habían terminado.",answer:"No habían terminado.",why:"No precede al auxiliar."}],
    conversation:conversations([["¿Qué nunca habías hecho antes de tu último viaje?","Antes de ese viaje nunca había…","¿Cómo resultó?"],["Contá una ocasión en que llegaste y algo ya había ocurrido.","Cuando llegué…","¿Cómo reaccionaste?"],["¿Qué habías preparado antes de una decisión importante?","Antes de decidir…","¿Fue suficiente?"],["¿Qué expectativa tenías que después cambió?","Había pensado que…","¿Qué descubriste?"],["¿Alguna vez olvidaste algo que ya habías prometido?","Había prometido…","¿Cómo lo resolviste?"],["¿Qué habías aprendido antes de empezar tu trabajo actual?","Ya había aprendido…","¿Qué aprendiste después?"],["¿Qué lugar conociste después de haber oído mucho sobre él?","Había oído…","¿Coincidió con tu imagen?"],["¿Qué error se habría evitado si alguien hubiera comprobado algo antes?","Ya habían / no habían…","¿Quién era responsable?"]]),
    regional:["Ya, todavía no, antes y hasta entonces ayudan a hacer visible la anterioridad.","Había + participio es común en todas las variedades.","No debe confundirse con hubiera + participio, que pertenece al subjuntivo."],
  },
  {
    id:148,slug:"presente-de-subjuntivo",title:"Presente de subjuntivo",shortTitle:"Presente",level:"B1",mood:"Subjuntivo",tense:"Presente",plane:"Presente",status:"Productivo",compound:false,bilingual:false,curriculumOrder:2010,requires:[107,140],accent:"#7d55c7",
    question:"¿La acción se afirma o aparece filtrada por otra perspectiva?",core:"No afirma la acción como mensaje independiente: la integra en deseos, valoración, duda, finalidad, negación, búsqueda o futuro pendiente.",formula:"YO DEL PRESENTE → QUITO -O → TERMINACIONES OPUESTAS",
    formation:["Partí de la forma yo: tengo, digo, conozco.","Quitá -o: teng-, dig-, conozc-.","Agregá e para -ar y a para -er/-ir, con sus terminaciones."],
    uses:[{title:"Deseo e influencia",explanation:"Una persona proyecta una acción sobre otra.",example:{es:"Quiero que vengas."}},{title:"Valoración",explanation:"La acción se filtra mediante una reacción.",example:{es:"Me alegra que estés aquí."}},{title:"Finalidad",explanation:"La acción funciona como objetivo.",example:{es:"Te llamo para que me ayudes."}},{title:"Futuro pendiente",explanation:"Después de cuando, en cuanto o hasta que.",example:{es:"Cuando llegues, avisame."}}],
    examples:[{es:"Es importante que descanses."},{es:"No creo que sea fácil."},{es:"Busco una casa que tenga jardín."},{es:"Aunque llueva, voy."},{es:"Ojalá podamos ir."},{es:"Quiero hablar antes de que salgas."}],
    contrast:[{left:"Sé que viene.",right:"Dudo que venga.",why:"Afirmación frente a información filtrada por duda."},{left:"Cuando llega, llama.",right:"Cuando llegue, llamará.",why:"Hábito afirmado frente a futuro pendiente."}],
    practice:[{prompt:"Quiero que vos ___.",options:["vengas","venís","vendrás"],answer:0,why:"Querer que con sujetos distintos selecciona subjuntivo."},{prompt:"No creo que ___ fácil.",options:["sea","es siempre","será seguro"],answer:0,why:"La negación de la creencia filtra la afirmación."},{prompt:"Te llamo para que me ___.",options:["ayudes","ayudás","ayudaste"],answer:0,why:"Para que expresa finalidad."},{prompt:"Cuando ___ mañana, avisame.",options:["llegues","llegás siempre","llegaste"],answer:0,why:"La llegada futura está pendiente."},{prompt:"Busco un libro que ___ ejemplos.",options:["tenga","tiene identificado","tuvo ayer"],answer:0,why:"El referente buscado no está identificado."}],
    transform:[{prompt:"Filtrá con duda: Viene mañana.",answer:"Dudo que venga mañana.",why:"La duda selecciona subjuntivo."},{prompt:"Convertí en finalidad: Te lo explico / entender mejor.",answer:"Te lo explico para que entiendas mejor.",why:"Para que introduce el objetivo."},{prompt:"Hacé futura la relación: Cuando llega, me llama.",answer:"Cuando llegue, me llamará.",why:"El futuro pendiente usa subjuntivo."}],
    conversation:conversations([["¿Qué querés que cambie en tu ciudad?","Quiero que…","¿Quién podría cambiarlo?"],["¿Qué te alegra que exista en tu vida?","Me alegra que…","¿Cómo te ayuda?"],["¿Qué dudás que ocurra este año?","Dudo que…","¿Qué podría hacerlo posible?"],["¿Qué buscás en una persona con la que trabajás?","Busco a alguien que…","¿Qué cualidad es indispensable?"],["¿Qué hacés para que tu semana funcione mejor?","… para que…","¿Siempre funciona?"],["¿Qué vas a hacer cuando termine esta semana?","Cuando termine…","¿Con quién?"],["¿Qué recomendás que haga una persona que aprende español?","Recomiendo que…","¿Qué debería evitar?"],["¿Qué situación te parece increíble que todavía exista?","Me parece increíble que…","¿Por qué continúa?"]]),
    regional:["El presente puede referirse al futuro: Espero que venga mañana.","El voseo subjuntivo alterna: que vengas / que vengás, según región y registro.","No todo que exige subjuntivo: importa la perspectiva y la estructura."],
  },
  {
    id:149,slug:"preterito-perfecto-subjuntivo",title:"Pretérito perfecto de subjuntivo",shortTitle:"Perfecto",level:"B1",mood:"Subjuntivo",tense:"Pretérito perfecto",plane:"Pasado",status:"Productivo",compound:true,bilingual:false,curriculumOrder:2020,requires:[148,141],accent:"#8a5bd8",
    question:"¿La acción filtrada ya ocurrió antes de una reacción actual?",core:"Combina subjuntivo y anterioridad: el hablante reacciona ahora ante una acción ya completada o posible.",formula:"PRESENTE DE SUBJUNTIVO DE HABER + PARTICIPIO · HAYA / HAYAS / HAYAMOS / HAYAN",
    formation:["Conjugá haber en presente de subjuntivo.","Agregá el participio invariable.","Mantené el disparador actual y marcá que la subordinada es anterior."],
    uses:[{title:"Reacción actual",explanation:"Valoración presente de un hecho anterior.",example:{es:"Me alegra que hayas venido."}},{title:"Duda sobre resultado",explanation:"No se afirma la acción terminada.",example:{es:"Dudo que hayan entendido."}},{title:"Posibilidad completada",explanation:"Evalúa un resultado posible.",example:{es:"Es posible que se haya perdido."}},{title:"Futuro anterior",explanation:"Acción terminada antes de otra futura.",example:{es:"Cuando hayas terminado, avisame."}}],
    examples:[{es:"No creo que haya llegado."},{es:"Es una pena que se hayan ido."},{es:"Puede que haya olvidado la cita."},{es:"Espero que hayas descansado."},{es:"Busco a alguien que haya trabajado aquí."},{es:"Después de que hayas leído esto, hablamos."}],
    contrast:[{left:"Me alegra que vengas.",right:"Me alegra que hayas venido.",why:"Acción simultánea o futura frente a acción ya completada."},{left:"Sé que ha llegado.",right:"Dudo que haya llegado.",why:"Perfecto de indicativo afirmado frente a perfecto de subjuntivo filtrado."}],
    practice:[{prompt:"Me alegra que ___.",options:["hayas venido","has venido","habías venido"],answer:0,why:"Reacción presente + acción anterior."},{prompt:"Dudo que ellos ___.",options:["hayan entendido","han entendido afirmado","entenderían"],answer:0,why:"La duda selecciona haya(n)."},{prompt:"El participio…",options:["queda invariable","concuerda con el sujeto","se conjuga"],answer:0,why:"Decimos hayan llegado."},{prompt:"Cuando ___, salimos.",options:["hayas terminado","terminaste ayer","habrías"],answer:0,why:"Acción futura completada antes de salir."},{prompt:"Es posible que se ___.",options:["haya perdido","ha perdió","habría perder"],answer:0,why:"Haya + participio."}],
    transform:[{prompt:"Marcá anterioridad: Me alegra que venís.",answer:"Me alegra que hayas venido.",why:"La llegada ya ocurrió."},{prompt:"Pasá de certeza a duda: Ha salido.",answer:"Dudo que haya salido.",why:"El auxiliar cambia al subjuntivo."},{prompt:"Construí futuro anterior: terminar / llamarme.",answer:"Cuando hayas terminado, llamame.",why:"La terminación precede a la llamada futura."}],
    conversation:conversations([["¿Qué te alegra que haya pasado este año?","Me alegra que haya…","¿Qué consecuencia tuvo?"],["¿Qué dudás que la gente haya entendido bien?","Dudo que hayan…","¿Por qué es difícil?"],["¿Qué película esperás que el profesor haya visto?","Espero que hayas visto…","¿Por qué la elegiste?"],["¿Qué cambio te sorprende que haya ocurrido tan rápido?","Me sorprende que…","¿Qué lo aceleró?"],["¿Qué lugar buscás que haya conservado su identidad?","Busco un lugar que haya…","¿Conocés alguno?"],["¿Qué te molesta que alguien haya hecho recientemente?","Me molesta que…","¿Lo hablaste?"],["¿Qué harás cuando hayas terminado tus tareas de esta semana?","Cuando haya terminado…","¿Cuándo será?"],["¿Qué noticia puede que haya pasado desapercibida?","Puede que haya…","¿Por qué importa?"]]),
    regional:["Haya + participio es estable en todo el mundo hispánico.","En habla informal puede alternar con presente si la anterioridad no importa.","No uses ha donde la estructura exige subjuntivo: dudo que haya, no dudo que ha."],
  },
  {
    id:150,slug:"preterito-imperfecto-subjuntivo",title:"Pretérito imperfecto de subjuntivo",shortTitle:"Imperfecto",level:"B2",mood:"Subjuntivo",tense:"Pretérito imperfecto",plane:"Pasado",status:"Productivo",compound:false,bilingual:false,curriculumOrder:2310,requires:[148,146],accent:"#6e4bb6",
    question:"¿La acción depende de un pasado, una hipótesis o una distancia discursiva?",core:"Presenta la acción desde un marco pasado o hipotético. Las formas en -ra y -se son variantes del mismo tiempo.",formula:"ELLOS DEL INDEFINIDO − RON + -RA/-SE · HABLARON → HABLARA/HABLASE",
    formation:["Tomá ellos del indefinido.","Quitá -ron.","Agregá las terminaciones de -ra o -se; tildá nosotros: habláramos."],
    uses:[{title:"Concordancia pasada",explanation:"Depende de un verbo principal pasado.",example:{es:"Quería que vinieras."}},{title:"Hipótesis",explanation:"Distancia una condición del presente.",example:{es:"Si tuviera tiempo, viajaría."}},{title:"Deseo difícil",explanation:"Ojalá presenta distancia o baja probabilidad.",example:{es:"Ojalá fuera más fácil."}},{title:"Cortesía",explanation:"Atenúa deseos o pedidos.",example:{es:"Quisiera hacer una pregunta."}}],
    examples:[{es:"Me pidió que esperara."},{es:"Si supieras la verdad, cambiarías de opinión."},{es:"Era importante que todos participaran."},{es:"Ojalá no lloviera."},{es:"Buscaba a alguien que pudiera ayudar."},{es:"Como si no pasara nada."}],
    contrast:[{left:"Quiero que vengas.",right:"Quería que vinieras.",why:"El punto de referencia cambia de presente a pasado."},{left:"Si tengo tiempo, voy.",right:"Si tuviera tiempo, iría.",why:"Condición abierta frente a hipótesis distante."}],
    practice:[{prompt:"Quería que vos ___.",options:["vinieras","vengas ahora","vendrías en la condición"],answer:0,why:"Principal pasada + subjuntivo."},{prompt:"Si yo ___ más tiempo…",options:["tuviera","tendría en si","tengo ayer"],answer:0,why:"Después de si hipotético usamos imperfecto de subjuntivo."},{prompt:"La base de pudiera viene de…",options:["pudieron","pueden","podrían"],answer:0,why:"Ellos pudieron menos -ron."},{prompt:"Ojalá ___ más fácil.",options:["fuera","sería después de ojalá","es seguro"],answer:0,why:"Deseo difícil o contrario al presente."},{prompt:"-ra y -se son…",options:["variantes del mismo tiempo","modos diferentes","presente y pasado"],answer:0,why:"Tuviera y tuviese pertenecen al mismo tiempo."}],
    transform:[{prompt:"Mové al pasado: Quiero que venga.",answer:"Quería que viniera.",why:"La subordinada se alinea con el marco pasado."},{prompt:"Distanciá la condición: Si tengo dinero, viajo.",answer:"Si tuviera dinero, viajaría.",why:"La hipótesis usa imperfecto + condicional."},{prompt:"Atenuá: Quiero preguntar algo.",answer:"Quisiera preguntar algo.",why:"Quisiera funciona como fórmula cortés."}],
    conversation:conversations([["¿Qué harías si tuvieras seis meses libres?","Si tuviera…","¿Qué condición pondrías?"],["¿Qué querían tus padres que hicieras de niño?","Querían que…","¿Estabas de acuerdo?"],["¿Qué cambiarías si fueras responsable de tu ciudad?","Si fuera…","¿Quién se opondría?"],["¿Qué habilidad ojalá fuera más fácil aprender?","Ojalá fuera…","¿Qué la hace difícil?"],["¿Qué buscabas en tu primer trabajo?","Buscaba un trabajo que…","¿Lo encontraste?"],["¿Qué pedirías si pudieras hablar con una persona poderosa?","Le pediría que…","¿Cómo la convencerías?"],["¿Qué situación resolviste como si tuvieras mucha experiencia?","Actué como si…","¿Qué sentías realmente?"],["¿Qué habría sido distinto si tomaras otra decisión hoy?","Si tomara…","¿Valdría el costo?"]]),
    regional:["Las series en -ra y -se son equivalentes en la mayoría de los usos.","-ra es hoy mucho más frecuente en conversación.","El voseo puede aparecer en la subordinada sin cambiar esta serie: quería que vos vinieras."],
  },
  {
    id:151,slug:"preterito-pluscuamperfecto-subjuntivo",title:"Pretérito pluscuamperfecto de subjuntivo",shortTitle:"Pluscuamperfecto",level:"B2",mood:"Subjuntivo",tense:"Pretérito pluscuamperfecto",plane:"Pasado",status:"Productivo",compound:true,bilingual:false,curriculumOrder:2320,requires:[150,147],accent:"#593b9b",
    question:"¿Imaginamos o valoramos una acción anterior dentro del pasado?",core:"Expresa anterioridad subordinada y construye alternativas sobre un pasado que ya no puede cambiar.",formula:"HUBIERA/HUBIESE + PARTICIPIO",
    formation:["Conjugá haber en imperfecto de subjuntivo.","Agregá el participio invariable.","Decidí si expresa anterioridad pasada o pasado contrario a los hechos."],
    uses:[{title:"Anterioridad subordinada",explanation:"La acción ocurre antes de otra reacción pasada.",example:{es:"Me sorprendió que hubieras venido."}},{title:"Condición irreal pasada",explanation:"Reescribe una causa imposible de cambiar.",example:{es:"Si hubiera sabido, no habría ido."}},{title:"Lamento",explanation:"Ojalá revisa un pasado irreversible.",example:{es:"Ojalá hubiera escuchado."}},{title:"Evaluación contrafactual",explanation:"Valora algo que pudo ser distinto.",example:{es:"Habría sido mejor que avisaras."}}],
    examples:[{es:"Dudaba que hubieran terminado."},{es:"Si hubiéramos salido antes, habríamos llegado."},{es:"No creía que lo hubieses visto."},{es:"Ojalá no hubiera dicho eso."},{es:"Buscaban a alguien que hubiera trabajado allí."},{es:"Me alegró que ya hubieras vuelto."}],
    contrast:[{left:"Dudo que haya salido.",right:"Dudaba que hubiera salido.",why:"Reacción presente frente a marco pasado."},{left:"Si sabía, no iba.",right:"Si hubiera sabido, no habría ido.",why:"Contexto habitual/coloquial frente a contrafactual pasado explícito."}],
    practice:[{prompt:"Si lo ___, te habría llamado.",options:["hubiera sabido","habría sabido después de si","sabía mañana"],answer:0,why:"La condición pasada irreal usa pluscuamperfecto de subjuntivo."},{prompt:"Ojalá no ___.",options:["hubiera ocurrido","habría ocurrido","ha ocurrido seguro"],answer:0,why:"Ojalá + lamento pasado."},{prompt:"El participio…",options:["permanece invariable","concuerda con yo","cambia por persona"],answer:0,why:"Hubiéramos llegado."},{prompt:"Dudaba que ya ___.",options:["hubieran salido","hayan salido desde presente","saldrían seguro"],answer:0,why:"Duda pasada + acción anterior."},{prompt:"Hubiera y hubiese…",options:["son variantes","son tiempos distintos","cambian indicativo/subjuntivo"],answer:0,why:"Son dos series del mismo tiempo."}],
    transform:[{prompt:"Convertí en contrafactual: No sabía, por eso fui.",answer:"Si hubiera sabido, no habría ido.",why:"Reescribe causa y resultado pasados."},{prompt:"Expresá lamento: Dije eso.",answer:"Ojalá no hubiera dicho eso.",why:"El pasado ya no puede modificarse."},{prompt:"Mové al pasado: Dudo que haya llegado.",answer:"Dudaba que hubiera llegado.",why:"Cambia el marco y se conserva la anterioridad."}],
    conversation:conversations([["¿Qué habrías hecho distinto si hubieras tenido más información?","Si hubiera sabido…","¿Qué dato faltaba?"],["¿Qué viaje no habrías hecho de la misma manera?","Si hubiera podido…","¿Qué cambiarías?"],["¿Qué invento habría tardado más si cierta persona no hubiera existido?","Si no hubiera existido…","¿Quién habría ocupado su lugar?"],["¿Qué te hubiera gustado haber aprendido antes?","Ojalá hubiera…","¿Qué habría mejorado?"],["¿Qué problema se habría evitado si alguien hubiera escuchado?","Se habría evitado si…","¿Por qué no escuchó?"],["¿Qué decisión ajena te sorprendió que se hubiera tomado?","Me sorprendió que…","¿Cuál fue la consecuencia?"],["¿Qué película habría terminado mejor si el personaje hubiera actuado distinto?","Si el personaje hubiera…","¿Seguiría siendo buena?"],["¿Qué cambio histórico habría alterado más el presente?","Si… hubiera…","Dame un contraejemplo."]]),
    regional:["Hubiera es más frecuente que hubiese, pero ambas series son normativas.","En algunos registros coloquiales aparece hubiera en ambos miembros: si hubiera sabido, hubiera ido.","La norma cuidada suele contrastar hubiera + habría en el tercer condicional."],
  },
  {
    id:152,slug:"condicional-compuesto-indicativo",title:"Condicional compuesto de indicativo",shortTitle:"Condicional compuesto",level:"B2",mood:"Indicativo",tense:"Condicional compuesto",plane:"Condicional",status:"Productivo",compound:true,bilingual:false,curriculumOrder:2330,requires:[146,151],accent:"#b96c37",
    question:"¿Qué resultado pasado habría ocurrido bajo otras condiciones?",core:"Presenta un resultado posible pero no realizado, una consecuencia deducida o un futuro perfecto visto desde el pasado.",formula:"CONDICIONAL DE HABER + PARTICIPIO · HABRÍA / HABRÍAS / HABRÍAMOS / HABRÍAN",
    formation:["Conjugá haber en condicional.","Agregá el participio invariable.","En una condición pasada, combiná si + hubiera con habría en el resultado."],
    uses:[{title:"Resultado contrafactual",explanation:"Imagina una consecuencia pasada diferente.",example:{es:"Habría ido si hubiera podido."}},{title:"Futuro perfecto desde el pasado",explanation:"Mira una acción terminada desde un punto pasado.",example:{es:"Pensó que para junio habría terminado."}},{title:"Conjetura anterior",explanation:"Calcula un resultado pasado.",example:{es:"Habrían llegado tarde."}},{title:"Reproche atenuado",explanation:"Presenta una alternativa esperable.",example:{es:"Habrías podido avisar."}}],
    examples:[{es:"Sin tu ayuda, no lo habría conseguido."},{es:"Yo habría elegido otra opción."},{es:"¿Qué habrías hecho?"},{es:"Dijo que ya habría salido."},{es:"Habríamos llegado antes."},{es:"No habría sido suficiente."}],
    contrast:[{left:"Iría si pudiera.",right:"Habría ido si hubiera podido.",why:"Hipótesis presente/futura frente a pasado alternativo."},{left:"Habrá terminado para junio.",right:"Dijo que habría terminado para junio.",why:"Referencia actual frente a punto de vista pasado."}],
    practice:[{prompt:"Si hubiera podido, ___.",options:["habría ido","hubiera ido en la principal normativa","iré ayer"],answer:0,why:"Resultado pasado contrafactual."},{prompt:"Nosotros no lo ___.",options:["habríamos sabido","habíamos saber","hayamos sabido"],answer:0,why:"Habríamos + participio."},{prompt:"Pensó que para entonces ___.",options:["habrían terminado","terminarán desde ahora","terminen"],answer:0,why:"Futuro perfecto desde un pasado."},{prompt:"Reproche atenuado…",options:["Habrías podido avisar","Avisaras ayer","Has avisaría"],answer:0,why:"Presenta la alternativa que se esperaba."},{prompt:"El participio en habrían llegado…",options:["no concuerda","concuerda en plural","cambia a llegados"],answer:0,why:"Los tiempos con haber mantienen el participio invariable."}],
    transform:[{prompt:"Pasá al pasado alternativo: Iría si pudiera.",answer:"Habría ido si hubiera podido.",why:"Ambas acciones se desplazan a un pasado imposible."},{prompt:"Atenuá el reproche: Tenías que avisar.",answer:"Habrías podido avisar.",why:"El condicional compuesto suaviza sin borrar la crítica."},{prompt:"Cambiá la perspectiva: Habrá terminado → pensó.",answer:"Pensó que habría terminado.",why:"Se convierte en futuro perfecto desde el pasado."}],
    conversation:conversations([["¿Qué habrías estudiado si no hubieras elegido tu profesión?","Habría estudiado…","¿Por qué no lo hiciste?"],["¿Qué viaje habría resultado distinto con más dinero?","Habría…","¿Realmente habría sido mejor?"],["¿Qué decisión pública habría evitado un problema?","Se habría evitado si…","¿Qué costo habría tenido?"],["¿Qué habrías querido saber hace diez años?","Habría querido saber…","¿Te habría cambiado?"],["¿Qué película habría sido mejor con otro final?","Habría sido…","Proponé el final."],["¿Qué no habrías logrado sin ayuda?","No habría logrado…","¿Quién te ayudó?"],["¿Qué compra no habrías hecho con la información actual?","No habría comprado…","¿Qué señal ignoraste?"],["¿Qué oportunidad habrías aceptado en otras condiciones?","La habría aceptado si…","¿Qué condición faltaba?"]]),
    regional:["Habría + participio es el condicional compuesto del indicativo.","La alternancia coloquial hubiera/habría varía por región y registro.","En escritura cuidada conviene mantener clara la relación entre condición y resultado."],
  },
  {
    id:153,slug:"futuro-compuesto-indicativo",title:"Futuro compuesto de indicativo",shortTitle:"Futuro compuesto",level:"B2",mood:"Indicativo",tense:"Futuro compuesto",plane:"Futuro",status:"Productivo",compound:true,bilingual:false,curriculumOrder:2340,requires:[144,141],accent:"#d29b26",
    question:"¿Qué estará terminado antes de un punto futuro?",core:"Mira desde el futuro hacia una acción anterior y también permite conjeturar sobre un pasado reciente.",formula:"FUTURO DE HABER + PARTICIPIO · HABRÉ / HABRÁS / HABREMOS / HABRÁN",
    formation:["Conjugá haber en futuro.","Agregá el participio invariable.","Fijá el punto futuro o la evidencia desde la que se formula la conjetura."],
    uses:[{title:"Anterioridad futura",explanation:"La acción termina antes de otra referencia futura.",example:{es:"Para junio habré terminado."}},{title:"Balance futuro",explanation:"Mide lo acumulado hasta una fecha.",example:{es:"En diciembre habremos vivido un año aquí."}},{title:"Conjetura pasada",explanation:"Supone qué ocurrió.",example:{es:"Habrá perdido el tren."}},{title:"Resultado esperado",explanation:"Anticipa un estado completado.",example:{es:"Cuando llegues, ya habrán preparado todo."}}],
    examples:[{es:"A esta hora mañana habré llegado."},{es:"Para 2030 habrán cambiado muchas cosas."},{es:"¿Habrá entendido el mensaje?"},{es:"No habremos terminado todavía."},{es:"Ya se habrá enterado."},{es:"Dentro de un mes habrás aprendido mucho."}],
    contrast:[{left:"Terminaré en junio.",right:"Para junio habré terminado.",why:"Momento de finalización frente a resultado ya completado antes del límite."},{left:"Perdió el tren.",right:"Habrá perdido el tren.",why:"Afirmación pasada frente a conjetura sobre el pasado."}],
    practice:[{prompt:"Para mañana ya ___.",options:["habré terminado","terminaría ayer","haya terminado sin marco"],answer:0,why:"Anterioridad respecto de mañana."},{prompt:"No contesta; ___ dormido.",options:["se habrá quedado","se quedará seguro mañana","se hubiera quedado"],answer:0,why:"Conjetura sobre un hecho pasado reciente."},{prompt:"Nosotros ___ un año aquí.",options:["habremos vivido","hemos vivir","viviríamos antes"],answer:0,why:"Habremos + participio."},{prompt:"El participio…",options:["queda invariable","concuerda con nosotros","se vuelve futuro"],answer:0,why:"Habremos vivido."},{prompt:"¿___ el mensaje?",options:["Habrá leído","Haya leer","Habría leyendo"],answer:0,why:"Futuro compuesto de conjetura."}],
    transform:[{prompt:"Destacá el resultado: Terminaré antes de junio.",answer:"Para junio habré terminado.",why:"El límite futuro mira hacia atrás."},{prompt:"Convertí en conjetura: Seguramente perdió el tren.",answer:"Habrá perdido el tren.",why:"El futuro compuesto calcula un pasado."},{prompt:"Negá: Habrán llegado.",answer:"No habrán llegado.",why:"No precede al auxiliar."}],
    conversation:conversations([["¿Qué habrás terminado antes de fin de año?","Para fin de año habré…","¿Qué podría retrasarlo?"],["¿Qué habrá cambiado en tu ciudad dentro de diez años?","Para entonces habrá…","¿Qué seguirá igual?"],["¿Qué habilidad habrás mejorado en seis meses?","Habré mejorado…","¿Cómo medirás el progreso?"],["¿Qué habrá ocurrido si alguien no responde un mensaje importante?","Habrá…","¿Qué otra explicación existe?"],["¿Cuánto habrás viajado al terminar este año?","Habré visitado…","¿Cuál habrá sido el mejor lugar?"],["¿Qué tecnología habrá desaparecido en veinte años?","Habrá desaparecido…","¿Qué la reemplazará?"],["¿Qué problema no habremos resuelto en 2035?","No habremos resuelto…","¿Por qué?"],["¿Qué habrá aprendido la sociedad de una crisis reciente?","Habrá aprendido…","¿Qué evidencia lo mostraría?"]]),
    regional:["El futuro compuesto es menos frecuente que otras alternativas en conversación.","Para + fecha ayuda a interpretar anterioridad futura.","Su valor de conjetura es productivo en distintas variedades."],
  },
  {
    id:154,slug:"preterito-anterior-indicativo",title:"Pretérito anterior de indicativo",shortTitle:"Pretérito anterior",level:"C1",mood:"Indicativo",tense:"Pretérito anterior",plane:"Pasado",status:"Receptivo",compound:true,bilingual:false,curriculumOrder:2610,requires:[147],accent:"#65728a",
    question:"¿Una acción terminó inmediatamente antes de otra en un relato formal?",core:"Es un tiempo compuesto hoy raro. Marca anterioridad inmediata en narración escrita y suele reemplazarse por indefinido o pluscuamperfecto.",formula:"PRETÉRITO PERFECTO SIMPLE DE HABER + PARTICIPIO · HUBE / HUBO / HUBIERON + PARTICIPIO",
    formation:["Reconocé hube, hubiste, hubo, hubimos, hubieron.","Sumá el participio invariable.","Buscá conectores como apenas, cuando, luego que o tan pronto como."],
    uses:[{title:"Anterioridad inmediata",explanation:"La segunda acción sigue casi sin intervalo.",example:{es:"Apenas hubo terminado, salió."}},{title:"Narración formal",explanation:"Aparece en prosa literaria o histórica.",example:{es:"Cuando hubieron firmado, abandonaron la sala."}},{title:"Secuencia cerrada",explanation:"Ambos eventos se presentan completos.",example:{es:"Tan pronto como hubo hablado, comenzó la votación."}},{title:"Efecto estilístico",explanation:"Crea condensación y distancia narrativa.",example:{es:"No bien hubo amanecido, partieron."}}],
    examples:[{es:"Apenas hube llegado, empezó la reunión."},{es:"Cuando hubo concluido, todos callaron."},{es:"Luego que hubieron comido, continuaron el viaje."},{es:"Tan pronto como hubo leído la carta, la quemó."},{es:"No bien hubo salido, llamaron."},{es:"Una vez hubo terminado, entregó el informe."}],
    contrast:[{left:"Cuando terminó, salió.",right:"Cuando hubo terminado, salió.",why:"La segunda subraya la terminación inmediatamente anterior y eleva el registro."},{left:"Ya había terminado cuando salieron.",right:"Apenas hubo terminado, salieron.",why:"Anterioridad de estado frente a secuencia inmediata cerrada."}],
    practice:[{prompt:"Apenas ___, se fue.",options:["hubo terminado","ha terminar","habría terminado"],answer:0,why:"Forma canónica del pretérito anterior."},{prompt:"Su uso actual es principalmente…",options:["receptivo y literario","cotidiano A1","imperativo"],answer:0,why:"Es raro en conversación moderna."},{prompt:"El auxiliar aparece en…",options:["pretérito perfecto simple","presente","futuro"],answer:0,why:"Hubo es indefinido de haber."},{prompt:"Modernizá: cuando hubo llegado…",options:["cuando llegó…","cuando llegare…","cuando haya llegar…"],answer:0,why:"El indefinido suele reemplazarlo."},{prompt:"El participio…",options:["permanece invariable","concuerda","se omite"],answer:0,why:"Hubieron llegado, no llegados."}],
    transform:[{prompt:"Modernizá: Apenas hubo cenado, salió.",answer:"Apenas cenó, salió.",why:"El indefinido conserva la secuencia."},{prompt:"Hacé explícita la anterioridad sin tono literario.",answer:"Ya había cenado cuando salió.",why:"El pluscuamperfecto es productivo hoy."},{prompt:"Dale tono narrativo formal: Terminó y salió inmediatamente.",answer:"Apenas hubo terminado, salió.",why:"El pretérito anterior condensa la secuencia."}],
    conversation:conversations([["¿Qué efecto produce una forma verbal que casi nunca aparece en conversación?","Produce un efecto…","¿Puede ser útil deliberadamente?"],["¿Preferís modernizar textos antiguos o conservar su ritmo?","Prefiero…","¿Qué se pierde al modernizar?"],["¿En qué géneros aceptarías el pretérito anterior?","Lo aceptaría en…","¿Y en una noticia?"],["¿Una forma rara siempre dificulta la comprensión?","No necesariamente…","Dame un ejemplo."],["¿Qué diferencia percibís entre apenas terminó y apenas hubo terminado?","La segunda…","¿Es significado o estilo?"],["¿Las leyes deberían evitar tiempos poco frecuentes?","Creo que…","¿Qué gana la precisión jurídica?"],["¿Qué recursos crean distancia en una narración?","Además del tiempo verbal…","¿Cuándo conviene acercar la voz?"],["Inventá dos frases: una cotidiana y otra deliberadamente solemne.","En versión cotidiana…","¿Cuál elegirías y por qué?"]]),
    regional:["El tiempo es raro en todas las variedades actuales.","Sobrevive sobre todo como recurso escrito y literario.","No debe confundirse hubo terminado con había terminado: no expresan exactamente la misma perspectiva."],
  },
  {
    id:155,slug:"futuro-simple-subjuntivo",title:"Futuro simple de subjuntivo",shortTitle:"Futuro de subjuntivo",level:"C1",mood:"Subjuntivo",tense:"Futuro simple",plane:"Futuro",status:"Histórico / restringido",compound:false,bilingual:false,curriculumOrder:2620,requires:[148,150],accent:"#7b6b42",
    question:"¿Estamos ante una condición futura jurídica, solemne o fosilizada?",core:"Forma en -re hoy restringida. En español corriente suele reemplazarse por presente de subjuntivo.",formula:"ELLOS DEL INDEFINIDO − RON + -RE · HABLARON → HABLARE",
    formation:["Partí de ellos del indefinido.","Quitá -ron.","Agregá -re, -res, -re, -remos, -reis, -ren."],
    uses:[{title:"Lenguaje jurídico",explanation:"Formula condiciones futuras impersonales.",example:{es:"Quien incumpliere será sancionado."}},{title:"Fórmula fija",explanation:"Sobrevive en expresiones heredadas.",example:{es:"Sea lo que fuere."}},{title:"Prosa histórica",explanation:"Marca futuro eventual desde un texto antiguo.",example:{es:"Cuando llegare el mensajero…"}},{title:"Solemnidad deliberada",explanation:"Puede usarse hoy con efecto estilístico.",example:{es:"Donde fueres, haz lo que vieres."}}],
    examples:[{es:"Quien tuviere dudas, pregunte."},{es:"Si alguien infringiere la norma…"},{es:"Cuando fuere necesario…"},{es:"Adonde fueres…"},{es:"Sea cual fuere el resultado…"},{es:"Quienes solicitaren la ayuda…"}],
    contrast:[{left:"Cuando llegue, avisará.",right:"Cuando llegare, avisará.",why:"Uso contemporáneo frente a registro arcaico o jurídico."},{left:"Sea lo que sea.",right:"Sea lo que fuere.",why:"Fórmula actual frente a fórmula solemne heredada."}],
    practice:[{prompt:"Forma moderna de cuando llegare…",options:["cuando llegue","cuando llegará siempre","cuando llegaría"],answer:0,why:"El presente de subjuntivo ocupa hoy ese espacio."},{prompt:"Hablare sin tilde pertenece al…",options:["futuro de subjuntivo","futuro de indicativo","imperativo"],answer:0,why:"Hablaré con tilde es indicativo."},{prompt:"Quien ___ la norma…",options:["incumpliere","incumplirá en cláusula histórica","incumplía"],answer:0,why:"Forma jurídica tradicional."},{prompt:"Su objetivo principal para el alumno es…",options:["reconocer e interpretar","usarlo siempre","reemplazar el presente"],answer:0,why:"El uso productivo es muy limitado."},{prompt:"Base de tuviere…",options:["tuvieron","tienen","tendrían"],answer:0,why:"Ellos tuvieron menos -ron."}],
    transform:[{prompt:"Modernizá: Quien tuviere dudas, pregunte.",answer:"Quien tenga dudas, que pregunte.",why:"El presente de subjuntivo es normal hoy."},{prompt:"Identificá el contraste: hablaré / hablare.",answer:"Hablaré: futuro de indicativo. Hablare: futuro de subjuntivo.",why:"La tilde distingue las formas."},{prompt:"Producí deliberadamente una fórmula solemne.",answer:"Sea cual fuere la decisión, la respetaremos.",why:"La expresión conserva un uso vivo formulístico."}],
    conversation:conversations([["¿Por qué el lenguaje jurídico conserva formas desaparecidas de la conversación?","Puede conservarlas porque…","¿Eso aumenta la precisión?"],["¿Qué problemas crea un contrato que la mayoría no entiende?","Crea…","¿Quién debe simplificarlo?"],["¿Qué fórmulas antiguas sobreviven en tu idioma?","Sobrevive…","¿La gente conoce su origen?"],["¿Cuándo una expresión solemne resulta efectiva?","Resulta efectiva cuando…","¿Cuándo suena ridícula?"],["¿Modernizarías sea lo que fuere?","La mantendría / cambiaría…","¿Qué matiz conserva?"],["¿El lenguaje institucional debería parecerse al cotidiano?","Debería…","¿Qué límite pondrías?"],["¿Una forma rara puede manipular la percepción de autoridad?","Puede…","Dame un caso."],["Creá una regla formal y después explicala en español cotidiano.","Versión formal…","¿Cuál comunica mejor?"]]),
    regional:["Es restringido en todas las variedades modernas.","Tiene mayor visibilidad en textos legales de algunos países.","Las fórmulas fosilizadas pueden aparecer sin que el hablante produzca libremente el tiempo."],
  },
  {
    id:156,slug:"futuro-perfecto-subjuntivo",title:"Futuro perfecto de subjuntivo",shortTitle:"Futuro perfecto",level:"C2",mood:"Subjuntivo",tense:"Futuro perfecto",plane:"Futuro",status:"Histórico / restringido",compound:true,bilingual:false,curriculumOrder:2700,requires:[155,149],accent:"#685d42",
    question:"¿Una condición formal mira una acción ya completada desde el futuro?",core:"Hubiere + participio marca anterioridad futura en registros jurídicos o históricos. En español actual suele sustituirse por haya + participio.",formula:"FUTURO DE SUBJUNTIVO DE HABER + PARTICIPIO · HUBIERE / HUBIEREN + PARTICIPIO",
    formation:["Conjugá haber en futuro de subjuntivo.","Agregá el participio invariable.","Interpretá la condición como completada antes de otra consecuencia futura."],
    uses:[{title:"Condición jurídica anterior",explanation:"La acción debe haberse completado antes de aplicar una consecuencia.",example:{es:"Quien hubiere presentado la solicitud podrá continuar."}},{title:"Texto normativo histórico",explanation:"Define requisitos con máxima formalidad.",example:{es:"Si el acusado hubiere comparecido…"}},{title:"Prosa antigua",explanation:"Ordena anterioridad dentro de un futuro eventual.",example:{es:"Cuando hubiere concluido su viaje…"}},{title:"Efecto de archivo",explanation:"Hoy señala deliberadamente un registro antiguo.",example:{es:"Aquel que hubiere vencido recibirá el premio."}}],
    examples:[{es:"Quien hubiere pagado quedará registrado."},{es:"Si alguno hubiere faltado a la verdad…"},{es:"Cuando hubieren finalizado…"},{es:"Donde se hubiere producido el daño…"},{es:"Una vez hubiere recibido la notificación…"},{es:"Los que hubieren solicitado acceso…"}],
    contrast:[{left:"Quien haya terminado puede salir.",right:"Quien hubiere terminado podrá salir.",why:"Perfecto moderno frente a futuro perfecto formal y restringido."},{left:"Cuando haya llegado, llamará.",right:"Cuando hubiere llegado, llamará.",why:"La segunda crea un registro jurídico o arcaizante."}],
    practice:[{prompt:"Forma moderna de hubiere terminado…",options:["haya terminado","habrá terminado siempre","habría terminado"],answer:0,why:"El perfecto de subjuntivo suele reemplazarlo."},{prompt:"La estructura es…",options:["hubiere + participio","habría + gerundio","haya + infinitivo"],answer:0,why:"Futuro de subjuntivo de haber + participio."},{prompt:"Su uso es…",options:["histórico/restringido","A1 cotidiano","imperativo"],answer:0,why:"Predomina en textos jurídicos e históricos."},{prompt:"El participio…",options:["queda invariable","concuerda","se convierte en infinitivo"],answer:0,why:"Hubieren presentado."},{prompt:"¿Qué relación marca?",options:["anterioridad dentro de un futuro eventual","rutina presente","orden directa"],answer:0,why:"Una condición se completa antes de la consecuencia futura."}],
    transform:[{prompt:"Modernizá: Quien hubiere pagado podrá entrar.",answer:"Quien haya pagado podrá entrar.",why:"El perfecto de subjuntivo es la opción contemporánea."},{prompt:"Explicalo sin tecnicismos.",answer:"La persona que ya pagó podrá entrar.",why:"La paráfrasis conserva la condición anterior."},{prompt:"Compará hubiere / habría.",answer:"Hubiere pertenece al subjuntivo histórico; habría, al condicional del indicativo.",why:"La semejanza formal no implica el mismo modo."}],
    conversation:conversations([["¿La precisión jurídica justifica usar formas que casi nadie produce?","La justifica / no la justifica porque…","¿Qué alternativa propondrías?"],["¿Qué responsabilidad tiene una institución al redactar condiciones?","Tiene que…","¿Precisión y claridad pueden chocar?"],["¿Qué textos deberían ofrecer una versión en lenguaje claro?","Deberían…","¿Quién decide qué se simplifica?"],["¿Una traducción moderna debe conservar el registro antiguo?","Debería…","¿Qué perdería?"],["¿Qué diferencia hay entre comprender una forma y usarla activamente?","Comprender implica…","¿Qué necesita un alumno C2?"],["¿Los arcaísmos pueden dar prestigio artificial?","Pueden…","Dame un ejemplo comparable."],["¿Cómo explicarías hubiere presentado a un alumno B1?","Diría…","¿Qué ejemplo evitarías?"],["Reescribí una regla formal en tres registros.","Formal…, neutro…, cotidiano…","¿Cuál elegirías para un contrato real?"]]),
    regional:["La forma es restringida en todo el español contemporáneo.","Puede aparecer con distinta frecuencia en legislación nacional.","El objetivo pedagógico principal es reconocerla, modernizarla y valorar su efecto."],
  },
];

export const verbalLessons: VerbalLesson[] = verbalLessonSources.map((lesson)=>({
  ...lesson,
  grammaticalTense:lesson.tense,
  temporalPlane:lesson.plane,
  productiveStatus:lesson.status,
  route:`/sistema-verbal/${lesson.slug}`,
  duration:"≈ 45 min",
  regionalVariants:lesson.regional,
  isCompound:lesson.compound,
  isHistoricalOrRestricted:lesson.status!=="Productivo",
}));

export const verbalLessonBySlug = new Map(verbalLessons.map((lesson)=>[lesson.slug,lesson]));

export const verbalLessonSummaries: VerbalLessonSummary[] = verbalLessons.map((lesson)=>({
  id:lesson.id,
  slug:lesson.slug,
  title:lesson.title,
  shortTitle:lesson.shortTitle,
  level:lesson.level,
  levels:lesson.levels,
  mood:lesson.mood,
  tense:lesson.tense,
  plane:lesson.plane,
  status:lesson.status,
  compound:lesson.compound,
  accent:lesson.accent,
  question:lesson.question,
}));
