"use client";

import Link from "next/link";
import {useEffect,useMemo,useState,type CSSProperties} from "react";
import GrammarStep from "../grammar-steps/GrammarStep";
import {SpanishCueBrand} from "../SpanishCueBrand";
import ModeTimeIntro from "./ModeTimeIntro";
import {verbalLessons,type VerbalLesson} from "./lesson-data";
import "./system.css";

type BridgeNote={code:string;name:string;difference:string;equivalence:string;interference:string;example:string};

const bridgeNotes=(lesson:VerbalLesson):BridgeNote[]=>{
  const subj=lesson.mood==="Subjuntivo";
  const past=lesson.plane==="Pasado";
  const imp=lesson.mood==="Imperativo";
  const sample=lesson.examples[0];
  const example=`${sample.es}${sample.en?` · ${sample.en}`:""}`;
  return [
    {code:"EN",name:"INGLÉS",difference:imp?"El inglés usa la base verbal y don’t; el español distingue persona, registro y variedad en la terminación.":subj?"El inglés casi no conserva un subjuntivo morfológico; el español marca la perspectiva en la forma verbal.":past?"Simple past, used to y past continuous reparten funciones que el español organiza mediante diferentes pasados.":"Los auxiliares ingleses y el sujeto obligatorio no coinciden uno a uno con la morfología española.",equivalence:"Usá la traducción inglesa como aproximación al mensaje completo, no como fórmula para elegir el tiempo.",interference:"Evitá copiar do/did, mantener siempre el pronombre sujeto o traducir una forma inglesa palabra por palabra.",example},
    {code:"DE",name:"ALEMÁN",difference:subj?"Konjunktiv y subjuntivo tienen zonas funcionales distintas: discurso referido, cortesía y subordinación no se distribuyen igual.":past?"Perfekt y Präteritum se reparten mucho por registro; el español obliga además a elegir la perspectiva aspectual.":"Persona, modalidad y posición del verbo se organizan de otra manera.",equivalence:"Perfekt, Präteritum o Konjunktiv pueden ofrecer un punto de comparación según el contexto, nunca una equivalencia automática.",interference:"No traslades al español la posición final o segunda del verbo ni la preferencia alemana por un pasado según el registro.",example:sample.es},
    {code:"FR",name:"FRANCÉS",difference:subj?"Aunque existe subjonctif, los disparadores y la concordancia temporal moderna no coinciden siempre.":past?"Passé composé e imparfait son un puente útil, con una distribución regional y discursiva distinta.":"La gran semejanza formal ayuda, pero también produce falsos paralelos de uso.",equivalence:"Compará la intención y el marco temporal antes de asociar dos formas de aspecto parecido.",interference:"Evitá elegir por semejanza gráfica o aplicar al español la frecuencia conversacional de un tiempo francés.",example:sample.es},
    {code:"PT",name:"PORTUGUÉS",difference:subj?"El portugués conserva un futuro de subjuntivo productivo; en español actual es restringido.":past?"Pretérito perfeito e imperfeito se parecen, pero el compuesto español no funciona como tenho falado.":"Las formas próximas no garantizan la misma frecuencia ni el mismo contexto.",equivalence:"La morfología puede servir de puente, pero la elección final depende del contexto español.",interference:"Evitá sobreusar el futuro de subjuntivo o trasladar directamente el perfecto compuesto portugués.",example:sample.es},
    {code:"IT",name:"ITALIANO",difference:subj?"Congiuntivo y subjuntivo comparten funciones, pero el uso conversacional y la selección temporal difieren.":past?"Passato prossimo, remoto e imperfetto ofrecen puentes con distribuciones regionales distintas.":"Las formas semejantes no siempre expresan la misma perspectiva.",equivalence:"Buscá primero la intención comunicativa y después la forma italiana más cercana.",interference:"Evitá extender al español la distribución regional del passato prossimo o del congiuntivo.",example:sample.es},
    {code:"HE",name:"HEBREO MODERNO",difference:subj?"No existe un paradigma morfológico equivalente al subjuntivo español; la perspectiva se expresa con estructuras, partículas y contexto.":imp?"Hay imperativo, futuro y otras estrategias directivas, pero la cortesía no se copia forma por forma.":"Tiempo y aspecto no se alinean exactamente; el presente hebreo tiene origen participial.",equivalence:"Compará el significado de la oración completa y su referencia temporal, no una terminación aislada.",interference:"Evitá asignar un único tiempo español a cada forma hebrea u omitir marcas que el español sí necesita.",example:sample.es},
  ];
};

export default function VerbLessonPage({lesson}:{lesson:VerbalLesson}){
  const [answers,setAnswers]=useState<Record<number,number>>({});
  const [checked,setChecked]=useState(false);
  const [revealed,setRevealed]=useState<Set<number>>(new Set());
  const [active,setActive]=useState("descubrir");
  const index=verbalLessons.findIndex(item=>item.id===lesson.id);
  const previous=index>0?verbalLessons[index-1]:null;
  const next=index<verbalLessons.length-1?verbalLessons[index+1]:null;
  const nav=useMemo(()=>[["descubrir","DESCUBRIR"],["entender","ENTENDER"],["formar","FORMAR"],["usar","USAR"],["contrastar","CONTRASTAR"],["practicar","PRACTICAR"],["transformar","TRANSFORMAR"],["hablar","HABLAR"]],[]);
  useEffect(()=>{const nodes=nav.map(([id])=>document.getElementById(id)).filter(Boolean) as HTMLElement[];const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive(visible.target.id)},{rootMargin:"-18% 0px -68%",threshold:[0,.2,.5]});nodes.forEach(node=>observer.observe(node));return()=>observer.disconnect()},[nav]);
  const go=(id:string)=>document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});
  const score=lesson.practice.reduce((sum,item,i)=>sum+(answers[i]===item.answer?1:0),0);
  return <main className="vt-shell" style={{"--vt-accent":lesson.accent} as CSSProperties}>
    <header className="vt-top"><Link href="/sistema-verbal" aria-label="Volver al sistema verbal">←</Link><SpanishCueBrand variant="compact" tone="light" context="SISTEMA VERBAL"/><div><span>{lesson.level}</span><b>{lesson.mood}</b></div></header>
    <section className="vt-hero"><div className="vt-hero-meta"><span>★ CLASE CANÓNICA · {lesson.status.toUpperCase()}</span><span>{lesson.compound?"TIEMPO COMPUESTO":"FORMA SIMPLE"}</span></div><h1>{lesson.title}</h1><p>{lesson.question}</p>{lesson.questionEn&&<p className="vt-en">{lesson.questionEn}</p>}<div className="vt-position"><span><small>MODO</small><b>{lesson.mood}</b></span><span><small>TIEMPO</small><b>{lesson.tense}</b></span><span><small>PLANO</small><b>{lesson.plane}</b></span><span><small>DURACIÓN</small><b>≈ 45 min</b></span></div></section>
    <nav className="vt-route" aria-label="Etapas de la clase">{nav.map(([id,label],i)=><button key={id} className={active===id?"active":""} aria-current={active===id?"step":undefined} onClick={()=>go(id)}><span>{String(i+1).padStart(2,"0")}</span><b>{label}</b></button>)}</nav>
    <div className="vt-content grammar-step-stack">
      <section id="descubrir" className="vt-anchor"><GrammarStep number="01" eyebrow="DESCUBRIR · 4 MIN" title={lesson.question} description={lesson.questionEn} accent={lesson.accent}><div className="vt-discovery"><span>PENSÁ ANTES DE ABRIR LA REGLA</span><p>{lesson.examples.slice(0,3).map(item=>item.es).join(" · ")}</p>{lesson.bilingual&&<small>Look at the three examples. What changes: the time, the speaker’s perspective or both?</small>}</div></GrammarStep></section>
      <section id="entender" className="vt-anchor"><GrammarStep number="02" eyebrow="ENTENDER · 5 MIN" title="La perspectiva central" description={lesson.bilingual?"The core perspective":"Qué hace esta forma en el discurso"} accent={lesson.accent}><div className="vt-core"><p>{lesson.core}</p>{lesson.coreEn&&<p className="vt-en">{lesson.coreEn}</p>}<div className="vt-formula"><small>FÓRMULA CENTRAL</small><b>{lesson.formula}</b></div><div className={`vt-timeline plane-${lesson.plane.toLowerCase().replaceAll(" ","-").replaceAll("ó","o")}`}><span>PASADO</span><i/><span>AHORA</span><i/><span>FUTURO</span></div></div></GrammarStep></section>
      <section id="formar" className="vt-anchor"><GrammarStep number="03" eyebrow="FORMAR · 6 MIN" title="Construir la forma sin memorizar a ciegas" description={lesson.bilingual?"Build the form step by step":"Patrón, auxiliar y terminaciones"} accent={lesson.accent}><div className="vt-formation">{lesson.formation.map((item,i)=><article key={item}><span>{String(i+1).padStart(2,"0")}</span><p>{item}</p>{lesson.formationEn?.[i]&&<small>{lesson.formationEn[i]}</small>}</article>)}</div><div className="vt-examples">{lesson.examples.map(item=><article key={item.es}><b>{item.es}</b>{item.en&&<span>{item.en}</span>}</article>)}</div></GrammarStep></section>
      <section id="usar" className="vt-anchor"><GrammarStep number="04" eyebrow="USAR · 5 MIN" title="Cuatro intenciones comunicativas" description="La forma cambia de valor según el contexto" accent={lesson.accent}><div className="vt-uses">{lesson.uses.map(use=><article key={use.title}><small>{use.title}</small>{use.titleEn&&<em>{use.titleEn}</em>}<p>{use.explanation}</p>{use.explanationEn&&<span>{use.explanationEn}</span>}<b>{use.example.es}</b>{use.example.en&&<i>{use.example.en}</i>}</article>)}</div></GrammarStep></section>
      <section id="contrastar" className="vt-anchor"><GrammarStep number="05" eyebrow="CONTRASTAR · 4 MIN" title="La decisión que cambia el significado" description="Dos formas cercanas, dos perspectivas" accent={lesson.accent}><div className="vt-contrasts">{lesson.contrast.map(item=><article key={item.left}><div><span>A</span><b>{item.left}</b></div><div><span>B</span><b>{item.right}</b></div><p>{item.why}</p>{item.whyEn&&<small>{item.whyEn}</small>}</article>)}</div></GrammarStep></section>
      <section id="practicar" className="vt-anchor"><GrammarStep number="06" eyebrow="PRACTICAR · 8 MIN" title="Elegir, comprobar y explicar" description={lesson.bilingual?"Choose first; feedback explains the decision":"La corrección muestra la perspectiva"} accent={lesson.accent}><div className="vt-practice">{lesson.practice.map((item,i)=><article className={checked?(answers[i]===item.answer?"correct":"incorrect"):""} key={item.prompt}><span>{String(i+1).padStart(2,"0")}</span><h3>{item.prompt}</h3><div>{item.options.map((option,j)=><button key={option} className={answers[i]===j?"selected":""} onClick={()=>{setAnswers(current=>({...current,[i]:j}));setChecked(false)}}>{option}</button>)}</div>{checked&&<p><b>{answers[i]===item.answer?"CORRECTO":`RESPUESTA · ${item.options[item.answer]}`}</b>{item.why}{item.whyEn&&<small>{item.whyEn}</small>}</p>}</article>)}</div><div className="vt-check"><span>{Object.keys(answers).length}/{lesson.practice.length} respondidas</span><button disabled={Object.keys(answers).length!==lesson.practice.length} onClick={()=>setChecked(true)}>COMPROBAR</button>{checked&&<b>{score}/{lesson.practice.length}</b>}</div></GrammarStep></section>
      <section id="transformar" className="vt-anchor"><GrammarStep number="07" eyebrow="TRANSFORMAR · 4 MIN" title="La misma idea desde otra cámara" description="Reformular sin perder el significado central" accent={lesson.accent}><div className="vt-transform">{lesson.transform.map((item,i)=><article key={item.prompt}><span>{item.prompt}</span><button aria-expanded={revealed.has(i)} onClick={()=>setRevealed(current=>{const next=new Set(current);if(next.has(i))next.delete(i);else next.add(i);return next})}>{revealed.has(i)?"OCULTAR":"VER PROPUESTA"}</button>{revealed.has(i)&&<div><b>{item.answer}</b><p>{item.why}</p></div>}</article>)}</div></GrammarStep></section>
      <section id="hablar" className="vt-anchor"><GrammarStep number="08" eyebrow="HABLAR · 9 MIN" title="Conversación real" description={lesson.bilingual?"Free conversation with optional support":"Argumentar, ejemplificar y repreguntar"} accent={lesson.accent}><div className="vt-speaking-intro"><b>No es un examen oral.</b><p>Usá las ayudas solamente cuando hagan falta. El profesor puede abandonar el orden y seguir la respuesta más interesante.</p>{lesson.bilingual&&<small>This is a real conversation. Starters are optional.</small>}</div><div className="vt-speaking">{lesson.conversation.map((item,i)=><article key={item.question}><span>{String(i+1).padStart(2,"0")}</span><h3>{item.question}</h3>{item.english&&<p className="vt-en">{item.english}</p>}<details><summary>AYUDA OPCIONAL</summary><p><b>STARTER</b> {item.starter}</p><p><b>FOLLOW-UP</b> {item.followUp}</p></details></article>)}</div></GrammarStep></section>
      <GrammarStep number="+" eyebrow="AMPLIACIÓN OPCIONAL" title="Si tu alumno habla…" description="Abrí solamente el idioma que ayude a tu alumno" accent={lesson.accent} defaultOpen={false} kind="optional"><div className="vt-bridges">{bridgeNotes(lesson).map(item=><details key={item.code}><summary><span>{item.code}</span><b>{item.name}</b></summary><dl><div><dt>DIFERENCIA PRINCIPAL</dt><dd>{item.difference}</dd></div><div><dt>EQUIVALENCIA APROXIMADA</dt><dd>{item.equivalence}</dd></div><div><dt>INTERFERENCIA FRECUENTE</dt><dd>{item.interference}</dd></div><div><dt>EJEMPLO ÚTIL</dt><dd>{item.example}</dd></div></dl></details>)}</div></GrammarStep>
      <GrammarStep number="+" eyebrow="VARIACIÓN OPCIONAL" title="España, América y español rioplatense" description="Frecuencia, formas y usos regionales" accent={lesson.accent} defaultOpen={false} kind="optional"><div className="vt-regional">{lesson.regional.map(item=><p key={item}>{item}</p>)}</div></GrammarStep>
      <GrammarStep number="M/T" eyebrow="BASE OPCIONAL" title="Volver a separar modo y tiempo" description="Una referencia rápida si aparece una confusión" accent={lesson.accent} defaultOpen={false} kind="optional"><ModeTimeIntro compact/></GrammarStep>
    </div>
    <footer className="vt-footer"><div>{previous?<Link href={`/sistema-verbal/${previous.slug}`}>← {previous.shortTitle}</Link>:<Link href="/sistema-verbal">← SISTEMA VERBAL</Link>}</div><Link className="vt-all" href="/sistema-verbal">VER LOS 16 TIEMPOS</Link><div>{next?<Link href={`/sistema-verbal/${next.slug}`}>{next.shortTitle} →</Link>:<Link href="/sistema-verbal">VOLVER AL MAPA →</Link>}</div></footer>
  </main>;
}
