import Link from 'next/link';
import { Breadcrumbs, CtaBand, GrowthFooter, GrowthTopbar, JsonLd, LessonGrid, Section } from '../growth/components';
import { GrammarHero } from '../growth/GrammarComponents';
import { grammarMetadata } from '../growth/grammar-metadata';
import { lessonCards } from '../growth/lessons';
import { webPageSchema } from '../growth/schema';
import TeachingProof from '../growth/TeachingProof';
import styles from '../growth/growth.module.css';
import grammar from '../growth/grammar.module.css';
const title='About SpanishCue: Our Teaching Method | SPANISHCUE';
const description='Explore the teaching practice and methodology behind SpanishCue: conversation-first lessons, communicative grammar, CEFR guidance and real student feedback.';
export const metadata=grammarMetadata('/about',title,description);
export default function AboutPage(){return <><main className={styles.page}><div className={styles.shell}>
  <JsonLd data={{...webPageSchema({pathname:'/about',name:title,description,about:['Spanish teaching methodology','Communicative grammar']}),'@type':'AboutPage'}}/>
  <GrowthTopbar current='/about'/><Breadcrumbs items={[{name:'SPANISHCUE',href:'/'},{name:'About and methodology',href:'/about'}]}/>
  <GrammarHero kicker='About SpanishCue' title='Made for the moment a learner has something to say.' intro='SpanishCue is a library of interactive Spanish lessons for teachers and online tutors. It grew out of real online teaching: the need for clear support, useful feedback and activities that lead somewhere in conversation.' previewId={41} primaryHref='#method' primaryLabel='Explore the teaching method'/>
  <Section title='For teachers who want to spend class time teaching' intro='Use SpanishCue in one-to-one tutoring, online classes or small groups of adults. Choose a level and objective, open a lesson in the browser and guide the learner through it. Teachers on Preply, italki or Zoom can use the material while keeping their own teaching approach.'>
    <div className={styles.twoCol}><article className={styles.panel}><h3>Ready to teach</h3><p>Prompts, examples and practice are already organized. Read the objective, check what your learner knows and choose the amount of support they need.</p></article><article className={styles.panel}><h3>Still led by a teacher</h3><p>You decide what to model, when to pause and which error deserves attention. The material supports a lesson; your judgment makes it fit the person in front of you.</p></article></div>
  </Section>
  <Section id='method' title='How the grammar classrooms are designed' intro='A focused lesson moves from understanding a situation to producing a useful message. The current grammar classrooms combine the following stages.'>
    <ol className={grammar.methodSteps}><li><h3>Set a purpose</h3><p>Begin with an accessible situation and a question the learner can respond to with support.</p></li><li><h3>Read and notice</h3><p>Use a contextual text and meaning questions to notice what a grammatical choice does.</p></li><li><h3>Explain and practise</h3><p>Make the form and contrast clear, then use guided tasks with explanations or model answers.</p></li><li><h3>Listen for meaning</h3><p>Use the recorded dialogue or message, comprehension questions and transcript to check understanding.</p></li><li><h3>Make a speaking choice</h3><p>Ask the learner to plan, negotiate, describe or explain, with sentence support and follow-up questions.</p></li><li><h3>Write and revisit</h3><p>Finish with a short written outcome and a focused review of what the learner can now do.</p></li></ol>
  </Section>
  <Section title='Conversation-first does not mean grammar-free'><div className={styles.twoCol}><article className={styles.panel}><h3>A form needs a purpose</h3><p>Use ser and estar to distinguish a description from a live report. Use the past tenses to choose a narrative perspective. Use the subjunctive to negotiate a recommendation. Meaning gives the learner a reason to choose a form.</p><Link className={styles.textLink} href='/spanish-grammar-lessons'>Explore communicative grammar →</Link></article><article className={styles.panel}><h3>Interaction needs a response</h3><p>A task becomes communicative when someone listens, reacts or needs information. Change a detail, ask a follow-up and let the learner repair the message. The goal is a useful exchange alongside more accurate language.</p><Link className={styles.textLink} href='/spanish-conversation-activities'>Explore conversation activities →</Link></article></div></Section>
  <Section id='cefr' title='How we use CEFR levels and the PCIC' intro='CEFR labels help teachers choose a suitable demand. The Plan Curricular del Instituto Cervantes (PCIC) is a curriculum reference for Spanish structures and functions. Neither is a substitute for checking the learner’s actual needs.'>
    <div className={styles.panel}><p>A1 tasks offer short frames and concrete choices. Intermediate tasks connect events, reasons and viewpoints. Advanced tasks ask for precision, reformulation and interpretation. The task and support change with the level; we do not simply replace a label.</p><p>The current grammar classrooms have a focused core level and sometimes a broader reference bank. Our grammar hub makes that distinction visible. C2 grammar coverage is currently a specialized historical-language classroom, not a complete C2 syllabus.</p><p>SpanishCue uses these frameworks as references. It is not affiliated with or endorsed by the Council of Europe or Instituto Cervantes, and the level labels are not an accreditation.</p><nav className={grammar.contextLinks} aria-label='Methodology references'><a href='https://www.coe.int/en/web/common-european-framework-reference-languages/cefr-in-the-classroom' rel='noreferrer'>Council of Europe: CEFR in the classroom</a><a href='https://cvc.cervantes.es/Ensenanza/biblioteca_ele/plan_curricular/indice.htm' rel='noreferrer'>Instituto Cervantes: PCIC</a></nav></div>
  </Section>
  <TeachingProof testimonials/>
  <Section title='A format you can inspect before subscribing' intro='Open a free grammar classroom and try the audio, prompts and teacher-led sequence. Free resources are labeled clearly; PRO previews show you the lesson before you choose access.'><LessonGrid lessons={lessonCards([40,41])}/><nav className={grammar.contextLinks}><Link href='/spanish-teacher-resources'>Teacher resource hub</Link><Link href='/resources'>Full lesson library</Link><Link href='/guides/how-to-teach-spanish-grammar-communicatively'>Communicative grammar guide</Link><Link href='/contact'>Contact SpanishCue</Link></nav></Section>
  <CtaBand title='Choose. Open. Teach.' copy='Start with a free lesson and use your own teaching judgment to make it work for your learner.' primary={{href:'/la-fabrica-de-los-nombres',label:'Try a free grammar lesson'}} secondary={{href:'/pricing',label:'Compare Free and PRO'}}/>
</div></main><GrowthFooter/></>}
