export type Question = { prompt: string; options: string[]; answer: number; feedback: string };
export type Room = {
  id: string; number: string; name: string; symbol: string; color: string;
  title: string; topic: string; speaker: string; voice: string; script: string;
  glossary: { word: string; meaning: string }[]; questions: Question[];
};

export const rooms: Room[] = [
  {
    id: "la-valija", number: "101", name: "La valija flotante", symbol: "🧳", color: "#f7c779",
    title: "Mi equipaje no quería bajar", topic: "Equipaje, objetos y una sorpresa",
    speaker: "Nico · huésped · voz argentina", voice: "es-AR-TomasNeural",
    script: "Anoche llegué al hotel con una mochila y una valija azul. Estaba cansado y quería dormir. Dejé la mochila en una silla, pero la valija empezó a subir hasta el techo. Llamé a recepción y una empleada vino con una escalera. Me preguntó qué llevaba adentro. Le dije que tenía ropa, un libro y un regalo para mi hermana. Sacamos la ropa y el libro, pero la valija seguía arriba. El regalo era un pequeño globo de vidrio con una nube adentro. La empleada abrió el globo y la nube salió por la ventana. Entonces la valija bajó sola. Por suerte, nada se rompió. Esta mañana compré otro regalo: una taza. Mi hermana ama las nubes, pero yo prefiero viajar con los pies en la tierra.",
    glossary: [{ word: "valija", meaning: "suitcase · maleta" }, { word: "techo", meaning: "ceiling · parte superior de una habitación" }, { word: "escalera", meaning: "ladder · sirve para subir" }, { word: "adentro", meaning: "inside · en el interior" }],
    questions: [
      { prompt: "¿Qué problema tuvo Nico con su equipaje?", options: ["Su valija desapareció", "Su valija empezó a flotar", "Su mochila estaba vacía"], answer: 1, feedback: "La valija subió hasta el techo de la habitación." },
      { prompt: "¿De qué color era la valija?", options: ["Roja", "Negra", "Azul"], answer: 2, feedback: "Nico llegó con una mochila y una valija azul." },
      { prompt: "¿Dónde dejó la mochila?", options: ["En una silla", "Debajo de la cama", "En recepción"], answer: 0, feedback: "Dejó la mochila en una silla antes de ver que la valija subía." },
      { prompt: "¿Qué llevó la empleada a la habitación?", options: ["Una llave", "Una escalera", "Una taza"], answer: 1, feedback: "La empleada vino con una escalera para alcanzar la valija." },
      { prompt: "¿Para quién era el regalo?", options: ["Para su madre", "Para una amiga", "Para su hermana"], answer: 2, feedback: "Dentro de la valija había un regalo para su hermana." },
      { prompt: "¿Qué pasó después de abrir el globo de vidrio?", options: ["La nube salió y la valija bajó", "La ropa se mojó", "La ventana se rompió"], answer: 0, feedback: "La nube salió por la ventana y entonces la valija bajó sola." },
      { prompt: "¿Qué tres cosas llevaba Nico dentro de la valija?", options: ["Llevaba ropa, un libro y un regalo para su hermana."], answer: 0, feedback: "Son los tres elementos que menciona cuando la empleada le pregunta." },
      { prompt: "¿Qué tenía adentro el globo de vidrio?", options: ["Tenía una pequeña nube adentro."], answer: 0, feedback: "La nube era parte del regalo y salió cuando abrieron el globo." },
      { prompt: "¿Se rompió algo cuando bajó la valija?", options: ["No, por suerte no se rompió nada."], answer: 0, feedback: "Nico dice explícitamente: «Por suerte, nada se rompió»." },
      { prompt: "¿Qué regalo compró después? ¿Por qué cambió de regalo?", options: ["Compró una taza. Después del problema con la nube, prefirió un regalo más fácil de transportar."], answer: 0, feedback: "La taza aparece al final; la razón se entiende por lo que pasó con la valija." },
    ],
  },
  {
    id: "el-desayuno", number: "102", name: "El desayuno del futuro", symbol: "☕", color: "#ffb897",
    title: "Todavía no había pedido nada", topic: "Comida, pedidos y horarios",
    speaker: "Elena · huésped · voz mexicana", voice: "es-MX-DaliaNeural",
    script: "Esta mañana bajé al comedor a las ocho. Antes de sentarme, un camarero puso frente a mí un café y dos tostadas con mermelada. Me sorprendí porque todavía no había pedido nada. Él me explicó que la cocina preparaba lo que los huéspedes iban a pedir cinco minutos después. Para probarlo, pensé en un jugo de naranja, pero no dije nada. Un momento más tarde apareció el jugo. Todo iba bien hasta que cambié de idea: ya no quería café, quería té. El camarero se rió y señaló una mesa junto a la ventana. Allí estaba mi té, pero también había seis platos de fruta. Eran de una señora que cambiaba de opinión todo el tiempo. Al final, compartimos la fruta y desayunamos juntas durante una hora.",
    glossary: [{ word: "comedor", meaning: "dining room · lugar para comer" }, { word: "tostadas", meaning: "toast · pan tostado" }, { word: "huéspedes", meaning: "guests · personas alojadas en el hotel" }, { word: "cambiar de opinión", meaning: "change your mind · decidir algo diferente" }],
    questions: [
      { prompt: "¿Qué tenía de especial la cocina?", options: ["Preparaba los pedidos antes de recibirlos", "Solo servía comida fría", "Cocinaba una vez por semana"], answer: 0, feedback: "La cocina preparaba lo que los huéspedes iban a pedir cinco minutos después." },
      { prompt: "¿A qué hora bajó Elena al comedor?", options: ["A las siete", "A las nueve", "A las ocho"], answer: 2, feedback: "El relato empieza con su llegada al comedor a las ocho." },
      { prompt: "¿Qué había en el primer pedido?", options: ["Té y fruta", "Café y dos tostadas con mermelada", "Jugo y un sándwich"], answer: 1, feedback: "El camarero puso un café y dos tostadas con mermelada frente a ella." },
      { prompt: "¿En qué bebida pensó para probar la cocina?", options: ["En un jugo de naranja", "En un vaso de leche", "En agua con limón"], answer: 0, feedback: "Pensó en un jugo de naranja sin decir nada y luego apareció." },
      { prompt: "¿Dónde estaba el té?", options: ["En la cocina", "En su habitación", "En una mesa junto a la ventana"], answer: 2, feedback: "El camarero señaló una mesa junto a la ventana: allí estaba el té." },
      { prompt: "¿Por qué había seis platos de fruta?", options: ["Elena había invitado a seis personas", "Una señora cambiaba de opinión todo el tiempo", "Era el cumpleaños del camarero"], answer: 1, feedback: "Los platos eran de una señora que cambiaba de opinión continuamente." },
      { prompt: "¿Cuántos minutos antes preparaba la cocina los pedidos?", options: ["Los preparaba cinco minutos antes."], answer: 0, feedback: "Es el tiempo que explica el camarero." },
      { prompt: "¿Qué bebida quería Elena después de cambiar de idea?", options: ["Quería té en lugar de café."], answer: 0, feedback: "Dice que ya no quería café, quería té." },
      { prompt: "¿Qué hicieron Elena y la señora con la fruta?", options: ["La compartieron y desayunaron juntas."], answer: 0, feedback: "El problema de los seis platos terminó en un desayuno compartido." },
      { prompt: "¿Cuánto tiempo duró el desayuno compartido?", options: ["Desayunaron juntas durante una hora."], answer: 0, feedback: "Es el último detalle del relato." },
    ],
  },
  {
    id: "la-ventana", number: "103", name: "La ventana del clima", symbol: "🌦️", color: "#8fe0e8",
    title: "Lluvia a la izquierda, sol a la derecha", topic: "Clima, ropa y pequeños errores",
    speaker: "Mateo · huésped · voz colombiana", voice: "es-CO-GonzaloNeural",
    script: "Reservé tres noches en el hotel porque necesitaba descansar. Mi habitación tenía una ventana enorme y tres botones: sol, lluvia y nieve. El primer día elegí sol y me senté a leer junto a la ventana. Afuera, sin embargo, toda la ciudad estaba bajo la lluvia. El clima especial solo existía delante de mi habitación. Por la tarde pulsé nieve para hacerle una foto a mi sobrino. Fue divertido hasta que olvidé cerrar la ventana. En diez minutos, la alfombra quedó blanca y mis zapatos estaban llenos de nieve. Llamé al servicio de limpieza. El empleado no trajo una aspiradora, sino un secador de pelo gigante. Después de media hora todo estaba seco. Desde entonces, miro el clima desde la cama y dejo los botones tranquilos.",
    glossary: [{ word: "pulsar", meaning: "press · tocar un botón" }, { word: "alfombra", meaning: "carpet / rug · cubre el piso" }, { word: "aspiradora", meaning: "vacuum cleaner · máquina para limpiar" }, { word: "secador de pelo", meaning: "hair dryer · aparato que produce aire caliente" }],
    questions: [
      { prompt: "¿Qué podía hacer la ventana?", options: ["Cambiar el clima de toda la ciudad", "Mostrar películas", "Cambiar el clima delante de la habitación"], answer: 2, feedback: "Mateo aclara que el clima especial solo existía delante de su habitación." },
      { prompt: "¿Cuántas noches reservó?", options: ["Tres", "Dos", "Cinco"], answer: 0, feedback: "Reservó tres noches porque necesitaba descansar." },
      { prompt: "¿Qué clima eligió primero?", options: ["Lluvia", "Sol", "Nieve"], answer: 1, feedback: "El primer día eligió sol y se sentó a leer." },
      { prompt: "¿Para quién quería hacer una foto de la nieve?", options: ["Para su hermano", "Para su jefe", "Para su sobrino"], answer: 2, feedback: "Pulsó nieve para hacerle una foto a su sobrino." },
      { prompt: "¿Qué olvidó hacer?", options: ["Cerrar la ventana", "Llamar a recepción", "Ponerse los zapatos"], answer: 0, feedback: "La nieve entró porque olvidó cerrar la ventana." },
      { prompt: "¿Con qué secó la habitación el empleado?", options: ["Con una aspiradora", "Con un secador de pelo gigante", "Con una toalla pequeña"], answer: 1, feedback: "El empleado llevó un secador de pelo gigante, no una aspiradora." },
      { prompt: "¿Cómo estaba el clima en el resto de la ciudad?", options: ["Estaba lloviendo en toda la ciudad."], answer: 0, feedback: "Aunque él eligió sol, fuera de su ventana la ciudad estaba bajo la lluvia." },
      { prompt: "¿Qué dos cosas se llenaron de nieve?", options: ["La alfombra y los zapatos de Mateo."], answer: 0, feedback: "La alfombra quedó blanca y sus zapatos estaban llenos de nieve." },
      { prompt: "¿Cuánto tardó en quedar todo seco?", options: ["Media hora."], answer: 0, feedback: "Diez minutos es el tiempo en que entró la nieve; media hora es el tiempo de secado." },
      { prompt: "¿Qué hace Mateo ahora para evitar otro problema?", options: ["Mira el clima desde la cama y no toca los botones."], answer: 0, feedback: "El final muestra que aprendió a disfrutar de la ventana sin cambiar el clima." },
    ],
  },
  {
    id: "el-espejo", number: "104", name: "El espejo sincero", symbol: "🪞", color: "#c5b5ff",
    title: "Mi reflejo tenía otros planes", topic: "Rutinas, cansancio y descanso",
    speaker: "Camila · huésped · voz chilena", voice: "es-CL-CatalinaNeural",
    script: "El sábado tenía una cena importante a las nueve. A las siete empecé a prepararme en el baño del hotel. Me puse una camisa verde y me miré al espejo, pero mi reflejo llevaba un pijama amarillo. Pensé que era una broma. Me lavé la cara y miré otra vez: el reflejo seguía en pijama y ahora tenía una taza de té. En la pared había una nota: este espejo muestra lo que tu cuerpo necesita. Esa semana había dormido muy poco y había trabajado hasta tarde todos los días. Llamé a mi amiga y le expliqué que estaba agotada. Cambiamos la cena por un almuerzo el domingo. Me puse el pijama, pedí una sopa y me acosté temprano. A la mañana siguiente, mi reflejo sonreía y llevaba ropa para salir.",
    glossary: [{ word: "reflejo", meaning: "reflection · imagen en un espejo" }, { word: "broma", meaning: "joke · algo para hacer reír" }, { word: "agotada", meaning: "exhausted · muy cansada" }, { word: "acostarse", meaning: "go to bed · ir a la cama" }],
    questions: [
      { prompt: "¿Qué mostraba el espejo?", options: ["Lo que necesitaba su cuerpo", "La ropa de otra huésped", "Lo que iba a pasar el próximo año"], answer: 0, feedback: "La nota decía que el espejo mostraba lo que su cuerpo necesitaba." },
      { prompt: "¿A qué hora era la cena?", options: ["A las siete", "A las nueve", "A las diez"], answer: 1, feedback: "La cena era a las nueve; empezó a prepararse a las siete." },
      { prompt: "¿Qué ropa se puso Camila al principio?", options: ["Un vestido rojo", "Un pijama amarillo", "Una camisa verde"], answer: 2, feedback: "Camila se puso una camisa verde, aunque su reflejo llevaba un pijama." },
      { prompt: "¿De qué color era el pijama del reflejo?", options: ["Amarillo", "Verde", "Azul"], answer: 0, feedback: "El reflejo llevaba un pijama amarillo." },
      { prompt: "¿Cómo había sido su semana?", options: ["Había descansado mucho", "Había dormido poco y trabajado hasta tarde", "Había estado de vacaciones"], answer: 1, feedback: "Había dormido muy poco y trabajado hasta tarde todos los días." },
      { prompt: "¿Para cuándo cambiaron la comida con su amiga?", options: ["Para el viernes por la noche", "Para el lunes por la mañana", "Para el domingo al mediodía"], answer: 2, feedback: "Cambiaron la cena del sábado por un almuerzo el domingo." },
      { prompt: "¿Qué tenía el reflejo en la mano cuando Camila miró otra vez?", options: ["Tenía una taza de té."], answer: 0, feedback: "La taza de té aparece después de que se lava la cara." },
      { prompt: "¿Por qué llamó Camila a su amiga?", options: ["Porque estaba agotada y necesitaba cambiar el plan para descansar."], answer: 0, feedback: "El espejo la ayudó a reconocer su cansancio y se lo explicó a su amiga." },
      { prompt: "¿Qué comió esa noche y qué hizo después?", options: ["Pidió una sopa y se acostó temprano."], answer: 0, feedback: "Primero se puso el pijama; luego pidió sopa y se fue a dormir." },
      { prompt: "¿Cómo era su reflejo a la mañana siguiente?", options: ["Sonreía y llevaba ropa para salir."], answer: 0, feedback: "El cambio del reflejo indica que ya estaba descansada." },
    ],
  },
  {
    id: "el-ascensor", number: "105", name: "El ascensor perdido", symbol: "🛗", color: "#86d8b5",
    title: "Apreté el cinco y llegué al bosque", topic: "Direcciones, lugares y ayuda",
    speaker: "Bruno · huésped · voz uruguaya", voice: "es-UY-MateoNeural",
    script: "Ayer entré al ascensor para subir al quinto piso. Apreté el cinco, pero las puertas se abrieron en un bosque. Había árboles altísimos y un banco de madera. Un señor con una bicicleta me preguntó si buscaba el desayuno. Le dije que solo quería volver a mi habitación. Entonces me mostró un cartel junto al ascensor: no elijas un número, decí adónde querés ir. Volví a entrar y dije recepción. Las puertas se cerraron y, unos segundos después, estaba frente a la recepcionista. Ella me explicó que el ascensor se había cansado de subir y bajar por los mismos pisos. Ahora prefería visitar lugares nuevos. Antes de volver a mi cuarto, le pedí ir a la terraza. Esta vez llegué bien, aunque había una ardilla sentada en una de las sillas.",
    glossary: [{ word: "apretar", meaning: "press · pulsar" }, { word: "bosque", meaning: "forest · lugar con muchos árboles" }, { word: "cartel", meaning: "sign · información escrita en un lugar visible" }, { word: "ardilla", meaning: "squirrel · pequeño animal de cola larga" }],
    questions: [
      { prompt: "¿Cuál era el problema con el ascensor?", options: ["No abría las puertas", "Llevaba a lugares inesperados", "Solo funcionaba de noche"], answer: 1, feedback: "Bruno quería ir al quinto piso, pero el ascensor lo llevó a un bosque." },
      { prompt: "¿A qué piso quería ir Bruno al principio?", options: ["Al primero", "Al tercero", "Al quinto"], answer: 2, feedback: "Entró para subir al quinto piso y apretó el cinco." },
      { prompt: "¿Dónde se abrieron las puertas la primera vez?", options: ["En un bosque", "En la terraza", "En el comedor"], answer: 0, feedback: "Las puertas se abrieron en un bosque con árboles altísimos." },
      { prompt: "¿Qué tenía el señor que encontró?", options: ["Un perro", "Una bicicleta", "Una valija"], answer: 1, feedback: "Era un señor con una bicicleta." },
      { prompt: "¿Cómo debía elegir su destino?", options: ["Escribiendo una dirección", "Apretando dos botones", "Diciendo adónde quería ir"], answer: 2, feedback: "El cartel indicaba que había que decir el destino, no elegir un número." },
      { prompt: "¿Adónde fue justo después de salir del bosque?", options: ["A recepción", "A su habitación", "Al desayuno"], answer: 0, feedback: "Volvió al ascensor, dijo «recepción» y llegó frente a la recepcionista." },
      { prompt: "¿Qué le preguntó el señor del bosque?", options: ["Le preguntó si buscaba el desayuno."], answer: 0, feedback: "Bruno respondió que solo quería volver a su habitación." },
      { prompt: "¿Por qué el ascensor visitaba lugares nuevos?", options: ["Porque se había cansado de subir y bajar por los mismos pisos."], answer: 0, feedback: "Esa es la explicación que le dio la recepcionista." },
      { prompt: "¿Qué lugar le pidió visitar Bruno antes de volver a su cuarto?", options: ["La terraza."], answer: 0, feedback: "Pidió ir a la terraza y esta vez llegó al lugar correcto." },
      { prompt: "¿Qué sorpresa encontró allí y dónde estaba?", options: ["Encontró una ardilla sentada en una silla."], answer: 0, feedback: "La ardilla es el último detalle inesperado del relato." },
    ],
  },
  {
    id: "la-almohada", number: "106", name: "La almohada musical", symbol: "🎵", color: "#f4a6c6",
    title: "No era el vecino: era mi almohada", topic: "Sueño, sonidos y preferencias",
    speaker: "Lucía · huésped · voz peruana", voice: "es-PE-CamilaNeural",
    script: "La primera noche en el hotel escuché música justo cuando apoyé la cabeza en la almohada. Pensé que venía de la habitación de al lado, pero al levantarme la música paró. Probé otra vez y empezó una canción de mi infancia. La almohada tenía una etiqueta que decía: elegí un recuerdo y dormí con su sonido. Me acordé de las vacaciones en casa de mis abuelos y escuché el mar. Era precioso, pero también se oía al perro de mi abuelo, que ladraba sin parar. Después pensé en una tarde en la biblioteca. Por fin hubo silencio, hasta que alguien empezó a pasar páginas muy rápido. A las doce llamé a recepción para pedir una almohada normal. La nueva no tenía música ni recuerdos. Dormí ocho horas seguidas y no soñé con ningún perro.",
    glossary: [{ word: "almohada", meaning: "pillow · donde apoyás la cabeza para dormir" }, { word: "etiqueta", meaning: "label · pequeño texto con información" }, { word: "ladrar", meaning: "bark · sonido de un perro" }, { word: "seguidas", meaning: "in a row · sin interrupción" }],
    questions: [
      { prompt: "¿De dónde venía realmente la música?", options: ["De la televisión", "De la habitación de al lado", "De la almohada"], answer: 2, feedback: "La música empezaba cuando Lucía apoyaba la cabeza en la almohada." },
      { prompt: "¿Qué pasaba cuando se levantaba?", options: ["La música paraba", "El sonido era más fuerte", "La almohada cambiaba de color"], answer: 0, feedback: "Al levantarse, la música paró." },
      { prompt: "¿Qué canción escuchó al probar otra vez?", options: ["Una canción nueva del hotel", "Una canción de su infancia", "Una canción que cantaba su vecino"], answer: 1, feedback: "La almohada empezó a reproducir una canción de su infancia." },
      { prompt: "¿Qué escuchó al recordar las vacaciones con sus abuelos?", options: ["Un tren y una radio", "Lluvia y viento", "El mar y un perro"], answer: 2, feedback: "Escuchó el mar, pero también al perro de su abuelo ladrando." },
      { prompt: "¿Qué ruido apareció en el recuerdo de la biblioteca?", options: ["Alguien pasando páginas muy rápido", "Una alarma de incendio", "Un grupo cantando"], answer: 0, feedback: "El silencio terminó cuando alguien empezó a pasar páginas muy rápido." },
      { prompt: "¿Qué pidió a recepción?", options: ["Unos auriculares", "Una almohada normal", "Otra habitación"], answer: 1, feedback: "A las doce llamó para pedir una almohada normal." },
      { prompt: "¿Qué había que elegir según la etiqueta?", options: ["Había que elegir un recuerdo para dormir con su sonido."], answer: 0, feedback: "La etiqueta explica cómo funciona la almohada fantástica." },
      { prompt: "¿Por qué no le sirvió el recuerdo del mar para dormir?", options: ["Porque también se oía al perro de su abuelo ladrando sin parar."], answer: 0, feedback: "El sonido del mar era precioso, pero el perro hacía demasiado ruido." },
      { prompt: "¿A qué hora llamó Lucía a recepción?", options: ["A las doce de la noche."], answer: 0, feedback: "Había probado varios recuerdos antes de llamar a las doce." },
      { prompt: "¿Cuántas horas durmió con la almohada nueva?", options: ["Durmió ocho horas seguidas."], answer: 0, feedback: "Con la almohada sin música ni recuerdos consiguió descansar." },
    ],
  },
  {
    id: "el-reloj", number: "107", name: "Los minutos prestados", symbol: "⏳", color: "#b9db83",
    title: "Pagué mi siesta con una fila", topic: "Tiempo, planes y decisiones",
    speaker: "Andrés · huésped · voz costarricense", voice: "es-CR-JuanNeural",
    script: "En mi habitación había un reloj sin agujas y una caja de monedas. Cada moneda te daba diez minutos extra, pero después tenías que devolverlos. El domingo tenía una excursión a las cuatro y quería dormir un poco más. Puse dos monedas en el reloj y tuve veinte minutos de siesta sin llegar tarde. Cuando bajé, el guía ya estaba junto a la puerta. Fuimos a un jardín lleno de flores que brillaban de noche. Todo salió perfecto. Al volver, encontré una nota sobre la cama: mañana vas a esperar veinte minutos más en algún lugar. No le di importancia. El lunes fui a comprar un café y la persona delante de mí pidió bebidas para toda su oficina. Miré el reloj y entendí todo. Ahora prefiero poner una alarma normal.",
    glossary: [{ word: "agujas", meaning: "clock hands · partes que señalan la hora" }, { word: "monedas", meaning: "coins · dinero de metal" }, { word: "siesta", meaning: "nap · descanso durante el día" }, { word: "devolver", meaning: "give back · regresar algo prestado" }],
    questions: [
      { prompt: "¿Cuál era la regla del reloj?", options: ["Daba tiempo extra que después había que devolver", "Detenía el tiempo para siempre", "Solo funcionaba los lunes"], answer: 0, feedback: "Cada moneda daba diez minutos extra, pero después había que devolverlos." },
      { prompt: "¿Qué le faltaba al reloj?", options: ["Los números", "La caja", "Las agujas"], answer: 2, feedback: "En la habitación había un reloj sin agujas." },
      { prompt: "¿Cuántas monedas usó Andrés?", options: ["Una", "Dos", "Cuatro"], answer: 1, feedback: "Puso dos monedas: consiguió veinte minutos extra." },
      { prompt: "¿A qué hora era la excursión?", options: ["A las cuatro", "A las dos", "A las seis"], answer: 0, feedback: "La excursión del domingo era a las cuatro." },
      { prompt: "¿Qué tenía de especial el jardín?", options: ["Las flores hablaban", "No tenía árboles", "Las flores brillaban de noche"], answer: 2, feedback: "Visitaron un jardín lleno de flores que brillaban de noche." },
      { prompt: "¿Dónde tuvo que devolver los minutos?", options: ["Esperando al guía", "Esperando para comprar un café", "Esperando el ascensor"], answer: 1, feedback: "El lunes tuvo una espera extra porque la persona anterior pidió bebidas para toda su oficina." },
      { prompt: "¿Para qué quería Andrés veinte minutos extra?", options: ["Para dormir una siesta un poco más larga sin llegar tarde a la excursión."], answer: 0, feedback: "Usó las monedas para descansar antes de salir." },
      { prompt: "¿Dónde esperaba el guía?", options: ["Estaba junto a la puerta del hotel."], answer: 0, feedback: "Cuando Andrés bajó, el guía ya estaba allí." },
      { prompt: "¿Qué decía la nota que encontró sobre la cama?", options: ["Que al día siguiente iba a esperar veinte minutos más en algún lugar."], answer: 0, feedback: "La nota anunciaba cómo iba a devolver el tiempo prestado." },
      { prompt: "¿Qué prefiere usar Andrés después de esta experiencia?", options: ["Prefiere poner una alarma normal."], answer: 0, feedback: "Decide organizarse sin pedir tiempo prestado al reloj." },
    ],
  },
  {
    id: "el-armario", number: "108", name: "El armario viajero", symbol: "🧥", color: "#97bfff",
    title: "Mi abrigo volvió con arena", topic: "Ropa, objetos y viajes secretos",
    speaker: "Mariana · huésped · voz dominicana", voice: "es-DO-RamonaNeural",
    script: "Dejé mi abrigo rojo dentro del armario antes de bajar a cenar. Cuando volví, el abrigo no estaba. En su lugar encontré una postal de una playa y unas sandalias pequeñas. Pensé que alguien había entrado en mi habitación, así que llamé al recepcionista. Él me pidió que esperara hasta las diez. A esa hora escuché un golpe suave dentro del armario. Abrí la puerta y allí estaba mi abrigo, caliente y lleno de arena. En un bolsillo había una foto: el abrigo estaba sobre una silla frente al mar. El recepcionista explicó que la ropa también necesitaba vacaciones. Al día siguiente guardé mis zapatos viejos y les dejé una nota: por favor, vuelvan antes de las siete. Volvieron a las seis y media, muy limpios, con un billete de tren entre los cordones.",
    glossary: [{ word: "abrigo", meaning: "coat · ropa para el frío" }, { word: "armario", meaning: "wardrobe · mueble para guardar ropa" }, { word: "arena", meaning: "sand · está en la playa" }, { word: "cordones", meaning: "shoelaces · sirven para atar los zapatos" }],
    questions: [
      { prompt: "¿Qué ocurría con la ropa del armario?", options: ["Se volvía invisible", "Salía de vacaciones", "Cambiaba de dueño"], answer: 1, feedback: "El recepcionista explicó que la ropa también necesitaba vacaciones." },
      { prompt: "¿De qué color era el abrigo?", options: ["Azul", "Negro", "Rojo"], answer: 2, feedback: "Mariana dejó un abrigo rojo dentro del armario." },
      { prompt: "¿Qué encontró en lugar del abrigo?", options: ["Una postal de una playa y unas sandalias pequeñas", "Una llave y un paraguas", "Una foto y un sombrero"], answer: 0, feedback: "Al volver de cenar encontró una postal y unas sandalias pequeñas." },
      { prompt: "¿Hasta qué hora le pidió esperar el recepcionista?", options: ["Hasta las ocho", "Hasta las diez", "Hasta las doce"], answer: 1, feedback: "Le pidió que esperara hasta las diez, cuando regresó el abrigo." },
      { prompt: "¿Dónde estaba el abrigo en la foto?", options: ["En un tren", "En una montaña", "Sobre una silla frente al mar"], answer: 2, feedback: "La foto mostraba al abrigo sobre una silla frente al mar." },
      { prompt: "¿A qué hora volvieron los zapatos?", options: ["A las seis y media", "A las siete y media", "A las diez"], answer: 0, feedback: "Volvieron a las seis y media, antes de la hora que Mariana había pedido." },
      { prompt: "¿Qué pensó Mariana cuando no encontró su abrigo?", options: ["Pensó que alguien había entrado en su habitación."], answer: 0, feedback: "Por eso llamó al recepcionista antes de entender lo que pasaba." },
      { prompt: "¿Cómo estaba el abrigo cuando regresó?", options: ["Estaba caliente y lleno de arena."], answer: 0, feedback: "Esos detalles, junto con la foto, sugieren que estuvo en la playa." },
      { prompt: "¿Qué pidió Mariana en la nota para sus zapatos?", options: ["Les pidió que volvieran antes de las siete."], answer: 0, feedback: "La nota marcaba una hora límite para el viaje de los zapatos." },
      { prompt: "¿Qué objeto trajeron los zapatos y dónde estaba?", options: ["Trajeron un billete de tren entre los cordones."], answer: 0, feedback: "Es la pista del viaje que hicieron los zapatos." },
    ],
  },
  {
    id: "el-telefono", number: "109", name: "La llamada de mañana", symbol: "☎️", color: "#f9be7c",
    title: "Yo mismo me llamé desde mañana", topic: "Mensajes, objetos perdidos y pistas",
    speaker: "Daniel · huésped · voz mexicana", voice: "es-MX-JorgeNeural",
    script: "El teléfono de mi habitación sonó el martes a las diez de la noche. Contesté y escuché mi propia voz. La persona dijo: soy vos, pero te llamo desde mañana. Pensé que era una broma de mi hermano. Sin embargo, la voz sabía que yo estaba comiendo galletas en la cama. Me dio un solo consejo: no lleves el paraguas negro al museo. Al día siguiente llovía mucho. Recordé la llamada y pedí un paraguas amarillo en recepción. En el museo vi a cinco personas con paraguas negros idénticos. Al salir, todos discutían porque no sabían cuál era el suyo. Yo encontré el amarillo enseguida y me fui tranquilo. Esa noche intenté llamar al día siguiente para preguntar los números de la lotería, pero el teléfono solo repetía: este servicio resuelve problemas pequeños.",
    glossary: [{ word: "contestar", meaning: "answer · responder a una llamada" }, { word: "propia voz", meaning: "own voice · su misma voz" }, { word: "idénticos", meaning: "identical · exactamente iguales" }, { word: "enseguida", meaning: "straight away · muy rápido" }],
    questions: [
      { prompt: "¿Quién dijo ser la persona que llamaba?", options: ["Daniel desde el día siguiente", "Su hermano desde el museo", "El recepcionista"], answer: 0, feedback: "La voz dijo que era él mismo, pero que llamaba desde mañana." },
      { prompt: "¿Cuándo recibió la llamada?", options: ["El lunes a las ocho", "El martes a las diez de la noche", "El miércoles al mediodía"], answer: 1, feedback: "El teléfono sonó el martes a las diez de la noche." },
      { prompt: "¿Qué estaba haciendo Daniel?", options: ["Leyendo en una silla", "Mirando la lluvia", "Comiendo galletas en la cama"], answer: 2, feedback: "La voz sabía que estaba comiendo galletas en la cama." },
      { prompt: "¿Qué consejo recibió?", options: ["No llevar el paraguas negro al museo", "No visitar el museo", "Salir antes de las ocho"], answer: 0, feedback: "El único consejo era no llevar el paraguas negro al museo." },
      { prompt: "¿De qué color era el paraguas que pidió?", options: ["Rojo", "Amarillo", "Azul"], answer: 1, feedback: "Recordó la llamada y pidió un paraguas amarillo en recepción." },
      { prompt: "¿Por qué discutían las otras personas al salir?", options: ["El museo había cerrado temprano", "No encontraban la salida", "No podían reconocer sus paraguas iguales"], answer: 2, feedback: "Había cinco paraguas negros idénticos y no sabían cuál era el suyo." },
      { prompt: "¿De quién pensó Daniel que era la broma al principio?", options: ["Pensó que era una broma de su hermano."], answer: 0, feedback: "Eso fue antes de que la voz mencionara las galletas." },
      { prompt: "¿Cómo estaba el tiempo el día de la visita al museo?", options: ["Llovía mucho."], answer: 0, feedback: "Por eso necesitaba un paraguas para salir." },
      { prompt: "¿Qué quiso preguntar Daniel en su segunda llamada?", options: ["Quiso preguntar los números de la lotería."], answer: 0, feedback: "Intentó aprovechar el teléfono para conocer los números del día siguiente." },
      { prompt: "¿Qué límite tenía el servicio del teléfono?", options: ["Solo resolvía problemas pequeños."], answer: 0, feedback: "El teléfono repetía esa frase en lugar de dar los números de la lotería." },
    ],
  },
  {
    id: "la-puerta", number: "110", name: "La puerta de los encuentros", symbol: "🚪", color: "#9cddce",
    title: "Pedí sal y encontré compañía", topic: "Compañía, necesidades y encuentros",
    speaker: "Sofía · huésped · voz argentina", voice: "es-AR-ElenaNeural",
    script: "Viajé sola al hotel para pasar un fin de semana tranquilo. El viernes pedí la cena a mi habitación: una sopa y pan. Cuando probé la sopa, le faltaba sal. Abrí la puerta para buscar a alguien y, en lugar del pasillo, encontré una cocina enorme. Había un hombre preparando pizza y una mujer cortando tomates. Los dos también eran huéspedes. El hombre buscaba un cuchillo y la mujer quería hablar con alguien porque extrañaba a su familia. En una pared leímos una frase: esta puerta te lleva a donde alguien puede ayudarte. Encontré la sal, el hombre encontró su cuchillo y la mujer encontró compañía. Cenamos los tres en una mesa redonda. El sábado volví a abrir la puerta, pero solo vi el pasillo. No necesitaba nada: ya tenía dos amigos y un plan para el almuerzo.",
    glossary: [{ word: "pasillo", meaning: "corridor · conecta las habitaciones" }, { word: "cuchillo", meaning: "knife · sirve para cortar" }, { word: "extrañar", meaning: "miss someone · sentir la falta de alguien" }, { word: "compañía", meaning: "company · estar con otra persona" }],
    questions: [
      { prompt: "¿Adónde llevaba la puerta especial?", options: ["Siempre a la misma cocina", "A donde alguien podía ayudarte", "A la casa de tu familia"], answer: 1, feedback: "La frase de la pared decía que la puerta llevaba a donde alguien podía ayudarte." },
      { prompt: "¿Con quién viajó Sofía al hotel?", options: ["Con su hermana", "Con dos amigos", "Viajó sola"], answer: 2, feedback: "Viajó sola para pasar un fin de semana tranquilo." },
      { prompt: "¿Qué le faltaba a su sopa?", options: ["Sal", "Tomate", "Agua"], answer: 0, feedback: "Al probar la sopa notó que le faltaba sal." },
      { prompt: "¿Qué estaba preparando el hombre?", options: ["Pan", "Pizza", "Sopa"], answer: 1, feedback: "En la cocina había un hombre preparando pizza." },
      { prompt: "¿Por qué quería hablar la mujer?", options: ["Porque no entendía una receta", "Porque había perdido una llave", "Porque extrañaba a su familia"], answer: 2, feedback: "La mujer quería hablar con alguien porque extrañaba a su familia." },
      { prompt: "¿Qué vio Sofía al abrir la puerta el sábado?", options: ["El pasillo normal", "La mesa con sus amigos", "Una playa"], answer: 0, feedback: "El sábado solo vio el pasillo: ya no necesitaba ayuda." },
      { prompt: "¿Qué dos cosas había pedido Sofía para cenar?", options: ["Una sopa y pan."], answer: 0, feedback: "Ese era su pedido inicial para comer sola en la habitación." },
      { prompt: "¿Qué objeto buscaba el hombre?", options: ["Buscaba un cuchillo."], answer: 0, feedback: "Mientras Sofía necesitaba sal, él necesitaba un cuchillo." },
      { prompt: "¿Dónde y con quién cenó Sofía al final?", options: ["Cenó con los otros dos huéspedes en una mesa redonda de la cocina."], answer: 0, feedback: "Los tres encontraron lo que necesitaban y compartieron la cena." },
      { prompt: "¿Qué había cambiado para Sofía al día siguiente?", options: ["Ya tenía dos amigos y un plan para el almuerzo."], answer: 0, feedback: "Su fin de semana tranquilo también se convirtió en una oportunidad para conocer gente." },
    ],
  },
];
