'use client';
import {useCallback,useEffect,useState} from 'react';
import {reportCategories,reportStatuses,type ReportRow} from '../../lesson-reports/contracts';
const labels:Record<string,string>={new:'Nuevo',reviewing:'En revisión',resolved:'Resuelto',dismissed:'Descartado'};
export default function ReportsManager(){const [items,setItems]=useState<ReportRow[]>([]);const [status,setStatus]=useState('');const [category,setCategory]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [selected,setSelected]=useState<ReportRow|null>(null);const [nextStatus,setNextStatus]=useState('new');const [resolution,setResolution]=useState('');const [busy,setBusy]=useState(false);
 const load=useCallback(async(signal?:AbortSignal)=>{if(signal?.aborted)return;try{const query=new URLSearchParams({status,category});const response=await fetch('/api/admin/lesson-reports?'+query,{signal});const data=await response.json() as {items:ReportRow[];error?:string};if(!response.ok)throw new Error(data.error);setError('');setItems(data.items);}catch(err){if(err instanceof Error&&err.name==='AbortError')return;setError(err instanceof Error?err.message:'No pudimos cargar los reportes.');}finally{if(!signal?.aborted)setLoading(false);}},[status,category]);
 useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>load(controller.signal));return()=>controller.abort();},[load]);
 async function save(){if(!selected||busy)return;setBusy(true);setError('');try{const response=await fetch('/api/admin/lesson-reports',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:selected.id,status:nextStatus,resolution})});const data=await response.json() as {error?:string};if(!response.ok)throw new Error(data.error);setSelected(null);await load();}catch(err){setError(err instanceof Error?err.message:'No pudimos guardar.');}finally{setBusy(false);}}
 return <><div className="reports-filters"><label>Estado<select value={status} onChange={e=>{setLoading(true);setStatus(e.target.value);}}><option value="">Todos</option>{reportStatuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label>Categoría<select value={category} onChange={e=>{setLoading(true);setCategory(e.target.value);}}><option value="">Todas</option>{reportCategories.map(c=><option key={c}>{c}</option>)}</select></label><button onClick={()=>{setLoading(true);void load();}}>Actualizar</button></div>{error&&<p role="alert">{error}</p>}{loading?<p role="status">Cargando reportes…</p>:<p>{items.length} reportes · últimos 200 resultados</p>}<div className="reports-list">{!loading&&!items.length&&!error&&<p>Todavía no hay reportes con estos filtros.</p>}{items.map(r=><button className="report-row" key={r.id} onClick={()=>{setSelected(r);setNextStatus(r.status);setResolution(r.resolution);}}><span className={`report-status report-status-${r.status}`}>{labels[r.status]}</span><strong>{r.lesson_title} · {r.level}</strong><span>{r.category} · {new Date(r.created_at).toLocaleString('es-AR')}</span><p>{r.message}</p></button>)}</div>{selected&&<section className="report-detail" aria-label="Detalle del reporte"><button onClick={()=>setSelected(null)} disabled={busy}>Cerrar detalle ×</button><h2>{selected.lesson_title} · {selected.level}</h2><p>{selected.user_email||selected.user_id}</p><p className="report-message">{selected.message}</p><a href={selected.url} target="_blank" rel="noreferrer">Abrir clase y contexto ↗</a><details><summary>Contexto del reporte</summary><pre>{JSON.stringify({reportId:selected.id,lessonId:selected.lesson_id,category:selected.lesson_category,aiStatus:selected.ai_status,...JSON.parse(selected.context_json)},null,2)}</pre></details><label>Estado<select value={nextStatus} onChange={e=>setNextStatus(e.target.value)}>{reportStatuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></label><label>Resolución<textarea value={resolution} onChange={e=>setResolution(e.target.value)} maxLength={2000} rows={4}/></label><button className="report-save" disabled={busy} onClick={()=>void save()}>{busy?'Guardando…':'Guardar cambios'}</button></section>}</>;
}
