"use client";

import {ConversationFamily} from '../conversation-families/ConversationFamily';
import type {CEFRLevel} from '../conversation-families/types';
import {nativeBank,nativeLabel,nativeInstruction,NativeSpeakingSupport} from '../conversation-narratives/native-adapter';
import {narratives,narrativeLevels} from '../conversation-narratives/data';
import {useState} from "react";
import Link from "next/link";
import "./style.css";

const authored_stages=[["El pitch","4 min"],["Tres ofertas","6 min"],["Primera ronda","7 min"],["Cláusula oculta","6 min"],["El veto","6 min"],["Firma o salida","6 min"],["Después del acuerdo","10 min"]] as const;
const authored_projects=[
  {name:"NIDO",line:"Cabinas silenciosas que se reservan por hora en barrios con poco espacio para trabajar.",challenge:"Convence a una persona que ya trabaja gratis en una cafetería."},
  {name:"PUENTE",line:"Una red que conecta a viajeros con expertos locales para descubrir barrios sin turismo masivo.",challenge:"Explica cómo crecer sin destruir aquello que hace valioso el servicio."},
  {name:"CLARO",line:"Un servicio que transforma contratos complejos en explicaciones comprensibles para cualquier persona.",challenge:"Defiende por qué los usuarios confiarían en tu resumen y pagarían por él."},
] as const;
const authored_offers=[
  {firm:"VELA CAPITAL",lead:"Amalia Reyes",style:"CRECIMIENTO",offer:"Financia la expansión inmediata a ocho ciudades y pide el 35 % de la empresa.",want:"Quiere velocidad, visibilidad y una decisión esta noche.",objections:["El proyecto crece demasiado despacio.","Tu ventaja se puede copiar en seis meses.","No pareces dispuesto/a a asumir suficiente riesgo."],clause:"Exclusividad durante cinco años y derecho a reutilizar todos los datos generados por los usuarios."},
  {firm:"NORTE STUDIO",lead:"Tomás Vidal",style:"CONTROL CREATIVO",offer:"Aporta equipo, marca y distribución; pide el 20 % y una licencia internacional exclusiva.",want:"Quiere una marca impecable y poder decidir cómo se presenta.",objections:["La propuesta todavía no tiene una identidad reconocible.","Tu precio no refleja un servicio premium.","El equipo fundador no tiene experiencia internacional."],clause:"Veto sobre precios, identidad visual y cualquier alianza con otra marca."},
  {firm:"FONDO COMÚN",lead:"Lucía Benítez",style:"IMPACTO",offer:"Financia un crecimiento gradual por el 25 % e incorpora una voz de los empleados al consejo.",want:"Quiere impacto verificable aunque la rentabilidad tarde más.",objections:["No has demostrado a quién beneficia realmente el proyecto.","Tu plan podría aumentar desigualdades.","No hay una forma clara de medir el impacto."],clause:"Límite anual a los beneficios de los fundadores y obligación de abandonar mercados que no cumplan los objetivos sociales."},
] as const;
const authored_tools={
  "CONTRAOFERTAR":["Podría aceptar ese punto siempre que…","Nuestra alternativa sería…","Si reducen…, podríamos ofrecer…","Propongo revisar esa condición dentro de…"],
  "PONER LÍMITES":["Eso no es negociable porque…","Ahí tendríamos que poner un límite.","Podemos ceder en…, pero no en…","Sin esa garantía no habría acuerdo."],
  "GANAR TIEMPO":["Antes de responder, necesito aclarar…","Déjame valorar las consecuencias.","¿Podrías concretar qué implicaría?","Quiero asegurarme de entender la condición."],
} as const;
const authored_finalQuestions=[
  ["¿Te resulta fácil hablar de dinero o control con personas de confianza?","¿Qué vuelve incómoda esa conversación?"],
  ["En el trabajo, ¿qué pesa más para ti: autonomía, seguridad o crecimiento?","¿Ha cambiado tu respuesta con el tiempo?"],
  ["¿Has rechazado una oportunidad atractiva porque las condiciones no encajaban?","¿Qué perdiste y qué protegiste?"],
  ["¿En qué momento un compromiso se convierte en ceder demasiado?","¿Existe una señal clara?"],
  ["¿Prefieres un socio parecido a ti o alguien que te contradiga?","¿Qué conflicto podría generar cada opción?"],
  ["¿Qué hace persuasiva a una persona sin volverla manipuladora?","Piensa en un ejemplo real."],
  ["¿Cuánto valor tienen las promesas verbales en tu entorno?","¿Cambiaría según la cultura o el tipo de relación?"],
  ["Si crearas un proyecto, ¿qué nunca permitirías que un inversor cambiara?","¿Aceptarías una oferta extraordinaria? ¿Dónde está tu límite?"],
] as const;

function MesaTresOfertasNative({level}:{level:CEFRLevel}){
 const stages=nativeBank('deal',level,'stages',authored_stages);
 const projects=nativeBank('deal',level,'projects',authored_projects);
 const offers=nativeBank('deal',level,'offers',authored_offers);
 const tools=nativeBank('deal',level,'tools',authored_tools);
 const finalQuestions=nativeBank('deal',level,'finalQuestions',authored_finalQuestions);

  const [stage,setStage]=useState(0);const [project,setProject]=useState(0);const [offer,setOffer]=useState(0);const [objection,setObjection]=useState(0);const [clause,setClause]=useState(false);const [protectedItems,setProtectedItems]=useState<string[]>([]);const [veto,setVeto]=useState(false);const [decision,setDecision]=useState<"ACEPTAR"|"CONTRAOFERTAR"|"RETIRARSE"|null>(null);const [ultimatum,setUltimatum]=useState(false);const [support,setSupport]=useState<keyof typeof tools|null>(null);const [finalOpen,setFinalOpen]=useState<number|null>(null);
  const go=(next:number)=>{setStage(Math.max(0,Math.min(6,next)));window.scrollTo({top:0,behavior:"auto"})};
  const chooseOffer=(index:number)=>{setOffer(index);setObjection(0);setClause(false);setDecision(null);setUltimatum(false)};
  const protect=(item:string)=>setProtectedItems(old=>old.includes(item)?old.filter(value=>value!==item):old.length<2?[...old,item]:old);
  return <main className="deal-app">
    <nav className="deal-nav"><Link href="/"><img src="/brand/mascot/portrait.webp" alt=""/><span><b>{nativeLabel(level,"SPANISHCUE")}</b><small>{nativeLabel(level,"B2 · CONVERSACIÓN")}</small></span></Link><div>{nativeLabel(level,"PLANTA 47 · REUNIÓN PRIVADA")}</div><Link href="/">{nativeLabel(level,"BIBLIOTECA")}</Link></nav>
    <aside className="deal-progress"><div style={{width:`${((stage+1)/7)*100}%`}}/><span>{stages[stage][0]} · {stages[stage][1]}</span></aside>

    {stage===0&&<section className="deal-hero"><div className="deal-hero-image"/><div className="deal-shade"/><article><span>{nativeLabel(level,"B2 · NEGOCIACIÓN CONTINUA · 45 MIN")}</span><h1>{nativeLabel(level,"Tres ofertas.")}<br/><em>{nativeLabel(level,"Una sola firma.")}</em></h1><p>{nativeInstruction('deal',level,stage,"Tienes treinta segundos antes de que entren los inversores. Elige qué proyecto lideras y véndeselo al profesor: problema, cliente y valor. No leas; convéncelo.",offer)}</p><div className="project-tabs">{projects.map((item,index)=><button key={item.name} className={project===index?"active":""} onClick={()=>setProject(index)}><b>{item.name}</b><span>{item.line}</span></button>)}</div><div className="pitch-call"><small>{nativeLabel(level,"PRIMERA OBJECIÓN DEL PROFESOR")}</small><h2>{projects[project].challenge}</h2><p>{nativeLabel(level,"Responde y pregúntale qué tendría que escuchar para invertir.")}</p></div><button className="deal-primary" onClick={()=>go(1)}>{nativeLabel(level,"HACER PASAR A LOS INVERSORES →")}</button></article></section>}

    {stage===1&&<section className="deal-page offers-room"><header><span>{nativeLabel(level,"MESA ABIERTA · 6 MIN")}</span><h1>{nativeLabel(level,"El dinero no viene solo.")}</h1><p>{nativeInstruction('deal',level,stage,"Escucha las tres posiciones. Elige con quién hablar primero y explica qué te atrae, qué te preocupa y qué información necesitas antes de negociar.",offer)}</p></header><div className="offers-grid">{offers.map((item,index)=><button key={item.firm} className={offer===index?"active":""} onClick={()=>chooseOffer(index)}><span>0{index+1} · {item.style}</span><h2>{item.firm}</h2><small>{item.lead}</small><p>{item.offer}</p><footer>{offer===index?nativeLabel(level,"EN LA MESA"):nativeLabel(level,"INVITAR A LA MESA")}</footer></button>)}</div><aside className="meeting-brief"><b>{offers[offer].lead} {nativeLabel(level," · PROFESOR EN PERSONAJE")}</b><p>“{offers[offer].want}”</p><h3>{nativeInstruction('deal',level,stage,"Resume su prioridad con tus propias palabras. Después, señala el primer punto que negociarías.",offer)}</h3></aside></section>}

    {stage===2&&<section className="deal-page round-room"><header><span>{nativeLabel(level,"PRIMERA RONDA · 7 MIN")}</span><h1>{nativeLabel(level,"No vendas más: responde.")}</h1><p>{nativeLabel(level,"El profesor interpreta a ")}{offers[offer].lead}{nativeInstruction('deal',level,stage,". Abre una objeción por vez, responde con un argumento y un ejemplo, y formula una contraoferta concreta.",offer)}</p></header><div className="boardroom"><section><small>{nativeLabel(level,"OFERTA ACTIVA")}</small><h2>{offers[offer].firm}</h2><p>{offers[offer].offer}</p><nav>{offers[offer].objections.map((item,index)=><button key={nativeLabel(level,item)} className={objection===index?"active":""} onClick={()=>setObjection(index)}>{nativeLabel(level,"OBJECIÓN ")}{index+1}</button>)}</nav></section><article><span>{offers[offer].lead.toUpperCase()}</span><blockquote>“{offers[offer].objections[objection]}”</blockquote><h2>{nativeLabel(level,"Tu respuesta debe incluir:")}</h2><ul><li>{nativeLabel(level,"una concesión parcial;")}</li><li>{nativeLabel(level,"un argumento que el inversor no haya considerado;")}</li><li>{nativeLabel(level,"una condición para avanzar.")}</li></ul><p>{nativeInstruction('deal',level,stage,"FOLLOW-UP DEL PROFESOR: “¿Qué prueba concreta me darías y qué pasaría si no funciona?”",offer)}</p></article></div></section>}

    {stage===3&&<section className="deal-page clause-room"><header><span>{nativeLabel(level,"GIRO 01 · 6 MIN")}</span><h1>{nativeLabel(level,"La carpeta tenía una página más.")}</h1><p>{nativeInstruction('deal',level,stage,"Antes de abrirla, anticipa qué condición te haría rechazar una gran oferta. Después decide si aceptas, modificas o eliminas la cláusula real.",offer)}</p></header><div className="sealed-file"><div><small>{nativeLabel(level,"ANEXO CONFIDENCIAL")}</small><h2>{offers[offer].firm}</h2><span>{nativeLabel(level,"CLÁUSULA 9.4")}</span></div><button onClick={()=>setClause(true)}>{clause?nativeLabel(level,"DOCUMENTO ABIERTO"):nativeLabel(level,"ROMPER EL SELLO")}</button></div>{clause&&<div className="clause-reveal"><span>{nativeLabel(level,"NUEVA CONDICIÓN")}</span><h2>{offers[offer].clause}</h2><p>{nativeInstruction('deal',level,stage,"El profesor afirma: “Sin esta cláusula, la valoración de la empresa baja considerablemente”.",offer)}</p><h3>{nativeInstruction('deal',level,stage,"Aclara qué parte exacta rechazas, explica la consecuencia y presenta dos alternativas. ¿Cuál retirarías primero si el inversor se niega?",offer)}</h3></div>}</section>}

    {stage===4&&<section className="deal-page veto-room"><header><span>{nativeLabel(level,"GIRO 02 · 6 MIN")}</span><h1>{nativeLabel(level,"Tu socio no estaba de acuerdo.")}</h1><p>{nativeInstruction('deal',level,stage,"Elige dos líneas rojas antes de escuchar su ultimátum. El profesor deja de ser inversor y se convierte en tu cofundador/a.",offer)}</p></header><div className="red-lines"><span>{nativeLabel(level,"PROTEGE SOLO DOS")}</span>{["CONTROL OPERATIVO","DATOS DE USUARIOS","MISIÓN DEL PROYECTO","CRECIMIENTO DEL EQUIPO"].map(item=><button key={nativeLabel(level,item)} className={protectedItems.includes(item)?"active":""} disabled={!protectedItems.includes(item)&&protectedItems.length===2} onClick={()=>protect(item)}>{protectedItems.includes(item)?"◆ ":"◇ "}{nativeLabel(level,item)}</button>)}</div><button className="veto-button" onClick={()=>setVeto(true)}>{veto?nativeLabel(level,"VETO SOBRE LA MESA"):nativeLabel(level,"ESCUCHAR AL COFUNDADOR")}</button>{veto&&<article className="cofounder"><span>{nativeLabel(level,"PROFESOR · COFUNDADOR/A")}</span><blockquote>{nativeInstruction('deal',level,stage,"“Si entregamos el control o los datos, me voy. Prefiero crecer más despacio que dejar de reconocer nuestro proyecto.”",offer)}</blockquote><h2>{nativeInstruction('deal',level,stage,"Explica qué proteges y qué estás dispuesto/a a ceder. Reformula su preocupación para demostrar que la entendiste y busca una condición común.",offer)}</h2><p>{nativeInstruction('deal',level,stage,"DESAFÍO: el profesor rechaza tu primera propuesta. Pregunta qué necesitaría para quedarse.",offer)}</p></article>}</section>}

    {stage===5&&<section className="deal-page signature-room"><header><span>{nativeLabel(level,"DECISIÓN FINAL · 6 MIN")}</span><h1>{nativeLabel(level,"La mesa cierra en tres minutos.")}</h1><p>{nativeInstruction('deal',level,stage,"Elige una salida y defiéndela. Tu decisión debe ser coherente con las condiciones que protegiste, aunque el profesor te presione.",offer)}</p></header><div className="decision-trio">{(["ACEPTAR","CONTRAOFERTAR","RETIRARSE"] as const).map(item=><button key={nativeLabel(level,item)} className={decision===item?"active":""} onClick={()=>setDecision(item)}><span>{item==="ACEPTAR"?nativeLabel(level,"FIRMA"):item==="CONTRAOFERTAR"?nativeLabel(level,"UNA ÚLTIMA CONDICIÓN"):nativeLabel(level,"SIN ACUERDO")}</span><b>{nativeLabel(level,item)}</b></button>)}</div>{decision&&<section className="closing-table"><div><small>{nativeLabel(level,"TU CIERRE")}</small><h2>{decision==="ACEPTAR"?nativeLabel(level,`Aceptas la oferta de ${offers[offer].firm}, pero debes explicar cómo protegerás el proyecto.`):decision==="CONTRAOFERTAR"?`Presenta una última versión con dos concesiones y una línea roja.`:`Rechaza la oferta sin romper la relación y deja abierta una alternativa futura.`}</h2><p>{nativeInstruction('deal',level,stage,"Resume en sesenta segundos: acuerdo, condiciones, responsabilidades y próximo paso.",offer)}</p></div><aside><button onClick={()=>setUltimatum(true)}>{ultimatum?nativeLabel(level,"ULTIMÁTUM REVELADO"):nativeLabel(level,"PROFESOR · ÚLTIMA PRESIÓN")}</button>{ultimatum&&<p>{nativeInstruction('deal',level,stage,"“La oferta caduca ahora. Si pides esa condición, invertiremos en tu competidor mañana.”",offer)}</p>}<h3>{nativeInstruction('deal',level,stage,"¿Mantienes tu decisión? Si la cambias, identifica el dato que resultó decisivo.",offer)}</h3></aside></section>}</section>}

    {stage===6&&<section className="deal-page deal-final"><header><span>{nativeLabel(level,"DESPUÉS DEL ACUERDO · CONVERSACIÓN ABIERTA · 10 MIN")}</span><h1>{nativeLabel(level,"Lo que realmente negociamos")}</h1><p>{nativeInstruction('deal',level,stage,"Dejamos atrás la empresa ficticia. Elige una pregunta, cuenta experiencias y abre la repregunta cuando la conversación pida más profundidad.",offer)}</p></header><div className="deal-final-grid">{finalQuestions.map(([question,follow],index)=><button key={question} className={finalOpen===index?"open":""} onClick={()=>setFinalOpen(finalOpen===index?null:index)}><span>{String(index+1).padStart(2,"0")}</span><h2>{question}</h2>{finalOpen===index&&<p>{follow} {nativeLabel(level," · ¿Estás de acuerdo con el profesor?")}</p>}</button>)}</div><aside className="afterword"><img src="/brand/mascot/pointing.webp" alt="Mascota oficial de SPANISHCUE"/><div><small>{nativeLabel(level,"ÚLTIMO MINUTO")}</small><h2>{nativeLabel(level,"Una condición justa para ambos")}</h2><p>{nativeInstruction('deal',level,stage,"Piensa en una negociación real pendiente o posible. Explica qué quieres, qué necesita la otra parte y cuál sería un acuerdo que podrías defender mañana.",offer)}</p></div></aside></section>}

    <button className="deal-support-trigger" onClick={()=>setSupport(support?null:"CONTRAOFERTAR")}>{support?nativeLabel(level,"CERRAR APOYO"):nativeLabel(level,"FRASES B2")}</button>{support&&<aside className="deal-support"><nav>{(Object.keys(tools) as (keyof typeof tools)[]).map(key=><button key={nativeLabel(level,key)} className={support===key?"active":""} onClick={()=>setSupport(key)}>{nativeLabel(level,key)}</button>)}</nav>{tools[support].map(item=><span key={nativeLabel(level,item)}>{nativeLabel(level,item)}</span>)}</aside>}
    <footer className="deal-controls"><button disabled={stage===0} onClick={()=>go(stage-1)}>{nativeLabel(level,"← ANTERIOR")}</button><div>{stages.map((_,index)=><button aria-label={`Ir a la etapa ${index+1}`} key={index} className={stage===index?"active":""} onClick={()=>go(index)}>{index+1}</button>)}</div>{stage<6?<button onClick={()=>go(stage+1)}>{nativeLabel(level,"SIGUIENTE →")}</button>:<Link href="/">{nativeLabel(level,"VOLVER A CONVERSACIÓN →")}</Link>}</footer>
  <NativeSpeakingSupport key={`${level}-${stage}-${offer}`} kind="deal" level={level} stage={stage} index={offer} chunks={stage===0?[['Nosotros','We'],['ofrecemos','offer'],[['un lugar tranquilo para trabajar','a quiet place to work'],['viajes con expertos locales','trips with local experts'],['contratos fáciles de entender','easy-to-understand contracts']][project] as [string,string]]:undefined}/></main>;
}

export default function MesaTresOfertas(){
 const lesson=narratives.deal;
 return <ConversationFamily id={lesson.id} title={lesson.title} levels={narrativeLevels} defaultLevel="B2">{level=><MesaTresOfertasNative key={level} level={level}/>}</ConversationFamily>;
}
