import Link from "next/link";
import { env } from "cloudflare:workers";
import { headers } from "next/headers";
import { SpanishCueBrand } from "../SpanishCueBrand";
import LanguageSwitcher from "../i18n/LanguageSwitcher";
import { localeFromHeaders } from "../i18n/messages";
import { legalOperator, publicContactEmail } from "./operator";
import PrelaunchLegalDocument from "./PrelaunchLegalDocument";
import "./legal.css";

export type LegalDocumentKind = "terms" | "privacy" | "cookies" | "subscription" | "refunds" | "legal" | "contact";

export default async function LegalDocument({ kind }: { kind: LegalDocumentKind }) {
  const locale = localeFromHeaders(await headers());
  const es = locale === "es";
  const title = {
    terms: es ? "Términos y condiciones" : "Terms and conditions",
    privacy: es ? "Política de privacidad" : "Privacy policy",
    cookies: es ? "Política de cookies" : "Cookie policy",
    subscription: es ? "Suscripción y facturación" : "Subscription and billing",
    refunds: es ? "Cancelaciones, desistimiento y reembolsos" : "Cancellation, withdrawal and refunds",
    legal: es ? "Aviso legal" : "Legal notice",
    contact: es ? "Contacto" : "Contact",
  }[kind];
  const googleEnv = env as unknown as Partial<Record<"NEXT_PUBLIC_GA4_MEASUREMENT_ID", string>>;
  const googleTrackingConfigured = /^G-[A-Z0-9]+$/i.test(googleEnv.NEXT_PUBLIC_GA4_MEASUREMENT_ID?.trim() || "");
  const operator = legalOperator(env);
  if (!operator) return <PrelaunchLegalDocument kind={kind} locale={locale} title={title} contactEmail={publicContactEmail(env)} googleTrackingConfigured={googleTrackingConfigured} />;

  const fiscalEs = operator.taxId ? ` Identificación fiscal: ${operator.taxId}.` : "";
  const fiscalEn = operator.taxId ? ` Tax identification: ${operator.taxId}.` : "";
  const registrationEs = operator.registration ? ` Registro: ${operator.registration}.` : "";
  const registrationEn = operator.registration ? ` Registration: ${operator.registration}.` : "";
  const common = <>
    <section><h2>{es ? "Titular del servicio" : "Service provider"}</h2><p>{es
      ? `${operator.legalName} (${operator.entityType}), con domicilio en ${operator.address}, ${operator.country}.${fiscalEs}${registrationEs} SPANISHCUE es el nombre comercial del servicio.`
      : `${operator.legalName} (${operator.entityType}), registered address: ${operator.address}, ${operator.country}.${fiscalEn}${registrationEn} SPANISHCUE is the service trading name.`}</p></section>
    <section><h2>{es ? "Contacto" : "Contact"}</h2><p>{es ? "Soporte y facturación" : "Support and billing"}: <a href={`mailto:${operator.supportEmail}`}>{operator.supportEmail}</a>. {es ? "Privacidad" : "Privacy"}: <a href={`mailto:${operator.privacyEmail}`}>{operator.privacyEmail}</a>.</p></section>
  </>;

  let body;
  if (kind === "terms") body = <>
    {common}
    <section><h2>{es ? "Servicio, elegibilidad y cuenta" : "Service, eligibility and account"}</h2><p>{es ? "SPANISHCUE ofrece una biblioteca digital para profesores de español. Debes tener capacidad legal para contratar y facilitar datos correctos. Eres responsable de proteger tus credenciales y de avisarnos si sospechas un acceso no autorizado." : "SPANISHCUE provides a digital library for Spanish teachers. You must have legal capacity to contract and provide accurate information. You are responsible for protecting your credentials and telling us if you suspect unauthorised access."}</p></section>
    <section><h2>{es ? "Licencia para enseñar" : "Teaching licence"}</h2><p>{es ? "Mientras tu acceso esté vigente recibes una licencia personal, limitada, no exclusiva y no transferible para abrir y reutilizar las clases con tus propios alumnos, mostrar el contenido, compartir pantalla y proyectarlo en clases online o presenciales." : "While your access is current, you receive a personal, limited, non-exclusive and non-transferable licence to open and reuse lessons with your own learners, display the content, share your screen and project it in online or in-person lessons."}</p><p>{es ? "La licencia no transfiere propiedad intelectual. No puedes revender, sublicenciar, redistribuir, republicar, subir clases completas a otra plataforma, copiar masivamente la biblioteca, eludir controles de acceso ni compartir credenciales." : "The licence does not transfer intellectual property. You may not resell, sublicense, redistribute, republish, upload complete lessons to another platform, bulk-copy the library, bypass access controls or share credentials."}</p></section>
    <section><h2>{es ? "Suscripción, precio e impuestos" : "Subscription, price and taxes"}</h2><p>{es ? "Las condiciones mostradas antes de pagar —plan, moneda, precio, período, renovación e impuestos aplicables— forman parte de la compra. SPANISHCUE PRO se factura mediante PayPal y se renueva automáticamente cada mes hasta la cancelación. Cualquier cambio futuro de precio se informa antes de aplicarse y no altera derechos ya adquiridos." : "The conditions shown before payment—plan, currency, price, period, renewal and applicable taxes—form part of the purchase. SPANISHCUE PRO is billed through PayPal and renews automatically each month until cancelled. Any future price change is disclosed before it applies and does not reduce rights already acquired."}</p></section>
    <section><h2>{es ? "Cancelación, Founder Price y reembolsos" : "Cancellation, Founder Price and refunds"}</h2><p>{es ? "Puedes cancelar online desde Mi cuenta. Se detienen las renovaciones futuras y, cuando corresponda, el acceso continúa hasta finalizar el período pagado. El Founder Price se conserva solo mientras la misma suscripción permanezca activa; si cancelas y vuelves, se aplica la oferta disponible entonces. Consulta las páginas de Suscripción y Reembolsos para el detalle y los derechos obligatorios." : "You can cancel online in My account. Future renewals stop and, where applicable, access continues through the paid period. Founder Price remains only while the same subscription stays active; if you cancel and return, the offer then available applies. See Subscription and Refunds for details and mandatory rights."}</p></section>
    <section><h2>{es ? "Disponibilidad, uso aceptable y suspensión" : "Availability, acceptable use and suspension"}</h2><p>{es ? "Podemos realizar mantenimiento y cambios razonables para mantener el producto seguro y actualizado. Podemos limitar o suspender acceso por fraude, abuso, impago, violación material de estos términos o exigencia legal, con aviso y oportunidad razonable de subsanar cuando corresponda." : "We may perform maintenance and make reasonable changes to keep the product secure and current. We may restrict or suspend access for fraud, abuse, non-payment, material breach of these terms or a legal requirement, with notice and a reasonable chance to remedy where appropriate."}</p></section>
    <section><h2>{es ? "Garantías y responsabilidad" : "Warranties and liability"}</h2><p>{es ? "No prometemos disponibilidad ininterrumpida ni resultados pedagógicos específicos. Nada excluye garantías, remedios o responsabilidades que legalmente no puedan excluirse, incluidas las protecciones obligatorias del consumidor. En la medida permitida, no respondemos por pérdidas indirectas o por usos ajenos a la finalidad normal del servicio." : "We do not promise uninterrupted availability or specific teaching outcomes. Nothing excludes warranties, remedies or liabilities that cannot legally be excluded, including mandatory consumer protections. To the extent permitted, we are not liable for indirect loss or use outside the service's normal purpose."}</p></section>
    <section><h2>{es ? "Ley aplicable y controversias" : "Governing law and disputes"}</h2><p>{es ? `Estos términos se rigen por ${operator.governingLaw} y los tribunales designados son ${operator.courts}, sin privar a consumidores de las normas imperativas ni de los foros disponibles en su lugar de residencia. Antes de iniciar un reclamo, puedes escribir a ${operator.supportEmail}.` : `These terms are governed by ${operator.governingLaw}; the designated courts are ${operator.courts}, without depriving consumers of mandatory rules or forums available where they live. Before starting a claim, you may write to ${operator.supportEmail}.`}</p></section>
  </>;
  else if (kind === "privacy") body = <>
    {common}
    <section><h2>{es ? "Responsable y datos tratados" : "Controller and data processed"}</h2><p>{es ? "Según las funciones que uses, tratamos nombre, email, identificadores de Firebase/Google/Apple, datos técnicos de solicitud como IP y navegador, estado de acceso, progreso, identificadores y estado de suscripción PayPal, mensajes de soporte y, solo con consentimiento, eventos internos y parámetros UTM." : "Depending on the features you use, we process name, email, Firebase/Google/Apple identifiers, request technical data such as IP and browser, access status, progress, PayPal subscription identifiers and status, support messages and, only with consent, internal events and UTM parameters."}</p><p>{es ? "PayPal conserva los datos completos de pago; SPANISHCUE no almacena números completos de tarjetas ni credenciales de PayPal." : "PayPal keeps complete payment data; SPANISHCUE does not store full card numbers or PayPal credentials."}</p></section>
    <section><h2>{es ? "Finalidades y bases jurídicas" : "Purposes and legal bases"}</h2><ul><li>{es ? "Contrato: cuenta, autenticación, acceso, progreso solicitado, facturación y suscripción." : "Contract: account, authentication, access, requested progress, billing and subscription."}</li><li>{es ? "Obligación legal: registros contables, fiscales, reclamos y cumplimiento." : "Legal obligation: accounting, tax, claims and compliance records."}</li><li>{es ? "Interés legítimo: seguridad, prevención de fraude y defensa del servicio, ponderado frente a tus derechos." : "Legitimate interests: security, fraud prevention and protecting the service, balanced against your rights."}</li><li>{es ? "Consentimiento: analítica interna opcional, atribución UTM y cualquier tecnología publicitaria futura." : "Consent: optional internal analytics, UTM attribution and any future advertising technology."}</li></ul></section>
    <section><h2>{es ? "Conservación" : "Retention"}</h2><p>{es ? "La sesión segura dura hasta 55 minutos; la elección de cookies, 180 días; y el idioma, un año. Los eventos consentidos viven durante la sesión y la atribución UTM local hasta borrar el almacenamiento o retirar el consentimiento. Cuenta, acceso, progreso, pagos y soporte se conservan durante la relación y después solo durante los plazos legales o para resolver reclamos; luego se eliminan o anonimizan." : "The secure session lasts up to 55 minutes; the cookie choice, 180 days; and language, one year. Consented events last for the session and local UTM attribution until storage is cleared or consent withdrawn. Account, access, progress, payments and support data are kept during the relationship and afterwards only for legal retention periods or resolving claims, then deleted or anonymised."}</p></section>
    <section><h2>{es ? "Proveedores y transferencias" : "Providers and transfers"}</h2><div className="legal-table-wrap"><table><thead><tr><th>{es ? "Servicio" : "Service"}</th><th>{es ? "Finalidad / datos" : "Purpose / data"}</th><th>{es ? "Rol" : "Role"}</th></tr></thead><tbody><tr><td>OpenAI Sites / Cloudflare</td><td>{es ? "Hosting, CDN, registros técnicos y base de datos" : "Hosting, CDN, technical logs and database"}</td><td>{es ? "Infraestructura / encargado" : "Infrastructure / processor"}</td></tr><tr><td>Google Firebase</td><td>{es ? "Autenticación e identidad de cuenta" : "Authentication and account identity"}</td><td>{es ? "Encargado / proveedor de identidad" : "Processor / identity provider"}</td></tr><tr><td>Google Fonts</td><td>{es ? "Entrega de tipografías en clases concretas; IP y datos técnicos de solicitud" : "Font delivery in specific lessons; IP and technical request data"}</td><td>{es ? "Proveedor externo" : "External provider"}</td></tr>{googleTrackingConfigured && <tr><td>Google Analytics</td><td>{es ? "Medición opcional con consentimiento" : "Optional consent-based measurement"}</td><td>{es ? "Proveedor de medición" : "Measurement provider"}</td></tr>}<tr><td>PayPal</td><td>{es ? "Pago, suscripción, antifraude e identificadores" : "Payment, subscription, fraud prevention and identifiers"}</td><td>{es ? "Proveedor de pagos; responsable independiente para ciertos fines" : "Payment provider; independent controller for some purposes"}</td></tr></tbody></table></div><p>{es ? "Estos proveedores pueden tratar datos fuera de tu país. Usamos sus salvaguardas aplicables y revisamos las transferencias según los mercados habilitados." : "These providers may process data outside your country. We rely on their applicable safeguards and review transfers for enabled markets."}</p></section>
    <section><h2>{es ? "Publicidad y decisiones automáticas" : "Advertising and automated decisions"}</h2><p>{googleTrackingConfigured
      ? (es ? "La medición de Google solo se activa según la elección de consentimiento. No vendemos datos personales ni tomamos decisiones con efectos legales mediante perfilado automatizado." : "Google measurement activates only according to the consent choice. We do not sell personal data or make decisions with legal effects through automated profiling.")
      : (es ? "No hay actualmente Meta Pixel, Google Ads, GA4 ni otros píxeles publicitarios activos. No vendemos datos personales ni tomamos decisiones con efectos legales mediante perfilado automatizado." : "Meta Pixel, Google Ads, GA4 and other advertising pixels are not currently active. We do not sell personal data or make decisions with legal effects through automated profiling.")}</p></section>
    <section><h2>{es ? "Tus derechos" : "Your rights"}</h2><p>{es ? `Puedes pedir acceso, rectificación, eliminación, limitación, oposición o portabilidad cuando corresponda, y retirar el consentimiento sin afectar el tratamiento anterior, escribiendo a ${operator.privacyEmail}. También puedes reclamar ante la autoridad competente de tu residencia.` : `You may request access, correction, deletion, restriction, objection or portability where applicable, and withdraw consent without affecting earlier processing, by writing to ${operator.privacyEmail}. You may also complain to the authority competent where you live.`}</p></section>
  </>;
  else if (kind === "cookies") body = <>
    {common}
    <section><h2>{es ? "Tecnologías que usamos" : "Technologies we use"}</h2><div className="legal-table-wrap"><table><thead><tr><th>{es ? "Nombre" : "Name"}</th><th>{es ? "Categoría y finalidad" : "Category and purpose"}</th><th>{es ? "Duración" : "Duration"}</th></tr></thead><tbody>
      <tr><td>__session</td><td>{es ? "Esencial · sesión Firebase segura" : "Essential · secure Firebase session"}</td><td>55 min</td></tr><tr><td>__Host-spanishcue-claim-*</td><td>{es ? "Esencial · vincula una compra verificada con tu cuenta" : "Essential · links a verified purchase to your account"}</td><td>{es ? "30 días" : "30 days"}</td></tr><tr><td>spanishcue_locale</td><td>{es ? "Esencial · idioma elegido" : "Essential · chosen language"}</td><td>{es ? "1 año" : "1 year"}</td></tr><tr><td>spanishcue-consent-v1</td><td>{es ? "Esencial · guarda tu elección" : "Essential · saves your choice"}</td><td>{es ? "180 días" : "180 days"}</td></tr><tr><td>Firebase IndexedDB/local storage</td><td>{es ? "Esencial · continuidad de autenticación" : "Essential · authentication continuity"}</td><td>{es ? "Hasta cerrar sesión o borrar datos" : "Until sign-out or data clearing"}</td></tr><tr><td>chespanish-favorites / chespanish-plan</td><td>{es ? "Funcional solicitada · favoritos y plan local" : "Requested functionality · local favourites and plan"}</td><td>{es ? "Hasta borrar datos" : "Until data clearing"}</td></tr><tr><td>conversation-world / founder-pill</td><td>{es ? "Funcional · actividad y cierre del pill" : "Functional · activity and pill dismissal"}</td><td>{es ? "Sesión" : "Session"}</td></tr><tr><td>Google Fonts</td><td>{es ? "Solicitud de red · tipografías de clases concretas; no crea almacenamiento propio de SPANISHCUE" : "Network request · fonts for specific lessons; creates no SPANISHCUE storage"}</td><td>{es ? "Durante la solicitud" : "During the request"}</td></tr><tr><td>spanishcue.marketing.events.v1</td><td>{es ? "Analítica opcional · eventos internos" : "Optional analytics · internal events"}</td><td>{es ? "Sesión" : "Session"}</td></tr><tr><td>spanishcue.marketing.attribution.v1</td><td>{es ? "Marketing opcional · atribución UTM" : "Optional marketing · UTM attribution"}</td><td>{es ? "Hasta borrar datos o retirar consentimiento" : "Until data clearing or consent withdrawal"}</td></tr>{googleTrackingConfigured && <tr><td>Google measurement</td><td>{es ? "Analítica o marketing opcionales" : "Optional analytics or marketing"}</td><td>{es ? "Según consentimiento y configuración de Google" : "According to consent and Google configuration"}</td></tr>}
    </tbody></table></div></section>
    <section><h2>{es ? "Elección y cambio" : "Choice and change"}</h2><p>{es ? "Antes de elegir, analítica y marketing están desactivados. Aceptar, rechazar y configurar tienen igual acceso; ninguna categoría opcional viene marcada. Puedes cambiar la elección en cualquier momento mediante “Configurar privacidad” en el pie. Al retirar consentimiento se detiene la escritura futura; también puedes borrar los datos ya guardados desde el navegador." : "Before you choose, analytics and marketing are off. Accept, reject and configure are equally available; no optional category is preselected. You can change your choice at any time using Privacy settings in the footer. Withdrawing consent stops future writing; you can also clear data already stored through your browser."}</p><p>{googleTrackingConfigured ? (es ? "La medición de Google solo se carga después de aceptar la categoría opcional correspondiente." : "Google measurement loads only after the corresponding optional category is accepted.") : (es ? "Actualmente no se cargan píxeles publicitarios externos." : "No external advertising pixels are currently loaded.")}</p></section>
  </>;
  else if (kind === "subscription") body = <>
    {common}
    <section><h2>{es ? "Plan y cobro recurrente" : "Plan and recurring charge"}</h2><p>{es ? "Antes de confirmar, el checkout muestra SPANISHCUE PRO, US$15 por mes, facturación mensual, renovación automática hasta cancelación y PayPal como proveedor. La fecha inicial es la aprobación en PayPal; las siguientes aparecen en PayPal y Mi cuenta. Los impuestos se muestran o incluyen según exija la jurisdicción." : "Before confirmation, checkout shows SPANISHCUE PRO, US$15 per month, monthly billing, automatic renewal until cancellation and PayPal as provider. The start date is PayPal approval; later dates appear in PayPal and My account. Taxes are shown or included as required by the jurisdiction."}</p></section>
    <section><h2>Founder Price</h2><p>{es ? "La oferta se limita a los primeros 1.000 profesores cuya primera cuota de US$15 haya sido confirmada. La aprobación de la suscripción por sí sola no ocupa una plaza y el contador no se simula. US$15/mes se mantiene mientras esa misma suscripción siga activa. Si cancelas y vuelves, se aplica la oferta disponible entonces." : "The offer is limited to the first 1,000 teachers whose first US$15 payment is confirmed. Subscription approval alone does not claim a place and the counter is not simulated. US$15/month remains while that same subscription stays active. If you cancel and return, the offer available then applies."}</p></section>
    <section><h2>{es ? "Cancelación online" : "Online cancellation"}</h2><p>{es ? "Mi cuenta → Suscripción → Cancelar envía la baja directamente a PayPal. Tras una segunda confirmación, se detienen renovaciones y la pantalla muestra una referencia y, cuando existe, la fecha hasta la que continúa el acceso pagado. No necesitas llamar ni escribir." : "My account → Subscription → Cancel sends the cancellation directly to PayPal. After a second confirmation, renewals stop and the screen shows a reference and, when available, the paid-access end date. You do not need to call or email."}</p></section>
    <section><h2>{es ? "Pagos realizados y cambios" : "Completed payments and changes"}</h2><p>{es ? "Cancelar no revierte automáticamente cargos ya efectuados. Reembolsos y desistimiento se rigen por la política específica y la ley obligatoria. Cualquier cambio futuro de precio se informa antes de la siguiente renovación afectada." : "Cancellation does not automatically reverse completed charges. Refunds and withdrawal are governed by the specific policy and mandatory law. Any future price change is disclosed before the next affected renewal."}</p></section>
  </>;
  else if (kind === "refunds") body = <>
    {common}<section><h2>{es ? "Política comercial" : "Commercial policy"}</h2><p>{es ? operator.refundPolicyEs : operator.refundPolicyEn}</p></section><section><h2>{es ? "Desistimiento o revocación" : "Withdrawal or revocation"}</h2><p>{es ? operator.withdrawalPolicyEs : operator.withdrawalPolicyEn}</p></section><section><h2>{es ? "Derechos obligatorios" : "Mandatory rights"}</h2><p>{es ? "Nada limita derechos irrenunciables del consumidor. Los cargos no autorizados o duplicados y la falta sustancial de prestación se revisan y reembolsan cuando la ley o PayPal lo exijan. SPANISHCUE no presume una renuncia al desistimiento por el mero acceso." : "Nothing limits mandatory consumer rights. Unauthorised or duplicate charges and material failure to provide the service are reviewed and refunded when required by law or PayPal. SPANISHCUE does not assume withdrawal rights are waived merely because the service was accessed."}</p></section><section><h2>{es ? "Cómo solicitarlo" : "How to request it"}</h2><p>{es ? `Escribe a ${operator.supportEmail} desde el email de la cuenta e indica fecha e identificador de operación. No envíes datos completos de tarjeta ni contraseñas.` : `Write to ${operator.supportEmail} from the account email and include the date and transaction identifier. Do not send full card data or passwords.`}</p></section>
  </>;
  else if (kind === "legal") body = <>{common}<section><h2>{es ? "Marca, propiedad intelectual y actividad" : "Brand, intellectual property and activity"}</h2><p>{es ? "SPANISHCUE es una plataforma digital de recursos didácticos para profesores de español. El nombre, textos, interfaces, imágenes y recursos propios están protegidos; el uso docente permitido se define en los Términos." : "SPANISHCUE is a digital teaching-resource platform for Spanish teachers. Its name, original text, interfaces, images and resources are protected; permitted teaching use is defined in the Terms."}</p></section><section><h2>{es ? "Ley y supervisión" : "Law and supervision"}</h2><p>{es ? `Ley aplicable: ${operator.governingLaw}. Tribunales designados: ${operator.courts}, sin perjuicio de derechos obligatorios del consumidor.` : `Governing law: ${operator.governingLaw}. Designated courts: ${operator.courts}, without prejudice to mandatory consumer rights.`}</p></section></>;
  else body = <>{common}<section><h2>{es ? "Qué canal usar" : "Which channel to use"}</h2><ul><li>{es ? `Producto, acceso, facturación, cancelación o reembolso: ${operator.supportEmail}.` : `Product, access, billing, cancellation or refund: ${operator.supportEmail}.`}</li><li>{es ? `Privacidad y derechos: ${operator.privacyEmail}.` : `Privacy and rights: ${operator.privacyEmail}.`}</li></ul><p>{es ? "Incluye el email de la cuenta y una descripción breve. No envíes contraseñas ni datos completos de pago." : "Include the account email and a short description. Do not send passwords or full payment details."}</p><a className="legal-contact" href={`mailto:${operator.supportEmail}`}>{es ? "Escribir a soporte" : "Email support"}</a></section></>;

  return <main className="legal-page"><header><Link href="/"><SpanishCueBrand variant="compact" /></Link><LanguageSwitcher /></header><article><span>SPANISHCUE · LEGAL</span><h1>{title}</h1><p className="legal-updated">{es ? "Vigente y actualizado desde" : "Effective and last updated"}: {operator.effectiveDate}</p>{body}<nav className="legal-related" aria-label={es ? "Documentos legales" : "Legal documents"}><Link href="/terms">{es ? "Términos" : "Terms"}</Link><Link href="/privacy">{es ? "Privacidad" : "Privacy"}</Link><Link href="/cookies">Cookies</Link><Link href="/subscription-terms">{es ? "Suscripción" : "Subscription"}</Link><Link href="/refunds">{es ? "Reembolsos" : "Refunds"}</Link></nav><footer><Link href="/">← {es ? "Volver a la biblioteca" : "Back to library"}</Link></footer></article></main>;
}
