import Link from "next/link";
import { SpanishCueBrand } from "../SpanishCueBrand";
import LanguageSwitcher from "../i18n/LanguageSwitcher";
import type { LegalDocumentKind } from "./LegalDocument";

export default function PrelaunchLegalDocument({
  kind,
  locale,
  title,
  contactEmail,
  googleTrackingConfigured,
}: {
  kind: LegalDocumentKind;
  locale: "es" | "en";
  title: string;
  contactEmail: string | null;
  googleTrackingConfigured: boolean;
}) {
  const es = locale === "es";
  const contact = contactEmail
    ? <a href={`mailto:${contactEmail}`}>{contactEmail}</a>
    : <span>{es ? "el canal de contacto (todavía no configurado)" : "the contact channel (not yet configured)"}</span>;
  const contactSection = <section><h2>{es ? "Contacto" : "Contact"}</h2><p>{es ? <>Para soporte, privacidad o solicitudes sobre tu cuenta, escribe a {contact}.</> : <>For support, privacy, or account requests, email {contact}.</>}</p></section>;

  let body;
  if (kind === "privacy") body = <>
    <section><h2>{es ? "Qué datos trata SPANISHCUE" : "Data SPANISHCUE processes"}</h2><p>{es ? "Al crear o usar una cuenta se tratan el email, el nombre si el proveedor lo facilita, el identificador de Firebase, el método de acceso y el estado de la cuenta. Si eliges email y contraseña, la contraseña la procesa Google Firebase Authentication; SPANISHCUE no recibe ni guarda una copia legible." : "When you create or use an account, we process your email, name when supplied by the provider, Firebase identifier, sign-in method, and account status. If you choose email and password, Google Firebase Authentication processes the password; SPANISHCUE does not receive or store a readable copy."}</p><p>{es ? "La infraestructura puede tratar IP, navegador, dispositivo, ruta solicitada y registros técnicos necesarios para entregar y proteger el servicio. La aplicación guarda progreso de clases y estado de acceso cuando corresponde." : "Infrastructure may process IP address, browser, device, requested path, and technical logs needed to deliver and protect the service. The application stores lesson progress and access status where applicable."}</p></section>
    <section><h2>{es ? "Para qué se usan" : "How the data is used"}</h2><ul><li>{es ? "Crear la cuenta, autenticarte y mantener una sesión segura." : "Create your account, authenticate you, and maintain a secure session."}</li><li>{es ? "Dar acceso a las clases gratuitas, recordar progreso solicitado y proteger contenido restringido." : "Provide free-lesson access, remember requested progress, and protect restricted content."}</li><li>{es ? "Prevenir abuso, investigar errores y mantener la seguridad y disponibilidad." : "Prevent abuse, investigate errors, and maintain security and availability."}</li><li>{es ? "Medir uso y atribución de campañas únicamente si das el consentimiento opcional correspondiente." : "Measure usage and campaign attribution only when you give the corresponding optional consent."}</li></ul></section>
    <section><h2>{es ? "Cookies, almacenamiento y analítica" : "Cookies, storage, and analytics"}</h2><p>{es ? "Las cookies esenciales mantienen la sesión, el idioma y tu elección de privacidad. Firebase puede usar almacenamiento local para la continuidad de autenticación. Favoritos, plan de clase y algunas actividades se guardan localmente en el navegador." : "Essential cookies maintain the session, language, and privacy choice. Firebase may use local storage for authentication continuity. Favourites, lesson plans, and some activities are stored locally in the browser."}</p><p>{googleTrackingConfigured
      ? (es ? "La medición de Google está configurada, pero sus etiquetas opcionales solo se cargan tras aceptar analítica o marketing. Los cuatro estados de Consent Mode v2 empiezan denegados y se actualizan después de tu elección." : "Google measurement is configured, but its optional tags load only after analytics or marketing is accepted. All four Consent Mode v2 states start denied and update after your choice.")
      : (es ? "La analítica interna y la atribución UTM están desactivadas hasta que las aceptes. El código admite una única configuración de Google Tag Manager, Google Analytics o Google Ads mediante variables de entorno; no hay identificadores de medición de Google configurados actualmente. Si se configuran, los cuatro estados de Consent Mode v2 empiezan denegados y solo se actualizan tras tu elección." : "Internal analytics and UTM attribution stay off until accepted. The code supports one Google Tag Manager, Google Analytics, or Google Ads configuration through environment variables; no Google measurement identifiers are currently configured. If configured, all four Consent Mode v2 states start denied and update only after your choice.")}</p></section>
    <section><h2>{es ? "Proveedores" : "Providers"}</h2><div className="legal-table-wrap"><table><thead><tr><th>{es ? "Proveedor" : "Provider"}</th><th>{es ? "Uso real" : "Actual use"}</th></tr></thead><tbody><tr><td>OpenAI Sites / Cloudflare</td><td>{es ? "Hosting, CDN, base de datos y registros técnicos" : "Hosting, CDN, database, and technical logs"}</td></tr><tr><td>Google Firebase</td><td>{es ? "Autenticación por email, contraseña o Google" : "Email, password, or Google authentication"}</td></tr><tr><td>Google Fonts</td><td>{es ? "Tipografías solicitadas por determinadas clases; puede recibir IP y datos técnicos de la solicitud" : "Fonts requested by specific lessons; it may receive IP and request technical data"}</td></tr>{googleTrackingConfigured && <tr><td>Google Tag / Analytics / Ads</td><td>{es ? "Medición y atribución opcionales con consentimiento" : "Optional consent-based measurement and attribution"}</td></tr>}</tbody></table></div><p>{es ? "PayPal está implementado en modo de pruebas, pero el checkout público no está activo y SPANISHCUE no recoge actualmente datos de pago de visitantes." : "PayPal is implemented in test mode, but public checkout is not active and SPANISHCUE does not currently collect visitors’ payment data."}</p></section>
    <section><h2>{es ? "Conservación y control" : "Retention and control"}</h2><p>{es ? "La sesión segura dura hasta 55 minutos; la preferencia de idioma, un año; y la elección de privacidad, 180 días. Los eventos consentidos duran la sesión y la atribución local permanece hasta que borres los datos o retires el consentimiento. Los datos de cuenta, acceso y progreso se conservan mientras sean necesarios para prestar el servicio, protegerlo o atender obligaciones aplicables." : "The secure session lasts up to 55 minutes; the language preference, one year; and the privacy choice, 180 days. Consented events last for the session, and local attribution remains until data is cleared or consent is withdrawn. Account, access, and progress data are kept while needed to provide and protect the service or meet applicable obligations."}</p><p>{es ? <>Puedes cambiar el consentimiento desde “Configurar privacidad”. También puedes solicitar acceso, corrección o eliminación de los datos de tu cuenta a través de {contact}; la solicitud se verificará antes de actuar.</> : <>You can change consent through “Privacy settings”. You may also request access to, correction of, or deletion of your account data through {contact}; the request will be verified before action is taken.</>}</p></section>
    {contactSection}
  </>;
  else if (kind === "terms") body = <>
    <section><h2>{es ? "Servicio actual" : "Current service"}</h2><p>{es ? "SPANISHCUE ofrece una biblioteca digital de clases visuales para profesores de español. La cuenta gratuita permite acceder a las muestras señaladas como gratuitas sin tarjeta. El plan PRO y el precio fundador previsto de US$15 por mes se muestran para explicar el lanzamiento, pero el checkout público aún no está activo y crear una cuenta no inicia una suscripción ni un cobro." : "SPANISHCUE provides a digital library of visual lessons for Spanish teachers. The free account provides access to samples marked as free without a card. The planned PRO plan and US$15 monthly Founder Price are displayed to explain the launch, but public checkout is not active; creating an account starts neither a subscription nor a charge."}</p></section>
    <section><h2>{es ? "Cuenta y uso permitido" : "Account and permitted use"}</h2><p>{es ? "Debes proporcionar datos correctos, proteger tus credenciales y usar el servicio de manera legal. Puedes abrir las clases disponibles, compartir pantalla y proyectarlas con tus propios alumnos en clases online o presenciales." : "You must provide accurate information, protect your credentials, and use the service lawfully. You may open available lessons, share your screen, and project them for your own learners in online or in-person lessons."}</p></section>
    <section><h2>{es ? "Propiedad intelectual" : "Intellectual property"}</h2><p>{es ? "El acceso no transfiere la propiedad de los textos, interfaces, imágenes ni recursos originales. No puedes revender, sublicenciar, redistribuir, republicar, copiar masivamente la biblioteca, subir clases completas a otra plataforma, compartir credenciales ni eludir controles de acceso." : "Access does not transfer ownership of original text, interfaces, images, or resources. You may not resell, sublicense, redistribute, republish, bulk-copy the library, upload complete lessons to another platform, share credentials, or bypass access controls."}</p></section>
    <section><h2>{es ? "Disponibilidad, cambios y abuso" : "Availability, changes, and abuse"}</h2><p>{es ? "Podemos realizar mantenimiento, corregir errores y cambiar razonablemente el contenido o las funciones. Podemos limitar o terminar una cuenta por fraude, abuso, uso ilegal, vulneración material de estos términos o riesgo para el servicio. Cuando sea razonable, se dará aviso y oportunidad de corregir el problema." : "We may perform maintenance, fix errors, and reasonably change content or features. We may restrict or terminate an account for fraud, abuse, unlawful use, material breach of these terms, or risk to the service. Where reasonable, notice and an opportunity to remedy will be provided."}</p></section>
    <section><h2>{es ? "PRO, renovación y cancelación" : "PRO, renewal, and cancellation"}</h2><p>{es ? "No hay actualmente una suscripción pública disponible. Antes de activar pagos se publicarán la identidad y domicilio del operador, las condiciones finales del plan, impuestos aplicables, renovación, cancelación, reembolsos, ley y contacto. Ninguna renovación automática comenzará sin una confirmación explícita en el proveedor de pago." : "No public subscription is currently available. Before payments are enabled, the operator’s identity and address, final plan terms, applicable taxes, renewal, cancellation, refunds, governing law, and contact details will be published. No automatic renewal will begin without explicit confirmation at the payment provider."}</p></section>
    <section><h2>{es ? "Responsabilidad" : "Liability"}</h2><p>{es ? "SPANISHCUE no garantiza disponibilidad ininterrumpida ni resultados pedagógicos específicos. Nada en estos términos limita derechos o responsabilidades que la ley aplicable no permita limitar." : "SPANISHCUE does not guarantee uninterrupted availability or specific teaching outcomes. Nothing in these terms limits rights or liabilities that applicable law does not allow to be limited."}</p></section>
    {contactSection}
  </>;
  else if (kind === "cookies") body = <>
    <section><h2>{es ? "Tecnologías actuales" : "Current technologies"}</h2><div className="legal-table-wrap"><table><thead><tr><th>{es ? "Nombre" : "Name"}</th><th>{es ? "Finalidad" : "Purpose"}</th><th>{es ? "Duración" : "Duration"}</th></tr></thead><tbody><tr><td>__session</td><td>{es ? "Sesión Firebase esencial" : "Essential Firebase session"}</td><td>55 min</td></tr><tr><td>spanishcue_locale</td><td>{es ? "Idioma elegido" : "Chosen language"}</td><td>{es ? "1 año" : "1 year"}</td></tr><tr><td>spanishcue-consent-v1</td><td>{es ? "Elección de privacidad" : "Privacy choice"}</td><td>{es ? "180 días" : "180 days"}</td></tr><tr><td>Firebase / local storage</td><td>{es ? "Continuidad de autenticación" : "Authentication continuity"}</td><td>{es ? "Hasta cerrar sesión o borrar datos" : "Until sign-out or data clearing"}</td></tr><tr><td>chespanish-favorites / chespanish-plan</td><td>{es ? "Favoritos y plan solicitados" : "Requested favourites and plan"}</td><td>{es ? "Hasta borrar datos" : "Until data clearing"}</td></tr><tr><td>spanishcue.marketing.*</td><td>{es ? "Analítica y atribución opcionales" : "Optional analytics and attribution"}</td><td>{es ? "Sesión / hasta retirada" : "Session / until withdrawal"}</td></tr></tbody></table></div></section>
    <section><h2>{es ? "Tu elección" : "Your choice"}</h2><p>{es ? "Analítica y marketing empiezan apagados. Puedes aceptar, rechazar o configurar cada categoría opcional, y volver a cambiarla desde Configurar privacidad en el pie de página. Retirar el consentimiento detiene la medición futura y borra los datos opcionales guardados por SPANISHCUE en el navegador." : "Analytics and marketing start off. You can accept, reject, or configure each optional category and change it later through Privacy settings in the footer. Withdrawing consent stops future measurement and clears optional data stored by SPANISHCUE in the browser."}</p></section>
    {contactSection}
  </>;
  else if (kind === "contact") body = <>
    <section><h2>{es ? "Soporte y privacidad" : "Support and privacy"}</h2><p>{es ? <>Para ayuda con el producto, acceso, cuenta o privacidad, escribe a {contact}. Incluye el email de tu cuenta y una descripción breve; no envíes contraseñas ni datos completos de pago.</> : <>For product, access, account, or privacy help, email {contact}. Include your account email and a short description; do not send passwords or complete payment details.</>}</p>{contactEmail && <a className="legal-contact" href={`mailto:${contactEmail}`}>{es ? "Escribir a soporte" : "Email support"}</a>}</section>
  </>;
  else body = <>
    <section><h2>{es ? "Estado previo al lanzamiento" : "Pre-launch status"}</h2><p>{es ? "El checkout público y las suscripciones PRO todavía no están activos. No se realizan cobros, renovaciones ni cancelaciones de pago a visitantes. Las condiciones comerciales completas y los datos reales del operador se publicarán antes de habilitar pagos." : "Public checkout and PRO subscriptions are not active yet. Visitors are not charged, renewed, or asked to cancel a paid plan. Complete commercial terms and verified operator details will be published before payments are enabled."}</p></section>
    {kind === "legal" && <section><h2>{es ? "Actividad y referencia curricular" : "Activity and curriculum reference"}</h2><p>{es ? "SPANISHCUE es una biblioteca digital de recursos didácticos. Utiliza el PCIC como referencia curricular y no está afiliado ni respaldado por el Instituto Cervantes." : "SPANISHCUE is a digital teaching-resource library. It uses the PCIC as a curriculum reference and is not affiliated with or endorsed by Instituto Cervantes."}</p></section>}
    {contactSection}
  </>;

  return <main className="legal-page"><header><Link href="/"><SpanishCueBrand variant="compact" /></Link><LanguageSwitcher /></header><article><span>SPANISHCUE · LEGAL</span><h1>{title}</h1><p className="legal-updated">{es ? "Vigente y actualizado desde: 15 de septiembre de 2026" : "Effective and last updated: 15 September 2026"}</p>{body}<nav className="legal-related" aria-label={es ? "Documentos legales" : "Legal documents"}><Link href="/terms">{es ? "Términos" : "Terms"}</Link><Link href="/privacy">{es ? "Privacidad" : "Privacy"}</Link><Link href="/cookies">Cookies</Link><Link href="/contact">{es ? "Contacto" : "Contact"}</Link></nav><footer><Link href="/">← {es ? "Volver a la biblioteca" : "Back to library"}</Link></footer></article></main>;
}
