"use client";

import { useEffect, useMemo, useState } from "react";
import "./news.css";

type Category = "Gramática" | "Conversación";
type Lesson = { id:number; level:string; levels?:string[]; displayLevel?:string; category:Category; title:string; subtitle:string; duration:string; tag:string; goals:string[]; warmup:string; explanation:string; practice:string[]; speaking:string[]; homework:string; special?:boolean; path?:string };

const levels = ["Todos", "A0", "A1", "A2", "B1", "B2", "C1", "C2"];
const levelNames:Record<string,string> = { A0:"Primeros pasos", A1:"Inicial", A2:"Básico", B1:"Intermedio", B2:"Intermedio alto", C1:"Avanzado", C2:"Dominio" };

const latestNews = [
  {lessonId:20,kicker:"NUEVA CLASE · B1",route:"CONVERSACIÓN + OPINIÓN",title:"El Reino de las Preguntas Prohibidas",copy:"15 mundos, 60 preguntas profundas, 7 bloques prohibidos y power-ups bilingües para construir opiniones con matices.",symbol:"🏰",words:["postura","matiz","conclusión"]},
  {lessonId:19,kicker:"NUEVA CLASE · A0",route:"ROLEPLAYS + ESPAÑOL ARGENTINO",title:"Argento Roleplays",copy:"15 situaciones reales, 210 intervenciones bilingües y práctica guiada para hablar desde cero sin quedarse en blanco.",symbol:"🎭",words:["mirá","robá chunks","hablá"]},
  {lessonId:18,kicker:"NUEVA CLASE · B1",route:"GRAMÁTICA + CONVERSACIÓN",title:"El Pasado",copy:"Indefinido e imperfecto en una experiencia visual completa con patrones, comparación, ejercicios y producción de historias.",symbol:"B1",words:["escenario","evento","historia"]},
  {lessonId:17,kicker:"NUEVA EXPERIENCIA · A1–A2",route:"CONVERSACIÓN + JUEGO",title:"La Ruleta de Tu Vida",copy:"18 temas, una ruleta interactiva y recursos bilingües para hablar, reaccionar y seguir la conversación sin presión.",symbol:"🎡",words:["girar","elegir","hablar"]},
  {lessonId:16,kicker:"NUEVA EXPERIENCIA · A0–A1",route:"ESPAÑOL ARGENTINO",title:"ARGENTO",copy:"12 mundos argentinos con vocabulario bilingüe, preguntas, reacciones, roleplays y slang para hablar desde el primer día.",symbol:"🇦🇷",words:["mate","conectar","hablar"]},
  {lessonId:15,kicker:"NUEVA CLASE · A1",route:"CONVERSACIÓN INICIAL",title:"Let’s Talk · A1",copy:"15 temas bilingües y 150 preguntas cortas para que el alumno empiece a hablar desde el primer minuto.",symbol:"A1",words:["entender","responder","hablar"]},
  {lessonId:14,kicker:"NUEVA CLASE · A2",route:"CONVERSACIÓN BÁSICA",title:"Let’s Talk · A2",copy:"15 mundos bilingües y 150 preguntas accesibles. El alumno elige solo 3 y empieza a hablar.",symbol:"A2",words:["elegir","animarse","hablar"]},
  {lessonId:13,kicker:"ESTRENO · B1+",route:"CONVERSACIÓN",title:"Choose Your Conversation",copy:"15 mundos. El alumno elige 1 tema, solo 3 preguntas y empieza a hablar de verdad.",symbol:"💬",words:["elegir","conectar","hablar"]},
  {lessonId:3,kicker:"NUEVA RUTA · A1",route:"GRAMÁTICA + HABLA",title:"Presente con vos",copy:"Hablás, comés, vivís. Un patrón visual y sonoro para activar el español argentino.",symbol:"VOS",words:["mirá","detectá","usalo"]},
  {lessonId:11,kicker:"NUEVA CLASE · C1",route:"CONVERSACIÓN AVANZADA",title:"Preguntas que dan ganas de hablar",copy:"16 categorías y 80 preguntas profundas para pensar, elegir y conversar con libertad.",symbol:"C1",words:["pensar","profundizar","conectar"]}
];

const lessons:Lesson[] = [
  {id:20,level:"B1",category:"Conversación",title:"El Reino de las Preguntas Prohibidas",subtitle:"15 mundos profundos, 60 preguntas y recursos bilingües para opinar con matices",duration:"75 min",tag:"60 preguntas",special:true,path:"/preguntas-prohibidas",goals:["Construir una postura clara","Agregar matices y contraargumentos","Sostener conversaciones profundas"],warmup:"Elegí una verdad incómoda y explicá por qué cuesta decirla.",explanation:"Una aventura conversacional para pensar bajo presión y desarrollar respuestas complejas con apoyo B1.",practice:[],speaking:[],homework:""},
  {id:19,level:"A0",category:"Conversación",title:"Argento Roleplays",subtitle:"15 situaciones reales con diálogos largos, práctica guiada y recursos bilingües",duration:"75 min",tag:"210 intervenciones",special:true,path:"/argento-roleplays",goals:["Comprender diálogos argentinos simples","Responder con chunks cotidianos","Sostener un roleplay largo desde cero"],warmup:"Elegí una situación cotidiana y entrá en personaje.",explanation:"Una experiencia de roleplays progresivos para hablar sin depender de explicaciones gramaticales.",practice:[],speaking:[],homework:""},
  {id:18,level:"B1",category:"Gramática",title:"El Pasado",subtitle:"Indefinido + imperfecto para narrar acontecimientos y construir escenarios",duration:"80 min",tag:"Clase completa",special:true,path:"/past-b1",goals:["Distinguir acontecimiento y escenario","Conjugar indefinido e imperfecto","Contar una historia completa"],warmup:"¿Qué pasó? ¿Cómo era?",explanation:"Una experiencia visual e interactiva sobre los dos pasados esenciales.",practice:[],speaking:[],homework:""},
  {id:17,level:"A1",levels:["A1","A2"],displayLevel:"A1–A2",category:"Conversación",title:"La Ruleta de Tu Vida",subtitle:"18 temas al azar con preguntas y recursos bilingües para sostener la conversación",duration:"60 min",tag:"18 temas",special:true,path:"/life-roulette",goals:["Hablar a partir de un tema aleatorio","Usar apoyos bilingües sin frenar la conversación","Practicar vocabulario y slang argentino"],warmup:"Girá la ruleta y dejá que el tema te encuentre.",explanation:"Una experiencia conversacional lúdica para A1–A2.",practice:[],speaking:[],homework:""},
  {id:16,level:"A0",levels:["A0","A1"],displayLevel:"A0–A1",category:"Conversación",title:"ARGENTO",subtitle:"12 mundos argentinos para hablar desde el primer día con recursos bilingües",duration:"70 min",tag:"12 mundos",special:true,path:"/argento",goals:["Hablar con apoyos visuales y bilingües","Usar vocabulario argentino cotidiano","Reaccionar y sostener intercambios simples"],warmup:"Elegí tu Argentina y empezá a hablar.",explanation:"Una experiencia comunicativa para A0–A1.",practice:[],speaking:[],homework:""},
  {id:15,level:"A1",category:"Conversación",title:"Let’s Talk · A1",subtitle:"15 mundos bilingües y 150 preguntas simples para empezar a conversar",duration:"55 min",tag:"150 preguntas",special:true,path:"/a1-conversation",goals:["Comprender preguntas breves","Responder con vocabulario cotidiano","Sostener una charla a partir de tres preguntas"],warmup:"Choose a topic. Pick 3 questions. Just talk.",explanation:"Conversación guiada de nivel A1.",practice:[],speaking:[],homework:""},
  {id:14,level:"A2",category:"Conversación",title:"Let’s Talk · A2",subtitle:"15 mundos bilingües y 150 preguntas para empezar a hablar sin presión",duration:"60 min",tag:"150 preguntas",special:true,path:"/basic-conversation",goals:["Elegir un tema cercano","Responder con frases claras","Sostener una conversación con tres preguntas"],warmup:"Choose a topic. Pick 3 questions. Just talk.",explanation:"Conversación guiada de nivel A2.",practice:[],speaking:[],homework:""},
  {id:13,level:"B1",category:"Conversación",title:"Choose Your Conversation",subtitle:"Elegí 1 tema, seleccioná solo 3 preguntas y hablá libremente",duration:"60 min",tag:"15 mundos",special:true,goals:["Elegir un tema que genere curiosidad","Sostener una conversación libre","Compartir historias y opiniones"],warmup:"Choose a topic. Pick 3 questions. Just talk.",explanation:"No perfect answers. No pressure.",practice:[],speaking:[],homework:""},
  {id:1,level:"A0",category:"Gramática",title:"El, la, los, las",subtitle:"Artículos y género sin memorizar reglas eternas",duration:"50 min",tag:"Base esencial",goals:["Reconocer masculino y femenino","Usar artículos definidos e indefinidos","Formar frases simples con ser y estar"],warmup:"Mirá cinco objetos a tu alrededor. ¿Cuáles conocés en español? Decí: es un… / es una…",explanation:"En español, los sustantivos tienen género y número. Usamos el / la para algo específico y un / una para presentar algo nuevo. El artículo siempre acompaña al sustantivo: la casa, un café, los amigos.",practice:["___ mate está caliente.","Quiero comprar ___ empanada.","___ chicos están en Buenos Aires.","Hay ___ farmacia cerca."],speaking:["¿Qué objetos hay en tu casa?","Describí tres cosas de tu ciudad.","Pedí dos cosas en un café argentino."],homework:"Sacá una foto de una habitación y escribí 8 frases usando el, la, los, las, un, una, unos y unas."},
  {id:2,level:"A0",category:"Conversación",title:"Tu primera charla",subtitle:"Saludar, presentarte y sostener 60 segundos",duration:"45 min",tag:"Supervivencia",goals:["Presentarte con naturalidad","Preguntar nombre y origen","Cerrar una conversación"],warmup:"Escuchá dos saludos: Hola, ¿todo bien? / Buenas, ¿cómo andás? ¿Cuál usarías?",explanation:"Una charla no necesita frases perfectas. Necesita turnos cortos: saludo, dato personal, pregunta y reacción. En Argentina, ¿todo bien? suele funcionar como saludo más que como pregunta profunda.",practice:["Completá: Hola, me ___…","¿De dónde ___?","Mucho ___","Nos ___"],speaking:["Presentate como si llegaras a un hostel.","Conocé a un argentino en un café.","Repetí la charla, pero esta vez hacé dos preguntas."],homework:"Grabá un audio de 60 segundos presentándote sin leer."},
  {id:3,level:"A1",category:"Gramática",title:"Presente con vos",subtitle:"Hablás, comés, vivís: el patrón rioplatense",duration:"60 min",tag:"Argentina real",goals:["Conjugar verbos regulares","Usar vos con seguridad","Hablar de rutinas"],warmup:"¿Qué hacés normalmente a la mañana? Usá palabras sueltas si todavía no podés formar frases.",explanation:"Con vos, los verbos regulares llevan el acento al final: hablás, comés, vivís. El pronombre puede omitirse cuando el contexto es claro.",practice:["Vos ___ (trabajar) desde casa.","¿___ (comer) carne?","___ (vivir) en Londres.","¿Qué ___ (hacer) hoy?"],speaking:["Contá tu rutina de lunes.","Compará tu mañana con la de tu profesor.","Entrevistá a alguien sobre sus hábitos."],homework:"Escribí 10 preguntas con vos para usar en la próxima clase."},
  {id:4,level:"A1",category:"Conversación",title:"En el café",subtitle:"Pedir, reaccionar y pagar sin sonar robótico",duration:"50 min",tag:"Roleplay",goals:["Pedir comida y bebida","Preguntar precios","Resolver un problema simple"],warmup:"Elegí: café, mate o té. Explicá por qué con una frase.",explanation:"En Argentina podés pedir con Quería…, Me das… o Para mí… . Quería es amable y muy frecuente. Cerrá con gracias y reaccioná a la respuesta.",practice:["Quería ___ cortado.","¿Me ___ la cuenta?","¿Cuánto ___?","Para mí, ___ medialunas."],speaking:["Pedí desayuno para dos.","La orden llegó mal: explicá el problema.","Preguntá qué recomienda el mozo."],homework:"Creá tu pedido ideal en una cafetería porteña con cinco intervenciones."},
  {id:5,level:"A2",category:"Gramática",title:"Pasado que sirve",subtitle:"Indefinido para contar qué hiciste",duration:"60 min",tag:"Historias",goals:["Narrar acciones terminadas","Ordenar eventos","Distinguir hoy y ayer"],warmup:"Decí tres palabras sobre tu último fin de semana.",explanation:"Usamos el pretérito indefinido para acciones terminadas en un momento cerrado: ayer fui, el sábado comí, en 2025 viajé.",practice:["Ayer ___ (salir) con amigos.","El año pasado ___ (ir) a España.","¿Qué ___ (hacer) anoche?","Primero ___ y después ___."],speaking:["Contá tu último viaje en cinco pasos.","Inventá una excusa por llegar tarde.","Hacé preguntas sobre el fin de semana."],homework:"Grabá una historia de 90 segundos usando primero, después, entonces y al final."},
  {id:6,level:"A2",category:"Conversación",title:"Perderte y recuperarte",subtitle:"Pedir direcciones y entender respuestas reales",duration:"55 min",tag:"Viaje",goals:["Pedir ayuda","Confirmar información","Usar frases de recuperación"],warmup:"¿Qué hacés cuando no entendés una dirección?",explanation:"No necesitás entender cada palabra. Capturá lugar, dirección y distancia. Recuperate con: Perdón, ¿me lo repetís? / ¿Es para allá? / ¿Está lejos?",practice:["¿Cómo ___ a Plaza de Mayo?","¿Está ___ de acá?","¿Doblo a la ___?","¿Me lo ___ más despacio?"],speaking:["Llegá al subte desde tu hotel.","Confirmá tres datos antes de irte.","Dale instrucciones a un turista."],homework:"Dibujá un mapa simple y prepará instrucciones para tres destinos."},
  {id:7,level:"B1",category:"Gramática",title:"Por o para",subtitle:"Elegir por intención, no por traducción",duration:"60 min",tag:"Confusión típica",goals:["Expresar causa y finalidad","Hablar de destinatarios","Corregir errores frecuentes"],warmup:"Completá rápido: Estudio español ___ viajar.",explanation:"Pensá en dirección: para apunta a un objetivo, destino o destinatario. Por mira la causa, el medio, el intercambio o el recorrido.",practice:["Vine ___ trabajo.","Este regalo es ___ vos.","Caminamos ___ Palermo.","Te llamo ___ confirmar."],speaking:["Explicá por qué estudiás español.","Defendé una decisión usando por y para.","Planificá un viaje para un amigo."],homework:"Escribí una mini historia con cinco usos de por y cinco de para."},
  {id:8,level:"B1",category:"Conversación",title:"Small talk sin perderte",subtitle:"Keywords, follow-ups y frases de recuperación",duration:"60 min",tag:"Fluidez",goals:["Seguir una charla cotidiana","Hacer preguntas de seguimiento","Recuperarte cuando falta una palabra"],warmup:"Respondé: ¿Cómo viene tu semana? Luego agregá un detalle.",explanation:"La conversación fluye cuando escuchás palabras clave y reaccionás. No pauses por una palabra: confirmá lo central, pedí un detalle y conectalo con algo propio.",practice:["Ah, ¿en ___?","¿Y qué ___ después?","No entendí la parte de…","O sea que… ¿___?"],speaking:["Charlá dos minutos sobre tu semana.","Perdé deliberadamente una palabra y recuperate.","Cambiá de tema con una conexión natural."],homework:"Escuchá dos minutos de una entrevista y anotá solo diez palabras clave."},
  {id:9,level:"B2",category:"Gramática",title:"Subjuntivo humano",subtitle:"Deseos, emociones y opiniones con intención",duration:"70 min",tag:"Matices",goals:["Expresar deseo y emoción","Identificar cambio de sujeto","Usar disparadores frecuentes"],warmup:"Terminá: Quiero que la gente… / Me molesta que…",explanation:"El subjuntivo no es una lista de excepciones: aparece cuando no afirmamos un hecho, sino que lo deseamos, evaluamos, dudamos o intentamos influir.",practice:["Espero que ___ (venir).","Me alegra que ___ (estar) acá.","No creo que ___ (ser) fácil.","Quiero ___ / Quiero que ___."],speaking:["Diseñá tu ciudad ideal.","Expresá tres límites en una relación.","Debatí cambios que querés en tu país."],homework:"Escribí un mensaje con dos deseos, una emoción y una recomendación."},
  {id:10,level:"B2",category:"Conversación",title:"Debates con onda",subtitle:"Disentir, matizar y sostener una idea",duration:"65 min",tag:"Opinión",goals:["Disentir sin cortar el diálogo","Dar ejemplos","Matizar afirmaciones"],warmup:"¿Las redes sociales nos conectan o nos aíslan? Elegí una postura.",explanation:"Una opinión fuerte suena mejor cuando incluye matiz: Entiendo el punto, pero… / Hasta cierto punto… / Depende de… . Después sumá una razón y un ejemplo.",practice:["Entiendo lo que ___, pero…","No estoy del ___ de acuerdo.","Por un lado… por ___…","Un ejemplo claro ___…"],speaking:["Debatí turismo masivo.","Defendé la postura contraria a la tuya.","Cerrá con un punto de acuerdo."],homework:"Prepará un argumento de dos minutos y anticipá una objeción."},
  {id:11,level:"C1",category:"Conversación",title:"Preguntas que dan ganas de hablar",subtitle:"16 categorías y 80 preguntas para una conversación avanzada libre",duration:"75 min",tag:"80 preguntas",special:true,path:"/advanced-conversation",goals:["Sostener ideas complejas","Matizar opiniones","Conectar experiencias y argumentos"],warmup:"Elegí una categoría y una pregunta que realmente te dé ganas de responder.",explanation:"Conversación libre de nivel avanzado.",practice:[],speaking:[],homework:""},
  {id:12,level:"C2",category:"Conversación",title:"Argentina entre líneas",subtitle:"Identidad, memoria y contradicciones culturales",duration:"75 min",tag:"Profundidad",goals:["Interpretar discursos complejos","Construir matices","Gestionar referencias culturales"],warmup:"¿Qué contradicciones forman la identidad de un país?",explanation:"En un nivel avanzado, conversar implica leer silencios, referencias compartidas y posiciones implícitas. La meta no es usar palabras difíciles, sino pensar con precisión.",practice:["Reformulá una generalización con matices.","Separá hecho, interpretación y juicio.","Identificá una presuposición cultural."],speaking:["Debatí identidad nacional y migración.","Analizá una noticia desde dos marcos.","Construí una síntesis que no borre el conflicto."],homework:"Escribí una reflexión de 250 palabras que sostenga dos ideas aparentemente opuestas."}
];

export default function Home() {
  const [level,setLevel]=useState("Todos");
  const [category,setCategory]=useState<"Todas"|Category>("Todas");
  const [query,setQuery]=useState("");
  const [activeLesson,setActiveLesson]=useState<Lesson|null>(null);
  const [newsIndex,setNewsIndex]=useState(0);
  const [newsPaused,setNewsPaused]=useState(false);
  const openLesson=(lesson:Lesson)=>{if(lesson.path){window.location.href=lesson.path}else if(lesson.special){window.location.href="/choose-conversation"}else{setActiveLesson(lesson)}};
  const surprise=()=>{const previous=Number(window.sessionStorage.getItem("chespanish-last-surprise"));const pool=lessons.filter(lesson=>lesson.id!==previous);const chosen=pool[Math.floor(Math.random()*pool.length)]||lessons[0];window.sessionStorage.setItem("chespanish-last-surprise",String(chosen.id));openLesson(chosen)};
  const filtered=useMemo(()=>lessons.filter(l=>(level==="Todos"||l.level===level||l.levels?.includes(level))&&(category==="Todas"||l.category===category)&&`${l.title} ${l.subtitle} ${l.tag}`.toLowerCase().includes(query.toLowerCase())),[level,category,query]);
  const news=latestNews[newsIndex];
  useEffect(()=>{if(newsPaused)return;const timer=window.setInterval(()=>setNewsIndex(index=>(index+1)%latestNews.length),5200);return()=>window.clearInterval(timer)},[newsPaused]);
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-avatar" aria-hidden="true"><img src="/chespanish-guide-avatar.png" alt="" /></span><div><b>CHE</b>SPANISH<small>TEACHER STUDIO</small></div></div>
      <nav className="main-nav"><button className="nav-item active"><span>⌂</span> Mi biblioteca</button><button className="nav-item"><span>▣</span> Plan de clase</button><button className="nav-item"><span>☆</span> Favoritas</button></nav>
      <p className="side-label">NIVELES</p><div className="level-nav">{levels.map(x=><button key={x} onClick={()=>setLevel(x)} className={level===x?"selected":""}><span className={`level-dot level-${x.toLowerCase()}`}>{x==="Todos"?"∞":x}</span><span>{x==="Todos"?"Todas las clases":levelNames[x]}</span><b>{x==="Todos"?lessons.length:lessons.filter(l=>l.level===x||l.levels?.includes(x)).length}</b></button>)}</div>
      <div className="mate-tip"><span>🧉</span><div><b>Tu biblioteca crece</b><p>Cada clase nueva va a aparecer acá, ordenada y lista para enseñar.</p></div></div>
      <div className="profile"><span>AN</span><div><b>Alejandro</b><small>Profesor</small></div><button>•••</button></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar tema, objetivo o palabra clave…"/><kbd>⌘ K</kbd></div><button className="new-button surprise-button" onClick={surprise} aria-label="Abrir una clase aleatoria diferente"><span>✦</span> ¡SORPRENDEME!</button></header>
      <section className={`news-carousel news-theme-${newsIndex}`} aria-label="Novedades y nuevas clases" onMouseEnter={()=>setNewsPaused(true)} onMouseLeave={()=>setNewsPaused(false)} onFocus={()=>setNewsPaused(true)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setNewsPaused(false)}}>
        <div className="news-head"><span><i/> NOVEDADES</span><b>{String(newsIndex+1).padStart(2,"0")} / {String(latestNews.length).padStart(2,"0")}</b></div>
        <div className="news-slide" key={news.title}>
          <div className="news-copy"><div className="news-labels"><span>{news.kicker}</span><em>{news.route}</em></div><h2>{news.title}</h2><p>{news.copy}</p><button onClick={()=>openLesson(lessons.find(lesson=>lesson.id===news.lessonId)!)}>Abrir esta clase <span>→</span></button></div>
          <div className="news-brain" aria-hidden="true"><span className="news-word word-one">{news.words[0]}</span><span className="news-word word-two">{news.words[1]}</span><span className="news-word word-three">{news.words[2]}</span><div className="news-core">{news.symbol}</div><img src="/chespanish-guide-avatar.png" alt="" /></div>
        </div>
        <div className="news-controls"><button aria-label="Novedad anterior" onClick={()=>setNewsIndex(index=>(index-1+latestNews.length)%latestNews.length)}>←</button><div>{latestNews.map((item,index)=><button key={item.title} className={index===newsIndex?"active":""} aria-label={`Ver ${item.title}`} aria-pressed={index===newsIndex} onClick={()=>setNewsIndex(index)}/>)}</div><button aria-label="Novedad siguiente" onClick={()=>setNewsIndex(index=>(index+1)%latestNews.length)}>→</button></div>
        <div className="news-progress" key={`progress-${newsIndex}`}><i/></div>
      </section>
      <section className="welcome"><div><p className="eyebrow">TU ESPACIO DE CLASES</p><h1>¿Qué vamos a enseñar hoy?</h1><p>Todo tu español real, organizado y listo para abrir frente al alumno.</p></div><div className="quick-stats"><div><b>{lessons.length}</b><span>clases listas</span></div><div><b>7</b><span>niveles</span></div><div><b>2</b><span>rutas</span></div></div></section>
      <section className="spotlight choose-spotlight" onClick={()=>openLesson(lessons.find(lesson=>lesson.id===13)!)}><div className="spotlight-copy"><span className="featured-pill">★ TU CLASE NUEVA</span><h2>Choose Your Conversation</h2><p>El alumno elige un mundo, selecciona solamente 3 preguntas y deja que la conversación vaya a donde quiera.</p><div className="meta"><span>B1+</span><span>◷ 60 min</span><span>◉ 100% conversación</span></div><button>Abrir clase interactiva <span>→</span></button></div><div className="guide-art" aria-hidden="true"><span className="guide-glow"></span><img src="/chespanish-guide-truck.png" alt="" /></div></section>
      <section className="library-heading"><div><p className="eyebrow">BIBLIOTECA</p><h2>{level==="Todos"?"Todas las clases":`${level} · ${levelNames[level]}`}</h2></div><button className={`show-all ${category==="Todas"?"active":""}`} onClick={()=>setCategory("Todas")}>Ver todas las clases</button></section>
      <section className="route-divider" aria-label="Elegir entre gramática y conversación">
        <button className={`route-card grammar-route ${category==="Gramática"?"active":""}`} onClick={()=>setCategory("Gramática")} aria-pressed={category==="Gramática"}><span>Aa</span><div><small>RUTA 01</small><b>GRAMÁTICA</b><em>Patrones, estructuras y práctica clara</em></div><i>{lessons.filter(lesson=>lesson.category==="Gramática").length} clases</i></button>
        <button className={`route-card conversation-route ${category==="Conversación"?"active":""}`} onClick={()=>setCategory("Conversación")} aria-pressed={category==="Conversación"}><span>“ ”</span><div><small>RUTA 02</small><b>CONVERSACIÓN</b><em>Hablar, reaccionar y conectar de verdad</em></div><i>{lessons.filter(lesson=>lesson.category==="Conversación").length} clases</i></button>
      </section>
      {filtered.length?<div className="lesson-grid">{filtered.map((l,i)=><article className={`lesson-card accent-${l.level.toLowerCase()} ${l.special?"special-card":""}`} key={l.id} onClick={()=>openLesson(l)}><div className="card-top"><span className="level-badge">{l.displayLevel||l.level}</span><button>☆</button></div><div className="card-icon">{l.special?"💬":l.category==="Gramática"?"Aa":"“ ”"}</div><span className="category-name">{l.category}</span><h3>{l.title}</h3><p>{l.subtitle}</p><div className="card-bottom"><span>◷ {l.duration}</span><span>{l.tag}</span><b>→</b></div>{i===0&&<span className="ready-marker">LISTA</span>}</article>)}</div>:<div className="empty-state"><span>⌕</span><h3>No encontré esa clase</h3><p>Probá con otra palabra o cambiá los filtros.</p></div>}
    </main>
    {activeLesson&&<div className="modal-backdrop" onMouseDown={()=>setActiveLesson(null)}><section className="lesson-viewer" onMouseDown={e=>e.stopPropagation()} role="dialog"><header className={`viewer-header accent-${activeLesson.level.toLowerCase()}`}><button className="close" onClick={()=>setActiveLesson(null)}>×</button><div className="viewer-brand">CHESPANISH · MODO CLASE</div><div className="viewer-title"><span>{activeLesson.level}</span><div><p>{activeLesson.category}</p><h2>{activeLesson.title}</h2><small>{activeLesson.subtitle}</small></div></div><div className="viewer-meta"><span>◷ {activeLesson.duration}</span><span>◎ {activeLesson.tag}</span><span>✓ Lista para enseñar</span></div></header><div className="viewer-body">
      <section className="objective-box"><div>01</div><article><span>OBJETIVOS DE HOY</span><h3>Al final de la clase, el alumno puede…</h3><ul>{activeLesson.goals.map(x=><li key={x}>✓ {x}</li>)}</ul></article></section>
      <section className="lesson-section"><div className="section-number">02</div><article><span>ACTIVACIÓN · 5 MIN</span><h3>Empezamos hablando</h3><p>{activeLesson.warmup}</p><div className="teacher-note">💡 <b>Nota para vos:</b> no corrijas todavía. Escuchá qué recursos ya tiene el alumno.</div></article></section>
      <section className="lesson-section"><div className="section-number">03</div><article><span>CLAVE DEL TEMA</span><h3>La idea simple</h3><p className="big-explanation">{activeLesson.explanation}</p></article></section>
      <section className="lesson-section"><div className="section-number">04</div><article><span>PRÁCTICA GUIADA</span><h3>Completá y justificá</h3><div className="exercise-grid">{activeLesson.practice.map((x,i)=><div key={x}><b>{i+1}</b><p>{x}</p><button onClick={e=>{e.currentTarget.textContent=e.currentTarget.textContent==="Ver pista"?"Pensá en el contexto":"Ver pista"}}>Ver pista</button></div>)}</div></article></section>
      <section className="lesson-section speaking-section"><div className="section-number">05</div><article><span>AHORA HABLAMOS</span><h3>De práctica a conversación real</h3><div className="prompt-list">{activeLesson.speaking.map((x,i)=><div key={x}><span>{["🗣️","🎭","⚡"][i]}</span><p><b>Ronda {i+1}</b>{x}</p></div>)}</div></article></section>
      <section className="homework"><span>↗</span><div><small>PARA SEGUIR</small><h3>Tarea breve</h3><p>{activeLesson.homework}</p></div></section></div><footer className="viewer-footer"><span>CHESPANISH · Español real para conversaciones reales</span><button onClick={()=>window.print()}>⤓ Imprimir clase</button></footer></section></div>}
  </div>;
}
