"use client";

import { useMemo, useState } from "react";

type Category = "Gramática" | "Conversación";
type Lesson = { id:number; level:string; category:Category; title:string; subtitle:string; duration:string; tag:string; goals:string[]; warmup:string; explanation:string; practice:string[]; speaking:string[]; homework:string; special?:boolean };

const levels = ["Todos", "A0", "A1", "A2", "B1", "B2", "C1", "C2"];
const levelNames:Record<string,string> = { A0:"Primeros pasos", A1:"Inicial", A2:"Básico", B1:"Intermedio", B2:"Intermedio alto", C1:"Avanzado", C2:"Dominio" };

const lessons:Lesson[] = [
  {id:13,level:"B1",category:"Conversación",title:"Choose Your Conversation",subtitle:"Elegí 1 tema, seleccioná solo 3 preguntas y hablá libremente",duration:"60 min",tag:"15 mundos",special:true,goals:["Elegir un tema que genere curiosidad","Sostener una conversación libre","Compartir historias y opiniones"],warmup:"Choose a topic. Pick 3 questions. Just talk.",explanation:"No perfect answers. No pressure.",practice:[],speaking:[],homework:""},
  {id:1,level:"A0",category:"Gramática",title:"El, la, los, las",subtitle:"Artículos y género sin memorizar reglas eternas",duration:"50 min",tag:"Base esencial",goals:["Reconocer masculino y femenino","Usar artículos definidos e indefinidos","Formar frases simples con ser y estar"],warmup:"Mirá cinco objetos a tu alrededor. ¿Cuáles conocés en español? Decí: es un… / es una…",explanation:"En español, los sustantivos tienen género y número. Usamos el / la para algo específico y un / una para presentar algo nuevo. El artículo siempre acompaña al sustantivo: la casa, un café, los amigos.",practice:["___ mate está caliente.","Quiero comprar ___ empanada.","___ chicos están en Buenos Aires.","Hay ___ farmacia cerca."],speaking:["¿Qué objetos hay en tu casa?","Describí tres cosas de tu ciudad.","Pedí dos cosas en un café argentino."],homework:"Sacá una foto de una habitación y escribí 8 frases usando el, la, los, las, un, una, unos y unas."},
  {id:2,level:"A0",category:"Conversación",title:"Tu primera charla",subtitle:"Saludar, presentarte y sostener 60 segundos",duration:"45 min",tag:"Supervivencia",goals:["Presentarte con naturalidad","Preguntar nombre y origen","Cerrar una conversación"],warmup:"Escuchá dos saludos: Hola, ¿todo bien? / Buenas, ¿cómo andás? ¿Cuál usarías?",explanation:"Una charla no necesita frases perfectas. Necesita turnos cortos: saludo, dato personal, pregunta y reacción. En Argentina, ¿todo bien? suele funcionar como saludo más que como pregunta profunda.",practice:["Completá: Hola, me ___…","¿De dónde ___?","Mucho ___","Nos ___"],speaking:["Presentate como si llegaras a un hostel.","Conocé a un argentino en un café.","Repetí la charla, pero esta vez hacé dos preguntas."],homework:"Grabá un audio de 60 segundos presentándote sin leer."},
  {id:3,level:"A1",category:"Gramática",title:"Presente con vos",subtitle:"Hablás, comés, vivís: el patrón rioplatense",duration:"60 min",tag:"Argentina real",goals:["Conjugar verbos regulares","Usar vos con seguridad","Hablar de rutinas"],warmup:"¿Qué hacés normalmente a la mañana? Usá palabras sueltas si todavía no podés formar frases.",explanation:"Con vos, los verbos regulares llevan el acento al final: hablás, comés, vivís. El pronombre puede omitirse cuando el contexto es claro.",practice:["Vos ___ (trabajar) desde casa.","¿___ (comer) carne?","___ (vivir) en Londres.","¿Qué ___ (hacer) hoy?"],speaking:["Contá tu rutina de lunes.","Compará tu mañana con la de tu profesor.","Entrevistá a alguien sobre sus hábitos."],homework:"Escribí 10 preguntas con vos para usar en la próxima clase."},
  {id:4,level:"A1",category:"Conversación",title:"En el café",subtitle:"Pedir, reaccionar y pagar sin sonar robótico",duration:"50 min",tag:"Roleplay",goals:["Pedir comida y bebida","Preguntar precios","Resolver un problema simple"],warmup:"Elegí: café, mate o té. Explicá por qué con una frase.",explanation:"En Argentina podés pedir con Quería…, Me das… o Para mí… . Quería es amable y muy frecuente. Cerrá con gracias y reaccioná a la respuesta.",practice:["Quería ___ cortado.","¿Me ___ la cuenta?","¿Cuánto ___?","Para mí, ___ medialunas."],speaking:["Pedí desayuno para dos.","La orden llegó mal: explicá el problema.","Preguntá qué recomienda el mozo."],homework:"Creá tu pedido ideal en una cafetería porteña con cinco intervenciones."},
  {id:5,level:"A2",category:"Gramática",title:"Pasado que sirve",subtitle:"Indefinido para contar qué hiciste",duration:"60 min",tag:"Historias",goals:["Narrar acciones terminadas","Ordenar eventos","Distinguir hoy y ayer"],warmup:"Decí tres palabras sobre tu último fin de semana.",explanation:"Usamos el pretérito indefinido para acciones terminadas en un momento cerrado: ayer fui, el sábado comí, en 2025 viajé.",practice:["Ayer ___ (salir) con amigos.","El año pasado ___ (ir) a España.","¿Qué ___ (hacer) anoche?","Primero ___ y después ___."],speaking:["Contá tu último viaje en cinco pasos.","Inventá una excusa por llegar tarde.","Hacé preguntas sobre el fin de semana."],homework:"Grabá una historia de 90 segundos usando primero, después, entonces y al final."},
  {id:6,level:"A2",category:"Conversación",title:"Perderte y recuperarte",subtitle:"Pedir direcciones y entender respuestas reales",duration:"55 min",tag:"Viaje",goals:["Pedir ayuda","Confirmar información","Usar frases de recuperación"],warmup:"¿Qué hacés cuando no entendés una dirección?",explanation:"No necesitás entender cada palabra. Capturá lugar, dirección y distancia. Recuperate con: Perdón, ¿me lo repetís? / ¿Es para allá? / ¿Está lejos?",practice:["¿Cómo ___ a Plaza de Mayo?","¿Está ___ de acá?","¿Doblo a la ___?","¿Me lo ___ más despacio?"],speaking:["Llegá al subte desde tu hotel.","Confirmá tres datos antes de irte.","Dale instrucciones a un turista."],homework:"Dibujá un mapa simple y prepará instrucciones para tres destinos."},
  {id:7,level:"B1",category:"Gramática",title:"Por o para",subtitle:"Elegir por intención, no por traducción",duration:"60 min",tag:"Confusión típica",goals:["Expresar causa y finalidad","Hablar de destinatarios","Corregir errores frecuentes"],warmup:"Completá rápido: Estudio español ___ viajar.",explanation:"Pensá en dirección: para apunta a un objetivo, destino o destinatario. Por mira la causa, el medio, el intercambio o el recorrido.",practice:["Vine ___ trabajo.","Este regalo es ___ vos.","Caminamos ___ Palermo.","Te llamo ___ confirmar."],speaking:["Explicá por qué estudiás español.","Defendé una decisión usando por y para.","Planificá un viaje para un amigo."],homework:"Escribí una mini historia con cinco usos de por y cinco de para."},
  {id:8,level:"B1",category:"Conversación",title:"Small talk sin perderte",subtitle:"Keywords, follow-ups y frases de recuperación",duration:"60 min",tag:"Fluidez",goals:["Seguir una charla cotidiana","Hacer preguntas de seguimiento","Recuperarte cuando falta una palabra"],warmup:"Respondé: ¿Cómo viene tu semana? Luego agregá un detalle.",explanation:"La conversación fluye cuando escuchás palabras clave y reaccionás. No pauses por una palabra: confirmá lo central, pedí un detalle y conectalo con algo propio.",practice:["Ah, ¿en ___?","¿Y qué ___ después?","No entendí la parte de…","O sea que… ¿___?"],speaking:["Charlá dos minutos sobre tu semana.","Perdé deliberadamente una palabra y recuperate.","Cambiá de tema con una conexión natural."],homework:"Escuchá dos minutos de una entrevista y anotá solo diez palabras clave."},
  {id:9,level:"B2",category:"Gramática",title:"Subjuntivo humano",subtitle:"Deseos, emociones y opiniones con intención",duration:"70 min",tag:"Matices",goals:["Expresar deseo y emoción","Identificar cambio de sujeto","Usar disparadores frecuentes"],warmup:"Terminá: Quiero que la gente… / Me molesta que…",explanation:"El subjuntivo no es una lista de excepciones: aparece cuando no afirmamos un hecho, sino que lo deseamos, evaluamos, dudamos o intentamos influir.",practice:["Espero que ___ (venir).","Me alegra que ___ (estar) acá.","No creo que ___ (ser) fácil.","Quiero ___ / Quiero que ___."],speaking:["Diseñá tu ciudad ideal.","Expresá tres límites en una relación.","Debatí cambios que querés en tu país."],homework:"Escribí un mensaje con dos deseos, una emoción y una recomendación."},
  {id:10,level:"B2",category:"Conversación",title:"Debates con onda",subtitle:"Disentir, matizar y sostener una idea",duration:"65 min",tag:"Opinión",goals:["Disentir sin cortar el diálogo","Dar ejemplos","Matizar afirmaciones"],warmup:"¿Las redes sociales nos conectan o nos aíslan? Elegí una postura.",explanation:"Una opinión fuerte suena mejor cuando incluye matiz: Entiendo el punto, pero… / Hasta cierto punto… / Depende de… . Después sumá una razón y un ejemplo.",practice:["Entiendo lo que ___, pero…","No estoy del ___ de acuerdo.","Por un lado… por ___…","Un ejemplo claro ___…"],speaking:["Debatí turismo masivo.","Defendé la postura contraria a la tuya.","Cerrá con un punto de acuerdo."],homework:"Prepará un argumento de dos minutos y anticipá una objeción."},
  {id:11,level:"C1",category:"Conversación",title:"Ironía y doble sentido",subtitle:"Leer lo que un argentino realmente quiere decir",duration:"70 min",tag:"Cultura",goals:["Detectar ironía por contexto","Interpretar tono","Responder sin literalidad"],warmup:"¿Qué puede significar «¡Qué puntual!» si alguien llega cuarenta minutos tarde?",explanation:"La ironía rioplatense depende de una contradicción entre palabras, situación y tono. Antes de traducir literalmente, preguntate qué expectativa se rompió.",practice:["Interpretá: Hermoso día… durante una tormenta.","Cambiá una frase literal por una irónica.","Marcá tono: afecto, crítica o humor."],speaking:["Analizá tres escenas cotidianas.","Contá una anécdota usando ironía.","Explicá cuándo la ironía puede fallar interculturalmente."],homework:"Encontrá un ejemplo real de ironía en una serie o video y explicá las pistas."},
  {id:12,level:"C2",category:"Conversación",title:"Argentina entre líneas",subtitle:"Identidad, memoria y contradicciones culturales",duration:"75 min",tag:"Profundidad",goals:["Interpretar discursos complejos","Construir matices","Gestionar referencias culturales"],warmup:"¿Qué contradicciones forman la identidad de un país?",explanation:"En un nivel avanzado, conversar implica leer silencios, referencias compartidas y posiciones implícitas. La meta no es usar palabras difíciles, sino pensar con precisión.",practice:["Reformulá una generalización con matices.","Separá hecho, interpretación y juicio.","Identificá una presuposición cultural."],speaking:["Debatí identidad nacional y migración.","Analizá una noticia desde dos marcos.","Construí una síntesis que no borre el conflicto."],homework:"Escribí una reflexión de 250 palabras que sostenga dos ideas aparentemente opuestas."}
];

export default function Home() {
  const [level,setLevel]=useState("Todos");
  const [category,setCategory]=useState<"Todas"|Category>("Todas");
  const [query,setQuery]=useState("");
  const [activeLesson,setActiveLesson]=useState<Lesson|null>(null);
  const openLesson=(lesson:Lesson)=>{if(lesson.special){window.location.href="/choose-conversation"}else{setActiveLesson(lesson)}};
  const filtered=useMemo(()=>lessons.filter(l=>(level==="Todos"||l.level===level)&&(category==="Todas"||l.category===category)&&`${l.title} ${l.subtitle} ${l.tag}`.toLowerCase().includes(query.toLowerCase())),[level,category,query]);
  return <div className="app-shell">
    <aside className="sidebar">
      <div className="brand"><span className="brand-sun">☀</span><div><b>CHE</b>SPANISH<small>TEACHER STUDIO</small></div></div>
      <nav className="main-nav"><button className="nav-item active"><span>⌂</span> Mi biblioteca</button><button className="nav-item"><span>▣</span> Plan de clase</button><button className="nav-item"><span>☆</span> Favoritas</button></nav>
      <p className="side-label">NIVELES</p><div className="level-nav">{levels.map(x=><button key={x} onClick={()=>setLevel(x)} className={level===x?"selected":""}><span className={`level-dot level-${x.toLowerCase()}`}>{x==="Todos"?"∞":x}</span><span>{x==="Todos"?"Todas las clases":levelNames[x]}</span><b>{x==="Todos"?lessons.length:lessons.filter(l=>l.level===x).length}</b></button>)}</div>
      <div className="mate-tip"><span>🧉</span><div><b>Tu biblioteca crece</b><p>Cada clase nueva va a aparecer acá, ordenada y lista para enseñar.</p></div></div>
      <div className="profile"><span>AN</span><div><b>Alejandro</b><small>Profesor</small></div><button>•••</button></div>
    </aside>
    <main className="main-content">
      <header className="topbar"><div className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar tema, objetivo o palabra clave…"/><kbd>⌘ K</kbd></div><button className="icon-button">♢<i/></button><button className="new-button" onClick={()=>openLesson(lessons[0])}><span>＋</span> Abrir nueva</button></header>
      <section className="welcome"><div><p className="eyebrow">TU ESPACIO DE CLASES</p><h1>¿Qué vamos a enseñar hoy?</h1><p>Todo tu español real, organizado y listo para abrir frente al alumno.</p></div><div className="quick-stats"><div><b>{lessons.length}</b><span>clases listas</span></div><div><b>7</b><span>niveles</span></div><div><b>2</b><span>rutas</span></div></div></section>
      <section className="spotlight choose-spotlight" onClick={()=>openLesson(lessons[0])}><div className="spotlight-copy"><span className="featured-pill">★ TU CLASE NUEVA</span><h2>Choose Your Conversation</h2><p>El alumno elige un mundo, selecciona solamente 3 preguntas y deja que la conversación vaya a donde quiera.</p><div className="meta"><span>B1+</span><span>◷ 60 min</span><span>◉ 100% conversación</span></div><button>Abrir clase interactiva <span>→</span></button></div><div className="conversation-art"><div className="bubble bubble-one">Choose<br/>a topic</div><div className="bubble bubble-two">Pick only<br/>3 questions</div><div className="bubble bubble-three">Just talk ✨</div><div className="mini-mate">💬</div></div></section>
      <section className="library-heading"><div><p className="eyebrow">BIBLIOTECA</p><h2>{level==="Todos"?"Todas las clases":`${level} · ${levelNames[level]}`}</h2></div><div className="category-tabs">{(["Todas","Gramática","Conversación"] as const).map(x=><button key={x} onClick={()=>setCategory(x)} className={category===x?"active":""}>{x==="Gramática"?"✎ ":x==="Conversación"?"◌ ":""}{x}</button>)}</div></section>
      {filtered.length?<div className="lesson-grid">{filtered.map((l,i)=><article className={`lesson-card accent-${l.level.toLowerCase()} ${l.special?"special-card":""}`} key={l.id} onClick={()=>openLesson(l)}><div className="card-top"><span className="level-badge">{l.level}</span><button>☆</button></div><div className="card-icon">{l.special?"💬":l.category==="Gramática"?"Aa":"“ ”"}</div><span className="category-name">{l.category}</span><h3>{l.title}</h3><p>{l.subtitle}</p><div className="card-bottom"><span>◷ {l.duration}</span><span>{l.tag}</span><b>→</b></div>{i===0&&<span className="ready-marker">LISTA</span>}</article>)}</div>:<div className="empty-state"><span>⌕</span><h3>No encontré esa clase</h3><p>Probá con otra palabra o cambiá los filtros.</p></div>}
    </main>
    {activeLesson&&<div className="modal-backdrop" onMouseDown={()=>setActiveLesson(null)}><section className="lesson-viewer" onMouseDown={e=>e.stopPropagation()} role="dialog"><header className={`viewer-header accent-${activeLesson.level.toLowerCase()}`}><button className="close" onClick={()=>setActiveLesson(null)}>×</button><div className="viewer-brand">CHESPANISH · MODO CLASE</div><div className="viewer-title"><span>{activeLesson.level}</span><div><p>{activeLesson.category}</p><h2>{activeLesson.title}</h2><small>{activeLesson.subtitle}</small></div></div><div className="viewer-meta"><span>◷ {activeLesson.duration}</span><span>◎ {activeLesson.tag}</span><span>✓ Lista para enseñar</span></div></header><div className="viewer-body">
      <section className="objective-box"><div>01</div><article><span>OBJETIVOS DE HOY</span><h3>Al final de la clase, el alumno puede…</h3><ul>{activeLesson.goals.map(x=><li key={x}>✓ {x}</li>)}</ul></article></section>
      <section className="lesson-section"><div className="section-number">02</div><article><span>ACTIVACIÓN · 5 MIN</span><h3>Empezamos hablando</h3><p>{activeLesson.warmup}</p><div className="teacher-note">💡 <b>Nota para vos:</b> no corrijas todavía. Escuchá qué recursos ya tiene el alumno.</div></article></section>
      <section className="lesson-section"><div className="section-number">03</div><article><span>CLAVE DEL TEMA</span><h3>La idea simple</h3><p className="big-explanation">{activeLesson.explanation}</p></article></section>
      <section className="lesson-section"><div className="section-number">04</div><article><span>PRÁCTICA GUIADA</span><h3>Completá y justificá</h3><div className="exercise-grid">{activeLesson.practice.map((x,i)=><div key={x}><b>{i+1}</b><p>{x}</p><button onClick={e=>{e.currentTarget.textContent=e.currentTarget.textContent==="Ver pista"?"Pensá en el contexto":"Ver pista"}}>Ver pista</button></div>)}</div></article></section>
      <section className="lesson-section speaking-section"><div className="section-number">05</div><article><span>AHORA HABLAMOS</span><h3>De práctica a conversación real</h3><div className="prompt-list">{activeLesson.speaking.map((x,i)=><div key={x}><span>{["🗣️","🎭","⚡"][i]}</span><p><b>Ronda {i+1}</b>{x}</p></div>)}</div></article></section>
      <section className="homework"><span>↗</span><div><small>PARA SEGUIR</small><h3>Tarea breve</h3><p>{activeLesson.homework}</p></div></section></div><footer className="viewer-footer"><span>CHESPANISH · Español real para conversaciones reales</span><button onClick={()=>window.print()}>⤓ Imprimir clase</button></footer></section></div>}
  </div>;
}
