'use client';
import Link from 'next/link';
import {useId,useState,type CSSProperties} from 'react';
import {ConversationFamily} from '../conversation-families/ConversationFamily';
import type {CEFRLevel} from '../conversation-families/types';
import {countries} from './data';
import {atlasMaps} from './map-data';
import {atlasLevels,p,type Country,type CountrySlug,type Pair,type Region} from './types';
import '../suiza-en-relieve/style.css';
import './style.css';

function Copy({text,english=true}:{text:Pair;english?:boolean}) {return <><span lang="es">{text.es}</span>{english&&text.en&&<small lang="en">{text.en}</small>}</>}
function point(slug:CountrySlug,region:Region) {
 const map=atlasMaps[slug];const viewport=slug==='espana'&&region.lon< -12?map.viewports[1]!:map.viewports[0];
 return {x:viewport.ox+(region.lon-viewport.bounds[0])*viewport.cos*viewport.scale,y:viewport.oy+(viewport.bounds[3]-region.lat)*viewport.scale};
}
function CountryMap({country,selected,onSelect,visited}:{country:Country;selected:string;onSelect:(id:string)=>void;visited:string[]}) {
 const id=useId().replaceAll(':','');const map=atlasMaps[country.slug];
 return <div className="atlas-map-surface"><svg viewBox="0 0 720 610" role="group" aria-label={`Mapa de ${country.name.es} / Map of ${country.name.en}`}>
  <defs><linearGradient id={`${id}-land`} x1="0" y1="0" x2="1" y2="1"><stop stopColor="#f5ecd8"/><stop offset=".6" stopColor="#d7caaa"/><stop offset="1" stopColor="#b8b58e"/></linearGradient><filter id={`${id}-shadow`} x="-30%" y="-30%" width="170%" height="180%"><feDropShadow dx="0" dy="13" stdDeviation="9" floodColor="#304940" floodOpacity=".22"/></filter></defs>
  <g filter={`url(#${id}-shadow)`}>{[12,8,4,0].map(offset=><g key={offset} transform={`translate(0 ${offset})`}>{map.paths.map((d,i)=><path key={i} d={d} fill={offset?'#9caa91':`url(#${id}-land)`} stroke={offset?'#9caa91':'#fff9e8'} strokeWidth="1" fillRule="evenodd"/>)}</g>)}</g>
  {country.slug==='espana'&&<><rect x="36" y="460" width="308" height="122" rx="12" className="atlas-inset"/><text x="50" y="482" className="atlas-map-note">CANARIAS · ATLÁNTICO</text><text x="50" y="570" className="atlas-map-note">RECUADRO / INSET · OTRA ESCALA / DIFFERENT SCALE</text></>}
  <g className="atlas-compass" transform="translate(658 58)"><path d="M0 -20 L-6 0 L0 -4 L6 0 Z"/><text y="-27">N</text></g>
  {country.regions.map((region,i)=>{const q=point(country.slug,region);return <g key={region.id} transform={`translate(${q.x} ${q.y})`} role="button" tabIndex={0} aria-label={`${region.name.es} / ${region.name.en}`} aria-pressed={selected===region.id} className={`atlas-pin ${selected===region.id?'selected':''} ${visited.includes(region.id)?'visited':''}`} onClick={()=>onSelect(region.id)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onSelect(region.id)}}}><circle r={selected===region.id?18:14}/><text y="4">{String(i+1).padStart(2,'0')}</text><title>{region.name.es}</title></g>})}
 </svg><p className="atlas-map-key"><span><i/> {country.slug==='espana'?'17 comunidades + 2 ciudades / 17 regions + 2 cities':'Destinos representativos / Representative places'}</span><span>N ↑ · <a href="https://www.naturalearthdata.com/about/terms-of-use/" target="_blank" rel="noreferrer">Natural Earth</a></span></p></div>;
}
const expressions=[p('¿Y tú?','And you?'),p('Otra vez, por favor.','Again, please.'),p('Más despacio, por favor.','More slowly, please.'),p('No entiendo.','I do not understand.'),p('Sí, gracias.','Yes, thank you.'),p('No, gracias.','No, thank you.')];
const rolePairs:Record<CountrySlug,[Pair,Pair]>={suecia:[p('Anfitrión: invita sin presionar.','Host: invite without pressure.'),p('Visita: expresa una preferencia y responde.','Guest: express a preference and reply.')],argentina:[p('Anfitrión: ofrece mate o una comida.','Host: offer mate or food.'),p('Visita: acepta o propone otra opción.','Guest: accept or suggest another option.')],espana:[p('Persona local: escucha y recomienda.','Local: listen and recommend.'),p('Visitante: pregunta sin dar nada por supuesto.','Visitor: ask without assuming.') ]};
const changes:Record<CountrySlug,Pair[]>={suecia:[p('Llueve y el grupo prefiere una actividad cubierta.','It is raining and the group prefers an indoor activity.'),p('Una persona necesita descanso y no quiere caminar.','One person needs rest and does not want to walk.'),p('Hoy no se ven auroras.','No auroras are visible today.')],argentina:[p('Solo queda un día: hay que elegir una zona.','There is only one day left: choose one area.'),p('Una persona no quiere compartir mate.','One person does not want to share mate.'),p('Alguien prefiere música en lugar de fútbol.','Someone prefers music instead of football.')],espana:[p('El museo está cerrado.','The museum is closed.'),p('Una persona quiere descansar y otra quiere salir.','One person wants to rest and another wants to go out.'),p('El grupo prefiere reducir los traslados.','The group prefers fewer journeys.') ]};
function Journey({country,level}:{country:Country;level:CEFRLevel}) {
 const [step,setStep]=useState(0),[selected,setSelected]=useState(country.regions[0].id),[visited,setVisited]=useState<string[]>([]),[completed,setCompleted]=useState<number[]>([]),[english,setEnglish]=useState(true),[choice,setChoice]=useState<number|null>(null),[draft,setDraft]=useState(''),[saved,setSaved]=useState<Pair[]>([]),[compare,setCompare]=useState<string[]>([]),[route,setRoute]=useState<string[]>([]),[role,setRole]=useState(0),[surprise,setSurprise]=useState<number|null>(null),[agreement,setAgreement]=useState<string[]>([]),[notes,setNotes]=useState(''),[showModel,setShowModel]=useState(level==='A0'),[finished,setFinished]=useState(false);
 const activity=country.lessons[level][step],region=country.regions.find(r=>r.id===selected)!,a0=level==='A0';
 const built=choice===null?null:p([activity.frame?.es,activity.options[choice].es].filter(Boolean).join(' '),[activity.frame?.en,activity.options[choice].en].filter(Boolean).join(' '));
 const chooseRegion=(id:string)=>{setSelected(id);setVisited(old=>old.includes(id)?old:[...old,id])};
 const move=(index:number)=>{setStep(index);setChoice(null);setDraft('');setShowModel(a0);setSurprise(null);setFinished(false);document.getElementById('atlas-classroom')?.scrollIntoView({behavior:'smooth',block:'start'})};
 const save=()=>{const value=draft.trim()?p(draft.trim(),''):built;if(value){setSaved(old=>old.some(x=>x.es===value.es)?old:[...old,value]);}};
 const toggle=(list:string[],value:string,limit:number)=>list.includes(value)?list.filter(x=>x!==value):list.length<limit?[...list,value]:[...list.slice(1),value];
 const next=()=>{setCompleted(old=>old.includes(step)?old:[...old,step]);if(step<9)move(step+1);else setFinished(true)};
 return <main className={`atlas-app atlas-${country.slug} ${english?'':'atlas-hide-english'}`} style={{'--atlas-accent':country.color,'--atlas-paper':country.paper} as CSSProperties}>
  <nav className="atlas-nav"><Link href="/">SPANISHCUE <span> / FIELD NOTES</span></Link><div><span>{level} · 60 min</span><button aria-pressed={english} onClick={()=>setEnglish(!english)}>ES / EN · {english?'ON':'OFF'}</button><a href="#atlas-map">Mapa / Map ↓</a></div></nav>
  <header className="atlas-hero"><div><p className="atlas-eyebrow"><Copy text={country.kicker}/></p><h1>{country.name.es}<span>{country.name.en!==country.name.es?country.name.en:'DE NORTE A SUR'}</span></h1><p className="atlas-intro"><Copy text={country.intro}/></p></div><aside><span className="atlas-volume">{String(country.regions.length).padStart(2,'0')}</span><p><Copy text={p('lugares, muchas conversaciones','places, many conversations')}/></p><div className="atlas-guide"><Copy text={p('El profesor comparte pantalla y hace clic. El alumno habla.','The teacher shares the screen and clicks. The learner speaks.')}/></div><a className="atlas-start" href="#atlas-classroom">Empezar / Start <span>↘</span></a></aside></header>
  <section className="atlas-journey" aria-label="Recorrido de 60 minutos / 60-minute journey"><div className="atlas-section-label"><span>01 — 10 / <Copy text={p('UN VIAJE, DIEZ CONVERSACIONES','ONE JOURNEY, TEN CONVERSATIONS')}/></span><span>{completed.length}/10</span></div><div className="atlas-stage-list">{country.lessons[level].map((a,i)=><button key={i} aria-current={step===i?'step':undefined} onClick={()=>move(i)}><span>{completed.includes(i)?'✓':String(i+1).padStart(2,'0')}</span><b><Copy text={a.title}/></b><em>{a.minutes} min</em></button>)}</div></section>
  <section id="atlas-classroom" className="atlas-classroom">
   <article className="atlas-activity"><header><span>{String(step+1).padStart(2,'0')} / {level}</span><span>{activity.minutes} min</span></header><h2><Copy text={activity.title}/></h2><p className="atlas-prompt"><Copy text={activity.prompt}/></p>
    {activity.kind==='map'&&<a className="atlas-inline-link" href="#atlas-map"><Copy text={p('Busca, señala y elige en el mapa','Find, point and choose on the map')}/> ↓</a>}
    {activity.kind==='compare'&&!a0&&<div className="atlas-comparison"><p><Copy text={p('El profesor anota las dos opciones de esta consigna. El alumno compara.','The teacher records the two options in this task. The learner compares.')}/></p><div>{[0,1].map(i=><label key={i}><span>{i?'B':'A'}</span><input aria-label={`Opción ${i?'B':'A'} / Option ${i?'B':'A'}`} placeholder="Opción / Option…" value={compare[i]||''} onChange={e=>setCompare(old=>{const n=[...old];n[i]=e.target.value;return n})}/></label>)}</div></div>}
    {activity.kind==='roleplay'&&<div className="atlas-role"><div>{[0,1].map(i=><button key={i} aria-pressed={role===i} onClick={()=>setRole(i)}>{i?'B':'A'} · <Copy text={p(i?'Alumno empieza':'Profesor empieza',i?'Learner starts':'Teacher starts')}/></button>)}</div>{(a0||level==='A1'||level==='A2')?<><p><Copy text={rolePairs[country.slug][role]}/></p><p><Copy text={rolePairs[country.slug][1-role]}/></p></>:<><p><Copy text={p('A plantea una posición dentro de esta situación. B responde desde una perspectiva distinta.','A takes a position within this situation. B responds from a different perspective.')}/></p><p><Copy text={p('Intercambien los papeles y busquen una respuesta que tenga en cuenta a ambos.','Swap roles and find a response that takes both perspectives into account.')}/></p></>}{a0&&<blockquote><Copy text={country.slug==='argentina'?p('¿Quieres mate? — No, gracias. Quiero agua.','Would you like mate? — No, thank you. I want water.'):country.slug==='suecia'?p('¿Quieres un café? — Sí, gracias. ¿Y tú?','Would you like a coffee? — Yes, thank you. And you?'):p('Hola. Agua, por favor. — Sí. — Gracias.','Hello. Water, please. — Yes. — Thank you.')}/></blockquote>}</div>}
    {activity.kind==='negotiate'&&!a0&&<div className="atlas-agreement"><p><Copy text={p('El acuerdo tiene dos prioridades. Elijan juntos.','The agreement has two priorities. Choose together.')}/></p>{[p('Descanso','Rest'),p('Encuentro','Connection'),p('Naturaleza','Nature'),p('Cultura','Culture')].map(item=><button key={item.es} aria-pressed={agreement.includes(item.es)} onClick={()=>setAgreement(toggle(agreement,item.es,2))}><Copy text={item}/></button>)}<p aria-live="polite">{agreement.length===2?<Copy text={p(`Acuerdo: ${agreement.join(' + ')}. Digan qué harán.`,`Agreement: ${agreement.map(x=>({Descanso:'rest',Encuentro:'connection',Naturaleza:'nature',Cultura:'culture'}[x])).join(' + ')}. Say what you will do.`)}/>:<Copy text={p('Falta escuchar y elegir.','Listen and choose.')}/>}</p></div>}
    {activity.kind==='route'&&<div className="atlas-route"><p><Copy text={p('Añade hasta tres paradas. Cambia el orden con las flechas.','Add up to three stops. Change their order with the arrows.')}/></p><select aria-label="Añadir parada / Add stop" value="" onChange={e=>e.target.value&&setRoute(old=>old.includes(e.target.value)?old:old.length<3?[...old,e.target.value]:old)}><option value="">+ Parada / Stop</option>{country.regions.filter(r=>!route.includes(r.id)).map(r=><option key={r.id} value={r.id}>{r.name.es}</option>)}</select><ol>{route.map((id,i)=><li key={id}><Copy text={country.regions.find(r=>r.id===id)!.name}/><div><button disabled={i===0} aria-label="Mover antes / Move earlier" onClick={()=>setRoute(old=>{const n=[...old];[n[i-1],n[i]]=[n[i],n[i-1]];return n})}>↑</button><button aria-label="Quitar parada / Remove stop" onClick={()=>setRoute(old=>old.filter(x=>x!==id))}>×</button></div></li>)}</ol><small><Copy text={p('El orden es una propuesta de clase. Comprueba conexiones reales antes de viajar.','The order is a classroom proposal. Check real connections before travelling.')}/></small></div>}
    {activity.kind==='reflect'&&!a0&&<blockquote className="atlas-language"><Copy text={country.language[level]}/></blockquote>}
    {activity.kind==='surprise'&&<div className="atlas-surprise"><button onClick={()=>setSurprise(old=>old===null?0:(old+1)%changes[country.slug].length)}><Copy text={p('Revelar una nueva condición','Reveal a new condition')}/> ↗</button>{surprise!==null&&<p aria-live="polite"><Copy text={changes[country.slug][surprise]}/></p>}</div>}
    {activity.kind==='final'&&<div className="atlas-final"><p><Copy text={p('Recupera tus elecciones. Combina dos ideas y responde a una pregunta del profesor.','Bring back your choices. Combine two ideas and answer one teacher question.')}/></p><div className="atlas-saved">{saved.length?saved.map(item=><button key={item.es} onClick={()=>setDraft(old=>old?`${old}${/[.!?]$/.test(old)?' ':'. '}${item.es}`:item.es)}><Copy text={item}/></button>):<p><Copy text={p('Usa las frases modelo o vuelve a una etapa para guardar tus ideas.','Use the models or return to a stage to save your ideas.')}/></p>}</div>{route.length>0&&<p><Copy text={p('Tu ruta: ','Your route: ')}/>{route.map(id=>country.regions.find(r=>r.id===id)!.name.es).join(' → ')}</p>}</div>}
    <section className="atlas-scaffold"><div className="atlas-scaffold-head"><h3><Copy text={p(a0?'Construye y dilo':'Un comienzo posible',a0?'Build it and say it':'A possible beginning')}/></h3><button aria-expanded={showModel} onClick={()=>setShowModel(!showModel)}><Copy text={p(showModel?'Ocultar modelo':'Ver modelo',showModel?'Hide model':'Show model')}/></button></div>{showModel&&<blockquote className="atlas-model"><Copy text={activity.model}/></blockquote>}
    {activity.tip&&<p className="atlas-tip"><b>TIP</b><Copy text={activity.tip}/></p>}
    {a0&&activity.frame?.es&&<div className="atlas-frame"><Copy text={activity.frame}/><b>+</b></div>}
    <div className="atlas-tiles">{activity.options.map((option,i)=><button key={option.es} aria-pressed={choice===i} onClick={()=>{setChoice(i);setDraft('')}}><Copy text={option}/></button>)}</div>
    {built&&<p className="atlas-built" aria-live="polite"><Copy text={built}/></p>}
    <label className="atlas-draft"><Copy text={p('El profesor puede escribir la idea del alumno o sustituir una palabra.','The teacher can write the learner’s idea or substitute a word.')}/><textarea rows={2} value={draft} onChange={e=>setDraft(e.target.value)} placeholder={a0?'Mi frase / My sentence…':'Nuestra idea…'}/></label><button className="atlas-save" onClick={save} disabled={!built&&!draft.trim()}><Copy text={p('Guardar para el cierre','Save for the final mission')}/>{saved.length>0&&` · ${saved.length}`}</button></section>
    <aside className="atlas-followup"><b>↗</b><Copy text={a0?p('El profesor muestra una frase. Repite, cambia una opción y di «¿Y tú?».','Your teacher models a sentence. Repeat, change one option and say “¿Y tú?” (And you?).'):activity.followup}/></aside>
    <nav className="atlas-controls"><button disabled={step===0} onClick={()=>move(step-1)}>← <Copy text={p('Anterior','Previous')}/></button><button className="primary" onClick={next}><Copy text={p(step===9?'Cerrar el viaje':'Listo · Siguiente',step===9?'Finish the journey':'Done · Next')}/> →</button></nav>
    {finished&&<div className="atlas-finished" role="status"><h3><Copy text={p('Tu voz ya está en el mapa.','Your voice is on the map.')}/></h3><p><Copy text={p('Di una frase que ahora puedes construir y una pregunta que quieres hacer. El profesor comprueba lo que puedes decir sin leer.','Say one sentence you can now build and one question you want to ask. Your teacher checks what you can say without reading.')}/></p></div>}
   </article>
   <aside className="atlas-context"><span className="atlas-eyebrow"><Copy text={p('Tu lugar de hoy','Your place today')}/></span><h2><Copy text={region.name}/></h2><p className="atlas-context-choice"><Copy text={region.choice}/></p><details open={!a0}><summary><Copy text={p('Contexto para conversar','Context for conversation')}/></summary><p><Copy text={region.fact}/></p></details><a href="#atlas-map"><Copy text={p('Elegir otro lugar','Choose another place')}/> ↓</a>
   {a0&&<section className="atlas-rescue"><h3><Copy text={p('Siempre puedes decir','You can always say')}/></h3>{expressions.map(item=><p key={item.es}><Copy text={item}/></p>)}</section>}
   <details className="atlas-teacher"><summary><Copy text={p('Guía del profesor','Teacher guide')}/></summary><ol><li><Copy text={p('Modela un intercambio. El alumno escucha y responde.','Model one exchange. The learner listens and responds.')}/></li><li><Copy text={p('Cambia una condición o una opción y repite el intercambio.','Change one condition or choice and repeat the exchange.')}/></li><li><Copy text={p('Invierte papeles. Pide una pregunta y una reacción.','Swap roles. Invite a question and a reaction.')}/></li><li><Copy text={p('Usa el tiempo sugerido para varios turnos de habla, no para explicar datos.','Use the suggested time for several speaking turns, not a lecture on facts.')}/></li></ol><label><Copy text={p('Notas de esta clase','Notes for this lesson')}/><textarea rows={4} value={notes} onChange={e=>setNotes(e.target.value)}/></label><small><Copy text={p('Las notas y elecciones se conservan durante este nivel. Cambiar de nivel o recargar reinicia el recorrido.','Notes and choices remain within this level. Changing level or reloading restarts the journey.')}/></small></details>
   </aside>
  </section>
  <section id="atlas-map" className="atlas-map-section"><header><div><p className="atlas-eyebrow">ATLAS / <Copy text={p('EXPLORAR PARA HABLAR','EXPLORE TO SPEAK')}/></p><h2><Copy text={p('¿Qué vida elegirías aquí?','Which life would you choose here?')}/></h2></div><button onClick={()=>{const pool=country.regions.filter(r=>r.id!==selected);chooseRegion(pool[Math.floor(Math.random()*pool.length)].id)}}><Copy text={p('Un lugar sorpresa','A surprise place')}/> ↗</button></header><div className="atlas-map-layout"><CountryMap country={country} selected={selected} onSelect={chooseRegion} visited={visited}/><aside><span>{String(country.regions.indexOf(region)+1).padStart(2,'0')} / {String(country.regions.length).padStart(2,'0')}</span><h3><Copy text={region.name}/></h3><p><Copy text={region.choice}/></p><blockquote><Copy text={a0?p(`Quiero ir ${region.destination.es.startsWith('el ')?'al '+region.destination.es.slice(3):'a '+region.destination.es}.`,`I want to go to ${region.destination.en}.`):p(`Elige ${region.name.es} o una zona diferente. ¿Qué cambia para ti?`,`Choose ${region.name.en} or a different area. What changes for you?`)}/></blockquote><a href="#atlas-classroom"><Copy text={p('Llevar a la conversación','Bring into the conversation')}/> ↑</a><small><Copy text={country.slug==='espana'?p('Los números sitúan destinos representativos; no dibujan fronteras autonómicas. Canarias aparece en un recuadro a otra escala.','Numbers locate representative destinations; they do not draw regional borders. The Canaries are shown in an inset at a different scale.'):p('Selección pedagógica de destinos; no es un mapa de divisiones administrativas.','A teaching selection of destinations, not a map of administrative divisions.')}/></small></aside></div>
  <div className="atlas-region-index">{country.regions.map((r,i)=><button key={r.id} aria-pressed={selected===r.id} onClick={()=>chooseRegion(r.id)}><span className="atlas-region-number">{String(i+1).padStart(2,'0')}</span><span className="atlas-region-icon" aria-hidden="true">{r.icon}</span><b><Copy text={r.name}/></b><small><Copy text={r.choice}/></small><em>{visited.includes(r.id)?'✓':'↗'}</em></button>)}</div></section>
  <footer className="atlas-footer"><p>SPANISHCUE / {country.name.es.toUpperCase()} / {level}</p><details><summary><Copy text={p('Fuentes y geografía','Sources and geography')}/></summary><p><Copy text={p('Contexto cultural consultado en octubre de 2026. Las situaciones y negociaciones son propuestas de clase.','Cultural context consulted in October 2026. Scenarios and negotiations are classroom proposals.')}/></p>{country.sources.map(source=><a key={source.url} href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a>)}<a href="https://www.naturalearthdata.com/" target="_blank" rel="noreferrer">Natural Earth · Contornos generalizados / Generalised outlines</a></details></footer>
 </main>;
}
export default function CountryAtlas({slug}:{slug:CountrySlug}) {const country=countries[slug];return <div className="atlas-family"><ConversationFamily id={slug} title={country.name.es} levels={atlasLevels} defaultLevel="A1" bilingual>{level=><Journey key={level} country={country} level={level}/>}</ConversationFamily></div>}
