import {p,atlasLevels,type Activity,type CountrySlug,type Pair} from './types';
import type {CEFRLevel} from '../conversation-families/types';
import {prompts} from './prompts';
const minutes=[4,6,5,6,7,7,6,6,5,8];
const kinds:Activity['kind'][]=['choose','map','compare','build','roleplay','negotiate','route','reflect','surprise','final'];
const titles:Record<CountrySlug,Pair[]>={
 suecia:[p('Tu ritmo','Your rhythm'),p('Entre agua y bosque','Between water and forest'),p('Dos estaciones','Two seasons'),p('Una pausa con sentido','A meaningful break'),p('Te invito','You are invited'),p('Un lugar compartido','A shared place'),p('Viajar despacio','Travel slowly'),p('Mirar desde casa','A view from home'),p('Cambia la luz','The light changes'),p('Tu Suecia posible','Your possible Sweden')],
 argentina:[p('Un país enorme','An enormous country'),p('De la selva al hielo','From forest to ice'),p('Dos formas de vivir','Two ways of living'),p('La ronda','The gathering'),p('A la mesa','At the table'),p('Nos organizamos','Let us organise'),p('La distancia importa','Distance matters'),p('Así lo vas a escuchar','How you will hear it'),p('Otro plan','Another plan'),p('Tu Argentina','Your Argentina')],
 espana:[p('Más de una España','More than one Spain'),p('Península e islas','Mainland and islands'),p('Norte, costa, interior','North, coast, inland'),p('Para compartir','To share'),p('Un encuentro local','A local encounter'),p('La plaza es de todos','A square for everyone'),p('Conexiones','Connections'),p('Voces y tratamientos','Voices and forms of address'),p('Otra mirada','Another perspective'),p('Tu mapa de España','Your map of Spain')]
};
// A0 options are grammatical, translated completions, not an unlabelled vocabulary dump.
type Starter=[string,string,string,string,string,string,[string,string][]];
const a0:Record<CountrySlug,Starter[]>={
 suecia:[
 ['Elige tu origen. Di «Soy de…». Puedes pedir al profesor otro país.','Choose where you are from. Say “Soy de…”. You can ask your teacher for another country.','Soy de','I am from','SOY = I am · DE = from. No necesitas cambiar el verbo.','SOY = I am · DE = from. You do not need to change the verb.',[['Suecia','Sweden'],['Argentina','Argentina'],['España','Spain'],['otro país','another country']]],
 ['Señala un lugar del mapa y di «Me gusta…».','Point to a place on the map and say “Me gusta…”.','Me gusta','I like','ME GUSTA + un lugar. Aprende estas dos palabras juntas.','ME GUSTA + one place. Learn these two words as one chunk.',[['Estocolmo','Stockholm'],['Kiruna','Kiruna'],['Malmö','Malmö']]],
 ['Elige tu estación. Escucha al profesor y di una opción diferente.','Choose your season. Listen to your teacher and say a different option.','Prefiero','I prefer','PREFIERO = I prefer. EL forma parte del nombre de la estación aquí.','PREFIERO = I prefer. EL is part of the season phrase here.',[['el verano','summer'],['el invierno','winter']]],
 ['Construye tu pedido para una fika. Di la frase y cambia la bebida.','Build your fika order. Say the sentence and change the drink.','Quiero','I want','QUIERO = I want. UN / UNA = a. Copia la opción completa.','QUIERO = I want. UN / UNA = a. Copy the whole option.',[['un café','a coffee'],['un té','a tea'],['agua','water'],['un bollo de canela','a cinnamon bun']]],
 ['El profesor ofrece una bebida. Acepta o rechaza y después ofrece tú.','Your teacher offers a drink. Accept or decline, then make an offer.','¿Quieres','Would you like','¿QUIERES…? = Would you like…? Responde «Sí, gracias» o «No, gracias».','¿QUIERES…? = Would you like…? Answer “Sí, gracias” (yes, thank you) or “No, gracias” (no, thank you).',[['un café?','a coffee?'],['un té?','a tea?'],['agua?','water?']]],
 ['Elijan un lugar para la tarde. Escucha otra propuesta antes de decidir.','Choose a place for the afternoon. Listen to another suggestion before deciding.','Vamos a','Let us go to','VAMOS A = Let us go to. AL = a + el; usa el bloque completo.','VAMOS A = Let us go to. AL = a + el; use the whole chunk.',[['un lago','a lake'],['un café','a café'],['un parque','a park']]],
 ['Elige un destino y después otro. Di las dos frases.','Choose one destination and then another. Say both sentences.','Quiero ir a','I want to go to','QUIERO = I want · IR = to go · A = to.','QUIERO = I want · IR = to go · A = to.',[['Estocolmo','Stockholm'],['Dalarna','Dalarna'],['Kiruna','Kiruna']]],
 ['Mira los paisajes suecos. ¿Qué hay en tu país? Elige una frase real para ti.','Look at the Swedish landscapes. What is there in your country? Choose a sentence that is true for you.','En mi país hay','In my country there is / are','HAY sirve para una o varias cosas. MI PAÍS = my country.','HAY works for one or several things. MI PAÍS = my country.',[['bosques','forests'],['lagos','lakes'],['ciudades','cities']]],
 ['Llueve. Cambia el plan: di lo que no quieres hacer.','It is raining. Change the plan: say what you do not want to do.','No quiero','I do not want','NO antes de QUIERO cambia la frase a negativa.','NO before QUIERO makes the sentence negative.',[['caminar','to walk'],['ir en barco','to go by boat'],['salir','to go out']]],
 ['Combina dos frases que ya conoces. Cambia una parte para hablar de ti.','Combine two sentences you already know. Change one part to talk about yourself.','', '', 'Y = and. Une dos frases completas. Puedes volver a mostrar el inglés.','Y = and. Join two complete sentences. You can show English again.',[['Me gusta Estocolmo y prefiero el verano.','I like Stockholm and I prefer summer.'],['Quiero un té y quiero ir a Dalarna.','I want a tea and I want to go to Dalarna.']]]
 ],
 argentina:[
 ['Elige una imagen del mapa y di lo que te gusta.','Choose a map image and say what you like.','Me gusta','I like','ME GUSTA = I like. Usa el bloque con una opción.','ME GUSTA = I like. Use the chunk with one option.',[['la montaña','the mountains'],['la selva','the forest'],['la ciudad','the city']]],
 ['Señala tu primera parada y construye una frase para viajar.','Point to your first stop and build a travel sentence.','Quiero ir a','I want to go to','QUIERO = I want · IR = to go · A = to.','QUIERO = I want · IR = to go · A = to.',[['la Patagonia','Patagonia'],['Buenos Aires','Buenos Aires'],['Mendoza','Mendoza']]],
 ['Ciudad o naturaleza: elige una y escucha la elección del profesor.','City or nature: choose one and listen to your teacher’s choice.','Prefiero','I prefer','PREFIERO = I prefer. No necesitas conjugar.','PREFIERO = I prefer. You do not need to conjugate.',[['un café','a café'],['un lago','a lake'],['un pueblo','a small town']]],
 ['Prepara una ronda con una bebida para ti. Cambia tu pedido una vez.','Prepare a gathering with a drink for you. Change your order once.','Quiero','I want','QUIERO + bebida. AGUA = water; MATE es el nombre de la bebida.','QUIERO + drink. AGUA = water; MATE is the name of the drink.',[['mate','mate'],['agua','water'],['un café','a coffee']]],
 ['El profesor ofrece mate. Responde y luego pide otra bebida.','Your teacher offers mate. Reply and then ask for another drink.','', '', 'SÍ = yes · NO = no · GRACIAS = thank you.','SÍ = yes · NO = no · GRACIAS = thank you.',[['Sí, gracias.','Yes, thank you.'],['No, gracias. Quiero agua.','No, thank you. I want water.']]],
 ['Organicen una comida. Di qué llevas y pregunta «¿Y tú?».','Organise a meal. Say what you are bringing and ask “¿Y tú?” (and you?).','Yo llevo','I am bringing','YO = I · LLEVO = I am bringing. Usa LLEVO sin cambiarlo.','YO = I · LLEVO = I am bringing. Use LLEVO without changing it.',[['pan','bread'],['verduras','vegetables'],['agua','water']]],
 ['Elige cómo viajar. Di una frase para cada medio que te gusta.','Choose how to travel. Say a sentence for each form of transport you like.','Voy en','I am going by','VOY EN + transporte. EN = by en esta frase.','VOY EN + transport. EN = by in this sentence.',[['autobús','bus'],['avión','plane'],['coche','car']]],
 ['Escucha «¿Vos querés mate?». Solo reconoce la oferta y responde. No necesitas usar vos.','Listen to “¿Vos querés mate?” (Would you like mate?). Just recognise the offer and reply. You do not need to use vos.','', '', '¿VOS QUERÉS? y ¿TÚ QUIERES? son dos formas de preguntar lo mismo aquí.','¿VOS QUERÉS? and ¿TÚ QUIERES? are two ways to ask the same thing here.',[['Sí, quiero mate.','Yes, I want mate.'],['No, quiero agua.','No, I want water.']]],
 ['Tu amigo quiere fútbol. Elige otra actividad si prefieres algo diferente.','Your friend wants football. Choose another activity if you prefer something different.','Quiero','I want','QUIERO + acción: ESCUCHAR = to listen · CAMINAR = to walk.','QUIERO + action: ESCUCHAR = to listen · CAMINAR = to walk.',[['escuchar música','to listen to music'],['caminar','to walk'],['ver fútbol','to watch football']]],
 ['Usa dos ideas tuyas: una preferencia y un destino. Combínalas con «y».','Use two ideas of your own: a preference and a destination. Combine them with “y” (and).','', '', 'Y conecta dos ideas. Lee un modelo, cambia una parte y vuelve a decirlo.','Y connects two ideas. Read a model, change one part and say it again.',[['Me gusta la montaña y quiero ir a Mendoza.','I like the mountains and I want to go to Mendoza.'],['Quiero mate y prefiero un café.','I want mate and I prefer a café.']]]
 ],
 espana:[
 ['Elige playa, ciudad o pueblo. Construye tu primera frase.','Choose beach, city or village. Build your first sentence.','Prefiero','I prefer','PREFIERO = I prefer. LA / EL forman parte de cada opción.','PREFIERO = I prefer. LA / EL are included in each option.',[['la playa','the beach'],['la ciudad','the city'],['el pueblo','the village']]],
 ['Busca las islas y una ciudad. Señala tu destino y habla.','Find the islands and a city. Point to your destination and speak.','Quiero ir a','I want to go to','QUIERO = I want · IR = to go · A = to. LAS = the para estas islas.','QUIERO = I want · IR = to go · A = to. LAS = the for these islands.',[['Madrid','Madrid'],['las Islas Canarias','the Canary Islands'],['las Islas Baleares','the Balearic Islands']]],
 ['Elige el tiempo que te gusta para viajar. Pregunta «¿Y tú?».','Choose the weather you like for travel. Ask “¿Y tú?” (and you?).','Me gusta','I like','ME GUSTA = I like. EL SOL = the sun · LA LLUVIA = the rain.','ME GUSTA = I like. EL SOL = the sun · LA LLUVIA = the rain.',[['el sol','the sun'],['la lluvia','the rain'],['el frío','cold weather']]],
 ['Construye un pedido para compartir. Di la frase y cambia la comida.','Build an order to share. Say the sentence and change the food.','Quiero','I want','QUIERO = I want. Aprende la comida con su traducción.','QUIERO = I want. Learn the food with its translation.',[['arroz','rice'],['pan','bread'],['verduras','vegetables']]],
 ['En el mercado, pide una cosa y da las gracias. El profesor responde.','At the market, ask for one thing and say thank you. Your teacher replies.','', '', 'POR FAVOR = please · GRACIAS = thank you.','POR FAVOR = please · GRACIAS = thank you.',[['Agua, por favor. Gracias.','Water, please. Thank you.'],['Pan, por favor. Gracias.','Bread, please. Thank you.']]],
 ['Elijan una actividad juntos. Propón un lugar para la tarde.','Choose an activity together. Suggest a place for the afternoon.','Vamos a','Let us go to','VAMOS A + lugar. Usa la opción entera para que la frase funcione.','VAMOS A + place. Use the whole option so the sentence works.',[['una plaza','a square'],['un museo','a museum'],['un mercado','a market']]],
 ['Di cómo viajas. Las islas no tienen conexión de tren con la península.','Say how you travel. The islands do not have a train connection to the mainland.','Voy en','I am going by','VOY EN = I am going by. TREN = train · BARCO = boat.','VOY EN = I am going by. TREN = train · BARCO = boat.',[['tren','train'],['barco','boat'],['avión','plane']]],
 ['Presenta tu origen y escucha el del profesor. Puedes pedir otro país.','Introduce where you are from and listen to your teacher. You can ask for another country.','Soy de','I am from','SOY DE = I am from. No necesitas otras formas del verbo.','SOY DE = I am from. You do not need other verb forms.',[['España','Spain'],['Argentina','Argentina'],['Suecia','Sweden'],['otro país','another country']]],
 ['El museo está cerrado. Di adónde quieres ir ahora.','The museum is closed. Say where you want to go now.','Quiero ir a','I want to go to','Ahora reutiliza QUIERO IR A con un lugar nuevo.','Now reuse QUIERO IR A with a new place.',[['un parque','a park'],['una plaza','a square'],['un mercado','a market']]],
 ['Une dos elecciones: lugar y transporte, o paisaje y destino. Di tu propia combinación.','Join two choices: place and transport, or landscape and destination. Say your own combination.','', '', 'Y = and. Puedes unir dos frases que ya usaste.','Y = and. You can join two sentences you have already used.',[['Quiero ir a Madrid y voy en tren.','I want to go to Madrid and I am going by train.'],['Prefiero la playa y quiero ir a las Islas Canarias.','I prefer the beach and I want to go to the Canary Islands.']]]
 ]
};
const stems:Record<Exclude<CEFRLevel,'A0'>,Pair[]>={
 A1:[p('Me gusta…','I like…'),p('Quiero ir a…','I want to go to…'),p('Prefiero… porque…','I prefer… because…'),p('Quiero…','I want…'),p('Sí, gracias. / No, gracias.','Yes, thank you. / No, thank you.'),p('Vamos a…','Let us go to…'),p('Primero… Después…','First… Then…'),p('En mi país hay…','In my country there is / are…'),p('Ahora quiero…','Now I want…'),p('Mi viaje es…','My trip is…')],
 A2:[p('Normalmente… y me gustaría…','Normally… and I would like…'),p('Voy a… y necesito…','I am going to… and I need…'),p('Aquí… pero allí…','Here… but there…'),p('Para la reunión necesitamos…','For the gathering we need…'),p('Gracias por… Prefiero…','Thank you for… I prefer…'),p('Yo puedo… ¿Puedes…?','I can… Can you…?'),p('Primero vamos a… Después…','First we are going to… Then…'),p('Uso… cuando…','I use… when…'),p('Antes quería… Ahora voy a…','Before I wanted… Now I am going to…'),p('Te recomiendo… porque…','I recommend… because…')],
 B1:[p('Una vez… y por eso…','Once… and that is why…'),p('Elegiría… aunque…','I would choose… although…'),p('Por un lado… Por otro…','On one hand… On the other…'),p('Cambiaría… para que…','I would change… so that…'),p('Entiendo que… pero necesito…','I understand that… but I need…'),p('Podríamos… Así…','We could… That way…'),p('Dejaría fuera… porque…','I would leave out… because…'),p('Se parece a… La diferencia es…','It resembles… The difference is…'),p('No siempre… Por ejemplo…','Not always… For example…'),p('Mi propuesta es… Aceptaría…','My proposal is… I would accept…')],
 B2:[p('Sostengo que… siempre que…','I argue that… provided that…'),p('Si priorizáramos… tendríamos que…','If we prioritised… we would have to…'),p('Dependería de… más que de…','It would depend on… more than on…'),p('Para incluir… habría que…','To include… we would need to…'),p('Comprendo la intención; el efecto…','I understand the intention; the effect…'),p('Aceptaría… a condición de que…','I would accept… on condition that…'),p('Renunciar a… permitiría…','Giving up… would allow…'),p('No implica necesariamente que…','It does not necessarily imply that…'),p('Reformularía… para evitar…','I would rephrase… to avoid…'),p('La objeción es válida, aunque…','The objection is valid, although…')],
 C1:[p('Conviene distinguir… de…','We should distinguish… from…'),p('Desde la perspectiva de…','From the perspective of…'),p('Esa lectura presupone…','That reading presupposes…'),p('Lo que parece voluntario…','What appears voluntary…'),p('Sin atribuir una intención…','Without attributing an intention…'),p('El desacuerdo reside en…','The disagreement lies in…'),p('El criterio que propongo…','The criterion I propose…'),p('La etiqueta invisibiliza…','The label renders invisible…'),p('Mi argumento no exige…','My argument does not require…'),p('El acuerdo tiene un límite…','The agreement has a limit…')],
 C2:[p('Tomado literalmente…; como metáfora…','Taken literally…; as a metaphor…'),p('El encuadre privilegia…','The framing privileges…'),p('La formulación oscila entre…','The formulation oscillates between…'),p('La implicatura depende de…','The implicature depends on…'),p('Concedo… sin que eso implique…','I concede… without implying…'),p('La neutralidad aparente…','The apparent neutrality…'),p('Mi selección necesariamente…','My selection necessarily…'),p('Ese juicio mezcla… con…','That judgement conflates… with…'),p('Asumo el efecto… y preciso…','I acknowledge the effect… and clarify…'),p('Hay consenso sobre…; no sobre…','There is consensus on…; not on…')]
};
const followups=[p('Ahora pregunta al profesor y reacciona a su elección.','Now ask your teacher and react to their choice.'),p('Señala otra zona y explica si cambiarías tu elección.','Point to another area and explain whether you would change your choice.'),p('Invierte las preferencias: defiende la otra opción.','Reverse the preferences: defend the other option.'),p('Cambia una pieza y vuelve a decir la frase completa.','Change one piece and say the whole sentence again.'),p('Intercambien los papeles y repitan con una respuesta diferente.','Swap roles and repeat with a different response.'),p('Escucha una objeción y encuentra un acuerdo que ambos acepten.','Listen to an objection and find an agreement both of you accept.'),p('Quita una parada: explica qué ganas y qué pierdes.','Remove one stop: explain what you gain and lose.'),p('Da un ejemplo de tu vida y pregunta por otra experiencia.','Give an example from your life and ask about another experience.'),p('Explica qué parte del plan mantienes y cuál cambias.','Explain which part of the plan you keep and which you change.'),p('El profesor cambia una condición. Ajusta tu propuesta y vuelve a presentarla.','Your teacher changes one condition. Adjust and present your proposal again.')];
export function countryLessons(slug:CountrySlug):Record<CEFRLevel,Activity[]> {
 return Object.fromEntries(atlasLevels.map(level=>[level,titles[slug].map((title,i)=>{
  if(level==='A0') {const [es,en,prefix,prefixEn,tipEs,tipEn,choices]=a0[slug][i]; const options=choices.map(([a,b])=>p(a,b));
   return {title,minutes:minutes[i],kind:kinds[i],prompt:p(es,en),model:p([prefix,options[0].es].filter(Boolean).join(' '),[prefixEn,options[0].en].filter(Boolean).join(' ')),followup:followups[i],options,tip:p(tipEs,tipEn),frame:p(prefix,prefixEn)};
  }
  return {title,minutes:minutes[i],kind:kinds[i],prompt:p(prompts[slug][level][i],''),model:stems[level][i],followup:followups[i],options:stems[level].filter((_,j)=>j===i||j===(i+1)%10||j===(i+2)%10)};
 })])) as Record<CEFRLevel,Activity[]>;
}
