import {p,type Region} from './types';
const r=(id:string,es:string,en:string,icon:string,lon:number,lat:number,zone:string,factEs:string,factEn:string,choiceEs:string,choiceEn:string,destEs=es,destEn=en):Region=>({id,name:p(es,en),icon,lon,lat,zone,fact:p(factEs,factEn),choice:p(choiceEs,choiceEn),destination:p(destEs,destEn)});
export const swedenRegions:Region[]=[
 r('stockholm','Estocolmo y archipiélago','Stockholm and archipelago','⛵',18.07,59.33,'centro','Estocolmo combina vida urbana e islas; el archipiélago se extiende hacia el Báltico.','Stockholm combines urban life and islands; the archipelago extends into the Baltic.','un paseo en barco','a boat ride'),
 r('west','Gotemburgo y costa oeste','Gothenburg and west coast','🦞',11.97,57.71,'sur','La costa oeste reúne islas, pueblos pesqueros y la ciudad de Gotemburgo.','The west coast brings together islands, fishing villages and Gothenburg.','una comida junto al mar','a meal by the sea'),
 r('skane','Malmö y Escania','Malmö and Skåne','🚲',13,55.6,'sur','En el sur, Malmö combina barrios urbanos con acceso a los paisajes agrícolas de Escania.','In the south, Malmö combines urban neighbourhoods with access to the farmland of Skåne.','un recorrido en bicicleta','a bike ride'),
 r('dalarna','Dalarna','Dalarna','🐴',15.63,60.6,'centro','Dalarna se asocia con artesanía, lagos y celebraciones de Midsummer; no representa toda Suecia.','Dalarna is associated with crafts, lakes and Midsummer celebrations; it does not represent all Sweden.','una celebración de verano','a summer celebration'),
 r('lakes','Värmland y lagos','Värmland and lakes','🛶',13.5,59.38,'centro','Värmland ofrece bosques y lagos; disfrutar de la naturaleza implica respetar a residentes y fauna.','Värmland has forests and lakes; enjoying nature means respecting residents and wildlife.','una tarde junto al lago','an afternoon by the lake'),
 r('high-coast','Costa Alta','High Coast','🥾',18.33,63.07,'norte','La Costa Alta está junto al golfo de Botnia y ofrece senderos y un paisaje marcado por la elevación del terreno tras la glaciación.','The High Coast faces the Gulf of Bothnia, with trails and landscapes shaped by post-glacial land uplift.','una caminata por la costa','a coastal walk'),
 r('kiruna','Kiruna y norte de Suecia','Kiruna and northern Sweden','🌌',20.23,67.86,'norte','En el extremo norte cambia mucho la luz entre estaciones. Las auroras requieren oscuridad y condiciones adecuadas; no están garantizadas. Sápmi atraviesa fronteras y la cultura sámi es viva y diversa.','Daylight varies greatly between seasons in the far north. Auroras need darkness and suitable conditions; they are not guaranteed. Sápmi crosses borders and Sámi culture is living and diverse.','una experiencia de invierno','a winter experience')
];
export const argentinaRegions:Region[]=[
 r('buenos-aires','Buenos Aires','Buenos Aires','🏙️',-58.38,-34.6,'centro','La ciudad y la provincia de Buenos Aires son jurisdicciones distintas. Cafés, barrios y costa ofrecen vidas diferentes.','Buenos Aires city and province are separate jurisdictions. Cafés, neighbourhoods and the coast offer different ways of life.','un café de barrio','a neighbourhood café'),
 r('pampas','Pampas y centro','Pampas and central plains','🌾',-60.7,-33.2,'centro','Las llanuras pampeanas abarcan partes de varias provincias; no son una única provincia ni una cultura uniforme.','The Pampas plains span parts of several provinces; they are neither one province nor a uniform culture.','un encuentro en un pueblo','a gathering in a small town'),
 r('cordoba','Córdoba','Córdoba','🎸',-64.19,-31.42,'centro','Córdoba reúne vida universitaria, sierras y tradiciones musicales como el cuarteto.','Córdoba combines university life, hills and musical traditions such as cuarteto.','un concierto y una excursión','a concert and an outing'),
 r('cuyo','Cuyo y Mendoza','Cuyo and Mendoza','🍇',-68.85,-32.89,'oeste','En Mendoza, los viñedos conviven con paisajes andinos y una gestión del agua fundamental en un ambiente árido.','In Mendoza, vineyards coexist with Andean scenery and essential water management in an arid environment.','una visita a los viñedos','a vineyard visit'),
 r('norte','Salta y Jujuy','Salta and Jujuy','🦙',-65.4,-24.2,'norte','El Norte reúne quebradas, puna, valles y también yungas: no es solamente desierto.','The North has ravines, high plateau, valleys and cloud forests: it is not only desert.','una ruta por la quebrada','a trip through the ravine'),
 r('litoral','Litoral e Iguazú','Litoral and Iguazú','🦋',-54.44,-25.69,'norte','Iguazú está en Misiones, en un entorno de selva subtropical. El Litoral también incluye grandes ríos y humedales.','Iguazú is in Misiones, in subtropical forest. The Littoral also includes major rivers and wetlands.','una visita a las cataratas','a waterfall visit'),
 r('patagonia','Patagonia','Patagonia','🧊',-71.3,-45.2,'sur','La Patagonia incluye estepa, lagos, montañas y costa atlántica. Las distancias hacen necesario elegir, no intentar verlo todo.','Patagonia includes steppe, lakes, mountains and the Atlantic coast. Distances make choosing essential rather than trying to see everything.','un viaje entre lagos y montañas','a trip among lakes and mountains','la Patagonia','Patagonia'),
 r('ushuaia','Tierra del Fuego y Ushuaia','Tierra del Fuego and Ushuaia','🐧',-68.3,-54.8,'sur','Ushuaia está en la isla Grande de Tierra del Fuego. Su ubicación austral no significa que siempre haya nieve.','Ushuaia is on the main island of Tierra del Fuego. Its southern location does not mean there is always snow.','un paseo junto al canal Beagle','a walk beside the Beagle Channel')
];
export const spainRegions:Region[]=[
 r('madrid','Madrid','Madrid','🖼️',-3.7,40.42,'interior','Madrid combina museos, barrios y conexiones ferroviarias con otras ciudades.','Madrid combines museums, neighbourhoods and rail connections to other cities.','una tarde de museos','an afternoon of museums'),
 r('catalunya','Cataluña','Catalonia','🧩',2.17,41.39,'mediterraneo','Barcelona es una puerta de entrada a Cataluña, donde conviven el castellano y el catalán; el aranés también es oficial.','Barcelona is a gateway to Catalonia, where Spanish and Catalan coexist; Aranese is also official.','un paseo de arquitectura','an architecture walk'),
 r('valencia','Comunidad Valenciana','Valencian Community','🥘',-.38,39.47,'mediterraneo','La paella se vincula con Valencia; el valenciano y el castellano son lenguas cooficiales en la comunidad.','Paella is associated with Valencia; Valencian and Spanish are co-official in the community.','un almuerzo de arroz','a rice lunch'),
 r('andalucia','Andalucía','Andalusia','🎶',-5.98,37.39,'sur','El flamenco tiene una relación especial con Andalucía; la región también reúne ciudades, sierras y costas muy distintas.','Flamenco has a special relationship with Andalusia; the region also has very different cities, mountains and coasts.','una noche de música','an evening of music'),
 r('galicia','Galicia','Galicia','🐚',-8.54,42.88,'norte','Santiago de Compostela es destino de varios caminos. En Galicia conviven gallego y castellano.','Several pilgrimage routes reach Santiago de Compostela. Galician and Spanish coexist in Galicia.','una etapa del Camino','a stage of the Camino'),
 r('asturias','Asturias','Asturias','🍎',-5.85,43.36,'norte','Asturias combina costa cantábrica, montañas y cultura de la sidra.','Asturias combines the Cantabrian coast, mountains and cider culture.','un día entre costa y montaña','a day between coast and mountains'),
 r('cantabria','Cantabria','Cantabria','🐄',-3.8,43.46,'norte','Cantabria reúne costa, valles y patrimonio de arte rupestre.','Cantabria combines coast, valleys and rock-art heritage.','una visita cultural y rural','a cultural and rural visit'),
 r('euskadi','País Vasco','Basque Country','🍢',-2.94,43.26,'norte','El euskera y el castellano son cooficiales. Los pintxos pueden abrir una conversación sobre comer y compartir.','Basque and Spanish are co-official. Pintxos can start a conversation about eating and sharing.','una ruta de pintxos','a pintxo route','el País Vasco','the Basque Country'),
 r('navarra','Navarra','Navarre','🌳',-1.64,42.82,'norte','Navarra tiene paisajes atlánticos y más secos; el euskera es cooficial en la zona vascófona.','Navarre has Atlantic and drier landscapes; Basque is co-official in the Basque-speaking zone.','una salida al bosque','a forest outing'),
 r('castilla-leon','Castilla y León','Castile and Leon','🏰',-4.72,41.65,'interior','Castilla y León combina ciudades históricas, pueblos y amplios paisajes de interior.','Castile and Leon combines historic cities, villages and broad inland landscapes.','una ruta de patrimonio','a heritage route'),
 r('castilla-mancha','Castilla-La Mancha','Castile-La Mancha','📖',-4.03,39.86,'interior','Los molinos y paisajes manchegos permiten hablar de literatura y de la vida actual fuera de las grandes ciudades.','La Mancha windmills and landscapes invite discussion of literature and present-day life outside big cities.','un recorrido literario','a literary trip'),
 r('aragon','Aragón','Aragon','⛰️',-.89,41.65,'interior','Aragón se extiende desde los Pirineos hasta paisajes de interior, con Zaragoza como capital.','Aragon extends from the Pyrenees to inland landscapes, with Zaragoza as its capital.','una escapada a los Pirineos','a Pyrenees getaway'),
 r('extremadura','Extremadura','Extremadura','🦅',-6.34,39.48,'interior','Extremadura combina dehesas, observación de aves y patrimonio histórico como el de Mérida.','Extremadura combines dehesa landscapes, birdwatching and historic heritage such as Mérida.','una mañana de observación de aves','a morning of birdwatching'),
 r('murcia','Región de Murcia','Region of Murcia','🥬',-1.13,37.98,'mediterraneo','La Región de Murcia permite comparar huerta, ciudad y costa mediterránea.','The Region of Murcia offers contrasts between market gardens, city and Mediterranean coast.','una visita al mercado','a market visit'),
 r('rioja','La Rioja','La Rioja','🍷',-2.45,42.46,'interior','La Rioja se vincula con el vino y ofrece también patrimonio, pueblos y senderos.','La Rioja is associated with wine and also offers heritage, villages and trails.','una conversación en una bodega','a conversation at a winery'),
 r('baleares','Islas Baleares','Balearic Islands','⛵',2.65,39.57,'islas','Las Baleares están en el Mediterráneo. Castellano y catalán son cooficiales; la vida isleña continúa fuera de la temporada turística.','The Balearics lie in the Mediterranean. Spanish and Catalan are co-official; island life continues outside the tourist season.','un paseo por una cala','a cove walk','las Islas Baleares','the Balearic Islands'),
 r('canarias','Islas Canarias','Canary Islands','🌋',-16.63,28.29,'islas','Canarias está en el Atlántico, frente al noroeste de África. Sus islas tienen paisajes y climas variados.','The Canaries lie in the Atlantic off northwestern Africa. The islands have varied landscapes and climates.','una ruta volcánica','a volcanic route','las Islas Canarias','the Canary Islands'),
 r('ceuta','Ceuta','Ceuta','⛴️',-5.32,35.89,'ciudades','Ceuta es una ciudad autónoma en el norte de África, junto al estrecho de Gibraltar.','Ceuta is an autonomous city in North Africa beside the Strait of Gibraltar.','una conversación junto al puerto','a conversation by the port'),
 r('melilla','Melilla','Melilla','🏛️',-2.94,35.29,'ciudades','Melilla es una ciudad autónoma en el norte de África, con patrimonio modernista.','Melilla is an autonomous city in North Africa with modernist heritage.','un paseo por el centro','a walk through the centre')
];

// A display heading may group regions; spoken destinations need their own articles.
const destinations:Record<string,[string,string]>={
 stockholm:['Estocolmo','Stockholm'],west:['Gotemburgo','Gothenburg'],skane:['Malmö','Malmö'],lakes:['Värmland','Värmland'],'high-coast':['la Costa Alta','the High Coast'],kiruna:['Kiruna','Kiruna'],
 pampas:['las Pampas','the Pampas'],cuyo:['Mendoza','Mendoza'],litoral:['Iguazú','Iguazú'],ushuaia:['Ushuaia','Ushuaia'],
 valencia:['la Comunidad Valenciana','the Valencian Community'],murcia:['la Región de Murcia','the Region of Murcia']
};
for(const region of [...swedenRegions,...argentinaRegions,...spainRegions]) if(destinations[region.id]) region.destination=p(...destinations[region.id]);
