import {author} from '../schema.mjs';
export default author('A2',{
 name:'Frases que se conectan',demand:'Oraciones cotidianas, reconstrucción y pausas entre ideas.',objective:'Reconstruye planes y rutinas al escuchar palabras conectadas.',warmup:'Cuenta qué vas a hacer después de la clase. ¿Qué palabras dices juntas?',teacher:'Usa situaciones familiares. Pide escuchar, reconstruir y cambiar un detalle; compara un ritmo cómodo con otro algo más ágil.',avoid:'No confundas velocidad con fluidez. No exijas nombres técnicos para reconocer una conexión.',extension:'Elige el banco opcional para pasar de planes a experiencias sin repetir todas las tareas.'},[
 {prompt:'¿La visita es antes o después de comer?',text:'Voy a visitar a una amiga después de comer.',options:['Antes de comer','Después de comer'],answer:1,explanation:'«Visitar a una amiga» conecta palabras que funcionan juntas. El final da el momento del plan.',transfer:'Cuenta a quién vas a visitar y cuándo, en una sola oración.',teacher:'Primero pide el sentido general; en la repetición dirige la atención a después de comer.'},
 {prompt:'¿Qué problema tuvo la persona esta mañana?',text:'Esta mañana perdí el autobús y llegué tarde al trabajo.',options:['Perdió el autobús','Olvidó una cita'],answer:0,explanation:'«Perdí el autobús» se escucha dentro de una cadena, no como tres grabaciones sueltas.',transfer:'Cuenta una llegada tarde real o inventada y su causa.',teacher:'No evalúes conjugaciones durante el primer eco. Elige un tramo que el oyente no reconoció.'},
 {prompt:'Agrupa primero el momento y después las dos acciones. Propón pausas que ayuden al oyente.',text:'El sábado por la mañana, voy al mercado y después preparo el almuerzo.',tokens:['El','sábado','por','la','mañana,','voy','al','mercado','y','después','preparo','el','almuerzo.'],target:[4,7],explanation:'Una opción es «El sábado por la mañana | voy al mercado | y después preparo el almuerzo». También puedes unir las dos acciones en un grupo más largo.',transfer:'Cuenta tu sábado con tres grupos cómodos.',teacher:'Pide leer la propuesta en voz alta. Acepta la versión sin pausa antes de y si es inteligible.'},
 {prompt:'Encuentra las dos uniones entre consonante final y vocal inicial.',text:'Mis amigos van a cenar.',tokens:['Mis','amigos','van','a','cenar.'],target:[0,2],explanation:'«Mis‿amigos» y «van‿a» permiten enlazar consonante y vocal. La escritura no cambia.',transfer:'Cambia cenar por estudiar. Repite despacio y después a ritmo cómodo.',teacher:'En variedades con debilitamiento de s, no impongas otra pronunciación; trabaja especialmente van a.'},
 {prompt:'Escucha el mensaje de la cita y reconstruye la secuencia.',text:'Tengo una cita a las ocho en el centro.',tokens:['en el centro.','a las ocho','Tengo una cita'],target:[2,1,0],explanation:'Primero aparece la cita, después la hora y por último el lugar. Cada pieza es un grupo útil.',transfer:'Dale al profe otra hora y otro lugar; pídele que confirme los datos.',teacher:'Repite sin mostrar la solución y pregunta qué información falta en su versión.'},
 {prompt:'¿A o B ayuda más a seguir el plan sin cortes palabra por palabra?',text:'Después del trabajo voy a tomar algo con Ana.',options:['A','B'],answer:1,explanation:'B mantiene unidades de sentido. Los cortes fabricados de A separan palabras que podrían fluir juntas.',transfer:'Di el mismo plan a dos velocidades cómodas, conservando las vocales.',teacher:'No premies la versión más rápida si pierde claridad. Compara el esfuerzo del oyente.'},
 {prompt:'Escucha la propuesta y cambia el día sin romper el resto de la frase.',text:'Podemos ir a la playa el domingo.',explanation:'Cambiar una información no exige volver a decir cada palabra de manera aislada.',transfer:'Propón otro día y después otro lugar. El profe acepta una de las dos propuestas.',teacher:'Deja que ensaye el grupo nuevo solo una vez; después pide la frase completa.'},
 {prompt:'Escucha cómo se organiza una rutina. Cuenta la tuya con dos momentos diferentes.',text:'Antes de trabajar desayuno en casa. Cuando termino, salgo a caminar con una amiga.',explanation:'Las pausas organizan dos momentos del día; dentro de cada momento las palabras siguen conectadas.',transfer:'Habla de tu mañana y tu tarde durante unos veinte segundos. Tu compañero resume el orden.',teacher:'Escucha si el alumno puede terminar una idea antes de parar, sin exigir una respiración enorme.'},
 {prompt:'Banco opcional: ¿qué cambió en el viaje?',text:'Íbamos a salir el viernes, pero salimos el sábado.',options:['El destino','El día de salida'],answer:1,explanation:'El contraste viernes/sábado organiza la información nueva.',transfer:'Cuenta un pequeño cambio de plan con pero.',teacher:'Diferencia el problema de tiempo verbal del problema de reconocer la fecha.'},
 {prompt:'Banco opcional: organiza un consejo y su motivo.',text:'Lleva un abrigo, porque por la noche hace frío.',tokens:['Lleva','un','abrigo,','porque','por','la','noche','hace','frío.'],target:[2],explanation:'La pausa propuesta separa el consejo de la explicación. «Un abrigo» puede sonar conectado.',transfer:'Dale otro consejo de viaje a tu compañero.',teacher:'Acepta una versión continua si se entiende; pide comparar con la pausa propuesta.'}
],{prompt:'Organiza una salida con tu compañero.',steps:['Elige lugar, día, horario y una actividad. Prepara palabras clave durante un minuto.','Explica el plan durante veinte o treinta segundos, con pausas entre ideas. El compañero confirma dos datos.','El compañero cambia la hora. Reformula el plan completo; repítelo después de una devolución sobre conexión o claridad.'],support:'El… vamos a… / Después podemos… / Mejor a las… / Entonces quedamos…',criteria:['Los grupos cotidianos se dicen sin pausas innecesarias entre todas las palabras.','El cambio de hora se entiende dentro del plan completo.','Las pausas separan el lugar, el momento o las acciones con claridad.']});
