import {author} from '../schema.mjs';
export default author('B1',{
 name:'Hablar en grupos',demand:'Ideas completas, palabras destacadas y respuesta espontánea.',objective:'Organizá una respuesta natural en grupos que el oyente pueda seguir.',warmup:'Contá un cambio de planes reciente sin preparar el texto. ¿Dónde necesitaste parar?',teacher:'Pasá de escuchar el sentido global a reconstruir grupos. Pedí justificar una pausa con el significado y transferirla a una experiencia propia.',avoid:'No marques como error toda vacilación. Trabajá una ruptura que realmente dificulte seguir la idea.',extension:'Usá el banco para introducir una condición y un contraste después de lograr el relato central.'},[
 {prompt:'¿Por qué cambió el lugar del encuentro? Escuchá la relación entre las ideas.',text:'Como empezó a llover, nos encontramos en el café de la esquina y dejamos el paseo para mañana.',options:['Porque cerró el café','Porque empezó a llover'],answer:1,explanation:'El primer grupo da la causa. Después aparecen una decisión y una alternativa; reconocer grupos ayuda a recuperar la historia.',transfer:'Explicá un cambio de plan con una causa y una decisión.',teacher:'Pedí primero un resumen, después un eco de la causa. No pidas transcribir todo.'},
 {prompt:'¿Qué dato necesita corregir la persona?',text:'No dije que venía el lunes. Dije que el lunes iba a confirmar si podía venir.',options:['Cuándo confirma su asistencia','Quién viene con ella'],answer:0,explanation:'El segundo enunciado corrige la interpretación del primero. «Iba a confirmar» debe poder reconocerse como parte de un grupo.',transfer:'Corregí un malentendido sobre una invitación sin repetir palabra por palabra.',teacher:'La clave está en la acción confirmar; pedí destacarla en la producción, sin afirmar un foco acústico que no se verificó.'},
 {prompt:'Proponé grupos para separar el problema, la decisión y el resultado.',text:'El tren se retrasó, así que tomamos un autobús y llegamos justo a tiempo.',tokens:['El tren','se retrasó,','así que','tomamos un autobús','y llegamos','justo a tiempo.'],target:[1,3],explanation:'Problema | decisión | resultado es una organización posible. Una frase larga puede admitir varios recorridos claros.',transfer:'Contá otro viaje con esa organización, sin leer las piezas.',teacher:'Pedí que el oyente identifique las tres partes antes de comentar la colocación exacta de las pausas.'},
 {prompt:'Marcá las uniones consonante–vocal que podrías mantener dentro de estos grupos.',text:'Llegamos al hotel al anochecer.',tokens:['Llegamos','al','hotel','al','anochecer.'],target:[0,1,2,3],explanation:'Hay contacto consonante–vocal en las cuatro fronteras; la h de hotel no representa un sonido consonántico. No es obligatorio realizar todas las uniones igual en cada variedad.',transfer:'Usá «al hotel» en una frase nueva y decila como un grupo cómodo.',teacher:'La s puede variar. Usá la l de al hotel y hotel al como foco estable, sin borrar vocales.'},
 {prompt:'Reconstruí los grupos del mensaje y explicá qué queda pendiente.',text:'Si salgo a tiempo, paso por tu casa antes de ir al cine.',tokens:['antes de ir al cine.','paso por tu casa','Si salgo a tiempo,'],target:[2,1,0],explanation:'La condición precede al plan. Escuchar el primer grupo evita interpretar la visita como algo seguro.',transfer:'Cambiá la condición y mantené el resto de la propuesta.',teacher:'Separá comprensión de la condición y memoria literal: se admite primero una paráfrasis oral.'},
 {prompt:'Compará A y B. ¿Cuál permite seguir la explicación con menos esfuerzo?',text:'Quería ir a la reunión, pero tuve que quedarme en casa.',options:['A','B'],answer:0,explanation:'La versión A conserva grupos relacionados con una intención y un obstáculo. B introduce cortes didácticos entre palabras.',transfer:'Contá una intención frustrada y destacá la palabra que explica el obstáculo.',teacher:'Pedí explicar qué grupo costó recuperar en B. Evitá presentar un patrón de duración como regla del español.'},
 {prompt:'Retené un grupo del audio, repetilo y cambiá quién realiza la acción.',text:'Mi hermano me avisó que iba a llegar más tarde.',explanation:'Podés reutilizar «me avisó que iba a llegar» como secuencia y cambiar la persona sin perder continuidad.',transfer:'Transmití un aviso real o inventado. El compañero te pregunta por la hora y vos ampliás.',teacher:'Tras el eco, ocultá el apoyo para provocar recuperación y no solo lectura.'},
 {prompt:'Escuchá una explicación breve y respondé con tu propia experiencia.',text:'Prefiero trabajar cerca de casa porque pierdo menos tiempo en el viaje. De todos modos, me gusta salir a caminar antes de empezar.',explanation:'La razón y el matiz organizan dos grupos mayores. Las palabras funcionales no necesitan convertirse en golpes separados.',transfer:'Hablá treinta o cuarenta y cinco segundos sobre tu rutina ideal. Incluí una razón y un matiz.',teacher:'El oyente resume la preferencia antes de dar una sugerencia sobre agrupación.'},
 {prompt:'Banco opcional: ¿la propuesta ya está confirmada?',text:'Podríamos encontrarnos a las ocho, siempre que vos salgas a tiempo.',options:['Sí, sin condiciones','No, depende del horario de salida'],answer:1,explanation:'El final limita la propuesta; no es un agregado sin importancia.',transfer:'Proponé una actividad con una condición que cambie la decisión.',teacher:'Escuchá especialmente la conexión de siempre que con la condición.'},
 {prompt:'Banco opcional: separá la expectativa del resultado inesperado.',text:'Aunque parecía una buena idea, al final nos salió bastante caro.',tokens:['Aunque parecía','una buena idea,','al final','nos salió','bastante caro.'],target:[1],explanation:'La frontera tras idea permite reconocer el contraste. Otra distribución es posible si conserva la relación.',transfer:'Contá una experiencia que no salió como esperabas.',teacher:'Pedí primero anticipar qué tipo de final vendría y después producirlo.'}
],{prompt:'Una decisión que cambió tu día.',steps:['Elegí un cambio de planes y anotá solo tres palabras: causa, decisión, resultado. Prepará la respuesta durante un minuto.','Hablá treinta o cuarenta y cinco segundos. El oyente resume la relación entre las tres partes y pregunta por un detalle.','Respondé sin leer. Repetí el tramo menos claro después de una sugerencia sobre agrupación, conservando las palabras importantes.'],support:'Al principio… / Como… / Así que… / Al final… / Lo que pasó fue que…',criteria:['La respuesta tiene grupos de sentido reconocibles.','Las palabras que expresan causa y resultado siguen siendo claras.','Puede ampliar o reparar un tramo sin volver a fragmentar toda la respuesta.']});
