"use client";
/* eslint-disable @next/next/no-img-element -- Wikimedia thumbnails are remote, attributed resources and the hosted image optimizer is intentionally bypassed. */
import Link from "next/link";
import {useEffect,useMemo,useState,type CSSProperties,type KeyboardEvent} from "react";
import "../suiza-en-relieve/style.css";
import "./style.css";
import {connectors,depthMoves,regionNames,starters,states,type Pair,type StateRegion,type USState} from "./state-data";
import {stateShapes} from "./map-data";
import {placesByCode,type StatePlace} from "./places";
import {iconForPlace,iconFromLegacySignal,usa3dSprites,type USA3DIcon} from "./visuals";

type Screen="cover"|"map"|"state";
type Region="todo"|StateRegion;
type Stance="elegiria"|"depende"|"otra"|null;
const stancePairs:Record<Exclude<Stance,null>,Pair>={elegiria:{es:"Yo elegiría…",en:"I would choose…"},depende:{es:"Para mí, depende de…",en:"For me, it depends on…"},otra:{es:"Veo otra posibilidad…",en:"I see another possibility…"}};
const stateByAtlasName=new Map(states.map(state=>[state.atlasName,state]));
const allCodes=new Set(states.map(state=>state.code));

function USMark(){return <span className="us50-mark" aria-hidden="true"><i>★</i><b>USA</b></span>}
function Atmosphere(){return <div className="ch-atmosphere us50-atmosphere" aria-hidden="true"><i/><i/><i/><span/><span/><span/><b/><b/></div>}
function USA3DSprite({icon,className=""}:{icon:USA3DIcon;className?:string}){const sprite=usa3dSprites[icon];return <span className={`usa3d-sprite sprite-${icon} ${className}`} role="img" aria-label={sprite.label} style={{"--sprite-sheet":`url(/usa-3d/americana-atlas-${sprite.sheet}.webp)`,"--sprite-x":`${sprite.column*25}%`,"--sprite-y":`${sprite.row*(100/3)}%`} as CSSProperties}/>}
function USGuide({className=""}:{className?:string}){return <span className={"us50-guide "+className} aria-hidden="true"><img src="/usa-3d/americana-guide.webp" alt=""/></span>}
function StateScene({state,compact=false}:{state:USState;compact?:boolean}){return <div className={"us50-scene"+(compact?" compact":"")} role="img" aria-label={"Escena 3D animada típica de "+state.name}><span className="us50-scene-label">{state.code} · CULTURA EN MOVIMIENTO</span><div className="us50-scene-stage">{state.sceneItems.map((item,index)=><USA3DSprite key={item+"-"+index} icon={iconFromLegacySignal(item)} className={"scene-"+index}/>)}</div><USGuide className="us50-scene-guide"/><b>{state.hook.es}</b></div>}

type CommonsPhoto={src:string;href:string;title:string};
type CommonsPage={title?:string;imageinfo?:Array<{thumburl?:string;url?:string;descriptionurl?:string;mime?:string}>};
function PlacePhoto({place,state}:{place:StatePlace;state:USState}){
  const [photo,setPhoto]=useState<CommonsPhoto|null>(null),[failed,setFailed]=useState(false);
  useEffect(()=>{
    const controller=new AbortController();
    const params=new URLSearchParams({
      action:"query",generator:"search",gsrsearch:place.imageSearch,gsrnamespace:"6",gsrlimit:"12",
      prop:"imageinfo",iiprop:"url|mime",iiurlwidth:"1200",format:"json",formatversion:"2",origin:"*",
    });
    fetch(`https://commons.wikimedia.org/w/api.php?${params.toString()}`,{signal:controller.signal})
      .then(response=>{if(!response.ok)throw new Error("image search failed");return response.json()})
      .then(data=>{
        const pages=((data as {query?:{pages?:CommonsPage[]}})?.query?.pages??[]);
        const usable=pages.filter(page=>page.imageinfo?.[0]?.thumburl||page.imageinfo?.[0]?.url);
        const match=usable.find(page=>["image/jpeg","image/png","image/webp"].includes(page.imageinfo?.[0]?.mime||""))||usable[0];
        const image=match?.imageinfo?.[0];
        if(!match||!image)throw new Error("no image found");
        setPhoto({src:image.thumburl||image.url||"",href:image.descriptionurl||`https://commons.wikimedia.org/wiki/${encodeURIComponent(match.title||"")}`,title:match.title?.replace(/^File:/,"")||place.name});
      })
      .catch(error=>{if(error instanceof DOMException&&error.name==="AbortError")return;setFailed(true)});
    return()=>controller.abort();
  },[place.imageSearch,place.name]);
  const searchUrl=`https://commons.wikimedia.org/w/index.php?search=${encodeURIComponent(place.imageSearch)}&title=Special:MediaSearch&type=image`;
  return <figure className={"us50-place-photo "+(photo?"is-ready":"is-loading")}>
    {photo?<>{/* Direct loading avoids the hosted image optimizer and preserves the Wikimedia attribution URL. */}<img src={photo.src} alt={`Fotografía de ${place.name}, ${state.name}`} loading="lazy" referrerPolicy="no-referrer"/></>:<div aria-label={failed?"No se pudo cargar la fotografía":"Cargando fotografía"}><span>{state.code}</span><b>{place.name}</b></div>}
    <USA3DSprite icon={iconForPlace(place.type,place.name)} className="us50-place-object"/><USGuide className="us50-place-guide"/>
    <figcaption><span>PHOTO REFERENCE · {place.name}</span><a href={photo?.href||searchUrl} target="_blank" rel="noreferrer">WIKIMEDIA COMMONS ↗</a></figcaption>
  </figure>;
}

function USMap({selected,onSelect,visibleCodes,visited,compact=false}:{selected:USState;onSelect:(state:USState)=>void;visibleCodes:Set<string>;visited:Set<string>;compact?:boolean}){
  const choose=(atlasName:string)=>{const state=stateByAtlasName.get(atlasName);if(state&&visibleCodes.has(state.code))onSelect(state)};
  const keys=(event:KeyboardEvent<SVGGElement>,atlasName:string)=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();choose(atlasName)}};
  const selectedShape=stateShapes.find(shape=>shape.name===selected.atlasName);
  const suffix=compact?"mini":"main";
  return <div className={"ch-map-orbit us50-map-orbit"+(compact?" compact":"")}><div className="ch-map-shadow"/>
    <svg className="ch-swiss-map us50-map" viewBox="-70 0 1050 630" role="img" aria-label="Mapa real tridimensional interactivo de los 50 estados de Estados Unidos">
      <defs><filter id={"us50-glow-"+suffix} x="-35%" y="-35%" width="170%" height="180%"><feGaussianBlur stdDeviation="7" result="blur"/><feMerge><feMergeNode in="blur"/><feMergeNode in="SourceGraphic"/></feMerge></filter><linearGradient id={"us50-side-"+suffix} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#153a57"/><stop offset="1" stopColor="#020c16"/></linearGradient></defs>
      <text x="8" y="345" className="us50-water-label">PACIFIC</text><text x="941" y="365" className="us50-water-label">ATLANTIC</text>
      {stateShapes.map(shape=>{const state=stateByAtlasName.get(shape.name)!;const selectedState=selected.code===state.code;const visible=visibleCodes.has(state.code);const classes=["ch-canton","us50-state",selectedState?"selected":"",visited.has(state.code)?"visited":"",visible?"":"filtered"].filter(Boolean).join(" ");return <g key={state.code} className={classes} role="button" tabIndex={visible?0:-1} aria-label={state.name+", estado "+state.number} onClick={()=>choose(shape.name)} onKeyDown={event=>keys(event,shape.name)} style={{"--canton":state.color} as CSSProperties}>{[14,10,6].map(offset=><path key={offset} d={shape.d} transform={"translate(0 "+offset+")"} className="ch-canton-side" fill={"url(#us50-side-"+suffix+")"} fillRule="evenodd"/>)}<path d={shape.d} className="ch-canton-top" fillRule="evenodd"/>{!compact&&<text x={shape.cx} y={shape.cy} className="ch-canton-code us50-state-code">{state.code}</text>}</g>})}
      {selectedShape&&<g className="ch-selected-label us50-selected-label" transform={"translate("+selectedShape.cx+" "+(selectedShape.cy-24)+")"}><circle r="18"/><text y="5">{selected.code}</text></g>}
    </svg><span className="ch-map-axis axis-one"/><span className="ch-map-axis axis-two"/><span className="ch-map-axis axis-three"/></div>;
}

export default function EstadosUnidosA2B1(){
  const [screen,setScreen]=useState<Screen>("cover"),[active,setActive]=useState<USState>(states[42]),[mapPick,setMapPick]=useState<USState>(states[42]),[question,setQuestion]=useState(0),[region,setRegion]=useState<Region>("todo"),[query,setQuery]=useState(""),[visited,setVisited]=useState<Set<string>>(new Set()),[englishVisible,setEnglishVisible]=useState(true),[stance,setStance]=useState<Stance>(null),[answerParts,setAnswerParts]=useState<Pair[]>([]),[placeFocus,setPlaceFocus]=useState(0);
  const visible=useMemo(()=>states.filter(state=>(region==="todo"||state.region===region)&&[state.name,state.nameEn,state.capital,state.hook.es,placesByCode[state.code].map(place=>place.name).join(" ")].join(" ").toLowerCase().includes(query.toLowerCase())),[region,query]);
  const visibleCodes=useMemo(()=>new Set(visible.map(state=>state.code)),[visible]),current=active.questions[question],currentFallback=active.questionFallbacks[question],activePlaces=placesByCode[active.code],focusedPlace=activePlaces[placeFocus],progress=Math.round(visited.size/states.length*100),answerPairs=[...(stance?[stancePairs[stance]]:[]),...answerParts],answerEs=answerPairs.map(part=>part.es.replace(/[…]+/g,"")).join(" "),answerEn=answerPairs.map(part=>part.en.replace(/[…]+/g,"")).filter(Boolean).join(" ");
  const show=(next:Screen)=>{setScreen(next);window.scrollTo({top:0,behavior:"smooth"})},enter=(state:USState,start=0)=>{setActive(state);setMapPick(state);setQuestion(start);setPlaceFocus(Math.min(start,3));setStance(null);setAnswerParts([]);setVisited(old=>new Set([...old,state.code]));show("state")},surprise=()=>{const pool=states.filter(state=>state.code!==active.code);const next=pool[Math.floor(Math.random()*pool.length)]||states[0];enter(next,Math.floor(Math.random()*6))},changeQuestion=(next:number)=>{const safe=Math.max(0,Math.min(5,next));setQuestion(safe);if(safe<4)setPlaceFocus(safe);setStance(null);setAnswerParts([]);document.querySelector(".ch-question-card")?.scrollIntoView({behavior:"smooth",block:"center"})},choosePlace=(index:number)=>{setPlaceFocus(index);setQuestion(index);setStance(null);setAnswerParts([])},addPart=(part:Pair)=>setAnswerParts(parts=>[...parts,part]),chooseRegion=(next:Region)=>{setRegion(next);const first=states.find(state=>next==="todo"||state.region===next);if(first)setMapPick(first)};
  return <main className={"ch-app us50-app "+(englishVisible?"":"ch-spanish-only")}>
    <nav className="ch-nav us50-nav"><Link href="/" className="ch-brand"><USMark/><span><b>CHESPANISH</b><small>AMERICAN FIELD GUIDE</small></span></Link><div className="ch-progress"><span>ESTADOS EXPLORADOS · STATES</span><i><b style={{width:progress+"%"}}/></i><strong>{visited.size}/50</strong></div><div className="ch-nav-actions"><button onClick={()=>setEnglishVisible(value=>!value)}>EN <b>{englishVisible?"ON":"OFF"}</b></button><button onClick={surprise}>★ SORPRESA</button><button onClick={()=>show(screen==="cover"?"map":"cover")}>{screen==="cover"?"MAPA":"INICIO"}</button></div></nav>

    {screen==="cover"&&<section className="ch-cover us50-cover"><Atmosphere/><div className="us50-cover-grid" aria-hidden="true"/><div className="ch-cover-copy us50-cover-copy"><div className="ch-level"><span>A2–B1</span> 100% CONVERSACIÓN · 100% CONVERSATION</div><p className="ch-eyebrow">50 ESTADOS · 200 PARADAS REALES · 300 PREGUNTAS PARA HABLAR</p><h1>UNITED<br/><em>STATES</em></h1><p className="us50-subtitle">IN DEPTH · EN RELIEVE</p><p className="ch-cover-lead">No es una “Ruta 40” ni un mapa con pines. <b>Cada estado es un territorio 3D real</b> y abre cuatro paradas propias para hablar de ciudades, naturaleza, música, historia, comida y vida cotidiana.<span className="ch-en">Every state is a real 3D territory and opens four local stops.</span></p><div className="us50-mobile-scene"><StateScene state={mapPick} compact/></div><div className="ch-cover-actions"><button onClick={()=>show("map")}>OPEN THE 3D MAP <span>→</span><small>ABRIR LOS 50 ESTADOS</small></button><button className="ghost" onClick={surprise}>★ RANDOM STATE<small>ESTADO SORPRESA</small></button></div><div className="ch-cover-stats"><article><b>50</b><span>estados reales<small>real states</small></span></article><article><b>200</b><span>paradas propias<small>local stops</small></span></article><article><b>300</b><span>preguntas A2/B1<small>A2/B1 prompts</small></span></article></div></div><div className="ch-hero-map us50-hero-map"><div className="ch-map-tag"><span>REAL BORDERS</span><b>50 STATES</b></div><USMap selected={mapPick} onSelect={setMapPick} visibleCodes={allCodes} visited={visited} compact/><StateScene state={mapPick} compact/></div></section>}

    {screen==="map"&&<section className="ch-map-page us50-map-page"><Atmosphere/><header className="ch-map-head"><div><span>THE 50-STATE CONVERSATION ATLAS</span><h1>Elegí un estado.<br/><em>Entrá en sus cuatro paradas.</em></h1></div><div><p>El mapa usa las fronteras reales de los 50 estados, incluyendo Alaska y Hawái. Cada pieza tiene volumen propio y abre cuatro lugares concretos con preguntas A2/B1.</p><p className="ch-en">The map uses the real boundaries of all 50 states. Every raised piece opens four specific places.</p><button onClick={surprise}>★ LET THE MAP DECIDE</button></div></header>
      <div className="ch-map-tools"><div><button className={region==="todo"?"active":""} onClick={()=>chooseRegion("todo")}>ALL 50</button>{(["noreste","sur","medio-oeste","montañas","pacifico"] as const).map(key=><button key={key} className={region===key?"active":""} onClick={()=>chooseRegion(key)}>{regionNames[key].es}</button>)}</div><label><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar estado, capital o parada…"/></label></div>
      <section className="ch-map-explorer"><div className="ch-map-panel us50-map-panel"><header><span>SELECT A STATE · ELEGÍ EL TERRITORIO</span><b>TRUE 3D RELIEF</b></header><USMap selected={mapPick} onSelect={setMapPick} visibleCodes={visibleCodes} visited={visited}/><footer><span><i/> SELECTED</span><span><i/> VISITED</span><a href="https://www.census.gov/geographies/mapping-files/time-series/geo/carto-boundary-file.html" target="_blank" rel="noreferrer">U.S. Census boundaries ↗</a></footer></div><aside className="ch-preview us50-preview" style={{"--canton":mapPick.color} as CSSProperties}><div className="ch-preview-top"><span>{mapPick.number}</span><USMark/><small>{mapPick.code}</small></div><p>{regionNames[mapPick.region].es} · CAPITAL {mapPick.capital}</p><h2>{mapPick.name}</h2><h3>{mapPick.hook.es}</h3><StateScene state={mapPick}/><div className="ch-fact"><span>FOUR LOCAL STOPS</span><b>{mapPick.fact.es}</b><small className="ch-en">{mapPick.fact.en}</small></div><div className="ch-preview-places"><span>DENTRO DEL ESTADO</span>{placesByCode[mapPick.code].map(place=><b key={place.name}>{place.name}</b>)}</div><div className="ch-preview-chips"><span>Capital: {mapPick.capital}</span><span>4 paradas</span><span>6 preguntas</span></div><button onClick={()=>enter(mapPick)}>ENTER {mapPick.code} <span>→</span><small>ENTRAR EN {mapPick.name.toUpperCase()}</small></button></aside></section>
      <section className="ch-canton-index us50-index"><header><div><span>ALL 50 STATES · LOS 50 ESTADOS</span><h2>Cada estado abre cuatro paradas propias.</h2></div><p>{visible.length} visibles · {visited.size} explorados</p></header><div>{visible.map(state=><button key={state.code} onClick={()=>setMapPick(state)} className={(mapPick.code===state.code?"active ":"")+(visited.has(state.code)?"visited":"")} style={{"--canton":state.color} as CSSProperties}><span>{state.number}</span><USA3DSprite icon={iconFromLegacySignal(state.sceneItems[0])} className="us50-index-object"/><i>{state.code}</i><b>{state.name}</b><small>{placesByCode[state.code].map(place=>place.name).join(" · ")}</small><em>VIEW →</em></button>)}</div></section></section>}

    {screen==="state"&&<section className="ch-canton-page us50-state-page" style={{"--canton":active.color} as CSSProperties}><header className="ch-canton-hero us50-state-hero"><Atmosphere/><USGuide className="us50-hero-guide"/><div className="ch-canton-topbar"><button onClick={()=>show("map")}>← 50-STATE MAP</button><span>STATE {active.number} · {regionNames[active.region].en.toUpperCase()}</span><button onClick={surprise}>★ ANOTHER STATE</button></div><div className="ch-canton-title"><small>{active.code} · CAPITAL {active.capital}</small><h1>{active.name}</h1><h2>{active.hook.es}</h2><p className="ch-en">Explore four local signals before choosing your position.</p><div><span>4 local stops</span><span>6 A2/B1 questions</span><span>bilingual support</span></div><StateScene state={active}/></div><div className="ch-canton-map"><USMap selected={active} onSelect={state=>enter(state)} visibleCodes={allCodes} visited={visited} compact/><b>{active.code}</b></div></header>
      <div className="ch-classroom"><section className="ch-canton-fact"><span>BEFORE YOU SPEAK</span><div><b>{active.fact.es}</b><small className="ch-en">{active.fact.en}</small></div><strong>{active.mission.es}<small className="ch-en">{active.mission.en}</small></strong></section>
        <section className="ch-place-deck"><header><div><span>INSIDE {active.name.toUpperCase()}</span><h2>Cuatro paradas que explican el estado.</h2><p className="ch-en">Four stops that explain this state.</p></div><p>Cada parada tiene una fotografía real, contexto local, una pregunta propia y una alternativa si todavía no conocés el lugar.</p></header><div className="ch-place-tabs">{activePlaces.map((place,index)=><button key={place.name} className={placeFocus===index?"active":""} onClick={()=>choosePlace(index)}><USA3DSprite icon={iconForPlace(place.type,place.name)} className="us50-tab-object"/><span>STOP {String(index+1).padStart(2,"0")}</span><b>{place.name}</b><i>→</i></button>)}</div><article className="ch-place-focus" key={active.code+"-"+placeFocus}><div><PlacePhoto place={focusedPlace} state={active}/><span>STOP {String(placeFocus+1).padStart(2,"0")} · {focusedPlace.type.toUpperCase()}</span><h3>{focusedPlace.name}</h3><p>{focusedPlace.context.es}</p></div><div><span>PLACE PROMPT · PREGUNTA</span><b>{focusedPlace.prompt.es}</b><small className="ch-en">{focusedPlace.prompt.en}</small><aside className="us50-place-fallback"><span>¿NO CONOCÉS ESTE LUGAR? NO PASA NADA.</span><b>{focusedPlace.fallback.es}</b><small className="ch-en">{focusedPlace.fallback.en}</small></aside><button onClick={()=>addPart(starters[placeFocus])}>+ ADD A STARTER</button></div></article></section>
        <section className="ch-question-card"><div className="ch-question-number"><span>QUESTION · PREGUNTA</span><b>{String(question+1).padStart(2,"0")} <i>/ 06</i></b></div><div className="ch-question-copy"><small>{active.code} · {active.name}</small><h2>{current.es}</h2><p className="ch-en">{current.en}</p><aside className="us50-question-fallback"><span>SI NO CONOCÉS EL LUGAR, USÁ ESTA PREGUNTA</span><b>{currentFallback.es}</b><small className="ch-en">{currentFallback.en}</small></aside><div><span>ELEGÍ</span><i>→</i><span>DA UNA RAZÓN</span><i>→</i><span>AGREGÁ UN EJEMPLO</span></div></div><USMark/></section>
        <section className="ch-response-grid"><article className="ch-stance"><span>1 · CHOOSE A POSITION</span><div>{(["elegiria","depende","otra"] as const).map(value=><button key={value} className={stance===value?"active":""} onClick={()=>setStance(value)}><b>{stancePairs[value].es}</b><small className="ch-en">{stancePairs[value].en}</small></button>)}</div></article><article className="ch-starters"><span>2 · START THE IDEA</span><div>{starters.slice(0,3).map(item=><button key={item.es} onClick={()=>addPart(item)}><b>{item.es}</b><small className="ch-en">{item.en}</small><i>+</i></button>)}</div></article><article className="ch-connectors"><span>3 · CONNECT</span><div>{connectors.map(item=><button key={item.es} onClick={()=>addPart(item)}><b>{item.es}</b><small className="ch-en">{item.en}</small><i>+</i></button>)}</div></article></section>
        <section className="ch-answer-lab" aria-live="polite"><header><div><span>YOUR A2/B1 DRAFT</span><h2>Construí una respuesta y después decila con tus palabras.</h2></div><button disabled={!answerPairs.length} onClick={()=>{setStance(null);setAnswerParts([])}}>CLEAR · BORRAR</button></header><div className={"ch-answer-canvas "+(answerPairs.length?"has-answer":"")}>{answerPairs.length?answerPairs.map((part,index)=><button key={part.es+"-"+index} onClick={()=>{if(stance&&index===0)setStance(null);else{const partIndex=index-(stance?1:0);setAnswerParts(parts=>parts.filter((_,i)=>i!==partIndex))}}}><b>{part.es}</b><small className="ch-en">{part.en}</small></button>):<p><b>Tocá una posición, un comienzo y uno o dos conectores.</b><span className="ch-en">Tap a position, a starter and one or two connectors.</span></p>}</div>{answerPairs.length>0&&<div className="ch-answer-readout"><b>{answerEs}</b>{answerEn&&<span className="ch-en">{answerEn}</span>}</div>}</section>
        <section className="ch-wordbank"><header><div><span>{active.code} WORDBANK</span><h2>Palabras para seguir hablando.</h2></div><p>Tocalas para agregarlas al borrador.</p></header><div>{active.words.map((word,index)=><button key={word.es} onClick={()=>addPart(word)}><span>{String(index+1).padStart(2,"0")}</span><b>{word.es}</b><small className="ch-en">{word.en}</small><i>+</i></button>)}</div></section><section className="ch-depth"><header><span>ONE MORE ROUND</span><h2>Elegí una misión extra.</h2></header><div>{depthMoves.map((move,index)=><button key={move.es}><span>{index+1}</span><b>{move.es}</b><small className="ch-en">{move.en}</small></button>)}</div></section><nav className="ch-question-nav"><button disabled={question===0} onClick={()=>changeQuestion(question-1)}>← PREVIOUS</button><div>{active.questions.map((_,index)=><button key={index} className={question===index?"active":""} onClick={()=>changeQuestion(index)}>{index+1}</button>)}</div><button onClick={()=>question===5?surprise():changeQuestion(question+1)}>{question===5?"NEXT STATE →":"NEXT →"}</button></nav>
      </div></section>}
  </main>;
}
