import {decisionChallenge} from '../conversation-families/game-challenges';
import * as base from './data';
import type {CEFRLevel} from '../conversation-families/types';
import {gameDemand} from '../conversation-families/game-language';
const scenarios:[base.CityChoice['category'],string,string,string,string,string][]=[
 ['BASE','Hay un espacio libre. / There is an empty space.','Parque / Park','Casas / Houses','Hay árboles. / There are trees.','Hay casas nuevas. / There are new houses.'],
 ['MOVILIDAD','Necesitas transporte. / You need transport.','Autobús / Bus','Tren / Train','Llega a todos los barrios. / It reaches all neighbourhoods.','Es rápido. / It is fast.'],
 ['VIVIENDA','Llegan más personas. / More people arrive.','Casas pequeñas / Small houses','Pisos grandes / Large flats','Cuestan menos. / They cost less.','Hay más espacio. / There is more space.'],
 ['VIDA','Es sábado. / It is Saturday.','Música / Music','Silencio / Quiet','Hay una fiesta. / There is a party.','La gente descansa. / People rest.'],
 ['FUTURO','La ciudad tiene dinero. / The city has money.','Escuela / School','Hospital / Hospital','Los niños estudian. / Children study.','Hay más ayuda. / There is more help.'],
];
export function cityGameContent(level:CEFRLevel){
 if(level==='B1')return base;
 const low=['A0','A1','A2'].includes(level),t=(s:string)=>level==='A0'?s:s.split(' / ')[0],q=(s:string)=>`${s} ${gameDemand[level]}`;
 if(!low)return {...base,cityChoices:base.cityChoices.map(c=>({...c,question:decisionChallenge(level,c.options[0].label,c.options[1].label),follow:level==='B2'?`¿Qué límite de presupuesto pondrías a «${c.options[0].label}»? Compáralo con la alternativa.`:level==='C1'?`Defiende tu decisión ante una persona perjudicada por «${c.options[1].label}». Reconoce un interés legítimo.`:`Reformula la justificación de tu elección sin convertir «${c.options[0].label}» en una solución universal.`})),priorityRounds:base.priorityRounds.map(c=>({...c,follow:decisionChallenge(level,c.items[0],c.items[1])})),urbanProblems:base.urbanProblems.map(c=>({...c,detail:q(c.detail),options:c.options.map(o=>({...o,consequence:q(o.consequence)})) as base.UrbanProblem['options']})),negotiationRounds:base.negotiationRounds.map(c=>({...c,shared:decisionChallenge(level,c.sideA.wants,c.sideB.wants),pressure:`${c.pressure} ${level==='B2'?'Reparte una concesión y un beneficio para cada parte.':level==='C1'?'Identifica qué interés no se había expresado y renegocia sin desautorizar a nadie.':'Reescribe oralmente el acuerdo para que una ambigüedad no oculte el desacuerdo pendiente.'}`})),changeRounds:base.changeRounds.map(c=>({...c,question:q(c.question)})),cityEvents:base.cityEvents.map(c=>({...c,question:q(c.question)})),bossPrompts:base.bossPrompts.map(([title,prompt])=>[title,q(prompt)] as [string,string]),finalQuestions:base.finalQuestions.map(q)};
 const cityChoices:base.CityChoice[]=scenarios.map(([category,question,a,b,fa,fb],i)=>({id:`${level}-city-${i}`,category,question:t(question),options:[{label:t(a),impact:base.cityChoices[i].options[0].impact,feedback:t(fa)},{label:t(b),impact:base.cityChoices[i].options[1].impact,feedback:t(fb)}],follow:level==='A0'?`Quiero ${a.split(' / ')[0].toLowerCase()}. / I want ${a.split(' / ')[1].toLowerCase()}.`:`¿Qué prefieres para tu barrio? ${gameDemand[level]}`}));
 const priorityRounds:base.PriorityRound[]=[{id:`${level}-priority`,situation:t('Elige dos cosas para tu ciudad. / Choose two things for your city.'),items:['Agua / Water','Parque / Park','Escuela / School','Autobús / Bus','Hospital / Hospital'].map(t) as base.PriorityRound['items'],follow:level==='A0'?'Quiero agua y un parque. / I want water and a park.':`Explica tus dos prioridades. ${gameDemand[level]}`}];
 const urbanProblems:base.UrbanProblem[]=[{id:`${level}-problem`,title:t('Mucho ruido / A lot of noise'),detail:t('Hay música de noche. La gente quiere dormir. / There is music at night. People want to sleep.'),options:[{label:t('Música baja / Quiet music'),consequence:t('La fiesta sigue. / The party continues.')},{label:t('Cerrar el bar / Close the bar'),consequence:t('No hay fiesta. / There is no party.')},{label:t('Otro lugar / Another place'),consequence:t('Está lejos. / It is far away.')}]},{id:`${level}-problem-2`,title:t('Sin autobús / No bus'),detail:t('La escuela está lejos. / The school is far away.'),options:[{label:t('Un autobús / A bus'),consequence:t('Cuesta dinero. / It costs money.')},{label:t('Bicicletas / Bicycles'),consequence:t('Hoy llueve. / It rains today.')},{label:t('Caminar / Walk'),consequence:t('Necesitas tiempo. / You need time.')}]}];
 const negotiationRounds:base.NegotiationRound[]=[{id:`${level}-negotiate`,sideA:{name:'ANA',wants:t('Quiero música. / I want music.')},sideB:{name:'LUIS',wants:t('Quiero dormir. / I want to sleep.')},shared:level==='A0'?'Música baja, por favor. / Quiet music, please.':`Acuerda un horario. ${gameDemand[level]}`,pressure:t('Mañana Luis trabaja. / Luis works tomorrow.')}];
 const changeRounds:base.ChangeRound[]=[{id:`${level}-change`,decision:t('Quieres un parque. / You want a park.'),change:t('No hay agua. / There is no water.'),question:level==='A0'?'¿Agua o parque? Quiero agua. / Water or park? I want water.':`¿Qué haces primero? ${gameDemand[level]}`},{id:`${level}-change-2`,decision:t('Quieres una fiesta. / You want a party.'),change:t('Llueve. / It is raining.'),question:level==='A0'?'¿Dentro o fuera? Dentro. / Inside or outside? Inside.':`¿Cómo cambias el plan? ${gameDemand[level]}`}];
 const cityEvents:base.CityEvent[]=[{id:`${level}-rain`,title:t('Lluvia / Rain'),detail:t('Llueve mucho. La plaza está vacía. / It rains a lot. The square is empty.'),question:level==='A0'?'¿Qué necesitas? Necesito un autobús. / What do you need? I need a bus.':`¿Cómo ayudas a la gente? ${gameDemand[level]}`,cues:['Necesito un autobús. / I need a bus.','Voy a casa. / I go home.','Necesito un paraguas. / I need an umbrella.'].map(t) as [string,string,string]}];
 return {...base,cityChoices,priorityRounds,urbanProblems,negotiationRounds,changeRounds,cityEvents,bossPrompts:scenarios.map(s=>[s[0],level==='A0'?`${s[1]} ${s[2]} o ${s[3]}. / Choose one and say Quiero (I want).`:`${t(s[1])} ${gameDemand[level]}`] as [string,string]),finalQuestions:scenarios.map(s=>level==='A0'?`¿${s[2]} o ${s[3]}? / Choose and speak. Quiero… / I want…`:`Para tu ciudad: ¿${t(s[2]).toLowerCase()} o ${t(s[3]).toLowerCase()}? ${gameDemand[level]}`)};
}
