// Noche abierta · calle · escenas fuertes (caos-sur): robos, heridos, persecuciones y caos que la ciudad reparte por sus barrios.
//
// Estación (un carterista, una estampida), Barrio Sur (una pelea de pareja que
// se descontrola, alguien escondido de sus vecinos) y Los Galpones (un asalto en
// marcha, un trato turbio que resulta inocente). Cada escena tiene su camino base
// y un camino propio para cada objeto: el objeto cambia la primera reacción, las
// opciones, los finales y la pregunta de cierre.

const tx = (A, B, C) => ({ A, B, C });
const go = (id, mood, next, say, reply) => ({ id, say, reply, mood, next });
const fin = (id, mood, end, say, reply) => ({ id, say, reply, mood, end });
const node = (who, mood, line, options) => ({ who, mood, line, options });
const end = (change, recap, text) => ({ text, change, recap });

const encounters = [
  // ------------------------------------------------------------ Estación
  {
    id: "estacion-carterista",
    kind: "escena",
    district: "estacion",
    title: "El bolso de Lidia",
    verb: "DETENER",
    goal: "Reaccionar ante un robo, describir a una persona, dar órdenes, acusar, pedir ayuda y decidir si perseguir o llamar a la policía.",
    cast: [
      {
        id: "lidia", name: "Lidia", role: "Viajera a la que acaban de robar",
        age: "adult", body: "f", build: "average", height: 1.66,
        hair: "bob", hairColor: "#3a2416", skin: "#d9ad8a",
        top: "coat", topColor: "#7a2e3a", bottom: "pants", bottomColor: "#2b2b33",
        extras: ["earrings", "phone"], pose: "scream", props: ["suitcase"],
      },
      {
        id: "rulo", name: "Rulo", role: "Carterista con el bolso en la mano",
        age: "young", body: "m", build: "slim", height: 1.74,
        hair: "cap", hairColor: "#1c1c1c", skin: "#b07a56",
        top: "hoodie", topColor: "#2f2f2f", bottom: "jeans", bottomColor: "#1f2a3a",
        extras: [], pose: "bag-run", props: ["handbag"],
      },
    ],
    start: "inicio",
    nodes: {
      inicio: node("lidia", "scared", tx(
        "Una mujer grita en la plaza. «¡Mi bolso! ¡Ese chico tiene mi bolso!» Un joven con capucha corre hacia ti.",
        "Una mujer grita en medio de la plaza: «¡Mi bolso! ¡Me lo acaba de robar!». El chico de la capucha corre directo hacia ti con el bolso bajo el brazo.",
        "Un grito parte la plaza en dos: «¡Mi bolso! ¡Ese de la capucha!». El chico viene corriendo hacia ti, con el bolso apretado contra el pecho y cara de no tener plan.",
      ), [
        go("cortar", "angry", "acorralado",
          tx("¡Eh! ¡Para! ¡Dame ese bolso!", "¡Eh, tú! ¡Quieto! Ese bolso no es tuyo.", "¡Alto ahí! Ese bolso tiene dueña y no eres tú."),
          tx("El chico frena. Está entre tú y una pared. Respira rápido.", "El chico frena en seco: tú delante, la pared detrás. Jadea y mira a los lados.", "El chico frena en seco. Entre tú y el muro de la estación no le queda ni un metro de plaza, y lo sabe.")),
        go("describir", "worried", "testigo",
          tx("¡Señora! Es un chico con capucha negra. Va hacia el túnel.", "¡Señora, mire! Capucha negra, gorra, jeans. Se va hacia el túnel.", "¡Señora! Capucha negra, gorra, jeans oscuros; corre hacia el túnel de la estación. ¿Llamo a la policía?"),
          tx("Lidia corre hacia ti. «¡Sí, ese! ¡Llama a la policía, por favor!»", "Lidia llega corriendo, sin aliento. «¡Ese, ese! Mi pasaporte está ahí dentro. ¡Llama a la policía!»", "Lidia llega sin aliento. «¡Ese! Llevo el pasaporte y el boleto del tren en ese bolso. Si se pierde, me quedo en esta ciudad para siempre.»")),
        go("gritar", "scared", "acorralado",
          tx("¡Policía! ¡Ladrón! ¡Aquí!", "¡Policía! ¡Un ladrón! ¡Que alguien lo pare!", "¡Al ladrón! ¡Policía! ¡Que nadie lo deje pasar!"),
          tx("La gente mira. El chico se asusta y se para delante de ti.", "Varias personas se giran. El chico se asusta, duda y se queda clavado delante de ti.", "Media plaza se gira hacia él. El chico, de pronto famoso, se queda clavado a dos metros de ti.")),
      ]),
      acorralado: node("rulo", "angry", tx(
        "El chico aprieta el bolso. «No te metas. No es tu problema.»",
        "El chico aprieta el bolso contra el pecho. «No te metas, ¿sí? Esto no va contigo.»",
        "El chico aprieta el bolso como si fuera un salvavidas. «No te metas. Esto no va contigo, y no quieres que vaya.»"),
      [
        fin("ordenar", "angry", "bolso",
          tx("Suelta el bolso. Ahora.", "Suelta el bolso ahora mismo y vete.", "Suelta el bolso ahora, antes de que esto tenga público y consecuencias."),
          tx("El chico tira el bolso al suelo y corre.", "El chico duda un segundo, tira el bolso al suelo y sale corriendo hacia el túnel.", "El chico calcula, pierde, tira el bolso al suelo y desaparece por el túnel.")),
        fin("agarrar", "furious", "golpe",
          tx("¡Dame eso!", "¡Dame eso ahora!", "Se acabó. Dame eso."),
          tx("Intentas agarrar el bolso. El chico te empuja y te caes.", "Agarras el bolso. El chico te da un empujón fuerte y caes al suelo.", "Tiras del bolso. El chico te empuja con todo el cuerpo y acabas en el suelo, con las manos raspadas.")),
        go("hablar", "worried", "testigo",
          tx("Tranquilo. Deja el bolso y vete. No pasa nada.", "Tranquilo, nadie quiere problemas. Deja el bolso en el suelo y vete.", "Nadie quiere problemas aquí. Deja el bolso en el suelo, date la vuelta y esta noche sigue siendo tuya."),
          tx("El chico deja el bolso y corre. Lidia llega corriendo.", "El chico suelta el bolso y se va corriendo. Lidia llega hasta ti temblando.", "El chico suelta el bolso, murmura algo y se esfuma. Lidia llega a tu lado temblando de arriba abajo.")),
      ]),
      testigo: node("lidia", "worried", tx(
        "Lidia tiene el celular en la mano. «¿Qué hago? ¿Llamo a la policía o corro?»",
        "Lidia tiene el celular en la mano y le tiemblan los dedos. «¿Qué hago? ¿Llamo a la policía o corro detrás de él?»",
        "Lidia sostiene el celular con los dedos temblando. «Dime qué hago. ¿Llamo a la policía, corro detrás, o me siento aquí a llorar?»"),
      [
        fin("llamar", "worried", "policia",
          tx("Llame a la policía. Yo lo vi bien.", "Llame a la policía ahora. Yo lo vi bien y puedo describirlo.", "Llame a la policía ahora mismo. Lo vi de cerca y puedo describirlo con detalle."),
          tx("Lidia llama. «Ya vienen. Quédate conmigo, por favor.»", "Lidia marca el número. «Ya vienen. Quédate conmigo hasta que lleguen, por favor.»", "Lidia marca con dedos torpes. «Ya vienen. No te vayas, por favor; tú eres la única persona que lo vio.»")),
        fin("correr", "scared", "huido",
          tx("Vamos. Corremos juntos.", "Vamos, corremos juntos. ¡Por el túnel!", "Vamos juntos. Por el túnel, rápido, antes de que llegue al andén."),
          tx("Corren hasta el túnel. Ya no está.", "Corren hasta el túnel, pero ya no está. Solo queda el eco de sus pasos.", "Llegan al túnel con el corazón en la garganta. Nada: solo el eco de unos pasos que ya no son suyos.")),
        fin("sentar", "sad", "consuelo",
          tx("Siéntese. Respire. ¿Qué había en el bolso?", "Siéntese un momento y respire. ¿Qué llevaba en el bolso?", "Siéntese y respire conmigo un momento. Luego me cuenta qué llevaba en ese bolso."),
          tx("Lidia se sienta. «Mi pasaporte. Y la foto de mi hija.»", "Lidia se sienta en el banco. «El pasaporte. Y una foto de mi hija que no tengo en ningún otro sitio.»", "Lidia se deja caer en el banco. «El pasaporte, el boleto… y una foto de mi hija de la que no existe copia.»")),
      ]),
      // Cuchillo: Rulo saca el suyo y se miden sin tocarse.
      "cuchillo-inicio": node("rulo", "furious", tx(
        "El chico ve tu cuchillo. Saca el suyo. «¿Quieres pelear? Ven.»",
        "El chico ve el cuchillo en tu mano y saca uno de la sudadera. «¿Así? Bien. Ven, a ver si te atreves.»",
        "El chico ve tu cuchillo y, sin dejar de correr, saca el suyo de la sudadera. «¿Vamos a hacer esto? Bien. Ven.»"),
      [
        go("bajar", "worried", "cuchillo-duelo",
          tx("Yo bajo el mío si tú bajas el tuyo.", "Yo bajo el mío si tú bajas el tuyo. Nadie quiere sangre aquí.", "Bajo el mío si bajas el tuyo. Ninguno de los dos quiere terminar la noche en el hospital."),
          tx("Los dos bajan los cuchillos despacio. Lidia grita detrás de ti.", "Los dos bajan los cuchillos muy despacio, sin dejar de mirarse. Detrás de ti, Lidia grita que llamen a la policía.", "Bajan los cuchillos a la vez, milímetro a milímetro, como en un espejo. Detrás, Lidia pide a gritos que alguien llame a la policía.")),
        go("firme", "angry", "cuchillo-duelo",
          tx("Suelta el bolso o esto termina mal.", "Suelta el bolso ahora o esto termina muy mal para los dos.", "Suelta el bolso ahora. Si esto sigue, termina mal para los dos, y tú tienes más que perder."),
          tx("Se miran. Nadie se mueve. El chico tira el bolso a un lado.", "Se miran un segundo eterno. Ninguno ataca. Al final, el chico tira el bolso a un lado sin bajar el cuchillo.", "Un segundo que dura un año. Nadie ataca. Al final el chico tira el bolso a un lado, sin bajar la punta ni los ojos.")),
        fin("atacar", "terror", "cuchillo-herida",
          tx("¡Dame el bolso!", "¡Dame ese bolso!", "¡El bolso, ahora!"),
          tx("Te lanzas. El cuchillo del chico te corta el brazo. Sangre. Él corre.", "Te lanzas sobre él. Su cuchillo te roza el brazo y la manga se llena de sangre. El chico huye con el bolso.", "Te lanzas. La hoja del chico te abre el antebrazo, la manga se empapa, y él se pierde con el bolso por el túnel.")),
      ]),
      "cuchillo-duelo": node("lidia", "terror", tx(
        "Lidia está pálida. «¡Dos cuchillos! ¡Ya viene la policía!»",
        "Lidia está pálida como la pared. «¡Dos cuchillos en mi plaza! Ya llamé a la policía, ya vienen.»", 
        "Lidia está lívida. «Dos cuchillos. Dos. Yo solo quería tomar un tren. Ya viene la policía, los dos van a tener que explicarlo.»"),
      [
        fin("guardar", "worried", "cuchillo-policia",
          tx("Guardo el cuchillo. Explico todo a la policía.", "Guardo el cuchillo y espero. Se lo explico todo a la policía.", "Guardo el cuchillo y me quedo. Lo explico todo a la policía, aunque suene mal."),
          tx("Guardas el cuchillo. El chico escapa. Llega una patrulla.", "Guardas el cuchillo. El chico aprovecha y escapa. La patrulla frena a tu lado.", "Guardas el cuchillo; el chico aprovecha la pausa y se va. La patrulla frena a tu lado con las luces girando.")),
        fin("irse", "scared", "cuchillo-huida",
          tx("Lo siento. Me voy antes de que llegue la policía.", "Perdón, Lidia. No puedo explicar esto. Me voy antes de que llegue la policía.", "Lo siento, Lidia. No sabría explicar lo que acaba de pasar. Me voy antes de que llegue la patrulla."),
          tx("Recoges el bolso, se lo das y corres.", "Recoges el bolso del suelo, se lo das y corres hacia la avenida.", "Recoges el bolso del suelo, se lo pones en las manos y desapareces por la avenida sin mirar atrás.")),
        fin("calmar", "worried", "cuchillo-policia",
          tx("Tranquila. Nadie está herido. Lo saqué para defenderla.", "Tranquila, nadie está herido. Lo saqué para defenderla, nada más.", "Tranquila, no hay heridos. Lo saqué para protegerla; sé que fue una locura, pero funcionó."),
          tx("Lidia respira. «Gracias… creo. Dilo así a la policía.»", "Lidia respira hondo. «Gracias… creo. Díselo exactamente así a la policía.»", "Lidia respira por fin. «Gracias, creo. Cuéntaselo a la policía con esas mismas palabras, y reza.»")),
      ]),
      // Pistola: Rulo frena, levanta las manos y el bolso.
      "pistola-inicio": node("rulo", "terror", tx(
        "El chico ve tu pistola. Frena y levanta las manos. «¡No! ¡Toma el bolso! ¡No dispares!»",
        "El chico ve la pistola, frena en seco y levanta las manos con el bolso colgando. «¡No, no! ¡Toma el bolso! ¡No dispares, por favor!»",
        "El chico ve la pistola y frena tan en seco que casi se cae. Manos arriba, bolso colgando de una. «¡No! ¡Todo tuyo! ¡No dispares!»"),
      [
        go("suelo", "angry", "pistola-lidia",
          tx("Deja el bolso en el suelo. Despacio.", "Deja el bolso en el suelo, despacio, y da dos pasos atrás.", "Deja el bolso en el suelo, despacio, y retrocede dos pasos. Sin trucos."),
          tx("El chico deja el bolso. Lidia llega. Mira la pistola y se para.", "El chico deja el bolso y retrocede. Lidia llega corriendo, ve la pistola y se queda helada.", "El chico obedece paso a paso. Lidia llega corriendo, ve la pistola y se frena como si hubiera chocado con un cristal.")),
        fin("corre", "scared", "pistola-huye",
          tx("Vete. Corre. No quiero verte más.", "Suelta el bolso y corre. No quiero verte más por aquí.", "Suelta el bolso y corre. Si te vuelvo a ver por esta plaza, no hablamos."),
          tx("El chico suelta el bolso y corre. Lidia te mira con miedo.", "El chico suelta el bolso y huye sin mirar atrás. Lidia te mira con más miedo que a él.", "El chico suelta el bolso y huye. Lidia te mira como si el ladrón fueras tú.")),
        go("guardar", "worried", "pistola-lidia",
          tx("Guardo la pistola. Devuelve el bolso y hablamos.", "Guardo la pistola, ¿de acuerdo? Devuelve el bolso y hablamos como personas.", "Guardo la pistola. Devuelve el bolso y hablamos como dos personas, no como en una película mala."),
          tx("Guardas la pistola. El chico deja el bolso. Lidia llega, temblando.", "Guardas la pistola. El chico deja el bolso en el suelo y Lidia llega temblando.", "Guardas la pistola. El chico deja el bolso y Lidia llega temblando, sin saber a cuál de los dos mirar.")),
      ]),
      "pistola-lidia": node("lidia", "scared", tx(
        "Lidia recoge su bolso. «Gracias… pero ¿por qué llevas una pistola?»",
        "Lidia recoge el bolso sin quitarte los ojos. «Gracias… pero ¿por qué llevas una pistola? ¿Quién eres?»",
        "Lidia recoge el bolso sin quitarte los ojos de encima. «Gracias, supongo. Ahora dime por qué llevas una pistola en una plaza.»"),
      [
        fin("verdad", "worried", "pistola-patrulla",
          tx("Por miedo. La noche es peligrosa.", "Por miedo, la verdad. Esta ciudad de noche da miedo.", "Por miedo, sinceramente. Esta ciudad de noche me asusta más de lo que quiero admitir."),
          tx("Una patrulla frena. Un agente te pide la pistola.", "Una patrulla frena a tu lado. Un agente baja y te pide la pistola con calma.", "Una patrulla frena a tu lado. Un agente baja, te pide la pistola con calma y Lidia explica que la salvaste.")),
        fin("mentir", "angry", "pistola-patrulla",
          tx("No es de verdad. Es de juguete.", "No es de verdad, es de juguete. Pero funcionó.", "No es de verdad, es de utilería. Pero reconoce que funcionó."),
          tx("Lidia no te cree. Llega la policía. Explicas.", "Lidia no te cree. La policía llega y tienes que explicarlo todo.", "Lidia no te cree ni media palabra. La policía llega y la explicación dura más que el robo.")),
        fin("irse", "sad", "pistola-huye",
          tx("Mejor me voy. Cuide su bolso.", "Mejor me voy. Cuide su bolso y buen viaje.", "Mejor me voy antes de que esto se complique. Cuide ese bolso y buen viaje."),
          tx("Te vas rápido. Lidia se queda mirando.", "Te alejas rápido. Lidia se queda mirándote con el bolso contra el pecho.", "Te alejas a paso rápido. Lidia se queda abrazada al bolso, sin saber si darte las gracias o denunciarte.")),
      ]),
      // Granada: la plaza entera se vacía.
      "granada-inicio": node("rulo", "terror", tx(
        "Levantas la granada. El chico grita. «¡Una bomba!» La plaza corre.",
        "Levantas la granada y el chico grita: «¡Tiene una bomba!». En dos segundos, toda la plaza corre.",
        "Levantas la granada. El chico grita «¡bomba!» con tanta convicción que la plaza entera se vacía en segundos."),
      [
        go("bolso", "angry", "granada-plaza",
          tx("¡El bolso! ¡Déjalo o la tiro!", "¡Deja el bolso o la tiro!", "¡El bolso al suelo o esto vuela!"),
          tx("El chico tira el bolso y corre. Suena una sirena.", "El chico tira el bolso y huye. A lo lejos, suena una sirena.", "El chico suelta el bolso y huye. A lo lejos, una sirena, luego dos.")),
        go("broma", "surprised", "granada-plaza",
          tx("¡Es de mentira! ¡Es un llavero!", "¡Es de mentira! ¡Es un llavero, nada más!", "¡Es un llavero! Una broma de mal gusto, lo reconozco, pero un llavero."),
          tx("Nadie te oye. Todos corren. El chico tira el bolso y huye.", "Nadie te escucha: todos corren. El chico suelta el bolso y huye con los demás.", "Nadie te oye: la plaza es un río de gente. El chico suelta el bolso y se va con la corriente.")),
        fin("huir", "scared", "granada-helicoptero",
          tx("Me voy. Esto es demasiado.", "Mejor me voy. Esto se me fue de las manos.", "Me voy. Esto se me escapó de las manos en tiempo récord."),
          tx("Corres. Un helicóptero vuela sobre la estación.", "Corres hacia la avenida. Un helicóptero aparece sobre la estación.", "Corres hacia la avenida mientras un helicóptero barre la estación con su foco.")),
      ]),
      "granada-plaza": node("lidia", "terror", tx(
        "Lidia recoge su bolso temblando. «¿Es de verdad? ¡Dime que no!»",
        "Lidia recoge el bolso temblando. «¿Es de verdad? ¡Dime que no, por favor!»",
        "Lidia recoge el bolso temblando de pies a cabeza. «Dime que no es de verdad. Dímelo aunque sea mentira.»"),
      [
        fin("guardar", "worried", "granada-helicoptero",
          tx("No lo sé. La guardo. Nos vamos.", "No lo sé, la verdad. La guardo y nos vamos.", "No lo sé, y prefiero no averiguarlo. La guardo y nos vamos."),
          tx("Un helicóptero llega. Policías con cascos corren.", "Un helicóptero ilumina la plaza. Policías con casco corren hacia ustedes.", "Un helicóptero clava su foco sobre la plaza. Policías con casco corren hacia ustedes y Lidia levanta las manos.")),
        fin("reir", "laugh", "granada-risa",
          tx("Es de plástico. Funcionó, ¿no?", "Es de plástico. Funcionó, ¿no? Tiene su bolso.", "Es de plástico. Pero reconozca que funcionó: tiene su bolso y el ladrón, un trauma."),
          tx("Lidia ríe y llora a la vez. «Estás loco. Gracias.»", "Lidia ríe y llora a la vez. «Estás completamente loco. Gracias.»", "Lidia ríe y llora al mismo tiempo. «Estás como una cabra. Gracias, de verdad.»")),
        fin("ordenar", "angry", "granada-helicoptero",
          tx("Corra. Vaya al túnel. Yo me quedo.", "Corra al túnel. Yo me quedo a explicar.", "Corra al túnel y no mire atrás. Yo me quedo a explicar lo inexplicable."),
          tx("Lidia corre. Un helicóptero vuela bajo. Levantas las manos.", "Lidia corre. Un helicóptero baja sobre la plaza y levantas las manos.", "Lidia corre. El helicóptero baja tanto que te despeina y levantas las manos antes de que te lo pidan.")),
      ]),
      // Gas pimienta: una nube y el bolso en el suelo.
      "gas-inicio": node("rulo", "pain", tx(
        "Le echas gas pimienta. El chico grita, tose y deja el bolso. «¡Mis ojos!»",
        "Le echas el gas pimienta en la cara. El chico grita, tose y suelta el bolso. «¡Mis ojos! ¡No veo nada!»",
        "Una nube de gas pimienta y el chico cae de rodillas, tosiendo y soltando el bolso. «¡Mis ojos! ¡Estás loco!»"),
      [
        go("bolso", "neutral", "gas-lidia",
          tx("Recojo el bolso. Quédate ahí.", "Recojo el bolso y tú te quedas ahí, en el suelo.", "Recojo el bolso. Tú te quedas en el suelo hasta que decida qué hacer contigo."),
          tx("Recoges el bolso. Lidia llega. «¿Qué le hiciste?»", "Recoges el bolso. Lidia llega corriendo. «¿Qué le hiciste? ¡Está llorando!»", "Recoges el bolso. Lidia llega corriendo y mira al chico. «¿Qué le hiciste? Parece que llora de verdad.»")),
        fin("agua", "worried", "gas-ambulancia",
          tx("Tranquilo. Necesitas agua. Llamo a una ambulancia.", "Tranquilo, no te frotes los ojos. Llamo a una ambulancia.", "No te frotes los ojos. Necesitas agua y aire. Llamo a una ambulancia, aunque no te lo mereces."),
          tx("El chico tose. Llega la ambulancia y la policía.", "El chico tose sin parar. La ambulancia llega con la policía detrás.", "El chico tose como si le faltara el mundo. La ambulancia llega, y la policía justo detrás.")),
        go("irse", "scared", "gas-lidia",
          tx("Toma, señora. Su bolso. Yo me voy.", "Tome, señora, su bolso. Yo mejor me voy.", "Tenga, su bolso. Yo me retiro antes de que alguien pregunte quién trajo el gas."),
          tx("Lidia agarra el bolso. «Espera. ¿Y él?»", "Lidia agarra el bolso. «Espera, ¿y él? No podemos dejarlo así.»", "Lidia agarra el bolso y mira al chico. «Espera. ¿Y él? No podemos dejarlo ciego en una plaza.»")),
      ]),
      "gas-lidia": node("lidia", "worried", tx(
        "Lidia mira al chico en el suelo. «Gracias. Pero mira cómo está.»",
        "Lidia mira al chico, que tose en el suelo. «Gracias, de verdad. Pero mira cómo lo dejaste.»",
        "Lidia mira al chico, que tose en el suelo con los ojos cerrados. «Gracias. Pero míralo: ahora el que da pena es él.»"),
      [
        fin("policia", "neutral", "gas-bolso",
          tx("Llamamos a la policía. Él no se mueve de aquí.", "Llamamos a la policía. Así no va a ir a ningún sitio.", "Llamamos a la policía. Con esos ojos no llega ni a la esquina."),
          tx("La policía llega. El chico, con los ojos rojos, no dice nada.", "La policía llega en cinco minutos. El chico, con los ojos rojos, ni intenta correr.", "La policía llega en cinco minutos. El chico, con los ojos rojos y el orgullo roto, no intenta nada.")),
        fin("perdonar", "sad", "gas-ambulancia",
          tx("Lo siento. Llamo a una ambulancia para él.", "Me pasé. Llamo a una ambulancia para él.", "Me pasé de la raya. Llamo a una ambulancia; el bolso ya está donde debe."),
          tx("Lidia asiente. La ambulancia se lleva al chico.", "Lidia asiente despacio. La ambulancia se lleva al chico con los ojos vendados.", "Lidia asiente. La ambulancia se lleva al chico con una gasa húmeda en los ojos y tu nombre en el informe.")),
        fin("defender", "angry", "gas-bolso",
          tx("Él la robó. Yo la defendí. Punto.", "Él la robó y yo la defendí. No me arrepiento.", "Él la robó y yo la defendí. No pienso disculparme por un bote de gas."),
          tx("Lidia te abraza el bolso. «Tienes razón. Vámonos.»", "Lidia aprieta el bolso contra el pecho. «Tienes razón. Vámonos de aquí.»", "Lidia abraza el bolso. «Tienes razón. Vámonos antes de que me dé lástima.»")),
      ]),
      // Lápiz: apuntas, dibujas, denuncias.
      "lapiz-inicio": node("lidia", "scared", tx(
        "Sacas el lápiz y apuntas. Lidia llega. «¿Qué escribes? ¡Se escapa!»",
        "Sacas el lápiz y empiezas a apuntar. Lidia llega sin aliento. «¿Qué escribes? ¡Se está escapando!»",
        "Sacas el lápiz y empiezas a apuntar en la mano. Lidia llega sin aliento. «¿Estás tomando notas? ¡Se escapa!»"),
      [
        go("datos", "neutral", "lapiz-retrato",
          tx("Capucha negra, gorra, jeans. Túnel. Hora: doce y diez.", "Capucha negra, gorra, jeans oscuros, va al túnel. Doce y diez. Todo apuntado.", "Capucha negra, gorra, jeans oscuros, dirección túnel, doce y diez. Con esto la policía tiene algo que buscar."),
          tx("Lidia te mira. «Eres muy raro. Pero gracias.»", "Lidia te mira con la boca abierta. «Eres la persona más rara de esta plaza. Pero gracias.»", "Lidia te mira sin saber si reírse. «Eres rarísimo. Pero es la primera cosa útil que pasa esta noche.»")),
        go("dibujar", "smile", "lapiz-retrato",
          tx("Le dibujo la cara. La vi bien.", "Le dibujo la cara, la vi bien. Un retrato para la policía.", "Le vi la cara de cerca. Le hago un retrato para la policía antes de que se me borre."),
          tx("Dibujas rápido. Lidia mira. «¡Es él! ¡Es igual!»", "Dibujas rápido, con trazos nerviosos. Lidia mira. «¡Es él! ¡Es clavado!»", "Dibujas con trazos rápidos. Lidia mira por encima de tu hombro. «Es él. Hasta la cara de culpable.»")),
        fin("nota", "neutral", "lapiz-denuncia",
          tx("Escribo todo en un papel. Lleve esto a la policía.", "Escribo todo en un papel. Llévelo a la policía ahora mismo.", "Lo escribo todo en un papel, con hora y detalles. Llévelo a la comisaría ahora mismo."),
          tx("Lidia toma el papel. «Voy. Gracias.» Corre hacia la comisaría.", "Lidia toma el papel y lo aprieta. «Voy ahora. Gracias.» Corre hacia la comisaría.", "Lidia toma el papel como si fuera un pasaporte nuevo. «Voy ahora mismo. Gracias.» Sale hacia la comisaría.")),
      ]),
      "lapiz-retrato": node("lidia", "worried", tx(
        "Lidia mira tu papel. «¿Y ahora? ¿Esto sirve para algo?»",
        "Lidia mira tu papel con los ojos húmedos. «¿Y ahora qué? ¿Esto sirve de algo?»",
        "Lidia mira tu papel con los ojos húmedos. «¿Y ahora? ¿De verdad crees que con esto lo encuentran?»"),
      [
        fin("comisaria", "neutral", "lapiz-denuncia",
          tx("Sí. Vamos a la comisaría con esto.", "Sí. Vamos ahora a la comisaría con esto.", "Sí. Vamos ahora mismo a la comisaría; con un retrato, al menos lo buscan."),
          tx("Van juntos a la comisaría. El agente guarda el dibujo.", "Van juntos a la comisaría. El agente mira el dibujo y lo guarda con la denuncia.", "Van juntos a la comisaría. El agente mira el dibujo, levanta una ceja y lo grapa a la denuncia.")),
        fin("regalo", "smile", "lapiz-dibujo",
          tx("Toma el dibujo. Para la policía. Y este otro, para usted.", "Tome el dibujo, para la policía. Y este otro, para usted: su hija, como me la describió.", "Tome el retrato para la policía. Y este otro, para usted: su hija, dibujada tal como me la describió."),
          tx("Lidia mira el segundo dibujo y llora. «Es ella.»", "Lidia mira el segundo dibujo y se le escapan las lágrimas. «Es ella. Es ella.»", "Lidia mira el segundo dibujo y rompe a llorar. «Es ella. No sé cómo lo hiciste, pero es ella.»")),
        fin("buscar", "worried", "lapiz-denuncia",
          tx("Sirve. Lo enseño a la gente del andén.", "Sirve. Enseño el dibujo a la gente del andén, alguien lo vio.", "Sirve. Enseño el retrato en el andén; alguien lo habrá visto subir a un tren."),
          tx("Enseñas el dibujo. Un hombre señala el tren. Lidia llama a la policía.", "Enseñas el dibujo en el andén. Un hombre señala un tren. Lidia llama a la policía con el dato.", "Enseñas el retrato en el andén. Un hombre señala un tren, y Lidia llama a la policía con el dato en la mano.")),
      ]),
      // Libro: una zancadilla literaria.
      "libro-inicio": node("rulo", "pain", tx(
        "Lanzas el libro a sus pies. El chico tropieza y cae. «¡Ay! ¿Un libro?»",
        "Lanzas el libro a sus pies. El chico tropieza, cae de boca y el bolso vuela. «¿Un libro? ¿En serio?»",
        "Lanzas el libro justo delante de sus pies. El chico tropieza, aterriza de boca y el bolso sale volando. «¿Un libro? ¿Me tiraste un libro?»"),
      [
        go("bolso", "smile", "libro-lidia",
          tx("Sí, un libro. Ahora dame el bolso.", "Sí, un libro. Pesa más que tu excusa. Dame el bolso.", "Un libro. Setecientas páginas de literatura rusa. Ahora dame el bolso."),
          tx("Agarras el bolso. El chico se levanta y corre. Lidia llega riendo.", "Agarras el bolso mientras el chico se levanta cojeando y corre. Lidia llega riéndose de nervios.", "Agarras el bolso. El chico se levanta cojeando y huye. Lidia llega riendo de puros nervios.")),
        go("leer", "laugh", "libro-lidia",
          tx("Es un buen libro. ¿Lo quieres? Cambio: el bolso.", "Es muy bueno, por cierto. ¿Lo quieres? Te lo cambio por el bolso.", "Es buenísimo, por cierto. Te lo regalo a cambio del bolso. Trato literario."),
          tx("El chico te mira. Deja el bolso. Agarra el libro y corre.", "El chico te mira como si estuvieras loco. Deja el bolso, agarra el libro y se va corriendo.", "El chico te mira, incrédulo. Deja el bolso, se lleva el libro y huye con la primera novela de su vida.")),
        fin("golpe", "angry", "libro-roto",
          tx("¡Dame eso!", "¡Dame el bolso ahora!", "¡El bolso, ya!"),
          tx("Agarras el bolso. El chico te da una patada en la pierna y huye. Tu libro queda roto.", "Agarras el bolso, pero el chico te da una patada en la rodilla y huye. Tu libro queda abierto y pisado en el suelo.", "Agarras el bolso. El chico te suelta una patada en la rodilla y huye; tu libro se queda en el suelo, pisado y con el lomo roto.")),
      ]),
      "libro-lidia": node("lidia", "laugh", tx(
        "Lidia abraza su bolso. «¿Con un libro? ¿Lo paraste con un libro?»",
        "Lidia abraza su bolso y se ríe. «¿Lo paraste con un libro? ¿Qué libro es?»",
        "Lidia abraza el bolso y se ríe sin poder parar. «¿Lo paraste con un libro? ¿Qué clase de libro derriba a un ladrón?»"),
      [
        fin("titulo", "smile", "libro-bolso",
          tx("Uno muy largo. Pesa mucho.", "Uno muy largo. Pesa más que una piedra.", "Uno muy largo. Pesa como una piedra y es igual de útil a esta hora."),
          tx("Lidia se ríe. «Mañana compro uno igual.»", "Lidia se ríe a carcajadas. «Mañana me compro uno igual, por seguridad.»", "Lidia ríe a carcajadas. «Mañana me compro uno igual. Por seguridad y por cultura.»")),
        fin("regalar", "love", "libro-bolso",
          tx("Tome. Se lo regalo. Para el tren.", "Tome, se lo regalo. Para leer en el tren.", "Tenga, se lo regalo. Para el tren, y para que lo use si vuelve a pasar."),
          tx("Lidia toma el libro. «Gracias. Nunca olvido esta noche.»", "Lidia toma el libro con las dos manos. «Gracias. Nunca voy a olvidar esta noche.»", "Lidia toma el libro con las dos manos. «Gracias. Esta noche me la llevo entera en este libro.»")),
        fin("policia", "neutral", "libro-roto",
          tx("Ahora llame a la policía. Yo busco mi libro.", "Ahora llame a la policía. Yo voy a buscar mi libro.", "Ahora llame a la policía. Yo voy a recoger lo que queda de mi libro."),
          tx("Lidia llama. Recoges tu libro: está roto y sucio.", "Lidia llama a la policía. Recoges tu libro: roto, sucio y pisado.", "Lidia llama a la policía. Recoges tu libro del suelo: roto, mojado y con una huella en la portada.")),
      ]),
      // Corazón: Lidia se calma, Rulo se quiebra.
      "corazon-inicio": node("lidia", "love", tx(
        "Usas el corazón. Lidia deja de gritar. Respira. «Gracias… ya estoy mejor.»",
        "Usas el corazón. Lidia deja de gritar y respira hondo. «Gracias… no sé qué hiciste, pero ya estoy mejor.»",
        "Usas el corazón. El grito de Lidia se apaga como una vela. «No sé qué acabas de hacer, pero puedo respirar.»"),
      [
        go("chico", "neutral", "corazon-rulo",
          tx("Espere aquí. Voy a hablar con el chico.", "Espere aquí. Voy a hablar con el chico, sin gritos.", "Espere aquí. Voy a hablar con el chico; a veces hablar funciona mejor que correr."),
          tx("El chico se detiene. Te mira. No corre.", "El chico, curiosamente, se detiene y te mira. No corre.", "El chico se detiene, cosa rara en un ladrón. Te mira y no corre.")),
        go("abrazo", "love", "corazon-rulo",
          tx("Venga. Un abrazo. Luego buscamos el bolso.", "Venga, un abrazo. Luego buscamos ese bolso juntos.", "Venga aquí. Un abrazo primero; el bolso después, y juntos."),
          tx("Lidia te abraza. El chico mira desde lejos, sin moverse.", "Lidia te abraza llorando. El chico mira desde lejos, inmóvil, con el bolso en la mano.", "Lidia te abraza y llora. El chico mira desde lejos, inmóvil, como si el abrazo también fuera para él.")),
        fin("sentar", "love", "corazon-hambre",
          tx("Siéntese. Hablamos. Nada es más importante que usted.", "Siéntese conmigo. Nada de ese bolso es más importante que usted.", "Siéntese conmigo. Nada de lo que lleva en ese bolso vale más que usted ahora mismo."),
          tx("Lidia se sienta. El chico vuelve y deja el bolso en el banco.", "Lidia se sienta. El chico vuelve despacio y deja el bolso en el banco, sin decir nada.", "Lidia se sienta. El chico vuelve despacio, deja el bolso en el banco y se queda de pie, con la gorra en la mano.")),
      ]),
      "corazon-rulo": node("rulo", "sad", tx(
        "El chico habla bajo. «Tengo hambre. No como desde ayer.»",
        "El chico habla sin levantar la vista. «Tengo hambre. No como nada desde ayer.»",
        "El chico habla sin levantar la vista, con la voz rota. «Tengo hambre. No pruebo bocado desde ayer, y nadie me mira.»"),
      [
        fin("comida", "love", "corazon-hambre",
          tx("Devuelve el bolso. Te compro algo de comer.", "Devuelve el bolso y te compro algo de comer ahora.", "Devuelve el bolso y te invito a comer ahora mismo. Sin policía, sin preguntas."),
          tx("El chico devuelve el bolso. Van juntos al quiosco.", "El chico devuelve el bolso y los tres van al quiosco de la estación.", "El chico devuelve el bolso y los tres caminan hasta el quiosco, en un silencio nuevo.")),
        fin("devolver", "love", "corazon-devuelve",
          tx("Dale el bolso a la señora. Pídele perdón.", "Devuélvele el bolso a la señora y pídele perdón.", "Devuélvele el bolso a la señora y pídele perdón mirándola a los ojos."),
          tx("El chico devuelve el bolso. «Perdón.» Lidia lo abraza.", "El chico devuelve el bolso y murmura «perdón». Lidia, para sorpresa de todos, lo abraza.", "El chico devuelve el bolso y dice «perdón» en voz baja. Lidia, contra todo pronóstico, lo abraza.")),
        fin("policia", "worried", "policia",
          tx("Lo siento. Pero llamo a la policía.", "Lo siento por ti, pero voy a llamar a la policía.", "Lo siento de verdad, pero esto se resuelve con la policía."),
          tx("El chico deja el bolso y espera. Llega la patrulla.", "El chico deja el bolso en el suelo y espera sin correr. Llega la patrulla.", "El chico deja el bolso y espera sin correr, como si estuviera cansado de correr. Llega la patrulla.")),
      ]),
    },
    ends: {
      bolso: end("corre", "Recuperaste el bolso de Lidia con una orden firme.", tx("Lidia recoge su bolso. «Gracias. Todo está aquí.» El chico ya no está.", "Lidia recoge el bolso y revisa: pasaporte, boleto, foto. «Está todo. Gracias.» El chico ya es un recuerdo.", "Lidia recoge el bolso y lo revisa con manos temblorosas: pasaporte, boleto, la foto. «Está todo.» Del chico solo queda el eco.")),
      golpe: end("cae", "Intentaste quitarle el bolso y terminaste en el suelo.", tx("Estás en el suelo. El chico huye con el bolso. Lidia te ayuda a levantarte.", "Te quedas en el suelo con las manos raspadas. El chico huye con el bolso y Lidia te ayuda a levantarte.", "Te quedas en el suelo, con las palmas en carne viva. El chico se lleva el bolso y Lidia, sin nada, te ayuda a levantarte.")),
      policia: end("policia", "Llamaste a la policía y describiste al carterista.", tx("Llega una patrulla. Describes al chico. Lidia te da las gracias.", "Llega una patrulla. Describes al chico con detalle y Lidia firma la denuncia.", "Llega una patrulla. Describes al chico con todo detalle y Lidia firma la denuncia con tu nombre como testigo.")),
      huido: end("huye", "Corriste tras el carterista y lo perdiste en el túnel.", tx("El chico se fue. Lidia llora en el túnel.", "El chico desapareció. Lidia llora apoyada en la pared del túnel.", "El chico se esfumó. Lidia llora contra la pared del túnel, con el boleto de un tren que ya no puede tomar.")),
      consuelo: end("se-sienta", "Te sentaste con Lidia después del robo.", tx("Lidia y tú se sientan en el banco. Ella respira mejor.", "Se quedan sentados en el banco. Poco a poco, Lidia respira mejor.", "Se quedan en el banco, sin prisa. Poco a poco, Lidia vuelve a respirar como una persona.")),
      "cuchillo-herida": end("ambulancia", "El carterista te cortó el brazo en el duelo de cuchillos.", tx("Sangras del brazo. Lidia llama a una ambulancia.", "Te sangra el brazo. Lidia llama a una ambulancia y te aprieta la herida con su bufanda.", "La sangre te baja por la muñeca. Lidia llama a una ambulancia y te aprieta la herida con su bufanda, pálida.")),
      "cuchillo-policia": end("policia", "Dos cuchillos en la plaza: la policía te pidió explicaciones.", tx("La policía te pide el cuchillo. Lidia explica todo.", "La policía te pide el cuchillo. Lidia explica que la defendiste.", "La policía te pide el cuchillo. Lidia explica que la defendiste, y el agente no sabe si creerla.")),
      "cuchillo-huida": end("huye", "Devolviste el bolso y huiste antes de que llegara la policía.", tx("Corres por la avenida. Detrás, luces azules.", "Corres por la avenida con luces azules a tu espalda.", "Corres por la avenida con las luces azules pintando los edificios detrás de ti.")),
      "pistola-patrulla": end("policia", "La pistola detuvo el robo y la policía se la llevó.", tx("La policía se lleva tu pistola. Lidia tiene su bolso.", "La policía se lleva tu pistola y tus datos. Lidia tiene su bolso.", "La policía se lleva tu pistola y tus datos. Lidia tiene su bolso, y tú, una noche larga por delante.")),
      "pistola-huye": end("manos-arriba", "El carterista huyó con las manos arriba al ver tu pistola.", tx("El chico huye. Lidia se aleja de ti con el bolso.", "El chico huye. Lidia se aleja de ti abrazando el bolso.", "El chico huye con las manos todavía arriba. Lidia se aleja abrazada a su bolso, sin darte las gracias.")),
      "granada-helicoptero": end("helicoptero", "La granada vació la plaza y trajo un helicóptero.", tx("El helicóptero gira sobre la estación. Policías gritan. Levantas las manos.", "El helicóptero da vueltas sobre la estación y los policías gritan órdenes. Levantas las manos.", "El helicóptero gira sobre la estación mientras los policías gritan órdenes. Levantas las manos y piensas en el tren que no vas a tomar.")),
      "granada-risa": end("sonrie", "Una granada de plástico salvó el bolso de Lidia.", tx("Lidia ríe con su bolso. La plaza vuelve poco a poco.", "Lidia ríe abrazada a su bolso. La plaza se llena poco a poco otra vez.", "Lidia ríe abrazada a su bolso mientras la plaza, con desconfianza, vuelve a llenarse.")),
      "gas-bolso": end("policia", "El gas pimienta detuvo al carterista hasta que llegó la policía.", tx("La policía se lleva al chico. Lidia tiene su bolso.", "La policía se lleva al chico con los ojos rojos. Lidia tiene su bolso.", "La policía se lleva al chico con los ojos rojos y la cara mojada. Lidia tiene su bolso y una historia.")),
      "gas-ambulancia": end("ambulancia", "Llamaste a una ambulancia para el carterista después del gas.", tx("La ambulancia se lleva al chico. Lidia tiene su bolso.", "La ambulancia se lleva al chico con los ojos vendados. Lidia tiene su bolso.", "La ambulancia se lleva al chico con los ojos vendados. Lidia tiene su bolso y tú, remordimientos.")),
      "lapiz-denuncia": end("llama", "Con tus notas y tu dibujo, Lidia presentó la denuncia.", tx("La policía tiene tu dibujo. Lidia espera noticias.", "La policía tiene tu dibujo y tus notas. Lidia espera noticias en la comisaría.", "La policía tiene tu retrato y tus notas con hora y lugar. Lidia espera noticias en la comisaría.")),
      "lapiz-dibujo": end("sonrie", "Dibujaste al ladrón y, de regalo, a la hija de Lidia.", tx("Lidia guarda el dibujo de su hija. Sonríe entre lágrimas.", "Lidia guarda el dibujo de su hija en el abrigo. Sonríe entre lágrimas.", "Lidia guarda el retrato de su hija en el bolsillo del abrigo, y sonríe entre lágrimas.")),
      "libro-bolso": end("sonrie", "Derribaste al carterista con un libro y Lidia recuperó su bolso.", tx("Lidia se va con su bolso, riendo todavía.", "Lidia se va con su bolso, todavía riéndose del libro.", "Lidia se va con su bolso, todavía riéndose de la novela que derribó a un ladrón.")),
      "libro-roto": end("se-va", "El carterista huyó con el bolso y dejó tu libro roto.", tx("Te duele la pierna. El libro está roto. El chico se fue.", "Te duele la rodilla. El libro está roto. El chico se fue con el bolso.", "Te duele la rodilla, el libro está destrozado y el chico se fue con el bolso. Una noche redonda.")),
      "corazon-devuelve": end("abraza", "El carterista devolvió el bolso y pidió perdón.", tx("Lidia abraza al chico. Tú miras. Nadie llama a la policía.", "Lidia abraza al chico y nadie llama a la policía. La plaza sigue su noche.", "Lidia abraza al chico y nadie llama a la policía. La plaza, que lo vio todo, sigue con su noche.")),
      "corazon-hambre": end("sonrie", "Invitaste a comer al carterista después de que devolviera el bolso.", tx("El chico come un sándwich en el quiosco. Lidia tiene su bolso.", "El chico come un sándwich en el quiosco. Lidia tiene su bolso y una historia rara.", "El chico devora un sándwich en el quiosco. Lidia tiene su bolso y una historia que nadie le va a creer.")),
    },
    speak: {
      A1: "¿Qué llevas en tu bolso o en tu cartera?",
      A2: "¿Te robaron algo alguna vez y qué hiciste?",
      B1: "¿Cómo reaccionas cuando ves un robo en la calle?",
      B2: "¿Qué harías si vieras a un ladrón correr con el bolso de alguien?",
      C1: "¿Dónde está el límite entre ayudar a una víctima y ponerse uno mismo en peligro?",
      C2: "¿Qué revela una plaza llena de gente que mira y no actúa?",
    },
    variants: {
      cuchillo: { start: "cuchillo-inicio", fx: "duelo-cuchillo", speak: tx("¿Tienes miedo de los cuchillos?", "¿Qué harías si alguien sacara un cuchillo delante de ti?", "¿En qué momento una defensa deja de ser legítima y se convierte en locura?") },
      pistola: { start: "pistola-inicio", fx: "manos-arriba", speak: tx("¿Hay pistolas en tu país?", "¿Qué haces si alguien te obliga a obedecer con un arma?", "¿Qué consecuencias tiene usar un arma, aunque sea para hacer el bien?") },
      granada: { start: "granada-inicio", fx: "evacuacion", speak: tx("¿Corres cuando hay pánico?", "¿Cuándo viste a mucha gente correr al mismo tiempo?", "¿Por qué el pánico se contagia tan rápido en una multitud?") },
      gas: { start: "gas-inicio", fx: "defensa", speak: tx("¿Llevas algo para defenderte?", "¿Qué llevas para defenderte y cuándo lo usarías?", "¿Es razonable salir de noche preparado para lo peor?") },
      lapiz: { start: "lapiz-inicio", fx: "curioso", speak: tx("¿Escribes notas en la mano?", "¿Qué detalles apuntas para no olvidar algo importante?", "¿Qué recuerda mejor, la memoria o un papel escrito con prisa?") },
      libro: { start: "libro-inicio", fx: "risa", speak: tx("¿Cuánto pesa tu libro favorito?", "¿Para qué cosa rara usaste un libro alguna vez?", "¿Qué libro regalarías a alguien que nunca ha leído?") },
      corazon: { start: "corazon-inicio", fx: "calma", speak: tx("¿Quién te calma cuando tienes miedo?", "¿Cómo consuelas a alguien que acaba de perder algo?", "¿Qué te hace sentir empatía por alguien que te hizo daño?") },
    },
  },
