export const a1Questions:string[][]=[
  ["¿Hablás solo?","¿Cantás cuando estás solo?","¿Bailás cuando nadie te mira?","¿Mirás mucho tu celular?","¿Dormís con música?","¿Comés algo raro?","¿Tenés un hábito raro?","¿Qué cosa rara hacés en casa?","¿Qué hábito de otra persona no te gusta?","¿Hacés algo diferente cuando estás nervioso?"],
  ["¿Qué te hace feliz?","¿Qué es importante para vos?","¿Preferís dinero o tiempo?","¿Te gusta tu vida ahora?","¿Qué querés cambiar en tu vida?","¿Qué te da tranquilidad?","¿Es importante tener amigos?","¿Es importante tener tiempo solo?","¿Preferís una vida tranquila o activa?","¿Qué querés hacer más?"],
  ["¿Qué te gusta en una persona?","¿Qué no te gusta en una pareja?","¿Es importante hablar todos los días?","¿Te gusta pasar mucho tiempo con tu pareja?","¿Necesitás tiempo solo?","¿Sos celoso?","¿Es fácil confiar en una persona?","¿Es fácil decir “te quiero”?","¿Preferís una persona tranquila o divertida?","¿Qué es importante en una relación?"],
  ["¿Sos tímido?","¿Sos tranquilo?","¿Te ponés nervioso fácilmente?","¿Pensás mucho?","¿Confiás rápido en la gente?","¿Te gusta conocer gente nueva?","¿Te importa la opinión de otras personas?","¿Qué hacés cuando estás nervioso?","¿Qué te ayuda cuando estás estresado?","¿Sos diferente con amigos y desconocidos?"],
  ["¿Cómo es la gente en tu país?","¿La gente es amable?","¿La gente es puntual?","¿La familia es importante?","¿La gente habla con desconocidos?","¿Qué costumbre te gusta?","¿Qué costumbre no te gusta?","¿Qué país tiene una cultura interesante?","¿Tu país es muy tradicional?","¿Qué cosa querés cambiar en tu país?"],
  ["¿Te gusta ahorrar?","¿Te gusta gastar dinero?","¿En qué gastás mucho dinero?","¿El dinero es importante para vos?","¿Preferís dinero o tiempo libre?","¿Querés ganar mucho dinero?","¿Qué cosa cara querés comprar?","¿Gastás dinero en viajes?","¿Preferís comprar cosas o viajar?","¿Un buen trabajo necesita un buen sueldo?"],
  ["¿Usás mucho el celular?","¿Qué aplicación usás más?","¿Usás Instagram?","¿Usás TikTok?","¿Preferís mensajes o llamadas?","¿Mirás el celular cuando comés?","¿Podés estar un día sin internet?","¿Usás inteligencia artificial?","¿Internet es bueno para vos?","¿Qué aplicación no necesitás?"],
  ["¿Mentís a veces?","¿Siempre decís la verdad?","¿Es difícil decir “no”?","¿Te gusta recibir críticas?","¿Hay personas que no te gustan?","¿Perdonás fácilmente?","¿Guardás secretos?","¿Evitás personas algunas veces?","¿Decís lo que pensás?","¿Hay cosas que nunca contás?"],
  ["¿Te gusta viajar?","¿Preferís viajar solo o acompañado?","¿Qué país querés visitar?","¿Qué ciudad querés conocer?","¿Preferís playa o montaña?","¿Podés vivir lejos de tu familia?","¿Querés vivir en otro país?","¿Qué necesitás cuando viajás?","¿Te gusta hablar con gente local?","¿Dónde querés vivir algún día?"],
  ["¿Querés visitar Argentina?","¿Qué sabés de Argentina?","¿Querés conocer Buenos Aires?","¿Querés probar mate?","¿Querés comer asado?","¿Te gusta el fútbol?","¿Qué lugar de Argentina querés visitar?","¿Cómo imaginás a los argentinos?","¿Argentina es muy diferente de tu país?","¿Podés vivir en Argentina por un año?"],
  ["¿Dónde querés vivir?","¿Querés viajar más?","¿Querés cambiar de trabajo?","¿Querés aprender otro idioma?","¿Querés vivir en otro país?","¿Querés tener más tiempo libre?","¿Qué querés aprender?","¿Qué país querés conocer?","¿Cómo querés vivir en diez años?","¿Pensás mucho en el futuro?"],
  ["Tenés mucho dinero. ¿Qué comprás?","Tenés un mes libre. ¿Dónde vas?","Podés vivir en cualquier país. ¿Cuál elegís?","Podés aprender un idioma. ¿Cuál?","No necesitás trabajar. ¿Qué hacés?","Podés conocer a una persona famosa. ¿Quién?","Tenés un viaje gratis. ¿Dónde vas?","Podés cambiar de trabajo. ¿Qué elegís?","Podés vivir en cualquier ciudad. ¿Dónde?","Podés aprender algo nuevo. ¿Qué?"],
  ["¿Te gusta estar solo?","¿A veces no querés hablar?","¿A veces no contestás mensajes?","¿Hay fiestas que no te gustan?","¿Qué cosa popular no te gusta?","¿Qué cosa de ser adulto no te gusta?","¿Instagram muestra la vida real?","¿La gente quiere parecer feliz?","¿A veces decís “sí” pero querés decir “no”?","¿Qué cosa muchas personas hacen pero no les gusta?"],
  ["¿Qué comida popular no te gusta?","¿Qué película famosa no te gusta?","¿Qué cantante famoso no te gusta?","¿Qué ciudad famosa no querés visitar?","¿Qué aplicación no te gusta?","¿Qué moda no entendés?","¿Qué actividad popular es aburrida para vos?","¿Qué comida de tu país no te gusta?","¿Qué cosa cara no querés comprar?","¿Qué opinión tuya sorprende a la gente?"],
  ["¿Qué animal querés ser por un día?","¿Qué trabajo nunca querés hacer?","¿Cuál es una buena edad para vos?","¿Qué lugar te hace feliz?","¿Qué olor te gusta?","¿Qué cosa mejora tu día?","¿Qué habilidad querés tener?","¿Qué persona famosa querés conocer?","¿Qué cosa siempre tenés con vos?","¿Qué tema te gusta mucho hablar?"]
];
