/** C1: recuerdos, lecturas alternativas y excepciones, en los quince mundos originales. */
export const c1Questions: string[][] = [
  [
    'Pensá en una costumbre familiar que de chico te parecía universal. ¿Cuándo descubriste que no lo era y qué entendiste entonces de tu propia casa?',
    'Hay personas que guardan la vajilla buena para visitas y otras que la usan todos los días. ¿Qué cuenta cada costumbre sobre la manera de disfrutar las cosas? ¿Dónde te reconocés vos?',
    '¿Qué hábito ajeno te irrita aunque hagas algo muy parecido? Contá una situación en la que te haya costado admitir esa semejanza.',
    'Alguien deja de felicitar cumpleaños porque quiere llamar cuando realmente tiene ganas. ¿Cómo distinguirías un gesto más sincero de una excusa cómoda?',
    'Recordá un ritual que hayas mantenido después de olvidar por qué lo empezaste. ¿Qué perderías si lo abandonaras: la actividad o la continuidad que te da?',
    'En un grupo, quien trae comida casera recibe elogios; quien compra algo parece haber hecho menos esfuerzo. ¿Qué se está valorando sin decirlo? ¿Cuándo te parecería injusta esa comparación?',
    'Una costumbre que antes te daba vergüenza ahora te resulta entrañable. ¿Cambió la costumbre, tu relación con quienes la practican o tu necesidad de encajar?',
    'Si alguien observara tus pequeñas manías durante una semana, ¿qué conclusión acertada sacaría sobre vos y en cuál se equivocaría por completo?',
  ],
  [
    '¿Qué logro tuyo perdió importancia cuando por fin lo conseguiste? Explicá si fue una decepción o una forma de entender mejor lo que querías.',
    'Recordá una etapa difícil de la que guardes un recuerdo sorprendentemente bueno. ¿Qué parte no convendría olvidar para no idealizarla?',
    'Una persona dice que quiere una vida tranquila, pero acepta proyectos que la mantienen ocupada. ¿En qué circunstancias verías una contradicción y en cuáles una forma de encontrar tranquilidad?',
    '¿Qué decisión pequeña terminó protegiendo algo importante para vos sin que lo supieras en ese momento?',
    'Te ofrecen recuperar tiempo a cambio de dejar de hacer algo en lo que sos muy bueno. ¿Cómo separarías el placer de hacerlo de la satisfacción de que te necesiten?',
    'Compará dos momentos en los que hayas dicho «tengo todo lo que necesito». ¿Significaba lo mismo en ambos?',
    'Hay quien cambia de rumbo y siente que desperdició años; otra persona siente que esos años hicieron posible el cambio. ¿Qué experiencia te permite entender las dos lecturas?',
    '¿Qué consejo sobre una buena vida te sirve personalmente, pero te daría reparo recomendar a cualquiera? Explicá qué condiciones lo hacen útil para vos.',
  ],
  [
    'Pensá en una amistad que funcione sin hablar demasiado. ¿Qué señales te permiten confiar en ella y por qué esas mismas señales podrían no alcanzar en otra relación?',
    '¿Alguna vez conociste una faceta inesperada de alguien al verlo con otras personas? Contá cómo cambió tu interpretación de su forma de ser con vos.',
    'Dos amigos recuerdan de manera distinta quién sostuvo la amistad durante una etapa difícil. ¿Cómo podrían hablarlo sin convertir los cuidados en una cuenta pendiente?',
    'Una persona deja de pedirte consejo después de ganar confianza. ¿Cómo sabrías si el vínculo se debilitó o si tu ayuda cumplió su propósito?',
    '¿Qué desacuerdo te acercó a alguien? Explicá qué tuvo esa conversación que no suelen tener las discusiones que desgastan una relación.',
    'El grupo sigue invitando a alguien que casi nunca viene para que no se sienta excluido. ¿En qué momento esa insistencia deja de ser amable y quién puede reconocerlo?',
    'A veces conocemos mejor los problemas de un amigo que sus alegrías cotidianas. ¿Qué imagen incompleta de la relación puede producir eso? Relacionalo con algo que hayas observado.',
    'Imaginá que volvés a conocer hoy a una amistad de hace veinte años. ¿Qué los acercaría y qué quizá no descubrirían sin la historia que comparten?',
  ],
  [
    '¿Qué rasgo que considerabas un defecto tuyo resultó útil en una situación concreta? ¿Eso cambió la forma en que lo valorás o solo mostró una excepción?',
    'Contá una ocasión en la que parecías seguro de algo y por dentro dudabas. ¿Qué habría entendido mal alguien que solo hubiera visto tu manera de actuar?',
    'Una persona se describe como espontánea, pero necesita que los demás resuelvan lo que no planifica. ¿Cómo distinguirías una forma de ser de una comodidad que otros sostienen?',
    '¿En qué ambiente sos una versión de vos que sorprende a quienes te conocen de otro contexto? Explicá qué te permite o te exige ese lugar.',
    'Recordá un elogio que te haya incomodado. ¿Qué expectativa venía escondida en él, aunque quien lo hizo tuviera buena intención?',
    'Cuando decís «yo soy así», ¿en qué casos estás siendo honesto y en cuáles podrías estar cerrando una posibilidad de cambio?',
    '¿Qué opinión sobre vos mismo revisaste por una experiencia, después de ignorar durante años comentarios parecidos de otras personas?',
    'Si pudieras escuchar cómo te describe alguien que recién te conoce, ¿qué malentendido dejarías pasar y cuál querrías aclarar enseguida? Explicá la diferencia.',
  ],
  [
    'Recordá una norma de cortesía que aprendiste tarde. ¿Qué cambió al conocerla y qué te hace dudar de que todos deban seguirla?',
    'Una fiesta del barrio atrae cada vez más visitantes y quienes la organizaban dejan de sentirse en casa. ¿Qué tendría que conservar para seguir siendo su fiesta aunque cambie?',
    '¿Qué forma de mostrar respeto puede parecer frialdad o distancia en otro entorno? Explicá cómo evitarías una interpretación apresurada con un ejemplo.',
    'Pensá en algo que se elogia como «auténtico». ¿Quién tiene permiso para cambiarlo sin que deje de serlo y quién decide ese límite?',
    'Un museo expone objetos cotidianos que todavía se usan en tu casa. ¿Qué te gustaría que entendieran los visitantes y qué te molestaría que vieran como una rareza?',
    '¿Qué cambio social celebrás en general, aunque haya hecho más difícil algo concreto de tu vida? ¿Cómo explicarías ambas cosas sin desautorizar el cambio?',
    'En una reunión, alguien dice «acá siempre se hizo así» para terminar una discusión. ¿Cuándo esa frase aporta una experiencia valiosa y cuándo evita explicar una decisión?',
    'Compará una celebración que conocés desde dentro con otra a la que fuiste como invitado. ¿Qué detalles interpretaste distinto según tu lugar en cada una?',
  ],
  [
    '¿Qué compra que en su momento pareció un capricho terminó teniendo mucho valor para vos? ¿Qué parte de ese valor habría sido imposible justificar antes?',
    'Alguien de tu entorno dice «el dinero no importa» y puede permitirse rechazar trabajos. ¿Cómo conversarías sobre esa frase sin descartar su experiencia ni presentarla como universal?',
    'Recordá un regalo barato que haya resultado difícil de corresponder. ¿Qué deuda sentiste, si la hubo, y de dónde venía?',
    'Dos personas ganan lo mismo, pero una puede contar con su familia si algo sale mal. ¿En qué decisiones cotidianas se vuelve visible esa diferencia?',
    '¿En qué gastás sin pensarlo demasiado y en qué cantidad pequeña te detenés a comparar? Explicá qué dice esa contradicción sobre tu idea de lo caro.',
    'Te ofrecen pagar por una actividad que hacés gratis con gusto. ¿Qué cambiaría en tu relación con esa actividad, incluso si nadie te exigiera más?',
    'Una amistad propone siempre planes económicos, pero nunca explica por qué. ¿Cómo dejarías espacio para hablar de dinero sin obligarla a revelar su situación?',
    'Si pudieras devolver una compra y recuperar también el tiempo que le dedicaste, ¿cuál elegirías? ¿Te arrepentís del objeto o de lo que esperabas que cambiara?',
  ],
  [
    '¿Qué comodidad digital aceptás hoy que antes te habría parecido demasiado invasiva? Reconstruí cómo cambió tu límite, sin dar por hecho que el cambio fue bueno o malo.',
    'Un mapa te lleva siempre por la ruta más rápida y dejás de pasar por un lugar que te gustaba. ¿Qué otras preferencias tuyas quedan fuera de lo que una aplicación llama «mejor»?',
    'Contá una vez que estar disponible todo el tiempo te haya hecho menos atento con alguien. ¿Qué habrías necesitado cambiar para estar realmente presente?',
    'Una aplicación te recuerda un aniversario que habías olvidado. ¿El mensaje que enviás después vale menos por haber necesitado ese aviso? ¿Dónde pondrías la diferencia?',
    '¿Qué tarea aprendiste a hacer más rápido sin que eso te dejara más tiempo libre? Explicá adónde fue a parar el tiempo que supuestamente ganaste.',
    'En un chat de vecinos, un problema menor se vuelve urgente porque todos lo comentan. ¿Cómo distinguirías una preocupación compartida de una importancia creada por la conversación?',
    'Pensá en una recomendación automática que te haya sorprendido para bien. ¿Qué te mostró de tus gustos y qué seguiría sin poder saber de vos?',
    'Si mañana desaparecieran las cifras de seguidores, valoraciones y «me gusta», ¿qué elegirías de otra manera y qué criterio tuyo quedaría más a la vista?',
  ],
  [
    '¿Qué pregunta aparentemente amable puede obligar a alguien a explicar más de lo que quiere? Reformulala para conservar el interés sin dar por sentada su situación.',
    'Un conocido celebra una decisión que vos lamentaste tomar. ¿Cuánto aclararías y qué te haría preferir dejar que conserve su interpretación?',
    'Recordá una disculpa que aceptaste sin quedar del todo conforme. ¿Qué diferencia había entre lo que la otra persona reconocía y lo que vos necesitabas que entendiera?',
    'En una cena todos elogian un proyecto y vos ves un problema serio. ¿Qué deberías saber antes de decidir si decirlo ahí, después o no decirlo?',
    '¿Alguna vez te pidieron sinceridad, pero parecía que solo esperaban apoyo? Explicá cómo reconociste esa diferencia y qué respuesta te pareció más honesta.',
    'Alguien cuenta como propia una idea que surgió en una conversación con vos. ¿Qué detalle determinaría si lo corregís, lo hablás en privado o lo dejás pasar?',
    'Te preguntan por qué ya no ves a una persona. ¿Cómo darías una respuesta verdadera que también respete la parte de la historia que no te pertenece?',
    '¿Qué silencio tuyo pudo interpretarse como acuerdo aunque no lo fuera? Si retomaras la conversación hoy, ¿cómo aclararías tu posición sin fingir que ya la habías expresado?',
  ],
  [
    'Recordá un lugar que te gustó más al dejar de intentar aprovechar cada día. ¿Qué cambió en tu manera de mirarlo?',
    'Al vivir fuera, una costumbre de tu país empieza a parecerte importante aunque antes te daba igual. ¿Qué podría estar representando ahora además de la costumbre en sí?',
    '¿Qué experiencia de viaje contás de forma distinta según quién te escucha? Explicá si cambiás los detalles, la interpretación o la imagen que querés dar de vos.',
    'Una persona vuelve a su ciudad después de muchos años y dice que ya no la reconoce. ¿Cómo separarías lo que cambió en la ciudad de lo que cambió en ella?',
    'Te reciben como «uno más» en un lugar nuevo, pero para eso esperan que no cuestiones ciertas cosas. ¿En qué momento pertenecer empezaría a costarte demasiado?',
    '¿Qué dificultad de vivir en otro lugar podría parecer una aventura durante un mes y volverse agotadora al cabo de un año? Contá qué apoyos cambiarían esa experiencia.',
    'Alguien recomienda visitar un barrio porque «todavía no hay turistas». ¿Qué contradicción encierra la recomendación y cómo hablarías del lugar sin venderlo como un descubrimiento propio?',
    'Si tuvieras que aconsejar a alguien que va a vivir donde vos vivís, ¿qué consejo habitual evitarías porque depende demasiado de quién lo recibe?',
  ],
  [
    'Una persona nacida en Argentina que vive fuera dice que se siente más argentina desde que se fue. ¿Qué podría haber cambiado en su relación con el país? Comparalo con otra experiencia de pertenencia.',
    'En una charla sobre Argentina, alguien cuenta una anécdota de Buenos Aires como si describiera todo el país. ¿Cómo abrirías la conversación a otras experiencias sin convertir la anécdota en un error?',
    '¿Qué te sugiere la diferencia entre aprender una receta argentina y aprender cuándo, con quién y para qué se prepara? Usá una comida conocida para explicar lo que falta en la receta.',
    'Un amigo argentino se ríe de un problema de su país, pero se incomoda cuando un visitante hace la misma broma. ¿Qué cambia con quien la cuenta y cómo interpretarías su reacción?',
    'Imaginá que dos personas argentinas de generaciones distintas te recomiendan lugares de su infancia. ¿Qué preguntarías para entender el país que cada una recuerda sin elegir una versión como la verdadera?',
    'Escuchás una expresión argentina que entendés palabra por palabra, pero no sabés si expresa cariño, fastidio o ironía. ¿Qué pistas buscarías antes de usarla vos?',
    'Una reunión alrededor del mate sigue siendo importante para alguien que ya no toma mate. ¿Qué revela eso sobre la relación entre una costumbre y la pertenencia? Buscá un paralelo en tu vida.',
    'Te encargan presentar Argentina y solo podés incluir tres voces personales. ¿A quiénes buscarías, qué les preguntarías y qué dejarías claro sobre lo que esas voces no representan?',
  ],
  [
    '¿Qué futuro que imaginabas con entusiasmo dejó de atraerte? Explicá si cambió lo que deseabas o lo que sabés sobre sus consecuencias.',
    'Un día tus hábitos actuales van a parecer anticuados. ¿Cuál te gustaría que sobreviviera y cuál sospechás que defenderías solo por costumbre?',
    'Podés saber cómo va a cambiar tu barrio, pero no impedirlo. ¿Qué información te ayudaría a prepararte y cuál te quitaría la posibilidad de disfrutarlo ahora?',
    'Pensá en una predicción sobre tu vida que se cumplió por razones totalmente distintas de las que imaginabas. ¿La considerarías un acierto?',
    'En el futuro se vuelve muy fácil cambiar de profesión. ¿Qué dificultades seguirían existiendo aunque aprender lo necesario dejara de ser un obstáculo?',
    '¿Qué problema actual temés que resolvamos de una forma que cree otro problema? Describí una mejora concreta y el precio que podríamos no ver al principio.',
    'Si tu yo de hace diez años conociera tu vida actual, ¿qué interpretaría como una renuncia que vos vivís como una elección?',
    'Una ciudad decide conservar un espacio vacío para necesidades que todavía no conoce. ¿Cómo defenderías esa decisión ante quienes necesitan usarlo ya? ¿Qué te haría cambiar de postura?',
  ],
  [
    'Podés borrar una equivocación de tu historia, pero también desaparecería lo que aprendiste gracias a ella. ¿Qué tendrías que saber de sus consecuencias para decidir?',
    'Una persona te ofrece cumplir un sueño que ya no tenés, delante de quienes todavía te recuerdan por él. ¿Cómo rechazarías el regalo sin rechazar la versión de vos que quisieron cuidar?',
    'Heredás un objeto que varios familiares quieren por motivos distintos. ¿Cómo decidirías qué hacer con él sin suponer que todos le dan el mismo valor?',
    'Podés escuchar una conversación en la que hablan bien de vos, pero nunca saber quién dijo cada cosa. ¿Te interesaría igual? Explicá qué buscás cuando querés saber la opinión ajena.',
    'Te invitan a representar a un grupo con el que compartís experiencias, pero no muchas opiniones. ¿Qué condiciones pondrías para aceptar sin hablar por quienes no piensan como vos?',
    'Un amigo te pide que le recuerdes una promesa si cambia de opinión; meses después te pide que dejes de hacerlo. ¿A cuál de sus dos pedidos darías más peso y por qué?',
    'Podés probar durante una semana la vida que habrías tenido al elegir otro camino. ¿Qué comparación sería justa y qué no podrías juzgar en tan poco tiempo?',
    'Organizás una sorpresa que entusiasma a todo el grupo menos a la persona homenajeada. ¿Cómo cambiarías el plan cuando ya hubo mucho esfuerzo sin convertir su preferencia en culpa?',
  ],
  [
    '¿Qué satisfacción te cuesta admitir porque no encaja con la imagen que das de vos? Podés inventar un ejemplo y explicar por qué sería difícil reconocerla.',
    'A veces nos molesta que alguien haga bien algo que nosotros le enseñamos. ¿Qué parte de esa reacción podrías comprender sin justificar que se la hagamos pagar?',
    'Contá una ocasión real o inventada en la que un alivio se haya confundido con indiferencia. ¿Qué faltaba saber para interpretar la reacción?',
    'Alguien recibe una buena noticia y tarda en compartirla por miedo a que cambie la relación con sus amigos. ¿Qué señales le ayudarían a distinguir un temor propio de un riesgo real?',
    '¿Qué versión de una historia seguís contando aunque ya no te represente del todo? Explicá qué pasaría si empezaras a contarla de otra manera.',
    'Una persona disfruta más preparando un encuentro que durante el encuentro mismo. ¿Eso le quita valor a la experiencia o muestra dónde estaba lo importante para ella?',
    '¿En qué situaciones decir «no me importa lo que piensen» puede ser una forma de proteger algo que sí importa mucho?',
    'Pensá en una expectativa que otros dejaron de tener sobre vos y que, contra lo que imaginabas, extrañaste. ¿Qué reconocimiento venía unido a esa presión?',
  ],
  [
    '¿Qué opinión tuya cambió sin que hubiera una gran discusión ni un hecho decisivo? Reconstruí las pequeñas experiencias que fueron haciendo la diferencia.',
    'Dos personas están de acuerdo en una decisión, pero por razones opuestas. ¿Qué conversación necesitarían tener antes de confiar en que ese acuerdo va a durar?',
    'Recordá una conversación en la que entendiste mejor una postura sin acercarte a ella. ¿Qué ganaste, aunque el desacuerdo siguiera igual?',
    '¿Qué gusto personal defendiste alguna vez como si fuera un criterio objetivo? Explicá qué te permitió reconocer la diferencia.',
    'Alguien usa una experiencia excepcional para cuestionar una afirmación bastante razonable. ¿Cómo reconocerías esa excepción sin fingir que invalida todo lo demás?',
    'Una persona cambia de opinión en público y otra la acusa de no tener criterio. ¿Qué distinguiría una revisión honesta de un cambio por conveniencia?',
    '¿Hay un tema en el que seas más comprensivo con desconocidos que con personas cercanas? Explicá qué expectativa hace variar tu juicio.',
    'Si tuvieras que explicar una opinión que no compartís de manera que quien la sostiene se sintiera bien representado, ¿qué parte te costaría más formular y por qué?',
  ],
  [
    'Encontrás una nota tuya con una preocupación que ya ni recordabas. ¿Te tranquilizaría comprobar que pasó o te haría desconfiar de la importancia que das a tus problemas actuales?',
    '¿Qué encuentro de pocos minutos cambió tu impresión de un día entero? Contá por qué tuvo más peso que otras cosas que habían pasado.',
    'Un objeto barato se rompe y descubrís que te cuesta más reemplazarlo que uno caro. ¿Qué historia podría explicar esa diferencia?',
    'Escuchás por casualidad una canción que no te gusta y te pone de buen humor. ¿Qué puede conectar un recuerdo con una emoción distinta del gusto?',
    '¿Cuándo fue la última vez que alguien hizo algo considerado por vos sin que lo notaras hasta después? ¿Qué cambia al reconocer tarde esos gestos?',
    'Una confusión te lleva a un lugar al que nunca habrías ido y terminás disfrutándolo. ¿Lo repetirías a propósito o perdería algo al dejar de ser accidental?',
    'Te muestran una foto donde todos parecen felices y vos recordás un día bastante malo. ¿Qué historia cuenta la imagen y qué derecho le darías a esa versión del recuerdo?',
    'Si escribieras una reseña de tu semana usando un detalle que nadie más notó, ¿cuál elegirías y qué impresión engañosa podría llevarse quien la leyera?',
  ],
];

export const c1DiscourseMoves = [
  { move: 'Delimitá lo que afirmás', chunk: 'En los casos que conozco…, aunque no lo extendería a…' },
  { move: 'Concedé sin retirar tu idea', chunk: 'Te concedo que…; mi reserva tiene que ver con…' },
  { move: 'Cambiá el foco', chunk: 'Más que discutir si…, me interesa distinguir…' },
  { move: 'Precisá una palabra', chunk: 'Con «…» no me refiero a…, sino a…' },
  { move: 'Corregite sobre la marcha', chunk: 'Lo dije demasiado tajante. Sería más preciso decir…' },
  { move: 'Introducí una excepción', chunk: 'Eso suele pasar, salvo cuando…; ahí cambia…' },
  { move: 'Sostené dos lecturas', chunk: 'Puede entenderse como…; visto desde…, también podría…' },
];

export const c1TopicSupport = [
  { line: 'Lo familiar también puede verse de otra manera.', followUps: ['¿Qué parte del hábito pertenece a la persona y qué parte al grupo que lo espera?', '¿Qué excepción te impide sacar una conclusión sobre toda tu familia?'] },
  { line: 'Lo que valorás y lo que aprendiste a valorar.', followUps: ['¿Con qué idea de una buena vida estás comparando esa experiencia?', '¿Qué pérdida aparente terminó abriendo un espacio que necesitabas?'] },
  { line: 'Los vínculos no siempre cuentan una sola historia.', followUps: ['¿Qué contaría la otra persona de ese mismo momento?', '¿Qué puede cambiar en un vínculo sin que cambie el afecto?'] },
  { line: 'No sos exactamente igual en todos los lugares.', followUps: ['¿Qué etiqueta sobre vos queda corta para explicar ese caso?', '¿Qué distinguiría un cambio de carácter de una respuesta al entorno?'] },
  { line: 'Mirar desde dentro cambia lo que se ve.', followUps: ['¿Qué está dando por sabido quien ya pertenece a ese entorno?', '¿Cómo conservarías un sentido compartido sin exigir una única forma de participar?'] },
  { line: 'El valor de algo no cabe entero en su precio.', followUps: ['¿Qué margen de elección estás suponiendo que tiene la otra persona?', '¿Cuándo una cantidad pequeña deja de ser pequeña en esa historia?'] },
  { line: 'La comodidad también cambia nuestras expectativas.', followUps: ['¿Qué decisión parece tuya, pero viene sugerida por el diseño de la herramienta?', '¿Qué señal te permitiría distinguir una preferencia de una costumbre adquirida?'] },
  { line: 'Una verdad puede decirse de más de una forma.', followUps: ['¿Qué parte de la verdad hace falta para esta conversación y qué parte la desviaría?', '¿Cómo cambiaría el sentido de tus palabras según quién estuviera presente?'] },
  { line: 'Irse, llegar y volver no significan lo mismo para todos.', followUps: ['¿Qué aspecto solo se entiende cuando el viaje se convierte en vida cotidiana?', '¿Qué estás comparando realmente: dos lugares o dos momentos de tu vida?'] },
  { line: 'Un país, muchas voces y pertenencias.', followUps: ['¿Qué detalle situaría esa experiencia en una región, una generación o un grupo concreto?', '¿Cómo la contarías dejando espacio a una experiencia argentina distinta?'] },
  { line: 'El futuro también revela cómo miramos el presente.', followUps: ['¿Qué das por permanente en ese futuro que podría cambiar antes?', '¿Qué parte de la predicción expresa un deseo más que una expectativa?'] },
  { line: 'Elegir también es decidir qué comparación vale.', followUps: ['¿A qué versión de esa persona estás respondiendo: la de antes o la de ahora?', '¿Qué compromiso seguiría teniendo sentido si cambiaran tus motivos para asumirlo?'] },
  { line: 'Lo difícil de admitir también tiene matices.', followUps: ['¿Qué diferencia hay entre sentir eso y actuar a partir de ese sentimiento?', '¿Qué dato volvería comprensible una reacción que desde fuera parece contradictoria?'] },
  { line: 'Entender una postura no obliga a compartirla.', followUps: ['¿Qué parte del desacuerdo se debe a que usan una palabra con sentidos distintos?', '¿Qué reconocerías como razonable sin incorporarlo a tu propia postura?'] },
  { line: 'Un detalle puede cambiar el relato de un día.', followUps: ['¿Qué otra historia se podría contar con los mismos detalles?', '¿Qué se perdería al convertir esa sorpresa en una explicación demasiado redonda?'] },
];

export function c1ClosingQuestions(selectedQuestions: string[]): string[] {
  if (selectedQuestions.length !== 3) return [
    'Buscá un hilo entre tus tres respuestas: puede ser una prioridad, una expectativa o un cambio de perspectiva. Evitá resumirlas por separado.',
    'Usá la tercera respuesta para poner a prueba lo que relacionaste en las otras dos. ¿Aparece una excepción o necesitás precisar tu idea?',
    'Construyan una reflexión compartida: una persona propone una lectura, la otra ofrece una lectura alternativa y juntas reformulan una conclusión que admita sus límites.',
  ];
  return [
    `Relacioná tus respuestas a «${selectedQuestions[0]}» y «${selectedQuestions[1]}». ¿Qué supuesto, tensión o cambio de perspectiva aparece en ambas? Proponé un hilo común e incorporá un detalle concreto de cada respuesta.`,
    `Contrastá ese hilo con «${selectedQuestions[2]}». ¿La tercera respuesta lo confirma, introduce una excepción o exige cambiar la formulación? Recuperá algo que haya dicho la otra persona para precisar tu interpretación.`,
    'Conversen durante tres minutos siguiendo ese hilo, sin volver a responder las preguntas por separado. Una persona propone una conclusión que reúna las tres experiencias; la otra ofrece una lectura alternativa y pide aclarar una palabra decisiva. Reformulen juntas lo que sostienen y cierren con una excepción o una pregunta que queda abierta.',
  ];
}
