import { topics } from './data';
import { a1Questions } from './a1-data';
import { c1Questions, c1TopicSupport, c1ClosingQuestions } from './c1-data';
import { b2Questions, b2TopicSupport, b2ClosingQuestions } from './b2-data';
import type { ConversationLevelVariant } from '../conversation-families/types';
import type { Topic } from './data';
const titles = ['Costumbres curiosas','Lo que importa','Relaciones','Cómo somos','Cultura y sociedad','Dinero y vida','Vida moderna','Preguntas incómodas','Viajes y vida en otro país','Argentina','El futuro','¿Qué harías?','Lo que no siempre decimos','Opiniones diferentes','Sorpresas cotidianas'];
const a2Questions = [
 ['Un amigo llega muy temprano a tu casa. ¿Qué le dices?', '¿Qué costumbre tuya es diferente de la de tu familia?', '¿Qué haces cuando no puedes dormir?', 'Quieres cambiar un hábito esta semana. Cuenta tu plan.', 'Tu compañero deja todo desordenado. Pídele un cambio.', '¿Qué haces en casa que no haces en el trabajo?'],
 ['¿Qué actividad te ayuda a descansar después de un día difícil?', 'Tienes una tarde libre y poco dinero. ¿Qué vas a hacer?', '¿Con quién hablas cuando tienes un problema?', 'Compara un día tranquilo y un día con muchos planes.', '¿Qué cosa pequeña te alegró esta semana?', 'Organiza un día agradable para un amigo que está cansado.'],
 ['Quieres invitar a un amigo nuevo a salir. ¿Qué le propones?', 'Tu pareja quiere ir al cine y tú quieres cocinar. Busquen un plan.', '¿Cómo conociste a un buen amigo?', '¿Qué haces cuando alguien llega tarde?', 'Un amigo necesita ayuda para mudarse. Explica cuándo puedes ayudar.', 'Cuenta una actividad que te gusta hacer con tu familia.'],
 ['¿Qué haces cuando estás nervioso antes de una reunión?', '¿Prefieres trabajar solo o con otra persona? Da una razón.', 'Describe a una persona tranquila que conoces.', '¿Qué lugar te ayuda a concentrarte?', 'Tu amigo está preocupado por un examen. ¿Qué le dices?', '¿Cómo cambia tu ánimo cuando duermes poco?'],
 ['Un visitante va a comer con tu familia. Explícale una costumbre.', '¿A qué hora se cena en tu ciudad? Compárala con otra ciudad.', 'Cuenta cómo celebraste una fiesta el año pasado.', '¿Qué regalo llevas cuando visitas a alguien?', 'Un amigo no conoce una comida local. Descríbela.', 'Prepara dos consejos sencillos para visitar tu barrio.'],
 ['Quieres ahorrar para un viaje. ¿Qué gasto puedes reducir?', 'Compara comprar comida afuera y cocinar en casa.', 'El precio de un producto es diferente al de la etiqueta. ¿Qué dices?', 'Organiza una salida con un presupuesto pequeño.', '¿En qué gastaste dinero esta semana?', 'Tu amigo quiere algo caro para su cumpleaños. Propón otra opción.'],
 ['Te quedaste sin batería en la calle. ¿Qué haces?', 'Describe una aplicación que usas todos los días.', 'Quieres pasar una tarde sin teléfono. Organiza el plan.', 'Tu pedido llegó equivocado. Explica el problema.', '¿Qué compras por internet y qué prefieres comprar en una tienda?', 'Explícale a un amigo cómo llegar a tu casa sin usar una aplicación.'],
 ['No quieres responder una pregunta personal. ¿Qué puedes decir?', 'Un amigo te pide dinero y no puedes ayudar. Explícalo.', 'Llegaste tarde a una clase. Cuenta qué pasó.', 'No te gusta la comida que te ofrecen. ¿Qué dices?', 'Quieres cambiar de habitación en un hotel. Explica por qué.', 'Tu vecino hace ruido de noche. Habla con él.'],
 ['Llegaste a una ciudad nueva. ¿Qué quieres hacer primero?', 'Compara viajar solo y viajar con un amigo.', 'Tu hotel no tiene agua caliente. Explica el problema.', 'Organiza dos días de viaje con poco equipaje.', '¿Qué lugar visitaste y te gustó?', 'Perdiste el autobús. Pregunta por otra opción.'],
 ['Un amigo quiere visitar Buenos Aires. Propón dos actividades.', 'Quieres probar una comida argentina. ¿Qué preguntas en el restaurante?', '¿Prefieres visitar una ciudad o conocer el campo? Explica.', 'Describe cómo preparas una bebida que te gusta.', 'Organiza una reunión con amigos un domingo.', 'Compara una costumbre argentina que conoces con una de tu país.'],
 ['¿Qué vas a hacer el próximo fin de semana?', 'Quieres aprender algo nuevo este año. Explica tu plan.', 'Tu amigo viene de visita el mes que viene. Organicen una salida.', '¿Dónde quieres vivir el próximo año? Da una razón.', 'Mañana va a llover. Cambia tu plan para la tarde.', 'Cuenta qué necesitas preparar antes de un viaje.'],
 ['Estás en una tienda y olvidaste la cartera. ¿Qué dices?', 'Tu amigo no encuentra su teléfono. Hazle preguntas para ayudar.', 'Tienes dos invitaciones para la misma hora. Elige y explica.', 'Llegas a una estación y no sabes dónde comprar el billete. Pregunta.', 'Un amigo no puede venir a cenar. Cambien la fecha.', 'Se acabó tu comida favorita. Elige otra y pide información.'],
 ['No quieres salir hoy. Explica cómo te sientes.', 'Necesitas estar solo un rato. ¿Cómo se lo dices a un amigo?', 'Un compañero te interrumpe mucho. Pídele que espere.', '¿Qué tarea de casa no te gusta hacer?', 'Quieres pedir ayuda pero te da vergüenza. Practica el pedido.', 'Cuenta una ocasión en la que cambiaste de opinión.'],
 ['A tu amigo le encanta una película y a ti no. Comparen sus gustos.', '¿Prefieres desayunar temprano o tarde? Explica.', 'Elijan entre playa y montaña para un viaje corto.', '¿Qué comida no te gusta aunque a otros sí?', 'Uno quiere música y otro silencio para trabajar. Busquen una solución.', 'Compara dos maneras de pasar un domingo.'],
 ['Encontraste una foto vieja. Cuenta quién aparece y dónde están.', 'Elige tres cosas para llevar a una isla por un día.', '¿Qué sonido te recuerda a tu casa?', 'Cuenta algo divertido que pasó en un viaje.', 'Tienes una hora libre en una ciudad desconocida. ¿Qué haces?', 'Haz tres preguntas para conocer mejor a tu profesor.'],
];
const activities = (questions: string[][]) => topics.map((topic,index)=>({...topic,title:titles[index],line:'Elige tres preguntas y conversa.',questions:questions[index]}));
export const talkVariants: Record<'A1'|'A2'|'B1'|'B2'|'C1', ConversationLevelVariant<Topic[]>> = {
 A1:{level:'A1',communicativeObjectives:['Intercambiar información personal y preferencias con apoyo'],expectedFunctions:['Identificar','Describir de forma breve','Preguntar por gustos'],pcicFocus:['Información personal','Gustos y preferencias'],activities:activities(a1Questions),teacherNotes:['Elige dos o tres mundos. Dedica unos cinco minutos a cada intercambio y ofrece apoyos breves cuando hagan falta.'],closingConversation:['¿Qué tema te gusta más?','¿Qué tienes en común con la otra persona?','Haz una pregunta nueva sobre su vida.']},
 A2:{level:'A2',communicativeObjectives:['Resolver pequeños problemas y acordar planes cotidianos'],expectedFunctions:['Explicar un problema','Proponer un plan','Comparar opciones'],pcicFocus:['Planes e intenciones','Peticiones','Razones sencillas'],activities:activities(a2Questions),teacherNotes:['Alternen papeles en las situaciones. Después de cada intercambio cambien un detalle y vuelvan a conversar.'],closingConversation:['¿Qué situación se parece a algo que te pasó? Cuéntalo.','Elijan una actividad que quieren hacer juntos y acuerden cuándo.','¿Qué puedes decir ahora cuando tienes un problema?']},
 B1:{level:'B1',communicativeObjectives:['Relacionar experiencias, justificar opiniones y reaccionar a otras perspectivas'],expectedFunctions:['Narrar','Justificar','Considerar alternativas'],pcicFocus:['Opiniones y valoraciones','Narración de experiencias'],activities:activities(topics.map(topic=>topic.questions)),teacherNotes:['Elige tres mundos y permite repreguntas del interlocutor. Profundicen en dos decisiones antes del cierre.'],closingConversation:['¿Qué opinión cambiaste o matizaste al escuchar a la otra persona?','Relaciona una pregunta con una experiencia que no habías contado.','Propongan un acuerdo sobre un tema en el que piensan diferente.']},
 B2:{level:'B2',communicativeObjectives:['Defender y matizar opiniones conectando situaciones cotidianas','Negociar acuerdos y revisar decisiones ante otras perspectivas'],expectedFunctions:['Comparar prioridades','Responder a objeciones','Explicar consecuencias','Reformular una postura'],pcicFocus:['Opiniones y valoraciones matizadas','Concesión y contraargumentación','Condiciones e hipótesis','Gestión de turnos y aclaraciones'],activities:activities(b2Questions).map((topic,index)=>({...topic,line:b2TopicSupport[index].line})),teacherNotes:['Propuesta de 45 minutos: 5 para elegir un mundo y anticipar un desacuerdo; 3 para seleccionar exactamente tres preguntas; 21 para conversar (7 por pregunta, alternando posturas y usando una repregunta si hace falta); 8 para cambiar una condición y negociar de nuevo; 8 para conectar las tres ideas y realizar el cierre oral. Los apoyos son opcionales. Se puede inventar una experiencia en vez de compartir algo personal.'],closingConversation:b2ClosingQuestions([])},
 C1:{level:'C1',communicativeObjectives:['Relacionar experiencias e interpretar sus contradicciones sin reducirlas a una sola explicación','Construir una reflexión compartida con matices, excepciones y lecturas alternativas'],expectedFunctions:['Delimitar generalizaciones','Reinterpretar experiencias','Precisar y reformular','Reconocer dos lecturas válidas'],pcicFocus:['Restricción y atenuación de afirmaciones','Concesión y rectificación','Significados implícitos','Organización de un discurso sostenido'],activities:activities(c1Questions).map((topic,index)=>({...topic,line:c1TopicSupport[index].line})),teacherNotes:['Propuesta de 45 minutos: 5 para evocar una conversación que cambió una perspectiva y elegir un mundo; 3 para seleccionar exactamente tres preguntas con enfoques distintos; 21 para conversar (7 por pregunta: experiencia concreta, interpretación y repregunta); 8 para ensayar una lectura alternativa y delimitar qué afirmaciones admiten excepciones; 8 para relacionar las tres respuestas, sostener una mini-conversación y precisar una conclusión compartida. Los apoyos son opcionales; se pueden inventar experiencias o elegir otras preguntas sin explicar por qué.'],closingConversation:c1ClosingQuestions([])},
};
