export type Topic={name:string;emoji:string;desc:[string,string];color:string;questions:string[]};
export type ForbiddenBlock={name:string;question:string;challenge:[string,string];color:string};
export type PowerUp={emoji:string;name:string;english:string;phrase:string;translation:string;color:string};

export const topics:Topic[]=[
  {name:"Sexo y Vergüenza",emoji:"🔥",desc:["Deseo, culpa, placer, miedo y silencio social.","Desire, guilt, pleasure, fear and social silence."],color:"#e33b64",questions:["¿Por qué tanta gente habla de libertad sexual, pero sigue sintiendo vergüenza?","¿El deseo revela quién sos o solo una parte de vos que no controlás?","¿La educación sexual debería hablar más de placer, miedo o responsabilidad?","¿Qué pesa más en la vida sexual de una persona: moral, inseguridad o experiencia?"]},
  {name:"Muerte y Sentido",emoji:"☠️",desc:["Muerte, miedo, legado y sentido de vida.","Death, fear, legacy and meaning in life."],color:"#48536f",questions:["¿La muerte hace que la vida tenga más sentido o solo más presión?","¿Qué asusta más: morir joven o vivir muchos años sin haber vivido de verdad?","¿La gente evita hablar de la muerte porque tiene miedo o porque no sabe cómo vivir?","¿Preferirías saber la fecha de tu muerte o vivir sin saber nada?"]},
  {name:"Amor Prohibido",emoji:"💘",desc:["Deseo, límites, culpa y consecuencias.","Desire, boundaries, guilt and consequences."],color:"#db3e9a",questions:["¿Un amor prohibido es más intenso porque es amor o porque es imposible?","¿Está mal sentir algo fuerte por alguien que no deberías desear?","¿Qué pesa más: lo que sentís o el daño que podrías causar?","¿Hay amores que solo funcionan porque nunca se vuelven reales?"]},
  {name:"Derechos Humanos",emoji:"⚖️",desc:["Dignidad, castigo, libertad y límites sociales.","Dignity, punishment, freedom and social limits."],color:"#7956c8",questions:["¿Los derechos humanos deben proteger incluso a personas que hicieron cosas horribles?","¿Una sociedad puede defender la libertad solo cuando le conviene?","¿Qué derecho humano se menciona mucho, pero se respeta poco?","¿La seguridad puede justificar perder libertad?"]},
  {name:"Brasil Sin Filtro",emoji:"🇧🇷",desc:["Brasil, deseo internacional, estereotipos, desigualdad e imagen global.","Brazil, international desire, stereotypes, inequality and global image."],color:"#179761",questions:["¿El mundo ama la imagen de Brasil, pero ignora sus problemas reales?","¿Brasil vende alegría hacia afuera mientras esconde dolor hacia adentro?","¿Qué estereotipo sobre Brasil te parece más injusto o más peligroso?","¿Brasil es visto como potencia cultural, país exótico o país subestimado?"]},
  {name:"Poder y Dinero",emoji:"💸",desc:["Ambición, riqueza, desigualdad y moral.","Ambition, wealth, inequality and morality."],color:"#12a979",questions:["¿El dinero cambia a la gente o solo le quita la necesidad de fingir?","¿La gente critica a los ricos porque tiene valores o porque quiere estar en su lugar?","¿Se puede ser muy exitoso sin volverse un poco egoísta?","¿Qué es más peligroso: no tener poder o tener demasiado?"]},
  {name:"Religión y Culpa",emoji:"⛪",desc:["Fe, deseo, culpa y control moral.","Faith, desire, guilt and moral control."],color:"#6448a7",questions:["¿La religión ayuda a vivir mejor o a sentir culpa con más palabras?","¿La culpa puede parecer espiritual, pero ser solo miedo?","¿Es posible tener fe sin controlar el deseo?","¿Qué pasa cuando una persona ama a Dios, pero se odia a sí misma?"]},
  {name:"Familia y Lealtad",emoji:"🏠",desc:["Sangre, deuda emocional, límites y culpa.","Blood ties, emotional debt, boundaries and guilt."],color:"#167bb3",questions:["¿La familia merece más perdón que otras personas?","¿La lealtad familiar puede convertirse en una cárcel?","¿Está mal alejarte de alguien que te quiere, pero te daña?","¿Los padres tienen derecho a esperar gratitud para siempre?"]},
  {name:"Redes y Narcisismo",emoji:"📱",desc:["Imagen, ego, exposición y validación.","Image, ego, exposure and validation."],color:"#9f42c7",questions:["¿Las redes nos hicieron más libres o más necesitados de aprobación?","¿La gente quiere expresarse o quiere ser deseada?","¿Mostrar vulnerabilidad online es autenticidad o estrategia?","¿Qué parte de tu vida se vuelve falsa cuando sabés que puede ser publicada?"]},
  {name:"Moral Hipócrita",emoji:"🎭",desc:["Doble discurso, juicio social y contradicciones.","Double standards, social judgement and contradictions."],color:"#b9414f",questions:["¿La gente juzga más fuerte los defectos que también tiene?","¿Todos somos morales hasta que algo nos conviene demasiado?","¿Qué mentira social repetimos para parecer mejores?","¿Ser buena persona significa actuar bien o querer verse bien?"]},
  {name:"Belleza y Privilegio",emoji:"🪞",desc:["Atractivo físico, poder social y ventaja invisible.","Physical attractiveness, social power and invisible advantage."],color:"#b7831e",questions:["¿La belleza es una forma de poder que la gente no quiere admitir?","¿Una persona atractiva vive la misma realidad que una persona común?","¿La belleza abre puertas o también crea una prisión?","¿La gente confunde belleza con bondad, inteligencia o valor?"]},
  {name:"Fracaso y Vergüenza",emoji:"🕳️",desc:["Perder, sentirse atrás, empezar tarde y no cumplir expectativas.","Losing, feeling behind, starting late and not meeting expectations."],color:"#4b5363",questions:["¿Qué fracaso duele más: el público o el privado?","¿La vergüenza sirve para mejorar o solo paraliza?","¿La gente teme fracasar o teme que otros vean el fracaso?","¿Empezar tarde es realmente tarde o solo parece tarde?"]},
  {name:"Libertad y Control",emoji:"🧠",desc:["Elecciones, disciplina, presión social y autonomía.","Choices, discipline, social pressure and autonomy."],color:"#247dc5",questions:["¿Somos libres o solo elegimos dentro de opciones que otros diseñaron?","¿Qué controlamos menos de lo que creemos?","¿La disciplina te libera o te convierte en prisionero de vos mismo?","¿Cuándo una decisión personal deja de ser personal?"]},
  {name:"Tecnología y Soledad",emoji:"🤖",desc:["IA, intimidad, compañía artificial y vacío moderno.","AI, intimacy, artificial companionship and modern emptiness."],color:"#42707a",questions:["¿La tecnología nos conecta o solo nos distrae de la soledad?","¿Una persona puede sentirse acompañada por una máquina?","¿La inteligencia artificial va a mejorar la intimidad o destruirla?","¿Qué parte humana no debería ser reemplazada nunca?"]},
  {name:"País, Patria y Fanatismo",emoji:"🏳️",desc:["Identidad nacional, orgullo, odio y pertenencia.","National identity, pride, hate and belonging."],color:"#b73b39",questions:["¿El patriotismo une a la gente o la vuelve más fácil de manipular?","¿Qué diferencia hay entre amar tu país y creer que es superior?","¿La identidad nacional es una raíz o una jaula?","¿Cuándo el orgullo cultural se vuelve fanatismo?"]}
];

export const forbiddenBlocks:ForbiddenBlock[]=[
  {name:"La Pregunta que Arruina una Cena",question:"¿Qué verdad social todos conocen, pero nadie dice porque arruinaría la convivencia?",challenge:["Respondé como si estuvieras en una mesa elegante y dijeras algo que incomoda a todos.","Answer as if you were at an elegant dinner saying something that makes everyone uncomfortable."],color:"#303646"},
  {name:"Sexo y Poder",question:"¿El deseo sexual es realmente libre o está más influenciado por poder, belleza, miedo y validación de lo que admitimos?",challenge:["Defendé una postura fuerte y después agregá un matiz.","Defend a strong position and then add nuance."],color:"#a6293e"},
  {name:"La Muerte",question:"Si supieras que te queda un año de vida, ¿qué parte de tu vida actual te parecería inmediatamente absurda?",challenge:["Respondé primero de forma práctica y después de forma emocional.","Answer first in a practical way and then emotionally."],color:"#60305f"},
  {name:"Brasil",question:"¿Brasil es admirado por su cultura o consumido como fantasía por el resto del mundo?",challenge:["Hablá de estereotipo, deseo, desigualdad e imagen internacional sin simplificar.","Discuss stereotype, desire, inequality and international image without oversimplifying."],color:"#a37616"},
  {name:"Amor Prohibido",question:"¿Un amor prohibido revela una verdad profunda o solo convierte el deseo en drama?",challenge:["Respondé desde la emoción y después desde la ética.","Answer from emotion and then from ethics."],color:"#9c3259"},
  {name:"Derechos Humanos",question:"¿Una persona pierde ciertos derechos cuando rompe gravemente las reglas de una sociedad?",challenge:["Defendé una postura difícil sin sonar cruel.","Defend a difficult position without sounding cruel."],color:"#73376b"},
  {name:"Moral Secreta",question:"¿Qué parte de tu moral cambiaría si nadie pudiera juzgarte nunca?",challenge:["Respondé con honestidad brutal, pero con lenguaje elegante.","Answer with brutal honesty but elegant language."],color:"#553d91"}
];

export const powerUps:PowerUp[]=[
  {emoji:"🔥",name:"Fuego de postura",english:"Position fire",phrase:"Mi postura clara es…",translation:"My clear position is…",color:"#ffcc4d"},
  {emoji:"🛡️",name:"Escudo de matiz",english:"Nuance shield",phrase:"Al mismo tiempo, entiendo que…",translation:"At the same time, I understand that…",color:"#65c8ff"},
  {emoji:"⚔️",name:"Espada de contraargumento",english:"Counterargument sword",phrase:"Alguien podría decir lo contrario porque…",translation:"Someone could argue the opposite because…",color:"#65df9a"},
  {emoji:"🧠",name:"Cerebro de análisis",english:"Analysis brain",phrase:"El problema de fondo es…",translation:"The underlying problem is…",color:"#b19aff"},
  {emoji:"🎭",name:"Máscara de contradicción",english:"Contradiction mask",phrase:"La contradicción está en que…",translation:"The contradiction is that…",color:"#ff8fc8"},
  {emoji:"🕳️",name:"Pozo incómodo",english:"Uncomfortable pit",phrase:"Lo que nadie quiere admitir es…",translation:"What nobody wants to admit is…",color:"#ffad69"},
  {emoji:"⚖️",name:"Balanza ética",english:"Ethical balance",phrase:"Éticamente, el problema es…",translation:"Ethically, the problem is…",color:"#ff7878"},
  {emoji:"🚀",name:"Salto final",english:"Final leap",phrase:"Mi conclusión final es…",translation:"My final conclusion is…",color:"#f7e45c"}
];

export const supportPhrases:[string,string][]=[
  ["Desde mi punto de vista…","From my point of view…"],
  ["Por un lado… por otro lado…","On the one hand… on the other hand…"],
  ["No estoy completamente de acuerdo porque…","I don’t completely agree because…"],
  ["Depende mucho de…","It depends a lot on…"],
  ["Un ejemplo claro sería…","A clear example would be…"],
  ["Aunque entiendo esa idea…","Although I understand that idea…"],
  ["La parte más difícil de responder es…","The hardest part to answer is…"],
  ["Necesito pensarlo un segundo.","I need a second to think about it."]
];

export const feedbackLabels:[string,string][]=[["Nivel de fluidez","Fluency level"],["Mejor postura","Best position"],["Frase más fuerte","Strongest phrase"],["Mejor matiz","Best nuance"],["Mejor contraargumento","Best counterargument"],["Tema más incómodo","Most uncomfortable topic"],["Vocabulario nuevo","New vocabulary"],["Error gramatical","Grammar point to improve"],["Frase para reutilizar","Phrase to reuse"],["Próximo tema prohibido","Next forbidden topic"]];
