import type { EliminationC2, AbsurdRuleC2, WorldGuide } from './types';

// Las consecuencias y los cambios de la ciudad son condiciones ficticias del juego.
export const eliminationsC2: EliminationC2[] = [
  {
    id:'c2-maquina-anonimato',title:'Las opiniones sin firma',group:'Lo que promete una etiqueta',
    intro:'La máquina propone eliminar toda opinión anónima: cada valoración tendría que llevar el nombre de quien la expresa.',
    question:'Vota ante una queja sin firma sobre una piscina: ¿qué crees que demostraría conocer el nombre y qué seguiría sin saberse?',
    depthPrompt:'Separa no saber quién habla de no poder pedirle que responda por lo que dice. ¿Tu decisión trata esas dos cosas como equivalentes?',
    consequence:'La piscina publica nombres, pero acepta empresas como autoras. Una vecina aparece identificada; una empresa firma como «Equipo de atención», sin persona responsable.',
    reinterpretation:'La firma existe en ambos casos. ¿Se ha eliminado el anonimato o solo una de sus formas? Revisa qué cuenta como identificación.',
    competingReading:'La empresa sostiene que responde colectivamente; la vecina cree que nadie responde personalmente. Defiende ambas lecturas antes de señalar dónde dejan de ser compatibles.',
    reformulationPrompt:'Sustituye «sin firma» por el rasgo que de verdad te preocupa. Explica a quién se podría pedir una respuesta y cuándo admitirías reservar el nombre.',
    teacherChallenge:'Prueba el criterio con un seudónimo estable y un nombre real que nadie puede verificar.',
    words:['atribuir','responder por','identidad verificable'],starter:'Identificar a alguien no garantiza…, mientras que…',
  },
  {
    id:'c2-maquina-gratis',title:'La palabra «gratis»',group:'Lo que promete una etiqueta',
    intro:'Ningún servicio podrá anunciarse como gratis. La máquina considera que siempre se paga de alguna manera.',
    question:'Una plaza ofrece conciertos sin entrada y una aplicación pide tus datos. ¿Apoyarías borrar la misma palabra en ambos anuncios? Precisa qué has entendido por pagar.',
    depthPrompt:'Distingue un precio, un coste para quien organiza y una renuncia del usuario. ¿Debe todo coste llamarse pago?',
    consequence:'El concierto se anuncia «sin desembolso» y la aplicación «sin dinero». La segunda conserva exactamente la impresión que motivó la eliminación.',
    reinterpretation:'Cambiar la palabra no ha cambiado lo que se sugiere. ¿Eliminarías un término, una omisión relevante o una promesa?',
    competingReading:'Una persona entiende gratis como precio cero; otra, como ausencia de contraprestación. Construye una frase que sea verdadera para la primera y engañosa para la segunda.',
    reformulationPrompt:'Redacta qué afirmación retirarías y qué información debería acompañar a las ofertas. Comprueba que tu versión permita anunciar el concierto.',
    teacherChallenge:'Añade un taller sin coste al que hay que acudir puntualmente: ¿el compromiso de tiempo lo convierte en pago?',
    words:['contraprestación','precio cero','dar a entender'],starter:'La afirmación es cierta en el sentido de…, pero sugiere…',
  },
  {
    id:'c2-maquina-tallas',title:'Las tallas «normales»',group:'Lo que promete una etiqueta',
    intro:'La máquina elimina la categoría de talla normal. Cada tienda tendrá que describir su ropa sin esa etiqueta.',
    question:'En un escaparate lees «normal» y «especial». ¿Qué eliminarías al votar: una medida frecuente, una expectativa sobre los cuerpos o ambas?',
    depthPrompt:'Una talla puede ser estadísticamente frecuente sin ser la talla que alguien debería tener. Explica dónde se introduce ese salto en la conversación.',
    consequence:'La tienda cambia los carteles por «línea habitual» y «otras medidas», pero mantiene las mismas prendas en el escaparate y las demás en un catálogo aparte.',
    reinterpretation:'¿Ha desaparecido la categoría o se reconoce ahora por su ubicación? Explica qué observación permitiría distinguir cambio de nombre y cambio de trato.',
    competingReading:'El dependiente dice que habitual describe sus existencias, no a las personas. Una clienta sostiene que ordenar así las prendas sigue diciéndole quién pertenece. Haz justicia a los dos argumentos.',
    reformulationPrompt:'Propón una eliminación que distinga información útil sobre medidas de una clasificación de clientes. Delimita qué podría seguir describiendo la tienda.',
    teacherChallenge:'Pregunta si habría que borrar también «la talla más vendida» cuando el dato es exacto pero depende de lo que se ofrece.',
    words:['frecuente','expectativa','criterio de clasificación'],starter:'El dato puede ser exacto y, aun así, dejar fuera…',
  },
  {
    id:'c2-maquina-nuevo',title:'La distinción entre nuevo y usado',group:'Lo que promete una etiqueta',
    intro:'Los objetos se venderán describiendo su estado actual. La máquina elimina las categorías nuevo y usado.',
    question:'Una bicicleta de exposición no ha tenido dueño, pero cientos de personas la han probado. ¿Qué información quieres conservar al decidir si borrarías esa distinción?',
    depthPrompt:'¿Clasificas por propietario anterior, desgaste o expectativas de funcionamiento? Elige un caso en que esos criterios produzcan respuestas distintas.',
    consequence:'Una bicicleta reparada queda impecable y otra sin estrenar tiene una pieza envejecida. Ambas anuncian «estado excelente», aunque sus historias permiten prever problemas diferentes.',
    reinterpretation:'Describir el presente no resuelve qué pasado importa. ¿Necesitas recuperar las dos categorías o descomponerlas en datos distintos?',
    competingReading:'Quien vende la reparada dice que juzgar su pasado sería injusto; quien compra afirma que la reparación es información relevante. ¿Pueden tener razón sin estar de acuerdo en el precio?',
    reformulationPrompt:'Reescribe qué clasificación eliminarías y qué historial seguiría visible. Evita usar «como nuevo» para resolver la dificultad que acabas de señalar.',
    teacherChallenge:'Introduce un libro con una dedicatoria valiosa: la misma huella de uso puede aumentar o reducir su valor.',
    words:['desgaste','historial','estado actual'],starter:'Bajo una sola etiqueta estamos mezclando…',
  },
  {
    id:'c2-maquina-autenticidad',title:'La exigencia de comida «auténtica»',group:'Lo que promete una etiqueta',
    intro:'La máquina elimina la exigencia de que una comida sea auténtica. Los platos podrán presentarse por sus ingredientes y su historia.',
    question:'Una cocinera cambia una receta que aprendió en casa y le dicen que ya no es auténtica. ¿Respaldas la eliminación? Aclara quién tendría autoridad para fijar la versión de referencia.',
    depthPrompt:'Compara fidelidad a una receta concreta, pertenencia a una tradición y sinceridad al contar el origen. ¿Cuál de ellas estás defendiendo?',
    consequence:'Un restaurante anuncia «la receta de mi abuela», aunque modifica varios ingredientes. La abuela confirma que ella también la cambiaba según lo que encontraba.',
    reinterpretation:'¿Ser fiel a esa abuela exigiría repetir sus ingredientes o su manera de adaptarse? Identifica qué versión de autenticidad sostendría cada respuesta.',
    competingReading:'Una comensal quería reconocer un sabor; otra celebra que una tradición siga viva. Ninguna exige engañar. Explica por qué discrepan sin reducirlo a apertura frente a nostalgia.',
    reformulationPrompt:'Formula qué pretensión excluirías del menú y cómo presentarías el plato sin prometer una única tradición ni borrar su procedencia.',
    teacherChallenge:'Pide una frase de menú suficientemente breve que comunique el cambio sin convertir la cena en una explicación histórica.',
    words:['versión de referencia','procedencia','fidelidad'],starter:'Ser fiel a… podría consistir en…, no necesariamente en…',
  },
  {
    id:'c2-maquina-lujo',title:'La categoría «lujo»',group:'Lo que promete una etiqueta',
    intro:'La máquina eliminará los bienes de lujo. Te pide aprobar primero la idea y precisar después qué objetos incluye.',
    question:'Una silla cuesta mucho porque está adaptada a una sola persona; otra, porque solo se fabricaron diez. ¿Votarías igual antes de conocer la razón del precio?',
    depthPrompt:'Separa lo caro, lo prescindible y lo exclusivo. ¿Qué criterio convierte un objeto en lujo, y para quién?',
    consequence:'La máquina fija un precio máximo. Desaparecen las dos sillas; la marca exclusiva divide el cobro entre asiento, respaldo y membresía, y vuelve a vender la suya.',
    reinterpretation:'El objeto no cambió, pero dejó de caer dentro de la definición. ¿Has eliminado el lujo o una forma de cobrarlo?',
    competingReading:'Una persona llama lujo a todo privilegio de acceso; otra, al exceso material. Demuestra que podrían apoyar medidas opuestas sobre una silla y compartir el mismo principio.',
    reformulationPrompt:'Delimita la práctica que eliminarías sin clasificar una necesidad individual por su precio. Pon una condición que no desaparezca al dividir la factura.',
    teacherChallenge:'Prueba la formulación con un objeto barato al que solo pueden acceder los miembros de un club.',
    words:['exclusividad','prescindible','criterio indirecto'],starter:'El precio sirve como pista de…, pero no define…',
  },
  {
    id:'c2-maquina-retoricas',title:'Las preguntas que no preguntan',group:'Lo que hacemos al hablar',
    intro:'Se eliminan las preguntas formuladas sin querer recibir información. Cada pregunta tendrá que expresar una duda real.',
    question:'Escuchas «¿Te parece normal dejar esto así?» ante una cocina sucia. ¿Eliminarías ese uso? Explica qué acción realiza la frase además de preguntar.',
    depthPrompt:'No conocer la respuesta y querer escucharla no siempre coinciden. ¿Tu criterio depende de la intención del hablante o del espacio que da para responder?',
    consequence:'La persona cambia la frase por «Quiero saber si te parece normal», pero interrumpe cualquier explicación. Otra pregunta «¿Quieres agua?» sabiendo que la respuesta será sí y queda bloqueada.',
    reinterpretation:'La máquina vigila la forma o la duda, mientras el problema quizá sea que una respuesta no cuenta. ¿Qué has puesto dentro de la misma categoría?',
    competingReading:'La primera frase puede pedir explicaciones o comunicar una acusación. Representa los dos usos con el mismo texto y señala qué cambia en el intercambio.',
    reformulationPrompt:'Reformula la eliminación atendiendo a lo que se permite hacer al interlocutor. Conserva un uso cotidiano de preguntas cuya respuesta ya se sospecha.',
    teacherChallenge:'Introduce «¿Cómo no voy a ayudarte?» y pide interpretar su compromiso sin tratarla como una consulta literal.',
    words:['acto de habla','dar pie','respuesta prevista'],starter:'La frase tiene forma de…, pero aquí funciona como…',
  },
  {
    id:'c2-maquina-eufemismos',title:'Las palabras que suavizan',group:'Lo que hacemos al hablar',
    intro:'La máquina elimina los eufemismos para que nadie disfrace una noticia incómoda.',
    question:'Un taller habla de «un pequeño ajuste» para una reparación cara. ¿Qué eliminarías exactamente: la cortesía, la imprecisión o el intento de reducir tu alarma?',
    depthPrompt:'Una palabra directa también puede minimizar: «solo es una avería». Explica qué hace engañosa una formulación sin depender de una lista de términos prohibidos.',
    consequence:'El taller sustituye «ajuste» por «reparación», pero sigue ocultando el precio hasta el final. En otra conversación, una amiga pierde una manera delicada de contar una pérdida.',
    reinterpretation:'El nombre más directo no ha aclarado la decisión del cliente. ¿Qué dato o inferencia debía quedar accesible?',
    competingReading:'Una persona considera que suavizar facilita escuchar; otra cree que condiciona la reacción antes de informar. Formula un caso en que ambas describan correctamente la misma frase.',
    reformulationPrompt:'Reescribe la propuesta para separar tacto y ocultación. Di qué tendría que poder comprender o preguntar quien recibe la noticia.',
    teacherChallenge:'Pide comunicar un retraso grave con claridad y delicadeza, sin imponer una emoción a quien lo escucha.',
    words:['atenuar','minimizar','información decisiva'],starter:'La suavidad no sería el problema si quedara claro…',
  },
  {
    id:'c2-maquina-advertencias',title:'Los avisos «por si acaso»',group:'Lo que hacemos al hablar',
    intro:'Desaparecen las advertencias sobre riesgos que quien habla no puede demostrar. La máquina quiere evitar alarmas sin fundamento.',
    question:'Antes de una excursión alguien dice «por si acaso, lleva otra capa». ¿Apoyarías eliminar ese aviso? Distingue no tener una prueba de no tener ninguna razón.',
    depthPrompt:'Precisa qué compromiso asume quien advierte: ¿predice lo que ocurrirá, señala una posibilidad o recomienda una precaución barata?',
    consequence:'Nadie anuncia que lloverá. Una persona dice «yo llevaré un abrigo» mirando al resto; el grupo lo interpreta como aviso y prepara exactamente lo mismo.',
    reinterpretation:'El aviso ha pasado de afirmación a insinuación. ¿Importa más la forma explícita o la interpretación razonablemente previsible?',
    competingReading:'Quien habla niega haber recomendado nada; quien escucha cree que la mirada daba sentido a la frase. Expón la mejor evidencia para cada lectura sin inventar certeza.',
    reformulationPrompt:'Delimita qué aviso retirarías y qué grados de incertidumbre permitirías expresar. Indica una evidencia que cambiaría tu decisión.',
    teacherChallenge:'Compara una precaución fácil de deshacer con otra que obligue a cancelar todo el viaje.',
    words:['precaución','grado de certeza','insinuar'],starter:'No afirmaría que vaya a…, pero sí que hay razones para…',
  },
  {
    id:'c2-maquina-consejos',title:'Los consejos no pedidos',group:'Lo que hacemos al hablar',
    intro:'La máquina elimina cualquier consejo que no se haya solicitado expresamente.',
    question:'Cuentas que tu planta se está secando y una amiga propone cambiarla de sitio. ¿Eliminarías su intervención? Explica qué podría haber solicitado tu relato sin decir «dame un consejo».',
    depthPrompt:'Compara contar un problema, pedir compañía y abrir una consulta. ¿Qué señales permiten distinguirlos sin dar por supuesta la intención?',
    consequence:'Tu amiga pregunta «¿Quieres que opine?» en cada conversación. Aceptas por educación, aunque querías terminar de contar lo ocurrido; el consejo pasa ahora el filtro.',
    reinterpretation:'Tener una autorización verbal no resuelve qué espacio había para negarla. ¿La categoría pedida/no pedida describe bien lo que querías cambiar?',
    competingReading:'La pregunta previa puede ser una salida respetuosa o una interrupción que obliga a negociar. Representa dos escenas donde las mismas palabras tengan esos efectos.',
    reformulationPrompt:'Reescribe la condición para ofrecer ayuda sin interpretar automáticamente un problema como una petición. Explica cómo se podría retirar una invitación a opinar.',
    teacherChallenge:'Añade una advertencia inmediata sobre una maceta a punto de caer y comprueba si es el mismo tipo de intervención.',
    words:['solicitud implícita','dar espacio','retirar el permiso'],starter:'Tomé el relato como una petición, pero esa lectura depende de…',
  },
  {
    id:'c2-maquina-comparaciones',title:'Las comparaciones entre personas',group:'Lo que hacemos al hablar',
    intro:'La máquina elimina las comparaciones entre personas para que nadie sea medido con la vida de otro.',
    question:'Una profesora dice «ahora explicas esto tan claro como tu compañero». ¿Qué borrarías al votar: una jerarquía, un ejemplo o cualquier referencia compartida?',
    depthPrompt:'Distingue comparar una actuación y equiparar a dos personas. ¿En qué momento una observación limitada parece convertirse en un juicio global?',
    consequence:'La profesora evita nombres y muestra «una respuesta modelo». Todo el grupo reconoce quién la escribió y la comparación sigue presente, aunque nadie la pronuncia.',
    reinterpretation:'¿Desapareció la comparación o se volvió imposible discutir sus términos? Señala quién controla ahora la referencia.',
    competingReading:'Una alumna encuentra útil saber qué significa claridad; otra oye que solo hay una manera válida de expresarse. ¿Qué parte de cada lectura permite el mismo ejemplo?',
    reformulationPrompt:'Formula qué inferencia impedirías, no solo qué palabras quitarías. Conserva una manera de aprender de otra persona sin convertirla en medida universal.',
    teacherChallenge:'Pide un comentario sobre dos explicaciones igualmente eficaces con estilos muy distintos.',
    words:['referencia','juicio global','criterio compartido'],starter:'Comparar en relación con… no permite concluir que…',
  },
  {
    id:'c2-maquina-absolutos',title:'El «siempre» de las discusiones',group:'Lo que hacemos al hablar',
    intro:'La máquina elimina siempre y nunca cuando no describen literalmente todos los casos.',
    question:'Tu compañero de piso dice «nunca recoges la mesa» y recuerdas dos veces que sí lo hiciste. ¿Eliminarías su frase? Explica qué refuta tu respuesta y qué reclamación podría seguir en pie.',
    depthPrompt:'Separa exactitud del cuantificador y frecuencia relevante. ¿Puede una objeción técnicamente correcta evitar responder al problema?',
    consequence:'El compañero cambia la frase por «recoges menos del 40 % de las veces». La conversación se atasca en qué comidas cuentan; nadie recoge la mesa de hoy.',
    reinterpretation:'La precisión numérica ha trasladado la disputa al denominador. ¿Qué compromiso compartido faltaba antes y después del cambio?',
    competingReading:'«Nunca» puede presentar una acusación absoluta o intensificar una queja acumulada. Da una respuesta que no acepte la exageración ni finja desconocer la queja.',
    reformulationPrompt:'Reescribe la eliminación para separar exageración revisable y acusación que niega cualquier contraejemplo. Explica cuándo mantendrías el voto inicial.',
    teacherChallenge:'Introduce «siempre puedes pedirme ayuda» y pregunta si la expresión ofrece disponibilidad o una garantía sin excepciones.',
    words:['contraejemplo','frecuencia','eludir el fondo'],starter:'Ese ejemplo corrige la palabra…, pero no responde todavía a…',
  },
  {
    id:'c2-maquina-anfitriones',title:'La separación entre anfitrión e invitado',group:'Las relaciones que damos por hechas',
    intro:'En las reuniones en casa desaparecerá la distinción entre anfitrión e invitado. Todo el mundo participará en igualdad.',
    question:'Te invitan a cenar y encuentras un reparto de limpieza en la puerta. ¿Apoyas la eliminación? Explica qué igualdad crees que se ha prometido.',
    depthPrompt:'¿Tener las mismas tareas implica tener la misma capacidad para decidir el menú, la hora y quién vuelve? Distingue participación de autoridad.',
    consequence:'Todos lavan platos, pero la persona que vive allí conserva la llave y decide cuándo termina la cena. Un invitado reorganiza la cocina alegando igualdad.',
    reinterpretation:'La distinción era una mezcla de carga, control y cuidado. ¿Qué parte puede desaparecer sin fingir que nadie está en su propia casa?',
    competingReading:'Una persona entiende «como en tu casa» como permiso para relajarse; otra, como invitación a colaborar. Haz compatibles esas lecturas fijando un límite.',
    reformulationPrompt:'Reescribe qué asimetría eliminarías y qué responsabilidad seguiría teniendo quien invita. Prueba la propuesta con alguien que viene por primera vez.',
    teacherChallenge:'Pide resolver la escena de la cocina sin usar «igualdad» como respuesta suficiente.',
    words:['asimetría','capacidad de decidir','hospitalidad'],starter:'Compartir la tarea no equivale a compartir…',
  },
  {
    id:'c2-maquina-deudas',title:'Las deudas de gratitud',group:'Las relaciones que damos por hechas',
    intro:'La máquina elimina la obligación de devolver favores. Agradecer no generará ninguna deuda.',
    question:'Un amigo te recuerda que te ayudó a mudarte cuando te pide cuidar su gato. ¿Eliminarías esa relación entre los favores? Distingue un recordatorio del vínculo y una factura encubierta.',
    depthPrompt:'Si nadie promete devolver nada, ¿puede existir una expectativa razonable de reciprocidad? Explica qué la haría revisable.',
    consequence:'El amigo deja de mencionar la mudanza y dice «pensaba que podía contar contigo». No reclama la misma tarea, pero tu negativa vuelve a presentarse como deslealtad.',
    reinterpretation:'La deuda ha perdido su unidad de medida y quizá resulte más difícil saldarla. ¿Qué eliminarías: la contabilidad o la imposibilidad de negarse?',
    competingReading:'Para uno, contar con alguien significa poder pedir; para otro, poder esperar un sí. Defiende la interpretación más generosa de cada uno antes de marcar el límite.',
    reformulationPrompt:'Formula una propuesta que permita reconocer un desequilibrio sin convertir cada ayuda pasada en un derecho sobre el tiempo futuro.',
    teacherChallenge:'Prueba el principio cuando siempre ayuda la misma persona: reconocer presión no obliga a negar el desequilibrio.',
    words:['reciprocidad','expectativa revisable','saldar'],starter:'Agradecer reconoce lo recibido; comprometerse a… añade…',
  },
  {
    id:'c2-maquina-despedidas',title:'Las despedidas obligatorias',group:'Las relaciones que damos por hechas',
    intro:'Nadie tendrá que despedirse antes de salir de un encuentro. La máquina elimina ese requisito de cortesía.',
    question:'Sales de una fiesta sin avisar y alguien empieza a buscarte. ¿Mantendrías la eliminación? Aclara qué diferencia hay entre pedir permiso para irse y comunicar que ya te has ido.',
    depthPrompt:'La despedida puede cerrar una conversación, coordinar un regreso o pedir reconocimiento. ¿Qué función has convertido en obligación?',
    consequence:'Los asistentes activan avisos automáticos al cruzar la puerta. Todo el mundo sabe quién se fue, pero una conversación queda a medias y sus participantes no saben si continúa.',
    reinterpretation:'Saber dónde está alguien no aclara el estado de una conversación. ¿Eliminaste un ritual o el acuerdo sobre cuándo termina un intercambio?',
    competingReading:'«Me voy» puede ser información suficiente o una ruptura abrupta según lo que estaba ocurriendo. Explica qué expectativa previa hace cambiar la lectura.',
    reformulationPrompt:'Define qué obligación retirarías y qué cierre mínimo conservarías cuando haya una tarea o conversación compartida.',
    teacherChallenge:'Incluye a alguien que necesita salir deprisa y puede explicar después su ausencia sin pedir autorización.',
    words:['dar por cerrado','coordinar','expectativa previa'],starter:'No tendría que pedir permiso para…, aunque sí aclarar…',
  },
  {
    id:'c2-maquina-charlas',title:'Las conversaciones «sin contenido»',group:'Las relaciones que damos por hechas',
    intro:'La máquina elimina las conversaciones que no aportan información nueva: comentarios del tiempo, saludos repetidos y preguntas de rutina.',
    question:'El panadero te dice «hoy sí que llueve» cuando llegas tan mojado como él. ¿Borrarías la frase? Explica qué cambia en la relación aunque nadie aprenda un dato.',
    depthPrompt:'Si una frase comprueba que se puede iniciar contacto, ¿eso cuenta como información? Delimita el término sin convertir cualquier sonido en contenido.',
    consequence:'La máquina permite «¿Tienes tiempo para hablar?», porque puede recibir una respuesta nueva. Cada saludo se convierte en una solicitud explícita y parece más exigente.',
    reinterpretation:'Hacer explícita la función cambia su intensidad. ¿Puedes sustituir una charla ligera por una pregunta directa sin alterar lo que se está ofreciendo?',
    competingReading:'Una vecina agradece no tener que fingir interés; otra agradecía poder hablar sin comprometerse a seguir. Explica la libertad que cada una encontraba en la misma costumbre.',
    reformulationPrompt:'Reescribe qué conversación eliminarías atendiendo a la posibilidad de salir de ella, y conserva una entrada al contacto que no exija confidencias.',
    teacherChallenge:'Pide un saludo de ascensor que ofrezca conversación y admita con naturalidad una respuesta mínima.',
    words:['abrir contacto','compromiso conversacional','respuesta mínima'],starter:'Aunque no añade un dato, permite comprobar…',
  },
  {
    id:'c2-maquina-excusas',title:'Las excusas',group:'Las relaciones que damos por hechas',
    intro:'La máquina elimina las excusas. Para rechazar un plan o justificar un fallo habrá que dar la razón real.',
    question:'Una amiga dice «no puedo ir» cuando está agotada pero podría salir físicamente. ¿Votarías por eliminar esa frase? Precisa qué imposibilidad crees que afirma.',
    depthPrompt:'Distingue explicar una limitación, pedir que se acepte y fabricar una causa falsa. ¿En qué sentido usas excusa?',
    consequence:'La amiga cuenta que necesita descansar. Le responden que una cena tranquila también ayuda a descansar; ahora tiene que demostrar que su motivo es suficiente.',
    reinterpretation:'La supuesta sinceridad ha convertido una decisión en un caso que otros autorizan. ¿Qué parte del rechazo necesita realmente una prueba?',
    competingReading:'«No puedo» puede ocultar falta de interés o comunicar un límite sin exponer intimidad. Explica qué se puede inferir de la frase sola y qué no.',
    reformulationPrompt:'Redefine la eliminación de modo que distinga engañar sobre un compromiso incumplido y reservar las razones de una negativa.',
    teacherChallenge:'Contrasta rechazar una invitación nueva con faltar a una tarea ya aceptada; aplica el mismo principio y explica la diferencia.',
    words:['limitación','dar por válida','razón reservada'],starter:'La frase no revela…, pero tampoco permite concluir…',
  },
  {
    id:'c2-maquina-nostalgia',title:'La nostalgia',group:'Las relaciones que damos por hechas',
    intro:'La máquina elimina la nostalgia para que el pasado deje de parecer mejor de lo que fue.',
    question:'Una canción te devuelve a un verano difícil que recuerdas con cariño. ¿Eliminarías esa experiencia? Explica si añorar algo equivale a afirmar que entonces se vivía mejor.',
    depthPrompt:'Separa deseo de volver, afecto por una etapa y juicio sobre sus condiciones. Busca dos de ellos que puedan coexistir sin el tercero.',
    consequence:'La canción ya no provoca añoranza, pero sigues defendiendo que antes todo era mejor: esa creencia se ha conservado porque no necesita una emoción nostálgica.',
    reinterpretation:'Has quitado una experiencia sin quitar la afirmación que te preocupaba. ¿Confundiste el origen posible de un argumento con su contenido?',
    competingReading:'Una persona dice «echo de menos aquella época» y no quiere recuperarla; otra lo interpreta como rechazo del presente. Explica qué información haría razonable cada lectura.',
    reformulationPrompt:'Precisa qué uso del pasado eliminarías y qué afecto conservarías. Incluye una forma de recordar un beneficio sin borrar lo que entonces iba mal.',
    teacherChallenge:'Pide defender un objeto antiguo por una cualidad comprobable sin tratar toda preferencia por el pasado como nostalgia.',
    words:['añoranza','idealizar','juicio retrospectivo'],starter:'Puedo echar de menos… sin sostener que…',
  },
  {
    id:'c2-maquina-metricas',title:'Las medidas de productividad',group:'Quién decide qué cuenta',
    intro:'La máquina elimina cualquier cifra usada para decir cuánto rinde una persona en el trabajo.',
    question:'Un taller cuenta piezas terminadas y otro cuenta problemas evitados. ¿Eliminarías ambas medidas? Explica qué diferencia hay entre registrar actividad y definir con ella el buen trabajo.',
    depthPrompt:'¿Deja una cifra de ser una medida de productividad cuando se llama información orientativa? Señala el uso concreto que decide tu voto.',
    consequence:'Se retiran las cifras del informe. El responsable sigue asignando turnos según quién termina más rápido y llama a esa comparación «impresión general».',
    reinterpretation:'Ya no hay una medida visible, pero sí una regla para repartir oportunidades. ¿Has eliminado la evaluación o la posibilidad de discutir cómo funciona?',
    competingReading:'Una trabajadora quiere que cuenten las piezas porque la impresión la perjudica; otra quiere que ninguna cifra defina su contribución. Formula una propuesta que reconozca ambas razones.',
    reformulationPrompt:'Cambia el objeto de la eliminación: distingue recoger un dato, interpretarlo y usarlo para decidir. Precisa en qué paso exigirías una explicación adicional.',
    teacherChallenge:'Pide qué evidencia mostraría que una medida orienta la conversación sin sustituirla.',
    words:['indicador','criterio de decisión','contribución'],starter:'El número describe…, pero la decisión añade el supuesto de que…',
  },
  {
    id:'c2-maquina-cargos',title:'Los títulos de los puestos',group:'Quién decide qué cuenta',
    intro:'Desaparecen los nombres de los cargos. En cada trabajo solo se describirá lo que hace cada persona.',
    question:'Dos personas organizan horarios, pero solo una puede cambiarlos sin pedir permiso. ¿Borrarías sus cargos? Explica qué oculta una descripción idéntica de tareas.',
    depthPrompt:'Separa hacer, autorizar y responder por una decisión. ¿Qué parte de un cargo es información y qué parte funciona como prestigio?',
    consequence:'Las firmas de correo enumeran tareas. La persona con autoridad se presenta como «quien da el visto bueno» y su descripción empieza a usarse como nuevo título.',
    reinterpretation:'¿Los cargos han reaparecido inevitablemente o solo has conservado una jerarquía que necesita nombrarse? No confundas ambas afirmaciones.',
    competingReading:'Una compañera considera que poner nombre al poder permite cuestionarlo; otra cree que el nombre lo vuelve natural. Explica cómo las dos cosas podrían ocurrir a la vez.',
    reformulationPrompt:'Reformula qué privilegio del título retirarías y qué responsabilidad tendría que seguir siendo fácil de identificar.',
    teacherChallenge:'Prueba la versión con una persona que tiene muchas responsabilidades y ninguna capacidad de autorizar gastos.',
    words:['autoridad','rendir cuentas','descripción de tareas'],starter:'Que haga… no significa que pueda decidir…',
  },
  {
    id:'c2-maquina-voluntario',title:'El trabajo «voluntario»',group:'Quién decide qué cuenta',
    intro:'La máquina eliminará las tareas llamadas voluntarias cuando no puedas rechazarlas libremente.',
    question:'En tu club nadie obliga a montar el escenario, pero quienes no ayudan quedan fuera de la siguiente actuación. ¿Aprobarías la eliminación? Define qué consecuencia vuelve obligatoria una tarea.',
    depthPrompt:'Toda elección puede tener consecuencias. Distingue perder una oportunidad ligada a la tarea de sufrir una penalización por negarte.',
    consequence:'El club deja de pedir ayuda y anuncia que solo actúan quienes forman parte del «equipo de montaje y música». La misma exigencia pasa a definir quién es miembro.',
    reinterpretation:'La obligación ya no se impone a los socios: selecciona quién puede serlo. ¿Es una diferencia relevante o un cambio de frontera?',
    competingReading:'El club describe un proyecto compartido; un músico describe una tarea añadida después de entrar. Explica cómo la historia del acuerdo altera la lectura sin cambiar el trabajo.',
    reformulationPrompt:'Reescribe qué condición eliminarías distinguiendo ingreso, permanencia y cambios posteriores. Di qué tendría que saberse antes de aceptar.',
    teacherChallenge:'Introduce a un grupo creado desde el principio para construir y tocar juntos; comprueba que no borres su propio propósito.',
    words:['condición de entrada','penalización','consentimiento previo'],starter:'Aceptar participar en… no equivale a aceptar después…',
  },
  {
    id:'c2-maquina-urgente',title:'La etiqueta «urgente»',group:'Quién decide qué cuenta',
    intro:'La máquina elimina la palabra urgente de mensajes y encargos para que cada petición explique su plazo.',
    question:'Recibes «lo necesito antes de las cinco», pero no sabes qué ocurre si llega mañana. ¿Apoyarías eliminar la etiqueta? Distingue una fecha deseada de una necesidad que desplaza otras.',
    depthPrompt:'Algo puede ser urgente para quien pide y poco importante para quien recibe. ¿Quién puede convertir su prisa en una prioridad compartida?',
    consequence:'Los mensajes llevan plazos cada vez más cortos. Como ninguno dice urgente, el equipo atiende primero al que fija la hora más cercana, aunque no haya ninguna consecuencia real.',
    reinterpretation:'La prioridad ha reaparecido en el plazo. ¿Borrar una etiqueta resolvía el modo de decidir o solo obligaba a expresarlo de otra manera?',
    competingReading:'«Antes de las cinco» puede informar de un límite externo o intentar crear uno. Explica qué pregunta permitiría distinguirlos sin acusar de entrada a quien lo escribió.',
    reformulationPrompt:'Redacta qué uso de la urgencia eliminarías y qué razón tendría que darse para interrumpir una tarea acordada.',
    teacherChallenge:'Introduce un plazo que se perdió por un error propio, pero cuya consecuencia ahora afecta a otra persona.',
    words:['plazo deseado','prioridad compartida','límite externo'],starter:'La hora indica cuándo lo quiere; falta saber…',
  },
  {
    id:'c2-maquina-experiencia',title:'Los años como prueba de experiencia',group:'Quién decide qué cuenta',
    intro:'La máquina elimina los años de experiencia como requisito para acceder a una actividad o un puesto.',
    question:'Alguien ha hecho la misma tarea diez años; otra persona ha resuelto diez situaciones diferentes en uno. ¿Eliminarías el requisito? Explica qué crees que cuentan esos años.',
    depthPrompt:'Distingue tiempo transcurrido, variedad de situaciones y aprendizaje demostrado. ¿Qué función de la experiencia no cabe en una prueba breve?',
    consequence:'Una escuela de baile pide «haber vivido muchas temporadas completas». No solicita un número de años, pero rechaza exactamente a las mismas personas que antes.',
    reinterpretation:'¿La nueva expresión describe otra capacidad o permite mantener el filtro sin reconocerlo? Señala qué evidencia permitiría decidir.',
    competingReading:'Quien selecciona valora haber visto cambios lentos; quien solicita dice que repetir temporadas no prueba haberlos entendido. Refuerza ambos argumentos antes de proponer una comprobación.',
    reformulationPrompt:'Sustituye la eliminación general por una distinción entre tiempo relevante y tiempo usado como atajo. Precisa un caso en que conservarías una duración mínima.',
    teacherChallenge:'Pide una forma de reconocer aprendizaje informal sin suponer que una buena presentación demuestra toda la capacidad.',
    words:['trayectoria','duración relevante','indicio'],starter:'Los años aportan un indicio de…, que habría que contrastar con…',
  },
  {
    id:'c2-maquina-errores',title:'Los errores del expediente',group:'Quién decide qué cuenta',
    intro:'La máquina borra del historial de una persona cualquier error ya corregido.',
    question:'Una camarera corrigió un cobro y una aprendiz repitió bien una tarea. ¿Eliminarías ambos registros? Precisa cuándo un error puede darse por corregido.',
    depthPrompt:'Separa reparar el resultado, aprender a no repetirlo y recuperar la confianza. ¿Cuál de esas cosas exigiría tu decisión?',
    consequence:'El historial queda limpio tras cada reparación. Un mismo error aparece como si fuera nuevo cada semana, mientras una equivocación difícil de reparar permanece para siempre.',
    reinterpretation:'Tu definición confunde cierre de un caso con ausencia de patrón. ¿Qué unidad debería mirar la máquina: el hecho aislado o la repetición?',
    competingReading:'Una persona pide poder empezar de cero; otra necesita reconocer un problema recurrente. Explica por qué conservar información y castigar indefinidamente no son la misma decisión.',
    reformulationPrompt:'Redacta qué uso del historial eliminarías, qué dato conservarías y cuándo dejaría de ser pertinente. Justifica qué significa corregido en tu versión.',
    teacherChallenge:'Añade un registro equivocado sobre un hecho que nunca ocurrió: ¿se corrige del mismo modo que una conducta real?',
    words:['reparación','patrón','pertinencia'],starter:'Cerrar aquel episodio no permite dar por resuelto…',
  },
  {
    id:'c2-maquina-colas',title:'Las colas invisibles',group:'Espacios, objetos y memoria',
    intro:'La máquina elimina las colas que no se ven: listas de espera, números de turno y salas virtuales. Promete que nadie volverá a esperar sin saber con quién comparte la espera.',
    question:'Te asignan el número treinta, pero puedes irte a pasear. ¿Eliminarías esa cola? Define si una cola es gente en fila, un orden de acceso o una espera.',
    depthPrompt:'Si no hay suficientes plazas, quitar el orden no quita necesariamente la demora. ¿Qué problema estaba resolviendo tu voto?',
    consequence:'La web abre reservas sin lista. Quien actualiza la pantalla más veces consigue entrar; esa repetición no aparece registrada como espera.',
    reinterpretation:'La cola desapareció del sistema, pero el tiempo invertido sigue repartiendo plazas. ¿Llamarías a eso otra cola o necesitas un concepto distinto?',
    competingReading:'Una persona prefiere un orden visible aunque sea lento; otra teme que aceptar el número legitime cualquier demora. Explica qué parte del acceso juzga cada una.',
    reformulationPrompt:'Delimita lo que eliminarías: opacidad, espera sin límite o un mecanismo de orden. Formula una condición verificable sin prometer acceso inmediato.',
    teacherChallenge:'Introduce a alguien que puede esperar muchas horas pero no permanecer junto a una pantalla.',
    words:['orden de acceso','demora','espera no registrada'],starter:'Desaparece la fila, pero sigue operando…',
  },
  {
    id:'c2-maquina-perdidos',title:'La propiedad de lo perdido',group:'Espacios, objetos y memoria',
    intro:'La máquina elimina la propiedad de cualquier objeto que su dueño haya perdido. Quien lo encuentre podrá usarlo.',
    question:'Encuentras un paraguas en una cafetería. ¿Aprobarías la eliminación? Explica qué distingue algo perdido de algo temporalmente fuera del alcance de su dueño.',
    depthPrompt:'La persona puede ignorar dónde está el objeto sin haber renunciado a él. ¿Qué hecho permitiría a otra persona decidir que ya no tiene dueño?',
    consequence:'Quien olvidó el paraguas recuerda el sitio antes de volver. Quien lo encontró lo llamó abandonado y empezó a usarlo; ambos creen que el estado del objeto cambió en un momento distinto.',
    reinterpretation:'¿La categoría describe el conocimiento del dueño, la apariencia para quien encuentra o una renuncia? Elige cuál debería tener efecto y por qué.',
    competingReading:'Un cartel dice «objetos sin recoger». Para el café significa pendientes de devolución; para un visitante, disponibles. Explica cómo corregirías la inferencia sin culparlo por leer literalmente.',
    reformulationPrompt:'Reformula la eliminación usando una condición que pueda comunicarse a quienes no conocen la intención del dueño. Reconoce qué incertidumbre seguiría abierta.',
    teacherChallenge:'Contrasta un paraguas sin nombre y una libreta cuyo valor solo reconoce quien la escribió.',
    words:['renuncia','custodia','conocimiento ajeno'],starter:'Que nadie lo reclame todavía no demuestra…',
  },
  {
    id:'c2-maquina-vacios',title:'Los espacios «sin uso»',group:'Espacios, objetos y memoria',
    intro:'La máquina elimina el derecho a mantener espacios sin uso: cualquier rincón vacío pasará a estar disponible para otra actividad.',
    question:'Una plaza conserva una zona despejada donde la gente se detiene sin hacer nada. ¿La incluirías en la eliminación? Define qué señales convierten la disponibilidad en un uso.',
    depthPrompt:'Distingue vacío, inactividad y reserva de una posibilidad. ¿La ausencia de una actividad programada demuestra que sobra el espacio?',
    consequence:'La zona se llena de mesas. Para recuperar un lugar donde no consumir, vecinos organizan «sesiones de no hacer nada» con inscripción; solo así se reconoce su uso.',
    reinterpretation:'Tu criterio obliga a convertir el descanso espontáneo en actividad oficial. ¿Eso protege la misma experiencia o crea otra distinta?',
    competingReading:'Una persona ve desaprovechamiento donde otra ve libertad de decidir al llegar. Da un caso defendible de cada lectura sin hacerlas universales.',
    reformulationPrompt:'Reescribe qué abandono eliminarías y cómo distinguirlo de una disponibilidad deliberada sin exigir que cada minuto quede ocupado.',
    teacherChallenge:'Prueba la distinción con un escenario vacío entre funciones y una pista cerrada todo el año sin explicación.',
    words:['disponibilidad','ocupación','posibilidad abierta'],starter:'No estar ocupado puede cumplir la función de…',
  },
  {
    id:'c2-maquina-versiones',title:'Las versiones antiguas de una historia',group:'Espacios, objetos y memoria',
    intro:'Cuando alguien corrige una historia sobre su vida, la máquina elimina las versiones anteriores. Solo queda la que esa persona reconoce ahora.',
    question:'Una amiga dice que un viaje que describía como maravilloso fue en realidad incómodo. ¿Borrarías su relato anterior? Distingue corregir un dato y reinterpretar una experiencia.',
    depthPrompt:'¿Dos relatos pueden ser sinceros y diferentes sin que uno sea un error? Explica qué cambia: los hechos, el recuerdo o el sentido que se les da.',
    consequence:'Se borra la primera versión de la amiga, pero no la del compañero de viaje, que todavía la recuerda encantada. La máquina conserva relatos incompatibles porque pertenecen a autores distintos.',
    reinterpretation:'La coherencia dentro de cada biografía produce desacuerdo entre biografías. ¿Quién tendría autoridad para decidir qué versión cuenta como corrección?',
    competingReading:'El compañero aporta una observación real; la amiga describe cómo vivió algo que no dijo entonces. Explica qué puede confirmar cada relato y qué no puede desmentir por sí solo.',
    reformulationPrompt:'Precisa qué uso de una versión anterior eliminarías y cómo señalarías una reinterpretación sin presentarla como prueba de mentira.',
    teacherChallenge:'Introduce un detalle comprobable, como la fecha del viaje, y exige distinguirlo de cómo se sintió cada persona.',
    words:['reinterpretación','testimonio','coexistir'],starter:'Ambas versiones pueden sostenerse si distinguimos…',
  },
  {
    id:'c2-maquina-records',title:'Los récords',group:'Espacios, objetos y memoria',
    intro:'La máquina elimina todos los récords: nadie podrá declarar que una marca es la mejor de la historia.',
    question:'Una nadadora mejora una marca con una piscina y un equipo distintos. ¿Eliminarías el récord? Explica qué condiciones deben mantenerse para que mejor signifique lo mismo.',
    depthPrompt:'Distingue resultado medido, dificultad de lograrlo y valor deportivo. ¿Tu comparación los está haciendo coincidir sin justificarlo?',
    consequence:'Los resultados siguen archivados. Un comentarista ordena las marcas y anuncia «nadie terminó en menos tiempo», aunque evita la palabra récord.',
    reinterpretation:'La clasificación persiste porque los datos permiten reconstruirla. ¿Eliminarías una palabra, la pretensión de equivalencia o la propia posibilidad de comparar?',
    competingReading:'La frase del comentarista es numéricamente cierta; una deportista dice que cuenta una historia incompleta. Formula esa objeción sin negar el cronómetro.',
    reformulationPrompt:'Redacta qué afirmación retirarías y con qué contexto aceptarías una marca destacada. Explica cómo evitarías multiplicar categorías solo para fabricar ganadores.',
    teacherChallenge:'Añade un récord personal: ¿necesita las mismas condiciones que una comparación entre personas?',
    words:['condiciones comparables','marca','equivalencia'],starter:'El tiempo acredita…, pero no basta para atribuir…',
  },
  {
    id:'c2-maquina-mascotas',title:'Ser «dueño» de una mascota',group:'Espacios, objetos y memoria',
    intro:'La máquina elimina la idea de tener una mascota en propiedad. Las personas podrán convivir con animales, pero no llamarlos suyos.',
    question:'Dos vecinos cuidan al mismo gato y cada uno dice «mi gato». ¿Eliminarías esa expresión? Aclara si nombra afecto, responsabilidad o derecho a decidir.',
    depthPrompt:'Una relación puede no ser propiedad y aun así generar obligaciones exclusivas. ¿Quién tendría que responder por el cuidado cuando los vecinos discrepen?',
    consequence:'Ambos se llaman compañeros del gato. Uno quiere mudarse con él; el otro dice que nadie tiene derecho a llevárselo. La nueva palabra no decide dónde vivirá.',
    reinterpretation:'¿Borrar la propiedad elimina el control o deja sin nombrar quién lo ejerce? Separa el rechazo de tratarlo como objeto de la necesidad de tomar decisiones.',
    competingReading:'«Es mío» puede reclamar poder sobre el gato o asumir que su cuidado te corresponde. Representa ambas lecturas y explica qué conducta las distinguiría.',
    reformulationPrompt:'Reformula qué facultad eliminarías y qué obligación conservarías. Cierra con una decisión condicionada si la propuesta original mezcla cosas que quieres separar.',
    teacherChallenge:'Pide un caso en que compartir una decisión mejore el cuidado y otro en que permita a todos eludir la responsabilidad.',
    words:['facultad','responsabilidad de cuidado','posesivo'],starter:'Renunciar a decidir cualquier cosa sobre… no implica renunciar a…',
  },
];

export const absurdRulesC2: AbsurdRuleC2[] = [
  {
    id:'c2-regla-nombre',title:'Tu nombre tiene que ser verdad',group:'Palabras con vida propia',
    law:'Para entrar en un edificio, tu nombre tiene que decir algo verdadero sobre ti.',
    scene:'En la puerta de una biblioteca, Blanca muestra una camiseta azul. La puerta duda si dejarla pasar.',
    developments:['Un vecino llamado León muestra su carné en lugar de una melena: sostiene que su nombre identifica, no describe.','La puerta de la biblioteca acepta a Rosa porque su nombre es realmente Rosa; la del cine rechaza a Sol porque no brilla. Las dos puertas aseguran haber comprobado la verdad.'],
    questions:['¿La regla exige un nombre auténtico o una descripción correcta? Defiende las dos lecturas y explica qué tendría que saber la puerta para aplicar cada una.','Si León demuestra cómo se llama, ¿ha cumplido la regla o ha cambiado el sentido de verdadero? Propón un caso que permita distinguir esas respuestas.','Una puerta comprueba identidad y otra, cualidades. Reformula la ley para que no cambie de criterio a mitad de la entrada; conserva una comprobación divertida y reconoce algo que no resolverá.'],
    teacherFollowUp:'Haz que la puerta explique su decisión a alguien llamado Mar que nunca ha visto el mar; no aceptes «porque lo dice la regla».',
    words:['identificar','describir','cambio de sentido'],starter:'Esa lectura convierte el nombre en…, mientras que…',
  },
  {
    id:'c2-regla-carteles',title:'Todo cartel se cumple',group:'Palabras con vida propia',
    law:'Todo lo que diga un cartel de la ciudad debe hacerse realidad mientras alguien lo lea.',
    scene:'Lees «vuelva mañana» en una tienda y el calendario salta un día. La tienda sigue cerrada.',
    developments:['Un café coloca «no leas este cartel». Quien ya lo ha leído insiste en que ahora es demasiado tarde para obedecer.','El ayuntamiento retira «prohibido retirar carteles» y afirma que, al retirarlo, ya nadie puede leerlo y no existe prohibición. El cartel protesta.'],
    questions:['¿Qué entiende la ley por lo que dice un cartel: una orden, una información o una promesa? Explica qué debería pasar con «vuelva mañana» según dos lecturas.','El cartel exige una acción que su propia lectura impide. ¿Falla la persona o falla la regla? Reformula la obligación sin fingir que se puede deshacer lo leído.','La retirada se justifica con una situación que solo existe después de retirar. Explica el círculo y propone una versión que permita corregir carteles sin que cada corrección se autorice a sí misma.'],
    teacherFollowUp:'Prueba la propuesta con un cartel decorativo que diga «aquí vive la felicidad» y otro que avise de un escalón.',
    words:['orden','autorreferencia','momento de aplicación'],starter:'Para justificar…, se está dando por hecho que ya…',
  },
  {
    id:'c2-regla-silencio',title:'Permiso para hacer ruido',group:'Palabras con vida propia',
    law:'Antes de hacer cualquier ruido, debes pedir permiso en voz alta a las personas que puedan oírlo.',
    scene:'Quieres preguntar si puedes tocar la guitarra. Al abrir la boca, una campanilla municipal te recuerda que todavía no tienes permiso.',
    developments:['Pides permiso por escrito. La campanilla rechaza la solicitud porque la ley exige voz alta, aunque todos los vecinos la han aceptado.','La campanilla suena para castigar una petición sin permiso. Un vecino le pide que demuestre quién autorizó su propio ruido.'],
    questions:['¿La ciudad intenta evitar molestias o regular sonidos? Identifica qué petición exige ya el permiso que quiere conseguir y explica la contradicción con una escena breve.','Los vecinos aceptan, pero el procedimiento no. ¿Qué distingue conseguir consentimiento y cumplir el modo de pedirlo? Defiende qué parte debería prevalecer aquí.','Si la campanilla queda exenta, la regla deja de ser universal; si no, no puede avisar. Propón una excepción coherente y prueba que no autorice cualquier ruido presentado como advertencia.'],
    teacherFollowUp:'Añade una risa involuntaria y pide distinguir controlar una acción de responder por sus efectos.',
    words:['requisito previo','consentimiento','exención'],starter:'Para cumplir…, primero tendría que incumplir…',
  },
  {
    id:'c2-regla-acuerdos',title:'Los desacuerdos se avisan juntos',group:'Palabras con vida propia',
    law:'Antes de discutir, las dos personas deben anunciar juntas y con las mismas palabras en qué no están de acuerdo.',
    scene:'Quieres discutir quién lavó la última taza. Tu compañero cree que el problema es quién ensució la primera.',
    developments:['Acuerdas con tu compañero decir «no estamos de acuerdo sobre la taza». Uno cree que así queda claro el tema; el otro cree que se oculta precisamente la diferencia.','Dos vecinas anuncian que discrepan sobre cómo anunciar su desacuerdo. La ciudad les exige primero otro anuncio acordado sobre esa discrepancia.'],
    questions:['¿Nombrar un objeto común equivale a compartir la descripción del conflicto? Explica qué presupone la ley sobre lo que hay que acordar antes de discutir.','La frase cumple literalmente, pero cada uno cree haber anunciado algo distinto. Propón una formulación que conserve ambas versiones sin decidir de antemano quién tiene razón.','El nuevo anuncio necesitaría otro anuncio sin final. Detén esa cadena con una revisión de la regla y reconoce qué desacuerdo inicial tendrás que permitir sin acuerdo previo.'],
    teacherFollowUp:'Representa una apertura de discusión en dos frases que muestre el desacuerdo sin atribuir al otro una intención.',
    words:['descripción compartida','presupuesto','cadena sin final'],starter:'Coincidimos en las palabras, pero no necesariamente en…',
  },
  {
    id:'c2-regla-fotos',title:'Fotos solo del presente',group:'Palabras con vida propia',
    law:'Solo se pueden mostrar fotografías del presente; las del pasado se convierten en dibujos.',
    scene:'Haces una foto a tu helado y la pantalla empieza a dibujarlo antes de que puedas enseñarlo.',
    developments:['Una fotógrafa muestra una imagen del reloj del ayuntamiento que se actualiza cada segundo y la vende como fotografía siempre actual.','El inspector considera presente la foto de una montaña que no ha cambiado, pero llama pasado a la de una persona que acaba de pestañear.'],
    questions:['¿Presente significa el instante de la imagen o que la imagen aún representa bien lo que existe? Explica por qué la primera lectura casi impide mostrar fotos.','¿La actualización conserva una fotografía o la sustituye continuamente? Elige una lectura y explica qué continuidad está suponiendo quien compra la imagen.','El inspector usa criterios distintos para montaña y persona. Reescribe la ley para que su criterio pueda explicarse; prueba una foto de un reloj parado y reconoce el margen que deja tu versión.'],
    teacherFollowUp:'Pide distinguir que una imagen sea antigua de que dé una impresión desactualizada.',
    words:['instante','actualizar','seguir representando'],starter:'La imagen no es reciente, aunque sigue siendo…',
  },
  {
    id:'c2-regla-ropa',title:'Siempre la ropa al revés',group:'La casa interpreta las reglas',
    law:'Para salir a la calle tienes que llevar toda tu ropa al revés.',
    scene:'Das la vuelta a una chaqueta reversible. La puerta te dice que ahora también está del derecho.',
    developments:['Una tienda vende prendas con una etiqueta que dice «interior» en ambos lados. Sus clientes aseguran salir siempre correctamente al revés.','El inspector aprueba una camiseta con las costuras fuera, pero rechaza un abrigo diseñado con las costuras fuera porque así se lleva normalmente.'],
    questions:['¿Al revés depende de la fabricación, de la costumbre o de cómo te la pusiste antes? Elige dos lecturas y aplícalas a la chaqueta sin cambiar de criterio.','¿Puede una etiqueta decidir cuál es el interior cuando la prenda no cambia? Explica quién gana autoridad para definir el cumplimiento con ese truco.','Las mismas costuras producen decisiones opuestas. Reformula la ley para que conserve el juego y pueda aplicarse también a una prenda sin lado correcto; admite una excepción necesaria.'],
    teacherFollowUp:'Introduce una bufanda lisa y pide comprobar si la nueva redacción crea una obligación imposible de observar.',
    words:['convención','lado de referencia','rasgo observable'],starter:'Solo puede estar al revés si antes acordamos…',
  },
  {
    id:'c2-regla-platos',title:'Ningún plato puede salir vacío',group:'La casa interpreta las reglas',
    law:'En los restaurantes está prohibido retirar de la mesa un plato vacío.',
    scene:'Terminas la sopa. El plato se agarra al mantel y el camarero espera con el postre. El restaurante dice que la regla busca evitar que alguien se quede con hambre.',
    developments:['Dejas una miga en el plato. El plato se suelta: el camarero puede retirarlo, aunque tú tienes exactamente la misma hambre que antes.','El inspector deja retirar un cuenco lleno de aire porque no está vacío, pero retiene un plato con salsa porque ya no contiene una ración.'],
    questions:['¿Vacío describe ausencia de materia, ausencia de comida o una comida terminada? Explica cuál de esas lecturas sirve al propósito anunciado y cuál lo contradice.','La miga resuelve el bloqueo sin cambiar si has comido suficiente. Defiende por qué puede ser cumplimiento correcto y, a la vez, irrelevante para la intención.','El aire cuenta en un caso y la salsa no cuenta en otro. Formula una regla que no salte de definición; pruébala con un plato para compartir y reconoce qué no puede saber el camarero.'],
    teacherFollowUp:'Pide contar el problema como cliente durante treinta segundos, sin vocabulario jurídico.',
    words:['contenido','ración','criterio constante'],starter:'Cumple con… si vacío significa…, pero ese sentido no…',
  },
  {
    id:'c2-regla-regalos',title:'Regalos obligatoriamente sorpresa',group:'La casa interpreta las reglas',
    law:'Todo regalo debe ser una sorpresa para quien lo recibe; de lo contrario, la caja vuelve a cerrarse.',
    scene:'Te preguntan qué quieres por tu cumpleaños. Al pedir un libro, la caja que lo contiene se cierra con un suspiro.',
    developments:['Tu amiga anuncia que te regalará lo que le pidas, pero no cuándo. Afirma que el momento inesperado basta para cumplir.','La caja acepta un regalo anunciado que decepciona de manera inesperada y rechaza otro que desconocías porque dices «ya me lo imaginaba».'],
    questions:['¿Debe sorprender el objeto, el momento o la experiencia? Distingue no saber de antemano y sentirse sorprendido; explica cuál parece buscar la ciudad.','Si el objeto está acordado pero el momento no, ¿hay una sorpresa genuina o se ha desplazado el requisito? Defiende la mejor versión de cada lectura.','La caja premia una decepción y castiga una frase cortés. Reescribe qué debe permanecer inesperado sin usar la reacción como prueba infalible; prueba tu versión con un regalo pedido expresamente.'],
    teacherFollowUp:'Añade a alguien que disfruta anticipando su regalo y pregunta qué parte del propósito merece conservarse.',
    words:['anticipación','reacción','alcance del requisito'],starter:'No sabía…, pero eso no significa que me sorprendiera…',
  },
  {
    id:'c2-regla-suenos',title:'Solo se duerme con los ojos cerrados',group:'La casa interpreta las reglas',
    law:'Toda persona que cierre los ojos debe considerarse dormida y no puede ser interrumpida.',
    scene:'Cierras los ojos para recordar una canción. El sofá te cubre con una manta y manda callar a tus amigos.',
    developments:['Una vecina cierra un solo ojo para evitar una petición. Alega que la ley dice los ojos y, por tanto, también incluye cualquiera de ellos.','La ciudad interrumpe a un durmiente con los ojos entreabiertos y protege de toda interrupción a una actriz que finge dormir en plena función.'],
    questions:['¿La ley define dormir o usa una señal para reconocerlo? Explica qué diferencia importa cuando cierras los ojos para pensar y el sofá te trata como dormido.','Defiende una lectura razonable de los ojos que incluya el guiño y otra que no. ¿Cuál encaja mejor con el propósito sin modificar silenciosamente las palabras?','La aplicación protege una apariencia y abandona el descanso real. Reformula el criterio y prueba cómo respetarías una petición de no interrumpir sin tener que comprobar si alguien duerme de verdad.'],
    teacherFollowUp:'Pide reconocer una limitación de la nueva señal: una persona podría necesitar ayuda aunque parezca estar descansando.',
    words:['señal','definición','apariencia'],starter:'Estamos tratando un indicio de… como si fuera…',
  },
  {
    id:'c2-regla-visitas',title:'Una casa abierta para todos',group:'La casa interpreta las reglas',
    law:'Toda casa debe tener siempre una puerta abierta para cualquiera que quiera entrar.',
    scene:'Dejas abierta la puerta de un armario y cierras la entrada. La casa asegura que ha cumplido.',
    developments:['Un vecino abre la puerta principal, pero coloca delante un laberinto de macetas que casi nadie logra atravesar.','El inspector acepta una puerta diminuta porque cualquiera puede intentarlo, pero rechaza una entrada accesible que se cierra un minuto para repararla.'],
    questions:['¿Una puerta abierta garantiza entrada o solo describe una posición? Explica qué palabras permiten el truco del armario y qué intención dejaría sin cumplir.','El laberinto no prohíbe pasar. ¿En qué sentido permite el acceso y en qué sentido lo impide? Separa permiso formal y posibilidad real con un ejemplo.','La aplicación favorece una apertura inútil sobre un cierre que permite volver a abrir. Reescribe la ley con un límite de privacidad y una excepción temporal; explica quién podría comprobar cada condición.'],
    teacherFollowUp:'Prueba dos casos: alguien que necesita refugio de la lluvia y alguien que exige entrar en un dormitorio.',
    words:['acceso efectivo','permiso formal','alcance'],starter:'Permitir intentar… no equivale a hacer posible…',
  },
  {
    id:'c2-regla-cumpleanos',title:'Un cumpleaños dura un día',group:'El calendario se contradice',
    law:'Cada persona debe celebrar su cumpleaños durante exactamente un día; el calendario no avanzará hasta que termine.',
    scene:'Tu fiesta empieza a las once de la noche. A medianoche el calendario pregunta por qué intentas acabar tras una sola hora.',
    developments:['Dos vecinos celebran juntos: uno entiende día como veinticuatro horas y otro como la fecha que aparece en el calendario.','El calendario exige que termine el día para dejarte terminar la fiesta y exige que termine la fiesta para dejar terminar el día. Las velas vuelven a encenderse.'],
    questions:['¿Un día es una duración o una fecha? Presenta dos horarios que cumplan una lectura y fallen en la otra sin inventar una excepción.','¿Celebrar juntos obliga a compartir el mismo comienzo y final? Distingue el cumpleaños de cada persona del evento que han organizado.','Explica por qué nadie puede dar el primer paso para terminar. Reescribe una condición para romper el círculo y comprueba qué pasa con una fiesta que cruza medianoche.'],
    teacherFollowUp:'Pregunta qué limitación queda para quien celebra en varios momentos breves con personas distintas.',
    words:['duración','fecha','condición circular'],starter:'Si día se refiere a…, la celebración termina…, pero si…',
  },
  {
    id:'c2-regla-viajes',title:'Volver antes de salir',group:'El calendario se contradice',
    law:'Solo puedes iniciar un viaje si ya tienes confirmada la vuelta.',
    scene:'Tu maleta pide una confirmación. Le enseñas un billete de regreso y pregunta cómo sabes que el tren llegará.',
    developments:['Una agencia vende sellos que dicen «vuelta confirmada». Garantiza la reserva, aunque aclara que no garantiza que viajes.','La maleta permite una vuelta al mundo que acaba en otra casa porque considera vuelta llegar a un hogar, pero bloquea un paseo hasta tu puerta porque no hay reserva de regreso.'],
    questions:['¿Confirmada significa reservada, decidida o garantizada? Explica qué promesa puede hacerse antes del viaje y cuál exige saber el futuro.','¿El sello informa o crea la confirmación que la regla pide? Defiende cuándo sería un trámite válido y cuándo solo certificaría su propia existencia.','La vuelta se interpreta como documento en un caso y como llegada en otro. Reformula la condición para un viaje sin billetes y prueba un cambio razonable de destino; admite lo que no se puede garantizar.'],
    teacherFollowUp:'Haz que la maleta acepte un plan revisable sin aceptar como plan cualquier frase tranquilizadora.',
    words:['reserva','garantía','plan revisable'],starter:'Puedo confirmar que he previsto…, sin garantizar que…',
  },
  {
    id:'c2-regla-vacaciones',title:'Descansar es obligatorio',group:'El calendario se contradice',
    law:'Durante las vacaciones está prohibido hacer cualquier cosa por obligación.',
    scene:'Preparas una excursión porque te apetece, pero empieza a llover. Ahora sientes que debes ir porque ya lo prometiste.',
    developments:['Una amiga quiere cuidar sus plantas y también se siente responsable de ellas. La regadera pregunta cuál de los dos motivos cuenta.','El inspector obliga a cancelar una excursión deseada para garantizar el descanso y luego te multa porque descansaste obedeciendo su orden.'],
    questions:['¿La regla clasifica acciones o motivos? Explica cómo la misma excursión puede ser elegida y obligatoria a la vez sin que nadie mienta.','Si una acción tiene dos motivos, ¿basta uno obligatorio para prohibirla? Defiende una interpretación y admite qué parte valiosa excluiría.','Cumplir la orden de descansar viola la prohibición de obedecer obligaciones. Reescribe la regla para proteger un margen real de elección y prueba el cuidado de las plantas sin fingir que toda responsabilidad desaparece.'],
    teacherFollowUp:'Pide una limitación que seguiría existiendo aunque la versión revisada estuviera perfectamente redactada.',
    words:['motivo','responsabilidad','margen de elección'],starter:'Que quiera hacerlo no elimina…, y que deba hacerlo no elimina…',
  },
  {
    id:'c2-regla-final',title:'Se trabaja hasta terminar',group:'El calendario se contradice',
    law:'Tu jornada termina en cuanto terminas todo lo que tenías que hacer; desde ese momento no puedes trabajar.',
    scene:'Terminas tu última tarea y aparece un formulario obligatorio para confirmar que has terminado. El escritorio no sabe si dejarte sentar.',
    developments:['Un compañero borra una tarea de su lista y afirma que ya ha terminado todo lo que tenía que hacer. Otra persona termina una tarea sin anotarla.','El escritorio permite responder un mensaje llamado «favor», pero bloquea rellenar el formulario de salida por considerarlo trabajo fuera de la jornada.'],
    questions:['¿Terminar depende de completar acciones, de cerrar una lista o de que alguien lo reconozca? Explica por qué el formulario cambia el momento que pretende registrar.','¿Eliminar una tarea pendiente equivale a dejar de tener que hacerla? Distingue renunciar, delegar y cumplir antes de juzgar la lista vacía.','El escritorio decide por la etiqueta de la actividad y vuelve imposible certificar el final. Reformula la regla con un cierre practicable y comprueba qué harías con una petición recibida después.'],
    teacherFollowUp:'Introduce una tarea que consiste en estar disponible durante un rato, sin producir un objeto terminado.',
    words:['cierre','tarea pendiente','reconocimiento'],starter:'La lista certifica…, pero por sí sola no demuestra…',
  },
  {
    id:'c2-regla-turnos',title:'El último pasa primero',group:'El calendario se contradice',
    law:'En cualquier cola, la última persona debe ser atendida primero.',
    scene:'Eres el último de la heladería. Justo cuando te llaman llega alguien más y tu turno se escapa hacia atrás.',
    developments:['Dos clientes se apartan y vuelven a ponerse al final a la vez. Cada uno sostiene que merece el siguiente helado.','La nevera congela una foto de la cola para decidir quién era el último. El inspector la multa por atender a alguien que ahora está delante de un recién llegado.'],
    questions:['¿Último se decide al llegar, al abrir el puesto o al atender? Explica qué presupone la regla sobre una cola que sigue cambiando.','¿Volver a colocarte al final crea una llegada nueva o conserva tu lugar en la misma espera? Defiende ambas lecturas y señala qué incentivo produce cada una.','La foto hace posible atender, pero contradice una lectura del presente. Reescribe cuándo se fija el turno y prueba dos casos límite: llegadas simultáneas y alguien que se aparta para ayudar. Reconoce qué injusticia no resuelve tu versión.'],
    teacherFollowUp:'Pide que expliques tu versión a la nevera en dos frases y compruebes si puede aplicarla sin interrumpir cada venta.',
    words:['momento de referencia','simultáneo','continuidad de la espera'],starter:'La palabra último no basta si no fijamos cuándo…',
  },
];

export const worldGuidesC2: Record<'machine'|'rules',WorldGuide> = {
  machine:{
    introduction:'La máquina necesita saber qué significa lo que quieres borrar. Vota, explica tu lectura y descubre otra defendible. Tu decisión final puede ser condicional: lo importante es precisar a qué se aplica.',
    warmup:'Di una cosa cotidiana que te gustaría eliminar. Tu compañero pregunta qué cuenta como esa cosa y propone un caso dudoso. Responde con un límite concreto antes de votar.',
    objective:'Delimitar categorías, contrastar interpretaciones defendibles y reformular una propuesta sin perder el principio que la sostiene.',
    stages:[
      {time:'0–5 min',title:'¿Estamos borrando lo mismo?',task:'Presenta la propuesta del inicio. Escucha una lectura distinta de la tuya y comprueba si el desacuerdo está en el objetivo o en la definición.'},
      {time:'5–13 min',title:'Primero el voto, luego el alcance',task:'Completa una decisión. Vota antes del giro, explica qué incluyes y qué excluyes, revela la consecuencia y responde a la lectura alternativa.'},
      {time:'13–27 min',title:'Tres categorías bajo presión',task:'Explora tres decisiones de otros grupos. Alterna quién sostiene la mejor versión de cada interpretación. Reformula la propuesta antes de cerrar cada voto, aunque mantengas la decisión.'},
      {time:'27–35 min',title:'Una condición que se pueda probar',task:'Explora una quinta decisión o retoma una cerrada. Pon a prueba tu condición con un caso cercano que no quieras eliminar y señala qué evidencia te haría revisarla.'},
      {time:'35–45 min',title:'Cambiar la pregunta',task:'Selecciona decisiones reales del recorrido para los tres papeles del cierre. Presenta una eliminación precisa, responde a una objeción y explica por qué tu nueva formulación es superior.'},
    ],
    teacherNote:'Selecciona unas cinco decisiones, no las treinta. Pide hablar antes de cada avance y deja el apoyo cerrado si no hace falta. Una postura condicional debe precisar el término, el alcance y una condición comprobable; «depende» no basta. Las consecuencias son ficción. No atribuyas al alumno un cambio que no tuvo: si falta un caso para el cierre, explora otra decisión o reconoce que ese papel aún no tiene ejemplo. Reserva diez minutos para conectar elecciones realmente cerradas.',
    moves:['Por… estaba entendiendo…, pero tu lectura incluye…','Puedo aceptar ambas afirmaciones si distinguimos…','Ese argumento es correcto respecto a…, pero deja sin resolver…','Eliminaría únicamente…, siempre que…','Revisaría esta conclusión si supiéramos que…'],
    challenge:'Tu compañero interpreta tu reformulación de una manera que no pretendías, pero que sus palabras permiten. Reconoce la lectura, cambia lo mínimo necesario y explica qué margen prefieres dejar abierto.',
    closingTitle:'Tres decisiones para cambiar la pregunta',
    closingTask:'Revisa varias decisiones cerradas y selecciona una que realmente eliminarías, una que inicialmente querías eliminar pero has redefinido y una cuya pregunta binaria resultó engañosa. Basa la explicación en tus votos reales. Reescribe una proposición y explica oralmente por qué es superior: qué distingue, qué conserva y qué malentendido evita.',
  },
  rules:{
    introduction:'En esta ciudad, las palabras también hacen travesuras. Una ley parece sencilla hasta que dos habitantes la cumplen de maneras incompatibles. Tu trabajo es encontrar una versión que puedas explicar sin quitarle toda la gracia.',
    warmup:'Di una regla breve para una merienda. Tu compañero la interpreta al pie de la letra y tú explicas qué pretendías. Señala la palabra que permite la diferencia.',
    objective:'Contrastar sentido literal e intención, resolver casos límite y revisar una regla ante aplicaciones contradictorias, reconociendo la incertidumbre que permanece.',
    stages:[
      {time:'0–5 min',title:'Una palabra, dos ciudades',task:'Representa la regla de la merienda. Distingue lo que has dicho de lo que esperabas que la otra persona entendiera.'},
      {time:'5–15 min',title:'Tres lecturas de una ley',task:'Explora una ley por etapas. Explica primero literalidad e intención, después el caso nuevo y finalmente la contradicción. Habla antes de descubrir cada cambio.'},
      {time:'15–28 min',title:'Cambiar de intérprete',task:'Explora otras dos leyes de grupos distintos. Alterna los papeles de habitante e inspector. Presenta la mejor lectura rival antes de defender tu criterio.'},
      {time:'28–35 min',title:'La misma regla en dos escenas',task:'Elige una ley ya explorada. Localiza la ambigüedad y ensaya una revisión. Tu compañero propone dos casos límite que obliguen a aplicar la misma definición.'},
      {time:'35–45 min',title:'Una ley explicable',task:'Completa el cierre con esa ley real: diagnóstico, nueva redacción, dos pruebas y una limitación. Explícalo como conversación entre vecinos; revisa una frase después de la objeción.'},
    ],
    teacherNote:'Tres leyes bastan para unos 45 minutos. Conserva el humor con escenas de veinte segundos y evita tecnicismos legales. Cada avance añade información: no leas los cambios antes de que el alumno responda. No basta detectar un truco; pide aplicar el mismo significado a dos casos y justificar por qué se conserva o cambia. En el cierre selecciona una ley realmente explorada y exige dos casos límite diferentes, no dos ejemplos cómodos. Una buena revisión admite lo que todavía no resuelve.',
    moves:['Literalmente permite…, aunque parece querer evitar…','Las dos lecturas se separan cuando…','Si aplicamos ese significado también a…, entonces…','Cambiaría esta palabra por… para distinguir…','Esta versión resuelve…, pero todavía deja abierto…'],
    challenge:'Defiende una aplicación que tu compañero considere absurda usando solo la redacción revisada. Después ayúdale a corregirla sin inventar una excepción distinta para cada habitante.',
    closingTitle:'Una ley, dos pruebas y un límite',
    closingTask:'Elige una ley problemática que hayas explorado. Explica por qué falla su redacción y propone una versión revisada en lenguaje cotidiano. Pruébala con dos casos límite distintos y admite una limitación que siga sin resolverse. Cuéntalo como si hablaras con una vecina que tiene que vivir con esa ley.',
  },
};

export const worldClosingC2: Record<'machine'|'rules',string[]> = {
  machine:[
    'Defiende una eliminación que realmente mantienes. Precisa qué entra en la categoría y qué caso cercano queda fuera.',
    'Recupera algo que inicialmente querías eliminar y que después has redefinido. Compara tu lectura inicial con la final usando el caso que hizo necesaria la distinción.',
    'Señala una pregunta binaria engañosa de tu recorrido: ¿qué posiciones compatibles parecía obligarte a separar?',
    'Reescribe una proposición. Explica por qué tu versión es superior y qué condición o evidencia podría hacerte revisarla.',
  ],
  rules:[
    'Identifica la palabra, el supuesto o la contradicción que hace fallar la ley explorada. Explica las dos interpretaciones con una escena.',
    'Propón una redacción revisada y explica qué intención conserva. Haz que un vecino pueda repetirla sin una explicación técnica.',
    'Prueba la misma versión con dos casos límite distintos. Explica qué respuesta produce en cada uno y modifica una frase si cambia de criterio.',
    'Admite una limitación que permanece: ¿qué interpretación, incertidumbre o coste aceptarías y por qué?',
  ],
};
