import type { EliminationA1, AbsurdRuleA1, WorldGuide } from './types';

// Separate beginner exchanges. Consequences describe this invented world only.
export const eliminationsA1: EliminationA1[] = [
  {id:'a1-maquina-tostadora',title:'Las tostadoras',group:'En casa',intro:'Es la hora del desayuno. Tu tostada sale negra otra vez.',question:'¿Te gusta el pan tostado o prefieres el pan sin tostar?',consequence:'Mañana tienes tu pan favorito, pero no puedes hacer tostadas.',words:['pan','caliente','desayunar'],starter:'Prefiero el pan…',answerFrames:['Me gusta… / No me gusta…','Desayuno… con…']},
  {id:'a1-maquina-television',title:'La televisión',group:'En casa',intro:'En tu casa hay una televisión grande. Hoy no sabes qué ver.',question:'¿Ves la tele solo o con otra persona?',consequence:'Esta noche tu familia quiere ver una película contigo. Ya no hay televisión.',words:['película','familia','noche'],starter:'Veo la tele con…',answerFrames:['Solo. / Con…','Me gusta ver… porque…']},
  {id:'a1-maquina-aspiradora',title:'Las aspiradoras',group:'En casa',intro:'Quieres escuchar música, pero la aspiradora hace mucho ruido.',question:'¿Usas una aspiradora en casa? ¿Para qué?',consequence:'Tu perro deja pelos en la alfombra. Ahora necesitas un cepillo y mucho tiempo.',words:['limpiar','ruido','alfombra'],starter:'La uso para…',answerFrames:['Sí, la uso. / No la uso.','La necesito para…']},
  {id:'a1-maquina-almohada',title:'Las almohadas',group:'En casa',intro:'Tu cama tiene cinco almohadas. No hay espacio para ti.',question:'¿Cuántas almohadas necesitas para dormir?',consequence:'Esta noche solo tienes el colchón. No hay nada blando para la cabeza.',words:['cama','cabeza','dormir'],starter:'Duermo con…',answerFrames:['Una. / Dos. / Ninguna.','Necesito… porque…']},
  {id:'a1-maquina-aire',title:'El aire acondicionado',group:'En casa',intro:'Entras en una tienda. El aire está muy frío y tú llevas una camiseta.',question:'¿Tienes calor o frío normalmente en verano?',consequence:'Hoy hace mucho calor. En tu habitación no hay aire acondicionado ni ventilador.',words:['calor','frío','verano'],starter:'En verano tengo…',answerFrames:['Tengo calor. / Tengo frío.','Uso… cuando hace…']},
  {id:'a1-maquina-espejos',title:'Los espejos',group:'En casa',intro:'Miras el espejo del baño. Tienes el pelo muy raro hoy.',question:'¿Miras un espejo antes de salir de casa?',consequence:'Vas a una fiesta con chocolate en la cara. No puedes verlo en un espejo.',words:['cara','pelo','salir'],starter:'Antes de salir, yo…',answerFrames:['Siempre. / A veces. / Nunca.','Lo uso para…']},
  {id:'a1-maquina-cafe',title:'El café',group:'Comer y salir',intro:'En la mesa hay una taza de café. El olor llega hasta tu habitación.',question:'¿Qué bebes por la mañana: café, té o leche?',consequence:'Tu amiga viene a desayunar. Su bebida favorita es el café y no puedes prepararlo.',words:['taza','beber','mañana'],starter:'Por la mañana bebo…',answerFrames:['Café. / Té. / Leche.','Prefiero… porque…']},
  {id:'a1-maquina-helados',title:'Los helados',group:'Comer y salir',intro:'Tu helado cae al suelo antes de la primera cucharada.',question:'¿Cuál es tu sabor de helado favorito?',consequence:'Estás en la playa y hace calor. El puesto vende agua, pero ya no vende helados.',words:['chocolate','fruta','playa'],starter:'Mi favorito es el de…',answerFrames:['El de…','Como helado con…']},
  {id:'a1-maquina-cebolla',title:'Las cebollas',group:'Comer y salir',intro:'Cortas una cebolla para la cena. Ahora te lloran los ojos.',question:'¿Te gusta la cebolla en la comida?',consequence:'Quieres preparar la sopa de tu abuela. Lleva cebolla y ahora falta ese ingrediente.',words:['cocinar','sopa','ojos'],starter:'Me gusta en…',answerFrames:['Sí, me gusta. / No, no me gusta.','En casa como… con…']},
  {id:'a1-maquina-restaurantes',title:'Los restaurantes',group:'Comer y salir',intro:'Miras la carta de un restaurante. Todo cuesta mucho dinero.',question:'¿Prefieres cenar fuera o cocinar en casa?',consequence:'Es tu cumpleaños. Quieres salir a cenar con amigos, pero todos tienen que cocinar en casa.',words:['cena','cocinar','amigos'],starter:'Prefiero cenar…',answerFrames:['Fuera. / En casa.','Con mis amigos me gusta…']},
  {id:'a1-maquina-carritos',title:'Los carritos del supermercado',group:'Comer y salir',intro:'Un carrito tiene una rueda rota. Es difícil moverlo.',question:'¿Compras muchas cosas o pocas cosas en el supermercado?',consequence:'Compras leche, patatas y una sandía. Ahora tienes que llevar todo en los brazos.',words:['comprar','pesado','llevar'],starter:'Compro…',answerFrames:['Muchas cosas. / Pocas cosas.','Lo necesito para llevar…']},
  {id:'a1-maquina-paraguas',title:'Los paraguas',group:'Comer y salir',intro:'Hace viento. Tu paraguas se abre al revés.',question:'Cuando llueve, ¿sales o te quedas en casa?',consequence:'Llueve mucho y tienes que caminar diez minutos hasta la parada. No tienes chaqueta.',words:['lluvia','mojado','caminar'],starter:'Cuando llueve, yo…',answerFrames:['Salgo. / Me quedo en casa.','Necesito… para…']},
  {id:'a1-maquina-ascensores',title:'Los ascensores',group:'Ir y venir',intro:'El ascensor es pequeño. Dentro hay tres personas y un perro grande.',question:'¿En qué piso vives? ¿Subes a pie?',consequence:'En este mundo vives en el piso doce. Hoy traes dos bolsas grandes del supermercado.',words:['piso','subir','bolsas'],starter:'Vivo en el piso…',answerFrames:['En el primero. / En el…','Uso el ascensor para…']},
  {id:'a1-maquina-bicicletas',title:'Las bicicletas',group:'Ir y venir',intro:'Tu bicicleta está mojada. Llueve y tienes que volver a casa.',question:'¿Sabes ir en bicicleta? ¿Adónde vas?',consequence:'Mañana hace sol. Tu amigo quiere ir contigo al parque en bicicleta, pero ya no hay bicicletas.',words:['parque','ir','sol'],starter:'Voy en bicicleta a…',answerFrames:['Sí. / No.','Voy a… con…']},
  {id:'a1-maquina-autobuses',title:'Los autobuses',group:'Ir y venir',intro:'Esperas el autobús. Hoy llega veinte minutos tarde.',question:'¿Vas al trabajo o a clase en autobús?',consequence:'Tu clase está a una hora a pie. No tienes coche y tampoco hay autobús.',words:['parada','clase','lejos'],starter:'Voy a… en…',answerFrames:['Sí. / No.','Lo necesito porque… está lejos.']},
  {id:'a1-maquina-maletas',title:'Las maletas',group:'Ir y venir',intro:'Tu maleta es grande y no entra debajo de la cama.',question:'¿Qué llevas en un viaje de tres días?',consequence:'Sales de viaje mañana. Tienes ropa y zapatos para llevar, pero solo puedes usar una bolsa pequeña.',words:['viaje','ropa','zapatos'],starter:'Llevo…',answerFrames:['Ropa y…','Necesito una maleta para…']},
  {id:'a1-maquina-zapatos',title:'Los zapatos',group:'Ir y venir',intro:'Tus zapatos nuevos son bonitos, pero te duelen los pies.',question:'¿Qué zapatos usas para caminar mucho?',consequence:'La calle está muy caliente. Quieres ir a la tienda y ahora tienes que ir sin zapatos.',words:['pies','cómodo','calle'],starter:'Uso zapatos…',answerFrames:['Cómodos. / Deportivos.','Los uso para…']},
  {id:'a1-maquina-semaforos',title:'Los semáforos',group:'Ir y venir',intro:'No hay coches, pero el semáforo sigue en rojo. Esperas para cruzar.',question:'¿Hay un semáforo cerca de tu casa?',consequence:'Ahora hay muchos coches. Quieres cruzar y no hay luz verde para ti.',words:['rojo','verde','cruzar'],starter:'Cerca de mi casa hay…',answerFrames:['Sí, hay uno. / No hay.','Lo necesito para…']},
  {id:'a1-maquina-despertadores',title:'Los despertadores',group:'Mi tiempo',intro:'Son las siete. El despertador suena y quieres dormir un poco más.',question:'¿A qué hora te levantas de lunes a viernes?',consequence:'Mañana tu tren sale a las seis. Nadie puede despertarte y ya no hay alarmas.',words:['hora','levantarse','tren'],starter:'Me levanto a las…',answerFrames:['A las…','Lo uso porque…']},
  {id:'a1-maquina-auriculares',title:'Los auriculares',group:'Mi tiempo',intro:'Quieres hablar con tu hermano. Él tiene auriculares y no te oye.',question:'¿Dónde escuchas música normalmente?',consequence:'Quieres escuchar tu canción favorita de noche. Tu familia duerme y no puedes usar auriculares.',words:['música','escuchar','noche'],starter:'Escucho música en…',answerFrames:['En casa. / En el autobús.','Los uso para…']},
  {id:'a1-maquina-moviles',title:'Los teléfonos móviles',group:'Mi tiempo',intro:'Estás con un amigo. Él mira su teléfono durante toda la comida.',question:'¿Para qué usas más el teléfono: hablar, hacer fotos o jugar?',consequence:'Tu hermana está en otra ciudad. Hoy quieres llamarla desde el parque, pero no tienes teléfono.',words:['llamar','hermana','foto'],starter:'Lo uso para…',answerFrames:['Para…','Lo necesito porque…']},
  {id:'a1-maquina-videojuegos',title:'Los videojuegos',group:'Mi tiempo',intro:'Llevas mucho tiempo con un videojuego y todavía no puedes ganar.',question:'¿Juegas con amigos o prefieres otro plan?',consequence:'Llueve todo el sábado. Tu primo viene a jugar contigo, pero no hay videojuegos.',words:['jugar','ganar','sábado'],starter:'Con mis amigos prefiero…',answerFrames:['Juego con… / Prefiero…','Me gusta porque…']},
  {id:'a1-maquina-regalos',title:'Los regalos de cumpleaños',group:'Mi tiempo',intro:'Es el cumpleaños de una amiga. No sabes qué regalo comprar.',question:'¿Te gusta dar regalos o recibirlos?',consequence:'Hoy es tu cumpleaños. Tus amigos vienen a verte, pero nadie puede darte un regalo.',words:['dar','recibir','cumpleaños'],starter:'Me gusta…',answerFrames:['Dar. / Recibir. / Las dos cosas.','Un regalo que me gusta es…']},
  {id:'a1-maquina-fotos',title:'Las fotografías',group:'Mi tiempo',intro:'En una fiesta todos hacen fotos. Nadie está bailando.',question:'¿De quién o de qué haces fotos?',consequence:'Mañana desaparecen también las fotos de tu infancia. Ya no puedes verlas con tu familia.',words:['familia','recuerdo','pequeño'],starter:'Hago fotos de…',answerFrames:['De…','Me gustan porque…']},
];

export const absurdRulesA1: AbsurdRuleA1[] = [
  {id:'a1-regla-sombrero-fruta',title:'Un sombrero de fruta',group:'Salir a la calle',law:'Para salir de casa, todos llevan una fruta en la cabeza.',scene:'Es lunes. En la puerta tienes una manzana, un plátano y una sandía.',questions:['¿Te gusta salir con una fruta en la cabeza?','¿Qué pasa con tu fruta cuando subes al autobús?','Para ir al trabajo, ¿qué fruta eliges?'],words:['cabeza','pequeño','pesado'],starter:'Elijo… porque…',questionFrames:[['Me gusta. / No me gusta.','Es…'],['En el autobús, mi fruta…','Necesito…'],['Elijo…','Es pequeña / grande / pesada.']]},
  {id:'a1-regla-parada-baile',title:'Un baile en la parada',group:'Salir a la calle',law:'El autobús solo para cuando una persona baila.',scene:'Estás en la parada con tu abuelo. Ya viene el autobús.',questions:['¿Te gusta bailar en la calle?','Cada mañana vas a clase en autobús. ¿Qué haces en la parada?','¿Bailas tú o le pides ayuda a tu abuelo?'],words:['bailar','esperar','ayuda'],starter:'En la parada…',questionFrames:[['Sí, me gusta. / No me gusta.','Bailo con…'],['Por la mañana…','Antes de subir, yo…'],['Bailo yo. / Le pido ayuda.','Prefiero… porque…']]},
  {id:'a1-regla-nombres-calles',title:'Calles con nombres de comida',group:'Salir a la calle',law:'Todas las calles tienen el nombre de una comida.',scene:'Un amigo te espera entre la calle Pizza y la calle Sopa.',questions:['¿Qué nombre te gusta más: Pizza o Sopa?','Un taxi te lleva a casa. ¿Qué dirección dices?','Elige una comida para el nombre de tu calle. ¿Cuál quieres?'],words:['calle','dirección','taxi'],starter:'Vivo en la calle…',questionFrames:[['Me gusta más…','Mi comida favorita es…'],['Voy a la calle…','Está cerca de…'],['Quiero la calle…','Elijo ese nombre porque…']]},
  {id:'a1-regla-banco-abrazo',title:'Bancos para dos',group:'Salir a la calle',law:'Los bancos del parque solo aparecen cuando llegan dos personas juntas.',scene:'Vas solo al parque y estás cansado. No hay ningún banco.',questions:['¿Te gusta ir al parque solo o con alguien?','Después de caminar, estás cansado. ¿Dónde descansas sin banco?','Mañana quieres sentarte en el parque. ¿A quién invitas?'],words:['sentarse','cansado','invitar'],starter:'Voy con…',questionFrames:[['Solo. / Con…','Normalmente voy…'],['Descanso en…','Estoy…'],['Invito a…','Vamos al parque a las…']]},
  {id:'a1-regla-puertas-animal',title:'Una puerta que hace miau',group:'En mi casa',law:'Las puertas solo se abren cuando haces el sonido de un animal.',scene:'Llegas a casa con dos bolsas. La puerta espera un «miau» o un «guau».',questions:['¿Qué sonido de animal te parece más divertido?','Llegas tarde a casa y tu familia duerme. ¿Cómo haces el sonido?','Para tu puerta, ¿eliges un gato, un perro o una vaca?'],words:['abrir','puerta','dormir'],starter:'Hago…',questionFrames:[['El sonido de…','Me gusta porque…'],['Hablo bajo. / Hago…','Mi familia está…'],['Elijo…','Para entrar, hago…']]},
  {id:'a1-regla-pijamas',title:'La tarde en pijama',group:'En mi casa',law:'A las cinco de la tarde, toda la ropa se convierte en pijama.',scene:'Son las cinco y estás en una cafetería. Ahora llevas un pijama de estrellas.',questions:['¿Te gusta tu pijama para salir a la calle?','Tienes una cena a las ocho. ¿Qué ropa llevas?','¿Prefieres un pijama de estrellas o uno de rayas para la cena?'],words:['ropa','tarde','rayas'],starter:'Llevo un pijama…',questionFrames:[['Sí. / No.','Mi pijama es…'],['Llevo…','A las ocho estoy en…'],['Prefiero el de…','Me gusta porque…']]},
  {id:'a1-regla-cama-musica',title:'La cama cantante',group:'En mi casa',law:'Tu cama canta hasta que dices «buenos días».',scene:'Es domingo. Quieres dormir, pero tu cama canta muy fuerte.',questions:['¿Quieres una cama que canta por la mañana?','Te despiertas y escuchas la canción. ¿Qué dices primero?','¿Eliges una canción tranquila o una canción para bailar?'],words:['despertarse','cantar','tranquilo'],starter:'Primero digo…',questionFrames:[['Quiero. / No quiero.','Me gusta dormir hasta las…'],['Buenos días.','Después…'],['Elijo una canción…','Por la mañana prefiero…']]},
  {id:'a1-regla-cucharas',title:'Una cuchara gigante',group:'A la mesa',law:'Los miércoles todas las cucharas son tan grandes como una silla.',scene:'Es miércoles. Tienes yogur para desayunar y una cuchara enorme.',questions:['¿Es fácil o difícil comer con esa cuchara?','¿Cómo comes tu yogur esta mañana?','El próximo miércoles, ¿preparas yogur o una tostada?'],words:['grande','comer','desayuno'],starter:'Para desayunar…',questionFrames:[['Es fácil. / Es difícil.','La cuchara es…'],['Uso…','Puedo / No puedo…'],['Preparo…','Es más fácil porque…']]},
  {id:'a1-regla-panaderia-chiste',title:'Pan con una sonrisa',group:'A la mesa',law:'En la panadería pagas el pan con una cara divertida.',scene:'Quieres dos panes. La panadera espera tu cara más divertida.',questions:['¿Te gusta esta forma de comprar pan?','Vas a comprar el desayuno para tu familia. ¿Qué cara haces?','¿Vas tú a la panadería o vas con un amigo?'],words:['pan','cara','sonreír'],starter:'En la panadería…',questionFrames:[['Sí, me gusta. / No me gusta.','Es…'],['Hago una cara…','Quiero… panes.'],['Voy…','Prefiero ir con… porque…']]},
  {id:'a1-regla-mesa-gira',title:'La mesa gira',group:'A la mesa',law:'En los restaurantes, la mesa gira lentamente durante la comida.',scene:'Tu sopa está delante de ti. Ahora pasa delante de tu amigo.',questions:['¿Te parece divertida una mesa que gira?','Quieres beber agua. Tu vaso está al otro lado. ¿Qué haces?','Para comer aquí, ¿prefieres sopa o un bocadillo?'],words:['vaso','esperar','pasar'],starter:'Quiero…',questionFrames:[['Sí, es divertida. / No me gusta.','La mesa…'],['Espero. / Pido el vaso.','Por favor, pasa…'],['Prefiero…','Es fácil comer…']]},
  {id:'a1-regla-menu-dibujo',title:'Un menú para dibujar',group:'A la mesa',law:'Para pedir comida, tienes que dibujarla. No puedes decir su nombre.',scene:'Tienes hambre. El camarero te da papel y un lápiz.',questions:['¿Te gusta dibujar tu comida?','Quieres desayunar aquí. ¿Qué dibujas en el papel?','¿Pides una comida fácil de dibujar o tu comida favorita?'],words:['dibujar','papel','pedir'],starter:'Dibujo…',questionFrames:[['Sí. / No.','Sé dibujar…'],['Dibujo…','Para desayunar quiero…'],['Elijo…','Es fácil / difícil de dibujar.']]},
  {id:'a1-regla-gatos-cine',title:'Gatos en el cine',group:'Con otras personas',law:'En el cine, un gato elige dónde te sientas.',scene:'Tienes dos entradas. El gato mira un asiento delante y otro detrás.',questions:['¿Te gusta que un gato elija tu asiento?','Vas al cine con tu hermano. El gato os da asientos separados. ¿Dónde te sientas tú?','El gato ofrece un asiento cerca de la pantalla o uno junto a tu hermano. ¿Cuál eliges?'],words:['asiento','cerca','juntos'],starter:'Me siento…',questionFrames:[['Me gusta. / No me gusta.','El gato es…'],['Me siento delante / detrás.','Mi hermano está…'],['Elijo el asiento…','Quiero estar cerca de…']]},
  {id:'a1-regla-cumple-mensual',title:'Doce cumpleaños',group:'Con otras personas',law:'Cada persona tiene un cumpleaños todos los meses.',scene:'Hoy es tu cumpleaños otra vez. La tarta del mes pasado todavía está en la nevera.',questions:['¿Quieres tener doce cumpleaños al año?','Este mes trabajas el día de tu cumpleaños. ¿A qué hora celebras?','Para tu próxima fiesta, ¿eliges tarta, fruta o pizza?'],words:['mes','fiesta','celebrar'],starter:'Mi fiesta es…',questionFrames:[['Quiero. / No quiero.','Me gustan los cumpleaños porque…'],['Celebro a las…','Después del trabajo…'],['Elijo…','Voy a comer… con…']]},
  {id:'a1-regla-saludo-codos',title:'Saludos con los codos',group:'Con otras personas',law:'Todos se saludan con los codos y dicen su comida favorita.',scene:'Conoces a una vecina nueva en el ascensor. Ella dice «¡Paella!».',questions:['¿Te parece divertido este saludo?','Por la mañana ves a tres compañeros. ¿Cómo los saludas?','Hoy tu comida favorita es otra. ¿Qué dices al saludar?'],words:['saludar','codo','compañero'],starter:'Para saludar, digo…',questionFrames:[['Es divertido. / Es raro.','Me gusta / No me gusta…'],['Digo…','Saludo con…'],['Hoy digo…','Hoy prefiero comer…']]},
  {id:'a1-regla-perro-profesor',title:'Un perro en clase',group:'Con otras personas',law:'En cada clase hay un perro. Cuando ladra, todos cambian de silla.',scene:'Estás en clase de español. El perro dice «guau» y empieza el movimiento.',questions:['¿Quieres un perro en tu clase de español?','Estás escribiendo y el perro ladra. ¿Qué haces con tu cuaderno?','Después del cambio, ¿prefieres sentarte junto a la puerta o junto a la ventana?'],words:['silla','cuaderno','ventana'],starter:'Me siento junto a…',questionFrames:[['Sí, quiero. / No quiero.','Me gustan / No me gustan los perros.'],['Llevo mi cuaderno. / Lo dejo…','Ahora me siento…'],['Prefiero…','Desde ahí veo…']]},
];

export const worldGuidesA1: Record<'machine' | 'rules', WorldGuide> = {
  machine: {
    introduction:'Una máquina puede hacer desaparecer cosas. Hoy tú eliges: ¿las eliminamos o las dejamos? Después, mira qué pasa.',
    warmup:'Mira a tu alrededor. Nombra tres cosas. Elige una y completa: «La uso para…». Tu compañero pregunta: «¿Todos los días?».',
    objective:'Elegir, dar una razón sencilla y cambiar o mantener una decisión después de una sorpresa concreta.',
    stages:[
      {time:'0–5 min',title:'Cosas que usamos',task:'Nombren tres cosas y digan para qué las usan. El docente modela una respuesta corta y una frase más.'},
      {time:'5–13 min',title:'Dos decisiones juntos',task:'Elijan dos cosas de En casa. Primero respondan sí o no. Antes de abrir la consecuencia, usen una frase visible para dar una razón.'},
      {time:'13–25 min',title:'Ahora tú preguntas',task:'Elijan tres cosas de otros grupos. Alternen quién pregunta y quién decide. Pregunten «¿Cuándo?» o «¿Con quién?» para añadir un detalle.'},
      {time:'25–35 min',title:'Una sorpresa más',task:'Elijan dos cosas más. Lean cada consecuencia, digan qué necesitan ahora y voten otra vez. Comparen una decisión con la de su compañero.'},
      {time:'35–45 min',title:'Mis tres decisiones',task:'Elijan algo para eliminar, algo para conservar siempre y una decisión que cambió. Presenten las tres elecciones y respondan una pregunta por elección.'},
    ],
    teacherNote:'Usa unas siete decisiones, no todo el banco. Acepta primero una palabra o sí/no y pide después una sola frase con porque o para. Lee la consecuencia despacio y comprueba quién está, dónde está y qué necesita. En clase individual, comparte también tus elecciones. Si nadie cambia de idea, comparen dos decisiones distintas sin inventar un cambio.',
    moves:['Elimino… porque no me gusta…','No elimino… porque lo uso para…','Sin esto, necesito…','Ahora cambio de idea porque…'],
    challenge:'Tu compañero elige otra cosa. Pregunta «¿Por qué?» y responde con una cosa que tú usas cada día.',
    closingTitle:'Mis tres decisiones',
    closingTask:'Mira tus decisiones de hoy. Elige tres y habla con las frases de abajo. Tu compañero escucha y pregunta «¿Por qué?» o «¿Para qué?». Después cambien los papeles. Si no cambiaste ninguna decisión, di «No cambio de idea porque…».',
  },
  rules: {
    introduction:'En esta ciudad pasan cosas muy raras. Lee una regla, imagina tu día y elige qué hacer.',
    warmup:'Di qué haces por la mañana: «Me levanto…», «Desayuno…», «Voy a…». Tu compañero elige una cosa igual y una diferente.',
    objective:'Reaccionar a una regla divertida, describir un efecto en una rutina y elegir una adaptación sencilla.',
    stages:[
      {time:'0–5 min',title:'Una mañana normal',task:'Cada persona cuenta tres acciones. El docente muestra cómo añadir la hora o una persona.'},
      {time:'5–14 min',title:'Entrar en la ciudad',task:'Elijan una regla. Comprueben la situación con un gesto o dibujo. Abran las tres preguntas y usen las frases visibles.'},
      {time:'14–26 min',title:'Vivir dos reglas más',task:'Elijan dos reglas de otros grupos. Alternen las preguntas: primero una reacción, después una rutina y al final una elección. Pidan un detalle con «¿A qué hora?» o «¿Con quién?».'},
      {time:'26–35 min',title:'Un día juntos',task:'Retomen una regla. Cada persona cuenta su mañana con dos o tres frases. El compañero propone una elección: «¿Prefieres… o…?».'},
      {time:'35–45 min',title:'Mi ciudad divertida',task:'Elijan la regla más divertida y la más difícil. Inventen una regla simple, cuenten una escena y respondan dos preguntas del compañero.'},
    ],
    teacherNote:'Trabaja tres reglas; las demás permiten otra sesión. Comprueba primero la acción concreta, no una explicación de la sociedad. Acepta una reacción breve y pide una frase más con el apoyo. Da dos opciones si el alumno se bloquea. En clase individual, inventa una regla propia para que el alumno también haga preguntas.',
    moves:['Me gusta / No me gusta porque…','Normalmente…, pero aquí…','Por la mañana puedo / no puedo…','Voy a… con…'],
    challenge:'Invita a tu compañero a tu ciudad. Explica una cosa que puede hacer y otra que no puede hacer.',
    closingTitle:'Mi ciudad divertida',
    closingTask:'Mira las reglas que conversaron. Elige dos para comparar. Después inventa una regla con una cosa, un lugar y una acción. Tu compañero pregunta «¿Dónde?» y «¿Cuándo?». Prueben la regla con una escena corta.',
  },
};

export const worldClosingA1 = {
  machine:['Una cosa que elimino: «Elimino… porque…».','Una cosa que nunca elimino: «Nunca elimino…; lo necesito para…».','Una decisión que cambio: «Primero…, pero ahora… porque…».'],
  rules:['La regla más divertida es… porque…','La regla más difícil es…; normalmente yo…','Mi nueva regla: «En mi ciudad, todos…». «Por la mañana, yo…».'],
};
