import type { EliminationB2, AbsurdRuleB2, WorldGuide } from './types';

// Consecuencias ficticias: son condiciones de cada simulación, no predicciones.
export const eliminationsB2: EliminationB2[] = [
  {
    id: 'b2-autoplay', title: 'La reproducción automática', group: 'Comodidad y autonomía',
    intro: 'Cada capítulo, canción y video termina de verdad. Para seguir, hay que elegir de nuevo.',
    question: '¿Eliminarías una comodidad que te hace perder la noción del tiempo, aunque también te permita descubrir cosas sin buscarlas?',
    consequence: 'Una persona que cocina con las manos ocupadas ya no puede escuchar una lista seguida. Las canciones de artistas desconocidos dejan de llegar a oyentes nuevos.',
    followUp: 'Describe una ocasión en que seguir mirando fue una elección tuya y otra en que simplemente te dejaste llevar.',
    counterpoint: 'Una cantante dice: «Sin esa función solo escucharán a quienes ya conocen». ¿Qué parte de su argumento aceptarías?',
    revision: '¿Mantienes la eliminación o conservarías la función bajo una condición concreta que el usuario pueda controlar?',
    words: ['dejarse llevar', 'interrumpir', 'por defecto', 'dar a conocer'], starter: 'Acepto que facilita…, pero dejaría de apoyarlo si…',
  },
  {
    id: 'b2-claves', title: 'Las contraseñas', group: 'Comodidad y autonomía',
    intro: 'Nadie vuelve a recordar claves. Para entrar en una cuenta solo se usa el rostro o la huella.',
    question: '¿Eliminarías las contraseñas a cambio de depender de una parte de tu cuerpo para demostrar quién eres?',
    consequence: 'Tu padre entra en sus cuentas sin pedir ayuda. Sin embargo, el lector de una estación no reconoce a tu hermana y nadie puede prestarle una clave de emergencia.',
    followUp: 'Al recuperar una cuenta, ¿preferirías más comprobaciones o una solución inmediata? Explica qué riesgo asumirías.',
    counterpoint: 'La estación afirma que añadir otra forma de acceso debilitaría el sistema. ¿Es suficiente esa razón para dejar fuera a alguien?',
    revision: 'Decide qué alternativa tendría que existir antes de mantener tu primera postura.',
    words: ['huella', 'comprobar la identidad', 'recuperar el acceso', 'fallar'], starter: 'La comodidad me convence siempre que exista…',
  },
  {
    id: 'b2-renovaciones', title: 'Las renovaciones automáticas', group: 'Comodidad y autonomía',
    intro: 'Cada mes hay que confirmar a mano las suscripciones y los servicios contratados.',
    question: '¿Eliminarías las renovaciones automáticas para evitar pagos olvidados, incluso si eso pone en riesgo servicios que sí necesitas?',
    consequence: 'Ahorras varias cuotas inútiles. Durante unas vacaciones olvidas confirmar el almacenamiento de fotos y se suspende el acceso a tu archivo familiar.',
    followUp: 'Compara la responsabilidad del cliente con la del servicio cuando cancelar cuesta mucho más que contratar.',
    counterpoint: 'Una persona que cuida a un familiar dice que no puede revisar veinte contratos al mes. ¿Cómo cambia eso tu propuesta?',
    revision: 'Defiende una decisión final y distingue qué servicios, si alguno, merecerían un trato diferente.',
    words: ['cuota', 'dar de baja', 'vencimiento', 'confirmación'], starter: 'Distinguiría entre un servicio esencial y…',
  },
  {
    id: 'b2-rutas', title: 'Las rutas sugeridas por el mapa', group: 'Comodidad y autonomía',
    intro: 'Los mapas muestran calles y distancias, pero ya no indican por dónde conviene ir.',
    question: '¿Eliminarías las rutas sugeridas para recuperar la capacidad de orientarte, aunque llegar a un lugar nuevo sea más difícil?',
    consequence: 'Vuelves a reconocer tu barrio. Una compañera con movilidad reducida descubre que el mapa ya no evita las escaleras y pierde una cita importante.',
    followUp: 'Explica cuándo seguir una indicación te libera para hacer otra cosa y cuándo te vuelve demasiado dependiente.',
    counterpoint: 'Tu compañera no quiere una lección de orientación: quiere poder llegar. Responde desde esa necesidad.',
    revision: '¿Cambias tu voto o propones una forma concreta de conservar la autonomía sin perder accesibilidad?',
    words: ['orientarse', 'desvío', 'accesibilidad', 'depender de'], starter: 'Para mí sería…, mientras que para alguien que…',
  },
  {
    id: 'b2-filtros', title: 'Los filtros de apariencia en videollamadas', group: 'Comodidad y autonomía',
    intro: 'Las cámaras dejan de suavizar la piel y modificar la cara. Los fondos virtuales siguen existiendo.',
    question: '¿Eliminarías estos filtros para reducir la presión por verse perfecto, aunque algunas personas hablen con más confianza gracias a ellos?',
    consequence: 'En tu equipo se normalizan las caras cansadas. Una colega con una marca visible en el rostro empieza a evitar las reuniones con cámara.',
    followUp: '¿Dónde situarías la diferencia entre sentirse cómodo y sentir que tienes que ocultarte para participar?',
    counterpoint: 'La colega te pide que no decidas por ella qué imagen es auténtica. ¿Qué le responderías?',
    revision: 'Formula tu decisión final sin convertir tu preferencia personal en una obligación para todos.',
    words: ['retocar', 'presión', 'ocultar', 'participar'], starter: 'No daría por hecho que quien usa un filtro…',
  },
  {
    id: 'b2-cajas', title: 'Las cajas de autoservicio', group: 'Comodidad y autonomía',
    intro: 'En cada compra vuelve a atenderte una persona, incluso cuando llevas un solo producto.',
    question: '¿Eliminarías las cajas de autoservicio para conservar el trato humano y puestos de trabajo, aceptando compras más lentas?',
    consequence: 'Una clienta recibe ayuda para entender una oferta. La tienda nocturna reduce su horario porque no puede cubrir todos los turnos.',
    followUp: '¿Qué parte de una compra merece atención personal y qué parte delegarías sin echarla de menos?',
    counterpoint: 'Un trabajador prefería ayudar en la sala a repetir el mismo cobro toda la noche. ¿Tu idea de protegerlo coincide con la suya?',
    revision: 'Sostén o cambia tu decisión incluyendo tanto las condiciones laborales como las necesidades de los clientes.',
    words: ['autoservicio', 'cubrir un turno', 'trato personal', 'agilizar'], starter: 'Conservar empleos no basta si esos empleos…',
  },
  {
    id: 'b2-reparto', title: 'Las entregas en el mismo día', group: 'Comodidad y autonomía',
    intro: 'Cualquier pedido tarda al menos dos días. La máquina no distingue entre un capricho y una necesidad.',
    question: '¿Eliminarías la entrega inmediata para reducir las prisas del reparto, aunque a veces resuelva una urgencia real?',
    consequence: 'Los repartidores de esta ciudad tienen horarios más previsibles. Una familia no consigue a tiempo una pieza para arreglar la nevera y pierde la comida de la semana.',
    followUp: 'Explica qué urgencia considerarías razonable pagar y cuál crees que hemos aprendido a inventarnos.',
    counterpoint: 'La familia vive lejos de las tiendas y no tiene coche. ¿Sigue siendo justa una espera idéntica para todos?',
    revision: 'Elige entre conservar o eliminar y añade qué responsabilidad asumirías como comprador.',
    words: ['plazo', 'capricho', 'avería', 'condiciones de trabajo'], starter: 'Reduciría las prisas, pero no a costa de…',
  },
  {
    id: 'b2-tarjetas', title: 'Los puntos de fidelidad', group: 'Comodidad y autonomía',
    intro: 'Desaparecen las tarjetas de puntos y los descuentos a cambio de registrar tus compras.',
    question: '¿Eliminarías un ahorro que depende de compartir tus hábitos, aunque otras personas necesiten esos descuentos para llegar a fin de mes?',
    consequence: 'Ya no entregas datos por cada compra. Una vecina paga más por los mismos alimentos y considera que tu victoria por la privacidad le sale cara.',
    followUp: '¿Se elige libremente compartir datos cuando rechazarlo supone renunciar a un ahorro importante?',
    counterpoint: 'La tienda ofrece el descuento a todos si sube el precio de otros productos. ¿Quién termina pagando?',
    revision: 'Explica si el giro cambia tu voto y qué alternativa repartiría mejor el coste.',
    words: ['hábitos de consumo', 'descuento', 'renunciar', 'llegar a fin de mes'], starter: 'Hay una elección, aunque no todos pueden permitirse…',
  },
  {
    id: 'b2-audios', title: 'Los mensajes de voz', group: 'Comodidad y autonomía',
    intro: 'Las conversaciones a distancia siguen por llamada o texto, pero no se pueden enviar audios grabados.',
    question: '¿Eliminarías los audios largos para respetar el tiempo de quien escucha, aunque escribir resulte difícil para quien los manda?',
    consequence: 'Dejas de escuchar instrucciones interminables. Tu abuelo, que ve mal la pantalla, participa mucho menos en el grupo familiar.',
    followUp: 'Negocia una norma para un grupo donde unos contestan caminando y otros leen durante el trabajo.',
    counterpoint: 'Tu abuelo dice que no quiere llamar porque teme interrumpir. ¿Qué posibilidad de comunicación pierde?',
    revision: 'Reconsidera si el problema exige eliminar el formato o cambiar una costumbre de uso.',
    words: ['interrumpir', 'resumir', 'acordar', 'mensaje pendiente'], starter: 'El problema no aparece cuando…, sino cuando…',
  },
  {
    id: 'b2-traduccion', title: 'La traducción instantánea del móvil', group: 'Comodidad y autonomía',
    intro: 'Puedes seguir consultando diccionarios y aprendiendo idiomas, pero el teléfono ya no traduce conversaciones al momento.',
    question: '¿Eliminarías una ayuda que a veces frena el esfuerzo por aprender, aunque permita comunicarse desde el primer día?',
    consequence: 'Practicas más en tus viajes. Una persona recién llegada no entiende una reunión sobre el colegio de su hijo y no puede explicar una preocupación.',
    followUp: 'Compara tu experiencia como estudiante con la de alguien que necesita resolver un problema hoy.',
    counterpoint: 'La profesora puede esperar a que mejores tu español; el problema del colegio no. ¿Qué prioridad defenderías?',
    revision: 'Aclara si mantienes tu decisión y qué apoyo ofrecerías en la situación del giro.',
    words: ['hacerse entender', 'matiz', 'resolver', 'apoyo'], starter: 'Aprender sería deseable, pero mientras tanto…',
  },
  {
    id: 'b2-reservas', title: 'Las reservas en restaurantes', group: 'Convivir y repartir',
    intro: 'Todos los restaurantes atienden por orden de llegada. Nadie puede guardar una mesa.',
    question: '¿Eliminarías las reservas para dejar espacio a planes espontáneos, aunque organizar una salida en grupo sea menos seguro?',
    consequence: 'Encuentras mesa un sábado sin planear nada. Un grupo que viajó una hora para celebrar un cumpleaños termina comiendo por separado.',
    followUp: '¿Sería razonable que una mesa vacía esperara a alguien que aún no ha llegado? Defiende un límite de tiempo.',
    counterpoint: 'El dueño compró comida contando con las reservas y ahora no sabe cuánta gente vendrá. Considera también su riesgo.',
    revision: '¿Tu voto sigue siendo el mismo si tú organizas la celebración o gestionas el restaurante?',
    words: ['prever', 'mesa libre', 'plantar a alguien', 'margen'], starter: 'Desde el punto de vista de quien organiza…',
  },
  {
    id: 'b2-plazas', title: 'Las plazas de aparcamiento reservadas a residentes', group: 'Convivir y repartir',
    intro: 'Cualquier persona puede aparcar en cualquier plaza pública, viva donde viva.',
    question: '¿Eliminarías la prioridad de los residentes porque la calle es de todos, aunque quienes viven allí pierdan comodidad?',
    consequence: 'Una cuidadora que viene de otro barrio encuentra dónde dejar el coche. Un vecino que vuelve del turno de noche tiene que aparcar a veinte minutos de casa.',
    followUp: 'Compara la necesidad de vivir cerca, trabajar allí y visitar a alguien antes de proponer un criterio.',
    counterpoint: 'El vecino propone dar prioridad a quien trabaja de noche; la cuidadora trabaja de día. ¿Basta el horario para decidir?',
    revision: 'Justifica tu voto final con un criterio que puedas aplicar también a alguien que no conoces.',
    words: ['residente', 'prioridad', 'necesidad', 'criterio'], starter: 'Daría prioridad según…, en lugar de fijarme solo en…',
  },
  {
    id: 'b2-depositos', title: 'Las fianzas para alquilar', group: 'Convivir y repartir',
    intro: 'Al alquilar una vivienda no se entrega dinero como garantía. Los daños siguen siendo responsabilidad de quien los causa.',
    question: '¿Eliminarías la fianza para facilitar las mudanzas, aunque el propietario se quede sin una garantía inmediata?',
    consequence: 'Una pareja puede entrar en su primera casa. En este escenario, una propietaria empieza a aceptar solo a personas con sueldos altos para sentirse segura.',
    followUp: 'Distingue entre una protección razonable y una barrera que deja fuera a quien puede pagar el alquiler mensual.',
    counterpoint: 'La propietaria alquila una sola vivienda y necesita ese ingreso. ¿Cambiaría tu argumento si fuera una gran empresa?',
    revision: 'Mantén o revisa tu decisión proponiendo quién asumiría el riesgo sin trasladarlo a los candidatos con menos recursos.',
    words: ['fianza', 'garantía', 'mudanza', 'asumir un riesgo'], starter: 'Entiendo que quiera protegerse; aun así…',
  },
  {
    id: 'b2-terrazas', title: 'Las terrazas en las aceras', group: 'Convivir y repartir',
    intro: 'Los bares conservan sus mesas interiores, pero dejan de ocupar las aceras.',
    question: '¿Eliminarías las terrazas para recuperar espacio de paso, aunque sean un lugar de encuentro y sostengan pequeños negocios?',
    consequence: 'Tu vecina circula mejor con su silla de ruedas. El café donde se reunía un grupo de jubilados pierde mesas y sube los precios.',
    followUp: 'Describe una acera concreta y explica qué usos deberían caber en ella antes de decidir.',
    counterpoint: 'Los jubilados también necesitan un sitio accesible para encontrarse. ¿Cómo evitarías enfrentar dos necesidades legítimas?',
    revision: 'Presenta tu decisión con un límite de espacio o una alternativa que estés dispuesto a defender ante ambos grupos.',
    words: ['paso libre', 'ocupar', 'convivencia', 'aforo'], starter: 'Compartir el espacio sería posible a condición de que…',
  },
  {
    id: 'b2-uniformidad', title: 'Los catálogos únicos de las grandes cadenas', group: 'Convivir y repartir',
    intro: 'Cada sucursal elige productos propios. Ya no encuentras exactamente lo mismo en cualquier ciudad.',
    question: '¿Eliminarías los catálogos idénticos para dar espacio a productos locales, aunque perder esa previsibilidad complique algunas compras?',
    consequence: 'Descubres creaciones de tu zona. Una viajera con necesidades alimentarias específicas ya no encuentra el producto que sabía que podía comprar.',
    followUp: 'Cuenta qué te gusta reconocer en un lugar nuevo y qué prefieres que sea diferente.',
    counterpoint: 'Un pequeño proveedor agradece la oportunidad, pero no puede garantizar existencias todo el año. ¿Aceptarías esa incertidumbre?',
    revision: 'Concreta qué variedad merece la pena ganar y qué continuidad protegerías al tomar tu decisión final.',
    words: ['existencias', 'proveedor', 'previsible', 'producto local'], starter: 'La variedad aporta…, aunque para algunas personas…',
  },
  {
    id: 'b2-bodas', title: 'Los regalos obligatorios por costumbre', group: 'Convivir y repartir',
    intro: 'En bodas, cumpleaños y otras celebraciones nadie espera un regalo. Todavía puedes dar uno por iniciativa propia.',
    question: '¿Eliminarías la obligación social de regalar para que todos puedan asistir sin gastar, aunque algunas celebraciones cuenten con esa ayuda?',
    consequence: 'Vas a más celebraciones sin preocuparte por el coste. Una pareja había elegido un lugar pequeño confiando en que los regalos ayudarían a pagarlo y tiene que cancelar.',
    followUp: '¿En qué momento un detalle deja de ser libre si todos los demás lo hacen? Pon un ejemplo concreto.',
    counterpoint: 'La pareja dice que recibir ayuda forma parte de celebrar en comunidad. ¿Lo entiendes como apoyo o como una entrada encubierta?',
    revision: 'Defiende una costumbre alternativa que conserve el apoyo sin excluir a nadie por su presupuesto.',
    words: ['compromiso social', 'detalle', 'presupuesto', 'dar por hecho'], starter: 'Me parece valioso apoyar, siempre que no se presuponga…',
  },
  {
    id: 'b2-turnos', title: 'Las citas previas obligatorias', group: 'Convivir y repartir',
    intro: 'Se puede acudir a cualquier oficina de atención sin reservar. Los servicios mantienen su horario y su personal.',
    question: '¿Eliminarías la cita previa para que nadie quede fuera por no saber reservar, aceptando una atención menos previsible?',
    consequence: 'Una persona sin internet consigue hacer su trámite. Otra pierde media jornada de sueldo porque no sabe cuánto tendrá que esperar.',
    followUp: 'Compara quién puede esperar en persona y quién puede competir por una cita en línea.',
    counterpoint: 'La oficina dice que con el mismo personal no puede ofrecer atención inmediata a todos. ¿Qué promesa sería honesta?',
    revision: 'Explica qué acceso garantizarías antes de mantener o cambiar tu decisión.',
    words: ['trámite', 'atender', 'previsible', 'perder el turno'], starter: 'Abrir el acceso no resuelve por sí solo…',
  },
  {
    id: 'b2-recomendaciones', title: 'Las recomendaciones personales para conseguir empleo', group: 'Convivir y repartir',
    intro: 'Nadie puede presentar a un conocido para un puesto. Solo cuentan las candidaturas enviadas por los canales abiertos.',
    question: '¿Eliminarías las recomendaciones para ampliar las oportunidades, aunque se pierda información valiosa sobre cómo trabaja alguien?',
    consequence: 'Una candidata sin contactos llega a la entrevista. Una persona que retoma su carrera después de años de cuidados no puede contar con quien conoce sus capacidades.',
    followUp: '¿Qué información de una recomendación sería útil y cuál solo reproduce la ventaja de conocer a alguien?',
    counterpoint: 'El encargado no tiene tiempo para revisar cientos de solicitudes. ¿La falta de tiempo justifica recurrir a su círculo?',
    revision: 'Formula una decisión que distinga entre aportar referencias y saltarse el proceso.',
    words: ['contactos', 'candidatura', 'referencia', 'retomar'], starter: 'No equipararía demostrar experiencia con…',
  },
  {
    id: 'b2-tareas', title: 'Las tareas escolares en casa', group: 'Convivir y repartir',
    intro: 'Todo el trabajo escolar se hace dentro del horario de clase. Fuera de él, cada estudiante decide qué practicar.',
    question: '¿Eliminarías las tareas para igualar el tiempo libre, aunque algunos estudiantes necesiten practicar más de lo que permite la clase?',
    consequence: 'Quien ayudaba a cuidar hermanos puede descansar. Las familias que pueden pagar clases particulares siguen consiguiendo práctica extra para sus hijos.',
    followUp: 'Explica qué debería poder resolverse en clase y qué aprendizaje depende de ensayar a solas.',
    counterpoint: 'Una estudiante pide ejercicios porque disfruta aprendiendo por su cuenta. ¿Tu propuesta limitaría también esa elección?',
    revision: 'Revisa si tu decisión reduce la desigualdad o simplemente cambia el lugar donde aparece.',
    words: ['reforzar', 'tiempo disponible', 'apoyo familiar', 'práctica'], starter: 'Eliminar la obligación ayudaría a…, pero no garantizaría…',
  },
  {
    id: 'b2-descuentos', title: 'Los descuentos por comprar grandes cantidades', group: 'Convivir y repartir',
    intro: 'Una unidad cuesta lo mismo tanto si compras una como si compras veinte.',
    question: '¿Eliminarías los descuentos por volumen para que ahorrar no dependa de tener dinero y espacio de sobra?',
    consequence: 'Una persona que vive sola paga menos por unidad. Un comedor vecinal deja de recibir su descuento habitual y puede preparar menos raciones.',
    followUp: '¿Qué diferencia harías entre comprar de más para ahorrar y comprar mucho para cubrir una necesidad real?',
    counterpoint: 'El proveedor dice que preparar un pedido grande le cuesta menos que preparar veinte pequeños. ¿Quién debería beneficiarse de ese ahorro?',
    revision: 'Defiende tu voto final explicando si aceptarías una excepción y cómo evitarías que se usara como excusa.',
    words: ['por unidad', 'ración', 'almacenar', 'volumen'], starter: 'La misma tarifa parece justa hasta que…',
  },
  {
    id: 'b2-reparaciones', title: 'Las reparaciones exclusivas del fabricante', group: 'Elegir con consecuencias',
    intro: 'Cualquier taller puede reparar cualquier aparato y obtener sus piezas e instrucciones.',
    question: '¿Eliminarías la exclusividad de reparación para alargar la vida de los aparatos, aunque aumente la dificultad de controlar la calidad?',
    consequence: 'Arreglas tu teléfono a buen precio. Después de una reparación defectuosa, el fabricante y el taller se culpan y nadie responde por el daño.',
    followUp: 'Compara la libertad de elegir taller con la tranquilidad de saber quién responde si algo falla.',
    counterpoint: 'El taller pequeño propone mostrar su experiencia en lugar de pagar una certificación cara. ¿Qué prueba te bastaría?',
    revision: 'Concreta qué garantía necesitarías para conservar o cambiar tu primera decisión.',
    words: ['repuesto', 'garantía', 'hacerse cargo', 'vida útil'], starter: 'Abriría la reparación, pero exigiría que…',
  },
  {
    id: 'b2-envases', title: 'Los envases de un solo uso', group: 'Elegir con consecuencias',
    intro: 'Toda compra necesita un recipiente reutilizable. La eliminación incluye los pequeños envases individuales.',
    question: '¿Eliminarías todos los envases de un solo uso para reducir residuos, aunque llevar y limpiar recipientes no resulte sencillo para todos?',
    consequence: 'El barrio produce menos basura. Una asociación que reparte comidas debe dedicar parte de su presupuesto a recoger y lavar recipientes en vez de cocinar.',
    followUp: 'Describe quién haría el trabajo extra en tu casa, una cafetería y un servicio de comidas solidario.',
    counterpoint: 'Una voluntaria pregunta por qué su organización debe resolver un problema creado por muchos. ¿Cómo repartirías la responsabilidad?',
    revision: '¿Mantienes la eliminación total o la modificas al considerar el tiempo, la limpieza y el acceso?',
    words: ['reutilizar', 'recoger', 'residuos', 'coste compartido'], starter: 'El beneficio es colectivo; por eso el esfuerzo…',
  },
  {
    id: 'b2-camaras', title: 'Las cámaras en las entradas de los edificios', group: 'Elegir con consecuencias',
    intro: 'Las entradas dejan de grabar a residentes, visitas y repartidores. Los porteros y las cerraduras siguen funcionando.',
    question: '¿Eliminarías esas cámaras para proteger los movimientos de las personas, aunque ayuden a aclarar incidentes?',
    consequence: 'Nadie puede reconstruir tus visitas. Desaparecen varios paquetes y una repartidora recibe la culpa sin imágenes que permitan comprobar qué pasó.',
    followUp: '¿Quién debería poder ver una grabación y por cuánto tiempo te parecería razonable guardarla?',
    counterpoint: 'La repartidora pide una prueba que la proteja; un vecino teme que se vigile a sus visitas. Da una respuesta a ambos.',
    revision: 'Señala qué límite verificable te haría mantener o cambiar tu voto.',
    words: ['grabación', 'acceso', 'comprobar', 'intimidad'], starter: 'Aceptaría esa medida únicamente si…',
  },
  {
    id: 'b2-entradas', title: 'La reventa de entradas', group: 'Elegir con consecuencias',
    intro: 'Quien compra una entrada solo puede usarla o devolverla al organizador por el precio original.',
    question: '¿Eliminarías la reventa para evitar precios abusivos, aunque se reduzcan las formas de recuperar dinero cuando cambian tus planes?',
    consequence: 'Dejan de aparecer entradas a precios desorbitados. El organizador cierra las devoluciones un día antes y tu amiga pierde el dinero al enfermarse esa mañana.',
    followUp: 'Distingue entre comprar para revender y transferir una entrada que ya no puedes usar.',
    counterpoint: 'Un aficionado pagaría más por ir a su único concierto del año. ¿Su libertad de pagar pesa más que el efecto sobre los precios?',
    revision: 'Define qué conducta quieres impedir y comprueba si tu decisión castiga también a quien no la practica.',
    words: ['devolución', 'transferir', 'precio original', 'abusivo'], starter: 'Mi objeción no es que alguien recupere…, sino que…',
  },
  {
    id: 'b2-propinas', title: 'Las propinas', group: 'Elegir con consecuencias',
    intro: 'La cuenta incluye todo el pago. No se puede dejar dinero extra por el servicio.',
    question: '¿Eliminarías las propinas para que el sueldo no dependa de agradar al cliente, aunque algunos trabajadores pierdan ingresos?',
    consequence: 'El personal deja de fingir simpatía para ganar más. En este escenario, los salarios no suben y una camarera gana bastante menos que antes.',
    followUp: '¿A quién le correspondería compensar esa diferencia y cuánto más estarías dispuesto a pagar en la cuenta?',
    counterpoint: 'La camarera prefería un sistema imperfecto con ingresos mayores. ¿Puedes defender el cambio sin ignorar su pérdida inmediata?',
    revision: 'Aclara si apoyarías la eliminación hoy o solo después de un cambio concreto en las condiciones de trabajo.',
    words: ['ingresos', 'compensar', 'sueldo fijo', 'transición'], starter: 'A largo plazo defendería…, pero antes habría que…',
  },
  {
    id: 'b2-caducidad', title: 'La fecha de consumo preferente', group: 'Elegir con consecuencias',
    intro: 'Desaparece esa indicación de calidad de los alimentos; las fechas de caducidad por seguridad se mantienen.',
    question: '¿Eliminarías una fecha que puede llevar a tirar comida aprovechable, aunque ayude a elegir productos?',
    consequence: 'En esta simulación se tira menos comida. Una tienda vende productos de calidad muy desigual y el cliente no sabe si el precio reducido compensa.',
    followUp: '¿Qué información necesitarías para decidir sin que una fecha lo resolviera todo por ti?',
    counterpoint: 'Una persona con poco dinero dice que no puede arriesgarse a comprar algo que luego no le guste. ¿Tu propuesta le exige asumir más riesgo?',
    revision: 'Decide si eliminar la información resuelve el problema o si cambiarías la manera de explicarla.',
    words: ['desperdiciar', 'calidad', 'aprovechable', 'etiqueta'], starter: 'No confundiría una orientación sobre calidad con…',
  },
  {
    id: 'b2-devoluciones', title: 'Las devoluciones gratuitas de ropa', group: 'Elegir con consecuencias',
    intro: 'Devolver una prenda cuesta dinero, salvo si llegó defectuosa. Puedes seguir probándotela en una tienda.',
    question: '¿Eliminarías las devoluciones gratis para reducir pedidos innecesarios, aunque comprar sin probar sea la única opción de algunas personas?',
    consequence: 'La gente pide menos tallas por si acaso. Un comprador que no encuentra su talla en tiendas cercanas empieza a pagar cada error de medidas.',
    followUp: 'Distingue una compra impulsiva de una prueba necesaria cuando las tallas cambian entre marcas.',
    counterpoint: 'La marca reconoce que sus medidas son poco claras. ¿Debería asumir el coste aunque la prenda no sea defectuosa?',
    revision: 'Explica tu decisión final repartiendo responsabilidades entre la tienda y quien compra.',
    words: ['devolver', 'medidas', 'por si acaso', 'gastos de envío'], starter: 'Cobrar lo mismo no sería justo si…',
  },
  {
    id: 'b2-estrellas', title: 'Los premios al mejor empleado del mes', group: 'Elegir con consecuencias',
    intro: 'Se reconoce el trabajo de los equipos, pero nadie recibe un premio individual mensual.',
    question: '¿Eliminarías ese premio para favorecer la colaboración, aunque algunas personas sientan que su esfuerzo deja de verse?',
    consequence: 'El equipo comparte más información. Una compañera que siempre cubre ausencias recibe el mismo reconocimiento que quien aporta muy poco y deja de ofrecerse.',
    followUp: 'Propón una forma de reconocer el esfuerzo sin convertir la ayuda entre compañeros en una competición.',
    counterpoint: 'Otro compañero hace tareas discretas que no cuentan para el premio. ¿Cómo sabrías quién merece reconocimiento?',
    revision: 'Revisa tu voto atendiendo tanto al trabajo visible como al que permite que los demás destaquen.',
    words: ['reconocimiento', 'esfuerzo', 'colaborar', 'pasar desapercibido'], starter: 'Reconocer a una persona sería razonable si también…',
  },
  {
    id: 'b2-multas', title: 'Las multas de las bibliotecas', group: 'Elegir con consecuencias',
    intro: 'No se cobra dinero por devolver tarde un libro. El compromiso de devolverlo sigue existiendo.',
    question: '¿Eliminarías las multas para que una deuda pequeña no aleje a nadie de la biblioteca, aunque otros lectores esperen el libro?',
    consequence: 'Vuelven usuarios que antes evitaban la biblioteca. El único ejemplar de una novela necesaria para un club de lectura llega varias semanas tarde.',
    followUp: '¿Qué respuesta distinguiría un olvido ocasional de retener libros repetidamente?',
    counterpoint: 'Una lectora propone suspender los préstamos; otra dice que eso también excluye. Compara las dos consecuencias.',
    revision: 'Defiende tu voto final con una medida que permita reparar el retraso sin ignorar a quienes esperan.',
    words: ['préstamo', 'retraso', 'ejemplar', 'reparar el daño'], starter: 'La respuesta debería ser proporcional a…',
  },
  {
    id: 'b2-telefonos', title: 'Los menús telefónicos automáticos', group: 'Elegir con consecuencias',
    intro: 'Al llamar a una empresa siempre responde una persona. Desaparecen las opciones de pulsar números.',
    question: '¿Eliminarías esos menús para explicar tu problema directamente, aunque las consultas sencillas tarden más?',
    consequence: 'Una usuaria que nunca encontraba la opción correcta recibe ayuda. Durante una avería, cientos de personas esperan para pedir el mismo dato básico.',
    followUp: 'Compara cómo querrías ser atendido si buscas un horario y si necesitas explicar un cobro inesperado.',
    counterpoint: 'Una trabajadora dice que repetir horarios le quita tiempo para resolver casos difíciles. ¿Qué función humana quieres proteger realmente?',
    revision: 'Cierra el experimento: ¿qué conservarías, qué eliminarías y qué has aprendido sobre decidir por otras personas?',
    words: ['derivar una llamada', 'espera', 'consulta', 'atención personalizada'], starter: 'Después de escuchar ambas necesidades, matizaría mi postura así:…',
  },
];

export const absurdRulesB2: AbsurdRuleB2[] = [
  {
    id: 'b2-semaforos', title: 'El semáforo escucha', group: 'La ciudad se mete en tu vida',
    law: 'Los semáforos solo se ponen en verde cuando dos desconocidos que esperan han encontrado algo en común. Si hay una sola persona, pasan a verde solos.',
    scene: 'Llegas tarde. La persona que espera contigo no tiene ganas de hablar, pero detrás ya se forma un grupo.',
    questions: [
      '¿Qué intentarías compartir para avanzar sin convertir una conversación amable en un interrogatorio?',
      'Una vecina disfruta conociendo gente y otra vive la charla obligatoria como una invasión. ¿Qué solución tomaría en serio a las dos?',
      'La gente empieza a repetir «nos gusta el pan» sin escucharse. ¿Reformarías la regla, aceptarías el truco o la eliminarías? Defiende tu decisión.',
    ],
    teacherFollowUp: 'Pide que negocien un tiempo máximo de espera y una excepción para quien no pueda o no quiera hablar.',
    words: ['romper el hielo', 'invadir', 'ganar tiempo', 'salida alternativa'], starter: 'La intención me parece buena, aunque obligar a…',
  },
  {
    id: 'b2-ascensor', title: 'El ascensor negocia', group: 'La ciudad se mete en tu vida',
    law: 'El ascensor de cada edificio solo se mueve cuando sus ocupantes acuerdan el orden de las paradas. No decide por ellos.',
    scene: 'Una persona lleva comida que se enfría, otra va con un bebé dormido y una tercera tiene una entrega urgente.',
    questions: [
      'Propón un orden de paradas y explica qué necesidad has considerado primero; otra persona debe intentar convencerte de cambiarlo.',
      'Una vecina callada siempre acepta el plan de los demás y tarda más en llegar. ¿Un acuerdo es justo solo porque nadie protesta?',
      'El edificio quiere fijar una norma para evitar negociar cada viaje. Diseña una excepción razonable y explica quién podría activarla.',
    ],
    teacherFollowUp: 'Cambia los papeles después del primer acuerdo: quien defendía la rapidez ahora representa a la vecina que nunca reclama.',
    words: ['ceder', 'priorizar', 'dar por aceptado', 'turnarse'], starter: 'Aceptaría ese orden, siempre que la próxima vez…',
  },
  {
    id: 'b2-sombras', title: 'La sombra pide descanso', group: 'La ciudad se mete en tu vida',
    law: 'Cuando llevas tres horas sin descansar, tu sombra se sienta y te impide alejarte más de dos metros durante quince minutos.',
    scene: 'Tu sombra se sienta justo antes de que llegue el autobús. La conductora también está a punto de cumplir sus tres horas.',
    questions: [
      '¿Cómo reorganizarías tu mañana para aprovechar el descanso sin perder compromisos importantes?',
      'Compara la situación de alguien con horario flexible y la de quien atiende a otras personas. ¿Quién necesita apoyo para cumplir la misma regla?',
      'La ciudad propone comprar minutos extra de actividad. Decide si lo permitirías y negocia una excepción que no dependa de tener dinero.',
    ],
    teacherFollowUp: 'Solicita un plan de sustituciones: una excepción que diga solo «en emergencias» necesita explicar qué cuenta como emergencia.',
    words: ['relevo', 'pausa', 'aplazar', 'horario flexible'], starter: 'El descanso sería un derecho real si…',
  },
  {
    id: 'b2-paraguas', title: 'La lluvia se vota', group: 'La ciudad se mete en tu vida',
    law: 'Cada calle elige por votación a qué hora llueve durante veinte minutos. El agua nunca cruza a la calle de al lado.',
    scene: 'Los comerciantes quieren lluvia de madrugada; quienes limpian la calle trabajan precisamente a esa hora.',
    questions: [
      'Elige una hora para tu calle y describe una consecuencia práctica que asumirías personalmente.',
      'Los trabajadores de limpieza no viven allí y no pueden votar. ¿A quién darías voz en una decisión que afecta también a visitantes y trabajadores?',
      'Una mayoría fija siempre el horario que perjudica al mismo grupo. Revisa el sistema para repartir la molestia sin tener que votar cada hora.',
    ],
    teacherFollowUp: 'Pide una propuesta con duración de prueba y un motivo concreto por el que aceptarían revisarla.',
    words: ['repartir la carga', 'mayoría', 'tener voz', 'rotación'], starter: 'Aunque la mayoría prefiera…, habría que escuchar a…',
  },
  {
    id: 'b2-bancos', title: 'Los bancos salen a pasear', group: 'La ciudad se mete en tu vida',
    law: 'Los bancos públicos caminan diez metros por hora hacia donde oyen más risas. Solo se detienen cuando alguien está sentado.',
    scene: 'Los bancos de una plaza tranquila se acercan a una terraza animada. Una persona mayor llega a descansar y no encuentra ninguno.',
    questions: [
      '¿Seguirías a los bancos, intentarías atraerlos o reservarías uno? Explica cómo cambia tu idea de una plaza agradable.',
      'Quien busca silencio pierde asientos frente a quien hace ruido. ¿Qué necesidad debería orientar el mobiliario de la ciudad?',
      'Un bar contrata a gente para reír y atraer todos los bancos. Propón una reforma que conserve el juego y garantice un lugar para descansar.',
    ],
    teacherFollowUp: 'Pregunta quién se encargaría de devolver los bancos y qué ocurriría en un barrio sin terrazas.',
    words: ['atraer', 'descansar', 'apropiarse', 'espacio compartido'], starter: 'La regla sería divertida mientras no impidiera…',
  },
  {
    id: 'b2-bolsillos', title: 'El bolsillo revela el precio', group: 'Pequeños poderes, grandes líos',
    law: 'Al tocar un objeto ajeno, aparece sobre él el precio que pagó su dueño. No se puede ocultar ni saber dónde lo compró.',
    scene: 'En una cena descubres que dos personas pagaron cantidades muy distintas por el mismo abrigo.',
    questions: [
      '¿Comentarías la diferencia o guardarías silencio? Explica qué información útil podrías compartir sin avergonzar a nadie.',
      'Una tienda dice que comparar precios ayuda; tu amiga dice que la regla convierte cada regalo en una cuenta. ¿En qué situaciones cambia el valor de saber?',
      'Alguien usa la regla para decidir a quién invitar a su grupo. ¿Qué límite pondrías al poder y cómo evitarías que perjudicara a quien tiene menos?',
    ],
    teacherFollowUp: 'Invita a revisar la postura imaginando que aparece el precio de algo usado o recibido como regalo.',
    words: ['ganga', 'valor sentimental', 'comparar', 'exponer'], starter: 'Saber el precio sería útil para…, pero no autoriza a…',
  },
  {
    id: 'b2-desorden', title: 'El desorden se muda', group: 'Pequeños poderes, grandes líos',
    law: 'A medianoche, todo objeto que no has guardado aparece en la habitación de una persona elegida al azar. Debe devolvértelo al día siguiente.',
    scene: 'Te despiertas entre juguetes ajenos y apuntes de un examen. Tú habías dejado una taza y un abrigo fuera de lugar.',
    questions: [
      '¿Cómo organizarías las devoluciones sin perder toda la mañana? Justifica qué objetos devolverías antes.',
      'Una familia con niños genera más desorden que una persona que vive sola. ¿Aplicarles exactamente la misma regla reparte justamente el trabajo?',
      'Alguien deja regalos sin guardar para que lleguen a desconocidos. Decide qué usos permitirías y qué cambiarías para no convertir a otros en mensajeros.',
    ],
    teacherFollowUp: 'Haz que definan «fuera de lugar» cuando una persona está trabajando en un proyecto que ocupa toda la mesa.',
    words: ['hacerse cargo', 'devolver', 'carga extra', 'intención'], starter: 'Antes de culpar a quien dejó…, tendría en cuenta…',
  },
  {
    id: 'b2-boton', title: 'Repetir los últimos cinco minutos', group: 'Pequeños poderes, grandes líos',
    law: 'Una vez al día puedes repetir los últimos cinco minutos. Todas las personas presentes recuerdan las dos versiones, pero solo cuenta la segunda.',
    scene: 'Respondes mal en una reunión y quieres corregirte. Una compañera acababa de anunciar una buena noticia y no quiere repetirla.',
    questions: [
      '¿Usarías tu repetición o repararías lo dicho conversando? Compara lo que ganarías y lo que no conseguirías borrar.',
      'Un vendedor repite una negociación cuando el cliente ya había conseguido un buen precio. ¿A quién debería pertenecer la decisión de repetir?',
      'Propón un acuerdo sobre cuándo hace falta permiso de los demás y defiende una excepción que aceptarías también si te perjudicara.',
    ],
    teacherFollowUp: 'Pide que expliquen por qué una segunda oportunidad no siempre devuelve la confianza de la primera versión.',
    words: ['rectificar', 'consentimiento', 'segunda oportunidad', 'aprovecharse'], starter: 'Corregir el resultado no significa que…',
  },
  {
    id: 'b2-objetos', title: 'Los objetos publican reseñas', group: 'Pequeños poderes, grandes líos',
    law: 'Cada domingo, tus objetos escriben una reseña pública sobre cómo los trataste. No pueden mentir, pero solo cuentan su propia experiencia.',
    scene: 'Tu bicicleta te llama «dueño descuidado» porque estuvo bajo la lluvia. Tú estabas ayudando a un amigo y no pudiste recogerla.',
    questions: [
      'Responde a la bicicleta admitiendo lo ocurrido y explicando el contexto sin quitarle importancia al cuidado.',
      'Una persona que vende objetos usados queda mal por una reseña de hace años. ¿Cuánto tiempo debería influir esa experiencia en la confianza de nuevos compradores?',
      'Los objetos caros reciben más cuidados y escriben mejores reseñas. Revisa el sistema para que una puntuación no se confunda con el valor de una persona.',
    ],
    teacherFollowUp: 'Intercambia papeles: quien justificó al dueño debe formular después una queja razonable como objeto.',
    words: ['reseña', 'contexto', 'reputación', 'derecho a responder'], starter: 'No niego que ocurriera…, lo que falta explicar es…',
  },
  {
    id: 'b2-pantallas', title: 'La pantalla necesita compañía', group: 'Pequeños poderes, grandes líos',
    law: 'Las pantallas de ocio solo funcionan si dos personas deciden juntas qué ver o jugar. Las de trabajo, estudio y comunicación funcionan normalmente.',
    scene: 'Quieres relajarte con una serie. Tu compañero de piso quiere un partido y tu amiga, que vive sola, intenta encontrar a alguien disponible.',
    questions: [
      'Negocia qué ver durante una hora sin limitarte a que una persona ceda siempre. ¿Qué harías si los gustos no coinciden?',
      'Una familia celebra tener una actividad compartida; alguien que vive solo pierde libertad. ¿Qué supuesto sobre la vida cotidiana esconde la regla?',
      'Empiezan a venderse muñecos que cuentan como acompañantes. ¿Aceptarías esa salida o reformarías la ley? Justifica qué parte de la convivencia quieres conservar.',
    ],
    teacherFollowUp: 'Pide distinguir compañía física, conversación real y la libertad de disfrutar algo a solas.',
    words: ['coincidir', 'ceder', 'ocio', 'alternar'], starter: 'Compartir una actividad no garantiza que…',
  },
  {
    id: 'b2-cumplidos', title: 'Los cumplidos dan energía', group: 'Vivir juntos de otra manera',
    law: 'Las luces de cada edificio se encienden con cumplidos sinceros entre sus habitantes. Un cumplido repetido no genera energía y nadie puede juzgar su sinceridad desde fuera.',
    scene: 'Necesitas luz para leer, pero después de una discusión no te sale decir nada amable a tu vecino.',
    questions: [
      '¿Cómo buscarías algo sincero que reconocer sin fingir que el conflicto ha desaparecido?',
      'Un edificio de gente extrovertida tiene mucha luz y otro de personas reservadas se queda a oscuras. ¿Qué conducta está premiando la ley sin querer?',
      'La comunidad propone contratar a alguien que elogie a todos. Evalúa el plan y acuerda una garantía de luz que no obligue a mostrar afecto.',
    ],
    teacherFollowUp: 'Pregunta si un reconocimiento breve sobre una acción concreta puede valer tanto como un gran elogio personal.',
    words: ['reconocer', 'sincero', 'forzar', 'necesidad básica'], starter: 'Aprecio la intención de…, aun cuando sigo en desacuerdo sobre…',
  },
  {
    id: 'b2-calendario', title: 'Los planes dejan huella', group: 'Vivir juntos de otra manera',
    law: 'Cada plan que aceptas aparece como una pequeña pegatina visible en tu ropa. Al cancelarlo, cambia de color y permanece una semana, sin explicar el motivo.',
    scene: 'Llegas a una fiesta con tres pegatinas de cancelación porque tuviste que cuidar a un familiar.',
    questions: [
      '¿Explicarías tus cancelaciones o pedirías que no se sacaran conclusiones? Defiende cuánto contexto quieres compartir.',
      'Un organizador usa las pegatinas para invitar solo a personas «fiables». ¿Qué confunde esa medida y a quién podría dejar fuera?',
      'Diseña una modificación que ayude a planificar sin castigar cambios inevitables; después explica qué información dejaría de ser pública.',
    ],
    teacherFollowUp: 'Contrapón una cancelación por cansancio y otra por cuidados: ¿quién tendría derecho a exigir pruebas?',
    words: ['fiable', 'imprevisto', 'sacar conclusiones', 'justificarse'], starter: 'Se puede pedir compromiso sin exigir que alguien…',
  },
  {
    id: 'b2-comida', title: 'El menú cambia de dueño', group: 'Vivir juntos de otra manera',
    law: 'Una vez por semana, cada adulto elige la cena de otro adulto al azar. Se respetan siempre alergias y necesidades de salud, pero no necesariamente sus gustos.',
    scene: 'Te toca elegir para alguien que solo tiene veinte minutos para cocinar. Esa noche tú recibes una receta muy elaborada.',
    questions: [
      '¿Qué información pedirías antes de elegir una cena para un desconocido y qué harías si no te responde?',
      'Quien tiene tiempo descubre recetas; quien trabaja hasta tarde recibe una obligación. Compara cuándo la sorpresa es un regalo y cuándo es una carga.',
      'Un participante compra una cena ya hecha para saltarse el esfuerzo. Acuerda una versión de la regla que preserve la curiosidad sin imponer dinero ni tiempo extra.',
    ],
    teacherFollowUp: 'Pide defender una opción para alguien con utensilios limitados y otra para quien disfruta cocinando.',
    words: ['disponer de', 'adaptar', 'preferencia', 'esfuerzo'], starter: 'Antes de proponer algo que a mí me encanta, comprobaría…',
  },
  {
    id: 'b2-colores', title: 'El barrio cambia de color', group: 'Vivir juntos de otra manera',
    law: 'Cada semana una persona del barrio decide el color de todas las fachadas. Las paredes cambian solas y nadie paga la pintura.',
    scene: 'Te toca elegir. Quieres un naranja alegre; una panadera teme que su cartel deje de verse y tu vecino prefiere colores discretos.',
    questions: [
      'Presenta tu elección como si hablaras ante el vecindario e incorpora al menos una objeción antes de que te la hagan.',
      'Un grupo propone votar todos los colores; otro quiere que cada persona tenga su semana sin negociar. ¿Qué valor protege cada propuesta?',
      'Alguien escoge un color que dificulta distinguir escalones y puertas. Revisa los límites de la decisión individual y explica qué excepción sería obligatoria.',
    ],
    teacherFollowUp: 'Haz que reformulen la propuesta inicial después de escuchar a quien necesita reconocer fácilmente la entrada de su casa.',
    words: ['fachada', 'contraste', 'gusto personal', 'ceder espacio'], starter: 'Mantendría la libertad de elegir salvo cuando…',
  },
  {
    id: 'b2-equipaje', title: 'La maleta se prepara sola', group: 'Vivir juntos de otra manera',
    law: 'Antes de cada viaje, tu maleta selecciona lo que considera imprescindible. Solo puedes añadir un objeto; el resto de sus decisiones es obligatorio.',
    scene: 'La maleta incluye ropa práctica, pero deja fuera el traje de una celebración y un regalo que llevabas para alguien.',
    questions: [
      'Elige tu único objeto extra y explica qué entiende tu maleta por «imprescindible» que no coincide con tu criterio.',
      'A una persona olvidadiza la regla le resuelve el viaje; a otra le impide cumplir una costumbre importante. ¿Quién debería definir lo necesario?',
      'La maleta aprende observando tus viajes anteriores. Decide cuándo confiarías en ella y negocia un derecho a corregirla que no elimine toda la sorpresa.',
    ],
    teacherFollowUp: 'Cierra pidiendo una norma común que funcione tanto para unas vacaciones como para visitar a una persona querida.',
    words: ['imprescindible', 'prescindir de', 'criterio', 'corregir'], starter: 'Para alguien que…, bastaría con…; en mi caso, en cambio…',
  },
];

export const worldGuidesB2: Record<'machine' | 'rules', WorldGuide> = {
  machine: {
    introduction: 'La máquina ofrece soluciones definitivas a problemas cotidianos. Antes de pulsar, piensa quién gana, quién pierde y qué condición podría cambiar tu voto.',
    warmup: 'Piensa en una comodidad que uses todos los días. Explica en treinta segundos qué te aporta y quién podría necesitarla más que tú. La otra persona resume tu idea antes de responder.',
    objective: 'Defender una postura, reconocer una objeción y revisar una decisión a partir de sus consecuencias.',
    stages: [
      { time: '0–5 min', title: 'Abrir el experimento', task: 'Comparen sus comodidades cotidianas y elijan un criterio: autonomía, acceso, tiempo o trato personal.' },
      { time: '5–13 min', title: 'Dos decisiones con apoyo', task: 'Elijan dos objetos de Comodidad y autonomía. Antes de revelar, sostengan una postura durante un minuto y pidan un ejemplo concreto.' },
      { time: '13–28 min', title: 'Consecuencias en cadena', task: 'Exploren otras tres decisiones de grupos distintos. Alternen quién defiende el voto y quién representa a una persona afectada. Tras el giro, respondan a la objeción antes de votar de nuevo.' },
      { time: '28–35 min', title: 'Poner a prueba el criterio', task: 'Elijan una sexta decisión. Negocien una condición aceptable para ambos y comprueben si aplicarían el mismo criterio cuando les perjudicara.' },
      { time: '35–45 min', title: 'Acuerdo final', task: 'Preparen una propuesta conjunta, preséntenla, respondan preguntas y terminen con una revisión individual.' },
    ],
    teacherNote: 'La sesión selecciona unas seis decisiones; el banco permite repetir la experiencia. En clase individual, representa a la persona afectada y después intercambia el papel. Pide razones y ejemplos antes del giro; tras él, exige una respuesta a la objeción, no solo otro voto. No hay una postura correcta. Las consecuencias son ficticias. Reserva diez minutos para el cierre.',
    moves: ['Mi postura inicial sería…, sobre todo porque…', 'Entiendo la preocupación de…, aunque no daría por hecho que…', 'Si lo miramos desde la situación de…, cambia…', 'Mantendría mi decisión siempre que…', 'A la luz de esta consecuencia, matizaría…'],
    challenge: 'Defiende durante un minuto la postura contraria a la tuya sin caricaturizarla. Tu compañero señala qué argumento le parece más sólido; después explica qué conservarías de ese argumento en tu decisión final.',
    closingTitle: 'Acuerdo final · El comité de la máquina',
    closingTask: 'En parejas, dediquen dos minutos a elegir una eliminación que aprobarían y otra que rechazarían entre las conversadas. Presenten una propuesta de tres minutos: criterio común, personas afectadas, consecuencia que aceptan y condición que les haría revisar el acuerdo. Durante tres minutos, la otra pareja o el docente cuestiona dos puntos. Cierren con un minuto por persona explicando qué cambió en su manera de decidir.',
  },
  rules: {
    introduction: 'Una ciudad imposible necesita reglas que funcionen para vidas muy diferentes. Prueba cada ley, escucha a quien sale perdiendo y negocia una versión mejor sin quitarle toda la gracia.',
    warmup: 'Recuerda una norma cotidiana que te resulte cómoda y que pueda complicarle la vida a otra persona. Descríbanla desde las dos perspectivas antes de entrar en la ciudad.',
    objective: 'Explorar consecuencias, comparar perspectivas y negociar excepciones justas mediante un discurso conectado.',
    stages: [
      { time: '0–5 min', title: 'Mirar desde dos vidas', task: 'Compartan la norma del inicio. La otra persona pregunta por una situación en la que dejaría de funcionar.' },
      { time: '5–14 min', title: 'Probar una ley', task: 'Elijan una regla y abran sus tres preguntas por turnos. Describan una escena concreta, comparen intereses y propongan la primera reforma.' },
      { time: '14–28 min', title: 'Cambiar de perspectiva', task: 'Exploren dos reglas de otros grupos. Alternen quién cuenta su día y quién representa a alguien con necesidades distintas. Respondan a la propuesta anterior antes de añadir otra.' },
      { time: '28–35 min', title: 'Negociar una excepción', task: 'Retomen la ley que generó más desacuerdo. Pongan a prueba la excepción con un caso difícil y acuerden cómo saber si funciona.' },
      { time: '35–45 min', title: 'Acuerdo final', task: 'Presenten una ley revisada a la asamblea, respondan una objeción inesperada y expliquen qué han cedido.' },
    ],
    teacherNote: 'Bastan tres reglas para una sesión de 45 minutos. Deja que el absurdo produzca humor y después pide una escena cotidiana verificable dentro de ese mundo. En clase individual, alterna con el alumno el papel de habitante y representante vecinal. No aceptes «depende» sin una condición ni «haría una excepción» sin explicar para quién. Usa la repregunta de cada regla si la conversación se queda en una reacción breve.',
    moves: ['Al principio parece…, pero en una situación como…', 'Para quien…, la misma regla supondría…', 'Aceptaría tu propuesta si añadimos…', 'Esa excepción resolvería…, aunque podría provocar…', 'Después de escucharte, mantengo…, pero cambio…'],
    challenge: 'Representen a dos habitantes con intereses distintos. Cada uno debe resumir fielmente la necesidad del otro antes de proponer un cambio. Negocien una excepción y un límite para evitar que todo el mundo la use como excusa.',
    closingTitle: 'Acuerdo final · La asamblea de la ciudad',
    closingTask: 'Tienen dos minutos para elegir y reformar una ley. Presenten durante tres minutos una jornada en esa ciudad: qué sigue siendo divertido, quién necesita protección, qué excepción habrá y quién comprobará que funciona. Durante tres minutos, otro grupo o el docente representa a un habitante olvidado y plantea una objeción. Dediquen el último minuto de cada participante a defender o revisar el acuerdo y explicar qué cedieron.',
  },
};

export const worldClosingB2 = {
  machine: [
    '¿Qué criterio conecta las dos decisiones de su propuesta y en qué caso entraría en conflicto con otro valor?',
    '¿Qué consecuencia les costó más aceptar? Respondan desde la perspectiva de la persona afectada.',
    'Tras las preguntas del comité, ¿qué mantienen, qué matizan y qué información pedirían antes de actuar de verdad?',
  ],
  rules: [
    '¿Qué problema resuelve su excepción y qué nuevo problema podría crear? Ilústrenlo con una escena.',
    '¿Cómo responderían a alguien que cumple la norma pero sigue saliendo perjudicado?',
    'Comparen su primera reacción con la propuesta final: ¿qué argumento del otro influyó más y por qué?',
  ],
};
