export type Pair={es:string;en:string};
export type Question={prompt:Pair;quick:Pair[];level:"A2"|"B1";place:string;motion:string};
export type AustraliaRegion={id:string;code:string;number:string;name:string;nameEn:string;capital:string;color:string;character:number;topic:Pair;hook:Pair;fact:Pair;mission:Pair;places:Pair[];words:Pair[];questions:Question[];source:{label:string;url:string}};

const p=(es:string,en:string):Pair=>({es,en});
const pairs=(...items:string[])=>items.map(item=>{const [es,en]=item.split("|");return p(es,en)});
const q=(level:"A2"|"B1",place:string,motion:string,es:string,en:string,...quick:string[]):Question=>({level,place,motion,prompt:p(es,en),quick:pairs(...quick)});
const placeList=(...items:string[])=>items.map(item=>p(item,item));

export const regions:AustraliaRegion[]=[
  {id:"sydney",code:"NSW",number:"01",name:"Nueva Gales del Sur",nameEn:"New South Wales",capital:"Sídney",color:"#ff5d43",character:0,
    topic:p("Del puerto al interior","From the harbour to the outback"),hook:p("Una misma región puede sentirse como cinco países.","One state can feel like five different countries."),
    fact:p("Nueva Gales del Sur combina el puerto de Sídney, playas urbanas, las Montañas Azules, pueblos costeros y el paisaje desértico de Broken Hill.","New South Wales combines Sydney Harbour, urban beaches, the Blue Mountains, coastal towns and Broken Hill's outback landscape."),
    mission:p("Armá una ruta que muestre una Australia más grande que Sídney.","Build a route that shows an Australia bigger than Sydney."),
    places:placeList("Circular Quay · Manly","Bondi to Coogee","Montañas Azules","Jervis Bay","Broken Hill","Byron Bay"),
    words:pairs("el ferry|ferry","la caminata costera|coastal walk","el mirador|lookout","el interior|outback","hacer una escapada|take a short trip","quedarse una noche|stay overnight","llevar una capa extra|take an extra layer","vale la pena|it is worth it"),
    questions:[
      q("A2","Circular Quay · Manly","ferry-glide","Tenés libre solo desde las cuatro hasta el atardecer. ¿Tomás el ferry a Manly o te quedás caminando por el puerto? ¿Por qué?","You are free only from four o'clock until sunset. Do you take the ferry to Manly or stay around the harbour? Why?","tomo el ferry|I take the ferry","camino por el puerto|I walk around the harbour","quiero ver el atardecer|I want to see the sunset","prefiero un plan tranquilo|I prefer a calm plan"),
      q("A2","Bondi to Coogee","cliff-step","Vas a hacer la caminata de Bondi a Coogee. Solo podés llevar tres cosas en una mochila pequeña. ¿Qué llevás?","You are walking from Bondi to Coogee. You can carry only three things in a small backpack. What do you take?","agua y comida|water and food","protector solar|sunscreen","una cámara|a camera","una campera liviana|a light jacket"),
      q("A2","Jervis Bay","sand-shimmer","Llegás a Jervis Bay para descansar, no para correr de actividad en actividad. ¿Cómo es tu día perfecto allí?","You arrive in Jervis Bay to rest, not to rush from one activity to another. What is your perfect day there like?","nado temprano|I swim early","leo en la playa|I read on the beach","hago un picnic|I have a picnic","miro el atardecer|I watch the sunset"),
      q("A2","Broken Hill","outback-zoom","Broken Hill cambia el mar por el desierto y el arte. ¿Te interesa más una galería, una mina histórica o el paisaje del interior?","Broken Hill swaps the sea for desert and art. Are you more interested in a gallery, a historic mine or the outback landscape?","una galería|a gallery","la mina histórica|the historic mine","el paisaje|the landscape","quiero combinar todo|I want to combine everything"),
      q("B1","Montañas Azules","mist-lift","Muchos visitantes llegan a las Montañas Azules en auto. ¿Un sistema de buses más fuerte mejoraría la experiencia o le quitaría libertad al viaje?","Many visitors reach the Blue Mountains by car. Would a stronger bus system improve the experience or take freedom away from the trip?","mejoraría la experiencia|it would improve the experience","quitaría libertad|it would take freedom away","reduciría el tráfico|it would reduce traffic","depende de la frecuencia|it depends on frequency"),
      q("B1","Byron Bay","coast-pulse","Byron Bay atrae turismo por su estilo relajado. Cuando un lugar se vuelve muy popular, ¿todavía puede conservar esa identidad?","Byron Bay attracts visitors for its relaxed style. When a place becomes very popular, can it still keep that identity?","sí, con límites|yes, with limits","es difícil|it is difficult","la identidad cambia|identity changes","la comunidad decide|the community decides")
    ],source:{label:"Tourism Australia · NSW",url:"https://www.australia.com/en/places/new-south-wales.html"}},

  {id:"melbourne",code:"VIC",number:"02",name:"Victoria",nameEn:"Victoria",capital:"Melbourne",color:"#8167ee",character:1,
    topic:p("Cultura que se vive en la calle","Culture lived in the street"),hook:p("Tranvías, deporte, diseño y una costa que pide tiempo.","Trams, sport, design and a coast that asks you to slow down."),
    fact:p("Victoria concentra arte, mercados y deporte en Melbourne, y a pocas horas suma la Great Ocean Road, pueblos históricos, montañas y la colonia de pingüinos de Phillip Island.","Victoria packs art, markets and sport into Melbourne, with the Great Ocean Road, historic towns, mountains and Phillip Island's penguin colony only hours away."),
    mission:p("Diseñá un fin de semana que explique por qué Victoria no es solo Melbourne.","Design a weekend that explains why Victoria is more than Melbourne."),
    places:placeList("Tranvías de Melbourne","Queen Victoria Market","MCG","Phillip Island","Ballarat","Great Ocean Road"),
    words:pairs("el tranvía|tram","el puesto|stall","la hinchada|crowd","el callejón|laneway","la costa escarpada|rugged coast","el patrimonio|heritage","cambiar de plan|change plans","tener ambiente|have atmosphere"),
    questions:[
      q("A2","Tranvías de Melbourne","tram-cut","Vivís una semana en Melbourne. ¿Usás el tranvía para explorar sin plan o preparás cada parada antes de salir?","You live in Melbourne for a week. Do you use the tram to explore without a plan or prepare every stop before leaving?","exploro sin plan|I explore without a plan","preparo la ruta|I prepare the route","bajo donde hay ambiente|I get off where there is atmosphere","combino las dos ideas|I combine both ideas"),
      q("A2","Queen Victoria Market","market-pop","Tenés 30 dólares australianos para preparar un almuerzo del mercado para dos personas. ¿Qué comprás?","You have 30 Australian dollars to prepare a market lunch for two people. What do you buy?","pan y queso|bread and cheese","fruta fresca|fresh fruit","algo caliente|something hot","un postre para compartir|a dessert to share"),
      q("A2","MCG","stadium-bounce","Entrás al MCG sin conocer bien las reglas del deporte. ¿Qué puede hacer que igual disfrutes el partido?","You enter the MCG without knowing the rules well. What could still make you enjoy the match?","la hinchada|the crowd","ir con alguien local|going with a local","aprender tres reglas|learning three rules","la energía del estadio|the stadium's energy"),
      q("A2","Phillip Island","penguin-step","Para ver a los pingüinos tenés que esperar en silencio y sin buscar una foto perfecta. ¿Te resulta fácil disfrutar así?","To see the penguins you have to wait quietly and stop chasing the perfect photo. Is it easy for you to enjoy an experience that way?","sí, me relaja|yes, it relaxes me","me cuesta esperar|waiting is hard for me","guardo el celular|I put my phone away","prefiero observar|I prefer to observe"),
      q("B1","Ballarat","history-rise","Ballarat conserva edificios de la época de la fiebre del oro. Si una ciudad necesita más viviendas, ¿qué edificios antiguos debería proteger?","Ballarat preserves gold-rush-era buildings. If a city needs more housing, which old buildings should it protect?","los más importantes|the most important ones","los que tienen una historia|those with a story","no todos|not all of them","se pueden adaptar|they can be adapted"),
      q("B1","Great Ocean Road","coast-sweep","La Great Ocean Road puede hacerse rápido, pero sus pueblos y bosques quedan fuera de la foto famosa. ¿El turismo de una sola foto empobrece un lugar?","The Great Ocean Road can be rushed, but its towns and forests sit beyond the famous photo. Does one-photo tourism make a place poorer?","sí, reduce la experiencia|yes, it reduces the experience","no, atrae visitantes|no, it attracts visitors","hay que quedarse más|people should stay longer","depende del viajero|it depends on the traveller")
    ],source:{label:"Tourism Australia · Victoria",url:"https://www.australia.com/en/places/victoria.html"}},

  {id:"queensland",code:"QLD",number:"03",name:"Queensland",nameEn:"Queensland",capital:"Brisbane",color:"#06bfa5",character:2,
    topic:p("Dos mundos vivos","Two living worlds"),hook:p("El arrecife y la selva obligan a mirar más despacio.","The reef and rainforest make you look more slowly."),
    fact:p("Queensland reúne más de mil tipos de ecosistemas y cinco sitios Patrimonio Mundial: costa, islas, arrecife, selva tropical y también interior.","Queensland has more than one thousand ecosystem types and five World Heritage sites, spanning coast, islands, reef, rainforest and outback."),
    mission:p("Creá una aventura tropical que cuide lo que viniste a ver.","Create a tropical adventure that protects what you came to see."),
    places:placeList("Brisbane River","Gold Coast Hinterland","Gran Barrera de Coral","Daintree","K’gari","Winton"),
    words:pairs("el arrecife|reef","la selva tropical|rainforest","la marea|tide","la excursión guiada|guided tour","la tarifa ambiental|environmental fee","el interior|outback","proteger el hábitat|protect the habitat","cambiar de ritmo|change pace"),
    questions:[
      q("A2","Brisbane River","river-loop","En Brisbane podés usar el río como parte del transporte diario. ¿Preferís viajar por agua, en tren o en bicicleta?","In Brisbane the river can be part of everyday transport. Do you prefer travelling by water, train or bicycle?","por agua|by water","en tren|by train","en bicicleta|by bicycle","depende del clima|it depends on the weather"),
      q("A2","Gold Coast Hinterland","hinterland-fold","Todo el mundo va a la playa, pero vos tenés un día en Gold Coast. ¿Elegís surf, un parque temático o el interior verde?","Everyone goes to the beach, but you have one day on the Gold Coast. Do you choose surf, a theme park or the green hinterland?","surf|surf","un parque temático|a theme park","el interior verde|the green hinterland","mitad y mitad|half and half"),
      q("A2","Daintree","canopy-fall","Tenés dos días cerca de Cairns: uno para el arrecife y otro para Daintree. ¿Qué hacés primero y qué cambia entre los dos días?","You have two days near Cairns: one for the reef and one for Daintree. Which comes first, and what changes between the two days?","primero el arrecife|the reef first","primero la selva|the rainforest first","cambio el equipo|I change my gear","cambio el ritmo|I change the pace"),
      q("A2","Winton","dinosaur-track","En Winton podés conectar el interior de Queensland con dinosaurios y fósiles. ¿Te gustaría una excursión científica o una aventura de película?","In Winton you can connect Queensland's outback with dinosaurs and fossils. Would you like a scientific tour or a movie-style adventure?","una excursión científica|a scientific tour","una aventura de película|a movie-style adventure","quiero aprender|I want to learn","quiero imaginar|I want to imagine"),
      q("B1","Gran Barrera de Coral","reef-breathe","Si una tarifa ambiental encarece un poco la visita al arrecife pero financia su cuidado, ¿te parece una decisión justa?","If an environmental fee makes a reef visit slightly more expensive but funds its care, does that seem fair?","sí, es justa|yes, it is fair","depende del precio|it depends on the price","debe ser transparente|it should be transparent","todos deben colaborar|everyone should help"),
      q("B1","K’gari","island-float","K’gari necesita reglas para vehículos, campamentos y fauna. ¿Cómo explicás límites estrictos sin arruinar la idea de aventura?","K’gari needs rules for vehicles, camps and wildlife. How do you explain strict limits without ruining the idea of adventure?","protegen la isla|they protect the island","dan seguridad|they provide safety","la aventura sigue|the adventure remains","hay que explicarlos bien|they must be explained well")
    ],source:{label:"Tourism Australia · Queensland",url:"https://www.australia.com/en/places/queensland.html"}},

  {id:"northern",code:"NT",number:"04",name:"Territorio del Norte",nameEn:"Northern Territory",capital:"Darwin",color:"#e66f2f",character:3,
    topic:p("Escuchar antes de entrar","Listen before entering"),hook:p("El territorio cambia con las estaciones y con la historia del lugar.","The territory changes with its seasons and the story of Country."),
    fact:p("El Territorio del Norte no es solo desierto: suma humedales, cascadas, islas tropicales, aguas termales y paisajes culturales aborígenes vivos.","The Northern Territory is not only desert: it also has wetlands, waterfalls, tropical islands, thermal springs and living Aboriginal cultural landscapes."),
    mission:p("Viajá con curiosidad sin tratar el territorio como un decorado.","Travel with curiosity without treating Country as scenery."),
    places:placeList("Darwin","Kakadu","Nitmiluk Gorge","Alice Springs","Uluṟu–Kata Tjuṯa","Tiwi Islands"),
    words:pairs("la estación seca|dry season","la estación húmeda|wet season","el paisaje cultural|cultural landscape","el guía tradicional|Traditional guide","el humedal|wetland","el agua termal|thermal water","pedir permiso|ask permission","escuchar primero|listen first"),
    questions:[
      q("A2","Darwin","monsoon-shift","Darwin cambia mucho entre la estación seca y la húmeda. ¿Qué clima elegís y cómo cambia tu plan del día?","Darwin changes greatly between the dry and wet seasons. Which weather do you choose, and how does your day plan change?","la estación seca|the dry season","la estación húmeda|the wet season","salgo temprano|I go out early","dejo un plan flexible|I keep the plan flexible"),
      q("A2","Darwin","market-spark","En los mercados de Darwin aparecen sabores del Sudeste Asiático y del norte australiano. ¿Qué comida nueva probarías sin saber exactamente qué tiene?","Darwin's markets mix Southeast Asian and northern Australian flavours. What new food would you try without knowing exactly what is in it?","algo picante|something spicy","pescado local|local fish","fruta tropical|tropical fruit","pregunto primero|I ask first"),
      q("A2","Nitmiluk Gorge","gorge-echo","En Nitmiluk Gorge podés caminar, navegar o escuchar la historia del lugar con una guía. ¿Qué combinación elegís?","At Nitmiluk Gorge you can walk, cruise or hear the place's story from a guide. Which combination do you choose?","caminar y escuchar|walk and listen","navegar con guía|cruise with a guide","hacer las tres cosas|do all three","empezar temprano|start early"),
      q("A2","Alice Springs","red-centre-line","Alice Springs puede ser base para rutas muy largas. ¿Qué necesitás para sentirte tranquilo durante un viaje con grandes distancias?","Alice Springs can be a base for very long routes. What do you need to feel calm during a trip with huge distances?","un buen mapa|a good map","agua y comida|water and food","un plan claro|a clear plan","compañía|company"),
      q("B1","Uluṟu–Kata Tjuṯa","story-reveal","Uluṟu es un paisaje cultural vivo, no solo una imagen famosa. ¿Qué debería aprender una persona antes de llegar?","Uluṟu is a living cultural landscape, not just a famous image. What should someone learn before arriving?","quién cuida el lugar|who cares for the place","las reglas de respeto|the rules of respect","su historia|its history","cómo escuchar|how to listen"),
      q("B1","Kakadu","wetland-wing","En Kakadu, las estaciones locales explican mejor el paisaje que nuestras cuatro estaciones. ¿Viajar también significa aprender otra forma de organizar el tiempo?","In Kakadu, local seasons explain the landscape better than our four seasons. Does travelling also mean learning another way to organise time?","sí, totalmente|yes, completely","cambia la mirada|it changes your view","ayuda a planificar|it helps you plan","requiere humildad|it requires humility")
    ],source:{label:"Parks Australia · Uluṟu",url:"https://parksaustralia.gov.au/uluru/"}},

  {id:"south",code:"SA",number:"05",name:"Australia Meridional",nameEn:"South Australia",capital:"Adelaida",color:"#ef4776",character:4,
    topic:p("Ideas debajo de la superficie","Ideas below the surface"),hook:p("Festivales, fósiles, casas subterráneas y una costa salvaje.","Festivals, fossils, underground homes and a wild coast."),
    fact:p("Australia Meridional cruza una capital de festivales, el desierto de Coober Pedy, cuevas con fósiles y santuarios de fauna costera.","South Australia spans a festival capital, Coober Pedy's desert, fossil caves and coastal wildlife sanctuaries."),
    mission:p("Encontrá cuatro formas diferentes de contar una región que suele quedar fuera del primer viaje.","Find four different ways to tell the story of a state often left out of a first trip."),
    places:placeList("Adelaida","Coober Pedy","Kangaroo Island","Naracoorte Caves","Eyre Peninsula","Ikara–Flinders Ranges"),
    words:pairs("subterráneo/a|underground","el fósil|fossil","la recuperación|recovery","el productor local|local producer","el festival|festival","la colonia de animales|animal colony","adaptarse al calor|adapt to the heat","mirar desde lejos|watch from a distance"),
    questions:[
      q("A2","Adelaida","festival-spin","Adelaida es conocida por sus festivales. Si tuvieras que llenar una plaza por una noche, ¿qué evento organizarías?","Adelaide is known for its festivals. If you had to fill a square for one night, what event would you organise?","música en vivo|live music","cine al aire libre|outdoor cinema","comida local|local food","arte con luces|light art"),
      q("A2","Coober Pedy","cave-glow","En Coober Pedy muchas personas usan espacios subterráneos para escapar del calor. ¿Qué parte de tu casa pondrías bajo tierra?","In Coober Pedy many people use underground spaces to escape the heat. Which part of your home would you put underground?","el dormitorio|the bedroom","la oficina|the office","toda la casa|the whole house","ninguna parte|no part"),
      q("A2","Naracoorte Caves","fossil-lift","Las cuevas de Naracoorte guardan fósiles de animales antiguos. ¿Preferís aprender con una guía, una reconstrucción 3D o una actividad práctica?","Naracoorte Caves preserve fossils of ancient animals. Would you rather learn with a guide, a 3D reconstruction or a practical activity?","con una guía|with a guide","con una reconstrucción 3D|with a 3D reconstruction","con una actividad|with an activity","con las tres|with all three"),
      q("A2","Eyre Peninsula","ocean-dive","Eyre Peninsula propone encuentros intensos con el océano. ¿Qué te atrae más: fauna marina, acantilados o comida del mar?","The Eyre Peninsula offers intense ocean encounters. What attracts you most: marine life, cliffs or seafood?","la fauna marina|marine life","los acantilados|the cliffs","la comida del mar|seafood","prefiero mirar desde tierra|I prefer watching from land"),
      q("B1","Kangaroo Island","recovery-grow","Después de un incendio grande, ¿el turismo ayuda a una isla a recuperarse o puede crear más presión? ¿De qué depende?","After a major fire, does tourism help an island recover or can it create more pressure? What does it depend on?","puede ayudar|it can help","puede crear presión|it can create pressure","depende de los límites|it depends on limits","debe apoyar a locales|it should support locals"),
      q("B1","Ikara–Flinders Ranges","range-rise","En un paisaje enorme como Ikara–Flinders Ranges, ¿una visita rápida permite entender el lugar o solo verlo?","In a huge landscape like Ikara–Flinders Ranges, does a quick visit let you understand the place or only see it?","solo permite verlo|it only lets you see it","se necesita tiempo|you need time","una buena guía ayuda|a good guide helps","depende de la atención|it depends on attention")
    ],source:{label:"South Australia Parks",url:"https://www.parks.sa.gov.au/get-inspired/npsa-adventure-list"}},

  {id:"western",code:"WA",number:"06",name:"Australia Occidental",nameEn:"Western Australia",capital:"Perth",color:"#f5aa2c",character:5,
    topic:p("La escala cambia todo","Scale changes everything"),hook:p("Una costa inmensa donde la distancia forma parte del viaje.","A vast coast where distance is part of the journey."),
    fact:p("Australia Occidental une Perth y Fremantle con Wadjemup, Margaret River, Esperance y, miles de kilómetros al norte, Nyinggulu y Kimberley.","Western Australia links Perth and Fremantle with Wadjemup, Margaret River, Esperance and, thousands of kilometres north, Nyinggulu and the Kimberley."),
    mission:p("Diseñá un viaje posible dentro de un territorio que no entra en una sola semana.","Design a realistic trip through a state too large for one week."),
    places:placeList("Perth · Fremantle","Wadjemup","Nyinggulu","Broome","Kimberley","Esperance"),
    words:pairs("la distancia|distance","la marea|tide","el arrecife costero|fringing reef","la señal|signal","la ruta remota|remote route","no alimentar animales|do not feed wildlife","dividir el viaje|split the trip","quedarse sin apuro|stay without rushing"),
    questions:[
      q("A2","Perth · Fremantle","sunset-sink","Tenés una tarde entre Perth y Fremantle. ¿Elegís playa al atardecer, mercado, museo marítimo o música en vivo?","You have an afternoon between Perth and Fremantle. Do you choose a sunset beach, a market, a maritime museum or live music?","la playa|the beach","el mercado|the market","el museo|the museum","música en vivo|live music"),
      q("A2","Wadjemup","quokka-peek","En Wadjemup querés una foto con un quokka, pero no podés tocarlo ni alimentarlo. ¿Cómo conseguís un buen recuerdo sin molestarlo?","On Wadjemup you want a quokka photo, but you cannot touch or feed it. How do you get a good memory without disturbing it?","mantengo distancia|I keep my distance","espero con paciencia|I wait patiently","uso el zoom|I use zoom","solo observo|I simply watch"),
      q("A2","Nyinggulu","whale-cruise","En Nyinggulu el arrecife está cerca de la costa. ¿Preferís entrar al agua desde la playa o hacer una salida pequeña con guía?","At Nyinggulu the reef sits close to the coast. Would you rather enter from the beach or take a small guided trip?","desde la playa|from the beach","con una guía|with a guide","primero pregunto|I ask first","depende de la marea|it depends on the tide"),
      q("A2","Esperance","beach-bloom","En Esperance hay playas muy blancas y un paisaje abierto. ¿Qué actividad simple haría que recuerdes el lugar?","Esperance has very white beaches and open landscapes. What simple activity would make you remember the place?","caminar sin apuro|walk without rushing","hacer un picnic|have a picnic","nadar|swim","dibujar el paisaje|draw the landscape"),
      q("B1","Kimberley","signal-fade","En una ruta remota de Kimberley puede no haber señal. ¿Estar desconectado mejora la aventura o agrega un riesgo innecesario?","On a remote Kimberley route there may be no signal. Does being disconnected improve the adventure or add unnecessary risk?","mejora la aventura|it improves the adventure","agrega riesgo|it adds risk","hay que prepararse|you need to prepare","las dos cosas|both"),
      q("B1","Broome","distance-map","Australia Occidental es tan grande que elegir una zona significa renunciar a otras. ¿Planificar bien un viaje también es saber qué dejar afuera?","Western Australia is so large that choosing one area means giving up others. Is good travel planning also knowing what to leave out?","sí, totalmente|yes, completely","evita correr|it avoids rushing","prefiero ver menos|I prefer seeing less","me cuesta elegir|choosing is hard for me")
    ],source:{label:"Tourism Western Australia",url:"https://www.westernaustralia.com/en/plan-my-trip/itineraries"}},

  {id:"tasmania",code:"TAS",number:"07",name:"Tasmania",nameEn:"Tasmania",capital:"Hobart",color:"#419666",character:6,
    topic:p("Una isla de contrastes","An island of contrasts"),hook:p("Arte incómodo, clima cambiante y naturaleza muy cerca.","Uncomfortable art, changing weather and nature close at hand."),
    fact:p("Tasmania combina Hobart y su escena artística con senderos, fauna, costas, sitios históricos y parques donde el clima puede cambiar rápido.","Tasmania combines Hobart's art scene with trails, wildlife, coasts, historic sites and parks where the weather can change quickly."),
    mission:p("Armá una isla donde cultura y naturaleza tengan el mismo peso.","Build an island route where culture and nature carry equal weight."),
    places:placeList("Hobart · MONA","Cradle Mountain","Freycinet","Bay of Fires","Port Arthur","Bruny Island"),
    words:pairs("la isla|island","la capa impermeable|waterproof layer","el sendero|trail","la historia difícil|difficult history","el arte provocador|provocative art","la fauna nocturna|nocturnal wildlife","cambiar de plan|change plans","dejar poca huella|leave little trace"),
    questions:[
      q("A2","Hobart · MONA","art-turn","En Hobart podés empezar con un mercado tradicional y terminar en MONA, un museo muy provocador. ¿Qué orden elegís?","In Hobart you can start at a traditional market and finish at MONA, a provocative museum. Which order do you choose?","mercado y después museo|market then museum","museo y después mercado|museum then market","solo el museo|only the museum","quiero los dos|I want both"),
      q("A2","Cradle Mountain","weather-flip","En Cradle Mountain el clima cambia rápido. ¿Qué llevás para no cancelar el día cuando aparece lluvia o frío?","At Cradle Mountain the weather changes quickly. What do you take so you do not cancel the day when rain or cold arrives?","ropa por capas|layers of clothing","una campera impermeable|a waterproof jacket","comida y agua|food and water","un plan más corto|a shorter plan"),
      q("A2","Bruny Island","island-sway","En Bruny Island tenés que elegir una experiencia lenta: comida local, aves, costa o faro. ¿Cuál elegís?","On Bruny Island you have to choose one slow experience: local food, birds, coast or lighthouse. Which one do you choose?","comida local|local food","observar aves|watch birds","caminar por la costa|walk the coast","visitar el faro|visit the lighthouse"),
      q("A2","Bay of Fires","lichen-glow","Las rocas naranjas de Bay of Fires cambian totalmente el paisaje. ¿Qué colores, sonidos y sensaciones usarías para describirlo?","The orange rocks at Bay of Fires completely change the landscape. Which colours, sounds and feelings would you use to describe it?","naranja y azul|orange and blue","viento y olas|wind and waves","calma|calm","un paisaje fuerte|a powerful landscape"),
      q("B1","Port Arthur","memory-door","Port Arthur es hermoso y también cuenta una historia dura. ¿Cómo puede un lugar turístico evitar convertir el dolor en espectáculo?","Port Arthur is beautiful and also tells a difficult story. How can a tourist site avoid turning pain into entertainment?","con contexto|with context","con respeto|with respect","sin exagerar|without exaggerating","escuchando varias voces|by hearing several voices"),
      q("B1","Freycinet","trail-balance","Cuando una vista famosa atrae a mucha gente, ¿es mejor crear más senderos o concentrar a visitantes en una sola ruta protegida?","When a famous view attracts many people, is it better to create more trails or concentrate visitors on one protected route?","más senderos|more trails","una ruta protegida|one protected route","cupos diarios|daily limits","depende del impacto|it depends on impact")
    ],source:{label:"Tourism Australia · Tasmania",url:"https://www.australia.com/en/places/tasmania.html"}},

  {id:"canberra",code:"ACT",number:"08",name:"Territorio de la Capital",nameEn:"Australian Capital Territory",capital:"Canberra",color:"#2f7fd1",character:7,
    topic:p("Una capital diseñada","A designed capital"),hook:p("Geometría, museos y naturaleza dentro de una ciudad política.","Geometry, museums and nature inside a political city."),
    fact:p("Canberra fue planificada alrededor de ejes, colinas y el lago Burley Griffin; sus instituciones nacionales conviven con ciclovías, reservas y barrios tranquilos.","Canberra was planned around axes, hills and Lake Burley Griffin; its national institutions sit beside cycle paths, reserves and quiet neighbourhoods."),
    mission:p("Hacé que una capital planificada se sienta humana y curiosa.","Make a planned capital feel human and curious."),
    places:placeList("Lake Burley Griffin","Mount Ainslie","Parliament House","National Museum","National Gallery","Namadgi"),
    words:pairs("el eje|axis","la ciudad planificada|planned city","el espacio público|public space","la entrada gratuita|free entry","el debate|debate","la reserva natural|nature reserve","moverse en bicicleta|get around by bike","participar|participate"),
    questions:[
      q("A2","Lake Burley Griffin","lake-cycle","Tenés dos horas alrededor del lago Burley Griffin. ¿Vas en bicicleta, caminás o hacés un picnic?","You have two hours around Lake Burley Griffin. Do you cycle, walk or have a picnic?","voy en bicicleta|I cycle","camino|I walk","hago un picnic|I have a picnic","combino dos planes|I combine two plans"),
      q("A2","Mount Ainslie","city-grid","Desde Mount Ainslie se ve el diseño de Canberra. ¿Te gustaría vivir en una ciudad muy planificada o en una ciudad más espontánea?","From Mount Ainslie you can see Canberra's design. Would you like to live in a highly planned city or a more spontaneous one?","muy planificada|highly planned","más espontánea|more spontaneous","una mezcla|a mixture","depende del barrio|it depends on the neighbourhood"),
      q("A2","National Museum","museum-door","Muchos museos nacionales tienen entrada gratuita. Si solo tenés una hora, ¿cómo elegís qué ver?","Many national museums offer free entry. If you have only one hour, how do you choose what to see?","elijo un solo tema|I choose one theme","pregunto por lo esencial|I ask for the highlights","camino sin plan|I walk without a plan","vuelvo otro día|I return another day"),
      q("A2","Namadgi","bush-wave","Canberra tiene instituciones nacionales y naturaleza muy cerca. ¿Tu día ideal combina parlamento por la mañana y Namadgi por la tarde?","Canberra has national institutions and nature close together. Does your ideal day combine parliament in the morning and Namadgi in the afternoon?","sí, es ideal|yes, it is ideal","prefiero solo naturaleza|I prefer only nature","prefiero la ciudad|I prefer the city","cambiaría el orden|I would change the order"),
      q("B1","Parliament House","debate-ping","Canberra fue elegida como capital entre Sídney y Melbourne. ¿Una capital neutral une mejor a un país o necesita una identidad propia fuerte?","Canberra was chosen as the capital between Sydney and Melbourne. Does a neutral capital unite a country better, or does it need a strong identity of its own?","une mejor|it unites better","necesita identidad|it needs identity","puede hacer las dos cosas|it can do both","la identidad crece|identity grows"),
      q("B1","National Gallery","public-space","Un edificio nacional debe representar al país entero. ¿Cómo incluís historias regionales, migrantes e indígenas sin convertirlas en una lista?","A national building should represent the whole country. How do you include regional, migrant and Indigenous stories without turning them into a list?","con historias personales|with personal stories","con varias voces|with several voices","cambiando exposiciones|by changing exhibitions","trabajando con comunidades|by working with communities")
    ],source:{label:"VisitCanberra",url:"https://visitcanberra.com.au/articles/11-things-americans-might-not-know-about-australias-capital"}}
];

export const connectors=pairs("porque|because","pero|but","además|in addition","por ejemplo|for example","aunque|although","por eso|that is why");
export const speakingMoves=pairs("Agregá un detalle del lugar.|Add one detail about the place.","Comparalo con tu país.|Compare it with your country.","Explicá una consecuencia.|Explain one consequence.","Hacé una pregunta de seguimiento.|Ask a follow-up question.");
