'use client';
import {lazy,Suspense,useEffect,useRef,useState} from 'react';
import Link from 'next/link';
import ConversationGlosses from '../conversation-vocabulary/ConversationGlosses';
import {BANKS,LEVEL_SUPPORT,stationFor,hasExpedition} from './content';
import type {CategoryId,Level,Prompt} from './content/types';
import {CATEGORIES,LEVELS,newSession,restoreSession,parseLevel,switchLevel,drawPrompt,discuss,finalUnlocked,beginFinal,beginExpeditionFinal,openStation,completeFinalPrompt,finishSession,type Session} from './engine.mjs';
import './forest.css';
const World=lazy(()=>import('./World3D'));
const SAVE='spanishcue-forest-session-v1';
export default function BosqueHongos(){
 const [session,setSession]=useState<Session>(()=>newSession('A1',1791));
 const [ready,setReady]=useState(false),[started,setStarted]=useState(false),[fallback,setFallback]=useState(false),[reduced,setReduced]=useState(false);
 const [category,setCategory]=useState<CategoryId|null>(null),[finalMode,setFinalMode]=useState(false),[help,setHelp]=useState(false);
 const [notice,setNotice]=useState('');
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const update=()=>{setReduced(media.matches);if(media.matches)setFallback(true);};let saved:Session|null=null;try{saved=restoreSession(localStorage.getItem(SAVE),BANKS);}catch{/* storage is optional */}const query=new URLSearchParams(location.search).get('level');const next=query!==null?parseLevel(query):saved?.level??'A1';queueMicrotask(()=>{update();setSession(saved&&saved.level===next?saved:newSession(next));setReady(true);});media.addEventListener('change',update);return()=>media.removeEventListener('change',update);},[]);
 useEffect(()=>{if(!help)return;const closeHelp=(e:KeyboardEvent)=>{if(e.key==='Escape')setHelp(false);};document.addEventListener('keydown',closeHelp);return()=>document.removeEventListener('keydown',closeHelp);},[help]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(SAVE,JSON.stringify(session));}catch{/* private mode still works */}},[session,ready]);
 useEffect(()=>{function onPop(){const next=parseLevel(new URLSearchParams(location.search).get('level'));setSession(s=>switchLevel(s,next));setCategory(null);setFinalMode(false);}window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop);},[]);
 const level=session.level,bank=BANKS[level],deck=bank.filter(p=>!p.station),prompt=bank.find(p=>p.id===session.active)??null;
 // A level with authored stations opens the landmark's own conversation first; later visits draw from the category deck.
 function enter(s:Session,zone:CategoryId,lvl:Level=s.level){const station=stationFor(lvl,zone);if(station&&!s.discussed.includes(station.id))return openStation(s,station);return drawPrompt(s,BANKS[lvl].filter(p=>p.zone===zone&&!p.station)).session;}
 function changeLevel(next:Level){if(next===level)return;let s=switchLevel(session,next);if(category&&category!=='final')s=enter(s,category,next);else setCategory(null);setSession(s);setFinalMode(false);setNotice('');const url=new URL(location.href);url.searchParams.set('level',next);history.replaceState(null,'',url);}
 function openCategory(zone:CategoryId){setNotice('');if(zone==='final'){if(!finalUnlocked(session)){setNotice('Para abrir el mirador: habla sobre 10 preguntas en al menos 3 paradas.');return;}const summit=stationFor(level,'final');const result=summit?beginExpeditionFinal(session,bank,summit):beginFinal(session,deck);setSession({...result.session,active:result.prompts[0]?.id??null});setCategory(zone);setFinalMode(true);return;}setFinalMode(false);setCategory(zone);setSession(enter(session,zone));}
 function another(){if(!category)return;setSession(drawPrompt(session,deck.filter(p=>p.zone===category)).session);}
 function close(){setCategory(null);setSession(s=>({...s,active:null}));setFinalMode(false);}
 function spoken(){if(!prompt)return;let next=discuss(session,prompt);if(finalMode){next=completeFinalPrompt(next,prompt.id);next.active=next.finalIds.find(id=>!next.finalDone.includes(id))??null;setSession(next);}else{setSession(next);setCategory(null);}}
 const levelPicker=<div className="bh-levels" aria-label="Nivel de español">{LEVELS.map(l=><button key={l} aria-pressed={l===level} onClick={()=>changeLevel(l)}>{l}</button>)}</div>;
 const categories=<div className="bh-category-grid">{CATEGORIES.map((c,i)=><button key={c.id} style={{'--zone':c.color} as React.CSSProperties} onClick={()=>openCategory(c.id)} aria-disabled={c.id==='final'&&!finalUnlocked(session)}><span>{String(i+1).padStart(2,'0')} {session.visited.includes(c.id)?'✓':''}</span><strong>{c.short}</strong><small>{c.id==='final'?(finalUnlocked(session)?'El mirador te espera':'10 conversaciones · 3 paradas'):c.ecology}</small></button>)}</div>;
 return <main className={`bh ${started?'bh-playing':''}`}>
 <header className="bh-top"><Link href="/" className="bh-brand">SPANISH<span>CUE</span><small>MODO PLAY</small></Link>{levelPicker}<div className="bh-top-actions">{started&&fallback&&<button onClick={()=>setFallback(v=>!v)}>{fallback&&!reduced?'Explorar en 3D':fallback?'Mapa sin movimiento':'Abrir mapa 2D'}</button>}<button aria-label="Ayuda y controles" onClick={()=>setHelp(v=>!v)}>?</button></div></header>
 {!started?<section className="bh-intro" style={{backgroundImage:'linear-gradient(90deg,rgba(9,23,21,.92),rgba(9,23,21,.28)),url(/bosque-hongos/cover.webp)'}}>
  <div className="bh-intro-copy"><p className="bh-eyebrow">CONVERSACIÓN · A0–C2</p><h1>El bosque de los<br/><em>hongos gigantes</em></h1><p className="bh-hook">Sube. Descubre. Habla.<br/>{hasExpedition(level)?'Del suelo del bosque hasta las nubes: cada hongo gigante esconde una conversación.':'Cada camino abre una conversación.'}</p><div className="bh-facts"><span>45–60 min</span><span>12 paradas</span><span>Del suelo a 56 m</span></div><p className="bh-level-demand">{LEVEL_SUPPORT[level].demand}</p><button className="bh-primary" disabled={!ready} onClick={()=>setStarted(true)}>Entrar en el bosque <span>↗</span></button><button className="bh-text-button" disabled={!ready} onClick={()=>{setFallback(true);setStarted(true);}}>Explorar con el mapa sin movimiento</button>{session.discussed.length>0&&<p>Tu recorrido guardado: {session.discussed.length} conversaciones en {level}.</p>}</div>
  <div className="bh-intro-bottom"><span>WASD · MOVERTE</span><span>ESPACIO · SALTAR</span><span>ARRASTRA · MIRA · RUEDA · ZOOM</span><span>Sin respuestas correctas. Tu voz abre el camino.</span></div>
 </section>:<>
 <div className="bh-session-bar"><div><strong>{session.complete?'Llegaste al cielo':finalUnlocked(session)?'El mirador del cielo está abierto':hasExpedition(level)?'Expedición: del suelo a las nubes':'Tu camino al mirador'}</strong><span>{session.discussed.length} preguntas habladas · {session.visited.filter(z=>z!=='final').length} paradas</span></div></div>
 {fallback?<section className="bh-map-view" aria-label="Mapa del bosque, todas las categorías"><div className="bh-map-heading"><p className="bh-eyebrow">EL BOSQUE A TU RITMO</p><h1>Elige dónde conversar</h1><p>Los mismos caminos, preguntas y progreso. Puedes explorar sin saltar.</p></div>{categories}</section>:<Suspense fallback={<div className="bh-loading" role="status">El bosque se despierta…<button onClick={()=>setFallback(true)}>Usar el mapa</button></div>}><World paused={category!==null||help} visited={session.visited} completed={session.complete} unlocked={finalUnlocked(session)} onZone={openCategory} onFail={()=>{setFallback(true);setNotice('Puedes continuar con el mapa. Conservamos tu nivel y tus conversaciones.');}}/></Suspense>}
 {session.complete&&<div className="bh-completion" role="status"><strong>Has llegado al mirador del cielo.</strong><span>Mira hacia abajo: todo el bosque que subiste está bajo las nubes. Puedes seguir explorando y conversando.</span></div>}
 </>}
 {notice&&<div className="bh-notice" role="status">{notice}<button onClick={()=>setNotice('')} aria-label="Cerrar aviso">×</button></div>}
 {help&&<div className="bh-help"><button onClick={()=>setHelp(false)} aria-label="Cerrar ayuda">×</button><h2>Una expedición para hablar</h2><p>Sube desde el suelo del bosque hasta las nubes. Cada globo ¿? marca una parada de conversación: primero eliges, después hablas. Con unas 10–12 paradas se abre el mirador del cielo.</p><p><b>Ordenador:</b> WASD o flechas para moverte, Shift para correr, espacio para saltar y E para conversar. Arrastra para girar y mirar arriba o abajo; la rueda (o + y −) acerca y aleja la cámara; V cambia entre cerca, media y lejos; R y F inclinan la vista; M abre el mapa.</p><p><b>Móvil:</b> mueve el joystick, toca Saltar, arrastra para mirar y pellizca para acercar. Al aterrizar en una parada, toca Conversar.</p><p>Las caídas te devuelven al último hongo seguro. Las preguntas se responden en voz alta, sin grabación ni puntuación. El profesor decide cuándo continuar.</p><p>Los hongos con anillo dorado te impulsan muy alto: úsalos para mirar el camino desde arriba.</p><button onClick={()=>{setFallback(true);setHelp(false);setStarted(true);}}>Usar el mapa sin movimiento</button><button onClick={()=>{setSession(newSession(level));setCategory(null);setFinalMode(false);setHelp(false);setNotice('Nuevo banco barajado. Tu posición en el bosque se conserva.');}}>Nueva sesión de conversación</button></div>}
 {category&&<ConversationDialog onClose={close} focusKey={`${level}-${prompt?.id??'personal'}`}>
  {prompt?<PromptCard key={`${level}-${prompt.id}`} prompt={prompt} level={level} category={CATEGORIES.find(c=>c.id===prompt.zone)?.short??''} finalMode={finalMode} progress={finalMode?`${session.finalDone.length+1} / ${session.finalIds.length}`:undefined} onSpoken={spoken} onAnother={another} onDifficulty={changeLevel}/>:finalMode?<section className="bh-personal"><p className="bh-eyebrow">LA ÚLTIMA MIRADA · {level}</p><h2>{LEVEL_SUPPORT[level].personal}</h2><p>{level==='A0'?'Repite un modelo del recorrido. / Repeat a model from your walk.':'Relaciona tu respuesta con algo que conversaste durante el recorrido.'}</p><button className="bh-primary" onClick={()=>{setSession(finishSession(session));setCategory(null);setFinalMode(false);}}>He compartido mi respuesta · Terminar</button></section>:<section><h2>Has explorado todas las preguntas de esta categoría.</h2><p>No repetimos preguntas durante la sesión. Prueba otro camino o inicia una nueva sesión desde la guía.</p></section>}
  {!finalMode&&<details className="bh-category-switch"><summary>Cambiar categoría</summary>{categories}</details>}
 </ConversationDialog>}
 </main>;
}
function ConversationDialog({children,onClose,focusKey}:{children:React.ReactNode;onClose:()=>void;focusKey:string}){
 const ref=useRef<HTMLDivElement>(null);const onCloseRef=useRef(onClose);useEffect(()=>{onCloseRef.current=onClose;},[onClose]);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const root=ref.current;root?.focus();function key(e:KeyboardEvent){if(e.key==='Escape'){e.preventDefault();onCloseRef.current();}if(e.key==='Tab'&&root){const list=Array.from(root.querySelectorAll<HTMLElement>('button:not(:disabled),summary,[href],input,[tabindex="0"]')).filter(el=>el.getClientRects().length);const first=list[0],last=list.at(-1);if(!first){e.preventDefault();return;}if(e.shiftKey&&(document.activeElement===first||document.activeElement===root||!root.contains(document.activeElement))){e.preventDefault();last?.focus();}else if(!e.shiftKey&&(document.activeElement===last||document.activeElement===root||!root.contains(document.activeElement))){e.preventDefault();first.focus();}}}document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[]);
 useEffect(()=>{ref.current?.focus();},[focusKey]);
 return <div className="bh-dialog-backdrop"><div className="bh-dialog" ref={ref} role="dialog" aria-modal="true" aria-label="Conversación del bosque" tabIndex={-1}><button className="bh-dialog-close" onClick={onClose} aria-label="Volver al bosque">×</button>{children}</div></div>;
}
function PromptCard({prompt:p,level,category,finalMode,progress,onSpoken,onAnother,onDifficulty}:{prompt:Prompt;level:Level;category:string;finalMode:boolean;progress?:string;onSpoken:()=>void;onAnother:()=>void;onDifficulty:(level:Level)=>void}){
 const [selected,setSelected]=useState<string[]>([]),[follow,setFollow]=useState(-1),[condition,setCondition]=useState(false),[tool,setTool]=useState('');
 const station=Boolean(p.station),[openShown,setOpenShown]=useState(!p.choices?.length);
 const idx=LEVELS.indexOf(level);const choices=p.choices??(p.type==='scale'?['1','2','3','4','5']:[]);
 function choose(c:string){const next=p.type==='ranking'?(selected.includes(c)?selected.filter(x=>x!==c):[...selected,c]):[c];setSelected(next);if(station&&(p.type!=='ranking'||next.length>=3))setOpenShown(true);}
 const tools:Record<string,string>=level==='A0'?{'Repite / Repeat':'Repite el modelo. / Repeat the model.','¿Y tú? / And you?':'Pregunta: ¿Y tú? / Ask: And you?','Otra palabra / Another word':'Elige el otro modelo completo. / Choose the other complete model.'}:{'¿Por qué?':'¿Por qué?','Dame un ejemplo':level==='A1'?'Di un ejemplo.':'Da un ejemplo de tu vida.','Compara':level==='A1'?'¿Y la otra opción?':'Compara tu respuesta con otra posibilidad.','¿Y tú?':'¿Y tú?','¿Qué cambiaría tu respuesta?':idx<3?'Ahora tienes más tiempo. ¿Tu respuesta es la misma?':'¿Qué tendría que cambiar para que revisaras tu respuesta?'};
 if(idx>=3)tools['Defiende lo contrario']='Defiende brevemente la postura contraria. ¿Cuál es su argumento más sólido?';
 return <article className="bh-prompt"><div className="bh-prompt-label"><span>{finalMode?'GRAN CONVERSACIÓN FINAL':category.toUpperCase()}</span><span>{level}{progress?` · ${progress}`:''}</span></div>{p.scene&&<p className="bh-scene"><span>EN EL BOSQUE</span>{p.scene}</p>}<h2>{p.question}</h2>{p.statement&&<blockquote>{p.statement}</blockquote>}<p className="bh-speech-hint">{LEVEL_SUPPORT[level].demand} {level==='A0'?'No hay una respuesta correcta. / There is no correct answer.':'No hay una respuesta correcta.'}</p>
 {choices.length>0&&<div className="bh-choices" aria-label={p.type==='ranking'?'Elige en orden y explica tu clasificación':'Elige y explica tu respuesta'}>{choices.map((c,i)=><button key={c} aria-pressed={selected.includes(c)} onClick={()=>choose(c)}><b>{p.type==='ranking'&&selected.includes(c)?selected.indexOf(c)+1:String.fromCharCode(65+i)}</b>{c}</button>)}</div>}
 {selected.length>0&&<p className="bh-answer-cue" role="status">{p.type==='ranking'?`Tu orden: ${selected.join(' → ')}. Explica tus prioridades.`:station?(p.reactions?.[choices.indexOf(selected[0])]??'Explica tu elección.'):level==='A0'?`Has elegido: ${selected.join(', ')}. / Your choice. Say its complete model below.`:`Has elegido: ${selected.join(', ')}. Ahora explica por qué.`}</p>}
 {station&&p.open&&(openShown?<div className="bh-open" role="status"><small>AHORA, CONVERSA</small><p>{p.open}</p></div>:<button className="bh-open-skip" onClick={()=>setOpenShown(true)}>Pasar a la conversación abierta</button>)}
 <ConversationGlosses glosses={p.glosses} level={level}/>
 <details className="bh-support" open={level==='A0'||level==='A1'}><summary>Un comienzo para tu respuesta</summary><div>{(p.support??LEVEL_SUPPORT[level].starters).map(x=><span key={x}>{x}</span>)}</div></details>
 {p.condition&&<div className="bh-condition"><button onClick={()=>setCondition(true)} disabled={condition}>Ya di mi primera respuesta · Cambiar condición</button>{condition&&<p role="status">{p.condition}</p>}</div>}
 {follow>=0&&<div className="bh-followup" role="status"><small>REPREGUNTA</small><p>{p.followUps[follow%p.followUps.length]}</p></div>}
 {tool&&<p className="bh-followup" role="status">{tool}</p>}
 <div className="bh-main-actions"><button className="bh-primary" onClick={onSpoken}>Marcar como hablada <span>→</span></button><button onClick={()=>setFollow(n=>n+1)}>Repregunta</button>{!finalMode&&<button onClick={onAnother}>Otra de esta categoría</button>}</div>
 <details className="bh-teacher"><summary>Herramientas del profesor</summary><div>{Object.entries(tools).map(([label,text])=><button key={label} onClick={()=>setTool(text)}>{label}</button>)}{!finalMode&&<><button disabled={idx===0} onClick={()=>onDifficulty(LEVELS[idx-1])}>Más fácil</button><button disabled={idx===LEVELS.length-1} onClick={()=>onDifficulty(LEVELS[idx+1])}>Más difícil</button><button onClick={onAnother}>Siguiente pregunta</button></>}</div>{p.teacherNote&&<p>{p.teacherNote}</p>}</details>
 </article>;
}
