// A1 is authored independently; the legacy decks remain in engine.mjs.
const cards = [
  {
    situation: 'En la cafetería, tu cita dice «gracias» cuando llega el café.',
    followUp: '¿Qué decís cuando alguien te trae un café?',
    chunks: ['gracias', 'muy amable', 'el café'],
    reason: 'Me gusta porque es amable.',
    teacher: 'Representá el gesto de servir un café. La otra persona responde con una palabra y después con una frase.',
  },
  {
    situation: 'Le contás tu día. Tu cita escucha y pregunta: «¿Y después?».',
    followUp: '¿Qué contás primero: el trabajo, la clase o la comida?',
    chunks: ['escuchar', 'mi día', '¿y después?'],
    reason: 'Me gusta porque escucha.',
    teacher: 'Ofrecé las tres opciones. Pedí una frase sobre el día y una pregunta breve de la pareja.',
  },
  {
    situation: 'Pedís una pizza. Tu cita pregunta: «¿Querés un poco de la mía?».',
    followUp: '¿Qué comida te gusta compartir?',
    chunks: ['compartir', 'un poco', '¿querés?'],
    reason: 'Me gusta porque comparte la comida.',
    teacher: 'Señalá una comida imaginaria. Practiquen ofrecer y responder «sí, gracias» o «no, gracias».',
  },
  {
    situation: 'Están en una cita. Suena su teléfono y habla veinte minutos.',
    followUp: '¿Qué decís: «Te espero» o «Hablamos después»?',
    chunks: ['el teléfono', 'esperar', 'veinte minutos'],
    reason: 'No me gusta porque espero mucho.',
    teacher: 'Mostrá veinte con los dedos. Aceptá cualquiera de las dos respuestas con una razón sencilla.',
  },
  {
    situation: 'Tu cita pregunta tu nombre, pero después te llama por otro nombre.',
    followUp: '¿Cómo le decís tu nombre otra vez?',
    chunks: ['mi nombre', 'otra vez', 'me llamo…'],
    reason: 'No me gusta porque no es mi nombre.',
    teacher: 'Modelá «Me llamo…». Repetí la escena con nombres inventados para evitar datos personales.',
  },
  {
    situation: 'Hace frío. Tu cita pregunta: «¿Querés entrar a un café?».',
    followUp: '¿Preferís un café o un té caliente?',
    chunks: ['hace frío', 'entrar', 'caliente'],
    reason: 'Me gusta porque tengo frío.',
    teacher: 'Hacé un gesto de frío. La pareja propone un lugar y la otra persona elige una bebida.',
  },
  {
    situation: 'La cita es a las seis. A las seis y diez llega y dice: «Perdón».',
    followUp: '¿Diez minutos es mucho o poco para vos?',
    chunks: ['llegar tarde', 'diez minutos', 'perdón'],
    reason: 'Me gusta porque pide perdón. / No me gusta porque llega tarde.',
    teacher: 'Dibujá las dos horas. Permití respuestas distintas; pedí elegir solo una razón.',
  },
  {
    situation: 'Mandás un mensaje por la mañana. Responde por la noche: «Trabajo todo el día».',
    followUp: '¿Vos mandás mensajes por la mañana o por la noche?',
    chunks: ['un mensaje', 'trabajar', 'por la noche'],
    reason: 'Me gusta porque responde. / No me gusta porque espero.',
    teacher: 'Comprobá mañana y noche con gestos. Preguntá por horarios, sin pedir explicar intenciones.',
  },
  {
    situation: 'Querés ir al cine. Tu cita dice: «Hoy estoy muy cansado. ¿Mañana?».',
    followUp: '¿Mañana podés ir al cine? ¿A qué hora?',
    chunks: ['estar cansado', 'hoy', 'mañana puedo'],
    reason: 'Me gusta porque propone otro día.',
    teacher: 'Usá un calendario sencillo. Pedí una hora concreta y una respuesta a la propuesta.',
  },
  {
    situation: 'A vos te gusta bailar. Tu cita dice: «A mí no, pero me gusta la música».',
    followUp: '¿Qué música les gusta a los dos?',
    chunks: ['bailar', 'a mí también', 'a mí no'],
    reason: 'Me gusta porque habla de sus gustos.',
    teacher: 'Ofrecé dos estilos conocidos si falta vocabulario. Busquen un gusto compartido sin exigirlo.',
  },
  {
    situation: 'Tu cita trae un chocolate, pero a vos no te gusta el chocolate.',
    followUp: '¿Qué decís: «Gracias» o «Prefiero otra cosa»? ¿Las dos?',
    chunks: ['un regalo', 'el chocolate', 'prefiero…'],
    reason: 'Me gusta el regalo. / No me gusta el chocolate.',
    teacher: 'Separá el objeto y el gesto con dos ejemplos concretos. Practiquen agradecer y decir un gusto.',
  },
  {
    situation: 'Van a comer. Tu cita pregunta: «¿Invitamos también a mi amiga?».',
    followUp: '¿Hoy preferís comer con dos personas o solo con tu cita?',
    chunks: ['invitar', 'una amiga', 'solo con vos'],
    reason: 'Me gusta conocer gente. / Prefiero comer solo con vos.',
    teacher: 'Mostrá dos y tres personas con dibujos. La respuesta puede ser sí o no; pedí decir la preferencia.',
  },
  {
    situation: 'Tenés una bolsa muy pesada. Tu cita dice: «¿Te ayudo?».',
    followUp: 'Respondé: ¿querés ayuda con la bolsa?',
    chunks: ['una bolsa', 'pesada', 'sí, por favor'],
    reason: 'Me gusta porque ayuda.',
    teacher: 'Representen llevar una bolsa. La otra persona ofrece ayuda y espera una respuesta.',
  },
  {
    situation: 'Estás triste. Tu cita pregunta: «¿Cómo estás? ¿Querés hablar?».',
    followUp: '¿Ahora querés hablar o caminar un poco?',
    chunks: ['estar triste', 'hablar', 'caminar'],
    reason: 'Me gusta porque pregunta cómo estoy.',
    teacher: 'Usá un personaje ficticio. Admití «No quiero hablar» sin pedir una historia personal.',
  },
  {
    situation: 'En el restaurante, tu cita pide dos platos de pescado sin preguntarte.',
    followUp: 'No querés pescado. ¿Qué plato pedís?',
    chunks: ['pedir', 'el pescado', 'para mí…'],
    reason: 'No me gusta porque no pregunta.',
    teacher: 'Ofrecé un menú de tres platos. Practiquen «Para mí…» y luego «¿Qué querés comer?».',
  },
  {
    situation: 'Tu cita muestra una foto de ustedes y pregunta: «¿La mando a mis amigos?».',
    followUp: '¿Qué respondés: «Sí, está bien» o «No, por favor»?',
    chunks: ['una foto', 'mandar', 'está bien'],
    reason: 'Me gusta porque pregunta primero.',
    teacher: 'Mostrá una foto imaginaria. Practiquen las dos respuestas sin entrar en explicaciones abstractas.',
  },
  {
    situation: 'Vos querés pasear por el parque. Tu cita prefiere una cafetería cerca.',
    followUp: '¿Qué plan proponés primero? ¿Y después?',
    chunks: ['el parque', 'cerca', 'primero… después…'],
    reason: 'Prefiero el parque porque me gusta caminar.',
    teacher: 'Señalá dos lugares. Ayudá a acordar una secuencia de dos actividades con «primero» y «después».',
  },
  {
    situation: 'Después de la cita, recibís un mensaje: «Me gusta estar con vos. ¿Nos vemos el sábado?».',
    followUp: '¿Querés otra cita? Respondé y proponé una hora.',
    chunks: ['otra cita', 'el sábado', 'nos vemos a las…'],
    reason: 'Me gusta porque quiero otra cita. / No quiero otra cita.',
    teacher: 'Dales medio minuto para preparar una respuesta. Hagan un intercambio de propuesta, respuesta y despedida.',
  },
];

export const a1Config = {
  level: 'A1',
  accent: '#e35460',
  accentText: '#9f1f34',
  warmup: '¿Qué te gusta en una cita: hablar, escuchar o pasear?',
  situations: cards.map(card => card.situation),
  followUps: cards.map(card => card.followUp),
  finale: [
    'Elegí una situación verde. Contá qué hace la persona y decí: «Me gusta porque…».',
    'Elegí una situación roja. Decí qué no te gusta. Tu compañero pregunta: «¿Qué preferís?».',
    'Prepará una cita: elegí un lugar, un día y una hora. Preguntá: «¿Dónde nos vemos?». Escuchá la respuesta y acordá el plan.',
    'Cambiá los papeles. Uno llega diez minutos tarde y pide perdón. Respondé. Después decí una cosa que te gusta de esta cita.',
  ],
};

export const a1Support = {
  cards,
  rounds: {
    quick: {label: 'GESTOS PEQUEÑOS', copy: 'Elegí un color. Decí qué te gusta o no te gusta.', minutes: 10},
    ambiguous: {label: 'GUSTOS Y PLANES', copy: 'Elegí y explicá. Escuchá la respuesta de otra persona.', minutes: 13},
    deep: {label: 'AHORA HABLAMOS', copy: 'Elegí y explicá. Después, hablá con tu compañero.', minutes: 13},
  },
  intro: ['Verde: me gusta.', 'Roja: no me gusta.', 'Podemos elegir colores diferentes.'],
  frames: ['Me gusta porque…', 'No me gusta porque…', 'Prefiero… ¿Y vos?'],
  teacher: 'Usá personas inventadas; nadie necesita contar su vida. Modelá una elección con una razón. En la primera ronda, aceptá dos palabras y ayudá a formar una frase. En la segunda, comparen gustos. En la tercera, hagan intercambios de dos o tres turnos. Reparto sugerido: 4 + 10 + 13 + 13 + 5 minutos. No hay colores correctos.',
  finaleTitle: 'Nuestra próxima cita',
  finaleCopy: 'Hablá con un compañero. Elegí dos situaciones y después preparen una cita. Usá frases cortas. Los dos hablan y hacen preguntas.',
  finaleFrames: ['Me gusta cuando…', 'No me gusta… Prefiero…', '¿Dónde nos vemos? ¿A qué hora?', '¿El sábado a las seis? Sí, está bien.'],
  finaleTeacher: 'Cierre de cinco minutos: un minuto para elegir, dos para acordar el plan y dos para cambiar los papeles. Pedí al menos una pregunta y una respuesta por persona. Si terminan pronto, cambien el lugar o la hora y vuelvan a acordar la cita.',
};
