import type { Module } from "../../types";

export const a2w01: Module = {
  id: "a2-01",
  level: "a2",
  week: 1,
  kind: "core",
  title: "¿Alguna vez has…?",
  subtitle: "Contar experiencias y lo que has hecho hoy con el pretérito perfecto, ya, todavía no y nunca.",
  stop: { place: "La Habana", country: "Cuba" },
  minutes: 80,
  newObjectives: [
    "a2.gram.perfecto-compuesto",
    "a2.gram.participios-irregulares",
    "a2.gram.ya-todavia",
    "a2.voc.experiencias-viaje",
    "a2.pron.sinalefa-compuestos",
    "a2.fun.experiencias",
    "a2.spk.nunca-he",
  ],
  reviewObjectives: ["a1.gram.presente-er-ir", "a1.gram.frecuencia", "a1.voc.tiempo-libre"],
  prerequisites: ["a1-20"],
  goal: {
    canDo: "Al final de esta semana puedes contar experiencias de tu vida y lo que has hecho hoy o esta semana, preguntar a otras personas por las suyas y reaccionar con interés.",
    canDoEn: "By the end of this week, you can talk about your life experiences and what you have done today or this week, ask other people about theirs and react with interest.",
    steps: [
      "Descubre el **pretérito perfecto**: `he`, `has`, `ha` + participio.",
      "Memoriza los participios irregulares más frecuentes: `hecho`, `dicho`, `visto`, `escrito`…",
      "Pregunta y responde con **alguna vez**, **ya**, **todavía no** y **nunca**.",
      "Une _lo_he_visto_ en un solo bloque, sin pausas.",
      "Escucha un desayuno en una casa particular de La Habana y lee el blog de una viajera.",
      "Prepara tres verdades y una mentira para tu próxima clase.",
    ],
  },
  theory: {
    intro: "Bienvenido a A2. Hasta ahora has hablado del presente y de tus planes. Esta semana empiezas a hablar del pasado con un tiempo muy útil: el **pretérito perfecto** (_he visitado, has comido, ha visto_). Con él cuentas las experiencias de tu vida y lo que ha pasado hoy o esta semana.",
    parts: [
      {
        heading: "He, has, ha + participio",
        body: [
          "El pretérito perfecto tiene dos piezas: el verbo **haber** en presente (**he, has, ha, hemos, habéis, han**) y el **participio** del verbo principal. El participio regular se forma así: los verbos en **-ar** terminan en **-ado** (_visitar → visitado_) y los verbos en **-er** e **-ir** terminan en **-ido** (_comer → comido, vivir → vivido_). También **ser → sido**, **estar → estado** e **ir → ido** son regulares.",
          "El participio **no cambia nunca**: no concuerda con el sujeto. _Ana ha visitado_, _los chicos han visitado_. Y las dos piezas van siempre juntas: no se pone nada entre _haber_ y el participio. Los pronombres van delante del bloque: **Lo he visto. Me he levantado tarde.**",
          "¿Para qué sirve? Para hablar del pasado **conectado con el presente**: las experiencias de tu vida hasta hoy (**He estado en Cuba dos veces**) y las acciones en un tiempo que todavía no ha terminado: **hoy, esta mañana, esta semana, este año**.",
          "Variación: en España este tiempo es muy frecuente para hablar de hoy (**Hoy he comido arroz**). En gran parte de América, también en Cuba, para hoy se prefiere otro pasado que aprendes la próxima semana (_Hoy comí arroz_). Pero para las experiencias, **¿Alguna vez has…?** se usa y se entiende en todas partes.",
        ],
        support: [
          "The _pretérito perfecto_ works much like the English present perfect: _he comido_ = I have eaten. _Haber_ is only an auxiliary here; it is never _tener_.",
          "Unlike English, nothing goes between the two parts: _¿Has comido?_ (Have you eaten?), _Nunca he estado_ (I have never been). The participle never agrees: _ellas han comido_.",
        ],
        table: {
          caption: "Haber en presente + participio",
          head: ["Persona", "Haber", "Ejemplo"],
          rows: [
            ["yo", "he", "He visitado La Habana Vieja."],
            ["tú / vos", "has", "¿Has probado el café cubano?"],
            ["usted, él, ella", "ha", "Ella ha vivido dos años en Cuba."],
            ["nosotros, nosotras", "hemos", "Hemos bebido jugo de guayaba."],
            ["vosotros, vosotras (España)", "habéis", "¿Habéis comido ya?"],
            ["ustedes, ellos, ellas", "han", "¿Ustedes han bailado salsa?"],
          ],
        },
        examples: [
          { es: "Esta semana he caminado mucho por La Habana Vieja.", en: "This week I've walked a lot around Old Havana." },
          { es: "¿Has vivido alguna vez en otro país?", en: "Have you ever lived in another country?" },
          { es: "Mis amigos han comido en un paladar.", en: "My friends have eaten at a paladar.", note: "En Cuba, un **paladar** es un restaurante privado, muchas veces en una casa." },
        ],
        mistakes: [
          { wrong: "Tengo visitado Cuba.", right: "He visitado Cuba.", why: "El auxiliar del perfecto es **haber**, no _tener_." },
          { wrong: "María ha visitada el museo.", right: "María ha visitado el museo.", why: "Con _haber_, el participio no concuerda: siempre en **-o**." },
          { wrong: "He lo comprado.", right: "Lo he comprado.", why: "Los pronombres van **delante** de _haber_, nunca en medio." },
        ],
        tip: "Piensa en el inglés: _I **have** eaten_ → **he** comido. El auxiliar está en el mismo lugar, pero en español es **haber**.",
      },
      {
        heading: "Participios irregulares",
        body: [
          "Algunos verbos muy frecuentes tienen un participio irregular. Hay que aprenderlos de memoria, pero son pocos y los vas a usar todos los días: **hacer → hecho, decir → dicho, ver → visto, escribir → escrito, poner → puesto, volver → vuelto, abrir → abierto, romper → roto**. También **morir → muerto** y **descubrir → descubierto**.",
          "Ya conoces algunos: en A1 usaste **abierto** y **roto** como adjetivos con _estar_ (_La tienda está abierta. La silla está rota._). La diferencia es importante: con _estar_ el participio concuerda (**la tienda está abiert_a_**), con _haber_ no cambia (**han abierto la tienda**).",
          "Los verbos que tienen otra vocal delante de **-ido** llevan tilde en la **í** para separar las dos vocales: **leer → leído, oír → oído, traer → traído, creer → creído**.",
          "Los verbos derivados repiten la irregularidad: **devolver → devuelto, describir → descrito, deshacer → deshecho**.",
        ],
        support: [
          "Irregular participles are like English _done, said, seen, written_: they belong to the most frequent verbs, so learn them first.",
          "Most of them end in **-to** or **-cho**: _visto, escrito, puesto, vuelto, abierto, roto · hecho, dicho_.",
        ],
        table: {
          caption: "Los ocho participios irregulares de la semana",
          head: ["Infinitivo", "Participio", "Ejemplo"],
          rows: [
            ["hacer", "hecho", "¿Qué has hecho hoy?"],
            ["decir", "dicho", "¿Qué te ha dicho Ernesto?"],
            ["ver", "visto", "Nunca he visto un mar tan azul."],
            ["escribir", "escrito", "He escrito dos postales."],
            ["poner", "puesto", "¿Dónde has puesto las llaves?"],
            ["volver", "vuelto", "Ya hemos vuelto a la casa."],
            ["abrir", "abierto", "Han abierto un café nuevo en Obispo."],
            ["romper", "roto", "Me he roto una uña."],
          ],
        },
        examples: [
          { es: "¿Has visto la película _Fresa y chocolate_?", en: "Have you seen the film _Fresa y chocolate_?" },
          { es: "Este año he leído tres novelas cubanas.", en: "This year I've read three Cuban novels." },
        ],
        mistakes: [
          { wrong: "He hacido la maleta.", right: "He hecho la maleta.", why: "_Hacer_ tiene participio irregular: **hecho**." },
          { wrong: "¿Has escribido a tu madre?", right: "¿Has escrito a tu madre?", why: "_Escribir_ → **escrito**." },
          { wrong: "Han rompido la ventana.", right: "Han roto la ventana.", why: "_Romper_ → **roto**." },
          { wrong: "He leido tres libros.", right: "He leído tres libros.", why: "Dos vocales seguidas: la **í** lleva tilde para separarlas (le-í-do)." },
        ],
        tip: "Si un verbo muy frecuente te suena raro con **-ido** (_hacido, ponido, volvido_), probablemente es irregular. Revisa la lista.",
      },
      {
        heading: "Ya, todavía no, alguna vez, nunca",
        body: [
          "Para preguntar por **experiencias** usamos **alguna vez**: **¿Alguna vez has comido langosta?** o **¿Has comido langosta alguna vez?** Las respuestas típicas: **Sí, una vez / dos veces / muchas veces** o **No, nunca**.",
          "**Nunca** puede ir delante del verbo (**Nunca he estado en Cuba**) o detrás; si va detrás, necesitas **no** delante: **No he estado nunca en Cuba**. Es la doble negación que conoces de A1 (_No como carne nunca_).",
          "Para acciones **esperadas** o planeadas usamos **ya** y **todavía no**: **¿Ya has visto el Capitolio?** — **Sí, ya lo he visto.** / **No, todavía no.** _Todavía no_ dice que algo no ha pasado, pero piensas hacerlo. En muchos países también se dice **aún no**.",
          "Cuidado con **ya no**: no es lo contrario de _ya_. Significa que algo terminó: **Ya no vivo en La Habana** (antes sí, ahora no).",
        ],
        support: [
          "_Alguna vez_ = ever. _Nunca_ = never. _Ya_ = already, or _yet_ in questions. _Todavía no_ = not yet. _Ya no_ = not any more.",
          "Spanish happily uses double negatives: _No he estado nunca_ = I've never been. But never _No he nunca estado_: nothing goes between _he_ and _estado_.",
        ],
        table: {
          caption: "Preguntar y responder",
          head: ["Pregunta", "Respuesta afirmativa", "Respuesta negativa"],
          rows: [
            ["¿Alguna vez has bailado salsa?", "Sí, muchas veces. / Sí, una vez.", "No, nunca. / No, no he bailado nunca."],
            ["¿Ya has visitado el Malecón?", "Sí, ya lo he visitado.", "No, todavía no. / Todavía no lo he visitado."],
            ["¿Has probado la fruta bomba?", "Sí, la he probado.", "No, no la he probado todavía."],
          ],
        },
        examples: [
          { es: "Nunca he montado en un almendrón.", en: "I've never ridden in an almendrón.", note: "En La Habana, los **almendrones** son carros antiguos que funcionan como taxi colectivo." },
          { es: "Todavía no he escrito las postales.", en: "I haven't written the postcards yet." },
          { es: "Ya no bebo café por la noche.", en: "I don't drink coffee at night any more." },
        ],
        mistakes: [
          { wrong: "No he nunca bailado salsa.", right: "No he bailado nunca salsa. / Nunca he bailado salsa.", why: "_Nunca_ no puede ir entre _he_ y el participio." },
          { wrong: "Nunca no he estado en Cuba.", right: "Nunca he estado en Cuba.", why: "Si _nunca_ va delante del verbo, no necesitas _no_." },
          { wrong: "—¿Ya has visto la catedral? —No, ya no.", right: "—¿Ya has visto la catedral? —No, todavía no.", why: "_Ya no_ significa «no más». Para algo que no ha pasado aún: **todavía no**." },
        ],
        tip: "Posición fácil: **ya** y **nunca** van delante de todo el bloque (_ya lo he visto_, _nunca he ido_); **todavía** va delante o al final (_todavía no he ido_ / _no he ido todavía_).",
      },
      {
        heading: "Preguntar por experiencias y reaccionar",
        body: [
          "Una buena conversación sobre experiencias tiene tres pasos: **preguntas** con _¿Alguna vez has…?_, **reaccionas** a la respuesta y **pides más información**. Las reacciones muestran interés: **¿De verdad?**, **¡Qué suerte!**, **¡Qué envidia!**, **¡Qué miedo!**, **¡No me digas!**, **¡Yo también!**, **Yo tampoco.**",
          "Para pedir más información, combina el perfecto con el presente que ya conoces: **¿Cuántas veces has ido?**, **¿Y todavía bailas?**, **¿Con qué frecuencia comes marisco?** El perfecto cuenta la experiencia; el presente, cómo es tu vida ahora.",
          "**Yo también** responde a una frase afirmativa (_He estado en México. —¡Yo también!_). **Yo tampoco** responde a una frase negativa (_Nunca he hecho surf. —Yo tampoco._). Si tu experiencia es distinta: **Yo sí** / **Yo no**.",
        ],
        support: [
          "_¡Qué envidia!_ literally means 'what envy!', but it is friendly, like 'I'm so jealous!'.",
          "Question → reaction → follow-up question. That pattern makes you sound interested, not like an interrogator.",
        ],
        examples: [
          { es: "—He nadado con delfines. —¿De verdad? ¡Qué envidia! ¿Dónde?", en: "I've swum with dolphins. — Really? I'm so jealous! Where?" },
          { es: "—Nunca he bebido ron. —Yo tampoco. No bebo alcohol.", en: "I've never drunk rum. — Me neither. I don't drink alcohol." },
          { es: "—He aprendido a bailar salsa. —¡Qué bien! ¿Y bailas a menudo?", en: "I've learned to dance salsa. — Great! And do you dance often?" },
        ],
        mistakes: [
          { wrong: "—Nunca he visto la nieve. —Yo también.", right: "—Nunca he visto la nieve. —Yo tampoco.", why: "La frase es negativa: para estar de acuerdo, **tampoco**." },
        ],
        tip: "Una reacción y una pregunta de seguimiento valen más que diez preguntas seguidas.",
      },
    ],
  },
  grammar: {
    intro: "Primero el auxiliar, después los participios y, al final, la diferencia entre la costumbre (presente) y la experiencia (perfecto).",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "He, has, ha, hemos, han",
        prompt: "Elige la forma de **haber**.",
        items: [
          { q: "Camila y Jordi ___ dado un paseo por el Malecón.", options: ["ha", "han", "hemos"], answer: 1, why: "Dos personas (ellos) → **han**." },
          { q: "¿Tú ___ probado el café cubano?", options: ["has", "ha", "he"], answer: 0, why: "Con **tú**: has." },
          { q: "Señora, ¿usted ___ visitado el Museo de Bellas Artes?", options: ["has", "ha", "han"], answer: 1, why: "**Usted** usa la forma de él/ella: ha." },
          { q: "Mis padres y yo ___ vivido dos años en Miami.", options: ["han", "hemos", "he"], answer: 1, why: "_Mis padres y yo_ = nosotros → **hemos**." },
          { q: "Chicos, ¿ustedes ya ___ desayunado?", options: ["habéis", "hemos", "han"], answer: 2, why: "Con **ustedes**: han. En América se usa también con amigos; _habéis_ va con _vosotros_ (España)." },
        ],
      },
      {
        id: "g2",
        type: "gap",
        title: "¿Qué participio?",
        prompt: "Completa con un participio del banco. Atención: casi todos son irregulares.",
        bank: ["hecho", "dicho", "visto", "escrito", "puesto", "vuelto", "abierto", "roto", "leído"],
        items: [
          { q: "—¿Qué has ___ esta mañana? —Nada especial, he descansado.", answers: [["hecho"]], why: "_Hacer_ → **hecho**." },
          { q: "Todavía no hemos ___ a la casa: estamos en la Plaza Vieja.", answers: [["vuelto"]], why: "_Volver_ → **vuelto**." },
          { q: "Ernesto ha ___ la ventana porque hace mucho calor.", answers: [["abierto"]], why: "_Abrir_ → **abierto**." },
          { q: "¿Alguna vez has ___ la película _Fresa y chocolate_?", answers: [["visto"]], why: "_Ver_ → **visto**." },
          { q: "Lo siento mucho, he ___ tu taza favorita.", answers: [["roto"]], why: "_Romper_ → **roto**." },
          { q: "Mi abuela me ha ___ una carta muy bonita.", answers: [["escrito"]], why: "_Escribir_ → **escrito**." },
          { q: "¿Dónde has ___ el pasaporte? No lo encuentro.", answers: [["puesto"]], why: "_Poner_ → **puesto**." },
          { q: "¿Qué te ha ___ el médico?", answers: [["dicho"]], why: "_Decir_ → **dicho**." },
          { q: "Este año he ___ cinco novelas de Leonardo Padura.", answers: [["leído"]], why: "_Leer_ → **leído**, con tilde en la í." },
        ],
      },
      {
        id: "g3",
        type: "classify",
        title: "¿Costumbre o pasado hasta hoy?",
        prompt: "Repaso de A1: el presente con frecuencia cuenta costumbres. El perfecto cuenta experiencias y lo que ha pasado hoy o esta semana. Clasifica.",
        categories: ["costumbre (presente)", "pasado hasta hoy (perfecto)"],
        items: [
          { text: "Casi nunca como carne.", cat: 0, why: "Presente + _casi nunca_: describe tu vida normal." },
          { text: "Nunca he comido cangrejo.", cat: 1, why: "_He comido_: experiencia de toda la vida." },
          { text: "Escribo a mi madre todos los domingos.", cat: 0, why: "_Todos los domingos_ + presente = costumbre." },
          { text: "Hoy he escrito tres postales.", cat: 1, why: "_Hoy_ + perfecto: acción terminada en un tiempo que no ha terminado." },
          { text: "A veces bebemos jugo de mango.", cat: 0, why: "_A veces_ + presente = costumbre." },
          { text: "¿Alguna vez has bebido agua de coco?", cat: 1, why: "_Alguna vez_ + perfecto = pregunta por una experiencia." },
          { text: "Mis tíos viven en el Vedado.", cat: 0, why: "Presente: la situación de ahora." },
          { text: "Esta semana hemos salido todas las noches.", cat: 1, why: "_Esta semana_ + perfecto: periodo que incluye el presente." },
        ],
      },
      {
        id: "g4",
        type: "transform",
        title: "Ya, todavía no, nunca",
        prompt: "Transforma según la instrucción.",
        items: [
          { source: "¿Ya has visitado el Capitolio?", instruction: "Responde que no, con **todavía no** y el pronombre _lo_.", answers: ["No, todavía no lo he visitado.", "Todavía no lo he visitado.", "No, no lo he visitado todavía.", "No lo he visitado todavía."], why: "_Todavía no_ + pronombre + _haber_ + participio." },
          { source: "Nunca he bailado salsa.", instruction: "Empieza con «No he…».", answers: ["No he bailado nunca salsa.", "No he bailado salsa nunca."], why: "Con _nunca_ detrás del verbo, necesitas **no** delante." },
          { source: "Hoy escribo el blog.", instruction: "Ya está terminado: usa **ya** y el perfecto.", answers: ["Hoy ya he escrito el blog.", "Ya he escrito el blog hoy.", "Ya he escrito el blog."], why: "_Escribir_ → **escrito**; _ya_ va delante de _he_." },
          { source: "¿Alguna vez has comido langosta?", instruction: "Responde que sí, dos veces, con el pronombre _la_.", answers: ["Sí, la he comido dos veces.", "Sí, he comido langosta dos veces."], why: "_La langosta_ → **la** he comido, delante de _haber_." },
          { source: "Vuelvo a casa a las ocho.", instruction: "Ya ha pasado hoy: empieza con «Hoy…».", answers: ["Hoy he vuelto a casa a las ocho."], why: "_Vuelvo_ (presente de A1) → **he vuelto**: _volver_ tiene participio irregular." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Aprende las experiencias como bloques: verbo + complemento. Así puedes preguntar ¿Alguna vez has…? con cualquiera de ellos.",
    groups: [
      {
        title: "De viaje",
        items: [
          { es: "visitar un museo / una catedral", en: "visit a museum / a cathedral" },
          { es: "dar un paseo por el Malecón", en: "take a walk along the Malecón (Havana's seafront)" },
          { es: "subir a un mirador", en: "go up to a viewpoint" },
          { es: "bañarse en el mar", en: "swim / bathe in the sea", note: "_Me he bañado en el mar._ El pronombre va delante de _haber_." },
          { es: "dormir en una casa particular", en: "stay in a casa particular (a room in a Cuban family home)" },
          { es: "montar en un carro antiguo", en: "ride in a classic car", note: "**carro** en gran parte de América, **coche** en España, **auto** en el Cono Sur." },
          { es: "hacer una excursión", en: "go on a day trip" },
          { es: "perder el vuelo / la guagua", en: "miss the flight / the bus", note: "**guagua** = autobús en Cuba, Puerto Rico, República Dominicana y Canarias." },
          { es: "viajar solo / sola", en: "travel alone" },
        ],
      },
      {
        title: "Probar cosas nuevas",
        items: [
          { es: "probar un plato típico", en: "try a typical dish" },
          { es: "comer langosta / marisco", en: "eat lobster / seafood" },
          { es: "beber jugo de guayaba", en: "drink guava juice", note: "**jugo** en América, **zumo** en España." },
          { es: "tomar un café cubano", en: "have a Cuban coffee" },
          { es: "aprender a bailar salsa", en: "learn to dance salsa" },
          { es: "ver un espectáculo en vivo", en: "see a live show" },
          { es: "conocer a gente nueva", en: "meet new people", note: "_Conocer_ **a** + persona." },
          { es: "ir a un concierto", en: "go to a concert" },
        ],
      },
      {
        title: "Reaccionar",
        items: [
          { es: "¿De verdad?", en: "Really?" },
          { es: "¡Qué suerte!", en: "How lucky!" },
          { es: "¡Qué envidia!", en: "I'm so jealous! (friendly)" },
          { es: "¡Qué miedo!", en: "How scary!" },
          { es: "¡No me digas!", en: "No way! / You don't say!" },
          { es: "Yo también. / Yo tampoco.", en: "Me too. / Me neither." },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "Verbo + complemento",
        prompt: "Une cada verbo con su complemento natural.",
        pairs: [
          { left: "dar", right: "un paseo por la playa" },
          { left: "probar", right: "la comida local" },
          { left: "subir", right: "a un mirador" },
          { left: "perder", right: "el último autobús" },
          { left: "conocer", right: "a gente de otros países" },
          { left: "montar", right: "en un carro antiguo" },
        ],
        why: "Son combinaciones fijas: **dar** un paseo (no _hacer_), **conocer a** + personas, **montar en** un vehículo, **subir a** un lugar alto.",
      },
      {
        id: "v2",
        type: "context",
        title: "¿Cómo reaccionas?",
        prompt: "Elige la reacción más natural.",
        items: [
          { context: "Tu amiga dice: «He nadado con tiburones en Jardines de la Reina».", q: "Reaccionas:", options: ["¡Qué miedo! ¿De verdad?", "Yo tampoco.", "Igualmente."], answer: 0, why: "Nadar con tiburones da miedo: **¡Qué miedo!** + pregunta de interés. _Yo tampoco_ responde a frases negativas." },
          { context: "Tu compañero dice: «Nunca he probado el café cubano».", q: "Tú tampoco lo has probado. Dices:", options: ["Yo también.", "Yo tampoco.", "¡Qué envidia!"], answer: 1, why: "La frase es negativa: para decir que te pasa lo mismo, **yo tampoco**." },
          { context: "Una señora mayor te cuenta: «He vivido en cuatro países».", q: "Reaccionas:", options: ["Yo tampoco.", "¡Qué interesante! ¿En cuáles?", "¡Qué miedo!"], answer: 1, why: "Reacción positiva + pregunta de seguimiento: muestra interés." },
          { context: "Tu amigo dice: «Este verano he ganado un viaje a Varadero».", q: "Reaccionas:", options: ["¡Qué miedo!", "Yo tampoco.", "¡Qué suerte!"], answer: 2, why: "Ganar un viaje es buena fortuna: **¡Qué suerte!**" },
        ],
      },
      {
        id: "v3",
        type: "gap",
        title: "Experiencias de esta semana",
        prompt: "Completa con el participio adecuado del banco.",
        bank: ["probado", "perdido", "subido", "conocido", "dado", "bañado"],
        items: [
          { q: "Hoy me he ___ en el mar por primera vez.", answers: [["bañado"]], why: "_Bañarse en el mar_: **me he bañado**." },
          { q: "¿Alguna vez has ___ un vuelo por llegar tarde?", answers: [["perdido"]], why: "_Perder el vuelo_ = no llegar a tiempo." },
          { q: "En este viaje hemos ___ a gente muy simpática.", answers: [["conocido"]], why: "_Conocer a_ + personas." },
          { q: "Todavía no he ___ el congrí.", hint: "arroz con frijoles negros, plato típico cubano", answers: [["probado"]], why: "Comida nueva → **probar**." },
          { q: "Esta tarde hemos ___ un paseo por La Habana Vieja.", answers: [["dado"]], why: "La combinación es **dar un paseo**." },
          { q: "¿Ya han ___ al mirador del Morro?", answers: [["subido"]], why: "_Subir a_ un lugar alto." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "Enlace en los tiempos compuestos: lo_he_visto",
    explanation: [
      "La **h** no suena. Por eso, en el perfecto, _he, has, ha, hemos, han_ empiezan con sonido de vocal, y esa vocal se une a la palabra anterior y a la siguiente: **lo_he_visto** suena casi como una sola palabra: lo-e-**vis**-to. Es la **sinalefa** que practicaste en A1 (_la_amiga_), ahora dentro del verbo.",
      "Cuando se encuentran dos vocales iguales, se funden en una sola, un poco más larga: **he_estado** → «heestado», **me_he_equivocado** → «meequivocado». Por eso **ha estado** y **está** se pueden confundir al escuchar: presta atención al final **-ado**.",
      "El bloque _haber_ + participio se dice **sin pausa** y con un solo acento fuerte, el del participio: lo he **vis**to, ya hemos co**mi**do, ¿has es**ta**do?",
      "Variación: en el habla relajada del Caribe, de Andalucía y de muchas otras zonas, la **d** de **-ado** casi desaparece: _he estado_ → «he ehtao», _¿qué ha pasado?_ → «¿qué ha pasao?». En La Habana lo vas a oír constantemente. Tienes que reconocerlo; en tu español, una **d** suave es perfecta.",
    ],
    support: [
      "Spanish links vowels across word boundaries. In the perfect tense the silent _h_ means _he, ha, han_ always start with a vowel, so they glue onto the words around them.",
      "Don't pause between _he_ and the participle. Say the whole block in one breath and stress only the participle.",
    ],
    examples: [
      { es: "lo_he_visto", en: "I've seen it", note: "lo-e-VIS-to" },
      { es: "me_he_equivocado", en: "I've made a mistake", note: "me-e-qui-vo-CA-do" },
      { es: "ya_ha_ido", en: "he/she has already gone", note: "ya-a-I-do" },
      { es: "¿has_estado?", en: "have you been?", note: "a-ses-TA-do" },
    ],
    perceive: {
      id: "p1",
      type: "listen",
      title: "¿Qué forma oyes?",
      prompt: "Escucha. Las palabras van unidas: decide qué forma de _haber_ o qué participio hay en la frase.",
      items: [
        { q: "¿Qué pregunta oyes?", audio: "¿Lo has hecho tú?", voice: "es-MX-f", options: ["¿Lo has hecho tú?", "¿Lo ha hecho él?", "¿Lo he hecho yo?"], answer: 0, why: "_Lo_has_hecho_ se une en «loasecho»; el _tú_ final lo confirma." },
        { q: "¿Qué frase oyes?", audio: "Ya ha ido al Malecón.", voice: "es-CU-m", options: ["Ya he ido al Malecón.", "Ya ha ido al Malecón.", "Ya han ido al Malecón."], answer: 1, why: "_Ya_ha_ se funde en una **a** larga: «yaaido». Con _he_ oirías una **e**: «yaeido»." },
        { q: "¿Qué participio oyes?", audio: "Usted ha oído esta canción, ¿verdad?", voice: "es-ES-f", options: ["ido", "oído", "dicho"], answer: 1, why: "«aoído»: hay una **o** entre _ha_ e _ído_. Es _oír_, no _ir_." },
        { q: "¿Quién se ha equivocado?", audio: "Me he equivocado de calle.", voice: "es-CO-m", options: ["yo (me he)", "él (se ha)", "tú (te has)"], answer: 0, why: "«meequivocado»: _me_ + _he_ + _equivocado_ forman una cadena de **e**." },
        { q: "¿Qué forma oyes?", audio: "Todavía no hemos abierto las maletas.", voice: "es-CU-f", options: ["han abierto", "he abierto", "hemos abierto"], answer: 2, why: "«hemosabierto»: la **s** de _hemos_ se une a _abierto_." },
        { q: "¿Qué frase oyes?", audio: "Ella ha estado en Santiago.", voice: "es-CU-m", options: ["Ella está en Santiago.", "Ella ha estado en Santiago."], answer: 1, why: "_ha_estado_ suena «aestado»: escucha el final **-ado**, que no está en _está_." },
        { q: "¿Qué pregunta oyes?", audio: "¿Qué ha pasado aquí?", voice: "es-CU-f", options: ["¿Qué ha pasado aquí?", "¿Qué pasa aquí?", "¿Qué has pasado aquí?"], answer: 0, why: "«¿qué_ha_pasao?»: aunque la **d** casi desaparece, se oye la **a** de _ha_ unida a _qué_." },
      ],
    },
    produce: [
      { text: "Lo he visto.", tip: "Tres palabras, un solo bloque: lo-e-VIS-to. Sin pausa después de _lo_." },
      { text: "Nunca he estado en Cuba.", tip: "Nun-ca_he_es-ta-do: la **a** se une a la **e**, y las dos **e** se funden." },
      { text: "¿Alguna vez has ido a un concierto?", tip: "«a-se-SI-do»: la **s** de _has_ pasa a la sílaba siguiente." },
      { text: "Todavía no lo hemos hecho.", tip: "_lo_hemos_hecho_: «loe-mo-SE-cho». El único acento fuerte es _HE_cho_." },
      { text: "Me he equivocado de guagua.", tip: "Una cadena de **e**: «meequivocado». _Guagua_ = autobús en Cuba." },
    ],
    spelling: "La **h** de _he, has, ha, hemos, habéis, han_ no suena, pero siempre se escribe. No confundas **ha** (verbo: _ha ido_) con **a** (preposición: _va a la playa_): **Ella ha ido a la playa.**",
  },
  listening: {
    title: "Desayuno en una casa particular",
    context: "Primera mañana en una casa particular de Centro Habana. Yamilé, la dueña, desayuna con dos viajeros: Camila, de Bogotá, y Jordi, de Barcelona. Después llega Ernesto, el hijo de Yamilé.",
    speakers: [
      { id: "yamile", name: "Yamilé", voice: "es-CU-f", role: "dueña de la casa" },
      { id: "camila", name: "Camila", voice: "es-CO-f", role: "viajera colombiana" },
      { id: "jordi", name: "Jordi", voice: "es-ES-m", role: "viajero español" },
      { id: "ernesto", name: "Ernesto", voice: "es-CU-m", role: "hijo de Yamilé" },
    ],
    script: [
      { speaker: "yamile", text: "¡Buenos días, muchachos! ¿Qué tal han dormido?" },
      { speaker: "camila", text: "Muy bien, gracias. ¡Y este desayuno se ve delicioso!" },
      { speaker: "jordi", text: "Pues yo he dormido fatal. Esta noche ha hecho muchísimo calor." },
      { speaker: "yamile", text: "Es que en agosto aquí siempre hace calor. Bueno, ¿y ustedes ya han ido al Malecón?" },
      { speaker: "camila", text: "Sí, ya hemos dado un paseo largo por el Malecón. ¡Qué lindo es!" },
      { speaker: "jordi", text: "Pero todavía no hemos visto el Capitolio. Queremos ir hoy." },
      { speaker: "ernesto", text: "Buenos días. Oigan, ¿alguna vez han montado en un almendrón? Son los carros antiguos que funcionan como taxi." },
      { speaker: "camila", text: "¡Nunca! En Bogotá no hay carros así." },
      { speaker: "jordi", text: "Yo tampoco, pero he visto mil fotos." },
      { speaker: "ernesto", text: "Pues hoy es el día: mi tío tiene uno rojo, del cincuenta y siete." },
      { speaker: "yamile", text: "¿Y han probado la langosta cubana?" },
      { speaker: "camila", text: "No, todavía no. Yo casi nunca como marisco, pero aquí quiero probarlo todo." },
      { speaker: "jordi", text: "Yo he comido langosta muchas veces en la Costa Brava, pero aquí todavía no." },
      { speaker: "yamile", text: "Entonces esta noche cocino yo. Y después… ¿ustedes bailan salsa?" },
      { speaker: "camila", text: "¡Claro! En Bogotá voy a clases de salsa todos los jueves." },
      { speaker: "jordi", text: "Yo no he bailado salsa nunca en mi vida. ¡Qué vergüenza!" },
      { speaker: "ernesto", text: "Tranquilo, asere. Esta noche aprendes." },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: no busques detalles. ¿De qué hablan y cómo es el ambiente?",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha todo una vez y responde.",
          items: [
            { q: "¿De qué hablan sobre todo?", options: ["De lo que han hecho y lo que todavía no han hecho en La Habana", "De sus trabajos y sus familias", "De cómo volver a su país"], answer: 0, why: "Se repiten _ya han ido_, _todavía no hemos visto_, _alguna vez han montado_…" },
            { q: "¿Cómo es el ambiente?", options: ["tenso y formal", "relajado y amistoso", "triste"], answer: 1, why: "Se tratan de tú y de ustedes, bromean y hacen planes juntos." },
            { q: "¿Qué plan hay para esta noche?", options: ["ir al Capitolio", "cenar langosta y bailar", "ir a un concierto"], answer: 1, why: "Yamilé dice _esta noche cocino yo_ y pregunta si bailan salsa." },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: atención a quién ha hecho qué.",
        exercise: {
          id: "l2",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "¿Por qué ha dormido mal Jordi?", options: ["Ha bebido mucho café.", "Ha hecho mucho calor.", "Ha vuelto muy tarde."], answer: 1, why: "Dice: _Esta noche ha hecho muchísimo calor_." },
            { q: "¿Qué han hecho ya Camila y Jordi?", options: ["Han visto el Capitolio.", "Han montado en un almendrón.", "Han dado un paseo por el Malecón."], answer: 2, why: "_Ya hemos dado un paseo largo por el Malecón._ El Capitolio, todavía no." },
            { q: "¿Qué es un almendrón, según Ernesto?", options: ["un carro antiguo que funciona como taxi", "un plato típico", "un barrio de La Habana"], answer: 0, why: "_Son los carros antiguos que funcionan como taxi._" },
            { q: "¿Con qué frecuencia come marisco Camila?", options: ["todos los días", "a menudo", "casi nunca"], answer: 2, why: "Dice: _Yo casi nunca como marisco_." },
            { q: "¿Dónde ha comido langosta Jordi?", options: ["en la Costa Brava", "en La Habana", "en ningún sitio"], answer: 0, why: "_He comido langosta muchas veces en la Costa Brava, pero aquí todavía no._" },
            { q: "¿Quién no ha bailado salsa nunca?", options: ["Camila", "Jordi", "Ernesto"], answer: 1, why: "Jordi: _Yo no he bailado salsa nunca en mi vida_. Camila va a clases los jueves." },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en el tiempo de cada frase. ¿Qué cuenta?",
        exercise: {
          id: "l3",
          type: "classify",
          prompt: "Clasifica las frases que oyes.",
          categories: ["experiencia en la vida", "algo de esta noche o de hoy", "costumbre (presente)"],
          items: [
            { text: "Esta noche ha hecho muchísimo calor.", cat: 1, why: "_Esta noche_ (la noche pasada, hoy) + perfecto." },
            { text: "¿Alguna vez han montado en un almendrón?", cat: 0, why: "_Alguna vez_ pregunta por una experiencia." },
            { text: "He comido langosta muchas veces.", cat: 0, why: "_Muchas veces_ en la vida: experiencia." },
            { text: "Yo casi nunca como marisco.", cat: 2, why: "Presente + _casi nunca_: costumbre." },
            { text: "Voy a clases de salsa todos los jueves.", cat: 2, why: "_Todos los jueves_: costumbre en presente." },
            { text: "No he bailado salsa nunca en mi vida.", cat: 0, why: "_Nunca en mi vida_: experiencia (doble negación)." },
            { text: "¿Qué tal han dormido?", cat: 1, why: "Pregunta por la noche que acaba de pasar." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Mi lista habanera",
    genre: "Entrada de blog de viajes",
    frame: "Mariana, una profesora de Guadalajara (México), escribe desde La Habana en su blog _Maleta ligera_.",
    text: [
      "¡Hola, viajeros! Estoy en La Habana desde el lunes y hoy les escribo desde la azotea de mi casa particular, en el Vedado. Este viaje ha sido muy diferente de todos mis viajes anteriores, así que aquí va mi lista.",
      "**Lo que ya he hecho.** He caminado por La Habana Vieja todos los días (¡mis pies ya no aguantan más!). He visitado tres museos y he visto el atardecer desde la azotea de un hotel. He probado la ropa vieja, que está riquísima, y he montado en un almendrón rosado. Ah, y he conocido a Rey, un músico que toca el tres desde los ocho años.",
      "**Lo que todavía no he hecho.** Todavía no he ido a la playa: las playas del Este están a veinte minutos, pero siempre encuentro otro plan. Tampoco he aprendido a bailar salsa. Aquí la gente baila en todas partes y yo… bueno, yo miro.",
      "**Una sorpresa.** Nunca he visto una ciudad con tanta música. En México escucho música a todas horas, pero aquí es otra cosa: la oyes en la calle, en las guaguas, en las ventanas abiertas. Y una cosa práctica: internet no siempre funciona bien, así que he escrito este post tres veces.",
      "¿Y ustedes? ¿Alguna vez han estado en La Habana? ¿Qué me recomiendan para mis últimos dos días?",
    ],
    glossary: [
      { es: "la azotea", en: "flat rooftop terrace" },
      { es: "la ropa vieja", en: "a Cuban dish of shredded beef in tomato sauce" },
      { es: "el tres", en: "a Cuban guitar with three pairs of strings" },
      { es: "la guagua", en: "bus (Cuba, Puerto Rico, Dominican Republic, Canary Islands)" },
      { es: "aguantar", en: "to bear, to stand" },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee la entrada y responde.",
        items: [
          { q: "¿Dónde se queda Mariana?", options: ["en un hotel de La Habana Vieja", "en una casa particular del Vedado", "en casa de Rey"], answer: 1, why: "_Les escribo desde la azotea de mi casa particular, en el Vedado._" },
          { q: "¿Qué plato ha probado?", options: ["la langosta", "el congrí", "la ropa vieja"], answer: 2, why: "_He probado la ropa vieja, que está riquísima._" },
          { q: "¿Por qué todavía no ha ido a la playa?", options: ["Porque está muy lejos.", "Porque siempre encuentra otro plan.", "Porque no le gusta el mar."], answer: 1, why: "La playa está a veinte minutos, _pero siempre encuentro otro plan_." },
          { q: "¿Qué le ha sorprendido más?", options: ["la cantidad de música en la ciudad", "los precios", "el calor"], answer: 0, why: "_Nunca he visto una ciudad con tanta música._" },
          { q: "¿Por qué ha escrito el post tres veces?", options: ["Porque ha perdido el teléfono.", "Porque internet no siempre funciona bien.", "Porque ha cometido muchos errores."], answer: 1, why: "_Internet no siempre funciona bien, así que he escrito este post tres veces._" },
        ],
      },
      {
        id: "r2",
        type: "classify",
        prompt: "¿Mariana ya lo ha hecho o todavía no? Clasifica según el texto.",
        categories: ["ya lo ha hecho", "todavía no lo ha hecho"],
        items: [
          { text: "caminar por La Habana Vieja", cat: 0, why: "_He caminado por La Habana Vieja todos los días._" },
          { text: "ir a la playa", cat: 1, why: "_Todavía no he ido a la playa._" },
          { text: "probar un plato típico", cat: 0, why: "_He probado la ropa vieja._" },
          { text: "aprender a bailar salsa", cat: 1, why: "_Tampoco he aprendido a bailar salsa._" },
          { text: "montar en un almendrón", cat: 0, why: "_He montado en un almendrón rosado._" },
          { text: "conocer a un músico", cat: 0, why: "_He conocido a Rey, un músico…_" },
        ],
      },
    ],
    noticing: {
      prompt: "Toca cada frase para ver qué hay detrás.",
      items: [
        { quote: "Este viaje ha sido muy diferente", note: "Participio de **ser**: _sido_ (regular). También _estar → estado_, _ir → ido_." },
        { quote: "¡mis pies ya no aguantan más!", note: "**Ya no** = antes sí, ahora no. No es lo contrario de _ya_." },
        { quote: "Todavía no he ido a la playa", note: "Algo planeado que no ha pasado: **todavía no** + perfecto." },
        { quote: "Nunca he visto una ciudad con tanta música", note: "_Nunca_ delante del verbo: no hace falta _no_. **Visto** es irregular." },
        { quote: "En México escucho música a todas horas", note: "Presente para la costumbre (repaso de A1), frente al perfecto para la experiencia." },
        { quote: "¿Y ustedes? ¿Alguna vez han estado en La Habana?", note: "En América, **ustedes** para cualquier grupo, también de amigos. En España: _¿Y vosotros? ¿Habéis estado…?_" },
      ],
    },
  },
  practice: {
    intro: "Combina el perfecto con lo que ya sabías: presente, frecuencia y tiempo libre.",
    exercises: [
      {
        id: "x1",
        type: "order",
        title: "Construye la frase",
        prompt: "Ordena las palabras.",
        items: [
          { words: ["¿Alguna", "vez", "has", "bebido", "agua", "de", "coco?"], alt: ["¿Has bebido agua de coco alguna vez?"], en: "Have you ever drunk coconut water?", why: "_Alguna vez_ va al principio o al final, nunca entre _has_ y _bebido_." },
          { words: ["Todavía", "no", "hemos", "visto", "el", "Morro."], alt: ["No hemos visto el Morro todavía.", "No hemos visto todavía el Morro."], en: "We haven't seen the Morro (castle) yet.", why: "_Todavía no_ delante del bloque, o _no_… _todavía_ alrededor." },
          { words: ["Mi", "hermana", "nunca", "ha", "viajado", "sola."], alt: ["Mi hermana no ha viajado nunca sola.", "Nunca ha viajado sola mi hermana."], en: "My sister has never travelled alone.", why: "_Nunca_ delante de _ha_; _sola_ concuerda con _hermana_." },
          { words: ["Ya", "lo", "he", "puesto", "en", "la", "maleta."], alt: ["Lo he puesto ya en la maleta."], en: "I've already put it in the suitcase.", why: "Orden: _ya_ + pronombre + _haber_ + participio." },
        ],
      },
      {
        id: "x2",
        type: "error",
        title: "Detective de errores",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "¿Has tú probado el congrí?", answers: ["¿Has probado el congrí?", "¿Tú has probado el congrí?", "¿Has probado tú el congrí?"], why: "Nada se pone entre _has_ y el participio: el sujeto va antes o después del bloque." },
          { sentence: "Esta semana hemos volvido tarde todos los días.", answers: ["Esta semana hemos vuelto tarde todos los días."], why: "_Volver_ → **vuelto** (irregular)." },
          { sentence: "Nunca no he comido fruta bomba.", answers: ["Nunca he comido fruta bomba.", "No he comido nunca fruta bomba.", "No he comido fruta bomba nunca."], why: "Con _nunca_ delante, sobra el _no_. (En Cuba, la papaya se llama **fruta bomba**.)" },
          { sentence: "Mis primas han venidas a La Habana.", answers: ["Mis primas han venido a La Habana."], why: "Con _haber_ el participio no concuerda: **venido**." },
          { sentence: "—Nunca he estado en Varadero. —Yo también.", answers: ["—Nunca he estado en Varadero. —Yo tampoco."], why: "Para estar de acuerdo con una frase negativa: **yo tampoco**." },
        ],
      },
      {
        id: "x3",
        type: "transform",
        title: "De la costumbre al perfecto",
        prompt: "Repaso de los verbos en -er/-ir: pasa la frase al perfecto según la instrucción.",
        items: [
          { source: "Bebo café cubano todas las mañanas.", instruction: "Di qué has hecho **esta mañana**.", answers: ["Esta mañana he bebido café cubano.", "He bebido café cubano esta mañana."], why: "_Beber_ → **bebido** (regular, -er → -ido)." },
          { source: "Escribimos en el blog los domingos.", instruction: "Cambia a **esta semana**.", answers: ["Esta semana hemos escrito en el blog.", "Hemos escrito en el blog esta semana."], why: "_Escribir_ → **escrito** (irregular)." },
          { source: "Mis amigos nunca vienen a Cuba.", instruction: "Habla de su experiencia: empieza con «Mis amigos nunca…».", answers: ["Mis amigos nunca han venido a Cuba."], why: "_Venir_ → **venido**; _nunca_ delante de _han_." },
          { source: "¿Abres la ventana?", instruction: "Pregunta si ya lo ha hecho, con **ya**.", answers: ["¿Ya has abierto la ventana?", "¿Has abierto ya la ventana?", "¿Has abierto la ventana ya?"], why: "_Abrir_ → **abierto** (irregular)." },
          { source: "Leo el periódico en el desayuno.", instruction: "Ya ha pasado hoy: empieza con «Hoy…».", answers: ["Hoy he leído el periódico en el desayuno.", "Hoy ya he leído el periódico en el desayuno."], why: "_Leer_ → **leído**, con tilde." },
        ],
      },
      {
        id: "x4",
        type: "context",
        title: "La pregunta de seguimiento",
        prompt: "Elige la mejor manera de continuar la conversación.",
        items: [
          { context: "Tu compañero dice: «He vivido seis meses en Santiago de Chile».", q: "Respondes:", options: ["¡Qué interesante! ¿Y qué tal la experiencia?", "¿Alguna vez has vivido en Santiago de Chile?", "¿Vives seis meses?"], answer: 0, why: "Reacción + pregunta nueva. La segunda opción repite lo que él acaba de decir." },
          { context: "Tu amiga dice: «Este año he aprendido a bucear».", q: "Respondes:", options: ["¿Ya no buceas?", "¡Qué bien! ¿Y buceas a menudo?", "Yo tampoco."], answer: 1, why: "Combinas perfecto (la experiencia) y presente con frecuencia (su vida ahora): **¿buceas a menudo?**" },
          { context: "Un señor mayor te cuenta: «He tocado la trompeta en una orquesta durante cuarenta años».", q: "Respondes:", options: ["¿Tocas tú?", "¿Has tocado alguna vez?", "¡Qué interesante! ¿Y todavía toca?"], answer: 2, why: "Es un señor mayor: **usted** (_toca_). Y _todavía_ + presente pregunta por su vida ahora." },
        ],
      },
      {
        id: "x5",
        type: "open",
        title: "Escribe tú",
        prompt: "Escritura guiada: escribe frases completas con el lenguaje de la semana.",
        items: [
          {
            prompt: "Prepara tres preguntas con **¿Alguna vez has…?** para tu próxima clase, sobre viajes, comida y tiempo libre. Contesta tú cada una con una frase completa.",
            model: "¿Alguna vez has hecho submarinismo? — Sí, lo he hecho una vez, en México. ¿Alguna vez has comido insectos? — No, nunca. ¿Alguna vez has ido a un concierto de salsa? — No, todavía no, pero quiero ir.",
            checklist: ["Cada pregunta tiene _has_ + participio, sin nada en medio.", "Las respuestas usan _una vez_, _nunca_ o _todavía no_.", "Al menos un participio es irregular."],
          },
          {
            prompt: "Responde a este mensaje de Yamilé: «¿Qué tal tu primer día en La Habana? ¿Qué has hecho? ¿Ya has probado el café cubano?» Escribe tres o cuatro frases.",
            model: "¡Hola, Yamilé! Mi primer día ha sido increíble. He dado un paseo por el Malecón y he visitado la catedral. Sí, ya he probado el café cubano: ¡es muy fuerte! Todavía no he ido a la playa.",
            checklist: ["Usas el perfecto para hablar de hoy.", "Respondes a la pregunta con _ya_ o _todavía no_.", "Saludas y escribes frases completas."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe un mensaje para el grupo de huéspedes de tu casa particular: qué has hecho ya, qué todavía no y una experiencia que nunca has tenido.",
    context: "Yamilé ha creado un grupo de WhatsApp para sus huéspedes y pregunta: «¿Qué tal su semana en La Habana, muchachos?».",
    steps: [
      "Saluda a Yamilé y al grupo.",
      "Cuenta dos o tres cosas que **ya** has hecho esta semana.",
      "Di una cosa que **todavía no** has hecho y cuándo quieres hacerla.",
      "Cuenta algo que **nunca** has hecho y compáralo con tu costumbre en tu país (presente + frecuencia).",
      "Termina con una pregunta para el grupo.",
    ],
    useLanguage: ["Esta semana he…", "Ya he… / Todavía no he…", "Nunca he… / No he… nunca", "En mi país casi nunca / a veces…", "¿Alguien ha…?"],
    model: [
      "¡Hola, Yamilé! ¡Hola a todos! Mi semana ha sido increíble. Ya he visitado La Habana Vieja y he dado un paseo por el Malecón al atardecer. También he probado la ropa vieja: ¡riquísima! Todavía no he ido a la playa, pero quiero ir el sábado. Y una confesión: nunca he bailado salsa. En mi país casi nunca bailo, pero aquí todo el mundo baila. ¿Alguien quiere enseñarme? ¡Un abrazo!",
    ],
    checklist: [
      "Uso **haber** + participio, sin nada en medio.",
      "Uso al menos dos participios irregulares (_hecho, visto, escrito, vuelto…_).",
      "Uso **ya**, **todavía no** y **nunca** en el lugar correcto.",
      "Uso el presente con un adverbio de frecuencia para mi costumbre.",
      "Termino con una pregunta para el grupo.",
    ],
    words: [60, 100],
  },
  speaking: {
    intro: "Esta semana tu producción oral es un juego: tres verdades y una mentira. Practica hasta decirlo sin leer.",
    tasks: [
      {
        title: "Tres verdades y una mentira",
        prompt: "Cuenta cuatro experiencias: tres reales y una inventada. Para cada una, añade un detalle (cuántas veces, dónde, con quién). En clase, los demás tienen que adivinar cuál es la mentira.",
        prep: ["He… muchas veces / una vez.", "Nunca he… / No he… nunca.", "He estado en… con…", "Un detalle: _en mi país…_, _con mi hermana…_"],
        seconds: 60,
        model: "Bueno, ahí van mis cuatro experiencias. Uno: he comido insectos en Oaxaca, dos veces. Dos: nunca he visto la nieve. Tres: he cantado en un karaoke delante de doscientas personas. Y cuatro: he perdido un vuelo por quedarme dormido. ¿Cuál es la mentira?",
        selfCheck: ["Uno _he_ + participio sin pausa: _he_estado_, _lo_he_visto_.", "Uso al menos dos participios irregulares.", "Pongo _nunca_ en el lugar correcto."],
      },
      {
        title: "Mensaje de voz para Ernesto",
        prompt: "Ernesto te ofrece un tour en el almendrón de su tío. Grábale un mensaje de voz: dile qué has hecho ya en La Habana, qué todavía no y hazle dos preguntas con ¿Alguna vez…? o ¿Ya…?",
        prep: ["¡Hola, Ernesto! Gracias por…", "Ya he… / Todavía no he…", "¿Tú alguna vez has…?", "¿Ya has…?"],
        seconds: 40,
        model: "¡Hola, Ernesto! Gracias por la invitación. Ya he visto la catedral y el Malecón, pero todavía no he ido al Morro. ¿Podemos ir en el almendrón? Oye, una pregunta: ¿tú alguna vez has salido de Cuba? ¿Y ya has probado la comida colombiana de Camila? ¡Hasta luego!",
        selfCheck: ["Hablo de tú con Ernesto.", "Uso _ya_ y _todavía no_.", "Las preguntas tienen entonación de pregunta."],
      },
      {
        title: "Tu semana en 40 segundos",
        prompt: "Cuenta tu semana real: tres cosas que has hecho, una que todavía no has hecho y una costumbre tuya con un adverbio de frecuencia.",
        prep: ["Esta semana he…", "También he…", "Todavía no he…", "Normalmente / casi nunca / todos los días…"],
        seconds: 40,
        model: "Esta semana he trabajado mucho. He escrito un informe largo y he ido al gimnasio dos veces. Todavía no he limpiado la casa: ¡está horrible! Normalmente cocino los domingos, pero esta semana he comido fuera casi todos los días.",
        selfCheck: ["Distingo presente (costumbre) y perfecto (esta semana).", "Hablo sin leer.", "Mi único acento fuerte en el bloque es el participio."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo, conviertes el perfecto en conversación real.",
    cards: [
      { move: "Cuenta", task: "Di tus tres verdades y una mentira. Deja que tu profesor o tus compañeros te hagan dos preguntas antes de adivinar.", phrases: ["He… dos veces.", "Nunca he…", "¿Cuál es la mentira?"] },
      { move: "Pregunta", task: "Haz tres preguntas sobre experiencias a tu profesor o profesora. Decide antes si hablas de tú o de usted.", phrases: ["¿Alguna vez has…?", "¿Alguna vez ha… usted?", "¿Ya has…?"] },
      { move: "Reacciona", task: "Reacciona a cada respuesta con una expresión de interés y una pregunta de seguimiento en presente.", phrases: ["¡Qué envidia! ¿Y todavía…?", "¿De verdad? ¿Cuántas veces?", "Yo tampoco."] },
      { move: "Compara", task: "Pregunta cómo dice tu profesor «hoy he comido…» en su país: ¿usa el perfecto o otro pasado?", phrases: ["En tu país, ¿se dice «hoy he comido» o «hoy comí»?", "En Cuba prefieren…"] },
    ],
    bring: "Tus cuatro experiencias (tres verdades y una mentira) escritas en una tarjeta, solo con palabras clave.",
  },
  quiz: {
    items: [
      { type: "choice", q: "—¿Ya has comprado los billetes para Trinidad? —No, ___. Los compro mañana.", options: ["ya no", "todavía no", "nunca"], answer: 1, why: "Algo planeado que no ha pasado: **todavía no**. _Ya no_ = no más." },
      { type: "choice", q: "¿Qué frase habla de una experiencia de toda la vida?", options: ["Siempre bebo jugo en el desayuno.", "Esta mañana he desayunado tarde.", "Nunca he visto un huracán."], answer: 2, why: "_Nunca he visto_ = en toda mi vida. La primera es una costumbre; la segunda habla de hoy." },
      { type: "listen", q: "¿Dónde no ha estado nunca el hermano?", audio: "Mi hermano ha vivido en Miami, pero nunca ha estado en Cuba.", voice: "es-CU-m", options: ["en Miami", "en Cuba", "en México"], answer: 1, why: "_Ha vivido en Miami, pero nunca ha estado en Cuba._" },
      { type: "listen", q: "¿Qué no han hecho todavía?", audio: "Todavía no hemos encontrado las llaves del balcón.", voice: "es-ES-f", options: ["encontrar las llaves", "abrir el balcón", "cerrar la puerta"], answer: 0, why: "_Todavía no hemos encontrado las llaves._" },
      { type: "gap", q: "Esta mañana mis padres me han ___ (escribir) un mensaje y yo todavía no les he ___ (responder).", answers: [["escrito"], ["respondido"]], why: "_Escribir_ → **escrito** (irregular); _responder_ → **respondido** (regular)." },
      { type: "gap", q: "Nosotros ya ___ (ver) el Malecón, pero ustedes todavía no lo ___ (ver).", answers: [["hemos visto"], ["han visto"]], why: "Nosotros → **hemos**; ustedes → **han**. _Ver_ → **visto**." },
      { type: "transform", source: "Ana viaja sola.", instruction: "Di que Ana no lo ha hecho en toda su vida, con **nunca**.", answers: ["Ana nunca ha viajado sola.", "Ana no ha viajado nunca sola.", "Ana no ha viajado sola nunca."], why: "_Nunca_ delante, o _no_… _nunca_ alrededor del verbo." },
      { type: "transform", source: "¿Has hecho la maleta?", instruction: "Pregunta a un grupo de amigos en Cuba (ustedes).", answers: ["¿Han hecho la maleta?", "¿Ustedes han hecho la maleta?", "¿Han hecho las maletas?", "¿Ustedes han hecho las maletas?"], why: "En América, para un grupo: **ustedes han**." },
      { type: "order", words: ["Esta", "semana", "he", "vuelto", "tarde", "a", "casa."], alt: ["He vuelto tarde a casa esta semana.", "Esta semana he vuelto a casa tarde.", "He vuelto a casa tarde esta semana."], en: "This week I've come home late.", why: "_He vuelto_ va junto; el marcador temporal, al principio o al final." },
      { type: "error", sentence: "Hoy he ponido el móvil en la mochila.", answers: ["Hoy he puesto el móvil en la mochila."], why: "_Poner_ → **puesto** (irregular)." },
      { type: "error", sentence: "Ellos han ya visitado Trinidad.", answers: ["Ellos ya han visitado Trinidad.", "Ya han visitado Trinidad.", "Ellos han visitado ya Trinidad."], why: "_Ya_ no puede ir entre _han_ y el participio." },
      { type: "error", sentence: "Mi abuela no ha nunca salido de Cuba.", answers: ["Mi abuela no ha salido nunca de Cuba.", "Mi abuela nunca ha salido de Cuba."], why: "_Nunca_ va delante de _ha_, o detrás del participio con _no_ delante." },
      { type: "open", prompt: "Escribe tres frases sobre ti: una experiencia que has tenido varias veces, una que no has tenido nunca y algo que todavía no has hecho esta semana.", model: "He ido a Nueva York tres veces. Nunca he montado a caballo. Esta semana todavía no he llamado a mi abuela.", checklist: ["_Haber_ + participio sin nada en medio.", "_Nunca_ y _todavía no_ en su lugar.", "Al menos un participio irregular."] },
    ],
  },
  complete: {
    canNow: [
      "Formar el pretérito perfecto con **he, has, ha, hemos, habéis, han** + participio.",
      "Usar los participios irregulares más frecuentes: _hecho, dicho, visto, escrito, puesto, vuelto, abierto, roto_.",
      "Preguntar por experiencias con **¿Alguna vez has…?** y responder con _ya_, _todavía no_ y _nunca_.",
      "Reaccionar con interés y hacer preguntas de seguimiento.",
      "Unir _lo_he_visto_ en un solo bloque al hablar y reconocer _pasao_ en el habla caribeña.",
    ],
    review: [
      "El participio no concuerda con _haber_: _ellas han visitado_.",
      "Nunca he… = No he… nunca.",
      "Todavía no (aún no ha pasado) ≠ ya no (ya terminó).",
      "Presente + frecuencia para costumbres: _casi nunca como marisco_.",
    ],
  },
  related: [
    { path: "/sistema-verbal/preterito-perfecto-compuesto-indicativo", label: "Sistema verbal · pretérito perfecto compuesto" },
  ],
};
