import type { Module } from "../../types";

export const a2w05: Module = {
  id: "a2-05",
  level: "a2",
  week: 5,
  kind: "checkpoint",
  title: "Checkpoint 1: Mi pasado",
  subtitle: "Repasa las semanas 1 a 4: experiencias, un día concreto, una biografía y tu infancia, eligiendo el pasado adecuado.",
  stop: { place: "Santiago de los Caballeros", country: "República Dominicana" },
  minutes: 95,
  newObjectives: ["a2.rev.checkpoint-1", "a2.lis.podcast-recuerdos"],
  reviewObjectives: [
    "a2.gram.perfecto-compuesto",
    "a2.gram.participios-irregulares",
    "a2.gram.ya-todavia",
    "a2.voc.experiencias-viaje",
    "a2.pron.sinalefa-compuestos",
    "a2.fun.experiencias",
    "a2.gram.indefinido-regular",
    "a2.gram.marcadores-pasado",
    "a2.voc.fin-de-semana",
    "a2.pron.acento-tiempos",
    "a2.fun.contar-ayer",
    "a2.gram.indefinido-irregular",
    "a2.gram.ser-ir-indefinido",
    "a2.voc.etapas-vida",
    "a2.pron.tilde-diacritica",
    "a2.fun.biografia",
    "a2.gram.imperfecto",
    "a2.gram.soler",
    "a2.voc.infancia",
    "a2.pron.s-aspirada",
    "a2.fun.comparar-antes",
  ],
  prerequisites: ["a2-04"],
  goal: {
    canDo: "Al final de esta semana puedes hablar de tus experiencias, contar un día concreto o una biografía y describir tu infancia, eligiendo entre **he hecho**, **hice** y **hacía**.",
    canDoEn: "By the end of this week, you can talk about your experiences, tell what happened on a specific day or in someone's life, and describe your childhood, choosing between the three past tenses you have learned.",
    steps: [
      "Repasa en cuatro resúmenes los tres pasados, las formas irregulares y las confusiones típicas.",
      "Practica todo mezclado: marcadores, participios, **fui/fue**, **ya/todavía no**, **solía**.",
      "Escucha un pódcast de recuerdos grabado en Santiago de los Caballeros y separa lo habitual de lo que pasó una vez.",
      "Lee el blog de una santiaguera que vuelve a su ciudad y escribe tu propio texto «Mi pasado en tres tiempos».",
      "Graba tres minirrelatos y haz el test de control de 16 preguntas.",
    ],
  },
  theory: {
    intro: "Esta semana no hay gramática nueva. En cuatro semanas has aprendido tres pasados: el **pretérito perfecto** (he viajado), el **indefinido** (viajé) y el **imperfecto** (viajaba). Ahora toca ordenarlos: cada uno responde a una pregunta distinta. Cada resumen termina con las confusiones más frecuentes en este punto del curso.",
    parts: [
      {
        heading: "Tres pasados, tres preguntas",
        body: [
          "**¿Lo has hecho alguna vez? ¿Qué has hecho hoy?** → pretérito perfecto (**he + participio**). Hablas de experiencias de toda tu vida, sin decir cuándo, o de un tiempo que todavía no ha terminado: _hoy, esta semana, este año_. **¿Has probado el mofongo?** — **Sí, lo he probado dos veces.**",
          "**¿Qué pasó ese día?** → indefinido. Hablas de una acción terminada en un momento terminado y concreto: _ayer, el sábado, en 2019, hace tres años, cuando tenía veinte años_. **El sábado fuimos al Monumento y comimos en el centro.** También es el tiempo de las biografías: **Nació en 1950, se casó en 1975 y se jubiló en 2010.**",
          "**¿Cómo era? ¿Qué hacías normalmente?** → imperfecto. Describes personas, lugares y situaciones del pasado y cuentas hábitos: **De niña vivía en el campo, la casa era pequeña y todos los domingos íbamos al río.** Para hábitos también puedes usar **solía + infinitivo**: **Solía jugar en la calle.**",
          "La clave no es «cuánto tiempo hace», sino **cómo miras la acción**: como experiencia conectada contigo ahora (he hecho), como hecho cerrado en un momento (hice) o como escena y costumbre (hacía).",
        ],
        support: [
          "Perfect (_he viajado_): life experience without a date, or things in a period that is still open (today, this week). Preterite (_viajé_): finished actions on a specific finished occasion (yesterday, in 2019, three years ago). Imperfect (_viajaba_): descriptions and habits in the past — 'used to' / 'was …ing'.",
          "Regional note: in most of Latin America (and in the Canary Islands and parts of Spain), people often use the preterite even for today: _Hoy comí mangú_. In central Spain you will hear _Hoy he comido mangú_. Both are correct in their region; for experiences without a date (_¿Has estado en Cuba?_) the perfect is common everywhere.",
        ],
        table: {
          caption: "Los marcadores te dan la pista",
          head: ["Tiempo", "Marcadores típicos", "Ejemplo"],
          rows: [
            ["perfecto (he hecho)", "alguna vez, nunca, ya, todavía no, hoy, esta semana, este año", "Nunca he visto la nieve."],
            ["indefinido (hice)", "ayer, anoche, el lunes, en 2018, hace dos años, el año pasado", "Hace dos años fui a Puerto Plata."],
            ["imperfecto (hacía)", "de niño/a, antes, siempre, todos los días, normalmente, cuando era pequeño", "De niño siempre iba en guagua al colegio."],
          ],
        },
        examples: [
          { es: "¿Has estado alguna vez en Santiago? — Sí, estuve allí en 2022.", en: "Have you ever been to Santiago? — Yes, I was there in 2022.", note: "La pregunta es de experiencia (perfecto); la respuesta da una fecha (indefinido)." },
          { es: "Antes trabajaba en un banco; ahora soy profesora.", en: "I used to work at a bank; now I'm a teacher." },
          { es: "Esta mañana he desayunado / desayuné en casa de mi abuela.", en: "This morning I had breakfast at my grandmother's.", note: "Las dos opciones son correctas: la primera es más española; la segunda, más americana." },
        ],
        mistakes: [
          { wrong: "Ayer he ido al cine.", right: "Ayer fui al cine.", why: "_Ayer_ es un tiempo terminado: con él se usa el **indefinido** en todas las variedades." },
          { wrong: "¿Has ido a México el año pasado?", right: "¿Fuiste a México el año pasado?", why: "Con una fecha terminada (_el año pasado_) no se usa el perfecto: **indefinido**. Sin fecha, sí: _¿Has ido alguna vez a México?_" },
          { wrong: "Cuando era niño, fui a la playa todos los veranos.", right: "Cuando era niño, iba a la playa todos los veranos.", why: "_Todos los veranos_ es un hábito: **imperfecto**." },
        ],
        tip: "Antes de hablar, hazte la pregunta: ¿experiencia (he…), hecho con fecha (…é / …ó) o escena y costumbre (…aba / …ía)?",
      },
      {
        heading: "Las formas que hay que saber de memoria",
        body: [
          "**Participios irregulares** (para el perfecto): hacer → **hecho**, decir → **dicho**, ver → **visto**, escribir → **escrito**, poner → **puesto**, volver → **vuelto**, abrir → **abierto**, romper → **roto**. Los demás son regulares: habl**ado**, com**ido**, viv**ido**.",
          "**Indefinidos irregulares** (semana 3): no llevan tilde y tienen raíces nuevas: **estuve, tuve, pude, puse, hice, vine, dije**. En la tercera persona, _hacer_ cambia la c por z: **hizo**. _Decir_ pierde la i en ellos: **dijeron** (no _dijieron_).",
          "**Ser** e **ir** comparten el indefinido: **fui, fuiste, fue, fuimos, fuisteis, fueron**. El contexto decide: **Fue a Santiago** (ir: hay un destino con _a_) frente a **Fue un viaje precioso** (ser: describe y valora).",
          "**Imperfecto**: solo tres verbos irregulares: **ser** (era), **ir** (iba) y **ver** (veía). Los demás son regulares: habl**aba**, com**ía**, viv**ía**.",
        ],
        support: [
          "Irregular preterites have no accent mark: _hice, hizo, vine, vino, estuve, estuvo_. Compare regular _habló_, which needs one.",
          "_Fue_ can mean 'went' or 'was'. If it is followed by _a_ + place, it is _ir_; if it describes or judges something, it is _ser_.",
        ],
        table: {
          caption: "Un verbo, tres pasados",
          head: ["Infinitivo", "Perfecto (yo)", "Indefinido (yo / él)", "Imperfecto (yo)"],
          rows: [
            ["hacer", "he hecho", "hice / hizo", "hacía"],
            ["decir", "he dicho", "dije / dijo", "decía"],
            ["ver", "he visto", "vi / vio", "veía"],
            ["poner", "he puesto", "puse / puso", "ponía"],
            ["volver", "he vuelto", "volví / volvió", "volvía"],
            ["ir", "he ido", "fui / fue", "iba"],
            ["ser", "he sido", "fui / fue", "era"],
            ["estar", "he estado", "estuve / estuvo", "estaba"],
            ["tener", "he tenido", "tuve / tuvo", "tenía"],
          ],
        },
        examples: [
          { es: "Todavía no he escrito el correo.", en: "I haven't written the email yet." },
          { es: "Mi abuelo vino a Santiago en 1965 y puso una tienda de tabaco.", en: "My grandfather came to Santiago in 1965 and opened a tobacco shop." },
          { es: "La fiesta fue en casa de Yari, pero yo no fui.", en: "The party was at Yari's house, but I didn't go." },
        ],
        mistakes: [
          { wrong: "He hacido la tarea.", right: "He hecho la tarea.", why: "_Hacer_ tiene participio irregular: **hecho**." },
          { wrong: "Ayer no pudé venir.", right: "Ayer no pude venir.", why: "Los indefinidos irregulares no llevan tilde: **pude**, **vine**, **hice**." },
          { wrong: "Mis padres me dijieron la verdad.", right: "Mis padres me dijeron la verdad.", why: "Después de **j**, la terminación es **-eron**: dij**eron**, traj**eron**." },
          { wrong: "De pequeña veía a mi tía y ella fue muy simpática.", right: "De pequeña veía a mi tía y ella era muy simpática.", why: "Describes cómo era una persona en una época: **imperfecto** (_era_)." },
        ],
      },
      {
        heading: "Pequeñas palabras que deciden: ya, todavía no, nunca, solía, antes",
        body: [
          "**Ya** dice que algo ha pasado (quizás antes de lo esperado): **Ya he comprado los boletos.** **Todavía no** dice que no ha pasado, pero esperas que pase: **Todavía no he llamado a mi madre.** **Nunca** dice que no ha pasado en toda tu vida: **Nunca he subido al Pico Duarte.**",
          "**Nunca** puede ir delante del verbo (**Nunca he ido**) o detrás con _no_ (**No he ido nunca**). Lo que no puedes hacer es poner _no_ y _nunca_ delante a la vez.",
          "En el perfecto, **he** y el participio no se separan: los pronombres van delante (**lo he visto**) y _ya_, _nunca_ y _todavía no_ también (**ya lo he visto**), nunca en el medio.",
          "Para comparar antes y ahora, combina el imperfecto con el presente: **Antes vivía en el campo; ahora vivo en la ciudad.** **Solía + infinitivo** expresa un hábito pasado; **suelo + infinitivo**, un hábito actual: **Solía caminar mucho; ahora suelo ir en carro.**",
        ],
        support: [
          "_Ya_ = already / yet (in questions). _Todavía no_ = not yet. _Nunca_ = never. Keep _he + participle_ together: _Ya lo he visto_, never _He ya visto_.",
          "_Solía_ + infinitive = I used to. _Suelo_ + infinitive = I usually (now).",
        ],
        examples: [
          { es: "¿Ya has terminado el libro? — No, todavía no.", en: "Have you finished the book yet? — No, not yet." },
          { es: "No he probado nunca el chivo guisado.", en: "I've never tried goat stew." },
          { es: "Antes solíamos cenar a las seis; ahora cenamos a las nueve.", en: "We used to have dinner at six; now we have dinner at nine." },
        ],
        mistakes: [
          { wrong: "He ya visitado el centro.", right: "Ya he visitado el centro.", why: "_He_ y el participio van juntos: **ya** va delante." },
          { wrong: "No nunca he estado en Cuba.", right: "Nunca he estado en Cuba. / No he estado nunca en Cuba.", why: "O **nunca** delante del verbo, o **no** delante y **nunca** detrás." },
          { wrong: "Antes solía a jugar béisbol.", right: "Antes solía jugar béisbol.", why: "_Soler_ va directamente con el infinitivo, sin _a_." },
        ],
        tip: "En el Caribe es muy normal _jugar pelota_ o _jugar béisbol_, sin artículo; en España se dice _jugar al béisbol_.",
      },
      {
        heading: "La tilde y el oído: lo que cambia el significado",
        body: [
          "Una tilde puede cambiar el tiempo verbal: **hablo** (yo, ahora) frente a **habló** (él, ayer); **trabajo** frente a **trabajó**; **llego** frente a **llegó**. En el indefinido regular, **yo** y **él/ella** llevan tilde en la última sílaba: habl**é**, habl**ó**, com**í**, com**ió**.",
          "La **tilde diacrítica** distingue palabras de una sílaba: **tú** (pronombre) / **tu** (posesivo); **él** / **el**; **sí** (afirmación) / **si** (condición); **mí** / **mi**; **sé** (saber) / **se**; **más** / **mas**. En una biografía es fácil confundirlas: **Él nació en Moca; el pueblo es pequeño.**",
          "Al oír, recuerda dos cosas de las semanas 1 y 4. En el perfecto, las palabras se unen: **lo_he_hecho** suena como una sola palabra. Y en el Caribe —también en Santiago— la **s** final se aspira o se pierde: _¿Cómo ehtá?_, _lo' do' niño'_. El contexto (y el verbo) te ayudan a entender si es singular o plural.",
        ],
        support: [
          "Stress changes the tense: _hablo_ (I speak) vs _habló_ (he spoke). Written accents on one-syllable words separate pairs like _tú/tu_, _él/el_, _sí/si_.",
          "In Caribbean Spanish, final -s is often aspirated (like a soft h) or dropped. Listen for other clues: _los niños estaban_ may sound like _lo' niño' ehtaban_, but the verb _estaban_ tells you it is plural.",
        ],
        table: {
          caption: "Parejas que hay que separar",
          head: ["Sin tilde", "Con tilde", "Ejemplo"],
          rows: [
            ["trabajo (yo, presente)", "trabajó (él, pasado)", "Hoy trabajo en casa; ayer Ana trabajó en la oficina."],
            ["tu (posesivo)", "tú (pronombre)", "¿Tú conociste a tu abuelo?"],
            ["el (artículo)", "él (pronombre)", "Él vivió en el Cibao."],
            ["si (condición)", "sí (afirmación)", "Si quieres, te lo cuento. — ¡Sí, cuéntamelo!"],
            ["se (pronombre)", "sé (saber)", "No sé cuándo se casó."],
          ],
        },
        examples: [
          { es: "Mi padre se jubiló el año pasado; yo todavía trabajo.", en: "My father retired last year; I still work." },
          { es: "Él me lo ha dicho a mí, no a ti.", en: "He has told me, not you." },
        ],
        mistakes: [
          { wrong: "Ayer mi hermano llego tarde.", right: "Ayer mi hermano llegó tarde.", why: "Pasado, tercera persona: **llegó**, con tilde. _Llego_ es presente, yo." },
          { wrong: "¿Tu has estado en Jarabacoa?", right: "¿Tú has estado en Jarabacoa?", why: "Es el pronombre (sujeto): **tú**, con tilde." },
        ],
      },
    ],
  },
  grammar: {
    intro: "Todo mezclado. Antes de responder, decide primero qué pregunta responde la frase: ¿experiencia, hecho con fecha o escena y costumbre?",
    exercises: [
      {
        id: "g1",
        type: "classify",
        title: "¿Por qué este pasado?",
        prompt: "Clasifica cada frase según el uso del tiempo verbal.",
        categories: ["experiencia o tiempo abierto (he hecho)", "hecho en un momento terminado (hice)", "descripción o hábito (hacía)"],
        items: [
          { text: "Nunca he bailado bachata en público.", cat: 0, why: "Experiencia en toda la vida, sin fecha: perfecto." },
          { text: "En 1863 empezó la Guerra de la Restauración.", cat: 1, why: "Fecha concreta y terminada: indefinido." },
          { text: "Mi escuela tenía un patio enorme con un mango.", cat: 2, why: "Describe cómo era un lugar: imperfecto." },
          { text: "Esta semana he cocinado tres veces.", cat: 0, why: "_Esta semana_ no ha terminado: perfecto." },
          { text: "Los sábados mi abuela nos hacía arepitas de yuca.", cat: 2, why: "_Los sábados_ = hábito: imperfecto." },
          { text: "Anoche vimos el partido en casa de Junior.", cat: 1, why: "_Anoche_ es un momento terminado: indefinido." },
          { text: "¿Ya has leído el mensaje de la profe?", cat: 0, why: "_Ya_ en pregunta: perfecto, el resultado importa ahora." },
          { text: "De adolescente era muy tímido.", cat: 2, why: "Describe a una persona en una época: imperfecto." },
        ],
      },
      {
        id: "g2",
        type: "gap",
        title: "Los marcadores mandan",
        prompt: "Completa con el verbo entre paréntesis en el tiempo adecuado. Si hay dos opciones correctas según la región, las dos valen.",
        items: [
          { q: "Hace tres años ___ (mudarse, yo) a Santiago por trabajo.", answers: [["me mudé"]], why: "_Hace tres años_ fija un momento terminado: indefinido." },
          { q: "Cuando ___ (ser, nosotros) pequeños, ___ (vivir) cerca del río Yaque.", answers: [["éramos"], ["vivíamos"]], why: "Descripción de una época: imperfecto. _Ser_ es irregular: **éramos**." },
          { q: "¿Alguna vez ___ (ver, tú) un partido de las Águilas Cibaeñas?", answers: [["has visto"]], why: "_Alguna vez_ pregunta por experiencias: perfecto. Participio irregular: **visto**." },
          { q: "El domingo pasado mis primos ___ (venir) a comer y nos ___ (traer) un dulce de leche.", answers: [["vinieron"], ["trajeron"]], why: "Momento terminado: indefinido irregular. Ojo: **trajeron**, sin i después de la j." },
          { q: "Hoy ___ (levantarse, yo) tardísimo.", answers: [["me he levantado", "me levanté"]], why: "_Hoy_: perfecto en España; en gran parte de América también se usa el indefinido." },
          { q: "Antes mi papá ___ (soler) fumar, pero lo ___ (dejar) en 2015.", answers: [["solía"], ["dejó"]], why: "Hábito pasado: **solía**. Cambio en una fecha concreta: **dejó**." },
        ],
      },
      {
        id: "g3",
        type: "choice",
        title: "Formas irregulares",
        prompt: "Elige la forma correcta.",
        items: [
          { q: "Todavía no he ___ la ventana del cuarto.", options: ["abierto", "abrido", "abrí"], answer: 0, why: "Participio irregular de _abrir_: **abierto**." },
          { q: "¿Quién ___ la torta de cumpleaños? ¡Está buenísima!", options: ["hizo", "hició", "hace"], answer: 0, why: "Indefinido de _hacer_ en tercera persona: **hizo** (c → z, sin tilde)." },
          { q: "Ayer no ___ ir a la reunión porque estaba enferma.", options: ["pude", "podí", "he podido"], answer: 0, why: "_Ayer_ → indefinido; _poder_ es irregular: **pude**." },
          { q: "De pequeños, mi hermano y yo ___ al colegio a pie.", options: ["íbamos", "fuimos", "hemos ido"], answer: 0, why: "Hábito de la infancia: imperfecto de _ir_, **íbamos**." },
          { q: "¿Dónde ___ las llaves? No las encuentro.", options: ["has puesto", "has ponido", "ponías"], answer: 0, why: "El resultado importa ahora (no las encuentro): perfecto, participio **puesto**." },
        ],
      },
      {
        id: "g4",
        type: "transform",
        title: "Cambia el marcador, cambia el verbo",
        prompt: "Reescribe la frase con el nuevo marcador. Cambia el tiempo verbal si es necesario.",
        items: [
          { source: "Esta mañana he ido al mercado. → Ayer…", answers: ["Ayer fui al mercado."], why: "_Ayer_ exige indefinido: he ido → **fui**." },
          { source: "El verano pasado fuimos a la playa. → De niños, todos los veranos…", answers: ["De niños, todos los veranos íbamos a la playa.", "De niños, todos los veranos solíamos ir a la playa."], why: "Hábito en la infancia: imperfecto (**íbamos**) o **solíamos ir**." },
          { source: "En 2020 escribí una novela. → Nunca…", answers: ["Nunca he escrito una novela.", "No he escrito nunca una novela."], why: "_Nunca_ habla de experiencia: perfecto, con el participio irregular **escrito**." },
          { source: "Ahora suelo trabajar en casa. → Antes…", answers: ["Antes solía trabajar en casa.", "Antes trabajaba en casa."], why: "Hábito pasado: **solía** + infinitivo o imperfecto." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Repasa el vocabulario de las cuatro semanas en bloques que se usan juntos. Fíjate en el tiempo verbal con el que suele aparecer cada bloque.",
    groups: [
      {
        title: "Experiencias y viajes (semana 1)",
        items: [
          { es: "He probado la comida típica.", en: "I've tried the local food." },
          { es: "Nunca he subido a una montaña tan alta.", en: "I've never climbed such a high mountain." },
          { es: "He perdido un vuelo dos veces.", en: "I've missed a flight twice." },
          { es: "¿Has hecho alguna vez un viaje solo?", en: "Have you ever travelled alone?" },
          { es: "conocer un lugar / a una persona", en: "to visit a place for the first time / to meet someone" },
        ],
      },
      {
        title: "El fin de semana (semana 2)",
        items: [
          { es: "quedar con amigos", en: "to meet up with friends" },
          { es: "salir a cenar / salir de fiesta", en: "to go out for dinner / to go out partying" },
          { es: "dar un paseo por el centro", en: "to go for a walk downtown" },
          { es: "ir a la playa / al campo", en: "to go to the beach / to the countryside" },
          { es: "quedarse en casa viendo series", en: "to stay at home watching series" },
          { es: "hacer la compra / hacer el mandado (Caribe, México)", en: "to do the shopping / run errands" },
        ],
      },
      {
        title: "Etapas de la vida (semana 3)",
        items: [
          { es: "nacer en un pueblo", en: "to be born in a village" },
          { es: "terminar la carrera", en: "to finish one's degree" },
          { es: "mudarse a otra ciudad", en: "to move to another city" },
          { es: "casarse / divorciarse", en: "to get married / divorced" },
          { es: "tener hijos", en: "to have children" },
          { es: "jubilarse / retirarse (América)", en: "to retire" },
          { es: "emigrar a Estados Unidos", en: "to emigrate to the United States" },
        ],
      },
      {
        title: "La infancia (semana 4)",
        items: [
          { es: "jugar en la calle / jugar pelota", en: "to play in the street / to play ball" },
          { es: "el colegio / la escuela", en: "school" },
          { es: "el uniforme", en: "school uniform" },
          { es: "portarse bien / mal", en: "to behave well / badly" },
          { es: "pasar las vacaciones en casa de los abuelos", en: "to spend the holidays at the grandparents'" },
          { es: "la guagua (Caribe, Canarias) / el autobús", en: "the bus" },
          { es: "el patio, el barrio, los vecinos", en: "the yard, the neighbourhood, the neighbours" },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "Bloques que van juntos",
        prompt: "Une el verbo con su complemento natural.",
        pairs: [
          { left: "terminar", right: "la carrera de Medicina" },
          { left: "quedar", right: "con unos compañeros del trabajo" },
          { left: "mudarse", right: "a la capital" },
          { left: "pasar las vacaciones", right: "en casa de los abuelos" },
          { left: "perder", right: "el último vuelo a Santiago" },
          { left: "portarse", right: "mal en clase" },
        ],
        why: "Son colocaciones fijas: _terminar la carrera_, _quedar con alguien_, _mudarse a_, _pasar las vacaciones en_, _perder un vuelo_, _portarse bien/mal_.",
      },
      {
        id: "v2",
        type: "gap",
        title: "Una vida en cuatro frases",
        prompt: "Completa con una palabra del banco. Sobra una.",
        bank: ["nació", "se mudó", "se jubiló", "jugaba", "ha probado", "quedamos"],
        items: [
          { q: "Mi abuela ___ en Moca en 1948.", answers: [["nació"]], why: "Hito de una biografía con fecha: indefinido, **nació**." },
          { q: "De niño, mi padre ___ pelota en un solar del barrio.", answers: [["jugaba"]], why: "Hábito de la infancia: imperfecto, **jugaba**." },
          { q: "Mi tío trabajó cuarenta años en la fábrica y ___ el año pasado.", answers: [["se jubiló"]], why: "_Jubilarse_ = dejar de trabajar por la edad; momento terminado." },
          { q: "El sábado ___ con Rosa en el parque Central.", answers: [["quedamos"]], why: "_Quedar con alguien_ = verse con alguien; _el sábado_ → indefinido (nosotros: **quedamos**)." },
          { q: "Mi novio es español y todavía no ___ el sancocho.", answers: [["ha probado"]], why: "_Todavía no_ + experiencia: perfecto, **ha probado**." },
        ],
      },
      {
        id: "v3",
        type: "classify",
        title: "¿Qué semana es?",
        prompt: "¿De qué tema es cada frase?",
        categories: ["experiencias", "fin de semana", "etapas de la vida", "infancia"],
        items: [
          { text: "Nunca he dormido en una tienda de campaña.", cat: 0 },
          { text: "El domingo nos quedamos en casa viendo series.", cat: 1 },
          { text: "Se casaron en 1999 y tuvieron tres hijos.", cat: 2 },
          { text: "Llevaba uniforme azul y me portaba bastante mal.", cat: 3 },
          { text: "¿Has conocido a alguien famoso?", cat: 0 },
          { text: "Emigró a Nueva York cuando tenía veinte años.", cat: 2, why: "_Emigrar_ es un hito de la vida, contado con indefinido." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "Repaso: el acento que cambia el tiempo, el enlace y la s caribeña",
    explanation: [
      "En las semanas 1 a 4 has trabajado cuatro detalles que afectan a la comprensión de los pasados. El más importante es el **acento**: **trabajo** (presente) y **trabajó** (pasado) solo se distinguen por la sílaba fuerte. Si pronuncias mal el acento, cambias el tiempo verbal.",
      "En el perfecto, **he/ha/hemos + participio** se pronuncian juntos, sin pausa: _lo_he_hecho_, _ha_ido_, _todavía_no_he_ido_. La **h** no suena, así que las vocales se unen.",
      "En Santiago, como en todo el Caribe, la **s** al final de sílaba se aspira (suena como una h suave) o desaparece: _ehtaba_, _lo' amigo'_. No necesitas imitarla, pero sí reconocerla: es la pronunciación normal de millones de personas, también en Andalucía y Canarias.",
    ],
    support: [
      "Stress is grammar here: _hablo_ = I speak; _habló_ = he/she spoke. Push the last syllable in the preterite.",
      "Link the auxiliary and the participle: _he_estado_ sounds like one word. The h is always silent.",
    ],
    table: {
      head: ["Punto", "Ejemplo", "Qué hacer"],
      rows: [
        ["acento = tiempo", "PREparo / prepaRÓ", "golpe de voz en la última sílaba del pasado"],
        ["enlace", "lo_he_escrito", "sin pausa entre _he_ y el participio"],
        ["s aspirada", "¿Cómo ehtá?, lo' niño'", "reconocerla; usa el contexto"],
        ["tilde diacrítica", "tú / tu, él / el", "no se oye: se escribe"],
      ],
    },
    perceive: {
      id: "p1",
      type: "classify",
      title: "¿Presente o pasado?",
      prompt: "Escucha cada forma. ¿Es presente (yo) o pasado (él/ella)? Fíjate en la sílaba fuerte.",
      categories: ["presente: yo (…o)", "pasado: él / ella (…ó)"],
      items: [
        { text: "▶ 1", audio: "preparó", cat: 1, why: "pre-pa-**ró**: la fuerza va al final." },
        { text: "▶ 2", audio: "visito", cat: 0, why: "vi-**si**-to: sílaba fuerte en el medio, presente." },
        { text: "▶ 3", audio: "terminó", cat: 1, why: "ter-mi-**nó**: pasado." },
        { text: "▶ 4", audio: "bailo", cat: 0, why: "**bai**-lo: presente." },
        { text: "▶ 5", audio: "cocinó", cat: 1, why: "co-ci-**nó**: pasado." },
        { text: "▶ 6", audio: "estudio", cat: 0, why: "es-**tu**-dio: presente." },
        { text: "▶ 7", audio: "regresó", cat: 1, why: "re-gre-**só**: pasado." },
        { text: "▶ 8", audio: "camino", cat: 0, why: "ca-**mi**-no: presente (yo camino)." },
      ],
    },
    produce: [
      { text: "Hoy cocino yo; ayer cocinó mi hermana.", tip: "co-**ci**-no / co-ci-**nó**: exagera la diferencia al principio y luego suavízala." },
      { text: "Todavía no he ido, pero ya lo he visto en fotos.", tip: "Une: _no_he_ido_, _lo_he_visto_. Cada bloque, una sola palabra." },
      { text: "Mi abuela nació en Moca y se mudó a Santiago en 1970.", tip: "na-**ció**, mu-**dó**: las dos formas del pasado terminan con fuerza." },
      { text: "De niños íbamos todos los domingos al Monumento.", tip: "**í**-ba-mos: la fuerza va al principio. Las vocales del imperfecto no se reducen." },
      { text: "¿Tú conociste a tu bisabuelo? — Sí, él vivía con nosotros.", tip: "La tilde de _tú_ y _él_ no cambia el sonido, pero en el texto escrito sí cambia el significado." },
    ],
    spelling: "En el indefinido regular, **yo** y **él/ella** llevan tilde en la última sílaba (hablé, habló, comí, comió). Los irregulares no llevan tilde (hice, hizo, fue, vino). Y recuerda: **fue** y **fui** nunca llevan tilde.",
  },
  listening: {
    title: "Pódcast «Voces del Cibao»: cuando éramos niños",
    context: "«Voces del Cibao» es un pódcast que se graba en Santiago de los Caballeros. Esta semana, la presentadora, Yaritza, habla con dos invitados sobre la infancia: Ramón, un santiaguero que vive en Nueva York, y Lupe, una mexicana que vive en Santiago desde hace diez años. Escucha el episodio completo.",
    speakers: [
      { id: "yari", name: "Yaritza", voice: "es-CU-f", role: "presentadora dominicana" },
      { id: "ramon", name: "Ramón", voice: "es-US-m", role: "santiaguero que vive en Nueva York" },
      { id: "lupe", name: "Lupe", voice: "es-MX-f", role: "mexicana, profesora de música en Santiago" },
    ],
    script: [
      { speaker: "yari", text: "¡Buenas, buenas! Bienvenidos a «Voces del Cibao». Hoy hablamos de la infancia. Ramón, tú creciste aquí en Santiago, ¿verdad? ¿Cómo era tu barrio?" },
      { speaker: "ramon", text: "Sí, yo me crié en Los Pepines. Era un barrio con mucha vida: las casas eran de colores, los vecinos se sentaban en la acera por la tarde y todo el mundo se conocía." },
      { speaker: "yari", text: "¿Y qué hacían los niños después de la escuela?" },
      { speaker: "ramon", text: "Jugábamos pelota en la calle hasta que oscurecía. Mi mamá salía al balcón y gritaba mi nombre para la cena. Eso pasaba todos los días." },
      { speaker: "yari", text: "Lupe, tú eres de Puebla. ¿Tu infancia era parecida?" },
      { speaker: "lupe", text: "En parte, sí. Yo también solía jugar en la calle, pero los domingos íbamos siempre al mercado con mi abuela. Ella compraba chiles y yo cargaba las bolsas." },
      { speaker: "yari", text: "¿Y hay algún día especial que recuerdes?" },
      { speaker: "lupe", text: "Sí, uno. Cuando tenía nueve años, mi abuela me regaló una guitarra. Esa noche no dormí: toqué hasta las dos de la mañana. Por eso hoy soy profesora de música." },
      { speaker: "ramon", text: "¡Qué bonito! Yo también tengo un día así. En 1998 pasó el huracán Georges y estuvimos tres días sin luz. Mi papá sacó la radio y escuchamos las noticias con todos los vecinos." },
      { speaker: "yari", text: "¡Qué susto! ¿Y ahora? ¿Ha cambiado mucho el barrio?" },
      { speaker: "ramon", text: "Mucho. Este año he vuelto dos veces y ya no hay niños en la calle. Ahora juegan con el celular." },
      { speaker: "lupe", text: "Pues yo todavía no he visitado Los Pepines. ¡Me tienes que llevar, Ramón!" },
      { speaker: "yari", text: "Ahí lo tienen. Antes jugábamos en la calle; ahora jugamos con una pantalla. ¡Hasta la próxima semana!" },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: no te preocupes por los detalles. ¿De qué hablan y en qué tono?",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha todo una vez y responde.",
          items: [
            { q: "¿Cuál es el tema principal del episodio?", options: ["La infancia de los invitados", "Los viajes a Nueva York", "La música mexicana"], answer: 0, why: "Yaritza lo dice al principio: _Hoy hablamos de la infancia_." },
            { q: "¿Qué conclusión saca Yaritza al final?", options: ["Los niños de antes jugaban más en la calle.", "Los niños de ahora son más felices.", "Los barrios no han cambiado nada."], answer: 0, why: "_Antes jugábamos en la calle; ahora jugamos con una pantalla._" },
            { q: "¿Cuántas personas hablan?", options: ["dos", "tres", "cuatro"], answer: 1, why: "Yaritza (la presentadora), Ramón y Lupe." },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: separa lo que era habitual de lo que pasó una sola vez. Esta es la habilidad clave del episodio.",
        exercise: {
          id: "l2",
          type: "classify",
          prompt: "¿Era un hábito o pasó una sola vez?",
          categories: ["hábito (pasaba siempre)", "pasó una vez"],
          items: [
            { text: "Los vecinos se sentaban en la acera por la tarde.", cat: 0, why: "Ramón describe el barrio: _se sentaban_, imperfecto." },
            { text: "La mamá de Ramón lo llamaba desde el balcón para cenar.", cat: 0, why: "Él dice: _Eso pasaba todos los días_." },
            { text: "Lupe iba al mercado con su abuela.", cat: 0, why: "_Los domingos íbamos siempre al mercado_." },
            { text: "La abuela de Lupe le regaló una guitarra.", cat: 1, why: "_Cuando tenía nueve años, mi abuela me regaló…_: un hecho, indefinido." },
            { text: "Lupe tocó la guitarra hasta las dos de la mañana.", cat: 1, why: "_Esa noche… toqué hasta las dos_: una noche concreta." },
            { text: "La familia de Ramón escuchó las noticias con los vecinos.", cat: 1, why: "Pasó durante el huracán Georges, en 1998." },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en cómo dicen las cosas.",
        exercise: {
          id: "l3",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "Ramón dice «este año he vuelto dos veces». ¿Por qué usa el perfecto?", options: ["Porque _este año_ todavía no ha terminado.", "Porque es un hábito de la infancia.", "Porque da una fecha exacta."], answer: 0, why: "_Este año_ es un tiempo abierto: perfecto." },
            { q: "¿Qué frase usa Lupe para un hábito?", options: ["Yo también solía jugar en la calle.", "Esa noche no dormí.", "Todavía no he visitado Los Pepines."], answer: 0, why: "**Solía + infinitivo** expresa un hábito pasado." },
            { q: "¿Qué dice Lupe sobre Los Pepines?", options: ["Que todavía no lo ha visitado.", "Que lo visitó en 1998.", "Que iba allí de niña."], answer: 0, why: "_Todavía no he visitado Los Pepines_: no ha pasado, pero quiere hacerlo." },
            { q: "Yaritza dice «¡Buenas, buenas!». Si oyes la s muy suave o no la oyes, ¿qué pasa?", options: ["Es la s aspirada del Caribe; el significado no cambia.", "Está hablando en singular.", "Está hablando en inglés."], answer: 0, why: "La s final aspirada es normal en el español caribeño; el contexto da el significado." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Volver a Santiago después de quince años",
    genre: "Entrada de blog personal",
    frame: "Blog «Raíces», escrito por Wendy Almonte, una dominicana que vive en Madrid. La entrada se publicó un domingo por la noche.",
    text: [
      "Esta semana he vuelto a Santiago de los Caballeros después de quince años. He paseado por la calle del Sol, he comido chicharrón en un colmado del barrio y he subido otra vez al Monumento. Todavía no he ido al Centro León, pero voy el martes con mi prima.",
      "Nací aquí en 1990. Mi familia vivía en una casa pequeña cerca del Parque Central. Mi padre tenía una tienda de tabaco y mi madre era maestra. Los domingos solíamos comer en casa de mi abuela, que siempre preparaba un sancocho enorme para quince personas. Los niños jugábamos en el patio mientras los mayores hablaban de política.",
      "En 2008 terminé el bachillerato y al año siguiente me mudé a Madrid para estudiar. Fue una decisión difícil. Los primeros meses fueron durísimos: no conocía a nadie, hacía frío y echaba de menos la comida. Pero en 2014 terminé la carrera, encontré trabajo y me quedé.",
      "Antes pensaba que Santiago no cambiaba nunca. Ahora veo que hay más tráfico, más edificios y más cafés modernos. Pero la gente sigue igual: el lunes, en la guagua, una señora me contó toda su vida en diez minutos. Eso solo pasa aquí.",
    ],
    glossary: [
      { es: "el chicharrón", en: "fried pork crackling" },
      { es: "el colmado (República Dominicana)", en: "small neighbourhood grocery shop" },
      { es: "el bachillerato", en: "secondary school (high school diploma)" },
      { es: "echar de menos / extrañar (América)", en: "to miss" },
      { es: "seguir igual", en: "to stay the same" },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee el blog y responde.",
        items: [
          { q: "¿Por qué escribe Wendy esta entrada?", options: ["Porque ha vuelto de visita a su ciudad natal.", "Porque se ha mudado a Santiago para siempre.", "Porque quiere vender la casa de su familia."], answer: 0, why: "_Esta semana he vuelto a Santiago después de quince años_ y vive en Madrid." },
          { q: "¿Qué no ha hecho todavía?", options: ["Ir al Centro León.", "Subir al Monumento.", "Comer chicharrón."], answer: 0, why: "_Todavía no he ido al Centro León, pero voy el martes._" },
          { q: "¿Qué hacía la familia los domingos?", options: ["Comía en casa de la abuela.", "Iba a la tienda de tabaco.", "Viajaba a Madrid."], answer: 0, why: "_Los domingos solíamos comer en casa de mi abuela_." },
          { q: "«Fue una decisión difícil». ¿Qué verbo es _fue_ aquí?", options: ["ser", "ir"], answer: 0, why: "Valora la decisión (no hay destino): es **ser**." },
        ],
      },
      {
        id: "r2",
        type: "classify",
        title: "¿Cuándo pasa?",
        prompt: "Clasifica cada información del texto según su lugar en la vida de Wendy.",
        categories: ["infancia en Santiago (hábitos y descripciones)", "hitos con fecha", "esta semana"],
        items: [
          { text: "Su madre era maestra.", cat: 0, why: "Descripción de su familia en la infancia: _era_." },
          { text: "Se mudó a Madrid para estudiar.", cat: 1, why: "_Al año siguiente_ (2009): hito, indefinido." },
          { text: "Ha paseado por la calle del Sol.", cat: 2, why: "_He paseado_: forma parte de _esta semana_." },
          { text: "Los niños jugaban en el patio.", cat: 0, why: "Hábito de los domingos: _jugábamos_." },
          { text: "Terminó la carrera.", cat: 1, why: "_En 2014 terminé la carrera_." },
          { text: "Ha comido chicharrón.", cat: 2, why: "_He comido_: experiencia de esta semana." },
        ],
      },
      {
        id: "r3",
        type: "gap",
        title: "Datos exactos",
        prompt: "Completa con información del texto (una palabra o un número).",
        items: [
          { q: "Wendy nació en el año ___.", answers: [["1990", "mil novecientos noventa"]], why: "_Nací aquí en 1990_." },
          { q: "Su padre tenía una tienda de ___.", answers: [["tabaco"]], why: "_Mi padre tenía una tienda de tabaco_." },
          { q: "Wendy no ha visitado Santiago durante ___ años.", answers: [["quince", "15"]], why: "_He vuelto… después de quince años_." },
        ],
      },
    ],
    noticing: {
      prompt: "Wendy usa los tres pasados en el mismo texto. Toca cada frase para ver por qué.",
      items: [
        { quote: "Esta semana he vuelto a Santiago", note: "Perfecto con _esta semana_ y participio irregular **vuelto**. Wendy vive en Madrid: usa el perfecto como en España." },
        { quote: "Mi familia vivía en una casa pequeña", note: "Imperfecto: describe la situación de su infancia, el escenario." },
        { quote: "En 2008 terminé el bachillerato y al año siguiente me mudé", note: "Indefinido: hitos con fecha, uno detrás de otro, como en una biografía." },
        { quote: "no conocía a nadie, hacía frío y echaba de menos la comida", note: "Imperfecto para describir cómo era esa época difícil, aunque el periodo ya terminó." },
        { quote: "Antes pensaba que Santiago no cambiaba nunca. Ahora veo…", note: "**Antes** + imperfecto frente a **ahora** + presente: así se compara antes y ahora." },
      ],
    },
  },
  practice: {
    intro: "Ahora todo junto, con mecánicas distintas. Si fallas, lee el _por qué_: te dice qué pregunta debías hacerte.",
    exercises: [
      {
        id: "x1",
        type: "error",
        title: "Detective de errores",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "El año pasado he trabajado en un hotel de Puerto Plata.", answers: ["El año pasado trabajé en un hotel de Puerto Plata."], why: "_El año pasado_ ya terminó: **indefinido**, en España y en América." },
          { sentence: "Mi hermana nunca ha escribido una carta a mano.", answers: ["Mi hermana nunca ha escrito una carta a mano.", "Mi hermana no ha escrito nunca una carta a mano."], why: "Participio irregular de _escribir_: **escrito**." },
          { sentence: "Cuando tenía ocho años, mi familia vivió en un apartamento muy pequeño.", answers: ["Cuando tenía ocho años, mi familia vivía en un apartamento muy pequeño."], why: "Describe la situación de una época: **imperfecto** (_vivía_)." },
          { sentence: "Ayer Joel no vino porque tuvo que trabajar y su jefe no le dijo nada antes; yo lo supé por la tarde.", answers: ["Ayer Joel no vino porque tuvo que trabajar y su jefe no le dijo nada antes; yo lo supe por la tarde."], why: "Indefinido irregular sin tilde: **supe** (como _pude_, _tuve_)." },
          { sentence: "¿Tu ya has hablado con el profesor?", answers: ["¿Tú ya has hablado con el profesor?", "¿Ya has hablado tú con el profesor?"], why: "Es el pronombre sujeto: **tú**, con tilde diacrítica." },
        ],
      },
      {
        id: "x2",
        type: "context",
        title: "¿Qué respondes?",
        prompt: "Lee la situación y elige la respuesta más natural.",
        items: [
          { context: "Un compañero nuevo te pregunta: «¿Has estado alguna vez en el Caribe?». Fuiste a Cuba en 2019.", q: "Respondes:", options: ["Sí, estuve en Cuba en 2019.", "Sí, estaba en Cuba en 2019.", "Sí, he estado en Cuba en 2019."], answer: 0, why: "Al dar la fecha, pasas al **indefinido**. _Estaba_ describiría una situación, no un hecho." },
          { context: "Tu amiga te cuenta: «¡Mi abuelo se ha jubilado hoy después de cuarenta años!».", q: "Reaccionas:", options: ["¡Qué bien! ¿Y qué va a hacer ahora?", "¡Qué pena! ¿Y cuándo nació?", "Sí, yo también me jubilaba."], answer: 0, why: "Reaccionas con interés y preguntas por el futuro. _Me jubilaba_ sería un hábito, no tiene sentido." },
          { context: "Te preguntan: «¿Ya has terminado el informe?». No lo has terminado, pero lo terminas mañana.", q: "Respondes:", options: ["Todavía no, lo termino mañana.", "Ya no, lo termino mañana.", "Nunca, lo termino mañana."], answer: 0, why: "**Todavía no**: no ha pasado, pero va a pasar." },
          { context: "Un niño te pregunta cómo era tu escuela.", q: "Respondes:", options: ["Era pequeña y tenía un patio con árboles.", "Fue pequeña y tuvo un patio con árboles.", "Ha sido pequeña y ha tenido un patio."], answer: 0, why: "Describes un lugar del pasado: **imperfecto**." },
        ],
      },
      {
        id: "x3",
        type: "order",
        title: "Construye la frase",
        prompt: "Ordena las palabras.",
        items: [
          { words: ["Todavía", "no", "lo", "he", "visto."], alt: ["No lo he visto todavía."], en: "I haven't seen it yet.", why: "_Todavía no_ y el pronombre van delante de _he_; _he_ + participio no se separan." },
          { words: ["De", "niña", "solía", "pasar", "el", "verano", "en", "Jarabacoa."], alt: ["Solía pasar el verano en Jarabacoa de niña."], en: "As a girl I used to spend the summer in Jarabacoa.", why: "**Solía** + infinitivo, sin preposición." },
          { words: ["¿Adónde", "fuiste", "el", "fin", "de", "semana", "pasado?"], alt: ["¿Adónde fuiste el pasado fin de semana?"], en: "Where did you go last weekend?", why: "_Adónde_ + **fuiste** (ir): pregunta por el destino." },
        ],
      },
      {
        id: "x4",
        type: "gap",
        title: "Un mensaje de voz",
        prompt: "Daniel, un colombiano, le cuenta su fin de semana en Santiago a su hermana. Completa con el pasado adecuado.",
        items: [
          { q: "¡Hola, Caro! Por fin ___ (llegar, yo) a Santiago el viernes por la noche.", answers: [["llegué"]], why: "_El viernes por la noche_: momento terminado, indefinido (yo: lleg**ué**, con u)." },
          { q: "El sábado ___ (hacer) un calor terrible, pero ___ (ir, nosotros) al Monumento igual.", answers: [["hizo"], ["fuimos"]], why: "Un día concreto: indefinido. **Hizo** (hacer) y **fuimos** (ir)." },
          { q: "La ciudad no es como me la imaginaba: yo ___ (pensar) que era más pequeña.", answers: [["pensaba"]], why: "Una idea que tenías antes, como situación: imperfecto." },
          { q: "Este fin de semana ___ (aprender, yo) a bailar merengue. ¡Te lo enseño en Bogotá!", answers: [["he aprendido", "aprendí"]], why: "_Este fin de semana_ todavía cuenta como tiempo abierto: perfecto; en Colombia muchos usarían el indefinido." },
        ],
      },
      {
        id: "x5",
        type: "open",
        title: "Escritura guiada",
        prompt: "Escribe respuestas breves (2–3 frases) usando el tiempo adecuado.",
        items: [
          {
            prompt: "Un amigo te escribe: «¿Has hecho algo interesante esta semana?». Respóndele con dos cosas que has hecho y una que todavía no has hecho.",
            model: "¡Sí! Esta semana he ido a un concierto de jazz y he probado un restaurante peruano nuevo. Todavía no he terminado la serie que me recomendaste, ¡no tengo tiempo!",
            checklist: ["Uso el perfecto (he + participio) para esta semana.", "Incluyo **todavía no**.", "Si uso hecho, visto, vuelto…, el participio es correcto."],
          },
          {
            prompt: "Escribe tres frases sobre la vida de una persona mayor de tu familia: dónde nació, un hito y cómo era su vida de joven.",
            model: "Mi abuelo nació en Oporto en 1946. En 1970 emigró a Francia y trabajó en una fábrica de coches. De joven era muy deportista y jugaba al fútbol todos los domingos.",
            checklist: ["Uso el indefinido para los hitos con fecha.", "Uso el imperfecto para describir o contar hábitos.", "Escribo bien los irregulares (fue, tuvo, hizo, vino…)."],
          },
          {
            prompt: "Compara un hábito de tu infancia con tu vida de ahora. Usa **antes** / **solía** y **ahora**.",
            model: "Antes solía levantarme a las siete para ir al colegio en bicicleta. Ahora me levanto a las ocho y voy a la oficina en metro.",
            checklist: ["Uso **solía** + infinitivo o el imperfecto para el pasado.", "Uso el presente para ahora.", "Uso **antes** y **ahora** para marcar el contraste."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe un texto para el foro del curso: «Mi pasado en tres tiempos».",
    context: "En el foro, cada estudiante se presenta a través de su pasado. El texto debe tener tres párrafos cortos: una experiencia, un momento importante de tu vida y tu infancia.",
    steps: [
      "Párrafo 1: dos experiencias que has tenido (o no) en tu vida o esta semana, con **alguna vez, nunca, ya, todavía no**.",
      "Párrafo 2: un momento importante con fecha (un viaje, una mudanza, un trabajo nuevo): qué pasó, en orden.",
      "Párrafo 3: cómo era tu vida de niño o niña y qué solías hacer.",
      "Termina con una frase que compare antes y ahora.",
      "Relee: ¿cada verbo responde a la pregunta correcta (experiencia, hecho, escena)?",
    ],
    useLanguage: ["Nunca he… / Todavía no he… / Ya he…", "En 2015…, hace … años…, el año pasado…", "fui, estuve, tuve, hice, vine", "De niño/a vivía…, era…, solía…", "Antes… ; ahora…"],
    model: [
      "Me llamo Kate y soy de Toronto. He viajado bastante, pero nunca he estado en el Caribe. Esta semana he visto muchas fotos de Santiago y ya he buscado vuelos.",
      "Hace cuatro años hice un viaje muy importante: fui a Oaxaca con una amiga y estuve allí dos meses. Allí empecé a estudiar español y decidí cambiar de trabajo.",
      "De niña vivía en un pueblo pequeño cerca de un lago. En invierno hacía mucho frío y solía patinar con mis hermanos después de la escuela. Antes era muy tímida; ahora hablo con todo el mundo, ¡también en español!",
    ],
    checklist: [
      "Uso el perfecto para experiencias y para _esta semana_ / _hoy_.",
      "Uso el indefinido para el momento con fecha, y los irregulares son correctos.",
      "Uso el imperfecto o **solía** para la infancia.",
      "Los participios irregulares son correctos (visto, hecho, escrito…).",
      "Las tildes de _tú, él, sí_ y de los indefinidos regulares están bien.",
      "Hay una comparación antes / ahora al final.",
    ],
    words: [100, 150],
  },
  speaking: {
    intro: "Tres minirrelatos, uno por cada pasado y uno que los mezcla. Grábate, escúchate y repite hasta hablar sin leer.",
    tasks: [
      {
        title: "Dos verdades y una mentira",
        prompt: "Cuenta tres experiencias: dos verdaderas y una inventada. Para una de ellas, añade cuándo fue y qué pasó. Después, pon la grabación en clase y que adivinen la mentira.",
        prep: ["Nunca he… / He… dos veces", "Una con fecha: Fue en 2018…", "Usa al menos un participio irregular: visto, hecho, escrito, roto"],
        seconds: 60,
        model: "He comido insectos en México. Nunca he visto la nieve. Y he roto un plato en un restaurante elegante: fue en 2019, en Madrid, y el camarero se rio mucho. ¿Cuál es la mentira?",
        selfCheck: ["Uno _he_ y el participio sin pausa.", "Paso al indefinido cuando doy la fecha.", "Uso al menos un participio irregular."],
      },
      {
        title: "Un día que no olvidas",
        prompt: "Cuenta un día concreto de tu vida (un viaje, un cumpleaños, el primer día de trabajo). Di cuándo fue y cuenta cuatro o cinco acciones en orden.",
        prep: ["Cuándo: hace … años, en …", "Primero…, después…, luego…, al final…", "Irregulares: fui, tuve, hice, vino, dijo"],
        seconds: 60,
        model: "Hace tres años fue mi primer día en un trabajo nuevo. Llegué muy temprano, pero la oficina estaba cerrada. Esperé media hora en un café. Después vino mi jefa, me dio las llaves y me dijo: «Bienvenida». Al final fue un día muy bueno.",
        selfCheck: ["Pronuncio bien la tilde final: lle**gué**, espe**ré**, lle**gó**.", "No pongo tilde en los irregulares (vino, dijo).", "Las acciones van en orden."],
      },
      {
        title: "Antes y ahora",
        prompt: "Describe tu infancia en tres frases (dónde vivías, cómo era, qué solías hacer) y compárala con tu vida de ahora en dos frases.",
        prep: ["De niño/a vivía… La casa era…", "Solía… / Todos los veranos…", "Antes… ; ahora…"],
        seconds: 45,
        model: "De niño vivía en un barrio de Lima. Mi casa era pequeña, pero tenía una terraza. Solía jugar al fútbol con mis primos todos los sábados. Ahora vivo solo en un apartamento y los sábados trabajo. Antes tenía mucho tiempo libre; ahora no tengo nada.",
        selfCheck: ["Uso el imperfecto para describir y para los hábitos.", "Uso el presente para ahora.", "Las vocales del imperfecto (-aba, -ía) son claras."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo, demuestra que ya manejas los tres pasados. Lleva tus tres grabaciones preparadas.",
    cards: [
      { move: "Cuenta", task: "Pon tu «dos verdades y una mentira» y deja que tu profesor o profesora haga preguntas antes de adivinar.", phrases: ["¿Cuál crees que es la mentira?", "¡Has acertado!", "No, eso sí es verdad: fue en…"] },
      { move: "Pregunta", task: "Hazle a tu profesor o profesora tres preguntas sobre su pasado: una experiencia, un hecho con fecha y su infancia.", phrases: ["¿Has… alguna vez?", "¿Cuándo empezaste a…?", "¿Cómo era tu escuela?", "¿Qué solías hacer los domingos?"] },
      { move: "Compara", task: "Compara un hábito de tu infancia con uno de tu profesor o profesora: ¿qué teníais en común y qué era diferente?", phrases: ["Yo también solía…", "Pues yo no: yo…", "Antes los niños…; ahora…"] },
      { move: "Reacciona", task: "Cuando te cuente algo, reacciona con interés y haz una pregunta más.", phrases: ["¡No me digas!", "¡Qué bonito!", "¿Y qué pasó después?", "¿Y todavía lo haces?"] },
    ],
    bring: "Tu texto «Mi pasado en tres tiempos» y una foto de cuando eras niño o niña para describirla.",
  },
  quiz: {
    items: [
      { type: "choice", q: "—¿Conoces Puerto Plata? —Sí, ___ allí el verano pasado.", options: ["estuve", "he estado", "estaba"], answer: 0, why: "_El verano pasado_: momento terminado → **estuve**." },
      { type: "choice", q: "Mi bisabuela ___ muy alta y siempre llevaba sombrero.", options: ["era", "fue", "ha sido"], answer: 0, why: "Descripción física de una persona en el pasado: **era**." },
      { type: "choice", q: "«Fueron al Cibao en carro.» ¿Qué verbo es _fueron_?", options: ["ir", "ser"], answer: 0, why: "Hay un destino (_al Cibao_): es **ir**." },
      { type: "choice", q: "Antes del viaje a Santo Domingo, ¿qué frase sobre la maleta es correcta?", options: ["Todavía no he hecho la maleta.", "He todavía no hecho la maleta.", "Todavía no he hacido la maleta."], answer: 0, why: "_Todavía no_ va delante; participio irregular **hecho**." },
      { type: "listen", q: "¿Qué tiempo oyes?", audio: "Mi hermano trabajó en Santiago.", voice: "es-CU-m", options: ["pasado: trabajó", "presente: trabajo"], answer: 0, why: "La fuerza cae en la última sílaba: traba**jó**, pasado." },
      { type: "listen", q: "¿La persona habla de un hábito o de una vez?", audio: "Cuando era pequeña, mi abuela me contaba un cuento todas las noches.", voice: "es-CO-f", options: ["un hábito", "una sola vez"], answer: 0, why: "_Contaba… todas las noches_: imperfecto de hábito." },
      { type: "gap", q: "Mi tía ___ (casarse) en 1985 y ___ (tener) dos hijos.", answers: [["se casó"], ["tuvo"]], why: "Hitos de una biografía: indefinido; _tener_ es irregular: **tuvo**." },
      { type: "gap", q: "¿Alguna vez le ___ (decir, tú) una mentira a tu jefe?", answers: [["has dicho"]], why: "_Alguna vez_ → perfecto; participio de _decir_: **dicho**." },
      { type: "gap", q: "Antes ___ (soler, yo) ir al gimnasio, pero ahora no tengo tiempo.", answers: [["solía"]], why: "Hábito pasado: **solía** + infinitivo." },
      { type: "transform", source: "Los domingos comíamos en casa de mi abuela.", instruction: "Cuenta solo un domingo concreto: «El domingo pasado…»", answers: ["El domingo pasado comimos en casa de mi abuela."], why: "Un día concreto: imperfecto → indefinido, **comimos**." },
      { type: "transform", source: "Ayer vi a Marta en el parque.", instruction: "Cambia «ayer» por «esta tarde» (variante de España).", answers: ["Esta tarde he visto a Marta en el parque."], why: "_Esta tarde_ (tiempo abierto, uso de España): perfecto con participio irregular **visto**." },
      { type: "order", words: ["Nunca", "he", "vuelto", "a", "mi", "antigua", "escuela."], alt: ["No he vuelto nunca a mi antigua escuela."], en: "I've never gone back to my old school.", why: "_Nunca_ delante de _he_; participio de _volver_: **vuelto**." },
      { type: "error", sentence: "Mis abuelos se conocieron en una fiesta y se casaban un año después.", answers: ["Mis abuelos se conocieron en una fiesta y se casaron un año después."], why: "Un hito con momento concreto (_un año después_): indefinido, **se casaron**." },
      { type: "error", sentence: "Ayer los estudiantes trajieron comida para la fiesta.", answers: ["Ayer los estudiantes trajeron comida para la fiesta."], why: "Después de **j**, la terminación es **-eron**: traj**eron**." },
      { type: "error", sentence: "No se si él ha llegado ya.", answers: ["No sé si él ha llegado ya.", "No sé si ha llegado ya."], why: "Verbo _saber_: **sé**, con tilde diacrítica (no _se_)." },
      {
        type: "open",
        prompt: "Escribe cuatro frases sobre ti: una experiencia que nunca has tenido, algo que hiciste el año pasado, cómo era tu casa de niño/a y algo que solías hacer.",
        model: "Nunca he montado a caballo. El año pasado fui a Lisboa con mi pareja. De niña vivía en una casa con un jardín enorme. Solía leer cómics debajo de un árbol.",
        checklist: ["Perfecto con _nunca_.", "Indefinido con _el año pasado_.", "Imperfecto para describir la casa.", "Solía + infinitivo para el hábito."],
      },
    ],
  },
  complete: {
    canNow: [
      "Preguntar y hablar de experiencias con **alguna vez, nunca, ya, todavía no** y los participios irregulares.",
      "Contar un día concreto o una biografía con el indefinido, regular e irregular, y distinguir **fue** (ser) de **fue** (ir).",
      "Describir tu infancia y tus hábitos pasados con el imperfecto y **solía**.",
      "Comparar antes y ahora.",
      "Distinguir en un audio lo que era habitual de lo que pasó una sola vez, también con acento caribeño.",
    ],
    review: [
      "Marcador → tiempo: _ayer_ → hice; _nunca, esta semana_ → he hecho; _de niño, siempre_ → hacía.",
      "Participios: hecho, dicho, visto, escrito, puesto, vuelto, abierto, roto.",
      "Irregulares sin tilde: pude, tuve, hice, vino, dijo; y _dijeron, trajeron_ sin i.",
      "La tilde que cambia el tiempo: trabajo / trabajó.",
    ],
  },
  related: [
    { path: "/sistema-verbal/preterito-perfecto-compuesto-indicativo", label: "Sistema verbal · pretérito perfecto compuesto" },
    { path: "/sistema-verbal/preterito-perfecto-simple-indicativo", label: "Sistema verbal · pretérito indefinido" },
    { path: "/sistema-verbal/preterito-imperfecto-indicativo", label: "Sistema verbal · pretérito imperfecto" },
  ],
};
