import type { Module } from "../../types";

export const a2w07: Module = {
  id: "a2-07",
  level: "a2",
  week: 7,
  kind: "core",
  title: "¿Ciudad o pueblo?",
  subtitle: "Comparar lugares para vivir, elegir y justificar: más… que, tan… como, el mejor de…",
  stop: { place: "Ponce", country: "Puerto Rico" },
  minutes: 85,
  newObjectives: [
    "a2.gram.comparativos",
    "a2.gram.superlativos",
    "a2.voc.ciudades-campo",
    "a2.pron.foco-contraste",
    "a2.fun.comparar-elegir",
    "a2.read.articulo-ciudades",
  ],
  reviewObjectives: ["a2.gram.indefinido-imperfecto", "a2.fun.anecdota", "a2.gram.imperfecto"],
  prerequisites: ["a2-06"],
  goal: {
    canDo: "Al final de esta semana puedes comparar dos lugares para vivir —tamaño, precio, clima, ambiente—, decir cuál es el mejor para ti y justificar tu elección.",
    canDoEn: "By the end of this week, you can compare two places to live (size, cost, climate, atmosphere), say which one is best for you and explain why.",
    steps: [
      "Aprende a comparar con **más… que**, **menos… que**, **tan… como** y **tanto… como**.",
      "Aprende los superlativos (**el más… de**, **-ísimo**) y los irregulares **mejor, peor, mayor, menor**.",
      "Aprende el vocabulario de la ciudad, el campo y el clima.",
      "Entrena el acento de contraste: la palabra que corriges suena más fuerte.",
      "Escucha a una pareja que decide entre San Juan y Ponce y lee un artículo que compara las dos ciudades.",
      "Graba una comparación y una elección justificada para defenderla en clase.",
    ],
  },
  theory: {
    intro: "Comparar es una de las cosas que más hacemos al hablar: elegir piso, trabajo, ciudad o restaurante. En español hay tres tipos de comparación (más, menos, igual) y unas pocas formas irregulares que se usan muchísimo.",
    parts: [
      {
        heading: "Más… que, menos… que",
        body: [
          "Para decir que algo tiene una cualidad en mayor o menor grado, usa **más / menos + adjetivo + que**: **San Juan es más grande que Ponce.** **El campo es menos ruidoso que la ciudad.** El adjetivo concuerda con lo primero que comparas: **La vida en Ponce es más tranquila.**",
          "La misma estructura funciona con nombres y adverbios: **En San Juan hay más tráfico que en Ponce.** **En el campo la gente se levanta más temprano que en la ciudad.** Con un verbo, la comparación va detrás: **En Ponce llueve menos que en San Juan.** **Trabajo más que antes.**",
          "Con números y cantidades se usa **más de / menos de**, no _que_: **Tardamos más de una hora.** **El piso cuesta menos de 900 dólares.**",
          "No hace falta repetir lo que ya está claro: **Mi barrio es más tranquilo que el tuyo** (que tu barrio). Y el segundo término se puede omitir si se entiende: **Ponce es más barato** (que San Juan).",
        ],
        support: [
          "_más… que_ = more… than; _menos… que_ = less… than. The adjective agrees with the noun: _la ciudad es más cara_, _los pueblos son más baratos_.",
          "Before a number, use _de_: _más de cien personas_ (more than a hundred people). _Más que cien_ is a mistake.",
        ],
        table: {
          caption: "Comparar con más y menos",
          head: ["Comparas…", "Estructura", "Ejemplo"],
          rows: [
            ["una cualidad (adjetivo)", "más / menos + adjetivo + que", "El norte es más húmedo que el sur."],
            ["una cantidad (nombre)", "más / menos + nombre + que", "Hay menos playas que en la capital."],
            ["una manera (adverbio)", "más / menos + adverbio + que", "Aquí se vive más despacio que allí."],
            ["una acción (verbo)", "verbo + más / menos + que", "En Ponce llueve menos que en San Juan."],
            ["un número", "más / menos + de + número", "Viven más de cien mil personas."],
          ],
        },
        examples: [
          { es: "El alquiler en San Juan es más caro que en Ponce.", en: "Rent in San Juan is more expensive than in Ponce." },
          { es: "En mi pueblo hay menos tiendas, pero más naturaleza.", en: "In my town there are fewer shops but more nature." },
          { es: "Mi hermana gana más que yo.", en: "My sister earns more than me.", note: "Después de _que_ va **yo**, **tú** (no _mí_, _ti_)." },
        ],
        mistakes: [
          { wrong: "Madrid es más grande de Sevilla.", right: "Madrid es más grande que Sevilla.", why: "Para comparar dos cosas se usa **que**; _de_ solo va delante de números." },
          { wrong: "Hay más que treinta playas.", right: "Hay más de treinta playas.", why: "Delante de un número: **más de**." },
          { wrong: "Ella es más alta que mí.", right: "Ella es más alta que yo.", why: "Después de _que_ se usan los pronombres sujeto: **yo, tú**." },
        ],
        tip: "Si dudas entre _que_ y _de_, mira lo que viene después: ¿un número? → _de_. ¿Otra persona, otro lugar? → _que_.",
      },
      {
        heading: "Igual: tan… como, tanto… como",
        body: [
          "Para decir que dos cosas son iguales en una cualidad, usa **tan + adjetivo o adverbio + como**: **La playa de Ponce no es tan bonita como la del Condado.** _Tan_ nunca cambia.",
          "Con nombres, usa **tanto / tanta / tantos / tantas + nombre + como**. Aquí sí hay concordancia, porque _tanto_ funciona como un adjetivo de cantidad: **No hay tanto tráfico como en la capital.** **No hay tanta gente.** **No hay tantos turistas.** **No tiene tantas tiendas.**",
          "Con verbos, **tanto como** va detrás del verbo y no cambia: **En el campo no llueve tanto como en la montaña.**",
          "En la conversación es muy frecuente usar la igualdad en negativo para suavizar: **No es tan caro como dicen** suena más amable que _Es más barato_.",
        ],
        support: [
          "_tan_ + adjective/adverb + _como_ = as… as (never changes). _tanto/a/os/as_ + noun + _como_ = as much / as many… as (agrees with the noun). Verb + _tanto como_ = as much as (never changes).",
        ],
        table: {
          caption: "Las formas de la igualdad",
          head: ["Con…", "Forma", "Ejemplo"],
          rows: [
            ["adjetivo / adverbio", "tan… como", "Ponce es tan bonita como San Juan."],
            ["nombre masculino singular", "tanto… como", "No hay tanto ruido como aquí."],
            ["nombre femenino singular", "tanta… como", "No hay tanta humedad como en el norte."],
            ["nombre masculino plural", "tantos… como", "Hay tantos parques como en mi ciudad."],
            ["nombre femenino plural", "tantas… como", "No hay tantas opciones como en la capital."],
            ["verbo", "verbo + tanto como", "Aquí no salgo tanto como antes."],
          ],
        },
        examples: [
          { es: "Mi barrio no es tan seguro como el tuyo.", en: "My neighbourhood isn't as safe as yours." },
          { es: "En Ponce no hay tantos tapones como en San Juan.", en: "In Ponce there aren't as many traffic jams as in San Juan." },
          { es: "Ahora no trabajo tanto como antes.", en: "Now I don't work as much as before." },
        ],
        mistakes: [
          { wrong: "Ponce es tan grande que San Juan.", right: "Ponce no es tan grande como San Juan.", why: "La igualdad se construye con **tan… como**, nunca con _que_." },
          { wrong: "No hay tanto gente como el sábado.", right: "No hay tanta gente como el sábado.", why: "_Gente_ es femenino singular: **tanta** gente." },
          { wrong: "No es tanto caro como pensaba.", right: "No es tan caro como pensaba.", why: "Delante de un adjetivo se usa **tan**; _tanto_ va con nombres o detrás de verbos." },
        ],
      },
      {
        heading: "El mejor, el más… de, -ísimo",
        body: [
          "El **superlativo** destaca un elemento dentro de un grupo: **el / la / los / las + (nombre) + más / menos + adjetivo + de + grupo**. **Es la plaza más bonita de la ciudad.** **Es el barrio menos caro de la zona.** El grupo va con **de**, no con _en_.",
          "Cuatro adjetivos tienen formas especiales muy frecuentes: **bueno → mejor**, **malo → peor**, y para la edad, **mayor** (más viejo) y **menor** (más joven). **Este café es mejor que el otro.** **Es el peor día del año.** **Mi hermana mayor vive en Ponce.** Para el tamaño, lo normal es **más grande / más pequeño**.",
          "**Bien** y **mal** (adverbios) también tienen comparativo **mejor** y **peor**: **Aquí se vive mejor.** **Hoy he dormido peor que ayer.**",
          "Para decir que algo es **muy** + adjetivo de forma intensa, añade **-ísimo/a/os/as**: **caro → carísimo**, **tranquilo → tranquilísimo**, **fácil → facilísimo**. Fíjate en la ortografía: **rico → riquísimo**, **largo → larguísimo**, **feliz → felicísimo**. No se combina con _muy_.",
        ],
        support: [
          "Superlative: _el/la más… de_ = the most… in. Spanish uses _de_ for the group: _la ciudad más grande **de** la isla_ (in the island).",
          "Never say _más bueno_ or _más malo_ for quality: use _mejor_, _peor_. And never _más mejor_. _-ísimo_ = extremely; don't add _muy_.",
        ],
        table: {
          caption: "Irregulares y -ísimo",
          head: ["Base", "Comparativo", "Superlativo", "-ísimo"],
          rows: [
            ["bueno / bien", "mejor", "el / la mejor", "buenísimo"],
            ["malo / mal", "peor", "el / la peor", "malísimo"],
            ["viejo (edad)", "mayor", "el / la mayor", "—"],
            ["joven (edad)", "menor", "el / la menor", "—"],
            ["caro", "más caro", "el / la más caro/a", "carísimo"],
            ["rico", "más rico", "el / la más rico/a", "riquísimo"],
          ],
        },
        examples: [
          { es: "El Parque de Bombas es el edificio más fotografiado de Ponce.", en: "The Parque de Bombas is the most photographed building in Ponce." },
          { es: "Para mí, la mejor época para visitar la isla es la primavera.", en: "For me, the best time to visit the island is spring." },
          { es: "El mofongo de este sitio está riquísimo.", en: "The mofongo at this place is delicious." },
        ],
        mistakes: [
          { wrong: "Este restaurante es más mejor que el otro.", right: "Este restaurante es mejor que el otro.", why: "**Mejor** ya significa _más bueno_: no se añade _más_." },
          { wrong: "Es la ciudad más antigua en la isla.", right: "Es la ciudad más antigua de la isla.", why: "En el superlativo, el grupo va con **de**." },
          { wrong: "La comida estaba muy buenísima.", right: "La comida estaba buenísima.", why: "**-ísimo** ya es intensivo: no se usa con _muy_." },
        ],
        tip: "_Mayor_ y _menor_ se usan casi solo para la edad (_mi hermano mayor_). Para el tamaño, di _más grande_ y _más pequeño_: _Ponce es más pequeña que San Juan_ suena más natural que _menor_.",
      },
      {
        heading: "Comparar para elegir",
        body: [
          "Comparar casi siempre sirve para decidir. Para presentar dos opciones: **Por un lado…, por otro (lado)…**. Para contrastar: **En cambio…**, **pero**. Para hablar de pros y contras: **La ventaja es que…**, **El inconveniente / El problema es que…**.",
          "Para elegir: **Prefiero…**, **Me quedo con…**, **Para mí, lo mejor es…**, **Yo elijo… porque…**. La regla de oro: después de elegir, da al menos una razón con **porque**.",
          "Para comparar dos opciones con _preferir_, la forma recomendada es **preferir A a B**: **Prefiero el campo a la ciudad.** En la conversación también oirás _prefiero el campo que la ciudad_, pero en un texto escrito usa **a**.",
          "Muchas veces comparamos con el pasado o con nuestra experiencia: **Antes vivía en San Juan y tardaba una hora en llegar al trabajo; ahora vivo en Ponce y tardo diez minutos.** El imperfecto describe cómo era la situación antes.",
        ],
        support: [
          "_Por un lado… por otro…_ = on the one hand… on the other. _Me quedo con…_ = I'll go for… (I choose). _Prefiero A a B_ = I prefer A to B.",
          "When you compare with your past life, use the imperfect for how things used to be: _Antes vivía… y tardaba…_",
        ],
        examples: [
          { es: "Por un lado, San Juan tiene más vida; por otro, Ponce es más barata.", en: "On the one hand, San Juan is livelier; on the other, Ponce is cheaper." },
          { es: "La ventaja del pueblo es que hay menos ruido. El inconveniente es que necesitas carro.", en: "The advantage of the town is that there's less noise. The drawback is that you need a car." },
          { es: "Me quedo con el apartamento pequeño porque está más cerca del trabajo.", en: "I'll go for the small flat because it's closer to work." },
        ],
        mistakes: [
          { wrong: "Prefiero vivir en el campo. Me gusta.", right: "Prefiero vivir en el campo porque hay más naturaleza y menos estrés.", why: "Una elección sin razón suena incompleta: justifica con **porque** + una comparación." },
          { wrong: "Por una parte es barato, por otro lado es lejos.", right: "Por una parte es barato; por otra, está lejos.", why: "Combina **por una parte… por otra** (o _por un lado… por otro_). Y la ubicación va con **estar**: _está lejos_." },
        ],
      },
    ],
  },
  grammar: {
    intro: "Practica primero cada estructura y después las mezclas.",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "Que, como o de",
        prompt: "Elige la palabra que completa la comparación.",
        items: [
          { q: "El viaje en carro de San Juan a Ponce dura más ___ una hora.", options: ["de", "que", "como"], answer: 0, why: "Delante de una cantidad (_una hora_): **más de**." },
          { q: "En verano, Ponce es más calurosa ___ San Juan.", options: ["que", "de", "como"], answer: 0, why: "Comparas dos ciudades: **más… que**." },
          { q: "Mi apartamento nuevo no es tan grande ___ el anterior.", options: ["como", "que", "de"], answer: 0, why: "Igualdad: **tan… como**." },
          { q: "Es el museo más importante ___ la ciudad.", options: ["de", "en", "que"], answer: 0, why: "Superlativo: el grupo va con **de**." },
          { q: "Hoy hay menos gente ___ ayer en la plaza.", options: ["que", "de", "como"], answer: 0, why: "Comparas dos días: **menos… que**." },
        ],
      },
      {
        id: "g2",
        type: "gap",
        title: "Tan, tanto, tanta, tantos, tantas",
        prompt: "Completa con la forma correcta de la igualdad.",
        items: [
          { q: "En mi pueblo no hay ___ restaurantes como en la capital.", answers: [["tantos"]], why: "_Restaurantes_ es masculino plural: **tantos**." },
          { q: "La ciudad no es ___ peligrosa como dicen las noticias.", answers: [["tan"]], why: "Delante de un adjetivo: **tan** (no cambia)." },
          { q: "En febrero no hace ___ calor como en agosto.", answers: [["tanto"]], why: "_Calor_ es masculino singular: **tanto**." },
          { q: "Aquí no hay ___ humedad como en la costa norte.", answers: [["tanta"]], why: "_Humedad_ es femenino singular: **tanta**." },
          { q: "Los fines de semana no salgo ___ como antes.", answers: [["tanto"]], why: "Detrás de un verbo: **tanto como** (no cambia)." },
          { q: "Mi calle no tiene ___ tiendas como la tuya, pero es ___ tranquila como un pueblo.", answers: [["tantas"], ["tan"]], why: "_Tiendas_ (femenino plural) → **tantas**; delante del adjetivo → **tan**." },
        ],
      },
      {
        id: "g3",
        type: "match",
        title: "Formas especiales",
        prompt: "Une cada expresión con su forma especial o intensiva.",
        pairs: [
          { left: "más bueno", right: "mejor" },
          { left: "más malo", right: "peor" },
          { left: "más viejo (una persona)", right: "mayor" },
          { left: "más joven", right: "menor" },
          { left: "muy rico", right: "riquísimo" },
          { left: "muy largo", right: "larguísimo" },
        ],
        why: "_Mejor_ y _peor_ sustituyen a _más bueno / más malo_; _mayor_ y _menor_ hablan de edad. En _-ísimo_, la ortografía conserva el sonido: c → **qu** (riquísimo), g → **gu** (larguísimo).",
      },
      {
        id: "g4",
        type: "classify",
        title: "¿Qué tipo de comparación?",
        prompt: "Clasifica cada frase.",
        categories: ["superioridad (más)", "inferioridad (menos)", "igualdad (tan / tanto)", "superlativo (el más / -ísimo)"],
        items: [
          { text: "Ponce es más calurosa que Mayagüez.", cat: 0 },
          { text: "El tren es menos cómodo que el carro.", cat: 1 },
          { text: "Mi barrio es tan animado como el centro.", cat: 2 },
          { text: "Es la playa más limpia de la zona.", cat: 3 },
          { text: "Este café es mejor que el de la esquina.", cat: 0, why: "**Mejor** = más bueno: comparación de superioridad." },
          { text: "Aquí no llueve tanto como en El Yunque.", cat: 2, why: "Igualdad en forma negativa: _no… tanto como_." },
          { text: "El alquiler está carísimo.", cat: 3, why: "**-ísimo** expresa el grado máximo." },
          { text: "Ahora gano menos que antes.", cat: 1 },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Para comparar lugares necesitas nombres concretos (el tráfico, el alquiler) y adjetivos que se puedan comparar (ruidoso, tranquilo). Apréndelos en parejas de contrarios.",
    groups: [
      {
        title: "La vida en la ciudad",
        items: [
          { es: "el tráfico / los tapones (Puerto Rico)", en: "traffic / traffic jams" },
          { es: "el ruido", en: "noise" },
          { es: "la contaminación", en: "pollution" },
          { es: "el transporte público", en: "public transport" },
          { es: "la vida nocturna", en: "nightlife" },
          { es: "la oferta cultural: museos, teatros, conciertos", en: "cultural life: museums, theatres, concerts" },
          { es: "el alquiler / la renta (México, Puerto Rico)", en: "rent" },
          { es: "quedar cerca / lejos del trabajo", en: "to be close to / far from work" },
        ],
      },
      {
        title: "La vida en el pueblo o en el campo",
        items: [
          { es: "la naturaleza", en: "nature" },
          { es: "el aire puro", en: "clean air" },
          { es: "la tranquilidad", en: "peace and quiet" },
          { es: "Todos los vecinos se conocen.", en: "All the neighbours know each other." },
          { es: "Hay pocos servicios.", en: "There are few services (shops, hospitals…)." },
          { es: "Hace falta carro (América) / coche (España).", en: "You need a car." },
          { es: "la plaza del pueblo", en: "the town square" },
        ],
      },
      {
        title: "Adjetivos en parejas",
        items: [
          { es: "ruidoso ≠ tranquilo", en: "noisy ≠ quiet" },
          { es: "caro ≠ barato", en: "expensive ≠ cheap" },
          { es: "seguro ≠ peligroso", en: "safe ≠ dangerous" },
          { es: "animado ≠ aburrido", en: "lively ≠ boring" },
          { es: "limpio ≠ sucio", en: "clean ≠ dirty" },
          { es: "bien comunicado ≠ aislado", en: "well connected ≠ isolated" },
        ],
      },
      {
        title: "El clima",
        items: [
          { es: "caluroso ≠ fresco", en: "hot ≠ cool" },
          { es: "húmedo ≠ seco", en: "humid ≠ dry" },
          { es: "lluvioso", en: "rainy" },
          { es: "Hace calor / fresco todo el año.", en: "It's hot / cool all year round." },
          { es: "En el sur llueve menos.", en: "It rains less in the south." },
          { es: "la temporada de huracanes", en: "hurricane season" },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "classify",
        title: "¿Ventaja o inconveniente?",
        prompt: "Para alguien que busca una vida tranquila y barata, ¿estas características son una ventaja o un inconveniente?",
        categories: ["ventaja", "inconveniente"],
        items: [
          { text: "Los alquileres son bajos.", cat: 0 },
          { text: "Hay mucho ruido por la noche.", cat: 1 },
          { text: "Todos los vecinos se conocen.", cat: 0, why: "Para una vida tranquila, conocer a los vecinos es una ventaja (aunque a otras personas no les guste)." },
          { text: "Hay tapones todas las mañanas.", cat: 1 },
          { text: "El barrio está muy bien comunicado.", cat: 0 },
          { text: "La vida nocturna es muy animada y cara.", cat: 1, why: "Más ruido y más gastos: no es lo que busca esta persona." },
        ],
      },
      {
        id: "v2",
        type: "gap",
        title: "Contrarios",
        prompt: "Completa con el adjetivo contrario. Ojo con la concordancia.",
        items: [
          { q: "Mi calle no es ruidosa; es muy ___.", answers: [["tranquila"]], why: "Contrario de _ruidosa_: **tranquila** (femenino, como _calle_)." },
          { q: "Los pisos del centro no son baratos; son ___.", answers: [["caros"]], why: "Contrario de _baratos_: **caros** (masculino plural)." },
          { q: "En el sur el clima no es húmedo; es ___.", answers: [["seco"]], why: "Contrario de _húmedo_: **seco**." },
          { q: "El pueblo no está bien comunicado; está bastante ___.", answers: [["aislado"]], why: "Contrario de _bien comunicado_: **aislado**." },
          { q: "La plaza no es aburrida por la noche; es muy ___.", answers: [["animada"]], why: "Contrario de _aburrida_: **animada**." },
        ],
      },
      {
        id: "v3",
        type: "match",
        title: "Variantes regionales",
        prompt: "Une las palabras que significan lo mismo en distintas regiones.",
        pairs: [
          { left: "el carro (América)", right: "el coche (España)" },
          { left: "la renta (Puerto Rico, México)", right: "el alquiler" },
          { left: "el tapón (Puerto Rico)", right: "el atasco (España)" },
          { left: "la guagua (Caribe)", right: "el camión (México)" },
        ],
        why: "Todas significan lo mismo: el vehículo particular, el dinero mensual de la vivienda, el tráfico parado y el autobús.",
      },
    ],
  },
  pronunciation: {
    focus: "El acento de contraste: la palabra que corriges suena más fuerte",
    explanation: [
      "En una frase normal, el acento principal cae en la última palabra importante: _Vivo en Ponce._ Pero cuando **contrastas** o **corriges** algo, la palabra nueva recibe un golpe de voz más fuerte, más alto y un poco más largo: _—¿Vives en San Juan? —No, vivo en **PONCE**._",
      "Esto es muy útil al comparar: **Ponce no es más GRANDE, es más TRANQUILA.** La voz señala qué palabras se oponen. Quien escucha entiende el contraste aunque no oiga bien el resto.",
      "El contraste también puede caer en el sujeto o en un pronombre: **YO no vivo allí; vive mi HERMANA.** En inglés se hace algo parecido, pero en español la sílaba fuerte de la palabra no cambia: _tran-**QUI**-la_, nunca _TRAN-qui-la_.",
      "Además de la voz, el español usa el orden de palabras para el contraste: **En Ponce llueve menos**, **Menos llueve en Ponce** (más enfático). Esta semana, céntrate en la voz.",
    ],
    support: [
      "To contrast or correct, make the new word louder, higher and slightly longer. Keep the normal stressed syllable of the word: _tran-QUI-la_.",
      "Contrast often comes in pairs: _no es más GRANDE, es más BONITA_.",
    ],
    table: {
      head: ["Situación", "Ejemplo", "Palabra con foco"],
      rows: [
        ["corregir un lugar", "—¿Ponce está en el norte? —No, en el **sur**.", "sur"],
        ["corregir una cualidad", "No es más **barata**, es más **cómoda**.", "barata / cómoda"],
        ["corregir a una persona", "No lo dijo **Ana**, lo dijo **Luis**.", "Ana / Luis"],
        ["elegir entre dos", "—¿Playa o montaña? —**Montaña**.", "montaña"],
      ],
    },
    perceive: {
      id: "p1",
      type: "listen",
      title: "¿Dónde está el contraste?",
      prompt: "Escucha el minidiálogo y elige la palabra que lleva el foco (la información nueva o corregida).",
      items: [
        { q: "¿Qué palabra lleva el foco en la respuesta?", audio: "¿Ponce está en el norte de la isla? No, está en el sur.", options: ["sur", "está", "isla"], answer: 0, why: "_Sur_ corrige a _norte_: es la información nueva." },
        { q: "¿Qué palabra lleva el foco en la respuesta?", audio: "¿La renta es más cara en Ponce? No, es más cara en San Juan.", options: ["San Juan", "cara", "más"], answer: 0, why: "Se repite _más cara_; lo que cambia es el lugar: **San Juan**." },
        { q: "¿Qué palabra lleva el foco en la respuesta?", audio: "¿Tu hermana es mayor que tú? No, es menor.", options: ["menor", "es", "hermana"], answer: 0, why: "**Menor** corrige a _mayor_." },
        { q: "¿Qué palabras se oponen?", audio: "Mi pueblo no es más bonito, es más tranquilo.", options: ["bonito / tranquilo", "pueblo / más", "no / es"], answer: 0, why: "El contraste está entre las dos cualidades: _bonito_ frente a **tranquilo**." },
        { q: "¿Qué palabra lleva el foco?", audio: "Yo no vivo en Ponce. Mi hermana vive en Ponce.", options: ["hermana", "vive", "Ponce"], answer: 0, why: "_Ponce_ se repite; lo nuevo es la persona: **hermana** (frente a _yo_)." },
        { q: "¿Qué palabra lleva el foco en la respuesta?", audio: "¿Prefieres la playa o la montaña? Prefiero la montaña.", options: ["montaña", "prefiero", "la"], answer: 0, why: "La elección entre dos opciones: **montaña**." },
      ],
    },
    produce: [
      { text: "—¿Vives en San Juan? —No, vivo en **Ponce**.", tip: "Sube y alarga _PON_-ce. El resto de la frase, normal." },
      { text: "Ponce no es más **grande**; es más **tranquila**.", tip: "Dos focos: el primero (grande) se niega, el segundo (tranquila) gana. Mantén la sílaba fuerte: tran-**qui**-la." },
      { text: "No lo pagué **yo**; lo pagó **mi hermano**.", tip: "En español no hace falta decir _yo_, así que cuando aparece, suele ser para contrastar: dale fuerza." },
      { text: "El piso no es más **caro**; es más **pequeño**.", tip: "Niega la primera cualidad con fuerza y da todavía más fuerza a la segunda: es la que importa." },
      { text: "Para mí, la **montaña** es mejor que la **playa**.", tip: "Las dos opciones comparadas llevan foco; _mejor_ va más suave." },
    ],
    spelling: "En la escritura, el contraste no se marca con mayúsculas ni con tilde: se marca con el orden de palabras o con la puntuación (_No, en el sur._). Al leer en voz alta, busca las palabras que se oponen y dales fuerza.",
  },
  listening: {
    title: "¿San Juan o Ponce?",
    context: "Gabriela, puertorriqueña, y su pareja Julián, venezolano, viven en San Juan. A Gabriela le han ofrecido un trabajo en Ponce, en la costa sur, y tienen que decidir si se mudan. Están en la sala de su casa hablando por videollamada con la tía de Gabriela, Nilda, que vive en Ponce. Escucha la conversación completa.",
    speakers: [
      { id: "gabriela", name: "Gabriela", voice: "es-US-f", role: "puertorriqueña, arquitecta" },
      { id: "julian", name: "Julián", voice: "es-VE-m", role: "venezolano, diseñador gráfico" },
      { id: "nilda", name: "Nilda", voice: "es-CU-f", role: "tía de Gabriela, vive en Ponce" },
    ],
    script: [
      { speaker: "gabriela", text: "Titi Nilda, te llamamos porque tenemos que decidir esta semana. ¿Tú qué piensas? ¿Nos mudamos a Ponce?" },
      { speaker: "nilda", text: "¡Ay, mija, claro que sí! Aquí la vida es mucho más tranquila que en San Juan. Y la renta es más barata: por un apartamento de dos cuartos pagan menos de ochocientos dólares." },
      { speaker: "julian", text: "Eso es verdad. En San Juan pagamos casi el doble. Y el tráfico… Cuando vivía en Caracas, tardaba dos horas en llegar al trabajo. Un día me quedé tres horas en un tapón y llegué cuando todos se iban. Aquí no es tan malo, pero casi." },
      { speaker: "nilda", text: "En Ponce no hay tantos tapones como allá. Y la gente es más amable, todo el mundo se conoce." },
      { speaker: "gabriela", text: "Bueno, tía, eso no lo sabemos. Por otro lado, San Juan tiene más vida: más restaurantes, más conciertos, más amigos…" },
      { speaker: "julian", text: "Y mejores playas. Para mí, las playas del norte son las más bonitas de la isla." },
      { speaker: "nilda", text: "Las playas sí, pero aquí tenemos el Museo de Arte, la plaza, el Parque de Bombas… Cuando yo era joven, Ponce era la ciudad más elegante de Puerto Rico." },
      { speaker: "gabriela", text: "Lo que me preocupa es el calor. Ponce es más calurosa que San Juan, ¿verdad?" },
      { speaker: "nilda", text: "Sí, hace más calor y llueve menos. Pero hay menos humedad. Para mí, el clima de aquí es mejor." },
      { speaker: "julian", text: "Además, San Juan está a hora y media en carro. No es tan lejos como parece. Si extrañamos la playa, vamos el fin de semana." },
      { speaker: "gabriela", text: "Mmm… Por un lado, el trabajo en Ponce es mejor y la renta es más barata. Por otro, aquí tenemos a los amigos. Pero bueno… creo que me quedo con Ponce." },
      { speaker: "nilda", text: "¡Wepa! Les preparo el cuarto de huéspedes para la primera semana." },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: ¿qué deciden y quién está a favor de qué?",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha todo una vez y responde.",
          items: [
            { q: "¿Qué tienen que decidir Gabriela y Julián?", options: ["Si se mudan a Ponce", "Si compran un carro", "Si van de vacaciones a Venezuela"], answer: 0, why: "Gabriela tiene una oferta de trabajo en Ponce y preguntan: _¿Nos mudamos a Ponce?_" },
            { q: "¿Qué opina la tía Nilda?", options: ["Que es mejor vivir en Ponce", "Que es mejor quedarse en San Juan", "Que las dos ciudades son iguales"], answer: 0, why: "Nilda solo da ventajas de Ponce y dice _¡claro que sí!_" },
            { q: "¿Qué deciden al final?", options: ["Mudarse a Ponce", "Quedarse en San Juan", "Pensarlo un mes más"], answer: 0, why: "Gabriela dice: _creo que me quedo con Ponce_." },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: ¿de qué ciudad hablan en cada caso?",
        exercise: {
          id: "l2",
          type: "classify",
          prompt: "Según la conversación, ¿qué característica corresponde a cada ciudad?",
          categories: ["San Juan", "Ponce"],
          items: [
            { text: "La renta es más barata.", cat: 1, why: "Nilda: en Ponce pagan menos de ochocientos dólares; en San Juan, _casi el doble_." },
            { text: "Hay más restaurantes y conciertos.", cat: 0, why: "Gabriela: _San Juan tiene más vida_." },
            { text: "Tiene las playas más bonitas, según Julián.", cat: 0, why: "_Las playas del norte son las más bonitas de la isla_." },
            { text: "Hace más calor, pero hay menos humedad.", cat: 1, why: "Nilda lo confirma: _hace más calor y llueve menos. Pero hay menos humedad_." },
            { text: "Hay más tapones.", cat: 0, why: "Nilda: _En Ponce no hay tantos tapones como allá_ (en San Juan)." },
            { text: "Era la ciudad más elegante cuando Nilda era joven.", cat: 1, why: "_Cuando yo era joven, Ponce era la ciudad más elegante_." },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en las estructuras para comparar y en la anécdota de Julián.",
        exercise: {
          id: "l3",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "Nilda dice «pagan menos ___ ochocientos dólares». ¿Qué palabra usa?", options: ["de", "que", "como"], answer: 0, why: "Delante de un número: **menos de**." },
            { q: "Julián dice que San Juan «no es tan lejos ___ parece». ¿Qué palabra usa?", options: ["como", "que", "de"], answer: 0, why: "Igualdad: **tan… como**." },
            { q: "En su anécdota, ¿por qué Julián usa «tardaba» y luego «me quedé»?", options: ["_Tardaba_ es lo habitual; _me quedé_ es lo que pasó un día.", "Los dos son hábitos.", "_Tardaba_ es presente."], answer: 0, why: "Imperfecto para el hábito (_cuando vivía en Caracas, tardaba_) e indefinido para el hecho de un día (_un día me quedé_)." },
            { q: "¿Qué expresión usa Gabriela para elegir?", options: ["Me quedo con Ponce.", "Prefiero Ponce que San Juan.", "Ponce es la mejor."], answer: 0, why: "**Me quedo con…** = elijo esta opción." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "San Juan o Ponce: dos maneras de vivir en Puerto Rico",
    genre: "Artículo de revista",
    frame: "Sección «Mudarse a…» de una revista digital de vivienda. Autora: Marisol Ortiz.",
    text: [
      "Cada año, muchas personas que vuelven a Puerto Rico o que llegan de fuera se hacen la misma pregunta: ¿la capital o la Perla del Sur? Hemos comparado San Juan y Ponce en cinco aspectos clave.",
      "**Tamaño y ambiente.** San Juan es la ciudad más grande de la isla y tiene una vida cultural y nocturna mucho más animada. Ponce es más pequeña y más tranquila, pero no es un pueblo aburrido: su centro histórico, con la plaza Las Delicias y el famoso Parque de Bombas, es uno de los más bonitos de la isla.",
      "**Precio.** Esta es la gran ventaja de Ponce. Los alquileres son bastante más bajos que en la capital, y comer fuera también cuesta menos. En los barrios más buscados de San Juan, como Condado u Ocean Park, un apartamento pequeño puede costar el doble.",
      "**Clima.** Las dos ciudades tienen calor todo el año, pero Ponce, en la costa sur, es más seca y un poco más calurosa. En San Juan llueve más y la humedad es mayor. Si no soportas la humedad, el sur es mejor opción.",
      "**Transporte.** Ni en San Juan ni en Ponce el transporte público es tan bueno como en otras ciudades del mundo: en las dos ciudades hace falta carro. San Juan tiene el Tren Urbano, pero la red es pequeña, y los tapones de la mañana son famosos. En Ponce se tarda menos en llegar a todas partes.",
      "**Conclusión.** San Juan es mejor para quien busca trabajo en empresas grandes, vida nocturna y vuelos internacionales cerca. Ponce es ideal para familias y para quien prefiere una vida más barata y relajada. Como nos dijo Ernesto, un lector que se mudó al sur hace dos años: «Antes pasaba una hora y media al día en el carro. Un día hice cuentas y me di cuenta de que eran casi cuarenta días al año. Ahora llego al trabajo en diez minutos. No hay comparación».",
    ],
    glossary: [
      { es: "la Perla del Sur", en: "'the Pearl of the South', Ponce's nickname" },
      { es: "los barrios más buscados", en: "the most sought-after neighbourhoods" },
      { es: "no soportar algo", en: "to be unable to stand something" },
      { es: "hacer cuentas", en: "to do the maths" },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee el artículo y responde.",
        items: [
          { q: "¿Cuál es el objetivo del artículo?", options: ["Ayudar a elegir entre las dos ciudades", "Explicar la historia de Ponce", "Vender apartamentos en Condado"], answer: 0, why: "Compara las dos ciudades _en cinco aspectos clave_ y termina con una conclusión para cada tipo de persona." },
          { q: "Según el artículo, ¿cuál es la gran ventaja de Ponce?", options: ["el precio", "la vida nocturna", "el transporte público"], answer: 0, why: "_Precio. Esta es la gran ventaja de Ponce._" },
          { q: "¿Qué dice el texto del transporte público?", options: ["Que no es muy bueno en ninguna de las dos ciudades.", "Que es mejor en Ponce.", "Que en San Juan no hace falta carro."], answer: 0, why: "_Ni en San Juan ni en Ponce el transporte público es tan bueno como en otras ciudades del mundo_." },
          { q: "¿Por qué está contento Ernesto en Ponce?", options: ["Porque ahora pasa mucho menos tiempo en el carro.", "Porque gana más dinero.", "Porque hace menos calor."], answer: 0, why: "_Antes pasaba una hora y media al día en el carro… Ahora llego al trabajo en diez minutos._" },
        ],
      },
      {
        id: "r2",
        type: "classify",
        title: "¿Qué ciudad?",
        prompt: "Según el artículo, ¿a qué ciudad corresponde cada información? Si es verdad para las dos, elige «las dos».",
        categories: ["San Juan", "Ponce", "las dos"],
        items: [
          { text: "Tiene más vida nocturna.", cat: 0, why: "_una vida cultural y nocturna mucho más animada_." },
          { text: "Es más seca.", cat: 1, why: "_Ponce, en la costa sur, es más seca_." },
          { text: "Hace calor todo el año.", cat: 2, why: "_Las dos ciudades tienen calor todo el año_." },
          { text: "Hace falta carro.", cat: 2, why: "_en las dos ciudades hace falta carro_." },
          { text: "Comer fuera es más barato.", cat: 1, why: "_comer fuera también cuesta menos_ (en Ponce)." },
          { text: "Tiene un tren urbano.", cat: 0, why: "_San Juan tiene el Tren Urbano_." },
          { text: "Es mejor para quien busca vuelos internacionales cerca.", cat: 0, why: "Está en la conclusión, sobre San Juan." },
        ],
      },
    ],
    noticing: {
      prompt: "El artículo está lleno de comparaciones. Toca cada frase para ver cómo funcionan.",
      items: [
        { quote: "San Juan es la ciudad más grande de la isla", note: "Superlativo: **el/la más + adjetivo + de** + grupo." },
        { quote: "Los alquileres son bastante más bajos que en la capital", note: "**Bastante** o **mucho** delante de _más_ gradúan la diferencia: _mucho más barato_, _un poco más caro_." },
        { quote: "Ni en San Juan ni en Ponce el transporte público es tan bueno como en otras ciudades del mundo", note: "Igualdad en negativo: **no / ni… tan + adjetivo + como**." },
        { quote: "la humedad es mayor", note: "**Mayor** también significa _más grande_ con nombres abstractos (_mayor humedad_, _mayor problema_); con personas habla de edad." },
        { quote: "Antes pasaba una hora y media al día en el carro. Un día hice cuentas y me di cuenta…", note: "Una pequeña anécdota para apoyar la comparación: imperfecto para el hábito de antes, indefinido para el día en que todo cambió." },
      ],
    },
  },
  practice: {
    intro: "Ahora compara, elige y justifica. Algunas actividades mezclan la comparación con los pasados de las últimas semanas.",
    exercises: [
      {
        id: "x1",
        type: "gap",
        title: "Dos apartamentos",
        prompt: "Paola compara dos apartamentos en Ponce. Completa con una palabra del banco. Sobran dos.",
        bank: ["que", "como", "de", "tan", "tantas", "mejor", "más"],
        items: [
          { q: "El apartamento de la calle Victoria es ___ grande que el de la playa.", answers: [["más"]], why: "Superioridad: **más** + adjetivo + que." },
          { q: "El de la playa cuesta menos ___ 700 dólares.", answers: [["de"]], why: "Delante de un número: **menos de**." },
          { q: "El de la calle Victoria no tiene ___ ventanas como el otro.", answers: [["tantas"]], why: "_Ventanas_ es femenino plural: **tantas**." },
          { q: "Los dos están ___ cerca del centro como del hospital.", answers: [["tan"]], why: "Delante de un adverbio (_cerca_): **tan… como**." },
          { q: "Para mí, el de la playa es ___ porque tiene balcón y es más barato.", answers: [["mejor"]], why: "**Mejor** = más bueno; no se dice _más mejor_." },
        ],
      },
      {
        id: "x2",
        type: "transform",
        title: "Lo mismo, con otras palabras",
        prompt: "Reescribe la frase sin cambiar el significado. Usa la estructura indicada.",
        items: [
          { source: "Ponce es más pequeña que San Juan. (menos… que, con «grande»)", answers: ["Ponce es menos grande que San Juan."], why: "_Más pequeña_ = **menos grande**." },
          { source: "Mi barrio es más ruidoso que el tuyo. (no… tan… como)", answers: ["Tu barrio no es tan ruidoso como el mío.", "El tuyo no es tan ruidoso como el mío."], why: "Si el mío es más ruidoso, el tuyo **no es tan ruidoso como** el mío." },
          { source: "Antes había más tráfico que ahora. (ahora no hay… como antes)", answers: ["Ahora no hay tanto tráfico como antes."], why: "_Tráfico_, masculino singular: **tanto** tráfico." },
          { source: "Este mofongo está muy rico. (-ísimo)", answers: ["Este mofongo está riquísimo."], why: "rico → **riquísimo** (c → qu)." },
        ],
      },
      {
        id: "x3",
        type: "error",
        title: "Detective de errores",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "Mi abuela es la persona más sabia en mi familia.", answers: ["Mi abuela es la persona más sabia de mi familia."], why: "En el superlativo, el grupo va con **de**." },
          { sentence: "Cuando era niño, mi pueblo fue más tranquilo que ahora.", answers: ["Cuando era niño, mi pueblo era más tranquilo que ahora."], why: "Describes cómo era el pueblo en una época: **imperfecto** (_era_)." },
          { sentence: "Mi hermano menor es más alto que mí.", answers: ["Mi hermano menor es más alto que yo."], why: "Después de _que_: **yo**, no _mí_." },
          { sentence: "La comida de mi abuela es más mejor que la de los restaurantes.", answers: ["La comida de mi abuela es mejor que la de los restaurantes."], why: "**Mejor** no lleva _más_." },
        ],
      },
      {
        id: "x4",
        type: "context",
        title: "Elige y justifica",
        prompt: "Lee la situación y elige la respuesta más lógica.",
        items: [
          { context: "Te encanta la vida nocturna y trabajas en una empresa grande del centro de la capital. Te ofrecen dos pisos: uno en el centro y otro en un pueblo a una hora.", q: "¿Qué dices?", options: ["Me quedo con el del centro porque está más cerca del trabajo y hay más vida.", "Me quedo con el del pueblo porque es más ruidoso.", "Prefiero el del pueblo porque está más lejos de todo."], answer: 0, why: "La elección coherente con tus prioridades, justificada con **porque** + comparación." },
          { context: "Tu amiga dice: «En Ponce hace tanto calor como en San Juan». Tú sabes que en Ponce hace más calor.", q: "¿Cómo la corriges?", options: ["No, en Ponce hace más calor.", "Sí, hace tanto calor.", "No, en Ponce hace tan calor."], answer: 0, why: "Corriges con **más** (y con foco en la voz: _hace MÁS calor_). _Tan calor_ es incorrecto." },
          { context: "Un compañero no puede elegir entre dos cursos. Uno es más barato; el otro tiene mejores profesores.", q: "¿Qué le dices para presentar las dos opciones?", options: ["Por un lado, el primero es más barato; por otro, el segundo tiene mejores profesores.", "Por un lado, el primero es más barato; por final, el segundo es mejor.", "El primero es tan barato que el segundo."], answer: 0, why: "**Por un lado… por otro** presenta dos opciones." },
        ],
      },
      {
        id: "x5",
        type: "order",
        title: "Construye la comparación",
        prompt: "Ordena las palabras.",
        items: [
          { words: ["Es", "el", "barrio", "más", "seguro", "de", "la", "ciudad."], en: "It's the safest neighbourhood in the city.", why: "Superlativo: el + nombre + **más** + adjetivo + **de**." },
          { words: ["Aquí", "no", "llueve", "tanto", "como", "en", "el", "norte."], alt: ["No llueve tanto aquí como en el norte.", "No llueve aquí tanto como en el norte."], en: "It doesn't rain as much here as in the north.", why: "Verbo + **tanto como**." },
        ],
      },
      {
        id: "x6",
        type: "open",
        title: "Escritura guiada",
        prompt: "Escribe textos breves comparando y eligiendo.",
        items: [
          {
            prompt: "Compara en tres frases tu ciudad con otra que conoces bien: tamaño, precio y clima.",
            model: "Valencia es más pequeña que Madrid, pero es igual de animada. La vivienda es bastante más barata. Y el clima es mejor: en invierno no hace tanto frío como en Madrid.",
            checklist: ["Uso **más / menos… que**.", "Uso **tan / tanto… como** al menos una vez.", "Uso **mejor** o **peor** correctamente."],
          },
          {
            prompt: "Un amigo te pregunta: «¿Playa o montaña para las vacaciones?». Elige y justifica en dos o tres frases.",
            model: "Me quedo con la montaña. Por un lado, hace menos calor y hay menos gente; por otro, me encanta caminar. La playa es más relajante, pero me aburro muchísimo.",
            checklist: ["Elijo con **me quedo con** o **prefiero**.", "Doy al menos una razón con una comparación.", "Uso **por un lado… por otro** o **pero**."],
          },
          {
            prompt: "Escribe cómo era tu barrio hace diez años y cómo es ahora (3 frases). Añade algo que pasó un día concreto.",
            model: "Hace diez años mi barrio era más tranquilo y había menos tiendas. Ahora hay muchísimos bares y más ruido. Un día abrieron una discoteca debajo de mi casa y esa noche no pude dormir.",
            checklist: ["Uso el imperfecto para cómo era antes.", "Comparo con **más / menos** o **-ísimo**.", "Cuento un hecho concreto en indefinido."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Responde en un foro a una persona que no sabe dónde vivir.",
    context: "En un foro de expatriados, Hannah escribe: «Me voy a vivir un año a tu país (o a tu región) para trabajar en remoto. Dudo entre dos lugares: [la ciudad grande] y [un lugar más pequeño]. ¿Cuál me recomiendan?». Elige dos lugares reales que conozcas.",
    steps: [
      "Saluda y presenta las dos opciones.",
      "Compara al menos tres aspectos: precio, ambiente, clima, transporte, naturaleza.",
      "Usa un superlativo para destacar algo (_el mejor…_, _el más… de_).",
      "Cuenta una pequeña experiencia tuya en uno de los dos lugares (imperfecto + indefinido).",
      "Recomienda una opción y justifícala.",
    ],
    useLanguage: ["más / menos… que", "no es tan… como / no hay tanto(s)… como", "el / la más… de", "mejor / peor", "-ísimo", "Por un lado…, por otro…", "La ventaja / El inconveniente es que…", "Yo me quedo con… porque…"],
    model: [
      "¡Hola, Hannah! Yo conozco bien Bogotá y Villa de Leyva. Bogotá es muchísimo más grande y tiene más vida cultural, pero también hay más tráfico y más contaminación. Villa de Leyva es un pueblo pequeño, tranquilísimo y bastante más barato.",
      "El clima es diferente: en Bogotá llueve más y hace más frío; Villa de Leyva es más seca. La plaza de Villa de Leyva es la más bonita que conozco. El año pasado pasé allí un fin de semana: hacía sol, la gente era amabilísima y una señora nos invitó a café en su casa.",
      "Por un lado, Bogotá es mejor para conocer gente; por otro, para trabajar en remoto necesitas tranquilidad. Yo me quedo con Villa de Leyva, porque el internet funciona bien y la vida es menos estresante.",
    ],
    checklist: [
      "Comparo al menos tres aspectos.",
      "Uso **más/menos… que**, **tan/tanto… como** y un superlativo.",
      "Uso _de_ delante de números y en los superlativos.",
      "No escribo _más mejor_ ni _muy -ísimo_.",
      "La experiencia personal usa imperfecto (escena) e indefinido (hechos).",
      "Termino con una recomendación justificada con **porque**.",
    ],
    words: [100, 140],
  },
  speaking: {
    intro: "Esta semana hablas para convencer. Grábate, escucha si se oyen los contrastes y repite.",
    tasks: [
      {
        title: "Mi ciudad frente a otra",
        prompt: "Compara la ciudad donde vives con otra que conoces bien. Habla de tamaño, precio, clima y ambiente, y di cuál es mejor para ti.",
        prep: ["más / menos… que", "no es tan… como", "el / la más… de", "Para mí, … es mejor porque…"],
        seconds: 60,
        model: "Vivo en Lyon, pero conozco bien París. París es mucho más grande y tiene más museos, pero es carísima. Lyon no es tan famosa como París, pero la comida es mejor y la vida es más tranquila. En verano hace tanto calor como en París, o más. Para mí, Lyon es mejor porque tengo más tiempo libre.",
        selfCheck: ["Uso los tres tipos de comparación.", "Marco con la voz las palabras que contrastan.", "No digo _más mejor_.", "Termino con una elección y una razón."],
      },
      {
        title: "Elige un apartamento",
        prompt: "Tienes dos opciones en Ponce. A: centro histórico, 2 cuartos, 850 dólares, ruidoso, a 5 minutos del trabajo. B: cerca de la playa, 1 cuarto, 650 dólares, tranquilo, a 25 minutos en carro. Compáralos y elige.",
        prep: ["A es más… que B", "B cuesta menos de…", "B no es tan… como A", "Me quedo con… porque…"],
        seconds: 45,
        model: "El apartamento A es más grande y está más cerca del trabajo, pero es más caro y más ruidoso. El B cuesta menos de setecientos dólares y es tranquilísimo, aunque no es tan grande como el A. Yo me quedo con el B, porque prefiero dormir bien a llegar rápido al trabajo.",
        selfCheck: ["Uso **menos de** con el precio.", "Justifico la elección.", "Uso al menos una forma en _-ísimo_."],
      },
      {
        title: "Antes y ahora en mi barrio",
        prompt: "Cuenta cómo era un lugar que conoces bien hace años y cómo es ahora. Incluye una pequeña anécdota que muestre el cambio.",
        prep: ["Antes… era / había / tenía…", "Ahora es más… / hay menos…", "Un día… (anécdota en indefinido)"],
        seconds: 60,
        model: "Cuando era pequeña, mi barrio era más tranquilo que ahora. Había menos carros y los niños jugábamos en la calle. Ahora hay muchísimo tráfico. Un día, el año pasado, intenté cruzar la calle de mi infancia y tardé cinco minutos. ¡Me sentí muy vieja! El barrio es más moderno, pero para mí antes era mejor.",
        selfCheck: ["Uso el imperfecto para cómo era antes.", "Uso el indefinido para la anécdota.", "Comparo antes y ahora con **más / menos**."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo, compara, elige y defiende tus elecciones.",
    cards: [
      { move: "Compara", task: "Presenta tu comparación de dos ciudades sin leer. Tu profesor o profesora te hará una pregunta sobre un aspecto que no mencionaste.", phrases: ["… es más… que…", "… no es tan… como…", "Lo mejor de… es…"] },
      { move: "Elige", task: "Pídele a tu profesor o profesora que te dé dos opciones (dos restaurantes, dos viajes, dos trabajos) y elige en menos de 30 segundos, con razones.", phrases: ["Me quedo con…", "Prefiero… a… porque…", "La ventaja es que…"] },
      { move: "Defiende", task: "Tu profesor o profesora defenderá la opción contraria. Mantén tu elección con dos argumentos más.", phrases: ["Sí, pero…", "Por un lado tienes razón; por otro…", "Para mí, eso no es tan importante como…"] },
      { move: "Pregunta", task: "Pregunta a tu profesor o profesora por el lugar más bonito, más caro y más raro que ha visitado, y pídele una anécdota de uno de ellos.", phrases: ["¿Cuál es el lugar más… que conoces?", "¿Qué te pasó allí?", "¿Cómo era?"] },
    ],
    bring: "Dos fotos de dos lugares que conoces (tu ciudad y otra) para compararlos en voz alta.",
  },
  quiz: {
    items: [
      { type: "choice", q: "Mi pueblo tiene menos ___ tres mil habitantes.", options: ["de", "que", "como"], answer: 0, why: "Delante de un número: **menos de**." },
      { type: "choice", q: "En invierno, la costa no es ___ fría como la montaña.", options: ["tan", "tanto", "tanta"], answer: 0, why: "Delante de un adjetivo, siempre **tan**." },
      { type: "choice", q: "Mi hermana tiene 30 años y yo 25. Ella es mi hermana ___.", options: ["mayor", "más grande", "mejor"], answer: 0, why: "Para la edad: **mayor**." },
      { type: "listen", q: "¿Qué palabra lleva el foco en la respuesta?", audio: "¿Vas a vivir en el centro? No, voy a vivir en las afueras.", voice: "es-MX-m", options: ["afueras", "vivir", "voy"], answer: 0, why: "**Afueras** corrige a _centro_: es la información nueva." },
      { type: "listen", q: "¿Qué prefiere la persona?", audio: "La ciudad es más divertida, pero me quedo con el campo porque necesito tranquilidad.", voice: "es-CL-f", options: ["el campo", "la ciudad", "no lo sabe"], answer: 0, why: "**Me quedo con el campo** = elige el campo." },
      { type: "gap", q: "En la capital hay ___ (+) museos ___ en mi ciudad.", answers: [["más"], ["que"]], why: "Superioridad con nombre: **más** + nombre + **que**." },
      { type: "gap", q: "Aquí no hay ___ contaminación como en el centro.", answers: [["tanta"]], why: "_Contaminación_ es femenino singular: **tanta**." },
      { type: "gap", q: "Es el restaurante más barato ___ barrio.", answers: [["del"]], why: "Superlativo: **de** + el → **del**." },
      { type: "transform", source: "Este pueblo es muy tranquilo.", instruction: "Usa la forma en -ísimo.", answers: ["Este pueblo es tranquilísimo."], why: "tranquilo → **tranquilísimo**; sin _muy_." },
      { type: "order", words: ["Mi", "barrio", "es", "menos", "caro", "que", "el", "tuyo."], en: "My neighbourhood is less expensive than yours.", why: "**menos** + adjetivo + **que**." },
      { type: "error", sentence: "Prefiero vivir aquí porque los alquileres son más bajos de en la capital.", answers: ["Prefiero vivir aquí porque los alquileres son más bajos que en la capital."], why: "Para comparar dos lugares: **más… que**." },
      { type: "error", sentence: "Cuando vivíamos en Lima, un día veíamos a Vargas Llosa en una librería.", answers: ["Cuando vivíamos en Lima, un día vimos a Vargas Llosa en una librería."], why: "_Un día_ marca un hecho concreto: **vimos** (indefinido). _Vivíamos_ es la escena." },
      {
        type: "open",
        prompt: "Compara en cuatro frases el lugar donde vives ahora con el lugar donde vivías antes. Usa un comparativo, una igualdad, un superlativo y el imperfecto.",
        model: "Antes vivía en un pueblo de Galicia; ahora vivo en Barcelona. Barcelona es mucho más cara que mi pueblo. En mi pueblo no había tantas cosas que hacer como aquí. Pero la playa de mi pueblo es la más bonita de España.",
        checklist: ["Uso **más / menos… que**.", "Uso **tan / tanto… como**.", "Uso un superlativo con **de**.", "Uso el imperfecto para antes."],
      },
    ],
  },
  complete: {
    canNow: [
      "Comparar con **más / menos… que** y **más / menos de** + número.",
      "Expresar igualdad con **tan… como** y **tanto/a/os/as… como**.",
      "Destacar con **el más… de**, **-ísimo**, **mejor, peor, mayor, menor**.",
      "Describir y comparar lugares para vivir: ciudad, pueblo y clima.",
      "Marcar con la voz la palabra que contrasta.",
      "Elegir entre dos opciones y justificar la elección, también con una anécdota.",
    ],
    review: [
      "_Que_ para comparar; _de_ con números y en el superlativo.",
      "_Tan_ + adjetivo; _tanto/a/os/as_ + nombre.",
      "Nunca _más mejor_ ni _muy buenísimo_.",
      "Antes + imperfecto para comparar con el pasado.",
    ],
  },
  related: [
    { path: "/el-mercado-de-las-cantidades", label: "El Mercado de las Cantidades · comparar cantidades" },
    { path: "/modo-play-uno-o-el-otro", label: "Uno o el otro · elegir y justificar" },
    { path: "/expandir-y-precisar-descripciones", label: "El Estudio del Detalle · comparar y describir (A2)" },
  ],
};
