import type { Module } from "../../types";

export const a2w08: Module = {
  id: "a2-08",
  level: "a2",
  week: 8,
  kind: "core",
  title: "¿Me lo prestas?",
  subtitle: "Pedir, prestar, regalar y devolver: le, les y la combinación se lo.",
  stop: { place: "Cartagena", country: "Colombia" },
  minutes: 80,
  newObjectives: [
    "a2.gram.oi-pronombres",
    "a2.gram.se-lo",
    "a2.voc.regalos-prestamos",
    "a2.pron.cliticos-acento",
    "a2.fun.favores",
    "a2.wri.mensaje-favor",
  ],
  reviewObjectives: ["a2.gram.comparativos", "a2.gram.superlativos", "a2.fun.comparar-elegir", "a2.gram.imperfecto"],
  prerequisites: ["a2-07"],
  goal: {
    canDo: "Al final de esta semana puedes pedir algo prestado, ofrecer ayuda, hablar de regalos y decir a quién das algo sin repetir palabras: «¿Me lo prestas?» «Sí, te lo presto».",
    canDoEn: "By the end of this week, you can borrow things, offer help, talk about gifts and say who you give something to without repeating words: 'Can you lend it to me?' 'Yes, I'll lend it to you.'",
    steps: [
      "Aprende **me, te, le, nos, os, les**: la persona que recibe algo.",
      "Combina dos pronombres en el orden correcto: `me lo`, `te la`, `se lo`.",
      "Aprende a pedir, ofrecer y devolver favores de tú y de usted.",
      "Entrena el acento de palabras largas como `dárselo` o `explicártela`.",
      "Escucha a cuatro compañeros de piso en Cartagena que se prestan de todo.",
      "Escribe un mensaje para pedir un favor y agradecerlo.",
    ],
  },
  theory: {
    intro: "Para pedir, prestar o regalar algo necesitas hablar de dos cosas a la vez: **qué** das (el objeto) y **a quién** se lo das (la persona). Esta semana aprendes los pronombres de la persona que recibe y cómo combinarlos con lo, la, los, las, que ya conoces del A1.",
    parts: [
      {
        heading: "¿A quién? Me, te, le, nos, os, les",
        body: [
          "El **objeto indirecto** (OI) es la persona que recibe algo o se beneficia de una acción: _Doy un regalo **a Marta**_. Para no repetir el nombre usamos un pronombre: **Le** doy un regalo.",
          "Ya conoces estos pronombres: son los mismos de _gustar_ (**me** gusta, **te** gusta, **le** gusta). Solo cambian **le** y **les**, que sirven para él, ella, usted (le) y ellos, ellas, ustedes (les). No cambian según el género: _le_ vale para Marta y para Pedro.",
          "En español es muy normal decir el pronombre **y** el nombre en la misma frase: **Le** escribo **a mi abuela** todos los domingos. No es una repetición incorrecta: con _le_ y _les_ es la forma más natural, y además aclara quién es la persona.",
          "**Dónde va.** Delante del verbo conjugado: _Te mando la foto_. Con un infinitivo puede ir delante del verbo conjugado o pegado al infinitivo: **Le** voy a escribir = Voy a escribir**le**. Nunca en medio: ~~voy le a escribir~~.",
        ],
        support: [
          "Indirect object pronouns answer 'to whom?' or 'for whom?'. _Le_ = to him / to her / to you (usted); _les_ = to them / to you all (ustedes).",
          "Spanish happily says the pronoun AND the person: _Le doy el libro a Ana_ (literally 'I give her the book to Ana'). This doubling is normal, not a mistake.",
          "Some verbs take an indirect object in Spanish where English uses a direct one: _escribir a alguien, pedir algo a alguien, preguntar a alguien_. So: _Le escribo a mi madre_, not ~~Lo escribo~~.",
        ],
        table: {
          caption: "Pronombres de objeto indirecto",
          head: ["Persona", "OI", "Ejemplo"],
          rows: [
            ["yo", "me", "Mi hermana **me** presta su bici."],
            ["tú", "te", "¿**Te** mando la dirección?"],
            ["él, ella, usted", "le", "**Le** regalo flores a mi madre."],
            ["nosotros, nosotras", "nos", "El vecino **nos** trae el correo."],
            ["vosotros, vosotras (España)", "os", "¿**Os** devuelvo las llaves mañana?"],
            ["ellos, ellas, ustedes", "les", "**Les** escribo a mis abuelos por WhatsApp."],
          ],
        },
        examples: [
          { es: "Le pido ayuda a mi vecina.", en: "I ask my neighbour for help." },
          { es: "¿Les mandas las fotos a tus padres?", en: "Are you sending the photos to your parents?" },
          { es: "Señora, ¿le traigo un café?", en: "Madam, shall I bring you a coffee?" },
        ],
        mistakes: [
          { wrong: "Regalo a ella un libro.", right: "Le regalo un libro (a ella).", why: "La persona que recibe necesita el pronombre **le** delante del verbo; _a ella_ es opcional, para insistir." },
          { wrong: "Lo escribo a mi madre cada semana.", right: "Le escribo a mi madre cada semana.", why: "Mi madre recibe el mensaje: es objeto indirecto, **le**. _Lo_ sería la carta, no la persona." },
          { wrong: "Le doy los regalos a mis sobrinos.", right: "Les doy los regalos a mis sobrinos.", why: "_Mis sobrinos_ son varias personas: **les**. En la conversación oirás a veces _le_ con plural, pero en un texto escribe _les_." },
        ],
        tip: "Truco: pregunta **¿a quién?** Si la respuesta es una persona que recibe algo (un regalo, un mensaje, una pregunta, ayuda), el pronombre es _le_ o _les_.",
      },
      {
        heading: "Dos pronombres juntos: me lo, te la, se lo",
        body: [
          "Muchas veces quieres sustituir las dos cosas: la persona y el objeto. —¿Me prestas **tu paraguas**? —Sí, **te lo** presto. El orden es fijo: primero la **persona** (me, te, le, nos, os, les) y después la **cosa** (lo, la, los, las).",
          "**La regla del _se_.** Cuando _le_ o _les_ se encuentran con _lo, la, los, las_, cambian a **se**: no decimos ~~le lo~~ ni ~~les la~~, sino **se lo**, **se la**. _Le doy el libro a Ana_ → **Se lo** doy.",
          "Como _se lo_ puede ser «a él», «a ella», «a usted», «a ellos»… a veces añadimos la persona para aclarar: **Se lo** doy **a usted**, no a su hijo.",
          "La posición es la misma que con un pronombre: los dos juntos delante del verbo conjugado (**Te la** voy a devolver) o los dos pegados al infinitivo (Voy a devolvér**tela**). Nunca separados.",
        ],
        support: [
          "Order: person first, thing second — 'me it', 'you it': _me lo, te la, nos los_.",
          "_le/les_ + _lo/la/los/las_ always becomes _se_: _se lo, se la, se los, se las_. This _se_ has nothing to do with reflexive verbs; it is just _le_ in disguise.",
        ],
        table: {
          caption: "Persona + cosa",
          head: ["", "lo (el libro)", "la (la llave)", "los (los libros)", "las (las llaves)"],
          rows: [
            ["me", "me lo", "me la", "me los", "me las"],
            ["te", "te lo", "te la", "te los", "te las"],
            ["le / les → se", "se lo", "se la", "se los", "se las"],
            ["nos", "nos lo", "nos la", "nos los", "nos las"],
            ["os (España)", "os lo", "os la", "os los", "os las"],
          ],
        },
        examples: [
          { es: "—¿Me dejas tu cargador? —Claro, te lo dejo.", en: "Can I borrow your charger? — Sure, I'll lend it to you." },
          { es: "—¿Le diste la llave a Pedro? —Sí, se la di ayer.", en: "Did you give Pedro the key? — Yes, I gave it to him yesterday." },
          { es: "Las fotos de la boda… ¿nos las vas a mandar?", en: "The wedding photos… are you going to send them to us?" },
          { es: "Mis padres quieren ver el video. Voy a enviárselo esta noche.", en: "My parents want to see the video. I'm going to send it to them tonight." },
        ],
        mistakes: [
          { wrong: "Le lo doy mañana.", right: "Se lo doy mañana.", why: "_Le_ + _lo_ es imposible: _le_ cambia a **se**." },
          { wrong: "Lo te presto.", right: "Te lo presto.", why: "Primero la persona (**te**), después la cosa (**lo**)." },
          { wrong: "Te voy a lo devolver.", right: "Te lo voy a devolver. / Voy a devolvértelo.", why: "Los dos pronombres van juntos: delante del verbo conjugado o pegados al infinitivo." },
        ],
        tip: "En gran parte de América oirás **se los** para decir «se lo (a ellos)»: _—¿Les dijiste la noticia? —Sí, se los dije_. El plural pasa a _los_ para mostrar que las personas son varias. Entiéndelo; en un examen, la forma estándar es _se lo dije_.",
      },
      {
        heading: "Pedir, ofrecer y devolver favores",
        body: [
          "Para **pedir** algo prestado, la pregunta en presente es la forma más natural y amable: **¿Me prestas** tu bici? **¿Me dejas** el carro el sábado? Con más cortesía: **¿Me puedes** prestar…? / **¿Te importa** prestarme…? Con usted: **¿Me presta** su bolígrafo?",
          "Atención a dos verbos: **prestar** es dar algo por un tiempo (_Te presto mi paraguas_) y **pedir prestado** es lo que hace la otra persona (_Le pido prestado el paraguas a Luis_). Después, la cosa se **devuelve**: _Te lo devuelvo el lunes_.",
          "Para **ofrecer** ayuda, usa también una pregunta en presente: **¿Te ayudo?** **¿Le llevo la maleta?** **¿Te lo traigo?** Para aceptar: _Sí, gracias, muy amable_. Para rechazar con cortesía: _No hace falta, gracias_.",
          "Para **responder** a un favor: _Claro, toma_ / _Sí, cómo no_ / _Con mucho gusto_. Para decir que no, da una razón: _Lo siento, es que lo necesito hoy_. Y para agradecer un favor grande: **Te debo una**.",
        ],
        support: [
          "In Spanish, simple present questions are the most common way to ask for and offer things: _¿Me prestas…?_ (Can you lend me…?), _¿Te ayudo?_ (Shall I help you?).",
          "_Prestar_ = to lend; _pedir prestado_ = to borrow. English speakers often say ~~¿Puedo prestar tu libro?~~ — the correct form is _¿Me prestas tu libro?_ or _¿Te puedo pedir prestado el libro?_",
        ],
        examples: [
          { es: "¿Me prestas cinco mil pesos? Te los devuelvo mañana.", en: "Can you lend me five thousand pesos? I'll pay you back tomorrow." },
          { es: "Señor, ¿le ayudo con las bolsas?", en: "Sir, can I help you with the bags?" },
          { es: "—¿Me dejas tu portátil? —Lo siento, es que lo necesito para trabajar.", en: "Can I use your laptop? — Sorry, I need it for work." },
          { es: "Gracias por llevarme al aeropuerto. ¡Te debo una!", en: "Thanks for driving me to the airport. I owe you one!" },
        ],
        mistakes: [
          { wrong: "¿Puedo prestar tu libro?", right: "¿Me prestas tu libro?", why: "_Prestar_ lo hace quien da. Quien recibe pide: **¿Me prestas…?** o **¿Te puedo pedir prestado…?**" },
          { wrong: "Le pregunto un favor a mi vecino.", right: "Le pido un favor a mi vecino.", why: "**Pedir** es solicitar algo; _preguntar_ es buscar información." },
        ],
        tip: "En Colombia oirás **¿Me regalas…?** para pedir algo en una tienda: _¿Me regalas un tinto?_ No es gratis: significa «¿me das…?». Y muchos colombianos usan **usted** incluso con amigos y familia.",
      },
      {
        heading: "Elegir un regalo: comparar y recordar",
        body: [
          "Cuando eliges un regalo, comparas: _Un libro es **más barato que** una cafetera, pero **menos útil**_. _Esta camisa es **tan bonita como** la otra y cuesta **menos**_. Y al final eliges **el mejor** o **el más original**.",
          "Y muchas veces recuerdas: _Cuando **era** pequeña, mi abuela siempre **me regalaba** libros_. Aquí el imperfecto describe un hábito del pasado, y el pronombre _me_ dice quién recibía los regalos.",
          "Fíjate en que los pronombres funcionan igual en todos los tiempos: _me regala_ (presente), _me regalaba_ (imperfecto), _me lo regaló_ (indefinido), _me lo va a regalar_ (futuro con _ir a_).",
        ],
        support: [
          "This week recycles comparatives (_más… que, tan… como, el mejor_) and the imperfect for past habits. Pronouns stay in front of any conjugated verb, whatever the tense.",
        ],
        examples: [
          { es: "Las flores son más bonitas, pero el vino dura más.", en: "Flowers are prettier, but wine lasts longer." },
          { es: "Es el regalo más original que tengo.", en: "It's the most original present I have." },
          { es: "De niños, mis tíos nos traían dulces de Cartagena.", en: "As children, our uncles and aunts used to bring us sweets from Cartagena." },
        ],
        mistakes: [
          { wrong: "Este regalo es más mejor.", right: "Este regalo es mejor.", why: "_Mejor_ ya es comparativo: no necesita _más_." },
        ],
      },
    ],
  },
  grammar: {
    intro: "Primero un pronombre (la persona), después dos (la persona y la cosa).",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "¿A quién?",
        prompt: "Elige el pronombre de la persona que recibe.",
        items: [
          { q: "Mañana es el cumpleaños de mi padre. ___ voy a regalar una camisa.", options: ["Lo", "Le", "Les"], answer: 1, why: "Mi padre recibe el regalo: objeto indirecto singular, **le**." },
          { q: "Mis vecinos están de viaje y yo ___ riego las plantas.", options: ["le", "los", "les"], answer: 2, why: "Riego las plantas **para ellos**: son varias personas, **les**." },
          { q: "—¿Qué ___ trajo tu hermana de Perú? —Me trajo un gorro de lana.", options: ["te", "le", "me"], answer: 0, why: "La pregunta es a _ti_: ¿qué **te** trajo? La respuesta usa _me_." },
          { q: "Profesora, ¿___ puedo hacer una pregunta?", options: ["la", "le", "te"], answer: 1, why: "Hablas a la profesora **de usted**: le. _La_ sería objeto directo, y _te_ es para tú." },
          { q: "Nuestro jefe ___ paga el almuerzo los viernes a todo el equipo, a mí también.", options: ["les", "le", "nos"], answer: 2, why: "_A todo el equipo, a mí también_: el que habla está incluido, **nos**." },
        ],
      },
      {
        id: "g2",
        type: "classify",
        title: "¿Lo o le?",
        prompt: "En cada frase falta un pronombre. ¿Es la cosa (lo/la) o la persona que recibe (le)?",
        categories: ["lo / la (la cosa o persona directa)", "le (la persona que recibe)"],
        items: [
          { text: "El paquete… ___ envío mañana.", cat: 0, why: "Envío **el paquete**: objeto directo, _lo_." },
          { text: "A mi madre… ___ escribo los domingos.", cat: 1, why: "_Escribir a alguien_: la persona es objeto indirecto, _le_." },
          { text: "La bicicleta… ¿___ necesitas hoy?", cat: 0, why: "Necesitas **la bicicleta**: _la_." },
          { text: "A Julián… ___ pido ayuda con la mudanza.", cat: 1, why: "Pido ayuda **a Julián**: _le_." },
          { text: "A tu jefe… ¿___ has preguntado por las vacaciones?", cat: 1, why: "_Preguntar a alguien_: _le_." },
          { text: "Esta foto… ___ hice en la muralla de Cartagena.", cat: 0, why: "Hice **la foto**: _la_." },
        ],
      },
      {
        id: "g3",
        type: "transform",
        title: "Sin repetir",
        prompt: "Sustituye las palabras en negrita (la cosa y, si aparece, la persona) por pronombres.",
        items: [
          { source: "Te presto **mi paraguas**.", answers: ["Te lo presto."], why: "_Mi paraguas_ → **lo**. Orden: persona + cosa, **te lo**." },
          { source: "Le doy **la llave** **a Rosa**.", answers: ["Se la doy.", "Se la doy a Rosa."], why: "_Le_ + _la_ → **se la**." },
          { source: "Nos mandan **las fotos** mañana.", answers: ["Nos las mandan mañana.", "Mañana nos las mandan."], why: "_Las fotos_ → **las**: nos las." },
          { source: "Les devuelvo **los libros** **a mis compañeros**.", answers: ["Se los devuelvo.", "Se los devuelvo a mis compañeros."], why: "_Les_ + _los_ → **se los**." },
          { source: "¿Me explicas **el problema**?", answers: ["¿Me lo explicas?"], why: "_El problema_ → **lo**: me lo explicas." },
        ],
      },
      {
        id: "g4",
        type: "gap",
        title: "Con infinitivo",
        prompt: "Escribe los dos pronombres. Puedes ponerlos delante del verbo conjugado o pegados al infinitivo (con tilde).",
        items: [
          { q: "La guitarra de Andrés… ___ voy a devolver el viernes.", answers: [["se la"]], why: "Devuelvo la guitarra **a Andrés**: le + la → **se la**." },
          { q: "¿Las entradas del concierto? Mi hermano quiere ___ (dar a mí) hoy.", answers: [["dármelas"]], hint: "dar + me + las", why: "Pegados al infinitivo: dar + me + las = **dármelas**, con tilde porque el acento queda en la antepenúltima sílaba o antes." },
          { q: "Si no entiendes el ejercicio, puedo ___ (explicar a ti) después de clase.", answers: [["explicártelo"]], hint: "explicar + te + lo", why: "Explicar + te + lo = **explicártelo**. El acento de _explicar_ (-car) no se mueve, por eso necesita tilde." },
          { q: "Mi tía quiere ver las fotos del viaje. ___ voy a mandar por correo.", answers: [["Se las"]], why: "Las fotos (las) a mi tía (le) → **se las**." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Aprende los verbos con sus compañeros: **prestar algo a alguien**, **pedir algo prestado**, **devolver algo**. Así ya tienes la frase completa.",
    groups: [
      {
        title: "Prestar y devolver",
        items: [
          { es: "prestarle algo a alguien", en: "to lend something to someone" },
          { es: "pedir algo prestado", en: "to borrow something" },
          { es: "dejarle algo a alguien", en: "to let someone use something (very common for lending)" },
          { es: "devolver algo (a tiempo)", en: "to give something back (on time)" },
          { es: "deberle dinero a alguien", en: "to owe someone money" },
          { es: "la plata (Colombia, Cono Sur) / el dinero", en: "money (colloquial / standard)" },
          { es: "el carro (América) / el coche (España)", en: "the car" },
          { es: "el cargador del celular (América) / del móvil (España)", en: "the phone charger" },
        ],
      },
      {
        title: "Regalos y celebraciones",
        items: [
          { es: "regalarle algo a alguien", en: "to give someone a present" },
          { es: "envolver un regalo", en: "to wrap a present" },
          { es: "una tarjeta de cumpleaños", en: "a birthday card" },
          { es: "un detalle", en: "a small gift, a thoughtful gesture" },
          { es: "una sorpresa", en: "a surprise" },
          { es: "darle las gracias a alguien", en: "to thank someone" },
          { es: "abrir los regalos", en: "to open the presents" },
          { es: "el amigo secreto (América) / el amigo invisible (España)", en: "Secret Santa" },
        ],
      },
      {
        title: "Enviar, ayudar y pedir favores",
        items: [
          { es: "enviar / mandar un paquete", en: "to send a parcel" },
          { es: "mandarle un mensaje a alguien", en: "to send someone a message" },
          { es: "pedirle un favor a alguien", en: "to ask someone a favour" },
          { es: "hacerle un favor a alguien", en: "to do someone a favour" },
          { es: "echarle una mano a alguien", en: "to give someone a hand" },
          { es: "regarle las plantas a alguien", en: "to water someone's plants" },
          { es: "recogerle un paquete a alguien", en: "to pick up a parcel for someone" },
          { es: "Te debo una.", en: "I owe you one." },
          { es: "No hace falta, gracias.", en: "There's no need, thanks." },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "context",
        title: "¿Prestar, pedir prestado o devolver?",
        prompt: "Lee la situación y elige la frase correcta.",
        items: [
          { context: "Tu amiga tiene una maleta grande y tú te vas de viaje.", q: "Le dices:", options: ["¿Me prestas tu maleta?", "¿Te presto tu maleta?", "¿Me devuelves tu maleta?"], answer: 0, why: "Ella es quien presta: **¿me prestas…?** _Te presto_ sería ofrecerle tu maleta." },
          { context: "Tu compañero te dejó un libro hace tres semanas.", q: "Le dices:", options: ["Te pido prestado el libro.", "Te devuelvo el libro, gracias.", "Te regalo el libro."], answer: 1, why: "El libro es suyo y ya lo leíste: lo **devuelves**." },
          { context: "Le cuentas a otra persona lo que hiciste ayer.", q: "Dices:", options: ["Le presté el taladro de mi vecino.", "Le devolví prestado el taladro.", "Le pedí prestado el taladro a mi vecino."], answer: 2, why: "El taladro es del vecino y tú lo necesitabas: se lo **pediste prestado**." },
          { context: "Alguien te hizo un favor enorme.", q: "Dices:", options: ["¡Te debo una!", "¡Te presto una!", "¡No hace falta!"], answer: 0, why: "**Te debo una** = I owe you one. _No hace falta_ sirve para rechazar ayuda." },
        ],
      },
      {
        id: "v2",
        type: "match",
        title: "Variantes",
        prompt: "Une la palabra de América con la de España.",
        pairs: [
          { left: "el carro", right: "el coche" },
          { left: "el celular", right: "el móvil" },
          { left: "el amigo secreto", right: "el amigo invisible" },
          { left: "la plata", right: "el dinero" },
        ],
        why: "Las dos formas se entienden en todas partes; las de la izquierda son las habituales en Colombia y gran parte de América. _Dinero_ es la forma estándar en todo el mundo hispano.",
      },
      {
        id: "v3",
        type: "gap",
        title: "Frases de favor",
        prompt: "Completa con una palabra del banco.",
        bank: ["mano", "favor", "detalle", "falta", "envolver"],
        items: [
          { q: "¿Me echas una ___ con la mudanza el sábado?", answers: [["mano"]], why: "_Echar una mano_ = ayudar." },
          { q: "Gracias por las flores, ¡qué ___ tan bonito!", answers: [["detalle"]], why: "Un **detalle** es un regalo pequeño con cariño." },
          { q: "—¿Te ayudo con las bolsas? —No hace ___, gracias.", answers: [["falta"]], why: "_No hace falta_ = no es necesario." },
          { q: "En la tienda me pueden ___ el regalo con papel bonito.", answers: [["envolver"]], why: "**Envolver** un regalo = to wrap it." },
          { q: "¿Te puedo pedir un ___? Necesito que alguien me recoja un paquete.", answers: [["favor"]], why: "**Pedir un favor** a alguien." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "Pronombres pegados: el acento se queda en su sitio",
    explanation: [
      "Cuando pegas pronombres a un infinitivo, la palabra crece por detrás, pero **el acento no se mueve**: sigue en la misma sílaba del verbo. _prestar_ → pres**tar**le → pres**tár**telo. Los pronombres son átonos: se pronuncian débiles, pegados al verbo, como sílabas extra.",
      "Con **un** pronombre, la palabra normalmente es llana terminada en vocal: _darle, comprarte, explicarlo_. No lleva tilde. Con **dos** pronombres, el acento queda tres sílabas o más antes del final, la palabra es esdrújula (o sobresdrújula) y **siempre lleva tilde**: _dárselo, comprártela, explicárnoslo_.",
      "Verás lo mismo la próxima semana con el imperativo: _da_ → **dá**melo, _explica_ → ex**plí**caselo. La tilde no cambia la pronunciación: solo marca en la escritura la sílaba que ya era fuerte.",
      "En todas las variedades del español el acento se mantiene en el verbo. Lo que cambia de región a región es el ritmo y algún sonido: en la costa caribe de Colombia, por ejemplo, la s final de _nos_ o _les_ se aspira delante de consonante, y _les traigo_ suena casi «leh traigo».",
    ],
    support: [
      "Attached pronouns never take the stress. Keep the stress where it was in the verb and let the pronouns trail after it: pres-TÁR-te-lo, not pres-tar-TE-lo.",
      "Written accent rule: one pronoun on an infinitive → no accent (_darle_); two pronouns → accent (_dárselo_).",
    ],
    table: {
      head: ["Verbo", "+ 1 pronombre", "+ 2 pronombres"],
      rows: [
        ["dar", "darle", "dárselo"],
        ["prestar", "prestarte", "prestártela"],
        ["devolver", "devolverle", "devolvérselos"],
        ["explicar", "explicarnos", "explicárnoslo"],
        ["pedir", "pedirle", "pedírselo"],
      ],
    },
    perceive: {
      id: "p1",
      type: "listen",
      title: "¿Dónde está la fuerza?",
      prompt: "Escucha la palabra y elige la sílaba más fuerte.",
      items: [
        { q: "¿Qué sílaba es la fuerte?", audio: "prestártelo", options: ["pres", "tár", "te", "lo"], answer: 1, why: "El acento de _prestar_ está en **-tar**, y ahí se queda." },
        { q: "¿Qué sílaba es la fuerte?", audio: "devolvérmelas", options: ["de", "vol", "vér", "me"], answer: 2, why: "_Devolver_ → devol**ver** → devol**vér**melas." },
        { q: "¿Qué sílaba es la fuerte?", audio: "regalarle", options: ["re", "ga", "lar", "le"], answer: 2, why: "Con un pronombre: rega**lar**le, llana, sin tilde." },
        { q: "¿Qué sílaba es la fuerte?", audio: "pedírselo", options: ["pe", "dír", "se", "lo"], answer: 1, why: "_Pedir_ → pe**dir** → pe**dír**selo." },
        { q: "¿Qué sílaba es la fuerte?", audio: "enviárnosla", options: ["en", "viár", "nos", "la"], answer: 1, why: "_Enviar_ → en**viar** → en**viár**nosla." },
        { q: "¿Qué sílaba es la fuerte?", audio: "dármelo", options: ["dár", "me", "lo"], answer: 0, why: "_Dar_ tiene una sola sílaba: toda la fuerza en **dár**." },
      ],
    },
    produce: [
      { text: "¿Me lo prestas? Te lo devuelvo mañana.", tip: "_Me lo_ y _te lo_ son débiles y rápidos: me-lo-PRES-tas, te-lo-de-VUEL-vo." },
      { text: "Voy a dárselo esta noche.", tip: "Toda la fuerza en **dár**; _selo_ casi sin peso.", voice: "es-CO-f" },
      { text: "No entiendo el problema. ¿Puedes explicármelo otra vez?", tip: "expli-**CÁR**-me-lo: no subas la voz en _me_ ni en _lo_." },
      { text: "Las fotos de la fiesta… quiero mandárselas a mis abuelos.", tip: "man-**DÁR**-se-las. Practica primero _mandar_, luego _mandarle_, luego _mandárselas_." },
      { text: "Señora, ¿se lo llevo? Puedo llevárselo ahora mismo.", tip: "Dos posiciones, el mismo acento en el verbo: se-lo-**LLE**-vo / lle-**VÁR**-se-lo." },
    ],
    spelling: "Regla rápida: infinitivo + un pronombre → sin tilde (_darle, prestarte_). Infinitivo + dos pronombres → tilde en la vocal del infinitivo (_dárselo, prestártela_).",
  },
  listening: {
    title: "Un apartamento en Getsemaní",
    context: "Cuatro amigos comparten un apartamento en el barrio de Getsemaní, en Cartagena. Lucía, una española de intercambio, se va el fin de semana a una boda y necesita ayuda. Escucha la conversación en la cocina.",
    speakers: [
      { id: "lucia", name: "Lucía", voice: "es-ES-f", role: "estudiante de intercambio" },
      { id: "camila", name: "Camila", voice: "es-CO-f", role: "compañera de piso, de Cartagena" },
      { id: "andres", name: "Andrés", voice: "es-VE-m", role: "compañero de piso" },
      { id: "mateo", name: "Mateo", voice: "es-MX-m", role: "compañero de piso" },
    ],
    script: [
      { speaker: "lucia", text: "Camila, ¿me haces un favor? El sábado tengo la boda de mi prima en Barú y no tengo nada para ponerme." },
      { speaker: "camila", text: "¡Claro! Tengo dos vestidos: uno azul y uno blanco. El azul es más fresco que el blanco, y con este calor…" },
      { speaker: "lucia", text: "El azul, entonces. ¿Me lo prestas hasta el domingo?" },
      { speaker: "camila", text: "Sí, te lo presto. Pero me lo devuelves limpio, ¿eh?" },
      { speaker: "andres", text: "Oye, Lucía, hablando de devolver… ¿y mi cargador? Te lo presté el lunes." },
      { speaker: "lucia", text: "¡Ay, perdón! Lo tengo en mi cuarto. Ahora mismo te lo doy." },
      { speaker: "andres", text: "Tranquila. Es que sin él no puedo cargar el celular." },
      { speaker: "mateo", text: "Lucía, ¿y qué le vas a regalar a tu prima?" },
      { speaker: "lucia", text: "No sé. Cuando éramos niñas, ella siempre me regalaba libros. A lo mejor le compro uno." },
      { speaker: "mateo", text: "Un libro es más barato que una cafetera, pero es para ella sola. ¿Por qué no les regalas algo a los dos? Tienen casa nueva." },
      { speaker: "lucia", text: "¡Buena idea! Les regalo unas copas para la casa." },
      { speaker: "camila", text: "Y yo te presto mi maleta pequeña. Es la más ligera de la casa." },
      { speaker: "lucia", text: "¡Gracias, de verdad! Les debo una a todos." },
      { speaker: "andres", text: "A mí no me debes nada… solo mi cargador." },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: ¿cuál es la situación en general?",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha una vez y responde.",
          items: [
            { q: "¿Por qué necesita ayuda Lucía?", options: ["Se cambia de apartamento.", "Se va a una boda.", "Está enferma."], answer: 1, why: "Dice: _tengo la boda de mi prima_." },
            { q: "¿Cómo reaccionan sus compañeros?", options: ["Nadie quiere ayudarla.", "Solo la ayuda Andrés.", "La ayudan todos."], answer: 2, why: "Camila le presta un vestido y una maleta, Mateo le da una idea para el regalo." },
            { q: "¿Qué problema tiene Andrés?", options: ["Lucía no le ha devuelto algo.", "Lucía le rompió algo.", "Lucía le debe dinero."], answer: 0, why: "_¿Y mi cargador? Te lo presté el lunes._" },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: los detalles.",
        exercise: {
          id: "l2",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "¿Qué vestido elige Lucía?", options: ["el blanco", "el azul", "los dos"], answer: 1, why: "Camila dice que el azul es **más fresco que** el blanco." },
            { q: "¿Hasta cuándo necesita el vestido?", options: ["hasta el lunes", "hasta el sábado", "hasta el domingo"], answer: 2 },
            { q: "¿Qué le regalaba la prima a Lucía cuando eran niñas?", options: ["libros", "copas", "vestidos"], answer: 0, why: "_Ella siempre me regalaba libros_: hábito en imperfecto." },
            { q: "Al final, ¿qué van a recibir los novios?", options: ["un libro", "unas copas", "una cafetera"], answer: 1, why: "_Les regalo unas copas para la casa._" },
            { q: "¿Cómo es la maleta de Camila?", options: ["más grande que la de Lucía", "tan pesada como la de Andrés", "la más ligera de la casa"], answer: 2 },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: ¿a qué se refieren los pronombres?",
        exercise: {
          id: "l3",
          type: "listen",
          prompt: "Escucha la frase y decide qué es _lo_ o _les_.",
          items: [
            { q: "En esta frase, **lo** es…", audio: "¿Me lo prestas hasta el domingo?", voice: "es-ES-f", options: ["el vestido azul", "el cargador", "el libro"], answer: 0, why: "Lucía acaba de elegir _el azul_ (el vestido)." },
            { q: "En esta frase, **lo** es…", audio: "Te lo presté el lunes.", voice: "es-VE-m", options: ["el vestido", "el cargador", "el celular"], answer: 1, why: "Andrés habla de su cargador." },
            { q: "En esta frase, **les** es…", audio: "¿Por qué no les regalas algo a los dos?", voice: "es-MX-m", options: ["los compañeros de piso", "los padres de Lucía", "la prima y su pareja"], answer: 2, why: "_A los dos_: los novios." },
            { q: "En esta frase, **me** es…", audio: "Ella siempre me regalaba libros.", voice: "es-ES-f", options: ["Lucía, la que habla", "la prima", "Mateo"], answer: 0, why: "_Me_ = a mí, la persona que habla." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Banco de favores · Edificio Las Palmas",
    genre: "Grupo de vecinos",
    frame: "Mensajes en el grupo de WhatsApp de un edificio del barrio Manga, en Cartagena. Los vecinos se piden y se ofrecen favores.",
    text: [
      "**Rosa (apto. 302):** Buenos días, vecinos. Me voy a Medellín del 10 al 15. ¿Alguien me puede regar las plantas? Les dejo la llave al portero y les traigo café de la zona cafetera, ¡prometido!",
      "**Fernando (apto. 105):** Rosa, yo se las riego, no hay problema. Mi hija las cuidaba el año pasado y las tenía más bonitas que tú, jaja. ¿Me dejas la llave a mí directamente?",
      "**Rosa (apto. 302):** ¡Mil gracias, Fernando! Sí, te la doy esta tarde. Te debo una.",
      "**Daniela (apto. 410):** Hola a todos. Alguien me pidió prestada la escalera hace dos semanas y no me la ha devuelto 😅. Es la escalera más alta del edificio, la necesito el viernes para pintar. ¿Me la devuelven, por favor?",
      "**Kevin (apto. 201):** Daniela, ¡fui yo! Perdón, se me olvidó. Te la llevo hoy. Y si quieres, te echo una mano con la pintura: tengo un rodillo mejor que el tuyo 😉.",
      "**Señora Beatriz (apto. 501):** Buenas tardes. Este jueves llega un paquete para mí y no voy a estar. ¿Alguno de ustedes me lo puede recibir? Les agradezco mucho.",
    ],
    glossary: [
      { es: "el portero", en: "the doorman" },
      { es: "la escalera", en: "the ladder (also: stairs)" },
      { es: "el rodillo", en: "the paint roller" },
      { es: "se me olvidó", en: "I forgot" },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee los mensajes y responde.",
        items: [
          { q: "¿Qué ofrece Rosa a cambio del favor?", options: ["plantas", "café", "dinero"], answer: 1, why: "_Les traigo café de la zona cafetera._" },
          { q: "¿Quién le va a regar las plantas a Rosa?", options: ["la hija de Fernando", "el portero", "Fernando"], answer: 2, why: "Fernando escribe: _yo se las riego_. Su hija las cuidaba **el año pasado**." },
          { q: "¿Por qué Daniela necesita la escalera?", options: ["para pintar", "para regar", "para mudarse"], answer: 0 },
          { q: "¿Qué tiene que hacer la persona que ayude a la señora Beatriz?", options: ["devolverle una llave", "recibir un paquete", "pintar su apartamento"], answer: 1 },
        ],
      },
      {
        id: "r2",
        type: "match",
        prompt: "¿A qué se refiere cada pronombre del texto?",
        pairs: [
          { left: "yo **se las** riego (Fernando)", right: "las plantas, a Rosa" },
          { left: "**te la** doy esta tarde (Rosa)", right: "la llave, a Fernando" },
          { left: "no **me la** ha devuelto (Daniela)", right: "la escalera, a Daniela" },
          { left: "¿**me lo** puede recibir? (Beatriz)", right: "el paquete, para Beatriz" },
        ],
        why: "Primero va la persona (me, te, se) y después la cosa (lo, la, las). _Se_ aparece en lugar de _le_ cuando va con _las_.",
      },
      {
        id: "r3",
        type: "classify",
        prompt: "¿Quién pide un favor y quién lo ofrece?",
        categories: ["pide un favor", "ofrece ayuda"],
        items: [
          { text: "Rosa", cat: 0, why: "Pide que le rieguen las plantas." },
          { text: "Fernando", cat: 1, why: "Ofrece regar las plantas." },
          { text: "Daniela", cat: 0, why: "Pide que le devuelvan la escalera." },
          { text: "Kevin", cat: 1, why: "Devuelve la escalera y además ofrece ayudar a pintar." },
          { text: "La señora Beatriz", cat: 0, why: "Pide que alguien reciba su paquete." },
        ],
      },
    ],
    noticing: {
      prompt: "Fíjate en cómo se piden y se ofrecen las cosas.",
      items: [
        { quote: "¿Alguien me puede regar las plantas?", note: "Pedir un favor con **poder** + infinitivo. _Me_ = para mí." },
        { quote: "yo se las riego", note: "_Le_ (a Rosa) + _las_ (las plantas) → **se las**." },
        { quote: "las tenía más bonitas que tú", note: "Repaso: imperfecto para un hábito del pasado + comparativo **más… que**." },
        { quote: "Es la escalera más alta del edificio", note: "Repaso: superlativo **la más… del**." },
        { quote: "¿Alguno de ustedes me lo puede recibir? Les agradezco mucho.", note: "La señora Beatriz habla de **ustedes** a todos: en América es el único plural de _tú_ y de _usted_." },
      ],
    },
  },
  practice: {
    intro: "Combina pronombres, favores y regalos. Los últimos ejercicios repasan comparativos e imperfecto.",
    exercises: [
      {
        id: "x1",
        type: "error",
        title: "Detective de pronombres",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "¿Las llaves? Le las di al portero.", answers: ["¿Las llaves? Se las di al portero."], why: "_Le_ + _las_ → **se las**." },
          { sentence: "¿Me puedes prestar tu carro? Lo te devuelvo el lunes.", answers: ["¿Me puedes prestar tu carro? Te lo devuelvo el lunes."], why: "Primero la persona, después la cosa: **te lo**." },
          { sentence: "Mañana voy a regalarlo a mi hermana un perfume.", answers: ["Mañana voy a regalarle a mi hermana un perfume.", "Mañana voy a regalarle un perfume a mi hermana.", "Mañana le voy a regalar a mi hermana un perfume.", "Mañana le voy a regalar un perfume a mi hermana."], why: "Mi hermana recibe el regalo: **le**, no _lo_." },
          { sentence: "¿Puedo prestar tu bicicleta esta tarde?", answers: ["¿Me prestas tu bicicleta esta tarde?", "¿Me puedes prestar tu bicicleta esta tarde?", "¿Te puedo pedir prestada tu bicicleta esta tarde?"], why: "Tú no prestas la bici de otra persona: se la **pides prestada**. Lo más natural: _¿Me prestas…?_" },
          { sentence: "El libro me lo regaló mi abuelo. Es el regalo más bonito de mi vida y es más mejor que todos.", answers: ["El libro me lo regaló mi abuelo. Es el regalo más bonito de mi vida y es mejor que todos."], why: "Repaso: _mejor_ ya es comparativo, nunca **más mejor**." },
        ],
      },
      {
        id: "x2",
        type: "context",
        title: "¿Qué respondes?",
        prompt: "Elige la respuesta más natural.",
        items: [
          { context: "Tu vecina mayor sube la escalera con tres bolsas.", q: "Le dices:", options: ["Señora, ¿me ayuda con las bolsas?", "Señora, ¿te ayudo con las bolsas?", "Señora, ¿le ayudo con las bolsas?"], answer: 2, why: "Ofreces ayuda (¿**le** ayudo?) y de usted, porque es una señora mayor que no conoces bien." },
          { context: "Un amigo: «¿Me prestas tu portátil esta noche?». Lo necesitas para trabajar.", q: "Respondes:", options: ["Lo siento, es que lo necesito para trabajar.", "No, no te lo presto.", "Sí, cómo no."], answer: 0, why: "Para decir que no con cortesía, da una razón: **es que…**" },
          { context: "Tu compañera te ofrece: «¿Te llevo al aeropuerto?». Ya tienes taxi.", q: "Respondes:", options: ["Te debo una.", "No hace falta, gracias. Ya tengo taxi.", "Sí, te lo llevo."], answer: 1, why: "**No hace falta** rechaza una oferta amablemente." },
          { context: "En una cafetería de Cartagena quieres un café.", q: "Lo más típico allí es:", options: ["¿Le presto un tinto?", "¿Me devuelve un tinto?", "¿Me regala un tinto, por favor?"], answer: 2, why: "En Colombia _regalar_ se usa para pedir en tiendas: **¿Me regala…?** = ¿Me da…? Y _tinto_ es un café negro." },
        ],
      },
      {
        id: "x3",
        type: "order",
        title: "Frases completas",
        prompt: "Ordena las palabras.",
        items: [
          { words: ["¿Me", "lo", "puedes", "traer", "mañana?"], en: "Can you bring it to me tomorrow?", why: "Los dos pronombres juntos delante del verbo conjugado: _me lo puedes_." },
          { words: ["Se", "la", "voy", "a", "devolver", "el", "viernes."], alt: ["El viernes se la voy a devolver."], en: "I'm going to give it back to him/her on Friday.", why: "_Se la_ delante de _voy a + infinitivo_." },
          { words: ["Cuando", "era", "niño,", "mi", "abuela", "me", "regalaba", "cuentos."], alt: ["Mi abuela me regalaba cuentos cuando era niño."], en: "When I was a child, my grandmother used to give me storybooks.", why: "Repaso: imperfecto para hábitos en el pasado; _me_ delante del verbo." },
        ],
      },
      {
        id: "x4",
        type: "gap",
        title: "¿Cuál es mejor regalo?",
        prompt: "Repaso: completa la comparación con una palabra.",
        items: [
          { q: "La bufanda cuesta 40 000 pesos y el libro 40 000 también. La bufanda es ___ cara como el libro.", answers: [["tan"]], why: "Igualdad con adjetivo: **tan** + adjetivo + **como**." },
          { q: "Para mi padre, una camisa es ___ útil que una tarjeta.", answers: [["más"]], why: "Superioridad: **más** + adjetivo + **que**." },
          { q: "De todas las opciones, la cafetera es la ___ práctica.", answers: [["más"]], why: "Superlativo: **la más** + adjetivo." },
          { q: "El vino es bueno, pero el café de Colombia es ___ todavía.", answers: [["mejor"]], why: "Comparativo irregular de _bueno_: **mejor**." },
          { q: "Mi hermano tiene ___ libros como yo: unos doscientos cada uno.", answers: [["tantos"]], why: "Igualdad con sustantivo: **tanto/a/os/as** concuerda con _libros_ → **tantos**." },
        ],
      },
      {
        id: "x5",
        type: "open",
        title: "Mensajes cortos",
        prompt: "Escribe dos o tres frases para cada situación. Usa pronombres para no repetir.",
        items: [
          {
            prompt: "Un amigo te escribe: «¿Me prestas tu cámara para el viaje?». Respóndele: di que sí y pon una condición.",
            model: "¡Claro! Te la presto, pero me la devuelves el lunes, porque la necesito para el trabajo. Te la llevo mañana a tu casa.",
            checklist: ["Uso _te la_ para no repetir _la cámara_.", "Pongo una condición o una fecha para devolverla.", "Los pronombres van delante del verbo conjugado."],
          },
          {
            prompt: "Cuenta qué te regalaban de niño o niña en tu cumpleaños y quién te lo regalaba.",
            model: "Cuando era pequeña, mis padres siempre me regalaban un libro y mi abuela me hacía una torta de chocolate. El libro era el mejor regalo del día.",
            checklist: ["Uso el imperfecto (_regalaban, hacía, era_).", "Uso _me_ para decir quién recibía el regalo.", "Incluyo una comparación o un superlativo."],
          },
          {
            prompt: "Tu vecina se va de viaje. Ofrécele dos ayudas concretas en un mensaje.",
            model: "Hola, Marta. Si quieres, te riego las plantas mientras estás fuera. También te puedo recoger los paquetes. ¡Buen viaje!",
            checklist: ["Ofrezco con presente o _te puedo + infinitivo_.", "Uso _te_ para la persona que recibe la ayuda."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe un mensaje a un vecino o una vecina para pedirle un favor, y después un segundo mensaje corto para darle las gracias.",
    context: "Te vas de viaje cinco días. Necesitas que alguien te recoja un paquete o te riegue las plantas. Escribes en el grupo del edificio, como en la lectura.",
    steps: [
      "Saluda y explica la situación (adónde vas y cuándo).",
      "Pide el favor con una pregunta amable: _¿Me puedes…? / ¿Te importa…?_",
      "Explica cómo le vas a dar la llave o la información (usa _se la_ o _te la_).",
      "Ofrece algo a cambio.",
      "Escribe el mensaje de agradecimiento después del viaje.",
    ],
    useLanguage: ["¿Me puedes…? / ¿Le importa…?", "te la dejo / se la doy", "le / les", "te traigo… / le traigo…", "¡Mil gracias! Te debo una."],
    model: [
      "Hola, Julián. Me voy a Bogotá del martes al domingo y el jueves me llega un paquete con unos libros. ¿Me lo puedes recoger? Le digo al portero que te lo dé a ti. Si quieres, te dejo la llave de mi casa y me lo pones encima de la mesa. A la vuelta te traigo unas almojábanas de Bogotá. ¡Gracias!",
      "Julián, ya estoy en casa y vi el paquete en la mesa. ¡Mil gracias! Te debo una. Las almojábanas te las llevo esta tarde.",
    ],
    checklist: [
      "Explico la situación antes de pedir el favor.",
      "Pido con una pregunta, no con una orden.",
      "Uso al menos dos combinaciones de pronombres (me lo, te la, se la…).",
      "_Le_ / _les_ cambian a _se_ delante de lo, la, los, las.",
      "Ofrezco algo a cambio y agradezco.",
    ],
    words: [60, 100],
  },
  speaking: {
    intro: "Graba cada tarea, escúchate y repite. Fíjate sobre todo en el orden de los pronombres.",
    tasks: [
      {
        title: "Tres favores en un día",
        prompt: "Hoy necesitas tres cosas: un cargador, que alguien te lleve al aeropuerto y que alguien te riegue las plantas. Pide los tres favores a tres personas: un compañero de piso (tú), tu vecina mayor (usted) y tu hermana (tú). Después contesta tú mismo con una respuesta positiva usando dos pronombres.",
        prep: ["¿Me prestas…? → Sí, te lo presto.", "¿Me puede…? → Sí, claro, se lo…", "¿Te importa…?"],
        seconds: 60,
        model: "Oye, Mateo, ¿me prestas tu cargador? —Sí, claro, te lo presto. … Señora Beatriz, ¿me puede regar las plantas esta semana? —Sí, cómo no, se las riego. … Ana, ¿te importa llevarme al aeropuerto? —Para nada, te llevo a las seis.",
        selfCheck: ["Uso usted con la vecina (_¿me puede…?_).", "Respondo con dos pronombres en el orden correcto.", "Pronuncio _me lo_, _te lo_ débiles y rápidos."],
      },
      {
        title: "El regalo perfecto",
        prompt: "Un amigo cumple años. Tienes tres ideas: un libro, una planta y una cena. Compáralas y explica cuál le vas a regalar y por qué.",
        prep: ["más / menos… que", "tan… como", "el mejor / el más original", "le voy a regalar…"],
        seconds: 60,
        model: "Para Diego tengo tres ideas. Un libro es más barato que una cena, pero él ya tiene muchísimos libros. Una planta es tan bonita como unas flores y dura más. Pero creo que la cena es el regalo más original, porque podemos ir juntos. Así que le voy a regalar una cena en un restaurante peruano.",
        selfCheck: ["Hago al menos dos comparaciones.", "Uso un superlativo.", "Uso _le_ para mi amigo."],
      },
      {
        title: "Un regalo de mi infancia",
        prompt: "Cuenta un regalo que recibías a menudo cuando eras pequeño o pequeña: quién te lo regalaba, cómo era y por qué te gustaba.",
        prep: ["Cuando era pequeño/a…", "mi tía siempre me regalaba…", "era más… que…"],
        seconds: 45,
        model: "Cuando era pequeño, mi tía Rosa siempre me regalaba camisetas de fútbol. Eran camisetas de equipos de todo el mundo. Me gustaban más que los juguetes porque las usaba todos los días.",
        selfCheck: ["Uso el imperfecto para los hábitos.", "Uso _me_ con el verbo _regalar_."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo vas a pedir, ofrecer y comparar de verdad.",
    cards: [
      { move: "Pide", task: "Pide prestado algo real a tu profesor o profesora (un bolígrafo, un libro, un enlace) y promete devolverlo.", phrases: ["¿Me prestas…? / ¿Me presta…?", "Te lo devuelvo al final de la clase.", "¿Me lo puedes mandar por el chat?"] },
      { move: "Ofrece", task: "Ofrece dos ayudas concretas relacionadas con la clase.", phrases: ["¿Te mando mi texto?", "¿Te lo explico otra vez con otro ejemplo?"] },
      { move: "Compara", task: "Presenta tres ideas de regalo para una persona de tu vida, compáralas y pide consejo.", phrases: ["Es más práctico que…", "¿Cuál es el mejor para ella?", "¿Qué me recomiendas?"] },
      { move: "Cuenta", task: "Cuenta el mejor regalo que recibiste de niño o niña y quién te lo regalaba.", phrases: ["Cuando era pequeño/a…", "Me lo regaló mi…", "Era el mejor regalo de…"] },
    ],
    bring: "Una foto de un regalo especial que recibiste o que regalaste.",
  },
  quiz: {
    items: [
      { type: "choice", q: "Mis abuelos viven lejos. ___ escribo una carta cada mes.", options: ["Les", "Los", "Le"], answer: 0, why: "Los abuelos reciben la carta: objeto indirecto plural, **les**." },
      { type: "choice", q: "—¿Le diste el regalo a Sara? —Sí, ___ di ayer.", options: ["le lo", "se lo", "lo le"], answer: 1, why: "_Le_ + _lo_ → **se lo**." },
      { type: "listen", q: "¿Qué pide la persona?", audio: "Oye, ¿me dejas tu carro el sábado? Te lo devuelvo el domingo con el tanque lleno.", voice: "es-CO-m", options: ["Que le lleven en carro", "Que le compren un carro", "Que le presten un carro"], answer: 2, why: "_¿Me dejas tu carro?_ = ¿me lo prestas?" },
      { type: "gap", q: "—¿Me prestas tus apuntes? —Sí, ___ ___ mando por correo esta noche.", answers: [["te"], ["los"]], why: "A ti (**te**) + los apuntes (**los**)." },
      { type: "gap", q: "La bici de mi hermana… tengo que ___ (devolver a ella) hoy.", answers: [["devolvérsela"]], hint: "devolver + se + la", why: "Le + la → se la, pegado al infinitivo con tilde: **devolvérsela**." },
      { type: "transform", source: "Le explico el ejercicio a Tomás.", instruction: "Sustituye el ejercicio y a Tomás por pronombres.", answers: ["Se lo explico.", "Se lo explico a Tomás."], why: "Le + lo → **se lo**." },
      { type: "transform", source: "Te voy a mandar las fotos.", instruction: "Pon los pronombres pegados al infinitivo.", answers: ["Voy a mandártelas."], why: "Mandar + te + las = **mandártelas**, con tilde." },
      { type: "order", words: ["¿Nos", "las", "puede", "traer,", "por", "favor?"], why: "Persona (**nos**) + cosa (**las**) delante del verbo conjugado." },
      { type: "error", sentence: "Mi compañera me pidió el diccionario y lo le presté.", answers: ["Mi compañera me pidió el diccionario y se lo presté."], why: "_Le_ + _lo_ no existe: **se lo**, y la persona va primero." },
      { type: "error", sentence: "Ayer presté el paraguas de Juan porque llovía.", answers: ["Ayer le pedí prestado el paraguas a Juan porque llovía.", "Ayer Juan me prestó el paraguas porque llovía.", "Ayer le pedí el paraguas a Juan porque llovía."], why: "El paraguas es de Juan: él te lo **prestó**, o tú se lo **pediste prestado**." },
      { type: "choice", q: "¿Qué palabra está bien escrita?", options: ["dárselo", "darselo", "darsélo"], answer: 0, why: "Infinitivo + dos pronombres → esdrújula → tilde en el verbo: **dárselo**." },
      { type: "gap", q: "De todos los regalos, el reloj era el ___ caro, pero la carta de mi hija era el ___ de todos.", answers: [["más"], ["mejor"]], why: "Repaso: superlativo **el más** + adjetivo; _bueno_ → **el mejor**." },
      { type: "open", prompt: "Pídele a tu jefe o jefa (de usted) que te deje salir antes el viernes y ofrécele algo a cambio. Escribe dos frases.", model: "Disculpe, ¿me deja salir una hora antes el viernes? Le prometo terminar el informe el jueves y se lo mando por la mañana.", checklist: ["Uso usted (_¿me deja…?_, _le prometo_).", "Uso _se lo_ o _se la_.", "Ofrezco algo a cambio."] },
    ],
  },
  complete: {
    canNow: [
      "Decir a quién das algo con me, te, le, nos, os, les.",
      "Combinar dos pronombres en el orden correcto: me lo, te la, se lo.",
      "Pedir algo prestado, ofrecer ayuda, rechazar con cortesía y agradecer un favor.",
      "Pronunciar y escribir palabras como dárselo o prestártela con el acento en su sitio.",
      "Comparar regalos y recordar los que recibías de niño.",
    ],
    review: ["Le / les + lo / la → se lo / se la.", "Prestar ≠ pedir prestado.", "Infinitivo + dos pronombres → tilde.", "Más… que, tan… como, el mejor."],
  },
  related: [
    { path: "/la-estacion-de-los-dos-destinos", label: "La Estación de los Dos Destinos · objeto directo e indirecto" },
  ],
};
