import type { Module } from "../../types";

export const a2w11: Module = {
  id: "a2-11",
  level: "a2",
  week: 11,
  kind: "core",
  title: "Ahora mismo",
  subtitle: "Contar qué está pasando y qué ha cambiado en tu vida: estar + gerundio, empezar a, acabar de, volver a, dejar de y seguir.",
  stop: { place: "Medellín", country: "Colombia" },
  minutes: 80,
  newObjectives: [
    "a2.gram.estar-gerundio",
    "a2.gram.perifrasis-fase",
    "a2.voc.cambios-habitos",
    "a2.pron.asimilacion-nasal",
    "a2.fun.describir-cambios",
    "a2.spk.videollamada",
  ],
  reviewObjectives: [
    "a2.gram.imperativo-afirmativo",
    "a2.gram.imperativo-pronombres",
    "a2.fun.instrucciones",
    "a2.gram.oi-pronombres",
  ],
  prerequisites: ["a2-10"],
  goal: {
    canDo: "Al final de esta semana puedes describir en directo lo que está pasando a tu alrededor (por ejemplo, en una videollamada) y explicar qué has empezado a hacer, qué has dejado de hacer y qué sigues haciendo en tu vida.",
    canDoEn: "By the end of this week, you can describe live what is happening around you (for example, on a video call) and explain what you have started doing, what you have stopped doing and what you are still doing in your life.",
    steps: [
      "Aprende a formar el gerundio (`hablando`, `comiendo`, `leyendo`, `durmiendo`) y a usar **estar + gerundio**.",
      "Coloca los pronombres con el gerundio: `lo estoy haciendo` o `estoy haciéndolo`.",
      "Usa las perífrasis de fase: `empezar a`, `acabar de`, `volver a`, `dejar de` y `seguir + gerundio`.",
      "Entrena la **n** que suena [m]: _un beso_, _con Pablo_, _en Medellín_.",
      "Escucha una videollamada entre Medellín y Ciudad de México.",
      "Graba una descripción en directo de lo que pasa a tu alrededor y cuenta tres cambios de tu vida.",
    ],
  },
  theory: {
    intro: "Esta semana estás en **Medellín**, la ciudad de la eterna primavera: metro, metrocable, montañas y mucha gente que ha cambiado de vida. Para hablar del **ahora** y de los **cambios** necesitas dos herramientas: **estar + gerundio** y cinco perífrasis muy frecuentes.",
    parts: [
      {
        heading: "Estar + gerundio: la acción en curso",
        body: [
          "Con **estar + gerundio** presentas una acción **en desarrollo**, que no ha terminado: **Estoy cocinando** (en este momento, con las manos en la olla). El verbo _estar_ cambia con la persona; el gerundio no cambia nunca.",
          "**Formación.** Los verbos en -ar hacen **-ando**: _hablar → hablando_. Los verbos en -er y en -ir hacen **-iendo**: _comer → comiendo_, _vivir → viviendo_. Si la raíz termina en vocal, la _i_ se convierte en **y**: _leer → leyendo_, _oír → oyendo_, _traer → trayendo_, _construir → construyendo_, _ir → yendo_.",
          "Los verbos en -ir que cambian la vocal en presente (_pido_, _duermo_) también la cambian en el gerundio, pero de otra manera: **e → i** y **o → u**. _Pedir → pidiendo_, _decir → diciendo_, _sentir → sintiendo_, _venir → viniendo_, _seguir → siguiendo_, _dormir → durmiendo_, _morir → muriendo_.",
          "**Dos usos.** (1) Lo que pasa **ahora mismo**: _¿Qué estás haciendo? —Estoy esperando el metro._ (2) Una situación **temporal**, de estos días o de esta época: _Este semestre estoy viviendo en Medellín_; _Estoy trabajando desde casa esta semana_. Compara con el presente simple, que presenta hábitos o situaciones estables: _Trabajo en un banco_ (es mi trabajo) / _Esta semana estoy trabajando desde casa_ (es temporal).",
          "**Cuidado con el inglés.** En español no usamos estar + gerundio para planes futuros: _I'm flying to Bogotá tomorrow_ = **Mañana vuelo a Bogotá** o **Mañana voy a volar a Bogotá**. Tampoco con verbos de estado como _tener_, _ser_ o _saber_: _Tengo dos hermanos_, no «estoy teniendo».",
        ],
        support: [
          "English uses the -ing form much more than Spanish. Use _estar + gerundio_ only for actions in progress now or for temporary situations. For habits use the simple present (_Corro todos los días_), and for future plans use the present or _ir a_ (_Mañana salgo / Mañana voy a salir_).",
          "The gerund never agrees: _Ella está cantando_, _Ellos están cantando_. Only _estar_ changes.",
        ],
        table: {
          caption: "El gerundio",
          head: ["Tipo", "Infinitivo", "Gerundio", "Ejemplo"],
          rows: [
            ["-ar", "hablar, trabajar", "hablando, trabajando", "Está hablando por teléfono."],
            ["-er / -ir", "comer, escribir", "comiendo, escribiendo", "Estamos comiendo arepas."],
            ["vocal + -er/-ir", "leer, oír, traer, ir", "leyendo, oyendo, trayendo, yendo", "¿Me estás oyendo?"],
            ["-ir con e → i", "pedir, decir, sentir, venir", "pidiendo, diciendo, sintiendo, viniendo", "¿Qué estás diciendo?"],
            ["-ir con o → u", "dormir, morir", "durmiendo, muriendo", "El bebé está durmiendo."],
          ],
        },
        examples: [
          { es: "—¿Qué estás haciendo? —Estoy esperando el metro en la estación Poblado.", en: "What are you doing? — I'm waiting for the metro at Poblado station." },
          { es: "Este año estoy estudiando inglés por las noches.", en: "This year I'm studying English in the evenings. (temporary)" },
          { es: "Trabajo en un hospital, pero esta semana estoy trabajando desde casa.", en: "I work in a hospital, but this week I'm working from home." },
          { es: "Mañana viajo a Cartagena.", en: "I'm travelling to Cartagena tomorrow. (plan → simple present)" },
        ],
        mistakes: [
          { wrong: "Estoy leiendo un libro.", right: "Estoy leyendo un libro.", why: "Después de vocal, la _i_ del gerundio se escribe **y**: le**y**endo." },
          { wrong: "Están pediendo la cuenta.", right: "Están pidiendo la cuenta.", why: "_Pedir_ cambia **e → i** en el gerundio: p**i**diendo." },
          { wrong: "Estoy viajando a Bogotá mañana.", right: "Mañana viajo a Bogotá. / Mañana voy a viajar a Bogotá.", why: "Para planes futuros, el español usa el presente o _ir a_, no estar + gerundio." },
          { wrong: "Ella está cansando.", right: "Ella está cansada.", why: "Para un estado se usa estar + **adjetivo** (_cansada_). _Cansando_ es otra cosa: la acción de cansar a alguien." },
        ],
        tip: "Pregunta clave de una videollamada: **¿Qué estás haciendo?** Y la respuesta rápida: **Nada, aquí, descansando.**",
      },
      {
        heading: "Pronombres con el gerundio: dos posiciones",
        body: [
          "Si el verbo lleva un pronombre (_me, te, lo, la, le, nos, les_ o _se_), tienes **dos opciones**, igual de correctas: **antes de estar** o **pegado al gerundio**. _Lo estoy haciendo_ = _Estoy haciéndolo_. _Le estoy escribiendo a mi mamá_ = _Estoy escribiéndole a mi mamá_.",
          "Cuando el pronombre va pegado, la palabra crece y el acento necesita **tilde**: _haciendo → haciéndolo_, _escribiendo → escribiéndole_, _diciendo → diciéndome_. Es la misma regla que ya conoces del imperativo: _compra → cómpralo_, _di → dímelo_.",
          "Lo que **no** es posible es poner el pronombre entre _estar_ y el gerundio: nunca «estoy lo haciendo».",
          "Recuerda el **objeto indirecto** (le, les) para la persona que recibe algo. En español es muy normal repetirlo: _Le estoy mandando una foto **a Diego**_; _Les estoy explicando el camino **a mis papás**_.",
        ],
        support: [
          "Pronouns go either before _estar_ (_Te estoy llamando_) or attached to the end of the gerund (_Estoy llamándote_). Never in the middle.",
          "When you attach a pronoun, add a written accent to keep the stress where it was: _llamando → llamándote_.",
        ],
        table: {
          caption: "Dos posiciones, el mismo significado",
          head: ["Antes de estar", "Pegado al gerundio"],
          rows: [
            ["Lo estoy haciendo.", "Estoy haciéndolo."],
            ["Te estoy llamando.", "Estoy llamándote."],
            ["Le estoy escribiendo a mi abuela.", "Estoy escribiéndole a mi abuela."],
            ["Me estoy duchando.", "Estoy duchándome."],
            ["Se la estoy mostrando.", "Estoy mostrándosela."],
          ],
        },
        examples: [
          { es: "—¿Y el café? —Lo estoy preparando.", en: "And the coffee? — I'm making it." },
          { es: "Espera, estoy buscándote en el mapa.", en: "Wait, I'm looking for you on the map." },
          { es: "Le estoy enviando la ubicación a Camila.", en: "I'm sending the location to Camila." },
        ],
        mistakes: [
          { wrong: "Estoy haciendolo ahora.", right: "Estoy haciéndolo ahora. / Lo estoy haciendo ahora.", why: "Con el pronombre pegado, la palabra lleva tilde: hac**ié**ndolo." },
          { wrong: "Estoy te llamando.", right: "Te estoy llamando. / Estoy llamándote.", why: "El pronombre va antes de _estar_ o pegado al gerundio, nunca en medio." },
        ],
      },
      {
        heading: "Perífrasis de fase: empezar, acabar, volver, dejar, seguir",
        body: [
          "Estas cinco construcciones dicen **en qué fase** está una acción: si empieza, si acaba de pasar, si se repite, si se interrumpe o si continúa. Cada una tiene su preposición fija: apréndelas como bloques.",
          "**Empezar a + infinitivo**: el comienzo. _Empecé a correr en enero._ **Acabar de + infinitivo**: algo que pasó hace muy poco. _Acabo de llegar a casa_ (hace un minuto). **Volver a + infinitivo**: repetir algo. _He vuelto a tocar la guitarra_ (la tocaba antes, la dejé, y ahora otra vez).",
          "**Dejar de + infinitivo**: interrumpir un hábito o una acción. _Dejé de tomar gaseosa._ **Seguir + gerundio**: algo que continúa, que todavía pasa. _Sigo viviendo en Laureles_ (todavía vivo allí). Ojo: _seguir_ va con **gerundio**, sin preposición. Su negativo es **seguir sin + infinitivo**: _Sigo sin entender esta app_.",
          "Con _dejar_ cuidado: **dejar de + verbo** (_dejar de fumar_), pero **dejar + sustantivo** (_dejar el azúcar_, _dejar el trabajo_). Y _ya no_ dice lo mismo que _dejar de_ en presente: _Ya no fumo_ = _He dejado de fumar_.",
        ],
        support: [
          "_empezar a_ = start · _acabar de_ = have just (done) · _volver a_ = do again · _dejar de_ = stop / quit · _seguir + -ando/-iendo_ = keep on / still be doing.",
          "In Spanish the preposition is part of the expression: _empezar **a**_, _dejar **de**_. Only _seguir_ has no preposition and takes the gerund.",
          "In Argentina and Uruguay you'll also hear _recién_ for 'just': _Recién llego_ = _Acabo de llegar_.",
        ],
        table: {
          caption: "Las cinco fases",
          head: ["Perífrasis", "Significado", "Ejemplo"],
          rows: [
            ["empezar a + infinitivo", "comienzo", "Empecé a ir al gimnasio en marzo."],
            ["acabar de + infinitivo", "pasó hace muy poco", "Acabo de terminar la reunión."],
            ["volver a + infinitivo", "otra vez", "Mi hermano ha vuelto a fumar."],
            ["dejar de + infinitivo", "interrupción", "He dejado de comprar ropa nueva."],
            ["seguir + gerundio", "continuación", "Sigo estudiando por las noches."],
            ["seguir sin + infinitivo", "todavía no", "Sigo sin tener carro."],
          ],
        },
        examples: [
          { es: "Acabo de salir de la oficina. Llego en veinte minutos.", en: "I've just left the office. I'll be there in twenty minutes." },
          { es: "Hace dos años dejé de comer carne, pero sigo comiendo pescado.", en: "Two years ago I stopped eating meat, but I still eat fish." },
          { es: "¿Vas a volver a vivir en Bogotá?", en: "Are you going to live in Bogotá again?" },
        ],
        mistakes: [
          { wrong: "Empecé estudiar francés.", right: "Empecé a estudiar francés.", why: "_Empezar_ necesita **a** delante del infinitivo." },
          { wrong: "Sigo trabajar en la misma empresa.", right: "Sigo trabajando en la misma empresa.", why: "_Seguir_ va con **gerundio**, no con infinitivo." },
          { wrong: "Dejé fumar el año pasado.", right: "Dejé de fumar el año pasado.", why: "Delante de un verbo es **dejar de**. Sin _de_, _dejar_ significa abandonar algo o a alguien." },
          { wrong: "Acabo de llegué.", right: "Acabo de llegar.", why: "Después de _acabar de_ va siempre el **infinitivo**." },
        ],
        tip: "Truco para recordar: **a** para empezar y volver (movimiento hacia la acción), **de** para acabar y dejar (salir de la acción).",
      },
      {
        heading: "Contar cambios personales",
        body: [
          "Para explicar cómo ha cambiado tu vida, combina las perífrasis con los tiempos que ya conoces. Con el **pretérito perfecto** hablas de un cambio que todavía es actual: _He empezado a madrugar_. Con el **indefinido** dices cuándo pasó: _En 2023 dejé el trabajo y empecé a estudiar diseño_.",
          "Otras fórmulas útiles: **Ya no** + presente (_Ya no veo tele_), **todavía** + presente (_Todavía me acuesto tarde_), **ahora** + presente (_Ahora camino al trabajo_), **cada vez más / menos** (_Cocino cada vez más en casa_) y **poco a poco** (_Poco a poco estoy aprendiendo a cocinar_).",
          "**Tú, usted y vos en Medellín.** Los paisas usan mucho **usted**, también entre amigos y en familia, y entre amigos jóvenes usan **vos**: _¿Y vos qué estás haciendo? Contame._ Con personas de fuera muchos cambian a **tú**. Las formas de _estar_ con vos son las mismas que con tú: _vos estás_.",
        ],
        support: [
          "_Ya no_ = no longer / not any more. _Todavía_ = still. _Cada vez más_ = more and more.",
          "Colombians use _usted_ even with friends and family; it can sound warm, not only formal.",
        ],
        table: {
          caption: "Antes y ahora",
          head: ["Antes", "Ahora", "Cómo lo cuentas"],
          rows: [
            ["Tomaba tres gaseosas al día.", "No tomo gaseosa.", "He dejado de tomar gaseosa. / Ya no tomo gaseosa."],
            ["No hacía ejercicio.", "Corro tres veces por semana.", "Empecé a correr hace un año."],
            ["Tocaba el piano, luego lo dejé.", "Toco otra vez.", "He vuelto a tocar el piano."],
            ["Vivía con mis papás.", "Vivo con mis papás.", "Sigo viviendo con mis papás."],
          ],
        },
        examples: [
          { es: "Desde que vivo en Medellín, ya no uso el carro: ahora voy en metro.", en: "Since I've lived in Medellín, I don't use the car any more: now I take the metro." },
          { es: "Poco a poco estoy aprendiendo a cocinar comida colombiana.", en: "Little by little I'm learning to cook Colombian food." },
          { es: "Todavía me cuesta madrugar, pero sigo intentándolo.", en: "I still find it hard to get up early, but I keep trying." },
        ],
      },
    ],
  },
  grammar: {
    intro: "Primero, la forma del gerundio; después, los pronombres; al final, las cinco perífrasis.",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "El gerundio correcto",
        prompt: "Elige la forma correcta del gerundio.",
        items: [
          { q: "Shh, el bebé está ___.", options: ["durmiendo", "dormiendo", "duermiendo"], answer: 0, why: "_Dormir_ cambia **o → u** en el gerundio: d**u**rmiendo." },
          { q: "¿Me estás ___? Se corta la llamada.", options: ["oyendo", "oiendo", "oyiendo"], answer: 0, why: "_Oír_: la raíz termina en vocal, así que **-yendo**: o**y**endo." },
          { q: "Mis vecinos están ___ una casa nueva.", options: ["construyendo", "construiendo", "construendo"], answer: 0, why: "_Construir_ → constru**y**endo, como _leer → leyendo_." },
          { q: "¿Qué me estás ___? No te entiendo.", options: ["diciendo", "deciendo", "dicendo"], answer: 0, why: "_Decir_ cambia **e → i**: d**i**ciendo." },
          { q: "Los turistas están ___ fotos en la Comuna 13.", options: ["tomando", "tomiendo", "tomado"], answer: 0, why: "Verbo en -ar → **-ando**. _Tomado_ es el participio (_he tomado_)." },
        ],
      },
      {
        id: "g2",
        type: "gap",
        title: "¿Qué están haciendo?",
        prompt: "Completa con **estar + gerundio** del verbo entre paréntesis.",
        items: [
          { q: "Ahora mismo (yo) ___ en el metrocable. (subir)", answers: [["estoy subiendo"]], why: "Yo → **estoy** + sub**iendo** (-ir → -iendo)." },
          { q: "Mis papás ___ la novela de las ocho. (ver)", answers: [["están viendo"]], why: "Ellos → **están**; _ver_ → v**iendo**." },
          { q: "¿Vos qué ___? (hacer)", answers: [["estás haciendo"]], hint: "vos = tú con estar", why: "Con vos, _estar_ es igual que con tú: **estás** haciendo." },
          { q: "Este mes Natalia ___ en un café de Laureles. (trabajar)", answers: [["está trabajando"]], why: "Situación temporal (_este mes_): **está trabajando**." },
          { q: "¿Ustedes ___ el partido? ¡Va ganando el Nacional! (seguir)", answers: [["están siguiendo"]], why: "_Seguir_ es -ir con e → i: s**i**guiendo. Ustedes → **están**." },
        ],
      },
      {
        id: "g3",
        type: "transform",
        title: "Mueve el pronombre",
        prompt: "Escribe la frase con el pronombre en la otra posición.",
        items: [
          { source: "Lo estoy buscando.", answers: ["Estoy buscándolo."], why: "Pegado al gerundio, con tilde: busc**á**ndolo." },
          { source: "Estoy escribiéndole a Diego.", answers: ["Le estoy escribiendo a Diego."], why: "El pronombre puede ir antes de _estar_; entonces el gerundio pierde la tilde." },
          { source: "Me estoy preparando para salir.", answers: ["Estoy preparándome para salir."], why: "_Preparándome_: la sílaba fuerte sigue siendo **ran**, por eso lleva tilde." },
          { source: "Te estamos esperando en la estación.", answers: ["Estamos esperándote en la estación."], why: "Espe**rán**dote: tres sílabas después del acento, siempre tilde." },
        ],
      },
      {
        id: "g4",
        type: "classify",
        title: "¿Ahora, temporal o hábito?",
        prompt: "Clasifica cada frase según lo que expresa.",
        categories: ["acción en este momento", "situación temporal", "hábito o algo estable"],
        items: [
          { text: "Espera, estoy pagando el taxi.", cat: 0, why: "Pasa en este preciso momento." },
          { text: "Este semestre estoy viviendo con una familia paisa.", cat: 1, why: "_Este semestre_: es temporal, va a terminar." },
          { text: "Trabajo en una empresa de software.", cat: 2, why: "Presente simple: es su trabajo, algo estable." },
          { text: "No puedo hablar, estoy manejando.", cat: 0, why: "Acción en curso ahora." },
          { text: "Estos días estoy durmiendo muy poco.", cat: 1, why: "_Estos días_: un periodo limitado." },
          { text: "Los domingos voy al mercado de San Alejo.", cat: 2, why: "_Los domingos_ + presente simple: costumbre." },
        ],
      },
      {
        id: "g5",
        type: "context",
        title: "¿Qué fase?",
        prompt: "Lee la situación y elige la perífrasis adecuada.",
        items: [
          { context: "Laura llegó a casa hace dos minutos. Su amiga la llama.", q: "Laura dice:", options: ["Acabo de llegar.", "Dejo de llegar.", "Vuelvo a llegar."], answer: 0, why: "Algo que pasó hace muy poco: **acabar de** + infinitivo." },
          { context: "Julián fumaba, lo dejó un año, y ahora fuma otra vez.", q: "Su hermana dice:", options: ["Ha vuelto a fumar.", "Ha dejado de fumar.", "Ha acabado de fumar."], answer: 0, why: "Repetir algo que se había interrumpido: **volver a**." },
          { context: "Hace tres años que Sofía vive en el mismo apartamento.", q: "Sofía dice:", options: ["Sigo viviendo en el mismo apartamento.", "Sigo a vivir en el mismo apartamento.", "Empiezo a vivir en el mismo apartamento."], answer: 0, why: "Continuidad: **seguir + gerundio**, sin preposición." },
          { context: "Antes Martín comía carne todos los días. Desde enero, nada.", q: "Martín dice:", options: ["Dejé de comer carne en enero.", "Dejé comer carne en enero.", "Acabé de comer carne en enero."], answer: 0, why: "Interrumpir un hábito: **dejar de** + infinitivo." },
          { context: "Tomás intenta configurar la app del banco desde ayer. Todavía no puede.", q: "Tomás dice:", options: ["Sigo sin entender esta app.", "Sigo no entendiendo esta app.", "Dejo de entender esta app."], answer: 0, why: "Algo que todavía no pasa: **seguir sin + infinitivo**." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Aprende cada hábito como un bloque completo con su verbo. Así puedes meterlo directamente en una perífrasis: _empecé a **comer sano**_, _he dejado de **acostarme tarde**_.",
    groups: [
      {
        title: "Hábitos que empiezan",
        items: [
          { es: "hacer ejercicio / ir al gimnasio", en: "to exercise / go to the gym" },
          { es: "salir a correr", en: "to go for a run" },
          { es: "madrugar", en: "to get up early" },
          { es: "acostarse temprano", en: "to go to bed early" },
          { es: "comer sano / comer más verduras", en: "to eat healthily / eat more vegetables" },
          { es: "cocinar en casa", en: "to cook at home" },
          { es: "meditar diez minutos al día", en: "to meditate ten minutes a day" },
          { es: "ir al trabajo en bici", en: "to cycle to work", note: "En Colombia también: _montar en cicla_. En México: _andar en bici_." },
          { es: "ahorrar un poco cada mes", en: "to save a little every month" },
        ],
      },
      {
        title: "Hábitos que se dejan",
        items: [
          { es: "dejar de fumar", en: "to quit smoking" },
          { es: "dejar el azúcar / la gaseosa", en: "to give up sugar / fizzy drinks", note: "_Gaseosa_ en Colombia y Argentina; _refresco_ en México y España." },
          { es: "acostarse tarde", en: "to go to bed late" },
          { es: "pasar horas con el celular", en: "to spend hours on the phone", note: "_El móvil_ en España." },
          { es: "pedir comida a domicilio", en: "to order food delivery" },
          { es: "comprar cosas que no necesito", en: "to buy things I don't need" },
          { es: "trabajar los fines de semana", en: "to work at weekends" },
        ],
      },
      {
        title: "Cómo cuentas el cambio",
        items: [
          { es: "Ya no…", en: "Not any more…" },
          { es: "Todavía…", en: "Still…" },
          { es: "Cada vez más / cada vez menos", en: "More and more / less and less" },
          { es: "Poco a poco…", en: "Little by little…" },
          { es: "Me cuesta + infinitivo", en: "I find it hard to…" },
          { es: "Desde que…", en: "Since…" },
          { es: "¡Por fin!", en: "At last!" },
          { es: "Me siento mucho mejor.", en: "I feel much better." },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "Antes y ahora",
        prompt: "Une cada situación con la frase que la resume.",
        pairs: [
          { left: "Antes me levantaba a las nueve; ahora, a las cinco y media.", right: "He empezado a madrugar." },
          { left: "Antes pedía pizza tres veces por semana; ahora cocino.", right: "He dejado de pedir comida a domicilio." },
          { left: "Corría en la universidad, lo dejé y este año corro otra vez.", right: "He vuelto a salir a correr." },
          { left: "Hace cinco años que voy al trabajo en bici y todavía lo hago.", right: "Sigo yendo al trabajo en bici." },
          { left: "La sesión de meditación terminó hace un minuto.", right: "Acabo de meditar con mi grupo." },
        ],
        why: "Cada perífrasis marca una fase: empezar (comienzo), dejar de (interrupción), volver a (repetición), seguir (continuación), acabar de (pasado inmediato).",
      },
      {
        id: "v2",
        type: "gap",
        title: "La nueva vida de Mauricio",
        prompt: "Completa con las palabras del banco. Sobra una.",
        bank: ["madrugar", "gaseosa", "celular", "ahorrar", "cicla", "a domicilio", "temprano"],
        items: [
          { q: "Desde que tengo trabajo nuevo, me levanto a las cinco: he empezado a ___.", answers: [["madrugar"]], why: "_Madrugar_ = levantarse muy temprano." },
          { q: "Ya no tomo ___: ahora prefiero jugo de lulo o agua.", answers: [["gaseosa"]], why: "_Gaseosa_ = bebida con gas (refresco)." },
          { q: "Voy a la oficina en ___ por la ciclorruta de la avenida.", answers: [["cicla"]], why: "_Cicla_ es la palabra colombiana para bicicleta." },
          { q: "Antes pedía comida ___ todas las noches; ahora cocino.", answers: [["a domicilio"]], why: "_Pedir a domicilio_ = que te traigan la comida a casa." },
          { q: "Por las noches dejo el ___ en la cocina para dormir mejor.", answers: [["celular"]], why: "_El celular_ (América) = _el móvil_ (España)." },
          { q: "Quiero ___ un poco cada mes para viajar a Cartagena.", answers: [["ahorrar"]], why: "_Ahorrar_ = guardar dinero." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "La n que suena [m]: un beso, con Pablo, en Medellín",
    explanation: [
      "En español, la **n** se adapta al sonido que viene después. Delante de **b**, **v**, **p** y **m**, los labios ya se preparan para cerrar, y la n suena **[m]**: _un beso_ suena «um beso», _con Pablo_ suena «com Pablo», _un vaso_ suena «um vaso», _en Medellín_ suena «em Medellín». Esto se llama **asimilación**.",
      "Pasa dentro de una palabra y también entre dos palabras: _envío_ [embío], _invierno_ [imbierno], _inmenso_ [immenso], _sin problema_ [sim problema], _un momento_ [um momento]. No es un acento regional ni hablar mal: lo hacen todos los hispanohablantes, en todos los países.",
      "Recuerda que **b** y **v** suenan igual en español. Por eso _un vaso_ y _un barco_ tienen la misma [m]: um vaso, um barco.",
      "Delante de **c, k, g, j** (sonidos del fondo de la boca) la n también se mueve hacia atrás: _tengo_, _un gato_, _blanco_. Y en la costa caribe de Colombia, en Venezuela y en otras zonas, la n **final** (pan, también) suena muy atrás, casi como la _ng_ de _sing_. En Medellín no es tan fuerte, pero lo vas a oír en muchos lugares.",
    ],
    support: [
      "Before _b, v, p, m_, close your lips and the _n_ becomes an _m_ sound: _un beso_ sounds like 'um beso'. Don't try to say a clear 'n' and then open your lips again: it sounds slow and foreign.",
      "This is why Spanish spelling has _m_ before _p_ and _b_ inside words (_campo, hombre, también_). Between words the spelling keeps _n_, but the sound is still [m].",
    ],
    table: {
      head: ["Contexto", "Se escribe", "Suena"],
      rows: [
        ["dentro de la palabra (m + p/b)", "campo, también, hombre", "[m]: cam-po, tam-bién"],
        ["dentro de la palabra (n + v/m)", "envío, invierno, inmenso", "[m]: em-ví-o, im-vier-no"],
        ["entre palabras", "un beso, con Pablo, en Medellín", "[m]: um beso, com Pablo"],
        ["n + vocal, d, t, s", "un amigo, con Diego, en serio", "[n] normal"],
      ],
    },
    perceive: {
      id: "p1",
      type: "classify",
      title: "¿[m] o [n]?",
      prompt: "Escucha cada grupo. ¿La n marcada suena [m] (labios cerrados) o [n] normal?",
      categories: ["suena [m]", "suena [n]"],
      items: [
        { text: "u**n** beso", audio: "un beso", cat: 0, why: "N + b: los labios se cierran: um beso." },
        { text: "u**n** amigo", audio: "un amigo", cat: 1, why: "N + vocal: n normal, se une a la vocal: u-na-mi-go." },
        { text: "co**n** Pablo", audio: "con Pablo", cat: 0, why: "N + p: com Pablo." },
        { text: "e**n** Medellín", audio: "en Medellín", cat: 0, why: "N + m: em Medellín." },
        { text: "co**n** Diego", audio: "con Diego", cat: 1, why: "N + d: la lengua ya está en los dientes, la n no cambia." },
        { text: "u**n** vaso", audio: "un vaso", cat: 0, why: "La v suena [b]: um vaso." },
        { text: "si**n** problema", audio: "sin problema", cat: 0, why: "N + p: sim problema." },
        { text: "e**n** serio", audio: "en serio", cat: 1, why: "N + s: n normal." },
      ],
    },
    produce: [
      { text: "un beso · un vaso · un momento", tip: "Cierra los labios en la n: **um** beso. No hay pausa entre las dos palabras." },
      { text: "Estoy en Medellín con Pablo.", tip: "Dos [m]: _e**m** Medellín_, _co**m** Pablo_. Dilo como una sola cadena." },
      { text: "Un momento, que estoy comiendo.", tip: "_U**m** momento_: una m un poco más larga. En _comiendo_ la n va antes de d: [n] normal." },
      { text: "Envíame un mensaje, sin problema.", tip: "_E**m**víame_, _u**m** mensaje_, _si**m** problema_. Tres asimilaciones en una frase de videollamada." },
      { text: "Con mucho gusto, vecino.", tip: "Respuesta muy colombiana a _gracias_. _Co**m** mucho_: labios cerrados." },
    ],
    spelling: "Dentro de una palabra se escribe **m** antes de **p** y **b** (_campo, cambio, siempre_) y **n** antes de **v** (_enviar, invitar, convencer_), aunque las dos suenan [m].",
  },
  listening: {
    title: "Videollamada Medellín–Ciudad de México",
    context: "Camila vive en Medellín. Su amigo mexicano Diego la llama por videollamada un sábado por la tarde. Hace un año que no hablan. Andrés, el hermano de Camila, también aparece en la llamada.",
    speakers: [
      { id: "camila", name: "Camila", voice: "es-CO-f", role: "diseñadora, vive en Medellín" },
      { id: "diego", name: "Diego", voice: "es-MX-m", role: "amigo de Camila, vive en Ciudad de México" },
      { id: "andres", name: "Andrés", voice: "es-CO-m", role: "hermano de Camila" },
    ],
    script: [
      { speaker: "diego", text: "¡Camila! ¿Me ves? ¿Me estás oyendo?" },
      { speaker: "camila", text: "¡Diego! Sí, te oigo, pero espera un momento, que estoy subiendo en el metrocable y se corta un poco." },
      { speaker: "diego", text: "¿En el metrocable? ¿Y adónde vas?" },
      { speaker: "camila", text: "Voy al Parque Arví. Mira, te muestro: estamos pasando por encima de las casas y allá abajo se ve toda la ciudad." },
      { speaker: "diego", text: "¡Qué bonito! Yo acabo de llegar a casa. Estoy preparando la comida: chilaquiles, como siempre." },
      { speaker: "camila", text: "¿Y qué es de tu vida? Hace un año que no hablamos." },
      { speaker: "diego", text: "Pues muchas cosas. Dejé el trabajo en el banco y empecé a dar clases de música. Y he vuelto a tocar la guitarra todos los días." },
      { speaker: "camila", text: "¡Qué chévere! Yo sigo trabajando desde casa, pero ahora madrugo: empecé a salir a correr a las seis." },
      { speaker: "diego", text: "¿Tú, a las seis? ¡No te creo!" },
      { speaker: "camila", text: "En serio. Y dejé de tomar gaseosa. Me siento mucho mejor." },
      { speaker: "andres", text: "Camila, ¿con quién estás hablando? Pasame el cargador, que me quedo sin batería." },
      { speaker: "camila", text: "Con Diego, mi amigo de México. Tomá, aquí está. Andrés, saludalo." },
      { speaker: "andres", text: "¡Quiubo, Diego! Mucho gusto. Oiga, muéstrenos la cocina, que Camila dice que usted cocina muy bien." },
      { speaker: "diego", text: "¡Claro! Miren: aquí estoy friendo las tortillas y la salsa verde ya está lista." },
      { speaker: "camila", text: "Diego, mándame la receta por WhatsApp, ¿sí? Y llámame la otra semana, que ya estoy llegando al parque." },
      { speaker: "diego", text: "Te la mando hoy mismo. ¡Un beso, Cami!" },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: no busques detalles. Imagina la escena.",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha toda la videollamada y responde.",
          items: [
            { q: "¿Dónde está Camila durante la llamada?", options: ["En el metrocable, camino de un parque", "En su casa, en la cocina", "En el metro, camino del trabajo"], answer: 0, why: "Dice: _Estoy subiendo en el metrocable_ y _Voy al Parque Arví_." },
            { q: "¿De qué hablan sobre todo?", options: ["De los cambios en su vida durante el último año", "De un viaje que van a hacer juntos", "De un problema con la conexión"], answer: 0, why: "Camila pregunta _¿Qué es de tu vida?_ y los dos cuentan qué han empezado y qué han dejado." },
            { q: "¿Cómo termina la llamada?", options: ["Camila llega al parque y se despiden.", "Se corta la conexión.", "Andrés termina la llamada."], answer: 0, why: "Camila dice _ya estoy llegando al parque_ y Diego se despide con _Un beso_." },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: atención a lo que hace cada uno y a los cambios.",
        exercise: {
          id: "l2",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "¿Qué está haciendo Diego cuando habla con Camila?", options: ["Está preparando la comida.", "Está tocando la guitarra.", "Está dando una clase."], answer: 0, why: "_Acabo de llegar a casa. Estoy preparando la comida_." },
            { q: "¿Qué cambio ha hecho Diego en su trabajo?", options: ["Dejó el banco y empezó a dar clases de música.", "Empezó a trabajar en un banco.", "Sigue en el banco y da clases los sábados."], answer: 0, why: "_Dejé el trabajo en el banco y empecé a dar clases de música_." },
            { q: "¿Qué hace ahora Camila a las seis de la mañana?", options: ["Sale a correr.", "Empieza a trabajar.", "Toma el metrocable."], answer: 0, why: "_Empecé a salir a correr a las seis_." },
            { q: "¿Qué ha dejado Camila?", options: ["la gaseosa", "el trabajo desde casa", "el café"], answer: 0, why: "_Dejé de tomar gaseosa_. El trabajo desde casa lo **sigue** haciendo." },
            { q: "¿Qué le pide Andrés a Camila?", options: ["el cargador", "el celular", "la receta"], answer: 0, why: "_Pasame el cargador, que me quedo sin batería_." },
            { q: "¿Qué le pide Camila a Diego al final?", options: ["Que le mande la receta y la llame la otra semana", "Que le muestre la cocina", "Que toque la guitarra"], answer: 0, why: "_Mándame la receta por WhatsApp_ y _llámame la otra semana_. La cocina la pide Andrés." },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en las formas verbales de cada frase.",
        exercise: {
          id: "l3",
          type: "classify",
          prompt: "¿Qué hace cada frase?",
          categories: ["describe lo que pasa ahora", "cuenta un cambio", "pide algo (imperativo)"],
          items: [
            { text: "Estamos pasando por encima de las casas.", cat: 0, why: "Estar + gerundio: lo que Camila ve en este momento." },
            { text: "Aquí estoy friendo las tortillas.", cat: 0, why: "_Freír_ → _friendo_: acción en curso en la cocina de Diego." },
            { text: "He vuelto a tocar la guitarra.", cat: 1, why: "_Volver a_: un hábito que regresa." },
            { text: "Dejé de tomar gaseosa.", cat: 1, why: "_Dejar de_: un hábito que se interrumpe." },
            { text: "Pasame el cargador.", cat: 2, why: "Imperativo de **vos** (paisa) con pronombre pegado: _pasá + me_." },
            { text: "Muéstrenos la cocina.", cat: 2, why: "Imperativo de **usted** con pronombre: _muestre + nos_. Andrés trata a Diego de usted, muy colombiano." },
            { text: "Mándame la receta por WhatsApp.", cat: 2, why: "Imperativo de **tú** + me: Camila habla de tú con su amigo mexicano." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Un año en Medellín: lo que ha cambiado",
    genre: "Publicación de blog personal",
    frame: "Andreína es venezolana. Hace un año se mudó de Caracas a Medellín y escribe un blog sobre su nueva vida.",
    text: [
      "Hoy hace exactamente un año que llegué a Medellín con dos maletas y mucho miedo. Estoy escribiendo esto en un café de Laureles, con un tinto y la lluvia de la tarde en la ventana. ¿Qué ha cambiado en este año? Casi todo.",
      "Lo primero: el transporte. En Caracas iba a todas partes en carro. Aquí he dejado de manejar: voy en metro y, los domingos, cuando cierran la avenida, monto en cicla con mi vecina Luz Marina. Al principio me costaba mucho, pero poco a poco le he cogido el gusto.",
      "También he empezado a madrugar. Los paisas se levantan tempranísimo y yo, que antes me acostaba a las dos de la mañana, ahora me acuesto a las diez. ¿El resultado? Duermo mejor y estoy de mejor humor.",
      "Hay cosas que sigo haciendo: sigo cocinando arepas venezolanas los sábados (las colombianas son distintas, ¡no empiecen esa discusión!) y sigo llamando a mi mamá todos los días. Y hay cosas que he vuelto a hacer: después de diez años, he vuelto a pintar.",
      "Lo que sigo sin entender es el clima: sol por la mañana, aguacero por la tarde. Si vienes a Medellín, mi consejo es este: lleva siempre un paraguas, pruébalo todo y dile que sí a cada invitación. Ahora mismo me estoy tomando el último sorbo de tinto. Les cuento más la próxima semana.",
    ],
    glossary: [
      { es: "un tinto", en: "a small black coffee (Colombia)" },
      { es: "monto en cicla", en: "I ride a bike (Colombia)" },
      { es: "cogerle el gusto a algo", en: "to start to enjoy something" },
      { es: "un aguacero", en: "a downpour" },
      { es: "un sorbo", en: "a sip" },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee el blog y responde.",
        items: [
          { q: "¿Cuál es la idea principal del texto?", options: ["Andreína explica cómo ha cambiado su vida en un año en Medellín.", "Andreína compara las arepas de Venezuela y Colombia.", "Andreína da consejos para encontrar trabajo en Medellín."], answer: 0, why: "Ella misma lo dice: _¿Qué ha cambiado en este año? Casi todo_." },
          { q: "¿Dónde está Andreína mientras escribe?", options: ["En un café de Laureles", "En su apartamento", "En el metro"], answer: 0, why: "_Estoy escribiendo esto en un café de Laureles_." },
          { q: "¿Por qué ahora duerme mejor?", options: ["Porque se acuesta más temprano", "Porque ya no toma café", "Porque ya no maneja"], answer: 0, why: "_Ahora me acuesto a las diez. ¿El resultado? Duermo mejor_." },
          { q: "¿Qué consejo NO da a los visitantes?", options: ["Ir en carro a todas partes", "Llevar paraguas", "Aceptar las invitaciones"], answer: 0, why: "Aconseja _lleva siempre un paraguas, pruébalo todo y dile que sí a cada invitación_. El carro lo ha dejado ella." },
        ],
      },
      {
        id: "r2",
        type: "classify",
        prompt: "Según el texto, ¿qué ha pasado con cada hábito de Andreína?",
        categories: ["lo empezó", "lo dejó", "lo sigue haciendo", "lo volvió a hacer"],
        items: [
          { text: "manejar", cat: 1, why: "_He dejado de manejar_." },
          { text: "madrugar", cat: 0, why: "_He empezado a madrugar_." },
          { text: "cocinar arepas venezolanas", cat: 2, why: "_Sigo cocinando arepas venezolanas los sábados_." },
          { text: "pintar", cat: 3, why: "_Después de diez años, he vuelto a pintar_." },
          { text: "llamar a su mamá", cat: 2, why: "_Sigo llamando a mi mamá todos los días_." },
          { text: "montar en cicla los domingos", cat: 0, why: "Es algo nuevo en Medellín, con su vecina." },
        ],
      },
    ],
    noticing: {
      prompt: "Mira cómo Andreína usa el lenguaje de la semana.",
      items: [
        { quote: "Estoy escribiendo esto en un café", note: "Estar + gerundio para lo que pasa mientras escribe: el lector la ve en la escena." },
        { quote: "he dejado de manejar", note: "Perfecto + _dejar de_: un cambio que sigue vigente hoy." },
        { quote: "sigo cocinando arepas", note: "_Seguir_ + gerundio, sin preposición." },
        { quote: "Lo que sigo sin entender es el clima", note: "_Seguir sin_ + infinitivo = todavía no entiendo." },
        { quote: "lleva siempre un paraguas, pruébalo todo y dile que sí", note: "Imperativos de tú para dar consejos; _pruébalo_ y _dile_ llevan el pronombre pegado." },
        { quote: "me estoy tomando el último sorbo", note: "El pronombre antes de _estar_. También es posible: _estoy tomándome_." },
      ],
    },
  },
  practice: {
    intro: "Combina estar + gerundio, las perífrasis y los imperativos de las semanas anteriores.",
    exercises: [
      {
        id: "x1",
        type: "transform",
        title: "Resume el cambio",
        prompt: "Resume cada situación en una frase con la perífrasis indicada (en pretérito perfecto o indefinido).",
        items: [
          { source: "Antes Valeria no hacía yoga. Ahora hace yoga los martes. (empezar a)", answers: ["Valeria ha empezado a hacer yoga.", "Valeria empezó a hacer yoga.", "Ha empezado a hacer yoga.", "Empezó a hacer yoga."], why: "Comienzo de un hábito: **empezar a** + infinitivo." },
          { source: "Antes yo trabajaba los sábados. Ahora no. (dejar de)", answers: ["He dejado de trabajar los sábados.", "Dejé de trabajar los sábados.", "Yo he dejado de trabajar los sábados.", "Yo dejé de trabajar los sábados."], why: "Interrupción: **dejar de** + infinitivo." },
          { source: "Mis tíos vivían en Envigado hace diez años y todavía viven allí. (seguir)", answers: ["Mis tíos siguen viviendo en Envigado.", "Siguen viviendo en Envigado."], why: "Continuidad: **seguir + gerundio**. Aquí usamos el presente: todavía pasa." },
          { source: "Pedro estudió alemán, lo dejó y este año estudia alemán otra vez. (volver a)", answers: ["Pedro ha vuelto a estudiar alemán.", "Pedro volvió a estudiar alemán.", "Ha vuelto a estudiar alemán.", "Volvió a estudiar alemán."], why: "Repetición después de una pausa: **volver a**." },
        ],
      },
      {
        id: "x2",
        type: "error",
        title: "Detective de errores",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "Ahora mismo estoy duchandome, te llamo después.", answers: ["Ahora mismo estoy duchándome, te llamo después.", "Ahora mismo me estoy duchando, te llamo después."], why: "Gerundio + pronombre pegado lleva tilde: duch**á**ndome." },
          { sentence: "Mi abuela sigue a trabajar en la tienda.", answers: ["Mi abuela sigue trabajando en la tienda."], why: "_Seguir_ va con gerundio y sin preposición." },
          { sentence: "Estoy saliendo para Cartagena el viernes que viene.", answers: ["Salgo para Cartagena el viernes que viene.", "Voy a salir para Cartagena el viernes que viene."], why: "Un plan futuro no va con estar + gerundio: presente o _ir a_." },
          { sentence: "Los niños están dormiendo en el cuarto.", answers: ["Los niños están durmiendo en el cuarto."], why: "_Dormir_ cambia o → u en el gerundio: d**u**rmiendo." },
          { sentence: "¿Le estás escribiendo a tus papás?", answers: ["¿Les estás escribiendo a tus papás?", "¿Estás escribiéndoles a tus papás?"], why: "Objeto indirecto plural (_a tus papás_): **les**." },
        ],
      },
      {
        id: "x3",
        type: "gap",
        title: "Instrucciones por videollamada",
        prompt: "Tu abuela no sabe usar la videollamada. Completa las instrucciones con el **imperativo de usted** y el pronombre pegado cuando lo hay.",
        items: [
          { q: "Abuela, ___ el celular con las dos manos. (coger)", answers: [["coja", "agarre"]], why: "Imperativo de usted de _coger_: **coja** (en Colombia también _agarre_)." },
          { q: "Ahora ___ el botón verde. (tocar)", answers: [["toque"]], why: "_Tocar_ → **toque** (c → qu delante de e)." },
          { q: "No la veo bien. ___ la cámara, por favor. (subir, la)", answers: [["Súbala"]], why: "Usted: _suba_ + _la_ → **Súbala**, con tilde." },
          { q: "¡Ya la veo! ___ qué está haciendo. (decir, me)", answers: [["Dígame"]], why: "_Diga_ + _me_ → **Dígame**." },
          { q: "___ a mi tía que la estoy esperando en línea. (decir, le)", answers: [["Dígale"]], why: "_Diga_ + _le_ (a mi tía) → **Dígale**." },
        ],
      },
      {
        id: "x4",
        type: "order",
        title: "Frases de la semana",
        prompt: "Ordena las palabras.",
        items: [
          { words: ["Te", "estoy", "mandando", "la", "ubicación."], alt: ["Estoy mandándote la ubicación."], en: "I'm sending you the location.", why: "Pronombre antes de _estar_ + gerundio." },
          { words: ["Hace", "un", "año", "dejé", "de", "fumar."], alt: ["Dejé de fumar hace un año."], en: "I quit smoking a year ago.", why: "_Dejar de_ + infinitivo; _hace un año_ puede ir al principio o al final." },
          { words: ["Sigo", "sin", "entender", "el", "metro."], en: "I still don't understand the metro.", why: "_Seguir sin_ + infinitivo." },
          { words: ["¿Qué", "estás", "haciendo", "ahora", "mismo?"], alt: ["¿Ahora mismo qué estás haciendo?"], en: "What are you doing right now?", why: "Pregunta típica de videollamada." },
        ],
      },
      {
        id: "x5",
        type: "open",
        title: "Escritura guiada: mensajes cortos",
        prompt: "Escribe respuestas breves (2–3 frases) con el lenguaje de la semana.",
        items: [
          {
            prompt: "Un amigo te escribe: «¿Qué estás haciendo? ¿Puedes hablar?». Responde: di qué estás haciendo y cuándo puedes llamarlo.",
            model: "Ahora no puedo, estoy haciendo la compra en el supermercado. Acabo de entrar. Te llamo en media hora, ¿vale?",
            checklist: ["Usas estar + gerundio para lo que haces ahora.", "Añades un detalle con _acabar de_ o _seguir_.", "Propones un momento para hablar."],
          },
          {
            prompt: "Escribe tres frases sobre tu vida este año: algo que has empezado a hacer, algo que has dejado de hacer y algo que sigues haciendo.",
            model: "Este año he empezado a ir al trabajo en bici. He dejado de pedir comida a domicilio. Sigo viviendo en el mismo barrio, pero ahora conozco a mis vecinos.",
            checklist: ["Usas _empezar a_ y _dejar de_ con infinitivo.", "Usas _seguir_ + gerundio, sin preposición.", "Los hábitos son concretos (con verbo + complemento)."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe un mensaje a un amigo o una amiga que no ves desde hace un año: cuéntale qué estás haciendo en este momento y qué ha cambiado en tu vida.",
    context: "Encontraste una foto antigua con esta persona y decides escribirle por WhatsApp o por correo.",
    steps: [
      "Saluda y explica por qué escribes (la foto).",
      "Di qué estás haciendo ahora mismo y dónde estás.",
      "Cuenta dos o tres cambios: algo que empezaste, algo que dejaste, algo que volviste a hacer.",
      "Di una cosa que sigues haciendo igual.",
      "Termina con una petición en imperativo (llámame, cuéntame, mándame…).",
    ],
    useLanguage: ["Ahora mismo estoy…", "Este año estoy…", "He empezado a / Empecé a…", "He dejado de…", "He vuelto a…", "Sigo + gerundio", "Ya no… / Todavía…", "Cuéntame / Llámame / Mándame…"],
    model: [
      "¡Hola, Lucía! Estoy ordenando mi cuarto y acabo de encontrar una foto de nosotras en Guatapé. ¡Qué recuerdos!",
      "Te cuento: este año estoy viviendo en Medellín por trabajo. He dejado de manejar, ahora voy en metro a todas partes. También he empezado a ir a clases de salsa los jueves y he vuelto a leer novelas antes de dormir. Lo que no cambia: sigo tomando demasiado café.",
      "¿Y tú? ¿Sigues en Valencia? Cuéntame qué estás haciendo y mándame una foto de tu nueva casa. ¡Un abrazo!",
    ],
    checklist: [
      "Usas estar + gerundio al menos dos veces (ahora y situación temporal).",
      "Usas al menos tres perífrasis distintas con su preposición correcta.",
      "_Seguir_ va con gerundio.",
      "Terminas con un imperativo con pronombre pegado (cuéntame, mándame…).",
      "Revisas las tildes de los gerundios con pronombre.",
    ],
    words: [70, 110],
  },
  speaking: {
    intro: "Habla sin leer. Primero prepara con las notas, después tapa la pantalla y grábate.",
    tasks: [
      {
        title: "En directo: ¿qué está pasando?",
        prompt: "Imagina que estás en una videollamada. Mira a tu alrededor (o por la ventana) y describe en directo lo que está pasando: qué estás haciendo tú, qué hacen otras personas, qué se oye.",
        prep: ["Ahora mismo estoy…", "En la calle hay una señora que está…", "Se oye a alguien que está…", "Mi gato / mi compañero está…", "Espera, que…"],
        seconds: 45,
        model: "Ahora mismo estoy sentada en el balcón. Abajo, en la calle, un señor está vendiendo mangos y dos niños están jugando fútbol. Mi vecina está regando las plantas y se oye a alguien que está escuchando salsa. Espera, que está empezando a llover… ¡Sí, está lloviendo!",
        selfCheck: ["Uso al menos cinco gerundios distintos.", "Uno las frases con _y_, _mientras_, _espera, que…_", "Pronuncio _un momento_, _en el balcón_ con [m] donde toca."],
      },
      {
        title: "Mi vida ha cambiado",
        prompt: "Cuenta tres cambios reales de tu vida en los últimos años y una cosa que sigues haciendo igual.",
        prep: ["Hace… empecé a…", "He dejado de…", "He vuelto a…", "Pero sigo…", "Me siento…"],
        seconds: 60,
        model: "Hace dos años empecé a trabajar desde casa y mi vida cambió mucho. He dejado de pasar dos horas en el tráfico y ahora cocino en casa. También he vuelto a nadar, como cuando era niño. Pero sigo acostándome demasiado tarde: eso no cambia. En general, me siento mucho mejor.",
        selfCheck: ["Cada perífrasis tiene su preposición (a, de) o el gerundio con _seguir_.", "Digo cuándo empezó un cambio (_hace…_, _en 2022_…).", "Termino con una valoración."],
      },
      {
        title: "Ayuda técnica",
        prompt: "Tu tío te llama por videollamada y no te ve. Dale instrucciones de usted para arreglar la cámara y el sonido.",
        prep: ["Mire la pantalla…", "Toque el botón de…", "Súbale el volumen…", "Póngase cerca de la ventana…", "Dígame si me oye."],
        seconds: 40,
        model: "Tío, mire la pantalla. Abajo hay un botón con una cámara: tóquelo. ¡Ya lo veo! Ahora súbale el volumen al celular, el botón está al lado. Póngase cerca de la ventana, que está muy oscuro. Perfecto. Dígame, ¿me oye bien?",
        selfCheck: ["Uso imperativos de usted (_mire, toque, póngase_).", "Pego los pronombres y pongo tilde: _tóquelo, dígame_.", "Doy los pasos en orden."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo, la clase misma es una videollamada: úsala para practicar.",
    cards: [
      { move: "Describe", task: "Al empezar, describe en directo lo que está pasando donde estás tú (ruido, personas, tiempo) y pregunta qué está pasando donde está tu profesor o profesora.", phrases: ["Aquí está lloviendo…", "Mi vecino está…", "¿Y allá qué está pasando?"] },
      { move: "Cuenta", task: "Cuenta un cambio de tu vida de este año con dos perífrasis distintas.", phrases: ["Este año he empezado a…", "He dejado de…", "Sigo + gerundio…"] },
      { move: "Pregunta", task: "Hazle tres preguntas a tu profesor o profesora sobre sus cambios de hábitos y reacciona a cada respuesta.", phrases: ["¿Has empezado a…?", "¿Sigues…?", "¿Has vuelto a…?", "¡Qué bien! / ¡No me digas!"] },
      { move: "Dirige", task: "Pídele que te muestre algo de su casa o de su mesa con imperativos y pronombres.", phrases: ["Muéstrame…", "Acércalo a la cámara.", "Dime qué es."] },
    ],
    bring: "Una foto de hace unos años: vas a explicar qué ha cambiado y qué sigue igual.",
  },
  quiz: {
    items: [
      { type: "choice", q: "—¿Puedes hablar? —Ahora no, ___ la cena.", options: ["estoy haciendo", "hago", "estoy hecho"], answer: 0, why: "Acción en curso ahora mismo: **estar + gerundio**." },
      { type: "choice", q: "¿Cuál es el gerundio de _traer_?", options: ["trayendo", "traiendo", "trajendo"], answer: 0, why: "Raíz terminada en vocal → **-yendo**: tra**y**endo." },
      { type: "listen", q: "Escucha el audio de tu amiga: ¿qué te dice?", audio: "Acabo de salir del gimnasio, te llamo en diez minutos.", voice: "es-CO-m", options: ["Salió del gimnasio hace muy poco.", "Va a ir al gimnasio en diez minutos.", "Ha dejado de ir al gimnasio."], answer: 0, why: "_Acabo de salir_ = salí hace un momento." },
      { type: "listen", q: "¿Qué ha cambiado en la vida de esta persona?", audio: "Desde enero ya no como dulces, pero sigo tomando mucho café.", voice: "es-AR-f", options: ["Dejó los dulces, pero no el café.", "Dejó el café y los dulces.", "Empezó a tomar café en enero."], answer: 0, why: "_Ya no como dulces_ (lo dejó) / _sigo tomando café_ (continúa)." },
      { type: "gap", q: "En enero mi hermana empezó ___ estudiar inglés y dejó ___ estudiar francés.", answers: [["a"], ["de"]], why: "**Empezar a** + infinitivo; **dejar de** + infinitivo." },
      { type: "gap", q: "Llevo tres años en Medellín y ___ trabajando en el mismo hospital. (seguir, yo)", answers: [["sigo"]], why: "_Seguir_ (e → i): yo **sigo**, + gerundio." },
      { type: "transform", source: "Les estoy explicando el camino.", instruction: "Pon el pronombre detrás del gerundio.", answers: ["Estoy explicándoles el camino."], why: "Pegado al gerundio, con tilde: explic**á**ndoles." },
      { type: "transform", source: "Antes Ana tocaba el violín. Lo dejó. Ahora toca otra vez.", instruction: "Resume con _volver a_ en pretérito perfecto.", answers: ["Ana ha vuelto a tocar el violín.", "Ha vuelto a tocar el violín."], why: "Repetir algo después de una pausa: **volver a** + infinitivo." },
      { type: "order", words: ["Estoy", "esperándote", "en", "la", "estación", "Poblado."], why: "Gerundio con pronombre pegado: _esperándote_." },
      { type: "error", sentence: "Dejé tomar café porque no podía dormir.", answers: ["Dejé de tomar café porque no podía dormir."], why: "Delante de un infinitivo: **dejar de**." },
      { type: "error", sentence: "Mis primos están viniendo a visitarme el próximo mes.", answers: ["Mis primos vienen a visitarme el próximo mes.", "Mis primos van a venir a visitarme el próximo mes."], why: "Plan futuro: presente o _ir a_, no estar + gerundio." },
      { type: "error", sentence: "Un momento, estoy lo buscando.", answers: ["Un momento, lo estoy buscando.", "Un momento, estoy buscándolo."], why: "El pronombre va antes de _estar_ o pegado al gerundio, nunca en medio." },
      { type: "open", prompt: "Estás en una videollamada con tu profesor. Escribe 3 frases: qué estás haciendo ahora, algo que acabas de hacer y algo que has dejado de hacer este año.", model: "Ahora estoy tomando un té en la cocina. Acabo de volver del trabajo. Este año he dejado de comer carne roja.", checklist: ["estar + gerundio", "acabar de + infinitivo", "dejar de + infinitivo"] },
    ],
  },
  complete: {
    canNow: [
      "Describir lo que está pasando ahora mismo y situaciones temporales con estar + gerundio.",
      "Formar gerundios regulares e irregulares (_leyendo_, _pidiendo_, _durmiendo_) y colocar los pronombres.",
      "Contar cambios con _empezar a_, _acabar de_, _volver a_, _dejar de_ y _seguir_ + gerundio.",
      "Pronunciar la n como [m] delante de b, v, p y m.",
      "Describir en directo una escena en una videollamada.",
    ],
    review: [
      "Gerundios irregulares: e → i (pidiendo, diciendo), o → u (durmiendo), -yendo (leyendo, oyendo).",
      "Tilde con pronombre pegado: haciéndolo, escribiéndole.",
      "Seguir + gerundio (sin preposición) y seguir sin + infinitivo.",
      "Planes futuros: presente o ir a, nunca estar + gerundio.",
    ],
  },
  related: [
    { path: "/empezar-seguir-repetir-dejar-de-hacer", label: "Empezar, seguir, repetir, dejar de hacer" },
    { path: "/sistema-verbal/imperativo", label: "Sistema verbal · Imperativo" },
  ],
};
