import type { Module } from "../../types";

export const a2w12: Module = {
  id: "a2-12",
  level: "a2",
  week: 12,
  kind: "core",
  title: "Lo que vendrá",
  subtitle: "Predicciones, promesas y condiciones reales con el futuro simple y si + presente.",
  stop: { place: "Bogotá", country: "Colombia" },
  minutes: 80,
  newObjectives: [
    "a2.gram.futuro-simple",
    "a2.gram.si-presente",
    "a2.voc.tecnologia-futuro",
    "a2.pron.vocales-atonas",
    "a2.fun.predecir-prometer",
    "a2.read.horoscopo-predicciones",
  ],
  reviewObjectives: [
    "a2.gram.estar-gerundio",
    "a2.gram.perifrasis-fase",
    "a2.fun.describir-cambios",
    "a2.gram.imperativo-afirmativo",
  ],
  prerequisites: ["a2-11"],
  goal: {
    canDo: "Al final de esta semana puedes hacer predicciones sobre tu vida, tu ciudad y la tecnología, prometer cosas, poner condiciones reales (si llueve, nos quedaremos en casa) y distinguir en un texto planes, predicciones y condiciones.",
    canDoEn: "By the end of this week, you can make predictions about your life, your city and technology, make promises, set real conditions (if it rains, we'll stay at home) and tell plans, predictions and conditions apart in a text.",
    steps: [
      "Aprende el futuro simple regular: una sola serie de terminaciones para -ar, -er e -ir.",
      "Memoriza los doce irregulares más frecuentes: `tendré`, `saldré`, `haré`, `diré`, `podré`, `habrá`…",
      "Decide cuándo usar el futuro, `ir a` o el presente.",
      "Construye condiciones reales con `si` + presente.",
      "Mantén claras las vocales átonas en palabras largas como _comunicación_ o _trabajaremos_.",
      "Escucha un programa de radio de Bogotá sobre la ciudad en 2040 y lee un horóscopo con trampa.",
    ],
  },
  theory: {
    intro: "Esta semana estás en **Bogotá**, a 2.600 metros de altura: TransMilenio, ciclovía los domingos, frío por la mañana y obras del metro por todas partes. Una ciudad que habla mucho del futuro. Para unirte a esa conversación necesitas el **futuro simple** y las **condiciones con si**.",
    parts: [
      {
        heading: "El futuro simple: una forma fácil",
        body: [
          "El futuro simple es uno de los tiempos más regulares del español. Tomas el **infinitivo completo** (_hablar_, _comer_, _vivir_) y añades las terminaciones: **-é, -ás, -á, -emos, -éis, -án**. Son las mismas para los tres grupos de verbos.",
          "Todas las formas llevan **tilde** excepto _nosotros_: _hablaré, hablarás, hablará, hablaremos, hablaréis, hablarán_. El acento está siempre en la terminación, por eso las palabras suenan largas y fuertes al final.",
          "Con **vos** la forma es la misma que con tú: _vos hablarás_. Con **usted** y **ustedes**, la de él y ellos: _usted vivirá_, _ustedes vivirán_. La forma de **vosotros** (_viviréis_) solo se usa en España.",
          "**¿Para qué sirve?** Para **predicciones** (_En 2040 habrá metro en Bogotá_), para **promesas** (_Te llamaré mañana_), para hablar de un futuro más lejano o menos seguro (_Algún día viviré en el campo_) y para hacer suposiciones sobre el presente, uso que verás en B1.",
        ],
        support: [
          "Spanish future = infinitive + -é, -ás, -á, -emos, -éis, -án. No 'will' is needed: _hablaré_ = I will speak.",
          "The written accent is on every form except _nosotros_ (_hablaremos_).",
        ],
        table: {
          caption: "Futuro regular",
          head: ["Persona", "trabajar", "aprender", "vivir"],
          rows: [
            ["yo", "trabajaré", "aprenderé", "viviré"],
            ["tú / vos", "trabajarás", "aprenderás", "vivirás"],
            ["él, ella, usted", "trabajará", "aprenderá", "vivirá"],
            ["nosotros/as", "trabajaremos", "aprenderemos", "viviremos"],
            ["vosotros/as (España)", "trabajaréis", "aprenderéis", "viviréis"],
            ["ellos, ellas, ustedes", "trabajarán", "aprenderán", "vivirán"],
          ],
        },
        examples: [
          { es: "En diez años trabajaremos menos horas.", en: "In ten years we will work fewer hours." },
          { es: "Te lo prometo: estudiaré todos los días.", en: "I promise: I'll study every day." },
          { es: "¿Vivirás siempre en Bogotá?", en: "Will you always live in Bogotá?" },
        ],
        mistakes: [
          { wrong: "Mañana hablare con ella.", right: "Mañana hablaré con ella.", why: "Sin tilde, _hablare_ es otra forma (futuro de subjuntivo, que casi no se usa). El futuro lleva tilde: habla**ré**." },
          { wrong: "Nosotros comerémos a las ocho.", right: "Nosotros comeremos a las ocho.", why: "_Nosotros_ es la única persona sin tilde: comer**e**mos es una palabra llana terminada en -s." },
        ],
      },
      {
        heading: "Los irregulares: cambia la raíz, no la terminación",
        body: [
          "Unos doce verbos muy frecuentes cambian la raíz, pero las terminaciones son las mismas de siempre. Se agrupan en tres familias, y conocer la familia te ayuda a recordarlos.",
          "**1. Pierden la e del infinitivo**: _poder → podr-é_, _saber → sabr-é_, _querer → querr-é_, _haber → habr-á_. **2. Cambian la vocal por una d**: _tener → tendr-é_, _poner → pondr-é_, _salir → saldr-é_, _venir → vendr-é_. **3. Son especiales**: _hacer → har-é_, _decir → dir-é_.",
          "Los compuestos siguen al verbo base: _mantener → mantendré_, _deshacer → desharé_, _proponer → propondré_.",
          "**Habrá** (de _haber_) es la forma impersonal para hablar de existencia en el futuro, como _hay_ en presente. Es **siempre singular**: _Habrá más bicicletas_, nunca «habrán más bicicletas».",
        ],
        support: [
          "Irregular futures change only the stem. Learn them in three families: drop the -e (_podr-, sabr-, querr-, habr-_), add -d- (_tendr-, pondr-, saldr-, vendr-_) and the two odd ones (_har-, dir-_).",
          "_Habrá_ = there will be. It stays singular, just like _hay_.",
        ],
        table: {
          caption: "Las tres familias de irregulares",
          head: ["Familia", "Infinitivo", "Raíz", "Ejemplo"],
          rows: [
            ["pierden la e", "poder, saber, querer, haber", "podr-, sabr-, querr-, habr-", "¿Podrás venir? · Habrá metro."],
            ["e/i → d", "tener, poner, salir, venir", "tendr-, pondr-, saldr-, vendr-", "Saldremos a las seis."],
            ["especiales", "hacer, decir", "har-, dir-", "Haré la tarea. · ¿Qué dirán?"],
          ],
        },
        examples: [
          { es: "Si tengo tiempo, haré la tarea esta noche.", en: "If I have time, I'll do the homework tonight." },
          { es: "En 2040 habrá metro en toda la ciudad.", en: "In 2040 there will be a metro across the whole city." },
          { es: "No sé si podré ir. Mañana te diré.", en: "I don't know if I'll be able to go. I'll tell you tomorrow." },
        ],
        mistakes: [
          { wrong: "Mañana teneré tiempo.", right: "Mañana tendré tiempo.", why: "_Tener_ es irregular: **tendr**-é." },
          { wrong: "Haceremos una fiesta.", right: "Haremos una fiesta.", why: "_Hacer_ → **har**-: haremos." },
          { wrong: "En el futuro habrán más robots.", right: "En el futuro habrá más robots.", why: "_Habrá_ (existencia) es siempre singular, como _hay_." },
          { wrong: "Saliré a las ocho.", right: "Saldré a las ocho.", why: "_Salir_ pertenece a la familia de la **d**: sal**d**ré." },
        ],
        tip: "Una frase para recordar la familia de la d: **Tendré que poner la mesa antes de salir, porque vendrán mis papás** → tendré, pondré, saldré, vendrán.",
      },
      {
        heading: "¿Futuro, ir a o presente?",
        body: [
          "Ya conoces **ir a + infinitivo** (A1) para planes. En la conversación diaria de América Latina es la forma más frecuente para hablar del futuro: _Este fin de semana voy a subir a Monserrate_. Expresa una **intención decidida** o algo que ya vemos venir: _¡Mira esas nubes! Va a llover._",
          "El **futuro simple** suena más **lejano, más general o menos seguro**: predicciones (_En 2050 los carros serán eléctricos_), promesas (_Te devolveré el libro_) y planes sin fecha concreta (_Algún día aprenderé a bailar salsa_). En Colombia, México y Argentina se oye menos en la conversación rápida que en España, pero en promesas y predicciones lo usa todo el mundo.",
          "El **presente** sirve para el futuro cuando hay un **horario o un plan cerrado**: _El vuelo sale a las 7:40_; _Mañana trabajo hasta tarde_. Y también para promesas rápidas: _Mañana te lo devuelvo_.",
          "Las perífrasis de la semana pasada también tienen futuro: _Seguiré estudiando_, _Dejaré de fumar_, _Volveré a intentarlo_, _Empezaré a correr_. Y _estar_ + gerundio en futuro dice qué pasará en un momento concreto: _Mañana a esta hora estaré volando a Madrid._",
        ],
        support: [
          "_Ir a_ = going to (plan or clear evidence). Future simple = will (prediction, promise, distant or uncertain future). Present = timetables and fixed arrangements.",
          "Don't overthink it: in many cases two options are correct. The difference is in how sure or how close you feel the event is.",
        ],
        table: {
          caption: "Tres maneras de hablar del futuro",
          head: ["Forma", "Para…", "Ejemplo"],
          rows: [
            ["presente", "horarios, planes cerrados", "El TransMilenio pasa a las 6:10."],
            ["ir a + infinitivo", "intención decidida, evidencia", "Voy a renovar el pasaporte. · Va a llover."],
            ["futuro simple", "predicción, promesa, futuro lejano", "Algún día viajaremos a Marte."],
          ],
        },
        examples: [
          { es: "Esta noche voy a ver el partido con mis primos.", en: "Tonight I'm going to watch the match with my cousins. (plan)" },
          { es: "Creo que Santa Fe ganará la liga este año.", en: "I think Santa Fe will win the league this year. (prediction)" },
          { es: "El concierto empieza a las ocho.", en: "The concert starts at eight. (schedule)" },
        ],
        mistakes: [
          { wrong: "Mira el cielo: lloverá.", right: "Mira el cielo: va a llover.", why: "Con una evidencia que ves ahora, lo natural es **ir a**." },
          { wrong: "Mañana estoy viajando a Cali.", right: "Mañana viajo a Cali. / Mañana voy a viajar a Cali.", why: "Recuerda la semana pasada: estar + gerundio no sirve para planes." },
        ],
      },
      {
        heading: "Si + presente: condiciones reales",
        body: [
          "Para una condición **posible y real**, usa **si + presente** y, en la otra parte de la frase, el **futuro**, **ir a**, el **presente** o el **imperativo**: _Si llueve, nos quedaremos en casa_; _Si llueve, nos quedamos en casa_; _Si tienes tiempo, llámame_.",
          "**Nunca** pongas el futuro después de _si_ en este tipo de frase: _Si mañana **hace** sol_, no «si mañana hará sol». La condición va en presente, aunque hable del futuro. Es como en inglés: _If it rains…_, not _If it will rain…_",
          "El orden es libre. Si la condición va primero, ponemos **coma**: _Si vienes, te presento a mis amigos._ Si va al final, normalmente sin coma: _Te presento a mis amigos si vienes._",
          "**Si** condicional no lleva tilde. **Sí** con tilde es la respuesta afirmativa (_Sí, claro_) — ya lo viste en la semana 3.",
        ],
        support: [
          "Real conditions: _si_ + present, then future / present / imperative. Never use the future right after _si_ here.",
          "Comma when the _si_ clause comes first, usually no comma when it comes second.",
        ],
        table: {
          caption: "La estructura",
          head: ["Condición (si + presente)", "Resultado"],
          rows: [
            ["Si llueve,", "nos quedaremos en casa. (futuro)"],
            ["Si llueve,", "vamos a ver una película. (ir a)"],
            ["Si llueve,", "no hay ciclovía. (presente: algo general)"],
            ["Si llueve,", "llévate un paraguas. (imperativo)"],
          ],
        },
        examples: [
          { es: "Si aprendes a programar, encontrarás trabajo más fácilmente.", en: "If you learn to code, you'll find a job more easily." },
          { es: "Si sumercé quiere, le llevo las bolsas.", en: "If you'd like, I'll carry the bags for you. (Bogotá, affectionate usted)" },
          { es: "Llámame si necesitas algo.", en: "Call me if you need anything." },
        ],
        mistakes: [
          { wrong: "Si tendré tiempo, iré al gimnasio.", right: "Si tengo tiempo, iré al gimnasio.", why: "Después de _si_ condicional va el **presente**, nunca el futuro." },
          { wrong: "Sí estudias, aprobarás.", right: "Si estudias, aprobarás.", why: "El _si_ condicional va **sin tilde**." },
        ],
        tip: "**Sumercé** es una forma muy bogotana y boyacense de decir _usted_ con cariño: _¿Qué le provoca, sumercé?_ Los verbos van como con usted.",
      },
      {
        heading: "Predecir y prometer",
        body: [
          "Para **predecir** con distintos grados de seguridad: **Seguro que** + futuro (muy seguro), **Seguramente / Probablemente** + futuro, **Creo que** + futuro, **A lo mejor** + presente o futuro (posible), **No creo que**… (necesita subjuntivo: lo verás más adelante; por ahora di **Creo que no**).",
          "Para **prometer**: **Te prometo que** + futuro, **Te lo prometo**, **Te doy mi palabra**, y en lenguaje coloquial **Te lo juro**. Con usted: **Se lo prometo**.",
          "Para **reaccionar**: **¡Ojalá!** (eso espero), **¡Eso espero!**, **Ya veremos** (no estoy seguro), **¡Qué va!** (no lo creo, típico de España y del Caribe), **¿Tú crees?** / **¿Usted cree?**, **¡Más te vale!** (amenaza amable a una promesa).",
        ],
        support: [
          "_A lo mejor_ = maybe (very common in speech). _¡Ojalá!_ on its own = I hope so! _Ya veremos_ = we'll see.",
        ],
        examples: [
          { es: "—Seguro que mañana hará frío. —¡Qué raro, en Bogotá! (ironía)", en: "It'll surely be cold tomorrow. — How unusual, in Bogotá! (irony)" },
          { es: "—Te prometo que llegaré a tiempo. —¡Más te vale!", en: "I promise I'll be on time. — You'd better!" },
          { es: "—A lo mejor nos mudamos a Medellín. —¿Usted cree?", en: "Maybe we'll move to Medellín. — Do you think so?" },
        ],
      },
    ],
  },
  grammar: {
    intro: "Forma el futuro, memoriza los irregulares y construye condiciones con si.",
    exercises: [
      {
        id: "g1",
        type: "gap",
        title: "Bogotá en 2040",
        prompt: "Completa con el futuro simple del verbo entre paréntesis.",
        items: [
          { q: "En 2040 los bogotanos ___ en metro elevado. (viajar)", answers: [["viajarán"]], why: "Ellos → infinitivo + **-án**: viajar**án**." },
          { q: "Tú ___ desde casa tres días por semana. (trabajar)", answers: [["trabajarás"]], why: "Tú → **-ás**, con tilde." },
          { q: "Nosotros ___ más verduras y menos carne. (comer)", answers: [["comeremos"]], why: "Nosotros → **-emos**, sin tilde." },
          { q: "¿Sumercé ___ en la ciudad o en el campo? (vivir)", answers: [["vivirá"]], why: "_Sumercé_ funciona como usted → **-á**." },
          { q: "Yo ___ a usar la bicicleta todos los días. (volver)", answers: [["volveré"]], why: "Yo → **-é**. Y _volver a_ + infinitivo: la perífrasis de la semana pasada." },
        ],
      },
      {
        id: "g2",
        type: "choice",
        title: "Irregulares",
        prompt: "Elige la forma correcta.",
        items: [
          { q: "Mañana no ___ ir a clase, tengo médico.", options: ["podré", "poderé", "pudré"], answer: 0, why: "_Poder_ pierde la e: **podr**-é." },
          { q: "Si salimos a las seis, ___ a tiempo.", options: ["llegaremos", "llegarémos", "llegamos a"], answer: 0, why: "Regular, _nosotros_ sin tilde: llegar**emos**." },
          { q: "Mis papás ___ en diciembre a visitarme.", options: ["vendrán", "venirán", "venderán"], answer: 0, why: "_Venir_ → **vendr**-án. _Venderán_ es de _vender_." },
          { q: "En el futuro ___ menos trabajos en las fábricas.", options: ["habrá", "habrán", "hayrá"], answer: 0, why: "Existencia en futuro: **habrá**, siempre singular." },
          { q: "No te preocupes, no se lo ___ a nadie.", options: ["diré", "deciré", "dicaré"], answer: 0, why: "_Decir_ → **dir**-é." },
          { q: "¿Qué ___ ustedes el fin de semana de la ciclovía?", options: ["harán", "hacerán", "haceran"], answer: 0, why: "_Hacer_ → **har**-án." },
        ],
      },
      {
        id: "g3",
        type: "classify",
        title: "¿Plan, predicción o promesa?",
        prompt: "Clasifica cada frase según su función.",
        categories: ["plan decidido", "predicción", "promesa"],
        items: [
          { text: "El sábado vamos a subir a Monserrate a pie.", cat: 0, why: "_Ir a_ + fecha concreta: plan decidido." },
          { text: "Dentro de veinte años los carros no necesitarán conductor.", cat: 1, why: "Futuro simple sobre algo general y lejano: predicción." },
          { text: "Te prometo que te devolveré el libro el lunes.", cat: 2, why: "_Te prometo que_ + futuro." },
          { text: "Ya compré los tiquetes: viajo a Cartagena el 15.", cat: 0, why: "Presente para un plan cerrado (ya tiene los tiquetes)." },
          { text: "Seguro que la inteligencia artificial cambiará la medicina.", cat: 1, why: "_Seguro que_ + futuro: predicción con mucha seguridad." },
          { text: "No volveré a llegar tarde, se lo juro.", cat: 2, why: "Futuro + _se lo juro_: promesa (con usted)." },
        ],
      },
      {
        id: "g4",
        type: "match",
        title: "Condición y resultado",
        prompt: "Une cada condición con su resultado lógico.",
        pairs: [
          { left: "Si mañana hace sol,", right: "iremos a la ciclovía en bici." },
          { left: "Si se te acaba la batería,", right: "cárgala en el café de la esquina." },
          { left: "Si ahorras un poco cada mes,", right: "podrás viajar en diciembre." },
          { left: "Si el computador no prende,", right: "llama al servicio técnico." },
          { left: "Si sigues durmiendo tan poco,", right: "te enfermarás." },
        ],
        why: "Todas las condiciones van con **si + presente**; el resultado va en futuro o en imperativo.",
      },
      {
        id: "g5",
        type: "transform",
        title: "Pon la condición",
        prompt: "Une las dos ideas en una frase con **si + presente** y futuro (la condición primero).",
        items: [
          { source: "Llueve mañana. → No hay ciclovía. (cancelar, ellos)", answers: ["Si llueve mañana, cancelarán la ciclovía.", "Si mañana llueve, cancelarán la ciclovía."], why: "_Si_ + presente (_llueve_), futuro en el resultado (_cancelarán_)." },
          { source: "Tienes tiempo. → Vienes a la fiesta. (venir)", answers: ["Si tienes tiempo, vendrás a la fiesta.", "Si tienes tiempo, ¿vendrás a la fiesta?"], why: "_Venir_ irregular: **vendr**ás." },
          { source: "Estudiamos juntos. → Aprobamos el examen. (aprobar)", answers: ["Si estudiamos juntos, aprobaremos el examen."], why: "Nosotros: aprobar**emos**, sin tilde." },
          { source: "El metro funciona. → Hay menos tráfico. (haber)", answers: ["Si el metro funciona, habrá menos tráfico."], why: "_Haber_ → **habrá**, singular." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Palabras para hablar del futuro de la tecnología y del trabajo. Fíjate en las variantes: en Colombia se dice _el computador_, en México _la computadora_ y en España _el ordenador_.",
    groups: [
      {
        title: "Tecnología de todos los días",
        items: [
          { es: "el celular / el móvil", en: "mobile phone", note: "_Celular_ en América; _móvil_ en España." },
          { es: "el computador / la computadora / el ordenador", en: "computer", note: "Colombia / México y gran parte de América / España." },
          { es: "descargar una aplicación", en: "to download an app" },
          { es: "cargar la batería", en: "to charge the battery" },
          { es: "guardar archivos en la nube", en: "to save files in the cloud" },
          { es: "conectarse al wifi", en: "to connect to the wifi" },
          { es: "la contraseña", en: "password" },
          { es: "pagar con el celular", en: "to pay with your phone" },
        ],
      },
      {
        title: "El trabajo del futuro",
        items: [
          { es: "la inteligencia artificial (la IA)", en: "artificial intelligence (AI)" },
          { es: "el teletrabajo / trabajar en remoto", en: "remote work / to work remotely" },
          { es: "un robot hará las tareas repetitivas", en: "a robot will do repetitive tasks" },
          { es: "desaparecer / aparecer", en: "to disappear / appear", note: "Algunos trabajos desaparecerán y aparecerán otros." },
          { es: "sustituir a las personas", en: "to replace people" },
          { es: "aprender nuevas habilidades", en: "to learn new skills" },
          { es: "crear empleo", en: "to create jobs" },
        ],
      },
      {
        title: "La ciudad que viene",
        items: [
          { es: "el carro eléctrico / el coche eléctrico", en: "electric car", note: "_Carro_ en gran parte de América; _coche_ en España; _auto_ en el Cono Sur." },
          { es: "el carro autónomo (sin conductor)", en: "self-driving car" },
          { es: "las compras en línea", en: "online shopping" },
          { es: "los drones de reparto", en: "delivery drones" },
          { es: "la realidad virtual", en: "virtual reality" },
          { es: "la energía solar", en: "solar energy" },
          { es: "contaminar menos", en: "to pollute less" },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "¿Qué es?",
        prompt: "Une cada palabra con su definición.",
        pairs: [
          { left: "la contraseña", right: "Palabra secreta para entrar en una cuenta." },
          { left: "la nube", right: "Lugar en internet donde guardas fotos y archivos." },
          { left: "el teletrabajo", right: "Trabajar desde casa con el computador." },
          { left: "el carro autónomo", right: "Vehículo que se maneja solo." },
          { left: "descargar", right: "Pasar una aplicación de internet a tu celular." },
        ],
        why: "Son las palabras básicas para hablar de tecnología en cualquier país.",
      },
      {
        id: "v2",
        type: "context",
        title: "¿Cómo se dice aquí?",
        prompt: "Elige la palabra más natural en cada lugar.",
        items: [
          { context: "Estás en una oficina de Bogotá y tu pantalla no funciona.", q: "Dices:", options: ["Se me dañó el computador.", "Se me dañó el ordenador.", "Se me dañó el coche."], answer: 0, why: "En Colombia: **el computador**. _Ordenador_ es de España." },
          { context: "Estás en Madrid y no encuentras tu teléfono.", q: "Preguntas:", options: ["¿Has visto mi móvil?", "¿Has visto mi celular?", "¿Has visto mi computador?"], answer: 0, why: "En España se dice **móvil**; en América, _celular_ (también se entiende)." },
          { context: "En Ciudad de México hablas de la contaminación.", q: "Dices:", options: ["En el futuro habrá más carros eléctricos.", "En el futuro habrán más carros eléctricos.", "En el futuro habrá más coche eléctrico."], answer: 0, why: "En México se dice **carro**; y _habrá_ siempre en singular." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "Vocales átonas plenas en palabras largas",
    explanation: [
      "Las palabras del futuro suelen ser **largas**: _comunicación_, _universidad_, _tecnología_, _trabajaremos_, _desaparecerán_. En español todas las vocales, también las que no llevan el acento (las **átonas**), se pronuncian **completas y claras**. _Co-mu-ni-ca-ción_ tiene cinco sílabas, y se oyen las cinco.",
      "El inglés hace lo contrario: reduce las vocales átonas a un sonido débil (como la primera vocal de _about_). Si haces eso en español, _comunicación_ suena «cuh-myu-nuh-cation», y se pierde información: _pasado_, _pesado_ y _pisado_ son tres palabras distintas, y la diferencia está justo en una vocal átona.",
      "Con el futuro es todavía más importante, porque el acento llega **al final**: _tra-ba-ja-re-MOS_. Las cuatro vocales anteriores tienen que sonar tan claras como la última. Piensa en el ritmo del español como una fila de sílabas del mismo tamaño: ta-ta-ta-ta-TA.",
      "**Variación.** En el español del altiplano mexicano y de los Andes de Perú, Bolivia y Ecuador, las vocales átonas a veces se debilitan, sobre todo junto a una **s**: _pues_ suena casi «ps», _gracias_ casi «grac's». Lo vas a oír, pero en Bogotá y en la mayoría del mundo hispano las vocales se mantienen plenas.",
    ],
    support: [
      "Don't reduce unstressed vowels to 'uh'. Every Spanish vowel keeps its full quality: _u-ni-ver-si-dad_ = five clear syllables.",
      "Practise long words by tapping one finger per syllable, all the same length, with a little extra strength on the stressed one.",
    ],
    table: {
      head: ["Palabra", "Sílabas", "Fuerte"],
      rows: [
        ["comunicación", "co-mu-ni-ca-ción (5)", "ción"],
        ["universidad", "u-ni-ver-si-dad (5)", "dad"],
        ["tecnología", "tec-no-lo-gí-a (5)", "gí"],
        ["trabajaremos", "tra-ba-ja-re-mos (5)", "re"],
        ["desaparecerán", "de-sa-pa-re-ce-rán (6)", "rán"],
      ],
    },
    perceive: {
      id: "p1",
      type: "listen",
      title: "Escucha cada vocal",
      prompt: "Escucha y elige. En las primeras palabras cambia solo una vocal átona; en las últimas, cuenta las sílabas.",
      items: [
        { q: "¿Qué palabra oyes?", audio: "pesado", options: ["pasado", "pesado", "pisado"], answer: 1, why: "La primera vocal, átona, es **e**: pe-sa-do (que pesa mucho)." },
        { q: "¿Qué palabra oyes?", audio: "malestar", options: ["molestar", "malestar"], answer: 1, why: "**Ma**-les-tar: la a átona del principio se oye clara." },
        { q: "¿Qué palabra oyes?", audio: "sacado", options: ["secado", "sacado"], answer: 1, why: "**Sa**-ca-do, de _sacar_. _Secado_ es de _secar_." },
        { q: "¿Qué forma oyes?", audio: "hablaremos", options: ["hablaremos", "hablaríamos", "habláramos"], answer: 0, why: "Ha-bla-re-**mos**: las vocales a, a, e antes del acento suenan plenas." },
        { q: "¿Cuántas sílabas tiene?", audio: "comunicación", options: ["4", "5", "6"], answer: 1, why: "Co-mu-ni-ca-ción: 5 sílabas, ninguna desaparece." },
        { q: "¿Cuántas sílabas tiene?", audio: "necesitaremos", options: ["5", "6", "7"], answer: 1, why: "Ne-ce-si-ta-re-mos: 6 sílabas." },
        { q: "¿Cuántas sílabas tiene?", audio: "aplicación", options: ["3", "4", "5"], answer: 1, why: "A-pli-ca-ción: 4 sílabas (_ción_ es una sola: diptongo)." },
        { q: "¿Cuántas sílabas tiene?", audio: "desaparecerán", options: ["5", "6", "7"], answer: 1, why: "De-sa-pa-re-ce-rán: 6 sílabas, todas con su vocal completa." },
      ],
    },
    produce: [
      { text: "co-mu-ni-ca-ción · u-ni-ver-si-dad · tec-no-lo-gí-a", tip: "Primero sílaba por sílaba, dando un golpe de dedo en la mesa por cada una. Después, rápido, sin perder ninguna." },
      { text: "La inteligencia artificial cambiará la comunicación.", tip: "_In-te-li-gen-cia ar-ti-fi-cial_: nueve sílabas antes de llegar al verbo. La **i** de cada sílaba suena igual de clara." },
      { text: "Si estudias en la universidad, conocerás a mucha gente.", tip: "_Co-no-ce-rás_: la o y la e átonas no se convierten en «uh»." },
      { text: "Trabajaremos menos y necesitaremos nuevas habilidades.", tip: "Ritmo de metralleta: ta-ta-ta-ta-TA. _Ha-bi-li-da-des_ tiene cinco sílabas." },
      { text: "Te prometo que te llamaré mañana.", tip: "_Pro-me-to_, _lla-ma-ré_: no te comas la **e** de _prometo_." },
    ],
    spelling: "En el futuro, la tilde marca dónde está la fuerza: _llamaré, llamarás, llamará, llamarán_. Si pronuncias la vocal acentuada demasiado larga y las demás demasiado cortas, la palabra se deforma: mantén todas las vocales del mismo tamaño y da solo un poco más de fuerza a la del acento.",
  },
  listening: {
    title: "Bogotá en 2040: programa de radio",
    context: "En el programa de radio «Bogotá mañana», la periodista Mariana entrevista a Ignacio, un investigador chileno que vive en Bogotá. Después llama un oyente, Don Hernando, taxista.",
    speakers: [
      { id: "mariana", name: "Mariana", voice: "es-CO-f", role: "periodista de radio, bogotana" },
      { id: "ignacio", name: "Ignacio", voice: "es-CL-m", role: "investigador chileno" },
      { id: "hernando", name: "Don Hernando", voice: "es-CO-m", role: "taxista, oyente del programa" },
    ],
    script: [
      { speaker: "mariana", text: "Buenas tardes, sumercés. Están escuchando «Bogotá mañana». Hoy nos acompaña Ignacio Rojas, investigador chileno que vive en Bogotá desde hace cinco años. Bienvenido, Ignacio." },
      { speaker: "ignacio", text: "Gracias, Mariana. Un gusto estar aquí." },
      { speaker: "mariana", text: "Primera pregunta: ¿cómo será Bogotá en el año 2040?" },
      { speaker: "ignacio", text: "Habrá menos carros en el centro y mucha más gente en bicicleta. El metro ya estará funcionando y muchas personas trabajarán desde casa dos o tres días por semana." },
      { speaker: "mariana", text: "¿Y el dinero? ¿Seguiremos pagando en efectivo?" },
      { speaker: "ignacio", text: "Creo que no. Dejaremos de usar efectivo casi del todo y pagaremos todo con el celular, hasta el tinto en la esquina." },
      { speaker: "mariana", text: "Mucha gente tiene miedo de la inteligencia artificial. ¿Perderemos el trabajo?" },
      { speaker: "ignacio", text: "Algunos trabajos desaparecerán, es verdad, pero aparecerán otros. Si aprendemos a usar estas herramientas, no tendremos que competir con ellas." },
      { speaker: "mariana", text: "Tenemos una llamada. Buenas tardes, ¿con quién hablamos?" },
      { speaker: "hernando", text: "Buenas tardes, sumercé. Habla Hernando, taxista desde hace treinta años." },
      { speaker: "mariana", text: "Don Hernando, ¿qué piensa de los carros sin conductor?" },
      { speaker: "hernando", text: "Mire, con el tráfico de Bogotá, eso no funcionará nunca. Pero le digo una cosa: si un robot maneja mi taxi, yo me iré al campo y sembraré papa en Boyacá." },
      { speaker: "ignacio", text: "Don Hernando tiene algo de razón: los cambios llegarán, pero poco a poco." },
      { speaker: "mariana", text: "Ignacio, ¿una promesa para nuestros oyentes?" },
      { speaker: "ignacio", text: "Les prometo una cosa: volveré al programa en diez años y veremos quién tenía razón." },
      { speaker: "hernando", text: "Trato hecho. Y si gano yo, sumercé me invita a un tinto." },
      { speaker: "mariana", text: "Prometido. Y ustedes, oyentes, escríbannos al WhatsApp del programa y cuéntennos sus predicciones. Ya volvemos, después de la música." },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: capta la idea general.",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha todo el programa una vez y responde.",
          items: [
            { q: "¿De qué trata el programa?", options: ["De cómo será Bogotá en el futuro", "De la historia del transporte en Bogotá", "De los problemas de los taxistas hoy"], answer: 0, why: "La primera pregunta es _¿cómo será Bogotá en el año 2040?_" },
            { q: "¿Cuál es la actitud de Don Hernando frente a los carros sin conductor?", options: ["Es escéptico, pero lo dice con humor.", "Está muy entusiasmado.", "Está enfadado con Ignacio."], answer: 0, why: "Dice que _no funcionará nunca_ y bromea con irse a sembrar papa." },
            { q: "¿Cómo termina el programa?", options: ["Con una promesa y una apuesta amistosa", "Con una discusión", "Con una llamada de otro oyente"], answer: 0, why: "Ignacio promete volver en diez años y Don Hernando apuesta un tinto." },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: atención a los datos y a las condiciones.",
        exercise: {
          id: "l2",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "Según Ignacio, ¿cuántos días trabajarán muchas personas desde casa?", options: ["dos o tres por semana", "todos los días", "uno por semana"], answer: 0, why: "_Trabajarán desde casa dos o tres días por semana_." },
            { q: "¿Qué dejaremos de usar, según Ignacio?", options: ["el efectivo", "el celular", "el metro"], answer: 0, why: "_Dejaremos de usar efectivo casi del todo_." },
            { q: "¿Qué pasará si aprendemos a usar la inteligencia artificial?", options: ["No tendremos que competir con ella.", "Perderemos el trabajo.", "Trabajaremos más horas."], answer: 0, why: "_Si aprendemos a usar estas herramientas, no tendremos que competir con ellas_." },
            { q: "¿Qué hará Don Hernando si un robot maneja su taxi?", options: ["Se irá al campo a sembrar papa.", "Comprará un carro eléctrico.", "Trabajará en la radio."], answer: 0, why: "_Yo me iré al campo y sembraré papa en Boyacá_." },
            { q: "¿Qué promete Ignacio?", options: ["Volver al programa en diez años", "Invitar a todos a un tinto", "Escribir un libro sobre Bogotá"], answer: 0, why: "_Volveré al programa en diez años_." },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en para qué sirve cada frase.",
        exercise: {
          id: "l3",
          type: "classify",
          prompt: "¿Es una predicción, una condición o una promesa?",
          categories: ["predicción", "condición (si…)", "promesa"],
          items: [
            { text: "Habrá menos carros en el centro.", cat: 0, why: "_Habrá_: futuro de _haber_ para predecir." },
            { text: "Algunos trabajos desaparecerán.", cat: 0, why: "Predicción general con futuro." },
            { text: "Si aprendemos a usar estas herramientas, no tendremos que competir con ellas.", cat: 1, why: "_Si_ + presente (_aprendemos_) + futuro irregular (_tendremos_)." },
            { text: "Si un robot maneja mi taxi, me iré al campo.", cat: 1, why: "Condición real con _si_ + presente." },
            { text: "Les prometo una cosa: volveré al programa.", cat: 2, why: "_Les prometo_ + futuro." },
            { text: "Y si gano yo, sumercé me invita a un tinto.", cat: 1, why: "Condición con _si_ + presente y resultado en presente: una apuesta." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Tu semana según las estrellas (y según tu celular)",
    genre: "Horóscopo de humor en una revista",
    frame: "Columna semanal de «Doña Estrella» en una revista cultural gratuita de Bogotá. Mezcla horóscopo, tecnología y consejos.",
    text: [
      "**Aries.** Esta semana va a ser intensa: ya tienes tres reuniones en la agenda y el jueves vas a presentar tu proyecto. Las estrellas dicen que todo saldrá bien. Pero atención: si no cargas la batería del computador antes de la presentación, Marte no podrá ayudarte.",
      "**Tauro.** Venus te traerá una sorpresa el fin de semana: alguien que no ves desde hace años volverá a escribirte. Si te invita a un café, di que sí. Y por favor, deja de mirar el celular durante la cena: tu familia te lo agradecerá.",
      "**Géminis.** Estás empezando un nuevo hábito y las estrellas lo aprueban. Seguro que en un mes notarás los cambios. El domingo vas a ir a la ciclovía con tus amigos; si llueve (es Bogotá, lloverá), lleva chaqueta.",
      "**Cáncer.** Tu jefe te pedirá un favor difícil. Si lo haces con paciencia, recibirás una buena noticia antes de fin de mes. El viernes vas a cenar con alguien especial: elige un lugar sin wifi.",
      "**Para todos los signos.** Doña Estrella no puede ver el futuro, pero sí puede hacer una predicción segura: si lees este horóscopo todas las semanas, volverás a reírte el próximo jueves. Prometido.",
    ],
    glossary: [
      { es: "la agenda", en: "diary / schedule" },
      { es: "saldrá bien", en: "will go well" },
      { es: "agradecer", en: "to be grateful for, thank" },
      { es: "aprobar", en: "to approve of" },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee el horóscopo y responde.",
        items: [
          { q: "¿Qué tipo de texto es?", options: ["Un horóscopo con humor que no se toma en serio", "Un artículo científico sobre astrología", "Un anuncio de una tienda de tecnología"], answer: 0, why: "La autora dice al final que _no puede ver el futuro_ y bromea con la lluvia de Bogotá." },
          { q: "¿Qué tiene que hacer Aries antes de la presentación?", options: ["Cargar la batería del computador", "Hablar con Marte", "Cancelar las reuniones"], answer: 0, why: "_Si no cargas la batería del computador antes de la presentación…_" },
          { q: "¿Qué le pasará a Tauro, según Venus?", options: ["Alguien del pasado volverá a escribirle.", "Recibirá un favor de su jefe.", "Empezará un nuevo hábito."], answer: 0, why: "_Alguien que no ves desde hace años volverá a escribirte_." },
          { q: "¿Qué aconseja Doña Estrella a Cáncer para la cena del viernes?", options: ["Elegir un lugar sin wifi", "Ir a la ciclovía", "Llevar chaqueta"], answer: 0, why: "_Elige un lugar sin wifi_. La chaqueta es para Géminis." },
        ],
      },
      {
        id: "r2",
        type: "classify",
        prompt: "En el texto hay planes ya decididos, predicciones y condiciones. Clasifica estas frases.",
        categories: ["plan ya decidido", "predicción", "condición"],
        items: [
          { text: "el jueves vas a presentar tu proyecto", cat: 0, why: "_Ir a_ + día concreto, y ya está en la agenda: plan." },
          { text: "todo saldrá bien", cat: 1, why: "Futuro irregular (_salir → saldrá_) para predecir." },
          { text: "si te invita a un café, di que sí", cat: 2, why: "_Si_ + presente + imperativo." },
          { text: "El domingo vas a ir a la ciclovía con tus amigos", cat: 0, why: "Plan con _ir a_ y fecha." },
          { text: "Tu jefe te pedirá un favor difícil", cat: 1, why: "Futuro simple: algo que las estrellas «ven»." },
          { text: "si lo haces con paciencia, recibirás una buena noticia", cat: 2, why: "_Si_ + presente + futuro." },
        ],
      },
    ],
    noticing: {
      prompt: "Mira cómo funcionan el futuro y las condiciones en el horóscopo.",
      items: [
        { quote: "todo saldrá bien", note: "_Salir_ es de la familia de la d: **saldr**-á." },
        { quote: "Marte no podrá ayudarte", note: "_Poder_ pierde la e: **podr**-á. El pronombre va pegado al infinitivo: _ayudarte_." },
        { quote: "volverá a escribirte", note: "Perífrasis _volver a_ en futuro: las perífrasis de la semana pasada funcionan en todos los tiempos." },
        { quote: "deja de mirar el celular", note: "Imperativo de tú + _dejar de_: consejo directo." },
        { quote: "si llueve (es Bogotá, lloverá)", note: "Después de _si_, presente (_llueve_). Fuera de la condición, la predicción va en futuro (_lloverá_)." },
        { quote: "Estás empezando un nuevo hábito", note: "Estar + gerundio para un proceso que ocurre estos días." },
      ],
    },
  },
  practice: {
    intro: "Mezcla el futuro, las condiciones y lo que aprendiste la semana pasada.",
    exercises: [
      {
        id: "x1",
        type: "error",
        title: "Detective de errores",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "Si mañana hará buen tiempo, subiremos a Monserrate.", answers: ["Si mañana hace buen tiempo, subiremos a Monserrate."], why: "Después de _si_ condicional va el presente: **hace**." },
          { sentence: "Te prometo que te deciré la verdad.", answers: ["Te prometo que te diré la verdad."], why: "_Decir_ → **dir**-é." },
          { sentence: "En 2050 habrán ciudades sin carros.", answers: ["En 2050 habrá ciudades sin carros."], why: "_Habrá_ es impersonal: siempre singular." },
          { sentence: "Nosotros saliremos temprano para evitar el tráfico.", answers: ["Nosotros saldremos temprano para evitar el tráfico.", "Saldremos temprano para evitar el tráfico."], why: "_Salir_ → **saldr**-emos." },
          { sentence: "Sí tienes frío, ponte la chaqueta.", answers: ["Si tienes frío, ponte la chaqueta."], why: "_Si_ condicional sin tilde. _Sí_ con tilde significa _yes_." },
        ],
      },
      {
        id: "x2",
        type: "order",
        title: "Frases del futuro",
        prompt: "Ordena las palabras.",
        items: [
          { words: ["Si", "llueve,", "nos", "quedaremos", "en", "casa."], alt: ["Nos quedaremos en casa si llueve."], en: "If it rains, we'll stay at home.", why: "_Si_ + presente, futuro en el resultado." },
          { words: ["Te", "prometo", "que", "no", "volveré", "a", "llegar", "tarde."], en: "I promise I won't be late again.", why: "_Te prometo que_ + futuro; _volver a_ + infinitivo." },
          { words: ["Seguro", "que", "habrá", "mucho", "tráfico", "mañana."], alt: ["Seguro que mañana habrá mucho tráfico."], en: "There'll surely be a lot of traffic tomorrow.", why: "_Seguro que_ + futuro: predicción segura." },
          { words: ["Llámame", "si", "necesitas", "ayuda."], alt: ["Si necesitas ayuda, llámame."], en: "Call me if you need help.", why: "Imperativo + _si_ + presente." },
        ],
      },
      {
        id: "x3",
        type: "context",
        title: "Reacciona",
        prompt: "Lee lo que te dicen y elige la reacción más natural.",
        items: [
          { context: "Tu amigo: «Te prometo que esta vez llegaré a tiempo».", q: "Tú, que no le crees mucho:", options: ["¡Más te vale!", "¡Qué rico!", "Lo siento mucho."], answer: 0, why: "**¡Más te vale!** responde con humor a una promesa poco creíble." },
          { context: "Tu compañera: «Creo que el año que viene nos subirán el sueldo».", q: "Tú, con esperanza:", options: ["¡Ojalá!", "¡Qué va, nunca!", "Te lo prometo."], answer: 0, why: "**¡Ojalá!** = espero que sí." },
          { context: "Un señor en una tienda de Bogotá: «Si sumercé quiere, se lo envuelvo para regalo».", q: "Tú respondes:", options: ["Sí, por favor, muchas gracias.", "Si, por favor, me lo envuelvo.", "¡Ojalá!"], answer: 0, why: "Aceptas la oferta con **Sí** (con tilde: afirmación)." },
          { context: "Tu primo: «A lo mejor dejo el trabajo y me voy a vivir a la playa».", q: "Tú, sorprendido y con dudas:", options: ["¿Tú crees? Ya veremos…", "¡Más te vale!", "Te lo juro."], answer: 0, why: "**¿Tú crees?** y **Ya veremos** muestran duda ante una predicción." },
        ],
      },
      {
        id: "x4",
        type: "gap",
        title: "Mensajes de Bogotá",
        prompt: "Completa los mensajes con la forma correcta (futuro, presente, gerundio o imperativo).",
        items: [
          { q: "Camila, ahora mismo ___ en TransMilenio, pero si me ___ en diez minutos, podemos hablar. (viajar: acción en curso / llamar, tú)", answers: [["estoy viajando"], ["llamas"]], why: "Estar + gerundio (ahora); después de _si_, presente: **llamas**." },
          { q: "Si ___ antes de las ocho, ___ a cenar con nosotros. (salir, tú / venir, tú)", answers: [["sales"], ["vendrás", "ven", "vienes"]], why: "_Si_ + presente (**sales**); el resultado puede ir en futuro (**vendrás**), presente o imperativo (**ven**)." },
          { q: "Mamá, te prometo que ___ de tomar tanto café. (dejar, yo)", answers: [["dejaré"]], why: "Promesa con futuro + _dejar de_." },
          { q: "Si ves a Andrés, ___ que lo espero en la Candelaria. (decir, tú + le)", answers: [["dile"]], why: "Imperativo de _decir_ (tú): **di** + **le** = **dile**." },
          { q: "En diez años ___ más personas trabajando desde casa. (haber)", answers: [["habrá"]], why: "Existencia en futuro: **habrá**." },
        ],
      },
      {
        id: "x5",
        type: "open",
        title: "Escritura guiada: el futuro en pocas líneas",
        prompt: "Escribe 2–3 frases para cada situación.",
        items: [
          {
            prompt: "Otra vez olvidaste devolverle un libro a tu amiga Sara. Escríbele un mensaje con una disculpa y dos promesas.",
            model: "¡Perdón, Sara! Se me olvidó tu libro otra vez. Te prometo que mañana te lo llevaré a la oficina. Y la próxima vez, te invitaré a un tinto para compensar.",
            checklist: ["Te disculpas al principio.", "Usas _te prometo que_ + futuro.", "Hay al menos un futuro irregular o un pronombre (_te lo llevaré_)."],
          },
          {
            prompt: "Escribe tres predicciones para tu ciudad dentro de veinte años. Una de ellas debe tener una condición con si.",
            model: "Dentro de veinte años habrá más parques y menos carros en mi ciudad. La gente trabajará desde casa la mitad de la semana. Si el gobierno construye más ciclorrutas, todos iremos al trabajo en bicicleta.",
            checklist: ["Usas al menos tres verbos en futuro.", "Usas _habrá_ en singular.", "La condición va con _si_ + presente."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe una carta a tu «yo» de dentro de diez años.",
    context: "Un proyecto de tu escuela: cada estudiante escribe una carta que leerá en diez años. Tiene que incluir predicciones, promesas y condiciones.",
    steps: [
      "Saluda a tu yo del futuro y di dónde y cómo estás ahora (estar + gerundio, presente).",
      "Haz tres predicciones sobre tu vida (trabajo, casa, idiomas, tecnología).",
      "Haz dos promesas: algo que empezarás o dejarás de hacer.",
      "Añade al menos dos condiciones con si + presente.",
      "Despídete con un consejo en imperativo.",
    ],
    useLanguage: ["Ahora mismo estoy…", "Dentro de diez años…", "Seguro que / Seguramente / A lo mejor…", "Te prometo que…", "Si + presente, futuro", "habrá, tendré, podré, haré, sabré", "dejaré de / empezaré a / seguiré + gerundio"],
    model: [
      "Querido yo de 2036:",
      "Te escribo desde mi cuarto en Bogotá. Está lloviendo, como siempre, y estoy tomando un chocolate caliente. Ahora tengo 28 años y estoy aprendiendo español.",
      "Creo que dentro de diez años hablarás español sin problemas y seguramente trabajarás para una empresa internacional. A lo mejor tendrás una casa con jardín y un perro. Seguro que habrá robots en todas partes, pero tú seguirás escribiendo cartas a mano.",
      "Te prometo dos cosas: dejaré de comprar ropa que no necesito y empezaré a ahorrar para viajar por América Latina. Si cumplo estas promesas, podrás conocer Perú, Chile y Argentina. Si no las cumplo, perdóname.",
      "Un consejo: sigue aprendiendo cosas nuevas y ríete mucho. Un abrazo.",
    ],
    checklist: [
      "Usas al menos cinco verbos en futuro, dos de ellos irregulares.",
      "Escribes al menos dos condiciones con si + presente (no futuro después de si).",
      "Haces al menos una promesa con _te prometo que_.",
      "Usas una perífrasis (dejar de, empezar a, seguir + gerundio).",
      "Revisas las tildes del futuro (todas excepto _nosotros_).",
    ],
    words: [80, 130],
  },
  speaking: {
    intro: "Prepara con las notas, tapa la pantalla y grábate. Escucha la grabación pensando en las vocales átonas.",
    tasks: [
      {
        title: "Mi ciudad en 2045",
        prompt: "Eres el invitado del programa «Bogotá mañana», pero hablas de tu propia ciudad. Haz al menos cuatro predicciones sobre el transporte, el trabajo y la tecnología, y añade una condición.",
        prep: ["En 2045 habrá…", "La gente trabajará…", "Seguro que… / A lo mejor…", "Dejaremos de… / Seguiremos…", "Si…, …"],
        seconds: 60,
        model: "En 2045, en mi ciudad habrá un tren rápido hasta el aeropuerto y casi no habrá carros de gasolina. La gente trabajará desde casa tres días por semana, así que el centro estará más tranquilo. Seguro que dejaremos de usar efectivo, pero seguiremos tomando café en las mismas cafeterías. Si el ayuntamiento planta más árboles, la ciudad será mucho más agradable en verano.",
        selfCheck: ["Uso al menos dos irregulares (habrá, tendremos, podremos…).", "La condición va con si + presente.", "Las palabras largas suenan completas, sin vocales perdidas."],
      },
      {
        title: "Promesas para salvar la amistad",
        prompt: "Olvidaste el cumpleaños de tu mejor amigo. Te llama, un poco enfadado. Discúlpate y haz tres promesas concretas.",
        prep: ["Perdóname, de verdad…", "Te prometo que…", "Te lo juro.", "Si quieres, el sábado…", "¡Nunca más!"],
        seconds: 40,
        model: "¡Perdóname, de verdad! No tengo excusa. Te prometo que el sábado te invitaré a cenar a tu restaurante favorito. También te prometo que pondré una alarma en el celular para el año que viene. Y si quieres, después iremos a bailar. ¡Te lo juro, nunca más!",
        selfCheck: ["Hago tres promesas distintas con futuro.", "Uso _te prometo que_ y _te lo juro_.", "Mi tono suena sincero."],
      },
      {
        title: "Cadena de condiciones",
        prompt: "Empieza con «Si gano la lotería…» y encadena consecuencias: cada resultado se convierte en la siguiente condición. Llega lo más lejos que puedas.",
        prep: ["Si gano la lotería, dejaré de trabajar.", "Si dejo de trabajar, tendré mucho tiempo.", "Si tengo mucho tiempo, …"],
        seconds: 45,
        model: "Si gano la lotería, dejaré de trabajar. Si dejo de trabajar, tendré mucho tiempo libre. Si tengo mucho tiempo libre, viajaré por toda Colombia. Si viajo por Colombia, conoceré a mucha gente. Si conozco a mucha gente, a lo mejor me enamoraré. Y si me enamoro… ¡volveré a trabajar para pagar la boda!",
        selfCheck: ["Cada condición está en presente, cada resultado en futuro.", "Hablo sin parar más de dos segundos.", "Cambio la forma del verbo correctamente al pasar del resultado a la condición."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo, juega con el futuro.",
    cards: [
      { move: "Predice", task: "Haz tres predicciones sobre tu profesor o profesora para el año que viene (trabajo, viajes, hábitos) y pregúntale si está de acuerdo.", phrases: ["Creo que el año que viene…", "Seguro que…", "A lo mejor…", "¿Tú crees? / ¿Usted cree?"] },
      { move: "Promete", task: "Promete dos cosas concretas para tu español en el próximo mes.", phrases: ["Te prometo que…", "Empezaré a…", "Dejaré de…"] },
      { move: "Negocia", task: "Propón un plan para la próxima clase con condiciones: qué haréis si hay tiempo, si llueve, si estás cansado.", phrases: ["Si tenemos tiempo, …", "Si no puedo conectarme, te escribiré…", "Si quieres, …"] },
      { move: "Reacciona", task: "Escucha las predicciones de tu profesor sobre ti y reacciona a cada una con una fórmula distinta.", phrases: ["¡Ojalá!", "¡Eso espero!", "Ya veremos.", "¡Qué va!"] },
    ],
    bring: "Tu carta al yo del futuro: léela en voz alta en dos minutos.",
  },
  quiz: {
    items: [
      { type: "choice", q: "El año que viene mis amigos y yo ___ un viaje a Leticia.", options: ["haremos", "haceremos", "hacemos a"], answer: 0, why: "_Hacer_ → **har**-emos." },
      { type: "choice", q: "Elige la frase correcta.", options: ["Si tengo vacaciones en julio, iré a Cartagena.", "Si tendré vacaciones en julio, iré a Cartagena.", "Si tengo vacaciones en julio, fui a Cartagena."], answer: 0, why: "_Si_ + presente, resultado en futuro." },
      { type: "listen", q: "¿Qué hace la persona?", audio: "Te lo prometo: el lunes te devolveré el computador.", voice: "es-CO-m", options: ["Una promesa", "Una predicción sobre el tiempo", "Una condición"], answer: 0, why: "_Te lo prometo_ + futuro: promesa." },
      { type: "listen", q: "¿Qué pasará si llueve?", audio: "Si llueve el domingo, no habrá ciclovía y nos quedaremos viendo películas.", voice: "es-MX-f", options: ["Verán películas en casa.", "Irán a la ciclovía.", "Saldrán a cenar."], answer: 0, why: "_Nos quedaremos viendo películas_." },
      { type: "gap", q: "Mañana no ___ (yo, poder) ir a la reunión, pero te ___ (yo, decir) todo por correo.", answers: [["podré"], ["diré"]], why: "_Poder_ → **podr**é; _decir_ → **dir**é." },
      { type: "gap", q: "¿A qué hora ___ ustedes de la oficina el viernes? (salir)", answers: [["saldrán"]], why: "_Salir_ → **saldr**-án." },
      { type: "transform", source: "Voy a ahorrar dinero. Voy a comprar una moto.", instruction: "Une las dos ideas con si + presente y futuro.", answers: ["Si ahorro dinero, compraré una moto.", "Si ahorro dinero, me compraré una moto."], why: "Condición en presente (_ahorro_), resultado en futuro (_compraré_)." },
      { type: "transform", source: "Ahora sigo viviendo con mis papás.", instruction: "Cámbiala al futuro: «En 2030…».", answers: ["En 2030 seguiré viviendo con mis papás."], why: "_Seguir_ en futuro: **seguiré** + gerundio." },
      { type: "order", words: ["Seguramente", "tendremos", "robots", "en", "casa."], alt: ["Tendremos robots en casa seguramente."], why: "_Seguramente_ + futuro irregular (_tener → tendremos_)." },
      { type: "error", sentence: "Mañana a esta hora estaré volar a Madrid.", answers: ["Mañana a esta hora estaré volando a Madrid."], why: "Para una acción en curso en un momento del futuro: _estar_ en futuro + **gerundio**." },
      { type: "error", sentence: "Dentro de veinte años no habrán coches de gasolina.", answers: ["Dentro de veinte años no habrá coches de gasolina."], why: "_Habrá_ es siempre singular." },
      { type: "error", sentence: "Mis abuelos venirán a Bogotá en Navidad.", answers: ["Mis abuelos vendrán a Bogotá en Navidad."], why: "_Venir_ es de la familia de la d: **vendr**-án." },
      { type: "open", prompt: "Escribe dos predicciones sobre la tecnología en tu vida dentro de diez años y una promesa relacionada.", model: "Dentro de diez años no tendré carro: usaré carros autónomos compartidos. Seguramente trabajaré con inteligencia artificial todos los días. Te prometo que pasaré menos tiempo con el celular.", checklist: ["Dos verbos en futuro", "Vocabulario de tecnología", "Una promesa con te prometo que"] },
    ],
  },
  complete: {
    canNow: [
      "Formar el futuro simple regular y los irregulares más frecuentes.",
      "Hacer predicciones y promesas, y reaccionar a las de otros.",
      "Expresar condiciones reales con si + presente.",
      "Elegir entre futuro, ir a y presente según la seguridad y el tipo de plan.",
      "Distinguir planes, predicciones y condiciones en un texto.",
      "Pronunciar palabras largas sin reducir las vocales átonas.",
    ],
    review: [
      "Las tres familias: podr-/sabr-/querr-/habr-, tendr-/pondr-/saldr-/vendr-, har-/dir-.",
      "Habrá: siempre singular.",
      "Después de si condicional, nunca futuro.",
      "Tilde en todas las formas del futuro excepto nosotros.",
    ],
  },
  related: [
    { path: "/sistema-verbal/futuro-simple-indicativo", label: "Sistema verbal · Futuro simple" },
    { path: "/si-pasa-esto", label: "Si pasa esto… · condiciones reales" },
  ],
};
