import type { Module } from "../../types";

export const a2w14: Module = {
  id: "a2-14",
  level: "a2",
  week: 14,
  kind: "core",
  title: "¿Podría ayudarme?",
  subtitle: "Pedir con cortesía, resolver gestiones en un hotel, una terminal o un aeropuerto, y reclamar sin perder la amabilidad.",
  stop: { place: "Salento, Eje Cafetero", country: "Colombia" },
  minutes: 85,
  newObjectives: [
    "a2.gram.condicional-cortesia",
    "a2.voc.hotel-transporte",
    "a2.pron.cortesia-entonacion",
    "a2.fun.reclamar",
    "a2.wri.correo-reserva",
    "a2.read.condiciones",
  ],
  reviewObjectives: ["a2.gram.doler", "a2.gram.consejos-deberias", "a2.fun.medico", "a2.gram.estar-gerundio"],
  prerequisites: ["a2-13"],
  goal: {
    canDo: "Al final de esta semana puedes pedir cosas con cortesía (podría, me gustaría, quería), resolver gestiones en un hotel, una terminal o un aeropuerto, reclamar un problema de forma amable y escribir un correo breve para reservar o cambiar una reserva.",
    canDoEn: "By the end of this week, you can make polite requests (podría, me gustaría, quería), deal with hotels, bus stations and airports, complain about a problem politely and write a short formal email to book or change a reservation.",
    steps: [
      "Aprende el condicional de cortesía y por qué suaviza una petición.",
      "Ordena una reclamación en cuatro pasos: atención, problema, petición y cierre.",
      "Aprende el vocabulario de hoteles y viajes, con las palabras que cambian de país.",
      "Entrena la entonación amable: la curva suave que convierte una orden en una petición.",
      "Escucha a dos viajeros que llegan a un hostal de Salento con un problema.",
      "Lee las condiciones de un hostal y encuentra horarios, precios y normas.",
      "Escribe un correo para cambiar una reserva y grábate resolviendo problemas.",
    ],
  },
  theory: {
    intro: "Viajar es pedir: una habitación, un cambio de fecha, un vaso de agua, una solución. En español, la diferencia entre sonar amable y sonar brusco está muchas veces en **una sola forma verbal**: no es lo mismo _Quiero otra habitación_ que _¿Sería posible cambiar de habitación?_. Esta semana estamos en **Salento**, en el Eje Cafetero colombiano, una región famosa por su café, sus casas de colores y una cortesía muy cuidada.",
    parts: [
      {
        heading: "El condicional de cortesía: podría, me gustaría, sería",
        body: [
          "El **condicional** se forma con el infinitivo completo + **-ía, -ías, -ía, -íamos, -íais, -ían**: hablar → **hablaría**, ser → **sería**, gustar → **gustaría**. Todas las terminaciones llevan tilde en la **í**.",
          "Los verbos irregulares usan **la misma raíz que el futuro** (semana 12): poder → **podr**ía, tener → **tendr**ía, hacer → **har**ía, decir → **dir**ía, querer → **querr**ía, salir → **saldr**ía, venir → **vendr**ía. Si sabes _podré_, ya sabes _podría_.",
          "¿Por qué el condicional suena más amable? Porque presenta la petición como algo **hipotético**, no como una orden. _¿Puede ayudarme?_ ya es correcto, pero _¿Podría ayudarme?_ deja más espacio a la otra persona para decir que no. Es como poner un cojín entre tu deseo y la otra persona.",
          "Las fórmulas más útiles son cuatro: **¿Podría + infinitivo?** (pedir una acción), **Me gustaría + infinitivo o sustantivo** (decir lo que quieres), **¿Sería posible + infinitivo?** (preguntar si se puede) y **¿Tendría…?** (preguntar si hay algo).",
          "Con el condicional también das consejos suaves: **Yo que tú, haría la reserva hoy**. Y recuerda **deberías / tendrías que** de la semana pasada: son condicionales de los verbos _deber_ y _tener_.",
        ],
        support: [
          "The conditional ('would') softens requests in Spanish just like in English: _¿Podría…?_ = 'Could you…?', _Me gustaría…_ = 'I would like…'.",
          "Irregular conditionals share their stem with the future: _podré → podría_, _tendré → tendría_, _haré → haría_.",
          "_Gustar_ still works like _gustar_: _me gustaría_, _nos gustaría_, _les gustaría_. The verb stays singular before an infinitive.",
        ],
        table: {
          caption: "Del más directo al más cortés",
          head: ["Función", "Directo", "Neutro", "Cortés"],
          rows: [
            ["pedir algo", "Deme la llave.", "¿Me da la llave?", "¿Me podría dar la llave?"],
            ["pedir ayuda", "Ayúdeme.", "¿Me ayuda?", "¿Podría ayudarme?"],
            ["decir lo que quieres", "Quiero cambiar la fecha.", "Quería cambiar la fecha.", "Me gustaría cambiar la fecha."],
            ["preguntar si se puede", "¿Puedo pagar con tarjeta?", "¿Se puede pagar con tarjeta?", "¿Sería posible pagar con tarjeta?"],
            ["preguntar si hay algo", "¿Hay toallas?", "¿Tiene toallas?", "¿Tendría una toalla más?"],
          ],
        },
        examples: [
          { es: "¿Podría decirme a qué hora sale el bus a Armenia?", en: "Could you tell me what time the bus to Armenia leaves?" },
          { es: "Nos gustaría una habitación con vista a las montañas.", en: "We would like a room with a view of the mountains." },
          { es: "¿Sería posible dejar las maletas aquí hasta la tarde?", en: "Would it be possible to leave our bags here until the afternoon?" },
          { es: "¿Tendría un cargador para este celular?", en: "Would you have a charger for this phone?" },
          { es: "¿Podrías pasarme el mapa? (tú)", en: "Could you pass me the map? (informal)" },
        ],
        mistakes: [
          { wrong: "¿Puedería ayudarme?", right: "¿Podría ayudarme?", why: "La raíz es la del futuro: **podr-**. No existe _puedería_." },
          { wrong: "Me gustaría a reservar una mesa.", right: "Me gustaría reservar una mesa.", why: "_Gustaría_ va directamente con el infinitivo, sin _a_." },
          { wrong: "¿Podrías ayudarme, señora?", right: "¿Podría ayudarme, señora?", why: "Con _señora_ hablas de usted: **podría** (sin -s). _Podrías_ es de tú." },
          { wrong: "¿Podría usted me decir la hora?", right: "¿Me podría decir la hora? / ¿Podría decirme la hora?", why: "El pronombre va delante del verbo conjugado o pegado al infinitivo, nunca en medio." },
        ],
        tip: "Si dudas, empieza con **¿Podría…?**: funciona para casi todo, con cualquier persona y en cualquier país.",
      },
      {
        heading: "Quería: el pasado que también es cortés",
        body: [
          "En tiendas, hoteles y ventanillas oyes muchísimo **Quería…**: _Quería una habitación para esta noche_, _Quería preguntar una cosa_. Es imperfecto, pero **no habla del pasado**: el deseo es de ahora. El pasado sirve como distancia, igual que el condicional.",
          "Solo funciona así con **querer** (y con _venir_ en _Venía a…_, más formal). Con _gustar_ no: _Me gustaba una habitación_ significa que antes te gustaba. Para el presente amable usa **me gustaría**.",
          "En un nivel más formal oirás **Quisiera…** (_Quisiera hablar con el encargado_). Por ahora basta con reconocerlo: es todavía más cortés que _quería_.",
          "En Colombia hay además una fórmula muy local: **¿Me regala…?** (_¿Me regala un tinto?_, _¿Me regala su nombre?_). No significa que sea gratis: es una manera amable de pedir. Y para disculparse, muchos colombianos dicen **Qué pena con usted** en lugar de _lo siento_.",
        ],
        support: [
          "_Quería_ (imperfect) is used for polite requests in the present, like English 'I wanted to ask…'. It only works with _querer_: for 'I would like' with _gustar_, use _me gustaría_, never _me gustaba_.",
          "In Colombia, _¿Me regala…?_ ('would you give me…?') is a normal, polite way to ask for something you are going to pay for.",
        ],
        examples: [
          { es: "Buenas tardes, quería un tiquete para Pereira.", en: "Good afternoon, I'd like a ticket to Pereira." },
          { es: "Quería preguntarle una cosa sobre el desayuno.", en: "I wanted to ask you something about breakfast." },
          { es: "¿Me regala un tinto, por favor? (Colombia)", en: "Could I have a black coffee, please? (Colombia)" },
          { es: "Qué pena con usted, se me olvidó la llave. (Colombia)", en: "I'm so sorry, I forgot the key. (Colombia)" },
        ],
        mistakes: [
          { wrong: "Me gustaba una habitación más tranquila.", right: "Me gustaría una habitación más tranquila.", why: "_Me gustaba_ es un gusto del pasado. Para pedir ahora: **me gustaría**." },
          { wrong: "Estoy queriendo cambiar mi reserva.", right: "Quería cambiar mi reserva.", why: "_Querer_ casi nunca va con estar + gerundio. Para pedir con cortesía: **quería** o **me gustaría**." },
        ],
      },
      {
        heading: "Reclamar sin perder la amabilidad",
        body: [
          "Una buena reclamación en español tiene cuatro pasos. **1. Llamar la atención**: _Perdone_, _Disculpe_, _Buenas tardes, mire…_ **2. Explicar el problema**: _La ducha no funciona_, _Hay un error en la reserva_, _Me han cobrado dos veces_. **3. Pedir una solución**: _¿Podría…?_, _¿Sería posible…?_, _Me gustaría…_ **4. Cerrar**: _Muchas gracias_, _Muy amable_, _Le agradezco la ayuda_.",
          "Para describir el problema usas lo que ya sabes: el **presente** (_el aire acondicionado no funciona_), **estar + gerundio** para algo que pasa ahora mismo (_el baño está goteando_, _estoy esperando desde las tres_) y el **perfecto** para lo que acaba de pasar (_he perdido la llave_, _me han dado otra habitación_).",
          "La persona que te atiende responderá con fórmulas fijas: **Disculpe las molestias**, **Ahora mismo lo solucionamos**, **Lo siento, no es posible, pero le puedo ofrecer…** Si la primera solución no te sirve, negocia con suavidad: **¿Y no tendría otra opción?**",
          "Reclamar con cortesía no significa aceptar cualquier cosa: significa ser firme con el problema y amable con la persona.",
        ],
        support: [
          "A polite complaint = attention-getter + problem + request + thanks. The conditional goes in the request, not in the problem: say clearly what is wrong, then ask softly.",
          "_Disculpe las molestias_ = 'Sorry for the inconvenience' — you will hear it, you don't need to say it.",
        ],
        table: {
          caption: "Una reclamación completa en el hotel",
          head: ["Paso", "Ejemplo"],
          rows: [
            ["1. Atención", "Buenas noches, disculpe."],
            ["2. Problema", "Estoy en la habitación 12 y el agua caliente no funciona."],
            ["3. Petición", "¿Podría mandar a alguien? Y si no es posible, ¿sería posible cambiar de habitación?"],
            ["4. Cierre", "Muchas gracias, muy amable."],
          ],
        },
        examples: [
          { es: "Perdone, hay un error en la factura: nos han cobrado el desayuno dos veces.", en: "Excuse me, there's a mistake on the bill: we've been charged for breakfast twice." },
          { es: "Disculpe, los vecinos están haciendo mucho ruido. ¿Podría hablar con ellos?", en: "Excuse me, the neighbours are making a lot of noise. Could you talk to them?" },
          { es: "—Lo siento, no es posible. —¿Y no tendría otra opción?", en: "I'm sorry, it's not possible. — And wouldn't you have another option?" },
        ],
        mistakes: [
          { wrong: "¡La ducha no funciona! ¡Quiero otra habitación!", right: "Perdone, la ducha no funciona. ¿Sería posible cambiar de habitación?", why: "Sin saludo y con _quiero_ suena a orden. Llama la atención primero y pide con el condicional." },
          { wrong: "Me he reservado una habitación doble.", right: "He reservado una habitación doble.", why: "_Reservar_ no es reflexivo: **he reservado**, sin _me_." },
        ],
      },
      {
        heading: "Viajes: palabras que cambian de país y el correo formal",
        body: [
          "Muchas palabras de viaje cambian según el país. En Colombia compras un **tiquete** y en el aeropuerto te dan el **pasabordo**; en España es un **billete** y la **tarjeta de embarque**; en México, un **boleto** y el **pase de abordar**. Todas se entienden en todas partes, pero es útil reconocerlas.",
          "Para reservar o cambiar algo por escrito, el correo formal tiene una estructura fija. **Saludo**: _Estimados señores:_ o _Estimada señora Gómez:_ (con dos puntos). **Motivo**: _Les escribo para…_ / _Me pongo en contacto con ustedes porque…_ **Petición**: _Me gustaría…_, _¿Sería posible…?_, _¿Podrían confirmarme…?_ **Despedida**: _Quedo atento/atenta a su respuesta._ + _Un cordial saludo_ o _Atentamente_.",
          "En el correo formal usas **usted / ustedes** de principio a fin. Atención: en América _ustedes_ es el plural de tú y de usted; en España, entre amigos, se usa _vosotros_, pero a un hotel siempre le escribes de **ustedes**.",
        ],
        support: [
          "Formal emails in Spanish open with _Estimado/a…_ followed by a colon (not a comma) and close with _Un cordial saludo_ or _Atentamente_.",
          "Never mix _tú_ and _usted_ in the same email: choose _usted/ustedes_ for hotels, airlines and companies.",
        ],
        table: {
          caption: "La misma cosa, cuatro países",
          head: ["", "Colombia", "México", "España", "Argentina"],
          rows: [
            ["ticket", "el tiquete", "el boleto", "el billete", "el pasaje / el boleto"],
            ["boarding pass", "el pasabordo", "el pase de abordar", "la tarjeta de embarque", "la tarjeta de embarque"],
            ["suitcase", "la maleta", "la maleta", "la maleta", "la valija"],
            ["single room", "la habitación sencilla", "la habitación sencilla", "la habitación individual", "la habitación simple"],
            ["long-distance bus", "el bus", "el autobús / el camión", "el autobús", "el micro"],
          ],
        },
        examples: [
          { es: "Estimados señores: les escribo para cambiar la fecha de mi reserva.", en: "Dear Sir or Madam: I'm writing to change the date of my booking." },
          { es: "¿Podrían confirmarme si el desayuno está incluido?", en: "Could you confirm whether breakfast is included?" },
          { es: "Quedo atenta a su respuesta. Un cordial saludo.", en: "I look forward to your reply. Kind regards. (woman writing)" },
        ],
        mistakes: [
          { wrong: "Hola amigo, quiero cambiar mi reserva.", right: "Estimados señores: me gustaría cambiar mi reserva.", why: "En un correo a una empresa el saludo es formal y la petición va en condicional." },
          { wrong: "Estimado señor, ¿puedes confirmarme la hora?", right: "Estimado señor: ¿podría confirmarme la hora?", why: "Con _estimado señor_ hablas de usted: **podría**. Y después del saludo van dos puntos." },
        ],
        tip: "Lee el correo en voz alta antes de enviarlo: si suena como una orden, cambia _quiero_ por _me gustaría_ y _puede_ por _podría_.",
      },
    ],
  },
  grammar: {
    intro: "Practica las formas del condicional y el imperfecto de cortesía en situaciones de viaje.",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "La forma amable",
        prompt: "Elige la forma correcta para cada situación.",
        items: [
          { q: "Hablas con un policía en la plaza de Salento: «Disculpe, ¿___ decirme dónde está la terminal?»", options: ["podría", "podrías", "puedería"], answer: 0, why: "Con un desconocido usas usted: **podría**. _Podrías_ es de tú y _puedería_ no existe." },
          { q: "En la recepción: «Buenas noches, ___ una habitación para dos personas».", options: ["quería", "quise", "estoy queriendo"], answer: 0, why: "**Quería** es el imperfecto de cortesía: un deseo de ahora dicho con suavidad." },
          { q: "«Nos ___ cambiar la fecha del vuelo.»", options: ["gustaría", "gustaríamos", "gustarían"], answer: 0, why: "_Gustar_ concuerda con lo que gusta (_cambiar la fecha_, singular): **nos gustaría**." },
          { q: "«¿___ posible dejar la maleta aquí hasta las cuatro?»", options: ["Sería", "Sería a", "Estaría"], answer: 0, why: "La fórmula es **¿Sería posible + infinitivo?**, sin preposición." },
          { q: "En una tienda: «Disculpe, ¿___ protector solar?»", options: ["tendría", "tenería", "tenía"], answer: 0, why: "_Tener_ es irregular: **tendr**ía, como _tendré_ en futuro." },
          { q: "A tu amiga, de tú: «¿Me ___ tu cargador un momento?»", options: ["prestarías", "prestaría", "prestas a"], answer: 0, why: "Con tú, la terminación lleva **-s**: prestar**ías**." },
        ],
      },
      {
        id: "g2",
        type: "gap",
        title: "Conjuga con cortesía",
        prompt: "Completa con el condicional del verbo entre paréntesis.",
        items: [
          { q: "¿___ (poder, ustedes) enviarme la factura por correo electrónico?", answers: [["Podrían"]], why: "Ustedes → **podrían** (raíz _podr-_ + _-ían_)." },
          { q: "¿Te ___ (importar) cerrar la ventana? Hace frío.", answers: [["importaría"]], why: "_Importar_ funciona como _gustar_: **te importaría** + infinitivo." },
          { q: "Yo que tú, ___ (hacer) la reserva hoy: el fin de semana hay mucha gente.", answers: [["haría"]], why: "_Hacer_ es irregular: **har**ía. _Yo que tú_ + condicional da un consejo suave." },
          { q: "¿A ustedes les ___ (gustar) ir al valle de Cocora mañana?", answers: [["gustaría"]], why: "Les **gustaría** + infinitivo: el verbo va en singular." },
          { q: "¿___ (tener, usted) una habitación más tranquila, lejos de la calle?", answers: [["Tendría"]], why: "Usted → **tendría**, con la raíz irregular _tendr-_." },
          { q: "Señor, ¿me ___ (decir) su nombre completo, por favor?", answers: [["diría", "podría decir"]], why: "_Decir_ → **dir**ía. También es natural _¿me podría decir…?_" },
        ],
      },
      {
        id: "g3",
        type: "transform",
        title: "Suaviza la petición",
        prompt: "Transforma la frase directa en una petición cortés de usted.",
        items: [
          { source: "Deme la llave de la habitación.", instruction: "Usa ¿podría…?", answers: ["¿Me podría dar la llave de la habitación?", "¿Podría darme la llave de la habitación?", "¿Me podría dar la llave de la habitación, por favor?", "¿Podría darme la llave de la habitación, por favor?"], why: "Orden → pregunta con **podría** + infinitivo. El pronombre va delante (_me podría_) o pegado (_darme_)." },
          { source: "Quiero un taxi para el aeropuerto.", instruction: "Usa me gustaría o quería.", answers: ["Me gustaría un taxi para el aeropuerto.", "Quería un taxi para el aeropuerto.", "Me gustaría pedir un taxi para el aeropuerto.", "Quería pedir un taxi para el aeropuerto."], why: "_Quiero_ suena exigente; **me gustaría** o **quería** expresan el mismo deseo con distancia." },
          { source: "¿Puedo pagar con tarjeta?", instruction: "Usa ¿sería posible…?", answers: ["¿Sería posible pagar con tarjeta?"], why: "**¿Sería posible + infinitivo?** pregunta si algo se puede hacer sin pedir permiso directamente." },
          { source: "Cámbieme el asiento.", instruction: "Usa ¿podría…?", answers: ["¿Podría cambiarme el asiento?", "¿Me podría cambiar el asiento?", "¿Podría cambiarme el asiento, por favor?", "¿Me podría cambiar el asiento, por favor?"], why: "El imperativo _cámbieme_ pasa a **podría + cambiarme** (o _me podría cambiar_)." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Aprende estas palabras en bloques: el verbo con su compañero (_hacer una reserva_, _perder el bus_) sale más rápido en una gestión real.",
    groups: [
      {
        title: "En el hotel o el hostal",
        items: [
          { es: "hacer / cancelar una reserva", en: "to make / cancel a booking" },
          { es: "una habitación sencilla / doble", en: "a single / double room (sencilla in Latin America, individual in Spain)" },
          { es: "con desayuno incluido", en: "with breakfast included" },
          { es: "la llegada y la salida (el check-in y el check-out)", en: "check-in and check-out" },
          { es: "dejar el equipaje en recepción", en: "to leave your luggage at reception" },
          { es: "la salida tardía", en: "late check-out" },
          { es: "el agua caliente / el aire acondicionado", en: "hot water / air conditioning" },
          { es: "una toalla más / una almohada más", en: "an extra towel / an extra pillow" },
          { es: "estar sujeto a disponibilidad", en: "to be subject to availability" },
        ],
      },
      {
        title: "En la terminal y el aeropuerto",
        items: [
          { es: "un tiquete (CO) / billete (ES) / boleto (MX) de ida y vuelta", en: "a return ticket" },
          { es: "facturar la maleta (ES) / documentar la maleta (MX)", en: "to check in your suitcase" },
          { es: "el equipaje de mano", en: "hand luggage" },
          { es: "el pasabordo (CO) / la tarjeta de embarque (ES)", en: "the boarding pass" },
          { es: "la puerta de embarque", en: "the boarding gate" },
          { es: "El vuelo está retrasado. / Sale con retraso.", en: "The flight is delayed." },
          { es: "perder el vuelo / el bus", en: "to miss the flight / the bus" },
          { es: "un asiento de ventana / de pasillo", en: "a window / an aisle seat" },
          { es: "la terminal de transportes (CO)", en: "the bus station (Colombia)" },
        ],
      },
      {
        title: "Problemas y soluciones",
        items: [
          { es: "No funciona. / Está roto.", en: "It doesn't work. / It's broken." },
          { es: "Hay un error en la reserva.", en: "There's a mistake in the booking." },
          { es: "Me han cobrado de más.", en: "I've been overcharged." },
          { es: "cambiar de habitación", en: "to change rooms" },
          { es: "pedir un reembolso", en: "to ask for a refund" },
          { es: "hablar con el encargado / la encargada", en: "to speak to the manager" },
          { es: "Disculpe las molestias.", en: "Sorry for the inconvenience." },
          { es: "Ahora mismo lo solucionamos.", en: "We'll sort it out right away." },
          { es: "Qué pena con usted. (CO)", en: "I'm so sorry. (Colombia)" },
          { es: "A la orden. (CO)", en: "You're welcome / At your service. (Colombia)" },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "Problema y petición",
        prompt: "Une cada problema con la petición más lógica.",
        pairs: [
          { left: "El aire acondicionado hace un ruido horrible.", right: "¿Sería posible cambiar de habitación?" },
          { left: "Mi vuelo sale a las seis de la mañana.", right: "¿Me podría pedir un taxi para las cuatro?" },
          { left: "Llegamos a las nueve y el check-in es a las tres.", right: "¿Podríamos dejar el equipaje en recepción?" },
          { left: "En la factura aparecen dos desayunos de más.", right: "¿Podría revisar la cuenta, por favor?" },
          { left: "Mi avión sale tarde y no quiero esperar en la calle.", right: "¿Sería posible tener la salida tardía?" },
        ],
        why: "Cada petición responde al problema concreto: un ruido se soluciona cambiando de habitación; un error en la factura, revisando la cuenta; llegar temprano, dejando el equipaje.",
      },
      {
        id: "v2",
        type: "context",
        title: "¿Qué palabra necesitas?",
        prompt: "Lee la situación y elige la palabra adecuada.",
        items: [
          { context: "Estás en el aeropuerto de Bogotá. La agente te pide el documento para subir al avión.", q: "Ella dice:", options: ["Su pasabordo, por favor.", "Su reembolso, por favor.", "Su recepción, por favor."], answer: 0, why: "En Colombia la tarjeta de embarque se llama **pasabordo**." },
          { context: "Solo llevas una mochila pequeña en el avión.", q: "Llevas…", options: ["equipaje de mano", "una maleta facturada", "una salida tardía"], answer: 0, why: "Lo que llevas contigo en la cabina es el **equipaje de mano**." },
          { context: "Llegas a la terminal a las 8:05. Tu bus salió a las 8:00.", q: "¿Qué te pasó?", options: ["Perdí el bus.", "Facturé el bus.", "Cancelé el bus."], answer: 0, why: "**Perder el bus / el vuelo** = llegar tarde y no poder subir." },
          { context: "Pagaste 120.000 pesos y la habitación cuesta 100.000.", q: "Dices en recepción:", options: ["Creo que me han cobrado de más.", "Creo que hay salida tardía.", "Creo que el desayuno está incluido."], answer: 0, why: "**Cobrar de más** = cobrar más dinero del correcto." },
          { context: "Un recepcionista en Salento te da la llave y dices «gracias».", q: "Él responde, muy a la colombiana:", options: ["A la orden.", "Qué pena con usted.", "Disculpe las molestias."], answer: 0, why: "**A la orden** es la respuesta típica colombiana a _gracias_. _Qué pena_ es para disculparse." },
        ],
      },
      {
        id: "v3",
        type: "gap",
        title: "Un mensaje al hostal",
        prompt: "Completa con las palabras del banco. Sobra una.",
        bank: ["reserva", "incluido", "retrasado", "equipaje", "ventana", "sujeta"],
        items: [
          { q: "Hola, tengo una ___ para dos noches a nombre de Klein.", answers: [["reserva"]], why: "Tener / hacer una **reserva**." },
          { q: "Mi vuelo está ___ y voy a llegar a medianoche.", answers: [["retrasado"]], why: "Un vuelo que sale tarde está **retrasado**." },
          { q: "¿El desayuno está ___ en el precio?", answers: [["incluido"]], why: "_Desayuno_ es masculino: **incluido**." },
          { q: "¿Puedo dejar el ___ en recepción antes del check-in?", answers: [["equipaje"]], why: "**Dejar el equipaje** = dejar las maletas." },
          { q: "La salida tardía está ___ a disponibilidad.", answers: [["sujeta"]], why: "_Salida_ es femenino: **sujeta a disponibilidad**." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "Entonación de cortesía: una curva suave y un ritmo amable",
    explanation: [
      "Las mismas palabras pueden sonar a petición o a orden. Lo que decide es la **melodía**. Una petición amable es una pregunta: la voz **sube suavemente al final** (_¿Me podría ayudar?_ ↗). Una orden baja de golpe y suena corta (_Ayúdeme._ ↘).",
      "El **ritmo** también cuenta. La cortesía va un poco más despacio y sin golpes fuertes. Una pequeña pausa después de _Perdone…_ o _Disculpe…_ prepara a la otra persona: le dices «voy a pedirte algo».",
      "**Por favor** al final de la frase va bajo y suave, como un adorno. Si lo dices fuerte y separado (_¡Por favor!_), puede sonar impaciente, casi una queja.",
      "Cada región tiene su música: la entonación **paisa** del Eje Cafetero es famosa por «cantada», la rioplatense alarga las sílabas acentuadas y la caribeña va más rápido. Pero en todas las variedades una petición amable suena más suave y más lenta que una orden.",
    ],
    support: [
      "A polite request rises gently at the end, like a question; a command falls sharply. Slow down a little and pause after _Perdone…_ or _Disculpe…_.",
      "Say _por favor_ low and soft at the end. A loud, separate _¡Por favor!_ can sound impatient.",
    ],
    table: {
      head: ["Suena brusco", "Suena amable", "¿Qué cambia?"],
      rows: [
        ["Deme la llave. ↘", "¿Me podría dar la llave? ↗", "Pregunta y curva que sube"],
        ["¡Otra toalla! ↘", "Perdone… ¿me trae otra toalla? ↗", "Pausa inicial y pregunta"],
        ["¡Por favor! El recibo.", "El recibo, por favor. (suave)", "_Por favor_ bajo, al final"],
      ],
    },
    perceive: {
      id: "p1",
      type: "listen",
      title: "¿Petición u orden?",
      prompt: "Escucha cada frase. Decide si suena a petición amable o a orden directa, y si la voz sube o baja al final.",
      items: [
        { q: "¿Cómo suena?", audio: "¿Me podría dar una toalla más, por favor?", voice: "es-CO-f", options: ["Petición amable", "Orden directa"], answer: 0, why: "Pregunta con _podría_ y la voz sube al final: petición amable." },
        { q: "¿Cómo suena?", audio: "Deme una toalla.", voice: "es-ES-m", options: ["Petición amable", "Orden directa"], answer: 1, why: "Imperativo y curva que baja: suena a orden." },
        { q: "¿La voz sube o baja al final?", audio: "¿Sería posible cambiar de habitación?", voice: "es-MX-f", options: ["Sube", "Baja"], answer: 0, why: "Es una pregunta de sí o no: la curva **sube** al final." },
        { q: "¿La voz sube o baja al final?", audio: "Necesito el recibo ahora.", voice: "es-AR-m", options: ["Sube", "Baja"], answer: 1, why: "Es una afirmación: la voz **baja**. Con _ahora_ suena exigente." },
        { q: "¿Cómo suena?", audio: "Perdone… ¿me ayuda con la maleta?", voice: "es-PE-f", options: ["Petición amable", "Orden directa"], answer: 0, why: "La pausa después de _Perdone…_ y la pregunta suavizan la petición." },
        { q: "¿Cómo suena?", audio: "Cámbieme el asiento.", voice: "es-CO-m", options: ["Petición amable", "Orden directa"], answer: 1, why: "Imperativo con curva descendente: es una orden, aunque sea correcta." },
      ],
    },
    produce: [
      { text: "Perdone… ¿me podría ayudar?", tip: "Haz una pausa corta después de _Perdone_ y deja que la voz suba en _ayudar_.", voice: "es-CO-f" },
      { text: "¿Sería posible dejar las maletas aquí?", tip: "Ritmo tranquilo, sin golpes. La subida final va en _aquí_.", voice: "es-MX-m" },
      { text: "Me gustaría cambiar la fecha de mi reserva, por favor.", tip: "Es una afirmación, así que baja al final, pero _por favor_ va suave y bajo, sin separarlo.", voice: "es-ES-f" },
      { text: "Disculpe, el agua caliente no funciona. ¿Podría mandar a alguien?", tip: "Dos melodías: la primera frase baja (es información), la segunda sube (es la petición).", voice: "es-CO-m" },
      { text: "¿Y no tendría otra opción?", tip: "Para negociar: sube en _opción_ y alarga un poco la _o_ de _otra_. Suena a esperanza, no a queja.", voice: "es-AR-f" },
    ],
    spelling: "Los signos **¿ ?** te avisan desde el principio de que la frase es una pregunta: prepárate para subir la voz al final. Las terminaciones del condicional llevan tilde: podr**í**a, gustar**í**a, ser**í**a.",
  },
  listening: {
    title: "Llegada a un hostal de Salento",
    context: "Paula, argentina, y Diego, mexicano, son amigos y viajan juntos por el Eje Cafetero. Llegan en bus desde Armenia al Hostal La Cafetera, en Salento. En la recepción los atiende Andrés. Escucha cómo resuelven el check-in.",
    speakers: [
      { id: "andres", name: "Andrés", voice: "es-CO-m", role: "recepcionista" },
      { id: "paula", name: "Paula", voice: "es-AR-f", role: "viajera argentina" },
      { id: "diego", name: "Diego", voice: "es-MX-m", role: "viajero mexicano" },
    ],
    script: [
      { speaker: "andres", text: "Buenas tardes, bienvenidos al Hostal La Cafetera. ¿En qué les puedo ayudar?" },
      { speaker: "paula", text: "Buenas tardes. Tenemos una reserva a nombre de Paula Ferreyra: dos noches, habitación doble con dos camas." },
      { speaker: "andres", text: "A ver… Sí, aquí está. Pero en el sistema aparece una habitación sencilla, con una sola cama." },
      { speaker: "diego", text: "Uy, no. En el correo de confirmación dice «doble con dos camas». ¿Podría revisarlo, por favor?" },
      { speaker: "andres", text: "Claro que sí. Qué pena con ustedes. La doble con dos camas está ocupada hasta mañana. Esta noche solo tengo una con cama de matrimonio." },
      { speaker: "paula", text: "Mmm… somos amigos y preferimos camas separadas. ¿No tendría otra opción?" },
      { speaker: "andres", text: "Tengo una habitación familiar con tres camas. Es más cara, pero se la puedo dejar al mismo precio esta noche." },
      { speaker: "diego", text: "¡Qué amable! Perfecto, muchas gracias. Otra cosa: nos gustaría ir mañana al valle de Cocora. ¿A qué hora salen los jeeps?" },
      { speaker: "andres", text: "Los Willys salen de la plaza cada media hora, desde las seis y media. El primero siempre va lleno; es mejor tomar el de las siete." },
      { speaker: "paula", text: "Perdón… ¿me podría traer un vaso de agua? Me duele muchísimo la cabeza." },
      { speaker: "andres", text: "Claro. ¿Se siente mal?" },
      { speaker: "paula", text: "Estoy un poco mareada. El bus desde Armenia tenía muchísimas curvas." },
      { speaker: "andres", text: "Debería descansar un rato y tomar bastante agua. Si quiere, le preparo una aguapanela con limón." },
      { speaker: "diego", text: "Deberías acostarte ya, Pau. Yo subo las maletas." },
      { speaker: "andres", text: "Ah, una cosa más: en este momento están arreglando el agua caliente del segundo piso. En una hora ya funciona." },
      { speaker: "paula", text: "No hay problema. Diego, ¿vos me traés la mochila también? Gracias, Andrés, muy amable." },
      { speaker: "andres", text: "A la orden. Que descansen." },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: no te preocupes por los detalles. Descubre cuál es el problema y cómo termina.",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha una vez y responde.",
          items: [
            { q: "¿Cuál es el problema con la reserva?", options: ["El tipo de habitación no es el correcto.", "La reserva no existe.", "El hostal está cerrado."], answer: 0, why: "Reservaron una doble con dos camas y en el sistema aparece una **sencilla**." },
            { q: "¿Cómo se resuelve?", options: ["Les dan una habitación familiar al mismo precio.", "Pagan más por una habitación familiar.", "Se van a otro hostal."], answer: 0, why: "Andrés dice: _se la puedo dejar al mismo precio esta noche_." },
            { q: "¿Cómo es el tono de la conversación?", options: ["Amable, aunque hay problemas.", "Muy tenso: discuten.", "Frío y muy rápido."], answer: 0, why: "Todos piden con cortesía (_¿Podría revisarlo?_, _¿No tendría otra opción?_) y Andrés se disculpa." },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: ahora atención a los horarios, a la salud de Paula y al agua caliente.",
        exercise: {
          id: "l2",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "¿Qué jeep les recomienda Andrés?", options: ["El de las siete", "El de las seis y media", "El de las siete y media"], answer: 0, why: "_El primero siempre va lleno; es mejor tomar el de las siete_." },
            { q: "¿Qué le pasa a Paula?", options: ["Le duele la cabeza y está mareada.", "Le duele el estómago y tiene fiebre.", "Está cansada y tiene hambre."], answer: 0, why: "_Me duele muchísimo la cabeza_ y _estoy un poco mareada_." },
            { q: "¿Por qué se siente mal, según ella?", options: ["Por las curvas del bus desde Armenia", "Por el café de la mañana", "Por el frío de Salento"], answer: 0, why: "_El bus desde Armenia tenía muchísimas curvas_." },
            { q: "¿Qué le aconseja Andrés?", options: ["Descansar y tomar bastante agua", "Ir al médico enseguida", "Tomar un café"], answer: 0, why: "_Debería descansar un rato y tomar bastante agua_." },
            { q: "¿Qué están arreglando en el hostal?", options: ["El agua caliente del segundo piso", "El aire acondicionado de la habitación", "La puerta de la recepción"], answer: 0, why: "_Están arreglando el agua caliente del segundo piso_; en una hora funciona." },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en para qué sirve cada frase.",
        exercise: {
          id: "l3",
          type: "classify",
          prompt: "¿La frase pide algo con cortesía, da un consejo o describe algo que pasa ahora?",
          categories: ["pedir con cortesía", "dar un consejo", "acción en curso"],
          items: [
            { text: "¿Podría revisarlo, por favor?", cat: 0, why: "**Podría** + infinitivo: petición cortés." },
            { text: "¿No tendría otra opción?", cat: 0, why: "Pregunta negativa con **tendría**: negocia con suavidad." },
            { text: "¿Me podría traer un vaso de agua?", cat: 0 },
            { text: "Debería descansar un rato.", cat: 1, why: "**Debería** + infinitivo: consejo de usted." },
            { text: "Deberías acostarte ya, Pau.", cat: 1, why: "**Deberías**: el mismo consejo, de tú." },
            { text: "Están arreglando el agua caliente.", cat: 2, why: "**Estar + gerundio**: algo que pasa en este momento." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Hostal La Cafetera · Información y condiciones",
    genre: "Página web de un alojamiento",
    frame: "Sección «Antes de llegar» de la web de un hostal en Salento, Quindío.",
    text: [
      "**Llegada y salida.** El check-in es a partir de las 3:00 p. m. y el check-out, hasta las 11:00 a. m. Si llega antes, puede dejar su equipaje en recepción sin costo. La salida tardía (hasta las 2:00 p. m.) cuesta 30.000 pesos y está sujeta a disponibilidad.",
      "**Reservas y cancelaciones.** La cancelación es gratuita hasta 48 horas antes de la llegada. Después de ese plazo, cobramos la primera noche. Para cambiar las fechas, escríbanos un correo con su número de reserva y le responderemos en menos de 24 horas.",
      "**Desayuno.** Está incluido en todas las tarifas y se sirve de 7:00 a 10:00 a. m. Tenemos opción vegetariana. Si tiene alguna alergia, por favor avísenos el día anterior.",
      "**Transporte.** Recogida en la terminal de Armenia: 90.000 pesos por vehículo (hasta cuatro personas), con reserva previa de 24 horas. Los jeeps Willys al valle de Cocora salen de la plaza principal; el hostal no vende los tiquetes.",
      "**Normas de la casa.** No se permite fumar en las habitaciones. Silencio a partir de las 10:00 p. m. Las mascotas son bienvenidas en las habitaciones del jardín, con un suplemento de 20.000 pesos por noche.",
    ],
    glossary: [
      { es: "a partir de", en: "from (a time onwards)" },
      { es: "el plazo", en: "the deadline, the time limit" },
      { es: "la tarifa", en: "the rate, the price" },
      { es: "la recogida", en: "pick-up (service)" },
      { es: "el suplemento", en: "the extra charge" },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee las condiciones y responde.",
        items: [
          { q: "Llegas a Salento a las 10 de la mañana. ¿Qué puedes hacer?", options: ["Dejar la maleta en recepción gratis.", "Entrar en la habitación enseguida.", "Pagar 30.000 pesos para entrar antes."], answer: 0, why: "El check-in es a partir de las 3:00, pero _puede dejar su equipaje en recepción sin costo_." },
          { q: "Cancelas tu reserva un día antes de llegar. ¿Qué pasa?", options: ["Te cobran la primera noche.", "No pagas nada.", "Te cobran todas las noches."], answer: 0, why: "Es gratis solo _hasta 48 horas antes_; después _cobramos la primera noche_." },
          { q: "Viajan tres amigos desde la terminal de Armenia. ¿Cuánto cuesta la recogida?", options: ["90.000 pesos en total", "90.000 pesos por persona", "270.000 pesos"], answer: 0, why: "El precio es **por vehículo**, hasta cuatro personas." },
          { q: "Quieres ir al valle de Cocora. ¿Dónde compras el tiquete del jeep?", options: ["No en el hostal: los jeeps salen de la plaza.", "En la recepción del hostal.", "En la terminal de Armenia."], answer: 0, why: "_El hostal no vende los tiquetes_; los Willys salen de la plaza principal." },
        ],
      },
      {
        id: "r2",
        type: "classify",
        prompt: "Según el texto, ¿cada cosa es gratis, cuesta dinero extra o no está permitida?",
        categories: ["gratis o incluido", "cuesta dinero extra", "no está permitido"],
        items: [
          { text: "el desayuno", cat: 0, why: "_Está incluido en todas las tarifas_." },
          { text: "dejar las maletas antes del check-in", cat: 0, why: "_Sin costo_." },
          { text: "quedarse en la habitación hasta las 2:00 p. m.", cat: 1, why: "La salida tardía cuesta 30.000 pesos." },
          { text: "llevar a tu perro a una habitación del jardín", cat: 1, why: "Las mascotas pagan un suplemento de 20.000 pesos por noche." },
          { text: "fumar en la habitación", cat: 2, why: "_No se permite fumar en las habitaciones_." },
          { text: "cancelar tres días antes de llegar", cat: 0, why: "Tres días son más de 48 horas: la cancelación es gratuita." },
        ],
      },
    ],
    noticing: {
      prompt: "Fíjate en cómo habla un texto de condiciones.",
      items: [
        { quote: "Si llega antes, puede dejar su equipaje", note: "El texto trata al cliente de **usted** (_llega_, _puede_, _su_): es la norma en textos de servicios." },
        { quote: "escríbanos un correo", note: "Imperativo de **ustedes/usted** + pronombre pegado: _escríbanos_ = escriba + nos. Lleva tilde porque la palabra crece." },
        { quote: "está sujeta a disponibilidad", note: "Fórmula fija: no te lo garantizan, depende de si hay sitio. _Sujeta_ concuerda con _la salida tardía_." },
        { quote: "No se permite fumar", note: "**No se permite** + infinitivo: la forma impersonal típica de las normas." },
        { quote: "con reserva previa de 24 horas", note: "Hay que pedirlo al menos un día antes." },
      ],
    },
  },
  practice: {
    intro: "Combina la cortesía de esta semana con la salud y los consejos de la semana 13 y con estar + gerundio.",
    exercises: [
      {
        id: "x1",
        type: "context",
        title: "¿Qué dices aquí?",
        prompt: "Lee la situación y elige la frase más adecuada.",
        items: [
          { context: "En una farmacia de Salento. Te duele el estómago desde anoche.", q: "Le dices al farmacéutico:", options: ["Buenas, quería algo para el dolor de estómago.", "Buenas, me duelen el estómago.", "Buenas, estoy doliendo del estómago."], answer: 0, why: "**Quería** + lo que necesitas es una petición cortés. _Me duele_ va en singular con _el estómago_, y _doler_ no va con estar + gerundio." },
          { context: "Tu amiga tiene fiebre y quiere ir mañana a una caminata de seis horas.", q: "Le aconsejas:", options: ["Yo que tú, me quedaría en el hostal.", "Yo que tú, me quedé en el hostal.", "Tú quedarías en el hostal."], answer: 0, why: "**Yo que tú** + condicional es un consejo suave. También podrías decir _deberías quedarte_." },
          { context: "Llamas a recepción. Alguien está tocando música muy alta en la habitación de al lado.", q: "Dices:", options: ["Disculpe, en la habitación 8 están poniendo música muy alta. ¿Podría hablar con ellos?", "¡Música! ¡Hablen con ellos ya!", "Disculpe, en la habitación 8 ponen música. Me gustaba dormir."], answer: 0, why: "Problema en curso con **estar + gerundio** y petición con **podría**. _Me gustaba_ habla del pasado." },
          { context: "En el aeropuerto. Quieres sentarte junto a la ventanilla.", q: "Le dices a la agente:", options: ["¿Sería posible un asiento de ventana?", "¿Sería posible a un asiento de ventana?", "¿Será posible ventana?"], answer: 0, why: "**¿Sería posible + sustantivo o infinitivo?**, sin preposición." },
        ],
      },
      {
        id: "x2",
        type: "error",
        title: "Detective de errores",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "Disculpe, ¿podría usted me ayudar con la maleta?", answers: ["Disculpe, ¿podría usted ayudarme con la maleta?", "Disculpe, ¿me podría ayudar con la maleta?", "Disculpe, ¿podría ayudarme con la maleta?", "Disculpe, ¿usted me podría ayudar con la maleta?"], why: "El pronombre va antes del verbo conjugado (_me podría_) o pegado al infinitivo (_ayudarme_), nunca entre los dos." },
          { sentence: "Nos gustaríamos una habitación con dos camas.", answers: ["Nos gustaría una habitación con dos camas."], why: "_Gustar_ concuerda con _una habitación_ (singular): **nos gustaría**." },
          { sentence: "Estimada señora: ¿puedes confirmarme la reserva?", answers: ["Estimada señora: ¿podría confirmarme la reserva?", "Estimada señora: ¿puede confirmarme la reserva?", "Estimada señora: ¿me podría confirmar la reserva?"], why: "Con _estimada señora_ el trato es de **usted**: _podría_ (o _puede_), no _puedes_." },
          { sentence: "Me duelen mucho la espalda después del viaje.", answers: ["Me duele mucho la espalda después del viaje."], why: "_La espalda_ es singular: **me duele**." },
          { sentence: "Perdone, el baño está gotear desde esta mañana.", answers: ["Perdone, el baño está goteando desde esta mañana."], why: "Estar + **gerundio**: gote**ando**." },
        ],
      },
      {
        id: "x3",
        type: "order",
        title: "Construye la petición",
        prompt: "Ordena las palabras.",
        items: [
          { words: ["¿Me", "podría", "decir", "dónde", "está", "la", "terminal?"], alt: ["¿Podría decirme dónde está la terminal?"], en: "Could you tell me where the bus station is?", why: "_Me_ va delante de _podría_; la pregunta indirecta (_dónde está…_) va al final." },
          { words: ["Nos", "gustaría", "cambiar", "la", "fecha", "de", "la", "reserva."], en: "We would like to change the date of the booking.", why: "**Nos gustaría** + infinitivo + complemento." },
          { words: ["¿Sería", "posible", "dejar", "las", "maletas", "en", "recepción?"], en: "Would it be possible to leave the suitcases at reception?", why: "**¿Sería posible** + infinitivo?" },
        ],
      },
      {
        id: "x4",
        type: "gap",
        title: "Una mañana complicada",
        prompt: "Completa con la forma correcta. Mezcla condicional, doler, deberías y estar + gerundio.",
        items: [
          { q: "Disculpe, ___ (yo, querer) cambiar mi tiquete para el bus de las cuatro.", answers: [["quería", "querría"]], why: "Imperfecto de cortesía: **quería** (o el condicional _querría_)." },
          { q: "Mi compañero no puede viajar hoy: le ___ (doler) los oídos y tiene fiebre.", answers: [["duelen"]], why: "_Los oídos_ es plural: **le duelen**." },
          { q: "Tienes fiebre: ___ (deber, tú) ir al médico antes de viajar.", answers: [["deberías"]], why: "Consejo de tú: **deberías** + infinitivo." },
          { q: "Ahora mismo los mecánicos ___ (revisar) el bus, por eso sale con retraso.", answers: [["están revisando"]], why: "Acción en curso: **están revisando**." },
          { q: "¿Le ___ (importar) esperar cinco minutos? Ahora mismo lo atiendo.", answers: [["importaría"]], why: "**¿Le importaría** + infinitivo?: petición muy cortés de usted." },
        ],
      },
      {
        id: "x5",
        type: "open",
        title: "Mensajes cortos",
        prompt: "Escribe mensajes breves (2–3 frases) para estas situaciones. Usa la cortesía de la semana.",
        items: [
          {
            prompt: "Escribe por WhatsApp al hostal: llegas en un bus de la noche, a las 11 p. m., y la recepción cierra a las 10. Explica el problema y pide una solución.",
            model: "Buenas noches. Tengo una reserva para hoy a nombre de Sara Lindqvist, pero mi bus llega a Salento a las 11 de la noche. ¿Sería posible dejarme la llave en algún lugar o esperar en recepción? Muchas gracias.",
            checklist: ["Saludas y das tu nombre o tu reserva.", "Explicas el problema con claridad.", "Pides la solución con _sería posible_, _podría_ o _me gustaría_.", "Terminas agradeciendo."],
          },
          {
            prompt: "Tu amigo tiene dolor de garganta y mañana quiere hacer un tour en bicicleta. Escríbele un mensaje con un consejo y una propuesta.",
            model: "¡Oye! Si te duele la garganta, deberías descansar mañana. Yo que tú, haría el tour el jueves. ¿Te parece bien?",
            checklist: ["Mencionas el síntoma con _doler_ bien concordado.", "Das un consejo con _deberías_, _tendrías que_ o _yo que tú_ + condicional.", "Haces una propuesta o una pregunta final."],
          },
          {
            prompt: "Estás en la terminal y tu bus a Pereira está retrasado. Escribe a tu anfitrión para avisar y pedirle algo.",
            model: "Hola, Liliana. Mi bus está retrasado una hora: ahora mismo estamos esperando en la terminal de Armenia. ¿Podrías guardarme la cena? ¡Mil gracias!",
            checklist: ["Explicas qué pasa con estar + gerundio o con _está retrasado_.", "Pides un favor con _podrías_ (tú) o _podría_ (usted), coherente con el trato.", "El mensaje es breve y amable."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe un correo formal al Hostal La Cafetera para cambiar tu reserva.",
    context: "Tienes una reserva para dos personas del 12 al 14 de marzo (número 4471). Tu vuelo a Armenia cambió y ahora llegas un día más tarde. Además, quieres saber si pueden recogerte en la terminal.",
    steps: [
      "Escribe un asunto claro (_Cambio de fechas – reserva 4471_).",
      "Saluda de forma formal, con dos puntos.",
      "Explica el motivo: quién eres, qué reserva tienes y qué ha pasado.",
      "Haz dos peticiones con el condicional: el cambio de fechas y la recogida.",
      "Despídete con una fórmula formal y tu nombre.",
    ],
    useLanguage: [
      "Estimados señores:",
      "Les escribo para… / porque…",
      "Me gustaría cambiar… / Quería preguntar…",
      "¿Sería posible…? / ¿Podrían confirmarme…?",
      "Quedo atento/atenta a su respuesta.",
      "Un cordial saludo,",
    ],
    model: [
      "Asunto: Cambio de fechas – reserva 4471",
      "Estimados señores:",
      "Les escribo porque tengo una reserva para dos personas del 12 al 14 de marzo (número 4471). La aerolínea ha cambiado mi vuelo y ahora llego a Armenia el día 13. Por eso, me gustaría cambiar la reserva al 13 y 15 de marzo. ¿Sería posible?",
      "También quería preguntar por la recogida en la terminal de Armenia: llegamos el 13 a las cuatro de la tarde. ¿Podrían confirmarme el precio y la hora?",
      "Muchas gracias de antemano. Quedo atenta a su respuesta.",
      "Un cordial saludo,",
      "Emma Clarke",
    ],
    checklist: [
      "Uso _usted/ustedes_ en todo el correo, sin mezclar con tú.",
      "El saludo formal termina en dos puntos.",
      "Doy los datos de la reserva (fechas, número, personas).",
      "Hago al menos dos peticiones con condicional (_me gustaría_, _sería posible_, _podrían_).",
      "Termino con una despedida formal y mi nombre.",
    ],
    words: [60, 110],
  },
  speaking: {
    intro: "Grábate. En estas tareas importa tanto lo que dices como la melodía: escucha si suenas amable.",
    tasks: [
      {
        title: "Llamada a recepción",
        prompt: "Llamas a la recepción desde tu habitación. El aire acondicionado no funciona y hay ruido de una obra en la calle. Explica los dos problemas y pide una solución. Si te dicen que no hay otra habitación, negocia.",
        prep: ["Buenas noches, disculpe. Estoy en la habitación…", "El aire acondicionado no funciona y están haciendo obras…", "¿Podría mandar a alguien? / ¿Sería posible cambiar de habitación?", "¿Y no tendría otra opción?", "Muchas gracias, muy amable."],
        seconds: 60,
        model: "Buenas noches, disculpe. Estoy en la habitación catorce. El aire acondicionado no funciona y, además, en la calle están haciendo obras y hay mucho ruido. ¿Sería posible cambiar de habitación? … Entiendo. ¿Y no tendría otra opción? ¿Podría mandar a alguien para revisar el aire, por lo menos? Muchas gracias, muy amable.",
        selfCheck: ["Sigo los cuatro pasos: atención, problema, petición y cierre.", "Uso al menos dos formas de cortesía distintas.", "La voz sube en las peticiones y no suena a orden."],
      },
      {
        title: "En la ventanilla de la terminal",
        prompt: "Estás en la terminal de transportes de Armenia. Compra un tiquete de ida a Salento para mañana por la mañana, pregunta a qué hora sale el primer bus y pide un asiento de ventana.",
        prep: ["Buenos días, quería un tiquete…", "¿Podría decirme a qué hora sale…?", "¿Sería posible un asiento de ventana?"],
        seconds: 40,
        model: "Buenos días. Quería un tiquete de ida a Salento para mañana por la mañana. ¿Podría decirme a qué hora sale el primer bus? … Perfecto. ¿Sería posible un asiento de ventana? Muchas gracias.",
        selfCheck: ["Empiezo con _quería_ y no con _quiero_.", "Hago una pregunta de información con _podría decirme_.", "Uso vocabulario de viaje: tiquete, de ida, asiento de ventana."],
      },
      {
        title: "Me siento mal en el viaje",
        prompt: "Estás en el hostal y te encuentras mal. Explica a la recepcionista qué te duele y desde cuándo, y pide con cortesía algo concreto (un médico, una farmacia, un té). Después, imagina que tu amigo está enfermo y dale dos consejos.",
        prep: ["Perdone, no me encuentro bien. Me duele…", "¿Me podría decir dónde hay una farmacia?", "A tu amigo: deberías… / yo que tú…"],
        seconds: 45,
        model: "Perdone, no me encuentro muy bien. Me duele mucho el estómago desde anoche. ¿Me podría decir dónde hay una farmacia? … Y tú, Marco, deberías tomar mucha agua. Yo que tú, no haría la excursión mañana.",
        selfCheck: ["Concuerdo _duele / duelen_ con lo que me duele.", "Pido con usted a la recepcionista y aconsejo de tú a mi amigo.", "Uso _deberías_ o _yo que tú_ + condicional."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo, convierte la clase en un hotel, una terminal o un aeropuerto.",
    cards: [
      { move: "Pide", task: "Pídele a tu profesor o profesora tres cosas reales de la clase (repetir algo, escribir una palabra, hablar más despacio) usando tres fórmulas distintas.", phrases: ["¿Podría repetir la última frase?", "¿Te importaría escribirlo en el chat?", "¿Sería posible hablar un poco más despacio?"] },
      { move: "Reclama", task: "Haz un juego de rol: tú eres cliente de un hotel y tienes dos problemas. Tu profesor o profesora es el recepcionista. Sigue los cuatro pasos y no aceptes la primera solución.", phrases: ["Disculpe, tengo un problema con…", "¿Y no tendría otra opción?", "Me gustaría hablar con el encargado."] },
      { move: "Negocia", task: "Cambia de papel: ahora tú eres recepcionista y solo puedes ofrecer soluciones parciales. Ofrece algo y explica por qué no puedes dar más.", phrases: ["Disculpe las molestias.", "Lo siento, no es posible, pero le puedo ofrecer…", "¿Le parece bien?"] },
      { move: "Aconseja", task: "Tu profesor o profesora te cuenta un problema de salud en un viaje. Dale tres consejos con deberías, tendrías que y yo que tú.", phrases: ["Deberías descansar.", "Tendrías que ir a la farmacia.", "Yo que tú, cambiaría el vuelo."] },
    ],
    bring: "Trae escrito tu correo de cambio de reserva: tu profesor o profesora lo revisará contigo y te responderá en el papel del hostal.",
  },
  quiz: {
    items: [
      { type: "choice", q: "¿Cuál es la forma más cortés para pedir en una oficina de turismo?", options: ["¿Me podría dar un mapa de la zona?", "Deme un mapa de la zona.", "Quiero un mapa de la zona."], answer: 0, why: "Pregunta con **podría**: deja espacio a la otra persona. Las otras dos suenan a orden." },
      { type: "choice", q: "En Colombia, un camarero te dice «¿Le regalo algo más?». ¿Qué significa?", options: ["¿Quiere pedir algo más?", "¿Quiere algo gratis?", "¿Quiere hacer un regalo?"], answer: 0, why: "En Colombia **regalar** se usa para ofrecer o pedir con amabilidad, aunque se pague." },
      { type: "listen", q: "¿Qué problema tiene la clienta?", audio: "Buenas noches, disculpe. Me han cobrado dos noches, pero solo me quedé una. ¿Podría revisar la factura?", voice: "es-PE-f", options: ["Le cobraron de más.", "Perdió la llave.", "La habitación está sucia."], answer: 0, why: "_Me han cobrado dos noches, pero solo me quedé una_: le **cobraron de más**." },
      { type: "listen", q: "¿Qué tiene que hacer el viajero?", audio: "Su vuelo está retrasado. La nueva puerta de embarque es la doce y el embarque empieza a las cinco y media.", voice: "es-CO-m", options: ["Ir a la puerta 12 a las 5:30.", "Ir a la puerta 2 a las 5:30.", "Ir a la puerta 12 a las 6:30."], answer: 0, why: "_La nueva puerta de embarque es la doce_ y el embarque _empieza a las cinco y media_." },
      { type: "gap", q: "¿___ (poder, usted) despertarme a las cinco? Mi bus sale a las seis.", answers: [["Podría"]], why: "Usted → **podría**, raíz irregular _podr-_." },
      { type: "gap", q: "A mi hermano le ___ (gustar) una habitación lejos del ascensor: tiene el sueño muy ligero.", answers: [["gustaría"]], why: "Le **gustaría** + _una habitación_ (singular)." },
      { type: "transform", source: "Quiero hablar con el encargado.", instruction: "Hazla más cortés.", answers: ["Me gustaría hablar con el encargado.", "Quería hablar con el encargado.", "¿Podría hablar con el encargado?", "Quisiera hablar con el encargado.", "¿Podría hablar con el encargado, por favor?", "Me gustaría hablar con el encargado, por favor."], why: "**Me gustaría** o **quería** suavizan el deseo; también vale preguntar con _¿podría…?_" },
      { type: "transform", source: "Tienes que ir a la farmacia.", instruction: "Conviértelo en un consejo más suave con deberías.", answers: ["Deberías ir a la farmacia."], why: "**Deberías** + infinitivo es un consejo; _tienes que_ suena a obligación." },
      { type: "order", words: ["¿Les", "importaría", "esperar", "en", "la", "sala", "un", "momento?"], why: "**¿Les importaría** + infinitivo? es una petición muy cortés de ustedes." },
      { type: "error", sentence: "Disculpe, me gustaba cambiar de habitación porque hay mucho ruido.", answers: ["Disculpe, me gustaría cambiar de habitación porque hay mucho ruido.", "Disculpe, quería cambiar de habitación porque hay mucho ruido."], why: "Para un deseo de ahora: **me gustaría** (condicional) o _quería_. _Me gustaba_ habla de un gusto del pasado." },
      { type: "error", sentence: "Señor, ¿podrías cerrar la puerta, por favor?", answers: ["Señor, ¿podría cerrar la puerta, por favor?"], why: "Con _señor_ el trato es de usted: **podría**, sin -s." },
      { type: "open", prompt: "Estás en el aeropuerto: tu maleta no ha llegado. Escribe lo que le dices al empleado (3–4 frases): saluda, explica el problema, pide dos cosas con cortesía y agradece.", model: "Buenas tardes, disculpe. Acabo de llegar en el vuelo de Bogotá y mi maleta no ha salido. ¿Podría revisar dónde está? Y si no la encuentran hoy, ¿sería posible enviarla a mi hostal en Salento? Muchas gracias.", checklist: ["Saludo y llamo la atención.", "Explico el problema con claridad.", "Hago dos peticiones con condicional.", "Agradezco al final."] },
    ],
  },
  complete: {
    canNow: [
      "Pedir con cortesía con podría, me gustaría, sería posible, tendría y quería.",
      "Formar el condicional regular y los irregulares más frecuentes (podría, tendría, haría, diría).",
      "Reclamar un problema en cuatro pasos y negociar otra solución.",
      "Resolver gestiones en un hotel, una terminal y un aeropuerto, y reconocer palabras de varios países (tiquete, billete, boleto).",
      "Encontrar horarios, precios y normas en las condiciones de un servicio.",
      "Escribir un correo formal breve para reservar o cambiar una reserva.",
      "Hacer una petición con una entonación amable.",
    ],
    review: [
      "Me gustaría + infinitivo, sin preposición.",
      "Podría (usted) y podrías (tú): no los mezcles.",
      "Me gustaría (ahora) frente a me gustaba (antes).",
      "Me duele / me duelen y los consejos con deberías.",
    ],
  },
  related: [
    { path: "/el-hotel-de-lo-imposible", label: "El hotel de lo imposible · escucha A2" },
    { path: "/buenos-aires-en-la-calle", label: "Buenos Aires en la calle · español de viaje" },
  ],
};
