import type { Module } from "../../types";

export const a2w17: Module = {
  id: "a2-17",
  level: "a2",
  week: 17,
  kind: "core",
  title: "¿Por qué? ¿Para qué?",
  subtitle: "Por y para, compras en línea y envíos: di por qué haces algo y para qué lo haces.",
  stop: { place: "Mérida", country: "Venezuela" },
  minutes: 80,
  newObjectives: [
    "a2.gram.por-para",
    "a2.voc.compras-online",
    "a2.pron.palabras-largas",
    "a2.fun.finalidad",
    "a2.lis.atencion-cliente",
  ],
  reviewObjectives: [
    "a2.gram.antes-despues-inf",
    "a2.fun.explicar-decisiones",
    "a2.gram.condicional-cortesia",
  ],
  prerequisites: ["a2-16"],
  goal: {
    canDo: "Al final de esta semana puedes decir para qué haces algo y por qué lo haces, comprar y devolver productos en línea, seguir un envío y entender un mensaje grabado de atención al cliente.",
    canDoEn: "By the end of this week, you can say what you do something for and why you do it, buy and return things online, track a delivery and follow a recorded customer-service message.",
    steps: [
      "Descubre la lógica de **para** (meta, destino, plazo, destinatario) y de **por** (causa, medio, intercambio, camino).",
      "Aprende el vocabulario de las compras en línea: pedido, envío, seguimiento, devolución, reembolso.",
      "Entrena el ritmo de las palabras largas: `de-vo-lu-ción`, `res-pon-sa-bi-li-DAD`.",
      "Escucha una llamada a atención al cliente desde Mérida, con menú grabado incluido.",
      "Escribe un mensaje para devolver un producto y explica por qué y para qué.",
    ],
  },
  theory: {
    intro: "**Por** y **para** se traducen muchas veces como _for_, pero en español no son intercambiables. La buena noticia: cada una tiene una idea central. **Para** mira hacia adelante, hacia una meta. **Por** mira hacia atrás o hacia el camino: la causa, el medio, el lugar por donde pasas.",
    parts: [
      {
        heading: "Para: la flecha que apunta a una meta",
        body: [
          "Piensa en **para** como una flecha →. Apunta a algo que está delante: un objetivo, un lugar al que vas, una fecha límite o la persona que va a recibir algo.",
          "**Finalidad** (para + infinitivo): **Ahorro para comprar una bici.** Responde a la pregunta **¿para qué?** **Destino**: **Mañana salgo para Caracas.** **Plazo** (fecha límite): **Necesito el paquete para el viernes.** **Destinatario**: **Este suéter es para mi abuela.**",
          "También usamos **para mí / para ti** para dar una opinión personal: **Para mí, comprar en línea es más cómodo.** Y para decir la utilidad de una cosa: **Esta caja sirve para enviar libros.**",
        ],
        support: [
          "_Para_ points forward: purpose ('in order to'), destination ('heading for'), deadline ('by Friday') and recipient ('this is for you').",
          "When you can say 'in order to' in English, Spanish uses _para_ + infinitive. Never _por_ + infinitive for a goal.",
        ],
        table: {
          caption: "Los cuatro usos centrales de para",
          head: ["Uso", "Pregunta", "Ejemplo"],
          rows: [
            ["finalidad", "¿Para qué?", "Uso la aplicación para seguir el pedido."],
            ["destino", "¿Hacia dónde?", "El camión sale para Mérida a las seis."],
            ["plazo", "¿Para cuándo?", "Lo necesito para el lunes."],
            ["destinatario", "¿Para quién?", "El regalo es para Andrés."],
          ],
        },
        examples: [
          { es: "Escribo a la tienda para cambiar la talla.", en: "I'm writing to the shop (in order) to change the size." },
          { es: "¿Para cuándo llega el pedido? —Para el jueves.", en: "When will the order arrive by? — By Thursday." },
          { es: "Esta ruana es para mi madre: tiene frío en Mérida.", en: "This poncho is for my mother: she's cold in Mérida." },
        ],
        mistakes: [
          { wrong: "Estudio español por trabajar en Venezuela.", right: "Estudio español para trabajar en Venezuela.", why: "Es una meta, algo que quieres conseguir: **para** + infinitivo." },
        ],
        tip: "Truco rápido: si puedes añadir _con el objetivo de_, es **para**. _Escribo (con el objetivo de) cambiar la talla_ → **para cambiar**.",
      },
      {
        heading: "Por: la causa, el medio y el camino",
        body: [
          "**Por** no apunta a una meta: explica **de dónde viene** algo o **por dónde pasa**. Tiene cuatro usos centrales a este nivel.",
          "**Causa**: **El envío llegó tarde por la lluvia.** **Gracias por tu ayuda.** Responde a **¿por qué?** **Medio**: **Te lo mando por correo**, **hablamos por teléfono**, **lo compré por internet**. **Intercambio y precio**: **Lo compré por veinte dólares**, **¿Me lo cambias por una talla M?** **Lugar de paso o aproximado**: **Paseamos por el centro**, **el autobús pasa por Mérida**, **vivo por aquí**.",
          "También va con las partes del día: **por la mañana, por la tarde, por la noche**. En muchos países de América también se dice **en la mañana, en la tarde**; los dos usos son correctos.",
        ],
        support: [
          "_Por_ looks back or along the way: the cause ('because of'), the means ('by phone, by email'), the exchange ('for 20 dollars', 'swap it for'), and the route ('through, around').",
          "_Gracias por_ is fixed: you thank someone because of something they did. Never _gracias para_.",
        ],
        table: {
          caption: "Los cuatro usos centrales de por",
          head: ["Uso", "Pregunta", "Ejemplo"],
          rows: [
            ["causa", "¿Por qué?", "Devolví la chaqueta por un defecto."],
            ["medio", "¿Cómo?", "Pagué por transferencia."],
            ["intercambio / precio", "¿Por cuánto? ¿Por qué cosa?", "Lo vendí por cincuenta dólares."],
            ["lugar de paso", "¿Por dónde?", "Caminamos por la plaza Bolívar."],
          ],
        },
        examples: [
          { es: "Gracias por el envío tan rápido.", en: "Thanks for the fast delivery." },
          { es: "El paquete pasó por Caracas antes de llegar a Mérida.", en: "The parcel went through Caracas before reaching Mérida." },
          { es: "No pude pagar por la aplicación, así que llamé por teléfono.", en: "I couldn't pay through the app, so I phoned." },
        ],
        mistakes: [
          { wrong: "Gracias para el regalo.", right: "Gracias por el regalo.", why: "Agradeces una causa, algo que ya pasó: **gracias por**." },
          { wrong: "Compré estas botas para treinta dólares.", right: "Compré estas botas por treinta dólares.", why: "El precio es un intercambio (dinero ↔ producto): **por**." },
        ],
        tip: "Fíjate en la dirección: **salgo para Mérida** (Mérida es la meta) / **paso por Mérida** (Mérida está en el camino, la meta es otra).",
      },
      {
        heading: "¿Por qué? o ¿para qué? Causa y finalidad",
        body: [
          "Muchas veces una misma acción tiene una causa y una finalidad. **¿Por qué** llamas a la tienda? **Porque** el paquete no llegó (la causa, lo que pasó antes). **¿Para qué** llamas? **Para** pedir el número de seguimiento (la meta, lo que quieres conseguir).",
          "Fíjate en la forma: **porque** + verbo conjugado (_porque no llegó_), **por** + nombre (_por el retraso_), **para** + infinitivo (_para pedir_) o + nombre (_para el viernes_). Y recuerda las conexiones de la semana pasada: **como** el paquete no llegaba, llamé; no llegaba, **así que** llamé.",
          "Atención a la ortografía: **¿por qué?** (dos palabras, con tilde) es la pregunta; **porque** (una palabra, sin tilde) es la respuesta.",
        ],
        support: [
          "'Why' has two Spanish versions: _¿por qué?_ asks for the cause, _¿para qué?_ asks for the purpose. Both are natural, but they expect different answers.",
          "_Porque_ + conjugated verb; _para_ + infinitive. Compare: _Llamo porque quiero información_ / _Llamo para pedir información_.",
        ],
        examples: [
          { es: "—¿Por qué devuelves el teléfono? —Porque la pantalla llegó rota.", en: "Why are you returning the phone? — Because the screen arrived broken." },
          { es: "—¿Para qué guardas la caja? —Para devolverlo si no funciona.", en: "What are you keeping the box for? — To return it if it doesn't work." },
          { es: "Como la talla era pequeña, la cambié por una M.", en: "As the size was small, I exchanged it for a medium." },
        ],
        mistakes: [
          { wrong: "Llamé para el paquete no llegó.", right: "Llamé porque el paquete no llegó.", why: "Con un verbo conjugado (_llegó_) expresas la causa con **porque**." },
          { wrong: "¿Porque compras en línea?", right: "¿Por qué compras en línea?", why: "La pregunta se escribe en dos palabras y con tilde: **¿por qué?**" },
        ],
        tip: "Antes de elegir, hazte la pregunta: ¿esto pasó **antes** y lo provoca (por), o está **delante** y lo busco (para)?",
      },
    ],
  },
  grammar: {
    intro: "Practica por y para paso a paso: primero el sentido, después la forma.",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "¿Meta o causa?",
        prompt: "Elige **por** o **para** y lee la explicación.",
        items: [
          { q: "Hice el pedido el lunes ___ tenerlo antes del fin de semana.", options: ["por", "para"], answer: 1, why: "Es la meta, lo que quieres conseguir: **para** + infinitivo." },
          { q: "La tienda cerró dos días ___ el corte de luz.", options: ["por", "para"], answer: 0, why: "El corte de luz es la causa: **por** + nombre." },
          { q: "Este libro de cocina andina es ___ mi tía Carmen.", options: ["por", "para"], answer: 1, why: "Tu tía va a recibir el libro: destinatario → **para**." },
          { q: "Me mandaron la factura ___ correo electrónico.", options: ["por", "para"], answer: 0, why: "Es el medio, el canal: **por** correo, **por** teléfono." },
          { q: "El repartidor dice que lo trae ___ el miércoles.", options: ["por", "para"], answer: 1, why: "Fecha límite: **para** el miércoles." },
          { q: "Cambié la mochila azul ___ una negra.", options: ["por", "para"], answer: 0, why: "Es un intercambio: una cosa a cambio de otra → **por**." },
        ],
      },
      {
        id: "g2",
        type: "classify",
        title: "¿Qué hace por aquí?",
        prompt: "Todas las frases usan **por**. Clasifícalas según su uso.",
        categories: ["causa", "medio", "precio / intercambio", "lugar de paso"],
        items: [
          { text: "No salimos por el frío.", cat: 0, why: "El frío explica por qué no salimos." },
          { text: "Te escribo por WhatsApp esta noche.", cat: 1, why: "WhatsApp es el canal de comunicación." },
          { text: "Conseguí el casco por quince dólares.", cat: 2, why: "Dinero a cambio del producto." },
          { text: "El teleférico sube por la montaña.", cat: 3, why: "La montaña es el camino, no la meta." },
          { text: "Me quedé en casa por el dolor de cabeza.", cat: 0, why: "El dolor es la causa." },
          { text: "Pagué el pedido por transferencia.", cat: 1, why: "La transferencia es el medio de pago." },
          { text: "¿Me cambias tu turno del sábado por el mío?", cat: 2, why: "Un turno a cambio de otro." },
          { text: "Vamos a dar una vuelta por el mercado.", cat: 3, why: "Recorres el mercado, pasas por dentro." },
        ],
      },
      {
        id: "g3",
        type: "transform",
        title: "De porque a para",
        prompt: "Reescribe la frase con **para + infinitivo**. Expresa la meta, no la causa.",
        items: [
          { source: "Ahorro dinero porque quiero comprar una bicicleta.", answers: ["Ahorro dinero para comprar una bicicleta."], why: "_Porque quiero_ + infinitivo es una meta: **para comprar**." },
          { source: "Abro la aplicación porque quiero ver dónde está mi paquete.", answers: ["Abro la aplicación para ver dónde está mi paquete."], why: "La meta es ver el paquete: **para ver**." },
          { source: "Llamamos a la tienda porque queremos pedir un descuento.", answers: ["Llamamos a la tienda para pedir un descuento."], why: "El infinitivo no cambia con la persona: **para pedir**, aunque el sujeto sea _nosotros_." },
          { source: "Guardo el recibo porque quiero devolver los zapatos si no me quedan bien.", answers: ["Guardo el recibo para devolver los zapatos si no me quedan bien."], why: "Guardas el recibo con un objetivo: **para devolver**." },
        ],
      },
      {
        id: "g4",
        type: "gap",
        title: "Un pedido con historia",
        prompt: "Completa con **por** o **para**.",
        items: [
          { q: "Mariela compró un abrigo ___ internet ___ su viaje a los páramos.", answers: [["por"], ["para"]], why: "Internet es el medio (**por**); el viaje es la finalidad (**para**)." },
          { q: "El lunes el paquete salió de Valencia ___ Mérida y el martes pasó ___ Barquisimeto.", answers: [["para"], ["por"]], why: "Mérida es el destino final (**salir para**); Barquisimeto está en el camino (**pasar por**)." },
          { q: "Lo necesita ___ el sábado, ___ eso pagó el envío urgente.", answers: [["para"], ["por"]], why: "Fecha límite: **para** el sábado. _Por eso_ = a causa de eso (conector de consecuencia)." },
          { q: "Le dio las gracias al repartidor ___ subir la caja hasta el quinto piso.", answers: [["por"]], why: "**Gracias por** + la acción que agradeces." },
          { q: "—¿___ qué quieres otra caja? —___ enviar los libros a mi hermano.", answers: [["Para"], ["Para"]], why: "Pregunta y respuesta de finalidad: **¿para qué?** → **para** + infinitivo." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Aprende estas expresiones en bloque: verbo + nombre, tal como aparecen en una tienda en línea o en un correo de seguimiento.",
    groups: [
      {
        title: "Comprar en línea",
        items: [
          { es: "buscar un producto en la tienda en línea", en: "to look for a product in the online shop" },
          { es: "añadir al carrito", en: "to add to the cart" },
          { es: "hacer un pedido", en: "to place an order" },
          { es: "pagar con tarjeta / por transferencia", en: "to pay by card / by bank transfer" },
          { es: "usar un código de descuento", en: "to use a discount code" },
          { es: "los gastos de envío", en: "shipping costs" },
          { es: "elegir la talla y el color", en: "to choose the size and colour" },
          { es: "la confirmación del pedido", en: "the order confirmation" },
        ],
      },
      {
        title: "El envío",
        items: [
          { es: "el paquete (la encomienda en Venezuela, Chile, Argentina)", en: "the parcel" },
          { es: "el número de seguimiento", en: "the tracking number" },
          { es: "rastrear / seguir el envío", en: "to track the delivery" },
          { es: "el repartidor / la repartidora", en: "the delivery person" },
          { es: "la dirección de entrega", en: "the delivery address" },
          { es: "estar en camino", en: "to be on its way" },
          { es: "llegar con retraso", en: "to arrive late" },
          { es: "recoger el paquete en la oficina", en: "to pick up the parcel at the office" },
        ],
      },
      {
        title: "Problemas y devoluciones",
        items: [
          { es: "llegar dañado / roto", en: "to arrive damaged / broken" },
          { es: "no ser lo que pedí", en: "not to be what I ordered" },
          { es: "quedar grande / pequeño", en: "to be too big / too small (clothes)" },
          { es: "devolver un producto", en: "to return a product" },
          { es: "cambiar algo por otra talla", en: "to exchange something for another size" },
          { es: "pedir el reembolso", en: "to ask for a refund" },
          { es: "el plazo de devolución", en: "the return period" },
          { es: "la atención al cliente", en: "customer service" },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "Del carrito a tu puerta",
        prompt: "Une cada momento de la compra con la expresión adecuada.",
        pairs: [
          { left: "Te gusta un producto y quieres comprarlo después.", right: "Lo añades al carrito." },
          { left: "Quieres saber dónde está el paquete.", right: "Lo rastreas con el número de seguimiento." },
          { left: "La camisa te queda pequeña.", right: "La cambias por otra talla." },
          { left: "No quieres el producto y quieres tu dinero.", right: "Pides el reembolso." },
          { left: "El repartidor no te encontró en casa.", right: "Recoges el paquete en la oficina." },
        ],
        why: "Cada expresión corresponde a una etapa: comprar, seguir, cambiar, recuperar el dinero, recoger.",
      },
      {
        id: "v2",
        type: "gap",
        title: "Un correo de la tienda",
        prompt: "Completa el correo con las palabras del banco.",
        bank: ["pedido", "en camino", "seguimiento", "gastos de envío", "plazo", "entrega"],
        items: [
          { q: "Hola, Daniel: tu ___ n.º 4581 ya está confirmado.", answers: [["pedido"]], why: "_Hacer / confirmar un **pedido**_ = la compra que hiciste." },
          { q: "El paquete ya salió del almacén y está ___.", answers: [["en camino"]], why: "_Estar **en camino**_ = viajar hacia ti." },
          { q: "Con este número de ___ puedes ver dónde está en todo momento.", answers: [["seguimiento"]], why: "El número de **seguimiento** sirve para rastrear el envío." },
          { q: "Revisa tu dirección de ___: calle 24, Mérida.", answers: [["entrega"]], why: "La dirección de **entrega** es donde recibes el paquete." },
          { q: "Como tu compra supera los 50 dólares, no pagas ___.", answers: [["gastos de envío"]], why: "Los **gastos de envío** son el precio del transporte." },
          { q: "Tienes un ___ de 15 días para devolverlo.", answers: [["plazo"]], why: "El **plazo** de devolución = el tiempo máximo." },
        ],
      },
      {
        id: "v3",
        type: "context",
        title: "¿Qué dices aquí?",
        prompt: "Lee la situación y elige la frase más natural.",
        items: [
          { context: "Abres la caja y la taza está partida en dos.", q: "Escribes a la tienda:", options: ["La taza llegó rota.", "La taza me queda pequeña.", "La taza está en camino."], answer: 0, why: "Un objeto que se rompe en el transporte **llega roto / dañado**. _Quedar pequeño_ es para ropa y zapatos." },
          { context: "Pediste unos zapatos negros y recibes unos marrones.", q: "Dices:", options: ["No es lo que pedí.", "Me queda grande.", "Pagué los gastos de envío."], answer: 0, why: "El error es del producto: **no es lo que pedí**." },
          { context: "Tu amiga venezolana te pregunta por un paquete.", q: "Ella dice: «¿Ya te llegó la ___?»", options: ["encomienda", "carrito", "talla"], answer: 0, why: "En Venezuela, Chile y Argentina se dice mucho **encomienda** para _paquete_." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "Palabras largas sin perder sílabas",
    explanation: [
      "Las palabras de las compras y los servicios son largas: **devolución**, **confirmación**, **responsabilidad**, **desafortunadamente**. Muchos estudiantes las aceleran, se comen sílabas o mueven el acento. En español cada sílaba ocupa más o menos el **mismo tiempo**: es un ritmo regular, como un tambor.",
      "Para decir una palabra larga: (1) sepárala en sílabas, (2) busca la sílaba tónica —la que lleva el golpe de voz—, (3) dila despacio, sílaba a sílaba, (4) acelera poco a poco sin cambiar el golpe. **De-vo-lu-CIÓN**, **con-fir-ma-CIÓN**, **res-pon-sa-bi-li-DAD**.",
      "Las palabras en **-ción** y **-dad** llevan siempre el acento en la última sílaba. Las palabras en **-mente** tienen dos golpes: el del adjetivo y el de _-men-_: **RÁ-pi-da-MEN-te**, **de-sa-for-tu-NA-da-MEN-te**.",
      "Recuerda la semana 12: las vocales átonas no se reducen. En **seguimiento** suenan las cinco vocales: se-gui-mien-to. Y en Venezuela y el Caribe vas a oír la **s** final aspirada: _lah devolucioneh_; no cambia el número de sílabas.",
    ],
    support: [
      "English stress-timed rhythm squashes unstressed syllables ('com-f'mation'). Spanish is syllable-timed: give every syllable roughly the same length and keep the vowel full.",
      "Words ending in _-ción_ and _-dad_ are always stressed on the last syllable. Adverbs in _-mente_ keep two stresses.",
    ],
    table: {
      caption: "Del pedazo a la palabra entera",
      head: ["Palabra", "Sílabas", "Golpe"],
      rows: [
        ["devolución", "de-vo-lu-ción (4)", "-ción"],
        ["seguimiento", "se-gui-mien-to (4)", "-mien-"],
        ["confirmación", "con-fir-ma-ción (4)", "-ción"],
        ["electrodoméstico", "e-lec-tro-do-més-ti-co (7)", "-més-"],
        ["responsabilidad", "res-pon-sa-bi-li-dad (6)", "-dad"],
        ["desafortunadamente", "de-sa-for-tu-na-da-men-te (8)", "-na- y -men-"],
      ],
    },
    perceive: {
      id: "p1",
      type: "listen",
      title: "¿Dónde está el golpe?",
      prompt: "Escucha cada palabra y elige la sílaba que suena más fuerte.",
      items: [
        { q: "¿Qué sílaba es la tónica?", audio: "devolución", options: ["de", "vo", "lu", "ción"], answer: 3, why: "Las palabras en _-ción_ son agudas: de-vo-lu-**CIÓN**." },
        { q: "¿Qué sílaba es la tónica?", audio: "seguimiento", options: ["se", "gui", "mien", "to"], answer: 2, why: "Llana: se-gui-**MIEN**-to. _-mien-_ es un diptongo, una sola sílaba." },
        { q: "¿Qué sílaba es la tónica?", audio: "electrodoméstico", options: ["lec", "do", "més", "ti"], answer: 2, why: "Esdrújula, con tilde: e-lec-tro-do-**MÉS**-ti-co." },
        { q: "¿Qué sílaba es la tónica?", audio: "disponibilidad", options: ["dis", "po", "ni", "dad"], answer: 3, why: "Las palabras en _-dad_ son agudas: dis-po-ni-bi-li-**DAD**." },
        { q: "¿Cuántas sílabas tiene?", audio: "transferencia", options: ["tres", "cuatro", "cinco"], answer: 1, why: "trans-fe-ren-cia: _-cia_ es un diptongo, así que son **cuatro**." },
        { q: "¿Cuántas sílabas tiene?", audio: "inmediatamente", options: ["cinco", "seis", "siete"], answer: 1, why: "in-me-dia-ta-men-te: **seis**, con _-dia-_ en una sola sílaba." },
      ],
    },
    produce: [
      { text: "de · devo · devolu · devolución", tip: "Construye la palabra de izquierda a derecha y guarda el golpe para el final: **-CIÓN**." },
      { text: "Quisiera pedir la devolución del dinero.", tip: "No aceleres en _devolución_: cuatro sílabas iguales y la última, más fuerte." },
      { text: "¿Me puede dar el número de seguimiento?", tip: "Se-gui-mien-to: la **u** de _gui_ no suena, pero la **i** sí." },
      { text: "Desafortunadamente, el paquete llegó dañado.", tip: "Dos golpes: de-sa-for-tu-**NA**-da-**MEN**-te. Haz una pequeña pausa después de la coma." },
      { text: "La confirmación del pedido llegó inmediatamente.", voice: "es-VE-f", tip: "Escucha el modelo venezolano: el ritmo es regular aunque la **s** se suavice." },
    ],
    spelling: "Las palabras en **-ción** llevan tilde (devolución), pero el plural la pierde: **devoluciones**, porque la palabra pasa a ser llana y termina en -s. Las palabras en **-dad** nunca llevan tilde.",
  },
  listening: {
    title: "Una llamada desde Mérida",
    context: "Camila, una chilena que vive en Mérida, compró unas botas de montaña en una tienda en línea de Valencia. Llama a atención al cliente. Primero escucha el menú grabado y después habla con un agente.",
    speakers: [
      { id: "menu", name: "Mensaje grabado", voice: "es-VE-f", role: "menú automático" },
      { id: "camila", name: "Camila", voice: "es-CL-f", role: "clienta" },
      { id: "jose", name: "José Gregorio", voice: "es-VE-m", role: "agente de atención al cliente" },
    ],
    script: [
      { speaker: "menu", text: "Bienvenido a Andina Outdoor. Por su seguridad, esta llamada puede ser grabada." },
      { speaker: "menu", text: "Para hacer un pedido nuevo, marque uno. Para consultar el estado de un envío, marque dos. Para cambios y devoluciones, marque tres. Para hablar con un agente, marque cero." },
      { speaker: "menu", text: "Usted ha elegido cambios y devoluciones. Por favor, espere: en breve lo atenderá un agente." },
      { speaker: "jose", text: "Buenas tardes, le habla José Gregorio. ¿En qué le puedo ayudar?" },
      { speaker: "camila", text: "Buenas tardes. Le llamo por unas botas que compré la semana pasada. Me quedan grandes y quería cambiarlas por una talla más pequeña." },
      { speaker: "jose", text: "Claro que sí. ¿Me podría dar el número del pedido?" },
      { speaker: "camila", text: "Sí, es el siete, cuatro, dos, cinco. Las pedí para una excursión al Pico Espejo el sábado, así que las necesito antes del viernes." },
      { speaker: "jose", text: "Entiendo. Mire, como usted está en Mérida, lo más rápido es esto: antes de enviarnos las botas, le mandamos las nuevas por mensajería urgente." },
      { speaker: "camila", text: "¡Qué bien! ¿Y tengo que pagar algo por el cambio?" },
      { speaker: "jose", text: "No, el cambio es gratis. Al recibir las botas nuevas, el repartidor recoge las grandes. Solo tiene que dejarlas en la caja original." },
      { speaker: "camila", text: "Perfecto. ¿Y me podría enviar el número de seguimiento por correo?" },
      { speaker: "jose", text: "Por supuesto. Se lo mando ahora mismo. Las botas llegan el jueves por la mañana. ¿Algo más?" },
      { speaker: "camila", text: "No, eso es todo. Muchas gracias por la ayuda, José Gregorio." },
      { speaker: "jose", text: "A la orden. Que disfrute la excursión." },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: solo la idea general. ¿Qué opción elige Camila y por qué llama?",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha una vez y responde.",
          items: [
            { q: "En el menú, ¿qué número marca Camila?", options: ["el uno", "el dos", "el tres", "el cero"], answer: 2, why: "El mensaje confirma: _Usted ha elegido cambios y devoluciones_, que es el **tres**." },
            { q: "¿Por qué llama Camila?", options: ["Porque el paquete no llegó.", "Porque las botas le quedan grandes.", "Porque le cobraron dos veces."], answer: 1, why: "Dice: _Me quedan grandes y quería cambiarlas_." },
            { q: "Al final, ¿el problema está resuelto?", options: ["Sí, recibe otras botas.", "No, tiene que llamar otra vez.", "Sí, le devuelven el dinero."], answer: 0, why: "El agente le manda botas nuevas: es un **cambio**, no un reembolso." },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: ahora los datos concretos.",
        exercise: {
          id: "l2",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "Según el menú, ¿qué número marcas para saber dónde está tu envío?", options: ["el uno", "el dos", "el cero"], answer: 1, why: "_Para consultar el estado de un envío, marque dos._" },
            { q: "¿Para qué compró Camila las botas?", options: ["para trabajar", "para una excursión", "para regalarlas"], answer: 1, why: "_Las pedí para una excursión al Pico Espejo._" },
            { q: "¿Cuánto paga Camila por el cambio?", options: ["nada", "los gastos de envío", "la mitad del precio"], answer: 0, why: "José Gregorio dice: _el cambio es gratis_." },
            { q: "¿Cómo recibe Camila el número de seguimiento?", options: ["por teléfono", "por correo", "por mensaje de texto"], answer: 1, why: "Ella pregunta: _¿Me podría enviar el número de seguimiento por correo?_" },
            { q: "¿Cuándo llegan las botas nuevas?", options: ["el jueves por la mañana", "el viernes por la tarde", "el sábado"], answer: 0, why: "_Las botas llegan el jueves por la mañana._" },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en por y para. ¿Qué expresa cada frase de la llamada?",
        exercise: {
          id: "l3",
          type: "classify",
          prompt: "Clasifica estas frases de la conversación.",
          categories: ["para: meta, plazo o destino", "por: causa, medio o intercambio"],
          items: [
            { text: "Para hacer un pedido nuevo, marque uno.", cat: 0, why: "Es la finalidad de marcar el uno." },
            { text: "Le llamo por unas botas que compré.", cat: 1, why: "Las botas son el motivo, la causa de la llamada." },
            { text: "Quería cambiarlas por una talla más pequeña.", cat: 1, why: "Intercambio: una talla a cambio de otra." },
            { text: "Las pedí para una excursión al Pico Espejo.", cat: 0, why: "La excursión es la meta de la compra." },
            { text: "Le mandamos las nuevas por mensajería urgente.", cat: 1, why: "La mensajería es el medio de envío." },
            { text: "Muchas gracias por la ayuda.", cat: 1, why: "_Gracias por_: agradeces una causa." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Preguntas frecuentes · Tejidos del Páramo",
    genre: "Página de ayuda de una tienda en línea",
    frame: "Una pequeña tienda de Mérida vende ruanas, gorros y bufandas de lana por internet. Esta es su página de preguntas frecuentes.",
    text: [
      "**¿Cómo hago un pedido?** Elige tu producto, la talla y el color, y añádelo al carrito. Puedes pagar con tarjeta o por transferencia. Al confirmar el pago, recibes un correo con el número de pedido. Si quieres un regalo, escribe «Es para…» en las notas y lo envolvemos gratis.",
      "**¿Cuánto tarda el envío?** Dentro de Mérida, entregamos en 24 horas. Para el resto de Venezuela, el paquete tarda de tres a cinco días hábiles, porque pasa por nuestro centro de distribución en Barquisimeto. Si lo necesitas para una fecha concreta, avísanos antes de pagar.",
      "**¿Cómo sigo mi envío?** Después de enviar el paquete, te mandamos el número de seguimiento por correo y por WhatsApp. Con ese número puedes rastrear la encomienda en la página de la empresa de transporte.",
      "**¿Puedo devolver o cambiar un producto?** Sí. Tienes un plazo de 15 días desde la entrega. Por higiene, no aceptamos devoluciones de gorros usados. Si una ruana te queda grande o pequeña, la cambiamos por otra talla sin coste. Si el producto llegó dañado por el transporte, te devolvemos el dinero completo.",
      "**¿Por qué los precios cambian a veces?** Trabajamos con lana de oveja de los páramos y el precio depende de la temporada. Por eso actualizamos los precios cada tres meses. ¿Tienes otra pregunta? Escríbenos: respondemos de lunes a sábado, por la mañana y por la tarde.",
    ],
    glossary: [
      { es: "la ruana", en: "a heavy woollen poncho typical of the Venezuelan and Colombian Andes" },
      { es: "envolver", en: "to gift-wrap" },
      { es: "días hábiles", en: "working days" },
      { es: "sin coste (sin costo en gran parte de América)", en: "free of charge" },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee la página y responde.",
        items: [
          { q: "Vives en Maracaibo. ¿Cuánto tarda tu pedido?", options: ["24 horas", "de tres a cinco días hábiles", "15 días"], answer: 1, why: "Maracaibo está fuera de Mérida: _para el resto de Venezuela, de tres a cinco días hábiles_." },
          { q: "¿Por qué tarda más fuera de Mérida?", options: ["Porque el paquete pasa por Barquisimeto.", "Porque la lana viene de los páramos.", "Porque solo trabajan por la mañana."], answer: 0, why: "El texto dice: _porque pasa por nuestro centro de distribución en Barquisimeto_." },
          { q: "¿Qué tienes que hacer si quieres envolver un producto para regalo?", options: ["pagar un poco más", "escribir «Es para…» en las notas", "llamar por teléfono"], answer: 1, why: "_Escribe «Es para…» en las notas y lo envolvemos gratis._" },
        ],
      },
      {
        id: "r2",
        type: "classify",
        title: "¿Qué dice la tienda?",
        prompt: "Según el texto, ¿cada caso es posible o no?",
        categories: ["sí, es posible", "no, no es posible"],
        items: [
          { text: "Cambiar una ruana por otra talla sin pagar.", cat: 0, why: "_La cambiamos por otra talla sin coste._" },
          { text: "Devolver un gorro que ya usaste.", cat: 1, why: "_Por higiene, no aceptamos devoluciones de gorros usados._" },
          { text: "Recibir el dinero si el producto llegó roto.", cat: 0, why: "_Si el producto llegó dañado por el transporte, te devolvemos el dinero completo._" },
          { text: "Devolver un producto un mes después de recibirlo.", cat: 1, why: "El plazo es de **15 días** desde la entrega." },
          { text: "Seguir el paquete con un número que llega por WhatsApp.", cat: 0, why: "_Te mandamos el número de seguimiento por correo y por WhatsApp._" },
          { text: "Escribir a la tienda un domingo y recibir respuesta ese día.", cat: 1, why: "Responden **de lunes a sábado**." },
        ],
      },
    ],
    noticing: {
      prompt: "Toca cada fragmento: todos usan por o para con un sentido distinto.",
      items: [
        { quote: "Es para…", note: "**Para** + persona: el destinatario del regalo." },
        { quote: "Si lo necesitas para una fecha concreta", note: "**Para** + fecha: plazo límite." },
        { quote: "porque pasa por nuestro centro de distribución", note: "**Porque** introduce la causa; **por** marca el lugar de paso." },
        { quote: "Por higiene, no aceptamos devoluciones", note: "**Por** + nombre: la causa de la norma." },
        { quote: "Al confirmar el pago, recibes un correo", note: "**Al** + infinitivo (semana 16): en el momento en que confirmas." },
        { quote: "Por eso actualizamos los precios", note: "**Por eso** presenta la consecuencia de la frase anterior." },
      ],
    },
  },
  practice: {
    intro: "Mezcla por y para con lo que ya sabes: conectores, antes de / después de y el condicional de cortesía.",
    exercises: [
      {
        id: "x1",
        type: "error",
        title: "Detective de errores",
        prompt: "Cada frase tiene un error con por, para o porque. Escríbela bien.",
        items: [
          { sentence: "Muchas gracias para responder tan rápido.", answers: ["Muchas gracias por responder tan rápido."], why: "Agradeces algo que la otra persona hizo: **gracias por**." },
          { sentence: "Voy a la oficina de envíos por recoger mi paquete.", answers: ["Voy a la oficina de envíos para recoger mi paquete."], why: "Recoger el paquete es la meta: **para** + infinitivo." },
          { sentence: "Compré esta chaqueta para cuarenta dólares.", answers: ["Compré esta chaqueta por cuarenta dólares."], why: "El precio es un intercambio: **por**." },
          { sentence: "No pude ir a la excursión para la lluvia.", answers: ["No pude ir a la excursión por la lluvia.", "No pude ir a la excursión porque llovía."], why: "La lluvia es la causa: **por** + nombre (o **porque** + verbo)." },
          { sentence: "¿Para qué no pediste el reembolso?", answers: ["¿Por qué no pediste el reembolso?"], why: "Preguntas la causa de algo que no pasó: **¿por qué?**" },
        ],
      },
      {
        id: "x2",
        type: "transform",
        title: "Antes, después, al",
        prompt: "Une las dos frases con la expresión indicada (repaso de la semana 16).",
        items: [
          { source: "Compro algo en línea. Antes leo las opiniones.", instruction: "Usa «antes de» + infinitivo.", answers: ["Antes de comprar algo en línea, leo las opiniones.", "Leo las opiniones antes de comprar algo en línea."], why: "Mismo sujeto (yo) → **antes de** + infinitivo, sin conjugar." },
          { source: "Recibí el paquete. Después revisé que todo estaba bien.", instruction: "Usa «después de» + infinitivo.", answers: ["Después de recibir el paquete, revisé que todo estaba bien.", "Revisé que todo estaba bien después de recibir el paquete."], why: "**Después de** + infinitivo: _recibir_, no _recibí_." },
          { source: "Abrí la caja y en ese momento vi que la pantalla estaba rota.", instruction: "Usa «al» + infinitivo.", answers: ["Al abrir la caja, vi que la pantalla estaba rota.", "Vi que la pantalla estaba rota al abrir la caja."], why: "**Al** + infinitivo = en el momento en que." },
        ],
      },
      {
        id: "x3",
        type: "context",
        title: "Pedir con cortesía",
        prompt: "Estás hablando con atención al cliente. Elige la frase más adecuada.",
        items: [
          { context: "Quieres el número de seguimiento. Hablas con una agente que no conoces.", q: "Dices:", options: ["¿Me podría dar el número de seguimiento?", "Dame el número de seguimiento.", "Quiero el número y ya."], answer: 0, why: "Con una desconocida en un servicio, el condicional **podría** suaviza la petición." },
          { context: "Llamas para cambiar la dirección de entrega.", q: "Empiezas así:", options: ["Quería cambiar la dirección de entrega, por favor.", "Cambio la dirección de entrega.", "Cambie usted la dirección."], answer: 0, why: "**Quería** + infinitivo es una forma muy amable de presentar lo que necesitas." },
          { context: "El paquete llegó dañado y quieres explicar tu decisión de devolverlo.", q: "Lo mejor es:", options: ["Como llegó dañado, me gustaría devolverlo.", "Llegó dañado, por qué lo devuelvo.", "Para dañado, lo devuelvo."], answer: 0, why: "**Como** + causa al principio y **me gustaría** para la petición: claro y cortés." },
        ],
      },
      {
        id: "x4",
        type: "order",
        title: "Ordena la explicación",
        prompt: "Toca las palabras en orden.",
        items: [
          { words: ["Como", "llegó", "tarde,", "pedí", "un", "descuento."], en: "As it arrived late, I asked for a discount." },
          { words: ["Lo", "compré", "por", "internet", "para", "ahorrar", "tiempo."], en: "I bought it online to save time." },
          { words: ["Me", "quedaba", "pequeño,", "así", "que", "lo", "cambié."], en: "It was too small for me, so I exchanged it." },
        ],
      },
      {
        id: "x5",
        type: "open",
        title: "Escritura guiada: por qué y para qué",
        prompt: "Escribe dos o tres frases para cada situación. Usa **porque / por** para la causa y **para** para la meta.",
        items: [
          {
            prompt: "Tu última compra en línea: ¿qué compraste, por qué en línea y para qué lo necesitabas?",
            model: "Compré unos auriculares por internet porque en mi barrio no hay tiendas de electrónica. Los necesitaba para mis clases de español en línea.",
            checklist: ["Usas **por** o **porque** para la causa.", "Usas **para** + infinitivo o + nombre para la meta.", "El pasado está en indefinido: compré, necesitaba / necesité."],
          },
          {
            prompt: "Un amigo te pregunta: «¿Por qué llamaste a la tienda?». Responde con la causa y la finalidad.",
            model: "Llamé porque el paquete no llegaba. Llamé para pedir el número de seguimiento y para saber cuándo llegaba.",
            checklist: ["Hay una frase con **porque** + verbo conjugado.", "Hay una frase con **para** + infinitivo.", "Escribes _por qué_ en la pregunta y _porque_ en la respuesta."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe un mensaje a una tienda en línea para cambiar o devolver un producto.",
    context: "Compraste algo en una tienda en línea (ropa, zapatos, un aparato…) y tienes un problema. Escribe por el formulario de contacto de la tienda.",
    steps: [
      "Saluda con cortesía y di qué compraste, cuándo y el número de pedido.",
      "Explica el problema y su causa con **porque**, **por** o **como**.",
      "Di qué quieres: cambiar, devolver o pedir el reembolso, con **quería** / **me gustaría** / **¿podría…?**",
      "Añade para qué o para cuándo lo necesitas (**para** + infinitivo / **para** + fecha).",
      "Despídete y da las gracias (**gracias por**…).",
    ],
    useLanguage: ["Le escribo por…", "porque / como / por eso / así que", "Quería cambiarlo por…", "Me gustaría pedir el reembolso", "Lo necesito para…", "Muchas gracias por su ayuda"],
    model: [
      "Buenos días:",
      "Le escribo por el pedido n.º 3317. La semana pasada compré una chaqueta impermeable talla L para un viaje a la Sierra Nevada de Mérida. Al abrir el paquete, vi que la chaqueta tenía un agujero en la manga. Como el viaje es el 20 de marzo, quería cambiarla por otra igual, en la misma talla. ¿Me podría decir si es posible enviarla antes del día 18? Si no es posible, me gustaría pedir el reembolso.",
      "Muchas gracias por su ayuda.",
      "Un saludo, Valentina Rondón",
    ],
    checklist: [
      "Usas **por** para la causa, el medio o el intercambio y **para** para la meta, el plazo o el destinatario.",
      "Explicas la causa con al menos un conector: _porque_, _como_, _por eso_ o _así que_.",
      "Tu petición es cortés: _quería_, _me gustaría_ o _¿podría…?_",
      "Usas _usted_ (o _ustedes_) de forma coherente en todo el mensaje.",
      "Escribes _gracias por_, nunca _gracias para_.",
    ],
    words: [70, 110],
  },
  speaking: {
    intro: "Grábate, escúchate y repite. Cuida el ritmo de las palabras largas.",
    tasks: [
      {
        title: "Llama a atención al cliente",
        prompt: "Un paquete con un regalo para tu madre no llegó y su cumpleaños es el sábado. Deja un mensaje de voz a la tienda: saluda, da el número de pedido, explica el problema, di para cuándo lo necesitas y pide una solución.",
        prep: ["Le llamo por el pedido número…", "Lo compré para… / Es para…", "Lo necesito para el sábado.", "¿Me podría…? / Quería…"],
        seconds: 60,
        model: "Buenas tardes. Le llamo por el pedido número 5820. Compré una bufanda para mi madre, porque su cumpleaños es el sábado. El seguimiento dice que el paquete está en camino desde hace una semana, pero no llega. La necesito para el viernes como muy tarde. ¿Me podría llamar para decirme qué pasa? Si no llega a tiempo, quería pedir el reembolso. Muchas gracias.",
        selfCheck: ["Digo _seguimiento_ y _reembolso_ sin comerme sílabas.", "Uso **para** con la persona y con la fecha.", "Mi petición usa _podría_ o _quería_."],
      },
      {
        title: "¿Por qué y para qué?",
        prompt: "Elige tres cosas que haces esta semana (estudiar español, ahorrar, ir al gimnasio…). Para cada una, di una causa y una finalidad.",
        prep: ["Estudio español porque…, y lo estudio para…", "Voy al gimnasio por… / para…", "Ahorro dinero para…"],
        seconds: 45,
        model: "Estudio español porque mi pareja es venezolana, y lo estudio para hablar con su familia en Mérida. Voy al gimnasio por mi espalda: me duele mucho. Y ahorro dinero para comprar un pasaje en diciembre.",
        selfCheck: ["Cada cosa tiene una causa y una meta.", "No digo _por_ + infinitivo para una meta."],
      },
      {
        title: "La mejor o la peor compra",
        prompt: "Cuenta la mejor o la peor compra en línea que hiciste. ¿Qué compraste, por cuánto, qué pasó y qué decidiste hacer después?",
        prep: ["Lo compré por… dólares.", "Al recibirlo, vi que…", "Como…, decidí…", "…, así que…"],
        seconds: 60,
        model: "Mi peor compra fue un teléfono que compré por internet por ciento veinte dólares. Al recibirlo, vi que no era el modelo que pedí. Como la tienda no respondía, llamé por teléfono tres veces. Al final me devolvieron el dinero, así que ahora siempre leo las opiniones antes de comprar.",
        selfCheck: ["Uso conectores de causa y consecuencia.", "Uso _al_ o _antes de_ + infinitivo al menos una vez."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo, pon por y para a trabajar en situaciones reales.",
    cards: [
      { move: "Cuenta", task: "Cuenta una compra en línea con un problema: qué pasó, por qué y qué hiciste para resolverlo.", phrases: ["Lo compré por…", "Llegó roto por…", "Llamé para…", "Como…, decidí…"] },
      { move: "Pregunta", task: "Pregúntale a tu profesor o profesora por qué y para qué hace tres cosas de su rutina. Escucha bien la diferencia en sus respuestas.", phrases: ["¿Por qué…?", "¿Y para qué…?", "¿Para cuándo…?"] },
      { move: "Negocia", task: "Juego de rol: tú eres el cliente y tu profesor es el agente. Pide un cambio con cortesía y negocia una fecha de entrega.", phrases: ["Quería cambiarlo por…", "¿Me lo podría enviar para el…?", "¿Y si…?", "Muchas gracias por…"] },
      { move: "Corrige", task: "Di cinco frases con por o para, dos de ellas con un error a propósito. Tu profesor tiene que encontrar los errores y explicarlos.", phrases: ["¿Es correcto o no?", "¿Por qué es para y no por?"] },
    ],
    bring: "Trae la captura de pantalla (o el correo) de una compra en línea real para contar su historia.",
  },
  quiz: {
    items: [
      { type: "choice", q: "«Salgo ___ Caracas en el autobús de las ocho.»", options: ["para", "por", "porque"], answer: 0, why: "Caracas es el destino, la meta del viaje: **para**." },
      { type: "choice", q: "«El vuelo pasa ___ Bogotá antes de llegar a Madrid.»", options: ["para", "por", "a"], answer: 1, why: "Bogotá está en el camino: lugar de paso → **por**." },
      { type: "listen", q: "¿Qué número marcas para hablar con una persona?", audio: "Para pagar una factura, marque uno. Para hablar con una persona, marque nueve. Para repetir este menú, marque asterisco.", voice: "es-VE-m", options: ["el uno", "el nueve", "el asterisco"], answer: 1, why: "_Para hablar con una persona, marque nueve._" },
      { type: "gap", q: "Te mando las fotos del paquete roto ___ WhatsApp ___ que veas el problema.", answers: [["por"], ["para"]], hint: "_para que_ + subjuntivo: solo tienes que elegir la preposición.", why: "WhatsApp es el medio (**por**); que veas el problema es la meta (**para**)." },
      { type: "gap", q: "Este pastel es ___ los vecinos: les damos las gracias ___ cuidar al perro.", answers: [["para"], ["por"]], why: "Destinatario → **para**; agradecer una acción → **gracias por**." },
      { type: "transform", source: "Escribo a la tienda porque quiero saber dónde está mi pedido.", instruction: "Expresa la meta con para + infinitivo.", answers: ["Escribo a la tienda para saber dónde está mi pedido."], why: "_Porque quiero_ + infinitivo = meta → **para saber**." },
      { type: "order", words: ["Lo", "necesito", "para", "el", "lunes", "por", "la", "mañana."], alt: ["Para el lunes por la mañana lo necesito."], why: "**Para** marca el plazo; **por la mañana**, la parte del día." },
      { type: "error", sentence: "Gracias para el código de descuento.", answers: ["Gracias por el código de descuento."], why: "Siempre **gracias por**." },
      { type: "error", sentence: "Cerraron la carretera para la nieve.", answers: ["Cerraron la carretera por la nieve."], why: "La nieve es la causa: **por**." },
      { type: "choice", q: "¿Cuál pregunta pide la finalidad?", options: ["¿Para qué sirve este cable?", "¿Por qué no funciona este cable?", "¿Porque es caro este cable?"], answer: 0, why: "**¿Para qué?** pregunta la meta o la utilidad; **¿por qué?** pregunta la causa." },
      { type: "transform", source: "Pagué y después recibí la confirmación.", instruction: "Usa «después de» + infinitivo.", answers: ["Después de pagar, recibí la confirmación.", "Recibí la confirmación después de pagar."], why: "**Después de** + infinitivo: _pagar_." },
      { type: "open", prompt: "Escribe a una tienda: el pantalón que compraste te queda grande. Explica el problema y pide un cambio con cortesía (2–3 frases).", model: "Buenas tardes. Le escribo por el pantalón que compré el lunes: me queda grande. ¿Podría cambiarlo por una talla 38? Muchas gracias por su ayuda.", checklist: ["Le escribo por…", "un cambio con _por_ + talla", "podría / quería / me gustaría", "gracias por"] },
    ],
  },
  complete: {
    canNow: [
      "Decir para qué hago algo con **para** + infinitivo y por qué lo hago con **porque** o **por**.",
      "Usar **para** con destinos, plazos y destinatarios, y **por** con medios, precios y lugares de paso.",
      "Hacer, seguir, cambiar y devolver un pedido en línea.",
      "Entender un menú grabado y una llamada de atención al cliente.",
      "Pronunciar palabras largas como _devolución_ o _seguimiento_ sin perder sílabas.",
    ],
    review: ["Gracias **por**, nunca gracias para.", "Meta → **para** + infinitivo.", "**¿Por qué?** (pregunta) / **porque** (respuesta).", "Precio e intercambio → **por**."],
  },
  related: [
    { path: "/ideas-dentro-de-ideas", label: "Ideas dentro de ideas · porque y para + infinitivo" },
    { path: "/antes-despues-cuando", label: "Antes, después, cuando" },
  ],
};
