// B1 expedition: one authored conversation per landmark of the climb.
// The world sets the scene (scene), a compact choice starts the talk (question
// + choices, each with a short reaction), and an open spoken question follows
// (open). Early stations are personal and concrete; the middle asks for
// decisions and opinions; the top asks for hypotheses and reflection.
const stations = [
  {
    id: 'b1-ruta-sobre-ti', level: 'B1', zone: 'sobre-ti', type: 'choice', station: true,
    scene: 'Entras en un bosque donde los hongos son más altos que las casas. Arriba, entre la niebla, brilla algo dorado.',
    question: 'Cuando llegas a un lugar nuevo, ¿qué te llama la atención primero?',
    choices: ['La gente y cómo se comporta', 'La comida y los olores', 'La naturaleza y los paisajes'],
    reactions: [
      'Te interesan las personas. ¿Qué detalle de la gente notas enseguida?',
      'Empiezas por los sentidos. ¿Qué olor o sabor recuerdas de un viaje?',
      'Te fijas en el paisaje. ¿Qué paisaje te impresionó la primera vez que lo viste?',
    ],
    open: 'Cuenta un lugar al que llegaste por primera vez y que te sorprendió. ¿Qué fue lo primero que notaste y por qué te sorprendió?',
    followUps: ['¿Ese lugar cambió la idea que tenías antes de ir?', '¿Volverías? ¿Qué harías de forma diferente?'],
    glosses: [{ es: 'llamar la atención', en: 'to catch your attention' }, { es: 'el paisaje', en: 'the landscape' }],
    support: ['Lo primero que noté fue…', 'Me sorprendió que…', 'Yo pensaba que… pero…'],
    teacherNote: 'Pregunta de calentamiento. Pide un lugar concreto y un detalle sensorial antes de pasar a la opinión.',
  },
  {
    id: 'b1-ruta-vida-real', level: 'B1', zone: 'vida-real', type: 'choice', station: true,
    scene: 'Al lado del camino hay una cesta llena de setas recién cortadas. No hay nadie cerca.',
    question: 'Encuentras una cesta llena de setas y no ves a su dueño. ¿Qué haces?',
    choices: ['La miro y sigo mi camino', 'Espero un rato a que vuelva su dueño', 'Me llevo una o dos setas'],
    reactions: [
      'Respetas lo que no es tuyo. ¿Siempre actúas así?',
      'Paciencia y responsabilidad. ¿Cuánto tiempo esperarías?',
      'Solo una o dos… ¿Dónde está el límite entre tomar prestado y robar?',
    ],
    open: '¿Alguna vez encontraste algo que no era tuyo: dinero, un móvil, una cartera? ¿Qué hiciste y por qué?',
    followUps: ['¿Qué esperarías que hiciera otra persona si encontrara algo tuyo?', '¿Cambia tu decisión si el objeto vale mucho dinero?'],
    glosses: [{ es: 'la cesta', en: 'the basket' }, { es: 'el dueño', en: 'the owner' }, { es: 'la cartera', en: 'the wallet' }],
    support: ['Una vez encontré…', 'Lo que hice fue…', 'Creo que lo correcto es…'],
    teacherNote: 'Situación cotidiana para practicar el pretérito indefinido al narrar. Pide qué pasó al final.',
  },
  {
    id: 'b1-ruta-elige', level: 'B1', zone: 'elige', type: 'choice', station: true,
    scene: 'Unas setas doradas cubren el sombrero. Una mujer del pueblo te dice: «Son deliciosas. Aquí las comemos desde siempre».',
    question: 'Nunca has visto estas setas, pero una persona local dice que son deliciosas. ¿Las pruebas?',
    choices: ['Sí, confío en ella', 'Solo si ella las come primero', 'No, prefiero no arriesgarme'],
    reactions: [
      'Confías en la experiencia local. ¿Siempre te fías de la gente del lugar?',
      'Prudente pero curioso. ¿Haces lo mismo con la comida de otros países?',
      'Mejor seguro. ¿Hay comidas que nunca probarías, aunque todo el mundo las coma?',
    ],
    open: '¿Alguna vez comiste algo sin saber exactamente qué era? ¿Dónde fue y cómo te sentiste al descubrirlo?',
    followUps: ['¿Cuál es la comida más extraña que probaste viajando?', '¿Qué comida de tu país sorprende a los extranjeros?'],
    glosses: [{ es: 'probar', en: 'to try (food)' }, { es: 'arriesgarse', en: 'to take a risk' }, { es: 'fiarse de', en: 'to trust' }],
    support: ['Una vez probé…', 'No sabía que era…', 'Al principio… pero después…'],
    teacherNote: 'Primera parada de «¿se come o no?». La elección es solo el punto de partida: lo importante es la anécdota.',
  },
  {
    id: 'b1-ruta-opinion', level: 'B1', zone: 'opinion', type: 'choice', station: true,
    scene: 'Dos setas casi idénticas crecen juntas. Una se come. La otra puede hacerte mucho daño.',
    question: 'Para distinguir dos setas casi idénticas, ¿en quién confías más?',
    choices: ['En una persona con mucha experiencia', 'En una aplicación del móvil', 'En un libro especializado'],
    reactions: [
      'La experiencia primero. ¿Y si esa persona se equivoca una vez?',
      'La tecnología. ¿Te ha fallado alguna vez una aplicación?',
      'Una fuente escrita y revisada. ¿Lees antes de decidir cosas importantes?',
    ],
    open: '¿Confías más en una persona con experiencia o en lo que encuentras en internet? Da un ejemplo de una decisión real.',
    followUps: ['¿Cómo sabes si una información de internet es fiable?', '¿A quién pides consejo cuando tienes un problema de salud?'],
    glosses: [{ es: 'distinguir', en: 'to tell apart' }, { es: 'fiable', en: 'reliable' }, { es: 'equivocarse', en: 'to make a mistake' }],
    support: ['Yo confío más en… porque…', 'Depende de…', 'Por ejemplo, cuando…'],
    teacherNote: 'Opinión con un ejemplo. Anima a comparar dos fuentes con «más… que».',
  },
  {
    id: 'b1-ruta-suposiciones', level: 'B1', zone: 'suposiciones', type: 'suppose', station: true,
    scene: 'Parece perfecto: rojo brillante, con puntos blancos, como en un cuento. Huele bien. ¿Lo comerías?',
    question: 'Estás perdido en el bosque y tienes mucha hambre. Solo encuentras hongos como este. ¿Qué haces?',
    choices: ['Lo como: tengo hambre', 'Lo dejo y sigo buscando', 'Busco información primero'],
    reactions: [
      'El hambre manda. ¿Qué otras decisiones tomamos mal cuando estamos cansados o con hambre?',
      'Resistes. ¿Cuánto tiempo crees que aguantarías sin comer?',
      'Primero investigar. ¿Cómo buscarías información en medio del bosque?',
    ],
    open: '¿Qué haces normalmente cuando no estás seguro de algo importante? ¿Esperas, preguntas o decides rápido?',
    followUps: ['Si estuvieras perdido tres días en un bosque, ¿qué harías primero?', '¿Qué decisión rápida tomaste alguna vez y luego te arrepentiste?'],
    glosses: [{ es: 'estar perdido', en: 'to be lost' }, { es: 'aguantar', en: 'to hold out' }, { es: 'arrepentirse', en: 'to regret' }],
    support: ['Si estuviera perdido, yo…', 'Normalmente, cuando no estoy seguro…', 'Lo primero que haría sería…'],
    teacherNote: 'Hongo rojo con puntos blancos: hermoso y tóxico. Introduce el condicional (comería, buscaría) sin corregir en exceso.',
  },
  {
    id: 'b1-ruta-afirmacion', level: 'B1', zone: 'afirmacion', type: 'statement', station: true,
    scene: 'Un círculo de hongos violetas y negros rodea el sombrero. Son preciosos. Nadie se atreve a tocarlos.',
    question: '¿Estás de acuerdo con esta frase?',
    statement: 'Lo más bonito suele ser lo más peligroso.',
    choices: ['De acuerdo', 'Depende', 'No estoy de acuerdo'],
    reactions: [
      'Belleza y peligro van juntos para ti. ¿Por qué crees que nos atrae lo peligroso?',
      'Depende. ¿De qué depende exactamente?',
      'No lo ves así. ¿Qué cosa bonita conoces que sea totalmente segura?',
    ],
    open: 'Algo puede ser hermoso y peligroso al mismo tiempo. ¿Qué ejemplos se te ocurren en la naturaleza, en la ciudad o en las relaciones?',
    followUps: ['¿Alguna vez algo te pareció atractivo justamente porque era un poco peligroso?', '¿Qué deporte o actividad arriesgada te gustaría probar?'],
    glosses: [{ es: 'atreverse', en: 'to dare' }, { es: 'peligroso', en: 'dangerous' }, { es: 'atraer', en: 'to attract' }],
    support: ['Estoy de acuerdo porque…', 'Depende de si…', 'Un buen ejemplo es…'],
    teacherNote: 'Reacción a una afirmación. Pide dos ejemplos de ámbitos distintos para alargar la respuesta.',
  },
  {
    id: 'b1-ruta-compara', level: 'B1', zone: 'compara', type: 'compare', station: true,
    scene: 'Aquí los hongos brillan azules en la sombra. Nadie sabe por qué. El camino sigue hacia arriba, entre luces.',
    question: 'En un viaje, ¿qué te atrae más?',
    choices: ['Un lugar misterioso que casi nadie conoce', 'Un lugar famoso que todos recomiendan'],
    reactions: [
      'Te gusta descubrir. ¿Qué haces si el lugar desconocido te decepciona?',
      'Prefieres lo seguro. ¿Alguna vez un lugar famoso no fue como esperabas?',
    ],
    open: 'Compara un viaje que planificaste con mucho detalle y otro improvisado. ¿Cuál recuerdas mejor y por qué?',
    followUps: ['¿Qué ventajas tiene planificar todo? ¿Y qué desventajas?', '¿Prefieres viajar solo, en pareja o en grupo? Compara dos opciones.'],
    glosses: [{ es: 'improvisado', en: 'unplanned' }, { es: 'decepcionar', en: 'to disappoint' }, { es: 'planificar', en: 'to plan' }],
    support: ['El primero fue más… que…', 'En cambio,…', 'Lo recuerdo mejor porque…'],
    teacherNote: 'Comparación: busca «más/menos… que», «en cambio», «mientras que».',
  },
  {
    id: 'b1-ruta-recuerdos', level: 'B1', zone: 'recuerdos', type: 'memory', station: true,
    scene: 'Estás sobre un sombrero gigante, a la altura de los árboles. Mira atrás: desde aquí ves todo el camino que hiciste.',
    question: 'Mira el camino que hiciste. ¿Qué tipo de riesgo te ha dado mejores resultados en tu vida?',
    choices: ['Un viaje o un cambio de ciudad', 'Un estudio o un trabajo nuevo', 'Conocer a una persona'],
    reactions: [
      'Moverse cambia la perspectiva. ¿Qué aprendiste lejos de casa?',
      'Un cambio profesional. ¿Tuviste miedo al principio?',
      'Las personas cambian vidas. ¿Cómo empezó esa relación?',
    ],
    open: '¿Qué riesgo pequeño tomaste alguna vez y terminó siendo una buena decisión? Cuenta cómo pasó.',
    followUps: ['¿Qué habría pasado si no te hubieras arriesgado?', '¿Qué le dirías a alguien que tiene miedo de dar ese mismo paso?'],
    glosses: [{ es: 'arriesgarse', en: 'to take a chance' }, { es: 'dar un paso', en: 'to take a step' }, { es: 'al principio', en: 'at first' }],
    support: ['Hace unos años…', 'Al principio tenía miedo, pero…', 'Al final…'],
    teacherNote: 'Mirador del recorrido. Narración en pasado: pretérito indefinido e imperfecto (tenía miedo, tomé la decisión).',
  },
  {
    id: 'b1-ruta-futuro', level: 'B1', zone: 'futuro', type: 'ranking', station: true,
    scene: 'Unos hongos de repisa crecen en el tronco de un roble enorme. Desde la copa, el bosque parece no terminar nunca.',
    question: 'Vas a vivir una semana en este bosque. Elige las tres cosas más importantes, en orden.',
    choices: ['Una linterna', 'Un libro sobre setas', 'Comida de casa', 'Un amigo o una amiga', 'Un cuaderno', 'El móvil'],
    reactions: [],
    open: 'Si pudieras vivir una semana lejos de la ciudad y de la tecnología, ¿lo harías? ¿Qué echarías de menos y qué no?',
    followUps: ['¿Qué aprenderías sobre ti en esa semana?', '¿Cuál es el lugar más tranquilo donde has dormido?'],
    glosses: [{ es: 'la linterna', en: 'the flashlight' }, { es: 'echar de menos', en: 'to miss' }, { es: 'el cuaderno', en: 'the notebook' }],
    support: ['Lo primero que llevaría sería…', 'Echaría de menos…', 'No necesitaría…'],
    teacherNote: 'Clasificación: pide justificar el orden. Después, la pregunta abierta usa el condicional.',
  },
  {
    id: 'b1-ruta-cambia', level: 'B1', zone: 'cambia', type: 'change-condition', station: true,
    scene: 'La niebla es tan espesa que no ves el próximo hongo. Solo sabes que está ahí, más arriba. Tienes que saltar igual.',
    question: 'Cuando tienes que decidir sin toda la información, ¿qué haces?',
    choices: ['Sigo mi intuición', 'Espero hasta saber más', 'Pido la opinión de alguien'],
    reactions: [
      'Intuición. ¿Te ha funcionado bien hasta ahora?',
      'Esperar también es decidir. ¿Cuándo esperar es un error?',
      'Otra mirada ayuda. ¿A quién pides consejo normalmente?',
    ],
    open: 'Cuenta una decisión que tomaste sin estar seguro. ¿Qué pasó? ¿Volverías a decidir lo mismo?',
    condition: 'Ahora imagina que tu decisión también afecta a tu familia o a tus amigos. ¿Cambia tu respuesta?',
    followUps: ['¿Es más fácil decidir por ti o por otras personas?', '¿Qué decisiones prefieres no tomar solo?'],
    glosses: [{ es: 'la niebla', en: 'the fog' }, { es: 'la intuición', en: 'gut feeling' }, { es: 'afectar a', en: 'to affect' }],
    support: ['Cuando no estoy seguro…', 'En ese momento opté por…', 'Si afectara a mi familia…'],
    teacherNote: 'Cambio de condición: primero la respuesta personal, después revela la condición y pide revisar la postura.',
  },
  {
    id: 'b1-ruta-contrario', level: 'B1', zone: 'contrario', type: 'reverse', station: true,
    scene: 'Estás por encima de las nubes. Debajo, el bosque ha desaparecido. Solo los hongos más altos atraviesan el cielo.',
    question: '¿Qué es mejor en la vida?',
    choices: ['Evitar los riesgos siempre que se pueda', 'Aprender a reconocer qué riesgos valen la pena'],
    reactions: [
      'La seguridad primero. Ahora defiende lo contrario: ¿qué perdemos si nunca nos arriesgamos?',
      'Riesgos inteligentes. Ahora defiende lo contrario: ¿por qué alguien preferiría evitarlos todos?',
    ],
    open: 'Defiende durante un minuto la opción que NO elegiste. Después di si tu opinión cambió un poco.',
    followUps: ['¿Qué riesgos vale la pena enseñar a los niños?', '¿Te consideras una persona prudente o atrevida? Da un ejemplo.'],
    glosses: [{ es: 'valer la pena', en: 'to be worth it' }, { es: 'prudente', en: 'cautious' }, { es: 'atrevido', en: 'daring' }],
    support: ['Alguien podría pensar que…', 'Una ventaja de… es que…', 'Sigo pensando que… aunque…'],
    teacherNote: 'Defender la postura contraria. Valora la argumentación, no la opinión.',
  },
  {
    id: 'b1-ruta-final', level: 'B1', zone: 'final', type: 'final', station: true,
    scene: 'Llegaste a la cima. Debajo, un mar de nubes. A lo lejos, los hongos más altos asoman como islas. Todo el camino está a tus pies.',
    question: 'Llegaste hasta las nubes. ¿Qué lugar real te hizo sentir una sorpresa parecida?',
    open: 'Describe ese lugar: dónde estaba, con quién estabas y qué sentiste. ¿Por qué crees que algunos lugares nos cambian?',
    followUps: ['¿Qué parada de hoy te hizo pensar más?', '¿Qué riesgo te gustaría tomar este año?'],
    glosses: [{ es: 'la cima', en: 'the top' }, { es: 'a tus pies', en: 'below you' }, { es: 'asomar', en: 'to peek out' }],
    support: ['El lugar que más me sorprendió fue…', 'La sensación fue…', 'Hoy me di cuenta de que…'],
    teacherNote: 'Cierre reflexivo. Conecta la respuesta con dos paradas del recorrido.',
  },
];
export default stations;
