import type { Module } from "../../types";

export const b1w09: Module = {
  id: "b1-09",
  level: "b1",
  week: 9,
  kind: "core",
  title: "Yo que tú",
  subtitle: "El condicional simple para aconsejar, pedir con cortesía y expresar deseos, y todo lo necesario para una entrevista de trabajo.",
  stop: { place: "Cusco", country: "Perú" },
  minutes: 85,
  newObjectives: [
    "b1.gram.condicional-simple",
    "b1.voc.trabajo-entrevistas",
    "b1.pron.modalidad-cortesia",
    "b1.fun.entrevista-trabajo",
    "b1.spk.entrevista-simulada",
  ],
  reviewObjectives: [
    "b1.gram.relativas-modo",
    "b1.gram.relativos-quien-donde",
    "b1.fun.describir-ideal",
    "b1.gram.opinion-subjuntivo",
  ],
  prerequisites: ["b1-08"],
  goal: {
    canDo: "Al final de esta semana puedes dar consejos con yo que tú y deberías, pedir cosas con cortesía, hablar de tus deseos profesionales y responder con seguridad a las preguntas de una entrevista de trabajo.",
    canDoEn: "By the end of this week, you can give advice with 'yo que tú' and 'deberías', make polite requests, talk about your career wishes and answer job-interview questions confidently.",
    steps: [
      "Aprende las formas del condicional, también las irregulares: `tendría`, `podría`, `haría`, `diría`.",
      "Usa el condicional para aconsejar (`yo que tú, aceptaría`), pedir (`¿podría…?`) y desear (`me encantaría…`).",
      "Aprende el vocabulario de las ofertas de empleo y de las entrevistas, con sus variantes regionales.",
      "Distingue al oído `podía` y `podría`, y suaviza tus peticiones con la entonación.",
      "Escucha una entrevista para un puesto de guía en una agencia de Cusco.",
      "Haz una entrevista simulada de cinco preguntas con ejemplos concretos.",
    ],
  },
  theory: {
    intro: "Esta semana estás en **Cusco**, la antigua capital inca, donde miles de personas trabajan en turismo: guías, recepcionistas, cocineros, conductores. Es un buen lugar para preparar una entrevista de trabajo. La herramienta gramatical de la semana, el **condicional**, te sirve para sonar prudente, amable y profesional.",
    parts: [
      {
        heading: "Las formas del condicional",
        body: [
          "El condicional se forma como el futuro: a partir del **infinitivo completo**, al que se añaden unas terminaciones. Las terminaciones son iguales para los tres grupos de verbos y coinciden con las del imperfecto de _-er/-ir_: **-ía, -ías, -ía, -íamos, -íais, -ían**. _Trabajar → trabajaría_, _ser → sería_, _vivir → viviría_.",
          "La **í** lleva siempre tilde y es la sílaba fuerte: _tra-ba-ja-**rí**-a_. Esa tilde marca el hiato: la _i_ y la _a_ se pronuncian en dos sílabas.",
          "Los verbos irregulares son **los mismos que en el futuro** y con la misma raíz. Si ya sabes _tendré_, ya sabes _tendría_. Hay tres grupos: (1) la vocal del infinitivo se cambia por **d**: _tener → tendr-_, _poner → pondr-_, _salir → saldr-_, _venir → vendr-_, _valer → valdr-_; (2) la vocal desaparece: _poder → podr-_, _saber → sabr-_, _haber → habr-_, _querer → querr-_, _caber → cabr-_; (3) dos raíces especiales: _hacer → har-_, _decir → dir-_.",
          "Los compuestos siguen al verbo base: _mantener → mantendría_, _proponer → propondría_, _deshacer → desharía_, _suponer → supondría_.",
        ],
        support: [
          "The conditional usually translates English 'would': _trabajaría_ = I would work. But careful: when 'would' describes a habit in the past ('When I was a kid, I would play outside'), Spanish uses the imperfect: _jugaba fuera_.",
        ],
        table: {
          caption: "Condicional: regulares e irregulares",
          head: ["Persona", "trabajar", "tener", "poder", "hacer", "decir"],
          rows: [
            ["yo", "trabajaría", "tendría", "podría", "haría", "diría"],
            ["tú / vos", "trabajarías", "tendrías", "podrías", "harías", "dirías"],
            ["usted, él, ella", "trabajaría", "tendría", "podría", "haría", "diría"],
            ["nosotros/as", "trabajaríamos", "tendríamos", "podríamos", "haríamos", "diríamos"],
            ["vosotros/as", "trabajaríais", "tendríais", "podríais", "haríais", "diríais"],
            ["ustedes, ellos, ellas", "trabajarían", "tendrían", "podrían", "harían", "dirían"],
          ],
        },
        examples: [
          { es: "Con más experiencia, Paula podría ser jefa de guías." },
          { es: "¿Saldrías con nosotros a celebrar si te dan el puesto?" },
          { es: "Yo no diría eso en una entrevista." },
          { es: "En tu lugar, yo pondría el inglés al principio del currículum." },
        ],
        mistakes: [
          { wrong: "No sabería qué responder.", right: "No sabría qué responder.", why: "_Saber_ pierde la vocal: **sabr-** → _sabría_." },
          { wrong: "¿Poderías ayudarme con el currículum?", right: "¿Podrías ayudarme con el currículum?", why: "_Poder_ → **podr-**: _podrías_." },
          { wrong: "Yo haceria lo mismo.", right: "Yo haría lo mismo.", why: "_Hacer_ tiene raíz especial **har-**; y la **í** lleva tilde." },
          { wrong: "Decirías la verdad?", right: "¿Dirías la verdad?", why: "_Decir_ → **dir-**. Y en español la pregunta lleva signo de apertura." },
        ],
        tip: "Aprende los irregulares en una frase que tenga sentido para ti: _Yo que tú, **tendría** paciencia, **diría** la verdad y **haría** la entrevista con calma._",
      },
      {
        heading: "Aconsejar: yo que tú, yo en tu lugar, deberías",
        body: [
          "El condicional es la forma más natural de dar consejos porque te pones **imaginariamente en el lugar** de la otra persona: _Yo que tú, aceptaría la oferta_ = si yo fuera tú, aceptaría. Las fórmulas más frecuentes son **Yo que tú** / **Yo en tu lugar** + condicional (en primera persona: _yo **hablaría**_).",
          "También puedes aconsejar en segunda persona con **deberías**, **podrías** o **tendrías que** + infinitivo: _Deberías preparar ejemplos concretos_; _Podrías llamar para confirmar_; _Tendrías que llevar el título impreso_. _Deberías_ es un consejo; _tendrías que_ suena más insistente.",
          "Otra opción impersonal: **Sería mejor / Sería buena idea / Lo mejor sería** + infinitivo: _Sería buena idea llegar diez minutos antes_.",
          "Compara con lo que aprendiste en la semana 4: _Te recomiendo que **prepares** ejemplos_ (verbo de influencia + que + subjuntivo). Las dos formas son correctas. El condicional suena un poco más suave y personal; _te recomiendo que_, más directo.",
          "En conversación coloquial también oirás **yo que tú** con presente: _Yo que tú, lo llamo ya_. Es muy común en España y en partes de América, pero en un contexto cuidado usa el condicional.",
        ],
        table: {
          caption: "Fórmulas para aconsejar",
          head: ["Fórmula", "Persona del verbo", "Ejemplo"],
          rows: [
            ["Yo que tú / Yo en tu lugar", "yo + condicional", "Yo que tú, pediría más información sobre el horario."],
            ["Deberías / Podrías + infinitivo", "tú", "Deberías hablar de tu experiencia en Machu Picchu."],
            ["Tendrías que + infinitivo", "tú (más insistente)", "Tendrías que actualizar tu currículum."],
            ["Sería mejor / Lo mejor sería + infinitivo", "impersonal", "Lo mejor sería no hablar mal de tu antiguo jefe."],
            ["Te recomiendo que + subjuntivo", "tú (repaso semana 4)", "Te recomiendo que investigues la empresa."],
          ],
        },
        examples: [
          { es: "—No sé si aceptar el trabajo en Lima. —Yo en tu lugar, lo aceptaría: es una gran oportunidad." },
          { es: "Deberías buscar un trabajo que te permita practicar inglés." },
          { es: "Yo que tú, no diría que tu debilidad es «ser demasiado perfeccionista»." },
        ],
        mistakes: [
          { wrong: "Yo que tú, hablarías con la jefa.", right: "Yo que tú, hablaría con la jefa.", why: "Con _yo que tú_ el verbo va en **primera persona**: hablas de lo que harías tú mismo." },
          { wrong: "Deberías a preparar la entrevista.", right: "Deberías preparar la entrevista.", why: "_Deber_ + infinitivo, **sin preposición**." },
          { wrong: "Te recomiendo que preparas ejemplos.", right: "Te recomiendo que prepares ejemplos.", why: "Con _te recomiendo que_ el verbo va en **subjuntivo**." },
        ],
        tip: "_Yo que tú_ va seguido normalmente de una coma en la escritura y de una pequeña pausa al hablar: _Yo que tú, | aceptaría_.",
      },
      {
        heading: "Pedir con cortesía y expresar deseos",
        body: [
          "El condicional **suaviza** las peticiones: las presenta como algo hipotético y deja espacio para decir que no. Compara: _Cierre la puerta_ (orden) → _¿Puede cerrar la puerta?_ (petición) → _¿**Podría** cerrar la puerta?_ (petición amable) → _¿Le **importaría** cerrar la puerta?_ (muy cortés).",
          "Fórmulas frecuentes: **¿Podría(s) + infinitivo?**, **¿Le / Te importaría + infinitivo?**, **¿Sería posible + infinitivo?**, **Me gustaría + infinitivo** (para pedir algo para ti: _Me gustaría hacerle una pregunta sobre el horario_). En A2 aprendiste también **quería** (imperfecto de cortesía): _Quería preguntarle por el sueldo_. _Quería_ y _querría_ significan lo mismo aquí; _quería_ es mucho más frecuente.",
          "Para los **deseos**: **Me gustaría / Me encantaría + infinitivo** (_Me encantaría trabajar como guía en el Valle Sagrado_) y **¡Qué bien me vendría…!** (_¡Qué bien me vendría un trabajo con horario flexible!_). Atención a la concordancia de _gustar_: _Me gustaría **un** puesto_ / _Me gustarían **unas** condiciones mejores_; pero con infinitivo, siempre singular: _Me gustaría **viajar** y **conocer** gente_.",
          "**Tú o usted.** En una entrevista en Perú, México o Colombia lo normal es tratar al entrevistador de **usted**, al menos al principio. En España muchas empresas usan **tú** desde el primer momento. Si dudas, empieza de usted y cambia si la otra persona te tutea.",
        ],
        table: {
          caption: "De directo a muy cortés",
          head: ["Directo", "Amable", "Muy cortés"],
          rows: [
            ["Mándeme la información.", "¿Podría mandarme la información?", "¿Le importaría mandarme la información?"],
            ["Quiero saber el horario.", "Quería saber el horario.", "Me gustaría saber cuál sería el horario."],
            ["Cambie la fecha de la entrevista.", "¿Sería posible cambiar la fecha?", "¿Habría alguna posibilidad de cambiar la fecha?"],
          ],
        },
        examples: [
          { es: "¿Podría repetir la pregunta, por favor? No la escuché bien." },
          { es: "Me encantaría trabajar en una agencia donde pueda usar mis idiomas." },
          { es: "¿Te importaría revisar mi carta de presentación antes del viernes?" },
        ],
        mistakes: [
          { wrong: "Me gustarían trabajar en turismo.", right: "Me gustaría trabajar en turismo.", why: "Con infinitivo, _gustar_ va siempre en **singular**." },
          { wrong: "¿Podría a explicarme las condiciones?", right: "¿Podría explicarme las condiciones?", why: "_Poder_ + infinitivo, sin preposición." },
        ],
      },
      {
        heading: "La entrevista de trabajo: contar experiencia con ejemplos",
        body: [
          "En una entrevista te piden dos cosas: **qué has hecho** y **cómo lo harías**. Para tu trayectoria usa los tiempos del pasado: el **indefinido** para trabajos terminados con fechas (_Trabajé tres años en un hotel de Arequipa_), el **perfecto** para tu experiencia en general (_He trabajado con grupos de hasta cuarenta personas_) y el **imperfecto** para describir cómo era (_Me encargaba de la recepción_).",
          "Las respuestas fuertes tienen un **ejemplo concreto** en cuatro pasos: la situación, el problema, lo que hiciste y el resultado. _Una vez, un grupo perdió el tren a Aguas Calientes. Llamé a la agencia, organicé un bus hasta Ollantaytambo y llegamos a tiempo para la visita. Los clientes nos dejaron una reseña excelente._",
          "Para las preguntas hipotéticas (_¿Qué haría usted ante un cliente enfadado?_) responde con **condicional**: _Primero lo escucharía con calma, después le ofrecería una solución…_",
          "Y para hablar del puesto que buscas, recupera las relativas de la semana pasada: _Busco un puesto en el que **pueda** crecer_ / _Su empresa es una agencia que **trabaja** con turismo sostenible, y eso me interesa mucho_. Con la opinión, recuerda: _Creo que **soy** la persona adecuada_, pero _No creo que **sea** un problema_.",
        ],
        table: {
          caption: "Preguntas típicas y cómo empezar la respuesta",
          head: ["Pregunta", "Empieza así"],
          rows: [
            ["Hábleme de usted.", "Soy… Estudié… Desde 2021 he trabajado en…"],
            ["¿Por qué quiere este puesto?", "Porque busco un trabajo en el que pueda… y su empresa…"],
            ["¿Cuál es su mayor fortaleza?", "Creo que mi punto fuerte es… Por ejemplo, una vez…"],
            ["¿Y su principal debilidad?", "Me cuesta… pero estoy trabajando en ello: ahora…"],
            ["¿Qué haría si un cliente se queja?", "Lo primero que haría sería…"],
            ["¿Tiene alguna pregunta?", "Sí, me gustaría saber… / ¿Podría decirme…?"],
          ],
        },
        examples: [
          { es: "He trabajado con grupos de hasta cuarenta personas y nunca he tenido un accidente." },
          { es: "Lo primero que haría sería tranquilizar al cliente y escuchar el problema." },
          { es: "No creo que el horario sea un problema: estoy acostumbrado a madrugar." },
        ],
        mistakes: [
          { wrong: "Trabajaba en un hotel de 2019 a 2022.", right: "Trabajé en un hotel de 2019 a 2022.", why: "Un periodo cerrado con fechas de principio y fin se cuenta con el **indefinido**." },
          { wrong: "No creo que soy la persona más experta.", right: "No creo que sea la persona más experta.", why: "_No creo que_ + **subjuntivo** (semana 6)." },
        ],
        tip: "Prepara antes de la entrevista tres historias cortas con situación, problema, acción y resultado. Sirven para casi cualquier pregunta.",
      },
    ],
  },
  grammar: {
    intro: "Primero las formas, después los usos: aconsejar, pedir y desear.",
    exercises: [
      {
        id: "g1",
        type: "gap",
        title: "Formas del condicional",
        prompt: "Completa con el condicional del verbo entre paréntesis.",
        items: [
          { q: "Yo que tú, ___ (salir) de casa una hora antes: el tráfico en la avenida Sol es terrible.", answers: [["saldría"]], why: "_Salir_ → **saldr-** (la vocal se cambia por _d_)." },
          { q: "¿___ (poder, usted) enviarme la oferta por correo?", answers: [["Podría"]], why: "_Poder_ → **podr-**: _podría_." },
          { q: "Nosotros no ___ (decir) nada malo de la empresa anterior.", answers: [["diríamos"]], why: "_Decir_ → **dir-**: _diríamos_." },
          { q: "Con ese sueldo, ¿tú ___ (venir) a vivir a Cusco?", answers: [["vendrías"]], why: "_Venir_ → **vendr-**: _vendrías_." },
          { q: "En tu lugar, yo ___ (hacer) un curso de primeros auxilios.", answers: [["haría"]], why: "_Hacer_ → **har-**: _haría_." },
          { q: "Mis padres ___ (querer) que trabaje cerca de casa, pero yo prefiero viajar.", answers: [["querrían"]], why: "_Querer_ → **querr-**, con doble _r_: _querrían_." },
        ],
      },
      {
        id: "g2",
        type: "classify",
        title: "¿Para qué usamos el condicional?",
        prompt: "Clasifica cada frase según la función del condicional.",
        categories: ["dar un consejo", "pedir con cortesía", "expresar un deseo"],
        items: [
          { text: "Yo en tu lugar, pediría una semana para pensarlo.", cat: 0, why: "_Yo en tu lugar_ + condicional = consejo." },
          { text: "¿Le importaría esperar un momento en la sala?", cat: 1, why: "_¿Le importaría…?_ es una petición muy cortés." },
          { text: "Me encantaría trabajar como guía en el Valle Sagrado.", cat: 2, why: "_Me encantaría_ + infinitivo = deseo." },
          { text: "Deberías llevar dos copias del currículum.", cat: 0, why: "_Deberías_ + infinitivo = consejo." },
          { text: "¿Podrías revisar mi carta antes de enviarla?", cat: 1, why: "_¿Podrías…?_ = petición amable." },
          { text: "¡Qué bien me vendría un trabajo con horario flexible!", cat: 2, why: "_¡Qué bien me vendría!_ = deseo." },
        ],
      },
      {
        id: "g3",
        type: "transform",
        title: "Otra forma de aconsejar",
        prompt: "Transforma el consejo con la fórmula indicada.",
        items: [
          { source: "Te recomiendo que llegues antes. (Yo que tú…)", answers: ["Yo que tú, llegaría antes.", "Yo que tú llegaría antes."], why: "_Yo que tú_ + condicional en **primera persona**: _llegaría_." },
          { source: "Es mejor que no hables de dinero en la primera entrevista. (Yo en tu lugar…)", answers: ["Yo en tu lugar, no hablaría de dinero en la primera entrevista.", "Yo en tu lugar no hablaría de dinero en la primera entrevista."], why: "La negación va delante del verbo: _no hablaría_." },
          { source: "Te aconsejo que pongas una foto profesional. (Deberías…)", answers: ["Deberías poner una foto profesional."], why: "_Deberías_ + **infinitivo**." },
          { source: "Te sugiero que tengas preparadas tres preguntas. (Tendrías que…)", answers: ["Tendrías que tener preparadas tres preguntas.", "Tendrías que preparar tres preguntas."], why: "_Tendrías que_ + infinitivo." },
        ],
      },
      {
        id: "g4",
        type: "context",
        title: "¿Qué dirías?",
        prompt: "Lee la situación y elige la frase más adecuada.",
        items: [
          { context: "Estás en una entrevista en Lima. No has entendido una pregunta.", q: "Le dices al entrevistador:", options: ["¿Podría repetir la pregunta, por favor?", "Repite la pregunta.", "¿Puedes a repetir la pregunta?"], answer: 0, why: "Usted + condicional de cortesía: la opción más adecuada en una entrevista." },
          { context: "Tu amigo tiene dos ofertas y te pide tu opinión. Tú prefieres la del hotel.", q: "Le dices:", options: ["Yo que tú, aceptaría la del hotel.", "Yo que tú, aceptarías la del hotel.", "Yo que tú, aceptaba la del hotel."], answer: 0, why: "_Yo que tú_ + condicional de **yo**: _aceptaría_." },
          { context: "Te preguntan en la entrevista qué te gustaría hacer en el futuro.", q: "Respondes:", options: ["Me gustaría coordinar un equipo de guías.", "Me gustarían coordinar un equipo de guías.", "Me gusto coordinar un equipo de guías."], answer: 0, why: "_Me gustaría_ + infinitivo, en singular." },
          { context: "Tienes una entrevista el lunes, pero ese día tienes un examen.", q: "Escribes a la empresa:", options: ["¿Sería posible cambiar la entrevista al martes?", "Cambien la entrevista al martes.", "¿Sería posible que cambian la entrevista al martes?"], answer: 0, why: "_¿Sería posible_ + infinitivo?: petición cortés y correcta." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Organiza el vocabulario en tres momentos: leer la oferta, hacer la entrevista y hablar del trabajo con amigos.",
    groups: [
      {
        title: "La oferta de empleo",
        items: [
          { es: "el puesto de guía bilingüe" },
          { es: "una vacante / un puesto vacante" },
          { es: "los requisitos: experiencia mínima de dos años" },
          { es: "jornada completa / media jornada", note: "En gran parte de América: _tiempo completo / medio tiempo_." },
          { es: "el sueldo / el salario bruto y neto", note: "_Bruto_: antes de impuestos; _neto_: lo que recibes." },
          { es: "un contrato indefinido / temporal", note: "En Perú también _contrato a plazo fijo_." },
          { es: "un horario flexible / turnos rotativos" },
          { es: "el trabajo remoto / el teletrabajo" },
          { es: "los beneficios", note: "En México: _las prestaciones_." },
          { es: "incorporarse de inmediato" },
        ],
      },
      {
        title: "La entrevista",
        items: [
          { es: "enviar el currículum (CV)", note: "En Colombia: _la hoja de vida_." },
          { es: "una carta de presentación" },
          { es: "el entrevistador / la entrevistadora" },
          { es: "mis fortalezas y mis debilidades / mis puntos fuertes y débiles" },
          { es: "trabajar en equipo" },
          { es: "resolver problemas bajo presión" },
          { es: "tener don de gentes", note: "Tener facilidad para tratar con las personas." },
          { es: "la atención al cliente" },
          { es: "estar disponible a partir de marzo" },
          { es: "la pretensión salarial", note: "El sueldo que esperas cobrar; muy usado en Perú y Chile." },
        ],
      },
      {
        title: "El trabajo en la calle",
        items: [
          { es: "la chamba / chambear", note: "Perú y México, coloquial." },
          { es: "el curro / currar", note: "España, coloquial." },
          { es: "el laburo / laburar", note: "Argentina y Uruguay, coloquial." },
          { es: "la pega", note: "Chile, coloquial." },
          { es: "estar en paro / estar desempleado", note: "_En paro_ en España; _desempleado_ o _sin chamba_ en América." },
          { es: "pedir un aumento" },
          { es: "renunciar / dimitir", note: "_Renunciar_ en América; _dimitir_ o _despedirse_ en España." },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "La misma palabra en cinco países",
        prompt: "Une cada palabra coloquial con el país o la zona donde se usa.",
        pairs: [
          { left: "chamba", right: "Perú y México" },
          { left: "curro", right: "España" },
          { left: "laburo", right: "Argentina y Uruguay" },
          { left: "pega", right: "Chile" },
          { left: "hoja de vida", right: "Colombia (currículum)" },
        ],
        why: "Todas significan «trabajo» (o currículum, en el caso de _hoja de vida_). En una entrevista formal usa siempre _trabajo_, _empleo_ o _puesto_.",
      },
      {
        id: "v2",
        type: "gap",
        title: "Una oferta en Cusco",
        prompt: "Completa la oferta con las palabras del banco. Sobran dos.",
        bank: ["puesto", "requisitos", "jornada", "sueldo", "indefinido", "incorporarse", "don de gentes", "prestaciones"],
        items: [
          { q: "Agencia de turismo busca cubrir el ___ de guía bilingüe para rutas en el Valle Sagrado.", answers: [["puesto"]], why: "_El puesto_ = el trabajo concreto que se ofrece." },
          { q: "___: inglés avanzado y experiencia mínima de dos años.", answers: [["Requisitos"]], why: "_Los requisitos_ = lo que la empresa exige." },
          { q: "Ofrecemos contrato ___ después de tres meses de prueba.", answers: [["indefinido"]], why: "_Indefinido_ = sin fecha de fin." },
          { q: "___ completa de lunes a sábado, con un día libre rotativo.", answers: [["Jornada"]], why: "_Jornada completa_ = tiempo completo." },
          { q: "Buscamos a alguien que tenga ___ y paciencia con los turistas.", answers: [["don de gentes"]], why: "_Tener don de gentes_ = facilidad para tratar con la gente." },
          { q: "Disponibilidad para ___ de inmediato.", answers: [["incorporarse"]], why: "_Incorporarse_ = empezar a trabajar." },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "Cortesía y modalidad: podía / podría y la petición amable",
    explanation: [
      "El condicional y el imperfecto de los verbos en _-er/-ir_ se parecen mucho: _podía_ / _podría_, _tenía_ / _tendría_, _hacía_ / _haría_, _quería_ / _querría_, _sabía_ / _sabría_. La sílaba fuerte es la misma (**-í-**), así que la diferencia está en la **consonante** antes de la í: en el condicional hay una **r** (y a veces una **d**: _ten**dr**ía_). Escúchala con atención: _po-**rí**-a_ frente a _po-**dí**-a_.",
      "_Quería_ y _querría_ se distinguen solo por la **r simple** frente a la **rr vibrante múltiple**: _que-**r**í-a_ / _que-**rr**í-a_. Muchos hablantes ni siquiera los distinguen en la práctica, y por eso en las peticiones se usa casi siempre _quería_.",
      "La cortesía no está solo en el verbo: también está en la **entonación**. Una petición con _¿Podría…?_ suena amable si la dices con una melodía suave, sin subir bruscamente al final, y con un _por favor_ en tono bajo. La misma frase con tono alto y cortante suena a orden o a impaciencia.",
      "Para suavizar todavía más, los hablantes alargan un poco el principio (_Perdone, eh…_) y bajan el volumen. En el español andino, y en Cusco en particular, el trato es especialmente cortés: oirás mucho _por favorcito_, _¿me podría hacer un favorcito?_ y diminutivos como _un momentito_.",
    ],
    table: {
      head: ["Imperfecto", "Condicional", "Diferencia"],
      rows: [
        ["podía", "podría", "d / r"],
        ["tenía", "tendría", "n / ndr"],
        ["hacía", "haría", "c (s / z) / r"],
        ["quería", "querría", "r simple / rr múltiple"],
        ["sabía", "sabría", "b / br"],
      ],
    },
    perceive: {
      id: "p1",
      type: "classify",
      title: "¿Imperfecto o condicional?",
      prompt: "Escucha cada frase. ¿El verbo está en imperfecto (_podía_) o en condicional (_podría_)?",
      categories: ["imperfecto (-ía sin r)", "condicional (-ría)"],
      items: [
        { text: "Frase 1", audio: "Tendría que hablar con mi jefa.", cat: 1, why: "_Tendría_: se oye **dr** antes de la í." },
        { text: "Frase 2", audio: "Tenía que hablar con mi jefa.", cat: 0, why: "_Tenía_: sin _r_, imperfecto." },
        { text: "Frase 3", audio: "Yo haría lo mismo que tú.", cat: 1, why: "_Haría_: _r_ simple antes de la í." },
        { text: "Frase 4", audio: "Mi padre hacía lo mismo cada mañana.", cat: 0, why: "_Hacía_: se oye la _c_ (como _s_ en América)." },
        { text: "Frase 5", audio: "¿Podría ayudarme con el formulario?", cat: 1, why: "_Podría_: petición en condicional." },
        { text: "Frase 6", audio: "De niño no podía dormir sin luz.", cat: 0, why: "_Podía_: hábito en el pasado, imperfecto." },
        { text: "Frase 7", audio: "No sabría qué responder.", cat: 1, why: "_Sabría_: **br** antes de la í." },
        { text: "Frase 8", audio: "No sabía qué responder.", cat: 0, why: "_Sabía_: solo _b_." },
      ],
    },
    produce: [
      { text: "¿Podría repetir la pregunta, por favor?", tip: "_Po-**drí**-a_: tres sílabas, la í bien marcada. Termina el _por favor_ en tono bajo y suave." },
      { text: "Tendría que consultarlo con mi familia.", tip: "Junta bien la **ndr**: _ten-drí-a_. No digas «tenería»." },
      { text: "Yo que tú, haría la entrevista en persona.", tip: "Pausa breve después de _yo que tú_. _Ha-**rí**-a_ con r simple." },
      { text: "Me encantaría trabajar con ustedes.", tip: "La sílaba fuerte es **rí**: _en-can-ta-**rí**-a_. Tono descendente y cálido." },
      { text: "Disculpe, ¿me podría hacer un favorcito?", tip: "Fórmula muy andina. Alarga un poco _Disculpe_ y baja el volumen en _un favorcito_." },
    ],
    spelling: "Todas las formas del condicional llevan tilde en la **í** (_sería, haríamos, podrían_) porque la _i_ tónica forma hiato con la vocal siguiente.",
  },
  listening: {
    title: "Entrevista en una agencia de Cusco",
    context: "La agencia Inti Rumi busca un guía bilingüe para rutas por el Valle Sagrado y Machu Picchu. Rosa, la responsable de personal, entrevista a Sofía, una candidata argentina que vive en Cusco desde hace tres años. Al final entra Ernesto, el gerente.",
    speakers: [
      { id: "rosa", name: "Rosa", voice: "es-PE-f", role: "responsable de personal" },
      { id: "sofia", name: "Sofía", voice: "es-AR-f", role: "candidata, guía argentina" },
      { id: "ernesto", name: "Ernesto", voice: "es-PE-m", role: "gerente de la agencia" },
    ],
    script: [
      { speaker: "rosa", text: "Buenos días, Sofía, tome asiento, por favor. ¿Le puedo ofrecer un mate de coca?" },
      { speaker: "sofia", text: "Sí, muchas gracias, me vendría muy bien. Todavía me cuesta un poco la altura por las mañanas." },
      { speaker: "rosa", text: "Bueno, empecemos. Hábleme un poco de usted y de su experiencia." },
      { speaker: "sofia", text: "Soy de Mendoza, estudié Turismo y llegué a Cusco hace tres años. Primero trabajé en la recepción de un hostal, y desde 2023 he trabajado como guía freelance, sobre todo con grupos de habla inglesa." },
      { speaker: "rosa", text: "¿Y por qué le interesa este puesto?" },
      { speaker: "sofia", text: "Porque busco una agencia en la que pueda tener un contrato estable y crecer. Además, ustedes trabajan con comunidades del Valle, y eso para mí es muy importante." },
      { speaker: "rosa", text: "Aquí dice que habla inglés y portugués. ¿Y quechua?" },
      { speaker: "sofia", text: "Estoy aprendiendo. No creo que pueda hacer una visita en quechua todavía, pero puedo saludar y presentarme. Me encantaría hacer el curso que ofrece la municipalidad." },
      { speaker: "rosa", text: "Muy bien. Una última pregunta: ¿cuál diría que es su principal debilidad?" },
      { speaker: "sofia", text: "Me cuesta decir que no. Antes aceptaba todos los grupos y terminaba agotada. Ahora organizo mejor mi calendario." },
      { speaker: "ernesto", text: "Perdón por interrumpir. Sofía, ¿no? Mucho gusto. Le hago una pregunta práctica: ¿qué haría usted con un turista que se siente mal por la altura en plena ruta?" },
      { speaker: "sofia", text: "Lo primero que haría sería sentarlo a la sombra y darle agua. Después le preguntaría por los síntomas y, si no mejora, llamaría a la agencia para bajarlo a Urubamba, que está más bajo. Nunca lo dejaría solo." },
      { speaker: "ernesto", text: "Muy bien. Rosa, ¿le podrías explicar las condiciones?" },
      { speaker: "rosa", text: "Claro. Es jornada completa, de martes a domingo, con contrato de seis meses y después indefinido. ¿Tendría alguna pregunta para nosotros?" },
      { speaker: "sofia", text: "Sí: me gustaría saber si sería posible empezar en marzo, porque en febrero tengo un grupo ya confirmado." },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: sigue la entrevista en general.",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha y responde.",
          items: [
            { q: "¿Para qué puesto es la entrevista?", options: ["Guía bilingüe en una agencia", "Recepcionista en un hostal", "Profesora de quechua"], answer: 0, why: "La agencia busca un guía bilingüe; Sofía trabajó en un hostal antes." },
            { q: "¿Cómo es, en general, la impresión que da Sofía?", options: ["Segura y bien preparada", "Nerviosa y sin experiencia", "Poco interesada en el puesto"], answer: 0, why: "Responde con ejemplos, explica su motivación y hace una pregunta al final." },
            { q: "¿Cómo termina la entrevista?", options: ["Sofía pregunta si puede empezar más tarde.", "Le ofrecen el puesto inmediatamente.", "Ernesto le dice que no tiene experiencia suficiente."], answer: 0, why: "_Me gustaría saber si sería posible empezar en marzo_." },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: atención a los datos y a los ejemplos.",
        exercise: {
          id: "l2",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "¿Qué hizo Sofía cuando llegó a Cusco?", options: ["Trabajó en la recepción de un hostal.", "Empezó como guía freelance.", "Estudió Turismo."], answer: 0, why: "_Primero trabajé en la recepción de un hostal_. Turismo lo estudió en Argentina." },
            { q: "¿Por qué le interesa la agencia Inti Rumi?", options: ["Por la estabilidad y su trabajo con comunidades", "Porque paga mejor que otras", "Porque está cerca de su casa"], answer: 0, why: "_Contrato estable y crecer… trabajan con comunidades del Valle_." },
            { q: "¿Qué nivel de quechua tiene?", options: ["Puede saludar y presentarse.", "Puede hacer visitas en quechua.", "No habla nada."], answer: 0, why: "_No creo que pueda hacer una visita en quechua todavía, pero puedo saludar y presentarme_." },
            { q: "¿Cuál es su debilidad?", options: ["Le cuesta decir que no.", "Le cuesta la altura.", "Es demasiado perfeccionista."], answer: 0, why: "_Me cuesta decir que no_. La altura le cuesta, pero no lo presenta como debilidad profesional." },
            { q: "¿Adónde llevaría a un turista que no mejora?", options: ["A Urubamba, porque está más bajo", "Al hospital de Cusco", "Al hotel, para descansar"], answer: 0, why: "_Llamaría a la agencia para bajarlo a Urubamba, que está más bajo_." },
            { q: "¿Qué condiciones ofrece la agencia?", options: ["Jornada completa y seis meses de contrato antes del indefinido", "Media jornada y contrato indefinido desde el principio", "Trabajo de lunes a viernes"], answer: 0, why: "_Jornada completa, de martes a domingo, con contrato de seis meses y después indefinido_." },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Tercera escucha: fíjate en para qué usa cada persona el condicional.",
        exercise: {
          id: "l3",
          type: "classify",
          prompt: "Clasifica cada frase de la entrevista.",
          categories: ["cortesía o petición", "deseo", "respuesta hipotética (qué haría)"],
          items: [
            { text: "Me vendría muy bien.", cat: 1, why: "Expresa lo que le apetece o le haría bien: un deseo." },
            { text: "¿Cuál diría que es su principal debilidad?", cat: 0, why: "Pregunta suavizada con condicional." },
            { text: "Me encantaría hacer el curso que ofrece la municipalidad.", cat: 1, why: "_Me encantaría_ + infinitivo." },
            { text: "Lo primero que haría sería sentarlo a la sombra.", cat: 2, why: "Responde a una situación imaginada: _¿qué haría usted…?_" },
            { text: "Nunca lo dejaría solo.", cat: 2, why: "Parte de la respuesta hipotética." },
            { text: "¿Le podrías explicar las condiciones?", cat: 0, why: "Ernesto pide algo a Rosa con cortesía (y de tú: son compañeros)." },
            { text: "Me gustaría saber si sería posible empezar en marzo.", cat: 0, why: "Petición cortés con doble condicional." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Yo que tú: cinco consejos antes de tu primera entrevista",
    genre: "Artículo de blog de orientación laboral",
    frame: "Mariela Huamán es psicóloga y selecciona personal para hoteles en Cusco y Lima. Escribe un blog para jóvenes que buscan su primer trabajo.",
    text: [
      "Cada semana entrevisto a unas veinte personas. Muchas tienen un buen currículum, pero pierden la oportunidad en los primeros cinco minutos. Si un amigo me pidiera consejo, esto es lo que le diría.",
      "**1. Investiga la empresa.** Yo que tú, pasaría al menos media hora leyendo su página web y sus reseñas. No hay nada peor que un candidato que no sabe qué hace la empresa en la que quiere trabajar. **2. Prepara historias, no adjetivos.** Todos dicen que son «responsables» y «proactivos». Yo en tu lugar, contaría una situación concreta en la que demostraste esas cualidades.",
      "**3. Cuidado con la debilidad.** No creo que exista una pregunta más temida. Deberías evitar respuestas como «soy demasiado perfeccionista»: los entrevistadores la escuchamos diez veces al día. Sería mucho mejor mencionar algo real que estás mejorando. **4. Habla de dinero, pero al final.** Es normal preguntar por el sueldo, pero yo esperaría a la segunda entrevista o a que el entrevistador saque el tema.",
      "**5. Haz preguntas.** Cuando te digan «¿Tiene alguna pregunta?», nunca respondas que no. Podrías preguntar cómo es un día normal en el puesto o qué es lo que más valoran en su equipo. Y un detalle final: en Perú, trata al entrevistador de usted hasta que él o ella te diga lo contrario. Me encantaría saber cómo te va: ¡cuéntamelo en los comentarios!",
    ],
    glossary: [
      { es: "temido/a", note: "Que provoca miedo o nervios." },
      { es: "sacar el tema", note: "Empezar a hablar de algo." },
      { es: "proactivo/a", note: "Que toma la iniciativa sin esperar instrucciones." },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        prompt: "Lee el artículo y responde.",
        items: [
          { q: "¿Cuál es el problema que ve Mariela en muchos candidatos?", options: ["Tienen un buen currículum pero fallan al principio de la entrevista.", "No tienen experiencia ni estudios.", "Llegan tarde a la entrevista."], answer: 0, why: "_Pierden la oportunidad en los primeros cinco minutos_." },
          { q: "Según Mariela, ¿cómo deberías demostrar que eres responsable?", options: ["Contando una situación concreta", "Repitiendo el adjetivo varias veces", "Llevando cartas de recomendación"], answer: 0, why: "_Prepara historias, no adjetivos… contaría una situación concreta_." },
          { q: "¿Qué opina de hablar del sueldo?", options: ["Es normal, pero mejor al final o en la segunda entrevista.", "Nunca se debe preguntar por el sueldo.", "Hay que preguntarlo al principio."], answer: 0, why: "_Es normal preguntar por el sueldo, pero yo esperaría a la segunda entrevista_." },
          { q: "¿Qué hay que responder a «¿Tiene alguna pregunta?»?", options: ["Siempre hacer alguna pregunta", "Decir que no, para no molestar", "Preguntar por las vacaciones"], answer: 0, why: "_Nunca respondas que no_." },
        ],
      },
      {
        id: "r2",
        type: "classify",
        prompt: "¿Mariela recomienda o desaconseja cada acción?",
        categories: ["lo recomienda", "lo desaconseja"],
        items: [
          { text: "leer las reseñas de la empresa", cat: 0, why: "_Pasaría al menos media hora leyendo su página web y sus reseñas_." },
          { text: "decir que tu debilidad es el perfeccionismo", cat: 1, why: "_Deberías evitar respuestas como «soy demasiado perfeccionista»_." },
          { text: "describirte con adjetivos como «proactivo»", cat: 1, why: "_Prepara historias, no adjetivos_." },
          { text: "preguntar cómo es un día normal en el puesto", cat: 0, why: "_Podrías preguntar cómo es un día normal_." },
          { text: "tutear al entrevistador desde el principio en Perú", cat: 1, why: "_Trata al entrevistador de usted hasta que él o ella te diga lo contrario_." },
          { text: "mencionar algo real que estás mejorando", cat: 0, why: "_Sería mucho mejor mencionar algo real que estás mejorando_." },
        ],
      },
    ],
    noticing: {
      prompt: "Observa cómo Mariela da consejos y cómo combina el condicional con lo que ya sabes.",
      items: [
        { quote: "Yo que tú, pasaría al menos media hora", note: "_Yo que tú_ + condicional en primera persona." },
        { quote: "Deberías evitar respuestas como…", note: "_Deberías_ + infinitivo: consejo directo a _tú_." },
        { quote: "Sería mucho mejor mencionar algo real", note: "Consejo impersonal: _sería mejor_ + infinitivo." },
        { quote: "un candidato que no sabe qué hace la empresa en la que quiere trabajar", note: "Repaso: relativa en indicativo (el candidato existe) y relativo con preposición: _en la que_." },
        { quote: "No creo que exista una pregunta más temida.", note: "Repaso: _no creo que_ + subjuntivo." },
        { quote: "Me encantaría saber cómo te va", note: "Condicional de deseo, muy útil para cerrar un texto con cercanía." },
      ],
    },
  },
  practice: {
    intro: "Combina el condicional con las relativas de la semana pasada y con la opinión de la semana 6.",
    exercises: [
      {
        id: "x1",
        type: "transform",
        title: "Suaviza la petición",
        prompt: "Transforma la orden en una petición cortés con la fórmula indicada (trato de usted).",
        items: [
          { source: "Mándeme el contrato hoy. (¿Podría…?)", answers: ["¿Podría mandarme el contrato hoy?", "¿Me podría mandar el contrato hoy?"], why: "_¿Podría_ + infinitivo? El pronombre puede ir pegado al infinitivo o delante de _podría_." },
          { source: "Espere un momento. (¿Le importaría…?)", answers: ["¿Le importaría esperar un momento?"], why: "_¿Le importaría_ + infinitivo? = muy cortés." },
          { source: "Quiero saber el horario de trabajo. (Me gustaría…)", answers: ["Me gustaría saber el horario de trabajo.", "Me gustaría saber cuál es el horario de trabajo."], why: "_Me gustaría_ + infinitivo para pedir información." },
          { source: "Cambie la cita al jueves. (¿Sería posible…?)", answers: ["¿Sería posible cambiar la cita al jueves?"], why: "_¿Sería posible_ + infinitivo?" },
        ],
      },
      {
        id: "x2",
        type: "gap",
        title: "Busco un trabajo que…",
        prompt: "Completa con el verbo en indicativo, subjuntivo o condicional según el sentido.",
        items: [
          { q: "Me encantaría encontrar un trabajo en el que ___ (poder) usar mis idiomas.", answers: [["pueda"]], why: "Trabajo deseado, aún no existe: relativa en **subjuntivo**." },
          { q: "Ahora trabajo en un hotel que ___ (estar) en la plaza de Armas.", answers: [["está"]], why: "Hotel concreto y real: **indicativo**." },
          { q: "Yo en tu lugar, ___ (buscar) una empresa que ofrezca formación.", answers: [["buscaría"]], why: "_Yo en tu lugar_ + **condicional**." },
          { q: "No creo que el sueldo ___ (ser) lo más importante.", answers: [["sea"]], why: "_No creo que_ + **subjuntivo**." },
          { q: "Creo que mi experiencia ___ (ser) suficiente para este puesto.", answers: [["es"]], why: "_Creo que_ + **indicativo**." },
        ],
      },
      {
        id: "x3",
        type: "error",
        title: "Errores de entrevista",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "Yo que tú, pedirías más información sobre el contrato.", answers: ["Yo que tú, pediría más información sobre el contrato.", "Yo que tú pediría más información sobre el contrato."], why: "_Yo que tú_ + condicional de **yo**: _pediría_." },
          { sentence: "Me gustarían trabajar en una empresa internacional.", answers: ["Me gustaría trabajar en una empresa internacional."], why: "_Gustar_ + infinitivo: siempre **singular**." },
          { sentence: "¿Podría decirme cuándo sabería algo? Tenería que avisar en mi trabajo actual.", answers: ["¿Podría decirme cuándo sabría algo? Tendría que avisar en mi trabajo actual."], why: "Dos irregulares: _saber_ → **sabría**, _tener_ → **tendría**." },
          { sentence: "Busco un puesto donde puedo aprender cosas nuevas.", answers: ["Busco un puesto donde pueda aprender cosas nuevas.", "Busco un puesto en el que pueda aprender cosas nuevas."], why: "Puesto buscado → relativa en **subjuntivo**: _pueda_." },
        ],
      },
      {
        id: "x4",
        type: "match",
        title: "Pregunta y buena respuesta",
        prompt: "Une cada pregunta de entrevista con la respuesta más adecuada.",
        pairs: [
          { left: "¿Por qué quiere trabajar con nosotros?", right: "Porque busco una empresa que apueste por el turismo responsable, como ustedes." },
          { left: "¿Cuál es su punto fuerte?", right: "Creo que es la calma: una vez se canceló un tren y reorganicé todo el grupo en una hora." },
          { left: "¿Qué haría si un compañero no hace su parte?", right: "Hablaría con él en privado antes de ir a la jefa." },
          { left: "¿Cuál es su pretensión salarial?", right: "Me gustaría estar en la banda de lo que se paga en el sector, entre 2500 y 3000 soles." },
          { left: "¿Tiene alguna pregunta?", right: "Sí, ¿podría contarme cómo es un día normal en este puesto?" },
        ],
        why: "Las buenas respuestas son concretas, usan ejemplos (pasado), condicional para lo hipotético y cortesía para preguntar.",
      },
      {
        id: "x5",
        type: "open",
        title: "Escritura guiada: consejos y respuestas",
        prompt: "Escribe 2–4 frases para cada situación.",
        items: [
          {
            prompt: "Tu amiga Valentina tiene mañana su primera entrevista como recepcionista y está muy nerviosa. Escríbele un mensaje con tres consejos con fórmulas distintas.",
            model: "¡Vale, vas a hacerlo genial! Yo que tú, prepararía dos ejemplos de cuando ayudaste a clientes en la tienda. Deberías llegar un poco antes para tranquilizarte. Y sería buena idea llevar una pregunta preparada para el final. ¡Mucha suerte!",
            checklist: ["Usas _yo que tú_ o _yo en tu lugar_ + condicional en primera persona.", "Usas _deberías / podrías / tendrías que_ + infinitivo.", "Los consejos son concretos, no generales."],
          },
          {
            prompt: "Responde por escrito a la pregunta «¿Por qué quiere este puesto?» para una oferta de trabajo que te interese de verdad.",
            model: "Porque busco un puesto en el que pueda combinar mis idiomas con el trato con la gente. He trabajado dos años en atención al cliente y creo que es lo que mejor se me da. Además, su empresa es una de las pocas que trabajan con turismo sostenible, y me encantaría formar parte de ese proyecto.",
            checklist: ["Usas una relativa en subjuntivo para lo que buscas.", "Mencionas tu experiencia con un tiempo del pasado.", "Terminas con un deseo en condicional (_me encantaría / me gustaría_)."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Escribe un correo de presentación para responder a una oferta de trabajo.",
    context: "Has visto esta oferta: «Hotel boutique en Cusco busca recepcionista con idiomas, don de gentes y disponibilidad para turnos rotativos. Envíe su CV y carta de presentación.» (Puedes adaptar el puesto a tu profesión real.)",
    steps: [
      "Saluda con una fórmula formal y di a qué oferta respondes.",
      "Preséntate y resume tu experiencia con tiempos del pasado.",
      "Explica por qué te interesa el puesto: lo que buscas (relativa en subjuntivo) y lo que te gusta de la empresa (indicativo).",
      "Da un ejemplo breve de una de tus fortalezas.",
      "Pide algo con cortesía (una entrevista, información, una fecha) y despídete.",
    ],
    useLanguage: [
      "Estimado/a señor/a… / Estimado equipo de…",
      "Me dirijo a ustedes en relación con la oferta de…",
      "He trabajado… / Trabajé… en…",
      "Busco un puesto en el que pueda…",
      "Me encantaría / Me gustaría…",
      "¿Sería posible…? / Quedaría a su disposición para…",
      "Atentamente / Un cordial saludo",
    ],
    model: [
      "Estimado equipo del Hotel Casa Andina:",
      "Me dirijo a ustedes en relación con la oferta de recepcionista publicada en su página web. Me llamo Daniel Ortega, soy mexicano y vivo en Cusco desde hace dos años. Trabajé tres años en la recepción de un hostal en Oaxaca y, desde 2024, he trabajado en una agencia de viajes de la avenida Sol, donde atiendo a clientes en español, inglés y francés.",
      "Busco un puesto en el que pueda tener un trato más cercano con los huéspedes, y su hotel, que es conocido por su atención personalizada, es exactamente el tipo de lugar en el que me gustaría trabajar. Creo que mi punto fuerte es la calma: el año pasado una tormenta canceló todos los vuelos y reorganicé las reservas de un grupo de treinta personas en una tarde.",
      "Me encantaría tener la oportunidad de conocerlos en persona. ¿Sería posible concertar una entrevista la próxima semana? Adjunto mi currículum.",
      "Un cordial saludo,",
      "Daniel Ortega",
    ],
    checklist: [
      "Usas fórmulas formales de saludo y despedida y tratas a la empresa de usted / ustedes.",
      "Cuentas tu experiencia con indefinido y perfecto.",
      "Incluyes al menos una relativa en subjuntivo y una en indicativo.",
      "Usas el condicional al menos tres veces (deseo, petición, hipótesis).",
      "Das un ejemplo concreto, no solo adjetivos.",
    ],
    words: [120, 170],
  },
  speaking: {
    intro: "Esta semana la producción oral es una entrevista simulada. Prepara tus historias, lee las preguntas y responde sin leer.",
    tasks: [
      {
        title: "Entrevista simulada: cinco preguntas",
        prompt: "Responde a estas cinco preguntas para un puesto que te interese (dale unos 25 segundos a cada una): 1) Hábleme de usted. 2) ¿Por qué quiere este puesto? 3) Cuénteme una situación difícil que resolvió. 4) ¿Qué haría si un cliente se queja de algo que no es culpa suya? 5) ¿Tiene alguna pregunta?",
        prep: [
          "1) Soy… Estudié… Desde… he trabajado…",
          "2) Busco un puesto en el que pueda… Su empresa…",
          "3) Una vez… El problema era que… Lo que hice fue… Al final…",
          "4) Lo primero que haría sería… Después…",
          "5) Me gustaría saber… / ¿Podría contarme…?",
        ],
        seconds: 150,
        model: "Soy Laura, soy enfermera y desde 2020 he trabajado en un hospital de Quito. Quiero este puesto porque busco un trabajo en el que pueda combinar la medicina con el turismo, y su clínica atiende a muchos viajeros. Una vez llegó a urgencias un turista que no hablaba español; no había nadie que hablara inglés, así que hice de intérprete y lo atendimos a tiempo. Si un cliente se quejara… perdón: ante un cliente que se queja, lo primero que haría sería escucharlo con calma; después le explicaría qué podemos hacer. Y me gustaría saber: ¿cómo son los turnos en temporada alta?",
        selfCheck: ["Cuento mi experiencia con indefinido y perfecto.", "Doy un ejemplo con situación, problema, acción y resultado.", "Respondo a la pregunta hipotética con condicional.", "Hago una pregunta cortés al final."],
      },
      {
        title: "Yo que tú…",
        prompt: "Tu amigo Gonzalo tiene dos ofertas: una en Lima, bien pagada pero con mucho estrés, y otra en Cusco, con menos sueldo pero con horario flexible. Dale tu consejo y justifícalo.",
        prep: ["Yo que tú, aceptaría…", "Creo que… / No creo que…", "Deberías pensar en…", "Lo mejor sería…", "Al final, lo que importa es…"],
        seconds: 45,
        model: "Gonzalo, yo que tú, aceptaría la de Cusco. No creo que el dinero lo sea todo, y tú siempre dices que necesitas tiempo para tus proyectos. Deberías pensar en cómo quieres vivir dentro de cinco años. Eso sí, yo en tu lugar pediría un pequeño aumento antes de firmar. Lo que importa es que estés tranquilo.",
        selfCheck: ["Uso _yo que tú_ y otra fórmula de consejo.", "Uso _creo que_ + indicativo o _no creo que_ + subjuntivo.", "Justifico el consejo."],
      },
      {
        title: "Una llamada cortés",
        prompt: "Llamas a la agencia Inti Rumi: tienes la entrevista el lunes, pero estás enfermo. Pide cambiar la fecha y pregunta si puedes llevar algún documento.",
        prep: ["Buenos días, disculpe…", "Quería pedirle un favor…", "¿Sería posible…?", "¿Le importaría…?", "Me gustaría saber si…"],
        seconds: 30,
        model: "Buenos días, disculpe, soy Martín Rivas, tengo una entrevista el lunes a las diez. Quería pedirle un favor: estoy enfermo y no voy a poder ir. ¿Sería posible cambiarla al miércoles o al jueves? Y me gustaría saber si tendría que llevar algún documento original. Muchas gracias, y disculpe las molestias.",
        selfCheck: ["Trato a mi interlocutor de usted.", "Uso al menos dos fórmulas de cortesía distintas.", "Mi entonación es suave, sin subir bruscamente."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo, pide a tu profesor o profesora que haga de entrevistador o entrevistadora.",
    cards: [
      { move: "Responde", task: "Haz la entrevista simulada en vivo: tu profesor o profesora te hace las cinco preguntas (y alguna sorpresa). Responde con ejemplos concretos.", phrases: ["Una vez, en mi trabajo anterior…", "Lo primero que haría sería…", "Creo que mi punto fuerte es…"] },
      { move: "Aconseja", task: "Tu profesor o profesora te cuenta un dilema de trabajo (real o inventado). Dale dos consejos con fórmulas distintas.", phrases: ["Yo que tú…", "Yo en tu lugar…", "Deberías…", "Lo mejor sería…"] },
      { move: "Pide", task: "Pide tres cosas con distintos grados de cortesía y pregunta cuál suena mejor en su país.", phrases: ["¿Podrías…?", "¿Te importaría…?", "¿Sería posible…?"] },
      { move: "Compara", task: "Compara cómo son las entrevistas de trabajo en tu país y en el de tu profesor o profesora: tú o usted, sueldo, ropa, preguntas.", phrases: ["En mi país lo normal es…", "Aquí nunca preguntarían…", "¿Y en tu país se habla de usted?"] },
    ],
    bring: "Una oferta de empleo real (en español si puedes) que te interese: la usaréis para la entrevista simulada.",
  },
  quiz: {
    items: [
      { type: "choice", q: "Con más tiempo libre, yo ___ un curso de quechua en Cusco.", options: ["haría", "hacería", "hacía"], answer: 0, why: "_Hacer_ → raíz **har-**: _haría_." },
      { type: "choice", q: "Elige la petición más cortés para una entrevista:", options: ["¿Le importaría explicarme cómo funciona el periodo de prueba?", "Explíqueme cómo funciona el periodo de prueba.", "Quiero que me explique cómo funciona el periodo de prueba."], answer: 0, why: "_¿Le importaría_ + infinitivo? es la fórmula más suave." },
      { type: "listen", q: "¿Qué hace la persona del audio: aconseja, pide o desea?", audio: "Yo en tu lugar, no firmaría ese contrato sin leerlo dos veces.", voice: "es-MX-m", options: ["Aconseja", "Pide un favor", "Expresa un deseo propio"], answer: 0, why: "_Yo en tu lugar_ + condicional = consejo." },
      { type: "listen", q: "¿En qué tiempo está el verbo que escuchas en esta frase sobre el turno de noche?", audio: "Tendría que trabajar en el turno de noche.", voice: "es-PE-f", options: ["Condicional (tendría)", "Imperfecto (tenía)", "Futuro (tendré)"], answer: 0, why: "Se oye **dr** + **ía**: _tendría_." },
      { type: "gap", q: "¿___ (saber, usted) decirme dónde queda la oficina de recursos humanos?", answers: [["Sabría"]], why: "_Saber_ → **sabr-**: _sabría_, condicional de cortesía." },
      { type: "gap", q: "Mis compañeros ___ (poner) la reunión el viernes, pero la jefa prefiere el lunes.", answers: [["pondrían"]], why: "_Poner_ → **pondr-**: _pondrían_." },
      { type: "transform", source: "Te aconsejo que no menciones tu sueldo actual.", instruction: "Reescribe el consejo con _Yo que tú_.", answers: ["Yo que tú, no mencionaría tu sueldo actual.", "Yo que tú no mencionaría tu sueldo actual.", "Yo que tú, no mencionaría mi sueldo actual.", "Yo que tú no mencionaría mi sueldo actual."], why: "_Yo que tú_ + condicional de primera persona: _no mencionaría_." },
      { type: "transform", source: "Necesito un trabajo. Quiero un horario flexible en ese trabajo.", instruction: "Une en una frase: _Necesito un trabajo que…_", answers: ["Necesito un trabajo que tenga un horario flexible.", "Necesito un trabajo que tenga horario flexible."], why: "Trabajo buscado → relativa en **subjuntivo**: _tenga_." },
      { type: "order", words: ["¿Sería", "posible", "hacer", "la", "entrevista", "por", "videollamada?"], why: "_¿Sería posible_ + infinitivo?: petición cortés." },
      { type: "error", sentence: "Yo en tu lugar, aceptarías la oferta de Arequipa.", answers: ["Yo en tu lugar, aceptaría la oferta de Arequipa.", "Yo en tu lugar aceptaría la oferta de Arequipa."], why: "Con _yo en tu lugar_ el verbo va en **primera persona**." },
      { type: "error", sentence: "No creo que tengo la experiencia que piden.", answers: ["No creo que tenga la experiencia que piden."], why: "_No creo que_ + **subjuntivo**: _tenga_." },
      { type: "error", sentence: "¿Podrías a mandarme tu hoja de vida?", answers: ["¿Podrías mandarme tu hoja de vida?", "¿Me podrías mandar tu hoja de vida?"], why: "_Poder_ + infinitivo, sin preposición." },
      { type: "open", prompt: "En una entrevista te preguntan: «¿Qué haría usted si tuviera que trabajar con un compañero muy desorganizado?». Responde en 2–3 frases.", model: "Primero hablaría con él para entender cómo organiza su trabajo. Después propondría una lista de tareas compartida para que los dos sepamos qué falta. Y si el problema siguiera, se lo comentaría a la jefa.", checklist: ["Usas el condicional al menos dos veces.", "Ordenas la respuesta (primero, después…).", "La respuesta es concreta y profesional."] },
    ],
  },
  complete: {
    canNow: [
      "Formar el condicional regular e irregular (_tendría, podría, haría, diría, sabría_).",
      "Aconsejar con _yo que tú_, _yo en tu lugar_, _deberías_ y _sería mejor_.",
      "Pedir con cortesía y expresar deseos con _¿podría…?_, _¿le importaría…?_ y _me encantaría…_.",
      "Distinguir al oído _podía_ / _podría_ y suavizar una petición con la entonación.",
      "Presentar mi experiencia y responder preguntas de entrevista con ejemplos concretos.",
    ],
    review: [
      "Irregulares del condicional = irregulares del futuro.",
      "_Yo que tú_ + condicional en primera persona.",
      "Busco un trabajo que + subjuntivo; trabajo en una empresa que + indicativo.",
      "_Creo que_ + indicativo / _no creo que_ + subjuntivo.",
    ],
  },
  related: [
    { path: "/sistema-verbal/condicional-simple-indicativo", label: "Sistema verbal · Condicional simple" },
    { path: "/la-entrevista-que-no-salio-al-aire", label: "La entrevista que no salió al aire" },
  ],
};
