import type { Module } from "../../types";

export const b1w12: Module = {
  id: "b1-12",
  level: "b1",
  week: 12,
  kind: "core",
  title: "Cuando llegue a Puno",
  subtitle: "Haz planes que dependen del tiempo con cuando, en cuanto, hasta que y antes de que + subjuntivo, y habla de tus metas y plazos.",
  stop: { place: "Lago Titicaca, Puno", country: "Perú" },
  minutes: 85,
  newObjectives: [
    "b1.gram.temporales-subjuntivo",
    "b1.voc.proyectos-metas",
    "b1.pron.enlaces-rapidos",
    "b1.fun.planificar-condiciones",
    "b1.lis.mensaje-planes",
  ],
  reviewObjectives: ["b1.gram.probabilidad", "b1.fun.suponer", "b1.gram.condicional-simple"],
  prerequisites: ["b1-11"],
  goal: {
    canDo: "Al final de esta semana puedes explicar planes y metas que dependen de que algo pase (cuando termine, en cuanto tenga, hasta que encuentre, antes de que empiece), distinguir lo habitual de lo futuro y reconstruir un plan encadenado a partir de un mensaje de voz.",
    canDoEn: "By the end of this week, you can explain plans and goals that depend on something happening first, tell habitual 'when' from future 'when', and follow a chain of plans in a voice message.",
    steps: [
      "Descubre por qué decimos **cuando llego** (siempre) pero **cuando llegue** (mañana).",
      "Amplía el sistema: **en cuanto**, **hasta que**, **antes de que**, **mientras** y **después de que**.",
      "Aprende a hablar de metas, plazos y proyectos: **fijarse una meta**, **a medio plazo**, **sacar adelante**.",
      "Entrena los enlaces rápidos de **voy a ir** y **lo he hecho**.",
      "Escucha los audios de un grupo de amigos que organiza un viaje al lago Titicaca y lee el blog de una emprendedora de Llachón.",
      "Escribe y graba tus propios planes con condiciones de tiempo.",
    ],
  },
  theory: {
    intro: "En A2 aprendiste a decir **cuando llego a casa, ceno**: una costumbre. Esta semana miras hacia delante: **cuando llegue a Puno, te llamo**. La diferencia es una sola letra, pero cambia la perspectiva: hablas de algo que todavía no ha pasado. Por eso el español usa el **subjuntivo**, el modo de lo que no es (todavía) un hecho.",
    parts: [
      {
        heading: "Cuando + indicativo o cuando + subjuntivo",
        body: [
          "**Cuando** sitúa una acción en el tiempo. Si hablas de una **costumbre** o de algo **general**, usas indicativo: **Cuando llego a un pueblo nuevo, busco el mercado.** Si hablas del **pasado**, también indicativo: **Cuando llegué a Puno, me dolía la cabeza por la altura.** En los dos casos describes hechos reales, comprobados.",
          "Si el momento está en el **futuro**, todavía no es un hecho: es un momento que esperas. Entonces usas **presente de subjuntivo**: **Cuando llegue a Puno, compraré mate de coca para el soroche.** La parte principal de la frase va en futuro, en _ir a_ + infinitivo, en presente con valor de futuro o en imperativo: **Cuando llegues, llámame.**",
          "La regla de oro: después de **cuando** temporal **nunca** va el futuro. _Cuando llegaré_ no existe en español. Pero cuidado con las **preguntas**: **¿cuándo?** (con tilde) pregunta por un dato, así que lleva indicativo: **¿Cuándo vas a llegar? —Cuando termine el trabajo.**",
        ],
        support: [
          "English uses the present after 'when' for the future (_when I arrive_). Spanish uses the present subjunctive (_cuando llegue_), never the future (_cuando llegaré_ ✗). _Cuando llego_ means 'whenever I arrive', as a habit.",
        ],
        table: {
          caption: "Cuatro usos de «cuando»",
          head: ["Hablas de…", "Forma", "Ejemplo"],
          rows: [
            ["una costumbre o algo general", "cuando + presente de indicativo", "Cuando hace sol, se ve la isla de Taquile desde el puerto."],
            ["el pasado", "cuando + pasado de indicativo", "Cuando llegamos al muelle, el barco ya había salido."],
            ["el futuro", "cuando + presente de subjuntivo", "Cuando haga sol, iremos a Taquile."],
            ["una pregunta", "¿cuándo? + indicativo", "¿Cuándo sale el próximo barco?"],
          ],
        },
        examples: [
          { es: "Cuando mis abuelos vienen a Puno, siempre comemos trucha frita.", note: "Costumbre: indicativo." },
          { es: "Cuando vinieron el año pasado, hacía un frío terrible.", note: "Pasado: indicativo." },
          { es: "Cuando vengan en julio, los llevaremos a los Uros.", note: "Futuro: subjuntivo." },
          { es: "—¿Cuándo vas a abrir la tienda? —Cuando tenga los permisos.", note: "Pregunta con indicativo; respuesta con subjuntivo." },
        ],
        mistakes: [
          { wrong: "Cuando llegaré a Puno, te llamaré.", right: "Cuando llegue a Puno, te llamaré.", why: "Después de **cuando** temporal nunca va el futuro. Para el futuro: **presente de subjuntivo**." },
          { wrong: "Cuando tengo tiempo el año que viene, voy a estudiar quechua.", right: "Cuando tenga tiempo el año que viene, voy a estudiar quechua.", why: "_El año que viene_ es futuro: **cuando tenga**. _Cuando tengo tiempo_ sería una costumbre." },
          { wrong: "¿Cuándo llegues?", right: "¿Cuándo llegas? / ¿Cuándo vas a llegar?", why: "En la pregunta directa **¿cuándo?** va con indicativo: preguntas por un dato." },
        ],
        tip: "Hazte una pregunta antes de conjugar: ¿es una costumbre o algo que ya pasó? → indicativo. ¿Todavía está por pasar? → subjuntivo.",
      },
      {
        heading: "En cuanto, hasta que, antes de que, después de que, mientras",
        body: [
          "Los demás conectores de tiempo funcionan igual que **cuando**: indicativo para costumbres y pasado, subjuntivo para el futuro. **En cuanto** significa «justo después»: **En cuanto tenga señal, te escribo.** En Perú y en Argentina también oirás **ni bien**, y en muchos países **apenas**: **Apenas llegues, avísame.** **Hasta que** marca el límite: **No salimos hasta que pare el viento.** **Mientras** marca dos acciones al mismo tiempo: **Mientras estés en el lago, ponte protector solar.**",
          "**Antes de que** es especial: lleva **siempre** subjuntivo, porque la acción todavía no ha ocurrido en el momento del que hablas: **Vamos al muelle antes de que salga el último barco.** **Después de que** sigue la regla general: **Después de que se van los turistas, la isla está tranquila** (costumbre) / **Después de que se vayan, cerraremos** (futuro).",
          "Si las dos partes de la frase tienen **el mismo sujeto**, lo normal es preposición + **infinitivo**, como ya sabes de A2: **Antes de salir, revisa el pronóstico.** **Después de comer, damos una vuelta.** **No paro hasta terminar.** Con sujetos distintos, necesitas **que** + subjuntivo: **Antes de que salgas, te doy el mapa.** En el habla oirás a veces **hasta que no** con el mismo significado: **No me voy hasta que no me paguen.** Ese _no_ no niega nada; es enfático y muy frecuente.",
        ],
        table: {
          caption: "Conectores de tiempo para hablar del futuro",
          head: ["Conector", "Idea", "Ejemplo"],
          rows: [
            ["cuando + subjuntivo", "en el momento en que", "Cuando termine el curso, buscaré trabajo."],
            ["en cuanto / apenas / ni bien + subjuntivo", "justo después", "En cuanto sepa algo, te aviso."],
            ["hasta que + subjuntivo", "el límite final", "Te espero hasta que salgas."],
            ["mientras + subjuntivo", "al mismo tiempo, durante", "Mientras vivas aquí, no pagas luz."],
            ["después de que + subjuntivo", "más tarde", "Después de que se vayan, limpiamos."],
            ["antes de que + subjuntivo (siempre)", "antes", "Llama antes de que cierren."],
            ["antes de / después de / hasta + infinitivo", "mismo sujeto", "Antes de salir, cierro la ventana."],
          ],
        },
        examples: [
          { es: "En cuanto amanezca, salimos hacia los Uros." },
          { es: "No compro el pasaje hasta que me confirmen las vacaciones." },
          { es: "Antes de que oscurezca, quiero ver el atardecer en Sillustani." },
          { es: "Antes de subir al barco, compra agua: en el lago no venden nada." },
        ],
        mistakes: [
          { wrong: "Antes de que salir, desayunamos.", right: "Antes de salir, desayunamos.", why: "Con infinitivo no hay **que**: _antes de_ + infinitivo, _antes de que_ + subjuntivo." },
          { wrong: "Te espero hasta que llegas.", right: "Te espero hasta que llegues.", why: "Hablas del futuro: **hasta que** + subjuntivo." },
          { wrong: "Antes de que yo salga, cierro la ventana.", right: "Antes de salir, cierro la ventana.", why: "El sujeto es el mismo (yo salgo, yo cierro): lo natural es **antes de + infinitivo**." },
          { wrong: "Siempre te llamo antes de que llego.", right: "Siempre te llamo antes de llegar.", why: "**Antes de que** nunca lleva indicativo; además aquí el sujeto es el mismo, así que mejor infinitivo." },
        ],
        tip: "Truco para **antes de que**: no lo pienses. Siempre subjuntivo, en todos los tiempos.",
      },
      {
        heading: "Planificar con condiciones de tiempo",
        body: [
          "Un plan real casi nunca es una sola frase: es una **cadena**. Primero pasa una cosa y, cuando pasa, empieza la siguiente: **En cuanto termine el curso, haré la web. Cuando la web esté lista, empezaremos a recibir reservas directas. Y hasta que no tengamos el 70 % ahorrado, no construimos nada.** Fíjate en el ritmo: condición de tiempo + acción, condición de tiempo + acción.",
          "Los planes también tienen incertidumbre. Para eso usas lo que aprendiste en la semana 10: el **futuro de probabilidad** y **a lo mejor / quizás / tal vez**. **Cuando llegues, ya estará oscuro** (supongo). **A lo mejor** termino antes. **Quizás** tengamos que esperar. Y si alguien te pide opinión sobre su plan, el **condicional** de la semana 9: **Yo que tú, esperaría hasta que bajen los precios.** **Yo no compraría nada antes de que confirmen la fecha.**",
          "No confundas **si** y **cuando**. **Si** + presente de **indicativo** presenta una condición que puede pasar o no: **Si llueve, nos quedamos.** **Cuando** + subjuntivo da por hecho que va a pasar; solo no sabes cuándo: **Cuando llueva, nos quedaremos.** Y nunca pongas subjuntivo presente después de **si**: _si llueva_ no existe.",
        ],
        table: {
          caption: "Las piezas de un plan",
          head: ["Pieza", "Recursos", "Ejemplo"],
          rows: [
            ["condición de tiempo", "cuando, en cuanto, hasta que, antes de que + subjuntivo", "En cuanto tenga el certificado…"],
            ["acción", "futuro, ir a + infinitivo, presente, imperativo", "…voy a trabajar como guía."],
            ["incertidumbre", "futuro de probabilidad, a lo mejor, quizás, tal vez", "Será en marzo, más o menos."],
            ["consejo sobre el plan", "yo que tú / yo en tu lugar + condicional", "Yo que tú, no dejaría el trabajo todavía."],
          ],
        },
        examples: [
          { es: "Cuando junte suficiente plata, me compraré un kayak; a lo mejor será de segunda mano." },
          { es: "Si el lago está tranquilo, seguimos hasta Taquile; si no, volvemos a Puno." },
          { es: "Yo en tu lugar, no renunciaría hasta que te ofrezcan algo por escrito." },
        ],
        mistakes: [
          { wrong: "Si tenga tiempo, iré a Taquile.", right: "Si tengo tiempo, iré a Taquile.", why: "Después de **si** condicional va indicativo, nunca presente de subjuntivo." },
          { wrong: "Yo que tú, espero hasta que baje el precio.", right: "Yo que tú, esperaría hasta que baje el precio.", why: "**Yo que tú** pide **condicional**: es un consejo, no una costumbre." },
          { wrong: "A lo mejor llegue tarde.", right: "A lo mejor llego tarde.", why: "**A lo mejor** va con indicativo. Con _quizás_ o _tal vez_ puedes usar los dos modos." },
        ],
        tip: "Cuando expliques un plan en voz alta, numera los pasos con **primero**, **en cuanto…**, **y cuando…**: quien te escucha sigue la cadena sin perderse.",
      },
    ],
  },
  grammar: {
    intro: "Primero decide entre indicativo y subjuntivo; después conjuga y construye frases con los conectores.",
    exercises: [
      {
        id: "g1",
        type: "choice",
        title: "¿Costumbre, pasado o futuro?",
        prompt: "Elige la forma correcta según el tiempo del que se habla.",
        items: [
          { q: "Cuando ___ a Puno la semana que viene, te mando fotos del lago.", options: ["llego", "llegue", "llegaré"], answer: 1, why: "_La semana que viene_ = futuro: **cuando llegue**. _Cuando llegaré_ no existe." },
          { q: "Todos los años, cuando ___ la fiesta de la Candelaria, la ciudad se llena de bailarines.", options: ["llega", "llegue", "llegará"], answer: 0, why: "_Todos los años_ = costumbre: **cuando llega**, indicativo." },
          { q: "La primera vez que ___ a 3800 metros, me faltaba el aire.", options: ["subí", "suba", "subiré"], answer: 0, why: "Hablas del pasado: indicativo, **subí**." },
          { q: "¿Cuándo ___ el próximo barco a las islas de los Uros?", options: ["sale", "salga", "saldría"], answer: 0, why: "Es una **pregunta directa** con _¿cuándo?_: indicativo." },
          { q: "No pienso comprar el pasaje hasta que me ___ las vacaciones.", options: ["confirman", "confirmen", "confirmarán"], answer: 1, why: "Futuro todavía no ocurrido: **hasta que** + subjuntivo, **confirmen**." },
          { q: "En el altiplano, en cuanto ___ el sol, empieza a hacer muchísimo frío.", options: ["se pone", "se ponga", "se pondrá"], answer: 0, why: "Es algo general que pasa cada día: indicativo, **se pone**." },
        ],
      },
      {
        id: "g2",
        type: "gap",
        title: "Conjuga en su sitio",
        prompt: "Completa con el verbo entre paréntesis en indicativo o subjuntivo.",
        items: [
          { q: "Te llamo en cuanto ___ de la reunión. (salir, yo)", answers: [["salga"]], why: "Futuro: **en cuanto** + subjuntivo. _Salir_ → _salgo_ → **salga**." },
          { q: "Antes de que ___ la temporada de lluvias, quiero visitar Sillustani. (empezar)", answers: [["empiece"]], why: "**Antes de que** + subjuntivo siempre. Ojo con la ortografía: _empiece_, con **c**." },
          { q: "Mientras ___ en el barco, no te quites el gorro: aquí el sol quema. (estar, tú)", answers: [["estés"]], why: "Futuro (un consejo para el viaje): **mientras** + subjuntivo, **estés** con tilde." },
          { q: "No vamos a abrir el hostal hasta que ___ todos los permisos. (tener, nosotros)", answers: [["tengamos"]], why: "**Hasta que** + subjuntivo para el futuro. _Tengo_ → **tengamos**." },
          { q: "—¿Y tú qué quieres hacer cuando ___ mayor? —Capitán de barco. (ser, tú)", answers: [["seas"]], why: "El niño todavía no es mayor: futuro, **cuando seas**." },
          { q: "Después de que se ___ los turistas, cada tarde, la isla vuelve a estar tranquila. (ir)", answers: [["van"]], why: "_Cada tarde_ = costumbre: indicativo, **se van**. No todo lo que va después de un conector es subjuntivo." },
        ],
      },
      {
        id: "g3",
        type: "transform",
        title: "Une las dos acciones",
        prompt: "Une las dos frases con el conector indicado. Decide si necesitas infinitivo o que + subjuntivo.",
        items: [
          { source: "Voy a terminar la tesis. Después voy a viajar por el sur del Perú.", instruction: "Usa «cuando».", answers: ["Cuando termine la tesis, voy a viajar por el sur del Perú.", "Voy a viajar por el sur del Perú cuando termine la tesis."], why: "La tesis no está terminada: **cuando termine**." },
          { source: "Voy a comprar agua. Después subo al mirador.", instruction: "Usa «antes de».", answers: ["Antes de subir al mirador, voy a comprar agua.", "Voy a comprar agua antes de subir al mirador."], why: "Mismo sujeto (yo): **antes de + infinitivo**, sin _que_." },
          { source: "El guía va a llegar. Justo después, salimos.", instruction: "Usa «en cuanto».", answers: ["En cuanto llegue el guía, salimos.", "Salimos en cuanto llegue el guía.", "En cuanto el guía llegue, salimos.", "Salimos en cuanto el guía llegue."], why: "Futuro inmediato: **en cuanto** + subjuntivo, **llegue**." },
          { source: "Te voy a esperar. Vas a terminar de comer.", instruction: "Usa «hasta que».", answers: ["Te voy a esperar hasta que termines de comer.", "Voy a esperarte hasta que termines de comer.", "Te espero hasta que termines de comer."], why: "Sujetos distintos (yo espero, tú terminas): **hasta que termines**." },
          { source: "Mis padres van a venir. Antes, quiero limpiar la casa.", instruction: "Usa «antes de que».", answers: ["Quiero limpiar la casa antes de que vengan mis padres.", "Antes de que vengan mis padres, quiero limpiar la casa.", "Quiero limpiar la casa antes de que mis padres vengan.", "Antes de que mis padres vengan, quiero limpiar la casa."], why: "Sujetos distintos: **antes de que** + subjuntivo, **vengan**." },
        ],
      },
      {
        id: "g4",
        type: "classify",
        title: "¿Qué tiempo es?",
        prompt: "Clasifica cada frase según el tiempo real del que habla.",
        categories: ["costumbre (indicativo)", "pasado (indicativo)", "futuro (subjuntivo)"],
        items: [
          { text: "Cuando hay viento, el barco tarda más.", cat: 0, why: "Algo que pasa siempre que hay viento." },
          { text: "Cuando termine la temporada, descansaré un mes.", cat: 2, why: "_Termine_: la temporada todavía no ha terminado." },
          { text: "En cuanto vi el lago, entendí por qué es sagrado.", cat: 1, why: "_Vi_: pretérito, un hecho pasado." },
          { text: "Mientras estés aquí, puedes usar mi bicicleta.", cat: 2, why: "_Estés_: subjuntivo, el tiempo de la visita está por llegar." },
          { text: "Siempre espero hasta que se duermen los niños para trabajar.", cat: 0, why: "_Siempre_ + indicativo: rutina." },
          { text: "Antes de que se vayan, sácales una foto.", cat: 2, why: "**Antes de que** + subjuntivo, con una instrucción para el futuro." },
          { text: "Cuando vivía en Juliaca, trabajaba en un banco.", cat: 1, why: "Imperfecto: una etapa del pasado." },
        ],
      },
    ],
  },
  vocabulary: {
    intro: "Para hablar de planes de verdad necesitas el vocabulario de las metas: cómo se fijan, cuánto tardan, qué obstáculos aparecen y cómo se celebran. Apréndelo en bloques, con su verbo.",
    groups: [
      {
        title: "Metas y plazos",
        items: [
          { es: "fijarse una meta / ponerse un objetivo", note: "Este año me he fijado una meta: correr diez kilómetros." },
          { es: "alcanzar una meta / cumplir un objetivo", note: "Alcanzamos la meta antes de lo previsto." },
          { es: "a corto, medio y largo plazo", note: "A largo plazo, quiero vivir cerca del lago." },
          { es: "el plazo / dentro del plazo / se acaba el plazo", note: "El plazo para pedir la beca se acaba el viernes." },
          { es: "dar el primer paso", note: "Lo más difícil es dar el primer paso." },
          { es: "ponerse manos a la obra", note: "Ya basta de hablar: manos a la obra." },
        ],
      },
      {
        title: "Proyectos y recursos",
        items: [
          { es: "emprender / un emprendimiento", note: "_Emprendimiento_ es muy común en América; en España se dice más _un negocio propio_ o _una empresa_." },
          { es: "poner un negocio (montar un negocio en España)" },
          { es: "sacar adelante un proyecto", note: "Sacamos adelante el hostal entre toda la familia." },
          { es: "ahorrar para algo / juntar plata (en América)", note: "Estoy juntando plata para un kayak." },
          { es: "pedir un préstamo / devolver un préstamo" },
          { es: "conseguir una beca / un certificado" },
          { es: "hacer un curso / sacarse un título" },
        ],
      },
      {
        title: "Logros y obstáculos",
        items: [
          { es: "lograr + infinitivo / un logro", note: "Por fin logré hablar con el banco." },
          { es: "salir bien / salir mal", note: "El primer año todo salió mal; el segundo, salió bien." },
          { es: "dejar algo para después / postergar (aplazar en España)" },
          { es: "echarse atrás", note: "Tenía miedo, pero no me eché atrás." },
          { es: "tirar la toalla", note: "No tires la toalla: es solo el primer año." },
          { es: "valer la pena", note: "Fue duro, pero valió la pena." },
          { es: "ir paso a paso / poco a poco" },
        ],
      },
    ],
    exercises: [
      {
        id: "v1",
        type: "match",
        title: "Colocaciones de metas",
        prompt: "Une cada verbo con la palabra que lo acompaña.",
        pairs: [
          { left: "fijarse", right: "una meta" },
          { left: "sacar adelante", right: "un proyecto" },
          { left: "pedir", right: "un préstamo" },
          { left: "tirar", right: "la toalla" },
          { left: "dar", right: "el primer paso" },
          { left: "ponerse manos", right: "a la obra" },
        ],
        why: "Estas combinaciones son fijas: _tirar la toalla_ (rendirse), _dar el primer paso_ (empezar). Si cambias el verbo, la expresión deja de sonar natural.",
      },
      {
        id: "v2",
        type: "gap",
        title: "Planes en Puno",
        prompt: "Completa con las expresiones del banco.",
        bank: ["a largo plazo", "se acaba el plazo", "juntando plata", "valió la pena", "me eché atrás", "conseguir una beca"],
        items: [
          { q: "Estoy ___ para comprar una lancha propia y llevar turistas a Taquile.", answers: [["juntando plata"]], why: "**Juntar plata** (América) = ahorrar dinero poco a poco." },
          { q: "Tengo que mandar los papeles hoy porque mañana ___.", answers: [["se acaba el plazo"]], why: "**Se acaba el plazo** = termina el tiempo para hacer algo." },
          { q: "___, me gustaría tener mi propia agencia; de momento trabajo como guía.", answers: [["A largo plazo"], ], why: "**A largo plazo** = dentro de muchos años." },
          { q: "Estuve a punto de cancelar el viaje, pero no ___.", answers: [["me eché atrás"]], why: "**Echarse atrás** = cambiar de idea por miedo o dudas." },
          { q: "Subir hasta el mirador fue agotador, pero la vista ___.", answers: [["valió la pena"]], why: "**Valer la pena** = el esfuerzo tiene un buen resultado." },
          { q: "Si quiero estudiar turismo en Arequipa, primero tengo que ___.", answers: [["conseguir una beca"]], why: "**Conseguir una beca** = obtener ayuda económica para estudiar." },
        ],
      },
      {
        id: "v3",
        type: "classify",
        title: "¿Avanzas o te frenas?",
        prompt: "Clasifica cada frase: ¿la persona avanza hacia su meta o se frena?",
        categories: ["avanza", "se frena"],
        items: [
          { text: "Por fin me he puesto manos a la obra.", cat: 0 },
          { text: "Siempre lo dejo para después.", cat: 1, why: "_Dejar para después_ = postergar." },
          { text: "He logrado ahorrar la mitad.", cat: 0 },
          { text: "Al final tiré la toalla.", cat: 1, why: "_Tirar la toalla_ = rendirse." },
          { text: "Voy paso a paso, pero no paro.", cat: 0 },
          { text: "En el último momento me eché atrás.", cat: 1 },
        ],
      },
    ],
  },
  pronunciation: {
    focus: "Enlaces vocálicos rápidos: voy a ir, lo he hecho, va a haber",
    explanation: [
      "En español hablado las palabras no se separan: la vocal final de una palabra se une a la vocal inicial de la siguiente. Ya lo practicaste en A2 con los tiempos compuestos. A velocidad natural, el enlace va más lejos: **dos vocales iguales se funden en una** algo más larga, y la **h** no suena nunca. Así, **va a hacer** suena casi como _vaacer_, y **lo he hecho**, como _loecho_.",
      "Cuando una palabra termina en **y** (_voy_, _hay_, _muy_) y la siguiente empieza por vocal, la **y** se une como consonante a esa vocal: **voy a ir** suena _bo-ya-ir_, **hay agua** suena _a-ya-gua_. Por eso, en un mensaje de voz rápido, **voy a ir a Puno** puede sonar como una sola palabra larga.",
      "Esto explica muchos errores de escritura, incluso de nativos: _va hacer_ en vez de **va a hacer**, _lo echo_ en vez de **lo he hecho**. La **a** de _ir a_ y el **he** de _he hecho_ casi no se oyen, pero están, y cambian el significado. En el español andino de Puno, Cusco o La Paz el ritmo suele ser más pausado y las consonantes muy claras, así que los enlaces son más suaves; en Lima, en el Caribe, en Madrid o en Buenos Aires son más rápidos. Entiende los dos, y usa el ritmo que te salga natural.",
    ],
    table: {
      caption: "Se escribe así, suena así",
      head: ["Se escribe", "Suena aproximadamente", "Qué pasa"],
      rows: [
        ["va a hacer", "va-a-cer → vaacer", "a + a se funden; la h no suena"],
        ["lo he hecho", "lo-e-e-cho → loecho", "e + e se funden"],
        ["voy a ir", "bo-ya-ir", "la y se une a la vocal siguiente"],
        ["me he enterado", "meenterado", "tres e casi en una"],
        ["te espero en la entrada", "tes-pe-roen-laen-tra-da", "cada vocal final se une a la siguiente"],
      ],
    },
    perceive: {
      id: "p1",
      type: "listen",
      title: "¿Qué dijo de verdad?",
      prompt: "Escucha cada frase a velocidad natural y elige lo que la persona dijo realmente. La vocal escondida está, aunque casi no se oiga.",
      items: [
        { q: "¿Qué dijo?", audio: "Mañana va a hacer mucho frío en el lago.", voice: "es-PE-f", options: ["Mañana va a hacer mucho frío en el lago.", "Mañana va hacer mucho frío en el lago.", "Mañana hace mucho frío en el lago."], answer: 0, why: "**Va a hacer**: _ir a_ + infinitivo. La _a_ se funde con la _a_ de _hacer_ (la h no suena)." },
        { q: "¿Qué dijo?", audio: "Ya lo he hecho, no te preocupes.", voice: "es-MX-m", options: ["Ya lo hecho, no te preocupes.", "Ya lo he hecho, no te preocupes.", "Ya lo echo, no te preocupes."], answer: 1, why: "**Lo he hecho**: el _he_ se funde con _hecho_. Sin _he_, la frase no tiene verbo conjugado." },
        { q: "¿Qué dijo?", audio: "Voy a ir a Taquile en cuanto pueda.", voice: "es-AR-f", options: ["Voy a Taquile en cuanto pueda.", "Voy ir a Taquile en cuanto pueda.", "Voy a ir a Taquile en cuanto pueda."], answer: 2, why: "Se oye _bo-ya-ir-a_: hay un _ir_ entre las dos _a_. _Voy ir_ no es posible en español." },
        { q: "¿Qué dijo?", audio: "Te he esperado más de una hora.", voice: "es-ES-m", options: ["Te he esperado más de una hora.", "Te esperado más de una hora.", "Te espero más de una hora."], answer: 0, why: "_Te he_ suena casi _te_: pero **he esperado** necesita el auxiliar." },
        { q: "¿Qué dijo?", audio: "Va a haber mucha gente en la fiesta.", voice: "es-CO-f", options: ["Va haber mucha gente en la fiesta.", "Va a ver mucha gente en la fiesta.", "Va a haber mucha gente en la fiesta."], answer: 2, why: "**Va a haber** = habrá. _Haber_ y _a ver_ suenan igual, pero aquí se habla de la cantidad de gente." },
        { q: "¿Qué dijo?", audio: "Me va a esperar en el muelle.", voice: "es-CL-m", options: ["Me va a esperar en el muelle.", "Me va esperar en el muelle.", "Me espera en el muelle."], answer: 0, why: "**Va a esperar**: las dos _a_ se unen en una, pero la preposición está." },
      ],
    },
    produce: [
      { text: "Voy a ir a Puno en cuanto pueda.", tip: "Une _voy a ir a_ en un solo bloque: _bo-ya-i-ra_. No hagas pausas entre las palabras." },
      { text: "Ya lo he hecho, te lo he dicho mil veces.", tip: "Funde las e: _loe-cho_, _teloe-dicho_. La h no suena." },
      { text: "Mañana va a haber mucha gente en el muelle.", voice: "es-PE-f", tip: "Primero escucha el modelo peruano, más pausado; después repítelo un poco más rápido sin perder la _a_." },
      { text: "Te espero en la entrada hasta que llegues.", tip: "Enlaza _te-es_, _roen_, _laen_ y _que-lle_: toda la frase en un solo soplo." },
      { text: "Cuando llegue a Arequipa, te aviso.", tip: "_Llegue a_ suena _lle-gea_: une la e y la a, y mantén el acento en _lle-GUE_, no en la última sílaba." },
    ],
    spelling: "Aunque no se oigan, se escriben: la **a** de _ir a_ (**va a hacer**, **voy a ir**) y el **he** de los tiempos compuestos (**lo he hecho**). Y recuerda: **haber** (verbo) no es **a ver** (vamos a mirar).",
  },
  listening: {
    title: "Audios de un plan · grupo «Titicaca 3»",
    context: "Rocío, una limeña que ya está en Puno, organiza por mensajes de voz la llegada de sus amigos: Diego, un mexicano que viene en bus desde Cusco, y Facundo, un argentino que sale de Arequipa. Escucha los audios del grupo.",
    speakers: [
      { id: "rocio", name: "Rocío", voice: "es-PE-f", role: "organiza el viaje, ya está en Puno" },
      { id: "diego", name: "Diego", voice: "es-MX-m", role: "viene en bus desde Cusco" },
      { id: "facundo", name: "Facundo", voice: "es-AR-m", role: "sale de Arequipa" },
    ],
    script: [
      { speaker: "rocio", text: "¡Hola, chicos! Les dejo un audio porque escribir todo esto es eterno. Ya estoy en Puno, en el hostal Totora, al lado del puerto. Les cuento el plan, ¿ya?" },
      { speaker: "rocio", text: "Diego, tu bus llega de Cusco como a las cinco, ¿no? Ni bien bajes del bus, mándame un mensaje. Después tomas un taxi y le dices al chofer: «hostal Totora, por el puerto». No te debería cobrar más de ocho soles." },
      { speaker: "rocio", text: "Facundo, tú tranquilo: te esperamos para cenar hasta que llegues. Bueno, hasta las diez, ¿eh? A las diez la cocina del hostal cierra." },
      { speaker: "rocio", text: "Y mañana, en cuanto amanezca, vamos al muelle. El barco a los Uros sale a las siete, y antes de que salga hay que comprar los boletos en la caseta. Después, si el lago está tranquilo, seguimos hasta Taquile y dormimos allá, en casa de una familia." },
      { speaker: "diego", text: "¡Qué buena onda, Rocío! Oye, una cosa: mi bus va a llegar más tarde, como a las siete, porque dicen que hay un bloqueo en la carretera. Ahorita no sé si será verdad o si será un retraso normal. En cuanto sepa algo más, te aviso." },
      { speaker: "diego", text: "Y otra cosa: yo que tú, no compraría todavía los boletos para Taquile. Hasta que no veamos cómo está el tiempo, mejor no pagamos nada, ¿no crees?" },
      { speaker: "facundo", text: "Che, perdón, recién escucho los audios. Yo salgo de Arequipa a las tres, así que llegaré a eso de las nueve y media. Si llego después de las diez, no me esperen, eh, como algo en la terminal." },
      { speaker: "facundo", text: "Ah, y una idea: cuando volvamos de Taquile, ¿por qué no vamos a Sillustani antes de que se haga de noche? Dicen que el atardecer allá es tremendo." },
      { speaker: "rocio", text: "Me encanta. Entonces, resumo: Diego, me escribes cuando sepas la hora exacta. Facundo, te guardamos la cena hasta las diez. Lo de Taquile lo decidimos mañana en el muelle, cuando veamos el lago. Y lo de Sillustani, al volver." },
      { speaker: "rocio", text: "¡Y abríguense, que acá de noche hace un frío que no se imaginan!" },
    ],
    stages: [
      {
        stage: "gist",
        prompt: "Primera escucha: ¿de qué tratan los audios y qué queda sin decidir?",
        exercise: {
          id: "l1",
          type: "choice",
          prompt: "Escucha una vez, sin pausas, y responde.",
          items: [
            { q: "¿Para qué manda Rocío sus audios?", options: ["Para organizar la llegada y el día siguiente.", "Para cancelar el viaje por el mal tiempo.", "Para recomendar un hostal a sus amigos."], answer: 0, why: "Explica cómo llegar al hostal y qué harán mañana: _Les cuento el plan_." },
            { q: "¿Quién tiene un problema con el horario?", options: ["Facundo, porque pierde el bus.", "Diego, porque su bus va a llegar tarde.", "Rocío, porque el hostal cierra."], answer: 1, why: "Diego: _mi bus va a llegar más tarde, como a las siete_." },
            { q: "¿Qué deciden dejar para mañana?", options: ["si van a los Uros", "si van a Taquile", "dónde cenan"], answer: 1, why: "_Lo de Taquile lo decidimos mañana en el muelle, cuando veamos el lago._" },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Segunda escucha: reconstruye las dos secuencias en orden.",
        exercise: {
          id: "l2",
          type: "order",
          prompt: "Ordena los pasos tal como los plantea Rocío.",
          items: [
            { words: ["Diego baja del bus.", "Le manda un mensaje a Rocío.", "Toma un taxi.", "Le dice al chofer el nombre del hostal."], en: "Diego's arrival", why: "_Ni bien bajes del bus, mándame un mensaje. Después tomas un taxi y le dices al chofer…_" },
            { words: ["Amanece.", "Van al muelle.", "Compran los boletos.", "Sale el barco a los Uros.", "Siguen hasta Taquile si el lago está tranquilo."], en: "Tomorrow's plan", why: "_En cuanto amanezca, vamos al muelle… antes de que salga hay que comprar los boletos… si el lago está tranquilo, seguimos hasta Taquile._" },
          ],
        },
      },
      {
        stage: "detail",
        prompt: "Tercera escucha: los datos concretos.",
        exercise: {
          id: "l3",
          type: "choice",
          prompt: "Elige la respuesta correcta.",
          items: [
            { q: "¿Cuánto debería costar el taxi?", options: ["como mucho ocho soles", "dieciocho soles", "ocho dólares"], answer: 0, why: "_No te debería cobrar más de ocho soles._" },
            { q: "¿Está seguro Diego de que hay un bloqueo?", options: ["Sí, lo ha visto en las noticias.", "No, solo lo dicen; puede ser un retraso normal.", "Sí, porque el chofer se lo ha confirmado."], answer: 1, why: "_Dicen que hay un bloqueo… no sé si será verdad o si será un retraso normal._ Futuro de probabilidad: no está seguro." },
            { q: "¿Qué aconseja Diego?", options: ["comprar ya los boletos para Taquile", "no comprar los boletos para Taquile hasta ver el tiempo", "ir a Taquile en bus"], answer: 1, why: "_Yo que tú, no compraría todavía los boletos… Hasta que no veamos cómo está el tiempo…_" },
            { q: "¿Qué hará Facundo si llega después de las diez?", options: ["Llamará a Rocío.", "Comerá algo en la terminal.", "Dormirá en Juliaca."], answer: 1, why: "_Si llego después de las diez, no me esperen, eh, como algo en la terminal._" },
            { q: "¿Qué propone Facundo para la vuelta de Taquile?", options: ["ir a Sillustani antes de que se haga de noche", "volver directamente a Arequipa", "cenar en el hostal"], answer: 0, why: "_¿Por qué no vamos a Sillustani antes de que se haga de noche?_" },
          ],
        },
      },
      {
        stage: "notice",
        prompt: "Cuarta escucha: fíjate en cómo hablan del futuro, de lo que no saben y de lo que aconsejan.",
        exercise: {
          id: "l4",
          type: "classify",
          prompt: "Clasifica cada fragmento de los audios.",
          categories: ["conector de tiempo + subjuntivo", "hipótesis (no está seguro)", "consejo con condicional"],
          items: [
            { text: "Ni bien bajes del bus", cat: 0, why: "**Ni bien** = en cuanto (Perú, Argentina): **bajes**, subjuntivo." },
            { text: "te esperamos para cenar hasta que llegues", cat: 0, why: "**Hasta que** + subjuntivo." },
            { text: "antes de que salga hay que comprar los boletos", cat: 0, why: "**Antes de que** + subjuntivo siempre." },
            { text: "no sé si será verdad", cat: 1, why: "Futuro de probabilidad: _será_ = supongo que es / puede ser." },
            { text: "yo que tú, no compraría todavía los boletos", cat: 2, why: "**Yo que tú** + condicional: consejo." },
            { text: "cuando volvamos de Taquile", cat: 0, why: "Futuro: **cuando volvamos**." },
            { text: "si será un retraso normal", cat: 1, why: "Otra hipótesis con futuro de probabilidad." },
          ],
        },
      },
    ],
  },
  reading: {
    title: "Cuatro metas y un plazo",
    genre: "Entrada de blog personal",
    frame: "Yaneth Quispe tiene una casa de turismo vivencial en Llachón, en la península de Capachica, a orillas del lago Titicaca. En su blog «Del lago al mundo» comparte sus planes para los próximos dos años.",
    text: [
      "Hace tres años, cuando abrimos la casa, solo teníamos dos habitaciones y una página de Facebook que casi nadie veía. Hoy recibimos visitantes de todo el mundo, y este año hemos cumplido una meta que parecía imposible: mi hermano Wilber ha conseguido el certificado de guía oficial. Por eso me he sentado a escribir nuestras metas a medio plazo. Escribirlas aquí, en público, es mi manera de no echarme atrás.",
      "**Meta 1: una web propia.** Ahora dependemos de las plataformas de reservas, que se quedan con una comisión del 15 %. En cuanto termine el curso de diseño web que estoy haciendo por las noches, haré nuestra página con reservas directas. Calculo que estará lista antes de que empiece la temporada alta, en junio.",
      "**Meta 2: dos habitaciones más.** Aquí vamos más despacio. No vamos a construir hasta que tengamos ahorrado el 70 % del dinero. Mi primo, que es contador, me dijo: «Yo que tú, no pediría un préstamo grande; los intereses se comerían las ganancias». Tiene razón, así que juntamos plata poco a poco.",
      "**Meta 3: kayaks para los huéspedes.** Muchos visitantes nos preguntan si pueden remar en el lago. Cuando Wilber saque el certificado de primeros auxilios, compraremos tres kayaks de segunda mano. A lo mejor los encontramos en Puno; si no, tendremos que traerlos de Arequipa, y eso costará bastante más.",
      "**Meta 4, la más personal: aprender inglés en serio.** Siempre lo dejo para después. Esta vez me he puesto un plazo: cuando lleguen los primeros visitantes de junio, quiero explicarles la historia de la península sin el traductor del celular. ¿Lo lograré? No lo sé, pero vale la pena intentarlo.",
      "¿Y ustedes? ¿Qué meta tienen a medio plazo y qué tiene que pasar antes de que den el primer paso? Los leo en los comentarios.",
    ],
    glossary: [
      { es: "el turismo vivencial", note: "Turismo en el que el visitante vive con una familia local y participa en su vida diaria." },
      { es: "el contador / la contadora", note: "En España, _el contable_." },
      { es: "remar", note: "Mover un kayak o una barca con los remos." },
      { es: "de segunda mano", note: "Usado, que ya tuvo otro dueño." },
    ],
    tasks: [
      {
        id: "r1",
        type: "choice",
        title: "Comprensión global y detalle",
        prompt: "Responde según el texto.",
        items: [
          { q: "¿Por qué escribe Yaneth sus metas en el blog?", options: ["Para no echarse atrás.", "Para pedir dinero a los lectores.", "Para hacer publicidad de las plataformas."], answer: 0, why: "_Escribirlas aquí, en público, es mi manera de no echarme atrás._" },
          { q: "¿Qué tiene que pasar antes de hacer la web?", options: ["Que empiece la temporada alta.", "Que Yaneth termine un curso de diseño.", "Que Wilber saque un certificado."], answer: 1, why: "_En cuanto termine el curso de diseño web… haré nuestra página._" },
          { q: "¿Qué piensa el primo de Yaneth sobre el préstamo?", options: ["Que es la mejor opción.", "Que es mejor no pedir uno grande.", "Que es imposible conseguirlo."], answer: 1, why: "_Yo que tú, no pediría un préstamo grande._" },
          { q: "¿Está segura Yaneth de dónde comprará los kayaks?", options: ["Sí, en Puno.", "Sí, en Arequipa.", "No: quizás en Puno, si no, en Arequipa."], answer: 2, why: "_A lo mejor los encontramos en Puno; si no, tendremos que traerlos de Arequipa._" },
        ],
      },
      {
        id: "r2",
        type: "classify",
        title: "¿Logro o plan?",
        prompt: "Clasifica cada elemento: ¿ya lo han conseguido o es un plan para el futuro?",
        categories: ["logro ya conseguido", "plan para el futuro"],
        items: [
          { text: "el certificado de guía oficial de Wilber", cat: 0, why: "_Mi hermano Wilber ha conseguido el certificado._" },
          { text: "recibir visitantes de todo el mundo", cat: 0, why: "_Hoy recibimos visitantes de todo el mundo._" },
          { text: "una web con reservas directas", cat: 1, why: "_Haré nuestra página_: futuro." },
          { text: "dos habitaciones más", cat: 1, why: "_No vamos a construir hasta que…_" },
          { text: "el certificado de primeros auxilios de Wilber", cat: 1, why: "_Cuando Wilber saque el certificado_: todavía no lo tiene." },
          { text: "explicar la historia de la península en inglés", cat: 1, why: "_Quiero explicarles…_ y no sabe si lo logrará." },
        ],
      },
      {
        id: "r3",
        type: "match",
        title: "Condición y plan",
        prompt: "Une cada condición de tiempo con el plan que depende de ella.",
        pairs: [
          { left: "en cuanto termine el curso de diseño", right: "hará la web de la casa" },
          { left: "hasta que tengan el 70 % ahorrado", right: "no van a construir" },
          { left: "cuando Wilber saque el certificado de primeros auxilios", right: "comprarán tres kayaks" },
          { left: "cuando lleguen los visitantes de junio", right: "quiere hablarles en inglés sin traductor" },
        ],
        why: "Cada meta de Yaneth depende de un momento futuro: por eso todas las condiciones van en subjuntivo (_termine_, _tengan_, _saque_, _lleguen_).",
      },
    ],
    noticing: {
      prompt: "Toca cada fragmento y observa cómo Yaneth combina pasado, futuro, condiciones e hipótesis.",
      items: [
        { quote: "cuando abrimos la casa, solo teníamos dos habitaciones", note: "**Cuando** + indefinido: un hecho pasado. Compara con _cuando lleguen los visitantes_ (futuro)." },
        { quote: "Calculo que estará lista antes de que empiece la temporada alta", note: "**Estará**: futuro con un toque de cálculo o previsión. **Antes de que** + subjuntivo, siempre." },
        { quote: "No vamos a construir hasta que tengamos ahorrado el 70 %", note: "**Hasta que** + subjuntivo marca el límite: hasta ese momento, nada." },
        { quote: "Yo que tú, no pediría un préstamo grande", note: "Repaso de la semana 9: consejo con **yo que tú** + condicional." },
        { quote: "A lo mejor los encontramos en Puno", note: "Repaso de la semana 10: **a lo mejor** + indicativo para una posibilidad." },
        { quote: "antes de que den el primer paso", note: "**Den** es el subjuntivo de _dar_ (sin tilde; _dé_ lleva tilde solo en la forma de yo/él/usted)." },
      ],
    },
  },
  practice: {
    intro: "Mezcla los conectores de tiempo con lo que ya sabes: hipótesis con futuro y a lo mejor (semana 10) y consejos con condicional (semana 9).",
    exercises: [
      {
        id: "x1",
        type: "error",
        title: "Corrige el plan",
        prompt: "Cada frase tiene un error. Escríbela bien.",
        items: [
          { sentence: "Cuando terminaré la carrera, me iré a vivir a Lima.", answers: ["Cuando termine la carrera, me iré a vivir a Lima."], why: "Nunca futuro después de **cuando**: **termine**." },
          { sentence: "Te aviso en cuanto sé algo del bus.", answers: ["Te aviso en cuanto sepa algo del bus."], why: "Todavía no sabes nada: **en cuanto** + subjuntivo, **sepa**." },
          { sentence: "Antes de que salir, apaga la estufa.", answers: ["Antes de salir, apaga la estufa."], why: "Con infinitivo, **antes de** sin _que_." },
          { sentence: "Si llegue tarde, cenaré en la terminal.", answers: ["Si llego tarde, cenaré en la terminal."], why: "**Si** condicional + presente de **indicativo**." },
          { sentence: "Yo que tú, ahorraré un poco antes de viajar.", answers: ["Yo que tú, ahorraría un poco antes de viajar."], why: "Repaso: **yo que tú** + **condicional** (_ahorraría_)." },
          { sentence: "—¿Dónde está Diego? —A lo mejor esté todavía en el bus.", answers: ["—¿Dónde está Diego? —A lo mejor está todavía en el bus.", "¿Dónde está Diego? A lo mejor está todavía en el bus."], why: "Repaso: **a lo mejor** va con indicativo (_está_)." },
        ],
      },
      {
        id: "x2",
        type: "gap",
        title: "Elige el conector",
        prompt: "Completa con el conector del banco que tenga sentido. Úsalos todos.",
        bank: ["en cuanto", "hasta que", "antes de que", "mientras", "antes de", "cuando"],
        items: [
          { q: "Tengo que devolver el libro a la biblioteca ___ cierren por vacaciones.", answers: [["antes de que"]], why: "Sujetos distintos + subjuntivo (_cierren_): **antes de que**." },
          { q: "No voy a firmar el contrato ___ lo lea un abogado.", answers: [["hasta que"]], why: "Límite: no firmo hasta ese momento." },
          { q: "Llámame ___ aterrices; no voy a dormir tranquila sin saber nada.", answers: [["en cuanto"]], why: "Justo después de aterrizar: **en cuanto**." },
          { q: "___ estés en Puno, aprovecha para probar la trucha del lago.", answers: [["Mientras"]], why: "Durante tu estancia: **mientras** + subjuntivo." },
          { q: "Siempre reviso el pronóstico ___ salir con el kayak.", answers: [["antes de"]], why: "Mismo sujeto + infinitivo (_salir_): **antes de**." },
          { q: "___ sea mayor, quiero vivir en una casa frente al lago.", answers: [["Cuando"]], why: "Momento futuro general: **cuando** + subjuntivo." },
        ],
      },
      {
        id: "x3",
        type: "context",
        title: "¿Qué respondes?",
        prompt: "Elige la respuesta más natural en cada situación.",
        items: [
          { context: "Tu compañera te pregunta por mensaje: «¿A qué hora llegas a la reunión?». No lo sabes: depende de tu jefe.", q: "Respondes:", options: ["Cuando mi jefe me deje salir. Te aviso en cuanto salga.", "Cuando mi jefe me deja salir. Te aviso en cuanto salgo.", "Cuando mi jefe me dejará salir."], answer: 0, why: "Futuro: **cuando me deje**, **en cuanto salga**." },
          { context: "Son las ocho y tu amigo, que siempre es puntual, no ha llegado al restaurante.", q: "Dices:", options: ["Estará en un atasco. Cuando llegue, pedimos.", "Está en un atasco seguro. Cuando llega, pedimos.", "Estaría en un atasco. Cuando llegará, pedimos."], answer: 0, why: "Hipótesis sobre el presente: futuro de probabilidad (**estará**). Plan: **cuando llegue**." },
          { context: "Un amigo quiere dejar su trabajo mañana, aunque todavía no tiene otro.", q: "Le aconsejas:", options: ["Yo que tú, esperaría hasta que te ofrezcan algo por escrito.", "Yo que tú, espero hasta que te ofrecen algo.", "Yo que tú, esperaré hasta que te ofrecerán algo."], answer: 0, why: "Consejo: **yo que tú + condicional**; límite futuro: **hasta que + subjuntivo**." },
          { context: "Una turista te pregunta: «¿Qué hacen ustedes en la isla cuando llueve mucho?».", q: "Le explicas una costumbre:", options: ["Cuando llueve mucho, no salen los barcos y nos quedamos en casa tejiendo.", "Cuando llueva mucho, no saldrán los barcos.", "Cuando lloverá mucho, no salen los barcos."], answer: 0, why: "Pregunta por una costumbre: **cuando llueve**, indicativo." },
        ],
      },
      {
        id: "x4",
        type: "order",
        title: "Ordena el plan",
        prompt: "Toca las palabras en el orden correcto.",
        items: [
          { words: ["En", "cuanto", "tenga", "el", "título,", "buscaré", "trabajo", "de", "guía."], alt: ["Buscaré trabajo de guía en cuanto tenga el título."], why: "**En cuanto** + subjuntivo, coma, acción en futuro." },
          { words: ["No", "me", "voy", "hasta", "que", "me", "paguen", "lo", "que", "me", "deben."], why: "**Hasta que** + subjuntivo: _paguen_." },
          { words: ["Yo", "que", "tú,", "ahorraría", "antes", "de", "pedir", "un", "préstamo."], alt: ["Antes de pedir un préstamo, yo que tú, ahorraría."], why: "Consejo con condicional + **antes de** + infinitivo." },
        ],
      },
      {
        id: "x5",
        type: "open",
        title: "Escritura guiada: planes con condiciones",
        prompt: "Escribe de dos a cuatro frases para cada situación.",
        items: [
          {
            prompt: "Una amiga te escribe: «¿Cuándo vienes a visitarme a Puno?». Respóndele explicando de qué depende la fecha.",
            model: "¡Me encantaría! Pero hasta que no me confirmen las vacaciones, no puedo comprar el pasaje. En cuanto lo sepa, te escribo. Seguramente será en agosto, cuando termine el proyecto del trabajo.",
            checklist: ["Usas al menos dos conectores de tiempo + subjuntivo.", "Incluyes una hipótesis (_seguramente_, _será_, _a lo mejor_).", "No hay futuro después de _cuando_ ni de _en cuanto_."],
          },
          {
            prompt: "Escribe una meta que tienes a medio plazo y los dos pasos que tienen que pasar antes.",
            model: "A medio plazo, quiero hacer un voluntariado en Latinoamérica. Primero tengo que ahorrar: cuando tenga unos dos mil euros, empezaré a buscar organizaciones. Y antes de que me vaya, quiero aprobar el examen de B1.",
            checklist: ["Usas vocabulario de metas (_a medio plazo_, _ahorrar_, _meta_…).", "Encadenas al menos dos pasos con **cuando**, **en cuanto** o **antes de que**.", "Distingues **antes de** + infinitivo y **antes de que** + subjuntivo."],
          },
        ],
      },
    ],
  },
  writing: {
    task: "Responde a una invitación explicando cuándo podrás aceptarla y qué tiene que pasar antes.",
    context: "Yaneth, la autora del blog de Llachón, busca voluntarios para ayudar en su casa de turismo vivencial durante la temporada alta (de junio a agosto). Te escribe: «¿Te animas a venir? ¿Cuándo podrías llegar?». Contéstale con un correo.",
    steps: [
      "Agradece la invitación y reacciona con entusiasmo.",
      "Explica tu situación actual (trabajo, estudios, dinero).",
      "Encadena los pasos de tu plan con **cuando**, **en cuanto**, **hasta que** y **antes de que** + subjuntivo.",
      "Añade al menos una hipótesis (**a lo mejor**, **seguramente**, futuro de probabilidad).",
      "Pregunta algo práctico y despídete.",
    ],
    useLanguage: [
      "cuando / en cuanto + subjuntivo",
      "hasta que (no) + subjuntivo",
      "antes de que + subjuntivo / antes de + infinitivo",
      "a lo mejor / seguramente / futuro de probabilidad",
      "vocabulario de metas y plazos",
    ],
    model: [
      "¡Hola, Yaneth! Muchísimas gracias por la invitación. Me encantaría ir a Llachón: desde que leí tu blog, conocer el lago es una de mis metas para este año.",
      "Ahora mismo estoy terminando un curso de turismo, así que no puedo viajar hasta que haga el examen final, el 20 de junio. En cuanto termine, compraré el pasaje. Seguramente llegaré a Puno a principios de julio; a lo mejor un poco antes, si encuentro un vuelo barato a Juliaca.",
      "Antes de que me vaya, quiero practicar un poco de quechua para saludar a tu familia. Una pregunta: ¿necesito llevar saco de dormir o allá tienen mantas? Te aviso cuando tenga la fecha exacta.",
      "Un abrazo grande, Claire",
    ],
    checklist: [
      "Explicas de qué depende tu llegada, con al menos tres conectores de tiempo.",
      "Usas subjuntivo después de **cuando**, **en cuanto**, **hasta que** y **antes de que** para el futuro.",
      "No pones futuro después de **cuando**.",
      "Hay una hipótesis con **a lo mejor**, **seguramente** o futuro de probabilidad.",
      "El correo tiene saludo, pregunta práctica y despedida.",
    ],
    words: [110, 150],
  },
  speaking: {
    intro: "Esta semana hablas de lo que todavía no ha pasado. El reto: encadenar condiciones de tiempo sin pensar demasiado. Graba, escucha y comprueba que no se te escapa ningún _cuando llegaré_.",
    tasks: [
      {
        title: "Mi plan a medio plazo",
        prompt: "Habla durante un minuto y medio de una meta que tienes para los próximos dos o tres años. Explica qué pasos tienen que ocurrir antes, qué harás en cada momento, qué no sabes todavía y qué te han aconsejado.",
        prep: [
          "Meta: A medio plazo quiero…",
          "Paso 1: Primero tengo que… En cuanto…",
          "Paso 2: Cuando…, …",
          "Límite: No voy a… hasta que…",
          "Incertidumbre: A lo mejor… / Seguramente será…",
          "Consejo recibido: Mi amiga me dijo: «Yo que tú, …»",
        ],
        seconds: 90,
        model: "A medio plazo, quiero vivir un año en Latinoamérica, probablemente en Perú o en Bolivia. Primero tengo que ahorrar: ahora trabajo en una tienda y guardo un poco cada mes. En cuanto tenga suficiente dinero, pediré una excedencia en el trabajo. No voy a comprar el billete hasta que me la den por escrito, porque no quiero perder mi puesto. Cuando llegue, buscaré un trabajo de voluntaria, a lo mejor en un hostal o en una escuela. Seguramente será en dos años, más o menos. Mi hermana me dijo: «Yo que tú, haría primero un viaje corto para ver si te gusta la altura». Y creo que tiene razón.",
        selfCheck: [
          "Uso al menos tres conectores de tiempo con subjuntivo.",
          "Distingo **antes de** + infinitivo y **antes de que** + subjuntivo.",
          "Incluyo una hipótesis y un consejo con condicional.",
          "Hablo con enlaces naturales: _voy a ir_, _lo he hecho_.",
        ],
      },
      {
        title: "Deja un audio con instrucciones",
        prompt: "Un amigo llega mañana a tu ciudad y tú estarás trabajando. Grábale un mensaje de voz, como Rocío: qué tiene que hacer cuando baje del tren o del avión, dónde te espera, hasta cuándo, y qué haréis al día siguiente.",
        prep: ["Saludo: ¡Hola! Te dejo un audio con el plan.", "Llegada: Cuando llegues… / Ni bien bajes… / En cuanto…", "Espera: Te espero en… hasta que…", "Mañana: Antes de que…, …", "Cierre: Cualquier cosa, me escribes."],
        seconds: 60,
        model: "¡Hola, Diego! Te dejo un audio con el plan porque mañana trabajo todo el día. Cuando llegues al aeropuerto, toma el autobús amarillo; el taxi es carísimo. En cuanto bajes, escríbeme y te digo cómo llegar a casa. La llave está en la panadería de abajo: la señora te espera hasta que cierre, a las ocho. Y el sábado, antes de que se llene de gente, vamos al mercado a desayunar. ¡Cualquier cosa, me escribes!",
        selfCheck: ["El plan sigue un orden claro.", "Uso subjuntivo después de cada conector de tiempo futuro.", "Hablo como en un audio real: frases cortas y enlazadas."],
      },
      {
        title: "¿Por qué no ha llegado?",
        prompt: "Esperas a una amiga en la estación de Puno y ya lleva una hora de retraso. Haz tres hipótesis sobre lo que pasa y di qué harás cuando llegue o si no llega.",
        prep: ["Hipótesis: Estará… / Habrá un… / A lo mejor…", "Plan: Cuando llegue, … / Si no llega antes de las…, …"],
        seconds: 40,
        model: "Qué raro, ya es tardísimo. Estará en un bloqueo, como siempre en esta carretera. O a lo mejor se ha quedado dormida en el bus y ha pasado de largo. Tendrá el celular sin batería, porque no contesta. Bueno, cuando llegue, la llevo directamente a cenar. Y si no llega antes de las once, llamo a la empresa de buses.",
        selfCheck: ["Uso el futuro de probabilidad o _a lo mejor_ para las hipótesis.", "Diferencio **cuando llegue** (seguro que llegará) y **si no llega** (condición)."],
      },
    ],
  },
  useInClass: {
    intro: "En tu próxima clase en vivo vas a hablar de planes reales. Lleva una meta tuya preparada y úsala para practicar condiciones de tiempo con tu profesor.",
    cards: [
      { move: "Cuenta", task: "Explica tu meta a medio plazo en un minuto, con los pasos encadenados. Tu profesor solo puede interrumpir para preguntar «¿y cuándo pasará eso?».", phrases: ["A medio plazo quiero…", "En cuanto…, …", "Hasta que no…, no…", "Seguramente será…"] },
      { move: "Pregunta", task: "Entrevista a tu profesor sobre un plan suyo. Haz al menos cuatro preguntas con ¿cuándo? y reacciona a sus respuestas.", phrases: ["¿Cuándo vas a…?", "¿Y qué harás cuando…?", "¿Qué tiene que pasar antes de que…?", "¿Y si no sale bien?"] },
      { move: "Aconseja", task: "Tu profesor te cuenta un plan un poco arriesgado. Dale dos consejos con condicional y una condición de tiempo.", phrases: ["Yo que tú, esperaría hasta que…", "Yo en tu lugar, no … antes de que…", "Primero…, y cuando…"] },
      { move: "Negocia", task: "Organizad juntos una excursión de un día por el lago Titicaca con horarios. Cada uno tiene una condición diferente (uno llega tarde, otro se marea en barco).", phrases: ["Podemos salir en cuanto…", "Si te mareas, …", "Antes de que oscurezca, …", "Te esperamos hasta que…"] },
    ],
    bring: "Trae escrita una meta tuya con tres pasos y una fecha aproximada.",
  },
  quiz: {
    items: [
      { type: "choice", q: "«El año que viene, cuando ___ el máster, quiero trabajar en Bolivia.»", options: ["acabe", "acabo", "acabaré"], answer: 0, why: "Futuro: **cuando** + presente de subjuntivo, **acabe**." },
      { type: "choice", q: "«De niña, cuando ___ a casa de mi abuela en Juliaca, siempre comíamos queso con choclo.»", options: ["iba", "vaya", "iré"], answer: 0, why: "Costumbre del pasado: indicativo, imperfecto **iba**." },
      { type: "listen", q: "¿De qué depende el viaje de la persona?", audio: "Todavía no sé cuándo voy a ir. En cuanto me den las vacaciones, compro el pasaje.", voice: "es-PE-m", options: ["De que le den las vacaciones.", "Del precio del pasaje.", "Del tiempo en el lago."], answer: 0, why: "_En cuanto me den las vacaciones, compro el pasaje._" },
      { type: "gap", q: "No te vayas hasta que ___ (llegar) tu hermana; ella tiene las llaves.", answers: [["llegue"]], why: "Futuro y límite: **hasta que** + subjuntivo, **llegue** (con **u**)." },
      { type: "gap", q: "Ahorra un poco antes de ___ (viajar) y antes de que te ___ (subir) el alquiler.", answers: [["viajar"], ["suban"]], why: "Mismo sujeto: **antes de** + infinitivo. Sujeto distinto (ellos suben): **antes de que** + subjuntivo." },
      { type: "transform", source: "Voy a cobrar el sueldo. Inmediatamente después, te pago lo que te debo.", instruction: "Une con «en cuanto».", answers: ["En cuanto cobre el sueldo, te pago lo que te debo.", "Te pago lo que te debo en cuanto cobre el sueldo.", "En cuanto cobre el sueldo, te pagaré lo que te debo.", "Te pagaré lo que te debo en cuanto cobre el sueldo."], why: "**En cuanto** + subjuntivo: _cobre_." },
      { type: "transform", source: "Cuando tengo vacaciones, voy a la playa.", instruction: "Conviértelo en un plan para el próximo verano.", answers: ["Cuando tenga vacaciones, iré a la playa.", "Cuando tenga vacaciones, voy a ir a la playa.", "Cuando tenga vacaciones, voy a la playa."], why: "De costumbre a futuro: **cuando tenga** + futuro o _ir a_." },
      { type: "order", words: ["¿Qué", "harás", "cuando", "termines", "el", "proyecto?"], why: "Pregunta con _¿qué harás?_ (futuro) + **cuando** + subjuntivo." },
      { type: "error", sentence: "Te llamaré cuando sabré el resultado.", answers: ["Te llamaré cuando sepa el resultado."], why: "Nunca futuro después de **cuando**: **sepa**." },
      { type: "error", sentence: "Siempre desayuno antes de que salgo de casa.", answers: ["Siempre desayuno antes de salir de casa."], why: "Mismo sujeto: **antes de** + infinitivo. Y _antes de que_ nunca va con indicativo." },
      { type: "error", sentence: "Yo que tú, no firmaré nada hasta que lo lea un abogado.", answers: ["Yo que tú, no firmaría nada hasta que lo lea un abogado."], why: "**Yo que tú** + condicional: **firmaría**." },
      { type: "open", prompt: "Escribe tres frases sobre lo que harás el primer día de tu próximo viaje, con cuando, en cuanto y antes de que.", model: "Cuando llegue al hotel, me ducharé. En cuanto deje la maleta, saldré a buscar un mercado. Y antes de que se haga de noche, quiero ver el atardecer desde algún mirador.", checklist: ["tres conectores distintos", "subjuntivo después de cada conector", "futuro o ir a + infinitivo en la acción principal"] },
    ],
  },
  complete: {
    canNow: [
      "Distinguir **cuando llego** (costumbre), **cuando llegué** (pasado) y **cuando llegue** (futuro).",
      "Usar **en cuanto**, **hasta que**, **mientras**, **después de que** y **antes de que** + subjuntivo para el futuro.",
      "Elegir entre **antes de** + infinitivo (mismo sujeto) y **antes de que** + subjuntivo (sujetos distintos).",
      "Explicar una meta con plazos, pasos y obstáculos.",
      "Reconstruir un plan encadenado a partir de mensajes de voz.",
      "Entender y producir enlaces como **voy a ir**, **lo he hecho**, **va a haber**.",
    ],
    review: [
      "Nunca futuro después de **cuando**.",
      "**Antes de que** + subjuntivo, siempre.",
      "**Si** + indicativo; **cuando** (futuro) + subjuntivo.",
      "**Yo que tú** + condicional; **a lo mejor** + indicativo.",
    ],
  },
  related: [
    { path: "/antes-despues-cuando", label: "Antes, después, cuando · A2" },
    { path: "/sistema-verbal/presente-de-subjuntivo", label: "Sistema verbal: presente de subjuntivo" },
    { path: "/la-vida-despues-de-los-30", label: "La vida después de los 30 · B1" },
  ],
};
