import type { GrammarActivity } from './grammar';
export type GrammarTopicPage = {
  slug: string; path: string; title: string; description: string; h1: string;
  levels: string; introduction: string; lessonIds: number[]; levelSlugs: string[];
  prerequisites: string; activities: GrammarActivity[]; pitfalls: string[];
};
export const grammarTopicPages: GrammarTopicPage[] = [
  {
    slug: 'ser-estar', path: '/guides/how-to-teach-ser-vs-estar',
    title: 'Ser vs Estar Activities for Teachers | SPANISHCUE',
    description: 'Teach ser vs estar with three practical activities for adult beginners: room descriptions, live reports and meaning changes, plus teacher correction notes.',
    h1: 'Ser vs estar activities that make meaning visible', levels: 'A1–A2',
    introduction: 'Give learners a reason to identify, locate or describe a state. These short tasks work in one-to-one teaching or pairs; the first is supported A1, while adjective meaning changes are an A2 extension.',
    lessonIds: [48, 40, 41], levelSlugs: ['a1','a2'],
    prerequisites: 'Present forms of ser and estar, a small noun bank and basic adjective agreement. Add hay as a separate existence frame rather than another translation of “is”.',
    activities: [
      { name: 'Choose an office', minutes: 10, outcome: 'Describe two spaces and agree which one meets a need.', steps: ['Describe office A: small, near the station, with two desks. Describe B: quiet, farther away, with one large table.', 'The learner identifies each office, says where it is and explains what is in it.', 'Add a visitor who needs a chair. Ask for a revised recommendation.'], prompts: ['La oficina es pequeña. Está cerca de la estación.', 'Hay dos mesas. La silla está junto a la ventana.'], model: 'Prefiero la oficina A porque está cerca. Es pequeña, pero hay dos mesas.', correction: 'La oficina está pequeña → la oficina es pequeña for this ordinary description of size. Ask what meaning the learner intended instead of applying a permanent/temporary shortcut.', adaptation: 'A1: keep sentence frames visible. A2: remove labels and ask for an objection to the first choice.' },
      { name: 'Recommendation or live report?', minutes: 10, outcome: 'Separate a usual characteristic from a current state.', steps: ['Choose a café and give it a usual character: quiet, friendly or busy.', 'Change today’s situation: a celebration, a long queue or a closed room.', 'Have the learner leave two messages: a general recommendation and a report from today.'], prompts: ['Normalmente el café es tranquilo.', 'Hoy está lleno y la terraza está cerrada.'], model: 'Es un café tranquilo, pero hoy está lleno por una celebración.', correction: 'Both verbs can be meaningful with many adjectives. Ask for the context before correcting; “permanent versus temporary” does not explain every use.', adaptation: 'Pairs exchange roles as visitor and recommender. Online, use two columns titled usually and today.' },
      { name: 'The same adjective, a new message', minutes: 12, outcome: 'Interpret the change before producing a sentence.', steps: ['Show es listo / está listo and es aburrido / está aburrido.', 'Read a situation and ask which message fits: the colleague can start now; the film never holds attention.', 'The learner creates a context for the other sentence and explains the difference.'], prompts: ['La colega está lista para empezar.', 'La película es aburrida; el espectador está aburrido.'], model: 'Es listo describes someone as clever. Está listo means ready in this context.', correction: 'Do not mark every ser/estar swap as a conjugation error: it can produce a different valid meaning. Check the intended message.', adaptation: 'For A2 learners, introduce one pair at a time and let them describe the situation before naming the rule.' },
    ],
    pitfalls: ['Location of people and things usually uses estar; the location of an event uses ser: la reunión es en la sala dos.', 'Ser is not a synonym for permanent: es joven can describe something that changes.', 'Model the whole noun phrase so agreement is recycled alongside the verb choice.'],
  },
  {
    slug: 'past', path: '/guides/preterite-vs-imperfect-activities',
    title: 'Preterite vs Imperfect Activities for Teachers | SPANISHCUE',
    description: 'Use three Spanish past-tense activities to teach background, completed events and narrative perspective, with sample prompts, corrections and real lessons.',
    h1: 'Preterite vs imperfect activities with a story to tell', levels: 'A2–B1',
    introduction: 'Teach completed events and background with separate A2 support, then bring them together at B1. Each task asks the learner to communicate a perspective instead of guessing a tense from a keyword.',
    lessonIds: [142, 143, 18], levelSlugs: ['a2','b1'],
    prerequisites: 'Learners need a small set of familiar preterite and imperfect forms. If either tense is new, teach its own classroom lesson before the combined retelling.',
    activities: [
      { name: 'Build the scene, move the story', minutes: 12, outcome: 'Use background and bounded events for different narrative jobs.', steps: ['Give four facts: rain, a café, two friends talking, and a phone ringing.', 'The learner describes the scene before deciding what happened next.', 'Ask for a two-sentence story, then add a person arriving.'], prompts: ['Llovía y dos amigos hablaban en un café.', 'De repente sonó el teléfono.'], model: 'Mientras hablaban, sonó el teléfono y una amiga entró.', correction: 'The imperfect presents the scene from within; the preterite advances these events. Avoid “long versus short”: duration alone does not decide the tense.', adaptation: 'A2: offer conjugated choices. B1: let the learner choose the event and justify the perspective.' },
      { name: 'Two versions of the same arrival', minutes: 12, outcome: 'Explain how changing a tense changes the timeline.', steps: ['Compare: Cuando llegué, Ana preparaba la cena / Cuando llegué, Ana preparó la cena.', 'Ask the learner to draw each timeline and explain whether the preparation was already in progress.', 'Change the people and action; ask for another pair with two plausible meanings.'], prompts: ['¿Qué estaba en marcha cuando llegaste?', '¿Qué hecho cuenta la segunda versión?'], model: 'In the first version, the preparation was already in progress. The second presents preparation as a bounded event in the sequence.', correction: 'Do not call one version wrong without the intended story. Check whether the form expresses the timeline the learner chose.', adaptation: 'Use a shared sketch online. In pairs, one learner draws while the other explains.' },
      { name: 'Retell without tense labels', minutes: 15, outcome: 'Transfer the contrast into an uninterrupted narrative.', steps: ['Let the learner plan a visit: location, usual atmosphere and three events.', 'Listen once without interrupting, noting one useful tense decision and one unclear one.', 'Ask a genuine clarification question and have the learner retell only that part.'], prompts: ['¿Cómo era el lugar? ¿Qué pasó ese día?', '¿Era una costumbre o pasó una sola vez?'], model: 'El museo era pequeño. Normalmente había poca gente, pero ese día llegaron dos grupos.', correction: 'Ayer había mucha gente is valid: ayer does not force preterite. Correct the intended perspective, then the verb form.', adaptation: 'Offer a fictional visit if a learner prefers not to share personal experiences. The written follow-up can be a short message to a friend.' },
    ],
    pitfalls: ['A completed period can contain background descriptions in imperfect.', 'Regular habits and bounded repeated actions can be presented differently; ask what the speaker is doing.', 'The present perfect adds another perspective with regional variation; avoid forcing it into this first contrast.'],
  },
  {
    slug: 'subjunctive', path: '/guides/spanish-subjunctive-lesson-plan',
    title: 'Spanish Subjunctive Activities and Lesson Plan | SPANISHCUE',
    description: 'Plan communicative Spanish subjunctive activities for B1 and B2: workshop decisions, reactions and past requests, with sample prompts and teacher feedback.',
    h1: 'Spanish subjunctive activities built around a decision', levels: 'B1–B2, with C1 follow-up',
    introduction: 'Keep one communicative use in focus. Start with present wishes and recommendations at B1; move to earlier events or past requests only when the learner can explain the time relationship.',
    lessonIds: [148, 149, 150, 37], levelSlugs: ['b1','b2','c1'],
    prerequisites: 'Check familiar present forms and a clear distinction between the person expressing a wish and the person expected to act. Do not begin by testing a long trigger list.',
    activities: [
      { name: 'A workshop everyone can use', minutes: 12, outcome: 'B1: negotiate wishes and recommendations while also stating facts.', steps: ['Plan a practical workshop for four adults: two want more practice, two need clearer examples.', 'The learner states one fact and makes two recommendations.', 'Offer a conflicting recommendation and ask for a final agreed plan.'], prompts: ['El grupo tiene cuatro personas.', 'Recomiendo que trabajemos en parejas.'], model: 'Quiero practicar más. Quiero que todos tengan tiempo para hablar.', correction: 'Quiero que tengo → quiero tener when the subject stays the same. A change of subject supports quiero que tengas in this wish construction.', adaptation: 'The teacher represents the different priorities in a one-to-one class. Give each group member a priority card in a larger class.' },
      { name: 'What is confirmed?', minutes: 10, outcome: 'B1 extension: react to an earlier event while separating facts from uncertainty.', steps: ['Say a team has sent a project, but receipt is not yet confirmed.', 'Ask for one known fact, one reaction and one uncertain possibility.', 'Confirm receipt and ask which statements need updating.'], prompts: ['Sé que lo enviaron.', 'Me alegra que hayan terminado. Puede que no haya llegado.'], model: 'Ahora sabemos que ha llegado. Me alegra que lo hayan recibido.', correction: 'Subjunctive is not simply “unreal”: the reaction can concern a known fact. Distinguish the framing expression from the truth of the event.', adaptation: 'Use familiar participles first. If perfect subjunctive is new, return to present reactions before adding anteriority.' },
      { name: 'A request from last week', minutes: 12, outcome: 'B2: preserve a past request and negotiate the next step.', steps: ['Give a past meeting where someone asked for more practical work.', 'Ask the learner to report the request using a past main verb.', 'Move to a new meeting and ask what the learner would now like to change.'], prompts: ['Pedí que incluyeran una actividad práctica.', 'Me gustaría que dedicáramos más tiempo a conversar.'], model: 'Quería que explicaran el ejemplo antes de empezar.', correction: 'Check whether the subordinate event is present, past or future relative to the original request. Concordance is a relationship, not a command to put every verb in the same tense.', adaptation: 'At C1, change the reporting perspective and discuss whether an alternative tense remains possible in context.' },
    ],
    pitfalls: ['Do not teach subjunctive after every que.', 'Keep person changes and time relations visible before correcting endings.', 'A first B1 class can stay with one use; the three activities form a progression, not a requirement to teach every form in one hour.'],
  },
  {
    slug: 'por-para', path: '/spanish-grammar-lessons/por-vs-para-activities',
    title: 'Por vs Para Activities for Spanish Teachers | SPANISHCUE',
    description: 'Teach por vs para through a delivery problem, a purposeful exchange and a message repair task. B1 teacher instructions, sample answers and a real lesson.',
    h1: 'Por vs para activities with a plan to make', levels: 'B1',
    introduction: 'A shared delivery gives por and para different jobs: explain a cause, plan a route, identify a recipient and state a purpose or deadline. Ask what the speaker means before deciding which preposition fits.',
    lessonIds: [231, 212], levelSlugs: ['b1'],
    prerequisites: 'Familiar present and past verbs, basic destination language and infinitives for purpose. Lesson 212 is A1 prerequisite support; the complete por/para classroom is B1.',
    activities: [
      { name: 'Replan a delivery', minutes: 12, outcome: 'Distinguish why a plan changed from what the new plan is intended to achieve.', steps: ['A parcel must reach a colleague by Friday. The usual street is closed.', 'The learner explains the cause of the change and suggests a route with one stop.', 'Ask for a final message including the recipient, deadline and purpose.'], prompts: ['Cambiamos la ruta por las obras.', 'Pasamos por la imprenta para recoger el cartel.'], model: 'El cartel es para Julia. Lo necesitamos para el viernes.', correction: 'Por las obras gives the cause; para evitar las obras gives the intended purpose. Ask the learner to express both without changing the situation.', adaptation: 'Use a three-street map on paper or a shared screen. Pairs can receive different opening times.' },
      { name: 'A recipient or someone you represent?', minutes: 10, outcome: 'Explain two possible messages instead of guessing from an English translation.', steps: ['Present: Compré el regalo para Ana / Compré el regalo por Ana.', 'Assign a context: Ana receives the gift, or Ana could not go and you bought it on her behalf.', 'Ask for a follow-up sentence that makes the intended reading unambiguous.'], prompts: ['El regalo es para Ana; es su cumpleaños.', 'Fui por Ana porque ella no podía ir.'], model: 'Lo compré para Ana: ella va a recibirlo.', correction: 'Por Ana can support different readings, including cause or acting on her behalf. A bare sentence may not settle it; require a context rather than one universal answer.', adaptation: 'Use invented people. At a lower level, keep only recipient versus purpose before introducing an ambiguous pair.' },
      { name: 'Repair the message so someone can act', minutes: 12, outcome: 'Produce a usable message with cause, purpose, route, recipient and deadline.', steps: ['Give a vague message: «Cambio de plan. Lleva la caja. Es urgente».', 'The learner asks you for five missing details.', 'They rewrite the message; you follow it literally and check whether any important detail is still missing.'], prompts: ['¿Por qué cambió el plan? ¿Para quién es la caja?', '¿Por dónde paso? ¿Para cuándo la necesitan?'], model: 'Por la avería, pasamos por otra calle para llegar a tiempo. La caja es para Luis y debe llegar para las cinco.', correction: 'Do not reward the number of prepositions alone. Check whether a person could actually follow the message and whether each choice expresses the intended relation.', adaptation: 'Use a short voice-style report first, then a written message. Groups exchange messages and identify missing information.' },
    ],
    pitfalls: ['Both prepositions can appear in valid sentences whose meanings differ.', 'Avoid translating every English “for” with the same preposition.', 'This task covers frequent contextual uses, not every idiom or regional use.'],
  },
];
export const grammarTopicByPath = new Map(grammarTopicPages.map(topic => [topic.path, topic]));
